### ISSUE TITLE
[Bug]: can apply data is broken

### ISSUE THREAD

**Issue by Gh0sSte** [Yimura/YimMenu#1004]
### Describe the bug

can apply data is broken meaning invalid objects are not blocked. Because of this even the simplest and oldest crashes like slod ped crash work. I have tried to fix it myself but to no avail. I saw another issue where the exception handler was put into an infinite loop by one of these crashes. So by fixing this it would fix that issue too.

### Steps To Reproduce

1. get crashed with slod crash

### Expected Behavior

dont crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by binded-zz** [comment]
i was told by some one that just spawning and then driving to a prop is enough to crash the menu 
and that its a fault of the menu and not something that is going to get fixxed any time soon 
think he ment  like the base or something idk 

i use tupoye's fork i like the menus better and it seems to block the slod i swear i seen a noticed at least onces saying it protected from it shit i could be wrong 

think he said he had stand ultimate or something but he was inpressed with the rest of the protections

**Comment by Yimura** [comment]
YimMenu is 100% protected against Stand.

Though I don't know what edition of Stand it was as people aren't too keen on answering once they failed to crash you.

**Comment by binded-zz** [comment]
he said ultimate we didnt try the crashes he was sure they would work lol

ill ask when i see him online again to try them :)

**Comment by Gh0sSte** [comment]
> YimMenu is 100% protected against Stand.
> 
> Though I don't know what edition of Stand it was as people aren't too keen on answering once they failed to crash you.

it does when can apply data is working. But when its not burger king foot lettuce and steamroller do work sadly. Well steamroller works sometimes.

**Comment by yasmasdas** [comment]
Steamroller cannot work against yimmenu
