### ISSUE TITLE
[Bug]: Stuck in spectator

### ISSUE THREAD

**Issue by VolkerSchlegel** [Yimura/YimMenu#1008]
### Describe the bug

Even when the checkbox was turned off I'd still be invisible and if I tped I'd take the guy I was spectating with me.

### Steps To Reproduce

1. Spectate someone
2. Click remote control vehicle while still spectating

### Expected Behavior

I shouldn't be stuck spectating

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Kaki7964** [comment]
Actually I was using the version from before the can_apply_data pr got merged. Shouldn't matter though

**Comment by Yimura** [comment]
Won't fix, just don't use the two features together.

It's going to be too much work to add a check for each and every feature that's not compatible with each other.
I'm sure that clicking the suicide button in the Self tab correctly resets your game to be usable again.
