### ISSUE TITLE
[Bug]: Visible Locally option for Invisibility don't work anymore

### ISSUE THREAD

**Issue by lewai1** [Yimura/YimMenu#1009]
### Describe the bug

When "Invisible" and "Visible Locally' options are checked, I'm still invisible locally.

### Steps To Reproduce

1. Check Invisible option
2. Check Visible Locally option

### Expected Behavior

Normally I should see my character locally.

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/39082832/219955478-a79e6bd2-eddf-400f-b060-8d6f2e4b2fc1.png)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
Can confirm. This is a side effect of a countermeasure against a certain P2C and will be fixed soon
