### ISSUE TITLE
How Do I Change the GUI Title!

### ISSUE THREAD

**Issue by lordmulti-tools** [Yimura/YimMenu#101]
**Is your feature request related to a problem? Please describe.**
Please someone tell me how to change the menu title? The default is YimMenu. Thanks [...]

**Describe the solution you'd like**

**Provide Reasoning**
Tell us why you'd want for us to add this to YimMenu.

**Additional context**

**Comment by xM4ddy** [comment]
[The main title is here] 
(https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/views/view_navigation.cpp#L12-L16) though I'd just use Ctrl F if I was you to find other/all instances.

**Comment by Yimura** [comment]
Ye as @xM4ddy mentioned, CTRL+F is a feature in most IDE nowadays.
