### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zc311** [Yimura/YimMenu#1010]
### Describe the bug

Start a robbery mission (I am the host) invite friends, friends cannot enter the party, will be stuck in one interface and cannot enter

### Steps To Reproduce

All protections are turned off
Start a heist mission
Invite friends from the same round to join the mission

### Expected Behavior

Friends enter the mission

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by BeztNA** [comment]
Same
