### ISSUE TITLE
[Bug]: Vehicle GodMode

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1013]
### Describe the bug

I'm not sure if this is patched by R* or if it's a bug.. But the Vehicles doesn't remain GodModed once we step out of them as it used to earlier..

### Steps To Reproduce

1. Spawn a Vehicle
2. Enter it with Vehicle Godmode check and All the proofs Checked as well
3. Step out of vehicle
4. Try Explode it

### Expected Behavior

The Vehicle remains GodModed Even after stepping out of it.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
We intentionally disabled godmode once you leave a vehicle to prevent your whole world filling up with god mode vehicles.

**Comment by CypherMorgan** [comment]
Ah, Alright :)
