### ISSUE TITLE
[Bug]: My friends cant join my heist if i inject yim menu

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#1015]
### Describe the bug

My friends cant join my heist if i inject yim menu, they can join if i unload and create heast again

### Steps To Reproduce

1. inject yim menu
2. create a heist

### Expected Behavior

1

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by oxUNKNOWNxo** [comment]
I'm probably having the same problem.
・Cayo Perico Heist
・Casino Heist Finale
Starting these by inviting "friends in the same session" will stack your friends.

Inviting a friend who is in another session will start normally.

I turned off all the following items, but no change.
・Spoof
・Protections

Also, the stack will be released when the host finishes the job or after a certain period of time.

**Comment by epicmusicpt** [comment]
yeah i have confirmed the issue,i can only invite friends or other players if they´re in a different session

**Comment by epicmusicpt** [comment]
this still happens,i just checked in casino heist.

**Comment by epicmusicpt** [comment]
lately ive been able to play the heist with no issues.

**Comment by Yimura** [comment]
We're looking into the issue and it's still present as reported, joining the heist from outside of the session makes it start but then freezes when setting up the transition.

**Comment by Peax** [comment]
I'm experiencing this issue currently on any [The Last Dose](https://www.rockstargames.com/newswire/article/5125891458o3a5/los-santos-drug-wars-the-last-dose-out-now) mission and YimMenu a524009. My friend and I are both in the same session and I'm hosting the job. Until I unload YimMenu, my friend can't join and only sees a blurred screen. After a while he gets kicked back to free roam.

All the usual suspects like protections, force script host and spoofing are disabled. I also disabled all scripts under Debug menu to no avail.

Seems related to #1011 but I have no clue what byte patches I could try commenting out. Even with additional debug logs enabled there is no obvious hint.

**Comment by Yimura** [comment]
Resolved with #1598
