### ISSUE TITLE
F.A.R.T. Interface

### ISSUE THREAD

**Issue by LiamD-Flop** [Yimura/YimMenu#102]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a random kid walks up to me and explodes me. Then when I want to explode him using the menu, it takes a while to open the right player menu and go to the explode option.

**Describe the solution you'd like**
What we could do is add Fast Acquiring Rendered Target, or F.A.R.T. for short. What F.A.R.T. would do is it would add a context menu (Like the one in gmod, see below for example) This way we can quickly do some stuff on the entity. Without having to open our menu.

**Provide Reasoning**
Because it makes the menu easier to use. It also has controller support, this way you can use some of the menu's features while using a controller.

**Additional context**
![image](https://user-images.githubusercontent.com/40887493/157445041-767053d1-a839-4be2-a798-e0abce4acf4d.png)

**Comment by Tayipc38** [comment]
Preferably this feature will be highly customizable, maybe even through the menu itself.
