### ISSUE TITLE
[Request]: Infinite Ammo For Vehicles

### ISSUE THREAD

**Issue by EbneSinam** [Yimura/YimMenu#1021]
### Problem

Hi, Please Add Infinite Ammo For Vehicles.
For example, the Oppressor Mk II is limited to 20 Missiles and will not fire after 20 Missiles.
Or Vigilante is Limited to 30 Missiles and will not fire after 30 Missiles.

### Solution

.

### Reason

Infinite ammo does not work in the weapon section for vehicles.

**Comment by TheGreenBandit** [comment]
Seems easy, will check out adding it to my pr

**Comment by TheGreenBandit** [comment]
g_local_player->m_weapon_manager->m_vehicle_weapon_info->m_ammo_info->m_ammo_flags = eAmmoFlags::InfiniteAmmo || maxammo? Go off infinite ammo for normal ped

**Comment by Kenneth44z** [comment]
You could do this the native way by doing like this: 

```
std::array<uint32_t, 12> weaponHashes = { 0x7CBE304C, 0x44A56189, 0xA247D03E, 0xB4F96934, 0x753A78F1,
                                          0x8BB7C63E, 0x6C88E47D, 0xBCE908DB, 0x504DA665, 0x1EF01D8A,
                                          0x9E5840A2, 0x3C83C410 };

    for (auto hash : weaponHashes) {
        VEHICLE::SET_VEHICLE_WEAPON_RESTRICTED_AMMO(YourVehicle, hash, -1); 
    } // Setting to -1 will disable the used missiles count

```
(Im sure there are other ways but this works as intended)

**Comment by TheGreenBandit** [comment]
> You could do this the native way by doing like this: 
> 
> 
> 
> ```
> 
> std::array<uint32_t, 12> weaponHashes = { 0x7CBE304C, 0x44A56189, 0xA247D03E, 0xB4F96934, 0x753A78F1,
> 
>                                           0x8BB7C63E, 0x6C88E47D, 0xBCE908DB, 0x504DA665, 0x1EF01D8A,
> 
>                                           0x9E5840A2, 0x3C83C410 };
> 
> 
> 
>     for (auto hash : weaponHashes) {
> 
>         VEHICLE::SET_VEHICLE_WEAPON_RESTRICTED_AMMO(YourVehicle, hash, -1); 
> 
>     } // Setting to -1 will disable the used missiles count
> 
> 
> 
> ```
> 
> (Im sure there are other ways but this works as intended)

That is a very better way than i was going to make it, push your own pr if you want to push that

**Comment by EbneSinam** [comment]
> That is a very better way than i was going to make it, push your own pr if you want to push that

Please add, thank you

**Comment by EbneSinam** [comment]
Please add this feature. Thankful

@TheGreenBandit @Kenneth44z

**Comment by dynamoNg** [comment]
hi waiting for this feature thanks. 

Kiddion also has option -> Freeze Vehicle Ammo
