### ISSUE TITLE
[Bug]: Log Issues

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#1024]
### Describe the bug

1. Log Time is 1hour behind ex.: real time => [04:xx:xx.xxxxx] log time => [03:xx:xx.xxxxx]
2. After getting crashed by ex. a modder the logs spams exceptions

### Steps To Reproduce

- load the menu

### Expected Behavior

- none

### Screenshots and/or Logs

- none

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
The log time being behind is not an issue I care to fix and the exception logging that keeps going is not something that can be fixed because the means the game is repeatedly crashing and YimMenu trying to recover it.
