### ISSUE TITLE
[Bug]: God Mod startup failed

### ISSUE THREAD

**Issue by 1642054178** [Yimura/YimMenu#1027]
### Describe the bug

The vehicle will be injured and explode.

### Steps To Reproduce

https://user-images.githubusercontent.com/108277687/221393706-adc134fa-50cb-4194-a1e6-c02c3ceb37c7.mp4

### Expected Behavior

Same as before ：）

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by CypherMorgan** [comment]
@Yimura said that they have intentionally disabled godmode once you leave a vehicle to prevent your whole world filling up with god mode vehicles in #1013  :)

**Comment by 1642054178** [comment]
However, players may prefer to have an indestructible vehicle at any time. Of course, this is just my personal view  ：）

**Comment by Yimura** [comment]
Closing as the god mode behaviour is working as intended.
