### ISSUE TITLE
Menyoo's xml loader

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#103]
**Is your feature request related to a problem? Please describe.**
When I feel bored, I want to buttfuck the session and spawn a bunch of vehicles that have been made using Mafins Menyoo mod. Most of all, I want to be able to download xml files from all around the internet and use them online.

**Describe the solution you'd like**
I will personally be implementing this feature

**Provide Reasoning**
Cuz it looks nice

**Additional context**
![image](https://user-images.githubusercontent.com/79384354/157504069-fc995064-0181-45b1-ae43-6ad3babe09df.png)

**Comment by Loko415** [comment]
Based sigma male. Teach me you're ways. Bean car epic

**Comment by Yimura** [comment]
@Loko415 refrain from posting off-topic comments.

**Comment by Tayipc38** [comment]
Implemented.
