### ISSUE TITLE
[Bug]: New GTA Update 2845

### ISSUE THREAD

**Issue by Primexz** [Yimura/YimMenu#1031]
### Describe the bug

Rockstar has released a new GTA update 2845. Apparently, the sending of messages has changed a bit.
The pointers for this are oudated.

### Steps To Reproduce

/

### Expected Behavior

/

### Screenshots and/or Logs

```
Failed to find 'RBB'.
Failed to find 'SCM'.
Failed to find 'SCP'.
Failed to find 'HJR'.
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Seanghost117** [comment]
Seems to be an update in regards to anti-spamming the chat. This may also effect the profanity filter bypass. Stay tuned for more info.

**Comment by Primexz** [comment]
> Seems to be an update in regards to anti-spamming the chat. This may also effect the profanity filter bypass. Stay tuned for more info.

R* ID join seems to be RIP too. We will see :=)

Edit: Without the pointers for chat & the hook for the RID Joiner, YimMenu still seems to work completely.
Globals and Networks Events seem to remain the same.

Edit 2:
Rockstar has reduced the limit of sessions that can be accessed through their API again -> for session brower. From 1057 to 1054 (no idea..)

**Comment by ouka1998** [comment]
when does yim menu update guys

**Comment by Primexz** [comment]
> when does yim menu update guys

just wait..
