### ISSUE TITLE
[Request]: Riot Mode

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#1037]
### Problem

Can u add riot mode ?

### Solution

riot mode

### Reason

fun

**Comment by Ninja271** [comment]
What is riot mode?

**Comment by TheGreenBandit** [comment]
> What is riot mode?

I'm guessing he's referring to the native MISC::SET_RIOT_MODE_ENABLED

**Comment by Sys0xdbg** [comment]
no i know what he saying. its gonna be fun. like gta 4

**Comment by TheGreenBandit** [comment]
> no i know what he saying. its gonna be fun. like gta 4

Oh wait he is just saying to give the peds a task where they just start attacking? Shouldnt be hard to make

**Comment by BeztNA** [comment]
i saw in a video on youtube about mod menu has a riot mode, riot mode make npc kill each orthers, very funny. Sr for my bad english

**Comment by BeztNA** [comment]
the city was in bloody chaos

**Comment by TheGreenBandit** [comment]
Ill look at doing this later, should be easy

**Comment by BeztNA** [comment]
> Ill look at doing this later

thank you, hope to see it soon

**Comment by TheGreenBandit** [comment]
solving here -> https://github.com/TheGreenBandit/YimMenu/tree/pedcombat, todo: set check for every 1-5 seconds allowing peds to attack enemys,
