### ISSUE TITLE
[Bug]: Invalid player model (appearance node) crash alert from all players when spoofing player model

### ISSUE THREAD

**Issue by Svxy** [Yimura/YimMenu#1040]
### Describe the bug

<h3>I don't know if this is a common issue, not to mention I'm drunk and high on a Thursday night.. But when I attempt to "Spoof Player Model" (with nothing in the input field), I get spammed with the same alert, but from every player;</h3>

<br>

```
[WARN/notify.hpp:25] Blocked invalid player model (creation node) crash from (player) (player_rid)
```

<br>

<h3>I'm not sure if using my own injector would've been the cause of this issue or not, as it just uses the CreateRemoteThread function, but that's in my repos for testing purposes if needed.</h3>

<br>

<p align=center><a href='https://cdn.discordapp.com/attachments/952874996366213120/1081027352701718548/2023-03-02_19-56-33.mkv'>A video demonstration of the issue</a></p>

### Steps To Reproduce

> - inject the menu (maybe with my injector as that could be the issue)
> - go to spoofing
> - Spoof Player Model with NO input

### Expected Behavior

Spoofing of the players model....

### Screenshots and/or Logs

    >_

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by 1642054178** [comment]
I have the same problem

**Comment by 1642054178** [comment]
![image](https://user-images.githubusercontent.com/108277687/222900806-53f27ce9-88b5-4611-b9b2-800b96c5148c.png)

**Comment by maybegreat48** [comment]
You should enter a valid model in the model spoofer input for it to work properly. Probably a good idea adding a check though
