### ISSUE TITLE
[Request]: Add "Particle FX", self option.

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1041]
### Problem

Hello, it would be great to have the "Particle FX" self option, and if the devs feel to, add it on online players as well.

### Solution

.

### Reason

.

**Comment by Seanghost117** [comment]
There is currently already bone pftx in self options, I think you can also adjust which bones as well, this could be added to online options. I'll consider it in a future PR if it doesn't get picked up

**Comment by BUZZARDGTA** [comment]
oh yeah it already exists, I didn't see it before, thanks.

**Comment by BUZZARDGTA** [comment]
just checked, there are only a very limited number of Particle FX there. Would be great to add way more.

**Comment by ghost** [comment]
> just checked, there are only a very limited number of Particle FX there. Would be great to add way more.

Ngl particle fx is pretty sad. There's only a few good dictionaries.. probably the best you're gonna get
