### ISSUE TITLE
[Request]: Steering Wheel Support

### ISSUE THREAD

**Issue by OGCRACKUSER** [Yimura/YimMenu#1046]
### Problem

it would be cool to see the support of the game steering wheel because there is no such thing in any menu, but I want to play with the steering wheel

### Solution

-

### Reason

some people want to play with the game wheel and the evil rockstar do not allow it

**Comment by JDMJay** [comment]
you can actually play with a steering wheel just make sure it’s compatible

**Comment by Yimura** [comment]
Repository of an ASI mod with full wheel support and manual shifting.

https://github.com/E66666666/GTAVManualTransmission

**Comment by Yimura** [comment]
Won't be implemented in YimMenu as it's fairly complex and there are already mods out there doing this exact thing.
