### ISSUE TITLE
[Bug]: Texts in TAB menu

### ISSUE THREAD

**Issue by EbneSinam** [Yimura/YimMenu#1047]
### Describe the bug

The texts are not displayed in the correct tab.
All texts have problem in tab.

YimMenu v2d44f14

### Steps To Reproduce

Open YimMenu and see first TAB

### Expected Behavior

GUI_TAB_SELF => SELF
and More

### Screenshots and/or Logs

![GTA5 2023-03-05 17-27-01-740](https://user-images.githubusercontent.com/125854733/222979467-dace8688-eb38-4409-91e6-f2225ba845a5.png)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Remove the `%appdata%/BigBaseV2/translations/` directory and load YimMenu again, that should fix the issue.

**Comment by EbneSinam** [comment]
> Remove the `%appdata%/BigBaseV2/translations/` directory and load YimMenu again, that should fix the issue.

Fixed, Thank you
