### ISSUE TITLE
[Bug]: Game freezes in While loop on Sync Node processing.

### ISSUE THREAD

**Issue by Tetragromaton** [Yimura/YimMenu#1051]
### Describe the bug

While playing with last Nightly build [Nightly [2d44f14]](https://github.com/YimMenu/YimMenu/releases/tag/nightly)
I've faced an random game freeze loop, only game restart helps. 

How I'd figured it out. 
When game freezes you could attach your debugger to game process and it would show you code place where freeze occurs, in my case it pointed me to code (YimMenu was recompiled to RelWithDebInfo to see exact code place where loop never stops.)
`bool check_node(rage::netSyncNodeBase* node, CNetGamePlayer* sender, rage::netObject* object)`  in https://github.com/YimMenu/YimMenu/blob/master/src/hooks/protections/can_apply_data.cpp string: 506

Also check strings: 506 & 512 (Self re-call process again, shouldn't be).

As you can see here function may easily struck in itself that would lead to this issue in case of bad node appears in memory. 
Probably solution for that is to ensure that next pointer read wouldn't lead to initial RCX buffer that was passed initially for checks or make some actions ( null node or something) if check returned true at line 513, I can see here are nothing done to node so it would ofc will call itself again and again 🤷

Maybe I'm dumb but that's not supposed to happen. 

### Steps To Reproduce

1.Issue occurs randomly while >10 players in session.
2.All default protections should be turned on. (clean config)

### Expected Behavior

I think game shouldn't get stuck in execution loop on processing single node ?

### Screenshots and/or Logs

- No exception occurs while this happens. Only debugger helped to figure out where this loop occured that lead to game freeze.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by grasscrash4384** [comment]
🚑

**Comment by Yimura** [comment]
Related to #1073
