### ISSUE TITLE
[Request]: RID Join bypass session

### ISSUE THREAD

**Issue by Jig895** [Yimura/YimMenu#1052]
### Problem

There's no problem

### Solution

Being able to join players in solo/private or friends only session

### Reason

I want this in the YimMenu because it's good feature and I don't want to coload with another menu just for this.

**Comment by Yimura** [comment]
This should've been patched, which menu supposedly has this feature for the current version of GTA?
Mind you that YimMenu used to have this feature but it no longer works.

**Comment by Jig895** [comment]
I was using this feature with the north menu but my subscription ended so I can't tell if it's still work, probably not as you said it's patched, sorry for this useless post, and I didn't know that was possible to do this with the YimMenu

**Comment by gir489returns** [comment]
There's still a way to do this, but you have to manually poll the GTA V sessions by hand with the SCAPI and manually find the session that contains the SCID you're looking for. I'm not posting the code we used to do to do it since it was given to Limabean by someone else, and I ain't no fink.

**Comment by maybegreat48** [comment]
The query session info endpoint still works, but the remote player blocks uninvited peers now. This can only be bypassed using a SCAdmin presence event AFAIK

**Comment by shoaib842** [comment]
> This should've been patched, which menu supposedly has this feature for the current version of GTA? Mind you that YimMenu used to have this feature but it no longer works.

I use a free mod , named - Lightning X, there it's a feature of rid joining and it works. But it randomly at any point lags the game.

**Comment by Yimura** [comment]
> I use a free mod , named - Lightning X, there it's a feature of rid joining and it works. But it randomly at any point lags the game.

Do keep in mind that this issue is talking about joining people in invite only/solo lobbies.
YimMenu is still able to join people in public lobbies.
