### ISSUE TITLE
[Bug]: Breakup & Lost Connection kick not working

### ISSUE THREAD

**Issue by yzzuf** [Yimura/YimMenu#1054]
### Describe the bug

Literally does not kick other players or remove them from the session

### Steps To Reproduce

1. Go to option
2. Try to kick

### Expected Behavior

Kick or remove player from session

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Lost connection kick will be removed in #1053, breakup should still be working though.
