### ISSUE TITLE
[Bug]: infinite ped attachment crash message appears to be a false positive

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1056]
### Describe the bug

While playing online in quickjoin missions this message pops up a lot. Other players do not appear to be there to crash and are just playing the game. So the message appears to be a false positive. 

### Steps To Reproduce

Quickjoin through in-game phone and play mission. Message appears to happen more often the closer you are to other players. 

### Expected Behavior

Warning message only when specific attack is actually happening. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

Reported in unknowncheats thread as well. Another user also said they had the same issue. 
See here: https://www.unknowncheats.me/forum/3695629-post887.html
And here: https://www.unknowncheats.me/forum/3695671-post888.html
Added here per Yimmura's request. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
These false positive messages have been commented out in the source code to prevent confusion.

The protections are still there.
