### ISSUE TITLE
[Request]: Add siren/police light or field to add specified hex object on vehicle

### ISSUE THREAD

**Issue by brianr1511** [Yimura/YimMenu#1059]
### Solution

It would be awesome if the mod menu included siren/light emergency modding. Driving a civilian vehicle with a siren/light on could be really amazing. Or a specified object by hex, like a flag, a sticker, a ladder,...

### Reason

The reason above

**Comment by TheGreenBandit** [comment]
You could use the custom vehicle spawner to get the result you want

**Comment by epicmusicpt** [comment]
> You could use the custom vehicle spawner to get the result you want

is that "custom vehicle spwaner" feature on YimMenu?

**Comment by TheGreenBandit** [comment]
> > You could use the custom vehicle spawner to get the result you want
> 
> 
> 
> is that "custom vehicle spwaner" feature on YimMenu?

Yes, just find a json file to load got to appdata->bigbase->vehicles or whatever its called and paste the json into there

**Comment by epicmusicpt** [comment]
> > > You could use the custom vehicle spawner to get the result you want
> > 
> > 
> > is that "custom vehicle spwaner" feature on YimMenu?
> 
> Yes, just find a json file to load got to appdata->bigbase->vehicles or whatever its called and paste the json into there

but you still have to find the json file,so its not possible to create the siren or emergency lights on any spawned vehicle with YimMenu. you must find the file witch is created by someone else.

**Comment by Zuwy101** [comment]
Yes please do this devs, would be really cool. or teach us how.

**Comment by muhittinceko** [comment]
> ### Sorun
> _Cevap yok_
> 
> ### Çözüm
> Mod menüsünde siren/ışık acil durum modlaması yer alsaydı harika olurdu. Siren/ışık açıkken sivil bir aracı sürmek gerçekten harika olabilir. Veya bir bayrak, bir çıkartma, bir merdiven gibi onaltılık olarak belirlenmiş bir nesne...
> 
> ### Sebep
> Yukarıdaki sebep
> 
> ### ek bağlam
> _Cevap yok_
yes i agree with you mate i support you they should add this or tell you how it's done

**Comment by muhittinceko** [comment]
> ### Problem
> _No response_
> 
> ### Solution
> It would be awesome if the mod menu included siren/light emergency modding. Driving a civilian vehicle with a siren/light on could be really amazing. Or a specified object by hex, like a flag, a sticker, a ladder,...
> 
> ### Reason
> The reason above
> 
> ### Additional context
> _No response_

yes i agree with you mate i support you they should add this or tell you how it's done

**Comment by TheGreenBandit** [comment]
There is no way this can be added in the menu as there is no way to get the height of the vehicle, if you really wanna make custom cars use menyoo's spooner and then load yimmenu. Make the car or cars you want using menyoo then save them with yimmenu so that it becomes a json file. Then close game, remove menyoo. Start game inject yimmenu, load online if u wanna go online and spawn the cars u made as u wish

**Comment by Zuwy101** [comment]
> 

On menyoo can you put siren on vehicle? how?

**Comment by epicmusicpt** [comment]
> There is no way this can be added in the menu as there is no way to get the height of the vehicle, if you really wanna make custom cars use menyoo's spooner and then load yimmenu. Make the car or cars you want using menyoo then save them with yimmenu so that it becomes a json file. Then close game, remove menyoo. Start game inject yimmenu, load online if u wanna go online and spawn the cars u made as u wish

thanks for the info,i tryed i spawed a few funny vehicles with menyoo ,but when i tryed to inject YimMenu it crashed. so i tried again and saved the cars with kiddion´s modest menu,but it loses the features when spawned online. i went to try again and got a message warning about modified files in GTAV directory,so i aint touching that menyoo or scripthook again! dont wanna risk a ban.

**Comment by muhittinceko** [comment]
> > There is no way this can be added in the menu as there is no way to get the height of the vehicle, if you really wanna make custom cars use menyoo's spooner and then load yimmenu. Make the car or cars you want using menyoo then save them with yimmenu so that it becomes a json file. Then close game, remove menyoo. Start game inject yimmenu, load online if u wanna go online and spawn the cars u made as u wish
> 
> thanks for the info,i tryed i spawed a few funny vehicles with menyoo ,but when i tryed to inject YimMenu it crashed. so i tried again and saved the cars with kiddion´s modest menu,but it loses the features when spawned online. i went to try again and got a message warning about modified files in GTAV directory,so i aint touching that menyoo or scripthook again! dont wanna risk a ban.
im getting the same error yim and menyoo crashes they don't work together so i can't save cars so sorry i am waiting for your help please

**Comment by muhittinceko** [comment]
> There is no way this can be added in the menu as there is no way to get the height of the vehicle, if you really wanna make custom cars use menyoo's spooner and then load yimmenu. Make the car or cars you want using menyoo then save them with yimmenu so that it becomes a json file. Then close game, remove menyoo. Start game inject yimmenu, load online if u wanna go online and spawn the cars u made as u wish


im getting the same error yim and menyoo crashes they don't work together so i can't save cars so sorry i am waiting for your help please

**Comment by Seanghost117** [comment]
You can't actually load both at the same time, you would need an asi loader / yim menu would need one to load the menyoo image. It's not hard to implement one (but may not happen at the moment) and also it really doesn't matter from my testing k personally spawn them and try to save them but yim menu needs an update when it comes to its json vehicle saving and loading, in its current state spawning menyoo vehicles is a mess. I will open a PR to extend functionality first.

**Comment by muhittinceko** [comment]
> You can't actually load both at the same time, you would need an asi loader / yim menu would need one to load the menyoo image. It's not hard to implement one (but may not happen at the moment) and also it really doesn't matter from my testing k personally spawn them and try to save them but yim menu needs an update when it comes to its json vehicle saving and loading, in its current state spawning menyoo vehicles is a mess. I will open a PR to extend functionality first.


i support you i hope you can make this happen and we will save it safely in the yim menu or i will follow you in any other way you know

**Comment by TheGreenBandit** [comment]
> You can't actually load both at the same time, you would need an asi loader / yim menu would need one to load the menyoo image. It's not hard to implement one (but may not happen at the moment) and also it really doesn't matter from my testing k personally spawn them and try to save them but yim menu needs an update when it comes to its json vehicle saving and loading, in its current state spawning menyoo vehicles is a mess. I will open a PR to extend functionality first.

You dont actually need an asi loader, just change the model spawn bypass on menyoo to yimmenus and itll work

**Comment by muhittinceko** [comment]
> > You can't actually load both at the same time, you would need an asi loader / yim menu would need one to load the menyoo image. It's not hard to implement one (but may not happen at the moment) and also it really doesn't matter from my testing k personally spawn them and try to save them but yim menu needs an update when it comes to its json vehicle saving and loading, in its current state spawning menyoo vehicles is a mess. I will open a PR to extend functionality first.
> 
> You dont actually need an asi loader, just change the model spawn bypass on menyoo to yimmenus and itll work

I don't understand what you are saying can you explain a little more and is this safe?

**Comment by muhittinceko** [comment]
i managed to do it friends my friend used nenyoo menu and i recorded it with the menu but the sirens were not flashing

**Comment by muhittinceko** [comment]
i managed to do it friends my friend used nenyoo menu and i recorded it with the yim menu but the sirens were not flashing

**Comment by Yimura** [comment]
Should be done via custom vehicle spawns.
