### ISSUE TITLE
Menu display garbled code

### ISSUE THREAD

**Issue by drakmemory** [Yimura/YimMenu#106]
**Describe the bug**
Change to garbled code in other languages

**Expected behavior**
Display garbled code after changing to other languages

**Screenshots**
![image](https://user-images.githubusercontent.com/44662380/157837820-baca7b6e-1333-4eab-a028-36d2194c0fed.png)

**Build**
Select which applies for you:
- [ ] I used YimMenu unmodified
- [x] I use my own version of YimMenu

**Comment by Yimura** [comment]
Could you give some additional information around your own build, did you build it straight from source code?
What language is your PC using?

**Comment by drakmemory** [comment]
> 您能否就您自己的构建提供一些额外的信息，您是直接从源代码构建的吗？ 您的电脑使用什么语言？

I use simplified Chinese
![image](https://user-images.githubusercontent.com/44662380/157839233-dcf8a2f0-f111-4311-9728-6200a8e89a01.png)

**Comment by Yimura** [comment]
You will need to load a font that supports Chinese characters. Take a look at renderer.cpp

**Comment by Yimura** [comment]
If you need more help with this some users on the BigBaseV2 thread have talked about this
https://www.unknowncheats.me/forum/grand-theft-auto-v/327176-bigbase-v2-55.html#post3147821

Additionally on the ImGui Github:
https://github.com/ocornut/imgui/issues/2070

**Comment by Yimura** [comment]
I will be closing this issue, if you have any more information to add and I deem it relevant I will reopen it.
