### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#1061]
### Describe the bug

After i jnjected yim in game, i go public ss and i get instan freeze all my computer and game, cant do anything

### Steps To Reproduce

Inject
Go public ss
Freeze

### Expected Behavior

Fix

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by epicmusicpt** [comment]
im having this issue too,i crash a few minutes after injection,even just afk in apartement

**Comment by epicmusicpt** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/10941534/cout.log)

**Comment by ghost** [comment]
I have the same issue on the latest nightly version.. :(
