### ISSUE TITLE
[Bug]: Aimbot not working

### ISSUE THREAD

**Issue by JDMJay** [Yimura/YimMenu#1066]
### Describe the bug

doesnt work as intended

### Steps To Reproduce

1. enable aimbot
2. aim at ped with peds enabled
3. doesnt lock onto them

### Expected Behavior

locking on as intended

### Screenshots and/or Logs

not needed

### Store

Rockstar

### Additional context

Tried on both controller and keyboard and mouse

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iconFehu** [comment]
https://user-images.githubusercontent.com/46149128/224549869-bdd042c0-7699-4dae-b5c1-8d652ba1760a.mp4

#1075

**Comment by Seanghost117** [comment]
I've confirmed that the feature does work, although slightly delayed behind fast-moving targets, it does work. Maybe can I see your settings, when messing with them it may effect something and lead to it not locking correctly

**Comment by JDMJay** [comment]
> I've confirmed that the feature does work, although slightly delayed behind fast-moving targets, it does work. Maybe can I see your settings, when messing with them it may effect something and lead to it not locking correctly

I fixed my issue it was because I was in a car and the aim key isn’t Left trigger in the car maybe a check to see if there in the vehicle would be useful

**Comment by Seanghost117** [comment]
I see I just use input_aim and never experienced it because I was on keyboard and mouse, I'll add it to check for vehicle aiming as well or gamepad while in a vehicle, I think that is like LB in a vehicle or something. Will fix soon
