### ISSUE TITLE
[Bug]: Custom weapons

### ISSUE THREAD

**Issue by epicmusicpt** [Yimura/YimMenu#1067]
### Describe the bug

Custom weapons dont work (only vehicle weapon does)

### Steps To Reproduce

toogle custom weapons, choose like Cage gun , Gravity gun , Delete gun etc...only vehicle weapon works.

### Expected Behavior

Custom weapons should work.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

Tryed on story mode and online
### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Rxann** [comment]
I also experience this problem

**Comment by Yimura** [comment]
There are possibly issues with the `entity::take_control_of` function.

It's probably returning false causing those custom weapons to not work as intended.

**Comment by Yimura** [comment]
Fixed with #1226
