### ISSUE TITLE
[Bug]: Vehicle teleport lockup/dysfunction

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1069]
### Describe the bug

When you enter a vehicle and teleport to a waypoint, after arriving you cannot exit the vehicle without dying. The only way to get out of this situation is to press the teleport hotkey again and that seems to fix the problem.

### Steps To Reproduce

1. Spawn a vehicle
2. Set a teleport waypoint
3. Press the teleport hotkey
4. Try to exit the vehicle

### Expected Behavior

The expected behavior should be that when you teleport, you don't enter this lockup type situation and get the default car behavior. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Primexz** [comment]
What car are you trying this on?
Which hotkey are you using?

I could not reproducethe bug with a t20.

**Comment by Rxann** [comment]
All vehicles

**Comment by Yimura** [comment]
This should not be possible the death trigger from the game has been disabled, please confirm if this issue is still occurring.

**Comment by Rxann** [comment]
It is not still happening, this can be closed!
