### ISSUE TITLE
[Request]: Outfit Editor

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1070]
### Problem

My feature is not related to a problem, just something that is no implemented yet.

### Solution

I would like it to open like a character creator so I could create outfits for my character.

### Reason

I feel like this is a feature that could be a solid addition to the menu and would be fun.

### Additional context
My prospected feature would be like what stand has implemented for an outfit editor.

**Comment by yasmasdas** [comment]
Duplicate of https://github.com/YimMenu/YimMenu/issues/908

**Comment by Rxann** [comment]
Alright thanks
