### ISSUE TITLE
[Request]: Report Protection

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1077]
### Problem

There is no feature that can block reports in Yim.

### Solution

A protection to be implemented that can block users reporting you.

### Reason

I currently need to use kiddions to get report protection and it would be nice to have also.

**Comment by Yimura** [comment]
Report protection is by default enabled in YimMenu as it doesn't have any adverse effects.
You can go to Settings -> Reactions and enable logs, notifications as well as kick reactions there for when someone tries to report you.

https://github.com/YimMenu/YimMenu/blob/10bbf1f4bb93d8e6c82c7da98151166f00a07d68/src/hooks/protections/increment_stat_event.cpp#L1-L29

**Comment by Rxann** [comment]
Hey,thanks so much for your response, I am just wondering one more thing. Is kicking someone banable by r*?

**Comment by Yimura** [comment]
Anything you do that's not intended by the game developers can be bannable, there are just certain things that are more likely to get yourself banned.
In general if you don't want to get banned just don't do any stat editing, modding in money, griefing players, etc...

**Comment by Rxann** [comment]
okay thank you
