### ISSUE TITLE
[Request]: force freemode outfit in jobs/force enable interaction menu appearance options

### ISSUE THREAD

**Issue by X2E4VXpZKv** [Yimura/YimMenu#1080]
### Problem

game forces outfits in some older jobs and heists

### Solution

- add an option to keep the currently equipped freemode outfit when starting jobs  
- ~~add an option to keep interaction menu style options enabled during jobs/freemode activites~~

### Reason

qol

**Comment by X2E4VXpZKv** [comment]
the second request is solved by the outfit editor but the first one would stil be nice

**Comment by Yimura** [comment]
Persist outfit has been implemented.
