### ISSUE TITLE
Can’t start Casino Heist

### ISSUE THREAD

**Issue by stuckinplace** [Yimura/YimMenu#1086]
### Describe the bug

After inviting random people to the heist lobby I click start heist but it just gives “Heist leader left the planning board” error before it takes me to planning board. I thought it was something with my pc but without any mod menus or with other mod menus it doesn’t happen only with YimMenu.

I think it’s something with protections i read it somewhere.

Thanks

### Steps To Reproduce

Try to start Casino Heist after inviting people

See the error

### Expected Behavior

Just starts planning board

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Duplicate of #1015
