### ISSUE TITLE
[Bug]:  Instant Respawn & Model Death Causing Infinite Loading Screen At Respawn

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#1087]
### Describe the bug

Instant Respawn & Model Death causing infinite loading screen when die

### Steps To Reproduce

1. Go to Self
2. Active Instant Respawn 
3. Infinite loading screen when die
4. Go to World->Spawn Ped->Change Model
5. Infinite loading screen when die

### Expected Behavior

Do get Stuck at infinite loading screen and clear wanted level 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
Does this occur in singleplayer or online?

**Comment by 0xEmiil** [comment]
> Does this occur in singleplayer or online?

Singelplayer, i dont play online with the menu soo idk if this can take efect on online

**Comment by ghost** [comment]
> > Does this occur in singleplayer or online?
> 
> Singelplayer, i dont play online with the menu soo idk if this can take efect on online

Blame rockstar, they don't "expect" a model different than the protagonists to be played in singleplayer...

**Comment by 0xEmiil** [comment]
> > > Does this occur in singleplayer or online?
> > 
> > 
> > Singelplayer, i dont play online with the menu soo idk if this can take efect on online
> 
> Blame rockstar, they don't "expect" an model different than the protagonists to be played in singleplayer...

Yh i submit the issue anyway cuz the model change back feature on yim, but i couldnt find where yall add that
And cuz it happens the same(infinite black loading screen) even with the insta respawn feature not allways and without having a model set

**Comment by Aure7138** [comment]
Any special model names since I die after changing models with instant respawn enabled, it doesn't load infinitely

**Comment by 0xEmiil** [comment]
> Any special model names since I die after changing models with instant respawn enabled, it doesn't load infinitely.

weird i swear i tried recently with the instant respawn and it just stuck on black screen, i have to test again and if it doesn't get stuck, we can close this.

**Comment by Aure7138** [comment]
> weird i swear i tried recently with the instant respawn and it just stuck on black screen, i have to test again and if it doesn't get stuck, we can close this.

Can you share your settings.json, looks like it's time to start my EPIC platform

**Comment by Aure7138** [comment]
mmmm, I am using this build https://github.com/YimMenu/YimMenu/actions/runs/4558627853
[video](https://i.imgur.com/MKHcppp.mp4)

**Comment by Yimura** [comment]
No response from issue author, closing for now.

@0xEmiil, if you've got more information to add you can just comment here and I'll reopen the issue.
