### ISSUE TITLE
[Bug]: Weapon Damage modifier seemingly not working anymore

### ISSUE THREAD

**Issue by davidjan3** [Yimura/YimMenu#1092]
### Describe the bug

A few versions ago the damage modifier had a notable impact on actual damage in game. Enemies died with few shots, and kicking a car would result in notable deformation. Now that the GUI for that has changed, the damage modifier appears to be useless, regardless if the checkbox "Damage Override" is checked or not.

### Steps To Reproduce

1. Self -> Weapons -> Damage
2. Enter large number (e.g. 1000)
3. Activate checkbox above
4. Shoot a ped in the foot, kick a car...

### Expected Behavior

Ped dies, car has huge dent

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
how are u killing them, with a gun or by melee?

**Comment by BeztNA** [comment]
can we just give old multi dmg back ? its fine to me

**Comment by davidjan3** [comment]
Reverting the change seems reasonable. I think the new one works occasionally when you check the checkbox and shoot. It definitely never works with melee damage. And the older one with the slider was just easier to use imo
