### ISSUE TITLE
[Request]: Orbital Cannon Dubstep & Earrape

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1094]
### Solution

add orbital cannon dubstep player https://www.youtube.com/watch?v=Aod-S7r116o and earrape https://www.youtube.com/watch?v=GcW9OLQjgQc for whole session of course

### Reason

these features are needed to prevent griefing cause if everyone is deaf no one will want to play online

**Comment by Peax** [comment]
Categorically no to anything that can cause potential hearing damage. The dubstep thingy I don't mind. Besides that I'm still waiting for Daddy to finally approve #994.

**Comment by epicmusicpt** [comment]
"these features are needed to prevent griefing" lmao,toxic crap

**Comment by Svxy** [comment]
> Besides that I'm still waiting for Daddy to finally approve #994.

This should play out reeeeal smoothly.. xD

**Comment by Sys0xdbg** [comment]
i love it. 2end one

**Comment by Sys0xdbg** [comment]
https://www.youtube.com/watch?v=VrQ7N5oNJlY

made it.i would have posted but i don't think yim gonna approve it.

**Comment by Yimura** [comment]
Will not be implemented as it's overly obnoxious and I wouldn't want every other lobby to have this thing happening in it.
