### ISSUE TITLE
cant load into online

### ISSUE THREAD

**Issue by deadshot1538** [Yimura/YimMenu#1099]
i was messing around with stat editer and now I cant load into online its saying timed out locating session

**Comment by Peax** [comment]
Does this error occur only if YimMenu is loaded? What happens when you don't use any mod menu?

**Comment by Yimura** [comment]
Not a YimMenu issue, you probably messed with the wrong stats or modified them incorrectly.

**Comment by Yimura** [comment]
You're free to continue discussing here to try and fix it.

**Comment by deadshot1538** [comment]
> Does this error occur only if YimMenu is loaded? What happens when you don't use any mod menu?

it says the same thing without the menu

**Comment by deadshot1538** [comment]
also when i try to switch online characters my screen goes black and I cant do anything
