### ISSUE TITLE
Doesn't build, can't find rage::vector3

### ISSUE THREAD

**Issue by VolkerSchlegel** [Yimura/YimMenu#110]
**Describe the bug**
Menu doesn't build anymore, throwing a buch of errors.

**To Reproduce**
1. `git pull`
2. Run GenerateProjects.bat
3. Open the solution
4. Try to build it

**Screenshots**
![error3](https://user-images.githubusercontent.com/66200818/158161671-7227f31a-d2d1-471e-a90b-ae51efc6d85d.PNG)
![error4](https://user-images.githubusercontent.com/66200818/158161679-2441bec7-fa80-4c42-b3a0-03be6dbbb68e.PNG)
![error1](https://user-images.githubusercontent.com/66200818/158161682-57b97c24-a8d6-4f21-b652-a1795f820a05.PNG)
![error2](https://user-images.githubusercontent.com/66200818/158161685-016a96d1-9092-4c51-993e-0468ce067805.PNG)

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
I upgraded to Visual Studio Community 2022, since the project seemed to require the latest buildtools which I couldn't find in the visual studio installer
It's been a while since I looked at this project

**Comment by Kaki7964** [comment]
I can't even reopen it, stupid bot lol

**Comment by Yimura** [comment]
Are you sure you're using YimMenu unmodified? Because vanilla YimMenu works.

To fix this replace all occurrences with rage::fvector3.

Also the bot is talking to collaborators not to your specifically.

**Comment by Kaki7964** [comment]
Yeah, that is my unmodified version..

**Comment by Yimura** [comment]
Your unmodified version? Did you just merge in with this repository after your forked it a long time ago? Because that won't work you know. As well as other dependency issues you will need to update each vendor that has been updated since.

**Comment by Kaki7964** [comment]
No, I cloned it and never modified it, I have a modified version as well

**Comment by Kaki7964** [comment]
Ok nevermind, forgot to add `--recursive` to update imgui and all the other dependencies

**Comment by Yimura** [comment]
![image](https://user-images.githubusercontent.com/24669514/158164313-a1e6780c-5cd6-4208-90af-3d5d0dab29cf.png)
Also your steps to reproduce do not reflect what you tried.
