### ISSUE TITLE
[Bug]: Peds not spawning for everyone

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1104]
### Describe the bug

When using the ped spawner, when you put it on self, the peds spawn perfectly fine. But, when you put it on spawn for everyone, nothing spawns.

### Steps To Reproduce

1: Enter a lobby
2: Spawn ped for everyone
3: Observe

### Expected Behavior

The ped should spawn for everyone in the lobby

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

As of Nightly [0a35d12]

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This is normal as you need to be fairly close to a player before you can spawn anything on them, as a remediation spectate the player and then spawn the ped.
