### ISSUE TITLE
[Request]: Force Random Event

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1106]
### Solution

An option to force a specified event to spawn closest to you

### Reason

It would be pretty cool

**Comment by Yimura** [comment]
Could you clarify which events exactly you're talking about?

**Comment by Rxann** [comment]
Yeah basically force things to spawn with that blue blip on the map. for example where different crime scenes will spawn and when you complete them you get the service carbine.

**Comment by Rxann** [comment]
I believe this could be closed, as there is not a good solution(that i know of).
