### ISSUE TITLE
Clicking on Settings -> Hotkeys crashes the game

### ISSUE THREAD

**Issue by VolkerSchlegel** [Yimura/YimMenu#111]
**Describe the bug**
I opened the menu, looked through the different new options and klicked on `Hotkeys` in the settings tab, then my game suddenly crashed.

**To Reproduce**
1. Open the menu
2. Go to Settings
3. Click on "Hotkeys"

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
I don't know if that matters but I had one of the players open before opening the settings tab

Nice new UI btw 😄

**Comment by Yimura** [comment]
Logs?

**Comment by Kaki7964** [comment]
Nothing in the GTA V folder, I haven't searched anywhere else

**Comment by Yimura** [comment]
Logs can be found here: `%appdata%/BigBaseV2/cout.log`

**Comment by Kaki7964** [comment]
Nothing about the crash there

**Comment by Yimura** [comment]
Have you actually tried to reproduce it yourself or was this a one time occurrence because you yourself need to have reproduced it yourself and without any logs this issue is useless.

**Comment by Kaki7964** [comment]
I have reproduced it multiple times

**Comment by Kaki7964** [comment]
Wait, just did it again, this time it logged something: 
```
***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 14940

*******	STACKDUMP *******
stack dump [0]		C:\****\Modding\GTAV\tmp\YimMenu\BigBaseV2\src\widgets\imgui_hotkey.hpp L: 179 ImGui::Hotkey
stack dump [1]		C:\****\Modding\GTAV\tmp\YimMenu\BigBaseV2\src\views\view_settings.cpp L: 11 big::view::settings
stack dump [2]		C:\****\Modding\GTAV\tmp\YimMenu\BigBaseV2\src\views\view_active_view.cpp L: 41 big::view::active_view
stack dump [3]		C:\****\Modding\GTAV\tmp\YimMenu\BigBaseV2\src\hooking.cpp L: 182 big::hooks::swapchain_present
stack dump [4]	
stack dump [5]	
stack dump [6]	
stack dump [7]	 BaseThreadInitThunk
stack dump [8]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```

**Comment by Yimura** [comment]
Alright thank you, I will look at it when I have the time.

**Comment by Kakiking** [comment]
Uploading bug_scaled_down.mp4…
I also recorded the bug

**Comment by Yimura** [comment]
@Kakiking Are you doing anything else, like closing the console window that opens? I'm unable to reproduce this issue.

**Comment by Kaki7964** [comment]
I clicked on a player in the list before, I didn't test if it would crash if I didn't do that, but nothing otherwise.

**Comment by Yimura** [comment]
I'm unable to reproduce this issue, are you building in Release?

**Comment by Kaki7964** [comment]
Yes, debug doesn't even build, see #13

**Comment by Yimura** [comment]
> Yes, debug doesn't even build, see #13

Ye that's fine, some people just make Debug work instead of swapping to release. So they end up running Debug version of YimMenu which is slower and prone to crashing...

However I will close this issue as I'm unable to reproduce this issue.

If you forked YimMenu, push to that repository and link it in this issue. This issue feels like it's something in your build and not in YimMenu.

I have several people who I asked to reproduce this on their PC and they were unable to.

**Comment by Kaki7964** [comment]
> which is slower and prone to crashing...

The release version also sometimes like to crash. Happened multiple times to me already, it didn't log anything, so it might be GTA, not the menu 🤷‍♂️ 

> This issue feels like it's something in your build and not in YimMenu.
I'm 100% sure I didn't modify anything, but I can still clone the repo again. I'm using Visual Studio 2022, downloaded at the day I opened this issue.

Maybe I can get a video of the crash. I tried making one before but it was so laggy it was basically useless, the menu only appeared for a few frames(potato pc 🙈).

**Comment by Kaki7964** [comment]
Having a working debug build would be really usefull for debugging, I'll see if I can get the debug version working, maybe I'll make a PR.

**Comment by Yimura** [comment]
> Having a working debug build would be really usefull for debugging, I'll see if I can get the debug version working, maybe I'll make a PR.

No need, the Debug build can be made working easily by commenting out 2 lines or so.
I'm planning on removing the debug build as currently it causes more problems and is pretty useless.

**Comment by Kaki7964** [comment]
ok

**Comment by Kaki7964** [comment]
Still happens

**Comment by Yimura** [comment]
> Still happens

Ok but did you modify YimMenu? If yes then make sure your source code is pushed online on Github, I can check it out then. If not then I'm sorry but I know no one (except for you) that has had issue with this.

The issue will remain here obviously for others that might experience this but currently I'm not investing more time into fixing it.

**Comment by Kaki7964** [comment]
No, I didn't modify it, I just cloned it again and build it in Release, x64
