### ISSUE TITLE
[Request]: Remote Vehicle Control (not what you think)

### ISSUE THREAD

**Issue by wdymUsername** [Yimura/YimMenu#1114]
### Problem

1) GTA:O offers some basic remote vehicle control functions over personal vehicle such as opening doors, turning on and off lights, engine and radio.
2) Some not so online options, that I know of, add to this with abilities to open/close windows, toggle roof for applicable vehicles, toggle high beams, car alarm, indicator lights, etc.

Sadly we do not have this control over spawned vehicles.

### Solution

Introduce mentioned features to the menu.
Would be nice if we could have check for last entered vehicle, which would then be target of the controls and pull up "standalone" window with features via keybind.

### Reason

Personal vehicle controls are limited.
You have to purchase the vehicle.
Non toxic, fun feature for anyone who likes to play around with cars.

**Comment by Tayipc38** [comment]
When you mention standalone window and keybinds, do you mean an extra button to open up a window that remains even if the menu UI is turned off? And by keybinds, do you mean configurable hotkeys?

**Comment by wdymUsername** [comment]
That is the idea, yes, window independent on "main" menu UI. 
Something like the overlay option (GUI Overlay or something like that? It is already in the menu now - displays FPS, ped limits, etc.), but with its own hotkey to show/hide window with car related controls.
Indeed by keybind, I mean hotkey. For mentioned window alone. I think having hotkeys for how ever many options in it would be overkill.
