### ISSUE TITLE
[Bug]: random outfit crash

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#1118]
### Describe the bug

random outfit crash

### Steps To Reproduce

outfit editor
random

### Expected Behavior

no crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
Random Component crashes or, and please provide the full log, it is located at `%appdata%\BigBaseV2\cout.log`

**Comment by BeztNA** [comment]
> Random Component crashes or, and please provide the full log, it is located at `%appdata%\BigBaseV2\cout.log`

[cout.log](https://github.com/YimMenu/YimMenu/files/11011302/cout.log)

**Comment by Aure7138** [comment]
Thank you very much for providing the log, GTA5.exe+0x53DF00 points to CDrawCommandBuffer, the cause of the crash is not yet clear, and the current possible fix plan is to do a null check on the crashed place, that is, to force patch the crash
Another way is to reimplement SET_PED_RANDOM_COMPONENT_VARIATION with SET_PED_COMPONENT_VARIATION (not yet tested)

**Comment by FIying-Scotsman** [comment]
> Thank you very much for providing the log, GTA5.exe+0x53DF00 points to CDrawCommandBuffer, the cause of the crash is not yet clear, and the current possible fix plan is to do a null check on the crashed place, that is, to force patch the crash Another way is to reimplement SET_PED_RANDOM_COMPONENT_VARIATION with SET_PED_COMPONENT_VARIATION (not yet tested)

Similar to the "Gen9" vehicles - there's supposedly a handful of clothes (and vehicle mods for some older vehicles - i.e there's an invalid spoiler for one of the Porsche lookalikes for example) which are invalid/don't have a model so the game crashes. I don't have the hash to hand but a friend did mention a shirt (or jacket?) crashed them in SP while cycling clothes. It may be the case here as well.

**Comment by Aure7138** [comment]
> Similar to the "Gen9" vehicles - there's supposedly a handful of clothes (and vehicle mods for some older vehicles - i.e there's an invalid spoiler for one of the Porsche lookalikes for example) which are invalid/don't have a model so the game crashes. I don't have the hash to hand but a friend did mention a shirt (or jacket?) crashed them in SP while cycling clothes. It may be the case here as well.

I think it's more like some kind of memory leak, the crash happens after about 20 clicks manually, I also have logged the last component when the crash happens, reapply doesn't crash me

**Comment by unnamed204** [comment]
![image](https://user-images.githubusercontent.com/120012489/226321143-140f811d-d5d3-445b-9ce9-4301ac7d7f28.png)
The same thing happens when spawning peds. They get this weird texture attached. Normally the exception handler would prevent the game from crashing, but too many stack traces are generated, causing the game to freeze. (I added a rate limiter to avoid freezing)

**Comment by Aure7138** [comment]
> The same thing happens when spawning peds. They get this weird texture attached. Normally the exception handler would prevent the game from crashing, but too many stack traces are generated, causing the game to freeze. (I added a rate limiter to avoid freezing)

Crash when spawning Peds? It would be appreciated if you have any crash dumps(logs)

**Comment by unnamed204** [comment]
> Crash when spawning Peds? It would be appreciated if you have any crash dumps(logs)

https://github.com/YimMenu/YimMenu/blob/d12c7fe69cec6ec1a8c8df8c83c290f077502d27/src/views/world/view_spawn_ped.cpp#L137
It is exactly the same crash dump that BeztNA posted
