### ISSUE TITLE
[Bug]: Vehicle remote control not working

### ISSUE THREAD

**Issue by Papela** [Yimura/YimMenu#1119]
### Describe the bug

Sometimes when I try to stop him, turn off the engine and some other functions, it shows me a message that the player is not in a vehicle.

### Steps To Reproduce

1. Select the player and spectate him
2. Open the vehicle menu and click on stop the vehicle
3. See the error

### Expected Behavior

Stop his vehicle, kill the engine and other functions related to the vehicle.

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11011255/cout.log)
![B02](https://user-images.githubusercontent.com/45976195/226182535-56969583-a129-4bb9-849e-6a5fcdc49deb.jpg)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by LopeKinz** [comment]
Maybe he is using a protection against remote control. try this option with a friend.

**Comment by Rxann** [comment]
#1226 may have fixed this. I don't know though.
