### ISSUE TITLE
Nightly build missing?

### ISSUE THREAD

**Issue by OmniModz** [Yimura/YimMenu#1126]
The nightly build seems to be strangely missing.

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/releases/tag/nightly

**Comment by Yimura** [comment]
Thanks for making an issue, just the Nightly build failing to make the release public.

If somehow the nightly build failed to publish you can always find it here.
https://github.com/YimMenu/YimMenu/actions/workflows/nightly.yml
