### ISSUE TITLE
[Bug]: set bounty not work

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#1129]
### Describe the bug

set bounty not work

### Steps To Reproduce

set bounty not work

### Expected Behavior

work

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by BeztNA** [comment]
just work for my self

**Comment by Yimura** [comment]
Unable to reproduce, set bounty works perfectly both anonymous and not anonymous.

After about 5-10 seconds the bounty should be set on the target player.

**Comment by 43eayl5** [comment]
Both anonymous and non-anonymous don't work for me.
