### ISSUE TITLE
[Request]: Ghost Organization

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1130]
### Solution

A menu box that will enable CEO Ghost Organization

### Reason

I think it would be fun and convenient.

**Comment by Kenneth44z** [comment]
Just use off-radar..?

**Comment by TheGreenBandit** [comment]
> Just use off-radar..?

i think they mean for their friends to be off radar too, however they can just give them off radar selectively through the gui already

**Comment by Rxann** [comment]
> > Just use off-radar..?
> 
> i think they mean for their friends to be off radar too, however they can just give them off radar selectively through the gui already

Yes I do

**Comment by Yimura** [comment]
Implemented through a toggle near Off the Radar.
