### ISSUE TITLE
[Bug]: namespace "std" has no member "unreachable

### ISSUE THREAD

**Issue by EsmarW** [Yimura/YimMenu#1134]
### Describe the bug

Hello, this is the same issue as #642.

I have recloned repository, repaired visual studio installation, redownloaded the extensions, and have ensured MSVC is the latest version. 

Any tips on how to get rid of this issue/error will be greatly appreciated!

### Steps To Reproduce

1. Install Visual Studio + Related Extensions (Ensure MSVC is latest)
2. Clone YimMenu / Open in Visual Studio
3. CMake runs automatically
4. Run Build All
5. Error Occurs

### Expected Behavior

Expect Build to execute without error. I believe a .dll file is the result.

### Screenshots and/or Logs

The following is my Visual Studio configuration. I have the latest version of MSVC installed, and all related extensions installed as well.
![yimmennuissue2](https://user-images.githubusercontent.com/122946736/227127538-3e008d6b-2e5d-4893-ad64-c308ab6f2112.JPG)

Error Message + Location:
![yimmennuissue](https://user-images.githubusercontent.com/122946736/227127541-2fcd299a-4f2b-4f5d-92dc-91dba04be277.JPG)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by EsmarW** [comment]
Issue still persists after removing seemingly unnecessary extensions

Latest Visual Studio Installation Configuration:
![yimmennuissue3](https://user-images.githubusercontent.com/122946736/227131446-1072e018-1ef7-4024-a84a-8c9b3894a4d5.JPG)

**Comment by Yimura** [comment]
Could you try using Visual Studio 2022 (v143)? Because it appears you're using 2019 (v142).

**Comment by EsmarW** [comment]
> Could you try using Visual Studio 2022 (v143)? Because it appears you're using 2019 (v142).
 Man I'm so dumb. Thank you! For your help and the menu! I truly appreciate it greatly.
