### ISSUE TITLE
[Request]: Casino region lock bypass

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1136]
### Problem

Without a vpn, in some countries the casino features (such as spinning the wheel) are completely blocked from us.

### Solution

Add an option which allows the user to bypass casino region lock.

### Reason

Some people don't want to use a vpn as it makes their ping very unstable or they just can't afford one.

### Additional context

Stand mod menu already has this feature, so i think it would be possible to implement into YimMenu too.

**Comment by Aure7138** [comment]
#1018

**Comment by ghost** [comment]
oof sorry didnt notice that im closing this issue rn
