### ISSUE TITLE
Freeze then CTD, with a 1gb repeating error cout.log file

### ISSUE THREAD

**Issue by steveosten2** [Yimura/YimMenu#1144]
### Describe the bug

After usually under half an hour of play the game will freeze and crash to desktop. It now alos creates a roughly 1gb cout.log file that repeats the log posted below for 2.6 million lines

### Steps To Reproduce

Play game with menu injected

### Expected Behavior

expected to not crash

### Screenshots and/or Logs

EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0xC4D140FB
RCX: 0x240569C4800
RDX: 0x24095873AD0
RBX: 0x24095BC3D40
RSI: 0xD67E8AF040
RDI: 0x240569C4800
RSP: 0xD67E8AEC10
RBP: 0xD67E8AEDF0
R8:  0xD67E8AF040
R9:  0xD67E8AEED0
R10: 0x24095BBCB80
R11: 0x240569C4800
R12: 0xD67E8AF0E0
R13: 0x0
R14: 0x0
R15: 0xD67E8AF1B0
Dumping stacktrace:
[0]	GTA5.exe+0xFF6A7E 0x7FF7BB546A7E
[1]	GTA5.exe+0xFF9089 0x7FF7BB549089
[2]	GTA5.exe+0x1015498 0x7FF7BB565498
[3]	GTA5.exe+0x1014869 0x7FF7BB564869
[4]	GTA5.exe+0xD0E444 0x7FF7BB25E444
[5]	GTA5.exe+0xD0E148 0x7FF7BB25E148
[6]	GTA5.exe+0xD0E0C6 0x7FF7BB25E0C6
[7]	GTA5.exe+0xD04609 0x7FF7BB254609
[8]	GTA5.exe+0x1DC9A 0x7FF7BA56DC9A
[9]	YimMenu.dll+0xC898C 0x7FFF2451898C
[10]	YimMenu.dll+0x7BD9C 0x7FFF244CBD9C
[11]	YimMenu.dll+0x43722 0x7FFF24493722
[12]	YimMenu.dll+0xE8E1D 0x7FFF24538E1D
[13]	YimMenu.dll+0xE8D8C 0x7FFF24538D8C
[14]	YimMenu.dll+0xE8C81 0x7FFF24538C81
[15]	KERNELBASE.dll ChangeTimerQueueTimer
[16]	ntdll.dll RtlUserFiberStart
--------End of exception--------
(repeated for about a gb worth)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by steveosten2** [comment]
It also still does a freeze and not respond after 20 minutes although #1132 claimed to fix it

**Comment by Yimura** [comment]
No it's still there sadly.

**Comment by maybegreat48** [comment]
Are you using "Rapid Fire"? If so, try disabling it and see if it crashes

Were you in a vehicle when it crashed? Were you firing a weapon? Have you used sticky bombs or flare guns?

**Comment by steveosten2** [comment]
> 

It does not happen when firing a weapon or driving, I have downloaded the latest version posted 2 hours ago and will test it later today, I know a few things have been merged since the version I was on

**Comment by Aure7138** [comment]
If possible, I want to see all your full logs. If you get stuck in a loop, immediately end the process manually. The log won't be that big

**Comment by steveosten2** [comment]
> If possible, I want to see all your full logs. If you get stuck in a loop, immediately end the process manually. The log won't be that big

Will do, going to try and run it now on the newest version, if I dont have the issue by the end of the night I'll close this

**Comment by steveosten2** [comment]
> If possible, I want to see all your full logs. If you get stuck in a loop, immediately end the process manually. The log won't be that big

had a freeze and ended manually as fast as possible, it doesnt look exactly like the one before
edit: it hasnt happened since, I think it may have been a modder crashing me but im not sure
[cout.log](https://github.com/YimMenu/YimMenu/files/11073077/cout.log)

**Comment by ghost** [comment]
> Are you using "Rapid Fire"? If so, try disabling it and see if it crashes
> 
> Were you in a vehicle when it crashed? Were you firing a weapon? Have you used sticky bombs or flare guns?

I have been getting random crashes for a while with yimmenu. Happens mainly in missions and sometimes in freeroam. Mostly when driving and hitting a destructible object. Only once or twice so far while on foot and firing a weapon. CTD with no error logged in log file. Unable to reliably reproduce the crash on demand. But the most common way I've got it to happen repeatably (although not a guarantee) is during the finale of The Lost Contract for the auto shop during quickplay. Once you exit the northern-most meth lab, hop in a car and drive into the corner of the fence (there's no fuel tank during the mission) in the bottom left of this screenshot: https://gta.fandom.com/wiki/Foreclosed_Farm?file=ForeclosedFarm-GTAV-StorageArea.jpg The game has CTD (without logging an error) on me multiple times in this exact spot on this mission during quickplay using yimmenu. I think I've captured it twice using windows xbox gamebar capture, among a couple other instances of this crash.

**Comment by steveosten2** [comment]
I haven't had this issue on the last few latest patches, I'm closing this issue and if it resurfaces I'll open a more detailed issue
