### ISSUE TITLE
[Request]:  Data Rebuild Improved

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#1145]
### Problem

I think its really annoying when you rebuild the data and the game laggs off and we can improve this to use on other features or in the future

### Solution

I use gta_data from yim in my personal menu i checked out and tryed this 
void yim_fipackfile::for_each_fipackfile(std::function<size_t(yim_fipackfile& rpf_wrapper)> cb)
	{
		
		// The DLC devices are in another array.
		const auto non_dlc_mounted_devices_names = get_non_dlc_mounted_devices_names();

		// Use a set to keep track of which mount names have been tried for a given RPF file.
		std::set<std::string> tried_mount_names;

		for (auto i = 1; g_pointers->m_fipackfile_instances[i]; ++i)
		{
			auto* rpf = g_pointers->m_fipackfile_instances[i];

			// Its hard coded in the binary?
			if (i >= 3672)
			{
				break;
			}

			yim_fipackfile rpf_wrapper = yim_fipackfile(rpf, default_mount_name);

			// Check if the RPF file is already mounted on a non-DLC device.
			for (const auto& non_dlc_mounted_device_name : non_dlc_mounted_devices_names)
			{
				auto* non_dlc_mounted_device = rage::fiDevice::GetDevice(non_dlc_mounted_device_name.c_str(), true);

				if (rpf == non_dlc_mounted_device)
				{
					rpf_wrapper.mount_name = non_dlc_mounted_device_name;
					break;
				}
			}

			if (tried_mount_names.size() < 13)
			{
				// If we haven't tried all the mount names yet, try the remaining ones.
				for (const auto& mount_name : {"memory:/", "memory:", "dlc", "dlc:", "dlc:/", "dlcpacks:/", "common:/", "commoncrc:/", "update:/", "update2:/", "platform:/", "platformcrc:/", "gamecache:/"})
				{
					if (tried_mount_names.find(mount_name) == tried_mount_names.end())
					{
						rpf_wrapper.mount_name = mount_name;

						const auto result = cb(rpf_wrapper);

						if (result > 0)
						{
							// If we got a successful result from the callback function, we don't need to try
							// any more mount names for this RPF file.
							break;
						}
						else
						{
							// Otherwise, record the mount name that was tried.
							tried_mount_names.insert(mount_name);
						}
					}
				}
			}

			if (tried_mount_names.size() == 13)
			{
				// If we've tried all the mount names and haven't found the RPF file yet, mount it on the
				// default mount name.
				rpf_wrapper.mount_name = default_mount_name;
				rpf->Mount(default_mount_name);

				cb(rpf_wrapper);

				g_pointers->m_fipackfile_unmount(default_mount_name);
			}

			if (i % 80 == 0)
			{
				script::get_current()->yield();
			}
		}
	}
	This worked fine on my menu and i think it could be possible soultion as i said I tryied this on my MENU so idk if it will work on yim :)

### Reason

I wannted to add this and optimize or improve in case we can cache more data

**Comment by Yimura** [comment]
This is a one time thing for every game update, this is not something that needs to be improved.
