### ISSUE TITLE
[Bug]: gta_data_service not recognizing some peds.

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1147]
### Describe the bug

I believe the gta_data_service is not working correctly and not caching all peds because most peds are unspawnable via the spawn ped menu.

### Steps To Reproduce

1. Open Spawn Ped
2. Observe all peds are not spawnable.

### Expected Behavior

All the peds in the game should be able to be spawned.

### Store

Steam

### Additional context

Peds like the fat woman and stripper are unavailable I have noticed. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
Yes, I also hope that they will add all the peds such as u_m_m_jesus_01, player_two, player_one, player_zero etc https://docs.fivem.net/docs/game-references/ped-models/

**Comment by Rxann** [comment]
Yea and the strippers and fat people too

**Comment by Yimura** [comment]
It's possible to cache a lot more peds you need to follow some specific steps:
1. Remove the cache by removing the `%appdata%/BigBaseV2/cache` folder
2. Launch the game and inject YimMenu before loading single player or online.
3. Click the button to cache on init of the game

I haven't done this myself but according to what @Aure7138 told me you can cache around 600-700 more peds using this.

**Comment by ghost** [comment]
Yes, but why, after updating the cache, it is impossible to find, for example, Jesus ("u_m_m_jesus_01") or Trevor ("player_two") and many others in the drop-down list, but you have to enter the names manually.

**Comment by xiaoxiao921** [comment]
> Yes, but why, after updating the cache, it is impossible to find, for example, Jesus ("u_m_m_jesus_01") or Trevor ("player_two") and many others in the drop-down list, but you have to enter the names manually.

Were they available before? Or never?

**Comment by ghost** [comment]
They were never on the list, but they could always be spawned manually

**Comment by Rxann** [comment]
> They were never on the list, but they could always be spawned manually

How do you spawn manually

**Comment by Rxann** [comment]
> It's possible to cache a lot more peds you need to follow some specific steps:
> 
> 1. Remove the cache by removing the `%appdata%/BigBaseV2/cache` folder
> 2. Launch the game and inject YimMenu before loading single player or online.
> 3. Click the button to cache on init of the game
> 
> I haven't done this myself but according to what @Aure7138 told me you can cache around 600-700 more peds using this.

If more peds are cached, does that mean there are more spawnable in the Spawn Ped menu?

**Comment by ghost** [comment]
You can just select ALL and enter the name manually even when it is not in the list and the ped will spawn

**Comment by Rxann** [comment]
The cache on init does cache many more peds

**Comment by ghost** [comment]
Yes, but it does not cache all the peds that are in the game

**Comment by xiaoxiao921** [comment]
Yeah we can still improve it

**Comment by Rxann** [comment]
Alright

**Comment by Aure7138** [comment]
> Yes, but why, after updating the cache, it is impossible to find, for example, Jesus ("u_m_m_jesus_01") or Trevor ("player_two") and many others in the drop-down list, but you have to enter the names manually.

What is the number of loaded peds in your cache, mine is 1019, u_m_m_jesus_01 and player_two are also in it
![image](https://cdn.discordapp.com/attachments/963096010853347409/1092449124026171472/image.png)
![image](https://cdn.discordapp.com/attachments/963096010853347409/1092448600912568371/image.png)
![image](https://cdn.discordapp.com/attachments/963096010853347409/1092448648157204541/image.png)

**Comment by Rxann** [comment]
> > Yes, but why, after updating the cache, it is impossible to find, for example, Jesus ("u_m_m_jesus_01") or Trevor ("player_two") and many others in the drop-down list, but you have to enter the names manually.
> 
> What is the number of loaded peds in your cache, mine is 1019, u_m_m_jesus_01 and player_two are also in it ![image](https://camo.githubusercontent.com/3fb1dbd8d7d812d68ba93f679ab6a37e91641d59a4dbb7bdf1b278c05e5fb8e1/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3936333039363031303835333334373430392f313039323434393132343032363137313437322f696d6167652e706e67) ![image](https://camo.githubusercontent.com/28a647a5c711bfd8d34a96522921624466ac96eb120c6cd6193532ecbf1399bc/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3936333039363031303835333334373430392f313039323434383630303931323536383337312f696d6167652e706e67) ![image](https://camo.githubusercontent.com/a26c7b487e77cd4e663a0477c9dff8a88530a6feda120eb2d3fd7216251c056b/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3936333039363031303835333334373430392f313039323434383634383135373230343534312f696d6167652e706e67)

I have the same number as you. Sometimes in public sessions can you guys not spawn peds for everyone due to Invalid Online Player?

**Comment by Aure7138** [comment]
> I have the same number as you. Sometimes in public sessions can you guys not spawn peds for everyone due to Invalid Online Player?

I guess some players are too far away to not load collision

**Comment by ghost** [comment]
> The cache on init does cache many more peds

Oh now it works thanks

**Comment by Rxann** [comment]
is there a reason that sometimes peds will spawn far away when you spawn for everyone?

**Comment by Rxann** [comment]
This has been fixed with the cache on init feature.
