### ISSUE TITLE
Spawn maxed out vehicle

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#115]
**Is your feature request related to a problem? Please describe.**
Spawn maxed out vehicle

**Describe the solution you'd like**
Option to toggle 'spawn maxed out' when spawning vehicle

**Provide Reasoning**
why not

**Additional context**
N/A

**Comment by Yimura** [comment]
Would you like to have maxed out performance mods or maxed out EVERYTHING?

**Comment by howdoiusekeyboard** [comment]
Max out EVERYTHING, as some vehicles have wierd traction upgrades

**Comment by howdoiusekeyboard** [comment]
Doesn't include bulletproof tires

**Comment by Yimura** [comment]
Create a new issue.
