### ISSUE TITLE
[Request]: Party Mode

### ISSUE THREAD

**Issue by epicmusicpt** [Yimura/YimMenu#1150]
### Problem

no problem

### Solution

party mode peds

### Reason

like riot mode but peds dance and drink like in partys. i dont know if its possible i just got the ideia so i leave it here.

### Additional context

would be nice :)

**Comment by Aure7138** [comment]
sounds like dance mode
https://github.com/YimMenu/YimMenu/blob/5144d6ce45242e11d16bebbcc80778ea0e9ae0ed/src/views/self/view_self.cpp#L63

**Comment by wdymUsername** [comment]
Dance mode activates player dancing(nightclub) anywhere.

**Comment by epicmusicpt** [comment]
oh im sorry but when i check dance mode on my model doest´nt dance! i tryed i few times in the past too it never worked with me, or is there any key to start dancing after check the box on?

**Comment by wdymUsername** [comment]
It is the exact same dancing like in nightclubs. Either press or hold E to start dancing iirc. Only applies to player.

**Comment by epicmusicpt** [comment]
> It is the exact same dancing like in nightclubs. Either press or hold E to start dancing iirc. Only applies to player.

lol man all this time i never hold E! thank you so much for your help!

**Comment by epicmusicpt** [comment]
now is it possible to aplly to spawned peds or peds already nearby? like riot mode. thanks
