### ISSUE TITLE
[Bug]: Weapons In Vehicle

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1163]
### Describe the bug

Whenever you try to use a Sticky bomb or an grenade in a vehicle when you aim you get stuck in the vehicle

### Steps To Reproduce

1. go into a vehicle
2. select a grenade or a sticky bomb
3. aim and change to a pistol 

### Expected Behavior

To throw a sticky bomb and stop aiming

### Store

Steam

### Additional context

You cannot exit out of the vehicle

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
I have been able to recreate. Besides not being able to exit the vehicle, when you do so with some other feature, a lot of controls seem to be simply disabled.

**Comment by rrAsus** [comment]
So Is there a fix to this?

**Comment by Harmless05** [comment]
I happened to get the same/similar glitch. I don't know how, but the current way to "fix this" is to kill yourself (suicide) with the menu.

**Comment by Aure7138** [comment]
maybe need to switch to hooks, need to do some filter or reimplement, will look at it in a few days
