### ISSUE TITLE
[Bug]: Game Randomly Freezing

### ISSUE THREAD

**Issue by xenical1212** [Yimura/YimMenu#1165]
### Describe the bug

When i play gta o it will randomly freeze with this menu injected but if i play without the menu the game doesnt randomly freeze.

### Steps To Reproduce

just inject the menu and play gta for a bit

### Expected Behavior

no freezing

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by rrAsus** [comment]
after how many hours does it appear?

**Comment by xenical1212** [comment]
i dont really check the time but probably 1 or 2 hours

**Comment by Yimura** [comment]
Duplicate of #1073
