### ISSUE TITLE
Game freezes and crashes, has been ongoing for many versions

### ISSUE THREAD

**Issue by steveosten2** [Yimura/YimMenu#1166]
### Describe the bug

Freeze then either crash or just no response

### Steps To Reproduce

Play the game with yim injected

### Expected Behavior

not to crash

### Screenshots and/or Logs

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/11128485/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by epicmusicpt** [comment]
check this: https://github.com/YimMenu/YimMenu/issues/1073

**Comment by Yimura** [comment]
Duplicate of #1073
