### ISSUE TITLE
[Bug]: Trojan:Script/Wacatac.B!ml false positive?

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1167]
### Describe the bug

Whenever I go to launch Yim, the DLL keeps getting deleted by Windows Security.

### Steps To Reproduce

1. Turn on Windows Security
2. Get the latest DLL 
3. Observe deletion

### Expected Behavior

Not to be a false positive of a trojan.

### Screenshots and/or Logs

![2023-04-01 08_24_14-Windows Security](https://user-images.githubusercontent.com/80224521/229288496-4935dade-75c3-4458-a048-71376e170da7.png)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Nothing we can do about it, it's because of certain features we use in YimMenu triggering this alert.

Namely GetAsyncKeyState I would like to get rid of completely.

**Comment by Rxann** [comment]
Alright, thank you

**Comment by Yimura** [comment]
Try adding an exception on the folder in which you put the YimMenu.dll file.

**Comment by Rxann** [comment]
alright
