### ISSUE TITLE
[Request]: Summon Vehicle

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1168]
### Problem

Not a problem, just a feature

### Solution

A feature that operates similar to Tesla's summon feature. You press a button and your car drives to you.

### Reason

This would be very fun to have

**Comment by Tayipc38** [comment]
I believe this request could be combined with #1114 . Currently I am working on the other issue and might just try and create something a little more advanced then what you have described.

**Comment by Rxann** [comment]
Okay, thanks
