### ISSUE TITLE
[Request]: Walk on air

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1171]
### Problem

No, it's not related to a problem. I'm just trying to suggest features people might like to see.

### Solution

A toggle, when enabled you can walk in the air. Similar to noclip in a way but you don't go through walls, and you are also slower since walking. Possible up and down buttons could be SHIFT and CTRL (or SPACEBAR for up and CTRL for down)

### Reason

It's cool 😎 
Could also be useful when climbing things (maybe)

**Comment by Tayipc38** [comment]
What if noclip had some adjustable variables that would enable you to change its speed and enable its collisions.

**Comment by 0xEmiil** [comment]
I got a "levitation" code its what your looking for?

**Comment by TheGreenBandit** [comment]
probably could set ped config flag to walking as true while enabled
