### ISSUE TITLE
[Request]: Teleport forward/backwards up/down + [amount units]

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1172]
### Problem

No, it's not related to a problem. I'm just trying to suggest features people might like to see.

### Solution

Make a new section/tab under Self -> Teleport called Movement.
Under it make a button for the forwards/backwards and up/down teleports with an integer box (maybe the int could also be configured with arrows for increasing/lowering the distance)

Or it could be used in the YimMenu Command Executor
Possible names for the teleports:
1. vclip (int) - vertically teleport up/down
2. hclip (int) - horizontally teleport forwards/backwards
3. other names could be vtp/htp for vertical/horizontal teleport

### Reason

Useful when you want to teleport in a certain direction with the right amount of distance.

**Comment by TheGreenBandit** [comment]
to expand off of this you could probably just make a coordinate editor 

[682.3425]x allow them to change these
[235498.235423]y
[100.25]z

**Comment by Tayipc38** [comment]
This shouldn't be too difficult.
