### ISSUE TITLE
[Bug]: Glitched Spawn Ped Menu

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1174]
### Describe the bug

The Spawn Ped menu seems to have ped names in the category to spawn them.

### Steps To Reproduce

1. Load the menu
2. Go to Spawn Ped
3. Open the dropdown where "Online Player" is

### Expected Behavior

Maybe be more organized?

### Store

Steam

### Additional context

bug or feature?

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by binded-zz** [comment]
https://github.com/YimMenu/YimMenu/commit/ea33c09e8c41e68ee22a395c58c90cede17aea9e#commitcomment-107108636

**Comment by Tayipc38** [comment]
Did this break recently?

**Comment by xiaoxiao921** [comment]
> Did this break recently?

#1156 @Aure7138

**Comment by Rxann** [comment]
> Did this break recently?

Yes

**Comment by Aure7138** [comment]
what's wrong with online player?
![image](https://cdn.discordapp.com/attachments/1035859722043150346/1092083706119860244/image.png)

**Comment by Rxann** [comment]
@Aure7138 press the ped type

**Comment by Aure7138** [comment]
> press the ped type

yes it works fine for me, please use latest build and re-cache

**Comment by Rxann** [comment]
> > press the ped type
> 
> yes it works fine for me, please use latest build and re-cache

How do I recache? I am on the latest build

**Comment by Aure7138** [comment]
> How do I recache? I am on the latest build

delete folder %appdata%\BigBaseV2\cache

**Comment by Rxann** [comment]
> > How do I recache? I am on the latest build
> 
> delete folder %appdata%\BigBaseV2\cache

Alright thanks, I will test to see if it fixes this

**Comment by Rxann** [comment]
@Aure7138 This seems to fix the UI part, but I noticed some peds aren't spawn able also.

**Comment by binded-zz** [comment]
deleting the cache worked
