### ISSUE TITLE
[Bug]: Hotkey for Toggle Freecam and Fastrun don't work

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1178]
### Describe the bug

Doesn't recognize the hotkey to activate Noclip.

### Steps To Reproduce

1. Set hotkey for Toggle Noclip
2. Press the key
3. Noclip doesn't get activated

### Expected Behavior

Hotkey should activate Noclip

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Additional context

I'm not sure but could this be due to a conflict between the orbital drone feature as that utilizes noclip. I don't know if it worked fine before it was introduced so this is just a random guess.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Try a different key not all keys are supported.

**Comment by howdoiusekeyboard** [comment]
Okay that helped, but I think there is issue with Freecam and fast run hotkey (the naming is not consistent as well as its super run in the gui as opposed to fast run in the hotkey and command executor section)
