### ISSUE TITLE
[Bug]: Game crash/freeze in ped preview

### ISSUE THREAD

**Issue by epicmusicpt** [Yimura/YimMenu#1182]
### Describe the bug

game crashes/freezes when preview the "slod" peds in spawn ped menu.

### Steps To Reproduce

go to world ,spawn ped ,preview the last peds "slod human" etc...

### Expected Behavior

not to freeze/crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

other peds dont crash,only the last 3 or 4 named "slod"

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
menu protect you from players crashing you with these models, but not local spawns

**Comment by Yimura** [comment]
I would suggest you to not preview it, YimMenu blocks the slod model when someone else sends it to you but not when you spawn it locally.

**Comment by epicmusicpt** [comment]
ok thanks,should this be closed then?

**Comment by xiaoxiao921** [comment]
Imo this should still be fixed by YimMenu, a simple mistake from the user shouldnt make their game crash

**Comment by wdymUsername** [comment]
> Imo this should still be fixed by YimMenu, a simple mistake from the user shouldnt make their game crash

It is not even mistake by user in this case to be honest. Majority of people will have no idea what so ever about that specific model(s) being able to crash the game.
