### ISSUE TITLE
[Bug]: Armored vehicles lose armor with menu injected

### ISSUE THREAD

**Issue by metta117** [Yimura/YimMenu#1192]
### Describe the bug

When using yimmenu the ocelot virtue doesnt mimic the bricade 6x6 stats of the ammount of missles it can take before it is destroyed. Ive tried this with a new clone of yimmenu on a seperate computer and the same issue persists 

### Steps To Reproduce

To reproduce simply hook yimmenu into gta and go into online. When online call the machanic for your personal vehicle or spawn one using the menu provided. When using armor plating it should be able to take a explosion without being destroyed. Simply throw a sticky on your ocelot virtue and get into, when in you can detonate your stickies and you should die instantly. 

When done spawn thrle same ocelot virtue and unload yimmenu by pushing 'unload' on the yimmenus status gui. Throw a couple stickies on it and get inside and you are now able to detonate the stickies and survive to tell the tale.

### Expected Behavior

Car doesnt go boom

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [ ] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
Please send your settings

**Comment by metta117** [comment]
where  settings located

**Comment by TheGreenBandit** [comment]
appdata->bigbasev2->settings.json

**Comment by metta117** [comment]
`{
    "clone_pv": {
        "clone_plate": false,
        "plate": "",
        "preview_vehicle": false,
        "spawn_clone": false,
        "spawn_inside": false,
        "spawn_maxed": false
    },
    "context_menu": {
        "allowed_entity_types": 15,
        "bounding_box_color": 4278255360,
        "bounding_box_enabled": true,
        "enabled": false,
        "selected_option_color": 4278255360
    },
    "debug": {
        "logs": {
            "metric_logs": false,
            "packet_logs": false,
            "script_event": {
                "filter_player": true,
                "logs": false,
                "player_id": -1
            },
            "script_hook_logs": false
        }
    },
    "esp": {
        "armor": true,
        "box": true,
        "box_render_distance": [
            0.0,
            150.0
        ],
        "change_esp_color_from_dist": false,
        "default_color": 4285713522,
        "distance": true,
        "distance_threshold": [
            100.0,
            200.0
        ],
        "enabled": true,
        "enemy_color": 4281479904,
        "enemy_near_color": 4283794943,
        "friend_color": 4293244509,
        "global_render_distance": [
            0.0,
            600.0
        ],
        "god": true,
        "health": true,
        "hide_self": true,
        "name": true,
        "scale_armor_from_dist": false,
        "scale_health_from_dist": false,
        "tracer": true,
        "tracer_draw_position": [
            0.5,
            1.0
        ],
        "tracer_render_distance": [
            200.0,
            600.0
        ]
    },
    "notifications": {
        "gta_thread_kill": {
            "log": false,
            "notify": false
        },
        "gta_thread_start": {
            "log": false,
            "notify": false
        },
        "invalid_sync": {
            "log": false,
            "notify": false
        },
        "mismatch_sync_type": {
            "log": false,
            "notify": false
        },
        "network_player_mgr_init": {
            "log": false,
            "notify": false
        },
        "network_player_mgr_shutdown": {
            "log": false,
            "notify": false
        },
        "out_of_allowed_range_sync_type": {
            "log": false,
            "notify": false
        },
        "player_join": {
            "above_map": true,
            "log": false,
            "notify": false
        },
        "player_leave": {
            "log": false,
            "notify": false
        },
        "send_net_info_to_lobby": {
            "log": false,
            "notify": false
        },
        "transaction_rate_limit": {
            "log": false,
            "notify": false
        }
    },
    "player": {
        "character_slot": 1,
        "spectating": false
    },
    "protections": {
        "desync_kick": false,
        "lessen_breakups": false,
        "receive_pickup": false,
        "rid_join": false,
        "script_events": {
            "bounty": true,
            "ceo_money": true,
            "clear_wanted_level": true,
            "fake_deposit": true,
            "force_mission": true,
            "force_teleport": true,
            "give_collectible": true,
            "gta_banner": false,
            "mc_teleport": true,
            "personal_vehicle_destroyed": true,
            "remote_off_radar": true,
            "rotate_cam": true,
            "send_sms": true,
            "send_to_cutscene": true,
            "send_to_location": true,
            "sound_spam": true,
            "spectate": true,
            "start_activity": true,
            "teleport_to_warehouse": true,
            "vehicle_kick": true
        }
    },
    "reactions": {
        "bounty": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "breakup_others": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block": true,
            "block_joins": false,
            "karma": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "ceo_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "ceo_money": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "clear_ped_tasks": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "clear_wanted_level": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "crash": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "destroy_personal_vehicle": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "end_session_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "fake_deposit": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "force_mission": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "force_teleport": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "gamer_instruction_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "give_collectible": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "gta_banner": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "kick_from_interior": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "kick_vote": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "lost_connection_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "lost_connection_kick_others": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block": true,
            "block_joins": false,
            "karma": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "mc_teleport": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "modder_detection": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "network_bail": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "null_function_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "personal_vehicle_destroyed": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "remote_off_radar": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "remote_ragdoll": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "remote_wanted_level": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "remote_wanted_level_others": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block": true,
            "block_joins": false,
            "karma": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "report": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "report_cash_spawn": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "request_control_event": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "rotate_cam": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "send_to_cutscene": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "send_to_location": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "sound_spam": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "spectate_notification": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "start_activity": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "start_script": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "teleport_to_warehouse": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "transaction_error": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "trigger_business_raid": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "tse_freeze": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "tse_sender_mismatch": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "turn_into_beast": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        },
        "vehicle_kick": {
            "add_to_player_db": false,
            "announce_in_chat": false,
            "block_joins": false,
            "kick": false,
            "log": true,
            "notify": true
        }
    },
    "self": {
        "auto_tp": false,
        "beast_jump": false,
        "clean_player": false,
        "fast_respawn": false,
        "force_wanted_level": false,
        "free_cam": false,
        "god_mode": false,
        "healthregen": false,
        "healthregenrate": 1.0,
        "hud": {
            "a": 0,
            "b": 0,
            "force_show_hud": false,
            "force_show_hud_element": false,
            "g": 0,
            "hcolor": 0,
            "hide_ammo": false,
            "hide_radar": false,
            "hud_components_states": [
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "hudcolor": false,
            "index": 0,
            "mhcolor": false,
            "mtcolor": false,
            "r": 0,
            "selected_hud_component": 1,
            "shcolor": false,
            "tcolor": 0
        },
        "invisibility": false,
        "local_visibility": true,
        "mobile_radio": false,
        "never_wanted": false,
        "no_collision": false,
        "no_ragdoll": false,
        "no_water_collision": false,
        "noclip": false,
        "off_radar": false,
        "part_water": false,
        "proof_bullet": false,
        "proof_collision": false,
        "proof_drown": false,
        "proof_explosion": false,
        "proof_fire": false,
        "proof_mask": 0,
        "proof_melee": false,
        "proof_steam": false,
        "proof_water": false,
        "ptfx_effects": {
            "show": false,
            "size": 0.20000000298023224
        },
        "super_jump": false,
        "super_run": false,
        "superman": false,
        "unlimited_oxygen": false,
        "wanted_level": 0
    },
    "session": {
        "advertise_menu": false,
        "anonymous_bounty": true,
        "block_ceo_money": false,
        "block_ceo_raids": false,
        "block_jobs": false,
        "block_muggers": false,
        "chat_command_default_access_level": "friendly",
        "chat_commands": false,
        "chat_force_clean": false,
        "custom_time": {
            "hour": 0,
            "minute": 0,
            "second": 0
        },
        "damage_karma": false,
        "decloak_players": false,
        "disable_peds": false,
        "disable_traffic": false,
        "explosion_karma": false,
        "force_script_host": false,
        "force_session_host": false,
        "force_thunder": false,
        "is_team": false,
        "join_in_sctv_slots": false,
        "kick_chat_spammers": false,
        "kick_host_when_forcing_host": false,
        "local_weather": 0,
        "log_chat_messages": false,
        "log_text_messages": false,
        "name_spoof_enabled": false,
        "override_time": false,
        "override_weather": false,
        "player_magnet_count": 32,
        "player_magnet_enabled": false,
        "randomize_ceo_colors": false,
        "send_to_apartment_idx": 1,
        "send_to_warehouse_idx": 1,
        "show_cheating_message": false,
        "spoofed_name": ""
    },
    "session_browser": {
        "language_filter": 0,
        "language_filter_enabled": false,
        "player_count_filter_enabled": false,
        "player_count_filter_maximum": 32,
        "player_count_filter_minimum": 0,
        "pool_filter": 0,
        "pool_filter_enabled": false,
        "region_filter": 0,
        "region_filter_enabled": true,
        "replace_game_matchmaking": false,
        "sort_direction": 0,
        "sort_method": 0
    },
    "settings": {
        "dev_dlc": false,
        "hotkeys": {
            "beastjump": 0,
            "bringvehicle": 107,
            "cmd_excecutor": 85,
            "editing_menu_toggle": false,
            "fast_quit": 0,
            "fill_ammo": 106,
            "fill_inventory": 111,
            "freecam": 0,
            "heal": 110,
            "invis": 119,
            "invisveh": 0,
            "localinvisveh": 0,
            "menu_toggle": 116,
            "noclip": 109,
            "repairpv": 107,
            "skip_cutscene": 110,
            "superjump": 0,
            "superrun": 0,
            "teleport_objective": 118,
            "teleport_waypoint": 117
        }
    },
    "spawn_vehicle": {
        "plate": "",
        "preview_vehicle": false,
        "spawn_inside": false,
        "spawn_maxed": false
    },
    "spoofing": {
        "crew_tag": "",
        "hide_from_player_list": false,
        "rockstar_crew": false,
        "session_language": 0,
        "session_player_count": 25,
        "session_region_type": 0,
        "spoof_cheater": false,
        "spoof_crew_data": false,
        "spoof_hide_god": true,
        "spoof_hide_spectate": true,
        "spoof_session_language": false,
        "spoof_session_player_count": false,
        "spoof_session_region_type": false,
        "square_crew_tag": false,
        "voice_chat_audio": false
    },
    "stat_editor": {
        "packed_stat": {
            "bool_read": false,
            "bool_text": "",
            "bool_value": "",
            "int_read": false,
            "int_text": "",
            "int_value": "",
            "radio_button_index": 0
        },
        "stat": {
            "bool_read": false,
            "bool_text": "",
            "bool_value": "",
            "date_read": false,
            "date_text": "",
            "date_value": "",
            "float_read": false,
            "float_text": "",
            "float_value": "",
            "increment_loop_write": false,
            "increment_text": "",
            "increment_value": "",
            "int_read": false,
            "int_text": "",
            "int_value": "",
            "label_text": "",
            "label_value": "",
            "radio_button_index": 0,
            "string_read": false,
            "string_text": "",
            "string_value": "",
            "user_id_read": false,
            "user_id_text": "",
            "user_id_value": ""
        }
    },
    "tunables": {
        "disable_phone": false,
        "no_idle_kick": false
    },
    "ugc": {
        "infinite_model_memory": false
    },
    "vehicle": {
        "auto_drive_destination": "stopped",
        "auto_drive_speed": 1.0,
        "auto_drive_style": "law_abiding",
        "auto_turn_signals": false,
        "block_homing": true,
        "boost_behavior": "default",
        "change_engine_state_immediately": false,
        "disable_engine_auto_start": false,
        "drive_on_water": false,
        "fly": {
            "dont_stop": false,
            "enabled": false,
            "no_collision": false,
            "speed": 100.0,
            "stop_on_exit": false
        },
        "god_mode": false,
        "horn_boost": false,
        "instant_brake": false,
        "keep_on_ground": false,
        "keep_vehicle_repaired": false,
        "localped_visibility": true,
        "localveh_visibility": false,
        "no_collision": false,
        "no_water_collision": false,
        "proof_bullet": false,
        "proof_collision": false,
        "proof_explosion": false,
        "proof_fire": false,
        "proof_mask": 0,
        "proof_melee": false,
        "proof_steam": false,
        "proof_water": false,
        "rainbow_paint": {
            "neon": false,
            "primary": false,
            "secondary": false,
            "smoke": false,
            "speed": 0,
            "type": "off"
        },
        "seatbelt": false,
        "speed_unit": "miph",
        "speedo_meter": {
            "enabled": false,
            "left_side": false,
            "x": 0.8999999761581421,
            "y": 0.7200000286102295
        },
        "turn_signals": false,
        "unlimited_weapons": false,
        "vehicle_jump": false,
        "vehinvisibility": false
    },
    "weapons": {
        "aimbot": {
            "enable": false,
            "fov": 90.0,
            "selected_bone": 31086,
            "smoothing": true,
            "smoothing_speed": 2.0
        },
        "ammo_special": {
            "explosion_tag": -1,
            "toggle": false,
            "type": 0
        },
        "custom_weapon": "none",
        "force_crosshairs": false,
        "gravity_gun": {
            "launch_on_release": false
        },
        "increase_damage": false,
        "increased_c4_limit": false,
        "increased_damage": 1.0,
        "increased_flare_limit": false,
        "infinite_ammo": false,
        "infinite_mag": false,
        "infinite_range": false,
        "interior_weapon": false,
        "no_recoil": false,
        "no_spread": false,
        "rapid_fire": false,
        "triggerbot": false,
        "vehicle_gun_model": "bus"
    },
    "window": {
        "color": 3357612055,
        "gui_scale": 1.0,
        "ingame_overlay": {
            "opened": true,
            "show_fps": true,
            "show_game_versions": true,
            "show_players": true,
            "show_replay_interface": true,
            "show_time": true,
            "show_with_menu_opened": false
        },
        "switched_view": true
    },
    "world": {
        "blackhole": {
            "alpha": 150,
            "color": [
                1.0,
                1.0,
                1.0
            ],
            "include_peds": false,
            "include_vehicles": false
        },
        "custom_time": {
            "hour": 0,
            "local_weather": 0,
            "minute": 0,
            "second": 0
        },
        "model_swapper": {
            "models": []
        },
        "nearby": {
            "combative": false,
            "high_alert": false,
            "ignore": false,
            "ped_rain": false,
            "ped_rush": false,
            "veh_rain": false
        },
        "orbital_drone": {
            "detect_player": false,
            "nav_ovverride_fast": 3.0,
            "nav_ovverride_slow": 0.25
        },
        "spawn_ped": {
            "preview_ped": false,
            "spawn_as_attacker": false,
            "spawn_invincible": false,
            "spawn_invisible": false
        },
        "water": {
            "part_water": false
        }
    }
}`

**Comment by LexyDrow44WasTaken** [comment]
anything new? any fix in sight?

**Comment by ActualPotato** [comment]
Still not fixed, such a frustrating bug, literally makes the imani armor useless.
