### ISSUE TITLE
[Bug]: Context menu executes regardless of main UI

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#1193]
### Describe the bug

Action button for the context menu still operates even though the main UI is activated. Resulting in unwanted behaviour.

### Steps To Reproduce

1.Activate context menu
2.Open main UI
3.Click anything

### Expected Behavior

The Context menu should refrain from executing functions when the main UI is on.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Sys0xdbg** [comment]
hey not related and sorry for this but can you dm loko#2018

**Comment by Yimura** [comment]
> hey not related and sorry for this but can you dm loko#2018

To who is this message aimed?

**Comment by Sys0xdbg** [comment]
apologies yim but aimed at [DayibBaba](https://github.com/DayibBaba)

**Comment by Tayipc38** [comment]
> apologies yim but aimed at [DayibBaba](https://github.com/DayibBaba)

I dont think I understand the implication.

**Comment by Sys0xdbg** [comment]
> > apologies yim but aimed at [DayibBaba](https://github.com/DayibBaba)
> 
> I dont think I understand the implication.
I meant can you dm
loko#2018

**Comment by Sys0xdbg** [comment]
And this is becoming spam so I won't reply anymore lol.
