### ISSUE TITLE
[Bug]: Github Release shows inaccurate date.

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1194]
### Describe the bug

The Github Release on the Code Tab, shows that the latest release is 2 weeks old, but in reality, it is 1 or 2 hours old as of right now.

### Steps To Reproduce

1. Go to main page on the repo, where the code is accessible 
2. Observe incorrect date on the "Release" section

### Expected Behavior

Have the time or date of the latest release.

### Screenshots and/or Logs

![1](https://user-images.githubusercontent.com/80224521/230141809-9c64309c-a3ca-4c87-bae8-686ecf6e8bf9.png)

=======================================================================

![2](https://user-images.githubusercontent.com/80224521/230141824-1e0e58ef-cbcc-4097-b11b-3dcd4d094528.png)

### Store

Other (please mention in "Additional context")

### Additional context

This is a github related issue, so the store was not provided.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This is intended behaviour to prevent issues with how previously nightly release didn’t release always.

You need to check the date of the file instead.

**Comment by Rxann** [comment]
Alright, thank you
