### ISSUE TITLE
[Bug]: GAME_CACHE_ON_INIT translation data not shown

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1195]
### Describe the bug

When prompted for a cache rebuilt, the translation data for game_cache_on_init. it simply shows GAME_CACHE_ON_INIT instead of  Update Cache on Init.

### Steps To Reproduce

1. Delete cache folder
2. Inject YimMenu
3. Observe the GAME_CACHE_ON_INIT being displayed as a cache rebuild option.

### Expected Behavior

Give the accurate translation data.

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Have you tried removing your translations?

**Comment by Rxann** [comment]
> Have you tried removing your translations?

I don't know how to do this?

**Comment by Yimura** [comment]
I'm currently working on adding a button to force update the translations in PR #1200

**Comment by Rxann** [comment]
Alright, I just deleted the translation folder and let it regenerate on its own. I will see if this fixes the problem
