### ISSUE TITLE
Crash on inject possibly caused by having handling window open when last unloaded

### ISSUE THREAD

**Issue by GibsonHF** [Yimura/YimMenu#12]
Game seems to crash if you exit while having handling menu open then re injecting. need to set handling menu to false on startup or just check if in vehicle before displaying

**Comment by Yimura** [comment]
Any logs available when from when it happened, I know that logs can be empty sometimes just mention it. And do you know what you were doing at that moment does it occur frequently? Were you in a vehicle or on foot?

The menu should check if the data is readable and if it isn't it should show a message.
https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/gui/window/window_handling.cpp#L14-L19

I will experiment with what you told me and see if I can improve this part.

**Comment by GibsonHF** [comment]
I didnt get the log at the time but if unloading the menu it crashes once doing that and if you were in handling menu before doing that and join back while being on foot and open the menu you crash. if you get in a vehicle then open menu you can close out of handling menu and prevent the crash

**Comment by Yimura** [comment]
I was unable to crash myself using the latest version of my menu, I've improved the detection of your ped being in a vehicle but I'm unsure if this fixes your issue.

Checkout https://github.com/Yimura/YimMenu/commit/e557571314a1db35d22a9969736f49cbdd85a2f0 or just the current `master` and see if it happens again.

**Comment by Yimura** [comment]
I will close this issue now, if there are any problems remaining related to this issue you're free to reopen it.

**Comment by GibsonHF** [comment]
https://gyazo.com/86a1df312c5736351c343c052d73053f finally had a chance to replicate it, could be due to debug mode im not sure. meant to message you on discord but Yimura#6969 invalid

**Comment by Yimura** [comment]
Are you running a Debug build of YimMenu? Oh that's gotta hurt... (it's really slow)
But now it makes a lot of sense, I'll check and see if there's somewhere a call to create an ImGui window but the window is never closed afterwards.

Try using a Release build, could very well be that that will make it so this bug never occurs, the Debug build is made to forcefully crash when something happens that's not supposed to happen.

**Comment by Yimura** [comment]
Yes, just as expected there's no ImGui::End call inside this if statement.

https://github.com/Yimura/YimMenu/blob/9821a28e10e99dff1ab1ec109a49ec8390053e29/BigBaseV2/src/gui/window/window_handling.cpp#L14-L19

**Comment by GibsonHF** [comment]
I've just always naturally used debug builds i figured it couldve caused the problem i may just switch over to release and add the end call in the statement. my latest pr adds a player aimbot too but it was just thrown out of an old menu i had long ago  so it may bug out distance check etc

**Comment by Yimura** [comment]
Ye debug builds are SLOW and ye anything small that goes wrong takes everything else down with it.

Anyways I'm not too keen into adding stuff like aimbots, I prefer keeping it to friendly and cool new things to experiment with.
Aimbots are cool to program but then actually using it is just such a "no no" for me. So try make PR's that improve the quality of this menu, add cool new features and keep the quality of code high!

Take for example @karifeld he's doing a great job at following the same coding style as me, improving the menu by making small additions to it. Can't wait for him to drop a bom of a feature. Not forgetting to mention his commits styled similarly like mine!
