### ISSUE TITLE
Game crash when trying to stream after unload

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#120]
**Describe the bug**
GTA V crashes after you try to stream game on discord after you unload the menu

**To Reproduce**
1. Load yimmenu
2. Unload menu
3. Go to discord and join a vc
4. Stream game

**Expected behavior**
Your game will crash

**Logs**

I can't find any logs

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
Game won't crash when u have the menu loaded, its only after the unload
I confirmed the crash from another person.
I have the epic games version of the game

**Comment by howdoiusekeyboard** [comment]
Um I didn't assign anyone

**Comment by Yimura** [comment]
This is an issue with how the rendering works and how Discord grabs the frame buffer from the game.

The solution this is to screen share and never share your game dlrectly.
