### ISSUE TITLE
[Bug]: looped dumps log log files

### ISSUE THREAD

**Issue by binded-zz** [Yimura/YimMenu#1205]
### Describe the bug

maybe a way for the menu to clean up the sometimes very large cout.out logs that happen from repeated dumps that dont crash the game i have found some as large as a gig in size most of the time 100 500 megs in size

### Steps To Reproduce

play game people try to crash you but you dont crash and you get repeat after repeat of the same dump info over and over  result in huge log files

### Expected Behavior

idk some sorta way to purge from the menu i do just goto the folder and delete them my self 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by binded-zz** [comment]
that should be looped dumps large log files

**Comment by Rxann** [comment]
> This is the exception handler recovering from exceptions. Not an issue, however i feel there should be a toggle for the exception handler logging as most users wont need it.

I'm currently implementing the feature @TheGreenBandit mentioned

**Comment by xiaoxiao921** [comment]
Should be fixed by https://github.com/YimMenu/YimMenu/pull/1244 no?

**Comment by Yimura** [comment]
Yup you're right, should be fixed now.
