### ISSUE TITLE
Vehicle cannot be modified spam

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#121]
**Describe the bug**
The vehicle cannot be modified notification spam after trying to use the LS Customs service in mod

**To Reproduce**
1. Get into a vehicle that cannot be modified
2. Start LS Customs

**Expected behavior**
The vehicle cannot be modified notification spam

**Screenshots**
Add screenshots here,  you may remove this section if there are no screenshots applicable.

**Logs**

https://user-images.githubusercontent.com/90883505/159156543-4c1049fb-9673-4f62-826c-d92f7121247f.mp4

```
No logs
```

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
I tried it with the bunker delivery vehicle - Phantom Wedge to be specific

**Comment by Yimura** [comment]
Probably an issue with the `carmod_shop` script running or not having shut down correctly.

You can probably fix it by starting the LS Customs again with a vehicle that can be modified.

**Comment by Yimura** [comment]
Unable to reproduce, and not really an issue, will close the issue.
