### ISSUE TITLE
[Bug]: Error While Building

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1212]
### Describe the bug

'C:/Users/k/YimMenu/src/views/settings/view_outfit_editor.cpp', needed by 'CMakeFiles/YimMenu.dir/src/views/settings/view_outfit_editor.cpp.obj', missing and no known rule to make it

### Steps To Reproduce

git pull probably

### Expected Behavior

not to make it appear

### Screenshots and/or Logs

```
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Try CTRL + S in CMakeLists.txt and try building it after that has finished.

**Comment by rrAsus** [comment]
Thank you it worked
