### ISSUE TITLE
[Bug]: Cannot switch tabs in vehicle controller

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1213]
### Describe the bug

In one of the recent commits, theres a new bug that makes u unable to switch tabs when u enable the vehicle controller

### Steps To Reproduce

Open vehicle controller
click on another tab

### Expected Behavior

It should switch to that tab

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
I have been unable to recreate the bug. I assume you are talking about the tabs such as 'Doors', 'Lights, 'Misc' and such. It sounds like a ImGui issue. If UI elements harbor the same ID's such bugs do appear yet I am sure that is not the case here. The only thing I could not replicate is the game version u have tested this on but the scope of the bug makes me believe that it shouldn't make a difference. Could you maybe provide some more steps to recreating the bug? Like a specific vehicle or when you activate the feature?

**Comment by howdoiusekeyboard** [comment]
Game version is the latest: 2845. Bug is random it happened two times as of yet, I don't think it has to with a specific vehicle.. I had it with 10f widebody and annis 300r

https://user-images.githubusercontent.com/90883505/230702494-72a99917-65af-4628-8a5f-8f4e753797e5.mp4

**Comment by iwanttodo1t** [comment]
same

**Comment by Tayipc38** [comment]
I have confirmed the bug exists in the latest version of the menu. It appears to be a bug related to the translations or other improvements that have been added. Ill leave this to @Yimura.
