### ISSUE TITLE
[Request]: Remove Clothing Restrictions ex. Duffel Bag

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1218]
### Problem

Let's say you want to buy a gun or clothes with a duffel bag well you can't

### Solution

So Make a checkbox either to disable the restrictions in outfit editor or self

### Reason

Cause then you don't have to switch outfits every now and then.

**Comment by Yimura** [comment]
I'm not sure but heard someone say you can just edit your outfit with YimMenu's editor and then save it when you're in a wardrobe at one of your safe houses.

**Comment by rrAsus** [comment]
> I'm not sure but heard someone say you can just edit your outfit with YimMenu's editor and then save it when you're in a wardrobe at one of your safe houses.

when in a wardrobe in a safehouse when you edit the duffel bag id from 0 to the duffels bag id whouldn't that kick you out the wardrobe?

**Comment by Yimura** [comment]
> when in a wardrobe in a safehouse when you edit the duffel bag id from 0 to the duffels bag id whouldn't that kick you out the wardrobe?

Can't you edit your clothes outside of a wardrobe then go intk the wardrobe and save it?

**Comment by rrAsus** [comment]
> > when in a wardrobe in a safehouse when you edit the duffel bag id from 0 to the duffels bag id whouldn't that kick you out the wardrobe?
> 
> Can't you edit your clothes outside of a wardrobe then go intk the wardrobe and save it?



Yes , but with the duffel bag no.

**Comment by rrAsus** [comment]
@Yimura From What i've seen , While in a Gun Shop with the duffel bag you can still buy guns , armor. But in a Clothing shop you cannot buy clothes nor go into the wardrobe in the Clothing shop.

**Comment by rrAsus** [comment]
and on top of the gun shop part when you try to buy a weapon it gives you a wanted level?

**Comment by rrAsus** [comment]
i came to a sort of a consclusion that this may be a stupid thread cause probaby the only thing that is preventing you from buying clothing is the duffel bag.
