### ISSUE TITLE
A way to save favorite Vehicles

### ISSUE THREAD

**Issue by bugmaschine** [Yimura/YimMenu#122]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the Spawn tab a Favorites menu where you could spawn vehicles.

**Provide Reasoning**
It would make life easier if you wanted to spawn the same vehicle every time you change the lobby or go into story mode

**Comment by Yimura** [comment]
Sure we'll probably take some inspiration from spankers / @gir489returns source code: https://bitbucket.org/gir489/bigbasev2-fix/branch/persist_car

**Comment by Yimura** [comment]
Added in #366.
