### ISSUE TITLE
[Bug]: Request network control effectiveness

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#1220]
### Describe the bug

Currently, the request control method is a bit lackluster when it comes to effectively taking control of entities (especially player vehicles). Sometimes I have to click features several times before the control is transferred. I remember taking control wasn't this difficult.

### Steps To Reproduce

1.Use yimmenu
2.Choose a victim in a vehicle
3.Apply a feature that requires entity control
4.Observe the message "Taking control failed"

### Expected Behavior

Although the control wasn't always immediately taken, to my recollection it wasn't this difficult either. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by binded-zz** [comment]
i have noticed this as well like burst tired or kill engine most of the time i have to hit it 2 or 3 times 
i just figure its blocked  by some people

**Comment by iswaxan** [comment]
happens to me too, rly annoying
