### ISSUE TITLE
[Bug]: Vehicle Controller UI Bug

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1223]
### Describe the bug

The Vehicle Controller UI seems to not be able to switch tabs.

### Steps To Reproduce

1. Open Vehicle Controller via hotkey
2. Try to switch to the lights tab or settings.

### Expected Behavior

It should switch tabs

### Screenshots and/or Logs

https://user-images.githubusercontent.com/80224521/231299347-40902a95-00ff-4704-b227-917a8e9c62be.mp4

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This has been fixed with #1219, wait for the next release of YimMenu and check old issues before creating a new one.

**Comment by Rxann** [comment]
Okay thanks
