### ISSUE TITLE
[Bug]: Custom Weapon fires even when weapon isn't out

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1224]
### Describe the bug

When using a custom weapon, like the vehicle one, the buses for example will still spawn when you don't have a gun out.

### Steps To Reproduce

1. Enable custom weapon (I use the vehicle one and launch buses)
2. Put weapon away
3. Interact with something that uses the same key that you would to fire a gun.

### Expected Behavior

The vehicles only spawn when your weapon is out.

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
The feature will not turn off by putting your gun away, please turn it off in the gui next time as that will solve your issue:

**Comment by Tayipc38** [comment]
> The feature will not turn off by putting your gun away, please turn it off in the gui next time as that will solve your issue:

Or we could simply check whether a gun is equipped. Seems simple things as these just don't make it to the radar of contributers. I could probably fix like 10 issues with a single PR but I like working on more robust features.

**Comment by Rxann** [comment]
I will work on it and open a pr if it works!
