### ISSUE TITLE
[Request]: make persist car option compatible with xml files

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1232]
### Problem

i wanna put custom cars like a mega bus and shi like that, is it detected or not ? can it work ?
its basically just for attachements like a ufo and things like that

### Solution

e

### Reason

well its in the "problem" case

### Additional context

i have been able to save some custom vehicles (yoat with festval bus on a blimp (drivable with the blimp))

**Comment by Rxann** [comment]
I believe #1160 may relate to this

**Comment by Rxann** [comment]
But, I don't know about compatibility(if the vehicles would show up to people without the dlc) and detection status of this potential feature or if this would even work.

**Comment by iswaxan** [comment]
> I believe #1160 may relate to this

dont think it is but thx for the info

**Comment by Rxann** [comment]
Could you specify the feature you want a little more?

**Comment by iswaxan** [comment]
> Could you specify the feature you want a little more?

juts the ability to spawn cars (with persist car feature) that are a xml file type (current supported one is json)

**Comment by xiaoxiao921** [comment]
> I believe #1160 may relate to this

No it does not

also what people want are just a way of loading menyoo xml cars

**Comment by Rxann** [comment]
So could the data just be converted using an online tool to json?

**Comment by xiaoxiao921** [comment]
> 

No, the feature set is widly different between the two, menyoo is open source btw so you can check how they generate those xml files / parse them and compare the features we have with our json loader

**Comment by iswaxan** [comment]
> So could the data just be converted using an online tool to json?

Already tried didnt work

**Comment by xiaoxiao921** [comment]
Closed by #1594
