### ISSUE TITLE
Prometheus future crashes

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1235]
### Problem

Prometheus Mod menu has two new crashes coming with the new update and they say it works on paid menus, so when it realease we will need more protections

### Solution

Make 2 more protections

### Reason

We will be fuked else (and also it would be good to add these 2 crashes to yimmenu if possible)

**Comment by Yimura** [comment]
Not currently an issue.

**Comment by TheGreenBandit** [comment]
> Not currently an issue.

Yimura, i feel you should do something about them, considering they are using your code and violating your license.

**Comment by Yimura** [comment]
> > Not currently an issue.
> 
> Yimura, i feel you should do something about them, considering they are using your code and violating your license.

Like what? What do you expect me to do realistically? It’s best to just ignore them and never talk about them again.

**Comment by TheGreenBandit** [comment]
> 
> Like what? What do you expect me to do realistically? It’s best to just ignore them and never talk about them again.

I feel the best idea that would cost nothing and strike fear would be to threaten but not act upon a lawsuit. It might force them to close down their menu.

**Comment by Yimura** [comment]
> I feel the best idea that would cost nothing and strike fear would be to threaten but not act upon a lawsuit. It might force them to close down their menu.

Threaten? The words of one stranger to another stranger on the internet is worth jack.
I know that and they know that.
