### ISSUE TITLE
[Request]: Place for pre-made outfits to be stored

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1238]
### Solution

a place where people can upload their outfits they have created then other people can download them and use them.

### Reason

I don't know anything about the outfit editor and I can take premade good outfits from this.

**Comment by rrAsus** [comment]
So to say a cloud ? Or a server storing the outfits exactly?
and tbh instead of downloading them just export to clipboard and then import

**Comment by Rxann** [comment]
Well, I don't know. Cloud = Cost. That means expenses for Yimura. It could be a seperate repo where they are stored. Very complex decisions!

**Comment by TheGreenBandit** [comment]
Instead of hosting through a cloud which is expensive, outfits could be compartmentalized into jsons like the custom cars.

**Comment by Rxann** [comment]
This solution is much better. We should go with this one.

**Comment by maybegreat48** [comment]
JSON outfits are already a thing in YimMenu. Select the "Outfit Editor" tab and you should see a JSON save/load widget at the bottom

**Comment by Rxann** [comment]
Yes, I mean more of a central place to store them for the community

**Comment by Yimura** [comment]
Not on the roadmap to be implemented.
