### ISSUE TITLE
Two users behind same home internet connection facing issues when using Yim

### ISSUE THREAD

**Issue by TuxSax** [Yimura/YimMenu#1241]
We're both playing together GTA Online, but if one of os, or both try to use Yim, it will cause eventual game crashes to one of us or both.
Also, heists or jobs, or even joining game, sending invites, many times doesn't go through.
I believe it must have something to do with the fact Yim is proxying the requests, and when the answers come, they both come to the same router public IP, which is then translated via NAT to the home network, however, most probably that some of the responses or packets that are meant for one user, are getting to the other user.

I'd suggest adding an option to configure a fixed outgoing port for the requests, this way, we could configure a different port from each other and then the requests won't be confused by our computers and then game won't crash

**Comment by Yimura** [comment]
YimMenu is not proxying anything, not sure what you're talking about.

GTA chooses its port itself, neither do we host anything (aka. listening on any ports).

Besides colliding ports should never be a problem if you're behind a router. The router is responsible for managing ports that are open to the public network and correctly forwarding traffic that responds on that port to the appropriate client.
If your router routs network packets wrong I think you might need a new router.

The crashing you're speaking of will probably just occur if even one of you two has YimMenu injected.

**Comment by iswaxan** [comment]
> We're both playing together GTA Online, but if one of os, or both try to use Yim, it will cause eventual game crashes to one of us or both. Also, heists or jobs, or even joining game, sending invites, many times doesn't go through. I believe it must have something to do with the fact Yim is proxying the requests, and when the answers come, they both come to the same router public IP, which is then translated via NAT to the home network, however, most probably that some of the responses or packets that are meant for one user, are getting to the other user.
> 
> I'd suggest adding an option to configure a fixed outgoing port for the requests, this way, we could configure a different port from each other and then the requests won't be confused by our computers and then game won't crash

Try downloading lataest version if you don’t 
already have

**Comment by TuxSax** [comment]
Yes, this can happen even if only one of us is using Yim.
But if it was a router/network problem, then how do you explain that without using Yim we never have game crashes?
Besides the times that some moder will crash me because I'm not using any protection.

**Comment by xiaoxiao921** [comment]
The amount of game internals YimMenu modifies / touches is quite extreme, this can of course cause some instability, sadly it can very well be that YimMenu end up crashing the game due to some stuff we do incorrectly. Note also that reporting crash issues in GitHub without giving a log file may as well be considered as spam

**Comment by Yimura** [comment]
> Yes, this can happen even if only one of us is using Yim.
> But if it was a router/network problem, then how do you explain that without using Yim we never have game crashes?
> Besides the times that some moder will crash me because I'm not using any protection.

Because YimMenu is not injected? You do understand that crashes in general can be caused by the menu itself creating some instability in the game.
