### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by badminimum** [Yimura/YimMenu#1249]
Hey mates! I get an error when I want to build the YimMenu.
All files exists

![image](https://user-images.githubusercontent.com/82663068/232329525-ef7f2481-a585-4999-9443-9dcfb00adc1f.png)
![image](https://user-images.githubusercontent.com/82663068/232329594-44b93edc-3946-4d7c-a3ed-966044566f41.png)
![image](https://user-images.githubusercontent.com/82663068/232329596-062408a3-aa10-4f59-8081-82812bca1029.png)

**Comment by GeopJr** [comment]
https://github.com/YimMenu/YimMenu/issues/1134#issuecomment-1480935989
https://github.com/YimMenu/YimMenu/issues/642#issuecomment-1328062288

as for the version.hpp one, make sure you follow the instructions listed on the README

**Comment by badminimum** [comment]
I did
I only changed the Name in main and in the widgets

**Comment by badminimum** [comment]
The only error now is the Imgui file

**Comment by Yimura** [comment]
Issues are for problems with YimMenu vanilla, if you modify the source code you're on your own.

You can join the YimMenu matrix server if you'd like to ask questions that aren't related to YimMenu.

**Comment by howdoiusekeyboard** [comment]
how do i join that

**Comment by Yimura** [comment]
Here's the link to join the matrix server: https://matrix.to/#/#yimmenu:matrix.org

**Comment by 0xTheago** [comment]
> The only error now is the Imgui file

if u have discord write me I can help out
