### ISSUE TITLE
[Bug]: Command executor hotkey sticks to 'u'

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1252]
### Describe the bug

Cannot change the hotkey for command executor

### Steps To Reproduce

.

### Expected Behavior

be able to customise the hotkey

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iswaxan** [comment]
#1248 clone and fixed in general fixes yesterday (i think)
