### ISSUE TITLE
[Bug]: Yim Crashes on Unload

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1256]
### Describe the bug

When clicking unload in online or story mode the game just freezes then crashes. Sometimes it unloads and the other times it freezes

### Steps To Reproduce

1. Enter online or story mode
2. unload
3. observe

### Expected Behavior

the menu to unload per usual

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11245020/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iswaxan** [comment]
you sure you downloaded latest, bc for me it doesnt crashes

**Comment by Peax** [comment]
@iswaxan What version do you use? Please post the hash.

**Comment by Rxann** [comment]
Latest I will post hash later

**Comment by Yimura** [comment]
I've been unable to reproduce this bug, not sure what could be causing this for you.

**Comment by Rxann** [comment]
Could it be a hardware / memory problem on my pc?

**Comment by xiaoxiao921** [comment]
It's literally useless to post unless you give the log file

**Comment by Rxann** [comment]
I will post it later today

**Comment by Yimura** [comment]
> It's literally useless to post unless you give the log file

It's on unload so can't really capture something.
This is the hash according to the log file 958463d5ff775310cb6c03f56b5e67e08bfd4f2f

**Comment by Rxann** [comment]
wait... i already posted the log file @xiaoxiao921

**Comment by ghost** [comment]
I have also experienced this bug in previous versions. Like a lot of crashes with yimmenu I've experienced, though, it is not easy to replicate reliably.

**Comment by D-Borkan** [comment]
i also have this bug when unload the menu 
the game freeze direct then close

**Comment by Yimura** [comment]
> i also have this bug when unload the menu
> the game freeze direct then close

How long after injection does the bug occur? Were you in a mission at the time or in freemode? Single player or online?

**Comment by D-Borkan** [comment]
> > i also have this bug when unload the menu
> > the game freeze direct then close
> 
> How long after injection does the bug occur? Were you in a mission at the time or in freemode? Single player or online?

both in sp or online , the menu work fine but the bug heppen when unload the menu

**Comment by Yimura** [comment]
> both in sp or online , the menu work fine but the bug heppen when unload the menu

So every time you unload it would crash, after a few minutes of playing it would crash or it would crash at random?

Did you play any missions beforehand?

**Comment by D-Borkan** [comment]
for first Q yes everytime when i unload the game close 
and for sec Q i play normal with menu without any problem
and aslo play mission without any problem
the bug heppen with unload , i mean when i want close  or unload the menu

**Comment by Rxann** [comment]
@Yimura if I took a video of this bug/glitch would that help at all?

**Comment by Yimura** [comment]
> @Yimura if I took a video of this bug/glitch would that help at all?

The more info we get the better.

**Comment by D-Borkan** [comment]
> > @Yimura if I took a video of this bug/glitch would that help at all?
> 
> The more info we get the better.

i remember this bug appear after this feat : 
(https://github.com/YimMenu/YimMenu/commit/6df7be6f063065327b19b2d68712ddd62fa880bf)

**Comment by Yimura** [comment]
Ok thanks, then I might have some idea to what is causing the crash after unloading.

**Comment by D-Borkan** [comment]
> Ok thanks, then I might have some idea to what is causing the crash after unloading.

take your time , we hope this bug will fix soon

**Comment by Yimura** [comment]
> take your time , we hope this bug will fix soon

Could you check if this fixes the issue:
https://github.com/YimMenu/YimMenu/pull/1280#issuecomment-1519125153

**Comment by D-Borkan** [comment]
> > take your time , we hope this bug will fix soon
> 
> Could you check if this fixes the issue: [#1280 (comment)](https://github.com/YimMenu/YimMenu/pull/1280#issuecomment-1519125153)

I tested it , but still

**Comment by D-Borkan** [comment]
@Yimura 
another bug ,
with last fix is ok , when just open the menu and close the menu he unload without crash the game
but when use the  options like any option and unload the menu the game crash

**Comment by Rxann** [comment]
You should make a new issue for this I believe
