### ISSUE TITLE
[Bug]: The number of caches is reduced

### ISSUE THREAD

**Issue by Aure7138** [Yimura/YimMenu#1257]
### Describe the bug

![image](https://cdn.discordapp.com/attachments/1035859722043150346/1097384218797031515/image.png)
![image](https://cdn.discordapp.com/attachments/1035859722043150346/1097385578246451230/image.png)

### Steps To Reproduce

recache

### Expected Behavior

Quantity reduction should be within reason, e.g. filtered crash ped

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

In #1251, I noticed that get_non_dlc_mounted_devices_names was deleted, we need this to get update.rpf and update2.rpf and other instances, because these instances already exist before the game is initialized, and cannot be obtained through the mount hook

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
https://github.com/maybegreat48/YimMenu/blob/9fd84de6bdad9310a47c6b77f1587715fb491770/src/services/gta_data/yim_fipackfile.cpp#L50

https://github.com/maybegreat48/YimMenu/blob/9fd84de6bdad9310a47c6b77f1587715fb491770/src/hooks/misc/fipackfile_mount.cpp#L19

And I noticed that using "/" as mount_point doesn't work for some rpfs(works with most), it would be nice if there is a way to get the mount_point of any rpf, maybe we can go back to using the parameter passed in by the hook as mount_point as before, and via get_non_dlc_mounted_devices_names as mount_point

Here is my test code and the test code in the mount hook:

```cpp
if (ImGui::Button("test"))
{
	auto names = yim_fipackfile::get_non_dlc_mounted_devices_names();
	for (auto name : names)
	{
		auto device = rage::fiDevice::GetDevice(name.c_str(), true);
		if (*(void**)g_pointers->m_gta.m_fipackfile_instances[1] == *(void**)device)
		{
			yim_fipackfile rpf_wrapper = yim_fipackfile((rage::fiPackfile*)device, name);
			yim_fipackfile rpf_wrapper2 = yim_fipackfile((rage::fiPackfile*)device, "/");
			LOG(INFO) << device->GetName() << " " << name << " " << rpf_wrapper.get_file_paths().size() << " "
					    << rpf_wrapper2.get_file_paths().size();
		}	
	}
}
```

```cpp
bool hooks::fipackfile_mount(rage::fiPackfile* this_, const char* mount_point)
{
	auto result = g_hooking->get_original<fipackfile_mount>()(this_, mount_point);

	yim_fipackfile rpf_wrapper  = yim_fipackfile(this_, "/");
	yim_fipackfile rpf_wrapper2 = yim_fipackfile(this_, mount_point);
	LOG(INFO) << rpf_wrapper.get_name() << " " << rpf_wrapper.get_file_paths().size() << " "
		        << rpf_wrapper2.get_file_paths().size();
		
	return result;
}
```

```cpp
std::vector<std::filesystem::path> yim_fipackfile::get_file_paths(std::string parent)
{
	std::vector<std::filesystem::path> file_paths;
	if (parent.empty())
		parent = mount_name;

	std::vector<std::string> directories;

	rage::fiFindData findData = {0};
	auto handlef              = rpf->FindFirst(parent.c_str(), &findData);
	if (handlef != -1)
	{
		do
		{
			std::string fn;

			if (parent == "/")
				fn = std::string(parent.c_str()) + std::string(findData.fileName);
			else
				fn = std::string(parent.c_str()) + std::string("/") + std::string(findData.fileName);

			if (findData.fileAttributes & FILE_ATTRIBUTE_DIRECTORY)
			{
				directories.push_back(fn);
			}
			else
			{
				file_paths.push_back(fn);
			}
		} while (rpf->FindNext(handlef, &findData));

		rpf->FindClose(handlef);
	}

	for (auto& directory : directories)
	{
		auto files = get_file_paths(directory);

		file_paths.insert(file_paths.end(), files.begin(), files.end());
	}

	return file_paths;
}
```

And output:

![image](https://cdn.discordapp.com/attachments/963096010853347409/1097726380948607097/image.png)
![image](https://cdn.discordapp.com/attachments/963096010853347409/1097726679339769988/image.png)

**Comment by Rxann** [comment]
i have noticed this bug also
