### ISSUE TITLE
[Bug]: Anti afk basically not working

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1258]
### Describe the bug

When you enter a session with the No idle kick mode enabled, after a while a timer still appears, which after 13 minutes will kick you for inactivity.

### Steps To Reproduce

1. Enable No Idle Kick
2. Wait
3. You can even die a couple of times from nearby players
4. Get kicked for inaction

### Expected Behavior

Stay in session indefinitely

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Unable to reproduce, are you playing in full screen, windowed fullscreen?

**Comment by ghost** [comment]
i play in windowed fullscreen

**Comment by Yimura** [comment]
Mmmm not sure what the issue is, it seems to work for me.

I've been afk for a long time and haven't been kicked from the game.

**Comment by ghost** [comment]
As far as I understand, antiafk may not always work. for example, I can leave the menu open and even get killed a few times. and during this all the same, a timer appears like "13 minutes left until the kick" and I will be kicked.

**Comment by 0xEmiil** [comment]
same issue, im playing in windowed fullscreen

**Comment by Yimura** [comment]
Do you have pause game on focus loss enabled in settings? Can you try to turn that off?

![image](https://user-images.githubusercontent.com/24669514/232590794-48863bb3-e57b-4a2e-a44b-570bfc9ebf0b.png)

**Comment by ghost** [comment]
I have the game in focus was always turned off
![pic](https://user-images.githubusercontent.com/70230299/232593560-05497657-2a3d-4769-8370-546d8b0561ad.PNG)

**Comment by 0xEmiil** [comment]
> Do you have pause game on focus loss enabled in settings? Can you try to turn that off?
> 
> ![image](https://user-images.githubusercontent.com/24669514/232590794-48863bb3-e57b-4a2e-a44b-570bfc9ebf0b.png)

Same result

**Comment by Rxann** [comment]
Is the No Idle Kick a looped command?

**Comment by Yimura** [comment]
No it's literally byte patching the functionality out of the game.

**Comment by Rxann** [comment]
Oh 😂

**Comment by maybegreat48** [comment]
You mentioned that you die when spectating in another issue which implies that the script patcher service somehow does not work for you
* Are you coloading YimMenu with a P2C? (This includes "Stand Free")
* What are you using to inject YimMenu?
* When are you injecting YimMenu? (Singleplayer, or when in a session?)

**Comment by ghost** [comment]
Yes, I use a coload with free stand and for injecting I use a xenos injector.  I'm injecting a menu on the screen to choose between online and single player

**Comment by maybegreat48** [comment]
Co-loading YimMenu with Stand will break both menus. Please make sure that you can reproduce an issue without co-loading anything next time
