### ISSUE TITLE
[Request]: italian and french translations

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1259]
### Problem

them two might be helpful

### Solution

i can translate if ya want

### Reason

some people (mostly french people doesnt talk english or not very well)

### Additional context

ya can contact me on discord or element

**Comment by Seanghost117** [comment]
Anyone is free to add to or update translations based off the default translations. Just open a PR on https://github.com/YimMenu/Translations to add them in and follow the structure. No reason to make an issue.

**Comment by iswaxan** [comment]
> Anyone is free to add to or update translations based off the default translations. Just open a PR on https://github.com/YimMenu/Translations to add them in and follow the structure. No reason to make an issue.

ok thx tho
