### ISSUE TITLE
Godmode viewer in ESP does not mark some players

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1260]
### Describe the bug

ESP doesn't show this even if some players are in godmode (I'm not sure it's a bug). I don't know if the opposing player's protection is preventing this, but if I shoot at the opposing player with both a gun and a rocket, it usually doesn't work.

### Steps To Reproduce

go to ESP in settings

open godmode viewer

Go near a person who is usually a griefer (if you can meet them)

ESP sometimes this does not appear if its godmode is on.

### Expected Behavior

If the opposite player is immortal, ESP writes GOD in red.
(Except for players inside buildings and at the start of missions)

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
YimMenu has godmode hiding as a feature, other mod menu's are abusing the same thing and blocking godmode from being synced to other players.

It's enabled by default in YimMenu.
![image](https://user-images.githubusercontent.com/24669514/232569028-8ebd3ffc-31f4-463c-86d2-f65107531211.png)
