### ISSUE TITLE
[Request]: Vehicle Launch Control

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1262]
### Solution

A menu feature that allows u to enable the feature, set a rpm, and press a button to launch.

### Reason

I hate trying to launch control myself soo......

**Comment by Rxann** [comment]
this is an example of what I would want:

https://www.youtube.com/watch?v=QqgtJTVgxGU

**Comment by TheGreenBandit** [comment]
Setting the rpm doesn't do anything, just sets the sound.

**Comment by Rxann** [comment]
Ok thanks
