### ISSUE TITLE
ImGui::End need to be called even if ImGui::Begin returns false

### ISSUE THREAD

**Issue by maybegreat48** [Yimura/YimMenu#127]
**Describe the bug**
As stated in the documentation:
Return false when window is collapsed, so you can early out in your code. You always need to call ImGui::End() even if false is returned.

**To Reproduce**
1. Compile YimMenu in debug mode (may need to remove the exception handler in the invoker)
2. Inject
3. Open and close stuff

**Expected behavior**
ImGui::End called for every ImGui::Begin, even if it returns false

**Screenshots**
N/A

**Logs**
N/A

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
Compiling in debug mode may reveal hidden errors that are not easily visible in release mode

**Comment by Yimura** [comment]
Really, I thought you didn't need to do this, are there any other such things that need end to be called regardless of it if returned true or false?

**Comment by maybegreat48** [comment]
Not really sure as this isn't clearly documented anywhere, just a single comment on the function

**Comment by Yimura** [comment]
Alrighty, it'll be the first thing I do when I get home.
