### ISSUE TITLE
[Bug]: Random Crash

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1272]
### Describe the bug

I was driving, everything was okay, then my game froze. I just closed GTA after that.

### Steps To Reproduce

It's a pretty random freeze so idk...

### Expected Behavior

to not crash

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11299076/cout.log)

### Store

Steam

### Additional context

sorry for having to upload file instead of ctrl c & ctrl v, the log was too long.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
did you hit a random breakable object, like a street sign or chainlink fence? I've had it crash from hitting random objects while driving for months now.

**Comment by Rxann** [comment]
Nope

**Comment by Yimura** [comment]
Old crash log, might be outdated with the changes we've made to CanApply. Closing as the issue has gone stale...
