### ISSUE TITLE
[Request]: Protected Players

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1273]
### Solution

A feature that allows you to mark players as "protected players" that will block them from toxic things and kicks.

### Reason

bc i want to protect my friend.

**Comment by Tayipc38** [comment]
tell m to use yim

**Comment by Rxann** [comment]
see the problem is they don't like modders 💀

**Comment by CypherMorgan** [comment]
Don't mind but still you're their friend lol
