### ISSUE TITLE
[Bug]: Most of the players lose connection with the host

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1275]
### Describe the bug

The problem occurs frequently. When you have enabled Force session host, Force Script Host and Kick host during join when connecting to a session, after you become a host, then most of the players, if not all, lose connection with you. And for example, when you connect in the session, there were 30 people, then at the end there are 7 or even less, and sometimes you are left alone. And this happens to me almost half the time.

### Steps To Reproduce

1. Enable Force Session Host, Script Host, Kick host During Join, Joing in SCTV slots, Reveal OTR Players.
2. Join to session
3. The moment you become a host, most players start leaving at the same time
4. When you saw your character, you continue to see these players in the Yimmenu table; in the game table, most of them have already left the game. And after 10 seconds they disappear from the menu

### Expected Behavior

All players must remain in the session except for the person who was the host before.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Disable force host option if you don't want to have this happen, there's no way to prevent some players from dropping out of the session when forcing host.
