### ISSUE TITLE
[Bug]: Add players to database is not enabled in the reaction, but menu will automatically add players to the database

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#1277]
### Describe the bug

Add players to database is not enabled in the reaction, but menu will automatically add players to the database

### Steps To Reproduce

1

### Expected Behavior

It is not automatically added to the database

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Things that are guaranteed to be caused by a modder will always add them to the player database, there's no option to toggle this.

**Comment by epicmusicpt** [comment]
impossible to keep db with only the players you want...got to keep delete them all the time,and those spam notifications keeps adding them to db...

**Comment by iwanttodo1t** [comment]
I just want the player database to hold the players I follow, not all cheating players, which doesn't seem to make much sense

**Comment by iwanttodo1t** [comment]
I hope you can add a switch to stop adding automatically

**Comment by iwanttodo1t** [comment]
It seems that some events in the reaction menu are directed at oneself and some events are directed at anyone

**Comment by 43eayl5** [comment]
> Things that are guaranteed to be caused by a modder will always add them to the player database, there's no option to toggle this.

Isn't this basically a "Modder Detection"? I should be imo
Maybe this is triggered just by some specific events like triggering Rockstar's anticheat? But the name "Modder Detection" is so generic that I think it should be used for _all_ kinds of detections.

**Comment by Yimura** [comment]
Implicit adding of players to the Player DB has been removed from YimMenu.
