### ISSUE TITLE
[Request]: Choose Kick in Reactions

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1281]
### Solution

Add a List of Kick's after checking the box "Kick Player", 
Make it that you can select only one.
List : 
Null Function Kick.
End Session Kick.
Desync Kick.
OOM Kick.
Bail Kick.

### Reason

I sometimes wanna use others kicks in reactions

### Additional context

Oh and If a kick Doesn't Work Out then Use the other one

**Comment by Rxann** [comment]
I assume this should be pretty easy to implement, I may work on it if I have time.

**Comment by Rxann** [comment]
There is a working pr that has been made for it, and when features are going to be introduced again, it will be featured.

**Comment by Rxann** [comment]
I wouldn't close this, as it will auto close when the issue is actually solved
