### ISSUE TITLE
[Request]: libcpr alternate 

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1284]
### Problem

as @tupoy-ya pointed out in an issue, libcpr takes a lot of time to compile for the amount of usage it gets.

### Solution

A separate library like cpp-httplib, which seems to be simple and easy to implement. it is also just one header file. 

### Reason

Faster compilation speeds and less bloat.

**Comment by Yimura** [comment]
No we won't switch, besides cpp-httplib uses the same things underneath as cpr most likely.

Once SSL has been setup once you don't need to compile it anymore, it's a compile once and never compile it again.
