### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KnollenRick** [Yimura/YimMenu#1291]
### Describe the bug

I can't inject the DLL anymore. Maybe 3 weeks ago, I was driving around using the auto-drive funktion, and then GTA V closed by itself. I tried to inject the DLL using the Xenos Injector and then GTA V closed by itself again. Now, I tried it again, with the "new" DLL and it happens literally NOTHING. I think, YimMenu is outdated and needs an update. If not, how can I fix this issue?

### Steps To Reproduce

1. Open your favorite code injector
2. Select the YimMenu.dll
3. Press "Inject"

### Expected Behavior

Open a injector and load the dll into GTA V, press insert and open the menu.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by howdoiusekeyboard** [comment]
I can confirm yimmenu is not outdated and it injects. It works fine, maybe some error in your settings.json file, u should reset it

**Comment by KnollenRick** [comment]
> I can confirm yimmenu is not outdated and it injects. It works fine, maybe some error in your settings.json file, u should reset it

How?

**Comment by howdoiusekeyboard** [comment]
delete the file in your appdata

**Comment by KnollenRick** [comment]
From GTA's appdata folder? OK.

**Comment by xiaoxiao921** [comment]
The path is `C:\Users\YOUR_USERNAME\AppData\Roaming\BigBaseV2`

which can also be accessed by writing `%appdata%\BigBaseV2` in the "url" bar of your windows file explorer

**Comment by KnollenRick** [comment]
I deleted the settings.json file and it didn't changed. Still not working.

**Comment by Yimura** [comment]
Can you try deleting the whole folder of `BigBaseV2`?

**Comment by KnollenRick** [comment]
I'll missing my cool vehicles...

**Comment by Yimura** [comment]
> I'll missing my cool vehicles...

Ok instead try to remove all the files & folders in the `BigBaseV2` folder except `handling_profiles`, `jobs`, `saved_json_vehicles` and `saved_outfits`.
And maybe `players.json` if you'd like to keep the player database.

**Comment by KnollenRick** [comment]
Thank you so much, it's working again! Yaaay! XDD
