### ISSUE TITLE
[Bug]: Text bug in Orbital Drone Tooltip

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1292]
### Describe the bug

Text is bugged in the tooltip for "Automatically lock onto player" in orbital drone tooltip

### Steps To Reproduce

Hover on the option

### Expected Behavior

Text box of the tooltip should be clear

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://user-images.githubusercontent.com/90883505/234409509-3b146ea8-174f-442e-aa97-928d81e6523b.png)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Interesting
