### ISSUE TITLE
[Bug]: Bug log for while using orbital drone

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1293]
### Describe the bug

..

### Steps To Reproduce

Use orbital drone

### Expected Behavior

No log

### Screenshots and/or Logs

[Dumping modules.txt](https://github.com/YimMenu/YimMenu/files/11327067/Dumping.modules.txt)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Does this solve the issue you have?
https://github.com/YimMenu/YimMenu/pull/1295#issuecomment-1522500876

I'm not sure if you remember what you did to cause the crashing and can reproduce the issue.

**Comment by howdoiusekeyboard** [comment]
Well I was facing the bug when trying to lock onto players. I tried the new binary and I am not facing the bug

**Comment by Yimura** [comment]
> Well I was facing the bug when trying to lock onto players. I tried the new binary and I am not facing the bug

The one from the PR or the one from nightly release?

**Comment by howdoiusekeyboard** [comment]
From PR
