### ISSUE TITLE
[Request]: Display an alert when a player is online

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1298]
### Problem

I think it's problematic to constantly click on the "Reload Player Online States" button.

### Solution

I think it should be a loop that will gradually check players online, instead of constantly clicking on the appropriate button. For saved players, you can add the corresponding checkbox "Notify when online". You can add the same to the reaction, but I think it will be superfluous.

### Reason

Makes it easier to chase down pesky griefers and other scum who get in the way of others. Well, just for convenience. Let's hope that constantly updating the status in the network of players will not hurt performance much.

**Comment by TheGreenBandit** [comment]
This was implemented to be a manual refresh as it lags the game. Having it automatic would mean constant lag. Even on a delay it could become very annoying.

**Comment by Yimura** [comment]
> This was implemented to be a manual refresh as it lags the game. Having it automatic would mean constant lag. Even on a delay it could become very annoying.

The information on if players are online is ran in a separate thread from the game loop, there's no way that this will cause lag in the game.

We can definitely periodically check/update the list to see who is online.

**Comment by Rxann** [comment]
So would you want it to be like in the player database you mark them as a person you want to be notified of being online?

**Comment by ghost** [comment]
Yes, that's exactly what I meant. Just add a checkbox for each player something like "display notification when online"

**Comment by Rxann** [comment]
Alright, I will work on this. I also had this idea myself

**Comment by binded-zz** [comment]
can you maybe all so add some sorta sort and date seen or last seen 

the players are added randomly  

also is something it to hard or even possible to add another color code in the left player view 

idk 
blue modder
green friendly 
yellow has command access
red already modder, alerts

**Comment by Rxann** [comment]
It could work. I am quite busy right now with the original one. I don't have a clue on how to implement it.

**Comment by Tayipc38** [comment]
Added by #1386
