### ISSUE TITLE
[Bug]: 刷出个人载具的

### ISSUE THREAD

**Issue by 1719952486** [Yimura/YimMenu#1304]
### Describe the bug

刷出载具的的超级跑车分类里面没有伊格纳斯，全部里面有伊格纳斯，个人载具同样

### Steps To Reproduce

打开菜单，选择载具，刷出载具，分类选超级跑车

### Expected Behavior

希望能修复，上个版本没有这个问题

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Please use English for issues.
