### ISSUE TITLE
[Bug]: crash (macOS)

### ISSUE THREAD

**Issue by Hakimbhb** [Yimura/YimMenu#1307]
### Describe the bug
`whenever i inject YimMenu i get an error and the game crashes,` 

- ps i m macOS user and i use crossover to run it with epic !! and i use for inject (simple injector) 

-  i am already using mod named TnyavnTos-GTA5-Mod-Menu-main u could find it on github  but i like that mod and it seems not yet supported cross over so i wish u add it and thank u a lot

> 
 ### Steps To Reproduce

 ### Screenshots and/or Logs
<img width="1368" alt="Screenshot 2023-04-29 at 6 52 27 PM" src="https://user-images.githubusercontent.com/122839610/235317342-c8869315-61e4-4ad9-af96-1bcfd3df2252.png">

<img width="1368" alt="Screenshot 2023-04-29 at 6 51 12 PM" src="https://user-images.githubusercontent.com/122839610/235317364-c0e27f4b-a12c-4a0a-8529-efe59b5db2ba.png">

### Steps To Reproduce

> inject dll get error game crashes 

and it seems like the second photos 

then i choose online it blurry i only can use esc and arrow so i make online and it seems like all crush 

### Expected Behavior

> inject dll get error game crashes

### Store

Epic Games

### Additional context

i could be a beta user  i m open for that i use MacBook m1 pro with 8 ram 
and crossover last version 

my contact : bhbhakim001@gmail.com 

u could send me the beta version to test it at anytime thank u for that great work and i wish u consider my situation and help me too add your mod menu to include macros

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iswaxan** [comment]
Try waiting till youre actually in online (or SP) to inject, might Work i think

**Comment by Rxann** [comment]
I am on windows, but I can inject once it gets to the 3 rockstar loader signs without any trouble

**Comment by Hakimbhb** [comment]
i tried to wait a lot and nothing happened it stuck for a loop 

and i tried all the way haha like when the app launched sp directly online in the 3 point about to open it seems the problem from the script i wish he make a look on the script with it work for me and try to fix it or just make new one without update cash wait maybe it work..

**Comment by Hakimbhb** [comment]
### here is the log may it help : 

corct 132.d11 Base Address: 0x2BB750000 Size: 712704
hid.dil Base Address: OxF51E0000 Size: 20480
setupapi.di1 Base Address: 0x2107E0000 Size: 225280
XINPUT1 3. d11 Base Address: 0x253000000 Size: 20480
IPHLPAPI.DLL Base Address: 0x240030000 Size: 53248
dnsapi.d1l Base address: 0x29CFC0000 Size: 32768
nsi.dll Base Address: 0328DFA0000 Size: 8192
winemac.drv Base Address: 0x6C890000 Size: 503808
uxtheme.d11 Base Address: Ox2F7230000 Size: 77824
clochelp.d11 Base Address: Ox3BE590000 Size: 315392
dxgi.d11 Base Address: 0x2998F0000 Size: 86016
ddiac.dll Base Address: 0x3798B0000 Size: 32768
adraw.dll Base Address: 0x2C82F0000 Size: 233472 whemprox. d11 Base
Address: 0x241940000 Size: 122880
winspool.dry Base
Address:
0x1C4EE0000 Size: 102400
mdevapi.dIl Base Address: 0x336850000 Size:
57344
winecoreaudio.dry Base address: 0x1C92D0000 Size: 36864 devenu.dll Base Address: Ox3AD720000 Size:
36864
avicap32. dll Base Address:
Ox3A77E0000 Size:
8192
quartz.dll Base address: 0x341D30000 Size:
462848
msviw32.d11 Base Address:
0x394620000
Size:
53248
misacmez.dry Base Address:
Ox34E640000
Size:
20480
midimap.dll Base Address: 0x3346F0000
Sizp:
12288
winevulkan.d11 Base Address: Ox3B6DCO000
Size: 73728
EOSSDK-Win64-Shipping.di1 Base Address:
Ox4C160000 Size: 7229440
Secur32.dl1 Base Address: 0x201CF0000 Size: 69632
WINHTTP. d11 Base Address: 0x358120000 Size: 131072 jsproxy.dil Base Address: 0x346BA0000 Size: 12288
ULDAP32.11 Base Address: 0x38B500000 Size: 172032
Normaliz.dll Base Address: 0x1E40000 Size: 0
MSVCP140.d11 Base Address: 0x360E10000 Size: 479232
VCRUNTIME 140.dIl Base Address: 0x26ED50000 Size: 4096
Kerberos.dil Base Address: 0x274450000 Size: 16384
Msv1 0.d11 Base Address: 0x39C380000 Size: 28672
netapi32.d11 Base Address: 0x367300000 Size: 86016
concrt140.d11 Base Address: 0x3871C0000 Size: 61440
rsaenh.d11 Base Address: 0x2DE970000 Size: 90112
DSD11. DLL Base Address: Ox4EF40000 Size: 2126336
vulkan-1.d11 Base Address: 0:3785E0000 Size: 4096
DSD10 1. ILL Base Address: 0x4D300000 Size: 836608
DSD1OCORE. DLL Base Address: Ox4 210000 Size: 727552
VimMenu.dll Base Address: 0x5B4C0000 Size: 2523136
msver120.d11 Base Address: 0x21560000 Size: 528384
DSDCOMPILER 47.011 Base Address: 0x1C8890000 Size: 114688
VCRUNTIME140 1.011 Ease Address: Ox2F7F20000 Size: 16384
MAudio2 7.d11 Base Address: 0x242DF0000 Size: 122880
schannel.dI1 Base iddress: OxIDC810000 Size: 8192
imagehlp.dll Base Address: 0x2BC640000 Size: 20480
socialclub.d1l Base Address: 0x80000000 Size: 5092864
chrome elf.di1 Base Address: 0x67090000 Size: 685568
liber.dll Base Address: 0x82400000 Size: 109755392
UIautomationCore.DLL Base address: 0x5CC50000 Size: 182784
OLEACC. d11 Base Address: 0x2522E0000 Size: 110592
USERENV. d11 Base Address: 0x388E20000 Size: 16384
DUrite.d1l Base address: 0x300950000 Size: 282624
dumapi.d11 Base Address: 0x250740000 Size: 8192
USP10.11 Base Address: 0x67D40000 Size:
COMDLG32.11 Base Address: 0x31F800000 Size: 192512
davaz. d11 Base Address: 0x7FF33860000 Size: 65024
credui.d1l Base Address: 0x2D23F0000 Size: 16384
urlmon.d11 Base Address: 0x3422E0000 Size: 348160
ncrypt.d11 Base Address: Ox3A19E0000 Size: 12288
CRYPTUI. d11 Base Address: Ox3BB250000 Size: 69632 dhopesve.DLL Base Address: 0x3444C0000 Size: 8192
wevtapi.dll Base Address: 0x200880000 Size: 8192
ESENT.d11 Base address: 0x2F3920000 Size: 12288
xinput1 4.d11 Base Address: 0x349360000 Size: 20480
hetefg.dll Base Address: 0x324F00000 Size: 61440
Dumping registers:
RAX: OxO
RCX:
OxO
REX:
0x8B99FABO
REX:
0x0
RSI:
OxO
RDI:
0x8B99F480
ESP:
0x8B99FA30
REP:
OxeE99FE60
RB:
OXEd
R9:
0x170084480
R10: 0×4340000
R11: OxBB99F440
R12 :
OxO
R13 :
OxO
R14: 0x5B77FECO
R15: 0x567803C0
Dumping stacktrace:
[0]
VimMenu.d11+OxE4940 0×56524940
[1]
TimMenu.d11+0x106160 0x5B5C6160
[2]
TimMenu.d11+0xB72E3 0x565772E3
[3]
TimMenu.dIl+OxEATEC Ox5BS ATEC
[4]
TimMenu.d11+OxE&7DC Ox5BSAA7DC
[5]
VimMenu.dIl+OxE&6D1 Ox5B58A6D1
[6]
kernelbase.dll InitOnceExecuteonce
--------End of exception ==-----
EXCEPTION ACCESS VIOLATION
Dumping registers:
RAX: 0x0
ROX: 0x0
RIX: 0x8B99FABO
REX: OKO
RSI: 0X0
RDI: OxBB99F480
RSP: Ox8B99F430
REP: O×8B99FB60 RB:
OXE&
R9:
0x170084480
R10: 0K4E340000
R11: OXBB99F440
F12:
R13: 0x0
R14: 0x5B77FECO
R15: 0x5B7803C0
Dumping stacktrace:
[0]
VimMenu.di1+OxEA944 0x5B514944
[1]
VimMenu.dil+0x106160 0x5B5C616C
[2]
VimMenu.dil+OxE72E3 0x5E5772E3
[3]
VimMenu.dIl+OxE&TEC OxSESAATEC
[4］
VimMenu. d11+OxEATDC Ox5ESAATDO
[5]
VimMenu.dil+OxEA6D1 Ox5E5A46D1
[6]
kernelbase.dil InitOnceExecuteonce
--End of exception-
EXCEPTION ACCESS VIOLATION
Dumping registers:
RAX:
0x67FE0000
RCX:
0x0
RDX:
OKO
PBX: OKADDEFEAO RSI:
OxO
RDI: 0x4DF28670
RSP: OxBB99F430
REP: 0×8B99FB60 RB:
0x50499770
Re:
0x170084480
R10: 084E340000
R11: 0:8B99F440
R12: 0x0
R13: 0x0
R14: 0x5B77FECO
R15: 0x5B7808C0
Dumping stacktrace
[0]
kernelbase.d1l SwitchToFiber
[1]
VimMenu.d11+0x106160 0x565C616C
[2]
VimMenu.dll+OxB72E3 0×565772E3
[3]
VimMenu.dIl+OxE&TEC OxSESAATEC
[4]
VimMenu.d1l+OxEATDC OxSESAATDO
[5]
VimMenu.dIl+OxER6D1 OxSE5 A6D1
[6]
kernelbase.dll InitOnceExecuteOnce
---End of exception--

**Comment by ghost** [comment]
>
>     * i am already using mod named TnyavnTos-GTA5-Mod-Menu-main u could find it on github  but i like that mod and it seems not yet supported cross over so i wish u add it and thank u a lot
> 

You should be careful about some of the menu's you use on github. That one looks like a ripoff of this one: https://github.com/HatchesPls/GrandTheftAutoV-Cheat

I'm not saying it is, but it's def sus. Single release. No longer supported after one release.

**Comment by Hakimbhb** [comment]
> > ```
> > * i am already using mod named TnyavnTos-GTA5-Mod-Menu-main u could find it on github  but i like that mod and it seems not yet supported cross over so i wish u add it and thank u a lot
> > ```
> 
> 
> You should be careful about some of the menu's you use on github. That one looks like a ripoff of this one: https://github.com/HatchesPls/GrandTheftAutoV-Cheat
> 
> 
> I'm not saying it is, but it's def sus. Single release. No longer supported after one release.



yeah you are rg it no longer used i was just trying to check if i even could use mod menu with crossover!! i m not using it ! i just mention to clear that it s possible 

but i use sometimes scooby menu i just mention the first one bcc it the same technologies injecting dll!!


EDIT: 

thank u a lot for the repost u s sent ur rg it the same mod menu  and i got the new feature thank u mate 
even the injector they have the last version hahah

i was trying to find the owner but i didn't t get it u save my life with that thank u my friend and yeah it s working even  on last version so it s bones to the @Yimura 
he could check it maybe it help !!

<img width="1368" alt="Screenshot 2023-04-30 at 4 58 35 PM" src="https://user-images.githubusercontent.com/122839610/235363244-94fa797a-1e86-40fe-8f30-54db8715d822.png">

**Comment by Rxann** [comment]
why the close and reopen?

**Comment by Hakimbhb** [comment]
> why the close and reopen?

**Comment by Hakimbhb** [comment]
i did it by  mistake..

**Comment by Rxann** [comment]
Alright, if this is resolved, then you can close it

**Comment by Hakimbhb** [comment]
> Alright, if this is resolved, then you can close it

yeah it didn't t yet my request from beginning is to fix the .dll to work with crossover!! 

and thee photo i send is from another mod menu !!

**Comment by Rxann** [comment]
Open a request if you would like the feature to be implemented

**Comment by Yimura** [comment]
This is more a bug fix than a request really, though I don't see how we could debug this as I know of no one that plays on a Mac and is capable of debugging this.

**Comment by Hakimbhb** [comment]
> This is more a bug fix than a request really, though I don't see how we could debug this as I know of no one that plays on a Mac and is capable of debugging this.


i undrestand u i m not sure but i m thinking the whole problem from creation the folder in c folder maybe bcs i can t see any folder created under name yimmenu in other case the menu iwhich worked has created 

and i send the full log may help u more

`i really appreciate ur work i wish u get a solution for me `

> and gj man 
i wish that some day figure a solution..

**Comment by j1m1l0k0** [comment]
Use Valve Proton in macosx
https://github.com/ValveSoftware/Proton  instruction for compilation step by step

**Comment by iAmSpace** [comment]
@Hakimbhb could you please send a download link to this injector? unrelated but i cant find one that works for me.
