### ISSUE TITLE
[Bug]: Bring Player

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1309]
### Describe the bug

When you bring a player to your location (using bring player feature), the menu will keep bringing that person on the same spot multiple times after different time gaps.

### Steps To Reproduce

1. Go to any session with your friend or any player.
2. Bring that person to your place/location and once that person is there.
3. Now go to different place or stay there and wait for a while.
4. The player will be automatically Tp-ed to that spot again.

### Expected Behavior

The player doesn't get tp-ed multiple times.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Yeah this is an issue with the how the data is synced, we'll have to take a look at resetting the values to prevent the teleporting from happening over and over again.

**Comment by CypherMorgan** [comment]
Oh, Okay..

**Comment by Yimura** [comment]
If you take a look at the code you can see that we spawn a vehicle and then put the target player as an occupant, this causes their game to put them in the vehicle and at the same time we set the coordinates to teleport them to.

What I think is happening is that your game sends a sync of this same vehicle every so often causing the target to teleport back to that position, if you move away from that spot (as the one that triggered the bring player) it should stop from happening.

https://github.com/YimMenu/YimMenu/blob/eede8978d7f3fe408cff6f937377c6eff5c51a1f/src/hooks/toxic/write_vehicle_proximity_migration_data_node.cpp#L10-L23

**Comment by Tayipc38** [comment]
I think there are functions we can hook that are responsible for sending the sync. This hook is simply adjusting some values before the sync is sent, I believe. We could try and catch the sent sync and compare its node values to these variables and reset the said variables once they are sent. Thats just a thought and Im not the best at this.
