### ISSUE TITLE
[Bug]: Blocking players kicking us out of the lobby won't work.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1311]
### Describe the bug

When I entered any session, I added a player who kicked me out of the sessionto the database and ticked the block join setting. Likewise, in the reaction section, the option to block against kick players is selected. But this setting does not work and the player we do not want to join can enter the session.

note: I can kick the player from the sessionmanually, the kick settings are working.

### Steps To Reproduce

add the player to the database or wait for the reaction settings to do it.

The player can then enter the session and the reaction won't work either.

### Expected Behavior

the player who kicked you out of the session must not be able to join the sessions you are in

### Screenshots and/or Logs

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/11362646/cout.log)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Did you click the save button after enabling block join on the selected player?

**Comment by ghost** [comment]
Yes, I even saved it by ticking the cheater option as a reason.

**Comment by Yimura** [comment]
Do you have the latest version of the menu? The one that was release 9 hours ago?

Previously we had no fallback for if block join failed, block join would only work as host on the old version.
We have a fallback now that tries to kick them using breakup kick as a last resort.

**Comment by ghost** [comment]
Nightly [eede897] Yes I have the version here.

I don't know much of the technical details but just wanted to report what happened to me today to help.

**Comment by Yimura** [comment]
Mmmm it should work normally, I'll take a look later.

**Comment by epicmusicpt** [comment]
i notice some are blocked others aren´t, but the automatic kick if block join fails is working.

**Comment by ghost** [comment]
I think there is one more problem.
Kick options don't always work in a session with non-mods or friends.

This usually happens to me when I get kicked out of a modded player's server or when I try to kick a modded player in another session.

**Comment by binded-zz** [comment]
i had made some mods that was going to add a not friend icon and high light the player all was good till this morning 
im still trying to make it work 
so when it fails or  you join a session with them if it fails then as well you will still know

**Comment by Yimura** [comment]
Old issue and should be fixed with the changes we made to the kicks used by block join.
