### ISSUE TITLE
Armored vehicles not having armor

### ISSUE THREAD

**Issue by LexyDrow44WasTaken** [Yimura/YimMenu#1321]
it appears everytime the menu is loaded, my cars lose their armor.
for example, my omnis e-gt an my virtue (imani tech) should tank 12 explosions, yet, they explode instantly.
perhaps you guys should get this fixed?

**Comment by Rxann** [comment]
Could you provide any documentation of this issue such as a video or if there is a stack trace

**Comment by LexyDrow44WasTaken** [comment]
https://www.youtube.com/watch?v=3sSvc12jxy8
here is a video of me demonstrating how the omnis loses armor once i load the menu. this also happens with my Virtue, another imanitach car. it doesn't happen with other vehicles though, like the toreador or insurgent. only my imanitech cars

**Comment by Rxann** [comment]
Okay, I will take a look later, but I am not very skilled with this codebase so I may have to leave it with yimura or maybegreat etc

**Comment by maybegreat48** [comment]
Duplicate of #1192

**Comment by Yimura** [comment]
Closing in favour of #1192
