### ISSUE TITLE
[Bug]: (potentially) only compiling under Windows lib

### ISSUE THREAD

**Issue by dikivan2000** [Yimura/YimMenu#1326]
### Describe the bug

Hey folks, I'm the guy from the UC thread asking for help. Managed to get the build going but there is an issue.

error: no matching function for call to 'std::exception::exception(const char [71])'

Similar to https://github.com/zeromq/cppzmq/issues/88, I compile under MinGW distro and not VS (I really, really don't want to install VS, I don't have the space on C:). The solution is there in the linked issue, perhaps we could do that?

### Steps To Reproduce

Compile under standard C++

### Expected Behavior

No errors in compilation

### Screenshots and/or Logs

```
In file included from C:/YimMenu/src/logger/logger.hpp:3,
                 from C:/YimMenu/src/common.hpp:55,
                 from C:/YimMenu/build/CMakeFiles/YimMenu.dir/cmake_pch.hxx:5,
                 from <command-line>:
C:/YimMenu/src/file_manager.hpp: In member function 'big::file big::file_manager::get_project_file(std::filesystem::__cxx11::path)':
C:/YimMenu/src/file_manager.hpp:34:124: error: no matching function for call to 'std::exception::exception(const char [69])'
   34 |                                 throw std::exception("Project files are relative to the BaseDir, don't use absolute paths!");
      |
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Sorry YimMenu cannot be compiled using MingW, this is due to technical incompatibilities.

Please see the following issues/PR’s for more info:
#342 
#562 
#334

**Comment by dikivan2000** [comment]
Wow, people really run virtual machines to build this... Huh. Thanks for the help

**Comment by Yimura** [comment]
You can try taking a look at running MSVC under docker however I haven't looked into exactly how that works.

https://hub.docker.com/r/madduci/docker-wine-msvc

**Comment by dikivan2000** [comment]
> This requires a zipped package of a real MSVC installation from Windows

> Requirements: Enough Disk Space for Vagrant and Docker images (50 GByte free recommended)

Might be better off just installing Visual Studio, this sounds like I'll be doing it anyway. Time I did some spring cleaning on C. Thanks for the link though, I'll keep that in mind!
