### ISSUE TITLE
[Bug]: Some players texts in chat do not appear in chat.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1327]
### Describe the bug

While the player is typing a message in the chat, the typing animation appears, but the message he wrote in the chat is not.

### Steps To Reproduce

go near any player

write a post in the chat

then wait for him to write a text in the chat ( luckily, sometimes the message written by the player next to you will not appear in the chat)

### Expected Behavior

message should appear in chat

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Additional context

Most likely, while the chat wants to block spamming bots, normal users' messages may not be visible. I don't know if there is an on/off setting for the protection, but it would be nice to be able to whitelist some players.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
I have no idea if this is specific to yimmenu. I've been playing with a crew that uses a discord server and we come across this issue every day. I'm not using yimmenu during our sessions since it's too buggy but even my texts don't show up for other players sometimes. I'm sure someone is screwing it up for the session but I've no idea what specifically is causing it. We've had chat messages show up in-game on a 20 minute lag.

**Comment by dikivan2000** [comment]
This is not a bug of Yim's. I've been using Kiddions for a while before and my friend is clean, he can be playing a heist with only one other player who is 99% also clean and this happens to him too. I'm thinking either an issue with the session host network configs or just R* being R*

**Comment by Yimura** [comment]
I guess we have established that this is not an issue with YimMenu but lies with the game.

**Comment by Tayipc38** [comment]
Chat commands do still execute at times.
