### ISSUE TITLE
[Request]: Max vehicle for squads

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1328]
### Problem

I noticed that squads spawn with standard vehicles (for example, the Akula does not have rockets and bombs)

### Solution

I think you can add the appropriate checkbox (maximum vehicle), as it was in the vehicle spawn tab for yourself. Or is it still impossible due to some limitations?

### Reason

This will add more weapons for squads, for example, squads on the Akula will have missiles and bombs will appear on the Alkonost. I think that this will add more options to squads and survivability to vehicles if gmod is not enabled.

**Comment by Tayipc38** [comment]
Yes this is actually a good idea. However, I was thinking actually connecting the feature with persistent vehicles. That way the squad vehicle can be fully customizable. Granted you have some vehicles saved in persistent vehicles.
