### ISSUE TITLE
[Bug]: Idle Kick on Unload in Online

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1337]
### Describe the bug

When I am in Online, and I unload the menu, I am instantly hit with an idle kick.

### Steps To Reproduce

1. Enter Online
2. Unload
3. Get Kicked

### Expected Behavior

Not to be idle kicked.

### Screenshots and/or Logs

no logs.

### Store

Steam

### Additional context

I have No Idle Kick Enabled.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by D-Borkan** [comment]
you mean kicked from the game

**Comment by Rxann** [comment]
Like you have been idle for too long please return to gta online

**Comment by D-Borkan** [comment]
I haven't had a problem with this thing , try delete setting file or main folder of the menu

**Comment by maybegreat48** [comment]
You are not meant to unload the menu while online. You can, but you will trigger the anticheat and make your game unstable

**Comment by Rxann** [comment]
Oh...
