### ISSUE TITLE
Features script thread not running

### ISSUE THREAD

**Issue by proxhakkr** [Yimura/YimMenu#134]
**Additional context**
When I click on tabs in the menu (like self), it doesn't work. But when I click on like close menu or unload menu it works, am I doing something wrong here?

**Comment by Yimura** [comment]
Please provide additional information, try to make a video of the issue.

I have never heard of anyone having this problem.

**Comment by proxhakkr** [comment]
I must be dumb...
(https://drive.google.com/file/d/1SI1RoAfdnrrfNdGqy3Iv9ByaARU2LF7X/view?usp=sharing)

**Comment by Yimura** [comment]
Interesting something is broken, I'll see if I can replicate the issue.

**Comment by proxhakkr** [comment]
Ok thanks so much. Ill be here waiting! Do you want me to send you my code?

**Comment by Yimura** [comment]
Could you tell me what you modified to get YimMenu working?
As well as what your system specs are.

**Comment by proxhakkr** [comment]
I followed the guide to remove this line, from premake5 lua, vectorextensions "AVX2".

And my specs are, 
Processor	Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz   3.00 GHz
Installed RAM	12.0 GB (11.9 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by Loko415** [comment]
Try this. Set to windowed borderless in settings

**Comment by proxhakkr** [comment]
That didn't work.

**Comment by Yimura** [comment]
I'm unable to replicate this issue, the natives don't appear to be executing so the features script hasn't been started by the script mgr.

**Comment by proxhakkr** [comment]
I can send my code? or what should i do?

**Comment by Yimura** [comment]
Wait till I might fix it, currently I don't have a fix for this, sending your code is not necessary if all you changed is the vectoredextensions line.

**Comment by proxhakkr** [comment]
Okay, is there an estimated time on a fix? :)

**Comment by Yimura** [comment]
No, at the moment it's not on my todo list, so if you're lucky, maybe in 2 months.

**Comment by proxhakkr** [comment]
Damn. is there another mod menu i can use?

**Comment by Yimura** [comment]
Look on UC, this is not a place to ask such things.

**Comment by proxhakkr** [comment]
I fixed it, I forgot I messed with involker.cpp, but I pasted back in the original code, and it worked. I am so sorry. You may now close this.

**Comment by Yimura** [comment]
![picard-facepalm.jpg](https://user-images.githubusercontent.com/24669514/160248906-25444826-56d8-4e85-9963-3ad369842a60.jpg)
Facepalm moment
