### ISSUE TITLE
[Bug]: Small issue while building dll

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1349]
### Describe the bug

![image](https://github.com/YimMenu/YimMenu/assets/90883505/bf919e56-eaf4-4a18-8469-490ec20c400b)

### Steps To Reproduce

Build -> Build all

### Expected Behavior

No error

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
No doubt caused by #1332. Yet I don't see why the error occurs.

**Comment by Yimura** [comment]
> No doubt caused by #1332. Yet I don't see why the error occurs.

Github actions managed to build it, @howdoiusekeyboard did you regenerate the project after pulling from master? (aka. CTRL + S in the CMakeLists.txt file)

**Comment by howdoiusekeyboard** [comment]
Issue resolved. Thank you. You can close this issue or just let me know
