### ISSUE TITLE
[Bug]: Instant refill of vehicle boost bugs in air vehicles like bombushka JATO and starling

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1350]
### Describe the bug

Boost bar glitches out and the boost function is lost

### Steps To Reproduce

Turn on instant refill boost behaviour and use the particular vehicle

### Expected Behavior

Boost Bar instant refills and works as intended

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by pierrelasse** [comment]
Duplicate?: https://github.com/YimMenu/YimMenu/issues/1945
