### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Akshansh16** [Yimura/YimMenu#1351]
Game is crashing and getting no notifications. Others toxic modders crash my game even when the protection is on. Please have a look into this.

Thank You

**Comment by TheGreenBandit** [comment]
No menu can protect against everything. New crashes are developed daily

**Comment by Tayipc38** [comment]
> Game is crashing and getting no notifications. Others toxic modders crash my game even when the protection is on. Please have a look into this.
> 
> Thank You

At least provide some details. Or share the Event Viewer crash log. Anything but this. And you will almost never be fully protected against toxic p2c users.

**Comment by Akshansh16** [comment]
See the crash event and let me know what's the problem going on! ![IMG_20230515_113340.jpg](https://github.com/YimMenu/YimMenu/assets/97584101/ed6511af-05ab-4bd5-a5bc-cca3cccc3cf5)

**Comment by Yimura** [comment]
Not enough information to resolve issue, closing as the issue has gone stale.
