### ISSUE TITLE
[Bug]: Context Menu : TP on Top

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1352]
### Describe the bug

Whenever I try to Tp to the top of any vehicle using context menu, the game freeze for 0.1 second and an Exception is caught in the console.. But the feature works.

### Steps To Reproduce

1. Go to GTAO
2. Open Context Menu
3. Aim it on a vehicle (with a player inside it, the way i got the issue)
4. Select Tp On Top option
5. You'll get exception on Console.

### Expected Behavior

There shouldn't be an exception..

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11464164/cout.log)

### Store

Rockstar

### Additional context

According to Logs, its unable to call some native.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Does the tp work alongside this exception that occurs?

**Comment by CypherMorgan** [comment]
Yes, I get tp-ed too but it drops an exception

**Comment by xiaoxiao921** [comment]
log say that the exception is thrown while calling 281707892607355002 which is GET_MODEL_DIMENSIONS

could be because of the nullptr being given to it? unsure, the other usage of this native in the codebase always give a valid stack ptr for it

**Comment by Tayipc38** [comment]
> log say that the exception is thrown while calling 281707892607355002 which is GET_MODEL_DIMENSIONS
> 
> could be because of the nullptr being given to it? unsure, the other usage of this native in the codebase always give a valid stack ptr for it

Sounds plausible, i did fail to reproduce however.

**Comment by xiaoxiao921** [comment]
Maybe stale or invalid models
