### ISSUE TITLE
[Bug]: Crash by Stand steamroller

### ISSUE THREAD

**Issue by takoyakiwhite** [Yimura/YimMenu#1355]
### Describe the bug

Lastest YimMenu and maybegreat48's commit (not merge) version can crashed by Stand steamroller crash (if only two players)

### Steps To Reproduce

Steps To Reproduce
Inject Stand (first player)
Join session (two player)
Using Steamroller Crash
Go brrrrrrrrr

### Expected Behavior

Fix it

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/74053919/d4be51fd-759e-4f3f-9a1d-c4b5dc92106f)

### Store

Steam

### Additional context

I think it's need make more invaild node check

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by AriSchmarii** [comment]
If you look at the instruction where the crash occurs, you will see that it accesses an array. This array is the train track array that contains all the train tracks.
**How can this cause a crash?** 
If the index is invalid
**So what is the solution?**
Check if synced track ids are valid . They are synced through the CTrainGameStateDataNode
**When is it invalid?**
the game's track array has the size 26

the rest is up to you :)

**Comment by Tayipc38** [comment]
> If you look at the instruction where the crash occurs, you will see that it accesses an array. This array is the train track array that contains all the train tracks. **How can this cause a crash?** If the index is invalid **So what is the solution?** Check if synced track ids are valid . They are synced through the CTrainGameStateDataNode **When is it invalid?** the game's track array has the size 26
> 
> the rest is up to you :)

He mentioned a Draft that currently does exactly what you have described. Yet it seems checking for track id's within the can_apply_data hook does not prevent the crash. Nor does checking the carriage count. So either the crash occurs further back in the call stack or it does something extra apart from the track id.

**Comment by takoyakiwhite** [comment]
> > If you look at the instruction where the crash occurs, you will see that it accesses an array. This array is the train track array that contains all the train tracks. **How can this cause a crash?** If the index is invalid **So what is the solution?** Check if synced track ids are valid . They are synced through the CTrainGameStateDataNode **When is it invalid?** the game's track array has the size 26
> > the rest is up to you :)
> 
> He mentioned a Draft that currently does exactly what you have described. Yet it seems checking for track id's within the can_apply_data hook does not prevent the crash. Nor does checking the carriage count. So either the crash occurs further back in the call stack or it does something extra apart from the track id.

Yea, it’s so weird,if the session has 3 players, the crash will not work.

**Comment by maybegreat48** [comment]
1. Can you test my fork again?
2. Can you test vanilla (latest YimMenu nightly) with more than 2 players? Does my fork block the crash in this case, or is vanilla immune too?
3. If possible, can you log all the fields in `CTrainGameStateDataNode` during the crash? Can you try blocking the node altogether and see if it prevents the crash?

**Comment by takoyakiwhite** [comment]
> * Can you test my fork again?
> * Can you test vanilla (latest YimMenu nightly) with more than 2 players? Does my fork block the crash in this case, or is vanilla immune too?
> * If possible, can you log all the fields in `CTrainGameStateDataNode` during the crash? Can you try blocking the node altogether and see if it prevents the crash?

1 and 2 I will start test,and 3 I was already test before, CTrainGameStateDataNode return true (no condition) on YimMenu will still got crash

Addition: Steamroller crash not work on 3 or more players session on YimMenu, it’s look like if you are not host, you will not get crash,so it’s weird

**Comment by takoyakiwhite** [comment]
Just finished test, YimMenu nightly will crash quickly, while maybegreat48's fork will crash after several clicks (consecutive click Steamroller button)

@maybegreat48

**Comment by maybegreat48** [comment]
Can I get a full stack trace from the function that the game gets stuck in? My current suspicion is that train request event (`CNetworkTrainRequestEvent`) that apparently gets sent to the host

**Comment by takoyakiwhite** [comment]
> Can I get a full stack trace from the function that the game gets stuck in? My current suspicion is that train request event (`CNetworkTrainRequestEvent`) that apparently gets sent to the host

My friend was offline, test with you will be fast, contact info on my profile

and Already tried to block CNetworkTrainRequestEvent and CNetworkTrainReportEvent, still crashing..

**Comment by AriSchmarii** [comment]
> Can I get a full stack trace from the function that the game gets stuck in? My current suspicion is that train request event (`CNetworkTrainRequestEvent`) that apparently gets sent to the host

This assumption is wrong. If you look at the decide function (the function that decides whether the content should be applied locally on receive (7th index in the vtable )) of the net event, you can see that it checks whether the track idx is greater than 27 (the check for < 0 doesn't matter cause the track index is serialized as an unsigned int -> 4C 8B DC 48 83 EC 48 49 83 63 ? 49 89 53 F0 45 33 C9 48 8D 05 ? ? ? ? 48 8D 51 30 45 8D 41 04 49 89 43 D8 49 8D 4B D8 C6 44 24 ? FF 15 ? ? ? ? 48 83 C4 48 C3 CC). Same goes for the train report event.

The check I mentioned with the track index inside the data node is enough to fix this part of the crash :)

**Comment by maybegreat48** [comment]
> The check I mentioned with the track index inside the data node is enough to fix this part of the crash :)

Yes, but @takoyakiwhite reports that you can be crashed if you are the host even with that fix enabled. You are right though, the serialized int could only ever be 4 bits long (15 is the max index)

The only train related thing that the host manages is that net event and the world grid owner array as far as I know. The net event has a reply component which travels through a different path (will not reach `RECEIVED_EVENT`) so is worth checking out

**Comment by takoyakiwhite** [comment]
Addiction: it’s look like an invalid pos crash, but different than invalid sector pos. Does any one still checking those?

**Comment by ghost** [comment]
We tried this crash with my friend's menu. As far as I can see from the broadcast, when they try this, a train car spawns on my character and its color changes constantly. Then I become unresponsive and only if I restart the computer the problem is solved.

https://youtu.be/884fk67GH2o?t=192 
There is an example in this video.

**Comment by MarkEcza** [comment]
> We tried this crash with my friend's menu. As far as I can see from the broadcast, when they try this, a train car spawns on my character and its color changes constantly. Then I become unresponsive and only if I restart the computer the problem is solved.
> 
> https://youtu.be/884fk67GH2o?t=192 There is an example in this video.

The crash is 2 parts. As of what i've heard if you(receiver) is a host it will send another crash along with Steamroller.
The main steamroller can be patched easily(already is in Yim).
