### ISSUE TITLE
Socialclub appears to have updated making the Presence Data signature invalid

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#1357]
### Discussed in https://github.com/YimMenu/YimMenu/discussions/1356

<div type='discussions-op-text'>

<sup>Originally posted by **KennySpark** May 16, 2023</sup>
Today my social club decided to update and now when i inject the menu i get an error "failed to find 'pd'" in the command prompt window. anybody lknow a fix? thanks</div>

**Comment by scw-1937** [comment]
I can confirm that. Epic Store made me verify the game files and that triggered the Social Club update. I am using the latest YimMenu version (a524009cb719d92b858d1b82680319d94914edfe). Also, I removed the cache file and that did not change the error message.

pointers.cpp line 1412

**Comment by takoyakiwhite** [comment]
Try https://github.com/YimMenu/YimMenu/pull/1358

**Comment by Yimura** [comment]
Fixed with #1358
