### ISSUE TITLE
[Bug]: Need to delete the entire folder after each reboot

### ISSUE THREAD

**Issue by KnollenRick** [Yimura/YimMenu#1372]
### Describe the bug

Hi, why I need to delete the BigBaseV2 folder EVERY TIME after my PC has booted?! Real-time-protection is off and I even reinstalled Windows 10! What is wrong?! 

### Steps To Reproduce

Open GTA V
Open Xenos Injector
Inject DLL
Game’s closing by itself

### Expected Behavior

Just load the menu into GTA V

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Please make a zip of your BigBaseV2 folder after the issue occurs, that way we can reproduce. Currently a fresh install of BigBaseV2 works for me.

**Comment by KnollenRick** [comment]
> Please make a zip of your BigBaseV2 folder after the issue occurs, that way we can reproduce. Currently a fresh install of BigBaseV2 works for me.

Yeah, for me too, but I need to repeat it every time after windows is booted and it works never at the 1st attempt: I need to repeat it approximately 5 times in a row.

**Comment by KnollenRick** [comment]
Hi, here is the ZIP file, I’ve created after the error.
[BigBaseV2.zip](https://github.com/YimMenu/YimMenu/files/11646451/BigBaseV2.zip)
