### ISSUE TITLE
[Request] Player that kicked me from the session.

### ISSUE THREAD

**Issue by Akshansh16** [Yimura/YimMenu#1374]
### Problem

Anonymous player are kicking out from the session. It's difficult to know that who kicked me out. 

Atleast provide notification that who is doing this.

### Solution

Please add a function to know who is kicking out.

### Reason

Kicking out from a session while playing with a good player is vary terrible. And many times doing this is bad for gameplay.

### Additional context

Please have a look into this. And also please provide information if this option is already available in the menu.

Thank Yoy

**Comment by Rimmuru** [comment]
its not always possible to tell who is kicking who, especially when not host. of course, exceptions apply such as script kicks etc

**Comment by Yimura** [comment]
There's no exact way to know who kicked you out, there are some kicks where we know who is trying to kick us out and in those cases we show it and others where we can't know who is kicking us.
