### ISSUE TITLE
[Request]: Turn Siren off/on Option for Emergency Vehicles 

### ISSUE THREAD

**Issue by KnollenRick** [Yimura/YimMenu#1375]
### Problem

In „Menyoo“, there’s an option to (de)activate the siren of an emergency vehicle. I wish it for this menu. For now, I need to turn on the siren and go under water. Lights still on, but the vehicle is broken. Repairing the vehicle and I can drive around without sirens and activated lights. XD 

### Solution

In the vehicle controller, could be an option to turn off emergency lights.

### Reason

This is a cool and usefull feature.

**Comment by Tayipc38** [comment]
`SET_VEHICLE_SIREN`

**Comment by KnollenRick** [comment]
> SET_VEHICLE_SIREN

Is this an additional file or where can I find this option? In the vehicle controller is this option not listet.

**Comment by Tayipc38** [comment]
> > SET_VEHICLE_SIREN
> 
> Is this an additional file or where can I find this option? In the vehicle controller is this option not listet.

It is a native function registered within the game which you may utilize with the invoker that yimmenu provides you.

**Comment by KnollenRick** [comment]
I don’t understand, how to find this option?
Step 1 > Step 2 > Step 3

THX :)

**Comment by Tayipc38** [comment]
> I don’t understand, how to find this option? Step 1 > Step 2 > Step 3
> 
> THX :)

It is not on option that is currently present on YimMenu. I had hoped you may have some experience coding so that you may create this simple feature yourself and maybe even share it with the community by contributing it. For beginners, it is advised to surf through the codebase and observe how other contributors have written code to create features. The feature this issue is about could be compared with say the options on the Vehicle tab UI. I fear you may have misinterpreted what I meant with "native functions" and im affraid it would take a tad bit longer to explain than the time I have.

**Comment by CypherMorgan** [comment]
I made this, but there's an issue. If i disable siren in a car and then enable it, the siren wont work unless i use another car.

**Comment by KnollenRick** [comment]
> > I don’t understand, how to find this option? Step 1 > Step 2 > Step 3
> > THX :)
> 
> It is not on option that is currently present on YimMenu. I had hoped you may have some experience coding so that you may create this simple feature yourself and maybe even share it with the community by contributing it. For beginners, it is advised to surf through the codebase and observe how other contributors have written code to create features. The feature this issue is about could be compared with say the options on the Vehicle tab UI. I fear you may have misinterpreted what I meant with "native functions" and im affraid it would take a tad bit longer to explain than the time I have.

I have absolutely no coding skills, so IDK. I hope for a step-2-step tutorial. 😅🙈

**Comment by CypherMorgan** [comment]
> > > I don’t understand, how to find this option? Step 1 > Step 2 > Step 3
> > > THX :)
> > 
> > 
> > It is not on option that is currently present on YimMenu. I had hoped you may have some experience coding so that you may create this simple feature yourself and maybe even share it with the community by contributing it. For beginners, it is advised to surf through the codebase and observe how other contributors have written code to create features. The feature this issue is about could be compared with say the options on the Vehicle tab UI. I fear you may have misinterpreted what I meant with "native functions" and im affraid it would take a tad bit longer to explain than the time I have.
> 
> I have absolutely no coding skills, so IDK. I hope for a step-2-step tutorial. 😅🙈

I've Made Pull Request for the Feature, waiting on Merge.
