### ISSUE TITLE
Error While Building

### ISSUE THREAD

**Issue by 0xTheago** [Yimura/YimMenu#1376]
I Get This Type Of Error 
"#include YimMenu/build/_deps/asynclogger-build/CMakeFiles/AsyncLogger.dir/Release/cmake_pch.hxx"" einzufügen?	AsyncLogger	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\modules\std.ixx

and this one 
"_deps\asynclogger-build\Release\AsyncLogger.lib"  Cannot open

**Comment by tyackman** [comment]
Same issue here, both with my source & a fresh unmodified one. I just updated my visual studio to the most recent version this morning.

**Comment by 0xTheago** [comment]
> Same issue here, both with my source & a fresh unmodified one. I just updated my visual studio to the most recent version this morning.

i have it now but looking how ill use the ninja builder in vs if u have discord Write it i can help u out now

**Comment by tyackman** [comment]
I'm able to compile fine w/o using pre compiled headers for ASyncLogger, just thought this was odd, especially since you posted @ the pretty much the same time I ran into the issue.
