### ISSUE TITLE
[Bug]: Unable to go to Animations from Threads

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1377]
### Describe the bug

Weird bug where the user is unable to go to the Animations tab when under the Threads tab

### Steps To Reproduce

1. Go to Debug
2. Go to Threads
3. Then try to go to Animations

### Expected Behavior

It should just go to the Animations tab

### Screenshots and/or Logs

https://github.com/YimMenu/YimMenu/assets/88204341/86f2c7b8-f27c-43aa-8f5c-1e1a505a8561

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Probably a bug in the threads tab not being properly closed.
I'll take a look.
