### ISSUE TITLE
[Bug]: GodMode Off Walk underwater 

### ISSUE THREAD

**Issue by 0xTheago** [Yimura/YimMenu#1379]
### Describe the bug

GodMode Turned Off u can't swim u walk underwater

Btw GodMode i fixed it to turn on and off

### Steps To Reproduce

/

### Expected Behavior

/

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by CypherMorgan** [comment]
Make sure you have Water and Drown Proofs Disabled in Self Tab. This would let ur character swim.

**Comment by Yimura** [comment]
Make sure water proof is disabled otherwise your character will ignore water physics and not start swimming.
