### ISSUE TITLE
[Bug]: Incomplete Exception Logs

### ISSUE THREAD

**Issue by Peax** [Yimura/YimMenu#1384]
### Describe the bug

Exception logs don't contain a stack dump after a game crash.

Maybe related to #1303.

### Steps To Reproduce

Crash GTA.

### Expected Behavior

Complete exception logs.

### Store

Steam

### Additional context

My YimMenu build hash is 118c9ac. I only play in closed-friend sessions with max. 4 players.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
The exception logging implementation has since been changed, cannot replicate anymore.
