### ISSUE TITLE
[Bug]: Remove all weapons does not work

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1393]
### Describe the bug

When you press remove all weapons in the Session section you will get a crash without logs

### Steps To Reproduce

1. Open the Session section
2. Press the Remove all weapons button
3. Get crash

### Expected Behavior

Weapons must be removed from everyone in the session

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This should be fixed.
