### ISSUE TITLE
[Bug]: get_network_event_data CEventNetwork

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#1398]
### Describe the bug

This hook currently does work yet it seems the events aren't firing. Or rather the class might be faulty as any check on whether an event has been received does not work. 

For example:
![image](https://github.com/YimMenu/YimMenu/assets/79384354/3d1aca89-49b0-4205-a9cc-b5b22a92b22a)
Assuming this event is a rather frequent one, the log underneath should print at some point. Yet for an extended period of time it has remained dormant. Which leads me to think the class from which its gathered (`rage::CEventNetwork`) might be faulty for say the `get_type()` member.

### Steps To Reproduce

1. Log any event within `get_network_event_data `
2. Observe it not even firing once

### Expected Behavior

The `get_type()` member should fetch the event. Right now a very important mod detection is out of order due to this not working.
The detection in question is `CEventNetworkEntityDamage` event on players with god mode.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Vali0004** [comment]
Either I’m tripping or no one updated CEventNetwork and the vTable should have the RTTI class, but doesn’t
- EDIT: Looked at my personal classes that work, and it does indeed have atRTTI

**Comment by Tayipc38** [comment]
> Either I’m tripping or no one updated CEventNetwork and the vTable should have the RTTI class, but doesn’t
> 
> * EDIT: Looked at my personal classes that work, and it does indeed have atRTTI

So the class is faulty?

**Comment by Vali0004** [comment]
> > Either I’m tripping or no one updated CEventNetwork and the vTable should have the RTTI class, but doesn’t
> > 
> > * EDIT: Looked at my personal classes that work, and it does indeed have atRTTI
> 
> So the class is faulty?

In short, yes. No one ever updated it. I just made the PR to fix it

**Comment by Vali0004** [comment]
Issue was fixed in #1399, should be closed

**Comment by Tayipc38** [comment]
The class was misaligned, fixed with the help of @Faint0002
