### ISSUE TITLE
Menu doesn't open, caused by minhook.x64.dll not being present

### ISSUE THREAD

**Issue by ThatKakiGuy** [Yimura/YimMenu#14]
Ok, so it's building and injecting now, but nothing happens when I press insert.
Do I need to do any other setup?

**Comment by Yimura** [comment]
I deleted all the files my menu needs and injected my menu clean without any modifications.

It works for me, give me a log file, or anything else that might help me.
If the INSERT key doesn't exist on your keyboard you can modify the key to open the menu in [this file](https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/renderer.cpp#L111).

Aside from that I believe the problem lies with your setup.

**Comment by karifeld** [comment]
Does your cpu support AVX2? @ThatKakiGuy 

Try changing code generation to SSE or SSE2

**Comment by ThatKakiGuy** [comment]
Ok, so I tried changing code generation to SSE2, and modifying the key to be NUMPAD0, nothing changed.. I can't find any log files either(I looked in the directory of the dll and in the gtaV directory), but the injector says it injected it.
I don't think my CPU(Intel i7-6820HQ) is the problem, it's not that old..
Does Epic/Steam make a difference(I'm using the version from epic games)?

**Comment by ThatKakiGuy** [comment]
![InjectorOutput](https://user-images.githubusercontent.com/96546251/147340014-f05b7911-f98d-497c-906c-0f6ade45ecc5.PNG)

**Comment by Yimura** [comment]
There's not a whole lot I can do to fix this as I've never had the opportunity to debug such an issue.

Anything else that comes to mind that might prevent the DLL from starting?
Anti virus software or something else, like bios settings that disable certain features?

Edit: I have used it personally on Steam and Epic games but can also say it works for people on Social Club editions

**Comment by ThatKakiGuy** [comment]
I disabled Realtime protection and pretty much everything else in Windows Defender.
Nothing is disabled in Bios settings.

**Comment by ThatKakiGuy** [comment]
I tried injecting with Cheat Engine, and I an error.
![error](https://user-images.githubusercontent.com/96546251/147347274-b8ef6955-5390-445f-8995-a6fbcb46a39b.png)
.

**Comment by Yimura** [comment]
Interesting, ye my injector isn't so advanced that it will confirm if the DLL managed to start.

Seems strange that it would require minhook to be present, I thought it would be statically linked inside the DLL.

**Comment by ThatKakiGuy** [comment]
Ok, after putting minhook.x64.dll into the GTAV directroy it worked

**Comment by Yimura** [comment]
> Ok, after putting minhook.x64.dll into the GTAV directroy it worked

Good job finding this out, I will clean install my system some time in the future and see if this causes the same issues you've been having.

I will keep this issue open so others can find it if they have similar problems.

**Comment by xiaoxiao921** [comment]
https://github.com/Yimura/YimMenu/blob/master/premake5.lua#L117 minhook is statically linked to yimmenu so that error cannot phyiscally happen when you use premake

**Comment by Yimura** [comment]
> https://github.com/Yimura/YimMenu/blob/master/premake5.lua#L117 minhook is statically linked to yimmenu so that error cannot phyiscally happen when you use premake

Ye exactly that's what I don't get, I thought it would be impossible to get such an error but somehow he did.
