### ISSUE TITLE
[Request]: Change the No-Clip speed?

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1400]
### Problem

Hello, I would like to be able to change the no-clip speed because it would be very useful when I wanna travel faster, without using the map to teleport.

### Solution

Add an option somewhere in the menu in order to change the no-clip speed.

### Reason

Typically this would be useful when I sell stuff from my business, on that one mission with the 3 boats, where you deliver the stuff into 5 checkpoints on the sea. 

### Additional context

.

**Comment by alyxme** [comment]
AFAIK max speed is 540Km/H and noclip in menu uses native movement with speed restricted to its max. But "teleported noclip" like in Kid*os or others menu theoreticaly havent speed limit but not presented with Yim. Maybe you have to use hotkey to TP to objective?

**Comment by BUZZARDGTA** [comment]
@alyxme In this one mission, the TP to objective teleport to the wrong objective. Like there are 5 objectives right, and it teleports you to the next one from the current objective you have to go to.

**Comment by alyxme** [comment]
issue should be closed. noclip speed can be adjusted now
