### ISSUE TITLE
[Request]: Improve "Outfit Editor".

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1402]
### Problem

Is it only me or the current outfit editor is super complicated to use for creating custom outfits from scratch?
I mean you really have to type the number index of each stuff manually with the keyboard?

### Solution

I would like the devs to add a [+] or [-] clickable button on the menu to scroll trough the index of the selected outfit prop.
If that is not possible for some reasons to do, then maybe they can make the user's keyboard [+] and [-] keys to do the same behaviour?

### Reason

.

### Additional context

.

**Comment by alyxme** [comment]
Yes, at now we have to enter each number of Editor box manually with keyboard. Making control arrows or [+] [-] buttons would be great addition. Hope we see this in future releases. That would be is much useful. Bump
