### ISSUE TITLE
[Request]: Add auto disarm weapon from peds.

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1403]
### Problem

In GTA Online heists, when peds shoot your character, or those from your teamates, you loose money.
It would be very useful to have an option that automatically remove the weapons from the peds that are around.

### Solution

.

### Reason

.

### Additional context

There is already an option to make peds ignore you but that probably won't work (i didn't actually tried that option) if you are playing with your teammates, they will still get shooten from the peds.

**Comment by BUZZARDGTA** [comment]
And yes I mean automatically, like a loop. Because in Cayo peds are spawning infinite. So it would needs to continiously do that work. If the player wanna do it only once he can just enable the checkbox and disabled it right away lol

**Comment by BUZZARDGTA** [comment]
I'm guessing that if you disarm the peds's weapons they will still come and fight your character with hands, maybe make them automatically playing an infinite animation would be an easy fix for that issue?

**Comment by Tayipc38** [comment]
Make up your mind guy

**Comment by BUZZARDGTA** [comment]
@DayibBaba Why, what do you mean?

**Comment by BUZZARDGTA** [comment]
I'm guessing you mean that if they are into an animation they don't need to disarm the weapon, that's true, but the menu can add both options, these are just suggestions, the owner is free to decide if he wanna implement this or that, and how he want to do it...

**Comment by CypherMorgan** [comment]
Just automatically removing the spawned peds would be an easier way.

**Comment by Tayipc38** [comment]
So let me get it straight. Besides disarming surrounding attackers of their weapons, you'd like them to be stripped of any hostile capabilities? Should they remain or could they just be removed?

**Comment by BUZZARDGTA** [comment]
@CypherMorgan No, this option already exists in YimMenu and it fails the missions if the mission peds get removed.

**Comment by BUZZARDGTA** [comment]
@DayibBaba You got it right, and as I said they should not be removed

**Comment by Tayipc38** [comment]
> @DayibBaba You got it right, and as I said they should not be removed

Ill see what I can muster.

**Comment by CypherMorgan** [comment]
> @CypherMorgan No, this option already exists in YimMenu and it fails the missions if the mission peds get removed.

Ah, Okay.
