### ISSUE TITLE
[Request]: Delete previous spawned car.

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1404]
### Problem

It would be useful to have a checkbox that allow deleting the previously spawned car.

### Solution

.

### Reason

This would simply avoid making a huge mess of spawned cars when you spawn a bunch of them.

### Additional context

.

**Comment by V1RU513N** [comment]
Duplicate of https://github.com/YimMenu/YimMenu/issues/1369

**Comment by Yimura** [comment]
Duplicate of #1369
