### ISSUE TITLE
[Bug]: Upgrade to 1.67

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1406]
### Describe the bug

Must be updated online to 1.67 and build to 2944

### Steps To Reproduce

...

### Expected Behavior

.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by CypherMorgan** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/11734000/cout.log)
The Log File.

**Comment by Tayipc38** [comment]
The signatures should not be an issue but the globals and locals do need decompiled scripts to be updated.
