### ISSUE TITLE
[Request]: Enforce spaces / line ending in a commit checker

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#1409]
### Problem

the clang format use tabs, not sure why? I propose https://github.com/YimMenu/YimMenu/blob/master/.clang-format#L67

UseTab: Never

### Solution

A simple github action that check for any `\t` and make the pr not mergeable would be a great thing imo

### Reason

incoming pr / whats on the repo always differ, which break git diffs / make them much more annoying to read

**Comment by tupoy-ya** [comment]
I thought YimMenu prefers tabs over spaces.
https://github.com/YimMenu/YimMenu/blob/master/CONTRIBUTING.md#indents

Why even not allow tabs besides breaking git diffs which should be fixed in the opposite way?

**Comment by xiaoxiao921** [comment]
the pr is more about an unified way of doing it
