### ISSUE TITLE
[Request]: Change Player Model

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1411]
### Solution

The Abillity to change to any model in the game like Franklin , Lamar , Lester , Animal's etc.
So add a menu to self and make a dropdown menu and a search like Spawn Ped in World.

### Reason

1. Most of menu's have this feature so why not add it?
2. Technically another way of spoofing your model.

**Comment by ghost** [comment]
Is it not possible to do this here(press Change Player Model) or do you mean something else
![pic](https://github.com/YimMenu/YimMenu/assets/136161998/2ab58e0a-e6e8-4a9d-afdf-16a839ca05aa)

**Comment by rrAsus** [comment]
> Is it not possible to do this here(press Change Player Model) or do you mean something else ![pic](https://user-images.githubusercontent.com/136161998/245946840-2ab58e0a-e6e8-4a9d-afdf-16a839ca05aa.png)

i think that it should have it's own category and how do you have player two?

**Comment by ghost** [comment]
By the way, why does the player respawn after death in a standard character without an initial outfit?

**Comment by rrAsus** [comment]
> By the way, why does the player respawn after death in a standard character without an initial outfit?

you mean bald with blue shirt and jeans?

**Comment by ghost** [comment]
> > By the way, why does the player respawn after death in a standard character without an initial outfit?
> 
> you mean bald with blue shirt and jeans?

Yes, that's what I meant

**Comment by rrAsus** [comment]
> > > By the way, why does the player respawn after death in a standard character without an initial outfit?
> > 
> > 
> > you mean bald with blue shirt and jeans?
> 
> Yes, that's what I meant

you got any blacklisted accessory? police belt?

**Comment by ghost** [comment]
> > > > By the way, why does the player respawn after death in a standard character without an initial outfit?
> > > 
> > > 
> > > you mean bald with blue shirt and jeans?
> > 
> > 
> > Yes, that's what I meant
> 
> you got any blacklisted accessory? police belt?

no i was just dressed as an alien with a big brain

**Comment by rrAsus** [comment]
> > > > > By the way, why does the player respawn after death in a standard character without an initial outfit?
> > > > 
> > > > 
> > > > you mean bald with blue shirt and jeans?
> > > 
> > > 
> > > Yes, that's what I meant
> > 
> > 
> > you got any blacklisted accessory? police belt?
> 
> no i was just dressed as an alien with a big brain

then i've got no idea

**Comment by rrAsus** [comment]
@X-Kebab-Remover-X so tell me how do you have player 2?

**Comment by ghost** [comment]
> @X-Kebab-Remover-X so tell me how do you have player 2?

in order for you to have player_two and other characters, you need to delete the cache from the BigBaseV2 cheat folder and update the cache on init in the main menu for selecting the game mode then u should choose singleplayer

**Comment by rrAsus** [comment]
> > @X-Kebab-Remover-X so tell me how do you have player 2?
> 
> in order for you to have player_two and other characters, you need to delete the cache from the BigBaseV2 cheat folder and update the cache on init in the main menu for selecting the game mode then u should choose singleplayer

i don't have it

**Comment by ghost** [comment]
> > > @X-Kebab-Remover-X so tell me how do you have player 2?
> > 
> > 
> > in order for you to have player_two and other characters, you need to delete the cache from the BigBaseV2 cheat folder and update the cache on init in the main menu for selecting the game mode then u should choose singleplayer
> 
> i don't have it

when you delete the cache then boot back to the main menu where there is a choice between single player and online mod and inject the cheat there.  then click "update cache on init" and after that click singleplayer

**Comment by rrAsus** [comment]
Thank you

> > > > @X-Kebab-Remover-X so tell me how do you have player 2?
> > > 
> > > 
> > > in order for you to have player_two and other characters, you need to delete the cache from the BigBaseV2 cheat folder and update the cache on init in the main menu for selecting the game mode then u should choose singleplayer
> > 
> > 
> > i don't have it
> 
> when you delete the cache then boot back to the main menu where there is a choice between single player and online mod and inject the cheat there. then click "update cache on init" and after that click singleplayer

it works! Thanks.
