### ISSUE TITLE
[Request]: More detailed injection instructions/linux guide?

### ISSUE THREAD

**Issue by hl2jeep** [Yimura/YimMenu#1418]
### Problem

I have a steam deck and i'm kinda stumped how to get dll injection to even work on linux, the injectors i tried can all see the gta executable, however, they all fail on inject, i know some other injectors that possibly work under proton/wine but i don't know if they are detected by gta. 

### Solution

It would be nice to have some more info on injectors as currently apart from looking up sketchy youtube tutorials, there is no offical proper guide to injection.

### Reason

My main reason is that in theory i could run windows on my steam deck but performance would completely be thrown into the drain, gtao already is better laggy on lowest settings and running it on windows would make it unplayable.

### Additional context

Just as an fyi, I do know about proton pressure-vessel and all that crap and i've worked around that already, i'm purely stuck with the injection itself.

**Comment by tupoy-ya** [comment]
No injectors are detected by GTA V as far i know.

##### Proton/Wine/Linux/Gnu

You can read #334 for more information.

Basically Cheat Engine injection should work but i personally didn't try it.

Also this version https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/v4.68 of Ultimate-ASI-Loader works as `bink2w64.dll`.
Also also this old version of GH Injector works.
 https://www.unknowncheats.me/forum/counterstrike-global-offensive/203230-gh-injector-source-included.html

**Comment by hl2jeep** [comment]
The asi loader thing seems interesting. Would that just be renaming the menu from dll to asi?

**Comment by tupoy-ya** [comment]
> The asi loader thing seems interesting. Would that just be renaming the menu from dll to asi?

Yes rename `YimMenu.dll` to `YimMenu.asi` and put it in `Grand Theft Auto V/scripts` folder.

**Comment by hl2jeep** [comment]
Thanks for the info, still I think some guides for injection could be a good idea to consider, closing this for now.
