### ISSUE TITLE
Crash while loading in public session (send_net_info_to_lobby)

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#142]
**Describe the bug**
With your latest update, I am crashing while loading into a public online session, invite-only works fine tho. I am spoofing my ingame name "MoneyDropLobby" and my IP "68.68.65.49". I turned the spoofing off and tried to load a session but that's not the problem I guess.

**To Reproduce**
1. Inject menu in SP
2. Join Public Session
3. Error while loading in (clouds)

**Expected behavior**
Shouldn't crash at all.

**Screenshots**
![Uploading image.png…]()

**Logs**
*******	STACKDUMP *******
stack dump [0]		C:\Users\Ashu\YimMenu\BigBaseV2\src\hooks\send_net_info_to_lobby.cpp L: 8 big::hooks::send_net_info_to_lobby
stack dump [1]	
stack dump [2]	
stack dump [3]	
stack dump [4]	
stack dump [5]	
stack dump [6]	
stack dump [7]	
stack dump [8]	
stack dump [9]	
stack dump [10]	
stack dump [11]	
stack dump [12]	
stack dump [13]	
stack dump [14]	
stack dump [15]	
stack dump [16]	
stack dump [17]	
stack dump [18]	 BaseThreadInitThunk
stack dump [19]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Yimura** [comment]
Could you post which data exactly you're spoofing, as well as the values?

**Comment by MoneyDropLobby** [comment]
> Could you post which data exactly you're spoofing, as well as the values?

Updated the description :)

**Comment by MoneyDropLobby** [comment]
Does it crash too on your PC?

**Comment by Yimura** [comment]
Sorry I don't have the time to test it now.

**Comment by Z3nWare** [comment]
Try setting it to this ip: 
`		int ip_address[4] = { 103, 163, 187, 105 };`

**Comment by MoneyDropLobby** [comment]
> 

as it is written, I switched off the whole spoofing and it crashes.

**Comment by Yimura** [comment]
Unable to replicate, care to share your settings.json file?

Try removing your settings.json and see if the problem persist.

**Comment by MoneyDropLobby** [comment]
> Unable to replicate, care to share your settings.json file?
> 
> Try removing your settings.json and see if the problem persist.

Yeah will try that tomorrow, don't have a PC at the moment 👍🏼

**Comment by MoneyDropLobby** [comment]
I downloaded everything again from your github repo and now its working... strange. You can close this issue :)
