### ISSUE TITLE
[Bug]: Delayed in game chat messages from friends

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#1420]
### Describe the bug

I have limited experience with this bug. Don't even know whether its caused by the menu, but it seems chat messages from friends arrive in a delayed pace. 

### Steps To Reproduce

1.Have a friend
2.Make him write something in the in game chat
3.Observe the delay (which can be minutes)

### Expected Behavior

Chat should just act natural.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by CypherMorgan** [comment]
Tested this with my non modder friend, its a game bug.

**Comment by ghost** [comment]
#1327 Almost a similar problem here, probably due to the game.

**Comment by Tayipc38** [comment]
> #1327 Almost a similar problem here, probably due to the game.

Seems like ive made a duplicate issue
