### ISSUE TITLE
not work after gta5 update

### ISSUE THREAD

**Issue by ikategame** [Yimura/YimMenu#1429]
i cloned last stuff from github and compiled but game crash after recent update, its your issue right?

**Comment by Yimura** [comment]
Please follow the Bug report template if you're planning to report issues with YimMenu.

You do understand that this issues offers me no information at all in regards to helping you right?
What you can try to do is remove the `%appdata%/BigBaseV2/` folder and then inject YimMenu.
Also use a known good injector, I've personally used Process Hacker 2 to inject YimMenu for a long time.
Xenos Injector should also be a good option.

**Comment by ikategame** [comment]
can i get vac banned btw?

**Comment by ikategame** [comment]
can i get a vac in thee future for the cheat?

**Comment by Yimura** [comment]
> can i get a vac in thee future for the cheat?

You're going off topic of this issue, however this link may give you an answer to your question.

https://letmegooglethat.com/?q=is+gta+v+vac+secured

**Comment by ikategame** [comment]
it works,....
