### ISSUE TITLE
[Bug]: Breakup kick in reaction settings

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1430]
### Describe the bug

When any player who has been blocked from the session tries to join our session again, the menu sends him a breakup kick.
If I'm not mistaken, this kick type no longer works (because it doesn't show up under the kick tab).

### Steps To Reproduce

Select and block a player you don't want to join your session.

Wait for the player to join your server again (if he joins)

Observe the warning.

### Expected Behavior

If breakup kick is not used, another effective method can be tried.

### Screenshots and/or Logs

[23:31:20.9201127][WARN/reaction.cpp:25] Received TSE Sender Mismatch from Olxxxxx (220493859)
[23:33:49.6632492][WARN/assign_physical_index.cpp:116] Sending Breakup Kick due to block join failure...

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Akshansh16** [comment]
Yes, that's correct! Breakup Kick is no longer available on the menu as I'm using the latest 1.67 version updated menu.

I think it's any part of securities? Or maybe a rockstar detected the issue and fixed that so that it was removed.

Let's wait for the developer's reply
