### ISSUE TITLE
[Bug]: Personal Vehicle spawning

### ISSUE THREAD

**Issue by Vasto525i** [Yimura/YimMenu#1432]
### Describe the bug

Does not work. always returns "Mechanic is not ready to deliver a vehicle right now" regardless of what option I select.

### Steps To Reproduce

1. Go to Vehicle, personal vehicle
2. try spawning any personal vehicle
3.  "Mechanic is not ready to deliver a vehicle right now" 

### Expected Behavior

Spawn personal vehicle

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This should have been fixed by #1415, can you download the nightly again and check if it works?

**Comment by Vasto525i** [comment]
Can confirm Nightly [6aa713c] fixes this issue

  Online version 1.67 Game build 2944

Thank you for the quick response Yimura

**Comment by Vasto525i** [comment]
Closed then
