### ISSUE TITLE
[Bug]: Operations Center unavailable with menu running

### ISSUE THREAD

**Issue by dikivan2000** [Yimura/YimMenu#1433]
### Describe the bug

"Operations Center is unavailable right now" when approaching the screen with menu running. Unloading menu and switching sessions fixes this.

### Steps To Reproduce

1. Load menu whenever
2. Go to Avenger
3. Enjoy the view

### Expected Behavior

![2](https://github.com/YimMenu/YimMenu/assets/24930030/854311c2-d16a-448f-87b9-6ff7a7008f83)
Works smoothly

### Screenshots and/or Logs

![1](https://github.com/YimMenu/YimMenu/assets/24930030/3623e310-0d2d-4550-beeb-dca9569ce2ed)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by dikivan2000** [comment]
Forgot to add - the log also says there was a fatal error caching variables, so that might be related. Will upload in an hour or so, no access to the menu rn

**Comment by Nagahanakun** [comment]
Yup I'm running into same issue as well

[FATAL/tunables_service.cpp:87] Failed to cache tunables

**Comment by dikivan2000** [comment]
Update: I just launched the game and everything is working perfectly fine, and I no longer get the error mentioned above. I did not update the menu nor the game. Something is going on...

**Comment by LobaDK** [comment]
R* recently (within a few hours) dropped two tuneable updates in hopes of fixing a major issue with personal vehicles disappearing, related to the MOC. Since they require a game restart to apply, maybe this was the cause?

**Comment by Democles85** [comment]
I couldn't join it as well. Tried right now without the menu and I could access it. Weird :[

Edit: Could be one of the protections from the menu that is disabling Force CEO or something, who knows how Rockstar have implemented the Boss thing.

**Comment by dikivan2000** [comment]
> Could be one of the protections from the menu that is disabling Force CEO or something

Wouldn't say so (in the sense that it is the menu's fault). I got everything on and did not change everything between runs. This all happened last night, so even if it IS one of the protections, R* seems to have patched it. Either that or @LobaDK's version. I'll keep it open for the time being so that we can collect more info if anyone has any, but my issue has been resolved

**Comment by Democles85** [comment]
> > Could be one of the protections from the menu that is disabling Force CEO or something
> 
> Wouldn't say so (in the sense that it is the menu's fault). I got everything on and did not change everything between runs. This all happened last night, so even if it IS one of the protections, R* seems to have patched it. Either that or @LobaDK's version. I'll keep it open for the time being so that we can collect more info if anyone has any, but my issue has been resolved

To me, as well, last night. Since then, I have changed some things to YimMenu and added keep engine running functionality. Tried today, and it's the same thing... IDK, could be Rockstar that is on crack like always.

**Comment by Democles85** [comment]
Same thing right now :[

<img width="1920" alt="Screenshot_4" src="https://github.com/YimMenu/YimMenu/assets/42782503/f7c77243-ac77-4919-ba44-525328057488">

## EDIT
Playing through Epic Games Launcher, that may be a cause, IDK

**Comment by Democles85** [comment]
Also, quick question, would it be safe if I inject the menu while in a mission or in an Online session?

**Comment by dikivan2000** [comment]
> Also, quick question, would it be safe if I inject the menu while in a mission or in an Online session?

Should be. I inject whenever, usually on startup though. Still playing

**Comment by inthecatsdreams** [comment]
I'm having the same issue.
![20230617131009_1](https://github.com/YimMenu/YimMenu/assets/68013505/ef21a895-eeb5-4dda-aac5-ddefa12568ec)

**Comment by dikivan2000** [comment]
Probably part of #1442

**Comment by maybegreat48** [comment]
This has nothing to do with the tunables service failing. I cannot reproduce this. Can you please share your settings file?
Edit: this might actually have something to do with the tunables service failing. Weird

**Comment by dikivan2000** [comment]
> This has nothing to do with the tunables service failing.

Weird. Every time I got this there was a fatal error in the log, and whenever there wasn't one, everything worked... Since I haven't changed anything I'll drop the settings file (too)

**Comment by inthecatsdreams** [comment]
> Playing through Epic Games Launcher, that may be a cause, IDK

It has nothing to do with EGL, all versions are affected, I tried on all of them (steam, r* and epic) I also get the tunable error like everyone else in this thread

**Comment by maybegreat48** [comment]
The script patches aren't being cleaned up properly when the tunable service fails, causing all bool tunables to become corrupted during session join. I've fixed this in my branch

**Comment by Democles85** [comment]
> The script patches aren't being cleaned up properly when the tunable service fails, causing all bool tunables to become corrupted during session join. I've fixed this in my branch

Can you give any info on how to fix it?

**Comment by maybegreat48** [comment]
https://github.com/maybegreat48/YimMenu/commit/95afb4ca85a953abb389a07cbfc9513d4a7439a1#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c

**Comment by inthecatsdreams** [comment]
> [maybegreat48@95afb4c#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c](https://github.com/maybegreat48/YimMenu/commit/95afb4ca85a953abb389a07cbfc9513d4a7439a1#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c)

I just tested this and it worked for me, I can use the avenger terminal and no more tunable error :)

**Comment by LobaDK** [comment]
I am not sure if this is related to this, but I noticed, upon creating a new account for testing this menu, and injecting it at game start, all dripfeed vehicles have become available to me

edit: I have not tried the fix by @maybegreat48

**Comment by Nagahanakun** [comment]
> > [maybegreat48@95afb4c#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c](https://github.com/maybegreat48/YimMenu/commit/95afb4ca85a953abb389a07cbfc9513d4a7439a1#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c)
> 
> I just tested this and it worked for me, I can use the avenger terminal and no more tunable error :)

Can u guide me ?

**Comment by Democles85** [comment]
> > > [maybegreat48@95afb4c#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c](https://github.com/maybegreat48/YimMenu/commit/95afb4ca85a953abb389a07cbfc9513d4a7439a1#diff-cab503562b5aed0a49212f12a8d1f4b4682c322774f16a5381390b637fe4824c)
> > 
> > 
> > I just tested this and it worked for me, I can use the avenger terminal and no more tunable error :)
> 
> Can u guide me ?

Do you know how to compile the code? If not, just type to me on discord or read the README on GitHub repo. :D

## EDIT
My discord (best_peerat)
