### ISSUE TITLE
[Bug]: Yim Menu crashing Game

### ISSUE THREAD

**Issue by RobinGrasmueck** [Yimura/YimMenu#1435]
### Describe the bug

Game crashing right after injection of Yim Menu 

### Steps To Reproduce

1. Start GTA V
2. Open the Injector and select YimMenu and the GTA5.exe process
3. Inject the YimMenu.dll file

### Expected Behavior

Upon injection a CMD like window pops up without any text in it and after about 1-5 seconds of Frozen Frame both GTA and the cmd window are closing

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

I already tried the new version for San Andreas Mercenaries today but it didnt fix the bug

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by RobinGrasmueck** [comment]
PS: Multiple of my friends using YIm Menu had the same problem

**Comment by Democles85** [comment]
What program do you use to inject the menu?

**Comment by RobinGrasmueck** [comment]
I have multiple injectors and nothing worked for example with AlisaAlis Injector, Cheat Squad or Xenos injector

**Comment by Democles85** [comment]
You have the nightly build, right? I will give it a try and see.

**Comment by RobinGrasmueck** [comment]
Whats nightly build?

**Comment by Democles85** [comment]
> Whats nightly build?

This one -> https://github.com/YimMenu/YimMenu/releases/tag/nightly
Or you can go to the official website here: https://yim.gta.menu/

I have tried the injection, and it does not crash my game, please check if you have the latest version.

**Comment by RobinGrasmueck** [comment]
Ah Yes i downloaded it like 2 hours ago but my game kept crashing

**Comment by RobinGrasmueck** [comment]
What injector are you using?
Maybe i should try another one

**Comment by Democles85** [comment]
> Ah Yes i downloaded it like 2 hours ago but my game kept crashing

Can you be a little more specific on which part your game is crashing?
When are you injecting?

**Comment by Democles85** [comment]
> What injector are you using? Maybe i should try another one

I use Process Hacker 2.

**Comment by RobinGrasmueck** [comment]
Well anything i try. I tried doing it right on the start when i click on play in Rockstar but also did in Loading screen, when i joined the game and even after playing for some time nothing worked for me

**Comment by Yimura** [comment]
When using Xenos injector don't modify any of the settings use `Native inject - common approach using LoadLibraryW \ LdrLoadDll in newly created or existing thread`.

Or use Process Hacker 2 which only supports native inject (aka. LoadLibraryA/W with CreateRemoteThread)

You can also try and remove the `%appdata%/BigBaseV2/` folder to see if that changes something.

**Comment by RobinGrasmueck** [comment]
Ok ill try again with Process hacker 2

**Comment by RobinGrasmueck** [comment]
Well it still keeps crashing but i dont know what im doing wrong if it works fine for everyone

**Comment by xiaoxiao921** [comment]
do you have a log file inside `%appdata%/BigBaseV2` called `cout.log` ?

my path for me is `C:\Users\MYUSERNAME\AppData\Roaming\BigBaseV2\cout.log`

if you have such file can you drag and drop it in there?

**Comment by RobinGrasmueck** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/11770052/cout.log)

**Comment by Democles85** [comment]
> Well it still keeps crashing but i dont know what im doing wrong if it works fine for everyone

You could have a 3rd party program that might interfere with it, maybe an Antivirus or some sort of protection, maybe you played a game with Anticheat, and it's active, Battlenet is a pain in the back when it comes to this, I myself have had issues, maybe that's running?

**Comment by RobinGrasmueck** [comment]
Well i already did but i'll try disabling everything that could interfere again and try

**Comment by RobinGrasmueck** [comment]
Well still the same nothing worked I think im just gonna quit endless Problem Solving stuff and just be fine with it maybe im doing a full reset of my pc or something but thanks for your effort i really appreciate it
