### ISSUE TITLE
Ped Pool Window

### ISSUE THREAD

**Issue by Killer4563782** [Yimura/YimMenu#144]
**Is your feature request related to a problem? Please describe.**
No, it isn't

**Describe the solution you'd like**
Add a tab were you can see how many peds, vehicles etc ar around you and a button to delet all peds and vehicles around you

**Comment by Vali0004** [comment]
You could quickly create something like this with CReplayInterface. Pointer is: 48 8D 0D ? ? ? ? 48 8B D7 E8 ? ? ? ? 48 8D 0D ? ? ? ? 8A D8 E8 ? ? ? ? 84 DB 75 13 48 8D 0D | Add 3, Rip
Definition is CReplayInterface**
Or, Just use class informer on IDA
If you look into RI, it has 4 classes it leads to: CReplayInterfaceVehicle, CReplayInterfacePed, CReplayInterfacePickup and CReplayInterfaceObject
All of them have a int64 for the max count, and current count.

**Comment by Killer4563782** [comment]
The problem is I've already tried it, but it only shows me the index and not the real count

**Comment by Killer4563782** [comment]
![2022-04-22 23_59_41-Window](https://user-images.githubusercontent.com/98356478/164801415-df5f2148-1d2f-4650-b41f-15e2347e0775.png)

**Comment by Vali0004** [comment]
Works fine for me. Ensure you classes are correct
