### ISSUE TITLE
[Bug]: Kick reaction to an event

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1443]
### Describe the bug

As far as I know, breakup kick was fixed with the latest update, maybe you should use desync kick as a reaction, since the yimmenu cannot block it, for example, if another cheater tries to kick you or leave the function of choosing how to react to what the cheater does to you. It’s just that I haven’t met a cheater yet who could be kicked by me using the bail kick method. Maybe similar to #1281 Although, according to the idea for the host, you can choose another way to kick

### Steps To Reproduce

1. Open settings/reactions
2. Add a pop-up list of kick methods there after the "player kick" checkbox is active, it is possible to leave the desync kick by default and choose some other method for the cheater host

### Expected Behavior

The cheater should be automatically kicked when he tries to crash or kick me, etc. Because bail kick does not work on most cheaters or at least add the ability to select the kick method. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by rrAsus** [comment]
didn't other menu's have desync protection's?

**Comment by coder2754** [comment]
+1
