### ISSUE TITLE
[Bug]: cant run with stand free virson

### ISSUE THREAD

**Issue by Respawn-ID** [Yimura/YimMenu#1444]
### Describe the bug

cant run with stand free virson

### Steps To Reproduce

1.get in to the game
2.inject the tim menu
3.inject stand
4.crash

### Expected Behavior

game crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
YimMenu doesn’t work with Stand free, sorry.
