### ISSUE TITLE
[Request]: Add breakup kick to kick options

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1448]
### Problem

Just got hardcore trolled, with explosion loops, camera shaking, vehicles spawning all around me spam, and sound spam, quite unplayable. Since we both had really good protections we couldn't kick each other, I tried to kick them but it didn't work, they tried to kick me but it didn't work, so I added them to my player db and checked the block join button, left the session, joined them and the menu kicked them via breakup kick. I'm not sure why it isn't already in the kick options if the code is already there. It would be very nice to have for toxic people like this. :/

### Solution

Take the code the utilizes breakup kick and add it in the kick options please. I do not understand C++ much at all but I assume it's mostly a copy and paste type of job since the hard work is already done.
![image](https://github.com/YimMenu/YimMenu/assets/20650873/fdc481e2-6508-4e55-b48d-0603c12413a1)

### Reason

Uhhh I kinda already explained my reasoning in the "Problem" field.

**Comment by Yimura** [comment]
Breakup kick has been patched and only works as host, there's a PR currently open to add it as a host only kick.

**Comment by ghost** [comment]
yeah sorry i was reading about that and I was just about to close this aaaaahh
