### ISSUE TITLE
[Request]: MC sell missions features

### ISSUE THREAD

**Issue by chenry0553** [Yimura/YimMenu#1451]
### Problem

Sometimes I'm playing by myself as CEO/MC president and can't deliver the 5 packages in 3 different vehicles before somebody in a lobby explodes the other vehicles i'm not around to protect.

### Solution

an option for MC/CEO/Bunker quantity delivered option able to bet set anywhere from 1-X , X being the quantity of goods that need to be delivered. saw something like this in kiddions mod menu. 

### Reason

would be nice to see features for online that make generating money from your clubs a little easier. Sorry if it missed a post about money request not being allowed, you can close if thats not a focus. 

### Additional context

love the menu so far. much better than some discord mods i've seen.

**Comment by Tayipc38** [comment]
I don't believe this request would qualify as recovery since we aren't modifying any values that would directly result in money being added to your character. This strikes me as a rather reasonable request.

**Comment by Yimura** [comment]
Can be implemented through a Lua.
