### ISSUE TITLE
[Bug]: It is detected that some players are using Desync kick protection.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1452]
### Describe the bug

Yim menu reports that some players are using desync protection. After the 1.67 update this kick protection type is not visible in the protection settings of the yim menu. In some sessions, Yim menu reports that we are kicked with desync kick.
Are these false positives or a feature removed to make the menu stable?

### Steps To Reproduce

If you are lucky, Yim menu will notify you who is using desync protection in some sessions.

### Expected Behavior

Yim menu should not give warning if protection is patched in update 1.67

### Screenshots and/or Logs

![yimmenu (1)](https://github.com/YimMenu/YimMenu/assets/130869249/741f0740-1da9-43b7-81f0-1e039b0b04b6)
![yimmenu (2)](https://github.com/YimMenu/YimMenu/assets/130869249/8641e3bb-820d-41a3-90a1-f933ae3914ca)
![yimmenu (3)](https://github.com/YimMenu/YimMenu/assets/130869249/3dcd954f-b121-4fd0-9a78-70908ae3cbed)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
I forgot to write.
If I try to kick players using this protection with the desync kick method, they will not leave the session.

**Comment by maybegreat48** [comment]
The protection is patched, but Stand (a widespread paid mod menu) still has it for some reason. It doesn't actually work, and the reason you can't kick them is because you are the host. Use the host kick instead

**Comment by Yimura** [comment]
Not really an issue we can resolve and there's no active desync protection in YimMenu.

Only detection of a desync is in YimMenu.
