### ISSUE TITLE
[Request]: Nearby options for entity deletion

### ISSUE THREAD

**Issue by Awosk** [Yimura/YimMenu#1455]
### Problem

Car delete.

### Solution

A button can be added where I can delete the vehicle I am in and the vehicles around me.

### Reason

When I spawn a vehicle, when I want to delete that vehicle, I have to open noclip and throw it away from the map :D

**Comment by alyxme** [comment]
As TS mentioned, deleting all nearby entities and/or cars option is would be nice addition. It would be useful to cleanup a mess around without pointing to single entity especialy when some entitites just dont want to dissappear. 'Cleanup all around' would be great function.
