### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by MagzIsBack** [Yimura/YimMenu#1456]
### Problem

how to add lua scripts

### Solution

d

### Reason

it is a .dllo so i dont know how to add lua scripts

**Comment by tupoy-ya** [comment]
Look at #1389.

Note that YimMenu has it's own lua API and no documentation for it.

**Comment by Yimura** [comment]
Bear with us, there's currently no Lua API documentation and only YimMenu specific Lua scripts will work.

So until that is made if you want to make a Lua script you'll have to go and look in the source code for more information.
