### ISSUE TITLE
[Request]: Vehicle Handling Editor improvements

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1458]
### Problem

The handling editor available right now is great but for making handling for drifting a car is way too hard imo and even after converting it from "fvehicledata" to "mvehicledata" (by changing the values in handling.json files)the drifting doesnt work really great. :(

### Solution

Enhancement of current handling editor so that it might help changing the values easily or Addition of drift mode (i tried one but wasn't working as expected) or maybe adding functionality to use lua files such as wiriscript (used in stand).

### Reason

Drifting is fun :( and gta physics for it are real bad..

**Comment by V1RU513N** [comment]
Try my drift handling, i drift everyday with this
(To apply this config, you need to respawn the car)
[DRIFT.txt](https://github.com/YimMenu/YimMenu/files/11782279/DRIFT.txt)

https://github.com/YimMenu/YimMenu/assets/5224766/c7d56a7a-21c6-4ee7-a4d4-dfb1aac54248

**Comment by CypherMorgan** [comment]
Ah, Ill try it once im on my PC :D

**Comment by CypherMorgan** [comment]
Seems Like issue is resolved, gonna close the request. :D

**Comment by Yimura** [comment]
What do you mean exactly “resolved”? Nothing was changes on the menu to implement/fix this.

**Comment by CypherMorgan** [comment]
I meant like i was facing the issue to particularly get the drift thing to work and got a handling file for it which would work the way i wanted, so i thought of closing request as the main requirement for opening the request was completed. But yeah, i can reopen it if there would be some enhancement options which can be implemented in future. (Please let me know if i'll have to reopen this.) :)
