### ISSUE TITLE
[Bug]: My friends cant join my heists when i have the menu loaded

### ISSUE THREAD

**Issue by BigboiKilljoy** [Yimura/YimMenu#1462]
### Describe the bug

If my friends try to join me while im in a heist it will never work, random people can join just fine though. i dont think i have any menu options turned on that would cause this to happen 

### Steps To Reproduce

1. Try to start heist
2. Invite friends and they'll never be able to join
3. Hate your life
4. Be stuck with randoms for ever

### Expected Behavior

1: Invite friends 
2: Friends manage to join
3:Start heist with friends
4: Get rich with friends

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tessio** [comment]
This problem has been around for a long time.

It is not only in the heist, it is in any activity, if a friend is in your same session or if you invite a random person from your same session, they will not be able to join and will remain on an infinite black screen until you exit that activity or session.

I hope they can work on a solution, maybe it has something to do with some protection.

**Comment by vincentix** [comment]
Yeah, it's incredibly annoying but i'm fairly certain as @Tessio said it has something to do with protections.

**Comment by Yimura** [comment]
Should be fixed.
