### ISSUE TITLE
[Bug]: Give all weapons

### ISSUE THREAD

**Issue by tw1st31337** [Yimura/YimMenu#1463]
### Describe the bug

After selecting the option to give all weapons, it doesn't give you a Heavy rifle, gives you a bugged RPG and stun gun

### Steps To Reproduce

1. press insert
2. click on Self
3. click on Weapons
4. click on Give all weapons

### Expected Behavior

it gave me all weapons (not the bugged ones since i dont need them) and it hasn't, probably also didn't give some other ones and not only the heavy rifle

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

hi

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Iirc the weapons are fetched from the game on run time and cached. There is a known issue that the cache falls short when done at the wrong time.

**Comment by tw1st31337** [comment]
Also, if i already have MKII weapons and i try to equip an MKI weapon, it just gets removed in a second

**Comment by tw1st31337** [comment]
Also, if I already have MKII weapons and equip an MKI weapon, it gets removed in a second

**Comment by tw1st31337** [comment]
An unrelated bug I've also had is when I give a friend armor through the misc. tab, it only heals him
