### ISSUE TITLE
[Request]: Kill and DELETE Ped options.

### ISSUE THREAD

**Issue by loveshacks** [Yimura/YimMenu#1464]
### Problem

Kill and DELETE Ped options.

### Solution

Two options, One for KILL, and one for Delete.

If possible, make the kill and Delete to be continually active, so as you run, peds are killed or Deleted. Like, Toggle it on, or toggle it off.

### Reason

Useful for Cayo Perico heist (Maybe other heists as well).

### Additional context

It is pretty darn useful in Cayo Perico, where if you KILL enemies (peds), other peds can discover the bodies and sound the alarm, meaning you lose Elite bonus.

For DELETE option, as you run through, the peds are DELETED, meaning you can run through the compouind and not have bodies detected.

**Comment by Tayipc38** [comment]
There are other ways of circumventing ped intelligence. Deleting entities might soft lock certain missions.

**Comment by Yimura** [comment]
Won't be implemented, just kill enemies repeatedly.
