### ISSUE TITLE
[Bug]: a couple Session / Lobby in-mission bug that i've found so far.

### ISSUE THREAD

**Issue by fakedafuq1st** [Yimura/YimMenu#1465]
### Describe the bug

hello. this is a couple bug that i've found so far with the menu. most of it related to session host and job/heist.

- can't join to any mission lobby if the host are using the menu. this can be easily tested if the host lobby use the menu, then try to invite other player, they will be stuck in endless loading screen. as soon as the host unload the menu, they can join the lobby.

- in some occasion when in heist, if the heist failed and players trigger quick restart, if one of the players (in my case, i was trying to be the host by ticking/enable force host with force script host). there's a chance where one of the player (and sometimes the host itself) could resulting the game to crashed. (this was before the mercenaries update but it worth to report to.) the player that crashed is randomize and they don't use any menu. only the host.

- there's also an occasion where with the new DLC, for some reason can't play the new mercenaries DLC. it always show that the operation are unavailable. but as soon as you unload the menu, the mission is available. (i feel it has something to do with the protection "send to cutscene" but i don't know for sure)

- another one is on inside the new mission/job where you need to shoot the lock on the container to proceed, the game supposed to trigger the cutscene but instead, all player becoming bugged and the one who shot the lock will be stuck on god mode (as if they're mean to be in cutscene) and the only way to get out is basically the host need to be quit the job. (again, this one i feel like the same case as previous one. the game were supposed to send you to the cutscene but since you had a protection to not send into cutscene, the game confused and don't know what to do.)

**For the record : i double checked it and i didn't use the protection feature. i left them all on unchecked. it was only i unload the menu then everything is fine.**

### Steps To Reproduce

First case :
1. load the menu
2. start any job/heist and make sure to be the host
3. invite people to join.

Second case :
1. start any job/heist, invite people to join and make sure you're on the job/heist
2. load the menu and enable the force host and script
3. purposely fail the heist and do a quick restart
4. if it weren't crashing then do a re-try. because on the second case it not that often but sometimes it does. previously on my case, we crashed like 5 times back-to-back.

Third case:
1. load the menu
2. spawn avenger using interaction, be the securoserv and get into the terminal that inside the avenger
3. that's it.. the game just showing you the mission are unavailable and it will be available once the menu unloaded. (which mean i've tried to make new session, making sure the upgrade are there)

fourth case:
1. start the first mission of project overthrow, reporting for duty
2. load the menu and try to reach to the part where you need to shoot the lock on the container.
3. after shooting it, the game will be bugged and the one who shotted it will be on god mode.
the only way to reset is just to quit the session.

### Expected Behavior

Expected behavior on

case one : people joining the session fine without any problem
case two : not crashing?
case three : the operation available to play with the menu on
case four : the game trigger the cutscene just fine and proceed to next segment.

### Screenshots and/or Logs

Case on Cayo perico. this is the POV of the invited player on case number 1. they're stuck and can't do anything. the only way for them to get out is the host quit the lobby screen.
![image](https://github.com/YimMenu/YimMenu/assets/101154140/1a87ed98-c847-4fa2-b145-5cfd4db15c8a)

### Store

Epic Games

### Additional context

the second cases were tested on previous build (not the latest one so i don't know if the problem still exist or not but i'll try it out later). while the rest is on the latest build.

i don't know how and where to report and i'm avoiding spamming report so i just combine the problem into one. i'm sorry if i'm wrong but yeah i'm just reporting the cases. hope it help!

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Thanks for the extensive report. Will try and look into at least some of these myself.

**Comment by ticianomorvan** [comment]
Came to say the same thing, It doesn't seem to be a problem if you are using the menu in a mission hosted by another person.

**Comment by bdb157** [comment]
I have a similar case.
Inviting people to the heist diamond casino using the menu, they will be stuck in endless loading screen.
If I create a heist and disable the mod before inviting people, they can safely join. The second issue is that if I use a menu and invite someone from another session, they will join normally, but if I use a menu and someone is in the same session, they will not join.

**Comment by Yimura** [comment]
Excellent bug report with steps to reproduce!

**Comment by Yimura** [comment]
Dated issue.
