### ISSUE TITLE
[Bug]: I keep desyncing from my friend

### ISSUE THREAD

**Issue by Maho-Yoshino** [Yimura/YimMenu#1468]
### Describe the bug

As the title suggests, when i use Yimmenu my game just desyncs completely from my friend, even though i don't have anything enabled. I didn't notice anything like this before i started using the menu. I am using the latest version of Yimmenu and of Xenos. When i don't have the mod menu injected my game basically never desyncs

### Steps To Reproduce

1. Play gta with a friend
2. Eventually the games will just desync without doing anything
last time we had this issue we were doing DD Heist Act II Salvage recovery, and we had to wait like 2 minutes for each salvage to get collected up

### Expected Behavior

I would expect my game to not desync every 5 minutes

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Dated issue.
