### ISSUE TITLE
[Request]: Reset options to default upon unload or leaving

### ISSUE THREAD

**Issue by MarkingN1** [Yimura/YimMenu#1477]
### Problem

Its frustrating to always uncheck all the options that i used so it would be great to just reset to default with menu unload

### Solution

add a button or just a function that makes everything default

### Reason

it would make quality of life so much better

**Comment by BigboiKilljoy** [comment]
What they really should do is add a button that once hit, any other buttons you hit from that point can all instantly be undone by going back and hitting the first button you hit.

**Comment by Yimura** [comment]
This seems like a waste of development time, though anyone else is free to work on it.

**Comment by TheGreenBandit** [comment]
Couldn't the following be called? Then by just putting a button for it in settings that should be it.

:

menu_settings::write_default_config()

**Comment by arturburhanov580** [comment]
top idea

**Comment by Yimura** [comment]
Sure a button somewhere in the settings to reset everything would be a good option.
