### ISSUE TITLE
[Request]: Add "Change Extra Checksum" feature in "Replace Game Matchmaking"

### ISSUE THREAD

**Issue by vanquishes** [Yimura/YimMenu#1478]
### Solution

In the Session Browser's filters section, add an option to Override the Extra Checksum to any hex value up to 8 hex digits.

### Reason

I would like this feature to be added to YimMenu as most popular menus (Stand, 2Take1) have this feature. What it does is spoofs the "Extra Checksum" which when edited, you will limit matchmaking to people who only have this checksum, which can be very useful if people are just trying to play in a small friend group or a grinding crew that doesnt want anyone except for them to be able to matchmake with them or just a preset for only owners of YimMenu to be able to play with eachother, or if you simply want to be in a solo public session completely undisturbed, as if anyone who doesnt have this checksum tries to join they will not be able to connect.

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/17932849/96016e0d-fbf5-4b65-83d4-a8039df53083)

**Comment by Yimura** [comment]
Mmmm interesting, we could definitely take a look into this.
