### ISSUE TITLE
ESP Bug

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#148]
**Describe the bug**
I joined a new gta online lobby and enabled esp but it didnt showed up esp of the players, tried many things like changeing some settings

**To Reproduce**
1. Go to 'Session'
2. Click on Enable ESP
3. Scroll down to ENABLE
4. See that its not working

**Expected behavior**
- Esp wont show up

**Logs**

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**

**Comment by Yimura** [comment]
No need to open a new issue if the other one got closed, the other one can be reopened if needed.

Duplicate of #147
