### ISSUE TITLE
[Bug]: исправьте пожалуйста 

### ISSUE THREAD

**Issue by arturburhanov580** [Yimura/YimMenu#1481]
### Describe the bug

добрый день. Можно ли снести этот чит так чтобы удальть все данные на нем?
good afternoon. Is it possible to demolish this cheat so as to delete all the data on it?

### Steps To Reproduce

-

### Expected Behavior

чтобы чит стол стова как новый.Как будто только скачал 
to make the CHEAT as good as new.As if I just downloaded it

### Screenshots and/or Logs

```
<paste your logs here>
```
-

### Store

Epic Games

### Additional context

-

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Not English, please use English when making issues.
