### ISSUE TITLE
[Bug]: ошибка

### ISSUE THREAD

**Issue by arturburhanov580** [Yimura/YimMenu#1482]
### Describe the bug

я не могу открыть чит. да звучит глупо но он у меня идеально работал(чит топ).Но в последнее время я там кудата понатыкал) и все сломалось(я не могу открыть чит у меня пропали все иконки на экране и карта)

### Steps To Reproduce

-

### Expected Behavior

расскажите как снести чит  под ноля , чтобы он стал как новенький

### Screenshots and/or Logs

```
<paste your logs here>
```
-

### Store

Epic Games

### Additional context

-

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
English. E n g l i s h
