### ISSUE TITLE
[Bug]: mistake

### ISSUE THREAD

**Issue by arturburhanov580** [Yimura/YimMenu#1484]
### Describe the bug

I can't open the cheat. yes, it sounds silly, but it has already worked for me (cheat top).But lately I've been doing a lot of things there) and everything has broken (I can't open the cheat, all the icons on the screen and the map have disappeared)

### Steps To Reproduce

-

### Expected Behavior

tell us how to demolish the cheat under zero so that it becomes as good as new

### Screenshots and/or Logs

```
<paste your logs here>
```
![Снимок экрана (119)](https://github.com/YimMenu/YimMenu/assets/137269735/dd4df17d-158e-4389-891b-f798e087f2d9)

### Store

Epic Games

### Additional context

-

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Can you try to remove the `settings.json` file under `%appdata/BigBaseV2/` and see if that fixes it?

**Comment by arturburhanov580** [comment]
I do not know how to do this, can you please send a video lesson

**Comment by Yimura** [comment]
I cannot, but I can give a step by step guide:

1. Press Windows + R
2. Type/paste `%appdata%/BigBaseV2/` in the window that pops up
3. Windows Explorer should open up where you should see a file called `settings.json`
4. Remove the `settings.json` file.
5. Inject YimMenu and see if it works again.

**Comment by arturburhanov580** [comment]
you are a genius, I myself admire people like you very much, you can be said to be a hero of our time, there are very few of you, but you are famous in narrow circles.Thanks

**Comment by Yimura** [comment]
No problem, glad I could help.
