### ISSUE TITLE
Add Session Browser

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#149]
**Is your feature request related to a problem? Please describe.**
- X

**Describe the solution you'd like**
Able to select the region of the lobby and the slots which it should search for

**Provide Reasoning**
Its a very cool fun feature 

**Additional context**
- X

**Comment by maybegreat48** [comment]
Region spoofing (not sure about SCTV slots, maybe try setting your team to 8?):
```c++
const inline static std::vector<const char*> region_codes =
{
	"Unknown 0",
	"South America",
	"North America",
	"Russia",
	"China",
	"Europe",
	"Unknown 6",
	"Unknown 7",
	"Unknown 8"
};

main_batch.add("RC", "48 8D 15 ? ? ? ? 48 8D 4C 24 ? 89 05 ? ? ? ? E8 ? ? ? ?", [this](memory::handle ptr)
{
	m_region_code = ptr.add(3).rip().as<std::uint8_t*>();
});

if (ImGui::BeginCombo("Region", region_codes[g.spoofing.region_code]))
{
	for (int i = 0; i < region_codes.size(); i++) 
	{
		if (ImGui::Selectable(region_codes[i], g.spoofing.region_code == i)) 
		{
			g.spoofing.region_code = i;
			*g_pointers->m_region_code = i;
		};
	}
	ImGui::EndCombo();
}
```

**Comment by Yimura** [comment]
Would be nice to implement because I've joined some people in Asia region and it's full of bots and chat spammers.

**Comment by Vali0004** [comment]
You can use the SC Info class with the pointer "48 8D 05 ? ? ? ? 4D 69 F6 C0 0E ? ? 4C 03 F0 41 39 B6 80 02 ? ? 0F 86 ? ? ? ? 48 8B 15 ? ? ? ?" //Add 3, Rip
#pragma pack(push, 1)
class ScInfo {
public:
	char m_ticket[256]; //0x0000
	char pad_0100[256]; //0x0100
	char m_auth_token[128]; //0x0200
	char pad_0280[16]; //0x0280
	uint64_t m_peer_id; //0x0290
	char pad_0298[132]; //0x0298
	char m_country_code[3]; //0x031C
	char pad_031F[32]; //0x031F
	char m_email[78]; //0x033F
	char pad_038D[24]; //0x038D
	char m_language_code[8]; //0x03A5
	char pad_03AD[2]; //0x03AD
	char m_name[20]; //0x03AF
	char pad_03C3[200]; //0x03C3
}; //Size: 0x048B
static_assert(sizeof(ScInfo) == 0x48B);
#pragma pack(pop)
You can set the country code there, it's also useful in other ways too.

**Comment by Yimura** [comment]
That pointer already exists on the api_rewrite branch
https://github.com/Yimura/YimMenu/blob/88890d98e461ba7eae1e7737378f5d8ef03de376/BigBaseV2/src/pointers.cpp#L258-L262

**Comment by Vali0004** [comment]
I didn't even notice lmao

**Comment by Tayipc38** [comment]
Ive heard the p2c's simply get a bunch of player RID's to make a session browser.

**Comment by SkiddyToast** [comment]
> Ive heard the p2c's simply get a bunch of player RID's to make a session browser.

There’s a function in a vtable with no RTTI where you can get the result of the most recent matchmaking find result, although I couldn’t find the function that triggers the search.

**Comment by maybegreat48** [comment]
Spoofing pool type (0 = normal, 1 = cheater, 2 = bad sport) don't think the p2cs have this one yet
```c++
// Get Pool Type
main_batch.add("GPT", "48 89 5C 24 ? 57 48 83 EC 20 48 8B 1D ? ? ? ? BA", [this](memory::handle ptr)
{
	m_get_pool_type = ptr.as<PVOID>();
});

namespace big
{
	int hooks::get_pool_type()
	{
		return g.spoofing.pool;
	}
}
```
The cheater pool is empty and badsport has like 3 people and 5 spam bots. Pool type can go beyond 2 but it is very unlikely to find anyone there

**Comment by Yimura** [comment]
Woah nice find, is the cheater pool actively used or something Rockstar made once and then gave up on using?
Or is there something that automatically moves you into the cheater pool after a certain amount of detections have gone off?

Where you able to join others in other pools? Might be a cool thing to make a private pool of some sorts.

**Comment by maybegreat48** [comment]
Cheater pool I think is used in the last gen consoles and unused in PC (judging by the scripts you get into it if you leave during a race or deathmatch too many times). If you xref GetPoolType you will find a function that hashes that, timeout time, DLC list and something else and sends it to matchmaking servers (which can be spoofed i think)

**Comment by ApoIlos** [comment]
WIll add this here as it kinda fits.

You can grab every player thats on gta(connected to r* servers does not have to be in gta online) using natives(Yes thats right no need for hooking functions)

Heres some natives you can use to help make this function(You can also find it in the game scripts)

NETWORK_FIND_MATCHED_GAMERS
NETWORK_IS_FINDING_GAMERS
NETWORK_DID_FIND_GAMERS_SUCCEED
NETWORK_GET_NUM_FOUND_GAMERS
NETWORK_CLEAR_FOUND_GAMERS

I can post my function if people are having a hard time with making it just let me know

**Comment by FIying-Scotsman** [comment]
> Woah nice find, is the cheater pool actively used or something Rockstar made once and then gave up on using? Or is there something that automatically moves you into the cheater pool after a certain amount of detections have gone off?
> 
> Where you able to join others in other pools? Might be a cool thing to make a private pool of some sorts.

> Cheater pool I think is used in the last gen consoles and unused in PC (judging by the scripts you get into it if you leave during a race or deathmatch too many times). If you xref GetPoolType you will find a function that hashes that, timeout time, DLC list and something else and sends it to matchmaking servers (which can be spoofed i think)

Yup pretty much. It's a throw back from the Max Payne 3 days where you weren't banned but instead were forced into lobbies of fellow "cheaters". This included modders and griefers.

It was a thing in GTA but after the first batch of private menus started appearing (including famously joining R* streams and spawning UFOs as well as forcing animations on drivers during a race) they started outright banning accounts instead.

**Comment by Yimura** [comment]
Current version of the region list:
```cpp
const inline static std::vector<const char*> region_codes =
{
    "CIS",
    "Africa",
    "East",
    "Europe",
    "China",
    "Australia",
    "West",
    "Japan",
    "Unknown"
};
```

Credits: some guy on Discord
