### ISSUE TITLE
[Bug]: Can't use the operation terminal in the avanger when Yimmenu loaded (mercenaries update)

### ISSUE THREAD

**Issue by misterunknown** [Yimura/YimMenu#1498]
### Describe the bug

The GTA Online San Andreas Mercenaries introduced a new Operations Terminal for the Avenger. If YimMenu is loaded, I can't use it, because it says "The Operation Terminal ist not available" (or something like that, translated from german).

### Steps To Reproduce

1. Start GTA online
2. Load Yimmenu
3. Enter the Avenger and go to the Operations Terminal

### Expected Behavior

The Operations Terminal should be usable.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by MarkingN1** [comment]
Try to disable some options cuz if you left some of them  on they may cause the bug

**Comment by Yimura** [comment]
No this may be an issue with the protections in YimMenu or some of the hooks interfering with the game.
