### ISSUE TITLE
[Request]: Forge LSC/garage

### ISSUE THREAD

**Issue by meowmeowmoew3** [Yimura/YimMenu#1499]
### Solution

A feature to fake the vehicles model temporarily so that we can drive it into los santos customs/garage directly ,similar to what kiddions has (has to be done in a specific manner to work,but works every time)

### Reason

Makes it easier to spawn vehicles and keep them especially since many cars are gone from the online stores

**Comment by Tayipc38** [comment]
These are done with decorators I believe. It does approach recovery since it takes just one more step to sell the spawned vehicle this way.

**Comment by meowmeowmoew3** [comment]
> These are done with decorators I believe. It does approach recovery since it takes just one more step to sell the spawned vehicle this way.

Yes but, every car ive spawned and saved with stand mod menu cannot be sold, no matter the price so.. Maybe theres something that registers them as duped/0$ , idk, maybe it'll be the same in this case

**Comment by Tayipc38** [comment]
> > These are done with decorators I believe. It does approach recovery since it takes just one more step to sell the spawned vehicle this way.
> 
> Yes but, every car ive spawned and saved with stand mod menu cannot be sold, no matter the price so.. Maybe theres something that registers them as duped/0$ , idk, maybe it'll be the same in this case

I can definitely sell spawned vehicles ableit it takes some more adjustments. Since allowing vehicles into lsc is the first step of this, I see it as a step closer to recovery.

**Comment by tryintomakeit** [comment]
Every car I have saved using similar methods becomes impossible to sell once you get it insured (Can't sell cars worth more than $50.000 pop up) besides I'm sure there are better and safer ways to make money than selling spawned vehicles

**Comment by meowmeowmoew3** [comment]
Yes exactly, if it doesn't come to the menu i really hope it makes its way to a lua script or a custom yim version or something

**Comment by Yimura** [comment]
Falls under the recovery category, won't be implemented in YimMenu.
