### ISSUE TITLE
Feature Request: Expand spawn tab functionality

### ISSUE THREAD

**Issue by GibsonHF** [Yimura/YimMenu#15]
Possibly adding under spawn category of vehicles for category super, casino dlc, arena war dlc etc and list vehicles in those to spawn

**Comment by GibsonHF** [comment]
To add, my latest comment on my fork is very messy but starts the implementation of it unfortunately i didnt have time to clean it up or finish but mainly just finishing the switch statement and declaring the model to spawn based on list position

**Comment by Yimura** [comment]
Don't worry, I'm very happy that you're contributing on improving/extending the code with more features. 

I will eventually pull your PR locally and if there's anything I'd have done differently I'll tell you.

**Comment by Yimura** [comment]
@DayibBaba has found a list with all the model hashes in the game this will allow me to create a dynamically generated list off all the existing vehicles in the game.

**Comment by Yimura** [comment]
Closing issue as this request has been implemented although not exactly what was request, a replacement function has been added.

![image](https://user-images.githubusercontent.com/24669514/166742623-5eb499c4-bc7d-403b-a2c5-f93d517dd7c7.png)
