### ISSUE TITLE
Lua API / Lua Script Engine

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#150]
**Is your feature request related to a problem? Please describe.**
- X

**Describe the solution you'd like**
- Load Lua Scripts via the menu

**Provide Reasoning**
- its a easy to doing language which is very powerful and is able to add many missing feartures as simple as possible, would be such a nice thing

**Additional context**
- X

**Comment by Yimura** [comment]
Please check old issues for duplicates before making new issues.
Duplicate of #83 
Possibly related to #79
