### ISSUE TITLE
[Bug]: Not able to build Yim menu after latest commits

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1500]
### Describe the bug

This might be a a personal issue but I am not able to build yim menu after I updated cmake and pulled the latest commits

### Steps To Reproduce

![image](https://github.com/YimMenu/YimMenu/assets/90883505/27e11a5e-14c6-45b7-b0bd-0df5eba140bc)

### Expected Behavior

Build the dll

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by boredom1234** [comment]
Clean the build and then build again

**Comment by howdoiusekeyboard** [comment]
o.o
