### ISSUE TITLE
[Request]: View online reports

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1503]
### Problem

I want to know how much reports or comments are on my account

### Solution

Add a Reports tab to online category

### Reason

It's an useful option that Kiddion's Modest Menu can have using scripts, and Stand having it built-in.

**Comment by Yimura** [comment]
I don't see the use of adding this, R* doesn't care about how many reports you have on your account, so why should you care?

**Comment by pierrelasse** [comment]
Better have than not have i guess
