### ISSUE TITLE
[Bug]: game crash when loading an IPL

### ISSUE THREAD

**Issue by Vinnie-48** [Yimura/YimMenu#1505]
### Describe the bug

in the teleport tab) If you load the ipl "Life invader" the game will crash, instantly.
Retrun to the desktop, no error message.
All other ipl are unaffected (aircraft carrier, north yankton, cayo perico, hospital, ....)

### Steps To Reproduce

1. go to teleport tab
2. in the load ipl section select "life invader"
3. press load ipl

### Expected Behavior

after pressing the button load ipl, the game will crash to desktop

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
Just tried that and the game didn't crash.
I first teleported to LifeInvader and only then pressed the load IPL button, not sure if that is related.

**Comment by SlavicBlin** [comment]
does happen to me also when loading a ipl location and then trying to load a new one something with the unloading messes up and crashes... i dont have a log file but i have just removed the feature as a whole bcs of the bug / issue 

not really sure what causes it could be hardware or could just be something with the new update

**Comment by Vinnie-48** [comment]
Thank for the info.
A few more precision: no matter if it's the 1st or the 3rd you load, life invader will result in a crash.
Hardware, i think it's not the problem, my rig is quite powerful (i run in very high 60fps)
