### ISSUE TITLE
[Request]: Casino Machines Cheat

### ISSUE THREAD

**Issue by ReyZ19** [Yimura/YimMenu#1506]
### Solution

In Kiddion's Modest Menu, there was a cheat that made the casino machines 100% win. In the deity of the sun machine, we could win 2.500.000 money with 2500 chips.
When we got 2 wins in a row, we couldn't use the machine during the day, so we had 1 win 2 lose.

options in Modest Menu:
![image](https://github.com/YimMenu/YimMenu/assets/77238876/ed208337-670e-459d-8c5d-bc754dbe7a0e)

### Reason

for money

### Additional context

I found a video that shows the cheat i wanted https://youtu.be/RaJRa0Frb9E?t=171

**Comment by SlavicBlin** [comment]
> 

unfortunately this menu doesnt / is not going to implement this feature since they dont want to add recovery features due to detections / problems Take-Two would have.

you could try find a way of implementing into your own version of the menu.

**Comment by aoqia194** [comment]
Aside from what @SlavicBlin already stated, I thought this method of money making in GTA Online was detected a long time ago.

**Comment by vincentix** [comment]
Yim menu won't be adding recovery features I think /+ new features are not coming in the forseeable future.

**Comment by Yimura** [comment]
As others have said, this will not be implemented directly into YimMenu.
