### ISSUE TITLE
RID Joining

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#151]
**Is your feature request related to a problem? Please describe.**
- X

**Describe the solution you'd like**
Join a player by their rid/name

**Provide Reasoning**
Very cool and usefull feature 

**Additional context**
- X

**Comment by Yimura** [comment]
Not actually a duplicate but this request has been denied on the UnknownCheats forum.

Ref.: https://www.unknowncheats.me/forum/3328773-post109.html
