### ISSUE TITLE
[Request]: Current car delete button

### ISSUE THREAD

**Issue by Awosk** [Yimura/YimMenu#1513]
### Problem

Added an option to delete a car, but it wasn't exactly what I wanted.

### Solution

It would be enough to just put a button that deletes the vehicle we are in.
![Screenshot_1](https://github.com/YimMenu/YimMenu/assets/56509122/4aa6d7ce-4825-40c1-80ee-0fed2ede9242)

### Reason

Spawning too many vehicles can sometimes be a problem.

**Comment by SlavicBlin** [comment]
i have added a thing which deletes last spawned / driven vehicle when spawning a new one to my menu so i guess that could be quite useful.

**Comment by Tayipc38** [comment]
Did I overkill the issue

**Comment by smarbo** [comment]
Just use the delete gun from weapons and just shoot the car

**Comment by SlavicBlin** [comment]
> Just use the delete gun from weapons and just shoot the car

but then you have to navigate through the menu, find the weapon mods, locate the delete gun, get your gun out and shoot the car or cars, whereas having a button that just does it is faster and more convenient in my eyes 👍

**Comment by Akshansh16** [comment]
Update your menu... Then go to WORLD and find delete nearby vehicle. Select DELETE PERSIONAL and your good to go

**Comment by SlavicBlin** [comment]
i mean yh you can also do that... but me personally i prefer what i have added with the help from people here which is just, 
A checkbox which auto deletes the last driven / sat in car when spawing a new one, but everyone has their preferences and at the end of they day they all do the same thing. 👍
