### ISSUE TITLE
Recovery options

### ISSUE THREAD

**Issue by smarbo** [Yimura/YimMenu#1520]
### Problem

You could add some recovery options where you can like money drop or just money and RP options like in some other menus. You could also add rig casino slots and roulette which a good example of this is wealth booster on unknown cheats GTA forum

### Solution

Recovery options

### Reason

It would be very useful and would allow Devs to utilise these new features and build their own versions

**Comment by tupoy-ya** [comment]
No.

**Comment by Yimura** [comment]
No read the README again.
