### ISSUE TITLE
[Request]:  enhancement

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1522]
### Problem

1/ add a hotkey for the self clearwanted, cause it is something often used while cruising around with other players

2/ add in the players logs the ip address

3/ in the players info (of the session) if possible under the rockstar id and ip address, add the country while using a free updated app like https://ip-api.com/

4/ in the logs file "cout" maybe seperate the joining players info (and the chat in case it is also logged) from the logs of the module, cause when we log players activities (chat, join, leaving or admin) the file because very long

### Solution

well i can only bring ideas, sorry

### Reason

1/ better usage of the hotkeys
2/ can figure out modders (speacially grieffers) coming back to the session witha spoofed nick/rid/crew/lvl
3/ more info for the user
4/ easier way to read the logs

**Comment by ghost** [comment]
Yes, indeed, the idea of ​​displaying the country by ip address using api would be nice. Hope this will be added soon. It would also be nice to add the ability to display the city and the name of the provider and proxy check, then displaying the player's interface language would be superfluous.

**Comment by maybegreat48** [comment]
See #1333

**Comment by ChaT0n** [comment]
The api I pointed to isn't that precise since it is a free one, for ex :  it will tell u u're in Berlin while u're 100 kms far. But seeing what Yim wrote  in post [https://github.com/YimMenu/YimMenu/issues/1333] I didn't see things that way, for me it was just a way to use the ip. But I do need the ip address logs cause it will be helpfull to block the griefers who come back with spoofed info

**Comment by Tayipc38** [comment]
A button for clear wanted has been added.

**Comment by tryintomakeit** [comment]
With the amount of braindead people that can access this menu and the amount of people that play GTA Online without VPN, the IP info implementation is just overall a terrible idea

**Comment by ghost** [comment]
> With the amount of braindead people that can access this menu and the amount of people that play GTA Online without VPN, the IP info implementation is just overall a terrible idea

The fact is that you can still view the IP by simply copying it and pasting it to any site to view information about the IP, and adding the API will simplify this view and will not bring any harm, since the API will not show the exact location for free and countries and cities enough to troll a small modder, because if he has a good cheat, then just kicking him will not work, but it will be possible to teach him a lesson. That's what this function is for.

**Comment by xiaoxiao921** [comment]
> With the amount of braindead people that can access this menu and the amount of people that play GTA Online without VPN, the IP info implementation is just overall a terrible idea

The feature already exists in plenty of menus, what does YimMenu implementing it change anything exactly? It doesn't change the root issue that p2p network systems are dogshit for this kind of game

**Comment by tryintomakeit** [comment]
I don't care if it gets added or not, I never play this game without running a VPN, I'm simply against doxing and DDOSing, I think it's a very low thing to do regardless of who pissed you off, break up kick works wonders and so far it's unblockable as far as I know

**Comment by xiaoxiao921** [comment]
Tell that to the TakeTwo retards who thought the security of their users was less important than a fat bag of cash due to saving for their servers. $$$$

**Comment by ghost** [comment]
> I don't care if it gets added or not, I never play this game without running a VPN, I'm simply against doxing and DDOSing, I think it's a very low thing to do regardless of who pissed you off, break up kick works wonders and so far it's unblockable as far as I know

Some paid menus had break up kick protection until 1.67 came out and now there is no way to kick a modder at all. especially if he is a host and paid mod menu
