### ISSUE TITLE
[Request]: add a disable checkbox for desync protections detection

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1524]
### Problem

The problem is that in every session there are a lot of people using desync protection. Because of this, the database of players is very clogged. 

### Solution

I think the normal solution would be to add the appropriate section in the "reactions" so that you can turn off auto-adding to the player database

### Reason

So that the database of players is not clogged. I think that this can also appear to be such notifications as "attacked a player with a gmod" and similar notifications.

### Additional context

This also applies to the fact that even if someone tries to kick me and I turn off auto-adding to the player database for all methods of kicking, it is added anyway. The same situation with crashes and other

**Comment by Tayipc38** [comment]
I believe most of those detections are Stand users. I kick them either way.

**Comment by ghost** [comment]
> I believe most of those detections are Stand users. I kick them either way.

I think that this could be simplified simply by adding the appropriate section in the reaction. At the same time, it will be possible to disable the checkbox for auto-adding to the player database.

**Comment by Yimura** [comment]
Desync protections don't exist in YimMenu anymore.
