### ISSUE TITLE
[Bug]: `can_apply_data` hook is flawed due to different nodes having the same vft

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#1526]
### Describe the bug

That's problematic because the current code consider that they are unique...

### Steps To Reproduce

.

### Expected Behavior

.

### Screenshots and/or Logs

.

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Closed by #1533
