### ISSUE TITLE
[Request]: add a hotkey for clearing wanted level

### ISSUE THREAD

**Issue by fedayeenwinners** [Yimura/YimMenu#1528]
### Problem

sometimes I want the cops sometimes I dont but I am lazy to open the menu and click the button twice

### Solution

a hotkey for clearing the wanted level

### Reason

a

**Comment by Modyes** [comment]
Perhaps the best implement would be a custom hotkey, so that we can set whatever feature/button for whatever  hotkey but then again I don't know how can this be possible so a random outfit components hotkey would be useful too please..
