### ISSUE TITLE
RID Crash Protection

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#153]
**Rid Crash Protection**
- Blocks for example rid 0 crash

**Why?**
- Because Nightfall is a dumb dumb menu and others..

My Code:
—
#pragma once
#include <windows.h>
#include <iostream>
#include <thread>
#include <vector>
#include <string>
#include <functional>
#include <basetsd.h>
#include <mutex>

#include <MinHook.h>
#include "MinHook/include/MinHook.h"
#pragma comment(lib, "libMinHook-x64-v140-md.lib")

#include "scanner.hpp"

#pragma warning(disable : 4996) //due to std::wcscpy

class input {
public:
	constexpr explicit input(const char* info = { }, const std::int32_t key = { }) : info(info), key(key) { }
	~input() noexcept = default;
	void add_call(std::function<void()> callback) noexcept {
		if (GetAsyncKeyState(key) & 0x1) {
			callback();
			std::cout << info << std::endl;
		}
	}
public:
	const char* info;
	std::int32_t key;
};

#define create_hook(name, target, hk, og) \
if (MH_CreateHook(target, hk, (void**)&og) != MH_OK) \
   std::cout << "cant hook " << name << std::endl; \
else \
   std::cout << "hooked " << name << std::endl; \
—

**Comment by Yimura** [comment]
1. I don't think this crash is a thing
2. What is that code sample you dropped it doesn't even appear to be complete?

**Comment by KekN3t** [comment]
Thats the full code, for sure creaditing him, its a cool protection tho. Also it would be nice if u could a a example script event crash protection, so users can find them and share them :)
 https://github.com/AriSchmarii/sex-protex
