### ISSUE TITLE
[Bug]: afk not working

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1530]
### Describe the bug

I've activated the "no idle kick" but when I came back (around 30 minutes later) I was kicked for being afk

Did I miss something ? Don't think so

PS: maybe also make it compatible with the 'wander' option in 'Vehicule' -> 'Fun Features'

### Steps To Reproduce

1. Go to 'Self'
2. Check the 'No Idle Kick' box'
3. leave it running while being afk, but resulting in being kicked anyway

### Expected Behavior

Avoid kick for being afk

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
If you have co-loaded with other menus, such as stand, then the anti-afk does not work

**Comment by ChaT0n** [comment]
No other menu running

**Comment by eliegkassouf** [comment]
Also running into this. I still see the idle notification pop up countdown. No other menus running.

**Comment by secrethoku** [comment]
i have tested and i am also having this issue. i have been disconnected due to afk twice with the feature activated. no other menus running.

**Comment by iDominiqe** [comment]
Anti afk only works when you open another window on top of the game in windowed mode, and if you minimize the game, the game will kick you, the same thing has been checked for other menus without exception.
As another option, you could be kicked out or a bad connection to the script host, which may reveal a window with a connection error 😙

**Comment by Yimura** [comment]
Is this issue still present on the latest nightly @OneDomi? I have made some changes recently and I haven't been kicked yet.

**Comment by ChaT0n** [comment]
will try it tonight and give u a feedback

**Comment by iDominiqe** [comment]
thank you very much @Yimura , now you can turn off the game 🥰

**Comment by ChaT0n** [comment]
Seems to be working, thank you
