### ISSUE TITLE
[Bug]: Field InputText Dictonaries at Debug not active

### ISSUE THREAD

**Issue by alyxme** [Yimura/YimMenu#1531]
### Describe the bug

Field InputText search filter for Dictonaries in the Debug isnt active anymore after latest update. Can't enter any text, cant focus on that field. 

### Steps To Reproduce

1. Build and compile latest
2. Fully load then go to Debug then Animation tab
3. Fetch animations dicts
4. Try to input search filter
5. Field inactive

### Expected Behavior

Input text fields should work properly

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Additional context

InputText cursor is active for ~0.01s after tab is switched to Anims then immediately goes to inactive state

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
Same happened to me in TupoyeMenu which had updated ImGui, and now it occurs in YimMenu, so i think it is related to ImGui Update.

**Comment by Tayipc38** [comment]
I have also noticed this

**Comment by Tayipc38** [comment]
> Same happened to me in TupoyeMenu which had updated ImGui, and now it occurs in YimMenu, so i think it is related to ImGui Update.

It appears elements require an ID for them to be active. Any input text elements with an empty string as their labels are rendered inactive. Changing this to "##elementname" fixes it. PR'ing this now.
