### ISSUE TITLE
[Bug]: Cannot set player wanted level

### ISSUE THREAD

**Issue by MS-design-ui** [Yimura/YimMenu#1534]
### Describe the bug

With the new UI, the effective space has become less than halved. The Slider takes up the full allocated width of the section. The button (according to the code) is on the same line. Given the only visible thing is the slider, you can no longer set wanted levels.

I have managed to adjust the code slightly to confirm whether or not this is the correct behavior, but I removed the button from the same line.

In player_toxic.cpp

I removed lines 51 & 53.

It looks like this now:

```
static int wanted_level;
			ImGui::SliderInt("WANTED_LVL"_T.data(), &wanted_level, 0, 5);

			components::player_command_button<"wanted">(g_player_service->get_selected(), {(uint64_t)wanted_level}, "Set");

			components::player_command_button<"remweaps">(g_player_service->get_selected(), {});

			components::player_command_button<"tutorial">(g_player_service->get_selected(), {});
```

### Steps To Reproduce

1. Go online
2. Click on a player
3. Navigate to "Set wanted level"
4. Try to apply it.

### Expected Behavior

I'm imaging it makes sense for the button to be lower than the slider due to the visible estate of the UI.

### Screenshots and/or Logs

```
None.
```

### Store

Steam

### Additional context

Player UI tweaks (https://github.com/YimMenu/YimMenu/pull/1489) -> redesigned UI

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
You could make this a PR.
