### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by rr1231234** [Yimura/YimMenu#1535]
### Solution

1. Custom teleport locations
2. Tunables for RP, AP... Multiplies

### Reason

1. To precisely teleport to saved positions
2. To freeze up at a fixed rank (Multiplies = 0.00) or level up rank faster (Multiplies = 2.00)

**Comment by Tayipc38** [comment]
These are 2 separate requests, of which the first one is reasonable.

**Comment by pierrelasse** [comment]
Both make sense and are reasonable for me.

**Comment by Tayipc38** [comment]
> Both make sense and are reasonable for me.

Rank modifications do fall into recovery, although I dont think r* takes those seriously.

**Comment by Yimura** [comment]
Stat editor can already be used to modify you rank, as such we will not provide the functionality to do it.

We try to stay away from all recovery methods, or at least make them not as accessible.
And if you ask me it's not hard to change your rank with the state editor.

**Comment by rr1231234** [comment]
@Yimura might sound a little strange but actually i'd like to freeze up my rank at 420 and i need the RP multiply at 0.0, could change the rank with the editor but would have to do it too often

**Comment by Yimura** [comment]
> @Yimura might sound a little strange but actually i'd like to freeze up my rank at 420 and i need the RP multiply at 0.0, could change the rank with the editor but would have to do it too often

You can just spoof your level in freemode you know.

**Comment by Tayipc38** [comment]
Fixed by #1567
