### ISSUE TITLE
Script Event is sending continuous event after blocking it

### ISSUE THREAD

**Issue by ImpenetrableSystem** [Yimura/YimMenu#154]
**Describe the bug**
Script Event is still in queue even after blocking it which will result into getting all the script events sended at once, once unloaded
Its also a related issue to #86 

**To Reproduce**
1. Block an script event with scripted_game_event
2. Unload the menu
3. Get the whole power of script events in your face

**Expected behavior**
Normal behaviour after unload

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Yimura** [comment]
I opened a PR with an attempt to implement what you said, currently I have one more problem to fix.

The offsets of the CScriptedGameEvent are still correct but the bitBuffer appears to have changed.
I have the following code to replace the old functionality:
https://github.com/Yimura/YimMenu/blob/ca2d7c0f10239bb9bf8dff023c5e087deb01ca90/BigBaseV2/src/hooks/received_event.cpp#L37-L52

But the `m_args_size` is 0 when I read it out, currently don't have the time to finish this. Anyone with a direct fix is free to comment below with the solution.
