### ISSUE TITLE
[Bug]: Vehicle not syncing when passenger

### ISSUE THREAD

**Issue by Alpaca-exe** [Yimura/YimMenu#1540]
### Describe the bug

When I spectate a player and teleport into his vehicle the car is stopped and the car won't move (client side). It's only when you exit the car that it will actualize the position of the car.

### Steps To Reproduce

1. Spectate a player
2. TP in his vehicle
3. see the glitch

### Expected Behavior

No glitch

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by DayibBaba** [comment]
This due to how we circumvent dying when spectating. When you spectate someone, your location gets unloaded and the game kills you. By freezing the local player's location, this is avoided. But an undesired side-effect is that this freeze applies to the vehicle when you teleport into it. Ideally, the spectate should stop once a teleportation has taken place.

**Comment by Yimura** [comment]
We can technically remove the freezing since we don’t get killed anymore when the map unloads.

This is due to our patch that disables the kill trigger.

**Comment by Tayipc38** [comment]
> We can technically remove the freezing since we don’t get killed anymore when the map unloads.
> 
> This is due to our patch that disables the kill trigger.

Spectating after teleporting might still result with confusing instances, i think spectate should stop when the spectated ped is close to the local ped.

**Comment by Drsexo** [comment]
+1 the bug happens only in the latest nightly

**Comment by iwanttodo1t** [comment]
Even if you are not spectating, if you enter another player's vehicle, the vehicle will not move

**Comment by secrethoku** [comment]
> Even if you are not spectating, if you enter another player's vehicle, the vehicle will not move

yeah i had this happen to me as well. it never happened to me until the current nightly. now if i try to get in another player's car it freezes me wherever i first got in their car and when i get out they are wherever they were driving to and i am left in the location when i got in their vehicle way behind.

**Comment by xiaoxiao921** [comment]
This is most likely due to a false positive in the remote teleport protection inside can apply data now that the hook works properly, can you confirm @maybegreat48

**Comment by LasNarvalo** [comment]
can you give me the line on the can apply data please ?

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/f6969d88c570bded3357c607486488cbc178c0ce/src/hooks/protections/can_apply_data.cpp#L774-L793

**Comment by LasNarvalo** [comment]
thx :)

**Comment by maybegreat48** [comment]
>This is most likely due to a false positive in the remote teleport protection inside can apply data now that the hook works properly, can you confirm @maybegreat48

Can reproduce, vehicle gets stuck even when you enter it the normal way

```c++
if (is_in_vehicle(g_local_player, g_local_player->m_vehicle) && g_local_player->m_vehicle->m_net_object
						    && g_local_player->m_vehicle->m_net_object->m_object_id == object->m_object_id)
							return true; // vehicle kick?
```
This is broken

**Comment by Tayipc38** [comment]
> > This is most likely due to a false positive in the remote teleport protection inside can apply data now that the hook works properly, can you confirm @maybegreat48
> 
> Can reproduce, vehicle gets stuck even when you enter it the normal way
> 
> ```c++
> if (is_in_vehicle(g_local_player, g_local_player->m_vehicle) && g_local_player->m_vehicle->m_net_object
> 						    && g_local_player->m_vehicle->m_net_object->m_object_id == object->m_object_id)
> 							return true; // vehicle kick?
> ```
> 
> This is broken

This either needs to be removed or fixed asap

**Comment by tenko23** [comment]
I'll say it doesn't look good 'cause when you get in a vehicle and you don't move with it from your pov but the car is actually across the city with you by then --- and when you finally decide to get out of the non-moving vehicle (still from your pov), it appears to others that you teleport and people start calling cheating -_- .....

**Comment by Yimura** [comment]
Let’s for now just get it removed an dadd it back in when it has been fixed.

**Comment by song123jian** [comment]
> https://github.com/YimMenu/YimMenu/blob/f6969d88c570bded3357c607486488cbc178c0ce/src/hooks/protections/can_apply_data.cpp#L774-L793

易语言吗？
