### ISSUE TITLE
[Bug]: Out of game memory. Please reboot and restart the game

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1545]
### Describe the bug

Sometimes I get this error in the game and the game crashes.

### Steps To Reproduce

I don't know exactly how to reproduce it but it mostly happens to me when infinite clips setting is on and whenever I rpg fire an armored vehicle.

### Expected Behavior

The game should not crash.

### Screenshots and/or Logs

![Desktop Screenshot 2023 06 26 - 23 57 20 91](https://github.com/YimMenu/YimMenu/assets/130869249/20cad269-afb2-46ff-b36a-427195a16e02)

### Store

Epic Games

### Additional context

Also, if I rpg fire at an armored vehicle and the vehicle is destroyed in one hit, this error always happens to me without exception.
Sometimes an armored vehicle of another player is destroyed in one hit, even if the vehicle is not my own.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by secrethoku** [comment]
this also happens to me only when i am using the menu.

**Comment by Tayipc38** [comment]
This is a problem that is becoming more frequent.

**Comment by meowmeowmoew3** [comment]
oh its a menu bug,i thought my 24 gigs of ram wasnt enough lol

**Comment by Vinnie-48** [comment]
I confirm since I updated the menu (on the 24th), this happen quite frequently without even doing intensive stuff, like car repair or spawning a bodyguard.

**Comment by Yimura** [comment]
Maybe something to do with #1533

**Comment by tupoy-ya** [comment]
> Maybe something to do with #1533

Could be.
Both vehicle teleportation bug and "Out of game memory" error were happening some time ago.
Then i don't remember if "Out of game memory" error was fixed or not, maybe it was "fixed" by `can_apply_data` getting broken.

**Comment by Tayipc38** [comment]
This happened way before #1533 quite often with me.

**Comment by Yimura** [comment]
Does this happen after playing several missions in a row? I'm having trouble recreating this bug, then again I only hop from freemode to freemode lobby.

**Comment by artr9** [comment]
> Does this happen after playing several missions in a row? I'm having trouble recreating this bug, then again I only hop from freemode to freemode lobby.

Seems like it, I was speeding through the Gerald missions using noclip and on the fourth mission (i think?) it crashed with this error.

**Comment by CamioneroTrap** [comment]
i have the same problem during a mission and and in free mode

**Comment by grvelmaster** [comment]
> 

It usually happens to me with no clip and damage override turned on.
Also, if I detonate the armored vehicles with a single rpg shot even though the damage override is turned off, I feel certain that I will experience this problem.
If my work ends early tomorrow, I will try to play with the same settings for a little longer.

**Comment by ghost** [comment]
> Does this happen after playing several missions in a row? I'm having trouble recreating this bug, then again I only hop from freemode to freemode lobby.

It usually happens to me with no clip and damage override turned on.
Also, if I detonate the armored vehicles with a single rpg shot even though the damage override is turned off, I feel certain that I will experience this problem.
If my work ends early tomorrow, I will try to play with the same settings for a little longer.

**Comment by ehr7274** [comment]
> Does this happen after playing several missions in a row? I'm having trouble recreating this bug, then again I only hop from freemode to freemode lobby.

Yes, indeed.. I'm tackling LS Drug Wars Dax missions.. I get ERR_MEM_EMBEDDEDALLOC_ALLOC within the last phase of every second mission.. Only option I use (as being dead scared from a ban) is PROOFS: Bullets plus the occasional Vehicle REPAIR option.. I use XENOS64 for injection

**Comment by Akshansh16** [comment]
Out of game memory issues will be fixed by changing the DirectX version. You have to lower the DirectX to fix the issues.

**Comment by artr9** [comment]
> Out of game memory issues will be fixed by changing the DirectX version. You have to lower the DirectX to fix the issues.

I have my DX version on 10, yet the crash still happens. Dosen't seem like that's the solution.

**Comment by Harmless05** [comment]
> Out of game memory issues will be fixed by changing the DirectX version. You have to lower the DirectX to fix the issues.

I have it on DX11 and I haven't had the problem once.

**Comment by Akshansh16** [comment]
DX 10.1 is the best... I'm using 10.1 and having no issues. 10 is not supported on the latest cache. 11 is not supported by your outdated software (not game). Use 10.1 is the preference

**Comment by ghost** [comment]
this is arxan being triggered, most likely doe to the queue_dependency function you guys hook once i removed that hook from my menu the error stopped popping up.
you can find more info here: E8 ? ? ? ? CC 33 D2

also i recommend increasing the default heap size as that can improve performance:

```cpp
batch.Add({ "MEM_HS", "83 C8 01 48 8D 0D ? ? ? ? 41 B1 01 45 33 C0" }, [](Ptr ptr) {
            patterns::heap_size = ptr.add(17).as<decltype(patterns::heap_size)>();
            int ogHeapSize = *patterns::heap_size / 1024 / 1024;
            LOG(std::format("Original Memory Heap Size: {}MB", ogHeapSize).c_str());
            LOG("Modifying Memory Heap Size...");
            DWORD oldProtect;
            VirtualProtect(patterns::heap_size, 4, PAGE_EXECUTE_READWRITE, &oldProtect);
            *patterns::heap_size = 650 * 1024 * 1024;
            VirtualProtect(patterns::heap_size, 4, oldProtect, &oldProtect);
            LOG_WARN(std::format("Modified Memory Heap Size To: {}MB", *patterns::heap_size / 1024 / 1024).c_str());
        }, out);
```

**Comment by maybegreat48** [comment]
You would be detected and possibly banned if you remove that hook. I've played online for hours without being crashed so it is probably conditional

**Comment by takoyakiwhite** [comment]
I also got the error, when i start some missions.

**Comment by matarife123** [comment]
![Sin título](https://github.com/YimMenu/YimMenu/assets/110930030/d993a324-48d1-4e25-b921-4ba03a645a0a)
I did cayo perico and then I went to the workshop and started the mission of the agency, when I was about to finish on the beach looking for the buried object, when I took it out of the sand I jumped error.
(edit) It also happened to me in cayo perico, doing the daily buried objects, after removing an object from the sand, the error would jump

**Comment by Vinnie-48** [comment]
I noted it happen when I do an "alt tab", either to check youtube and/or discord running in the background.

**Comment by ehr7274** [comment]
If it can give any clue, I used YIMMENU's nightly version of 7/01/2023 and it shows no Out of Game Memory error as opposed to the latest nightly version I downloaded as of yesterday 7/03/2023..

**Comment by alyxme** [comment]
Got crash OutOfMemoryPlsRestart after received BlamingForExplosion notification when someone trigger my slicky mine

**Comment by DayibBaba** [comment]
Duplicate issue.

**Comment by KnollenRick** [comment]
Yesterday, I had the same problem.

**Comment by DidierSardine** [comment]
Same problem this morning after using the Orbital drone, when I fired, the guy exploded then 2 or 3 seconds later I had this issue. And yesterday I was discussing with someone that was using the modmenu Stand, and we were messing around with each other, so i ragdolled him and got this error instantly

**Comment by PinkyPromises** [comment]
/I thought I was the only one with this issue, when I don't use the menu it doesn't have any problems with the memory. I think it's the "No idle kick" feature that triggers it after long sessions, sometimes while navigating in the menu and moving the camera or interacting with anything too quickly after closing the menu happened to also trigger it too. 

Edit: I remember crashing like this in Lowrider Mission #4 - Funeral Party too 3 times

**Comment by Yimura** [comment]
> I thought I was the only one with this issue, when I don't use the menu it doesn't have any problems with the memory. I think it's the "No idle kick" feature that triggers it after long sessions, sometimes while navigating in the menu and moving the camera or interacting with anything too quickly after closing the menu happened to also trigger it too

It's not no idle kick, was it only that easy aha. The no idle kick feature only switches a couple of values to MAX_INT.
https://github.com/YimMenu/YimMenu/blob/47891cbcae2f48d2ecbe83c89ec81a963d78a58e/src/backend/looped/tunables/no_idle_kick.cpp#L6-L56

**Comment by GTMoraes** [comment]
Just had a crash with this error.

What I had done: I unloaded YimMenu so I could start a freemode mission, then started the freemode mission, alt-tabbed to re-inject YimMenu, concluded the freemode mission, drove around for a minute or two, then I tried entering my nightclub on foot, and it crashed mid transition.
No error message or box, but this warning and fatal error was in cout.log

Here's the log

```
[00:46:00.2708988][INFO/main.cpp:65] Yim's Menu Initializing
[00:46:00.2709156][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	40074118a1e34f8250492ee46a8a08ed3e807883
	Date:	Sun Aug 6 18:34:43 2023
[00:46:00.2709259][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[00:46:00.2715763][INFO/main.cpp:69] Thread pool initialized.
[00:46:00.2737665][INFO/main.cpp:72] Settings Loaded.
[00:46:00.2737777][DEBUG/thread_pool.cpp:95] Thread 2376 executing settings.cpp:18
[00:46:00.2740677][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[00:46:00.2740756][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:46:00.2740771][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[00:46:00.2740845][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[00:46:00.2742187][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[00:46:00.2742218][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:46:00.2742228][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[00:46:00.2742664][INFO/main.cpp:75] Pointers initialized.
[00:46:00.2743618][INFO/main.cpp:78] Byte Patch Manager initialized.
[00:46:00.8539835][INFO/main.cpp:81] Renderer initialized.
[00:46:01.1401685][INFO/main.cpp:85] Fiber pool initialized.
[00:46:01.6286891][INFO/main.cpp:88] Translation Service initialized.
[00:46:01.6524735][INFO/main.cpp:91] Hooking initialized.
[00:46:01.6601378][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[00:46:01.6601511][INFO/gta_data_service.cpp:174] Loading 1029 peds from cache.
[00:46:01.6606830][INFO/gta_data_service.cpp:192] Loading 815 vehicles from cache.
[00:46:01.6612666][INFO/gta_data_service.cpp:209] Loading 117 weapons from cache.
[00:46:01.6612787][INFO/gta_data_service.cpp:210] Loading 378 weapon components from cache.
[00:46:01.6613033][DEBUG/gta_data_service.cpp:168] Loaded all data from cache.
[00:46:01.6681670][INFO/tunables_service.cpp:21] Loading tunables from cache
[00:46:01.6681860][INFO/main.cpp:111] Registered service instances...
[00:46:01.6681927][DEBUG/thread_pool.cpp:95] Thread 26248 executing tunables_service.cpp:24
[00:46:01.6682821][INFO/main.cpp:132] Scripts registered.
[00:46:01.7302321][INFO/main.cpp:135] Hooking enabled.
[00:46:01.7313129][INFO/main.cpp:138] Dynamic native hooker initialized.
[00:46:01.7372032][INFO/lua_module.cpp:226] Loaded CasinoPacino.lua
[00:46:01.7372465][INFO/main.cpp:141] Lua manager initialized.
[00:46:01.7372607][DEBUG/thread_pool.cpp:95] Thread 26248 executing player_database_service.cpp:276
[00:46:01.8133294][INFO/backend.cpp:51] Starting script: Self
[00:46:01.8133408][INFO/backend.cpp:76] Starting script: Weapons
[00:46:01.8133484][INFO/backend.cpp:99] Starting script: Vehicles
[00:46:01.8133592][INFO/backend.cpp:115] Starting script: Miscellaneous
[00:46:01.8133632][INFO/backend.cpp:135] Starting script: Remote
[00:46:01.8133831][INFO/backend.cpp:150] Starting script: Ls customs
[00:46:01.8133850][INFO/backend.cpp:162] Starting script: Rainbow paint
[00:46:01.8133863][INFO/backend.cpp:174] Starting script: Disable Control Action
[00:46:01.8133884][INFO/backend.cpp:187] Starting script: World
[00:48:49.9130747][WARN/log_message_error_box.cpp:37] Error Code: ERR_MEM_EMBEDDEDALLOC_ALLOC
[00:48:49.9147078][FATAL/log_message_error_box.cpp:14] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF6F37D0000 Size: 67158528
ntdll.dll Base Address: 0x7FFFF8110000 Size: 1245184
KERNEL32.DLL Base Address: 0x7FFFF7670000 Size: 524288
KERNELBASE.dll Base Address: 0x7FFFF58B0000 Size: 1634304
USER32.dll Base Address: 0x7FFFF7140000 Size: 593920
win32u.dll Base Address: 0x7FFFF57C0000 Size: 49152
GDI32.dll Base Address: 0x7FFFF6A10000 Size: 57344
gdi32full.dll Base Address: 0x7FFFF5600000 Size: 679936
msvcp_win.dll Base Address: 0x7FFFF5720000 Size: 335872
ucrtbase.dll Base Address: 0x7FFFF5C60000 Size: 798720
PSAPI.DLL Base Address: 0x7FFFF8050000 Size: 4096
WS2_32.dll Base Address: 0x7FFFF6F80000 Size: 290816
RPCRT4.dll Base Address: 0x7FFFF68F0000 Size: 880640
CRYPT32.dll Base Address: 0x7FFFF5D80000 Size: 1138688
WINTRUST.dll Base Address: 0x7FFFF5510000 Size: 307200
msvcrt.dll Base Address: 0x7FFFF6A50000 Size: 507904
VERSION.dll Base Address: 0x7FFFECE70000 Size: 12288
DSOUND.dll Base Address: 0x7FFF9B560000 Size: 491520
IMM32.dll Base Address: 0x7FFFF8010000 Size: 126976
advapi32.dll Base Address: 0x7FFFF75C0000 Size: 425984
SHLWAPI.dll Base Address: 0x7FFFF8070000 Size: 212992
sechost.dll Base Address: 0x7FFFF7510000 Size: 446464
SHELL32.dll Base Address: 0x7FFFF5F70000 Size: 6524928
combase.dll Base Address: 0x7FFFF7990000 Size: 2539520
ole32.dll Base Address: 0x7FFFF7D20000 Size: 897024
OLEAUT32.dll Base Address: 0x7FFFF7000000 Size: 647168
WININET.dll Base Address: 0x7FFFDA340000 Size: 2113536
WINMM.dll Base Address: 0x7FFFEE470000 Size: 114688
MF.dll Base Address: 0x7FFFEF880000 Size: 368640
MFPlat.DLL Base Address: 0x7FFFEED00000 Size: 1503232
shcore.dll Base Address: 0x7FFFF6770000 Size: 679936
msdmo.dll Base Address: 0x7FFFE3750000 Size: 16384
MFReadWrite.dll Base Address: 0x7FFF58C40000 Size: 995328
PROPSYS.dll Base Address: 0x7FFFF1120000 Size: 688128
d3d9.dll Base Address: 0x7FFFC8B50000 Size: 1306624
WTSAPI32.dll Base Address: 0x7FFFF08A0000 Size: 40960
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFF973B0000 Size: 96256
D3DCOMPILER_43.dll Base Address: 0x7FFF9C8C0000 Size: 2423296
bink2w64.dll Base Address: 0x7FFFE2F70000 Size: 307712
ResampleDmo.DLL Base Address: 0x7FFF9B4A0000 Size: 503808
DINPUT8.dll Base Address: 0x7FFFC84E0000 Size: 176128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFFF6B00000 Size: 913408
IPHLPAPI.DLL Base Address: 0x7FFFF40B0000 Size: 122880
bcrypt.dll Base Address: 0x7FFFF4EC0000 Size: 110592
powrprof.dll Base Address: 0x7FFFF4410000 Size: 77824
winmmbase.dll Base Address: 0x7FFFDB050000 Size: 102400
cfgmgr32.dll Base Address: 0x7FFFF5220000 Size: 221184
dwmapi.dll Base Address: 0x7FFFF1E00000 Size: 90112
d3dx9_43.dll Base Address: 0x7FFF93EA0000 Size: 2280960
dxcore.dll Base Address: 0x7FFFF2300000 Size: 135168
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFFE62E0000 Size: 48128
OPENGL32.dll Base Address: 0x7FFFD6CC0000 Size: 798720
MFCORE.DLL Base Address: 0x7FFF5BCF0000 Size: 3256320
GLU32.dll Base Address: 0x7FFFD4C80000 Size: 126976
UMPDC.dll Base Address: 0x7FFFF43F0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFFF4640000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFFF5580000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFFEEC80000 Size: 102400
MSASN1.dll Base Address: 0x7FFFF51E0000 Size: 36864
gameoverlayrenderer64.dll Base Address: 0x7FFFE3000000 Size: 983552
inputhost.dll Base Address: 0x7FFFDC100000 Size: 1515520
CoreMessaging.dll Base Address: 0x7FFFF0CF0000 Size: 860160
CRYPTBASE.DLL Base Address: 0x7FFFF4D40000 Size: 12288
windows.storage.dll Base Address: 0x7FFFF34E0000 Size: 6909952
wintypes.dll Base Address: 0x7FFFF3020000 Size: 544768
dbghelp.dll Base Address: 0x7FFFF2DF0000 Size: 1626112
dbgcore.DLL Base Address: 0x7FFFE3980000 Size: 131072
d3d12.dll Base Address: 0x7FFFD6C70000 Size: 81920
CRYPTSP.dll Base Address: 0x7FFFF4D20000 Size: 57344
rsaenh.dll Base Address: 0x7FFFF45B0000 Size: 147456
uxtheme.dll Base Address: 0x7FFFF1C60000 Size: 425984
RTSSHooks64.dll Base Address: 0x180000000 Size: 677888
imagehlp.dll Base Address: 0x7FFFF7FF0000 Size: 49152
clbcatq.dll Base Address: 0x7FFFF72F0000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFE3800000 Size: 253952
d3d11.dll Base Address: 0x7FFFF3160000 Size: 1867776
WMICLNT.dll Base Address: 0x7FFFEE1D0000 Size: 32768
dxgi.dll Base Address: 0x7FFFF33C0000 Size: 647168
DEVOBJ.dll Base Address: 0x7FFFF51B0000 Size: 110592
wbemprox.dll Base Address: 0x7FFFEB7D0000 Size: 28672
wbemcomn.dll Base Address: 0x7FFFEB5B0000 Size: 311296
wbemsvc.dll Base Address: 0x7FFFEA040000 Size: 8192
fastprox.dll Base Address: 0x7FFFE2C80000 Size: 708608
amsi.dll Base Address: 0x7FFFE9250000 Size: 57344
USERENV.dll Base Address: 0x7FFFF4BC0000 Size: 102400
profapi.dll Base Address: 0x7FFFF5440000 Size: 90112
symamsi.dll Base Address: 0x7FFFE8F10000 Size: 503296
gpapi.dll Base Address: 0x7FFFF4B50000 Size: 77824
cryptnet.dll Base Address: 0x7FFFECE30000 Size: 139264
WINNSI.DLL Base Address: 0x7FFFF1D80000 Size: 16384
NSI.dll Base Address: 0x7FFFF68E0000 Size: 8192
directxdatabasehelper.dll Base Address: 0x7FFFEDCE0000 Size: 192512
steam_api64.dll Base Address: 0x51B90000 Size: 110592
steamclient64.dll Base Address: 0x7FFF8D4E0000 Size: 16099328
MSWSOCK.dll Base Address: 0x7FFFF4AC0000 Size: 331776
Secur32.dll Base Address: 0x7FFFD9E10000 Size: 12288
tier0_s64.dll Base Address: 0x7FFF9DA70000 Size: 260608
vstdlib_s64.dll Base Address: 0x7FFFE4A20000 Size: 285184
SSPICLI.DLL Base Address: 0x7FFFF48A0000 Size: 126976
nvapi64.dll Base Address: 0x7FFFE92C0000 Size: 6282752
drvstore.dll Base Address: 0x7FFFECC60000 Size: 1073152
wldp.dll Base Address: 0x7FFFF4DD0000 Size: 176128
D3D10_1.DLL Base Address: 0x7FFFE4F00000 Size: 147456
d3d10_1core.dll Base Address: 0x7FFFE4CF0000 Size: 12288
nvspcap64.dll Base Address: 0x7FFFCD320000 Size: 2055680
ntmarta.dll Base Address: 0x7FFFF4660000 Size: 147456
dhcpcsvc.DLL Base Address: 0x7FFFEE3F0000 Size: 69632
MSCTF.dll Base Address: 0x7FFFF7EC0000 Size: 942080
textinputframework.dll Base Address: 0x7FFFE3470000 Size: 921600
WINSTA.dll Base Address: 0x7FFFF4030000 Size: 229376
nvldumdx.dll Base Address: 0x7FFFEA080000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFFDC880000 Size: 36389376
NvCamera64.dll Base Address: 0x7FFF8B480000 Size: 4209664
HID.DLL Base Address: 0x7FFFF3DE0000 Size: 24576
XINPUT9_1_0.dll Base Address: 0x7FFFEF5B0000 Size: 8192
WindowsCodecs.dll Base Address: 0x7FFFEFF30000 Size: 1331200
MessageBus.dll Base Address: 0x7FFFE6890000 Size: 5349888
d3dcompiler_47_64.dll Base Address: 0x7FFF92770000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFF915A0000 Size: 5770240
dcomp.dll Base Address: 0x7FFFF0140000 Size: 1716224
DiscordHook64.dll Base Address: 0x7FFF9D2A0000 Size: 780288
D3DCompiler_47.dll Base Address: 0x7FFFEFB40000 Size: 3043328
MMDevApi.dll Base Address: 0x7FFFEA5C0000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFD0040000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFFE5790000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FFFF2140000 Size: 36864
Windows.UI.dll Base Address: 0x7FFFC3B70000 Size: 966656
avrt.dll Base Address: 0x7FFFF34D0000 Size: 8192
MessageBus.dll Base Address: 0x7FFFD4DF0000 Size: 5349888
napinsp.dll Base Address: 0x7FFFD88B0000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFFD75E0000 Size: 69632
DNSAPI.dll Base Address: 0x7FFFF4120000 Size: 716800
winrnr.dll Base Address: 0x7FFFD75C0000 Size: 32768
wshbth.dll Base Address: 0x7FFFECEB0000 Size: 45056
nlansp_c.dll Base Address: 0x7FFFD7590000 Size: 81920
fwpuclnt.dll Base Address: 0x7FFFED8A0000 Size: 299008
rasadhlp.dll Base Address: 0x7FFFEBF00000 Size: 8192
socialclub.dll Base Address: 0x7FFF94110000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFFE3BB0000 Size: 685568
libcef.dll Base Address: 0x7FFF50460000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFFF7410000 Size: 774144
UIAutomationCore.DLL Base Address: 0x7FFFAE9D0000 Size: 3063808
NETAPI32.dll Base Address: 0x7FFFDBB40000 Size: 49152
OLEACC.dll Base Address: 0x7FFFE7090000 Size: 274432
DWrite.dll Base Address: 0x7FFFF2910000 Size: 1605632
WINSPOOL.DRV Base Address: 0x7FFFE7100000 Size: 376832
COMCTL32.dll Base Address: 0x7FFFE6FD0000 Size: 573440
USP10.dll Base Address: 0x7FFF84790000 Size: 4096
dxva2.dll Base Address: 0x7FFFA0510000 Size: 102400
credui.dll Base Address: 0x7FFF85720000 Size: 65536
urlmon.dll Base Address: 0x7FFFE75F0000 Size: 1298432
WINHTTP.dll Base Address: 0x7FFFEE550000 Size: 987136
ncrypt.dll Base Address: 0x7FFFF4E90000 Size: 114688
ESENT.dll Base Address: 0x7FFFDC4B0000 Size: 3145728
wevtapi.dll Base Address: 0x7FFFF1A30000 Size: 278528
CRYPTUI.dll Base Address: 0x7FFFD1120000 Size: 278528
iertutil.dll Base Address: 0x7FFFE5440000 Size: 557056
srvcli.dll Base Address: 0x7FFFE2BD0000 Size: 61440
netutils.dll Base Address: 0x7FFFF40A0000 Size: 20480
WKSCLI.DLL Base Address: 0x7FFFEE020000 Size: 53248
SAMCLI.DLL Base Address: 0x7FFFF18F0000 Size: 61440
NTASN1.dll Base Address: 0x7FFFF4E50000 Size: 69632
FirewallAPI.dll Base Address: 0x7FFFF3F50000 Size: 380928
fwbase.dll Base Address: 0x7FFFF3F00000 Size: 196608
FWPolicyIOMgr.dll Base Address: 0x7FFFDB7C0000 Size: 241664
wdmaud.drv Base Address: 0x7FFFA1FC0000 Size: 200704
ksuser.dll Base Address: 0x7FFFAC520000 Size: 8192
msacm32.drv Base Address: 0x7FFFA20D0000 Size: 20480
MSACM32.dll Base Address: 0x7FFFA11D0000 Size: 77824
midimap.dll Base Address: 0x7FFFA20C0000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FFFB8C10000 Size: 45056
LINKINFO.dll Base Address: 0x7FFFC1D40000 Size: 20480
mfsrcsnk.dll Base Address: 0x7FFF9C6E0000 Size: 1613824
CompPkgSup.DLL Base Address: 0x7FFFE6060000 Size: 167936
Windows.Media.dll Base Address: 0x7FFFBADE0000 Size: 5017600
mp3dmod.dll Base Address: 0x7FFFE4BE0000 Size: 65536
Windows.ApplicationModel.dll Base Address: 0x7FFFD0160000 Size: 704512
AppXDeploymentClient.dll Base Address: 0x7FFFEE8C0000 Size: 815104
d3dx11_42.dll Base Address: 0x7FFFC7340000 Size: 248832
d3dcompiler_42.dll Base Address: 0x7FFF8ED80000 Size: 2477568
CoreUIComponents.dll Base Address: 0x7FFFECED0000 Size: 2036736
schannel.DLL Base Address: 0x7FFFF44B0000 Size: 561152
ncryptsslp.dll Base Address: 0x7FFFD9AB0000 Size: 86016
YimMenu.dll Base Address: 0x7FFF8ABF0000 Size: 6134272
MSVCP140.dll Base Address: 0x7FFFD4830000 Size: 346112
VCRUNTIME140.dll Base Address: 0x7FFFD4CB0000 Size: 64512
VCRUNTIME140_1.dll Base Address: 0x7FFFD8A70000 Size: 14848
xinput1_4.dll Base Address: 0x7FFFEF5E0000 Size: 26112
Dumping registers:
RAX: 0x1
RCX: 0x2BD841F0000
RDX: 0x2BD841F0000
RBX: 0x2BF14F2CA60
RSI: 0x7FF6F5705C18
RDI: 0xE36C4FEB38
RSP: 0xE36C4FEAA0
RBP: 0x10
R8:  0x2BD840EB940
R9:  0x1
R10: 0x3
R11: 0xE36C4FEA30
R12: 0x2BEC2AD8210
R13: 0xB2
R14: 0x2BD9FB94FC0
R15: 0x123
Dumping stacktrace:
[0]	YimMenu.dll+0xC5434 0x7FFF8ACB5434
[1]	YimMenu.dll+0xC5404 0x7FFF8ACB5404
[2]	GTA5.exe+0x1310BF7 0x7FF6F4AE0BF7
[3]	GTA5.exe+0x12F1947 0x7FF6F4AC1947
[4]	GTA5.exe+0x641712 0x7FF6F3E11712
[5]	GTA5.exe+0x5F781A 0x7FF6F3DC781A
[6]	GTA5.exe+0x908C6B 0x7FF6F40D8C6B
[7]	GTA5.exe+0x1640614 0x7FF6F4E10614
[8]	GTA5.exe+0x16405D2 0x7FF6F4E105D2
[9]	GTA5.exe+0x1642E0E 0x7FF6F4E12E0E
[10]	GTA5.exe+0x1656335 0x7FF6F4E26335
[11]	GTA5.exe+0x162F87C 0x7FF6F4DFF87C
[12]	GTA5.exe+0x16302EB 0x7FF6F4E002EB
[13]	GTA5.exe+0x16303AA 0x7FF6F4E003AA
[14]	GTA5.exe+0x805052 0x7FF6F3FD5052
[15]	GTA5.exe+0x161A8E9 0x7FF6F4DEA8E9
[16]	GTA5.exe+0x161A11B 0x7FF6F4DEA11B
[17]	GTA5.exe+0x2781C 0x7FF6F37F781C
[18]	GTA5.exe+0x20E9B 0x7FF6F37F0E9B
[19]	GTA5.exe+0x1619D24 0x7FF6F4DE9D24
[20]	GTA5.exe+0x1494 0x7FF6F37D1494
[21]	GTA5.exe+0x12F22C3 0x7FF6F4AC22C3
[22]	GTA5.exe+0x180CE38 0x7FF6F4FDCE38
[23]	KERNEL32.DLL BaseThreadInitThunk
[24]	ntdll.dll RtlUserThreadStart
--------End of exception--------

```

**Comment by abuazizv** [comment]
> this is arxan being triggered, most likely doe to the queue_dependency function you guys hook once i removed that hook from my menu the error stopped popping up. you can find more info here: E8 ? ? ? ? CC 33 D2
> 
> also i recommend increasing the default heap size as that can improve performance:
> 
> ```c++
> batch.Add({ "MEM_HS", "83 C8 01 48 8D 0D ? ? ? ? 41 B1 01 45 33 C0" }, [](Ptr ptr) {
>             patterns::heap_size = ptr.add(17).as<decltype(patterns::heap_size)>();
>             int ogHeapSize = *patterns::heap_size / 1024 / 1024;
>             LOG(std::format("Original Memory Heap Size: {}MB", ogHeapSize).c_str());
>             LOG("Modifying Memory Heap Size...");
>             DWORD oldProtect;
>             VirtualProtect(patterns::heap_size, 4, PAGE_EXECUTE_READWRITE, &oldProtect);
>             *patterns::heap_size = 650 * 1024 * 1024;
>             VirtualProtect(patterns::heap_size, 4, oldProtect, &oldProtect);
>             LOG_WARN(std::format("Modified Memory Heap Size To: {}MB", *patterns::heap_size / 1024 / 1024).c_str());
>         }, out);
> ```

yes i can confirm its the queue_dependency hook i have it in my menu and sometimes i get the same crash i tried to delete it the issue got fixed, however my main account got banned even with the queue_dependency function im not sure if its detected now, even a "p2c" aka stand menu use it and got detected but like i said im not sure what got my main banned but i dont really hook anything else than queue_dependency....

**Comment by xiaoxiao921** [comment]
Bans in GTA 5 are hugely delayed, the moment you removed the queue_dependency hook you were flagged.

**Comment by abuazizv** [comment]
> 

no when i removed it i tired it on another account and stayed in story mode for a couple of hours to see if ill get a crash, tbh i think something wrong with it seeing a "p2c" getting detected with it idk man, im not good with reverse engineering but maybe the function is integrity checked now? but like i said im not sure of the ban cause... but queue_dependency caused the same crash for me, btw i got banned exactly after 14 days so it wasnt that delayed..

**Comment by matarife123** [comment]
They banned me for 30 days and they deleted my pj
![Sin título](https://github.com/YimMenu/YimMenu/assets/110930030/8aaf7574-0bc2-4b6f-b0ab-772096df6040)

07/08/2023

**Comment by abuazizv** [comment]
> They banned me for 30 days and they deleted my pj ![Sin título](https://user-images.githubusercontent.com/110930030/262479788-8aaf7574-0bc2-4b6f-b0ab-772096df6040.png)
> 
> 07/08/2023

your pj?
 what menu you used did you injected another menu in the last 30 days? and what money options if you messed with money .

**Comment by matarife123** [comment]
> > They banned me for 30 days and they deleted my pj ![Sin título](https://user-images.githubusercontent.com/110930030/262479788-8aaf7574-0bc2-4b6f-b0ab-772096df6040.png)
> > 07/08/2023
> 
> your pj? what menu you used did you injected another menu in the last 30 days? and what money options if you messed with money .

just use yimenu and kiddions i didn't make any money just repair some cars from the shop and deliver them using tp

**Comment by abuazizv** [comment]
> > > They banned me for 30 days and they deleted my pj ![Sin título](https://user-images.githubusercontent.com/110930030/262479788-8aaf7574-0bc2-4b6f-b0ab-772096df6040.png)
> 
> > > 07/08/2023
> 
> > 
> 
> > your pj? what menu you used did you injected another menu in the last 30 days? and what money options if you messed with money .
> 
> 
> 
> just use yimenu and kiddions i didn't make any money just repair some cars from the shop and deliver them using tp

I see as long you didnt mess with money and modest menu is external then something is off, today i tested the queue_dependency hook on a fresh account ill let everyone knows if i get banned.

**Comment by gir489returns** [comment]
> You would be detected and possibly banned if you remove that hook. I've played online for hours without being crashed so it is probably conditional

@maybegreat48 Can you try playing some missions? I have to figure you spend most of your time in freemode, which is why you don't see this crash. It seems to only show itself while I'm on a mission, probably how the Arxan triggers fire.

**Comment by abuazizv** [comment]
> > You would be detected and possibly banned if you remove that hook. I've played online for hours without being crashed so it is probably conditional
> 
> @maybegreat48 Can you try playing some missions? I have to figure you spend most of your time in freemode, which is why you don't see this crash. It seems to only show itself while I'm on a mission, probably how the Arxan triggers fire.

you can get the same crash even if you afk'd too much sometimes it doesnt crash at all or after many hours

**Comment by maybegreat48** [comment]
> > You would be detected and possibly banned if you remove that hook. I've played online for hours without being crashed so it is probably conditional
> 
> @maybegreat48 Can you try playing some missions? I have to figure you spend most of your time in freemode, which is why you don't see this crash. It seems to only show itself while I'm on a mission, probably how the Arxan triggers fire.

Yeah, confirmed that long ago. Business battles also trigger this crash

**Comment by gir489returns** [comment]
> Yeah, confirmed that long ago. Business battles also trigger this crash

Any ideas how we can supress the crash?

**Comment by gir489returns** [comment]
@maybegreat48 if we move to a debug breakpoint hook for queue dependency like I had in BBv2-fix for the anti cheat function, would that fix Arxan detecting the hook?

**Comment by maybegreat48** [comment]
It isn't integrity checked, there's something like a heartbeat that's catching it
