### ISSUE TITLE
[Bug]:  Can't be a passenger, synchronization fails

### ISSUE THREAD

**Issue by redrafa** [Yimura/YimMenu#1550]
### Describe the bug

When being a passenger, as soon as you get in, it stops refreshing and loses sync of the drivers position. It's as if the driver isn't moving and is just AFK, any actions inside the car can still be seen like shooting, doing actions, etc.

As soon as you leave the vehicle you are still where the vehicle was to you (which didn't move since you got in) and the driver gets update to wherever he was. This breaks missions and overall freeroam. Happens in any session type, as far as it goes only happens with the mod menu on.

No custom scripts, no custom settings, tried with all menu settings off (besides protections) but menu on.

And tried with the mod menu off, which worked as expected.

### Steps To Reproduce

1. Get inside the passenger,
2. Bug occurs.

No self options enabled, no weapon options enabled, not a modded car, no special settings are in-place besides default protections, no spoofing is being done, user isn't flagged or a modder, host isn't a modder.
Happens in any session type, as far as it goes only happens with the mod menu on.

### Expected Behavior

Synchronization to be made with the driver or his position to be updated.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by redrafa** [comment]
Closed — Will be trying to personally pinpoint what is going on as to preserve the affected options and contribute to keep the menu operational.

**Comment by redrafa** [comment]
Reupdated to the latest compilation (10hours ago) still occurs.

**Comment by matarife123** [comment]
I keep having this problem

**Comment by Yimura** [comment]
Duplicate of #1540
