### ISSUE TITLE
[Bug]: more bug that i could find.

### ISSUE THREAD

**Issue by fakedafuq1st** [Yimura/YimMenu#1551]
### Describe the bug

hello! i'm going to report more bug that i could find while using the menu. same as before i'll combine them into one in order to avoid any spam issue here.

- "Bring players" are bugged
this feature is so helpful but so buggy. you can teleport other players to you but if you trigger this feature once, the player/target will be bugged. in my case i found 2 bug.
1. if the teleport succeeded, every one in a while that player will randomly teleport into random places that somewhere in the middle of the map or just straight up inside a building in my case. they are not stuck however. but this will happen again unless you re-load the menu.
2. if the teleport failed however, the player now will stuck. in previous build, if the teleport fails, the player will be stuck and can't move. if they're using the vehicle, the vehicle will be gone and they will be stuck somewhere. but in latest build (f8f63a7) the player sometimes is not stuck, and sometimes the vehicle (that they're using at that moment) will be gone.
also i found out sometimes you can "drive" the invisible vehicle after using this feature. that vehicle is invisible but you can still get in, drive it and using it. other players can't see you as you're become invisible as well.

- spawn ped feature
this feature have a couple interesting things but i frankly don't know whether it is a bug from the menu or just the game act this way. 
1. spawning any ped inside a building resulting this 2 thing that can be happen in my case are 
1.1 the ped sometimes desync with other players.
1.2 the ped won't de-spawn even if we change session.
1.3 sometimes using "clean up spawned ped" does not work. it will only clean them on your screen but other players can still see them.
1.2.1 sometimes after changing session, the ped that previously spawned will be teleported outside the interior to randomly somewhere around the map, resulting them become invisible but can still be "seen" within context menu or ESP. you can still hit them / hurt them and they will show blood. 
2. using change player model and then died resulting the original character model reset to "default?" character model with that green hair. and all of the removed weapon not returning. so ended up with nothing instead. changing session will fixed this issue. but if you're not dead while using change player model and changing the session, you will be reset back to original character BUT the other will still see you as different ped (becoming the one that you changed previously) death will not reset the model. if this happened, unload the menu immediately solved the issue.

- squad spawner
not much but spawning with larger squad size sometimes make the game crashes. in my cases, i spawn jesus machete (greatest idea ever) with 8 squad size. the jesus spawn inside the targeted player and the game crashes. other player game are fine, just the one who spawning them are.

that's it. i hope this help because i legit enjoy using this menu. i hope you add more feature in the future. i had a couple ideas in mind but i'll make the list later.

### Steps To Reproduce

Case 1:
1. just start session with menu loaded, had a friend to join
2. trigger the bring feature.

Case 2.1:
1. spawn any ped model inside a building

Case 2.2:
1. spawn any ped model inside a building
2. change session.

Case 2.3:
1. use change player model from spawn ped menu
2. go suicide / dead OR while still on other model, change session.

Case 3:
1. just spamming the spawn squad will do usually.

### Expected Behavior

Case 1: result is fine? the teleport works and it wont have any buggy effects
Case 2: result works fine as well. ped de-spawn and everything goes back to normal
Case 3: simply not crashing.

### Screenshots and/or Logs
![image](https://github.com/YimMenu/YimMenu/assets/101154140/b59b02f8-1e35-49ec-9f48-9c782b34c560)
![image](https://github.com/YimMenu/YimMenu/assets/101154140/a70fe273-a4f2-4a5a-8118-30532185fe3e)
![image](https://github.com/YimMenu/YimMenu/assets/101154140/4c12d287-0d0c-4a04-85c4-e1bdc07e8f85)
![image](https://github.com/YimMenu/YimMenu/assets/101154140/9ece8987-3d63-4ce3-8bab-8c4c79fa1059)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by HyperSABIT** [comment]
Im Also facing an issue when playing heist whenever I invite my friend in the same session my friends cant join my heist, their game freezes until I quit the mission. Then I start the mission from another session and invite them through R* Social Club they can join the game but when the heist starts the Entry vehicle is glitched or bugged if I use my starting vehicle as Alkonost the plane doesn't load. I float in the sky and cant jump also and when using LongFin the boat is glitched in the same way but when I get out of the boat and the boat's bug gets fixed and the boat spawns then when me and my friend come to the main land sometime my friend is teleported outside the map. Also in Diamond Casino Heist my friend gets teleported outside of the map and my character disappears and the main big problem is that I cant enter the casino. When I enter it the game loads infinitely

**Comment by Tayipc38** [comment]
Its nice that you report these, but almost all of them are neither prominent nor relevant issues. Spawning peds in interiors may be an issue, but it isn't one thats worthy of a fix no? Changing your model is not intended in online, so apart from the issue you mentioned, it may be breaking a lot of other things that we will simply never fix as it is not a priority. Spamming features that are also not meant to be in the game in the first place, is sure to cause errors. You can't expect to just be spawning so many squads and expect it to work flawlessly. Deleting these peds, "cleaning" as you call it, is also a networked event. To essentially delete an entity, that entity has to be deleted on all machines. Hence why we utilize something called 'Request Control'. So this case is more of the same. 

With all that out of the way, a real issue that is relevant is for example the vehicle's not moving due to faulty syncs caused in the `can_apply` hook. Or the fact that some UI elements were off screen in terms of the UI window. These are just some examples to give you an idea what bugs and glitches you should be reporting.

And btw, clogging this many issues into a single post is not very handy. Im not telling you to spam the issues section but some of these issues would be tracked and fixed easier if they had their own thread.

**Comment by Yimura** [comment]
Too many sub-issues within one issue.
