### ISSUE TITLE
[Bug]: The robbery mission cannot drive the specified vehicle（prison Break and First round of fundraising）

### ISSUE THREAD

**Issue by aierxiya** [Yimura/YimMenu#1559]
### Describe the bug

The robbery mission cannot drive the specified vehicle（prison Break and First round of fundraising）

### Steps To Reproduce

The robbery mission cannot drive the specified vehicle（prison Break and First round of fundraising）

### Expected Behavior

The robbery mission cannot drive the specified vehicle（prison Break and First round of fundraising）

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Same underlying problem as #1556

**Comment by Tayipc38** [comment]
#1557 should have fix this could you check @aierxiya?
