### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MrEnotobet** [Yimura/YimMenu#1560]
### Describe the bug

when you sit to someones vehicle it desyncs you from another person, on your screen you just staying on one place

### Steps To Reproduce

1.sit to someones vehicle

### Expected Behavior

won't desync

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Duplicate of #1540
