### ISSUE TITLE
[Bug]: When I join my friends or my friends want to join me, it says that session has been timed out and get sent to storymode.

### ISSUE THREAD

**Issue by Scripty2k** [Yimura/YimMenu#1561]
### Describe the bug

Hi there. I've been using this modmenu for quite sometime now with my friends. When we are trying to join eachother, it says timed out. We can't join eachother when we're injected.

### Steps To Reproduce

1. inject yimmenu
2. try and join via online and friends from the gta pause menu / or via player database in the modmenu
3. i get timed out. Or my friends do when theyre not injected but I am

### Expected Behavior

I want my friends to join. I even tried with the player database

### Screenshots and/or Logs

no logs

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by pierrelasse** [comment]
+1

I think it's patched since session browser doesn't work too :(
Also unloading the menu does not work. You will have to restart gta to join friends using socialclub. I really miss the feature :(

**Comment by Scripty2k** [comment]
Yeah that too. I wish I could join my friends when I'm injected. Sadly I have to unload the mod menu before my friends join or if I want to join my friends. But it's not only my friends. I think that the whole server would get locked (but thats just my theory) because maybe it's something in the protection that does this.

**Comment by Rxann** [comment]
don't close this, reopen it
