### ISSUE TITLE
[Bug]:online player's  Ped model

### ISSUE THREAD

**Issue by HanD-798** [Yimura/YimMenu#1563]
### Describe the bug

In the swiped ped model, the costumes of the online player model (including myself) are randomly generated

### Steps To Reproduce

1.Go to world options
2.click ped model-choose online player
3.click Swipe out the PED model

### Expected Behavior

Generate the right online player model

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Fixed in current editions of YimMenu.
