### ISSUE TITLE
[Bug]: Crashing the game when reloading Lua

### ISSUE THREAD

**Issue by drakmemory** [Yimura/YimMenu#1565]
### Describe the bug

Using script. register_ When looped, there will be no problem when adding code and reloading it normally, but if I delete it and write other code before reloading, it will cause the game to crash without any logs

### Steps To Reproduce

First, run this string of code.
`script.register_looped("test",function()
	local mypid = PLAYER.PLAYER_ID()
	log.info("test register_looped")
	script.yield()
end)`
After running, modify it like this before reloading
`log.info("test")`
After reloading, the game crashed without an error log

### Expected Behavior

It should be able to reload normally.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
Thanks for the repro case, managed to replicate, investigating
