### ISSUE TITLE
After the task is over, re-entering will be stuck on the "initializing" of the apartment[Bug]: 

### ISSUE THREAD

**Issue by aierxiya** [Yimura/YimMenu#1566]
### Describe the bug

After the task is over, re-entering will be stuck on the "initializing" of the apartment

### Steps To Reproduce

After the task is over, re-entering will be stuck on the "initializing" of the apartment

### Expected Behavior

After the task is over, re-entering will be stuck on the "initializing" of the apartment

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
This is not how you draft an issue. Stop pasting the same thing in all areas of the template.
