### ISSUE TITLE
Session switcher isn't working.

### ISSUE THREAD

**Issue by 8KV** [Yimura/YimMenu#157]
**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Yimura** [comment]
Yes anything related to modifying script values or blocking events from scripts will no longer work since the new update.

All of the related code will have to be updated for 1.59.

**Comment by Tayipc38** [comment]
1574589, 1575012 are the new globals respectively

**Comment by Yimura** [comment]
Fixed with https://github.com/Yimura/YimMenu/commit/b6e2cd5172183b6d275135a70d98d7658db3544b
