### ISSUE TITLE
[Bug]: Cannot see friend's vehicle driving/moving whilst having the menu open

### ISSUE THREAD

**Issue by fhuihnlsmnzdlkfsdjnlkfjsdn** [Yimura/YimMenu#1573]
### Describe the bug

I can see my friend driving while I'm not in the vehicle with the menu open but when I unload the menu it works just fine

### Steps To Reproduce

Load menu
Enter friend's vehicle as passenger
Nothing happens
Unload menu
Can see vehicle move

### Expected Behavior

Vehicle moves while menu is injected

### Store

Epic Games

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by eternights** [comment]
When you leave the car while the driver is moving, the car is moved and you keep the last position you entered the car.

**Comment by Tayipc38** [comment]
Have you downloaded the last nightly? We have removed the code that was responsible for this.

**Comment by Yimura** [comment]
Should've been fixed and no response from OP.
