### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1576]
### Describe the bug

I got crashed while driving a Car, not sure who/what caused it.

### Steps To Reproduce

1. Updated menu to latest version.
2. Got into car (XA21).
3. Driving the car and got crashed in like a minute.

### Expected Behavior

Shouldn't Crash

### Screenshots and/or Logs

[18:30:31.9085964][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7D50E0000 Size: 67158528
ntdll.dll Base Address: 0x7FFC51070000 Size: 1154048
KERNEL32.DLL Base Address: 0x7FFC50B50000 Size: 519168
KERNELBASE.dll Base Address: 0x7FFC4EB40000 Size: 1255424
apphelp.dll Base Address: 0x7FFC4C070000 Size: 323584
AcGenral.DLL Base Address: 0x7FFC2BB40000 Size: 243200
msvcrt.dll Base Address: 0x7FFC50F60000 Size: 477184
sechost.dll Base Address: 0x7FFC4F9D0000 Size: 412672
RPCRT4.dll Base Address: 0x7FFC4F520000 Size: 923136
SHLWAPI.dll Base Address: 0x7FFC4F810000 Size: 182784
USER32.dll Base Address: 0x7FFC509A0000 Size: 581120
win32u.dll Base Address: 0x7FFC4EAE0000 Size: 42496
GDI32.dll Base Address: 0x7FFC51000000 Size: 61952
gdi32full.dll Base Address: 0x7FFC4EEB0000 Size: 669696
msvcp_win.dll Base Address: 0x7FFC4E990000 Size: 344064
ucrtbase.dll Base Address: 0x7FFC4EFD0000 Size: 735744
ole32.dll Base Address: 0x7FFC4F650000 Size: 832000
combase.dll Base Address: 0x7FFC4FEF0000 Size: 2327040
SHELL32.dll Base Address: 0x7FFC50250000 Size: 5803008
ADVAPI32.dll Base Address: 0x7FFC50E50000 Size: 427520
USERENV.dll Base Address: 0x7FFC4E610000 Size: 108032
MPR.dll Base Address: 0x7FFC2AB70000 Size: 71168
SspiCli.dll Base Address: 0x7FFC4E640000 Size: 123392
IMM32.DLL Base Address: 0x7FFC4F340000 Size: 122368
PSAPI.DLL Base Address: 0x7FFC50B40000 Size: 2048
WS2_32.dll Base Address: 0x7FFC50D30000 Size: 275456
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFC1AF70000 Size: 96256
VERSION.dll Base Address: 0x7FFC489D0000 Size: 10752
DSOUND.dll Base Address: 0x7FFC03F00000 Size: 380416
CRYPT32.dll Base Address: 0x7FFC4E7E0000 Size: 1100288
WINTRUST.dll Base Address: 0x7FFC4EE40000 Size: 292864
bink2w64.dll Base Address: 0x7FFC2BAB0000 Size: 307712
WININET.dll Base Address: 0x7FFC38180000 Size: 2019840
bcrypt.dll Base Address: 0x7FFC4EB10000 Size: 103424
WINMM.dll Base Address: 0x7FFC43020000 Size: 81408
OLEAUT32.dll Base Address: 0x7FFC4F8D0000 Size: 608256
MF.dll Base Address: 0x7FFC37D00000 Size: 340992
msdmo.dll Base Address: 0x7FFC38880000 Size: 13312
MFPlat.DLL Base Address: 0x7FFC37AA0000 Size: 1409536
MFReadWrite.dll Base Address: 0x7FFC134B0000 Size: 918016
PROPSYS.dll Base Address: 0x7FFC4A2C0000 Size: 631296
cfgmgr32.dll Base Address: 0x7FFC4E940000 Size: 218624
powrprof.dll Base Address: 0x7FFC4E1F0000 Size: 70656
shcore.dll Base Address: 0x7FFC4F1B0000 Size: 476672
winmmbase.dll Base Address: 0x7FFC380D0000 Size: 95232
WTSAPI32.dll Base Address: 0x7FFC4C050000 Size: 37888
d3dx9_43.dll Base Address: 0x7FFC1CF10000 Size: 2280960
d3d9.dll Base Address: 0x7FFC29040000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFC1AD00000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFC46D60000 Size: 48128
DINPUT8.dll Base Address: 0x7FFC2FAD0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
IPHLPAPI.DLL Base Address: 0x7FFC4DB10000 Size: 170496
SETUPAPI.dll Base Address: 0x7FFC4FA80000 Size: 864768
kernel.appcore.dll Base Address: 0x7FFC4C540000 Size: 16384
dwmapi.dll Base Address: 0x7FFC4C510000 Size: 99328
windows.storage.dll Base Address: 0x7FFC4C820000 Size: 5819904
OPENGL32.dll Base Address: 0x7FFC1D180000 Size: 909312
Wldp.dll Base Address: 0x7FFC4E130000 Size: 94720
GLU32.dll Base Address: 0x7FFC35710000 Size: 122880
MFCORE.DLL Base Address: 0x7FFC36510000 Size: 3962880
ksuser.dll Base Address: 0x7FFC35F00000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFC4E010000 Size: 10752
UMPDC.dll Base Address: 0x7FFC4E1D0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFC4E750000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFC398F0000 Size: 105472
MSASN1.dll Base Address: 0x7FFC4E330000 Size: 34816
inputhost.dll Base Address: 0x7FFC45280000 Size: 976384
wintypes.dll Base Address: 0x7FFC4B2D0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFC4BD00000 Size: 606720
CoreUIComponents.dll Base Address: 0x7FFC4B9A0000 Size: 1804800
ntmarta.dll Base Address: 0x7FFC4D860000 Size: 140288
dbghelp.dll Base Address: 0x7FFC421C0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFC33AD0000 Size: 136704
d3d12.dll Base Address: 0x7FFC2F6F0000 Size: 73728
CRYPTSP.dll Base Address: 0x7FFC4E020000 Size: 46080
rsaenh.dll Base Address: 0x7FFC4D740000 Size: 142336
uxtheme.dll Base Address: 0x7FFC4C150000 Size: 382464
clbcatq.dll Base Address: 0x7FFC50DA0000 Size: 437760
dxdiagn.dll Base Address: 0x7FFC2BA20000 Size: 395264
DEVOBJ.dll Base Address: 0x7FFC4E500000 Size: 109056
WMICLNT.dll Base Address: 0x7FFC49A10000 Size: 31744
d3d11.dll Base Address: 0x7FFC4A4A0000 Size: 1853440
dxgi.dll Base Address: 0x7FFC4D120000 Size: 614912
wbemprox.dll Base Address: 0x7FFC440C0000 Size: 27648
wbemcomn.dll Base Address: 0x7FFC44030000 Size: 328704
wbemsvc.dll Base Address: 0x7FFC3AA20000 Size: 7168
fastprox.dll Base Address: 0x7FFC40BF0000 Size: 708608
amsi.dll Base Address: 0x7FFC2BF70000 Size: 62464
profapi.dll Base Address: 0x7FFC4E690000 Size: 68608
MpOav.dll Base Address: 0x7FFC2BEF0000 Size: 204800
nvapi64.dll Base Address: 0x7FFC464F0000 Size: 6282752
cryptnet.dll Base Address: 0x7FFC487E0000 Size: 135168
drvstore.dll Base Address: 0x7FFC48370000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFC2FA90000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFC4A290000 Size: 7680
imagehlp.dll Base Address: 0x7FFC4F9A0000 Size: 45056
nvspcap64.dll Base Address: 0x7FFBC96E0000 Size: 2055680
NSI.dll Base Address: 0x7FFC4F9C0000 Size: 7680
dhcpcsvc.DLL Base Address: 0x7FFC49070000 Size: 61440
MSCTF.dll Base Address: 0x7FFC50C10000 Size: 864256
textinputframework.dll Base Address: 0x7FFC453E0000 Size: 723968
WINSTA.dll Base Address: 0x7FFC4E0C0000 Size: 219648
nvldumdx.dll Base Address: 0x7FFC42730000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFC3AD10000 Size: 36384256
NvCamera64.dll Base Address: 0x7FFC1A490000 Size: 4209664
HID.DLL Base Address: 0x7FFC4CFC0000 Size: 20480
WindowsCodecs.dll Base Address: 0x7FFC48040000 Size: 1328128
XINPUT9_1_0.dll Base Address: 0x7FFC4A1A0000 Size: 4096
MessageBus.dll Base Address: 0x7FFC32A00000 Size: 5349888
dxcore.dll Base Address: 0x7FFC43D10000 Size: 147968
d3dcompiler_47_64.dll Base Address: 0x7FFC1A080000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFC31350000 Size: 5771776
MMDevApi.dll Base Address: 0x7FFC48920000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFC2B990000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFC49200000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFC4C1F0000 Size: 31744
Windows.UI.dll Base Address: 0x7FFC455B0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFC48A00000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFC484C0000 Size: 1468416
avrt.dll Base Address: 0x7FFC49110000 Size: 5632
MessageBus.dll Base Address: 0x7FFC33140000 Size: 5349888
napinsp.dll Base Address: 0x7FFC24DD0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFC24BF0000 Size: 66048
NLAapi.dll Base Address: 0x7FFC4A0E0000 Size: 68608
wshbth.dll Base Address: 0x7FFC24F50000 Size: 43008
mswsock.dll Base Address: 0x7FFC4DE20000 Size: 331776
DNSAPI.dll Base Address: 0x7FFC4DB50000 Size: 595456
winrnr.dll Base Address: 0x7FFC243B0000 Size: 32768
mdnsNSP.dll Base Address: 0x599A0000 Size: 91136
fwpuclnt.dll Base Address: 0x7FFC454E0000 Size: 288768
rasadhlp.dll Base Address: 0x7FFC47D60000 Size: 7168
DiscordHook64.dll Base Address: 0x7FFC19F70000 Size: 780288
gpapi.dll Base Address: 0x7FFC4CFD0000 Size: 69120
WINNSI.DLL Base Address: 0x7FFC49120000 Size: 11776
socialclub.dll Base Address: 0x7FFC1D2B0000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFC1E0F0000 Size: 685568
libcef.dll Base Address: 0x7FFB91D60000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFC4F0D0000 Size: 684032
Secur32.dll Base Address: 0x7FFC38130000 Size: 11264
OLEACC.dll Base Address: 0x7FFC396D0000 Size: 260608
COMCTL32.dll Base Address: 0x7FFC34FA0000 Size: 560128
NETAPI32.dll Base Address: 0x7FFC39090000 Size: 47616
DWrite.dll Base Address: 0x7FFC391A0000 Size: 1601024
WINSPOOL.DRV Base Address: 0x7FFC39740000 Size: 364544
credui.dll Base Address: 0x7FFC217C0000 Size: 61952
dxva2.dll Base Address: 0x7FFC23000000 Size: 96256
UIAutomationCore.DLL Base Address: 0x7FFC20A30000 Size: 2041344
urlmon.dll Base Address: 0x7FFC3A3E0000 Size: 1278464
WINHTTP.dll Base Address: 0x7FFC486D0000 Size: 845312
ncrypt.dll Base Address: 0x7FFC4E1A0000 Size: 102400
wevtapi.dll Base Address: 0x7FFC49610000 Size: 296960
ESENT.dll Base Address: 0x7FFC34950000 Size: 2585088
CRYPTUI.dll Base Address: 0x7FFC2F640000 Size: 246272
USP10.dll Base Address: 0x7FFC2C5F0000 Size: 512
iertutil.dll Base Address: 0x7FFC3AA50000 Size: 549888
srvcli.dll Base Address: 0x7FFC3A3A0000 Size: 54272
netutils.dll Base Address: 0x7FFC4DC20000 Size: 19456
WKSCLI.DLL Base Address: 0x7FFC4D8A0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFC410E0000 Size: 61440
NTASN1.dll Base Address: 0x7FFC4E160000 Size: 81408
D3DCompiler_47.dll Base Address: 0x7FFC4A710000 Size: 3396608
FirewallAPI.dll Base Address: 0x7FFC4D360000 Size: 364544
fwbase.dll Base Address: 0x7FFC4D2F0000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FFC36B40000 Size: 216064
wdmaud.drv Base Address: 0x7FFC2F810000 Size: 193024
msacm32.drv Base Address: 0x7FFC4A1B0000 Size: 17920
MSACM32.dll Base Address: 0x7FFC2F7F0000 Size: 74240
midimap.dll Base Address: 0x7FFC49AA0000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFC2C510000 Size: 42496
dhcpcsvc6.DLL Base Address: 0x7FFC49090000 Size: 23552
SL_0PRMV.dll Base Address: 0x7FFB9ECA0000 Size: 14861824
MSVCP140.dll Base Address: 0x7FFC390D0000 Size: 346112
VCRUNTIME140.dll Base Address: 0x7FFC397E0000 Size: 65024
VCRUNTIME140_1.dll Base Address: 0x7FFC388B0000 Size: 15360
schannel.DLL Base Address: 0x7FFC4D660000 Size: 480768
mskeyprotect.dll Base Address: 0x7FFC2D8A0000 Size: 48640
ncryptsslp.dll Base Address: 0x7FFC2CC80000 Size: 78848
xinput1_4.dll Base Address: 0x7FFC47830000 Size: 30208
Dumping registers:
RAX: 0x7601F3D00003300C
RCX: 0x218A17817A0
RDX: 0x218A7A2E770
RBX: 0x218A17817A0
RSI: 0x218A1781780
RDI: 0x216E014CC40
RSP: 0x66A88FF660
RBP: 0x1
R8:  0x216DD3E2D20
R9:  0x218A7A2E770
R10: 0x216E014CC40
R11: 0xFF000
R12: 0x0
R13: 0x0
R14: 0x10F4
R15: 0x888
Dumping stacktrace:
[0]	GTA5.exe+0x53F754 0x7FF7D561F754
[1]	GTA5.exe+0x1666C01 0x7FF7D6746C01
[2]	GTA5.exe+0x1666B1E 0x7FF7D6746B1E
[3]	GTA5.exe+0x16413C5 0x7FF7D67213C5
[4]	GTA5.exe+0x1641D62 0x7FF7D6721D62
[5]	GTA5.exe+0x164AA96 0x7FF7D672AA96
[6]	GTA5.exe+0x12FB80E 0x7FF7D63DB80E
[7]	KERNEL32.DLL BaseThreadInitThunk
[8]	ntdll.dll RtlUserThreadStart
--------End of exception--------

### Store

Rockstar

### Additional context

Not sure what caused this, If ya can find out thru logs please let me know :(

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iDominiqe** [comment]
There are many types of crashes that Yimenu cannot handle all types of crashes, especially since they are frequently updated. I literally had the same the other day, the game froze and the console did not stop showing different codes, it was fun at the same time and sad, because the players just put forward a crash against others 😀

**Comment by CypherMorgan** [comment]
Yeah, I know that part but I was just wondering what could've caused this crash as I was in a session with bunch of my friends and no one else from them used their menu to crash me. Might be something related to GTA causing Crash (Don't really know).

**Comment by iDominiqe** [comment]
You know @CypherMorgan  that there is a database of players in the network section, all the players who tried to harm you somehow are saved there, but there are also avengers who are similarly trying to go through the list and crash you, because you may have broken the game yesterday or the day before yesterday, while that he can enter as a spectator SCTV

**Comment by CypherMorgan** [comment]
> You know @CypherMorgan that there is a database of players in the network section, all the players who tried to harm you somehow are saved there, but there are also avengers who are similarly trying to go through the list and crash you, because you may have broken the game yesterday or the day before yesterday, while that he can enter as a spectator SCTV

I do know about it. Anyways I figured out what was causing the crash, it was the injector I use(Stand lauchpad) which was outdated. So, My bad about claiming it as the Menu's Bug.

**Comment by Tayipc38** [comment]
>  I use(Stand lauchpad) which was outdated. So, My bad about claiming it as the Menu's Bug.

Refrain from using anything from that garbage.

**Comment by CypherMorgan** [comment]
> 

Agreed. Lol

**Comment by CypherMorgan** [comment]
I have a doubt, should I close this as completed or just let it be here?

**Comment by Yimura** [comment]
> I have a doubt, should I close this as completed or just let it be here?

You gave steps to reproduce, does this happen every time you follow those steps?

**Comment by CypherMorgan** [comment]
For me It happened 3 times (whenever I open game and load menu, I usually spawn the same car and use it.) So, I did the same thing each time I got crashed so I thought it would be caused cuz of some issue related with menu as I was getting the Logs in the console. But particularly it was cause by a creepy outdated Injector(I tried changing it tonight) and the game doesn't crashes anymore.

That issue got reproduced within 1-2 minutes of joining the online session with menu injected.

**Comment by iDominiqe** [comment]
> That issue got reproduced within 1-2 minutes of joining the online session with menu injected.

Can you recommend a good injector?

**Comment by CypherMorgan** [comment]
> > That issue got reproduced within 1-2 minutes of joining the online session with menu injected.
> 
> Can you recommend a good injector?

I used Stand Launchpad for it...

**Comment by Yimura** [comment]
The type of injector doesn’t really matter, they will work all just as reliable.

It comes down to personal preference really.

**Comment by maybegreat48** [comment]
Stand's injector renames the DLL and probably manual maps it instead of using `LoadLibrary`. Just use Xenos

**Comment by CypherMorgan** [comment]
> Stand's injector renames the DLL and probably manual maps it instead of using `LoadLibrary`. Just use Xenos

Oh..
Alright

**Comment by CypherMorgan** [comment]
@Yimura (Sorry for the tag) As the Issue cannot be reproduced again by me as well, should I close this issue as resolved?

**Comment by iDominiqe** [comment]
is there a difference in the crash of the game associated with direct x versions?

**Comment by Yimura** [comment]
Closing as author is unable to reproduce the crash.
