### ISSUE TITLE
[虫子]：There is a vehicle problem, and saving the vehicle doesn't work.

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#1581]
### Describe the bug

The save vehicle doesn't seem to work. There is no response after clicking. How to solve it? There is no response in the online mode or the story mode.

### Steps To Reproduce

1个车辆选项
2召唤和生成车辆
3保存车辆，点击后没有响应

### Expected Behavior

In the previous version (f6969d8), a .json vehicle file will be generated, but now it seems to be unresponsive.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Unable to reproduce, works as intended.

Do know that the folder used by YimMenu to save data is no longer `%appdata%/BigBaseV2/` but instead has been moved to `%appdata%/YimMenu/`.
