### ISSUE TITLE
[虫子]：The player switch that shows human evaporation does not work.

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#1582]
### Describe the bug

The player switch that shows the evaporation in the world does not work, and the player who has disappeared cannot be seen on the radar. After the player chooses the ceo skill ghost organization, the player's position cannot be displayed on the map.

### Steps To Reproduce

The player switch that shows the evaporation in the world does not work, and the player who has disappeared cannot be seen on the radar. After the player chooses the ceo skill ghost organization, the player's position cannot be displayed on the map.

### Expected Behavior

The player switch that shows the evaporation in the world does not work, and the player who has disappeared cannot be seen on the radar. After the player chooses the ceo skill ghost organization, the player's position cannot be displayed on the map.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Your way of drafting these issues is getting on my nerves.

**Comment by Yimura** [comment]
Unclear what exactly is reported in this issue, could you clarify? What is meant by "evaporation" exactly?

**Comment by maybegreat48** [comment]
Are you co-loading YimMenu with something else? Menus like Stand (including the free version) interfere with YimMenu's script patching system, breaking features such as reveal players (I'm assuming that's what you mean by "human evaporation")

**Comment by Yimura** [comment]
Closing because it's unclear what even was reported in this issue and there's no response from issue author.
