### ISSUE TITLE
[Bug]: script.sleep causing crash

### ISSUE THREAD

**Issue by janisslsm** [Yimura/YimMenu#1585]
### Describe the bug

executing script.sleep causes the game to crash.

### Steps To Reproduce

1. Create a script
```
log.info("Loaded")
script.sleep(2)
log.info("slept")
``` 
2. Execute it
3. crash

### Expected Behavior

sleeps without crash

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11930137/cout.log)

### Store

Epic Games

### Additional context

tested it with local build and the nightly, both crash the same. local build shows that it's at src/script.cpp line 84, tried null checking and setting `m_main_fiber = GetCurrentFiber();` but neither helped.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Thanks for the extensive bug report we’ll take a look at it.

**Comment by xiaoxiao921** [comment]
script.sleep only work inside script.registet_looped and script.run_inside_fiber

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/script.md

Let this issue open, we need to change the doc to make this more clear

**Comment by xiaoxiao921** [comment]
Note for self: Only expose script.sleep and script yield inside run_in_fiber and register_looped and pass the script instance to the callback

**Comment by janisslsm** [comment]
> script.sleep only work inside script.registet_looped and script.run_inside_fiber

Thanks, that did the trick.
