### ISSUE TITLE
[Bug]: lua memory api error?

### ISSUE THREAD

**Issue by Alice2333g** [Yimura/YimMenu#1586]
### Describe the bug

in the previous versions, they worked very well, but now they seem to be ineffective. return is a pile of garbage int

### Steps To Reproduce

```
lua = {}
function lua.current_character_slot()
	local Pointer = memory.allocate()
	local Address = Pointer:add(Pointer:get_address())
	STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), Address, -1)
	outvalue = Address:get_dword()
	return outvalue
end
```
### Expected Behavior

null

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/memory.md#allocatesize

**Comment by xiaoxiao921** [comment]
for the
```lua
STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), Address, -1)
```
line, the system has changed, you should do something like this instead:

```lua
lua = {}
function lua.current_character_slot()
    -- Can be anything
    local randomStuff = 0123474748435

    res, outvalue = STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), randomStuff, -1)

    return outvalue
end
```

**Comment by Tayipc38** [comment]
> for the
> 
> ```lua
> STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), Address, -1)
> ```
> 
> line, the system has changed, you should do something like this instead:
> 
> ```lua
> lua = {}
> function lua.current_character_slot()
>     -- Can be anything
>     local randomStuff = 0123474748435
> 
>     res, outvalue = STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), randomStuff, -1)
> 
>     return outvalue
> end
> ```

Relying on the stat is better but just for info, global 1574918 also tracks the current char.

**Comment by Alice2333g** [comment]
> 对于
> 
> ```lua
> STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), Address, -1)
> ```
> 
> 行，系统已更改，您应该改为执行以下操作：
> 
> ```lua
> lua = {}
> function lua.current_character_slot()
>     -- Can be anything
>     local randomStuff = 0123474748435
> 
>     res, outvalue = STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), randomStuff, -1)
> 
>     return outvalue
> end
> ```

return nil value

**Comment by xiaoxiao921** [comment]
```lua
script.run_in_fiber(function()
    _, outvalue = STATS.STAT_GET_INT(MISC.GET_HASH_KEY("MPPLY_LAST_MP_CHAR"), 0, -1)
    log.info(outvalue)
end)
```
works for me

**Comment by Yimura** [comment]
Resolved.
