### ISSUE TITLE
[Bug]: Unable to save vehicle

### ISSUE THREAD

**Issue by light-lgt** [Yimura/YimMenu#1592]
### Describe the bug

Unable to save vehicle

### Steps To Reproduce

1.Ride on a vehicle
2.Save vehicle
3.No response

### Expected Behavior

Fix this bug

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
I am assuming you tried the persistent vehicle thing?

**Comment by CypherMorgan** [comment]
> I am assuming you tried the persistent vehicle thing?

If this is the case, then works fine for me.(The Persistent Vehicle)

**Comment by Yimura** [comment]
Yup unable to reproduce.

If you are sharing the persistent vehicles between friends make sure to use `%appdata%/YimMenu` and not `%appdata%/BigBaseV2/`. We have stopped using `%appdata%/BigBaseV2`.

**Comment by Yimura** [comment]
No response from thread author, I will reopen if they can confirm the issue is still happening to them.
