### ISSUE TITLE
[Request]: Upside down map 😅

### ISSUE THREAD

**Issue by iDominiqe** [Yimura/YimMenu#1597]
### Solution

Must be spawned with Lancescript and not menyoo.  Should be able to be networked.  Lancescript also says that it uses modded objects just ignore it 😗 
https://www.guilded.gg/stand/groups/x3ZgB10D/channels/bae59c11-4c7a-4a77-9738-d3876a47c786/docs/302105

### Reason

It will be very cool 😊 some players think it's a bug 🤣

### Additional context

Download Link
[!Upside down map.zip](https://github.com/YimMenu/YimMenu/files/11952446/Upside.down.map.zip)

![b471cf24e3e542ff2989b4df88c1c67c-Full](https://github.com/YimMenu/YimMenu/assets/115355282/8d1cf38f-bb8e-4bc0-bbf0-96dd9841414c)

**Comment by FIying-Scotsman** [comment]
Surprised Menyoo can’t spawn this (although I’ve never tried to be fair). It’s just the city LOD model you see when on Perico. You can spawn it like any other prop which means you should be able to spawn it via Menyoo (or any other menu which supports object loading).

It’s also networked, yes (so other players on Perico with you see it).

**Comment by ghost** [comment]
Even if this is not added, I hope someone writes a lua script for this case 😅

**Comment by maybegreat48** [comment]
> Surprised Menyoo can’t spawn this

You need a [bypass](https://github.com/YimMenu/YimMenu/blob/master/src/util/world_model.hpp#L30) to spawn world models

**Comment by iDominiqe** [comment]
> Even if this is not added, I hope someone writes a lua script for this case 😅

And if you load this modified map into the game itself through the menu stand, and then export it only in a different format as a source, is it possible?
Or are there special scripts that can read data from xml files?

**Comment by thomaskredpath** [comment]
Isn't this a movie? ;)

**Comment by 17z7h0m4s** [comment]
Doesn't this happen in a movie?

**Comment by iDominiqe** [comment]
> Doesn't this happen in a movie?

![InnocentGoodnaturedKangaroo-size_restricted](https://github.com/YimMenu/YimMenu/assets/115355282/7d3b8189-704b-4b8c-a44b-005eba69c151)
![maxresdefault](https://github.com/YimMenu/YimMenu/assets/115355282/cebc6bb9-d10c-4496-8fd7-056a881251cb)

**Comment by dynamoNg** [comment]
here all talking about upside down world and I wish to spawn a church - 
https://www.gta5-mods.com/maps/realistic-church-gtav-menyoo-fivem

**Comment by lonelybud** [comment]
ever talking about upside down world. me want to spawn a church - 
https://www.gta5-mods.com/maps/realistic-church-gtav-menyoo-fivem

i think xml parser can be used to spawn individual objects as done with xml vehicles.

**Comment by Yimura** [comment]
XML maps can be loaded into YimMenu since a good while now, closing.
