### ISSUE TITLE
[Bug]: Ingame Overlay moved out of position

### ISSUE THREAD

**Issue by laptoppe** [Yimura/YimMenu#1599]
### Describe the bug

It's what the title says. I somehow managed to move the overlay from its original position, and can't figure out how to move it back.

### Steps To Reproduce

1- Get on an Avenger.
2- Set it to fly on Autopilot somewhere.*
3- Go into the Avenger's hold.
4- Get on one of the turrets.
5- Move the camera around in some particular way (?), while intermittently holding the mouse button (Shooting while aiming- as if you were tracking around different targets)
6- ???
7- Success

### Expected Behavior

The overlay should usually stay on the top left corner, unmoved by the mouse or any settings.

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/138631123/92406899-8801-4acd-b039-f34e667664b4)

### Store

Epic Games

### Additional context

I was doing the Bogdan Problem finale with some random as the helicopter team, shooting at the buzzards(?) that approached the Avenger, and somehow "dragged" the overlay menu while holding m1 to shoot continuously.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by iDominiqe** [comment]
Solution - don't fly with the autopilot on 🤣

**Comment by laptoppe** [comment]
Addendum: Persists after both Menu and Game resets.

**Comment by Yimura** [comment]
Now to move the overlay you can go to settings and set the overlay to also be visible when the menu is open, then while it is open with the menu open as well you can use your mouse to drag/move it to wherever you want.

Note for devs:
This can be fixed to be fair by setting the no mouse input flag on the overlay window.
