### ISSUE TITLE
[Bug]: Crash after injection

### ISSUE THREAD

**Issue by Trapped-Bear** [Yimura/YimMenu#1601]
### Describe the bug

I have tried building brand new source code, but injecting it can still cause the game to crash

### Steps To Reproduce

1.Clone source code
2.Open the YimMenu folder using Visual Studio
3.Clicking Build All
4.Open game injection it

### Expected Behavior

Should not cause the game to crash

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11955547/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Which language are you using for YimMenu?

**Comment by Trapped-Bear** [comment]
> 您使用哪种语言进行 YimMenu？

C++，I followed Wiki's instructions

**Comment by Yimura** [comment]
No I meant which translation language are you using? Or is this your first time injecting YimMenu then it'll most likely be en_US.
Which language is your game set in?

@maybegreat48 this might have something to do with your PR where the menu is trying to force load the translation file depending on the game language.

**Comment by Trapped-Bear** [comment]
> 不，我的意思是你使用哪种翻译语言？或者这是您第一次注入 YimMenu，那么它很可能是en_US。您的游戏设置了哪种语言？
> 
> 这可能与您的 PR 有关，其中菜单试图根据游戏语言强制加载翻译文件。

chinese

**Comment by Yimura** [comment]
Thanks for the response we'll take a look at it.

As a temporary solution you can comment the following lines and you shouldn't have this error occur anymore:
https://github.com/YimMenu/YimMenu/blob/cbc80e6caf8f2f613d4c5fa5813ff8295b66f8c2/src/services/notifications/notification_service.cpp#L9-L10

After which you can build the menu and inject it again.

**Comment by Trapped-Bear** [comment]
> 不，我的意思是你使用哪种翻译语言？或者这是您第一次注入 YimMenu，那么它很可能是en_US。您的游戏设置了哪种语言？
> 
> 这可能与您的 PR 有关，其中菜单试图根据游戏语言强制加载翻译文件。

I just tried setting the game to English, but it still caused the game to crash

**Comment by Trapped-Bear** [comment]
> Thanks for the response we'll take a look at it.
> 
> As a temporary solution you can comment the following lines and you shouldn't have this error occur anymore:
> 
> https://github.com/YimMenu/YimMenu/blob/cbc80e6caf8f2f613d4c5fa5813ff8295b66f8c2/src/services/notifications/notification_service.cpp#L9-L10
> 
> After which you can build the menu and inject it again.

It can be used normally. Thank you for your help
