### ISSUE TITLE
[Bug]: Command executor text to the side

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1613]
### Describe the bug

The command executors text is off the visible box area

### Steps To Reproduce

1. open command executor

### Expected Behavior

The text should look as in previous versions

### Screenshots and/or Logs

![Screenshot 2023-07-05 214249](https://github.com/YimMenu/YimMenu/assets/88204341/71cb535d-d372-4b35-b2a7-38823fc1e30d)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
Can confirm this also happen if you try to drag the window by mistake, probably should use some extra ImGui flags for this

**Comment by Yimura** [comment]
Have been able to reproduce this as well, you can toggle the twitching to the side by left clicking (if you mouse cursor clicked in it when tabbed out).
