### ISSUE TITLE
[Request]: Make Overlay Indicators settings be persistent

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#1614]
### Problem

When I turn off an option in Overlay Indicators, and then unload the menu and load it, that option is back on and vice versa. I believe it just loads the defaults.

### Solution

When I turn off an option from Overlay Indicators, make it so when I unload and load the menu, it "remembers" that I had such option turned off.

### Reason

Since a lot of the options get saved to settings.json, I figured this could have been forgotten or left out on purpose.

**Comment by Democles85** [comment]
They should be on the latest version, it was my bad, forgor that I had only done that in my own version and not on the Pull Req

**Comment by Yimura** [comment]
> They should be on the latest version, it was my bad, forgor that I had only done that in my own version and not on the Pull Req

You closed your PR so it hasn't been merged into master yet, I can reopen your PR and then merge it if it's finished.

Edit:
Nvm you made a new PR with those changes in it.
If you want to work on multiple features you can create different branches and then create PR's to the main repo simultaneously.

**Comment by Democles85** [comment]
> > They should be on the latest version, it was my bad, forgor that I had only done that in my own version and not on the Pull Req
> 
> You closed your PR so it hasn't been merged into master yet, I can reopen your PR and then merge it if it's finished.
> 
> Edit: Nvm you made a new PR with those changes in it. If you want to work on multiple features you can create different branches and then create PR's to the main repo simultaneously.

I did create different branches, but for some reason it showed the same things...
