### ISSUE TITLE
[Request]: Create an official place to share LUA scripts

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1615]
### Solution

A UC thread or something

### Reason

The average user probably doesn't know how to create scripts. Having one place containing all community created scripts would be good.

**Comment by gir489returns** [comment]
I'm banned from UC, and seeing as how the project has an official website, I think there would be a proper place to store/showcase them.

**Comment by Yimura** [comment]
> I'm banned from UC, and seeing as how the project has an official website, I think there would be a proper place to store/showcase them.

Yeah I had an idea of making a place to store them all on Github, where you make an issue on a repo and Github bot automatically creates a repo and adds you to it. This repo will then become visible on some sort of view in the menu.

Problem I'm having is free time to do all this.
Combined with the site being statically hosted by Github.

**Comment by Harmless05** [comment]
Why not just have a Discord server (or guilded) for it?

**Comment by Yimura** [comment]
We have Matrix

**Comment by ghost** [comment]
Why not add a section for lua scripts in discussions on github? Users can even attach files.

**Comment by Yimura** [comment]
> Why not add a section for lua scripts in discussions on github? Users can even attach files.

I'm working on central place to share Lua's, something a little better than just a discussion on Github.

It'll be available under the https://github.com/YimMenu-Lua organisation.

**Comment by ghost** [comment]
Ok
  
  
  
  
  
  
  

  
  
>

**Comment by ghost** [comment]
sounds good.

**Comment by holysnipz** [comment]
> UC thread

people gonna make requests more than sharing stuffs there, and that thread gonna become messy real quick

making repo is better solution than that at least

------------------
<details><summary>Rant</summary>
<p>
and with the current state of GTAV forum after these <i>two</i> skids still alive and well, while kept playing victim and abusing UC system, kinda make me sick tbh
<p>
</details>

**Comment by Yimura** [comment]
Lua sharing is now possible by creating a repo under the YimMenu-Lua organisation.

You can create a repository under that org by creating an issue here: https://github.com/YimMenu-Lua/submission/issues
