### ISSUE TITLE
[Request]: Discord Server

### ISSUE THREAD

**Issue by HugoMskn** [Yimura/YimMenu#1619]
### Problem

It's not very easy to get intels on bugs or commons mistakes etc...

### Solution

Making a discord server would allow people to talk together, share ideas, lua scripts and new designs

### Reason

Why not ?

**Comment by gir489returns** [comment]
What about for people who aren't transgender or molest kids? 🤔 

Discord's community standards explicitly state that the use of their platform for cheating.

[Do not share content that violates anyone's intellectual property or other rights. This includes sharing or selling game cheats or hacks.](https://discord.com/guidelines)

I suggest Telegram instead.

**Comment by maybegreat48** [comment]
See #361. The discord server is banned, you can use the matrix server linked there instead
