### ISSUE TITLE
If player is far away the bring feature doesn't work.

### ISSUE THREAD

**Issue by 8KV** [Yimura/YimMenu#162]
**Describe the bug**
If player is far away the bring feature doesn't work.
It starts working if you spectate the player.

**To Reproduce**
1. Go far away from player
2. Click "Bring"
3. Warning: "Target player is not in a vehicle."

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Yimura** [comment]
This is an issue with how GTA V works, it unloads entities that are far away, you can see the same happening on the info window of a player. One moment it will say the player isn't in a vehicle, but the other (when you've started spectating them) it suddenly knows that person is in a vehicle.

So a fix you can spectate the person and then press bring, there might be some more elaborate solutions like requesting to load entities from that player (probably something related to bubbles).
