### ISSUE TITLE
[Bug]:  CMake Error - Could not find git for clone of minhook-populate

### ISSUE THREAD

**Issue by WHots** [Yimura/YimMenu#1620]
### Describe the bug

Getting this cmake error when trying to build the project in VS 2022 .. something about minhook.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at Z:/VS 2022 Comm/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/ExternalProject.cmake:2806 (message):
  error: could not find git for clone of minhook-populate		Z:/VS 2022 Comm/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/ExternalProject.cmake	2806	
`

Why can't you just make a solution :sad

### Steps To Reproduce

1 Just build the project.

### Expected Behavior

Expect it to build the project, but it gives cmake error.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development#visual-studio-1

read this

**Comment by WHots** [comment]
@xiaoxiao921  I've read this, I have cmake utilities installed .. I'm not git cloning it, idk if that's the issue i'm just downloading the repo from github normally. - opening local folder - let VS do its setup stuff - then when i try to build Local Machine - x64 Release it get the cmake error for minhook-populate

**Comment by gir489returns** [comment]
Did you do a recursive pull when you setup the repository?

**Comment by WHots** [comment]
@xiaoxiao921 `ln1610: message(FATAL_ERROR "CMake step for ${contentName} failed: ${result}")` Cmake generation failed.

**Comment by WHots** [comment]
I've tried doing it with cloning and manually downloading the repo.

**Comment by Yimura** [comment]
Well, how about you follow the guide how it is written? If you don't follow it, step by step, it's not going to work.

Obviously, you can do certain steps differently, but that means you need to do several things manually. Either follow the guide how it is written or you're on your own. If you follow the guide and still have issues then you're free to come here and ask questions.
