### ISSUE TITLE
[Bug]: invalid sector position crash spam

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1621]
### Describe the bug

getting a flow of warning messages

### Steps To Reproduce

1. inject the file
2. wait till it loads
3. check the console

### Expected Behavior

no messages overflood 

### Screenshots and/or Logs

```
<paste your logs here>
```
![bug](https://github.com/YimMenu/YimMenu/assets/13076710/07ab6a33-7e8d-4adc-8280-1d50a2db0573)

### Store

Epic Games

### Additional context
I've tried emtying the cache, but still same problem
This problem doesn't show up with the nightly build of the 4th of july

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
Why did you fucking take a screenshot of the logs and then chop of the bit where it tells you it's coming from? Just post the whole log.

**Comment by ChaT0n** [comment]
it was coming from another player, so I only chopped his nick and rid. And I tried with a second player, same result, coming from the player. The player is clean (no mods)

**Comment by CypherMorgan** [comment]
> 

What were you eventually doing while this happened?

**Comment by rr1231234** [comment]
annoying bug, menu constantly notify you when you're in a public session or in a mission that everyone trying to crash you with invalid sector position (player game state node) whatever that is

**Comment by rr1231234** [comment]
annoying bug, menu constantly notify you when you're in a public session or in a mission that everyone trying to crash you with invalid sector position (player game state node) or whatever that is

**Comment by iDominiqe** [comment]
maybe this bug is caused due to the spawn of modified vehicles of other players, tested on the spawn of xml files of cars, a separate topic in the developer's beta branch 😅
https://github.com/YimMenu/YimMenu/pull/1594
![image](https://github.com/YimMenu/YimMenu/assets/115355282/322c0d80-1867-4e4f-9e17-786c5c82580c)

**Comment by Yimura** [comment]
> maybe this bug is caused due to the spawn of modified vehicles of other players, tested on the spawn of xml files of cars, a separate topic in the developer's beta branch sweat_smile #1594 ![image](https://user-images.githubusercontent.com/115355282/251382846-322c0d80-1867-4e4f-9e17-786c5c82580c.png)

Is it though? I don't think @ChaT0n is using the #1594 PR, this is most likely just a false positive that we need to fix.

**Comment by iDominiqe** [comment]
> 

It is possible, but when spawning large objects and for example letting a friend play there, a crash error is triggered, even after deleting objects in the world cleanup. And I also wanted to note that when spawning a lot of objects, players fall to the bottom of the map as if through an abyss, and others crash the game. 😋
But you know better, you have done a great job, for which you are very well done and simply the best!❤️😊

**Comment by ghost** [comment]
In my experience the log spam is mainly from other session hosts only and appears to be false positives. Some of the spam will show up with all other players in the current session, too, such as the ragdoll message if someone strikes you with a car.

**Comment by ChaT0n** [comment]
To enlight some people :
1/ I was he host
2/ No modded vehicle was spawned
3/ The player with whom I tested it, is totally legit ( no modded vehicle spawned or in garage )
4/ No we were the only two in the lobby during the test
5/ Yeah it is a new clean session

**Comment by Yimura** [comment]
Anyways, we'll have to take a look at either disabling this warning or finding out the false positives from the actual crashes.

We can most likely hide this if we're not the host since I seem to remember this only is a concern for the host and not for session participants (someone confirm I'm not delusional).

**Comment by ChaT0n** [comment]
> Anyways, we'll have to take a look at either disabling this warning or finding out the false positives from the actual crashes.
> 
> We can most likely hide this if we're not the host since I seem to remember this only is a concern for the host and not for session participants (someone confirm I'm not delusional).

Yes it happens when I become the host of the session, and it still happening with the latest update ( 11th of july )
But something is off : I emptied the cache and restarted the game and joined another session, and the warning didn't show up

**Comment by Yimura** [comment]
> Yes it happens when I become the host of the session, and it still happening with the latest update ( 11th of july ) But something is off : I emptied the cache and restarted the game and joined another session, and the warning didn't show up

Correct, I was about to remove the notification but @maybegreat48 told me he had a fix for it so I held of with removing it.
Sadly I forgot to modify the commit title and so it still says I removed the notification even though I didn't.

**Comment by rr1231234** [comment]
stupid bug is back in latest build

**Comment by Yimura** [comment]
> stupid bug is back in latest build

It never left, check my previous comment on this issue.

**Comment by scoolharis** [comment]
does the bug been fixed?

**Comment by maybegreat48** [comment]
Cannot reproduce, can you please share your settings file? Are you co-loading YimMenu with something else? I somehow have never seen this bug even once

**Comment by Yimura** [comment]
> Cannot reproduce, can you please share your settings file? Are you co-loading YimMenu with something else? I somehow have never seen this bug even once

I think he was just wondering, this issue wasn't closed with your PR. Let's just close it and see if there's still an issue someone can make a new issue.
