### ISSUE TITLE
[Request]: Teleportation menu

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1623]
### Problem

The teleportation menu is really small when we have to go through a big list. On a 1440 p resolution it is ok, but on a FHD (1920 p) there isn't a lot of space for the list and is inconvenient, we have to scroll a lot
I am still working on the list, will post it soon on UC

NB: same problem with the saved cars list : too small  (width and lenght) when u want to spawn a vehicle u saved (not the personal ones)

### Solution

Maybe putting the menu in another part ?

### Reason

Usage enhancement

### Additional context
![teleport](https://github.com/YimMenu/YimMenu/assets/13076710/18264032-9182-4093-9437-176940b9d280)

**Comment by Tayipc38** [comment]
This could be done with a similar fashion to the handling menu.

**Comment by Tayipc38** [comment]
@ChaT0n Could I maybe borrow your telelocations file? I am working on this issue and then some.
