### ISSUE TITLE
[Request]: Add User-friendly Animations interface

### ISSUE THREAD

**Issue by alyxme** [Yimura/YimMenu#1624]
### Problem

Currently animation plays only once within Debug-Animation tab. That would be great addition to make able to choise how to play animations: with checkbox to loop animation or to play it once if it unchecked. 

### Solution

This request is for small but quite useful feature to add a checkbox that a loop animation selected and Fetched from Debug.

### Reason

Some animations are made to be looped, like dances or idles and playing them once is look so crumplet.

### Additional context

[EDIT](https://github.com/YimMenu/YimMenu/issues/1624#issuecomment-1623872015): request for user-friendly interface for animations but don't remove debug feature yet.
There is an animations LUA (Author: "DEEZY", he rewrite this from FiveM) that uses most useful animations and part of them can play them with props attached to player model bones [Animations2.zip](https://github.com/YimMenu/YimMenu/files/11970128/Animations2.zip). That file may can help to make new feature as code reference in future release of user-friendly interface. 

We must have user-friendly animations to able to: 
Use animations without locking player movement (urgent in certain animations) to animate (upper) body part with able to move freely while animation is playin;
Would be great to use animations with props attached and safely remove them after stoping playin or with special "Deattach" button (make it to choose maybe);
Able to loop animations, stop them or play them once;
Interface of user-friendly may be separated to different categories of animations (maybe droplist or menu select) and they can be like: Idle, Sitting, Romance, Emotes (Paired, Actions, Taunts, Sport, Car, etc), With Props (guitars, guns, everythin else), Animals animations when transformed;
Prop spawn feature above can be a part of code for Prop-spawn-user-friendly-interface that we also in need.

**Comment by Tayipc38** [comment]
The dev feature wasn't meant for regular usage. This request would go paired well with a new feature that actually makes an user friendly animation interface. You can change the request accordingly.

**Comment by alyxme** [comment]
Thank @DayibBaba you did so Great job! I'm very proud of you about how much effort you put into this! That is awesome!
