### ISSUE TITLE
[Bug]: Apparent integer overflow

### ISSUE THREAD

**Issue by 43eayl5** [Yimura/YimMenu#1625]
### Describe the bug

The amount of money a player has seems to overflow and display negative values

### Steps To Reproduce

1. Select a player
2. Click on "Extra Info"

### Expected Behavior

The values should not be negative

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/111658515/4e723bf0-d888-4c9d-9b1a-df04df4cb4b8)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Is this even fixable? Script variables only have 4 bytes to store data, even if we were to cast the value to a uint32_t it would still be limited to 4 billion.

**Comment by xiaoxiao921** [comment]
The value is definitely 64 bit wide, unsure why in that struct it's not the case though
