### ISSUE TITLE
[Bug]: Squad spawner appears as stat editor

### ISSUE THREAD

**Issue by Drsexo** [Yimura/YimMenu#1634]
### Describe the bug

Squad spawner appears as stat editor in the menu

### Steps To Reproduce

World > should see squad spawner

### Expected Behavior

Squad spawner

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/101467921/c8550a37-9701-4dd5-bdbc-9bdc0e9b1102)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by KernelFrog** [comment]
It seems to be wrong in %AppData%\YimMenu\translations\en_US.json
Line 288 has:
`"GUI_TAB_SQUAD_SPAWNER": "Stat Editor",`

Which presumabley should say 'Squad Spawn', or something like that.

**Comment by KernelFrog** [comment]
Have created a pull request to fix this: https://github.com/YimMenu/Translations/pull/48

**Comment by Yimura** [comment]
I've merged the translation fix.
