### ISSUE TITLE
[Bug]: i think i found a crash

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1636]
### Describe the bug

so, idk if i succesfully have found one, so ima need someone to tell me if he crashes, like a dummy as i only have 1 acc, so if anyone wanna help me: iswaxan (on discord)

### Steps To Reproduce

its a special file that spawns a car, and as soon as it spawned, it crashed
might be useful

### Expected Behavior

shouldnt crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
Post the file?

**Comment by TheGreenBandit** [comment]
since its just spawning a car im guessing they just try to spawn a ps5/xbox whatever exclusive car.

**Comment by iswaxan** [comment]
> g a car im guessing they just try to spawn a ps5/xbox whatever exclusive car.

not even, or afaik its not

**Comment by iswaxan** [comment]
@TheGreenBandit , finally, i think it only crashes me, as it is a motorcycle that has been translated from XML to JSON so it might be the cause, but its normally "ghost rider" from a menyoo model

**Comment by iswaxan** [comment]
{
  "Vehicle": {
    "ModelHash": 4135840458,
    "InitialHandle": 724239,
    "VehicleProperties": {
      "Colours": {
        "Primary": 12,
        "Secondary": 12,
        "Pearl": 0,
        "Rim": 27,
        "Mod1_a": 6,
        "Mod1_b": -1,
        "Mod1_c": -1,
        "Mod2_a": 6,
        "Mod2_b": -1,
        "IsPrimaryColourCustom": false,
        "IsSecondaryColourCustom": false,
        "tyreSmoke_R": 255,
        "tyreSmoke_G": 255,
        "tyreSmoke_B": 255,
        "LrInterior": 0,
        "LrDashboard": 0
      },
      "Livery": -1,
      "NumberPlateText": "CAGE",
      "NumberPlateIndex": 5,
      "WheelType": 6,
      "WheelsInvisible": false,
      "WindowTint": 1,
      "BulletProofTyres": true,
      "DirtLevel": 6.44738483,
      "PaintFade": 0.00784313772,
      "RoofState": 0,
      "EngineOn": true,
      "EngineHealth": 1000,
      "LightsOn": true,
      "Neons": {
        "Left": false,
        "Right": false,
        "Front": false,
        "Back": false,
        "R": 255,
        "G": 0,
        "B": 255
      },
      "ModExtras": "",
      "Mods": {
        "_0": "-1,0",
        "_1": "-1,0",
        "_2": "-1,0",
        "_3": "-1,0",
        "_4": "-1,0",
        "_5": "-1,0",
        "_6": "-1,0",
        "_7": "-1,0",
        "_8": "-1,0",
        "_9": "-1,0",
        "_10": "-1,0",
        "_11": "3,0",
        "_12": "2,0",
        "_13": "2,0",
        "_14": "45,0",
        "_15": "-1,0",
        "_16": "4,0",
        "_17": false,
        "_18": true,
        "_19": false,
        "_20": true,
        "_21": false,
        "_22": true,
        "_23": "25,0",
        "_24": "25,0",
        "_25": "-1,0",
        "_26": "-1,0",
        "_27": "-1,0",
        "_28": "-1,0",
        "_29": "-1,0",
        "_30": "-1,0",
        "_31": "-1,0",
        "_32": "-1,0",
        "_33": "-1,0",
        "_34": "-1,0",
        "_35": "-1,0",
        "_36": "-1,0",
        "_37": "-1,0",
        "_38": "-1,0",
        "_39": "-1,0",
        "_40": "-1,0",
        "_41": "-1,0",
        "_42": "-1,0",
        "_43": "-1,0",
        "_44": "-1,0",
        "_45": "-1,0",
        "_46": "-1,0",
        "_47": "-1,0",
        "_48": "-1,0"
      },
      "DoorsOpen": {
        "BackLeftDoor": false,
        "BackRightDoor": false,
        "FrontLeftDoor": true,
        "FrontRightDoor": false,
        "Hood": false,
        "Trunk": false,
        "Trunk2": false
      },
      "DoorsBroken": {
        "BackLeftDoor": false,
        "BackRightDoor": false,
        "FrontLeftDoor": false,
        "FrontRightDoor": false,
        "Hood": false,
        "Trunk": false,
        "Trunk2": false
      },
      "TyresBursted": {
        "FrontLeft": false,
        "FrontRight": false,
        "_2": false,
        "_3": false,
        "BackLeft": false,
        "BackRight": false,
        "_6": false,
        "_7": false,
        "_8": false
      }
    },
    "OpacityLevel": 255,
    "LodDistance": 500,
    "IsVisible": true,
    "IsOnFire": false,
    "IsInvincible": true,
    "IsBulletProof": true,
    "IsExplosionProof": true,
    "IsFireProof": false,
    "IsMeleeProof": true,
    "IsOnlyDamagedByPlayer": false,
    "SpoonerAttachments": {
      "Attachment": [
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 513807,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.47034,
            "Y": -1700.66504,
            "Z": 3.62097478,
            "Pitch": -66.8104935,
            "Roll": 63.0362015,
            "Yaw": 74.5379562
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 0,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": 89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 493829,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.51965,
            "Y": -1700.65137,
            "Z": 3.50147772,
            "Pitch": -8.95488358,
            "Roll": 79.5864868,
            "Yaw": 97.9614944
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 0,
            "Y": 0.12999998,
            "Z": 0,
            "Pitch": 59.9999924,
            "Roll": 89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 176398,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.43127,
            "Y": -1700.70361,
            "Z": 3.69834709,
            "Pitch": -66.8104858,
            "Roll": -116.963745,
            "Yaw": 74.5379715
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": -0.0299999993,
            "Y": -0.0899999887,
            "Z": 0,
            "Pitch": 0.0000133514404,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 73744,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.47192,
            "Y": -1700.6554,
            "Z": 3.6227603,
            "Pitch": -66.8104858,
            "Roll": -116.963776,
            "Yaw": 74.5379562
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 0.00999999978,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": -90,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 308230,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.57434,
            "Y": -1700.68799,
            "Z": 3.65038919,
            "Pitch": -66.8104935,
            "Roll": -116.96376,
            "Yaw": 74.5379562
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 1.49011612e-8,
            "Y": 0.00999999978,
            "Z": 0.109999985,
            "Pitch": 0,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 769550,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.37024,
            "Y": -1700.64099,
            "Z": 3.58236837,
            "Pitch": -66.8104935,
            "Roll": -116.96376,
            "Yaw": 74.5379562
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 0,
            "Y": 0,
            "Z": -0.109999985,
            "Pitch": 0,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 764431,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.08398,
            "Y": -1700.94788,
            "Z": 3.66440678,
            "Pitch": 77.3431931,
            "Roll": -144.574722,
            "Yaw": 153.506409
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": 0,
            "Z": 0.129999965,
            "Pitch": 29.9999962,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 684046,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.27625,
            "Y": -1700.95398,
            "Z": 3.52092505,
            "Pitch": 31.9970703,
            "Roll": -102.153557,
            "Yaw": 106.110153
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": 0,
            "Z": -0.109999985,
            "Pitch": -19.9999962,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 385542,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.23987,
            "Y": -1700.9729,
            "Z": 3.65702057,
            "Pitch": 65.2966614,
            "Roll": 115.291855,
            "Yaw": -103.632813
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": 0.0899999887,
            "Z": 0,
            "Pitch": 59.9999962,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 364815,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.13062,
            "Y": -1700.927,
            "Z": 3.50853968,
            "Pitch": 51.3961105,
            "Roll": 73.3714828,
            "Yaw": 112.737274
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": -0.0999999866,
            "Z": 0,
            "Pitch": 0,
            "Roll": 89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 321807,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.18811,
            "Y": -1700.95117,
            "Z": 3.58668756,
            "Pitch": 51.3961105,
            "Roll": -106.628479,
            "Yaw": 112.737274
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": -89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 540021153,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Fire Candle",
          "InitialHandle": 147983,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": false,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.18811,
            "Y": -1700.95117,
            "Z": 3.58668756,
            "Pitch": 51.3961105,
            "Roll": 73.3714828,
            "Yaw": 112.737274
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": 89.9999924,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 3008238621,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Wheel Hub",
          "InitialHandle": 607757,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.19958,
            "Y": -1700.8833,
            "Z": 3.59918594,
            "Pitch": -10.2851677,
            "Roll": -52.5835762,
            "Yaw": -170.399933
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 20,
            "X": 0.0699999928,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 89.9999924
          }
        },
        {
          "ModelHash": 3008238621,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Wheel Hub",
          "InitialHandle": 622095,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.48352,
            "Y": -1700.5874,
            "Z": 3.63525867,
            "Pitch": -10.2851925,
            "Roll": 69.1023483,
            "Yaw": -170.399933
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": 0.0799999908,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 89.9999924
          }
        },
        {
          "ModelHash": 3008238621,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Wheel Hub",
          "InitialHandle": 325647,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.45227,
            "Y": -1700.77173,
            "Z": 3.60133457,
            "Pitch": -10.2851925,
            "Roll": 69.1023483,
            "Yaw": -170.399933
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 8,
            "X": -0.109999985,
            "Y": 0,
            "Z": 0,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 89.9999924
          }
        },
        {
          "ModelHash": 1462895032,
          "Type": 1,
          "Dynamic": true,
          "HashName": "~italic~GhostRider~s~ Fire Cat",
          "InitialHandle": 517135,
          "PedProperties": {
            "IsStill": true,
            "HasShortHeight": true,
            "CurrentWeapon": 3799318422,
            "PedProps": {
              "_0": "-1,-1",
              "_1": "-1,-1",
              "_2": "-1,-1",
              "_3": "-1,-1",
              "_4": "-1,-1",
              "_5": "-1,-1",
              "_6": "-1,-1",
              "_7": "-1,-1",
              "_8": "-1,-1",
              "_9": "-1,-1"
            },
            "PedComps": {
              "_0": "0,2",
              "_1": "0,0",
              "_2": "0,0",
              "_3": "0,0",
              "_4": "0,0",
              "_5": "0,0",
              "_6": "0,0",
              "_7": "0,0",
              "_8": "0,0",
              "_9": "0,0",
              "_10": "0,0",
              "_11": "0,0"
            },
            "RelationshipGroupAltered": false,
            "RelationshipGroup": 4208871491,
            "ScenarioActive": false,
            "AnimActive": false
          },
          "OpacityLevel": 0,
          "LodDistance": 16960,
          "IsVisible": false,
          "Health": 0,
          "IsOnFire": true,
          "IsInvincible": false,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": false,
          "IsFireProof": false,
          "IsMeleeProof": false,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1143.45532,
            "Y": -1700.77795,
            "Z": 3.78497434,
            "Pitch": 0.10552872,
            "Roll": -10.2851915,
            "Yaw": 99.6192093
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": 0,
            "X": -0.0799999759,
            "Y": -0.759999573,
            "Z": 0.0499999821,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 1462895032,
          "Type": 1,
          "Dynamic": true,
          "HashName": "~italic~GhostRider~s~ Fire Cat",
          "InitialHandle": 441615,
          "PedProperties": {
            "IsStill": true,
            "HasShortHeight": true,
            "CurrentWeapon": 3799318422,
            "PedProps": {
              "_0": "-1,-1",
              "_1": "-1,-1",
              "_2": "-1,-1",
              "_3": "-1,-1",
              "_4": "-1,-1",
              "_5": "-1,-1",
              "_6": "-1,-1",
              "_7": "-1,-1",
              "_8": "-1,-1",
              "_9": "-1,-1"
            },
            "PedComps": {
              "_0": "0,2",
              "_1": "0,0",
              "_2": "0,0",
              "_3": "0,0",
              "_4": "0,0",
              "_5": "0,0",
              "_6": "0,0",
              "_7": "0,0",
              "_8": "0,0",
              "_9": "0,0",
              "_10": "0,0",
              "_11": "0,0"
            },
            "RelationshipGroupAltered": false,
            "RelationshipGroup": 4208871491,
            "ScenarioActive": false,
            "AnimActive": false
          },
          "OpacityLevel": 0,
          "LodDistance": 16960,
          "IsVisible": false,
          "Health": 0,
          "IsOnFire": true,
          "IsInvincible": false,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": false,
          "IsFireProof": false,
          "IsMeleeProof": false,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.04761,
            "Y": -1701.01892,
            "Z": 3.74245334,
            "Pitch": 0.0412651226,
            "Roll": -10.2851763,
            "Yaw": 99.6075439
          },
          "Attachment": {
            "AttachedTo": 724239,
            "BoneIndex": -1,
            "X": -0.0599999949,
            "Y": 0.849999487,
            "Z": 0,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 0
          }
        },
        {
          "ModelHash": 3008238621,
          "Type": 3,
          "Dynamic": false,
          "HashName": "~italic~GhostRider~s~ Wheel Hub",
          "InitialHandle": 604687,
          "OpacityLevel": 255,
          "LodDistance": 16960,
          "IsVisible": true,
          "Health": 1000,
          "IsOnFire": false,
          "IsInvincible": true,
          "IsBulletProof": false,
          "IsCollisionProof": true,
          "IsExplosionProof": true,
          "IsFireProof": false,
          "IsMeleeProof": true,
          "IsOnlyDamagedByPlayer": false,
          "PositionRotation": {
            "X": -1145.17493,
            "Y": -1701.02881,
            "Z": 3.57240391,
            "Pitch": 10.2851496,
            "Roll": 52.5835762,
            "Yaw": 9.60004616
          },
          "Attachment": {
            "AttachedTo": 607757,
            "BoneIndex": 0,
            "X": 1.49011612e-8,
            "Y": 0.149999976,
            "Z": 0,
            "Pitch": 0,
            "Roll": 0,
            "Yaw": 179.999985
          }
        }
      ]
    }
  }
}






@gir489returns

**Comment by iswaxan** [comment]
> Post the file?

cant post .json on comments, neither paste them

**Comment by TheGreenBandit** [comment]
so screenshot file contents. because the most likely thing is it has been translated wrong. wait until xml support

**Comment by xiaoxiao921** [comment]
You can post the json file, just rename the .json extension to .txt

**Comment by iswaxan** [comment]
> You can post the json file, just rename the .json extension to .txt

yup lemme do it rq

here:
[e.txt](https://github.com/YimMenu/YimMenu/files/11986968/e.txt)
@gir489returns 
@xiaoxiao921

**Comment by Yimura** [comment]
The JSON in question isn't using the YimMenu syntax, however the menu shouldn't crash if the JSON being loaded isn't valid.

**Comment by Yimura** [comment]
The persist vehicle service crashes on this line trying to access the vehicle JSON object it just loaded in:
https://github.com/YimMenu/YimMenu/blob/96493b5a22d9f57c884274797dcb2e23d338851c/src/services/vehicle/persist_car_service.cpp#L169-L171

Solving this would require us to swap to a C++ object and serialize it as that the moment the JSON is loaded in, this will allow us to catch it as early as possible in the code flow.

**Comment by xiaoxiao921** [comment]
This was fixed at some point, not sure when exactly

**Comment by Yimura** [comment]
Closing as this issue should've been resolved.
