### ISSUE TITLE
[Request]: infinite vehicle rockets

### ISSUE THREAD

**Issue by meowmeowmoew3** [Yimura/YimMenu#1637]
### Solution

as the tittle suggests,would be cool to have an infinite rocket/barrage option on the menu

### Reason

because im tired of missing my mk1 shots

**Comment by gir489returns** [comment]
If it's a vehicle weapon, meaning you select it like you would a drive-by weapon, Always Refill Ammo should do this already. If not, let me know which vehicle has this feature so I can test it.

**Comment by meowmeowmoew3** [comment]
> If it's a vehicle weapon, meaning you select it like you would a drive-by weapon, Always Refill Ammo should do this already. If not, let me know which vehicle has this feature so I can test it.

Nope it doesn't refill the rockets, tested on an oppressor mk 1

**Comment by gir489returns** [comment]
I just tested it and yes, I confirmed this behavior. However, it seems someone already has tried to dip their hands in the pot and fix this, but they didn't do it properly. PR #1060 has been pending the author change to class-based vehicle ammo for almost 4 months now, and if he hasn't done it by now, I doubt he's going to do it.

**Comment by meowmeowmoew3** [comment]
> I just tested it and yes, I confirmed this behavior. However, it seems someone already has tried to dip their hands in the pot and fix this, but they didn't do it properly. PR #1060 has been pending the author change to class-based vehicle ammo for almost 4 months now, and if he hasn't done it by now, I doubt he's going to do it. 

Dang so no hope of it ever making it?

**Comment by lonelybud** [comment]
have the same problem -

- Scenario 1: spawned new vehicle oppressor mk2 (maxed). can fire more than 20 missiles
- Scenario 2: spawned personal vehicle oppressor mk2 . can fire only 20 missiles
- Scenario 3: spawned personal vehicle oppressor mk2 + check `weapons > Always Full Ammo`. Still it can fire only 20 missiles.


If one want to spawn personal vehicle with infinite ammo then spawn personal vehicle as clone as follow -

![image](https://github.com/YimMenu/YimMenu/assets/139460769/9a88b5b4-338a-407d-a180-1f463be3641d)

**Comment by spinoza-spinoza** [comment]
if you want max rocket or  bomb   use new  vehicle spwpaned max   
it work with b11 strikere more then 50 bomb   and mk1 mk2    infinite  rocket

**Comment by ghost** [comment]
There is a native goes by SET_VEHICLE_WEAPON_RESTRICTED_AMMO that can set your vehicle missiles or ammo.

**The script goes like this:**

VEHICLE.SET_VEHICLE_WEAPON_RESTRICTED_AMMO(vehicle, weaponIndex, capacity) **-- For oppressor mk2 missiles the index is 2 and for capacity -1 means infinite. This does not work for bombs and countermeasures.**

**Here is the link:** https://natives.gta.menu/natives/0x44CD1F493DB2A0A6

**For bombs we use the native called SET_VEHICLE_BOMB_AMMO:**

VEHICLE.SET_VEHICLE_BOMB_AMMO(vehicle, bombCount) **-- I have never tried this but I think it might work.**

**Here is the link:** https://natives.gta.menu/natives/0xF4B2ED59DEB5D774
