### ISSUE TITLE
[Bug]: mod menu only launch when injecting but not when loading until loaded officially

### ISSUE THREAD

**Issue by HyperSkys** [Yimura/YimMenu#1639]
### Describe the bug

when i inject it work but not when i inject until loading until difficulty make it officially not working until you fix the issue

### Steps To Reproduce

1. open
2. play
3. injection but not patched
4. not inject!!!!

### Expected Behavior

for me to be able to play gta and hack people

### Screenshots and/or Logs

![download (13)](https://github.com/YimMenu/YimMenu/assets/66301237/b64770db-9ef6-47d7-aa85-360b2c142a70)

### Store

Steam

### Additional context

please fix immediatlly now thanks

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Sorry could you explain in more detail what the issue is? I don't understand what you're trying to say.

**Comment by HyperSkys** [comment]
> Sorry could you explain in more detail what the issue is? I don't understand what you're trying to say.

it not inject without the injectable host withoyt launch but when launch not load menu when loading rockstar 😭😭😭

**Comment by 3DSBricker** [comment]
Do you mean it doesn't inject without the injector (which makes sense), and afterwards when using the injector, nothing happens? So basically it says it's injected but you can't open it?

**Comment by HyperSkys** [comment]
> Do you mean it doesn't inject without the injector (which makes sense), and afterwards when using the injector, nothing happens? So basically it says it's injected but you can't open it? 

no no you don't get it the injecting process is the injector but the game isn't processing until the injector send the mod menu to the launcher until online alley way god mode activating not work until injector not until online done

**Comment by maybegreat48** [comment]
So you're saying that you can inject the menu in online but can't when the game is loading?

**Comment by HyperSkys** [comment]
> So you're saying that you can inject the menu in online but can't when the game is loading?

no no no i can't load until injected when GTA crashed but not

**Comment by gir489returns** [comment]
Dude, I have no idea what you're trying to say. You're basically saying nothing.

**Comment by HyperSkys** [comment]
> Dude, I have no idea what you're trying to say. You're basically saying nothing.

DIDE KM LITERAALY TELLING U SHAT I SAUS U JUDY DONT GET IT BECAUSE UR NOT SMART DNOUGJ TO UNDERSTAND IM YRUING TO SU YOU NEDC TI BR A REAL EEVDLOPSR TO TELL ME AND FIX IT WRONG

**Comment by gir489returns** [comment]
> DIDE KM LITERAALY TELLING U SHAT I SAUS U JUDY DONT GET IT BECAUSE UR NOT SMART DNOUGJ TO UNDERSTAND IM YRUING TO SU YOU NEDC TI BR A REAL EEVDLOPSR TO TELL ME AND FIX IT WRONG

Cope seethe and dilate.

**Comment by tupoy-ya** [comment]
> > Dude, I have no idea what you're trying to say. You're basically saying nothing.
> 
> DIDE KM LITERAALY TELLING U SHAT I SAUS U JUDY DONT GET IT BECAUSE UR NOT SMART DNOUGJ TO UNDERSTAND IM YRUING TO SU YOU NEDC TI BR A REAL EEVDLOPSR TO TELL ME AND FIX IT WRONG

Why are you say we fix it wrong when you can fix correct wrong?

**Comment by gir489returns** [comment]
> Why are you say we fix it wrong when you can fix correct wrong?

Yeah why don't you use your 5 years of Java experience and fix it, bro?

**Comment by HyperSkys** [comment]
> > Why are you say we fix it wrong when you can fix correct wrong?
> 
> 
> 
> Yeah why don't you use your 5 years of Java experience and fix it, bro?

If you had the intellectual properties of a reasonable human you would understand this project is made using the C++ language, must I mention it is possible to make a GTA mod menu in Java it wouldn't be very smart to do that!

**Comment by TheGreenBandit** [comment]
@HyperSkys it isn't possible have the menu fully loaded before the game is fully loaded. Just load it when you're in story mode.

**Comment by maybegreat48** [comment]
> > > Why are you say we fix it wrong when you can fix correct wrong?
> > 
> > 
> > Yeah why don't you use your 5 years of Java experience and fix it, bro?
> 
> If you had the intellectual properties of a reasonable human you would understand this project is made using the C++ language, must I mention it is possible to make a GTA mod menu in Java it wouldn't be very smart to do that!

Can you please rewrite your bug report using understandable English just like you did with this comment? We would appreciate a screen recording if you can't

**Comment by Yimura** [comment]
I'm unable to comprehend how someone with 5y of Java experience is so incapable of making a well structured English sentence. Like I want to help but nothing you say is clear to me on what you're talking to me about.

Or perhaps write it in your native language if that's easier because at this rate that'll be easier than having to decipher what you wrote.

**Comment by HyperSkys** [comment]
> I'm unable to comprehend how someone with 5y of Java experience is so incapable of making a well structured English sentence. Like I want to help but nothing you say is clear to me on what you're talking to me about.
> 
> 
> 
> Or perhaps write it in your native language if that's easier because at this rate that'll be easier than having to decipher what you wrote. 

Se tivese a última vista previa, entón non podería acceder ao menú de modificación en Windows 11, erro de lectura/escritura da memoria.

**Comment by maybegreat48** [comment]
> > I'm unable to comprehend how someone with 5y of Java experience is so incapable of making a well structured English sentence. Like I want to help but nothing you say is clear to me on what you're talking to me about.
> > Or perhaps write it in your native language if that's easier because at this rate that'll be easier than having to decipher what you wrote.
> 
> Se tivese a última vista previa, entón non podería acceder ao menú de modificación en Windows 11, erro de lectura/escritura da memoria.

Screenshots?

**Comment by gir489returns** [comment]
This dude is just fucking trolling and wasting your time, I suggest you close this ticket before you waste anymore of it.

**Comment by KernelFrog** [comment]
> Cope seethe and dilate.

Was that really necessary?

**Comment by xiaoxiao921** [comment]
I mean a troll message answering to another troll message is fine, no?

**Comment by KernelFrog** [comment]
> I mean a troll message answering to another troll message is fine, no?

Yes, but don't feed the trolls.
