### ISSUE TITLE
Receiving Script Event Crashing Client

### ISSUE THREAD

**Issue by gnchjnhkkhjk** [Yimura/YimMenu#164]
**Describe the bug**
Receiving unblocked script events that would normally not do so may crash your client. For example, I believe receiving the kick to singleplayer and a couple other kick script events that I know of will simply crash the YimMenu users client instead of just kicking them as normal.

**To Reproduce**
1. Receive an unblocked script event such as the kick to singleplayer (998716537) event. 
2. Your game should crash.

**Expected behavior**
Not crash the client but instead for example be kicked (if the received event is a kick)

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Yimura** [comment]
Interesting find, will definitely take a look at it!

**Comment by Yimura** [comment]
Can confirm this occurs, not sure what's causing it.

**Comment by Yimura** [comment]
Seems to have been resolved by https://github.com/Yimura/YimMenu/commit/524a961e435618652c3594e6a819f1dd5d405467
