### ISSUE TITLE
[Bug]: Game crashes while updating cache

### ISSUE THREAD

**Issue by Trapped-Bear** [Yimura/YimMenu#1640]
### Describe the bug

The DLL built from the latest version of the source code will cause the game to crash when updating the cache after injection

### Steps To Reproduce

1.Open game
2.Injection menu
3.Click to update cache

### Expected Behavior

Updating the cache should not cause the game to crash

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/11980424/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
Think I know the issue, which injector do you use?

**Comment by Trapped-Bear** [comment]
> 以为我知道问题，您使用哪种喷油器？

I injected it using Xenos

**Comment by xiaoxiao921** [comment]
Can you try this YimMenu.dll ? 

https://github.com/YimMenu/YimMenu/pull/1641#issuecomment-1625396806

**Comment by Trapped-Bear** [comment]
> Can you try this YimMenu.dll ?
> 
> [#1641 (comment)](https://github.com/YimMenu/YimMenu/pull/1641#issuecomment-1625396806)

Still the same, causing the game to crash

**Comment by Trapped-Bear** [comment]
> Can you try this YimMenu.dll ?
> 
> [#1641 (comment)](https://github.com/YimMenu/YimMenu/pull/1641#issuecomment-1625396806)

 This bug appeared after the release of #1635

**Comment by xiaoxiao921** [comment]
I know that it appeared after #1635 

can you give new cout.log file?

**Comment by Trapped-Bear** [comment]
> 我知道它出现在#1635之后
> 
> 你能给新的cout.log文件吗？
[cout.log](https://github.com/YimMenu/YimMenu/files/11982675/cout.log)

**Comment by alyxme** [comment]
Same as TS [latest](https://github.com/YimMenu/YimMenu/commit/5ffe6c7d3b295ee88af87cc3fd4746064abf6a79) release insist to update cache that can't cancel and after fully loaded online updating cache by pressing the Button cause crash. Injector is "Sta nd Laun chpad"

**Comment by Tayipc38** [comment]
> Same as TS [latest](https://github.com/YimMenu/YimMenu/commit/5ffe6c7d3b295ee88af87cc3fd4746064abf6a79) release insist to update cache that can't cancel and after fully loaded online updating cache by pressing the Button cause crash. Injector is "Stand Launchpad" 1.8.10.

Stop using stand trash. Do yourself a favor.

**Comment by xiaoxiao921** [comment]
> > Same as TS [latest](https://github.com/YimMenu/YimMenu/commit/5ffe6c7d3b295ee88af87cc3fd4746064abf6a79) release insist to update cache that can't cancel and after fully loaded online updating cache by pressing the Button cause crash. Injector is "Stand Launchpad" 1.8.10.
> 
> Stop using stand trash. Do yourself a favor.

The issue is not the injector, it's just that we incorrectly use the std filesystem classes and abuse string() which can throw, and apparently u8string() can too, i'm still trying to fix a correct solution to all this

**Comment by Tayipc38** [comment]
> > > Same as TS [latest](https://github.com/YimMenu/YimMenu/commit/5ffe6c7d3b295ee88af87cc3fd4746064abf6a79) release insist to update cache that can't cancel and after fully loaded online updating cache by pressing the Button cause crash. Injector is "Stand Launchpad" 1.8.10.
> > 
> > 
> > Stop using stand trash. Do yourself a favor.
> 
> The issue is not the injector, it's just that we incorrectly use the std filesystem classes and abuse string() which can throw, and apparently u8string() can too, i'm still trying to fix a correct solution to all this

I realize that this issue might not be originating from the usage of that injector, but my advise was a more general one.

**Comment by alyxme** [comment]
> > Same as TS [latest](https://github.com/YimMenu/YimMenu/commit/5ffe6c7d3b295ee88af87cc3fd4746064abf6a79) release insist to update cache that can't cancel and after fully loaded online updating cache by pressing the Button cause crash. Injector is "Stand Launchpad" 1.8.10.
> 
> Stop using stand trash. Do yourself a favor.

my apologise for answer not related to the issue but as you mention what you recommend to use to inject? (for general purpose) I will look into your recommendation! Also Im not using Stand itself cos I dont like it at all but as an injector the Launcher is working good and even make injected dlls spoofed. 
To make this answer not so useles to the issue: my cout.log didn't writen after the crash by cache update.

**Comment by gir489returns** [comment]
@Trapped-Bear can you give me the exact path of your GTA V installation directory, and the directory of where you are injecting YimMenu.dll from? I am setting up a Chinese Windows 10 install to test this issue so we can try and reproduce your issue, as both @xiaoxiao921 and I cannot reproduce the issue anymore after #1641.

**Comment by Trapped-Bear** [comment]
The&nbsp;installation&nbsp;directory&nbsp;of&nbsp;GTA&nbsp;V&nbsp;is&nbsp;F:\SteamLibrary\steamapps\common\Grand&nbsp;Theft&nbsp;Auto&nbsp;V\
Dll&nbsp;path&nbsp;is&nbsp;C:\Users\admin\source\repos\YimMenu\out\build\x64-Release\


---Original---
From: ***@***.***&gt;
Date: Sat, Jul 8, 2023 01:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YimMenu/YimMenu] [Bug]: Game crashes while updating cache (Issue#1640)




 
@Trapped-Bear can you give me the exact path of your GTA V installation directory, and the directory of where you are injecting YimMenu.dll from? I am setting up a Chinese Windows 10 install to test this issue so we can try and reproduce your issue, as both @xiaoxiao921 and I cannot reproduce the issue anymore after #1641.
 
&mdash;

**Comment by gir489returns** [comment]
>The&nbsp;installation&nbsp;directory&nbsp;of&nbsp;GTA&nbsp;V&nbsp;is&nbsp;F:\SteamLibrary\steamapps\common\Grand&nbsp;Theft&nbsp;Auto&nbsp;V\ Dll&nbsp;path&nbsp;is&nbsp;C:\Users\admin\source\repos\YimMenu\out\build\x64-Release

Are you using a translator? Why are the paths in English?

**Comment by xiaoxiao921** [comment]
I think these paths are the same as us, regardless of the windows locale

**Comment by xiaoxiao921** [comment]
@Trapped-Bear Can you please try the .dll from this zip? https://github.com/YimMenu/YimMenu/suites/14143420868/artifacts/792159899

**Comment by alyxme** [comment]
Not fixed for me. Not with devs dll above nor with clean build from Master neither.
![cacheupd-error](https://github.com/YimMenu/YimMenu/assets/62597693/a77e3247-f2e4-4a70-85d6-161cfe082bfe)
Tried to inject immidietly, wait for SP, or MP. Tried to delete Cache folder from YimMenu from AppData/Roaming before updating: only 2 files generated gta_pointer and sc_pointer. Tried to delete YimMenu folder completely to clean all settings. it is not work at all. (Epic) [cout.log](https://github.com/YimMenu/YimMenu/files/11990304/cout.log)

**Comment by xiaoxiao921** [comment]
Can you try the DLL I linked here https://github.com/YimMenu/YimMenu/issues/1640#issuecomment-1626030446 and give the log file

**Comment by alyxme** [comment]
Already try exactly that dear! But it just wont work!

**Comment by xiaoxiao921** [comment]
> Already try exactly that dear! But it just want work!

What about this one https://nightly.link/YimMenu/YimMenu/actions/artifacts/792913619.zip

**Comment by D-Borkan** [comment]
> 

i think this bug appear in some user
for me not , but some friends have encountered this problem

**Comment by D-Borkan** [comment]
> Not fixed for me. Not with devs dll above nor with clean build from Master neither. ![cacheupd-error](https://user-images.githubusercontent.com/62597693/251962843-a77e3247-f2e4-4a70-85d6-161cfe082bfe.jpg) Tried to inject immidietly, wait for SP, or MP. Tried to delete Cache folder from YimMenu from AppData/Roaming before updating: only 2 files generated gta_pointer and sc_pointer. Tried to delete YimMenu folder completely to clean all settings. it is not work at all. (Epic) [cout.log](https://github.com/YimMenu/YimMenu/files/11990304/cout.log)

i think this bug appear in some user
for me not , but some friends have encountered this problem

and it began to appear after this fix : https://github.com/YimMenu/YimMenu/commit/c121e72eb678412ad26440ebdb78cb29f67ea69c

**Comment by D-Borkan** [comment]
> 

and it began to appear after this fix : https://github.com/YimMenu/YimMenu/pull/1635[)](https://github.com/YimMenu/YimMenu/commit/c121e72eb678412ad26440ebdb78cb29f67ea69c)

**Comment by D-Borkan** [comment]
> > Not fixed for me. Not with devs dll above nor with clean build from Master neither. ![cacheupd-error](https://user-images.githubusercontent.com/62597693/251962843-a77e3247-f2e4-4a70-85d6-161cfe082bfe.jpg) Tried to inject immidietly, wait for SP, or MP. Tried to delete Cache folder from YimMenu from AppData/Roaming before updating: only 2 files generated gta_pointer and sc_pointer. Tried to delete YimMenu folder completely to clean all settings. it is not work at all. (Epic) [cout.log](https://github.com/YimMenu/YimMenu/files/11990304/cout.log)
> 
> i think this bug appear in some user for me not , but some friends have encountered this problem

and it began to appear after this fix : https://github.com/YimMenu/YimMenu/issues/1640#issuecomment-1627386739

**Comment by alyxme** [comment]
> > Already try exactly that dear! But it just want work!
> 
> What about this one https://nightly.link/YimMenu/YimMenu/actions/artifacts/792913619.zip

[cout.log](https://github.com/YimMenu/YimMenu/files/11991077/cout.log)

still nope

**Comment by tupoy-ya** [comment]
Also got crashed when building the cache.
In my case it was caused by me having old `update*.rpf` files in the game folder.

After trying it again with old rpfs removed i crashed when trying to load `RESIDENT_custom.rpf` which i forgot even existed.
Then i found out that i had background scripts downloaded to my GTA5 folder as well.

Then when i removed all of this it started working.

**Comment by D-Borkan** [comment]
> Also got crashed when building the cache. In my case it was caused by me having old `update*.rpf` files in the game folder.
> 
> After trying it again with old rpfs removed i crashed when trying to load `RESIDENT_custom.rpf` which i forgot even existed. Then i found out that i had background scripts downloaded to my GTA5 folder as well.
> 
> Then when i removed all of this it started working.

the game crash while update cache is fix with this : https://github.com/YimMenu/YimMenu/commit/f10c698396b154a166920b5138b48d019c56dcd2

but the error like this : https://github.com/YimMenu/YimMenu/issues/1640#issuecomment-1626927960
It started appearing for some users

**Comment by alyxme** [comment]
Need a way to bypass Update files that cause crashes without removing em.

**Comment by alyxme** [comment]
That [build](https://github.com/YimMenu/YimMenu/pull/1651#issuecomment-1627541782) is helps to fix the issue. Succefuly updated the cache without crash. I tried alot of things to fix (check file installation of the game, disk RW permission, different folders, etc). After rebuilding the cache with build above, Master build loaded succefuly without any insisting to rebuild that again. Also previously I mentioned about the way to bypass "updated" files but later I think that was so stupid but for now that has fixes the problem. Thanks to @xiaoxiao921 hero!
