### ISSUE TITLE
[Bug]: Update cache on init does not work.

### ISSUE THREAD

**Issue by tupoy-ya** [Yimura/YimMenu#1653]
### Describe the bug

If you use the "Update Cache On Init" option in main menu the cache will never generate.

### Steps To Reproduce

1. Inject YimMenu on main menu.
2. Press Update Cache On Init
3. Wait for single player to be loaded...
4. The Game Cache window remains on the screen and no cache is generated.

### Expected Behavior

Generate cache.

### Store

Steam

### Additional context

Is it even useful anymore since we mount the rpfs manually now?

Is it supposed to be available in the main menu?
The window code says it should be available at `eGameState::Respawn`.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TalesOrigin** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/96468292/c4a8db0f-221e-47e1-923e-f0cbdb7161d5)
error and game crash

**Comment by TalesOrigin** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/11995307/cout.log)
log

**Comment by Yimura** [comment]
Yeah we can probably remove the "Update cache on init" button.

**Comment by bmarcelov** [comment]
yeah same here, with rockstar game launcher ERR_GEN_INVALID error, game freezy and close

**Comment by xiaoxiao921** [comment]
> yeah same here, with rockstar game launcher ERR_GEN_INVALID error, game freezy and close

log file?

**Comment by bmarcelov** [comment]
> 

[07-08-2023-14-11-09_cout.log](https://github.com/YimMenu/YimMenu/files/11996992/07-08-2023-14-11-09_cout.log)

**Comment by bmarcelov** [comment]
[_cout.log](https://github.com/YimMenu/YimMenu/files/11997023/_cout.log)

**Comment by xiaoxiao921** [comment]
> [_cout.log](https://github.com/YimMenu/YimMenu/files/11997023/_cout.log)

You don't have the latest version of the menu.

**Comment by xiaoxiao921** [comment]
Fixed by #1663
