### ISSUE TITLE
[Bug]: Xml vehicles "Reload" not removing the deleted files

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#1655]
### Describe the bug

I can put xml vehicles in the folder and press "Reload" and it shows the new xml files just fine but when I delete some and press reload, they remain there. Despite the files being deleted, I am still able to spawn it.

### Steps To Reproduce

Put xml vehicle in the "%APPDATA%\YimMenu\xml_vehicles" folder and press "Reload" in the Spawn Vehicle->Xml submenu; delete the xml file and press "Reload" again.

### Expected Behavior

Xml files should not appear when they have been deleted from the folder.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Oh this is a simple one to fix, just clear the list before loading the new ones.
