### ISSUE TITLE
[Bug]: Any vehicle is vulnerable in its ability to withstand more missiles.

### ISSUE THREAD

**Issue by CHADREX** [Yimura/YimMenu#1660]
### Describe the bug

When launched, any vehicle (avenger, champion, toreador etc.) is vulnerable to 1 missile with the ability to withstand more missiles.

_Maybe I enabled something unnecessary, but I did a settings reset and still keep getting this bug._

### Steps To Reproduce

A sticky bomb on yourself, like an avenger...

### Expected Behavior

At least the vehicle must survive several times

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Duplicate of #1192
