### ISSUE TITLE
[Request]: improve lua

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1662]
### Problem

I would like to improve the scripts a little. for example, I would like to use a squad spawner using lua and give it arguments like player id, vehicle name, quantity, etc. The same goes for the ped spawner.

### Solution

Add appropriate commands for lua

### Reason

I understand that it may be difficult to implement, but maybe someone wants to do it

**Comment by gir489returns** [comment]
I agree, some of the issues I have seen trying to write Lua scripts are as follows:

1. Globals/Locals do not behave the same way they do in YimMenu's CPP files. There is no way to hyperextend the global by increments of repeated calls on itself, the get_int and other getters require a static full-sized offset, but that isn't how GTA's script files behave. There should be function called at that behaves the same way script_global/script_local does.
2. ImGui:Combo is not implemented.
3. execute_as_script is not implemented.
4. When a Lua script fails, it just spits out an EXCEPTION_ACCESS_VIOLATION with a script stack that contains lua_execute which is not helpful to the user at all. It should instead spit out the line number and Lua-based exception that occured.

**Comment by Yimura** [comment]
Issue is quite abstract and open to different interpretations, we're continuously working on exposing internal functionality to Lua scripts.
