### ISSUE TITLE
[Bug]: I keep falling through the map

### ISSUE THREAD

**Issue by Vroemvroem2000** [Yimura/YimMenu#1673]
### Describe the bug

After i used No Collision once. Now it does not turn on and now i fall through the map at random.

### Steps To Reproduce

No idea

### Expected Behavior

I thought i would just turn off

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by alyxme** [comment]
Check for Self and Vehicle tabs Collision checkbox are disabled both

**Comment by Yimura** [comment]
No respons from author, can't reproduce either.
