### ISSUE TITLE
[Bug]: out of bounds train track index crash spam

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1674]
### Describe the bug

whenever you get close to a player you get out of bounds train track index crash spammed in your logs.
i was having fun and then i got spammed this thing even though the player's were doing nothing.

### Steps To Reproduce

1. Get Close to a Player 
2. Watch The Spam

### Expected Behavior

to not make it spam? or detect if the player is actually crashing you

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/12004393/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by alyxme** [comment]
Happen to me several times even at the "clouds" with notices from different users.

**Comment by binded-zz** [comment]
just found this as well last night..
when you guys crash is it just to desktop or is it a full system hard crash 
just wondering as i was hard crashing and its been since the last big update like 2 weeks ago.
i wasnt even getting the notices i was just crashing 
that was with and with out a menu crashing :(

**Comment by rrAsus** [comment]
> just found this as well last night.. when you guys crash is it just to desktop or is it a full system hard crash just wondering as i was hard crashing and its been since the last big update like 2 weeks ago. i wasnt even getting the notices i was just crashing that was with and with out a menu crashing :(

when it show's me the prompt about the crash? no i don't get any crashes to desktop nor bluescreens

**Comment by Yimura** [comment]
We've disabled the detection message for now, the protection is still in YimMenu.

There appear to be no downsides to keeping the protection.
