### ISSUE TITLE
[Request]: Improve modder detection reaction

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1676]
### Problem

You recently added player detections such as desync protection, spoofed host token, attacked a player using a mod year, and so on.

### Solution

It would be appropriate to combine this with the "Modder detected by antivirus" reaction so that they can be automatically kicked and blocked from joining and that there would be an option not to add them to the player database, since the table quickly becomes clogged to no avail.
![screenshot](https://github.com/YimMenu/YimMenu/assets/139077095/8d644223-4195-4446-92cb-8e69402e866e)

### Reason

 I think this is much easier to do than filtering and sorting the player database

**Comment by gir489returns** [comment]
Where is desync protection? I tried finding it before but could not locate it. Someone desync kicked me and that really rustled my jimmies.

**Comment by ghost** [comment]
> Where is desync protection? I tried finding it before but could not locate it. Someone desync kicked me and that really rustled my jimmies.

I saw desync protection only at the stand and 2take1 users. It’s a pity that sometimes you have to co-load with a free stand and put up with random crashes(or kick the host, but often it is impossible) in order to somehow protect yourself from desync kicks, but even this does not always save.

**Comment by Yimura** [comment]
> I saw desync protection only at the stand and 2take1 users. It’s a pity that sometimes you have to co-load with a free stand and put up with random crashes(or kick the host, but often it is impossible) in order to somehow protect yourself from desync kicks, but even this does not always save.

The desync kick protection doesn’t work, they still have it enabled for some dumb reason. Co-loading Stand won’t protect you from desync kicks magically.
