### ISSUE TITLE
[Bug]: Chat filter it's always enabled after injecting

### ISSUE THREAD

**Issue by PinkyPromises** [Yimura/YimMenu#1682]
### Describe the bug

Chat filter it's always enabled no matter if in the menu it's disabled

### Steps To Reproduce

Enable or disable it

### Expected Behavior

Filter should be enabled after toggling it off

### Screenshots and/or Logs

No logs

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
To my awareness the chat filter hook doesn't work anymore as remote players are now checking against profanity and not locally.
