### ISSUE TITLE
[Bug]: Removing weapons doesn't persist

### ISSUE THREAD

**Issue by PinkyPromises** [Yimura/YimMenu#1683]
### Describe the bug

Removing weapons doesn't persist, it only works for 1 session (Trying to get rid of Hazardous Jerry Can)

### Steps To Reproduce

1. Get all weapons
2. Select Hazardous Jerry Can
3. Use remove weapon
4. Join a different lobby

### Expected Behavior

Removing Hazardous Jerry Can with the Remove Weapon should persist

### Screenshots and/or Logs

No logs

### Store

Epic Games

### Additional context

I don't have an idea how I got that Jerry Can but it's supposed to be impossible to get in free mode, yet I can't hide it even with a custom loadout

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
This is not a bug. It is working as intended. If you want to remove it, you have to remove it from your weapon bitset stats. This should be closed as not a bug.

**Comment by Tayipc38** [comment]
Like @gir489returns mentioned, removing weapons does not modify the actual data. You could request a feature that modifies your weapons data instead.
