### ISSUE TITLE
[Bug]: Outfit editor bugs

### ISSUE THREAD

**Issue by PinkyPromises** [Yimura/YimMenu#1684]
### Describe the bug

When changing certain values with "+"  will return to 0 or not past certain number unless you directly input the index.

**Components:**
BERD: 51 / 230
LOWR: 143 / 179
FEET: 101 / 136
TEEF: 168 / 147
ACCS: 122 / 200
DCL: 129 / 177
JBIB: 392 / 503

**Props:**
Head: 93 / 202 (pressing slowly)
Watch: 44 / 47
Wrist: 9 / 14

### Steps To Reproduce

1. Go to outfit editor
2. Click or hold on "+" in the mentioned above

### Expected Behavior

Continue to rolling the index without stopping or going back to X index.

### Screenshots and/or Logs

No logs.

### Store

Epic Games

### Additional context

Only tested with male character.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
```cpp
const inline std::unordered_set<std::uint32_t> gen9_berd   = {209, 210, 211, 212, 213, 226, 227, 229};
const inline std::unordered_set<std::uint32_t> gen9_m_uppr = {210};
const inline std::unordered_set<std::uint32_t> gen9_f_uppr = {243, 244};
const inline std::unordered_set<std::uint32_t> gen9_m_lowr = {144, 149, 150, 163, 164, 165, 166, 167, 168, 169, 170, 172, 174};
const inline std::unordered_set<std::uint32_t> gen9_f_lowr = {151, 157, 158, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 186, 189};
const inline std::unordered_set<std::uint32_t> gen9_m_feet = {102, 110, 129, 130, 131, 132, 133};
const inline std::unordered_set<std::uint32_t> gen9_f_feet = {106, 114, 133, 135, 136, 137, 138, 140};
const inline std::unordered_set<std::uint32_t> gen9_m_teef = {168, 169, 170, 173, 174};
const inline std::unordered_set<std::uint32_t> gen9_f_teef = {138, 139, 140, 143, 144};
const inline std::unordered_set<std::uint32_t> gen9_m_accs = {189, 192, 195, 196, 197, 198, 199};
const inline std::unordered_set<std::uint32_t> gen9_f_accs = {234, 237, 240, 241, 242, 243, 244, 245};
const inline std::unordered_set<std::uint32_t> gen9_m_decl = {140, 141, 142, 147, 163, 164, 166, 167, 168, 170, 171, 172, 181, 183, 184, 191, 192, 193, 194};
const inline std::unordered_set<std::uint32_t> gen9_m_jbib = {393, 414, 415, 416, 417, 418, 419, 420, 421, 454, 456, 457, 458, 461, 462, 463, 465, 466, 467, 468, 469, 471, 474, 477, 478, 479, 480, 483, 484, 485, 491, 492, 493, 496, 497, 498, 502, 503};
const inline std::unordered_set<std::uint32_t> gen9_f_jbib = {415, 441, 442, 443, 444, 445, 446, 447, 448, 449, 486, 488, 489, 490, 491, 492, 495, 496, 497, 499, 500, 501, 502, 503, 505, 509, 510, 512, 513, 514, 515, 516, 519, 521, 522, 530, 531, 532, 535, 536, 537, 542, 543};
```
All gen9 clothing IDs i found.

**Comment by gir489returns** [comment]
It uses GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS to determine the max.

**Comment by PinkyPromises** [comment]
> It uses GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS to determine the max.

In english please?

**Comment by gir489returns** [comment]
> > It uses GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS to determine the max.
> 
> In english please?

Oh really? Like your fucking ticket was? I can't tell what you're actually complaining about, so I assumed it was that you aren't able to use the + button over items that are within the stock game. DLC items require using DLC natives to retrieve the max, but the GUI is only using GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS which only iterates the stock drawables.

**Comment by tupoy-ya** [comment]
> Oh really? Like your fucking ticket was? I can't tell what you're actually complaining about, so I assumed it was that you aren't able to use the + button over items that are within the stock game. DLC items require using DLC natives to retrieve the max, but the GUI is only using GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS which only iterates the stock drawables.

It stops scrolling when you reach some gen9 clothing item.
https://github.com/YimMenu/YimMenu/pull/1441#issuecomment-1595869832

**Comment by PinkyPromises** [comment]
> > > It uses GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS to determine the max.
> > 
> > 
> > In english please?
> 
> Oh really? Like your fucking ticket was? I can't tell what you're actually complaining about, so I assumed it was that you aren't able to use the + button over items that are within the stock game. DLC items require using DLC natives to retrieve the max, but the GUI is only using GET_NUMBER_OF_PED_DRAWABLE_VARIATIONS which only iterates the stock drawables.

Why so pressed? I never intened to be mean or anything like that I just wanted an explanation since I don't know anything internal about GTA V. I'm not complaining, I'm reporting that reaching certain items it wont go past it and instead it will get stuck or return to 0 when there are a lot of available accesories you can wear past the numbers I posted.

**Comment by gir489returns** [comment]
You've opened like 3 tickets within the last hour and only one of them is a real bug. That's why.

**Comment by PinkyPromises** [comment]
> You've opened like 3 tickets within the last hour and only one of them is a real bug. That's why.

You are being a dick for no reason, I'm doing what was requested from Yimura, opening individual tickets for different bug reports.

**Comment by Tessio** [comment]
This important correction was gradually forgotten.

**Comment by gir489returns** [comment]
> This important correction was gradually forgotten.

We are not implementing this, as it overextends what the game allows for.

**Comment by Yimura** [comment]
> This important correction was gradually forgotten.

Anyone is free to work on whatever and we're tackling more important and impactful changes that will benefit us in the long run.
