### ISSUE TITLE
Gifting vehicles 

### ISSUE THREAD

**Issue by 8KV** [Yimura/YimMenu#169]
**Additional context**
Add a feature to gift vehicles to players.

**Comment by SkiddyToast** [comment]
This can be done with the DECOR_SET_INT native.
`DECORATOR::DECOR_SET_INT(vehicle, "Player_Vehicle", NETWORK::NETWORK_HASH_FROM_PLAYER_HANDLE(g_player_service->get_selected()->id()));`

**Comment by 8KV** [comment]
> This can be done with the DECOR_SET_INT native. `DECORATOR::DECOR_SET_INT(vehicle, "Player_Vehicle", NETWORK::NETWORK_HASH_FROM_PLAYER_HANDLE(g_player_service->get_selected()->id()));`

This puts you in an infinite loading screen if you drive the vehicle to your garage.

**Comment by SkiddyToast** [comment]
Seems to work for me... did you fill your garage first?
![image](https://user-images.githubusercontent.com/45642596/166819970-539b7c86-a1d6-4ca4-bec5-ea3e8826a404.png)

**Comment by LiamD-Flop** [comment]
See reasoning in PR #225
