### ISSUE TITLE
[Bug]: The weapon list in Spawn ped is broken

### ISSUE THREAD

**Issue by Vinnie-48** [Yimura/YimMenu#1698]
### Describe the bug

The weapon selection is broken, before there was sub categories. But now it's _"all" or "no weapons"_ under Weapon Type and 
in the weapon selection, everything is listed by alphabetical order (and there a few "null").

_cf the joined screenshots_

### Steps To Reproduce

1. Spawn Ped tab in world menu
2. Weapon section
3. check "weapon type" and "weapon"

### Expected Behavior

This problem is present since a couple of release, I tried cache rebuild too.

### Screenshots and/or Logs

```
<paste your logs here>
```
![spawn-ped bug 1](https://github.com/YimMenu/YimMenu/assets/137432520/6c763826-f984-49fb-831f-3f226344820d)
![spawn-ped bug 2](https://github.com/YimMenu/YimMenu/assets/137432520/0735728e-f1ea-452b-b6bd-f954280c3612)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
same problem. when I collect the cache for the first time in the game mode selection window, then the subcategories are present, but after restarting the game they disappear
