### ISSUE TITLE
[Bug]: Inability to join a player

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1702]
### Describe the bug

The problem is that I can't access a player who is online when looking at the player database. It has a green indicator and you can't tell if the host blocked you or if it's in a private session or if it's on a mission or some other reason. You just see the inscription "the time to join the session has expired" or something like that

### Steps To Reproduce

1. Section Network
2. Player database

### Expected Behavior

I think it's worth adding more indicators like yellow if you can't access it even though it's online. And you can also add a session type and more information about it. It seems to be possible to do this, as other mods like the stand can even view the specific type of session the host's player is in and so on. 
![1](https://github.com/YimMenu/YimMenu/assets/139077095/8731eb0c-32cc-4523-9ad2-d3821ed21391)

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
I thought your name was KBAR remover. Does the SCAPI even emit that information?

**Comment by maybegreat48** [comment]
> I thought your name was KBAR remover. Does the SCAPI even emit that information?

I'm assuming that they are using a different endpoint that gives the session type (`gstype`) along with the info (`gsinfo`)

I think I figured out where they're getting that from: the same place we got the socket info for the remote crash
