### ISSUE TITLE
[Bug]: pt2 - Cmake fails for minhook-populate

### ISSUE THREAD

**Issue by WHots** [Yimura/YimMenu#1707]
### Describe the bug

I don't even know what to say...

Look at screenshots... that's basically what happens immediately.

I'm not new to VS... and i followed those "instructions" which is literally just install VS 2022, make sure cmake is there and open the project local folder... haven't seen anyone else talk about my issue, assuming 99% of people on this are just normal users.

Screenshots are listed, pretty much immediate when opening the local folder.

### Steps To Reproduce

clone and open  the project.

### Expected Behavior

Stop packing shit wrong, something like this can just be shared via sln.

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://github.com/YimMenu/YimMenu/assets/56490828/7c420960-1664-474d-a692-894fb08486bc)
![image](https://github.com/YimMenu/YimMenu/assets/56490828/b2c25f9a-5257-42e1-8b10-8205acd6c7b2)
![image](https://github.com/YimMenu/YimMenu/assets/56490828/bfee0fe7-9308-4700-94cc-f784012fdf4d)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
Can you try installing [this](https://git-scm.com/download/win)?

**Comment by Yimura** [comment]
Did you follow the installation instructions for YimMenu?

**Comment by Yimura** [comment]
Shouldn't be an issue if the setup guide was followed properly.
