### ISSUE TITLE
Text does not fit and does not appear

### ISSUE THREAD

**Issue by HellPortal** [Yimura/YimMenu#171]
**Describe the bug**
Text does not fit and does not appear. Monitor resolution and game resolution (1920x1080)

**Screenshots**
![1](https://user-images.githubusercontent.com/104918285/166717307-539ac366-2a97-4cc7-9c1b-f75463bd8b6a.png)

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**

**Comment by Yimura** [comment]
Thanks for your issue, I have an ultrawide monitor and don't always check if text fits, however this will be fixed with the new UI that's almost finished.

**Comment by HellPortal** [comment]
> Thanks for your issue, I have an ultrawide monitor and don't always check if text fits, however this will be fixed with the new UI that's almost finished.

Thank you for your reply. Good luck.
