### ISSUE TITLE
[Request]: Clone and spawn nearest vehicle (closest vehicle)

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1713]
### Problem

Currently no way to clone the nearest posssibly vechicle.

Its just a request. If its not good for the menu then its fine to close it.

### Solution

Add a button "Clone nearest" in vechicle section.

### Reason

Clone cars that we cant sit in or are inaccessible. Main motivation is driving cars that are already finished and cool looking.

**Comment by xiaoxiao921** [comment]
In which car exactly you can't sit in? noclip + the context menu allow you to tp into the targeted car

**Comment by lonelybud** [comment]
like the car in LS car meet and luxury motors or friends car for example.
Currently we can tp only to last vechicle, personal vechile and one we spawn.

Kiddion mod menu had it working 0.9.9 but it is broken in 0.9.10

**Comment by xiaoxiao921** [comment]
... Did you try using the context menu like I said?

**Comment by lonelybud** [comment]
where is the context menu. i will liek to try

**Comment by dynamoNg** [comment]
how to open context menu?

**Comment by lonelybud** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/139460769/36073873-7e74-436c-b1a2-aaa4a430833b)

enable context menu and noclip.
not able to do what i expect. what should i do to clone nearest possible vehicleor enter a non drivable vehicle

**Comment by lonelybud** [comment]
also what is the purpose of context menu. cant see it over ped, objects ot vehicle
![image](https://github.com/YimMenu/YimMenu/assets/139460769/f11ab54b-2042-47e2-a6c7-bd3cb1faf769)

**Comment by xiaoxiao921** [comment]
Press the krybind for ducking inside a vehicle, which is X by default

**Comment by lonelybud** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/139460769/f0bbba35-7364-4427-9b0a-822aaf09c2e0)
yes its X.
in order to move aroudn the options i am using mouse middle scroll

**Comment by Yimura** [comment]
Mouse scroll wheel? It should be the controls for next and previous weapon.

**Comment by lonelybud** [comment]
yes the list as shown in image. i able to scroll through the list of options via scroll wheel

**Comment by lonelybud** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/139460769/a1cb44ad-1360-49fe-aac6-fabe08bec624)
@Yimura once i let this dance. how to reset the option. stop the dance

**Comment by lonelybud** [comment]
thanks @xiaoxiao921 i am able to use context menu to copy vehicles in situations i asked for.
![image](https://github.com/YimMenu/YimMenu/assets/139460769/cb8165b9-b6b7-444a-9917-a747d542b941)

**Comment by lonelybud** [comment]
there are some questions not related to this pr. can i ask here I think it would be better?

**Comment by dynamoNg** [comment]
there are some questions not related to this pr. can i ask here I think it would be better?

**Comment by Yimura** [comment]
No, if something is not related to this issue it shouldn't be asked on here.

Check if it exists, and if it doesn't make an new issue.

**Comment by lonelybud** [comment]
@Yimura shoudl we add documentation for like press X to open context menu or something to prevent future issues like this?
