### ISSUE TITLE
[Bug]: GTA crashes when I inject YimMenu

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1720]
### Describe the bug

I use the Xenos injector to inject the dll file but since yesterday, whenever I've tried to inject the menu, GTA ends up crashing. I've tried reinstalling and downloading the latest version of both the Xenos injector and YimMenu from UC but nothing has worked out yet. GTA crashes even when I try injecting the menu when in story mode.

### Steps To Reproduce

there isn't aren't really steps to reproduce the issue, it happens when I inject it.

### Expected Behavior

I expected the menu to get injected normally but it ended up crashing my game💀.

### Screenshots and/or Logs

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/12054146/cout.log)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Democles85** [comment]
Do you by any chance have any LUA script installed?

**Comment by gir489returns** [comment]
Yeah looks like the Lua interpreter exploding.

**Comment by ghost** [comment]
> 

yes, ill try deleting the lua script. (worked)

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/pull/1722

should make clearer which lua scripts are faulty
