### ISSUE TITLE
[Request]: leave gta online feature should work like that in kiddion mod menu

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1723]
### Problem

The game loads as follows

![image](https://github.com/YimMenu/YimMenu/assets/139460769/2ca1592a-3a7c-400f-94c3-0c898af0d9e3)
![image](https://github.com/YimMenu/YimMenu/assets/139460769/f4a12778-8bd6-44d4-8714-6846d8214fdc)
Further progress ....

In yim menu when I click `Leave Gta Online` under `network tab` before the player is shown in the game then it does not work. It shows `Player Switch in Progress`.

In kiddion similarly we have `Leave Online` under `Game`. When used it is able to leave online in every loading progress step after the `Pre-Hud Checks`

### Solution

One should be able to get out of gta online session if they are stuck in the clouds, white/black screen safely and get back to single player mod.

![image](https://github.com/YimMenu/YimMenu/assets/139460769/8c802bdf-c04f-44bd-8c73-e8653f9c774c)

### Reason

Stuck in session in which player is not loaded

**Comment by lonelybud** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/139460769/031df86e-de3e-4741-b4d7-5cd1dd5c52e4)
still not able to leave online when in joining progress...

I have used latest dll
@maybegreat48

**Comment by maybegreat48** [comment]
Works for me. Can you try again with the latest version of the menu?

**Comment by lonelybud** [comment]
i will check and confirm again. Buy the way as shown in image above if I click Leave GTA online when session is still in the process of joining then it should leave it immediatly. i will check it again.

**Comment by Yimura** [comment]
Duplicate of #1201

**Comment by lonelybud** [comment]
@maybegreat48 its still the same. By the way as mentioned my @Yimura in #1201 network bail can be used - 

![image](https://github.com/YimMenu/YimMenu/assets/139460769/08a05103-2d21-4989-9062-7eef56580853)

@Yimura network bail will not effect other players in lobby right? like it wont kick them?

**Comment by maybegreat48** [comment]
No
