### ISSUE TITLE
[Bug]: dance mod does not work

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1728]
### Describe the bug

There is an option **dance mod** under **self** but it does not work or have a tooltip for its purpose

### Steps To Reproduce

**dance mod** checkbox under **self** submenu

### Expected Behavior

it should work and have an info

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Tayipc38** [comment]
Hold E after enabling it.

**Comment by lonelybud** [comment]
lol. so this basically same as in nightclub. we press E. Do we need documentation for this? @DayibBaba
