### ISSUE TITLE
[Bug]: "Context Menu Enabled" stopped working

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#1740]
### Describe the bug

A couple builds ago, "Context Menu Enabled" in "Self" was working; now it no longer works.

### Steps To Reproduce

1. Load menu.
2. Enable "Context Menu Enabled"
3. Press X (playstation) or A (xbox)
4. Doesn't appear

### Expected Behavior

Context box should appear when pressing X or A

### Store

Epic Games

### Additional context

The first time using this option was hard since there was nothing pointing to how it even worked, but I figured out it was X or A, and you select options with L3 or R3 (I don't remember right now). Maybe the button to enable it has changed and I can't find it. If that's the case then please could you add some kind of info to the option? This is a bug alongside a small request, I hope it doesn't confuse things too much.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
Either button for ducking inside car

Try also aiming + Y on xbox controller

**Comment by Yimura** [comment]
The context menu is disabled by default, go to "Self -> Context Menu" to enable it.
