### ISSUE TITLE
[Bug]: Vehicle/Fun Abilities

### ISSUE THREAD

**Issue by GodOfPain0** [Yimura/YimMenu#1749]
### Describe the bug

While turning on keep vehicle repaired nothing comes on fun abilities but when you are turning it off it comes again and when abilities are being turned on nothing changes. At least rgb does not work 

### Steps To Reproduce

1.F3
2.Vehicle/Turn on Keep Repaired
3. Fun Abilities
4. Does not Appear
5.Vehicle/Turn off Keep Repaired
6.Abilities Appear but does not work

### Expected Behavior

Nothing Happens

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by holysnipz** [comment]
related: #1727 #1735

try this artifact build instead:
https://github.com/YimMenu/YimMenu/actions/runs/5569889953

**Comment by Yimura** [comment]
Should be fixed with the latest nightly.

**Comment by maybegreat48** [comment]
This issue should be reopened since RGB fade doesn't work anymore (#1708 probably broke it)

**Comment by Yimura** [comment]
True I had not noticed the RGB thing specifically.

**Comment by TheGreenBandit** [comment]
will fix in new pr, worked fine for me

**Comment by Yimura** [comment]
Closing this in favour for #1819
