### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lfengss** [Yimura/YimMenu#1753]
### Describe the bug

Does the send message seem to be unavailable?

### Steps To Reproduce

Does the send message seem to be unavailable?

### Expected Behavior

Does the send message seem to be unavailable?

### Screenshots and/or Logs

```
<paste your logs here>
```
![20230718083753](https://github.com/YimMenu/YimMenu/assets/87269887/942224eb-eec2-4942-bf0c-9455c424d832)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by lonelybud** [comment]
send message works. Fill the input with the player name or id. Then click search. Then click add. Then message that user. After successfully sending message you should see the notification on the top right

**Comment by lfengss** [comment]
> 



> send message works. Fill the input with the player name or id. Then click search. Then click add. Then message that user. After successfully sending message you should see the notification on the top right

Yes, this is how I operate, the upper right corner of the message sent successfully, but can not find this message!!

**Comment by lonelybud** [comment]
yes i am able to reproduce. with latest dll.

Please update your pr title correctly. Make it this -

`sending message via player database does not reflect in social club message list`

**Comment by lonelybud** [comment]
Earlier when we send a message it was instantly seen inside social club messages even the player is friend or not. Now the message sent is not reflected in social club.

**Comment by Yimura** [comment]
Doesn't seem like an issue with YimMenu then, the message is sent to their socialclub inbox.

Go to this page to see the messages you received: https://socialclub.rockstargames.com/message

**Comment by lonelybud** [comment]
i think the message is visible on social club only when they are online?
