### ISSUE TITLE
[Request]: Feature to clear persistent spawned garbage by other players

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1754]
### Problem

Some players have the ability to spawn persistent props or vehicles. These items persist between sessions, even into missions with other players that weren't present at the time the spawned garbage was added. 

### Solution

Ability to manually clear everything on a needed basis. 

### Reason

Only way I've been able to clear this persistent spawned garbage is with a restart of the game.

**Comment by maybegreat48** [comment]
Have you tried `World > Delete`?

**Comment by Tayipc38** [comment]
No idea whether objects in online require control. Maybe deleting them without asking network control might work.
