### ISSUE TITLE
[Bug]: natives.hpp a critical compilation error occurred

### ISSUE THREAD

**Issue by ifqmwe** [Yimura/YimMenu#1755]
### Describe the bug

natives.hpp a critical compilation error occurred

### Steps To Reproduce

natives.hpp a critical compilation error occurred

### Expected Behavior

natives.hpp a critical compilation error occurred

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Other (please mention in "Additional context")

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Logs? Screenshots? Without any of this it's pretty useless.

**Comment by Yimura** [comment]
No extra info from issue author, closing for now. Will reopen if they reply.
