### ISSUE TITLE
[Bug]: Cant inject latest nightly

### ISSUE THREAD

**Issue by Drsexo** [Yimura/YimMenu#1758]
### Describe the bug

Injecting latest nightly will force close the game (im on epic)

### Steps To Reproduce

inject
crash

### Expected Behavior

should inject

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/12080449/cout.log)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by BugisoftRSG** [comment]
Are you co-loading with another menu?

**Comment by Yimura** [comment]
It failed to find several of the signatures in GTA5.

**Comment by Drsexo** [comment]
after some tests it seems to only fail if i co-load with another menu (stand free)
even tho the version i downloaded 2 days ago from github actions didnt have this issue

**Comment by Yimura** [comment]
And when did you last use YimMenu? 2 days ago as well? Stand might have updated as well and broken YimMenu from working with it.
Nothing we changed in the last 2 days we did could cause the issues indicated by the log file. Try to load YimMenu without Stand at least once after updating, you can then unload and try again.

**Comment by Drsexo** [comment]
stand didnt change, it used to work perfectly with yim until #1734 
all the builds i tried after that commit got this crashing co load issue
not a problem yim works fine alone ty :)

**Comment by Yimura** [comment]
Hmmm unsure, any specific reason you're co-loading Stand free with YimMenu?

**Comment by xiaoxiao921** [comment]
I can't reproduce with YimMenu alone. I suggest asking the stand devs every time you coload instead of doing it there, as it's much easier to fix on their side than ours due to their code not being readily accessible, we could of course RE their dlls but that takes more time than just being able to check the source code directly

**Comment by Drsexo** [comment]
has more protections, i get crashed a lot with yim only 
stand can block bored teenagers

**Comment by Yimura** [comment]
> has more protections, i get crashed a lot with yim only stand can block bored teenagers

When was the last time you observed this? YimMenu has done a bunch of updates to improve protections.
With many more coming thanks to our wonderful contributors :)

**Comment by ghost** [comment]
I also co-load with stand free edition. No crashing problem on my end with the latest nightly (f8cf642) upon injection.

**Comment by maybegreat48** [comment]
I'm not sure, but I think you have to inject YimMenu before Stand for the co-load to work

**Comment by Yimura** [comment]
Not an issue with YimMenu.
