### ISSUE TITLE
[Bug]: game crashes when injecting from ex loader or dll

### ISSUE THREAD

**Issue by bobrel** [Yimura/YimMenu#1767]
### Describe the bug

when i inject the mod menu (yim menu) my game crashes after about 7 8 seconds

### Steps To Reproduce

1.i open gta and enter online
2. i press on exloader the launch button
3.i wait to load the cheat
4.after about 7 8 seconds the game crashes

### Expected Behavior

the game freezes and crashes

### Logs and/or screenshots

```
<paste your logs here>
```
[04:29:26.6676238][INFO/main.cpp:66] Yim's Menu Initializing
[04:29:26.6676602][INFO/main.cpp:67] Git Info
        Branch: master
        Hash:   f26514f8e459ca65ac62f16b00962ba8a0f1178b
        Date:   Thu Jul 13 07:36:13 2023
[04:29:26.6677621][INFO/main.cpp:70] Thread pool initialized.
[04:29:26.6736391][WARN/thread_pool.cpp:56] thread_pool potentially starved
[04:29:26.6736464][INFO/main.cpp:73] Settings Loaded.
[04:29:26.6748577][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[04:29:26.6748980][INFO/pointers.cpp:1409] Loading pointers instance from cache
[04:29:26.6749004][INFO/pointers.cpp:1418] Pointers cache: Loading 165 fields from the cache
[04:29:26.6756192][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[04:29:26.6762602][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[04:29:26.6762701][INFO/pointers.cpp:1409] Loading pointers instance from cache
[04:29:26.6762726][INFO/pointers.cpp:1418] Pointers cache: Loading 3 fields from the cache
[04:29:26.6763019][INFO/main.cpp:76] Pointers initialized.
[04:29:26.6763383][INFO/main.cpp:79] Byte Patch Manager initialized.
[04:29:26.6797911][DEBUG/thread_pool.cpp:22] Allocating 4 threads in thread pool.
[04:29:26.6808317][DEBUG/thread_pool.cpp:87] Thread 5360 executing settings.cpp:18
[04:29:27.5600714][INFO/main.cpp:82] Renderer initialized.
[04:29:27.9142706][INFO/main.cpp:86] Fiber pool initialized.
[04:29:28.0676530][INFO/main.cpp:89] Translation Service initialized.
[04:29:28.0965792][INFO/main.cpp:92] Hooking initialized.
[04:29:28.1053626][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[04:29:28.1053798][INFO/gta_data_service.cpp:175] Loading 1029 peds from cache.
[04:29:28.1058217][INFO/gta_data_service.cpp:193] Loading 815 vehicles from cache.
[04:29:28.1061632][INFO/gta_data_service.cpp:166] Loading 117 weapons from cache.
[04:29:28.1061686][INFO/gta_data_service.cpp:167] Loading 378 weapon components from cache.
[04:29:28.1061723][DEBUG/gta_data_service.cpp:169] Loaded all data from cache.
[04:29:28.1115154][INFO/tunables_service.cpp:21] Loading tunables from cache
[04:29:28.1115665][INFO/main.cpp:113] Registered service instances...
[04:29:28.1115505][DEBUG/thread_pool.cpp:87] Thread 14888 executing tunables_service.cpp:24
[04:29:28.1127149][INFO/main.cpp:133] Scripts registered.
[04:29:28.1775974][INFO/main.cpp:136] Hooking enabled.
[04:29:28.1801103][INFO/main.cpp:139] Dynamic native hooker initialized.
[04:29:28.1964100][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF6E7470000 Size: 67158528
ntdll.dll Base Address: 0x7FFF1E110000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFF1DD70000 Size: 519168
KERNELBASE.dll Base Address: 0x7FFF1BCC0000 Size: 1255424
USER32.dll Base Address: 0x7FFF1D6D0000 Size: 581120
win32u.dll Base Address: 0x7FFF1BA40000 Size: 42496
GDI32.dll Base Address: 0x7FFF1E040000 Size: 61952
gdi32full.dll Base Address: 0x7FFF1C050000 Size: 669696
msvcp_win.dll Base Address: 0x7FFF1B8F0000 Size: 344064
ucrtbase.dll Base Address: 0x7FFF1B7F0000 Size: 735744
PSAPI.DLL Base Address: 0x7FFF1D020000 Size: 2048
WS2_32.dll Base Address: 0x7FFF1D2E0000 Size: 275456
RPCRT4.dll Base Address: 0x7FFF1D470000 Size: 923136
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFECDF40000 Size: 96256
VERSION.dll Base Address: 0x7FFF15800000 Size: 10752
CRYPT32.dll Base Address: 0x7FFF1BB10000 Size: 1100288
DSOUND.dll Base Address: 0x7FFEFA320000 Size: 380416
msvcrt.dll Base Address: 0x7FFF1D960000 Size: 477184
WINTRUST.dll Base Address: 0x7FFF1BA70000 Size: 292864
advapi32.dll Base Address: 0x7FFF1C300000 Size: 427520
bink2w64.dll Base Address: 0x7FFEFB830000 Size: 307712
IMM32.dll Base Address: 0x7FFF1D100000 Size: 122368
ole32.dll Base Address: 0x7FFF1C170000 Size: 832000
bcrypt.dll Base Address: 0x7FFF1BAE0000 Size: 103424
combase.dll Base Address: 0x7FFF1DA00000 Size: 2327040
SHLWAPI.dll Base Address: 0x7FFF1C2A0000 Size: 182784
WININET.dll Base Address: 0x7FFEFC890000 Size: 2026496
SHELL32.dll Base Address: 0x7FFF1C8B0000 Size: 5803520
WINMM.dll Base Address: 0x7FFF12AD0000 Size: 81408
sechost.dll Base Address: 0x7FFF1DFA0000 Size: 412672
OLEAUT32.dll Base Address: 0x7FFF1D030000 Size: 608256
MF.dll Base Address: 0x7FFEE2C30000 Size: 340992
MFPlat.DLL Base Address: 0x7FFEE7790000 Size: 1409536
cfgmgr32.dll Base Address: 0x7FFF1BC70000 Size: 218624
msdmo.dll Base Address: 0x7FFF0D160000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFEF1320000 Size: 918016
shcore.dll Base Address: 0x7FFF1DE30000 Size: 476672
PROPSYS.dll Base Address: 0x7FFF17370000 Size: 631296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFF0D520000 Size: 48128
d3d9.dll Base Address: 0x7FFEED210000 Size: 1371648
WTSAPI32.dll Base Address: 0x7FFF174D0000 Size: 37888
D3DCOMPILER_43.dll Base Address: 0x7FFEF1D30000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFEF2330000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
d3dx9_43.dll Base Address: 0x7FFEEC350000 Size: 2280960
IPHLPAPI.DLL Base Address: 0x7FFF1ABC0000 Size: 170496
SETUPAPI.dll Base Address: 0x7FFF1C3B0000 Size: 864768
powrprof.dll Base Address: 0x7FFF1B390000 Size: 70656
winmmbase.dll Base Address: 0x7FFEEDB40000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFF196D0000 Size: 16384
OPENGL32.dll Base Address: 0x7FFEF1C00000 Size: 909312
dwmapi.dll Base Address: 0x7FFF193E0000 Size: 99328
windows.storage.dll Base Address: 0x7FFF198D0000 Size: 5819904
GLU32.dll Base Address: 0x7FFEF1B10000 Size: 122880
MFCORE.DLL Base Address: 0x7FFEC37C0000 Size: 3960832
Wldp.dll Base Address: 0x7FFF1B170000 Size: 94720
ksuser.dll Base Address: 0x7FFF174C0000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFF1B0C0000 Size: 10752
UMPDC.dll Base Address: 0x7FFF1B370000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFF1BFC0000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFEE7750000 Size: 105472
MSASN1.dll Base Address: 0x7FFF1B3E0000 Size: 34816
inputhost.dll Base Address: 0x7FFEFA760000 Size: 976384
wintypes.dll Base Address: 0x7FFF181C0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFF18DE0000 Size: 606720
CoreUIComponents.dll Base Address: 0x7FFF18A80000 Size: 1804800
ntmarta.dll Base Address: 0x7FFF1A910000 Size: 140288
dbghelp.dll Base Address: 0x7FFF11030000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFF0CF80000 Size: 136704
d3d12.dll Base Address: 0x7FFEFAAB0000 Size: 73728
CRYPTSP.dll Base Address: 0x7FFF1B0D0000 Size: 46080
rsaenh.dll Base Address: 0x7FFF1A7F0000 Size: 142336
uxtheme.dll Base Address: 0x7FFF19200000 Size: 382464
clbcatq.dll Base Address: 0x7FFF1D620000 Size: 437760
dxdiagn.dll Base Address: 0x7FFEF6EE0000 Size: 395264
d3d11.dll Base Address: 0x7FFF17990000 Size: 1853440
DEVOBJ.dll Base Address: 0x7FFF1B5A0000 Size: 109056
dxgi.dll Base Address: 0x7FFF1A0B0000 Size: 614912
WMICLNT.dll Base Address: 0x7FFF16E20000 Size: 31744
wbemprox.dll Base Address: 0x7FFF13F10000 Size: 27648
wbemcomn.dll Base Address: 0x7FFF0C1D0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFF0BCE0000 Size: 7168
fastprox.dll Base Address: 0x7FFF0B5A0000 Size: 708608
amsi.dll Base Address: 0x7FFF12880000 Size: 62464
USERENV.dll Base Address: 0x7FFF1B6F0000 Size: 108032
profapi.dll Base Address: 0x7FFF1B730000 Size: 68608
MpOav.dll Base Address: 0x7FFF12800000 Size: 204800
nvapi64.dll Base Address: 0x7FFF11710000 Size: 6282752
cryptnet.dll Base Address: 0x7FFF14EA0000 Size: 135168
drvstore.dll Base Address: 0x7FFF14C10000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFF04890000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFF134E0000 Size: 7680
imagehlp.dll Base Address: 0x7FFF1D000000 Size: 45056
nvspcap64.dll Base Address: 0x7FFEE1510000 Size: 2055680
NSI.dll Base Address: 0x7FFF1D950000 Size: 7680
dhcpcsvc.DLL Base Address: 0x7FFF15A40000 Size: 61440
MSCTF.dll Base Address: 0x7FFF1D350000 Size: 864256
textinputframework.dll Base Address: 0x7FFEFC430000 Size: 725504
WINSTA.dll Base Address: 0x7FFF1B1A0000 Size: 219648
nvldumdx.dll Base Address: 0x7FFF01C90000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFE78EB0000 Size: 36389376
NvCamera64.dll Base Address: 0x7FFEC8CF0000 Size: 4209664
HID.DLL Base Address: 0x7FFF1A070000 Size: 20480
XINPUT9_1_0.dll Base Address: 0x7FFF00B10000 Size: 4096
WindowsCodecs.dll Base Address: 0x7FFF15AA0000 Size: 1328128
MessageBus.dll Base Address: 0x7FFECAC00000 Size: 5349888
dxcore.dll Base Address: 0x7FFF14870000 Size: 147968
d3dcompiler_47_64.dll Base Address: 0x7FFECB480000 Size: 3922944
MMDevApi.dll Base Address: 0x7FFF15F00000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFEF6450000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFF16110000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFF192E0000 Size: 31744
Windows.UI.dll Base Address: 0x7FFEFA5C0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFF15DF0000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFF15600000 Size: 1449984
avrt.dll Base Address: 0x7FFF16670000 Size: 5632
MessageBus.dll Base Address: 0x7FFF03F00000 Size: 5349888
napinsp.dll Base Address: 0x7FFEEE2F0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFEED780000 Size: 66048
wshbth.dll Base Address: 0x7FFEFB6C0000 Size: 43008
NLAapi.dll Base Address: 0x7FFF17200000 Size: 68608
mswsock.dll Base Address: 0x7FFF1AED0000 Size: 331776
DNSAPI.dll Base Address: 0x7FFF1AC00000 Size: 599040
winrnr.dll Base Address: 0x7FFEE8360000 Size: 32768
fwpuclnt.dll Base Address: 0x7FFF0C310000 Size: 288768
rasadhlp.dll Base Address: 0x7FFF12E20000 Size: 7168
gpapi.dll Base Address: 0x7FFF1A080000 Size: 69120
WINNSI.DLL Base Address: 0x7FFF15D80000 Size: 11776
SspiCli.dll Base Address: 0x7FFF1B6B0000 Size: 123392
socialclub.dll Base Address: 0x7FFEE5930000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFEEA7A0000 Size: 685568
libcef.dll Base Address: 0x7FFEA64A0000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFF1D870000 Size: 684032
OLEACC.dll Base Address: 0x7FFF0FFE0000 Size: 260608
UIAutomationCore.DLL Base Address: 0x7FFEECF10000 Size: 2041344
Secur32.dll Base Address: 0x7FFEFFCF0000 Size: 11264
NETAPI32.dll Base Address: 0x7FFF0CB50000 Size: 47616
COMCTL32.dll Base Address: 0x7FFF0FD20000 Size: 560128
DWrite.dll Base Address: 0x7FFEF88D0000 Size: 1601024
USP10.dll Base Address: 0x7FFEEE770000 Size: 512
dxva2.dll Base Address: 0x7FFEEE1C0000 Size: 96256
urlmon.dll Base Address: 0x7FFF0E560000 Size: 1279488
credui.dll Base Address: 0x7FFEEB140000 Size: 61952
WINHTTP.dll Base Address: 0x7FFF14960000 Size: 845312
ncrypt.dll Base Address: 0x7FFF1B250000 Size: 102400
wevtapi.dll Base Address: 0x7FFF16690000 Size: 296960
ESENT.dll Base Address: 0x7FFF00B50000 Size: 2585088
CRYPTUI.dll Base Address: 0x7FFF01B3000

### Store

Rockstar

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by bobrel** [comment]
pls help

**Comment by Yimura** [comment]
Your log file is incomplete, can you include the whole log?

**Comment by Yimura** [comment]
No response from issue author, will reopen if they answer.
