### ISSUE TITLE
[Improvement]: Add get_all_as_handles API for Lua

### ISSUE THREAD

**Issue by sch-lda** [Yimura/YimMenu#1777]
### Which feature

 entities.get_all_peds_as_handles(), entities.get_all_vehicles_as_handles(), and entities.get_all_objects_as_handles() for Lua

### Reason

 It is fun to control nearby NPCs and vehicles using Lua. Lua is also very useful for batch deleting entities that meet certain conditions. I noticed that in the Lua API of Stand, there are functions like entities.get_all_peds_as_handles(), entities.get_all_vehicles_as_handles(), and entities.get_all_objects_as_handles(). These are helpful for Lua scripting.

**Comment by sch-lda** [comment]
I'm trying to do it myself. Moving code from entity.hpp. Is this correct?
![image](https://github.com/YimMenu/YimMenu/assets/54973190/56893ca7-db42-4a2d-9535-517f12bcb92f)
![image](https://github.com/YimMenu/YimMenu/assets/54973190/778eb65b-f1b8-497e-bd4f-afa24adf7318)
![image](https://github.com/YimMenu/YimMenu/assets/54973190/c058ed0d-ffc7-4655-b816-09f93c72c07f)

**Comment by gir489returns** [comment]
This is not necessary as the functions exposed from the natives already can be used to iterate entities, players and vehicles. This should be rejected.

**Comment by sch-lda** [comment]
I still believe that this cannot be achieved simply by wrapping native functions. I tried iterating through entities and using IS_ENTITY_A_PED, IS_ENTITY_A_VEHICLE, but the Yimmenu console outputted many [03:23:14.0130247][WARN/invoker.cpp:56] Exception caught while trying to call 0x6AC7003FA6E5575E native. I attempted using yield, which reduced the number of exceptions, but this means only one query can be executed per frame. I'm not sure how long it will take to complete one iteration.
I will keep this issue open until a better alternative solution is found.

**Comment by gir489returns** [comment]
You have to [run it in a script thread](https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/script.md#register_loopedname-func), you can't just run it inside a while loop or a gui callback. Stop opening stupid tickets. 65535 is also the max int16 I don't know if that's actually the maximum number of entitles there could be, but for players, there can only be 32, so if you're iterating players, start at 0, stop at 32. There's also the native PED_GET_PED_NEARBY_PEDS you can abuse and you can also do instead of a for loop, use a static integer and turn the for loop into an if condition that runs once every time the thread ticks.

**Comment by sch-lda** [comment]
First of all, thank you for your multiple replies. However, I disagree that this issue is foolish. Using native function traversal to achieve this functionality is inefficient and cumbersome. Other P2C menus such as Stand and 2T1 have similar APIs and they are widely used in their Lua scripts. The existence of Lua is helpful for users to write their own Lua scripts, which can improve efficiency and stability. I believe Lua serves both developers and regular users because it is simple, easy to learn, does not require professional review, can be uninstalled if problems arise, and does not require worrying about upstream code submissions for Yimmenu. C++ developers can directly submit code to the Yimmenu repository without going through Lua. The ability to serve regular users like me and easily customize and extend functionality is an important aspect of Lua, and a perfect Lua API is the foundation for that. My intention in opening this issue is to hope that a developer can fulfill my request, rather than seeking alternative solutions. If you do not agree with it, you can press the Unsubscribe button. If Yimmenu members also consider this to be foolish and close this issue, I will not reopen it.This is just a suggestion for improvement, and if no developer is willing to take it up, this issue will naturally be closed after a certain period of time.

**Comment by xiaoxiao921** [comment]
I can make these bindings, they don't take long to create, just a matter of doing it

**Comment by Yimura** [comment]
Yes, it really isn't a bad thing to expose this to lua as well.
