### ISSUE TITLE
help with car editor

### ISSUE THREAD

**Issue by matarife123** [Yimura/YimMenu#1778]
When I edit the wheels of my personal car they are not saved, it also happens with the license plate, am I doing something wrong?
![Sin título](https://github.com/YimMenu/YimMenu/assets/110930030/c5c8f494-6d08-4f87-a27b-8f4cee948e20)

**Comment by Yimura** [comment]
That editor is never meant to be permanent, if you need it to be permanent save as a persist vehicle and then spawn it using persist vehicle.

The Start LS Customs feature however should make the changes permanent on your vehicle. With the recent update it appears to have broken though.
