### ISSUE TITLE
Block Spam Message

### ISSUE THREAD

**Issue by HellPortal** [Yimura/YimMenu#178]
**Is your feature request related to a problem? Please describe.**
My phone keeps getting spam messages and the notification sound of spam messages is very annoying. And constant spam messages in chat.

**Describe the solution you'd like**
Blocking spam messages.

**Provide Reasoning**
Spam messages are annoying and notifications from spam messages are a headache. And seeing spam messages constantly in chat is eye catching, so I want to block spam messages.

**Additional context**
Someone from the forum sent me these source code. Can review this? I don't know coding. Thanks.
Source Code: https://github.com/HolyWurl/Block-GTASpamMessage

**Comment by Yimura** [comment]
Someone made a PR to block if the same chat message is sent, however that one doesn't block message on phone, so that one will come later.

**Comment by HellPortal** [comment]
> Someone made a PR to block if the same chat message is sent, however that one doesn't block message on phone, so that one will come later.

I tried this release and it works perfectly. I entered a session and there was someone spamming me. I dll "Block-GTASpamMessage" using an injector and the person who sent me a spam message was kicked out of the session.
