### ISSUE TITLE
[Bug]: crash while inject to game

### ISSUE THREAD

**Issue by Hamusuta0320** [Yimura/YimMenu#1784]
### Describe the bug

i clone the code from github, the code commit is 74ba7b686084ca23270a45ce75d699b412779e4f
i use visual studio to build the target dll
when i inject the dll to the game, crash occur

### Steps To Reproduce

1. clone the code with commit 74ba7b686084ca23270a45ce75d699b412779e4f
2. build with visual studio
3. vs settings, **i am no sure this setting is right to build release version**:
![image](https://github.com/YimMenu/YimMenu/assets/55654842/0f3ee412-673e-4dc4-8aa9-d78eb7d465c9)
4. build out this dll:
[YimMenu.zip](https://github.com/YimMenu/YimMenu/files/12114236/YimMenu.zip)
5. inject to game
6. then crash occur

### Expected Behavior

run no problem

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12114223/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Hamusuta0320** [comment]
need help！

**Comment by Rxann** [comment]
I suggest just using the already compiled one from the Releases page. Also, Make sure to not inject it too early because that will crash the game also.

**Comment by xiaoxiao921** [comment]
> I suggest just using the already compiled one from the Releases page. Also, Make sure to not inject it too early because that will crash the game also.

The error is due to a faulty translation line in the OP language json, this is a real issue that needs to be fixed

**Comment by Hamusuta0320** [comment]
> 

But one of my doubts is why the version of the Release page can run using the same source code compiled DLL, and my version reported an error. I also cleaned the YimMenu folder under appdata

**Comment by xiaoxiao921** [comment]
Which language you using in yimmenu? chinese?

**Comment by Hamusuta0320** [comment]
> Which language you using in yimmenu? chinese?

I don't seem to have actively configured this option, but he seems to have chosen to download Chinese files voluntarily

**Comment by gir489returns** [comment]
> > Which language you using in yimmenu? chinese?
> 
> I don't seem to have actively configured this option, but he seems to have chosen to download Chinese files voluntarily

It uses whatever language your computer uses.

**Comment by Hamusuta0320** [comment]
> 

Yes, my computer use chinese.

**Comment by gir489returns** [comment]
@xiaoxiao921 Is it possible https://github.com/YimMenu/Translations/pull/61 addresses this issue?

**Comment by Hamusuta0320** [comment]
Is this problem caused by an error in parsing the zh_CN. json file? How can i disable it and use en_US.json

**Comment by gir489returns** [comment]
> Is this problem caused by an error in parsing the zh_CN. json file? How can i disable it and use en_US.json

In YimMenu/translations in your appdata folder, index.json contains a key for selected_language (which would probably be zh_CN). You'd have to manually set it to en_US. That might be enough to do it.

**Comment by Hamusuta0320** [comment]
> > Is this problem caused by an error in parsing the zh_CN. json file? How can i disable it and use en_US.json
> 
> In YimMenu/translations in your appdata folder, index.json contains a key for selected_language (which would probably be zh_CN). You'd have to manually set it to en_US. That might be enough to do it.

It seems like this is the problem. I configured "selected_language": "en_US" in the index. json file, it works!

**Comment by gir489returns** [comment]
> > > Is this problem caused by an error in parsing the zh_CN. json file? How can i disable it and use en_US.json
> > 
> > 
> > In YimMenu/translations in your appdata folder, index.json contains a key for selected_language (which would probably be zh_CN). You'd have to manually set it to en_US. That might be enough to do it.
> 
> It seems like this is the problem. I configured "selected_language": "en_US" in the index. json file, it works!

Well, I'm glad we isolated the issue, but obviously we need to fix the Chinese language causing the build to fail to be injected, so please keep the issue open.

**Comment by Hamusuta0320** [comment]
> > > > Is this problem caused by an error in parsing the zh_CN. json file? How can i disable it and use en_US.json
> > > 
> > > 
> > > In YimMenu/translations in your appdata folder, index.json contains a key for selected_language (which would probably be zh_CN). You'd have to manually set it to en_US. That might be enough to do it.
> > 
> > 
> > It seems like this is the problem. I configured "selected_language": "en_US" in the index. json file, it works!
> 
> Well, I'm glad we isolated the issue, but obviously we need to fix the Chinese language causing the build to fail to be injected, so please keep the issue open.

Okay, I will keep this issue open，thanks for help!

**Comment by gir489returns** [comment]
@Hamusuta0320 Can you please try adding this compiler option to your build and revert to using the Chinese translation and see if it works? https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170

If it does, we might need to amend the build instructions for Chinese users.

**Comment by Hamusuta0320** [comment]
> @Hamusuta0320 Can you please try adding this compiler option to your build and revert to using the Chinese translation and see if it works? https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170
> 
> If it does, we might need to amend the build instructions for Chinese users.

I can not find the position to use this option... please tell me how to add it in vs

**Comment by Hamusuta0320** [comment]
The cmake project does not have a property page option in vs.

**Comment by gir489returns** [comment]
> The cmake project does not have a property page option in vs.

The page is probably not being translated properly, but the instructions are there.

To set this compiler option in the Visual Studio development environment
Open the project Property Pages dialog box. For more information, see [Set C++ compiler and build properties in Visual Studio](https://learn.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-170).

Select the Configuration Properties > C/C++ > Command Line property page.

In Additional Options, add the /utf-8 option to specify your preferred encoding.

Choose OK to save your changes.

**Comment by Hamusuta0320** [comment]
> > The cmake project does not have a property page option in vs.
> 
> The page is probably not being translated properly, but the instructions are there.
> 
> To set this compiler option in the Visual Studio development environment Open the project Property Pages dialog box. For more information, see [Set C++ compiler and build properties in Visual Studio](https://learn.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-170).
> 
> Select the Configuration Properties > C/C++ > Command Line property page.
> 
> In Additional Options, add the /utf-8 option to specify your preferred encoding.
> 
> Choose OK to save your changes.

In my case, when i open the property pages, it's empty page, 
![image](https://github.com/YimMenu/YimMenu/assets/55654842/c86d3bb0-f2af-4b85-8d88-13a1c16506d9)

**Comment by gir489returns** [comment]
Hmm, then try adding this to the bottom of CMakeLists.txt

add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")

**Comment by Hamusuta0320** [comment]
> add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
> add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")

I add this two line to CMakeLists.txt and rebuild the dll, but it  still crash when i inject to game.

**Comment by Hamusuta0320** [comment]
After debug, i found the function std::vformat() throw this error: "Invalid encoded character in format string", but i don't have the idea to fix this problem.

**Comment by Hamusuta0320** [comment]
> After debug, i found the function std::vformat() throw this error: "Invalid encoded character in format string", but i don't have the idea to fix this problem.

@gir489returns

**Comment by gir489returns** [comment]
> After debug, i found the function std::vformat() throw this error: "Invalid encoded character in format string", but i don't have the idea to fix this problem.

We've been trying to think what could be causing your issue, and the only thing we're for certain of is the Chinese are given a different distribution of Windows/Visual Studio/C Libraries that are PRC compliant. With this, it fundamentally changes how the functions we use behave. We loaded both Chinese translations from the project in our western builds of Windows and they all worked fine. So we're not exactly sure how we can debug this, bar going to China and buying a Chinese Windows machine to develop in so we can figure out how to cope with all these differences.

**Comment by Hamusuta0320** [comment]
> > After debug, i found the function std::vformat() throw this error: "Invalid encoded character in format string", but i don't have the idea to fix this problem.
> 
> We've been trying to think what could be causing your issue, and the only thing we're for certain of is the Chinese are given a different distribution of Windows/Visual Studio/C Libraries that are PRC compliant. With this, it fundamentally changes how the functions we use behave. We loaded both Chinese translations from the project in our western builds of Windows and they all worked fine. So we're not exactly sure how we can debug this, bar going to China and buying a Chinese Windows machine to develop in so we can figure out how to cope with all these differences.

Thank you for your patient answer. It looks like a tricky problem, and I have used other software before[ https://crazyzhang.cn/ ]The provided yimmenu.dll integrates yimmenu, and it works well, but I don't know what it does behind it.

**Comment by gir489returns** [comment]
> Thank you for your patient answer. It looks like a tricky problem, and I have used other software before[ https://crazyzhang.cn/ ]The provided yimmenu.dll integrates yimmenu, and it works well, but I don't know what it does behind it.

We generally don't support co-loading. It's caused a lot of issues. Have you tried loading Yim without this other menu?

**Comment by Yimura** [comment]
> We generally don't support co-loading. It's caused a lot of issues. Have you tried loading Yim without this other menu?

CrazyZhang was usually the one providing the Chinese translated version of YimMenu, so it was just normal YimMenu with a different font loaded to support the whole Chinese charset.

**Comment by Hamusuta0320** [comment]
> > Thank you for your patient answer. It looks like a tricky problem, and I have used other software before[ https://crazyzhang.cn/ ]The provided yimmenu.dll integrates yimmenu, and it works well, but I don't know what it does behind it.
> 
> We generally don't support co-loading. It's caused a lot of issues. Have you tried loading Yim without this other menu?

Yes, this issue occurred without loading other menus, I only injected the DLL

**Comment by Yimura** [comment]
Stale issue
