### ISSUE TITLE
[Improvement]: remove persist outfit

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1799]
### Which feature

I want to request removal of persist outfit

### Reason

players are stealing identity of original players. 
this is bcz persist outfit even persists the character modal along with dress.

**Comment by Yimura** [comment]
You want to have the persist outfit feature removed? We're not going to remove a feature that barely does any harm to the community.

**Comment by lonelybud** [comment]
steps to reproduce -
- spawn ped > online player > set player model
- outfit editor > save outfit

**Comment by lonelybud** [comment]
is the concern not valid making it easy for players just to copy characters rather than creating their own

**Comment by Yimura** [comment]
No, not really. You're just complaining about people combining steal identity with the persist outfit feature to have it permanently? If so, we're not going to remove the whole feature.

**Comment by Yimura** [comment]
Anyways we're not going to remove the feature.
