### ISSUE TITLE
ImGui is sigged!

### ISSUE THREAD

**Issue by maybegreat48** [Yimura/YimMenu#180]
**Describe the bug**
(BigBaseV2.dll) "written in the f" (16) (v2612) (PAGE_READONLY)
(version.dll) "written in the f" (16) (v2612) (PAGE_READONLY)
```c++
MetricsHelpMarker(
        "Note than the default embedded font is NOT meant to be scaled.\n\n"
        "Font are currently rendered into bitmaps at a given size at the time of building the atlas. "
        "You may oversample them to get some flexibility with scaling. "
        "You can also render at multiple sizes and select which one to use at runtime.\n\n"
        "(Glimmer of hope: the atlas system will be re  written in the future to make scaling more flexible.)");
```

**To Reproduce**
Run the sigscanner tool on any ImGui based menu

**Expected behavior**
ImGui should not be sigged (well I have to put something here)

**Logs**
N/A

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [x] I use my own version of YimMenu

**Comment by Yimura** [comment]
Oh no this day had to come lmao. Time to actively defeat the sigscanner...

**Comment by Yimura** [comment]
Also @maybegreat48 , there should be a post made about this on UC.

**Comment by maybegreat48** [comment]
Yeah I will after I perfect my bypass and make it public. Currently it only works for the epic games version

**Comment by maybegreat48** [comment]
If you have any other version of the game, can you open cheat engine and check if
`89 05 ?? ?? ?? ?? 48 8D 05 ?? ?? ?? ?? 48 6B DB 38 48 03 D8`.add(2).rip().add(0x14) (2 bytes) equals to 29? (do in singleplayer)

**Comment by Yimura** [comment]
I have all versions of the game but I can't check until this evening.

**Comment by maybegreat48** [comment]
Well if it is 29, all you have to do is set it to zero (maybe every tick?) and the anticheat may be disabled

**Comment by maybegreat48** [comment]
Potential bypass
```c++
// Some Anticheat Thing
main_batch.add("SAT", "89 05 ? ? ? ? 48 8D 05 ? ? ? ? 48 6B DB 38 48 03 D8", [this](memory::handle ptr)
{
	m_some_anticheat_thing = ptr.add(2).rip().add(0x14).as<std::uint16_t*>();
});

namespace big
{
	void looped::system_anticheat_bypass()
	{
		*g_pointers->m_some_anticheat_thing = 0;
	}
}
```

**Comment by maybegreat48** [comment]
Yeah this might actually work. Can you make a post in UC? Have to go now

**Comment by Yimura** [comment]
I've added your code to YimMenu master, although I'm not aware of what this prevents from running.

From my limited research I saw that settings this to 0 will prevent a subroutine from making a call to a loc_xxxxx and in other subroutines I could see the variable being incremented but I didn't go any more in-depth as to what happens with this variable.

I have done no testing either, currently looking at if the game runs stable without crashing out on me.

**Comment by gnchjnhkkhjk** [comment]
I was just banned, probably because of this. I'll test this bypass out and see if I get banned again and let you all know.

Edited by Yimura:
Probably not banned because of this specific detection vector.

**Comment by maybegreat48** [comment]
> I've added your code to YimMenu master, although I'm not aware of what this prevents from running.
> 
> From my limited research I saw that settings this to 0 will prevent a subroutine from making a call to a loc_xxxxx and in other subroutines I could see the variable being incremented but I didn't go any more in-depth as to what happens with this variable.
> 
> I have done no testing either, currently looking at if the game runs stable without crashing out on me.

The variable shouldn't be incremented (it should be set to 29 during a loading screen). All xrefs should lead to obfuscated/encryped junk. `48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 48 83 EC 70 48 8D 0D ? ? ? ? 33 F6 40 8A FE E8 ? ? ? ? E8 ? ? ? ? 29` set a breakpoint here, Go online solo session and wait for around a minute. If bypass works it should never be hit

**Comment by Yimura** [comment]
> The variable shouldn't be incremented (it should be set to 29 during a loading screen). All xrefs should lead to obfuscated/encryped junk. `48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 48 83 EC 70 48 8D 0D ? ? ? ? 33 F6 40 8A FE E8 ? ? ? ? E8 ? ? ? ? 29` set a breakpoint here, Go online solo session and wait for around a minute. If bypass works it should never be hit

Thanks for the explanation.

**Comment by maybegreat48** [comment]
```
(GTA5_dump_19.exe) { 5c 24 08 57 48 83 ec 20 81 f9 6d 9f } (12) (v2612) (PAGE_EXECUTE_READWRITE)
(GTA5_dump_19.exe) { 48 8b c4 48 81 ec b8 00 00 00 0f 29 70 e8 f3 } (15) (v2612) (PAGE_EXECUTE_READWRITE)
(GTA5_dump_19.exe) { c7 81 fc 3a 00 00 ff ff } (8) (v2612) (PAGE_EXECUTE_READWRITE)
(GTA5_dump_19.exe) { 53 48 83 ec 20 80 79 6b 00 48 8b d9 74 1a c6 } (15) (v2612) (PAGE_EXECUTE_READWRITE)
(GTA5_dump_19.exe) { b9 00 10 04 00 8d 82 ff ff 01 00 25 00 00 fe ff 05 00 10 00 00 3b c1 } (23) (v2612) (PAGE_EXECUTE_READWRITE)
```
....hmm interesting
So rockstar is obviously trying to do something. Perhaps they are checking if their sigscanner is working?
`5c 24 08 57 48 83 ec 20 81 f9 6d 9f` is is_dlc_present

**Comment by Yimura** [comment]
lmao

wait are you telling me they also scan GTA5.exe?

**Comment by maybegreat48** [comment]
Yes they scan everything. I think this is all intentional at this point
They may be using this as a heartbeat system. Perhaps disabling everything is not a really good idea

So let's take a look at the bigger picture:
Anything based on Nano and BigBaseV1 is detected (as they hook is_dlc_present so they don't send the full heartbeat and also is_dlc_present is in the impl table so that will be detected anyway)
Anything based on BigBaseV2 is detected (because ImGui)
Anything that stops anticheat is detected (because they don't send the sigscan heartbeat) that includes YimMenu, my menu, and basically all p2cs
And I am not mentioning all the little things they detect (like spamming script events for example) 
They must be doing all this to prepare for the "enhanced" edition for PC

**Comment by Yimura** [comment]
Ye was thinking this as well because this way they can filter on the people who don't intentionally trigger the signatures inside of GTA5.exe and those who trigger the obvious ImGui signatures are fucked as well.

Now I wonder if it's best to just remove all strings from ImGui, keep the signature scanner enabled as well to send out the sigscanner heartbeat to R*'s servers. Unless we can forge/fake the sig scanner results being sent to R*.

**Comment by Yimura** [comment]
Anyways, I'm gonna make a fork of ImGui, remove all strings or at least remove the detected strings, remove unused files, etc...

**Comment by Yimura** [comment]
In the following PR, I've made some changes to address the above concerns.

https://github.com/Yimura/YimMenu/pull/203

**Comment by maybegreat48** [comment]
So after research by jonaaa in the UC thread, you only get detected if the readonly region size of the menu is around a certain range. I checked the actual scan function again and I can confirm that there is a region size check in it. Removing the strings is still a safe thing however

**Comment by maybegreat48** [comment]
Issue needs to be reopened. Two crossmap entries are now detected

**Comment by Adler-D3R** [comment]
The detected crossmap are :
```{ 0x83666F9FB8FEBD4B, 0x83666F9FB8FEBD4B },``` and ```{ 0x953563CE563143AF, 0x425AEAA424677E5F },```
Thanks to Bugisoft and the boiz for their help.

**Comment by maybegreat48** [comment]
Thankfully both of the natives are mostly useless. Removing everything they sig might not be a good solution to this problem however

**Comment by Adler-D3R** [comment]
As long as the native they sig are useless, it's fine. in case that's an useful one, we will have to maybe directly use the memory.

**Comment by Yimura** [comment]
Please make a new issue as this is not related to ImGui being sigged.
