### ISSUE TITLE
[Bug]: Exception Error Thrown After Blocking Join.

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1800]
### Describe the bug

An exception error was thrown and my game froze after blocking a popular modder/sound spam bot from entering my lobby.

### Steps To Reproduce

1. Block Join
2. Maybe Observe the exception being thrown

### Expected Behavior

Not for game to throw exception and freeze.

### Logs and/or screenshots

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/12136452/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
this is a duplicate of #1666 sometimes it can just freeze my game too but most of the time i just crash and sometimes even no logs.

**Comment by Yimura** [comment]
Duplicate of #1666
