### ISSUE TITLE
[Improvement]: Logs

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1810]
### Which feature

The Log's
Instead of Spamming :
[WARN/notify.hpp:29] Blocked infinite ped attachment crash from Player (ID)
[WARN/notify.hpp:29] Blocked infinite ped attachment crash from Player (ID)
[WARN/notify.hpp:29] Blocked infinite ped attachment crash from Player (ID)
Do : 
[WARN/notify.hpp:29] Blocked infinite ped attachment crash from Player (ID)
[+] 2 Times 
And If the player doesn't do anything to you in 5 minutes or so it stop's the counter

### Reason

Less Bloated Logs?

### Additional context

The Reason might be stupid but the idea is cool to me

**Comment by Yimura** [comment]
From a logging stand point this is not really possible, rather it would be difficult to implement as it might interfere with other subsequent logs that come through.

Logging is really just meant to be logging of events at the point they occurred at in time. In UI we could do it though, add some sort of counter to the notification every time the same one is pushed to the queue.

**Comment by Yimura** [comment]
Infinite ped attachment crash detection has been improved, should be less of an issue now.
