### ISSUE TITLE
[Request]: Auto go to Anti-Crash Cam when Entity Spamming is Detected.

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1811]
### Problem

No, it would just be nice not to crash when this happens.

### Solution

An option that would detect if there was entity spamming, and would send you to a camera very high in the air to avoid crashing.

### Reason

Stand has it and it is a good feature.

**Comment by Yimura** [comment]
I think we have implemented some protections against entity spam crashing in the recent PR (#1803) from maybegreat.

**Comment by Rxann** [comment]
> I think we have implemented some protections against entity spam crashing in the recent PR (#1803) from maybegreat.

Ah yes, i do see there were detour hooks added for rendering entities, peds, and vehicles. You can close this if you would like
