### ISSUE TITLE
[Improvement]: maybe suggest some injector

### ISSUE THREAD

**Issue by vincyxiroff** [Yimura/YimMenu#1818]
### Reason

uk so we can run easly without being rat

**Comment by xiaoxiao921** [comment]
https://github.com/DarthTon/Xenos/releases/tag/2.3.2

**Comment by gir489returns** [comment]
I also use Xenos in Native mode.

**Comment by Rxann** [comment]
I use xenos also with default options

**Comment by howdoiusekeyboard** [comment]
<img width="452" alt="image" src="https://github.com/YimMenu/YimMenu/assets/90883505/0405ffe6-b9dd-4d0c-8d1a-ba1be08343d8">
Are these the best settings?

**Comment by Yimura** [comment]
That should work yeah, are you experiencing any issues with those settings?

**Comment by howdoiusekeyboard** [comment]
No issues in injection, just asked out of curiousity as I am not familiar with most settings that were there. So just asked if there were room for improvements

**Comment by idk-pixel** [comment]
@howdoiusekeyboard I have a yim manager that i made it has injection , updater, downloader, script installer. Dm me @whoaboutyt_real if u want heres the VA res: https://www.virustotal.com/gui/file/4f74aedf5a7b63f66c209ba2188f25cac1fe55dfb55f225d01a029f772458ca8/detection

**Comment by Yimura** [comment]
Not really an issue with YimMenu.
