### ISSUE TITLE
[Bug]: Fun feature vehicle rainbow fade option is not working

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1819]
### Describe the bug

Spasm option is working but fade is not.
![image](https://github.com/YimMenu/YimMenu/assets/139460769/73aea322-29d4-4f41-a994-6eb7365c6ef0)

Second
There is an option for rainbow under Settings Tab. It does not work when i am in vehicle first of all. Whats the purpose?
![image](https://github.com/YimMenu/YimMenu/assets/139460769/9bf573d8-c285-4681-bce4-a1c02d4dbf37)

### Steps To Reproduce

Mentioned in images

### Expected Behavior

Should worked as before.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by dynamoNg** [comment]
why its closed @Yimura ? how to fix it? disable -> keep vehicle repaired ?

**Comment by Yimura** [comment]
No need to @ me, I'll see the comment either way. And please refrain from doing that to any of the other contributors.

This issue has been fixed on master, wait for the next nightly update to have it or download it from the build artifacts of master.

**Comment by lonelybud** [comment]
thanks. I just saw my bad. The commit was added. Noted your point related to mentioning.
