### ISSUE TITLE
[Improvement]: desync protection

### ISSUE THREAD

**Issue by alyxme** [Yimura/YimMenu#1829]
### Which feature

With all protection enabled we can't defend against desync kick yet and anyone can desync anybody for now. So we should have desync protection.

### Reason

Because YimMenu is focusing on protecting the user from toxic modders.

### Additional context

This script is pretend to be the solution [desync_protecc.zip](https://github.com/YimMenu/YimMenu/files/12141896/desync_protecc.zip) 
Also if we made this protection we loose the ability for everyone to remove someones (with YimMenu) who tried to mess and only Host will able to do the kick.

**Comment by maybegreat48** [comment]
Does this actually work? Have you tried it? This isn't even a lua script

**Comment by gir489returns** [comment]
> Does this actually work? Have you tried it? This isn't even a lua script

This looks like something from the stolen GTA V source code, passed off to look like it stops desync.

**Comment by maybegreat48** [comment]
Nope. that's our old protection (like a year old) which probably never worked

**Comment by Yimura** [comment]
All it did back then was just attack the person trying to desync us back with complaints, no? Nothing convoluted.

Or did it actually just reset the complaint counter? Don't remember too well.

**Comment by alyxme** [comment]
> Does this actually work? Have you tried it? This isn't even a lua script

I found this in [Kid*s Discord #lua-scripts channel ](https://discord.com/channels/872637249081180222/935720668270579763/1125768131437137971) and it didn't work. I tho this is for previous versions.

**Comment by SkiddyToast** [comment]
> I found this in [Kid*s Discord #lua-scripts channel ](https://discord.com/channels/872637249081180222/935720668270579763/1125768131437137971) and it didn't work. I tho this is for previous versions.

It’s my old desync kick protection from [here](https://www.unknowncheats.me/forum/grand-theft-auto-v/500013-desync-kick-protection.html), and it’s in C++.

**Comment by alyxme** [comment]
So the spiral unwinds another loop

**Comment by Yimura** [comment]
Currently no known protection that I know of.
