### ISSUE TITLE
Restore handling does not restore vehicle gravity

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#183]
**Describe the bug**
Restore handling does not restore vehicle gravity

**To Reproduce**
1. Increase vehicle gravity
2. Click restore handling
3. Watch as nothing happens

**Expected behavior**
Vehicle gravity resets to default value

**Screenshots**
N/A

**Logs**
N/A

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
N/A

**Comment by Yimura** [comment]
You are correct, since gravity isn't tied to the CHandlingData but to the entity.

**Comment by cl52902** [comment]
Regardless you should have the button reset all of the values for the car. Users don't know this difference, and nobody is memorizing the number on that slider before they change it.

**Comment by Yimura** [comment]
Yes you are correct, I just hadn't gotten around to fixing this.

**Comment by karifeld** [comment]
Sorry for the sudden inquiry, but where is the vehicle handling data and its backup being saved?
I would love to solve this issue if i only i knew where they are, Thanks in advance.

**Comment by xM4ddy** [comment]
> Sorry for the sudden inquiry, but where is the vehicle handling data and its backup being saved? I would love to solve this issue if i only i knew where they are, Thanks in advance.

`win + r` then paste  `%APPDATA%/BigBaseV2/lib` the json file gets downloaded from `http://github-proxy.damon.sh/DurtyFree/gta-v-data-dumps/master/vehicles.json` in `src/services/vehicle_preveiw_service.cpp` if you want to see it on github just go here `https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/vehicles.json`

**Comment by xM4ddy** [comment]
To be honest we would probably be looking for a plan that fixed this and as well as #214 at the same time.

**Comment by Yimura** [comment]
CHandlingData is what you should look for, it's in the vehicle_service.
Arguably the vehicle service should be redone...

**Comment by Yimura** [comment]
This has been fixed in #510
