### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#1832]
### Describe the bug

Where am I supposed to place the animations json file. The notif says to place it in the mod folder but that isn't coherent. I have downloaded the file from https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/animDictsCompact.json and tried to place it everywhere but I keep getting the same error

### Steps To Reproduce

.

### Expected Behavior

..

### Logs and/or screenshots

```
<paste your logs here>
```
![image](https://github.com/YimMenu/YimMenu/assets/90883505/f7e7002d-2935-438c-8fab-c5edf076ad19)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by alyxme** [comment]
Put it in the yimmenu directory from the shortcut link provided with source

**Comment by howdoiusekeyboard** [comment]
Thats exactly where its at right now

**Comment by alyxme** [comment]
For me it works great. Maybe something on your side. Did your local username contain Spaces or diff codepage name? Also dict file shouldn't be renamed. Also check ntfs access permission.

**Comment by howdoiusekeyboard** [comment]
<img width="594" alt="image" src="https://github.com/YimMenu/YimMenu/assets/90883505/10190f91-9105-4dcc-a74a-6780f8a64c5e">

No spaces in local username, I am signed in Admin user, also no diff codepage name

**Comment by Yimura** [comment]
Well there's you issue, the filename is incorrect. As @alyxme said, make sure it's called the same as the actual file on Github `animDictsCompact.json`.

This is the filename the code looks for:
https://github.com/YimMenu/YimMenu/blob/16e8e571f04b6d9d94f9be8c0d1823dc1088ae31/src/util/animations.hpp#L58

**Comment by howdoiusekeyboard** [comment]
O.O tysm

**Comment by Yimura** [comment]
Is there still issue that you're reopening the issue?

**Comment by howdoiusekeyboard** [comment]
No, misclick
