### ISSUE TITLE
[Bug]: squad weapons bug

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1833]
### Describe the bug

When I want to change the weapon to any other one in the saved template (an example of a flare gun in the screenshot), the squads still continue to shoot from the plane with an uzi. The same situation, for example, if I spawn a squad on a motorcycle with a small hand grenade launcher, then he still has an uzi. I have not tried other weapons, but I think the situation will be the same. Settings below (maybe I did something wrong)
![pic](https://github.com/YimMenu/YimMenu/assets/139077095/bd224742-5710-489c-81c5-37e81556a994)

### Steps To Reproduce

1. Create a squad in luxor and give him a flare gun
2. Watch him shoot you or someone else with an uzi

### Expected Behavior

Squads must fire their flare pistol. And even when you've already been killed once

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by MickyMous999** [comment]
i agree!
