### ISSUE TITLE
[Request]: Modify Vehicle speed

### ISSUE THREAD

**Issue by Bradly7412** [Yimura/YimMenu#1835]
### Problem

Unable to figure out (this could just be me not sure) how to mod the speed

### Solution

Not sure if it is possible to do it vary easily but i am wanting to be able to open a lua script and mod my car speed with a checkbox.

### Reason

Possible docs on the native script side as i saw bits of it but unsure of how to use

**Comment by Harmless05** [comment]
Vehicle handling?

**Comment by Bradly7412** [comment]
Yes but controlled with lua files

**Comment by Yimura** [comment]
Have you looked at this native? https://natives.gta.menu/natives/0xAB54A438726D25D5

(Below is C++ syntax and not Lua syntax)
```cpp
VEHICLE::SET_VEHICLE_FORWARD_SPEED(vehicle, speed);
```

**Comment by Harmless05** [comment]
SET_VEHICLE_MAX_SPEED This could also work, no?

Ah nvm this is just to remove/set the max speed higher

**Comment by Bradly7412** [comment]
Ok so my other question is how would one start to use this in lua? (Not exactly fluent. i just prefer to learn from examples)

**Comment by Yimura** [comment]
```lua
local vehicle = PED.GET_VEHICLE_PED_IS_IN(PLAYER.PLAYER_PED_ID(), true)

local speed = 200.0

VEHICLE.SET_VEHICLE_FORWARD_SPEED(vehicle, speed)

VEHICLE.SET_VEHICLE_MAX_SPEED(vehicle, speed)
```

**Comment by Bradly7412** [comment]
So if i wanted to grab the current vehicle that the person is currently in how would one set the vehicle for that?

**Comment by Yimura** [comment]
I updated the comment to include the grabbing of the vehicle.

**Comment by Bradly7412** [comment]
so if i wanted to change the acceleration? or some of the other handling options

**Comment by Yimura** [comment]
It's possible from Lua however at that point you're better off switching to C++ to do it as you'll have to work with raw memory offsets.
