### ISSUE TITLE
[Bug]: ip addresses say unknown

### ISSUE THREAD

**Issue by xenical1212** [Yimura/YimMenu#1836]
### Describe the bug

ipaddresses say unknown

### Steps To Reproduce

click on player look at ip 

### Expected Behavior

see ip

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Go to Settings -> Protections -> Force Relay Connections and disable it. You'll be able to see other people's IP addresses again but they'll be able to see your IP address as well.

**Comment by ChaT0n** [comment]
I don't know if it is related but i've tested it 3 times with a friend :
When I activate the modmenu, my friend gets huge rolbacks in the game. The way we tested it is the following:
I drive and he is int he car with me
We make many rounds whithout Yim
I launch Yimmenu , and there while driving the rollbacks start

I've tested with an older version (10-12 days ago) and the rollbacks are inexistant

**Comment by Yimura** [comment]
Have you considered disabling the Force Relay Connections option?

**Comment by ChaT0n** [comment]
will try later and give u a feedback

**Comment by ChaT0n** [comment]
Disabling the Force Relay Connections seems to solve the options : I still had like a couple of rollbacks (maybe till the session stabilize after deactivating the force relay), but I would say that it totally dissapeared
