### ISSUE TITLE
Run & use weapons in restricted areas

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#184]
**Is your feature request related to a problem? Please describe.**
No, it's a request for a standalone feature.

**Describe the solution you'd like**
The player should be able to run around and use their weapons in places like the casino and other restricted areas.

**Provide Reasoning**
Why can't I run in the casino in the first place, Rockstar????

**Additional context**
N/A

**Comment by Yimura** [comment]
Yep definitely something that needs to add.
