### ISSUE TITLE
[Bug]: Copy session info doesn't work

### ISSUE THREAD

**Issue by dioxen88** [Yimura/YimMenu#1846]
### Describe the bug

Copy session info doesn't work

### Steps To Reproduce

Go to "Network" > press Copy Session Info. Nothing happens

### Expected Behavior

Copy and paste information

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I can't replicate this behavior. I clicked the button and my copy buffer was filled with the session information I was currently in. Try pressing CTRL+V into Notepad++ after you've clicked the button.

**Comment by dioxen88** [comment]
> I can't replicate this behavior. I clicked the button and my copy buffer was filled with the session information I was currently in. Try pressing CTRL+V into Notepad++ after you've clicked the button.

I tried several times to insert it into the notepad and into the join session info field (the buttons work, other information is inserted). I wonder if it just doesn't work for me or not

https://i.imgur.com/8esdZqy.gif

**Comment by Londiuh** [comment]
I can replicate this in GNU/Linux running the game under Proton. Other copy to clipboard buttons are working fine, only copy session info isn't working.

**Comment by Yimura** [comment]
As others have commented, I can replicate the same on my system. Kinda odd how it worked for @gir489returns.
