### ISSUE TITLE
[Bug]: player gets kicked out of spawned vehicle after unloading yimmenu (single player mod)

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1856]
### Describe the bug

- Play single player (dont go online)
- inject yimmenu
- spawn b-11 strikeforce as new vehicle (with spawn inside checked)
- sit inside the vehicle
- come out of it
- unload yimmenu
- try to enter vehicle

result -> after sitting player gets kicked out.

### Steps To Reproduce

described above

### Expected Behavior

should not kicked out of spawned vehicle

### Store

Epic Games

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/139460769/7ca3586b-c140-48fc-8e3d-39f9d9f4591a)
![image](https://github.com/YimMenu/YimMenu/assets/139460769/771ff2ff-b819-4a3a-a7ce-ab56ecb85830)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
This is normal and cannot be fixed, the game has checks for multiplayer only vehicles and uninjecting yimmenu will re-enable those checks (this is intended due to restoring the game data to a clean state upon unloading)
