### ISSUE TITLE
[Improvement]: Lua add_input

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#1857]
### Which feature

To improve Luas, add_input_int and add_input_float. 

- maximum value
- minimum value
- start/default value
- step size  (how much should each +- press increase/lower the value)

This could look like something like this:
test:add_input_int("Visible name", default value, min, max, step)

### Reason

So we could have better control over Lua and the menu

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/ImGui.md#widgets-input-with-keyboard
