### ISSUE TITLE
[Bug]: Cache not loading

### ISSUE THREAD

**Issue by InvalidJoker** [Yimura/YimMenu#1858]
### Describe the bug

When I press "Rebuild cache," nothing happens, and when I started YimMenu for the first time, it said it couldn't open the files.

### Steps To Reproduce

1. Go to Settings
2. Go to GTA Cache
3. Click Rebuild Cache

### Expected Behavior

My Vehicles would be shown

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
https://nightly.link/YimMenu/YimMenu/actions/artifacts/826380980.zip

can you try the YimMenu dll inside that .zip ? 

it probably won't fix the problem but it should give us more info on why it is failing, thanks

once you ran it if you can post your %appdata%/YimMenu/cout.log file here i would appreciate it

**Comment by InvalidJoker** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/12181945/cout.log)

**Comment by InvalidJoker** [comment]
?

**Comment by Yimura** [comment]
This might take some time to get fixed as the problem doesn't lie directly with YimMenu, rather it has in some part something to do with it.
The problems comes from a function within the game that fails and investigating that one on why it is failing may take a while.

**Comment by mmjjDev** [comment]
I found a temporary fix which is very easy to perform, the only thing you have to do is to ask someone to give you their updated cache files and just swap your files with the new ones, hope it helps :)

**Comment by InvalidJoker** [comment]
can you give me your cache files?

**Comment by mmjjDev** [comment]
[cache.zip](https://github.com/YimMenu/YimMenu/files/12214658/cache.zip)
Here you go

**Comment by InvalidJoker** [comment]
ty

**Comment by Yimura** [comment]
Stale issue, closing.
