### ISSUE TITLE
🔁 Multiple Ideas 🔁

### ISSUE THREAD

**Issue by N0TAD3V** [Yimura/YimMenu#186]
**🔁 WILL BE EDITING / UPDATING THIS ISSUE OVERTIME 🔁**

### 
       [Self]
             ↳ [Animations]
###

_↑ e.g. : Add a list, and/or "Play by name" + "Save & Load / Favorite" buttons. ↑_

###
       [Vehicle]
                ↳ [Paint]
                         ↳ [Select RGB]
                ↳ [???]                
                       ↳ [Custom Plate] 
###

_↑ The current mobile LS Customs feature only allows for use on owned/unowned vehicles, this will be helpful to give other people custom colors and plates. ↑_

###
       [Players]
                ↳ [Misc]
                        ↳ [Gift Vehicle]
###

_↑ See this issue, someone posted a code already: https://github.com/Yimura/YimMenu/issues/169 ↑_

###
       [Settings]
                 ↳ [Debug]
                          ↳ [Save / Load Script Events]

_↑ Easier to use kicks ect, instead of having to paste them everytime. ↑_
###

**Comment by Yimura** [comment]
Sorry bro, not how issues work.
Issues are supposed to be separated into features, not one issue for a dozen of features.

I can see you put some work into making this issue look nice but just don't. We can't keep track of what has been added and what not if you put multiple feature requests into one issue.

Take a look at the following issue it has been open for a long time and contains multiple requests #16 .

So I won't be accepting your issue sorry, unless you modify it.

**Comment by Yimura** [comment]
No worries, just keep this issue as-is.

Make a new one and follow the template, it's the help you and us to better implement features.
So as I said, in this post you described several different features, you could then split them up like so:
- Add gift vehicle
- Allow loading premade script events to send under debug
- Add possebility to modify number plate
- etc...
