### ISSUE TITLE
[Bug]: Car dont drive

### ISSUE THREAD

**Issue by vcMoo** [Yimura/YimMenu#1868]
### Describe the bug

If you spawn a car in then put saved profile on the car in handling and spawn another car in u will be unable to drive the car until u reset the handling and spawn a new car in

### Steps To Reproduce

vehicle > handling 
change a couple of things and create a new profile 
then spawn a new car in & put the custom profile on that vehicle and then spawn a new car in & u wont be able to move

### Expected Behavior

should be able to move still when u spawn a new car in

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by V1RU513N** [comment]
Works well for me. 
I just can't reproduce it. Maybe you set the wrong value (For example, if the value of "Initial Drive Gears" is too high, the vehicle will not move)

**Comment by Yimura** [comment]
Well you probably fucked some of the handling settings up of the vehicle and cause it to not drive properly.
