### ISSUE TITLE
[Request]: Improve Development

### ISSUE THREAD

**Issue by idk-pixel** [Yimura/YimMenu#1873]
### Problem

Theres locals and globals but not stats so we can't develop things like a Doomsday Heist feature due to this.

### Solution

Make more methods in the API document for stats if you have it. If you don't then make it please

### Reason

Improves development for 3rd-party features

**Comment by idk-pixel** [comment]
Additional Context: stats.get_int(), etc

**Comment by Yimura** [comment]
You are aware of natives existing right?

https://natives.gta.menu/natives/0xB3271D7AB655B441

**Comment by idk-pixel** [comment]
> You are aware of natives existing right?
> 
> https://natives.gta.menu/natives/0xB3271D7AB655B441

Yes, I didn't see anything in the documentation about using them though.

**Comment by Yimura** [comment]
Here's a Lua script that makes use of them:
https://github.com/YimMenu-Lua/Casino-Pacino/blob/13554089a0e8729fe7ddecaf12f7188900baac00/CasinoPacino.lua#L60-L62

**Comment by Yimura** [comment]
Has been implemented with #1875
