### ISSUE TITLE
Colours 

### ISSUE THREAD

**Issue by Dennuz070** [Yimura/YimMenu#1874]
:Minor: There is a problem with picking a colour in Yimmenu .. in the section Headlight there is backlight instead of blacklight.. and in the neon section there is no option to choose blacklight at all.. please solve this ... thanks in advance.. 👍

**Comment by Yimura** [comment]
Please follow the issue template next time, it helps us keep track of the type of issue you're trying to report.

**Comment by Dennuz070** [comment]
Sorry.. new to this.. but i will ..next time.. 🫣
Could you tell me in wich section of issue i have to set it.. ?

**Comment by Dennuz070** [comment]
Did it right this time ..:)
