### ISSUE TITLE
💡 [Vehicle Customization: Custom Color & Plate]

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#188]
**Is your feature request related to a problem? Please describe.**
👎

**Describe the solution you'd like**

   [Vehicle]
            ↳ [Paint], [Select RGB]
            ↳ [Extras], [Custom Plate] 

**Provide Reasoning**

The current mobile LS Customs feature only allows for use on owned vehicles, this will be helpful to give other people custom colors and plates.

**Additional context**

👎

**Comment by aa15032261** [comment]
I believe this is implemented.

**Comment by Yimura** [comment]
You're correct, closing this.
