### ISSUE TITLE
[Bug]: FPS counter shows 1000fps while loading GTAV, but it's capped to 60fps

### ISSUE THREAD

**Issue by tim-gromeyer** [Yimura/YimMenu#1886]
### Describe the bug

When loading GTAV, the FPS counter shows over 1000 fps, but the game is capped to 60 fps. MangoHUD shows 60 fps.

In game, the fps counter shows the correct number, just not in the loading screen

### Steps To Reproduce

1. Open GTAV
2. Inject the menu
3. See over 1000 fps

### Expected Behavior

It should show 60 fps, as it doesn when the game (story/online) is loaded

### Store

Rockstar

### Additional context

I'm running the game on Linux. I installed it via the Rockstar Games Launcher and added it to steam as a non-steam game.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Stating the comment left behind of the author of ImGui in the library:
> Rough estimate of application framerate, in frame per second. Solely for convenience. Rolling average estimation based on io.DeltaTime over 120 frames.

For some reason the game calls the IDXGISwapchain::Present function a lot during loading screens, perhaps they do some calculations at that point that don't rely on any game physics and want to make sure the game loads as fast as possible.

I don't think we can just cap the UI update rate as it may cause issues like flickering.

**Comment by tim-gromeyer** [comment]
Okay, it not that big of a deal. I just wanted to report this issue

**Comment by Yimura** [comment]
Doesn't seem like something quite necessary to fix.
