### ISSUE TITLE
[Improvement]: Add session switcher command to lua

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1888]
### Which feature

I think it should be a command with a numeric argument like 1 is JOIN_PUBLIC, 2 is NEW_PUBLIC and so on.

### Reason

Such a thing will be much more convenient than using globals, although I did not succeed with them :(

**Comment by Tayipc38** [comment]
Just because you couldnt succeed does not mean its not possible.

**Comment by ghost** [comment]
> Just because you couldnt succeed does not mean its not possible.

Maybe someone has a really working lua?
