### ISSUE TITLE
[Improvement]: gui 

### ISSUE THREAD

**Issue by Woosh9129** [Yimura/YimMenu#1889]
### Which feature

the entire gui

### Reason

you should do this because it takes a lil bit of a long time to navigate the menu like this, and the other menu's have it .
you can replace the dropdown with an integer range maybe

**Comment by Yimura** [comment]
What? This is quite a poorly written issue to improve the UI. Rewriting the UI requires planning and discussions beforehand.

In the current lifecycle of YimMenu, it's unlikely we'll make any large changes to the UI.
For now, I'll be closing this issue until the time comes for a rewrite.

And if you do want to see changes, open up a discussion and make sure to be detailed on what you want, how you want it, and how it should look, possibly with some example imagery.
