### ISSUE TITLE
different kiddion functions

### ISSUE THREAD

**Issue by matarife123** [Yimura/YimMenu#1891]
### Which feature

Could you add some functions like kiddion?
For example:
fast charge
win in casino machines
win car the roulette
![Captura de pantalla (64)](https://github.com/YimMenu/YimMenu/assets/110930030/bb13ac81-edc3-4644-ad76-535087e5ff5c)
![Captura de pantalla (65)](https://github.com/YimMenu/YimMenu/assets/110930030/e4009680-a5ce-43b5-9969-0a7f8f125c91)

### Reason

It is very useful

**Comment by Yimura** [comment]
This has already been implemented into a Lua for YimMenu, see: https://github.com/YimMenu-Lua/Casino-Pacino

**Comment by Yimura** [comment]
Recovery features will not be added directly to YimMenu.
