### ISSUE TITLE
[Request]: faster start of new session find / creation through network->session switcher

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#1892]
### Problem

being enough high in the air (z=751) skips the jumps in air when loading a new session.

### Solution

Inside views\network\view_network.cpp

```
// ...

for (const auto& session_type : sessions)
{
components::selectable(session_type.name, false, [&session_type] {
	+ Vector3 pos = ENTITY::GET_ENTITY_COORDS(self::ped, false);
	+ PED::SET_PED_COORDS_KEEP_VEHICLE(self::ped, pos.x, pos.y, 751.f);
	session::join_type(session_type.id);
});
}

// ...
```

OR inside util\session.hpp

```
// ...

inline bool join_type(eSessionType session)
{
   + Vector3 pos = ENTITY::GET_ENTITY_COORDS(self::ped, false);
   + PED::SET_PED_COORDS_KEEP_VEHICLE(self::ped, pos.x, pos.y, 751.f);

   SCRIPT::REQUEST_SCRIPT_WITH_NAME_HASH(RAGE_JOAAT("pausemenu_multiplayer"));

   while (!SCRIPT::HAS_SCRIPT_WITH_NAME_HASH_LOADED(RAGE_JOAAT("pausemenu_multiplayer")))

//...
}
```

### Reason

saves about 1 second but it's a neat feature to have ig?

### Additional context

i dont know how to "commit changes" straight to repo to be accepted, if its even possible. is commit a good word? idk not a github pro ;d

**Comment by ghost** [comment]
Just [fork](https://github.com/YimMenu/YimMenu/fork) the repository and commit changes yourself and then just hit the pull request button
