### ISSUE TITLE
[Improvement]: Mission Controller Heist

### ISSUE THREAD

**Issue by xd3ds3c** [Yimura/YimMenu#1895]
### Which feature

title = "Heist Instant"
t = "fm_mission_controller"
p = "fm_mission_controller_2020"
ult = gui.get_tab(title)
gui.show_error(title .. "\nPorted by: Testing")

ult:add_text("Testing Script For Heist")
checkbox = ult:add_checkbox("Enable")
network.force_script_host("Heist_Instant", function(script)
    script:yield()
	if script("fm_mission_controller"):is_active() then
		if  script("fm_mission_controller"):get_bool(3228) then
			script("fm_mission_controller"):set_int(31656, joaat("Alice2333"))
			script("fm_mission_controller"):set_int(19710, 12)
		end
	end
	if script("fm_mission_controller_2020"):is_active() then
		if  script("fm_mission_controller_2020"):get_bool(18627) then
			script("fm_mission_controller_2020"):set_int(46829, joaat("Alice2333"))
			script("fm_mission_controller_2020"):set_int(45450, 9)
		end
	end
end)

### Reason

Can anyone make it work?
Since YimMenu has script host strength
Thanks in advance

**Comment by Yimura** [comment]
Not a YimMenu issue, if you want to receive help around Lua scripts consider making a discussion perhaps.
