### ISSUE TITLE
Spoofing not working, not visible to myself

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#19]
Am I the only one or is the spoofing not working? The Player info popup should give you the right spoofed info, right?

The name isn't changed too in the ingame list

**Comment by Yimura** [comment]
Yes it works but it isn't visible for yourself, only others can see what's spoofed.

Ref: https://www.unknowncheats.me/forum/3326297-post102.html

**Comment by MoneyDropLobby** [comment]
Alright, but the the thing is that the message `LOG(INFO) << "HOOKS | Sending spoofed values to lobby.";` won't execute?

**Comment by Yimura** [comment]
Game version?
Anything in the logs that it hasn't found the signature?
For me it 100% worked on Steam and appeared to be working on Epic games edition of the game.

**Comment by MoneyDropLobby** [comment]
I am using the official rockstar launcher, and it doesn't log anything in the log file... 

It found the sig `[19:03:14] [INFO]   [pattern_batch.cpp:23]    Found 'SNITL' GTA5.exe+0x13CC814`
and it enables it too `[19:03:15] [INFO]   [detour_hook.cpp:40]      Enabled hook 'SNITL'.`

I updated the classes too actually..

**Comment by Yimura** [comment]
> I am using the official rockstar launcher, and it doesn't log anything in the log file...
> 
> It found the sig `[19:03:14] [INFO] [pattern_batch.cpp:23] Found 'SNITL' GTA5.exe+0x13CC814` and it enables it too `[19:03:15] [INFO] [detour_hook.cpp:40] Enabled hook 'SNITL'.`
> 
> I updated the classes too actually..

Could you tell me at which point you injected the menu? The spoofing of data only works when switching lobbies. Not when you're already in a lobby, it won't spoof at that point.

**Comment by MoneyDropLobby** [comment]
I inject the menu on startup before I can select story, online mode.... And yeah I know I have to change the lobby

**Comment by Yimura** [comment]
I'm not sure what you're doing wrong but I've confirmed for this feature to be working on Social Club version.
