### ISSUE TITLE
[Bug]: multiple actions bound to single hotkey doesn't work

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#1906]
### Describe the bug

i would like to have 'Fill Snacks', 'Repair PV' and 'Fill Ammo' bound to one key and if i do it, none of these actions work

### Steps To Reproduce

1. hotkeys -> set >=2 actions to one keybind
2. try to press the keybind

### Expected Behavior

run all of them

### Logs and/or screenshots

none

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by NjuuOwO** [comment]
Having all those three bound to one key, only the highest that shows in "Hotkeys" window (which is Fill Snacks) work

**Comment by alyxme** [comment]
I confirm that bug exists for me too with latest build.
