### ISSUE TITLE
[Bug]: CEO/MC [ORGANIZATION] chat is visible for all users

### ISSUE THREAD

**Issue by alyxme** [Yimura/YimMenu#1910]
### Describe the bug

CEO/MC [ORGANIZATION] / [TEAM] chat is visible for all users. Several players reported that they can see my chat as their Private chat. I did some experiments with removing any LUA and reloading then to disable em all but they still could see that.

### Steps To Reproduce

1. Have a friend online
2. Type in Team chat while your friend is not a member of your CEO/MC
3. So friend should see all your chat secrets

### Expected Behavior

Expected to stay private with CEO/MC chat

### Store

Rockstar

### Additional context

After additional testing Im confirm: with Yim youre unwillingly share private chat over all lobby players.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
@maybegreat48

**Comment by maybegreat48** [comment]
What happens if you don't have YimMenu loaded?

**Comment by alyxme** [comment]
Just tested. With clean load without injection no one can see team chat. So that is Yim "feature". Another friend with other non stand menu told he can also see only mine team chat and no one else's.

**Comment by alyxme** [comment]
upd I think everyone can see team chat with Yim. Not only who have menus

**Comment by pierrelasse** [comment]
Maybe try to disable this fast chat or instant chat messages feature

**Comment by CypherMorgan** [comment]
Some of the messages we type in chat also disappears for normal users, For example: "wanna go drift?" this wont be visible to normal player cuz I used a "?". I'm not sure if it comes under same issue but its related to chat so I just described it here. . .

**Comment by alyxme** [comment]
Thanks @maybegreat48
