### ISSUE TITLE
[Request]: make paint done by paint gun visible to other players

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#1911]
### Problem

other players cant see our painting

weapons -> custom weapons -> paint gun

### Solution

not yet found

### Reason

finding it useless somewhat if we cant show to others.

btw can only take pictures with painting done on walls etc as background.

**Comment by lonelybud** [comment]
@TheGreenBandit whats your thought?

**Comment by TheGreenBandit** [comment]
To fix not being able to draw everywhere light natives could probably be used but still no idea about networking it

**Comment by Yimura** [comment]
I don't think there's a native to do that currently neither am I aware of a network event that transfers such data to other players.

We can reopen if someone has information making this networked.
