### ISSUE TITLE
[Request]: add boost auto-recharge and inifite boost

### ISSUE THREAD

**Issue by Gasferr** [Yimura/YimMenu#1913]
### Problem

they would have to implement this option in the vehicle section

### Solution

It is an option that is needed since it is useful for the oppressor among other vehicles

### Reason

It seems to me an option that needs to be added and would be useful

### Additional context

![Sin título](https://github.com/YimMenu/YimMenu/assets/34402763/94576812-5ef9-463b-bebd-e1a7717f3615)

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/369e9cd3-e85e-4aa7-9e41-13c56ddbb9c4)
?
