### ISSUE TITLE
Colours are not shown right. 

### ISSUE THREAD

**Issue by Dennuz070** [Yimura/YimMenu#1925]
### Describe the bug

:Minor: There is a problem with picking a colour in Yimmenu .. in the section Headlight there is 'backlight' instead of "blacklight" .. and in the neon section there is no option to choose "blacklight" at all.. please solve this ... thanks in advance.. 👍

### Steps To Reproduce

Get in a car.
Use LScustom. 
Headlight and Neon section. 
Colours. 

### Expected Behavior

Can you please adjust this.. 😀
Get the spelling right and add Blacklight option to neon. 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This here's an American freedom language menu, take your 1776 loser language out the door with you with your unnecessary extra Us and Es. 

![image](https://github.com/YimMenu/YimMenu/assets/100792176/6418b191-6856-4310-95ec-91761990197f)

**Comment by Dennuz070** [comment]
Ow wow mr Perfect ... sorry for being 1776 ... Trumpstumper ... !

**Comment by Dennuz070** [comment]
> This here's an American freedom language menu, take your 1776 loser language out the door with you with your unnecessary extra Us and Es.

Ow wow mr Perfect ... sorry for being 1776 ... Trumpstumper ... !

**Comment by GTMoraes** [comment]
> This here's an American freedom language menu, take your 1776 loser language out the door with you with your unnecessary extra Us and Es.
> 
> ![image](https://user-images.githubusercontent.com/100792176/258606838-6418b191-6856-4310-95ec-91761990197f.png)

what the f is a kilometer

also, on topic, the Gold color for wheels is actually brown, when checked on an actual LS Customs.

**Comment by Dennuz070** [comment]
> > This here's an American freedom language menu, take your 1776 loser language out the door with you with your unnecessary extra Us and Es.
> > ![image](https://user-images.githubusercontent.com/100792176/258606838-6418b191-6856-4310-95ec-91761990197f.png)
> 
> what the f is a kilometer
> 
> also, on topic, the Gold color for wheels is actually brown, when checked on an actual LS Customs.

A kilometer is 1000 meter ... haha... and yeh there realy must be some things adjusted in the menu.
