### ISSUE TITLE
[Bug]: Damage Override Bug

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1928]
### Describe the bug

Even if the damageoverride setting is turned off, the menu still uses the value entered by the user.

### Steps To Reproduce

go to weapons

Turn on the damageoverride setting and enter a high value (it can be a value that destroys pedestrians with one shot)

shoot at pedestrians or vehicles

turn off damageoverride after some use

shoot at pedestrians or vehicles again

### Expected Behavior

Game defaults should work when damageoverride is turned off

### Logs and/or screenshots

https://youtu.be/S8-YNmjuMfY

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Tayipc38** [comment]
Could it be that it does not reset it to its original value?

**Comment by ghost** [comment]
It seems so. I set the value to 10.0 but I didn't apply it, but still the weapon power remains at 10.0 and it detonates the vehicles with just a few shots

**Comment by dikivan2000** [comment]
Can confirm. This happens with any value entered the first time and irrespectively of what is entered later on. If it's 1 changed to 100, it'll stay 1, and vise versa. Fixed by restarting the game, sometimes switching sessions also helps.

**Comment by ghost** [comment]
> 



> Can confirm. This happens with any value entered the first time and irrespectively of what is entered later on. If it's 1 changed to 100, it'll stay 1, and vise versa. Fixed by restarting the game, sometimes switching sessions also helps.

Sometimes I turn this setting against npc to escape easily in the game. But then when I pvp with my friends for fun, it's not fun at all since I can't turn this setting off against them either.
