### ISSUE TITLE
[Bug]: Unable to start missions due to Spoof Player Model being enabled.

### ISSUE THREAD

**Issue by GTMoraes** [Yimura/YimMenu#1931]
### Describe the bug

I'm unable to start some missions on freemode, such as the stash house missions. 
Whenever I try to start the mission, it says something like "Unable to start this mission. Try again soon".

It works if I'm playing solo, but it seems if I join a populated session, it doesn't work.
It also works if I unload YimMenu.

### Steps To Reproduce

1. Go to a stash house mission
2. Try to start mission
3. Fail to start mission
4. Unload YimMenu
5. Successfully start mission

### Expected Behavior

Missions should start without needing to unload YimMenu.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
Try to disable Fast Join in the Network tab

**Comment by GTMoraes** [comment]
It's not enabled

Em qui., 10 de ago. de 2023 12:47, pierrelasse ***@***.***>
escreveu:

**Comment by gir489returns** [comment]
Yet another one of your stupid bugs that don't actually exist.

https://www.youtube.com/watch?v=f5K-Z5W2-0M

**Comment by GTMoraes** [comment]
> Yet another one of your stupid bugs that don't actually exist.
> 
> https://www.youtube.com/watch?v=f5K-Z5W2-0M

Why such aggressiveness? I'm just reporting the issue I'm experiencing.

And as I mentioned in the original post, my issue doesn't happen on solo sessions, as it seems to be the case on your linked video.
On populated sessions, I'm unable to start such missions.

Please, do try starting the same mission, or any other freemode mission such as the Car Shop prep missions (or manual car delivery) on a public session and see if the same thing happens.

**Comment by GTMoraes** [comment]
Here's a video:

https://i.imgur.com/vFjlmfc.mp4

**Comment by gir489returns** [comment]
OK you goalpost moving gaslighting annoyance. [It's because I'm tired of seeing the ticket system flooded with nonsense tickets. 90% of the tickets you file are a you issue](https://youtu.be/oaDnuExc1sI?t=108). Don't eat the fish.

https://youtu.be/qbYb0R6OvYg

But go ahead and tell me how I didn't have enough players or I didn't turn 360 degrees and walk away exactly right or some other nonsense.

**Comment by Yimura** [comment]
@GTMoraes do you have dance mode enabled perhaps? That feature hijacks the `E` button if I remember correctly? Otherwise try sharing your `settings.json` so we can reproduce...

**Comment by GTMoraes** [comment]
> OK you goalpost moving gaslighting annoyan[..]

the hell's wrong with you, dude.

> https://youtu.be/qbYb0R6OvYg

Ok, so what could be causing it from my side? As I clearly showed, simply unloading YimMenu allows the missions to start...
I'm not coloading anything else.

> @GTMoraes do you have dance mode enabled perhaps? That feature hijacks the `E` button if I remember correctly? Otherwise try sharing your `settings.json` so we can reproduce...

Nope, it's off. Also, it's not necessarily the E button. It's any freemode mission. The stash house is just one of those.            
I can't start sell missions (hangar, nightclub, bunker, mc), stash house missions, prep missions, nightclub VIP missions etc. Some missions just say something like "Mission unavailable at this moment. Please try again later" or something like that.

I noticed that if I'm the ONLY one in a public session, it works. But as soon as someone enters, it stops working.

I'll send the settings.json so we can see what could be wrong
[settings.json as txt.txt](https://github.com/YimMenu/YimMenu/files/12324464/settings.json.as.txt.txt)

I've tried going into the debug submenu and disabling all looped threads, and it didn't work either.

Thanks for replying like a normal person, I guess...

**Comment by GTMoraes** [comment]
Ok, so I tried fixing on my own, and it seems that deleting the settings.json and letting the menu rebuild it, then setting it up to my liking, fixes the issue.

Somehow, that settings.json I attached on the previous response breaks these freemode missions up, or is somehow outdated and the menu is defaulting some values to whatever would make it break. Idk.

**Comment by xiaoxiao921** [comment]
Let's keep this open until someone figure out what in the settings exactly mess this up, thanks for the report

**Comment by Yimura** [comment]
I wonder if spoofing the player model has something to do with it? Seems unlikely since it's only "server-side".
![image](https://github.com/YimMenu/YimMenu/assets/24669514/181f4dfc-b950-4d91-9571-10c22a14f6a0)

Used this website to compare your JSON with the default generated: https://jsondiff.com/

**Comment by GTMoraes** [comment]
> I wonder if spoofing the player model has something to do with it? Seems unlikely since it's only "server-side". ![image](https://user-images.githubusercontent.com/24669514/260148449-181f4dfc-b950-4d91-9571-10c22a14f6a0.png)
> 
> Used this website to compare your JSON with the default generated: https://jsondiff.com/

Probably not, as when I spoofed that epsilon model, I already had the issue.

I was just looking for a way to compare the JSON files, thanks for the tool


------------

Ok, so I know which stuff I changed while I had the issue (such as the aforementioned spoof player model), I'll try to enable everything, see if it breaks stuff, then go disabling one by one until it works.

**Comment by GTMoraes** [comment]
> I wonder if spoofing the player model has something to do with it? Seems unlikely since it's only "server-side". ![image]

Correction, you got that right. It was the spoofing player model.
I got thrown off by the "a_f_y_epsilon_01" model, as I had used it like two days ago, and thought it was that thing I did. 

Come to think of it, A week ago, I have used the menu on Single Player to try new models, and tried to spoof the player model to see how it would work, before using in multiplayer, but forgot about it (it also didn't change the model)

That was the issue, spoofing player model. Thanks for pointing it out, and for recommending the tool to compare the JSONs.

**Comment by Yimura** [comment]
Very odd behaviour but thanks for confirming, unsure how we'll go on to fixing this elegantly.

**Comment by maybegreat48** [comment]
Can reproduce. Spoofing your model completely breaks the game

**Comment by maybegreat48** [comment]
After looking into the scripts a bit, I have found out that the only way you can fix all this is to enable `Force Script Host`. You can't get around the checks if you are not the host (check `func_8569` and `_IS_PLAYER_IN_ANIMAL_FORM` for more details)
