### ISSUE TITLE
[Bug]: Things get weird after using End Session Kick on someone

### ISSUE THREAD

**Issue by GTMoraes** [Yimura/YimMenu#1932]
### Describe the bug

After I use End Session Kick on someone, I have what seems to be an enormous latency when doing stuff like registering as boss, entering a personal vehicle or sitting on the Nightclub PC chair.

When I use the register as boss, I see my blip change colors, but I don't see the banner until, like, 30 minutes in. 
Also, when I try to enter my PV, my player character hangs mid animation and stays there, moving his eyes and mouth, until I cancel the action (if I use the Vehicle submenu option to jump inside the car, the car doesn't start up until I also click on the menu button to start the vehicle)
Trying to sit on a PC chair (like on the nightclub or office's chair), the player just stands in there. I can still move the character around, but can't open the interaction menu until I exit the nightclub or office (or use the elevator)

### Steps To Reproduce

1. End Session Kick someone
2. Try to register as CEO/MC
3. Try to sit on a computer chair

You should experience the bug. If not, wait a bit before doing step 2 or 3.

### Expected Behavior

Normal game like when I use the Desync kick option (which I use now, instead of End Session kick)

### Logs and/or screenshots

```
no logs atm. I didn't know how to report bugs here before. I just remembered this bug because I saw a PR about using all available kick options for reaction, and thought that'd be a bad idea due to this End Session kick bug.
```

### Store

Steam

### Additional context

I've just personally just switched to Desync kick. 
I have no idea what's the difference between them, all I know is that after 10-20 seconds, a lame player leaves.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
If you look at your backed-up log files are any of them unusually large after performing an end session kick? I'm not saying you're experiencing the same issue but the only time I've experienced a lag like what you're describing is when the log file is getting spammed really badly.

**Comment by GTMoraes** [comment]
None seems particularly large. I'll try End Session kicking someone next time and see if something weird pops up on the logs.

**Comment by GTMoraes** [comment]
Nope, no weird logs. It all looks normal and clean.

I end-session kicked someone and everything started to behave weirdly as I stated before. 

It's not an actual lag... I can see other players just fine, fight against them, drive with them etc. Just these actions, such as registering as CEO, entering my personal vehicle (sometimes on the 2nd or 3rd try) (also other vehicles are always fine), or starting some missions (such as Dax's First dose and Last dose, as the game will seemingly try to go to that "waiting for players" screen, but never gets there, and just returns to where I was previously on the session), they get bugged.
