### ISSUE TITLE
[Bug]: Spoofed model does not reset, now saved in settings

### ISSUE THREAD

**Issue by dikivan2000** [Yimura/YimMenu#1934]
### Describe the bug

One of the newer builds now loads a spoofed player model from settings on launch and on session switch. It is a nice touch however combined with being unable to roll back the spoof this function becomes a pain in the arse. Let me provide an example.

I made myself a monkey to fool around in session missions and bring some variety to cutscenes. That's all fine and cool. Next day I launch the game, the menu loads, my friend tells me I'm still a monkey. Spoofing as "self" through the menu glitches the character out, makes be a male with no head texture or bald (I play as female with hair) and wrong clothes. The model rolled back to normal whenever the menu was NOT running, and would corrupt on menu load. I could not roll back to my character at all, the only thing that did the trick for me is to remove the settings json which basically reset everything.

Older versions apparently did not store this as switching sessions always reset the model back to normal. At this moment what's needed is either being able to restore the normal model/reset this function somehow, or let the game do it on sessions switch.

### Steps To Reproduce

1. Spoof model (any will do)
2. Switch sessions/relaunch game
3. Try to restore default player model
4. Fail

### Expected Behavior

Either as in previous versions, do not store spoofed model in settings, or be able to correctly restore the player model

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This was probably introduced/should've been addressed when #1803 was done. My guess is that another field is still not being persisted. @maybegreat48

**Comment by maybegreat48** [comment]
You can disable that in Network > Spoofing but I guess it's a good idea to add a shortcut in the ped spawner
