### ISSUE TITLE
[Request]: spoof name .RID 

### ISSUE THREAD

**Issue by spinoza-spinoza** [Yimura/YimMenu#1956]
### Problem

in spoofing option we can spoof kd.rp.and other  issue 
i see in other menu you can change your name .RID  manually   or get  a random  RID  .name  

its will be great having  thIs options added to other spoofing options 

### Solution

add an 2 option to change name mannually  or get a random name 
same for  RID

### Reason

it will be an good option to not get  banned
 buy people reporting with video

**Comment by Yimura** [comment]
Spoofing name and RID is not possible anymore ( or very hard, at the least).
