### ISSUE TITLE
[Request]: Bypass Max Speed

### ISSUE THREAD

**Issue by Farrow92** [Yimura/YimMenu#1957]
### Solution

Bypass vehicle speed caps

### Reason

Make cars go vr0000m more

**Comment by pierrelasse** [comment]
Wdym? With accel multiplier and gravity you can go very very fast. Do you want to go even faster or what is the problem?

**Comment by Farrow92** [comment]
Using gravity and accel multiplier doesnt bypass the max speed set for the vehicle? For example even with those applied i cant make the Teseract go faster than 130

**Comment by GTMoraes** [comment]
> Using gravity and accel multiplier doesnt bypass the max speed set for the vehicle? For example even with those applied i cant make the Teseract go faster than 130

Are you sure? My cars can go over 200mph with 1.6 accel and gravity at 12

**Comment by xiaoxiao921** [comment]
https://alloc8or.re/gta5/nativedb/?n=0x0E46A3FCBDE2A1B1

ENTITY::SET_ENTITY_MAX_SPEED

just need someone to implement it / make a lua script for it

**Comment by NjuuOwO** [comment]
> ENTITY::SET_ENTITY_MAX_SPEED

Isn't it better to use VEHICLE::SET_VEHICLE_MAX_SPEED ?
It does bypass the entity max speed

**Comment by xiaoxiao921** [comment]
Yeah sure, should be even better

**Comment by Harmless05** [comment]
@Farrow92  I've made Luas about it already if you are interested. https://github.com/Harmless05/harmless-lua/tree/main/Scripts/Vehicle

**Comment by xiaoxiao921** [comment]
Trivially doable through a lua script
