### ISSUE TITLE
[Bug]: Bail Kick

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1960]
### Describe the bug

I don't know how this happened. It just caught my eye when I was going to use this kick method against someone. I reinstalled the menu cleanly but this button was still like this and not working.

While installing the menu cleanly, it also gives a baddlc warning, I don't know if it has anything to do with it.

### Steps To Reproduce

Go to the Kick section

This button will not work

### Expected Behavior

I think we should be able to send someone from the lobby that we're pretty sure it's not cheating.

### Logs and/or screenshots

[08-12-2023-19-46-36_cout.log](https://github.com/YimMenu/YimMenu/files/12327905/08-12-2023-19-46-36_cout.log)
![yimbaddlc](https://github.com/YimMenu/YimMenu/assets/130869249/8fb339fd-c262-4fe1-8776-62df247a000b)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
The bail-kick was patched by Rockstar a few days ago.

**Comment by Yimura** [comment]
The bad DLC log is not a warning, it's just that GTA contains some data from next gen which can't be used and would crash the game if the mod menu where to try and use it.
