### ISSUE TITLE
[Report]: Logs from after crashes

### ISSUE THREAD

**Issue by GTMoraes** [Yimura/YimMenu#1961]
### Which feature

I'm not sure whether those are useful, but here are the cout.log from when I receive a modder crash

### Reason

Maybe they'll help identifying what they're using. Or maybe it's useless junk. 

Either way, please respond if logs should be sent after a modder crash event, or if they're useless for development purposes.

### Additional context

[08-11-2023-04-43-05_cout.log](https://github.com/YimMenu/YimMenu/files/12327907/08-11-2023-04-43-05_cout.log)
[07-31-2023-07-08-26_cout.log](https://github.com/YimMenu/YimMenu/files/12327908/07-31-2023-07-08-26_cout.log)
[08-01-2023-22-58-01_cout.log](https://github.com/YimMenu/YimMenu/files/12327909/08-01-2023-22-58-01_cout.log)
[08-11-2023-04-42-00_cout.log](https://github.com/YimMenu/YimMenu/files/12327910/08-11-2023-04-42-00_cout.log)

**Comment by GTMoraes** [comment]
This one was crazy. Idk what happened, but I was fighting someone on a full lobby (30 players) where I was the host (legitimately). After beginning to win by a larger margin (like 33 x 25 to me), he said "gg hacker" and after like 10 seconds, my game froze up and the background log went NUTS.

I force-closed the game, and the resulting cout.log was over 65MB large.


Here's the file:
[cout.zip](https://github.com/YimMenu/YimMenu/files/12328317/cout.zip)

**Comment by Jordi0686** [comment]
I have several times that the game crashed in a friend session with no players. The game crashes at odd times while doing CEO missions and normal gameplay. There isn't really any logic to it that causes the game to crash. I have added one of the logs in the attachment.

[08-16-2023-05-08-18_cout.log](https://github.com/YimMenu/YimMenu/files/12354855/08-16-2023-05-08-18_cout.log)

**Comment by GTMoraes** [comment]
> I have several times that the game crashed in a friend session with no players. The game crashes at odd times while doing CEO missions and normal gameplay. There isn't really any logic to it that causes the game to crash. I have added one of the logs in the attachment.
> 
> [08-16-2023-05-08-18_cout.log](https://github.com/YimMenu/YimMenu/files/12354855/08-16-2023-05-08-18_cout.log)

Yours is different

`[03:08:18.7199326][WARN/log_message_error_box.cpp:37] Error Code: ERR_MEM_EMBEDDEDALLOC_ALLOC
[03:08:18.7212328][FATAL/log_message_error_box.cpp:14] EXCEPTION_ACCESS_VIOLATION`

It's more like the #1545

**Comment by Yimura** [comment]
We're only going to accept logs that are reproducible, random crashes aren't useful and become outdated very quickly.
And last time people just started dumping all their logs related or not in one issue.
