### ISSUE TITLE
[Improvement]: someone sells yimmenu

### ISSUE THREAD

**Issue by xhcherry** [Yimura/YimMenu#1964]
### Which feature

Suggestions to increase code security

### Reason

In mainland China, someone sells yimmenu and encapsulates the code, so that others cannot view any line of code, and releases both a free version and a paid version without a license, but when using the tool provided by the seller to inject, the prompt is yimmenu. dll

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/83774342/5482f089-2883-435b-b709-13929ed28b66)
![image](https://github.com/YimMenu/YimMenu/assets/83774342/99cee144-17c3-4f66-b9f8-c8161165ad12)
![image](https://github.com/YimMenu/YimMenu/assets/83774342/cb972446-ffbd-4623-874a-53831d67c7e9)
![image](https://github.com/YimMenu/YimMenu/assets/83774342/7c32cad2-1f6f-4779-a465-45a8c741f3ef)

**Comment by Yimura** [comment]
Nothing we can do about this.
