### ISSUE TITLE
[Improvement]: silent aimbot and aim on key

### ISSUE THREAD

**Issue by Kelrit402** [Yimura/YimMenu#1971]
### Which feature

I wish there was a better way to do pvp with guns or slaughter npc.
However, it would be better if it looked LEGIT.

### Reason

Currently, triggerbot is not very effective.
Rather than this feature, it would be better to add a silent aim feature to the aimbot.
Also, it would be nice to have it work when a specific key is pressed to control the aimbot.

### Additional context

Here is some code where I inserted the silent aim function into the aimbot.cpp
I hope you guys will make better code and update it.

`   if (sqrt(pow(movement.x, 2) + pow(movement.y, 2)) < local_fov_change)

     local_fov_change = sqrt(pow(movement.x, 2) + pow(movement.y, 2));

     if (g.weapons.triggerbot)

     {

          PED::SET_PED_SHOOTS_AT_COORD(self::ped, aim_lock.x, aim_lock.y, aim_lock.z, true);

     }

     else

     {

          mouse_movement.x = movement.x;

          mouse_movement.y = movement.y;

     }

     }   `

**Comment by ghost** [comment]
the game already has auto aim, honestly what more do you need?

**Comment by yousef157** [comment]
> the game already has auto aim, honestly what more do you need?

K&M & snipers

Could just be a skill issue though, you decide

**Comment by xiaoxiao921** [comment]
Triggerbot should be much better now, tell us if it's not
