### ISSUE TITLE
[Improvement]: Add more information about the player's IP

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1975]
### Which feature

Perhaps someone will want to add an API to view information about the player's IP and add it to "Extra Info". Or make a separate button and a modal window displaying this information. For example use this API: https://ip-api.com/

### Reason

I think it's not a super toxic feature that can be added and it won't harm the players as the IP of the players is still displayed, and this feature just makes it easier to find information. Moreover, this API is not very accurate, so that you can find out the exact location of the player directly on the street and sometimes in the city, but you can at least find out the country and whether he uses vpn and so on. And even more so, there are more harmful features in the menu, so this one seems generally harmless.

### Additional context

I think it's just worth making a json request: `http://ip-api.com/json/{ip}?fields=66846719` and just display all the fields in Extra info or a new modal window on the click of a button.

**Comment by Yimura** [comment]
I’d rather just remove the IP from the UI than add that.

**Comment by ghost** [comment]
> I’d rather just remove the IP from the UI than add that.

Yes, but other p2c menus and even some free ones have this feature. But if you remove the IP, then there is no point if the moderator knows everything about me, and I know nothing about him. In addition, not all players use vpn, this can give some kind of parity.

**Comment by D-Borkan** [comment]
> I’d rather just remove the IP from the UI than add that.
Exactly, i recommend removing it

**Comment by D-Borkan** [comment]
> I’d rather just remove the IP from the UI than add that.

Exactly, i recommend removing it

**Comment by ghost** [comment]
> > I’d rather just remove the IP from the UI than add that.
> 
> Exactly, i recommend removing it

I think this feature is fine as is. It's beneficial in order to block ip traffic from more aggressive stalkers.

**Comment by D-Borkan** [comment]
> > > I’d rather just remove the IP from the UI than add that.
> > 
> > 
> > Exactly, i recommend removing it
> 
> I think this feature is fine as is. It's beneficial in order to block ip traffic from more aggressive stalkers.

yes, protecting or preventing your IP from being revealed, It is already in protection --> force relays connection , this is an ideal thing, but I am talking in another side 
i think you or Yimmenu or the experts know exactly what I mean and which side I'm talking about

**Comment by ghost** [comment]
> > > > I’d rather just remove the IP from the UI than add that.
> > > 
> > > 
> > > Exactly, i recommend removing it
> > 
> > 
> > I think this feature is fine as is. It's beneficial in order to block ip traffic from more aggressive stalkers.
> 
> yes, protecting or preventing your IP from being revealed, It is already in protection --> force relays connection , this is an ideal thing, but I am talking in another side i think you or Yimmenu or the experts know exactly what I mean and which side I'm talking about

There's no non-toxic reason for you to know anything more than another player's ip. This kind of request would be used (as other menus have done) to make a feature that spouts out other player's physical locations in the game chat. That's some toxic nonsense and the game and the gta online gaming community is worse for it.

**Comment by Yimura** [comment]
Feature won't be implemented.
