### ISSUE TITLE
ESP Colors are incorrectly set

### ISSUE THREAD

**Issue by karifeld** [Yimura/YimMenu#198]
**Describe the bug**
Assuming if you were to use the default ESP color settings (Far: Green, Near: Orange, Close: Red) and any players were nearby, the colors would be set incorrectly to (Far: Orange, Near / Close: Red)

**To Reproduce**
1. Enable ESP
2. Toggle noclip and off-radar (optional)
3. Fly towards any player

**Expected behavior**
The colors should be in order of (Far: Green, Near: Orange, Close: Red) in accordance to the distance threshold.

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
The following code should fix the issue at line 67 of `view_esp.cpp`

else if (g->esp.change_esp_color_from_dist) {
	if (distance <= g->esp.distance_threshold[0]) 
		esp_color = g->esp.enemy_color;
	else if (distance >= g->esp.distance_threshold[0] && distance < g->esp.distance_threshold[1])
		esp_color = g->esp.enemy_near_color;
}

**Comment by karifeld** [comment]
Oversight on my end, my apologies

**Comment by Yimura** [comment]
No problem, in general it's just as a placeholder to auto remove the bad issues.

**Comment by Yimura** [comment]
@karifeld if you have the time you can open a PR resolving the issue.

**Comment by ghost** [comment]
Not sure why you don't just use a "from HSB" function and then clamp the ranges.

**Comment by karifeld** [comment]
@cl1xa i made something which i believe is what you are looking for

you can check it out here at my branch [esp_color_lerp](https://github.com/karifeld/YimMenu/tree/esp_color_lerp)

It lerps the default color to the defined enemy color in accordance to the distance threshold, its really sensitive to non-spectral colors or colors that have its saturation set in the middle

i dont think my implementation is efficient, but it works as is. i could use some help
