### ISSUE TITLE
[Request]: Revenge Kick (Counter Token Spoofers)

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#1988]
### Problem

So i was playing on a public session, till i came across a cheater with 2take, he had **host token spoofing** so i couldn't kick him, the whole lobby was getting nuked and getting drops, i tried multikick, didn't work and he kicked me, so i joined back and literally kicked everyone in the lobby but him, he got so mad it was so funny.

### Solution

This method would work in a similar way, if the target is using host token spoof or something like that,  add a "revenge kick" button that will kick everyone except the host in the lobby (idk if multikick would be a good idea because backfires).

### Reason

Would be a different and unblockable way to annoy paid menus users.

**Comment by ghost** [comment]
I agree that would be a cool feature. I think that we can just add such a checkbox and while joining, while we see the inscription "wait join freemode session" and determine that the host is a modder, then we can send an oom-kick or multi-kick to everyone except the host automatically. This way we would clear the session for the host modder.

**Comment by GTMoraes** [comment]
I remember reading that this would be an undesired thing - to kick everybody from the server.

You've some logic backing you up, but I think it'll be best left "manually" as you did.

**Comment by snowleopardd** [comment]
> I remember reading that this would be an undesired thing - to kick everybody from the server.
> 
> You've some logic backing you up, but I think it'll be best left "manually" as you did.

I completely understand this could be used to troll, but the method I'm proposing will check if the host is **indeed** spoofing their tokens, so the button will only work under those circumstances

**Comment by maybegreat48** [comment]
You can open the command executor and run `nfkickall` if you really want to do that

**Comment by ghost** [comment]
> You can open the command executor and run `nfkickall` if you really want to do that

As far as I know, you need to wait 15 seconds before the players leave and before that time the host kicks me. or am I wrong?

**Comment by Yimura** [comment]
This is a terrible idea, not all people who are host and spoofing token are malicious modders.

And if you really need to kick everyone just use the kick all buttons.
