### ISSUE TITLE
[Low Priority]: Add block join alert and chat command permission to reaction

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1991]
### Problem

Maybe someone will be bored and want to add it. I don't think it's very hard to implement.

### Solution

The block join alert combobox should be displayed below if the block join checkbox is checked in the reaction section. And, if possible, add a combobox of chat permission commands in the reaction so that it would be possible to prevent modders from using my commands in the chat, or at least assign access.

### Reason

Will prevent modders from using my chat commands and will give some access. Allows you to change the join blocking alert automatically instead of doing it manually in the player database. Perhaps someone wants to make their first PR and is looking for an easy task.

**Comment by pierrelasse** [comment]
Maybe tags could be whitelisted or blacklisted https://github.com/YimMenu/YimMenu/issues/2061

**Comment by binded-zz** [comment]
theres already a alert for when some one joins  and theres two settings for chat commands  
ones a global and the other is per user set the global to none and set the commands on the user in the player database 

or set a low global and set higher in the player database
