### ISSUE TITLE
[Build]: when i try build i got minhook error.

### ISSUE THREAD

**Issue by sezzyaep** [Yimura/YimMenu#1992]
### Describe the build issues

i wanna try build source with visual studio 2022 i get minhook error

![image](https://github.com/YimMenu/YimMenu/assets/49095369/20f55543-213f-42b7-86b9-b8332743e824)

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://github.com/YimMenu/YimMenu/assets/49095369/950ff54a-1e39-42b0-8211-c6c16c4504d2)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by maybegreat48** [comment]
Can you show your build logs?

**Comment by Yimura** [comment]
Forgot to install Git from the setup instructions perhaps?

**Comment by Yimura** [comment]
No response from author, closing.
