### ISSUE TITLE
[Bug]: Start tutorial not working?

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1995]
### Describe the bug

After trying to click the "Start Tutorial" button, the scene does not start for everyone.

### Steps To Reproduce

1. Click the "Start Tutorial" button in Network->Teleport section
2. Nothing will happen

### Expected Behavior

The scene should start for all players

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Additional context

Although if you try to run it for yourself, then it works

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by iDominiqe** [comment]
kicks out of the game when trying to become a host, and also kicks out if you use multikick
added here so as not to open a new request...

**Comment by WorthIessPricetag** [comment]
It does not start for some because they have protections against it, like "Send to Job". Nothing you want to do about it.

**Comment by pierrelasse** [comment]
I think it only works on joining players i read somewhere but im not sure

**Comment by maybegreat48** [comment]
> After trying to click the "Start Tutorial" button, the scene does not start for everyone.

Yeah, that's intended and cannot be fixed
