### ISSUE TITLE
[Bug]: Teleporting sends you to the bottom of the map.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1997]
### Describe the bug

When you try to teleport somewhere, you will often fall under the map.

### Steps To Reproduce

Open the map

choose where you want to teleport

press the hotkey you set to teleport

you must be falling down right now

### Expected Behavior

The character should land neatly on the ground

### Logs and/or screenshots

[log.txt](https://github.com/YimMenu/YimMenu/files/12386192/log.txt)

https://youtu.be/kmfLza0xp04

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by tim-gromeyer** [comment]
Is this with today's nightly build?

Because someone already complained about it here #1963

**Comment by ghost** [comment]
> Is this with today's nightly build?
> 
> Because someone already complained about it here #1963

I made that complaint. when I saw that it was merged today, I said I think it was fixed and I installed the latest build, but the problem still persists.

**Comment by D-Borkan** [comment]
i think this problem appear with last update, so y this need to fix

**Comment by ghost** [comment]
> i think this problem appear with last update, so y this need to fix

I also had this issue when pull request was made. I had videotaped it and reported it there, but I guess it went unnoticed.
I'm using the previous build since teleportation is the most used feature.

**Comment by gir489returns** [comment]
I am able to reproduce the issue, but not sure how to fix it.

**Comment by ChaT0n** [comment]
If i take the previous version  of yimmenu, it doesn't happen. So maybe checking what have changed between the last build and the previous one might help

**Comment by tim-gromeyer** [comment]
> maybe checking what have changed between the last build and the previous one might help

It's this commit (5eead0436fa075006fa7d712e387c8642fddaa95), maybe you can find out what causes it

**Comment by xiaoxiao921** [comment]
Maybe the changes to https://github.com/YimMenu/YimMenu/commit/5eead0436fa075006fa7d712e387c8642fddaa95#diff-02e87de06ffbd06268b8b77fefb9887487dd54489305cc1db00cbcc0d413fea6L175

?

**Comment by gir489returns** [comment]
> Maybe the changes to [5eead04#diff-02e87de06ffbd06268b8b77fefb9887487dd54489305cc1db00cbcc0d413fea6L175](https://github.com/YimMenu/YimMenu/commit/5eead0436fa075006fa7d712e387c8642fddaa95#diff-02e87de06ffbd06268b8b77fefb9887487dd54489305cc1db00cbcc0d413fea6L175)
> 
> ?

I'm not sure why, unless he's not teleporting the player there first and then calling this. GET_GROUND_Z_FOR_3D_COORD fails if the coordinates are not within render distance.

**Comment by gir489returns** [comment]
Hello @grvelmaster and @tim-gromeyer, please use the DLL included with my PR located here: https://github.com/YimMenu/YimMenu/pull/2011 Let me know if the issue was resolved. I tested it 20 times, and only once did I get sent under the map, not sure why, couldn't replicate it...

**Comment by ghost** [comment]
> Hello @grvelmaster and @tim-gromeyer, please use the DLL included with my PR located here: #2011 Let me know if the issue was resolved. I tested it 20 times, and only once did I get sent under the map, not sure why, couldn't replicate it...

I've tested it now, it's fine for flat and mountainous areas. If you just want to teleport to the roof of tall buildings, the character goes inside the building.

![gtateleporttest (4)](https://github.com/YimMenu/YimMenu/assets/130869249/6d7213de-1d0c-4efc-b5cf-2b4e7e126aea)
![gtateleporttest (1)](https://github.com/YimMenu/YimMenu/assets/130869249/7103d644-bcbb-4162-8a0d-c78a42bcb08c)
![gtateleporttest (2)](https://github.com/YimMenu/YimMenu/assets/130869249/8e828e3f-f947-47a2-9d33-8579e91e1b10)

**Comment by gir489returns** [comment]
@grvelmaster I have pushed another build that should fix it. Please redownload the artifact from the same PR and try again.

**Comment by ghost** [comment]
> @grvelmaster I have pushed another build that should fix it. Please redownload the artifact from the same PR and try again.

I've tested it, it's working perfectly right now

**Comment by gir489returns** [comment]
@Yimura You can close this.
