### ISSUE TITLE
[Bug]: try to multi kick chinese chat spammers result in desync kick and session lost

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2003]
### Describe the bug

go in some East (chinese) session
see chinese spammed messages by player
try to kick them (use multi kick or desync kick)
chances are high you will get desync kicked

![image](https://github.com/YimMenu/YimMenu/assets/139460769/b57af882-4ca6-4c89-8851-ecc506d9a590)

### Steps To Reproduce

mentioned in details

### Expected Behavior

should atleast be able to kick chat spammers.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by alyxme** [comment]
I personaly got same when tried to desync sinner with "host token spoofed" and it came to me immidietly (no 10sec wait).

**Comment by lonelybud** [comment]
yes but these chat spammers are normal these days in east. they dont even spoof any data. Earlier version of yim menu I was able to desync kick them simply

**Comment by snowleopardd** [comment]
dont use multikick, you will warn them.

**Comment by lonelybud** [comment]
> dont use multikick, you will warn them.

whats the point of it then. Also as in the past one was able to kick chat spammers using desync kick alone. Even that not worked with latest update. That's why I opened this pr.

**Comment by lonelybud** [comment]
closing this for now. If I encounter it again with latest build will open again in new pr.
