### ISSUE TITLE
[Bug]: Friends in personal vehicle appear invisible

### ISSUE THREAD

**Issue by IlIlIlIlIll** [Yimura/YimMenu#2004]
### Describe the bug

Friend in their toreadors appear invisible to me, they're on the minimap but not directly infront of me.

### Steps To Reproduce

join a session with friend = them invisible

### Expected Behavior

to be able to see them

### Logs and/or screenshots
![image](https://github.com/YimMenu/YimMenu/assets/142699143/d0238c4b-696d-4137-8056-cace6d33462d)

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by carrotcake43** [comment]
yes even people who are not using yimmenu appear invisible randomly in personal vehicles while the menu is loaded. it has done this since the last update.

**Comment by ChaT0n** [comment]
Confirmed :  if player gets in toreador he is invisible, and so is his toreador.
Beside this I noticed that I am getting a few bugs with the car while the menu is loaded, the vehicle can't be deleted if I spawn it (tested with toreador) (deleting it while inside or using the gun menu delete)

**Comment by Yimura** [comment]
If I understood correctly then this is not an issue with the menu but with the game?

**Comment by ChaT0n** [comment]
will check again tomorrow with this car and give u an answer
