### ISSUE TITLE
[Bug]: Vehicle GodMode not staying on for non PVs

### ISSUE THREAD

**Issue by ClapperJuan** [Yimura/YimMenu#2005]
### Describe the bug

When turning on godmode it puts it on for PVs and stays on as it should. however when you get into lets say a NPCs car the godmode turns on while your in the car but when you step out the car, it is no longer in godmode...

### Steps To Reproduce

1. Enable Vehicle GodMode
2. Get into a NPC car or Spawn one ( Not a PV )
3. While in the car try to explode it ( Nothing happens its Godmode )
4. Step out and try to explode it ( It explodes )
5. Test same thing with PV ( Does not explode )

### Expected Behavior

When getting into any car the godmode should stay on no matter if its a PV or not.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
An interesting fact if you turn on the vehicle godmod and teleport into another player's vehicle then the godmod will not work. And one more fact if you spawn the new car (not PV) and you jumped out from it, then the godmod is cleaned, and if you are killed, then the godmod remains.

**Comment by gir489returns** [comment]
This is intentional behavior to prevent rockets or some shit with armored cars.

**Comment by binded-zz** [comment]
> An interesting fact if you turn on the vehicle godmod and teleport into another player's vehicle then the godmod will not work. And one more fact if you spawn the new car (not PV) and you jumped out from it, then the godmod is cleaned, and if you are killed, then the godmod remains.

but you can use the misc options im sure and give that person semi god and even 
theres sch-lua which for sure does add god to other players cars

![Screenshot 2023-08-22 081938](https://github.com/YimMenu/YimMenu/assets/458540/4c72e41b-97be-401c-bd9a-4f733db9ca63)

the script is in Chinese just covert to English like i did 
4th top row god mode for other player cars and 5th top row is the no collision

**Comment by Yimura** [comment]
Intentional behaviour.
