### ISSUE TITLE
[Bug]: normal mission, heist & joining friend server issues

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2006]
### Describe the bug

**first problem -**
start first dose mission by Dax in a public server
complete it
you will be there with your friend in a public server once its done
but you do not load properly in that server and see black screen
then after sometime you get kicked to another public server.

**second problem -**
join last setup mission (destroy teredos and scan submarine) of bogdan problem heist (you are being invited)
you will be able to enter into the server with all 4 players but the mission will not start
mission will start when you unload yim menu
I also disabled all protections and tried again.

**third problem-**
I have a friend who is a non-modder.
i tried to join his session but I was unable to.
I unloaded yimmenu. I was able to join then.

**my settings include this** -

![image](https://github.com/YimMenu/YimMenu/assets/139460769/523cea2d-186d-4707-a41c-1f35817371d4)

rest all normal like
vehicle -> seat belt
weapon -> infinite ammo
protections -> disabled all

### Steps To Reproduce

mentioned above

### Expected Behavior

should work normal

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
when i used this version of yim menu. the teleport worked fine
https://github.com/YimMenu/YimMenu/commit/9a51d381c99e11fab50a383dcee8a3d73b75d49b

**Comment by rr1231234** [comment]
teleport is definitely fucked up, not sure of this is the game change or the script changed

**Comment by holysnipz** [comment]
>third problem -
teleporting to land locations sometimes actually teleport you below the land

can you try #2011 for that issue?

**Comment by lonelybud** [comment]
teleport issue has already been reported here - #1997 
therefore removing it from this issue

**Comment by 0xEmiil** [comment]
this thing of not seeing the player it happens to me even with Normal/Random Players like a bad sync

**Comment by lonelybud** [comment]
> this thing of not seeing the player it happens to me even with Normal/Random Players like a bad sync

please elaborate

**Comment by 0xEmiil** [comment]
> > this thing of not seeing the player it happens to me even with Normal/Random Players like a bad sync
> 
> please elaborate

Like if the players are not sync maybe this is caused by a protection bug

**Comment by lonelybud** [comment]
you mean player are seen to be near you in map but when you spectate them they are seen as underneath the map

**Comment by 0xEmiil** [comment]
> you mean player are seen to be near you in map but when you spectate them they are seen as underneath the map

Yep

**Comment by lonelybud** [comment]
> > you mean player are seen to be near you in map but when you spectate them they are seen as underneath the map
> 
> Yep

this is the problem I have seen as well. At that time I was using this build. https://github.com/YimMenu/YimMenu/commit/81e43b51d7049a40b49d826d09bdc3828b1c7bb3

**Comment by Yimura** [comment]
Do you have replace matchmaking enabled under Network > Session Browser? This will cause some issues when leaving a mission with friends.

**Comment by lonelybud** [comment]
> Do you have replace matchmaking enabled under Network > Session Browser? This will cause some issues when leaving a mission with friends.

I have not enabled that. I will close these issues for now since I have not retested them all but will keep note of them whenever possible and next time will raise pr for individual issues with more reproducible steps.
