### ISSUE TITLE
Create a "no u" godmode

### ISSUE THREAD

**Issue by LiamD-Flop** [Yimura/YimMenu#201]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
When a player attacks you, give the damage back to the player.

**Provide Reasoning**
Who wouldn't want to no u some griefing kiddo.

**Comment by xM4ddy** [comment]
What do you mean by the godmode part? As in godmode yourself then do the equivalent damage back to them? The damage part can be done easily with this native. https://docs.fivem.net/natives/?_0x867654CBC7606F2C

**Comment by xM4ddy** [comment]
or just https://docs.fivem.net/natives/?_0x697157CED63F18D4

**Comment by LiamD-Flop** [comment]
It would ideally just negate damage without godmode. For the other part it's as it suggests. Just give the same damage back to them. Probably with the bullet native

**Comment by Tayipc38** [comment]
We can parse the CWeaponDamageEvent within RECEIVED_EVENT. 
https://github.com/citizenfx/fivem/blob/35b24f68bd2c1fc29bcfca4d4d134e53a8a72815/code/components/citizen-server-impl/src/state/ServerGameState.cpp#L4547

**Comment by Tayipc38** [comment]
We may be able to redirect the damage event to the sender negating any need to manually forge the damage with natives.
