### ISSUE TITLE
[Bug]: No idle kick not working

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2010]
### Describe the bug

I get kicked out of the lobby even if this feature is active

### Steps To Reproduce

Go to Self tab

Activate no idle kick

you will be kicked out when you stand idle

### Expected Behavior

You shouldn't be thrown when you're idle

### Logs and/or screenshots

[yimidlebug.txt](https://github.com/YimMenu/YimMenu/files/12401450/yimidlebug.txt)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ScottiePimp** [comment]
I see a lot of people complaining about this. So just use this:

*Global(1654054).At(1155).As<int*>() = -1;
*Global(1654054).At(1155 + 16).As<int*>() = -1;

Want to disable the idle cam aswell? Call these natives in a loop:

CAM::INVALIDATE_IDLE_CAM();
CAM::INVALIDATE_CINEMATIC_VEHICLE_IDLE_MODE();

**Comment by ghost** [comment]
> I see a lot of people complaining about this. So just use this:
> 
> _Global(1654054).At(1155).As<int_>() = -1; _Global(1654054).At(1155 + 16).As<int_>() = -1;
> 
> Want to disable the idle cam aswell? Call these natives in a loop:
> 
> CAM::INVALIDATE_IDLE_CAM(); CAM::INVALIDATE_CINEMATIC_VEHICLE_IDLE_MODE();


I don't have a lot of technical knowledge about the game.
where will I enter these numbers in the stat editor, there are only 2 places below and 3. the part just shows how much the value is, I guess.

**Comment by ScottiePimp** [comment]
In the code. Same place you build the dll

**Comment by gir489returns** [comment]
> In the code. Same place you build the dll

I'm making a build off it, I'll post the PR number in a moment.

**Comment by ScottiePimp** [comment]
> > In the code. Same place you build the dll
> 
> 
> 
> I'm making a build off it, I'll post the PR number in a moment.

Great!

**Comment by gir489returns** [comment]
PR #2011 is submitted, when the build bot is done please test it.

**Comment by ScottiePimp** [comment]
> PR #2011 is submitted, when the build bot is done please test it.

Remove the for int loop. Also, set the globals to -1. I grabbed these a long time ago but I have a faint memory that they only worked with -1, could have changed throughout the updates but yea.

**Comment by gir489returns** [comment]
> > PR #2011 is submitted, when the build bot is done please test it.
> 
> Remove the for int loop. Also, set the globals to -1. I grabbed these a long time ago but I have a faint memory that they only worked with -1, could have changed throughout the updates but yea.

I looked in freemode.c4 and they check if they're 0 to reinitialize the timers. f_1171 checks both 0 and -1 for some reason.

**Comment by gir489returns** [comment]
There seems to be a bug with running looped commands at the moment.

**Comment by ScottiePimp** [comment]
> There seems to be a bug with running looped commands at the moment. That is why all 3 of these solutions don't work.

What seems to be the issue? If there's anything I can help with

**Comment by gir489returns** [comment]
> > There seems to be a bug with running looped commands at the moment. That is why all 3 of these solutions don't work.
> 
> What seems to be the issue? If there's anything I can help with

I'm not sure. I put some debug code into it to see if it was getting called and it wasn't getting called. Can you try the PR dll and see if it works?

**Comment by ScottiePimp** [comment]
> > > There seems to be a bug with running looped commands at the moment. That is why all 3 of these solutions don't work.
> 
> > 
> 
> > What seems to be the issue? If there's anything I can help with
> 
> 
> 
> I'm not sure. I put some debug code into it to see if it was getting called and it wasn't getting called. Can you try the PR dll and see if it works?


I'm no longer on PC. I'll check it out tomorrow, threads messing up is often times an easy fix so I'll see what I can do.

**Comment by ghost** [comment]
> > > There seems to be a bug with running looped commands at the moment. That is why all 3 of these solutions don't work.
> > 
> > 
> > What seems to be the issue? If there's anything I can help with
> 
> I'm not sure. I put some debug code into it to see if it was getting called and it wasn't getting called. Can you try the PR dll and see if it works?

I guess it's not fixed, I'm getting kicked out of the lobby while it's still idle.

**Comment by NjuuOwO** [comment]
ALT+TAB quick idle kick is also present, quite annoying.

**Comment by gir489returns** [comment]
If my newest push to the PR doesn't fix it then I give up and you guys will just have to seethe if you AFK because this is getting absurd.

**Comment by ScottiePimp** [comment]
> If my newest push to the PR doesn't fix it then I give up and you guys will just have to seethe if you AFK because this is getting absurd.

What was the issue? I'll try fixing it. Was it that the whole loop thread is broken? Or the globals not going into effect?

**Comment by Vali0004** [comment]
You could just yolo it and force the game to loop rejoin.

**Comment by ghost** [comment]
When I do alt+tab and wait a little on the desktop, I get kicked out of the lobby again.
[yimidletest.txt](https://github.com/YimMenu/YimMenu/files/12418606/yimidletest.txt)

**Comment by ghost** [comment]
after the change in #1963  , this feature was broken down. I don't have much technical knowledge, but can the files before that not be used ?

**Comment by lonelybud** [comment]
I am using https://github.com/YimMenu/YimMenu/commit/ee364cd684e85b6287b4034fed5d189fc29dbe94 build
and i dont see any kick issues. I was idle for hours
Stay in pause menu as well

**Comment by WorthIessPricetag** [comment]
I did testing on 81e43b5.  No idle kick works. 
I think Fullscreen mode in Gta settings makes it ineffective.
Same ppl suggested turning off "Pause game on focus loss " too.
[gta_settings.txt](https://github.com/YimMenu/YimMenu/files/12441934/gta_settings.txt)
[yim_settings.txt](https://github.com/YimMenu/YimMenu/files/12441935/yim_settings.txt)

**Comment by lonelybud** [comment]
> I did testing on [81e43b5](https://github.com/YimMenu/YimMenu/commit/81e43b51d7049a40b49d826d09bdc3828b1c7bb3). No idle kick works. I think Fullscreen mode in Gta settings makes it ineffective. Same ppl suggested turning off "Pause game on focus loss " too. [gta_settings.txt](https://github.com/YimMenu/YimMenu/files/12441934/gta_settings.txt) [yim_settings.txt](https://github.com/YimMenu/YimMenu/files/12441935/yim_settings.txt)

I play in windowed mod

**Comment by lonelybud** [comment]
i injected menu when i was in single player mode. then went online in friends only session of my own alone. I checked after an hour that I was kicked out. I dont know when i got kicked. Also i was playing in `graphics -> screen type -> windowed` and the game was paused

**Comment by Yimura** [comment]
Duplicate of #1977
