### ISSUE TITLE
[Request]: Extra for vehicules 

### ISSUE THREAD

**Issue by Shenmuee** [Yimura/YimMenu#2012]
### Solution

It would be nice to add in LS custom the possibility of removing and adding extras for vehicles

### Reason

because it's a bit annoying to save the vehicle and change the extras in the json files and then respawn it

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/142898234/eb5d71e6-bc5a-4e82-a3bd-3e1e9f436e06)

**Comment by gir489returns** [comment]
I had this in my LSC Customs menu, one of the big problems with this, is that the persistence layer that you save the cars in really only stores the extras once when you buy the vehicle. Changing them and then changing something on the car won't save it to your garage, this would really only be useful for new cars added to your garage with the LS Customs $2000 insurance method, or for crafting persisted cars.

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/assets/100792176/18986f54-4303-4706-95f0-b707a735a2d1

This car has 3 extras it was the most that I could remember.
