### ISSUE TITLE
Add Toggle & Hotkey Ability for Passive Mode

### ISSUE THREAD

**Issue by TwystedMind** [Yimura/YimMenu#2014]
### Problem

Could you create a toggle option to instantly enable/disable Passive Mode?  As well as the ability to set a hotkey to enable/disable Passive Mode?

### Solution

- A toggle (Checkbox) to enable and disable Passive Mode instantly.

- An option under the Hotkey settings to bind a key for enabling and disabling Passive Mode instantly.

### Reason

I don’t like enabling God Mode on myself and vehicles when I’m just moving around the city, I like the ability to go Passive when someone aggressive is approaching me and I don’t feel like interacting, then quickly disable once they’ve moved on.  Kiddions has the option to enable/disable Passive Mode instantly and bypass the 5 minute cooldown (this is honestly the only reason I’m using Kiddions at this point), but you cannot bind Hotkeys in Kiddions.

It would be really great to have the ability in YimMenu so that I didn’t have to co-load Kiddions and deal with the occasional crashes that Kiddions causes.

Thank you for your time and the work you all do!

**Comment by ScottiePimp** [comment]
*Global(1574582).As<bool*>() = true/false. 

That will enable/disable passive mode instantly.

**Comment by D-Borkan** [comment]
> _Global(1574582).As<bool_>() = true/false.
> 
> That will enable/disable passive mode instantly.

with yim menu be :
`		virtual void on_tick() override
		{
			*script_global(1574582).as<bool*>() = true;
		}

		virtual void on_disable() override
		{
			*script_global(1574582).as<bool*>() = false;
		}`

**Comment by D-Borkan** [comment]
> _Global(1574582).As<bool_>() = true/false.
> 
> That will enable/disable passive mode instantly.

with yim be
		virtual void on_tick() override
		{
			*script_global(1574582).as<bool*>() = true;
		}

		virtual void on_disable() override
		{
			*script_global(1574582).as<bool*>() = false;
		}

**Comment by D-Borkan** [comment]
> _Global(1574582).As<bool_>() = true/false.
> 
> That will enable/disable passive mode instantly.

with yim be :
		virtual void on_tick() override
		{
			*script_global(1574582).as<bool*>() = true;
		}

		virtual void on_disable() override
		{
			*script_global(1574582).as<bool*>() = false;
		}
