### ISSUE TITLE
[Improvement]: The ability to attract other players to the session.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2023]
### Which feature

To be honest, I did not understand what the "Player Magnet" function is for, but it would be nice to add a function that will allow you to attract other players to your session. For example, if we set the number of players to 30, then if someone leaves these players, then another would join in his place. Unless, of course, it depends on Rockstar's matchmaking servers or something like that. Once upon a time, I met a bug when I simply connected to the same player several times in a row just trying to find a random open session. I hope it's possible to do something similar if you know what I mean. Is it possible?

### Reason

Makes life a little easier by not changing the session every time the modder kicks everyone in the session or any other case when the players leave the game.

**Comment by WorthIessPricetag** [comment]
The player magnet is for attracting other players into your session. Set your desired number and the lobby will stay around that number as the other players join / leave.

**Comment by ghost** [comment]
> 
Apparently this function is not working properly

**Comment by FIying-Scotsman** [comment]
> > 
> 
> Apparently this function is not working properly

I haven't used it much but I believe it'll pull in players if they're looking for sessions themselves. It may also be region specific so if you're playing US for example, it'll may only pull in those players (could be wrong - this is from personal experience using it).

**Comment by ghost** [comment]
> > > 
> > 
> > 
> > Apparently this function is not working properly
> 
> I haven't used it much but I believe it'll pull in players if they're looking for sessions themselves. It may also be region specific so if you're playing US for example, it'll may only pull in those players (could be wrong - this is from personal experience using it).

I understand, but it is included that there is no players very rarely come in. Maybe once every 10 minutes. For example, when I set that there would be 30 players and there are 17 of them in the session, then the number of players will only decrease with time. Players enter the session with the same intensity as without this feature.

**Comment by WorthIessPricetag** [comment]
Can you post your settings.json?

**Comment by ghost** [comment]
> Can you post your settings.json?

[settings.txt](https://github.com/YimMenu/YimMenu/files/12443565/settings.txt)

**Comment by WorthIessPricetag** [comment]
I have a strong suspicion that this will be the issue:
![kebap](https://github.com/YimMenu/YimMenu/assets/140771500/5a8a318f-79da-4c54-83cc-afbf421cfa72)

**Comment by ghost** [comment]
> I have a strong suspicion that this will be the issue: ![kebap](https://user-images.githubusercontent.com/140771500/263398721-5a8a318f-79da-4c54-83cc-afbf421cfa72.PNG)

I turned off the RID block(Yes, I connected to the new one after turning off the RID block) and still I have been in a session of 18-20 checks for more than 10 minutes and the number does not rise above, but only decreases occasionally, one person can enter when 5 people leave before that. Does this feature work for you?

**Comment by WorthIessPricetag** [comment]
Mine is set to 25 and the lobby stays around 22-23 player most of the time. When i need a populated lobby i use the session browser to find one. I roll with these settings:

[settings.txt](https://github.com/YimMenu/YimMenu/files/12444160/settings.txt)

**Comment by ghost** [comment]
> Mine is set to 25 and the lobby stays around 22-23 player most of the time. When i need a populated lobby i use the session browser to find one. I roll with these settings:
> 
> [settings.txt](https://github.com/YimMenu/YimMenu/files/12444160/settings.txt)

it turns out that the function does not work properly and does not attract new players. they attach themselves even when this function is not enabled. Maybe it should be removed or fixed.

**Comment by Yimura** [comment]
Attracting more players isn't really possible, you're at the mercy of the match making servers.

As for what player magnet does is that it makes it more likely to join a match with that amount of players when looking for a session.

**Comment by lonelybud** [comment]
> Attracting more players isn't really possible, you're at the mercy of the match making servers.
> 
> As for what player magnet does is that it makes it more likely to join a match with that amount of players when looking for a session.

I believe you are referring that player magnet works when I am joining a session and it actually sorts the session according to specified count.
