### ISSUE TITLE
[Bug]: Lobby lock doesn't work?

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2024]
### Describe the bug

Players still join when Lobby lock option is enabled
Also the "allow friends to join locked session" checkbox doesn't show up

### Steps To Reproduce

1. Lobby lock ON
2. let somebody join

### Expected Behavior

don't join them

### Logs and/or screenshots

![image](https://github.com/YimMenu/YimMenu/assets/45913099/6c67e648-a177-4966-acc7-9c8808a6a6be)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by WorthIessPricetag** [comment]
As the infobox suggests: The function may not work on some modders.

**Comment by lonelybud** [comment]
you have to be host in order for this to work. Somebody correct if i am wrong

**Comment by ScottiePimp** [comment]
48 8B 0D ? ? ? ? 48 85 C9 74 10 48 8B 01 4D 8B C8 4C 8B C2 41 8B D2 48 FF 60 18 add(3).rip()

Take a look at this in IDA, feel free to add me on discord to ask for help if you get stuck. Essentially, this is the entry to PresenceData which you can use to block joins, even from modders. 

It is very simple and convenient. Only downside is it won't give you any info on the joining player without some further reversal. Credits goes to brunph for being the first to publish this. Good luck.

**Comment by maybegreat48** [comment]
> 48 8B 0D ? ? ? ? 48 85 C9 74 10 48 8B 01 4D 8B C8 4C 8B C2 41 8B D2 48 FF 60 18 add(3).rip()
> 
> Take a look at this in IDA, feel free to add me on discord to ask for help if you get stuck. Essentially, this is the entry to PresenceData which you can use to block joins, even from modders.
> 
> It is very simple and convenient. Only downside is it won't give you any info on the joining player without some further reversal. Credits goes to brunph for being the first to publish this. Good luck.

This was added to YimMenu months ago

**Comment by ScottiePimp** [comment]
> > 48 8B 0D ? ? ? ? 48 85 C9 74 10 48 8B 01 4D 8B C8 4C 8B C2 41 8B D2 48 FF 60 18 add(3).rip()
> 
> > 
> 
> > Take a look at this in IDA, feel free to add me on discord to ask for help if you get stuck. Essentially, this is the entry to PresenceData which you can use to block joins, even from modders.
> 
> > 
> 
> > It is very simple and convenient. Only downside is it won't give you any info on the joining player without some further reversal. Credits goes to brunph for being the first to publish this. Good luck.
> 
> 
> 
> This was added to YimMenu months ago

I'm aware that it's public but since you have a different method in YimMenu (which requires host), I assumed it's not in YimMenu anymore, so that's why I suggested it (because it doesn't require host since you're overriding gs_info)

But with a bit of reversal this method will do just fine, maybe even better than the current one (No idea what's used here), been using gs_info overriding for quite some time myself, no issues so far.

**Comment by lonelybud** [comment]
I have something noticed about lobby lock. The players who are not able to join you when lobby lock is on get stuck in cloud forever. I think this is very bad isn't.

**Comment by lonelybud** [comment]
> I have something noticed about lobby lock. The players who are not able to join you when lobby lock is on get stuck in cloud forever. I think this is very bad isn't.

the player goes in public session but gets stuck there

edit:  i blocked my friend from joining and he often tolds me that he is stuck in cloud. And then i have to go in his session and kick him out of it so that he is able to go to single player and not restart the game.

**Comment by lonelybud** [comment]
> Also the "allow friends to join locked session" checkbox doesn't show up

this is bcz the if check is wrong here -

https://github.com/YimMenu/YimMenu/blob/b28ce2188d4987a75e25fb067d1a40b257ab6717/src/views/network/view_network.cpp#L120

it should be like this - 

```C++
                        ImGui::Checkbox("LOBBY_LOCK"_T.data(), &g.session.lock_session);
			if (g.session.lock_session)
			{
				ImGui::Checkbox("LOBBY_LOCK_ALLOW_FRIENDS"_T.data(), &g.session.allow_friends_into_locked_session);
				if (ImGui::IsItemHovered())
					ImGui::SetTooltip("LOBBY_LOCK_ALLOW_FRIENDS_DESC"_T.data());
			}
```

**Comment by Yimura** [comment]
> this is bcz the if check is wrong here -
> 
> https://github.com/YimMenu/YimMenu/blob/b28ce2188d4987a75e25fb067d1a40b257ab6717/src/views/network/view_network.cpp#L120
> 
> it should be like this -
> 
> ```c++
>                         ImGui::Checkbox("LOBBY_LOCK"_T.data(), &g.session.lock_session);
> 			if (g.session.lock_session)
> 			{
> 				ImGui::Checkbox("LOBBY_LOCK_ALLOW_FRIENDS"_T.data(), &g.session.allow_friends_into_locked_session);
> 				if (ImGui::IsItemHovered())
> 					ImGui::SetTooltip("LOBBY_LOCK_ALLOW_FRIENDS_DESC"_T.data());
> 			}
> ```

Correct, this is an incredibly easy fix.
Odd that I missed that.

As for the lobby lock feature, it still makes use of the breakup kick command but that one only works as host and should normally fully disconnect the user. Perhaps we should swap it out with the multi-kick command.
