### ISSUE TITLE
List of vehicles that have extras?

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#2027]
### Which feature

With the addition of #2019 I was wondering if its possible to know the list of vehicles that have extra options

### Reason

Will make the feature easy to implement

**Comment by gir489returns** [comment]
A rule of thumb is, can you have it normally in SP. Generally, the cars in SP are the ones who use the extras. It is mostly used to toggle things like Mr. Strawberry Jam on the front of Trevor's car once you progress past that. And don't give me that spoilers bullshit on a 10-year-old game.

**Comment by gir489returns** [comment]
According to a program I wrote that scans vehicles.meta for vehicles that contain the word EXTRA in the <flags> field, these are all the models that have extras.

`ADDER
AIRBUS
ALPHA
APC
ARBITERGT
ARDENT
ARMYTANKER
ARMYTRAILER
ARMYTRAILER2
ASBO
ASEA
ASEA2
ASTRON
ASTRON2
AVISA
BAGGER
BALETRAILER
BALLER
BALLER2
BALLER3
BALLER4
BALLER5
BALLER6
BALLER7
BANSHEE
BANSHEE2
BARRACKS
BARRACKS2
BARRACKS3
BARRAGE
BENSON
BESTIAGTS
BFINJECTION
BIFF
BISON
BISON2
BISON3
BJXL
BLADE
BLAZER
BLAZER2
BLAZER3
BLAZER4
BLAZER5
BLISTA
BLISTA2
BLISTA3
BOATTRAILER
BOBCATXL
BODHI2
BOMBUSHKA
BOOR
BOXVILLE
BOXVILLE2
BOXVILLE3
BOXVILLE5
BRAWLER
BRICKADE
BRICKADE2
BRIOSO
BRIOSO2
BRIOSO3
BROADWAY
BRUTUS
BRUTUS2
BRUTUS3
BTYPE
BTYPE2
BUCCANEER
BUCCANEER2
BUFFALO
BUFFALO2
BUFFALO3
BUFFALO5
BULLDOZER
BULLET
BURRITO
BURRITO2
BURRITO3
BURRITO4
BURRITO5
BUS
CADDY3
CAMPER
CARACARA
CARACARA2
CARBONIZZARE
CARGOPLANE
CARGOPLANE2
CASCO
CAVALCADE
CAVALCADE2
CERBERUS
CERBERUS2
CERBERUS3
CHEETAH
CHEETAH2
CHERNOBOG
CHIMERA
CHINO
CHINO2
CINQUEMILA
CLIQUE
CLIQUE2
CLUB
COACH
COG55
COG552
COGCABRIO
COGNOSCENTI
COGNOSCENTI2
COMET3
COMET4
CONTENDER
COQUETTE
COQUETTE2
COQUETTE3
COQUETTE4
COUREUR
CRUSADER
CUTTER
CYCLONE
CYCLONE2
CYPHER
DEATHBIKE
DEATHBIKE2
DEATHBIKE3
DEITY
DELUXO
DEVESTE
DEVIANT
DILETTANTE
DILETTANTE2
DINGHY
DINGHY2
DINGHY3
DINGHY4
DLOADER
DOCKTRAILER
DOMINATOR
DOMINATOR2
DOMINATOR4
DOMINATOR5
DOMINATOR6
DRAFTER
DRAUGUR
DUBSTA
DUBSTA2
DUKES
DUKES2
DUKES3
DUMP
DUNE4
DUNE5
ELEGY
ELEGY2
EMERUS
EMPEROR
EMPEROR2
EMPEROR3
ENTITY2
ENTITY3
ENTITYXF
EVERON2
EXEMPLAR
F620
FACTION
FACTION2
FACTION3
FBI
FBI2
FCR2
FELON2
FELTZER2
FELTZER3
FLASHGT
FLATBED
FMJ
FORMULA
FORMULA2
FREECRAWLER
FREIGHTCAR2
FREIGHTCONT1
FREIGHTTRAILER
FUGITIVE
FURIA
FUSILADE
FUTO
FUTO2
GARGOYLE
GAUNTLET
GAUNTLET2
GAUNTLET3
GAUNTLET4
GAUNTLET5
GAUNTLET6
GBURRITO
GRANGER
GRANGER2
GRESLEY
HAULER
HAULER2
HELLION
HOTKNIFE
HOTRING
HUNTLEY
HUSTLER
IGNUS
IGNUS2
IMORGON
IMPALER
IMPALER2
IMPALER3
IMPALER4
IMPERATOR
IMPERATOR2
IMPERATOR3
INDUCTOR
INDUCTOR2
INFERNUS2
INGOT
INSURGENT
INSURGENT3
INTRUDER
ISSI2
ISSI7
IWAGEN
JACKAL
JB700
JB7002
JESTER
JESTER2
JETMAX
JOURNEY
JOURNEY2
JUBILEE
JUGULAR
KALAHARI
KAMACHO
KANJO
KANJOSJ
KHAMELION
KHANJALI
KOSATKA
KRIEGER
LANDSTALKER
LE7B
LGUARD
LIMO2
LM87
LONGFIN
LURCHER
MAMBA
MANANA
MANANA2
MARQUIS
MASSACRO
MASSACRO2
MENACER
MESA
MESA2
MESA3
METROTRAIN
MINITANK
MINIVAN
MINIVAN2
MIXER
MIXER2
MONROE
MONSTER
MONSTER3
MONSTER4
MONSTER5
MONSTROCITI
MOONBEAM
MOONBEAM2
MOWER
MULE
MULE2
NEBULA
NERO2
NIGHTSHADE
NIGHTSHARK
NINEF
NINEF2
NOVAK
OMNIS
OPENWHEEL1
OPENWHEEL2
ORACLE
ORACLE2
PACKER
PANTO
PARADISE
PARAGON
PARAGON2
PARIAH
PATRIOT
PATRIOT2
PATRIOT3
PBUS2
PENETRATOR
PENUMBRA2
PEYOTE
PEYOTE2
PEYOTE3
PFISTER811
PHANTOM
PHANTOM2
PHANTOM3
PHOENIX
PICADOR
POLICE
POLICE3
POLICE4
POLICEOLD1
POLICEOLD2
PONY
POSTLUDE
POUNDER
POUNDER2
PRAIRIE
PRANGER
PREMIER
PREVION
PRIMO
PRIMO2
PROPTRAILER
PROTOTIPO
RAKETRAILER
RANCHERXL
RANCHERXL2
RAPIDGT
RAPIDGT2
RAPIDGT3
RATBIKE
RATLOADER
RATLOADER2
REAPER
REBEL
REBEL2
REBLA
REGINA
REMUS
RENTALBUS
RETINUE
RETINUE2
REVOLTER
RHINO
RIATA
RIOT
RIOT2
RIPLEY
ROCOTO
ROMERO
RROCKET
RUBBLE
RUINER
RUINER2
RUINER3
RUINER4
RUMPO
RUMPO2
RUMPO3
RUSTON
S80
S95
SABREGT
SABREGT2
SADLER
SADLER2
SANDKING
SANDKING2
SAVESTRA
SCARAB
SCARAB2
SCARAB3
SCHAFTER2
SCHAFTER3
SCHAFTER4
SCHAFTER5
SCHAFTER6
SCHWARZER
SCORCHER
SCRAMJET
SCRAP
SEASHARK
SEASHARK2
SEASHARK3
SEMINOLE
SEMINOLE2
SENTINEL
SENTINEL2
SENTINEL3
SENTINEL4
SEVEN70
SHEAVA
SHERIFF
SHERIFF2
SKYLIFT
SLAMVAN4
SLAMVAN5
SLAMVAN6
SPECTER
SPECTER2
SPEEDER
SPEEDER2
SPEEDO
SPEEDO2
SPEEDO4
SPEEDO5
SQUALO
STALION
STALION2
STANIER
STINGER
STINGERGT
STOCKADE3
STRATUM
STREITER
STRETCH
STROMBERG
SUBMERSIBLE
SUBMERSIBLE2
SULTAN
SULTAN2
SULTAN3
SULTANRS
SUNTRAP
SUPERD
SURANO
SURFER
SURFER2
SURFER3
SURGE
TAHOMA
TAILGATER
TAILGATER2
TAMPA
TAMPA2
TAMPA3
TANKER
TANKER2
TANKERCAR
TAXI
TENF
TENF2
TERBYTE
TIGON
TIPTRUCK
TIPTRUCK2
TOREADOR
TORERO
TORERO2
TORNADO
TORNADO2
TORNADO3
TORNADO4
TORNADO5
TORO
TORO2
TOROS
TOURBUS
TOWTRUCK2
TR2
TR3
TR4
TRACTOR
TRACTOR3
TRAILERLARGE
TRAILERLOGS
TRAILERS
TRAILERS2
TRAILERS3
TRAILERSMALL
TRAILERSMALL2
TRFLAT
TROPHYTRUCK
TROPHYTRUCK2
TROPIC
TROPIC2
TULIP
TULIP2
TURISMO2
TURISMOR
TVTRAILER
TYRANT
UTILLITRUCK
UTILLITRUCK2
UTILLITRUCK3
VACCA
VAGRANT
VAMOS
VETIR
VIGERO
VIGERO2
VIRGO
VIRGO2
VIRGO3
VIRTUE
VISERIS
VOLTIC
VOLTIC2
WASHINGTON
WEEVIL
WEEVIL2
WINDSOR
WINDSOR2
WINKY
XLS
XLS2
YOSEMITE2
YOSEMITE3
YOUGA4
Z190
ZENO
ZENTORNO
ZHABA
ZION
ZION2
ZR350
ZR380
ZR3802
ZR3803`

Here's the program's source if you want to use it too:

`using System.Xml;

foreach (string filename in Directory.GetFiles("C:\\Users\\gir489\\Desktop\\Vehicles", "*.meta"))
{
    XmlDocument doc = new XmlDocument();
    doc.Load(filename);
    XmlNodeList nodes = doc.DocumentElement.SelectNodes("/CVehicleModelInfo__InitDataList/InitDatas/Item");
    foreach (XmlNode node in nodes)
    {
        if (node.SelectSingleNode("flags").InnerText.Contains("EXTRA"))
        {
            Console.WriteLine(node.SelectSingleNode("modelName").InnerText);
        }
    }
}`

**Comment by gir489returns** [comment]
Also, why is this an issue and not a discussion?
