### ISSUE TITLE
[Improvement]: Desync Kick Karma

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2030]
### Which feature

When I desync kick some modders, this kick backfires on me. 

Why shouldn't a similar feature be on the YimMenu ?

### Reason

You can't kick modders who ruin the session with other kick options other than desync kick because of their protection(if you are not a host).
If these modders are using desync kick karma for some reason, you will usually be kicked out of the session.

**Comment by WorthIessPricetag** [comment]
My well-tried method to get rid of modgriefers: First end session kick, works well on hosts too. Then start tutorial, no need to kick if they leave themself :) And if everything fails then desync. Personally i dont recommend multi-kick because it could easily trigger kick-karma.
