### ISSUE TITLE
[Bug]: Passive Mode Toggle Not Functioning Properly

### ISSUE THREAD

**Issue by TwystedMind** [Yimura/YimMenu#2031]
### Describe the bug

*I have attached a video showing the issues described, as well as my logs - I apologize in advance for the terrible compression, it took a lot of tweaking to get down to the 10MB limit for GitHub*

When toggling "Passive Mode", it does not place my character into Passive Mode fully.  The Weapon Wheel is disabled (as it should be), melee/punch is disabled (as it should be) and weapon cycling while in a vehicle is disabled (as it should be). 
 However, other players are still able to kill/make contact with me (which shouldn't be the case while in Passive Mode).  Also, while "Passive Mode" is toggled on in YimMenu, when opening the GTA Interactive Menu, "Disable Passive Mode" is greyed out, and a message is given saying, "Passive Mode is unavailable".

Once "Passive Mode" is disabled through YimMenu, other players are unable to kill/make contact with me (as if I'm now in Passive Mode).  Yet, the Weapon Wheel is enabled and melee/punch is re-enabled, yet I am unable to kill/make contact with other players.

Essentially, features are swapped.  Once "Passive Mode" is toggled on in YimMenu, all weapons and melee are disabled, but contact is still allowed by other players.  Yet, once "Passive Mode" is toggled off in YimMenu, all weapons and melee are re-enabled, but no physical contact is allowed towards or against other players.

The only way to fully deactivate Passive Mode once toggled "on" through YimMenu, is to toggle "off" in YimMenu, go to the GTA Interaction Menu, "Enable Passive Mode" then "Disable Passive Mode" and wait for the 30-second timer to count down.

### Steps To Reproduce

1.  Open YimMenu
2.  Go to "Self"
3.  Toggle "Passive Mode"

### Expected Behavior

Once toggled "on" (either by selecting the "Passive Mode" checkbox, or using a designated Hotkey), then Passive Mode should be enabled:

 - Kill/Physical Contact should be disabled (not working)
 - Weapon Wheel should be disabled (working)
 - Melee/Punch should be disabled (working)

Once toggled "off" (either by selecting the "Passive Mode" checkbox, or using a designated Hotkey), then Passive Mode should be disabled:

 - Kill/Physical Contact should be enabled (not working)
 - Weapon Wheel should be enabled (working)
 - Melee/Punch should be enabled (working)

### Logs and/or screenshots

```
<paste your logs here>
```

[cout.log](https://github.com/YimMenu/YimMenu/files/12447090/cout.log)

### Store

Steam

### Additional context

First off, I want to thank everyone who implemented the "Passive Mode" toggle into YimMenu so quickly.  I appreciate that very, very much!

Second, if you need me to add anything else, or provide any further details, please let me know and I'll be happy to help!

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

https://github.com/YimMenu/YimMenu/assets/142962424/7b97fc65-c87e-4c48-9b3d-d5e6fa075b3f

https://github.com/YimMenu/YimMenu/assets/142962424/b0209824-a517-42c2-a222-12e97b7cc29b

**Comment by NjuuOwO** [comment]
e24b0e15b21952188d94bd98db2c505570670b49

**Comment by NjuuOwO** [comment]
This bug doesn't occur for me on e24b0e15b21952188d94bd98db2c505570670b49
Can you test if any other occurs?

**Comment by NjuuOwO** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/45913099/69eb4fbe-6f41-4379-8cbd-d4e74e67413e)
This will run once but passive mode will still be present.
Anybody have idea how to remove it?

**Comment by TwystedMind** [comment]
In my opinion, I still believe that Passive Mode should still function as intended with the toggle in YimMenu (minus having to deal with the 30-second countdown upon Disabling, and the 5-minute cooldown once Disabled).

Meaning, Passive Mode should not be accessible when inside of a weaponized vehicle, when registered as a boss, etc.  Of course, I'm comparing Kiddions Modest Menu when speaking about the ability to instantly Enable/Disable Passive Mode - in that particular case, when inside of a weaponized vehicle, and I Enable Passive Mode instantly in Kiddions, the weaponized vehicle automatically stops and force exits me from the vehicle.  If I re-enter the weaponized vehicle while in Passive Mode, the game instantly Disables Passive Mode (without the 30-second countdown timer).

I'm by no means trying to imply that if the feature doesn't work exactly like it does in Kiddions that it's incorrect; I'm just using the way the feature is setup as a reference to what happens.

Ultimately, so long as Passive Mode can be Enabled/Disabled instantly with no 30-second countdown window (temporary or otherwise) or any sort of cooldown period, I think everyone, including myself will be very happy.

Hopefully this provides some sort of help or clarification.  My coding knowledge personally, is certainly considered "beginner".  Thank you *so so* much for taking the time to figure this out!  You guys are amazing!

**Comment by ScottiePimp** [comment]
> ![image](https://user-images.githubusercontent.com/45913099/263540769-69eb4fbe-6f41-4379-8cbd-d4e74e67413e.png) This will run once but passive mode will still be present. Anybody have idea how to remove it?

Set this tunable to 0. 
Global_262145.f_27371

**Comment by NjuuOwO** [comment]
> Set this tunable to 0. Global_262145.f_27371

I've found it before, but thanks.
Are you able to find function which turns off passive when entering weaponized vehicle? I'm unable to find it after 2 hours of searching ;\

**Comment by NjuuOwO** [comment]
> Meaning, Passive Mode should not be accessible when inside of a weaponized vehicle, when registered as a boss

I disabled toggling it whilst in ceo/mc, and it's switchable in weap. vehicles. You just can't shoot their projectiles.
Please test 72f3812e311a0c9f60cd5ed57575181eb768691c (#2040) if there are any other bugs (idk if bot will compile it auto or how it works)

**Comment by TwystedMind** [comment]
It's been a couple of days and I haven't seen the bot do an auto-pull/compile.  Should I manually add/remove the code mentioned in this ticket and build the menu myself to test?  Or is there another method I can attempt?

**Comment by NjuuOwO** [comment]
@TwystedMind
It's available here - https://github.com/YimMenu/YimMenu/issues/2040#issuecomment-1694746181
