### ISSUE TITLE
[Request]: search bar for persistent vehicles

### ISSUE THREAD

**Issue by UnionProject** [Yimura/YimMenu#2050]
### Problem

I have almost 200 saved vehicles, and it's getting hard to find what you need on that list.

### Solution

just a search bar, like in personal vehicle tab, or new vehicle tab, where you can type something and it will show cars that have this name. If i type overflod, it will show all cars with the name overflod that i saved for example.

### Reason

This should simplify and improve the user experience.

**Comment by gir489returns** [comment]
Why not just put them into folders? #2042
