### ISSUE TITLE
[Request]: Repair someones vehicle button

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2052]
### Solution

Add a "Repair Vehicle" in Player->Vehicle tab

### Reason

Vehicle shouldn't be only for toxic stuff ig

**Comment by spinoza-spinoza** [comment]
in left down    side   there is     "fix vehicle "  you can repair players car

**Comment by NjuuOwO** [comment]
i legit did not see that

**Comment by spinoza-spinoza** [comment]
you can also use special weapon    "repair gun"    you shot to each destroyed car it will be repaired
