### ISSUE TITLE
[Bug] курсор мышки все время посередине когда включаю чит

### ISSUE THREAD

**Issue by rGDHwUp** [Yimura/YimMenu#2056]
### Describe the bug

в гта все норм когда включаю чит курсор не смещается с середины и я немогу ничего включить выключить в чите что делать

### Steps To Reproduce

.

### Expected Behavior

.

### Logs and/or screenshots

```
<paste your logs here>
```
.

### Store

Steam

### Additional context

.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Not English sorry.
