### ISSUE TITLE
[Bug]: teleport to land surface failed

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2059]
### Describe the bug

When i tried to teleport (first time) on beach land area at the location as shown in video I teleported in the sea water -

<details><summary>Video</summary>

https://github.com/YimMenu/YimMenu/assets/139460769/02aaae3d-fa3a-4662-87b4-85621714dd67
</details>

when i teleported again (second time), It went well and i was on the wooden built surface above the sea.

<details><summary>Video</summary>

https://github.com/YimMenu/YimMenu/assets/139460769/a658c93e-ed08-4003-8b2d-7807a58c0e5b
</details>

### Steps To Reproduce

1 Start game fresh.
2 When going online be at a place far away from teleport location mentioned  in above video.
3 Try to teleport to the given location in video.

### Expected Behavior

Should be able to teleport to ground above the sea and not in sea.

### Logs and/or screenshots

no warning or error

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I cannot understand a single thing you said.

**Comment by lonelybud** [comment]
did you saw the video. as you can see when i teleported first i went in water. When i teleported again second time i was on wooden floor above the water. I have also added step to reproduce. Should i send you the coordinate to teleport to?

**Comment by lonelybud** [comment]
dont worry about the *Additional context*. It means that i was using latest build thats all

**Comment by lonelybud** [comment]
I updated the description again.

**Comment by Peax** [comment]
The bug is your PC not being fast enough to load in the assets. I doubt you can reproduce this when teleporting from nearby.

**Comment by lonelybud** [comment]
> The bug is your PC not being fast enough to load in the assets. I doubt you can reproduce this when teleporting from nearby.

try this build https://github.com/YimMenu/YimMenu/commit/ee364cd684e85b6287b4034fed5d189fc29dbe94
its working fine.

**Comment by Yimura** [comment]
Unable to reproduce, most likely occurs because of your PC being slow in loading in the data of the pier.

**Comment by lonelybud** [comment]
cool. no worries. it occurs at these special places only. I will close this.
