### ISSUE TITLE
[Bug]:Game Crashes After Injection

### ISSUE THREAD

**Issue by KiymaliBorek2** [Yimura/YimMenu#2062]
### Describe the bug

I use Xenos and when I inject Yumi it crashes. ( I have the latest version)

### Steps To Reproduce

1-Put Yumi on Xenos
2-Press Inject
3-It crashes (No Error)

### Expected Behavior

Expected to work

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

I dont know what the last one means

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
What does the event manager say?

**Comment by KiymaliBorek2** [comment]
> What does the event manager say?

nothing the game just closes

**Comment by gir489returns** [comment]
> nothing the game just closes

That’s not what I asked. If there was a crash it should be in the event manager. If the game is silently exiting then there’s something wrong with your copy of GTA.

**Comment by Yimura** [comment]
It might also have something to do with the injection settings he has in Xenos injector.

@KiymaliBorek2 do you have the injection set to Native Inject in Xenos?

**Comment by KiymaliBorek2** [comment]
> > nothing the game just closes
> 
> That’s not what I asked. If there was a crash it should be in the event manager. If the game is silently exiting then there’s something wrong with your copy of GTA.

Yes its just silently exiting when I press Inject like you said but I tried deleting it and download it again so I dont think I have a problem with my copy. I think it has to do smth with the script. I tried to find the older versions but it was just the latest one.

**Comment by KiymaliBorek2** [comment]
> It might also have something to do with the injection settings he has in Xenos injector.
> 
> @KiymaliBorek2 do you have the injection set to Native Inject in Xenos?

Native Inject?

**Comment by NjuuOwO** [comment]
> Native Inject?

Advanced -> Injection type: Native inject

**Comment by tiCkuhAr** [comment]
> > It might also have something to do with the injection settings he has in Xenos injector.
> > @KiymaliBorek2 do you have the injection set to Native Inject in Xenos?
> 
> Native Inject?

You can check what injection type you are using by pressing Advanced

**Comment by KiymaliBorek2** [comment]
> > > It might also have something to do with the injection settings he has in Xenos injector.
> > > @KiymaliBorek2 do you have the injection set to Native Inject in Xenos?
> > 
> > 
> > Native Inject?
> 
> You can check what injection type you are using by pressing Advanced

thx

**Comment by KiymaliBorek2** [comment]
> > Native Inject?
> 
> Advanced -> Injection type: Native inject

thanks

**Comment by KiymaliBorek2** [comment]
> It might also have something to do with the injection settings he has in Xenos injector.
> 
> @KiymaliBorek2 do you have the injection set to Native Inject in Xenos?

Yeah I have It In native Inject

**Comment by GTMoraes** [comment]
Weirdly enough, I once had this issue.

I *think* it had to do with the cout.log being opened, and the menu unable to write over it.             
I am, like, 99% sure that was the cause. I closed the notepad and the menu started opening like before.

I'm not sure if that's the error OP is experiencing, but sounds like it.

**Comment by KiymaliBorek2** [comment]
> Weirdly enough, I once had this issue.
> 
> I _think_ it had to do with the cout.log being opened, and the menu unable to write over it. I am, like, 99% sure that was the cause. I closed the notepad and the menu started opening like before.
> 
> I'm not sure if that's the error OP is experiencing, but sounds like it.

With the new update it started working but thx for the help anw
