### ISSUE TITLE
[Request]: Send ingame private message

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2064]
### Solution

Add a "Send Ingame PM" typebox/button in player tab, which sends message to someone as it is done through phone ingame

### Reason

It's cool addition to send inside game PMes (without cooldown preferably), and not be limited only to SC PMs

### Additional context

It's available only if voice chat is enabled
![send message](https://github.com/YimMenu/YimMenu/assets/45913099/cb741c12-2fd9-4711-9b87-4263538cf1e4)
It looks like this (example no friends to test sadge)
![image](https://github.com/YimMenu/YimMenu/assets/45913099/633e09ff-14a0-4588-a27a-03d3e35110aa)

**Comment by gir489returns** [comment]
>Furry owo name
>No friends.
NOT BIG SURPRISE

**Comment by NjuuOwO** [comment]
bruh i had no idea cuz it was taken didn't think i would use github D:

**Comment by ScottiePimp** [comment]
This was patched, it only works now if you send it to a friend. You can thank the advertisers for that.

**Comment by NjuuOwO** [comment]
> This was patched, it only works now if you send it to a friend. You can thank the advertisers for that.

Okay, but then what method would it be to send it to friend?

**Comment by Yimura** [comment]
Most likely by using this native:
https://natives.gta.menu/natives/0x3A214F2EC889B100
