### ISSUE TITLE
[Bug]: Mouse stucked?

### ISSUE THREAD

**Issue by JonathanDiez** [Yimura/YimMenu#2070]
### Describe the bug

Sorry for my eng, when I try open with insert key my mouse get stucked and I cant move it :(, is on the same point all time.

### Steps To Reproduce

just press insert

### Expected Behavior

move the mouse for open the menu, I just can move the menu when I open social club with Start key

### Logs and/or screenshots

I dont know how to generate logs rry

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Go into settings and change your mouse input setting to raw.
