### ISSUE TITLE
[Bug]: persistent car preview is glithing

### ISSUE THREAD

**Issue by UnionProject** [Yimura/YimMenu#2077]
### Describe the bug

When you spawn a saved transport, there is a still residual preview that you can't interact with, other players can see it.
Also, when selecting a car, other players also see the preview, as well as the mod menu user himself.

### Steps To Reproduce

1. Go in Spawn vehicle > Persistent
2. Turn on "preview" option
3. Spawn any saved vehicle

### Expected Behavior

Previews should not remain in the world after you spawn a vehicle. The preview should not be seen by other players at all

### Logs and/or screenshots

```
<paste your logs here>
```
![Screenshot_99](https://github.com/YimMenu/YimMenu/assets/47482956/faa6e280-02a0-43b1-8f09-abac0a58875b)
![my friend screen](https://github.com/YimMenu/YimMenu/assets/47482956/58e499e7-c001-4253-ae5d-7205bc975514)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by FIying-Scotsman** [comment]
While the vehicle could be removed after you spawn it - it’s not possible to hide it from other players to my knowledge and making it invisible to other players only (I.e via alpha) isn’t possible either as it would be invisible to you only (R* already patched this to stop players setting their own models invisible).

It’s similar to CLEO in San Andreas - the vehicle is spawned into the world as an alternative to an image like other native menus can use (in yimmenu’s case this is because drawing game textures onto the DX overlay is needlessly complicated).

**Comment by gir489returns** [comment]
I’m not going to fix this.

**Comment by Yimura** [comment]
~~The vehicle is most likely being spawned as networked, if we spawn it non-networked it won't be visible to others in the session.~~

Nvm the vehicle seems to be spawned properly non-networked.

**Comment by gir489returns** [comment]
> Nvm the vehicle seems to be spawned properly non-networked.

The problem is he's the host, and it's syncing to other players, we'd have to setup the cars to not get sync 'd to other players and I'm not going to do that shit.

**Comment by Yimura** [comment]
> The problem is he's the host, and it's syncing to other players, we'd have to setup the cars to not get sync 'd to other players.

Hmmm odd, I have never seen this bug appear in all this time of me using YimMenu.
Though it could be because I never really force myself to become host of a session.

**Comment by gir489returns** [comment]
> Hmmm odd, I have never seen this bug appear in all this time of me using YimMenu. Though it could be because I never really force myself to become host of a session.

I'd imagine you also don't go "HEY CAN YOU SEE THIS CAR SPINNING" either. Most people are just so jaded/checked out to random crap happening in GTA it's become normal.

**Comment by UnionProject** [comment]
The problem shows up either way, whether I host or not. The only thing im interested in gta is car meets, so this bug is annoying for me and some others people in the session. Lately i dont see the remaining preview projection after spawning a car, but the preview when selecting is still just annoying.
