### ISSUE TITLE
[Bug]: Changing player model results in player weapons vanishing/disappearing

### ISSUE THREAD

**Issue by naxce** [Yimura/YimMenu#2078]
### Describe the bug

I lost every weapon and i cant buy most of them after changing player model

### Steps To Reproduce

1. Change Playermodel to something else
2. Kill yourself to get your model back

### Expected Behavior

Not lose all weapons when changing playermodel or be able to rebuy it 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [x] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
#2002 also relates to same problem. Changing model will remove all your weapons. Current solution I guess is to rejoin same lobby.

**Comment by Tayipc38** [comment]
I recall @gir489returns adding some sort of persist weapons or something, couldn't that be used to circumvent this?

**Comment by gir489returns** [comment]
> I recall @gir489returns adding some sort of persist weapons or something, couldn't that be used to circumvent this?

Yes.

**Comment by lonelybud** [comment]
> I recall @gir489returns adding some sort of persist weapons or something, couldn't that be used to circumvent this?

![image](https://github.com/YimMenu/YimMenu/assets/139460769/ce123b9d-1d09-48a2-8924-32fe4e739f40)

so one can save the current weapon loadout. Here i enabled persistent weapon and then saved my loadout with name `main` say.
Then change the model.
Then apply that saved loadout.
Get the weapons back.

**Comment by Tayipc38** [comment]
> so one can save the current weapon loadout. Then change the model. Then apply that saved loadout. Get the weapons back.

Are you announcing this works or looking for validation? If this works be sure to close this issue with a confirmation helping any other person that might look for a fix.

**Comment by lonelybud** [comment]
> > so one can save the current weapon loadout. Then change the model. Then apply that saved loadout. Get the weapons back.
> 
> Are you announcing this works or looking for validation? If this works be sure to close this issue with a confirmation helping any other person that might look for a fix.

this is working. the persist weapon feature. I just explained how to do it. Please close the issue.
