### ISSUE TITLE
Automatically regenerate settings.json

### ISSUE THREAD

**Issue by GeopJr** [Yimura/YimMenu#208]
**Is your feature request related to a problem? Please describe.**
[Searching for `settings.json` on issues](https://github.com/Yimura/YimMenu/search?q=settings.json&type=issues) we can see that a big portion of the solutions is "Try removing your settings.json".

**Describe the solution you'd like**
Automatically regenerate `settings.json` if YimMenu is unable to parse it. Probably also keep a backup on `settings.json.bak` if it parsed it successfully.

**Provide Reasoning**
It would drop bug reports significantly as more often than not, just regenerating it fixes them. 

**Additional context**
There are more reports where the solution was to just regenerate it on the Discord community.

**Comment by GeopJr** [comment]
Quick flowchart of the initial plan:

![Flowchart of the plan](https://user-images.githubusercontent.com/18014039/168484442-132dc842-5f75-4496-8065-945e96408a39.svg)

(might not be 100% visible on dark backgrounds)

**Comment by Yimura** [comment]
It's a weird bug because the parser should recover if it fails to parse the JSON and just straight up overwrite the file with the defaults, seems there's some other edge case bug that only some people experience...

If someone has a JSON file that causes it we might be able to look into why this problem occurs.

**Comment by Yimura** [comment]
Bug hasn't appeared in quite a while, seems like it was more related to people running older versions of YimMenu and then suddenly updating.
