### ISSUE TITLE
[Bug]: the seat belt does not work

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#2082]
### Describe the bug

The seat belt doesn't work, the motorcycle hits an obstacle, the character still falls off the car, is my method of operation wrong? Or do I need to trigger a pre-condition to use my seat belt? My version is [c459ccc]

### Steps To Reproduce

the seat belt does not work, the motorcycle crashes into the obstacle, the character will still fall from the vehicle

### Expected Behavior

After starting this feature, the character should not fall off the car

### Logs and/or screenshots

```
<paste your logs here>
```
![Uploading IMG_7956.png…]()

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by NjuuOwO** [comment]
I can confirm this problem occurs on 1594ee1f7680731dd20c0aa194bc61137b9ebf72. 

https://github.com/YimMenu/YimMenu/blob/1594ee1f7680731dd20c0aa194bc61137b9ebf72/src/backend/looped/vehicle/seatbelt.cpp#L19

This will set value correspodning to this enums:
```
enum eKnockOffVehicle
{
	KNOCKOFFVEHICLE_DEFAULT, // = 0 = false
	KNOCKOFFVEHICLE_NEVER, // = 1 = true
	KNOCKOFFVEHICLE_EASY, // = 2
	KNOCKOFFVEHICLE_HARD // = 3
};
```

**Comment by lonelybud** [comment]
i am riding a bicycle and seat belt is not working can confirm this on latest build
