### ISSUE TITLE
[Request]: Toggle Unlocks

### ISSUE THREAD

**Issue by SmRzT** [Yimura/YimMenu#2087]
### Problem

All items (or atleast for cars) are unlocked and no longer have a requirement of somekind when the menu is loaded and as a person who kinda just uses the menu for protection it would be cool if this was a toggleable option as i dont see one

### Solution

add a toggle unlocks button in the settings

### Reason

id like to somewhat play normally

### Additional context

![Without](https://github.com/YimMenu/YimMenu/assets/79432172/4250cb7e-63a2-441c-83b7-4569f8b02d8c)
Without Yim ^
With Yim v
![With](https://github.com/YimMenu/YimMenu/assets/79432172/00ba0039-6f62-473d-a58c-1568ad76b766)

**Comment by gir489returns** [comment]
This is considered recovery, and since Yim does not support that, this will be closed. Also, you can bypass this by just using the LSC reimplementation Yim has, but it will not save to your car (because we don't support recovery.)

**Comment by SmRzT** [comment]
May i ask why/for more detail?

Yim alr unlocks them so surely that counts as recovery already so why not an option to disable that feature of yim?

This character is lvl4 so none of that should be unlocked (on personal vehicle)and I'd prefer it to not be unlocked... but yet Yim unlocks it all

**Comment by Yimura** [comment]
This technically doesn't modify anything on your account directly it just tells the LS Customs that you have earned those unlocks already.

You're right, tho. This shouldn't be enabled by default.

As to why, I had a level 1 account and wanted to install some mods on them without forcing those stats to be saved on my account so instead I just told this singular script that I had it enabled.

**Comment by SmRzT** [comment]
Gotcha, thanks for the clarity :D
