### ISSUE TITLE
[Bug]: When playing with friends in a mission, other players cant drive any car sometimes

### ISSUE THREAD

**Issue by 0xfalls** [Yimura/YimMenu#2088]
### Describe the bug

When playing with friends in a mission, other players cant drive any car sometimes

### Steps To Reproduce

?

### Expected Behavior

?

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
This is a game related issue.
Especially in apartment heist missions, some players complain that their vehicles cannot move. This problem was happening to me before using the menu.

The solution that works for me is to get away from that frozen player with any tool in the game.

**Comment by gir489returns** [comment]
Yeah I remember also the regular heist missions did this shit too, like breaking Pavlov out of jail, he would get stuck in the prison yard and nobody could get in a car. This is just regular Rockstar bullshit, nothing we can do, unless we start introspecting situational bugs that we can't reliably reproduce (akin to madness).
