### ISSUE TITLE
[Bug]: The game entered single player mode abnormally

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#2089]
### Describe the bug

Sometimes match the multiplayer game will not match others, even if you re-inject, the game can not match anyone, I do not know what is the reason, maybe in the battle by other players attacked, or kicked out of the battle, sometimes there will be this situation, can not match anyone normally, I uploaded the log, hope it will help

### Steps To Reproduce

, I do not know what is the reason, maybe in the battle by other players attacked, or kicked out of the battle,

### Expected Behavior

Join the game normally and match with other players instead of entering single player mode

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12520545/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Log files are in Chinese, user is using a modified version of YimMenu.
Make sure you verify the issue exists on an unmodified version of YimMenu (from Github).
