### ISSUE TITLE
Cant use veichle spawner[Bug]: 

### ISSUE THREAD

**Issue by MONSTER123e** [Yimura/YimMenu#2092]
### Describe the bug

for some reason when i try to use spawn veichle it doesnt work and no cars shows up it just says no veichle in registry

### Steps To Reproduce

go to veichle in the menu then click spawn veichle and i dont see anything idk why i recently got this from a friend

### Expected Behavior

me being able to use it lol 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
How about a log? It's there in the request for a reason.

**Comment by Yimura** [comment]
Screenshots or logs?

**Comment by xiaoxiao921** [comment]
They using steam so it probably the rpf reader not working

**Comment by Yimura** [comment]
I wonder if it has something to do with if the game is installed to a different Steam library folder than the default common one used by Steam.

**Comment by Yimura** [comment]
I installed GTA V on another Windows drive and was able to generate the cache correctly. I wonder if it has something to with the disk speed or some other obscure reason that causes the caching to fail?

@MONSTER123e do you have GTA V installed on HDD or SSD? What speed is the drive rated for? What language is your Windows installation set to?

**Comment by Yimura** [comment]
No answer from issue author, closing.
