### ISSUE TITLE
[Bug]: invalid sector position (sector node) crash false positive

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2096]
### Describe the bug

Invalid sector position (sector node) crash false positive spam during auto shop contract "superdollar." 

Occurs as non-host player upon returning to the city after attacking the MOC until mission ends. Spams log and notifications constantly. 

### Steps To Reproduce

1. Join auto shop contract "superdollar" through game phone via quickjoin, or reproduce with another player.
2. Proceed with mission until directed to deliver the bank plates to the drop-off. 
3. Once reaching the city the log and notifications are spammed with "invalid sector position (sector node) crash" false positive.

### Expected Behavior

Lack of false positives.

### Logs and/or screenshots

[redacted_cout.txt](https://github.com/YimMenu/YimMenu/files/12544677/redacted_cout.txt)

### Store

Steam

### Additional context

Haven't been quickjoining much lately but could possibly happen in other missions, contracts, and heists. Only noticed in "superdollar" so far. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
@maybegreat48

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/29fdb5c3bca874ff01f1c7cd97c570541120d1f3/src/hooks/protections/can_apply_data.cpp#L1315

It is probably because of this.

**Comment by gir489returns** [comment]
@freemantsinq Please try PR#2103 and see if it fixes the issue.

**Comment by maybegreat48** [comment]
> @maybegreat48 Why aren't we checking CPlayerSectorPosNode and should we check it in this datanode?

The game calculates object positions using `CPlayerSectorPosNode` and `CSectorDataNode`. The crash occurs if the sector is 712 or above but can also occur when it is 711 if certain conditions are met in `CPlayerSectorPosNode`. I haven't tested the PR yet but `sector_node->m_pos_x` and `sector_node->m_pos_y` stores sectors and not object positions

**Comment by gir489returns** [comment]
>I haven't tested the PR yet but `sector_node->m_pos_x` and `sector_node->m_pos_y` stores sectors and not object positions

Correct, which is why I'm doing the conversion from sector to cartesian coordinates, then checking if it's out of bounds. It is also possible that the calculation could pass, but CPlayerSectorPosNode pushes it just out of bounds causing it to crash. Is there a way to get the sector offset from CPlayerSectorPosNode within the CSectorDataNode? I don't see how to currently since we're not given the tree inside of check_node, unless the tree is cached somewhere.

**Comment by maybegreat48** [comment]
> > I haven't tested the PR yet but `sector_node->m_pos_x` and `sector_node->m_pos_y` stores sectors and not object positions
> 
> Correct, which is why I'm doing the conversion from sector to cartesian coordinates, then checking if it's out of bounds. It is also possible that the calculation could pass, but CPlayerSectorPosNode pushes it just out of bounds causing it to crash. Is there a way to get the sector offset from CPlayerSectorPosNode within the CSectorDataNode? I don't see how to currently since we're not given the tree inside of check_node, unless the tree is cached somewhere.

You have to iterate all nodes in the tree and select `CPlayerSectorPosNode`

**Comment by gir489returns** [comment]
> You have to iterate all nodes in the tree and select `CPlayerSectorPosNode`

That sounds like a pain in the ass.

**Comment by Tayipc38** [comment]
> On another issue I'm currently having: I am getting multiple crashes lately.... blablabla

This ticket does not appear to be the place for this, any research and requests regarding this either deserves its own ticket or a discussion thread. That being said, this sounds bizarre and interesting if it has any truth to it.

**Comment by xiaoxiao921** [comment]
Any talk about crashes without logs is worthless

**Comment by gir489returns** [comment]
> This ticket does not appear to be the place for this, any research and requests regarding this either deserves its own ticket or a discussion thread. That being said, this sounds bizarre and interesting if it has any truth to it.

I'd argue it's very apropos to this ticket. This ticket and its subsequent PR modifies a crash protection. If that crash protection is failing now due to the new code, then we need to address that. However, as Xiao mentioned, we need a crash log to show where it is crashing.

**Comment by gir489returns** [comment]
> Unforunately I haven't had much luck getting into a superdollar contract to test the same conditions that led to this bug report. Still testing.

You're not on the clock here. Test it when you can.

**Comment by gir489returns** [comment]
We still have to address the CPlayerSectorPosNode issue, it's just a matter of if I'm going to do it or if @maybegreat48 is going to do it.

**Comment by gir489returns** [comment]
I have implemented the CPlayerSectorPosNode code, and it should now be fully fixed and properly checking for the crash, but not rejecting normal syncs.

**Comment by gir489returns** [comment]
CSectorDataNode can only crash you if you're the host, I think. @maybegreat48 is there a scenario that you would receive this sync packet while not being host? Maybe extraneously?

**Comment by gir489returns** [comment]
@freemantsinq PR #2096 has been opened with the debugging code I had before I removed it without checking if it works, as I couldn't figure out how to fire the event maliciously. If you can cause the mission to occur again and log it with the new code, it should tell us what's wrong.

**Comment by gir489returns** [comment]
> That binary will not quickjoin. Attempted three times.
> 
> [230916_0946_redacted_cout.log](https://github.com/YimMenu/YimMenu/files/12641207/230916_0946_redacted_cout.log)

X: -1404 Y: 108 player_sector_pos_x: 52.2857 player_sector_pos_y: 48.211

Unless I suck at math, (((-1352 + 149) + 8192) / 75) should resolve to 93, which is below 255.
And (((156 + 149) + 8192) / 75) should resolve to 113. Also below 255.

There may be something lost in translation with the compiler. I'll have to investigate it.

**Comment by gir489returns** [comment]
@freemantsinq Turns out I just suck at math. 😐

Please try #2136 again.

**Comment by gir489returns** [comment]
> Also fails to quickjoin. Attempted once.
> 
> [230916_1030_redacted_cout.log](https://github.com/YimMenu/YimMenu/files/12641280/230916_1030_redacted_cout.log)

😩🔫 

I forgot to change out is_x_invalid's calculation to use x_pos not the parameter. Give #2136 another go please.

**Comment by gir489returns** [comment]
> This one did work. Here's the log after playing one superdollar:
> 
> [230916_1136_redacted_cout.log](https://github.com/YimMenu/YimMenu/files/12641395/230916_1136_redacted_cout.log)

It worked? The log is filled with blocked crashes, though. All of them are invalid, though, meaning they would crash you if executed.

**Comment by gir489returns** [comment]
> Are you saying these are not false positives?

I'm asking you. You said "This one did work."

**Comment by gir489returns** [comment]
> I am of the opinion that they are false positives.

I added an additional check to only apply the OOB check on player data nodes, as they're the only ones that can cause the crash. Please try #2136 again.

**Comment by xiaoxiao921** [comment]
How long did you play before getting the ALLOC crash?

**Comment by xiaoxiao921** [comment]
I'm stupid, just realized that info was in the log file, looks like you played for 5hours at least, my understanding is that we are still blocking some ac callbacks that still use the game allocator,  just it happens at a much slower rate than before, repro-ing this is gonna be extremely annoying (we will basically need to play for hours and hours just to gather some debug data that in the long run will allow us to finally fix it for good), idk if we'll ever bother
