### ISSUE TITLE
[Bug]: "force relay connections" break restart

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2100]
### Describe the bug

If "force relay connections" is enabled and during a mission, contract, or heist, there is a restart condition then the mission becomes unplayable. Either the player becomes stuck in the clouds or objectives do not register as complete. Only tested as non-host during quickjoin. 

### Steps To Reproduce

0. Enable "force relay connections" under protections.
1. Quickjoin mission, contract, or heist as non-host (not tested as host) or recreate with another player.
2. Fail the mission, contract, or heist.
3. Restart.
4. Mission, contract, or heist is now unable to be completed. 

### Expected Behavior

Restart should not break from relay connections. Relay connections are part of the game and do not normally break anything. 

### Logs and/or screenshots

Bug does not present itself through the log.

### Store

Steam

### Additional context

Only tested as non-host. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
And it did not do that without force relay connections?

**Comment by Yimura** [comment]
The Force Relay Connections settings should've never been enabled by default, I propose the following changes:
- Change the description of the feature to note that some missions will break and may you or other players to appear laggy
- Change the default from `true` to `false`

**Comment by xiaoxiao921** [comment]
Idk it's obvious too but it should probably say that what it does is hiding your ip
