### ISSUE TITLE
[Bug]: Join CEO

### ISSUE THREAD

**Issue by ToXicVibezz** [Yimura/YimMenu#2105]
### Describe the bug

When i try to use `Join Ceo` , it gives me a error about freemode and my player becomes invisible or cant move .

### Steps To Reproduce

1. Select Player
2. Misc
3. Join CEO
4. Results:: <  ...  >

### Expected Behavior

To join the CEO successfully

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
>  it gives me a error about freemode

Are you coloading YimMenu with something else?

**Comment by ToXicVibezz** [comment]
> > it gives me a error about freemode
> 
> Are you coloading YimMenu with something else?

I do not .. Buu this is new problem as up last cpl days .. i was unsure if maybe something had updated.. maybe i need to update my ver of yim

**Comment by ToXicVibezz** [comment]
Im not sure it hasnt happened since i rebuilt . also was not in stable yim release. Sorry for late response time.
