### ISSUE TITLE
[SOLVED] Lua take vehicle control

### ISSUE THREAD

**Issue by Bradly7412** [Yimura/YimMenu#2109]
I am unsure of how to take control of another users vehicle as right it seems to be client side and not effect the other user. I was looking in the commands thing and saw something about `entity::take_control_of(vehicle)` but unsure of how to use it in Lua instead

**Comment by gir489returns** [comment]
This is used to pilot their vehicle. There’s a tooltip that explains it under the toxic tab for their vehicle.

**Comment by Bradly7412** [comment]
But how would i do the same effect / control in the Lua API?

**Comment by gir489returns** [comment]
Yim manually calls the take control function but does not expose a way to invoke it from the Lua layer. This needs to be upgraded to a feature request.
