### ISSUE TITLE
[Bug]: Crash when selecting "Vehicle Fun" in Chinese

### ISSUE THREAD

**Issue by George0828Zhang** [Yimura/YimMenu#2114]
### Describe the bug

When using Chinese Traditional or Simplified for the menu language, then entering vehicle fun features, the game crashes to desktop. 

Subsequent attempt to load the menu crashes the game, unless the language is reset in `%Appdata%/Yimmenu/translations/index.json`

### Steps To Reproduce

1. Build master with Visual Studio
2. Launch game & inject
3. Go to Settings -> Menu Language and select Chinese Traditional / Simplified
4. Go back to Vehicle -> Vehicle Fun
5. Crashes
6. Restart GTA
7. Try to inject again
8. Crashes again

### Expected Behavior

Should work regardless of language.

### Logs and/or screenshots

Commandline output:
https://gist.github.com/George0828Zhang/fdc1addc7525a9fb0528af7ec42b29ab

### Store

Rockstar

### Additional context

1. It only happens with Chinese. All other languages works fine.
2. It only occurs when building from scratch. Nightly's .dll is fine. 
3. (Maybe is my machine's problem?)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Compile with utf-8, this Is because your literal encoding is not utf-8 compatible

https://github.com/microsoft/STL/issues/1820

**Comment by George0828Zhang** [comment]
> Compile with utf-8, this Is because your literal encoding is not utf-8 compatible
> 
> [microsoft/STL#1820](https://github.com/microsoft/STL/issues/1820)

Thank you, this worked.

```
add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
```
