### ISSUE TITLE
[Request]:  Block PTFX and Disable All Looped From Player

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#2117]
### Problem

1. Lets say that no all of us have a good pc and can lag with ptfx (Like stand mean options that do a annoying big ptfx to lag the player) so what if we block the ptfx spawn
2.  Let say that you have some loops on a player and you dont want to search for them, we can add a button to disable the current loops of the player if he have one enabled

### Solution

Block Spawned PTFX and print the player that is spawning the ptfx (dosent matter if this cant be done due to animations like smoke that request ptfx from the player that plays the anim)

### Reason

Flawless gameplay, better player-control from menu side

**Comment by maybegreat48** [comment]
You can toggle `Block Network Events` to block PTFXes and other annoying stuff

**Comment by 0xEmiil** [comment]
> You can toggle `Block Network Events` to block PTFXes and other annoying stuff

Got u thanks!
