### ISSUE TITLE
[Bug]: game crashed by some modder

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2122]
### Describe the bug

i was in a public lobby and someone tried to crash all the players.
No notification was given by yim menu that who tried to crash.

### Steps To Reproduce

Go to public lobby (not being a host) and some modder tried to crash all the players.

### Expected Behavior

Its ok to get kicked. But game crashed is not fine :(
Also possible reaction should be notified.

### Logs and/or screenshots

[cout.zip](https://github.com/YimMenu/YimMenu/files/12601248/cout.zip)

### Store

Epic Games

### Additional context

Using `relwithdebinfo` build of latest head of master.

other settings -
![Screenshot 2023-09-14 010925](https://github.com/YimMenu/YimMenu/assets/139460769/e6995229-62b5-4ad8-a970-c037423fc576)
![Screenshot 2023-09-14 010918](https://github.com/YimMenu/YimMenu/assets/139460769/bad9c365-dc26-49c0-b619-d625b77ad262)
![Screenshot 2023-09-14 010910](https://github.com/YimMenu/YimMenu/assets/139460769/b68e3ef3-3f49-4e9a-ae3a-485a38ab8b13)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
@maybegreat48 This one looks spicy.

**Comment by WilliamHottzz** [comment]
Where are u getting the crash logs from?

**Comment by lonelybud** [comment]
its `RelWithDebInfo` build logs from branch develop including latest yim menu master branch head at that time -

03b1668 feat(cmake): enforce utf8 (#2115)

**Comment by maybegreat48** [comment]
> @maybegreat48 This one looks spicy.

It doesn't appear to be targeted

**Comment by lonelybud** [comment]
closing this as stale.
