### ISSUE TITLE
[Bug]:  After injecting gta closes

### ISSUE THREAD

**Issue by WebUwU** [Yimura/YimMenu#2127]
### Describe the bug

So i did not get banned but now when i wanna inject the dll my game crashed out of nowhere? but only when its not in the loading screen i can inject it in the loading screen but when my char is loadet it crashed immidetly

### Steps To Reproduce

1. dowload dll (ik its currently not working)
2. download  xenos
3.  select the dll and gta in xenos
4. unject it

### Expected Behavior

that the mod menu is loading without crash

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

maybe it had to do with the bans or just bc my game is broken but yea

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Log?

**Comment by WebUwU** [comment]
> Log?

fixed it haha it was a currupted file
