### ISSUE TITLE
Replace freemode thread restorer with VM patch

### ISSUE THREAD

**Issue by maybegreat48** [Yimura/YimMenu#213]
**Is your feature request related to a problem? Please describe.**
I feel this is more cleaner that constantly memcpy-ing the stack each tick

**Describe the solution you'd like**
```c++
auto mod = memory::module(nullptr);

if (auto pat1 = mod.scan("3b 0a 0f 83 ? ? ? ? 48 ff c7"))
{
	*pat1.add(2).as<uint32_t*>() = 0xc9310272;
	*pat1.add(6).as<uint16_t*>() = 0x9090;
}

if (auto pat2 = mod.scan("3b 0a 0f 83 ? ? ? ? 49 03 fa"))
{
	*pat2.add(2).as<uint32_t*>() = 0xc9310272;
	*pat2.add(6).as<uint16_t*>() = 0x9090;
}

auto pat3 = mod.scan_all("3b 11 0f 83 ? ? ? ? 48 ff c7");
for (auto& handle : pat3)
{
	*handle.add(2).as<uint32_t*>() = 0xd2310272;
	*handle.add(6).as<uint16_t*>() = 0x9090;
}

auto pat4 = mod.scan_all("3b 11 0f 83 ? ? ? ? 49 03 fa");
for (auto& handle : pat4)
{
	*handle.add(2).as<uint32_t*>() = 0xd2310272;
	*handle.add(6).as<uint16_t*>() = 0x9090;
}
```
Not sure if this should go in pointers or hooking. I have it in pointers

**Provide Reasoning**
I fuzz tested this by spamming myself with every script event (except the crash ones ofc) and didn't get kicked

**Additional context**
Everything pasted from [this UC post](https://www.unknowncheats.me/forum/3075446-post22.html)

**Comment by Yimura** [comment]
Definitely will be replacing the freemode script recovery with this.
Going to be good to remove the freemode script recovery as it often lead to confusion when people had something else crash them and the recovery would kick in one last time before segfaulting the application.
