### ISSUE TITLE
Auto Update cache

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#214]
**Is your feature request related to a problem? Please describe.**
Currently a vehicles.json file is downloaded containing all the vehicles in the game.
It's only downloaded once and never checked again if outdated.

**Describe the solution you'd like**
We can use the Github public API to check if the GTA V dumps repo has been updated, if it has we redownload our files.

Example URL:
https://api.github.com/repos/DurtyFree/gta-v-data-dumps/git/refs/heads/master

**Provide Reasoning**
With each updated you'd have to manually go into the directory of YimMenu, remove the cached files and let it download again.

**Additional context**
Not applicable

**Comment by Yimura** [comment]
Doing this requires we replace the current http lib with one that supports https, but by using a https capable lib we might increase the difficulty of building YimMenu as OpenSSL is required.

**Comment by xiaoxiao921** [comment]
A dirty alternative is that `curl.exe` is available on Windows 10 (version 1803 or later) (https://stackoverflow.com/a/16216825) or also available if you have `Git for Windows`

**Comment by Yimura** [comment]
Actually this issue can be closed because the cache is auto updating currently.

Though this does not fix the issue of having to use a http only proxy.
