### ISSUE TITLE
[Build]: Wrong "Crash detected"

### ISSUE THREAD

**Issue by sirandr3w** [Yimura/YimMenu#2155]
### Describe the build issues

YimMenu detects a "fake" 'crash detected' event from a player who is actually spinning the casino wheel. (Epic Games)

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by pierrelasse** [comment]
It is not unoften that crash detection false flag. Thats why the player doesnt get marked as modder from crash detection because they are not 100%.

**Comment by CypherMorgan** [comment]
> Why can’t people read. What is this the 5th bug submitted without a log?

I guess He's talking about The Sound Spam Crash Detection, occurs when player spins the wheel inside the casino and you're nearby the casino building.

The Log for that:
[06:27:52.7085322][WARN/notify.hpp:30] Blocked sound spam crash from PlayerID (RID)

**Comment by lonelybud** [comment]
one can close this being without any description.

**Comment by Yimura** [comment]
Not an issue, the warning is there to spread awareness to the user without blaming anyone as the sound spam crash protection can't necessarily determine who is the bad actor.
