### ISSUE TITLE
[Improvement]: byte patching help? 

### ISSUE THREAD

**Issue by WHots** [Yimura/YimMenu#2163]
### Which feature

Hey, so not really catching how to use the byte patching methods you have associated with this project.

```
inline void clear_ped_tasks_immediatly(Ped ped)
{

		char pat[] = "\x48\x89\x5C\x24\x00\x57\x48\x83\xEC\x30\xE8\x00\x00\x00\x00\x48\x8B\xF8\x48\x85\xC0\x0F\x84\x00\x00\x00\x00\x8A\x80\x00\x00\x00\x00\xA8\x01\x74\x2F\xA8\x02";
		char msk[] = "xxxx?xxxxxx????xxxxxxxx????xx????xxxxxx";
		
		PVOID address = FindPattern(NULL, sizeof(pat), pat, msk);
		
		memory::byte_patch patch(address, 0xEB);
		patch.apply();
		

		fpClearPedTasksImmedidatly ptf = reinterpret_cast<fpClearPedTasksImmedidatly>(address);
		ptf(ped);

		patch.restore();
}
```

for this **memory::byte_patch patch(address, 0xEB);** I'm obviously getting the param1 wrong because it's not **uint8_t***, regardless of that when i do convert it, by any means at all i get an error saying it's inaccessible.

This is just boilerplate code to kinda show what im doing.

Thanks.

### Reason

n/a

**Comment by gir489returns** [comment]
Why not look at an example in the code base?

https://github.com/YimMenu/YimMenu/blob/5e177ef1516d68e97e73a4c7b2364547b864629b/src/byte_patch_manager.cpp#L82

**Comment by WHots** [comment]
@gir489returns - Yeah i get that, but in my particular scenario it's crashing when i use the method.

```
struct task_managed_patches
{
	inline static memory::byte_patch* m_can_clear_task;
};
```

```
inline void clear_ped_tasks_immediatly(Ped ped)
{

	char pat[] = "\x48\x89\x5C\x24\x00\x57\x48\x83\xEC\x30\xE8\x00\x00\x00\x00\x48\x8B\xF8\x48\x85\xC0\x0F\x84\x00\x00\x00\x00\x8A\x80\x00\x00\x00\x00\xA8\x01\x74\x2F\xA8\x02";
	char msk[] = "xxxx?xxxxxx????xxxxxxxx????xx????xxxxxx";
		
	PVOID address = FindPattern(NULL, sizeof(pat), pat, msk);
	g_pointers->m_gta.m_stop_ped_task_immedeatly = address;

	task_managed_patches::m_can_clear_task = memory::byte_patch::make(g_pointers->m_gta.m_stop_ped_task_immedeatly.add(2).as<uint8_t*>(), std::vector{0x90, 0x90, 0x90, 0x90, 0x90}).get(); 
	task_managed_patches::m_can_clear_task->apply();

	fpClearPedTasksImmedidatly ptf = reinterpret_cast<fpClearPedTasksImmedidatly>(address);
	ptf(ped);

	task_managed_patches::m_can_clear_task->restore();
}
```

I'd assume it's the **task_managed_patches::m_can_clear_task = memory::byte_patch::make(g_pointers->m_gta.m_stop_ped_task_immedeatly.add(2).as<uint8_t*>(), std::vector{0x90, 0x90, 0x90, 0x90, 0x90}).get(); ** line somewhere with the first param, but I'm not sure how  **.add(...)** and **.as<uint8_t*>()** are determined.

It's all kinda pseudo for now until i get something working.
