### ISSUE TITLE
[Request]: CAR Model Feature 

### ISSUE THREAD

**Issue by TheSR007** [Yimura/YimMenu#2172]
### Problem

plz add Car model feature control, Kiddon already has it but when I use both game crashes do I hope you will add it,

### Solution

provide model feature checkbox for boost, parashoot, missiles if possible, jump, etc. Also make sure you add infinite ammo for vehicle(missiles) or freeze ammo

### Reason

Yimmenu doesn't has it. It would be great if you add this.

**Comment by pierrelasse** [comment]
I can use YimMenu and kiddions at the same time

**Comment by jvsandhu** [comment]
yeah love that option best way to make planse faster by enabling rocket boost flag please add this into yim

**Comment by szarpii** [comment]
Planes can be faster by hornboost. Also game not crashes with kidlons, I was using it too as sidemenu

**Comment by TheSR007** [comment]
This was added, forgot to close it. you can now find it in Vehicle->Fun Features->Vehicle Abilities
![image](https://github.com/YimMenu/YimMenu/assets/101653309/da1f3e87-2f16-4035-a24e-b777325d79fc)
