### ISSUE TITLE
[Bug]: Crash when entering / exiting Garage

### ISSUE THREAD

**Issue by Rabtos** [Yimura/YimMenu#2173]
### Describe the bug

Game sometimes crashes when entering / exiting Garage since I'm using the new version.

I've noticed following Error: [WARN/invoker.cpp:56] and [FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION

### Steps To Reproduce

1. Go Into Garage / Exit Garage

### Expected Behavior

I expected no crash.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12684856/cout.log)

### Store

Epic Games

### Additional context

I tried deleting the Cache. And it worked, I could enter / exit garages without crashing. But after a while it crashes the game again when entering. 

There also was a case where I could enter the garage, but couldn't exit without a crash. So I just teleported outside everytime...

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

Edit: Tried to unload, enter Garage. Injecting it again while still in Garage --> Crash!
[cout.log](https://github.com/YimMenu/YimMenu/files/12685972/cout.log)

**Comment by pierrelasse** [comment]
Yes i also still have native errors (always on when blackscreen is and sometimes 1-2 randomly) and random crashed with and without errors.

**Comment by gir489returns** [comment]
You are using a build from before this was fixed, use: #2156

https://nightly.link/YimMenu/YimMenu/actions/artifacts/935103030.zip

**Comment by pierrelasse** [comment]
Why should we use this even tho it is merged?
