### ISSUE TITLE
[Bug]: ERR_MEM_EMBEDDEDALLOC_ALLOC 

### ISSUE THREAD

**Issue by leeqin6** [Yimura/YimMenu#2195]
### Describe the bug

There is a probability that the game will crash when joining an open session

### Steps To Reproduce

For me.
1. Change session 11-14 times
2. Play 5 - 30 minutes
3. Crash

### Expected Behavior

Crash shouldn't happen

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12726846/cout.log)
[cout.log](https://github.com/YimMenu/YimMenu/files/12731412/cout.log)

### Store

Rockstar

### Additional context

Changing sessions through the in-game session finder or via the menu results in the same bug.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by leeqin6** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/12726904/cout.log)

**Comment by Yimura** [comment]
Version from the log file [715af5203e08da9326a6eab0fdd89ca0d5b55838]

**Comment by leeqin6** [comment]
It reappears, usually after joining more than 10 sessions
[cout.log](https://github.com/YimMenu/YimMenu/files/12727540/cout.log)

**Comment by leeqin6** [comment]
Crash when joining a session again, usually after joining more than 10 sessions
[cout.log](https://github.com/YimMenu/YimMenu/files/12727568/cout.log)

**Comment by Yimura** [comment]
I've updated this issue to contain the information from #2201 as well.

**Comment by leeqin6** [comment]
After testing, the crash occurred after #2128

**Comment by ghost** [comment]
same boat ya can confirm this happens

**Comment by xiaoxiao921** [comment]
Closing cause that specific crash is fixed by #2232
