### ISSUE TITLE
[Request]: XML Map Spawner

### ISSUE THREAD

**Issue by tiCkuhAr** [Yimura/YimMenu#2207]
### Solution

Add an XML map spawner that can parse Menyoo XML maps.

### Reason

So we can spawn stunt maps and other types of fun modded maps.

**Comment by Tayipc38** [comment]
You guys are really gonna make me do this huh.

**Comment by yousef157** [comment]
> You guys are really gonna make me do this huh.

I mean, can't it be made as a lua script instead?

**Comment by gir489returns** [comment]
> I mean, can't it be made as a lua script instead?

It probably could, but that would be an extremely heavy lift, you would also need to include an XML parser.

**Comment by Tayipc38** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/79384354/40cf3568-0ee7-442a-868c-d85b99cc2a51)
![image](https://github.com/YimMenu/YimMenu/assets/79384354/84e61a85-ee45-4dec-82ec-58acfe822138)


This is a bit more of a headache then the vehicles. But I will try and support each factor of menyoos somewhat crooked system.
