### ISSUE TITLE
[Bug]: Update to Game Version: 3028

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#2215]
### Describe the bug

Rockstar Dropped another update

### Steps To Reproduce

Updating Game 😅

### Expected Behavior

...

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12791375/cout.log)

### Store

Rockstar

### Additional context

The menu loads fine, prolly the Globals needs to be updated for some stuff to work without triggering anti-cheats

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gaycookie** [comment]
Afters months of thinking to try out YimMenu, I downloaded it and already bumbed against this issue too haha!
R* always has to be annoying when I want to try out something new.

**Comment by Yimura** [comment]
I'm going to remove the download for now, they might have changed some things to the anti-cheat.

**Comment by fhencat** [comment]
> 我现在要删除下载，他们可能已经将一些东西更改为反作弊。

may i ask if you will still update yimmenu

**Comment by Rabtos** [comment]
Game keeps crashing with the new game version.
Tried running the game 11 times and it always crashed after 1-3 mins.

**Comment by D-Borkan** [comment]
> Game keeps crashing with the new game version. Tried running the game 11 times and it always crashed after 1-3 mins.

dont use it for now 
-- wait new update

**Comment by lonelybud** [comment]
> Game keeps crashing with the new game version. Tried running the game 11 times and it always crashed after 1-3 mins.
crashing in story mod?

**Comment by CypherMorgan** [comment]
> Game keeps crashing with the new game version. Tried running the game 11 times and it always crashed after 1-3 mins.

You shouldn't be Playing the Game using the YimMenu, Right now. As There's no clue what else have been changed with the Game's anticheat or other services.

and as per i've tried the menu was loaded normally for me without giving any crash. So, would u like to provide the log file. So that the devs can find out if Logs caught something.

**Comment by lonelybud** [comment]
Tried to join friend session game crashed. I checked game crash without any good information.

Edit: public session

**Comment by maybegreat48** [comment]
A function used in our AC bypass is integrity checked. Do not go online until we fix it (and see if they've added something new)

**Comment by gir489returns** [comment]
> A function used in our AC bypass is integrity checked. Do not go online until we fix it (and see if they've added something new)

You just told me it wasn't. Confused.
