### ISSUE TITLE
[Bug]: Presence Data Got Outdated.

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#2242]
### Describe the bug

The Presence Data (PD) signatures in Pointer.cpp are changed.

### Steps To Reproduce

Run The Game and Inject Menu.

### Expected Behavior

Working right

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12857700/cout.log)

### Store

Rockstar

### Additional context

R* Sucks haha (Sorry, Off-Topic)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I can confirm a social club update just occurred and the "PD" signature does not work anymore. Assigning @maybegreat48 since he was the one who added it.

**Comment by CypherMorgan** [comment]
> I can confirm a social club update just occurred and the "PD" signature does not work anymore. Assigning @maybegreat48 since he was the one who added it.

If I knew how to do it, I would've tried finding :/
