### ISSUE TITLE
[Bug]: Crash when starting up the game through newly updated Rockstar Games Launcher

### ISSUE THREAD

**Issue by theblaziken** [Yimura/YimMenu#2252]
### Describe the bug

Rockstar Games Launcher was recently updated, I tried injecting Yimmenu after updating it, immediately crashed after that.

### Steps To Reproduce

1. Update Rockstar Games Launcher
2. Let it install the new update
3. Start up GTA5
4. Inject YimMenu

### Expected Behavior

Not crashing

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12864473/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
You seems to be running the commit where this was supposedly fixed yet you crashed, weird

**Comment by xiaoxiao921** [comment]
People on matrix are reporting that rockstar slaves updated the social club twice

**Comment by santos7melo** [comment]
The game closes when I inject the dll, any fixes?

**Comment by xiaoxiao921** [comment]
No fixes for now, we need to update the menu because rockstar keep updating the social club for some reason

**Comment by xiaoxiao921** [comment]
Woops nevermind, finally took a look on my pc and just make sure you run atleast https://github.com/YimMenu/YimMenu/commit/1f7167cbfb032ac72404d10a02c32c8f39d67e02 or a commit even more recent
