### ISSUE TITLE
[Bug]: Game crashes after failed language file download

### ISSUE THREAD

**Issue by isdzjfs** [Yimura/YimMenu#2264]
### Describe the bug

The game crashes when clicking on "Settings" after the language file download fails.
![image](https://github.com/YimMenu/YimMenu/assets/142170538/a9b02aee-98a3-4b2b-8b00-581f9d7f0a99)

### Steps To Reproduce

1. Load the game into story mode (do not inject Yim)
2. Disable any internet connection
3. Injecting Yim
4. Click "Settings".

### Expected Behavior

No crash

### Logs and/or screenshots

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/12880626/cout.log)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Just made a PR that will fix this specific issue https://github.com/YimMenu/YimMenu/pull/2265

not sure on why you are not able to download the lang json though...

**Comment by isdzjfs** [comment]
> Just made a PR that will fix this specific issue #2265
> 
> not sure on why you are not able to download the lang json though...

Credit to China's firewall, Just tested it and it works fine.

**Comment by rr1231234** [comment]
still crashing too often, might wanna change the name to RagequitMenu lol
