### ISSUE TITLE
[Build]: Crashing game after injecting

### ISSUE THREAD

**Issue by DonniTM0** [Yimura/YimMenu#2269]
### Describe the build issues

I am experiencing a ISSUE while attempting use YimMenu. I am using the latest versions of both Epic Games and Rockstar, also using the Xenos injector. The issue prevents me from opening GTA V successfully. 

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/12884469/cout.log)

### IDE/Compiler

Visual Studio 2022

### Additional context

I didn't build Yimmenu, the last time i did Windwos Defender decided to remove it (it took me one hour to find out what was blocking it) but now i use the released version (.dll)

No specific context just when i launch the game, i open Xenos to inject, the moment it "injects", GTA crashes along side with a command prompt showing the log and exceptions.

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by xiaoxiao921** [comment]
You are running an old version of YimMenu, please update to atleast 1f7167cbfb032ac72404d10a02c32c8f39d67e02
