### ISSUE TITLE
Add yourself to playerlist

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#227]
**Is your feature request related to a problem? Please describe.**
Add yourself to the playerlist so you can use the selected player option on yourself

**Describe the solution you'd like**
Adding into the playerlist yourself

**Provide Reasoning**
It's a must-have to see yourself on the playerlist

**Additional context**
-

**Comment by Yimura** [comment]
Sure will do, would you prefer that your local player is rendered first? Or just sorted alphabetically?

**Comment by MoneyDropLobby** [comment]
> Sure will do, would you prefer that your local player is rendered first? Or just sorted alphabetically?

Would be better if it renders as first. 

And maybe adding a multifunktional bool system. Like if you toggle on 1 player a bool and switch to another one and also toggels the same bool option so it works for both... Is that understandable 🤔😂

**Comment by mentolixite** [comment]
You mean selecting multiple players with something like CTRL? Nice idea!

**Comment by mentolixite** [comment]
The local user is not explicitly filtered:

https://github.com/Yimura/YimMenu/blob/b1e20ab91fac2a3a2c7f14f865f8aeedee8322b1/BigBaseV2/src/views/players/view_players.cpp#L22-L35

But it is for ESP:

https://github.com/Yimura/YimMenu/blob/b1e20ab91fac2a3a2c7f14f865f8aeedee8322b1/BigBaseV2/src/views/esp/view_esp.cpp#L27-L34

I assume the ESP only draws other players, regardless of the setting?

**Comment by Yimura** [comment]
Yes but I don't think this is related to this issue, that the player isn't in the list is related to how the hooks work. On injection the player list is populated from CNetworkPlayerMgr which contains all players including our local CNetGamePlayer.
Then when we leave the session the list is cleared, causing all players to be removed including our local player from the player list. This in itself isn't a problem, the problem lies with the hooks, they're called when a player joins/leaves. Our local player never joins or leaves and thus always exists but never triggers to be added to the player list.

**Comment by mentolixite** [comment]
You're right:

https://github.com/Yimura/YimMenu/blob/52149aba33fc69b74981f33e510ba0f8c62c6ec0/BigBaseV2/src/hooks/network_player_mgr_shutdown.cpp#L6-L8
https://github.com/Yimura/YimMenu/blob/52149aba33fc69b74981f33e510ba0f8c62c6ec0/BigBaseV2/src/hooks/player_join.cpp#L7-L9
https://github.com/Yimura/YimMenu/blob/52149aba33fc69b74981f33e510ba0f8c62c6ec0/BigBaseV2/src/hooks/player_left.cpp#L6-L8

Why don't we always access `CNetworkPlayerMgr` instead of using our own player list?

**Comment by Yimura** [comment]
Because CNetworkPlayerMgr doesn't protect us when it suddenly decides to remove a player from the list, which will crash the menu. Neither does CNetworkPlayerMgr expose convenience functions to get the ped, vehicle, player info, etc...

But don't worry this is easily fixable, I just don't care to fix it NOW you see.

**Comment by mentolixite** [comment]
Okay, that's what I thought. Does a hook for `CNetworkPlayerMgr` startup exist?

**Comment by Yimura** [comment]
Maybe, you could just like not care and in general not add the local CNetGamePlayer to the player list and instead add a getter for the local player object.
Then when you need your local player you just render it first.

**Comment by mentolixite** [comment]
Working on it, I already created a signature for the function.

By the way, the one for `CNetworkPlayerMgr::Shutdown()` actually points to another function called by it. Should I fix that?

**Comment by Yimura** [comment]
> Working on it, I already created a signature for the function.
> 
> By the way, the one for `CNetworkPlayerMgr::Shutdown()` actually points to another function called by it. Should I fix that?

Does it matter? I just detoured the one from the vtable...

**Comment by mentolixite** [comment]
`CNetworkPlayerMgr`:

```
.rdata:0000000141A71160 28 36 C2 41 01 00 00 00                            dq offset ??_R4CNetworkPlayerMgr@@6B@
.rdata:0000000141A71168 B0 90 10 41 01 00 00 00 ??_7CNetworkPlayerMgr@@6B@ dq offset sub_1411090B0
.rdata:0000000141A71170 B8 9E 13 41 01 00 00 00                            dq offset sub_141139EB8
.rdata:0000000141A71178 B0 DF 16 41 01 00 00 00                            dq offset sub_14116DFB0
.rdata:0000000141A71180 E4 62 17 41 01 00 00 00                            dq offset ?_DeleteExceptionPtr@@YAXQEAV__ExceptionPtr@@@Z_23 
.rdata:0000000141A71188 80 9F 10 41 01 00 00 00                            dq offset sub_141109F80
.rdata:0000000141A71190 0C B4 14 41 01 00 00 00                            dq offset sub_14114B40C
.rdata:0000000141A71198 5C B4 14 41 01 00 00 00                            dq offset sub_14114B45C
.rdata:0000000141A711A0 1C A5 10 41 01 00 00 00                            dq offset sub_14110A51C
.rdata:0000000141A711A8 C0 77 69 41 01 00 00 00                            dq offset sub_1416977C0
.rdata:0000000141A711B0 0C 30 13 41 01 00 00 00                            dq offset sub_14113300C
.rdata:0000000141A711B8 64 30 13 41 01 00 00 00                            dq offset sub_141133064
.rdata:0000000141A711C0 44 F4 12 41 01 00 00 00                            dq offset sub_14112F444
.rdata:0000000141A711C8 AC 1A 12 41 01 00 00 00                            dq offset sub_141121AAC
.rdata:0000000141A711D0 58 1A 12 41 01 00 00 00                            dq offset sub_141121A58
.rdata:0000000141A711D8 5C A1 10 41 01 00 00 00                            dq offset sub_14110A15C
.rdata:0000000141A711E0 C4 9D 10 41 01 00 00 00                            dq offset sub_141109DC4
.rdata:0000000141A711E8 9C 99 10 41 01 00 00 00                            dq offset word_14110999A+2
.rdata:0000000141A711F0 00 A9 10 41 01 00 00 00                            dq offset sub_14110A900
.rdata:0000000141A711F8 28 AD 11 41 01 00 00 00                            dq offset sub_14111AD28
.rdata:0000000141A71200 9C AA 10 41 01 00 00 00                            dq offset sub_14110AA9C
.rdata:0000000141A71208 74 AD 11 41 01 00 00 00                            dq offset sub_14111AD74
```

`netPlayerMgrBase`:

```
.rdata:0000000141AD9B80 18 0E C5 41 01 00 00 00                                dq offset ??_R4netPlayerMgrBase@rage@@6B@
.rdata:0000000141AD9B88 8C EB 67 41 01 00 00 00 ??_7netPlayerMgrBase@rage@@6B@ dq offset sub_14167EB8C
.rdata:0000000141AD9B90 90 F7 68 41 01 00 00 00                                dq offset sub_14168F790
.rdata:0000000141AD9B98 54 BD 69 41 01 00 00 00                                dq offset sub_14169BD54
.rdata:0000000141AD9BA0 10 14 6A 41 01 00 00 00                                dq offset sub_1416A1410
.rdata:0000000141AD9BA8 4C 06 68 41 01 00 00 00                                dq offset sub_14168064C
.rdata:0000000141AD9BB0 94 75 69 41 01 00 00 00                                dq offset sub_141697594
.rdata:0000000141AD9BB8 10 77 69 41 01 00 00 00                                dq offset sub_141697710
.rdata:0000000141AD9BC0 C4 22 68 41 01 00 00 00                                dq offset sub_1416822C4
.rdata:0000000141AD9BC8 C0 77 69 41 01 00 00 00                                dq offset sub_1416977C0
.rdata:0000000141AD9BD0 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9BD8 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9BE0 F0 93 68 41 01 00 00 00                                dq offset sub_1416893F0
.rdata:0000000141AD9BE8 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9BF0 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9BF8 94 1A 68 41 01 00 00 00                                dq offset sub_141681A94
.rdata:0000000141AD9C00 58 02 68 41 01 00 00 00                                dq offset sub_141680258
.rdata:0000000141AD9C08 68 76 48 40 01 00 00 00                                dq offset nullsub_4
.rdata:0000000141AD9C10 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9C18 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9C20 44 ED 7D 41 01 00 00 00                                dq offset _purecall
.rdata:0000000141AD9C28 44 ED 7D 41 01 00 00 00                                dq offset _purecall
```

The call chain to our function goes like this: `sub_14116DFB0` -> `sub_14169BD54` -> `sub_14169BE00`

However, other paths to it exist.

While I have never seen the function being called unexpectedly, we should probably hook `sub_14116DFB0` (actual `CNetworkPlayerMgr::shutdown()`) instead.
