### ISSUE TITLE
[Bug]: Game freezes when using weapons as A_C_Rabbit_02

### ISSUE THREAD

**Issue by tiCkuhAr** [Yimura/YimMenu#2271]
### Describe the bug

When you change your model to A_C_Rabbit_02 and try to aim a gun, it spams errors and makes the game freeze up.

### Steps To Reproduce

1. Go to spawn ped
2. Change your model to A_C_Rabbit_02
3.  Aim a gun

### Expected Behavior

Not spam errors

### Logs and/or screenshots

```
[cout.log](https://github.com/YimMenu/YimMenu/files/12885930/cout.log)
```

### Store

Epic Games

### Additional context

Either the bug itself should be patched, or there should be a model check to prevent you from aiming if your current model is A_C_Rabbit_02, or just give the user a warning when they change to A_C_Rabbit_02 not to use guns.

Note: I'm not sure if there are more models that do this or not. I tested some other animal models, but so far the only one that has done it is A_C_Rabbit_02.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
Bruh

**Comment by gir489returns** [comment]
> Bruh

Exactly. Then don't do that?

**Comment by tiCkuhAr** [comment]
> > Bruh
> 
> Exactly. Then don't do that?

I kind of figured this was going to be closed, I still think simple notification when someone changed to A_C_Rabbit_02 telling them not to aim a gun would be nice

**Comment by maybegreat48** [comment]
It'll also crash the session

**Comment by ghost** [comment]
Really? I didn’t know that. Now if that’s true it’s actual problem.

**Comment by tiCkuhAr** [comment]
> It'll also crash the session

If it crashes others as well, then the best fix might just be to prevent aiming for that model or remove it from the model changer.

**Comment by ghost** [comment]
> > It'll also crash the session
> 
> 
> 
> If it crashes others as well, then the best fix might just be to prevent aiming for that model or remove it from the model changer.

Please don’t remove cute bunny from model changer. Instead force a weapon loadout on the model with only the animal attack weapon in the weapon wheel (it plays a cute animation) or idk do summ 🥺
