### ISSUE TITLE
[Bug]: im invisible to other ppl

### ISSUE THREAD

**Issue by cash121212** [Yimura/YimMenu#2277]
### Describe the bug

I put my self as another ped now when i open my game im invisible to ther ppl and when i open it mid session im wearing like a green shirt to everyone else a

### Steps To Reproduce

idk what to write here

### Expected Behavior

can it be fixed cus this is my favorite menu

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Cool story, bro.

**Comment by cash121212** [comment]
oi

**Comment by xiaoxiao921** [comment]
Post your %appdata%/yimmenu/settings.json file in here and delete it from the folder and report back if the issue still happens

**Comment by pierrelasse** [comment]
Add more info required tsg mb?

**Comment by Yimura** [comment]
No response from user or other users commenting that they're experiencing the same issue, myself I haven't had this happen before.
