### ISSUE TITLE
Random Crashes With No Errors

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2281]
### Discussed in https://github.com/YimMenu/YimMenu/discussions/2253

<div type='discussions-op-text'>

<sup>Originally posted by **eggrolls-repu** October 11, 2023</sup>
I still seem to get getting random crashes with the latest release of yim. Don't get me wrong, it is way more stable than before when the integrity checks weren't bypassed but ever since then I've still been getting random crashes. I'm not sure if it could be one of the settings I have enabled or if others are having the same problem as me but as far and I can tell I'm alone on this one qwq. OH and see, I would open an issue for the problem but there's no error log, and I don't wanna be that guy that doesn't upload the log so yeah. If it helps, I seem to only get crashes when I join missions. If I stay in freemode for hours I'm ok but when I start to join missions, I will crash eventually. Sorry if I've typed too much, below you can find a summary of my post generated by ChatGPT.

TLDR: The latest release of YIM is more stable than before, but there are still random crashes, especially when joining missions. The user isn't sure if it's their settings or a common issue. They can't provide an error log, but they want to report the problem. Freemode is fine, but missions cause crashes.

Okay, nevermind about it being ok in freemode. I injected yim, loaded into online, and it says "Received Modder Detection from "<Player name> and I instantly crashed. I'm really not sure what to do other than try to restore my settings to default or cry bc that'll prob do nothing. </div>

Here's my settings.json so you can see my reactions and protections I have if you'd like to replicate the crash. Oh, and here are 3 different event viewer crashes I created with the exact same settings. All I did was hop session to session (and find modders to send that chat message) and my game eventually crashes. It takes about 10-15 minutes before the game crashes, but could be quick as 3 minutes. It crashes when it wants to.

[Crash Logs](https://pastebin.com/pmNDi0mS) - At the end of each log is when the game crashes. There are 3 different crashes, all created the same.
[settings.json](https://github.com/YimMenu/YimMenu/files/12913640/settings.json)

this is a mess and not a properly formatted issue and dead so I'll just introduce the issue formally and close this for now.

**Comment by szarpii** [comment]
You simply have set too agressive protections, and menu trying to kick other modders when detects something. But they crashing your game as their way of defence from kicking. Also, if it happens a lot for you, you flagged as Badsport cheater. It means you bullying others with godmod etc. You gonna be banned soon.

**Comment by eggrolls-repu** [comment]
> You simply have set too agressive protections, and menu trying to kick other modders when detects something. But they crashing your game as their way of defence from kicking. Also, if it happens a lot for you, you flagged as Badsport cheater. It means you bullying others with godmod etc. You gonna be banned soon. 

What? No. I’m not gonna argue with you, everything you said is false. Please don’t comment on issues when you don’t think what you’re talking about. Thank you.

**Comment by szarpii** [comment]
You saying this after saying "I ain't going to read this" in other issue?  What hypocrisy... Some people should be canceled, fr

**Comment by xiaoxiao921** [comment]
If you can have a good way of replicating this and also at least give the event viewer entry instead of zero log this would be very nice, issues like this tends to be completely ignored by contributors due to no way of replicating and no log files. Try also to troubleshoot by disabling reactions too, could help narrowing it down

**Comment by ghost** [comment]
> If you can have a good way of replicating this and also at least give the event viewer entry instead of zero log this would be very nice, issues like this tends to be completely ignored by contributors due to no way of replicating and no log files. Try also to troubleshoot by disabling reactions too, could help narrowing it down

Well the event viewer log is in the discussion but I guess I can copy and paste it in here. Also, I think it's from my chat reactions. When modders are detected and I receive spectate others I have it send chat messages. I think maybe something about sending messages in chat is making my game crash because it always crashes right after it's supposed to send a chat message. Oh and also it's crashed once before when I just tried to manually send a message under network.

**Comment by ghost** [comment]
I have a lot of chat reactions enabled so my best suggestion for trying to replicate the crash is enabling all the chat reactions and just going session to session, or playing the game like normal (with modders to trigger the chat reactions)

**Comment by ghost** [comment]
> okay, so sorry for assuming You are baddmodder, actually sending Chat message in Network tab crashing very often to me too. You would know if You would read my thread, instead of commenting it by "no way i aint gonna read this", sir, but okay, i can forgive You, and also sorry, haha 🤣 

It’s okay, i was in the wrong for being a dickhead. It’s just that you typed a lot and I don’t feel like reading all of it teehee :3 
I'll give it a read later
Oh wtf you also mentioned the crashes in your issues thread ah, this is, funny. Alright good to know I'm not alone then.
