### ISSUE TITLE
[Bug]: about lua api (event.register_handler)

### ISSUE THREAD

**Issue by Alice2333g** [Yimura/YimMenu#2298]
### Describe the bug

event.register_handler(menu_event.ChatMessageReceived, function(id, msg)
    log.info(tostring(id))
    log.info(tostring(msg))
end)

it don't work.

### Steps To Reproduce

...

### Expected Behavior

...

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
Hello, it works for me so:

Are you using the newest version?
The output is in the console, did you check there?

A player must type in the chat that is NOT you for the event to trigger.

**Comment by Yimura** [comment]
No response from the issue author, closing.
