### ISSUE TITLE
[Bug]: Object/Ped Pool Spiking leads to crash

### ISSUE THREAD

**Issue by erm999** [Yimura/YimMenu#2302]
### Describe the bug

When entering interiors that require a black screen to initialize, the ped pools spikes to 256/256 
while object pool goes to around 1700/2300. This sometimes happens when loading in, but can
also happen seconds after loading into the interior.  

### Steps To Reproduce

1. Start a mission
2. Head towards objective 
3. Enter interior
4. Wait for Pools to spike and crash

### Expected Behavior

Sometimes it happes, sometime it doesn't. From my experience it happens mostly while on an active mission. 
When not doing missions, it's usually fine. 

### Logs and/or screenshots

```
<paste your logs here>
```
![log](https://github.com/YimMenu/YimMenu/assets/24779416/254bac4c-f562-4cba-b377-7ada04ef8ee9)
[10-19-2023-01-19-25_cout.log](https://github.com/YimMenu/YimMenu/files/13034694/10-19-2023-01-19-25_cout.log)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
OK. And?

**Comment by erm999** [comment]
> OK. And?
 
And is there a fix?

**Comment by xiaoxiao921** [comment]
Does it happen without the lua scripts?

**Comment by erm999** [comment]
I have removed a handful of lua scripts and it has remedied the crashing.

**Comment by WorthIessPricetag** [comment]
If you dont mind, would you share the jet lua here real quick?
Sorry for the off-topic. :)

**Comment by Yimura** [comment]
Issue was caused by external factors introduced by a Lua, unsure if we should bother fixing the consequence of these pools running out (by deleting entities from the pools causing possible issues with missions, etc...).
