### ISSUE TITLE
[Bug]: Not letting me inject

### ISSUE THREAD

**Issue by MetalBasket** [Yimura/YimMenu#2309]
### Describe the bug

Every time i try to inject with process hacker it says "end of exception" and crashes gta, 2 days ago it was working perfectly fine but it just randomly stopped working.

### Steps To Reproduce

Go to process hacker 2, gta5.exe, miscallanious, inject dll, yimmenu.dll, crash

### Expected Behavior

I expected it to just inject as usual

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Skill issue.

**Comment by pierrelasse** [comment]
Try other program to inject like xennossos or cheatengine. If not work then i guess you need a better gaming chair.

**Comment by Yimura** [comment]
No logs or response from user, closing.
