### ISSUE TITLE
Selected player distinction

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#232]
**Is your feature request related to a problem? Please describe.**
When you select a player, the only thing that changes is the name atop the player window.

**Describe the solution you'd like**
The button element of the selected player should be given a distinct color differentiating it from the others.

**Provide Reasoning**
It would greatly improve the user friendliness.

**Additional context**

![image](https://user-images.githubusercontent.com/79384354/169698328-47913664-abca-468e-a1f0-fd83628b5e49.png)

**Comment by xM4ddy** [comment]
I think this would coincidide with switching to the selected playing being highlighted in blue and having a tag system where tags get added next to people's names such as `H` for host `G` for godmode, `I` for interiors, ect. They could be combined together in brackets next to players names such as `[HI] atze1806`.
