### ISSUE TITLE
[Bug]: Sending Chat Msg Crashes Game

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2326]
### Describe the bug

When sending a chat message via NETWORK > Chat > the game instantly closes, giving no error or anything at all in the console log. 

### Steps To Reproduce

Start GTA V
Inject in story mode
Start new public session 
after loading in try to send any chat message using the NETWORK > Chat feature in the menu (might take a lot of tries)
Game will crash

### Expected Behavior

No crash

### Logs and/or screenshots

```
nothing out of the ordinary in cont.log so here's 2 event viewer logs.
-CRASH 1-
Faulting application name: GTA5.exe, version: 1.0.3028.0, time stamp: 0x650b237f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff7ec082374
Faulting process id: 0x652c
Faulting application start time: 0x01da04b9cb065306
Faulting application path: O:\Epic Games\GTAV\GTA5.exe
Faulting module path: unknown
Report Id: 3bf6c5d6-5adc-42af-b63e-1f3a6e386613
Faulting package full name: 
Faulting package-relative application ID: 
-END-

-CRASH 2-
Faulting application name: GTA5.exe, version: 1.0.3028.0, time stamp: 0x650b237f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff7ec082374
Faulting process id: 0x5044
Faulting application start time: 0x01da04ba6855cf7f
Faulting application path: O:\Epic Games\GTAV\GTA5.exe
Faulting module path: unknown
Report Id: 23b602e9-7f18-4138-be9d-0e5c22a63ee6
Faulting package full name: 
Faulting package-relative application ID: 
-END-
```

### Store

Epic Games

### Additional context

It’s important to know that the crash is extremely inconsistent. Sending one chat message could crash your game while sometimes you can send hundreds before it crashes. Although enabling chat reactions seems to increase the chance of you crashing I cannot confidently say that’s the root cause, I think it’s sending chat messages as a whole that’s behind all the crashes but I know nothing.

There was another issue thread I opened regarding this issue but it was messy so I closed it and created a proper issue that respects the format, in hopes it will bring some attention to the issue. #2281 

Oh and lua functions aswell and reactions also will trigger the crash sometimes. It seems to react the same as sending messages manually with the menu in network.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

- [X] I've spawned some bitches.

**Comment by pierrelasse** [comment]
I did this while i was not able to open the standard chat and crashed. Maybe you chatted in a situation where the chat was disabled for you and this why you crashed? Idk.

**Comment by ghost** [comment]
No, it happens even when i am able to open the chat box normally but that shouldn’t matter.

**Comment by pierrelasse** [comment]
Hm okay. Then idk. Did it ever work for you?

**Comment by lonelybud** [comment]
it is reproducible sometimes.

**Comment by ghost** [comment]
> it is reproducible sometimes.

Yes it could take a few sent messages before you crash but in my case it’s only 1-3 then i crash. Since i like to have a lot of chat reactions enabled, i think im one of the few affected by this. Effected? Idk I ain’t smort.

**Comment by lonelybud** [comment]
can you send a sample of message you sent.

**Comment by gir489returns** [comment]
> > it is reproducible sometimes.
> 
> Yes it could take a few sent messages before you crash but in my case it’s only 1-3 then i crash. Since i like to have a lot of chat reactions enabled, i think im one of the few affected by this. Effected? Idk I ain’t smort.

It’s more likely you’re just the only one who found it. There have been several bugs you discovered that have been in the code and nobody else reported it. One of the major ones was the tire smoke bug. That’s been an issue since day 1, nobody’s said anything until you did. The problem however with this issue is priority and cause. We have a lot of fires to deal with right now, most notable the translation change I just did brought about hell and we’re trying to put out as many fires as we can with it before normal development resumes. I’m 90% certain you have found an issue here.

**Comment by gir489returns** [comment]
I can't replicate this issue on the ROTW version, however, I think this has to do with an issue of how the Chinese version might be looking for wrongthink. I know we used to hook the chat function and reconstruct it to not report what we say to Rockstar, however, this might be causing issues for you if the Chinese version somehow does something different for this function. Could you upload a dumped EXE of GTA5.exe for us that you're using?

**Comment by ghost** [comment]
> I can't replicate this issue on the ROTW version, however, I think this has to do with an issue of how the Chinese version might be looking for wrongthink. I know we used to hook the chat function and reconstruct it to not report what we say to Rockstar, however, this might be causing issues for you if the Chinese version somehow does something different for this function. Could you upload a dumped EXE of GTA5.exe for us that you're using?

I don't know what ROTW means but I'm not on the Chinese version. Also here's my dumpy. https://1fichier.com/?uzhp92l4s5u6hg1olc2t
[Mirror](https://mega.nz/file/GcBBgLqA#aLQgo-i2Orq6hQ6j-CRabgbpsX4MGpBU9MKuDp2pxXE)

**Comment by gir489returns** [comment]
> I don't know what ROTW means but I'm not on the Chinese version. Also here's my dumpy. https://1fichier.com/?uzhp92l4s5u6hg1olc2t [Mirror](https://mega.nz/file/GcBBgLqA#aLQgo-i2Orq6hQ6j-CRabgbpsX4MGpBU9MKuDp2pxXE)

ROTW is Rest of the World. And no, that's not it. A dump of the EXE is when you launch the game, and then use a debugger to dump the decrypted EXE from memory to disk. I use [Explorer Suite](https://ntcore.com/files/ExplorerSuite.exe).

**Comment by ghost** [comment]
rip okay well thanks, I’ll do that tomorrow then.

**Comment by ghost** [comment]
> > I don't know what ROTW means but I'm not on the Chinese version. Also here's my dumpy. https://1fichier.com/?uzhp92l4s5u6hg1olc2t [Mirror](https://mega.nz/file/GcBBgLqA#aLQgo-i2Orq6hQ6j-CRabgbpsX4MGpBU9MKuDp2pxXE)
> 
> 
> 
> ROTW is Rest of the World. And no, that's not it. A dump of the EXE is when you launch the game, and then use a debugger to dump the decrypted EXE from memory to disk. I use [Explorer Suite](https://ntcore.com/files/ExplorerSuite.exe).

I lied here you go https://1fichier.com/?cx8a0xweqpoiep59wnox
[Mirror](https://mega.nz/file/aBwmGDxR#EnOXyTsbIZVP24hE4XmOUBTbU3YXE2qnBSj9dYKUpUg)
Was lazy so I Remote Desktop to my computer and did it lol, shouldn’t effect anything.

**Comment by lonelybud** [comment]
it actually crashed me for today when i was in russian server. I sent message - "dont take money" and crashed. There is no specific logs regarding this. I will also look into this.

**Comment by ghost** [comment]
> it actually crashed me for today when i was in russian server. I sent message - "dont take money" and crashed. There is no specific logs regarding this. I will also look into this.

Much appreciated

**Comment by sch-lda** [comment]
For me, sending chat messages before swooping down sometimes freezes my session or crashes the game. This can be replicated through the Modder Detection's announcement in chat. Yimmenu sends messages once a modder is detected, even during session transition.

**Comment by eggrolls-repu** [comment]
The cash also occurs while playing fully loaded into freemode so I don’t think being in the clouds contributes to the crash probability at all but idk

**Comment by lonelybud** [comment]
can you try this. before going online - disable idle kick and all spoofing inside spoofing tab view.

**Comment by ghost** [comment]
> can you try this. before going online - disable idle kick and all spoofing inside spoofing tab view.

played for about 10 minutes and still crashed
and yes, i always play on the latest nightly release

**Comment by gir489returns** [comment]
I just got this today. I sent a message to someone in the lobby via my phone, as soon as I pressed enter I crashed, nothing in the COUT log.

![image](https://github.com/YimMenu/YimMenu/assets/100792176/13cccf2d-9261-4495-bba0-cb28c1e8ded2)

@maybegreat48 Can you look at this?

**Comment by ghost** [comment]
This seems to have been fixed somewhere along the timeline. Just being a good boy and closing this to help clean up.
