### ISSUE TITLE
Yim inject 64 bit image Error?

### ISSUE THREAD

**Issue by HandyUnicorn377** [Yimura/YimMenu#2330]
(Fixed) Any time I attempt to inject Yim its pops up with an error saying "Can't inject 64 bit image 'YimMenu.dill" into a wow64 process".
I am using xenos.
To fix this if this happens to you Verify your game data.(What to do)

**Comment by pierrelasse** [comment]
1. Close this because you fixed it and it doesn't seem like a problem from yimmenu.
2. You are not following any issue template which makes this issue invalid.

**Comment by xiaoxiao921** [comment]
Closing because the author resolved it by verifying game data
