### ISSUE TITLE
[Bug]: Spamming new thread jobs may cause a downscale in available threads instead of upscaling

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#2337]
### Describe the bug

Spawning several new threads after each other will trigger the emergency response of the thread pool to start adding more threads into the pool to keep up with demand.
It's ignoring the minimum count of 4 and instead starting its up-scaling count from 1.

### Steps To Reproduce

1. Make a button that spawns a thread
2. Spam the button faster than the threads finish executing the spawned jobs
3. See console

### Expected Behavior

Start scaling upwards from the minimum amount of threads allocated by default instead of starting the count from 1.

### Logs and/or screenshots

```
[21:49:33.9724365][DEBUG/thread_pool.cpp:95] Thread 8168 executing system_proxy_watcher.cpp:25
[21:49:55.0777201][DEBUG/thread_pool.cpp:95] Thread 13360 executing view_proxy_settings.cpp:75
[21:50:25.4623858][DEBUG/thread_pool.cpp:95] Thread 13360 executing system_proxy_watcher.cpp:25
[21:50:26.8431101][DEBUG/thread_pool.cpp:95] Thread 8168 executing system_proxy_watcher.cpp:25
[21:50:27.1428988][WARN/thread_pool.cpp:55] Thread pool potentially starved, resizing to accommodate for load.
[21:50:27.1429151][DEBUG/thread_pool.cpp:21] Resizing thread pool from 4 to 1
[21:50:27.4627204][DEBUG/thread_pool.cpp:95] Thread 13360 executing system_proxy_watcher.cpp:25
[21:50:27.5055568][DEBUG/thread_pool.cpp:95] Thread 13360 executing system_proxy_watcher.cpp:25
```

### Store

Steam

### Additional context

Issue exists on modified version [`http-proxy-client`](https://github.com/YimMenu/YimMenu/tree/http-proxy-client) and most likely [`master`](https://github.com/YimMenu/YimMenu/tree/master).

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Looks like it's due to line 90 https://github.com/YimMenu/YimMenu/blob/0de9182735fd952febe5fb9bd9f447502df64764/src/thread_pool.cpp#L90

no ?

**Comment by Yimura** [comment]
Seems like a bad implementation on my part. It doesn't downscale, it just says it will. There's also a call to reserve for a number smaller than the current number of elements in the vector.

Anyways, the easiest fix would be to use the current thread vector size + m_alloc_count.

**Comment by xiaoxiao921** [comment]
I said line 90 because for some reason the allocated thread count get decreased right before the job get executed and then incremented right after, i'm not sure why? if anything ::run should instead increment it at it's first line of code, and decrement when the infinite for loop exit

**Comment by Yimura** [comment]
Probably best to introduce an extra variable to keep track of the available threads.

**Comment by gir489returns** [comment]
I have to ask, what are you doing where this exists? From the description, it sounds like you have to spawn an extraordinary number of threads for this to occur. Can you submit a sample to cause the problem? Maybe instead of kicking off a thread from the button click each time, you add a job to a queue that a single thread parses and calculates.

**Comment by Yimura** [comment]
A checkbox triggers the below code, if you spam it the threads will still be in their waiting state after the `m_running` member var has toggled to false, then toggling the checkbox back to true will spawn another thread because the `m_running` variable is false.

Suddenly you have double the threads both running because with the first in its waiting state the m_running variable went back to true. Anyways the underlying is still true that the scaling of the thread pool is flawed and should be modified. In the same line the below code is an awful example of how not to implement this.
```cpp
//begin func
if (m_running)
    return;
m_running = true;

g_thread_pool->push([this]{
    while (g_running && m_running)
    {
        // some code

        std::this_thread::sleep_for(1s);
    }
});
// end func
```
