### ISSUE TITLE
[Request]: Snow

### ISSUE THREAD

**Issue by Asiamies** [Yimura/YimMenu#2339]
### Problem

No snow

### Solution

Yes snow

### Reason

Hella fun

### Additional context

Forgive me if this suggestion has already been dismissed/patched but I couldn't find old issues about this

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/0de9182735fd952febe5fb9bd9f447502df64764/src/core/data/weathers.hpp#L5

Yes snow?

**Comment by Asiamies** [comment]
That's local if I'm not mistaken

**Comment by Yimura** [comment]
Your feature request is absolutely terrible, if you're asking if snow is visible to the whole session then you're out of luck since that isn't controllable remotely.
