### ISSUE TITLE
Expand Remote features to allow multiple players

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#234]
**Is your feature request related to a problem? Please describe.**
Currently remote features can only be enabled on the selected player. 

**Describe the solution you'd like**
A system to allow remote features for more than one player at once.

**Provide Reasoning**
You might want to grant "Never wanted" for 2 players at once (as an example).

**Additional context**
A struct could be created containing bools that specify whether a remote function should be executed on a certain player. This struct could be a member of each players own struct.

**Comment by Adler-D3R** [comment]
I must say it's a great idea, yes.
My only question is : how will it look ?
Do you plan to add like a new tab with options, and a list of players ?
And then you check which players are affected ?

**Comment by Tayipc38** [comment]
> I must say it's a great idea, yes. My only question is : how will it look ? Do you plan to add like a new tab with options, and a list of players ? And then you check which players are affected ?

A new tab within the selected player window that contains checkboxes for certain functions. Once enabled these functions are stored in their respective structures within the selected players structure. Thus ensuring that said function is executed for that player even when you select another player. A new script will be responsible for looping through each players "Remote Functions" structure and execute accordingly.
