### ISSUE TITLE
Does yimmenu co-load with P2C menu? 

### ISSUE THREAD

**Issue by doc-todd** [Yimura/YimMenu#2341]
### Describe the bug

Hi, I apologize for bothering you with this small problem.
I'd like to use yimmenu while I'm using another P2C menu, because I love the features, options, and simplicity of the menu, so if there's anything I can do to use this menu while I'm using the other p2c menu, I'd really appreciate it. 
thanks in advance

PS: I had to check the co-load box to submit the post.

### Steps To Reproduce

1-launching p2c menu.
2-opening GTA 5
3-opening Xenos64
4-inject yim
It just crashed the game 

### Expected Behavior

.....

### Logs and/or screenshots

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/13162960/cout.log)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [ ] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
We can not and will not make an effort to make YimMenu work with other menus. YimMenu seems to co-load fine with Stand as long as you disable the script vm reimplementation feature (if I remember correctly).

YimMenu is open source and as such should be easier for p2c to make co-loading work than for us to go and figure out why we can’t co-load with X or Y mod menu.

**Comment by Yimura** [comment]
See #1447 for more information.

**Comment by doc-todd** [comment]
Thank you for responding, and I apologize again for bothering you :) 
ps: it's not a stand menu it's 2t1 vip just to let you know :)

**Comment by doc-todd** [comment]
....
