### ISSUE TITLE
[Bug]:  Crash not patched

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#2342]
Describe the bug

I was fighting with another modder [Unknown Menu] Yim seems to be fine handling the crashes until one crash hits me
In case i miss any kind of data this is the name and Rid if someone wanna mess with him and prove the crash by yourselves
zerotwouwu377    218912961

### Steps To Reproduce

1. Active All Protections
2. Encounter him
3. Handle some crashes 
4. One of them hits after some sec. aprox 15 - 25 from crash start or crashes starts

### Expected Behavior

To block this crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13167204/cout.log)

### Store

Epic Games

### Additional context

I join him and mess with him to crash me like 2 times and its the same log

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
You truncated the log instead of just posting the file here, so I can't tell what commit hash you're on, which especially sucks ass, because the crash is not within GTA5.exe, the crash appears to be something you did within YimMenu as it appears on the stack several times.

**Comment by lonelybud** [comment]
>You truncated the log instead

yeah there should be full log,
Also i would like to ask that if the release build log gives good information like you can see its just the addresses in stack trace. Why we dont use `relwithdebuginfo` build?

**Comment by xiaoxiao921** [comment]
> Why we dont use relwithdebuginfo build?

Because it doesnt matter. A contributor can compile on their side and match the offsets

**Comment by 0xEmiil** [comment]
> You truncated the log instead of just posting the file here, so I can't tell what commit hash you're on, which especially sucks ass, because the crash is not within GTA5.exe, the crash appears to be something you did within YimMenu as it appears on the stack several times.

Your right i send not spam some events, but also i tried twice and its the same result also with the same timings.
Thats whyy also i leave his Rid just in case someone of wanna test or get a better log info

**Comment by gir489returns** [comment]
Then it's probably related to #2326.

**Comment by ghost** [comment]
good to know im not crazy

**Comment by 0xEmiil** [comment]
> Then it's probably related to #2326.

in that caseee i have to test again xd, i have no random crashes while using chat or just using yim, btw its normal to not seen some msg of chat of some ppl, most of it are from Honk Kong when they send a message and the message display like an invalid character or invalid word or something like that

**Comment by xiaoxiao921** [comment]
Reopen /tell us if it still happens
