### ISSUE TITLE
[Bug]: Few Bugs report

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2344]
### Describe the bug

When Trying to save Vehicle (Persistent) with Folder Name " FAVORITES ", game crashes. It should be really easy to Fix.
When used Feature "Remove Everyone from Interior", then "Give Weapons to all", then Network->Chat(as Crew), Crash
When using Network Chat option at all, game likes to crash very often, when doing other things, and after that Chat

Basically, even when i turn on Log Chat Messages, it's not visible in Yim's window, just appdata. New checkbox?
Actually i dont know why, but sometime's i cant join lobbies till i switch to SCTV-mode. Lobbies not full, not private.
Really serious bug! Lack of Tab like SUPPORT US! Just give paypal.me url there, and Credits to Yim's, maybegreat48 etc.
Driving with always-on-ground prevent from using airbreak, hotkey works but it should temp. disable stay-on-ground option

### Steps To Reproduce

 ( ͡° ͜ʖ ͡°)

### Expected Behavior

no bugs

### Logs and/or screenshots

```
GOODMODE
```

### Store

Rockstar

### Additional context

PS: i've turned off every add-to-database in reactions.. and still ton of auto-detections.. it keep adding people to player database :/

Ps2: Not me, but @pierrelasse noticed that You can't turn off chat filtering, it automatically hide spam from chat, You see only "Hi Guys", and no spam. What if we want to still see that?

Ps3: When You hoover on some options like force-relay-connections you can't read whole message, they should be in few lines.

Ps4: Lot of options should have added description, things like enable-dev-dlc as example. Also, few options absolutely
Shouldn't have description, like force-host, as it breaks the lobbies in 99% of cases.. If you know what it breaks.. well..
.. simply, do not explain it here, plase, TYVM! 😉

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Jesus fucking Christ, what is this incomprehensible fucking garbage? Stop jamming the system with tickets without searching first, there's like 3 tickets already about chat causing a crash.

**Comment by 7HA7MA77** [comment]
oho, someone have pr'oblems with reading, or someone dislikes me after i point his mistake.. i listed here few errors, and okay, maybe i duplicated one of error, but what with other issues? grow up man, dont act like a child

**Comment by 7HA7MA77** [comment]
@Yimura, bro, can You please say something to gir? i exposed him on other forum, where he did something very not nice, and now he's bullying me on YimMenu github, that cherrypicking jsut to close my threads is very not nice, can You please? thanks mate
