### ISSUE TITLE
[Improvement]: update of players database [GOODMODE]

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2348]
### Which feature

[ i am sorry for not perfect english, i am not a native speaker obviously :) ]
[also, i dont know how to divide that thread into seperate ideas, 
as it's general idea of way of rebuiliding system, so..]

I think players database don't work the best way it can. It would were good, if it would be rebuilt a 'lil
ngl, it's such a mess, if you want have there your friends added to let them use commands
gosh, and that auto-detections, you cant actually switch off all of them (bug?)

Maybe it should looks more like:
*Whitelist, where You can add Your Friends etc, to giving them Command Permisions etc.
*Blacklist, where You can add toxic people or badmodders, to prevent them from joining, or to hunt them when boored
*Auto-Detection list, where would were everyone from add-to-database feature from reactions.

Also, on Playerlist White Icon Flag, for players from Whitelist, and Black Flag from players from Blacklist?
Auto-detect can be still red button, or it also can be changed, to red flag, or to red warning icon, or, normal warning icon. ⚠️

Also: Search textarea, to type in and search for players in database. Also, it can be choosable if listed by alphabet, or by time when added, from newest to oldest etc.

Also: as @pierrelasse mentioned, option to apply some things excluding people from friend list, here also applying just on people from blacklist or just from whitelist

Also: Missing ScriptHost Flag, it's not listed anywhere, no info who is actual scripthost.

### Reason
#GOODMODE update pack ^^
Actual databse is such a mess. I have no option to add-to-database, and it still keep adding there mods from auto-detection, i still and still need to delete, and clean that list, as i want have there just few friends, and worst type of modders for whose i am hunting whenever they're online.

### Additional context

Auto-detection of spammers not always work, instead of prevent them from joining it kicks them when they spam. It should add them to auto-detections, and not let them in. Also, spammers collected by me below, if You meet other i dont know of, feel free to share, Thank You!

Nicknames; Veniciusmouraa Tsuyoiii NINR3D milkylawyer54 fineMarci_GTA giriboy-- sdz323 gir489returns  covef2 gta5175-----
xiaokaiyu danya_221_477_2 Zz1414511 Jia-VX_GAT_3663 dkwokgok hrhwddwad qwer345456 sevasty nyankii ww4365756

**Comment by 7HA7MA77** [comment]
@Yimura - is it written good now? Thanks for reply, and also thanks for previous help ;p

**Comment by gir489returns** [comment]
Still don't care.
