### ISSUE TITLE
[Improvement]: Hold Shift to delete (Saved Vehicles) [GOODMODE] #18

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2350]
### Which feature

PersistentClick with Shift to delete, as like in Teleports Tab? Not big, but good update i think :) 

### Reason

#GOODMODE update pack ^^

### Additional context

@gir489returns

**Comment by lonelybud** [comment]
should be closed as per #2354

**Comment by 7HA7MA77** [comment]
Rly gir is striking my propostitions and then doing it as HIS update? woah hes rly pathetic xD
