### ISSUE TITLE
[Bug]: Drift Tires Bug [GOODMODE] #18

### ISSUE THREAD

**Issue by 7HA7MA77** [Yimura/YimMenu#2358]
### Describe the bug

Drift Tires not saved to persistent veh list (any car, they just not saving)

### Steps To Reproduce

Save any car, and check?

### Expected Behavior

not needed

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

GOOD UPDATE no. 1

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Don’t care. Go make your own cheat like you said you were gonna do.

**Comment by 7HA7MA77** [comment]
i am doing, and you grow up, dont act like noobchild, you bad for envoirment and for project, you should be canceled, dude

**Comment by Yimura** [comment]
Perhaps I forgot to add one of the fields when saving the CHandlingData of a vehicle.

**Comment by Yimura** [comment]
I checked all the fields for vehicle handling and they're all being saved to the JSON so there's no way any data is missed.

**Comment by gir489returns** [comment]
I guess you could say, this ticket was BADMODE.
