### ISSUE TITLE
[Bug]: Crashing

### ISSUE THREAD

**Issue by XXTOUCOXX** [Yimura/YimMenu#2369]
### Describe the bug

When I load into story mode and go explode my car. My game crashes.

### Steps To Reproduce

1. load into story mode.
2. shoot rpg at car.

### Expected Behavior

The game freeze when car explodes then crashes.

### Logs and/or screenshots

[11-01-2023-23-13-36_cout.log](https://github.com/YimMenu/YimMenu/files/13233926/11-01-2023-23-13-36_cout.log)

### Store

Epic Games

### Additional context

it crashes when at 
g_hooking->get_original<hooks::invalid_mods_crash_detour>()(a1, a2, a3, a4);

i decided to log args to help tell what cause this.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by 0xEmiil** [comment]
Whats wrong with you Git Info?

**Comment by XXTOUCOXX** [comment]
> Whats wrong with you Git Info?

Sorry what?

**Comment by 0xEmiil** [comment]
> > Whats wrong with you Git Info?
> 
> Sorry what?

That it dosent show the version of YimMenu... just to make sure you are using the updated version and right one !

**Comment by XXTOUCOXX** [comment]
Yes it is updated. i downloaded and build it. and when i explode a car i crash.

**Comment by XXTOUCOXX** [comment]
Weird i use now and its fine!!
