### ISSUE TITLE
[Bug]: Cannot save json vehicle in persist vehicle

### ISSUE THREAD

**Issue by sch-lda** [Yimura/YimMenu#2377]
### Describe the bug

This weird bug occurs after commit d277f16 and does not exist in commit d2005ec. It was initially reported by other Chinese player and can be reproduced in my PC. I don't understand why the change in commit d277f16 would cause this problem, and I don't know if others have been able to reproduce it. I can only temporarily fix the problem for those who have it by setting the names of the two "save" buttons separately

temporary fix:
![image](https://github.com/YimMenu/YimMenu/assets/54973190/4fb235ae-527d-4956-b29b-b6d5a1ef8cbe)

### Steps To Reproduce

1.Enter a vehicle
2.Enter a name in persist vehicle and press save vehicle
And then nothing happened. No vehicle appears in the list. 

### Expected Behavior

Able to save json vehicles.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
The list doesn't live reload, does it appear after unloading the menu and injecting again?

**Comment by sch-lda** [comment]
> The list doesn't live reload, does it appear after unloading the menu and injecting again?

No,I can't find saved json in YimMenu/saved_json_vehicles

**Comment by gir489returns** [comment]
> The list doesn't live reload, does it appear after unloading the menu and injecting again?

It should be polling the file list every frame from the NTFS journal.

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/assets/100792176/feb655a8-5a5e-4a70-ba6c-04c965358b1f

**Comment by sch-lda** [comment]
I retested with the same github action Artifacts I downloaded a few hours ago and this bug disappeared.The bug has somehow disappeared.Maybe it's just a coincidence.

**Comment by sch-lda** [comment]
My bad. This problem only occurs when using my not-yet-merged Chinese translations. I'll look into it later

**Comment by sch-lda** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/54973190/cb73725e-bc2b-4940-a2da-86936d3869ab)
ah

**Comment by gir489returns** [comment]
I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just "ah"?

**Comment by sch-lda** [comment]
> I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just 

Two elements on the same tab use the same name and one of them loses functionality

**Comment by gir489returns** [comment]
> > I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just
> 
> Two elements on the same tab use the same name and one of them loses functionality

Oh, so then it's a translation issue? The tab is labeled as VIEW_SPAWN_VEHICLE_PERSISTENT and the button is labeled as SAVE_VEHICLE. You might have to get crafty with the verbage in Chinese, I suppose.

**Comment by sch-lda** [comment]
> > > I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just
> > 
> > 
> > Two elements on the same tab use the same name and one of them loses functionality
> 
> Oh, so then it's a translation issue? The tab is labeled as VIEW_SPAWN_VEHICLE_PERSISTENT and the button is labeled as SAVE_VEHICLE. You might have to get crafty with the verbage in Chinese, I suppose.

It's no problem to represent these two keys with the same Chinese characters, I'm ignoring imgui's limitations
Due to this limitation, sometimes I have to use weird words or expressions. In English, two selectable named weapon and weapons can bypass this limitation, but it's weird to use 武器 and 武器们(weapons). So I have to use 特殊武器 based on their function though it doesn't fit the English meaning.
The higher the level of translation of yimmenu the more problems this limitation creates.

**Comment by gir489returns** [comment]
> > > > I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just
> > > 
> > > 
> > > Two elements on the same tab use the same name and one of them loses functionality
> > 
> > 
> > Oh, so then it's a translation issue? The tab is labeled as VIEW_SPAWN_VEHICLE_PERSISTENT and the button is labeled as SAVE_VEHICLE. You might have to get crafty with the verbage in Chinese, I suppose.
> 
> It's no problem to represent these two keys with the same Chinese characters, I'm ignoring imgui's limitations Due to this limitation, sometimes I have to use weird words or expressions. In English, two selectable named weapon and weapons can bypass this limitation, but it's weird to use 武器 and 武器们(weapons). So I have to use 特殊武器 based on their function though it doesn't fit the English meaning. The higher the level of translation of yimmenu the more problems this limitation creates.

I don’t see why you simply can’t just add ##somejunk for the Chinese translation that’s duplicated.

**Comment by sch-lda** [comment]
> > > > > I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just
> > > > 
> > > > 
> > > > Two elements on the same tab use the same name and one of them loses functionality
> > > 
> > > 
> > > Oh, so then it's a translation issue? The tab is labeled as VIEW_SPAWN_VEHICLE_PERSISTENT and the button is labeled as SAVE_VEHICLE. You might have to get crafty with the verbage in Chinese, I suppose.
> > 
> > 
> > It's no problem to represent these two keys with the same Chinese characters, I'm ignoring imgui's limitations Due to this limitation, sometimes I have to use weird words or expressions. In English, two selectable named weapon and weapons can bypass this limitation, but it's weird to use 武器 and 武器们(weapons). So I have to use 特殊武器 based on their function though it doesn't fit the English meaning. The higher the level of translation of yimmenu the more problems this limitation creates.
> 
> I don’t see why you simply can’t just add ##somejunk for the Chinese translation that’s duplicated.

Thanks, you reminded me. I really hadn't thought about using ## in json before. I'll replace the strangest translation and use this method in the future

**Comment by sch-lda** [comment]
> > > > > I can't read Chinese, so I don't know what that says or what he's signifying in the button, can you elaborate more than just
> > > > 
> > > > 
> > > > Two elements on the same tab use the same name and one of them loses functionality
> > > 
> > > 
> > > Oh, so then it's a translation issue? The tab is labeled as VIEW_SPAWN_VEHICLE_PERSISTENT and the button is labeled as SAVE_VEHICLE. You might have to get crafty with the verbage in Chinese, I suppose.
> > 
> > 
> > It's no problem to represent these two keys with the same Chinese characters, I'm ignoring imgui's limitations Due to this limitation, sometimes I have to use weird words or expressions. In English, two selectable named weapon and weapons can bypass this limitation, but it's weird to use 武器 and 武器们(weapons). So I have to use 特殊武器 based on their function though it doesn't fit the English meaning. The higher the level of translation of yimmenu the more problems this limitation creates.
> 
> I don’t see why you simply can’t just add ##somejunk for the Chinese translation that’s duplicated.

Unfortunately, not all imgui elements support this method.
![image](https://github.com/YimMenu/YimMenu/assets/54973190/5d416c19-5cb2-4d47-9c7a-c6649d118eab)
