### ISSUE TITLE
Player join notifications upon session joining

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#238]
**Describe the bug**
When joining a session, each player that gets added to the player manager emits the notification "x Joined.". This message should only be shown when a player is truly joining the session you are in.

**To Reproduce**
1. Start up gta
2. Join a session
3. Notice that each player in that session commences the notification

**Expected behavior**
-

**Screenshots**
-

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
This could be achieved by utilizing the transition state global. The following states should constitute that the message should be displayed:
TRANSITION_STATE_TERMINATE_MAINTRANSITION
TRANSITION_STATE_MAX
TRANSITION_STATE_DLC_INTRO_BINK
TRANSITION_STATE_EMPTY

Adding a simple check within the player_join hook would resolve this issue

**Comment by Vali0004** [comment]
I mean, CNetowrkPlayerMgr uses the same function to add the player data Yim hooks. Fixing this should be easy. Check your transition state, check if the player is fully allocated (not quite the right terms, but whatever), or check the GameState to see if it's playing and not in a cutscene when notifying. There's lots of ways about how you can do this. These are just some ideas, but it should be pretty easy to do.

**Comment by Tayipc38** [comment]
> I mean, CNetowrkPlayerMgr uses the same function to add the player data Yim hooks. Fixing this should be easy. Check your transition state, check if the player is fully allocated (not quite the right terms, but whatever), or check the GameState to see if it's playing and not in a cutscene when notifying. There's lots of ways about how you can do this. These are just some ideas, but it should be pretty easy to do.

Ive mentioned a simple solution in the "**Additional context**"  part of the issue. I suggest you read that.
