### ISSUE TITLE
[Build]: Not Building getting error with Hue Colors

### ISSUE THREAD

**Issue by TechWithTy** [Yimura/YimMenu#2392]
### Describe the build issues

Cannot get  YimMenu to build on VS Code

-Unmodified Yim Code
-Running VS Code 2019
-Ran this Command Successfully 
```
Found Visual Studio Community 2022 [Microsoft.VisualStudio.2022.Community] Version 17.7.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/ebbb3a8f-0b8f-4c9d-ac08-5e244e84b4fe/0afd4aab10965b608e0b1995e82674aae16ea546d661fc6c5ca4be7eba7f388e/vs_Community.exe
  ██████████████████████████████  3.76 MB / 3.76 MB
Successfully verified installer hash
Starting package install...
The installer will request to run as administrator, expect a prompt.
Successfully installed
```
-Have microsoft C++ installed
-Tried using both amd64 2022 and 2019 built tools
-Using External Hard Drive
-Trying to install into my steam library on said SSD
-Options of compilers i have
![image](https://github.com/YimMenu/YimMenu/assets/37724661/7706473b-4f99-4429-a9b5-af53d32bd847)

-When i open the project in vs code it compiles automatically then i try to build and get this

### Screenshots and/or Logs

```
[build] D:\SteamLibrary\YimMenu\src\core/data/hud_colors.hpp(240,4): fatal error C1001: Internal compiler error. [D:\SteamLibrary\YimMenu\build\YimMenu.vcxproj]
[build]   (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\p1_init.c', line 3652)
[build]    To work around this problem, try simplifying or changing the program near the locations listed above.
[build]   If possible please provide a repro here: https://developercommunity.visualstudio.com
[build]   Please choose the Technical Support command on the Visual C++
[build]    Help menu, or open the Technical Support help file for more information
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/SteamLibrary/YimMenu/build --config Release --target ALL_BUILD -j 18 -- exited with code: 1
[driver] Build completed: 00:00:32.725
[build] Build finished with exit code 1
```

### IDE/Compiler

Visual Studio Code

### Additional context

Have been trying to get this to build for 3 hours 

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by gir489returns** [comment]
You are running it against Build Tools 2019, run it against Build Tools 2022. The project minimum support is C++ 2023.

**Comment by Yimura** [comment]
He said later in the post that he tried to use VS2022 as well, though that is the minimum require his compiler output seems really odd and is causing an internal compiler error.

This error isn't really something our code base caused or we can solve.

**Comment by Yimura** [comment]
@TechWithTy, how much RAM do you have installed as well as which CPU are you running?

**Comment by Yimura** [comment]
No response from issue author.

**Comment by TechWithTy** [comment]
Hi i have 32 gb of ram and 5700x AMD CPU sorry ddint expect you to respond so fast

**Comment by Yimura** [comment]
What happens after you remove the `build/` and/or `out/` folders and try to build the project again using Visual Studio 2022? Try to not clutter/dirty the build directories by starting up the build with Visual Studio 2019 or any other compiler.

Also make sure your Visual Studio is up-to-date, mine appear to be several versions newer.
![image](https://github.com/YimMenu/YimMenu/assets/24669514/47f4bf41-e90d-499f-9738-08ec5be8059b)

**Comment by Yimura** [comment]
No response again... will be closing the issue.

The compiler error is internal so it's not really something we can help with, the issue author will have to figure out the problem himself.
