### ISSUE TITLE
[Request]: Skip cloud loading

### ISSUE THREAD

**Issue by hun2memory** [Yimura/YimMenu#2395]
### Solution

Basically just skip the cloud at certain mp loading
And force giving control to your ped

### Reason

crazy useful

**Comment by yousef157** [comment]
I'm not sure I understand this?

Do you mean by forcing the infinite loading glitch to be fixed, or straight up just skip the loading?
Though I'm not sure myself if the infinite loading glitch was fixed by R*.

**Comment by tupoy-ya** [comment]
Related discussion: #1529.

Related PR: #1938 ( Closed ).

EDIT: If by cloud you mean Skycam and not cloud saves.

**Comment by gir489returns** [comment]
Funny enough, @NjuuOwO claimed he would maintain that PR, yet he's already absconded from the project a mere month later. Just more proof that the feature is a heavy lift. It also breaks more than it solves.

**Comment by hun2memory** [comment]
> EDIT: If by cloud you mean Skycam and not cloud saves.

Certainly, and apologize if my words have confused you guys.
so from the discussion link that Tupoy provided, [this is what im looking for](https://github.com/TupoyeMenu/TupoyeMenu/blob/lite/src/backend/looped/tunables/seamless_join.cpp)
However in some cases it can make the game bug, such as an infinite loading.
so i try to avoid that like this :
```LUA
local trans = get_global_int(g_transition_state)
if trans ~= 9 and trans > 5 and trans <= 29 then
  --gas
end
```
idk if anyone has a better way

> Just more proof that the feature is a heavy lift. It also breaks more than it solves.

i agree with gir and had the same opinion.
but still i'd like to try it if tupoy have finished the feature

Thanks for all the contributors
