### ISSUE TITLE
[Bug]: Game crashes after YimMenu inject

### ISSUE THREAD

**Issue by DonniTM0** [Yimura/YimMenu#2405]
### Describe the bug

I'm having an issue opening YimMenu, whenever i launch the menu the game immeditately crashes, therefore can't play with it whilst on the game.

Although the menu works on the loading screen but after some time passes it crashes.

### Steps To Reproduce

After opening online, launch yimmenu; anything option that is enabled within the menu the game crashes.

### Expected Behavior

To launch and normally play the game without any crashes.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13323485/cout.log)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Can you try to remove the `settings.json` file under `%appdata/YimMenu/` and see if that fixes it?

From what I can see the menu is crashing while trying to parse the no_idle_kick json key it seems.

**Comment by DonniTM0** [comment]
Hmmmm, yes that fixed the problem.
Kinda weird why it did that maybe i had enabled an option before hand and i saved the config. But thank you, that fixed the problem!!!
