### ISSUE TITLE
[Improvement]: make your vehicle visible, even when you are invisible

### ISSUE THREAD

**Issue by arnthorrr** [Yimura/YimMenu#2413]
### Which feature

self > invisible also makes the vehicle you are driving invisible for other people, even if vehicle > vehicle invisibility is off

### Reason

so i can troll as a self driving car

**Comment by gir489returns** [comment]
This is not an improvement it’s a bug.

**Comment by arnthorrr** [comment]
didnt even realise i put it in the improvement tab, my bad

**Comment by gir489returns** [comment]
The code from invisibility.cpp doesn't touch anything in the vehicle, however, it could be that we're setting globalplayer_bd's IsInvisible to true, which might propagate to the vehicles. This was added in https://github.com/YimMenu/YimMenu/pull/984 by @maybegreat48. Not sure why though. None of the tickets he references are for vehicle visibility issues. @maybegreat48 can you look at this ticket perhaps?

**Comment by maybegreat48** [comment]
I had added that a while ago to prevent a certain P2C from decloaking you. It can now be safely removed since that P2C probably bypasses the bool

**Comment by gir489returns** [comment]
@ImXyper We are still waiting on your feedback of the test.

**Comment by arnthorrr** [comment]
sorry i didnt get a notification for this, i will test in a bit once one of my friends is online

**Comment by arnthorrr** [comment]
yes, it seems to work, my friend can see the vehicle im in but not me myself, thanks!
