### ISSUE TITLE
[Bug]: download button doesnt work

### ISSUE THREAD

**Issue by Clapwastaken** [Yimura/YimMenu#2427]
### Describe the bug

yoo i cant download the ymmenu the download button doesnt seem to be working 

### Steps To Reproduce

a

### Expected Behavior

a

### Logs and/or screenshots

```
<paste your logs here>
```
a

### Store

Steam

### Additional context

a

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Download button is token down as a precaution:
https://github.com/YimMenu/YimMenu/issues/2425

**Comment by Clapwastaken** [comment]
yo sorry im not used to use github so mb for the porly made ticket why was it taken down?

**Comment by Yimura** [comment]
People have been getting detected lately, took the download down as a precaution to prevent more people from getting detected.

**Comment by Clapwastaken** [comment]
oh okay thx for letting me know i was trying to record a video on how to use it, when do u think it will be public again?

**Comment by gir489returns** [comment]
> People have been getting detected lately, took the download down as a precaution to prevent more people from getting detected.

Might do them some good. I saw one dude says he plays GTA V for 40 hours a week, like it's a full time job. Touch grass, yo.

**Comment by Clapwastaken** [comment]
even payed menus are easly detected now i have been burning at leat 1 acc every month
