### ISSUE TITLE
[Bug]: Crash when joining online

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2433]
### Describe the bug

Crash when connecting to a server with other players

### Steps To Reproduce

Build latest YimMenu with Precompiled headers disabled for asynclogger bcs it wont build without D:, inject, crash when connecting to a server with other players. singpleplayer and sometimes loading into a server by myself works.

### Expected Behavior

Join a server without crashing.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13405044/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
It's crashing at get_ped_bone. This is causing more problems than it's solving, and it didn't even solve the original problem at all. I'm going to walk back the change, since @maybegreat48 also got this crash too.

**Comment by MoneyDropLobby** [comment]
I am still getting this crash when trying to join a normal online session.

**Comment by Yimura** [comment]
> I am still getting this crash when trying to join a normal online session.

YimMenu isn't really meant for online right now, we haven't fixed the crashes yet because of the ongoing detection issues.
