### ISSUE TITLE
[Bug]: Download page 404

### ISSUE THREAD

**Issue by yeoh223** [Yimura/YimMenu#2435]
### Describe the bug

How do I update the latest YimMenu, I tried compiling it myself but the situation is not too rosy

### Steps To Reproduce

![image](https://github.com/YimMenu/YimMenu/assets/146529625/2bee9137-981f-4307-8f79-5fa1e243fab3)

### Expected Behavior

YimMenu was successfully updated

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Intentional. See: #2425
