### ISSUE TITLE
Where is the DLL? I don’t see the releases section! 

### ISSUE THREAD

**Issue by ege-art** [Yimura/YimMenu#2444]
### Describe the bug

Where is the DLL? I don’t see the releases section

### Steps To Reproduce

Go to home, then it should be there on the left or right corner 

### Expected Behavior

To be able to download the DLL from releases 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Please see https://github.com/YimMenu/YimMenu/issues/2427#issuecomment-1817252744 and #2425 for more information.

**Comment by ege-art** [comment]
When will it return?
