### ISSUE TITLE
When will the DLL be available to download 

### ISSUE THREAD

**Issue by ege-art** [Yimura/YimMenu#2448]
### Describe the bug

When will the DLL be available to download 

### Steps To Reproduce

a

### Expected Behavior

a

### Logs and/or screenshots

```
<paste your logs here>
```
a

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by akirayin** [comment]
Menu is marked detected as of 17.11.2023. Usual protocol is 30 days till we can be sure it's "good", as the cause behind the bans is still being investigated no more info can be provided on when it will be available in it's regular downloadable form. You can always compile it yourself if you are so inclined (it is public after all) or you can find made .dll in actions (that's all the info you get) BUT DOING SO YOU ARE RISKING A BAN!!! I gave you the map with the location of the rope you do with it as you please!

**Comment by pierrelasse** [comment]
If you still want to download the latest version, you can download the artifact from the latest workflow. [Workflows](https://github.com/YimMenu/YimMenu/actions?query=is%3Asuccess+branch%3Amaster+event%3Apush).
*don't complain if u get banned :^)*

**Comment by LK-Lilon** [comment]
> Menu is marked detected as of 17.11.2023. Usual protocol is 30 days till we can be sure it's "good", as the cause behind the bans is still being investigated no more info can be provided on when it will be available in it's regular downloadable form. You can always compile it yourself if you are so inclined (it is public after all) or you can find made .dll in actions (that's all the info you get) BUT DOING SO YOU ARE RISKING A BAN!!! I gave you the map with the location of the rope you do with it as you please!

=> So you are telling me when its safe to use, they will provide the dll file officially??

**Comment by pierrelasse** [comment]
Correct. You can still download an official dll that has a high chance of getting u banned from the actions tab

**Comment by Yimura** [comment]
I've made downloads for YimMenu available again, I'm not making any claims on safety of it for at the least the coming 30 days.

**Comment by ege-art** [comment]
Hope we don't get banned
