### ISSUE TITLE
[Request]: Can you help me to make the bmx jump normal?

### ISSUE THREAD

**Issue by taoletsgo** [Yimura/YimMenu#2483]
### Can you help me to make the bmx jump normal?

After the 1.67 version 2944 update, a new bicycle vehicle was added, but it caused problems with the original bicycle jumping. When I pressed the jump button, the bicycle would automatically go left or right, as shown in this Twitter video This bug 

https://twitter.com/perpetualperplx/status/1668634102336200705

Can any contributors fix it in yimmenu? Thank you very much for your work

### Solution

Return bmx jump to normal

### Reason

It's been half a year and rockstar hasn't fixed it yet, so I'm looking forward to your help!

**Comment by Yimura** [comment]
1. Missing issue title
2. Are you asking us to fix a game bug?

**Comment by taoletsgo** [comment]
> 1. Missing issue title
> 2. Are you asking us to fix a game bug?

1.Sorry, the issue title was missed while using the translation function
2.Yes, it's a bug in a game. I'm not sure if it can be fixed by loading third-party plugins

**Comment by yousef157** [comment]
Not sure if this should be unironically fixed. Most people just compensate for the jump going left lol

**Comment by gir489returns** [comment]
Could you try something like this https://www.gta5-mods.com/vehicles/perfect-bmx-handling
With this https://github.com/YimMenu/YimMenu/pull/2443
and see if it fixes your issue?

**Comment by taoletsgo** [comment]
😔bmx broken again in 3095 version，I‘ll close this issue and go back to 2845 version.Thx for ur support,even if you don't understand what I'm saying.

**Comment by taoletsgo** [comment]
😔bmx broken again in 3095 version，I‘ll close this issue and go back to 2845 version.Thx for ur support,even if you don't understand what I'm saying.
