### ISSUE TITLE
[Request]: Where do i find the LUA api for Yimmenu?

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2485]
### Problem

i just cant tell if its documented or not nor where to find it

### Solution

:3

### Reason

I wanted to make a lua for yimmenu

**Comment by TheGreenBandit** [comment]
You can find the lua docs [here](https://github.com/YimMenu/YimMenu/tree/master/docs/lua)

**Comment by ghost** [comment]
Thanks
