### ISSUE TITLE
[Bug]: crash log generated when injecting menu fresh

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2491]
### Describe the bug

when injecting menu from scratch it will log crash in console.

### Steps To Reproduce

delete the yim menu folder from appdata if exists
inject yimmenu at game menu screen (dont start single player)
see logs

use xenos64 with settings -

Native inject 
unlink module
erase pe headers
inject delay 3000
inject interval 800

### Expected Behavior

should not log crash 

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13602363/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is a duplicate of #2487 although just using LLA with extra steps.

**Comment by Yimura** [comment]
Manual mapping is not supported and unnecessary.

**Comment by lonelybud** [comment]
it should not log right. If it is not supported. I am not using any other stuff.

**Comment by lonelybud** [comment]
I added the xenos settings. Which one is wrong.

Native inject
unlink module
erase pe headers
inject delay 3000
inject interval 800

**Comment by Yimura** [comment]
So we should put code in YimMenu to check if we’ve been manual mapped or not so we can unload properly or what are you proposing? With not supported I mean that we’re not putting resources into making sure the game doesn’t crash when manual mapping YimMenu.

Aside from that there’s no need for it as GTA V doesn’t care / doesn’t detect the normal method of injection.

**Comment by FIying-Scotsman** [comment]
> I added the xenos settings. Which one is wrong.
> 
> Native inject unlink module erase pe headers inject delay 3000 inject interval 800

R* don't currently detect injection events so just the "native inject" (i.e LoadLibrary) will do. You don't need to fiddle with things like unlinking the DLL or erasing headers because they're not currently detected and just causes more issues than they solve.
