### ISSUE TITLE
[Improvement]: update nighty workflow to show correct time of last release

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2499]
## Problem

The current nighty release is created with same tag name which results in updating of existing release (body, assets etc). This does not update when the release was actually published as shown -

![Screenshot 2023-12-08 211612](https://github.com/YimMenu/YimMenu/assets/139460769/cb7e87e8-8f7d-47df-9c3f-cdfed9897488)

if the release was just published it will still show 5 days ago although the assets are shown as updated recently -

![image](https://github.com/YimMenu/YimMenu/assets/139460769/a054b456-2c5b-40d8-9206-24c3c1bf0bbf)

## Solution 1

before the step "Download Artifact", add step "Delete Previous GitHub Release" as follows

```yml
      - uses: actions/checkout@v3
      - name: Delete Previous GitHub Release
        run: |
          response=$(curl -sS -w '\n%{http_code}' "https://api.github.com/repos/YimMenu/YimMenu/releases/latest")
          http_code=$(echo "$response" | tail -n1)
          json_data=$(echo "$response" | sed '$d')
  
          # Check if the HTTP request was successful (status code 2xx)
          if [[ "$http_code" =~ ^2[0-9][0-9]$ ]]; then
              # Extract the "id" field from JSON data and save it to a variable
              release_id=$(echo "$json_data" | jq -r '.id')
              echo "release_id: $release_id"
              curl -L \
                -X DELETE \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/YimMenu/YimMenu/releases/$release_id"
          else
              echo "Failed to fetch release information. HTTP code: $http_code"
          fi
      - name: Download Artifact
```

This deletes the release but tag remains. Next time a release is created the tag is reused.

## Solution 2
instead of deleting release create new release with unique tag.

```yml
      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly [${{ needs.build_nightly.outputs.short_sha }}]
          tag_name: nightly-${{ needs.build.outputs.short_sha }}
```

### Reason

when a release is done it will show something like this 

![Screenshot 2023-12-08 211041](https://github.com/YimMenu/YimMenu/assets/139460769/6fa0aa32-6a8d-4dd2-be55-aaf774504ae6)

instead of incorrect "5 days ago"

![Screenshot 2023-12-08 211612](https://github.com/YimMenu/YimMenu/assets/139460769/12f52a54-d215-4c68-bf20-706240660a98)

**Comment by gir489returns** [comment]
Um, correct me if I'm wrong, but isn't that already covered in the name "nightly?" 🤨

**Comment by Yimura** [comment]
If the Github API is slow even though it said 200 success it might still take a while (a few seconds) and then when creating a new release it doesn't get published. This will require me to go in and manually update the release so it's public.

Also when creating a release with a unique tag it will bloat the tags of the repository really quickly combined with the fact that you can't explicitly check if a tag has a newer commit server-side than you've got locally.

**Comment by lonelybud** [comment]
> Um, correct me if I'm wrong, but isn't that already covered in the name "nightly?" 🤨

thats just the name of the release that gets update. Release remains the same identified by unique id and linked to unique tag.

**Comment by lonelybud** [comment]
> If the Github API is slow even though it said 200 success it might still take a while (a few seconds) and then when creating a new release it doesn't get published. This will require me to go in and manually update the release so it's public.
> 
> Also when creating a release with a unique tag it will bloat the tags of the repository really quickly combined with the fact that you can't explicitly check if a tag has a newer commit server-side than you've got locally.

there is api on both side deleting and creating. if delete api fails which it should never than there it will fallback to current scenario

**Comment by lonelybud** [comment]
nevertheless this improvement is not that magnificent. The release is nighty which is done at particular time and website `https://yim.gta.menu` is updating the label so i think it will not make difference here.
