### ISSUE TITLE
[Bug]: Update to Version: 3095

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#2513]
### Describe the bug

Rockstar dropped December update which outdated bunch of Pointers and prolly features as well

### Steps To Reproduce

1. Update and Open GTA
2. Inject Menu

### Expected Behavior

Working Fine

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13647301/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by SlavicBlin** [comment]
Going to assume that menu is not yet updated as trying to inject on the build made 1 hr ago just crashes the game 👍 all we can do is wait

**Comment by CypherMorgan** [comment]
yea the globals are updated but not the pointer sigs yet

**Comment by Yimura** [comment]
Issue is too generic to keep open, menu has been semi-updated for 1.67 b3095
