### ISSUE TITLE
[Question]: Is it safe?

### ISSUE THREAD

**Issue by muratcansimsek** [Yimura/YimMenu#2515]
### Problem

As far as I know, many players have been banned. Can I use it safely? I just want to protect myself from other cheaters.

### Solution

-

### Reason

-

**Comment by Yimura** [comment]
It _should_ be safe to use with the recent changes made to the anti-cheat bypass. However with the new update we won’t know until we update the menu.

**Comment by muratcansimsek** [comment]
I get it, I don't want to open a new ticket every time to do a risk assessment. https://github.com/YimMenu/YimMenu Can you make a section about player security that can be included on the homepage? For example, Status: Safe / Uncertain / Risky to use, you may be banned.

**Comment by Yimura** [comment]
Look I'd say that YimMenu or any other mod menu is risking a ban, so adding such a thing on the home page seems like a waste of time to keep up-to-date.

What I do hope to add to YimMenu is a remote kill switch for if we get reports of people getting banned we can remotely warn people that the mod menu is detected and it's probably best to not use it. Now this kill switch will never prevent you from using YimMenu, you'll be free to risk your account. The plan however is to just have it pop-up every time you launch the mod menu as a warning until you've updated to a safe version of the mod menu.
