### ISSUE TITLE
[Bug]: Sync nodes are busted?

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2525]
### Describe the bug

- Nonstop spammed with invalid player model (appearance node) crash from every player, if I don't crash.
- Spectate does not work, though it does on my private fork?

### Steps To Reproduce

play online

### Expected Behavior

not be spammed with false positives or crash

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Cant reproduce rn, ofc.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Waiting on @maybegreat48 to update GTAV-Classes.

**Comment by maybegreat48** [comment]
> Waiting on @maybegreat48 to update GTAV-Classes.

Yep, I'm working on it right now

**Comment by jvsandhu** [comment]
just so ya people know removing the scripts fixes the invalid model not a base menu bug I guess. could be wrong

**Comment by gir489returns** [comment]
You are wrong.

**Comment by jvsandhu** [comment]
also opening handling menu crashes the game.
[cout.log](https://github.com/YimMenu/YimMenu/files/13662976/cout.log)

**Comment by CypherMorgan** [comment]
> also opening handling menu crashes the game. [cout.log](https://github.com/YimMenu/YimMenu/files/13662976/cout.log)

Related with GTAV-Classes AFAIK
