### ISSUE TITLE
Spawn Max Vehicle Crash

### ISSUE THREAD

**Issue by Vlhss** [Yimura/YimMenu#253]
**Describe the bug**
When spawning certain cars while having the spawn max option enabled it crashes

**To Reproduce**
1. Go to Vehicle->Spawn
2. Search the car Banshee
3. Enable the spawn maxed option
4. Spawn the car
5. Crash

**Expected behavior**
Not to crash

**Screenshots**
-

**Logs**
-

**Build**
Select which applies for you:
- [ ] I used YimMenu unmodified
- [x] I use my own version of YimMenu

**Additional context**
While I do use my own version of YimMenu I haven't tweaked with vehicles yet. Also I tried with the latest build from github once and it crashed

**Comment by Yimura** [comment]
Going to close this in favour of making a new issue if the bug is recurring.
