### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by ege-art** [Yimura/YimMenu#2531]
### Describe the bug

Why does my Anti virus say that this has a Trojan or some kind that it didn’t have on the versions before, I scanned it on VirusTotal and it says Bkav Pro or whatever that sort of an virus that is. Can someone maybe explain this to me? 

### Steps To Reproduce

Download the DLL, trying to inject and then my computer blocks it 

### Expected Behavior

After injection to not get a virus warning

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by FIying-Scotsman** [comment]
It's a false positive. Malware also injects itself (or is injected) into processes like svchost so your AV is picking up an unsigned DLL is being injected into a remote process and throwing that message as a result. You can allow it in your AV to stop it quarantining the injector/dll.

As long as you only download releases from this repo you shouldn't have any issues.

**Comment by ege-art** [comment]
Okay thanks for letting me know
