### ISSUE TITLE
[Bug]: friends joining lobby dont show up

### ISSUE THREAD

**Issue by DSTC69** [Yimura/YimMenu#2532]
### Describe the bug

i have had it happen 2 or 3 times now and it only happens when the menu is loaded the moment i unload the menu everyone shows up on the map and it says they joined but they have been in the lobby the whole time

### Steps To Reproduce

be in a lobby 
have friend join and done

### Expected Behavior

for people to show up like gta online lol

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

i had this happen once in a older build 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Duplicate of #2526
