### ISSUE TITLE
[Bug]: Some eRemoteEvents out of date

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2534]
### Describe the bug

I've only tested sending a couple of script events such as interior tp, crash, and crash2, but they do not work. Additionally, player info doesn't work, though I suppose that's just waiting for @maybegreat48 to finalize the GPBD_FM update.

### Steps To Reproduce

Use the features listed above.

### Expected Behavior

The features to work.

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Thanks we had no idea were doing absolutely nothing until you told us.

**Comment by tyackman** [comment]
> Thanks we had no idea were doing absolutely nothing until you told us.

I figured you were enjoying singleplayer.
