### ISSUE TITLE
[Bug]: Crash when disabling lua script

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2540]
### Describe the bug

When unloading a lua script, gta goes brrr, though the script seems to be moved to the disabled folder just fine.

### Steps To Reproduce

1. Load a lua script
2. Unload the lua script

### Expected Behavior

Not crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13667203/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Unload and Reload all works fine, but unload specific scripts causes a crash. Maybe related to dependency scripts?

**Comment by maybegreat48** [comment]
Can confirm

**Comment by Yimura** [comment]
Fixed with #2745
