### ISSUE TITLE
[Bug]: Crash when Return personal vehicle to storage

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2541]
### Describe the bug

Game crashes when returning personal vehicle to storage via the interaction menu

### Steps To Reproduce

1. Call a personal vehicle
2. Navigate and select Interaction menu -> Return personal vehicle to storage

### Expected Behavior

Return vehicle to storage without crashing

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13667394/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Cannot reproduce. https://youtu.be/2jv5L_7FWOY

Most likely explanation: PEBCAK.

**Comment by YimMenuTheBest** [comment]
Requesting a personal car from the menu also causes a crash.

**Comment by takoyakiwhite** [comment]
This issue look about Classes

**Comment by lonelybud** [comment]
use latest build of menu. delete all settings & cache. dont use lua and check again.

**Comment by SlavicBlin** [comment]
fixed in https://github.com/YimMenu/YimMenu/pull/2561
