### ISSUE TITLE
[Bug]: Requesting a personal car from the menu causes a crash.

### ISSUE THREAD

**Issue by YimMenuTheBest** [Yimura/YimMenu#2542]
### Describe the bug

Requesting a personal car in the mod menu causes the game to hang up.

### Steps To Reproduce

1.- Request a personal car in the mod menu
2.- Game say goodbye uwu/

### Expected Behavior

The car spawns and does not cause the game to freeze.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13675981/cout.log)

### Store

Other (please mention in "Additional context")

### Language

English

### YimMenu Language

English (US)

### Additional context

Steam, RGL, Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
attach `cout.log` file when opening bug issues.

**Comment by gir489returns** [comment]
This is a duplicate of #2541 which I couldn't reproduce (invalid)

**Comment by YimMenuTheBest** [comment]
> This is a duplicate of #2541 which I couldn't reproduce (invalid)

This is not a duplication, the other issue talks about the interaction menu, I'm talking about yimmenu, anyway I leave a demonstration video

[Video](https://youtu.be/AiUQ8UDR1FU)

**Comment by gir489returns** [comment]
> > This is a duplicate of #2541 which I couldn't reproduce (invalid)
> 
> This is not a duplication, the other issue talks about the interaction menu, I'm talking about yimmenu, anyway I leave a demonstration video
> 
> [Video](https://youtu.be/AiUQ8UDR1FU)

https://youtu.be/wyXIeWlP1EA Can't reproduce.

**Comment by SlavicBlin** [comment]
> > > This is a duplicate of #2541 which I couldn't reproduce (invalid)
> > 
> > 
> > This is not a duplication, the other issue talks about the interaction menu, I'm talking about yimmenu, anyway I leave a demonstration video
> > [Video](https://youtu.be/AiUQ8UDR1FU)
> 
> https://youtu.be/wyXIeWlP1EA Can't reproduce.

i could reproduce with crash reasoning [19:24:43.1511534][FATAL/exception_handler.cpp:52] EXCEPTION_ACCESS_VIOLATION ]
currently building latest build of Yim to test again

**Comment by gir489returns** [comment]
Nothing I can do if I can't replicate it.

**Comment by SlavicBlin** [comment]
Still happening in latest build not sure why you cant replicate it...
heres the cout.log 
[cout.log](https://github.com/YimMenu/YimMenu/files/13677495/cout.log)

tried deleting Appdata but its still causing this issue.
but like you said if you cant replicate it then there is nothing that can be done for now i guess.

Edit:
I will try turning on preview and spawn inside to see if that helps.

Second Edit:
Did not help still crashed.

**Comment by SlavicBlin** [comment]
Not sure if this has anything to do with this crash but when the game crashes cout gives the output 
[20:13:55.8137095][FATAL/exception_handler.cpp:52] EXCEPTION_ACCESS_VIOLATION
Currently executing script: freemode
and when going into " freemode.hpp " there is alot of errors about things being undefined and other things saying name followed by :: must be a class or namespace name.

**Comment by CypherMorgan** [comment]
I was able to reproduce this but in a bit different way, spawning the PV using menu and then returning it back to garage which caused a crash (The car spawned for me) 

This is the Exception log.
[cout.log](https://github.com/YimMenu/YimMenu/files/13678031/cout.log)

**Comment by SlavicBlin** [comment]
> I was able to reproduce this but in a bit different way, spawning the PV using menu and then returning it back to garage which caused a crash (The car spawned for me)
> 
> This is the Exception log. [cout.log](https://github.com/YimMenu/YimMenu/files/13678031/cout.log)

yeah returning PV causes same error however my friend could not reproduce this error which is strange as some people can and others cant

only difference between me and my friend is he uses Windows 11 and i use Windows 10 but i doubt that has anything to do with it

**Comment by CypherMorgan** [comment]
> > I was able to reproduce this but in a bit different way, spawning the PV using menu and then returning it back to garage which caused a crash (The car spawned for me)
> > This is the Exception log. [cout.log](https://github.com/YimMenu/YimMenu/files/13678031/cout.log)
> 
> yeah returning PV causes same error however my friend could not reproduce this error which is strange as some people can and others cant
> 
> only difference between me and my friend is he uses Windows 11 and i use Windows 10 but i doubt that has anything to do with it

I'm using Win 10 too so might be a thing, not so sure.

**Comment by SlavicBlin** [comment]
> > > I was able to reproduce this but in a bit different way, spawning the PV using menu and then returning it back to garage which caused a crash (The car spawned for me)
> > > This is the Exception log. [cout.log](https://github.com/YimMenu/YimMenu/files/13678031/cout.log)
> > 
> > 
> > yeah returning PV causes same error however my friend could not reproduce this error which is strange as some people can and others cant
> > only difference between me and my friend is he uses Windows 11 and i use Windows 10 but i doubt that has anything to do with it
> 
> I'm using Win 10 too so might be a thing, not so sure.

Yeah no idea it would be really weird i honestly think its " freemode.hpp " since there is so many errors in there.

**Comment by gir489returns** [comment]
Have you guys tried without Yim injected? Maybe your GTA V install is contaminated?

**Comment by SlavicBlin** [comment]
> Have you guys tried without Yim injected? Maybe your GTA V install is contaminated?

Yes non injected and with other menus works fine.

edit: i will verify files to be sure 👍

**Comment by Yimura** [comment]
I can't reproduce this either, are you guys co-loading YimMenu with anything?

**Comment by SlavicBlin** [comment]
> I can't reproduce this either, are you guys co-loading YimMenu with anything?

nope... are you on windows 10 or 11 cuz all my friends on 11 are fine but friends and others on windows 10 are crashing...

**Comment by Yimura** [comment]
Win11

**Comment by SlavicBlin** [comment]
> Win11

that is actually so weird maybe some weird coincidence

**Comment by SlavicBlin** [comment]
Yeah i honestly dont know it might have something to do with windows 10 new update since i cant recreate this error at all on windows 11 i have asked 4 people to test on windows 10 and windows 11 and only people on windows 10 have crashed very very odd

edit: fixed spelling mistake

**Comment by gir489returns** [comment]
This may be fixed by https://github.com/YimMenu/YimMenu/pull/2561

**Comment by SlavicBlin** [comment]
> This may be fixed by #2561

Can confirm that fixed it

edit: Fixed spelling mistake

**Comment by SlavicBlin** [comment]
This can now be closed 
fixed in https://github.com/YimMenu/YimMenu/pull/2561
