### ISSUE TITLE
[Bug]: Random crash even with last version

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#2553]
### Describe the bug

Here the some when i test it :
- random crash while playing 
- return vehicles from intercation menu
-  spawn some new dlc vehicles lead to crash
- vehicle handling lead to crash

### Steps To Reproduce

- inject the menu in offline then go to online 

### Expected Behavior

.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13678456/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by 99-99itm** [comment]
> ### Describe the bug
> Here the some when i test it :
> 
> * random crash while playing
> * return vehicles from intercation menu
> * spawn some new dlc vehicles lead to crash
> * vehicle handling lead to crash
> 
> ### Steps To Reproduce
> * inject the menu in offline then go to online
> 
> ### Expected Behavior
> .
> 
> ### Logs and/or screenshots
> [cout.log](https://github.com/YimMenu/YimMenu/files/13678456/cout.log)
> 
> ### Store
> Steam
> 
> ### Language
> English
> 
> ### YimMenu Language
> English (US)
> 
> ### Additional context
> _No response_
> 
> ### Build
> * [x]  I've confirmed the issue exists on the latest version of YimMenu
> 
> ### Coload
> * [x]  I've tested this without co-loading anything.

HAVEING SAME PROBLEM ... GETTING RANDOM CRASHES ,,, WHILE DRIVING CARS 
BUT IT MIGHT GET FIXED SOON

**Comment by D-Borkan** [comment]
Edit : also new bug i found when test it already here #2555 
try to change from invite to public then crash
