### ISSUE TITLE
[Bug]: Session changing crash

### ISSUE THREAD

**Issue by 0CYBER** [Yimura/YimMenu#2555]
### Describe the bug

Session changing crash/freeze

### Steps To Reproduce

1. Load into the session with YimMenu
2. Try to change session

### Expected Behavior

Loading into another session without crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13678501/cout.log)

### Store

Steam

### Language

Russian

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is crashing in the script_vm function, @maybegreat48 can you take a look at the log?

**Comment by maybegreat48** [comment]
Are you sure that you aren't coloading anything with YimMenu?

**Comment by Yimura** [comment]
I was able to reproduce this.

**Comment by D-Borkan** [comment]
@0CYBER can you test this build here #2561
- cz i test it and work fine now
