### ISSUE TITLE
[Bug]: GETTING  RANDOM CRASHES 

### ISSUE THREAD

**Issue by 99-99itm** [Yimura/YimMenu#2556]
### Describe the bug

always crash when driving a car .. no idea why .. ALSO THIS IS THE BEST MOD MENU EVERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR TY FOR THE WORK FR FR 

### Steps To Reproduce

sit in a car and then drive for some time it will crash .. but  lobby must be full

### Expected Behavior

GETTING RANDOMLY CRASHED WHILE DRIVING A CAR

### Logs and/or screenshots

```
<paste your logs here>
```
[12-14-2023-22-56-32_cout.log](https://github.com/YimMenu/YimMenu/files/13678774/12-14-2023-22-56-32_cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

MUST BE SOME OPTION IN THE MENU CAUSING THE CRASH 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Please update YimMenu

**Comment by 99-99itm** [comment]
> Please update YimMenu

HI ... TY FOR THE RPLY I DID ... MUST BE PROBLEM FROM HERE ... MAY I ASK CAN I FIND ANY NEW LAU SCRIPTS ??

**Comment by Yimura** [comment]
> HI ... TY FOR THE RPLY I DID ... MUST BE PROBLEM FROM HERE ... MAY I ASK CAN I FIND ANY NEW LAU SCRIPTS ??

Hi there, this isn't the right place to ask this sort of question.
Consider making a discussion to ask these sorts of questions (DON'T MAKE AN ISSUE FOR THIS).

**Comment by 99-99itm** [comment]
> Please update YimMenu

![image](https://github.com/YimMenu/YimMenu/assets/122922328/a58b4384-699f-4855-9588-f7b7cb613a1b)
SEE CRASHED WHILE DRIVING CAR

**Comment by 99-99itm** [comment]
> > HI ... TY FOR THE RPLY I DID ... MUST BE PROBLEM FROM HERE ... MAY I ASK CAN I FIND ANY NEW LAU SCRIPTS ??
> 
> Hi there, this isn't the right place to ask this sort of question. Consider making a discussion to ask these sorts of questions (DON'T MAKE AN ISSUE FOR THIS).

I SEE  ..... MY BAD

**Comment by Yimura** [comment]
Yeah we're capturing these crashes ourselves, we'll fix them eventually, for now I've closed the issue as the title isn't descriptive and other users won't be able to easily match if they're experiencing the same without a proper title.

Also can you stop the ALL CAPS chatting, it's a bit annoying.
