### ISSUE TITLE
Secondary Gui

### ISSUE THREAD

**Issue by Killer4563782** [Yimura/YimMenu#256]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add a toggle to switch the Gui to a listgui 

**Provide Reasoning**
Becaus when i m playing with a Controller i have to switch every time to keyboard and mouse

**Comment by Vlhss** [comment]
Luna actually had this, it's a fantastic idea

**Comment by xM4ddy** [comment]
I'm not going to say its not going to happen but this would require quite a bit of work and I think I have heard the idea get shot down before.

**Comment by Aure7138** [comment]
sounds like a native ui and an imgui ui

**Comment by Killer4563782** [comment]
Actually true my idea that you just make a menu with DirectX where you can also navigate with the arrow keys and the controller

**Comment by Yimura** [comment]
No need for native ui ever, because most native UI's can be recreated using ImGui.

**Comment by Killer4563782** [comment]
true what I said
