### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by dilleraj** [Yimura/YimMenu#2560]
### Describe the bug

the game crashes when your in a car and click on handling in the mod menu

### Steps To Reproduce

1. login to gta 
2. boot up mod menu
3. get into any car
4. hit ins
5. click on vehicle
6. click on handling

### Expected Behavior

for it to open up the handling tab

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Duplicate of #2552
