### ISSUE TITLE
[Bug]: Some features from Yim aren’t working and malfunctioning 

### ISSUE THREAD

**Issue by Gituser4235** [Yimura/YimMenu#2567]
### Describe the bug

I can say that after the recent update, Yimmenu has shown some broken features. Here’s the list of features, as far as I can remember, which are not working: ESP, request Bullshark, Host kick, Off the radar, Some lua scripts, bring personal vehicle. In addiction, since after the update or before, some “protection” features are malfunctioning. For instance, when me and my friends were at the casino, I often received notifications alerting me that my friend was trying to crash me or sound spam me, though they never used any mods. This also applies to those players in the session but for now, I am getting these notifications from every single players in the session, which I find my pc screen covered with protection notifications. On top of that, I also find my self difficult to spawn vehicles or give weapons to spawned peds cuz the weapon and vehicle list are not written as English but as “???”. 

### Steps To Reproduce

1. Run gta and inject the menu
2. Try to use the features from the menu

### Expected Behavior

Features running without any problems

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
ESP is working fine, I just updated bull shark, we are not responsible for you to update the Lua scripts, bring personal vehicle is working. CBF'd to read the rest, you put too many things into one ticket as a giant wall of text.

**Comment by Gituser4235** [comment]
If yours working fine why not mine? I downloaded from the download page and I injected, didn’t even compile or added anything to it. What’s the cause then -__-? PC is updated to latest version any thoughts?

**Comment by 99-99itm** [comment]
> If yours working fine why not mine? I downloaded from the download page and I injected, didn’t even compile or added anything to it. What’s the cause then -__-? PC is updated to latest version any thoughts?

bruh .... lets just us appreciate the work he had put in his menu ... u are complaining about stupid things ... he had but 100  of hours for this menu ... if u are that un grateful then buy a mod menu

**Comment by Yimura** [comment]
No logs and possibly using an outdated version of YimMenu, consider updating and seeing which issues are still present.
