### ISSUE TITLE
[Bug]: game crashes on inject

### ISSUE THREAD

**Issue by bob6456** [Yimura/YimMenu#2576]
### Describe the bug
i use windows 10
if i want to inject the yimmenu my game crashes

### Steps To Reproduce

1 open gta
2 open yimmenu folder
3 inject yimmenu

### Expected Behavior

i want that the menu opens and gta dont crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13694191/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by D-Borkan** [comment]
try delete Yimmenu folder from appdate or use another injector

**Comment by bob6456** [comment]
> try delete Yimmenu folder from appdate or use another injector

i deletet every thing from yimmenu and i testet 2 injectors

**Comment by bob6456** [comment]
idk why but a friend from me that uses windows 11 can use the yimmenu normal and it dont crash

**Comment by UndeadCharacter** [comment]
This is happening to me aswell so hes not the only one having this issue. started a while ago and havent been able to play with the mod for the past three days or so.

> try delete Yimmenu folder from appdate or use another injector

Tried this aswell, Did not work, Not sure how to find the crashlogs for it either. ill poke around real quick and update you on anything i can find

**Comment by ToXicVibezz** [comment]
Download the newest Yim To Fix This :)

**Comment by ToXicVibezz** [comment]
> This is happening to me aswell so hes not the only one having this issue. started a while ago and havent been able to play with the mod for the past three days or so.
> 
> > try delete Yimmenu folder from appdate or use another injector
> 
> Tried this aswell, Did not work, Not sure how to find the crashlogs for it either. ill poke around real quick and update you on anything i can find

hit windows key // Type `%appdata%` .. Goto YimFolder
,, Send cout  .. Also Go Get New Yim.dll

**Comment by ToXicVibezz** [comment]
> ### Describe the bug
> i use windows 10 if i want to inject the yimmenu my game crashes
> 
> ### Steps To Reproduce
> 1 open gta 2 open yimmenu folder 3 inject yimmenu
> 
> ### Expected Behavior
> i want that the menu opens and gta dont crash
> 
> ### Logs and/or screenshots
> [cout.log](https://github.com/YimMenu/YimMenu/files/13694191/cout.log)
> 
> ### Store
> Steam
> 
> ### Language
> English
> 
> ### YimMenu Language
> English (US)
> 
> ### Additional context
> _No response_
> 
> ### Build
> * [x]  I've confirmed the issue exists on the latest version of YimMenu
> 
> ### Coload
> * [x]  I've tested this without co-loading anything.

Your Cout Says You Have Old Yim .. `Outdated`

**Comment by UndeadCharacter** [comment]
Thank you for the information. I will make sure to attach that next time if i get a bug. Can confirm it works just fine now! thank you again!

**Comment by bob6456** [comment]
i can play online now without crashing i deletet every thing from yimmenu i could find and now its working
