### ISSUE TITLE
[Improvement]: remove clean loop and fix current clean logic

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2579]
### Which feature

whenever player gets damaged it has blood decals, dirt, water & scars etc.
One can use clean button to clean player. It will not clean scars. Same is with clean loop bcz both use same function.

### remove clean loop
Clean loop purpose is to continuously clean player and so no need to manually open menu and hit the clean button. I think one can clean themselves by simply hitting clean button as necessary rather than running bunch of natives every frame.

### How to clean scars?
well one can add modify the clean function as -

```c++
	inline void clean_ped()
	{
		PED::CLEAR_PED_BLOOD_DAMAGE(ped);
		PED::CLEAR_PED_ENV_DIRT(ped);

                // https://forum.cfx.re/t/information-needed-to-clear-visible-player-damage-scars-etc/283216 
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 0, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 1, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 2, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 3, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 4, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 5, "ALL");
	}
```

i also removed `PED::CLEAR_PED_WETNESS(player_ped);` though its a decision one can make. It just removes water when you are wet.

### Reason

- clean loop is not such required. cleaning can be done as required.
- scars did not cleaned up. The above code guarantees one's beauty back.

**Comment by gir489returns** [comment]
I use keep player clean, this is a stupid suggestion. This isn't 1995 anymore, we're not counting clock cycles, and the people who want to save the runtime to not use this will do so by turning it off.

**Comment by lonelybud** [comment]
sure clean loop shall stay. as you said toggle is there

> I use keep player clean, this is a stupid suggestion. This isn't 1995 anymore, we're not counting clock cycles, and the people who want to save the runtime to not use this will do so by turning it off.
