### ISSUE TITLE
[Bug]: Chat log only logs my ip

### ISSUE THREAD

**Issue by USBMenus** [Yimura/YimMenu#2585]
### Describe the bug

yim only logs my ip address in the output, their username and rid are there but the ip is < UNKNOWN >

### Steps To Reproduce

open the chat.log file in the yimmenu folder

### Expected Behavior

it should show the ip address of every player and not just me

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Are you forcing a relay?

**Comment by USBMenus** [comment]
> Are you forcing a relay?

i dont think so

**Comment by USBMenus** [comment]
oh yea i am, thats my bad
