### ISSUE TITLE
[Bug]: Locking a cars doors, cannot be unlocked

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#2587]
### Describe the bug

I have locked my friend's car doors (he has unmodded gta) and when I press to unlock, it just doesn't unlock the doors no matter how many times I press.

### Steps To Reproduce

1. Have a player in a car
2. Lock that player's car doors
3. Unlock them
4. Doors won't be unlocked

### Expected Behavior

I expected it to unlock the doors

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

This issue has been present for a couple months so I don't associate it with the new update

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Do you know if this worked before the 3095 update?

**Comment by gamerboy1992** [comment]
> Do you know if this worked before the 3095 update?

This feature has not worked since version 2944 of gta. Since it was something so small I never bothered to report it

**Comment by gir489returns** [comment]
> > Do you know if this worked before the 3095 update?
> 
> This feature has not worked since version 2944 of gta. Since it was something so small I never bothered to report it

We like to use the "no news is good news" approach on features. We can't use and test everything, we just don't have the time given the amount of work that needs to be done, in the limited capacity the team has dedicated to the project, so if you do find something like this again, even if it's small or you feel it's irrelevant, let us make that decision, it's a process called triaging. Thanks for (eventually) reporting the issue. As you can see, it was a simple issue, and it was also a simple fix.
