### ISSUE TITLE
[Request]: crash players game

### ISSUE THREAD

**Issue by bob6456** [Yimura/YimMenu#2588]
### Solution

can you make that you add a button that you can crash the game from other people

### Reason

because it would be better to crash the game from trollers

**Comment by bob6456** [comment]
> ### Problem
> _No response_
> 
> ### Solution
> can you make that you add a button that you can crash the game from other people or can you add that you can spawn a car in front of the player
> 
> ### Reason
> because it would be better to crash the game from trollers
> 
> ### Additional context
> _No response_

**Comment by gir489returns** [comment]
"Become the thing you seek to destroy."

![image](https://github.com/YimMenu/YimMenu/assets/100792176/c4a393b9-9b05-4dd3-a256-5c8e968a741a)

**Comment by Striker0420** [comment]
Kicks works just fine, don't really need a crash, plus with join redirect if they try to join you again directly can direct it to someone else. Could also become host so it blocks them from joining so no need for crash really
