### ISSUE TITLE
[Request]: 1. xml vehicles search or 2. xml vehicle preview

### ISSUE THREAD

**Issue by bob6456** [Yimura/YimMenu#2589]
### Solution

1. add a search bar to search for an xml vehicle or 
2. add a preview for xml vehicles

### Reason

1. if you have to many xml vehicles you cant find the car you looking for 
2. you need to spawn the xml vehicle to see how it looks

**Comment by TheGreenBandit** [comment]
Adding searching in #2594, test and see how you like it
