### ISSUE TITLE
Certain crossmap entries are sigged

### ISSUE THREAD

**Issue by maybegreat48** [Yimura/YimMenu#259]
**Describe the bug**
Two crossmap entries have been added to the sigscanner recently

**To Reproduce**
1. Run sigscan tool on any menu

**Expected behavior**
N/A

**Logs**
```
{ 43 31 56 ce 63 35 95 5f 7e 67 24 a4 ea 5a 42 } (15) (v2628) (PAGE_READONLY)
{ 4b bd fe b8 9f 6f 66 83 4b bd fe b8 9f 6f 66 83 } (16) (v2628) (PAGE_EXECUTE_READWRITE)
```

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [x] I use my own version of YimMenu

**Additional context**
The entries are `{ 0x83666F9FB8FEBD4B, 0x83666F9FB8FEBD4B }` and `{ 0x953563CE563143AF, 0x425AEAA424677E5F }` which is `SYSTEM::TIMERA` and `PED::REGISTER_PEDHEADSHOT_TRANSPARENT` respectively

**Comment by Yimura** [comment]
Time to do something about this sigscanner, bypassing it is a temporary solution...

**Comment by yubie-re** [comment]
https://www.unknowncheats.me/forum/grand-theft-auto-v/492688-arxan-integrity-bypass.html
https://github.com/brunph/gta-antisig

1st one disables much more of the ac including scans, might need to be updated but should be trivial (usually last byte is diff), many p2cs use this lol. 
2nd disables the sig scan system only.

You have been given multiple bypasses (one more in the imgui issue) which disable it. There's no point in trying to circumvent the ac without a bypass, and I'm not quite sure why you haven't added anything yet.

Also wanted to say that this might not be directly targeted at you; scans target menus through region size.
Seen some people talk about it scanning gta in the imgui issue, but this is still a mystery to me. The region size is always 0 for gta sigs, which means they are never run. Interesting stuff. @maybegreat48, I'd recommend using a build based on my latest commit.

**Comment by Yimura** [comment]
@yubie-re so you're telling me there are no side effects from using that anti signature thing?

@maybegreat48 and I assumed that disabling the signature scanner might prevent the game from sending out "legit" sig scans.

**Comment by yubie-re** [comment]
no such thing as a legit sig scan, should work fine from my testing. chances are you already flag something else than sig scans anyway. the 1st one i listed would probably be more beneficial to use if you really want to cripple the AC, i haven't seen any arxan reports after using that.

**Comment by Yimura** [comment]
Alright sounds good to me, will implement the anti-sig, though for the other one I'll require some help from smarter people than I to help me with the UnknownCheats post.

**Comment by maybegreat48** [comment]
Totally missed this discussion here but yes the heartbeat thing seems to exist but I don't think blocking it has any adverse effects as of now. I recommend blocking the entire anticheat as there are unreversed functions that look like some kind of VM. About the arxan bypass, all the intercept sequences (no not the common call jmp ones) can be found by scanning `50 6A 10 48 F7 C4 0F` (8 results in 1.60, 6 in 1.58). I don't think blocking these things will block the anticheat as it seems to create a thread for itself (I haven't tested it however). Set a breakpoint at `44 8B 99 ? ? ? ? 4C 8B C9 B9 ? ? ? ? 4C 8B D2 44 3B D9 0F 8D ? ? ? ? 45 8B 81 ? ? ? ? 33 C0 41 FF C0 44 3B C1 44 0F 44 C0 41 8B 02 49 63 D0`. If it hits eventually (in a network game), the anticheat is running. Another thing is that looping `USING_MISSION_CREATOR` and `ALLOW_MISSION_CREATOR_WARP` will disable some parts of the AC like the frame flag detection, add owned explosion etc (you also get creator warp online as a side effect which basically automatically teleports you whenever you set a waypoint but you may need to nop `CEventNetworkCheatTriggered` as that gets triggered whenever you warp).

**Comment by DaniTRDev** [comment]
Yes, you are right. Arxan uses stack obfuscation as well as virtualization for its most critical structures. Also, talking about the thread shit, I think you are talking about the "watch dog thread". It's an odd timer that gets executed on-tick and do some bad operations to crash you if it gets that anything has been modified. It's initialized at start up and has it's own exclusive thread. It's retarded that you can patch either the thread spawner or the thread func without triggering other integrities.
