### ISSUE TITLE
[Bug]: Desync kick backfires every time

### ISSUE THREAD

**Issue by BlueGhost4** [Yimura/YimMenu#2590]
### Describe the bug

When i try to desync kick anyone (not as host) i get desync kicked instead.

### Steps To Reproduce

1. Go online
2. Select anyone
3. Click desync kick or multi kick option
4. Wait about 10s, after that you will be desync kicked and rejoining session

https://github.com/YimMenu/YimMenu/assets/145142640/560f8540-23a3-4487-87c2-74ece22c3d7f

### Expected Behavior

I'm not use if it's intended for a kick to backfire, i know that OOM can but i don't see the same information on the desync. Also the target player does not get kicked as i noticed.

### Logs and/or screenshots

```
[cout.log](https://github.com/YimMenu/YimMenu/files/13699049/cout.log)

<paste your logs here>
```

### Store

Steam

### Language

Polish

### YimMenu Language

English (US)

### Additional context

I notice the desync kick did that before the new update but it was not an issue for me, but now that i started to use the "block player from joining" more i get desync kicked every time someone is trying to join and i try to block that. I will also include my settings in case they would be needed. And log provided was not from the video but from a different time i played and that bug happened multiple times.
[settings.json](https://github.com/YimMenu/YimMenu/files/13699063/settings.json)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Could desync kicking have been patched in 3095? @maybegreat48

**Comment by lonelybud** [comment]
same

**Comment by BlueGhost4** [comment]
Again, i had that problem before 1.68 so it's not due to an update most likely.

**Comment by Striker0420** [comment]
> Could desync kicking have been patched in 3095? @maybegreat48

Desync kick seems fine at times, sometimes ive had it backfire on me but wasn't much. The multi kick backfires and does make you desync though

**Comment by pierrelasse** [comment]
Is it possible for the target to detect who he got desync kicked by and prevent themself from being kicked?

Also +1. I also have it sometimes backfire.

Edit: I did further testing and stumbled upon a modder and when i tried to desync kick him (my friend also tried. same thing), i got desync kicked after some time and he stayed in.
I asked him and he uses stand.

**Comment by BlueGhost4** [comment]
> Is it possible for the target to detect who he got desync kicked by and prevent themself from being kicked?
The desync is the only undetected kick that doesn't require host, all host kicks are not detected but cheaters and desync is not detected but all other methods are detected by other cheats, unless someone is useing kiddions, in that case they can't block anything.

**Comment by BlueGhost4** [comment]
Aciddently marked it, sorry

**Comment by BlueGhost4** [comment]
> Is it possible for the target to detect who he got desync kicked by and prevent themself from being kicked?
>
Yes, but the desync is the only non host kick that is not detected by other cheats, they can still block it but they will not know who tried to desync them most of the time. 
All host kicks are not blockable tho so if you have a host you can just kick anyone without any isssues and they can't block it.

**Comment by pierrelasse** [comment]
Okay so for example we have

Player1 (Host)
Player2 (You)
Player3 (Other modder)

If you would desync kick player3, he could detect it prevent themselfes from being kicked?

**Comment by BlueGhost4** [comment]
> Okay so for example we have
> 
> Player1 (Host) Player2 (You) Player3 (Other modder)
> 
> If you would desync kick player3, he could detect it prevent themselfes from being kicked?

Yes, they can prevent it but they don't know who did it 80% of the time from what i noticed. Same as yim menu will tell you that you have been desync kicked but it will not say who did it.
Unless you do something like null function kick or rotate camera they will not know who did it a lot of the time. So just using the desync can let you attempt a kick without the modder knowing yet but you have to spam the desync for it to work on a modder.

**Comment by maybegreat48** [comment]
It might backfire if the host is a modder, but should work otherwise. It's been a while since I looked at what the P2Cs are doing, so there could be a new protection that I'm not aware of

**Comment by AIdaveloper** [comment]
Desync kick in yim menu doesn't work now. Dont use it. It will backfire every time. Muktikick and block joins also use desync kick and it will have same effect.

No desync kick doesn't patched it still exist but need to update. You need to update the Network class. Its changed . and redesign the method of calling the function. Old function which been used now doesn't work with new network class.i know a new one but I'm not so good at assembly, but maybe someone who does it better could update it.


A bit more about desync. Desync kick can only be blocked by the host for another players. It's impossible to block desync if u non host. U can't detect who kicked u

**Comment by AIdaveloper** [comment]
Mb @Yimura could fix it

**Comment by maybegreat48** [comment]
> No desync kick doesn't patched it still exist but need to update. You need to update the Network class. Its changed . and redesign the method of calling the function. Old function which been used now doesn't work with new network class.i know a new one but I'm not so good at assembly, but maybe someone who does it better could update it.

I've updated the Network class a couple of days ago, and I can't reproduce this issue

**Comment by AIdaveloper** [comment]
> > No desync kick doesn't patched it still exist but need to update. You need to update the Network class. Its changed . and redesign the method of calling the function. Old function which been used now doesn't work with new network class.i know a new one but I'm not so good at assembly, but maybe someone who does it better could update it.
> 
> I've updated the Network class a couple of days ago, and I can't reproduce this issue

is desync kick working for you correctly?
I checked a few days ago and it backfire every time

**Comment by maybegreat48** [comment]
Yeah, the desync kick never backfires for me in the newest build

**Comment by AIdaveloper** [comment]
> Yeah, the desync kick never backfires for me in the newest build

sorry for wrong info. it works now
