### ISSUE TITLE
[Bug]: Speedometer overlay mixed with phone

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#2596]
### Describe the bug

Speedometer overlay sometimes appears weirdly inside the phone when I get calls and open the phone in general.

### Steps To Reproduce

1. Enable "Speedometer" in the "Vehicles" subsection
2. Enter any vehicle
3. Receive call or bring up phone
4. Observe the bugged overlay

### Expected Behavior

Expect either the overlay to disappear or move up above phone

### Logs and/or screenshots

![image](https://github.com/YimMenu/YimMenu/assets/84245768/922c8658-6202-44bc-a81e-fbd3ff69ae7b)
![image](https://github.com/YimMenu/YimMenu/assets/84245768/f8c076ed-5101-4650-97a9-c19fa33d3407)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
I guess check if the phone is opened before rending the speedometer?

**Comment by Aure7138** [comment]
What version are you using? It should have been fixed in #2378.

**Comment by gamerboy1992** [comment]
> What version are you using? It should have been fixed in #2378.

Using latest commit of YimMenu. Could it have to do with the resolution?

**Comment by gir489returns** [comment]
> What version are you using? It should have been fixed in #2378.

He couldn't possibly be on an older version, he's getting a call from Amir (3095) and that commit is from November.

**Comment by gir489returns** [comment]
@gamerboy1992 What resolution do you play at? The screenshot is posted in 1211x681 which is an extremely odd resolution. Is that 720 just crunched very hard into a borderless window, with a screenshot somehow taken without the windowed border?

**Comment by gamerboy1992** [comment]
> @gamerboy1992 What resolution do you play at? The screenshot is posted in 1211x681 which is an extremely odd resolution. Is that 720 just crunched very hard into a borderless window, with a screenshot somehow taken without the windowed border?

Playing in Fullscreen but this is also present with windowed borderless. Res is 1920x1080

I took the screenshot with Alt+Prt Screen, so maybe thats why it got a weird resolution

**Comment by gamerboy1992** [comment]
Just did some testing, it's working very strangely. I spawned a car and without moving, i pulled up my phone and the speedometer just fully disappeared. After driving it appeared again but inside the phone. Now I can't replicate it. Going to try some things

**Comment by gamerboy1992** [comment]
Ok, I think I know how to recreate it to some degree.

1. Suicide
2. Get in a car
3. Receive a call (random or go to those missions markers that if you don't have the business they will call you (Y, T...)
4. Watch the bugged overlay

This method seems to be a temporary one. But I am unsure as to the conditions to get the permanent overlay on the phone.

**Comment by gir489returns** [comment]
I think what is happening here, is the previous "fix" sets the draw order as the last call, and I guess when @Yimura tested it, he didn't test things like the other scripts resetting the draw order or calling RESET_SCRIPT_GFX_ALIGN in-between when the speedometer code finished and when it started up again. According to the scripts, you should set the order, do your draw code, then call RESET_SCRIPT_GFX_ALIGN to clean up after yourself. I've made PR #2601 to attempt to fix this wrapping issue, and hopefully it should solve your issue. Once the builder bot builds the PR, please test it.

**Comment by gamerboy1992** [comment]
> I think what is happening here, is the previous "fix" sets the draw order as the last call, and I guess when @Yimura tested it, he didn't test things like the other scripts resetting the draw order or calling RESET_SCRIPT_GFX_ALIGN in-between when the speedometer code finished and when it started up again. According to the scripts, you should set the order, do your draw code, then call RESET_SCRIPT_GFX_ALIGN to clean up after yourself. I've made PR #2601 to attempt to fix this wrapping issue, and hopefully it should solve your issue. Once the builder bot builds the PR, please test it.

Oh my bad I didn't read it fully, i thought it was going to be an actual commit. I tested it and I can't replicate any bugged overlay. Thank you! Going to play on that tested dll and see if anything happens
