### ISSUE TITLE
Add logging of freemode crash hashes

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#26]
Hello,

It would be helpful if you could like log which event with event hash the crash caused with the freemode script recovery

**Comment by Yimura** [comment]
I'm planning on adding a feature that you can toggle logging for several of the in-game events. The hash that crashed you is not available at the moment the freemode script recovery kicks in, it's almost near impossible to link the script hash with what made you crash. It's probably one of the last received script hashes right before you crash.

**Comment by Yimura** [comment]
To enable Script Event Logging, go to Windows (top-bar) => Debug (enable Debug Window) => Debug Tab => Script Event Logging

**Comment by MoneyDropLobby** [comment]
Thx
