### ISSUE TITLE
Fresh clone already defined DEBUG 

### ISSUE THREAD

**Issue by pard-00s** [Yimura/YimMenu#260]
**Describe the bug**
So I tried simply cloning the repo, running GenerateProjects and then building BigBaseV2 and I seem to get `DEBUG is already defined elsewhere which clashes with G3Log's log level DEBUG`

**To Reproduce**
1. Clone repo
2. Run GenerateProjects.bat
3. Build Solution

**Expected behavior**
Well, it's meant to just build the project normally

**Screenshots**
![error](https://i.imgur.com/lFbguU6.png)

**Logs**

```
Build started...
1>------ Build started: Project: g3log, Configuration: Debug x64 ------
2>------ Build started: Project: fmtlib, Configuration: Debug x64 ------
3>------ Build started: Project: MinHook, Configuration: Debug x64 ------
4>------ Build started: Project: ImGui, Configuration: Debug x64 ------
5>------ Build started: Project: GTAV-Classes, Configuration: Debug x64 ------
1>crashhandler_windows.cpp
2>format.cc
3>buffer.c
4>imgui_impl_dx11.cpp
3>hde32.c
3>hde64.c
3>hook.c
1>filesink.cpp
3>trampoline.c
4>imgui_impl_win32.cpp
3>Generating Code...
4>imgui.cpp
2>os.cc
3>MinHook.vcxproj -> C:\Users\Paradise\YimMenu\bin\lib\Debug\MinHook.lib
1>g3log.cpp
4>imgui_draw.cpp
2>Generating Code...
4>imgui_tables.cpp
4>imgui_widgets.cpp
2>fmtlib.vcxproj -> C:\Users\Paradise\YimMenu\bin\lib\Debug\fmtlib.lib
1>logcapture.cpp
4>Generating Code...
1>loglevels.cpp
4>ImGui.vcxproj -> C:\Users\Paradise\YimMenu\bin\lib\Debug\ImGui.lib
1>logmessage.cpp
1>logworker.cpp
1>stacktrace_windows.cpp
1>time.cpp
1>Generating Code...
1>g3log.vcxproj -> C:\Users\Paradise\YimMenu\bin\lib\Debug\g3log.lib
6>------ Build started: Project: BigBaseV2, Configuration: Debug x64 ------
6>Assembling src\invoker_asm.asm...
6>common.cpp
6>C:\Users\Paradise\YimMenu\vendor\g3log\src\g3log\loglevels.hpp(21,1): fatal error C1189: #error:  "DEBUG is already defined elsewhere which clashes with G3Log's log level DEBUG"
6>Done building project "BigBaseV2.vcxproj" -- FAILED.
========== Build: 5 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
Kinda weird that this happens with a fresh install

**Comment by Yimura** [comment]
Don't use Debug build or if you really need to use it then I'd assume you have the knowledge to fix this issue yourself.

**Comment by pard-00s** [comment]
Alright so I got it to work, you need to change from "Debug" to "Release" in Visual Studio
![image](https://user-images.githubusercontent.com/57621247/170871527-2f93e735-972b-4bcb-867b-754fe24a33f7.png)
