### ISSUE TITLE
[Bug]: When stealing a players outfit, it doesnt apply the accessories

### ISSUE THREAD

**Issue by USBMenus** [Yimura/YimMenu#2600]
### Describe the bug

when i try to steal someones outfit, it does not give me the players accessories

### Steps To Reproduce

go to a players name in the menu
click steal outfit

### Expected Behavior

it should give me the players accessories whenever i steal their outfit

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by USBMenus** [comment]
i figured it out and made a request

**Comment by lonelybud** [comment]
yes it is  problem and can be solved. by applying there props as well -

```c++
		PED::CLEAR_ALL_PED_PROPS(self::ped, 0);

		for (auto& item : props.items)
		{
			auto draw    = target ? PED::GET_PED_PROP_INDEX(target, item.id, 1) : item.drawable_id;
			auto texture = target ? PED::GET_PED_PROP_TEXTURE_INDEX(target, item.id) : item.texture_id;

			PED::SET_PED_PROP_INDEX(self::ped, item.id, draw, texture, TRUE, 1);
		}
```
