### ISSUE TITLE
[Request]: i have 4 thinks that i think are cool

### ISSUE THREAD

**Issue by bob6456** [Yimura/YimMenu#2605]
### Solution

1

### Reason

(1) a troll option that the player is like a magnet and it brings npcs/cars to the player That it does attract cars and npcs and the player dies because the cars and npcs crush you
(2) a troll option that you can ramm the player with a car/random car and a speed https://clipchamp.com/watch/rHlspcRQRVK
(3) a option to spawn objects at the player a mechanic press to kill the player or something like that https://github.com/YimMenu/YimMenu/assets/153788667/b583a8a9-24e7-45ee-8a68-a0375a801337
(4) a option to spawn cars in front the player that you dont need to spawn a car and then bring the player to you

(ufo thing) idk if you realy need this but it would be funny i think that you have a ufo wehre you can shot with and have a magnet on the bottom of the ufo where you can magnet cars idk

(bug) xml maps are not loading for other players i testet this with a friend and my friend didnt see the xml map but if i have a xml car my friend can see the xml vehicle thinks a ramp on the car and stuff like this or do i need to spawn a xml vehicle jump ramp on the car or something like this

i think this stuff would be cool to use

**Comment by ToXicVibezz** [comment]
`	inline void ram_player(Player player)
	{
		float offset;
		Hash vehmodel = RAGE_JOAAT("PARIAH");
		STREAMING::REQUEST_MODEL(vehmodel);

		while (!STREAMING::HAS_MODEL_LOADED(vehmodel))
			script::get_current()->yield();
		Vector3 pCoords = ENTITY::GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player), 0.0, -10.0, 0.0);

		if (STREAMING::IS_MODEL_IN_CDIMAGE(vehmodel) && STREAMING::IS_MODEL_A_VEHICLE(vehmodel))
		{
			Vector3 dim1, dim2;
			MISC::GET_MODEL_DIMENSIONS(vehmodel, &dim1, &dim2);

			offset = dim2.y * 1.6f;

			Vector3 dir = ENTITY::GET_ENTITY_FORWARD_VECTOR(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player));
			float rot   = (ENTITY::GET_ENTITY_ROTATION(PLAYER::GET_PLAYER_PED_SCRIPT_INDEX(player), 0)).z;

			Vehicle veh =
			    VEHICLE::CREATE_VEHICLE(vehmodel, pCoords.x + (dir.x * offset), pCoords.y + (dir.y * offset), pCoords.z, rot, 1, 1, false);

			VEHICLE::SET_VEHICLE_ON_GROUND_PROPERLY(veh, false);
			ENTITY::SET_ENTITY_VISIBLE(veh, true, 0);
			VEHICLE::SET_VEHICLE_FORWARD_SPEED(veh, 700.0);
		}
	}`

**Comment by ToXicVibezz** [comment]
ram player

**Comment by maybegreat48** [comment]
The Lua script engine is designed for feature requests such as these. The Lua docs are available [here](https://github.com/YimMenu/YimMenu/tree/master/docs/lua), and you can also ask someone to create one for you if you don't know how

**Comment by Yimura** [comment]
These would be better to be added as a Lua script rather than directly in the menu.
