### ISSUE TITLE
When you call on someone squad spawner npcs, istead of shooting the player, npcs shows to player middile finger[Bug]: 

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2615]
### Describe the bug

When you call on someone squad spawner npcs, istead of shooting the player, npcs shows to player middile finger

### Steps To Reproduce

s

### Expected Behavior

Shooting the player it should not middile finger player kind of funny but after player gets killed by npcs and when it respawns npcs will chase the player hunt him but they will not shoot the player but instead they will just keep following chasing player and nothing else

### Logs and/or screenshots

```
<paste your logs here>d
```
sas

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

s

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Tayipc38** [comment]
This means you have given the spawner either no weapon model or an invalid one. As for the behavior when the player respawns, unavoidable the way this feature is built.
