### ISSUE TITLE
some features work and some dont pls do more bug fixes[Bug]: 

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2616]
### Describe the bug

some features work and some dont pls do more bug fixes[Bug]: 

### Steps To Reproduce

some features work and some dont pls do more bug fixes[Bug]: 

### Expected Behavior

some features work and some dont pls do more bug fixes[Bug]: 

### Logs and/or screenshots

```
<paste your logs here>
```
some features work and some dont pls do more bug fixes[Bug]: 

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
What a terrible issue.
