### ISSUE TITLE
[Request]: You can call on someone a mugger npc to steal many cash or just few cash like a "gooh test" but actually make mugger feature workable unlike gooh test where you click at it and it do nothing now and lower cooldown

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2618]
### Problem

[Request]: You can call on someone a mugger npc to steal many cash or just few cash like a "gooh test" but actually make mugger feature workable unlike gooh test where you click at it and it do nothing now and lower cooldown

### Solution

[Request]: You can call on someone a mugger npc to steal many cash or just few cash like a "gooh test" but actually make mugger feature workable unlike gooh test where you click at it and it do nothing now and lower cooldown

### Reason

[Request]: You can call on someone a mugger npc to steal many cash or just few cash like a "gooh test" but actually make mugger feature workable unlike gooh test where you click at it and it do nothing now and lower cooldown

### Additional context

[Request]: You can call on someone a mugger npc to steal many cash or just few cash like a "gooh test" but actually make mugger feature workable unlike gooh test where you click at it and it do nothing now and lower cooldown

**Comment by Yimura** [comment]
The way you've filled in the issue template is basically an insult to all the contributors to this project.

Please fill in the issue template correctly.
