### ISSUE TITLE
[Request]: More squads in squad spawner npcs

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2619]
### Problem

[Request]: More squads in squad spawner npcs
Can be a mugger or snipers etc

### Solution

[Request]: More squads in squad spawner npcs

### Reason

[Request]: More squads in squad spawner npcs

### Additional context

[Request]: More squads in squad spawner npcs

**Comment by Yimura** [comment]
Fill in the issue templates correctly.
