### ISSUE TITLE
Pickup Reward Crash Protection

### ISSUE THREAD

**Issue by Vlhss** [Yimura/YimMenu#262]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
-

**Provide Reasoning**
Makes the menu safer for future use

**Additional context**
```
case GIVE_PICKUP_REWARDS_EVENT:
			{
				uint32_t amount{}, reward_hash{};
				buffer->ReadDword(&amount, 3);
				buffer->ReadDword(&reward_hash, 32);
				if (is_crash_reward(reward_hash))
				{
					BlockedEvent(eventName, source_player);
					g_pointers->m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);
					return false;
				}
				buffer->Seek(0);
				if (g_settings.options["log network events"] > 0)
					LOG(EVENT) << "Network Event from: " << source_player->player_info->m_name << " Type: " << eventName << " Value: " << amount << " reward_hash:" << HEX_TO_UPPER(reward_hash);
				return true;
			}
```
https://www.unknowncheats.me/forum/grand-theft-auto-v/414849-hooking-network-events-2.html
Thanks to spankerincrease for sharing this back in 2020

**Comment by Vlhss** [comment]
There are some things that need to be tweeked like the if statement when checking if the reward is valid and the last if statement but idk how to open a pull request

**Comment by Sainan** [comment]
This crash has been patched I think around tuners dlc

**Comment by Adler-D3R** [comment]
I tried this and now it seems to kick people, but does not crash them. The crurent Freemode Patch should prevent it.

**Comment by Yimura** [comment]
@Adler-D3R which sort of people does it kick exactly? The ones that have the protection or those that don't have it.

I couldn't figure this out from what you said.

**Comment by Adler-D3R** [comment]
> @Adler-D3R which sort of people does it kick exactly? The ones that have the protection or those that don't have it.
> 
> I couldn't figure this out from what you said.

I tried on some randon people, so I guess it  works against those who don't have the protection. However, I think it has to do with the Freemode Handler, that's why I said I think the actual patch can solve this kick. From what I tested, it kinda kicks like a SE Kick : you spawn it, the target picks it up, you see the " XXX has left ", and like 15 seconds after he is removed from the Player List.

**Comment by Yimura** [comment]
Ok so kick protection would still be welcome for this

**Comment by Adler-D3R** [comment]
In my opinion, if the actual Freemode Patch works, no need to add this cause it will not really help since it is already patched. Moreover, the less checks we do, the smoother the game will run, even if this is a tiny check. But yeah if you want to add it go ahead, it's welcome

**Comment by DaniTRDev** [comment]
> 

If the script thing stops this then there's no need of adding it to the src. Although I'd recommend to make a .txt file to know how the kick works. Won't be surprised if R* fucks it in comming updates and it starts to crash people, again.

**Comment by Adler-D3R** [comment]
I made tests and the actual Freemode patch blocks the kick so all good. We could add a check in ReceivedEvent Hook to get a notification of someone tries to kick you like this. I think we can close this issue now, to clear the lost being kinda huge right now.

**Comment by Yimura** [comment]
Should no longer be an issue.
