### ISSUE TITLE
[Request]: help

### ISSUE THREAD

**Issue by bob6456** [Yimura/YimMenu#2620]
### Solution

e

### Reason

i played normal and i didnt do any thing crazy and now this happend :(

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/153788667/2a3c8ca2-f8b6-4ca4-89d5-b00d8e5f7ddb)

**Comment by gir489returns** [comment]
You got banned.

**Comment by Yimura** [comment]
How long have you been using YimMenu?
When do you usually inject (online or single player)?
What features have you been using?

Can you post your cout.log and your settings.json?

**Comment by D-Borkan** [comment]
Did this happen to you while in the session ?

**Comment by bob6456** [comment]
> How long have you been using YimMenu? When do you usually inject (online or single player)? What features have you been using?
> 
> Can you post your cout.log and your settings.json?

2 days

**Comment by bob6456** [comment]
> How long have you been using YimMenu? When do you usually inject (online or single player)? What features have you been using?
> 
> Can you post your cout.log and your settings.json?

(1) 2 days because i startet playing gta because i didnt play it for 6 monts and all time i used yimmenu 2monts i think
(2) loading screen and story mode
(3) kick fly noclip ragdoll frezze godmode stuff cage gun paint gun car gun xml vehicles horn boost car jump teleport/bring player bring player in job thing upgrade player car downgrade player car vehicle kick vehicle remote controll boost vehicle burst tires spawn player model spawn enemy rainbow car explode player

**Comment by bob6456** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/13732393/cout.log)

[settings.json](https://github.com/YimMenu/YimMenu/files/13732394/settings.json)

**Comment by gir489returns** [comment]
If you were harassing players they probably reported you.

**Comment by bob6456** [comment]
> Did this happen to you while in the session ?

no i waket up and wantet to play and this happend

**Comment by bob6456** [comment]
> If you were harassing players they probably reported you.

i only kicket modders that trolled other players

**Comment by bob6456** [comment]
> How long have you been using YimMenu? When do you usually inject (online or single player)? What features have you been using?
> 
> Can you post your cout.log and your settings.json?

and i spawned this https://www.youtube.com/watch?v=VDVy819sKY4&t=2s  https://www.youtube.com/watch?v=qaoOS4ZO5Wo&pp=ygUSZ3RhIDUgZG9kZ2UgcG9saWNlv=KsDivtay58Y

**Comment by maybegreat48** [comment]
Did you install a lua script to cheat money?

**Comment by bob6456** [comment]
> Did you install a lua script to cheat money?

no i never cheatet money/level but yesterday some modder gave me money but i hat the no pickup thing on but i still got 20k i think

**Comment by bob6456** [comment]
i got this commet from the ticket from rockstar
Hello gta5noob_1,

Thank you for contacting Rockstar Support about the ban on your account.

All GTA Online accounts and/or gaming systems that violate the End User License Agreement and/or Terms of Service are subject to suspension or permanent banning depending on the severity or volume of actions performed on the account.

When accounts are suspended or banned, the associated characters are wiped. When this happens any purchased Shark Card funds remain on the account but all other progress is removed.

For more information about our policies, please see: [https://www.rockstargames.com/eula](https://www.rockstargames.com/eula?_gl=1*sg807l*_ga*MTc3OTM2Njk1LjE2OTE2ODM2NDE.*_ga_PJQ2JYZDQC*MTcwMzEwMTMwMy4xMC4xLjE3MDMxMTA5NDQuMC4wLjA.) [https://www.rockstargames.com/legal](https://www.rockstargames.com/legal?_gl=1*sg807l*_ga*MTc3OTM2Njk1LjE2OTE2ODM2NDE.*_ga_PJQ2JYZDQC*MTcwMzEwMTMwMy4xMC4xLjE3MDMxMTA5NDQuMC4wLjA.) https://support.rockstargames.com/articles/229514247

If you have any unrelated issues that we can assist with, please let us know. This ticket will now be closed since we do not provide further details about our security detections or the security actions taken on players’ accounts.

Best regards,


December 20, 2023

**Comment by bob6456** [comment]
then i need to play on my xbox one acc

**Comment by maybegreat48** [comment]
Yes, you are banned and we can't do anything about that
