### ISSUE TITLE
[Bug]: False sound spam crash during the data breachs heist 

### ISSUE THREAD

**Issue by USBMenus** [Yimura/YimMenu#2624]
### Describe the bug

when going into the control center and manning the guns, when the players shoot it detects them as sound spamming

### Steps To Reproduce

start the data breaches heist
proceed to the control rooms and wait for everyone to get in the gun
have the players shoot 

### Expected Behavior

i expect it to be fine and not detect the players as sound spamming

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

i was lagging pretty bad so im not sure if that could have something to do with it, but i tested it twice and it happened both times

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by USBMenus** [comment]
> No log = not helpful.

[cout.log](https://github.com/YimMenu/YimMenu/files/13734102/cout.log)

first time was at 00:51:36.6888395
second time was at 01:11:27.3669054

**Comment by gir489returns** [comment]
Your log is absolutely bursting with red flags. I don't even know where to begin.

**Comment by gir489returns** [comment]
Did you coload this with anything? I know you checked the box, and clearly you can read, but you've done this before, where you submit tickets without reading and obeying the rules before submitting a ticket.

**Comment by USBMenus** [comment]
> Did you coload this with anything? I know you checked the box, and clearly you can read, but you've done this before, where you submit tickets without reading and obeying the rules before submitting a ticket.

no, i did not co load with any other menu
the reason i had done that before is cause i couldnt submit it without checking the box, wont happen again tho, i apologize

**Comment by USBMenus** [comment]
> Your log is absolutely bursting with red flags. I don't even know where to begin.

i have a few outdated scripts that i havent deleted yet, but they shouldnt affect anything as i dont use them
