### ISSUE TITLE
Vehicle Tank Mod

### ISSUE THREAD

**Issue by bigdaddy2142** [Yimura/YimMenu#2626]
### Solution

Option to make cars and peds bounce off of your car at high speeds

### Reason

Good fun

**Comment by binded-zz** [comment]
theres a force field option in SCH lua script  https://github.com/sch-lda/SCH-LUA-YIMMENU

look for the english version https://github.com/Drsexo/English-Sch-lua/


vech and ped force fields 
many many other option s

**Comment by GreySideMM** [comment]
> theres a force field option in SCH lua script https://github.com/sch-lda/SCH-LUA-YIMMENU
> look for the english version https://github.com/Drsexo/English-Sch-lua/

That's a nice script! But what it does is a bit different.
I was wondering how to have "tank" abiliets, too. Changing the mass of a vehicle simply doesn't do the trick. Or is it broken? I couldn't find any differences when setting a vehicles mass the last time I checked.
