### ISSUE TITLE
What is this gamemode?

### ISSUE THREAD

**Issue by cristyanul** [Yimura/YimMenu#263]
**Describe the bug**
I got into a crazily fun game mode

**To Reproduce**
1.No idea
I want to find out how I got into that "gamemode"

**Expected behavior**
I became god

**Screenshots**
https://imgur.com/Z5o3x1p
**Logs**

```
<paste your logs here>
```

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**

**Comment by Yimura** [comment]
Related issues #241 #236 

Currently the context menu can be opened by pressing the button for ducking in a vehicle.
By default this is the `X` button on keyboard, in the future we'll be working on adding settings to access this.
