### ISSUE TITLE
[Request]: xml VEHICLES

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2632]
### Problem

Add a xml vehicles to yim menu please

### Solution

Add a xml vehicles to yim menu please

### Reason

Add a xml vehicles to yim menu please

**Comment by CypherMorgan** [comment]
Open Menu, Vehicle Tab < Spawn Vehicle < XML Vehicles

**Comment by cultysdaop** [comment]
Theres none in there

> Open Menu, Vehicle Tab < Spawn Vehicle < XML Vehicles

**Comment by CypherMorgan** [comment]
You want the XML Vehicle files that can be spawned or the ability to spawn XML vehicle?

**Comment by cultysdaop** [comment]
> You want the XML Vehicle files that can be spawned or the ability to spawn XML vehicle?

I want something like in Aurora Mod Menu where there are already ready xml vehicles to spawn and you can just scroll down and you can choose which one to spawn.

**Comment by Yimura** [comment]
YimMenu gives you the tools, adding vehicles into YimMenu by default bloats the experience.

Please find them yourself.

**Comment by cultysdaop** [comment]
how to add to yim menu xml vehicles maybe a tutorial idk how to do it, i did copy and paste xml vehicles from aurora to xml vehicles folder in yim menu and it didnt worked, i had no xml vehicles to spawn in Open Menu, Vehicle Tab < Spawn Vehicle < XML Vehicles

**Comment by CypherMorgan** [comment]
[xml_vehicles.zip](https://github.com/YimMenu/YimMenu/files/13754371/xml_vehicles.zip)
This Might help you, it's a collection of 1.1k xml files I got (Some doesn't work).
Try adding these to Appdata < Roaming < YimMenu < xml_vehicles

**Comment by cultysdaop** [comment]
Ah thanks, i pasted xml vehicles in yim menu folder maybe thats why it didnt worked for me.
Thanks.
Kind regards.

**Comment by CypherMorgan** [comment]
Np, Happy modding haha!
