### ISSUE TITLE
[Request]: add a recovery feature 

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#2633]
### Problem

For example you can drop collectables to other players and money options to give 

### Solution

For example you can drop collectables to other players and money options to give 

### Reason

For example you can drop collectables to other players and money options to give

**Comment by CypherMorgan** [comment]
#237 This might help you.

**Comment by yousef157** [comment]
basically what #237 says... YimMenu doesn't want to be fucked by 2take1 and I assume it just leaves it to people with lua scripts for those who really want recoveries

**Comment by CypherMorgan** [comment]
> basically what #237 says... YimMenu doesn't want to be fucked by 2take1 and I assume it just leaves it to people with lua scripts for those who really want recoveries

Not the 2Take1, It's Take2, R*'s Anticheat system, Afaik

**Comment by xiaoxiao921** [comment]
Duplicate.

**Comment by yousef157** [comment]
> > basically what #237 says... YimMenu doesn't want to be fucked by 2take1 and I assume it just leaves it to people with lua scripts for those who really want recoveries
> 
> Not the 2Take1, It's Take2, R*'s Anticheat system, Afaik

Sorry, I got them both mixed up. I haven't heard of Take2 in a long time
