### ISSUE TITLE
[Request]: Kill enemies loop

### ISSUE THREAD

**Issue by BlueGhost4** [Yimura/YimMenu#2635]
### Problem

Kill enemys button has limited range in a lot of cases and enemys offten spawn in over time.

### Solution

Add kill enemies loop to the menu (I think any interval below 3s would be fine)

### Reason

A lot of missions require you to kill enemies that spawn in over time so i think it would be a good quality of life improvement .

**Comment by pierrelasse** [comment]
A option to make it a headshot would be also very cool.

**Comment by BlueGhost4** [comment]
> A option to make it a headshot would be also very cool.

True, also would be good.

**Comment by xiaoxiao921** [comment]
trivially doable as a lua feature
