### ISSUE TITLE
Solved: GTA V crashes when injecting Yim.

### ISSUE THREAD

**Issue by idontdef** [Yimura/YimMenu#2636]
### Describe the bug

I get this error
```
 ntdll.dll RtlUserThreadStartFailed to find some patterns for Social Club
[13:27:19.2961401][WARN/batch.hpp:113] Failed to find 'RAP'.
[13:27:19.3124861][FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3765269347

```

### Steps To Reproduce

1. Inject YimMenu.dll through Xenos64
2. Yim and GTA V crashes after barely a second.

### Expected Behavior

It would load.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13752828/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Either outdated YimMenu or socialclub.dll updated.

**Comment by idontdef** [comment]
I used YimMenu latest version (1.68)
and same GTA V (1.68 3095 build)

Update: tried verifying the integrity of the game
I have installed GTA on epic aswell as on steam but not in the same directory. Could that be the issue

**Comment by Aure7138** [comment]
Maybe update your socia club launcher
https://socialclub.rockstargames.com/rockstar-games-launcher

**Comment by gir489returns** [comment]
> Either outdated YimMenu or socialclub.dll updated.

I seriously doubt that. That’s the same signature I just updated. It’s more likely his social club is out of date.

**Comment by idontdef** [comment]
I have installed GTA on epic aswell as on steam but not in the same directory. Could that be the issue? I was banned from Steam so I bought the account on epic, when the ban/suspension cleared, I tried using steam but it wont inject

**Comment by idontdef** [comment]
Fixed:
How to fix, 
If you have the game installed in Epic aswell as in Steam, then in order to play on steam, you need to update your Social Club Launcher.
Thanks to @Aure7138 for the help
