### ISSUE TITLE
[Bug]: Crash when going to Settings->Hotkeys

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#2643]
### Describe the bug

When I press "Settings" and try to press "Hotkeys", the game just crashes and I get the message below.

### Steps To Reproduce

1. Open Menu
2. Press "Settings"
3. Press "Hotkeys" and watch game crash

### Expected Behavior

Expect the game not to crash.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13760577/cout.log)

![Picture1](https://github.com/YimMenu/YimMenu/assets/84245768/813d3a3e-fb46-4774-bf41-7b79ada0d48e)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

This has never happened before and I have rebuilt from scratch twice to make sure. If any more files are needed please let me know.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Compile in release mode.

**Comment by TheDuke203** [comment]
+1 I recently built yim in debug and it showed the same error, its fine in release mode
@gir489returns Do you know exactly why in debug mode it crashes it would be interesting to know

**Comment by gamerboy1992** [comment]
> Compile in release mode.

I never change anything when compiling but I will double check and let you know. Sorry and thank you.

**Comment by gamerboy1992** [comment]
I can confirm I did indeed, somehow, set it to debug. I apologise for the confusion. Thank you for helping!

**Comment by TheDuke203** [comment]
You may wish to close the issue, if its solved as well :)
