### ISSUE TITLE
this seems to have broken something, it just snaps at random npcs and when aiming you cant get the crosshair off the randomly selected target 

### ISSUE THREAD

**Issue by janka23** [Yimura/YimMenu#2655]
Download the artifacts for this pull request:

* [binary.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/1199539776.zip)

_Originally posted by @github-actions[bot] in https://github.com/YimMenu/YimMenu/issues/2653#issuecomment-1913107588_

**Comment by gir489returns** [comment]
We are aware of the issue, and it was present in @navmodder's original commit. However, we do not know how to fix it.

**Comment by Yimura** [comment]
Good job on following the issue template 👍 /s

Also terrible titling!

**Comment by Yimura** [comment]
Next time follow the issue template or your issue will be removed.

**Comment by Sys0xdbg** [comment]
Yeah, I couldn't add a comment to the commit. I was thinking we could just switch to get_entity_closest_to_middle_of_screen.
