### ISSUE TITLE
[Bug]: Disabling Lua Scripts

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2661]
### Describe the bug

Disabling lua scripts one by one causes the game to crash, the disable all button works, just the normal disable one crashes

### Steps To Reproduce

click a lua script, click disable.

### Expected Behavior

pretty sure its supposed to disable the selected script

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by tyackman** [comment]
Duplicate of #2540
