### ISSUE TITLE
[Bug]: Custom weapon names are not translated in the menu

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2668]
### Describe the bug

https://prnt.sc/J_RzU4uPHdtB

### Steps To Reproduce

use eyes and look

### Expected Behavior

Should be translated to proper language

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

Newest nightly build

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Yup the bug is definitely there, should be trivial to fix, we can possibly move the call to fetch the names from the translation service in the UI loop (instead of in code that initializes once) however that'll add additional delays to frame timing.
