### ISSUE TITLE
[not bug][question]Correct way to add new feature

### ISSUE THREAD

**Issue by JTD420** [Yimura/YimMenu#267]
Hi,

I was just wondering if you could point me in the right direction of where I am going wrong with my code here?

I'm aware that both of these functions already exist in the menu but this was more of an exercise for me to see that I understand how the menu is working!

I have tried to create a new feature called NoRagdollSeatbelts which is just supposed to be like turning on/off the Radoll feature and the Seatbelts feature at the same time apposed to having to turn each option on/off individually.

This is the code I have got to do so

**backend/looped/self/no_ragdoll_seatbelts.cpp**:
```
#include "backend/looped/looped.hpp"
#include "services/player_service.hpp"
#include "natives.hpp"
namespace big
{
	static bool bLastNoRagdollSeatbelts = false;

	void looped::self_no_ragdoll_seatbelts()
	{
		bool bNoRagdollSeatbelts = g->self.no_ragdoll_seatbelts;

			if (bNoRagdollSeatbelts || (!bNoRagdollSeatbelts && bNoRagdollSeatbelts != bLastNoRagdollSeatbelts))
			{
				PED::SET_PED_CAN_RAGDOLL(self::ped, !g->self.no_ragdoll_seatbelts);
				PED::SET_PED_CONFIG_FLAG(self::ped, 32, false);
				PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(self::ped, 1);

				bLastNoRagdollSeatbelts = g->self.no_ragdoll_seatbelts;
			}
	}
}
```

I have also included the definitions in the globals.cpp and looped.hpp files respectively. 

I've tried a couple different variations so far but to no success! 

Also I tried adding in some other features last night which seemed to crash me immediately when I turned the options on... But when I tried to co-load my menu with stand and then tried the same features I added that crashed me before, they worked fine and with no crash! 😕 

Could it have had anything to do with the fact I didn't put them in the looped class when they were looping functions? I didn't realise there was the looped class till today so been trying to familiarise myself with it lol!

**Comment by JTD420** [comment]
Also is there a better place than here to ask questions related specifically to yim menu? Possibly a discord etc?

**Comment by Killer4563782** [comment]
Yes on the discord

**Comment by Killer4563782** [comment]
https://discord.gg/EG4zHFR
