### ISSUE TITLE
[Bug]: Aimbot FOV broken

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#2671]
### Describe the bug

Literally FOV setting not exists, i got instant aim move to any target on map, which i cant even see, with no delay between targets or FOV check.

### Steps To Reproduce

Enable Aimbot > try to aim

### Expected Behavior

FOV exists

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Related to #2669

**Comment by vladdoser** [comment]
> Related to #2659

It was at least normal, before last release, so i reported.

**Comment by Yimura** [comment]
I don't like aimbot in GTA V as it really just feels like a serious skill issue if you can't aim properly at peds. Though if someone else finds the time to fix this PROPERLY then we'll allow the code to be merged.

**Comment by SuEuMesma** [comment]
> Eu não gosto de aimbot em GTA V, pois realmente parece um problema sério de habilidade se você não pode mirar corretamente em peds. Embora se alguém encontrar tempo para corrigir isso CORRETAMENTE, então vamos permitir que o código seja mesclado.

Some people have a disability in aiming correctly, or have bad equipment. There's also the fact that people with joysticks can enable the aim lock function, making the competition a bit dodgy if you have enough money to buy a good joystick.

I used Yimmenu simply because he had an Aimbot, even though he had some flaws.
