### ISSUE TITLE
[Bug]: Crashed by stand

### ISSUE THREAD

**Issue by tyackman** [Yimura/YimMenu#2672]
### Describe the bug

Either the burger king foot lettuce, or the elegant crash is the culprit.

### Steps To Reproduce

Hurt a stand users feelings

### Expected Behavior

Not crash

### Logs and/or screenshots

[stand make game go brrr.log](https://github.com/YimMenu/YimMenu/files/14088682/stand.make.game.go.brrr.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

I will post the clone sync/script event logs when I can later, unless someone beats me to it.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by who-care123** [comment]
patch it through `WEAPON_DAMAGE_EVENT`
caused by invalid weapon type(hash) like `RAGE_JOAAT("weapon_explosion")`(this is valid)

**Comment by tyackman** [comment]
[stand crash.log](https://github.com/YimMenu/YimMenu/files/14104081/stand.crash.log)
sync and script event logs

**Comment by tyackman** [comment]
Isolated clone syncs from the "Burger king foot lettuce" crash. I havent had time to check if its just the model, I will later. There was no stack trace.
[cout.log](https://github.com/YimMenu/YimMenu/files/14172713/cout.log)

> patch it through `WEAPON_DAMAGE_EVENT` caused by invalid weapon type(hash) like `RAGE_JOAAT("weapon_explosion")`(this is valid)

I dont think it was that

**Comment by ghost** [comment]
Hello. I am making my own mod menu for GTAV with rust, I have the patches for both of these and im sharing them with you guys.

Burger king foot lettuce just spawns this model: 
![image](https://github.com/YimMenu/YimMenu/assets/86185324/9ac1d2b1-323d-450b-a287-5ef0f666c67d)

Elegant crash is a script event. (Script: -3971681992, args: -2)

The source code for the elegant crash block is:

```
if (args[0] == -3971681992)
{
	LOG(INFO) << "Blocked a (elegant) crash from: " << plyr->get_name();
	notify::crash_blocked(plyr->get_net_game_player(), "elegant crash");
	session::add_infraction(plyr, Infraction::TRIED_CRASH_PLAYER);
	return true;
}
```

Place this above of the line where the `return false` is in **src/hooks/protections/script_event_handler.cpp**

For the burger king one:

Add `1149510719` hash to the **crash_objects** table in src/util/protection.cpp

If you would like more crash models, I have a huge list of them (Might be duplicates.) but i can send that too if you want.

Happy coding

**Comment by GreySideMM** [comment]
Is there any update/background activity on this yet? I added it to my code but no one tried to crash me with it yet. At least not with the elegant crash, I had no output for the object crash added yet. (I got crashed twice yesterday regardless.) @xiaoxiao921 I would like to add the rest of your list, too. I could also test then how it goes, esp. since I encounter enough modders who want to crash me. ..
Anything in special I should test? Otherwise I could create a PR for the current two methods.

**Comment by ghost** [comment]
> Is there any update/background activity on this yet? I added it to my code but no one tried to crash me with it yet. At least not with the elegant crash, I had no output for the object crash added yet. (I got crashed twice yesterday regardless.) @xiaoxiao921 I would like to add the rest of your list, too. I could also test then how it goes, esp. since I encounter enough modders who want to crash me. .. Anything in special I should test? Otherwise I could create a PR for the current two methods.

I think you pinged the wrong person maybe lol

I can try and write some code to nlock it if you wish give me a bit. My list may have a bunch of duplicate ones already added in yimmenu but i can send that along too.

If you need help testing elegant crash and burger king I can help as I just bought stand a few days ago to test some kick protections (love letter)

Cheers xynny

**Comment by GreySideMM** [comment]
I pinged you for the list. I can add that object list as well, so you don't need to do that. (I will also check for duplicates.) I might not have enough knowledge for more complicated things like the elegant crash, tho. I can only do the simple stuff somewhat properly.
If the protections for elegant and burger king work for you I assume they work with Yim as well. But we sure can try testing stuff then.

**Comment by ghost** [comment]
Sure, I am trying to find how to do burger king right now, Done elegant protection.

**Comment by GreySideMM** [comment]
@xynnylol You do mean your own menu now, or YimMenu? (Maybe I understood you wrong.) I would assume that there is only one point where we need to check for invalid models, the one you mentioned above: crash_objects table in src/util/protection.cpp (I understood it as that you have similar protection already in your menu, too.)

**Comment by ghost** [comment]
> @xynnylol You do mean your own menu now, or YimMenu? (Maybe I understood you wrong.) I would assume that there is only one point where we need to check for invalid models, the one you mentioned above: crash_objects table in src/util/protection.cpp (I understood it as that you have similar protection already in your menu, too.)

Hello, Yes that seems to be where it does crash protection from my search, can_apply_data.cpp (Which from the looks of it handles crash protection on incoming objects peds cars and trains etc...) Calls a is_crash_object function which lead me to src/util/protection.cpp and that table. My menu does something different and i am trying to make my code fit in with the yimmenu code lol

**Comment by ghost** [comment]
I have removed any duplicates from my list and removed the duplicate RAGE_JOAAT("proc_dryplantsgrass_02") present in the original yim menu table. I will compile it now and test it against stand for you and send you the new code.

**Comment by ghost** [comment]
Alright patched elegant and burger king crash code is [here](https://github.com/xynnylol/YimMenu-test/commit/977059b242e3bc56a410277c6609e4755bdb6a16) Edit: Seems Stand have improved the Elegant crash since i patched it. There are a lot more script events being fired from the crashing user.

**Comment by tyackman** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/14324091/cout.log)
New stack trace from updated elegant crash, blocking all script events doesnt seem to mitigate it. I heard they've included the workings of cherax's new crash.

**Comment by ghost** [comment]
> [cout.log](https://github.com/YimMenu/YimMenu/files/14324091/cout.log) New stack trace from updated elegant crash, blocking all script events doesnt seem to mitigate it. I heard they've included the workings of cherax's new crash.

Yes I know, I found the script events BUT seeing it does something called a Suicide ped crash which from what I can tell kills the freemode script. Yim Menu would need an automatic freemode restarter probably. I am trying to debug this more but i don't exactly have a lot of free time at the moment.

**Comment by ghost** [comment]
During my testing the game never crashed only the Yim log file was filling up (Over a gigabyte in 20s) with the same exception which caused it to lag a LOT which is not normal for a 4090

**Comment by lonelybud** [comment]
you know your code i patched in my fork and today i got crashed even 2take1 crashed alongside me. 2take1 was host then after he left i became the host. Someone crashed both of us one by one. If your code is working then the culprit should not be stand but yeah there is a new types of crashs definetely yimmenu needs protection against. No logs were generated.

**Comment by ghost** [comment]
2take1 can be crashed by the steamroller crash in stand.

**Comment by ghost** [comment]
I have a bit of an idea where the elegant crash was updated. And i will start my debugging soon. If anyone wants to help with logs or anything feel free. I also have stand to test these crashes. The protection for elegant crash was working at least a whole month ago and is still somewhat valid as when I send the exact same script event to my stand test account it triggers the notification of a crash. Hopefully in the process i can fix some stuff that bypasses the godmode in YimMenu (Force camera forward) and some annoying stuff like PTFX spam.

**Comment by GreySideMM** [comment]
@xynnylol I can not help with the logs, I don't have enough knowledge of deeper GTA stuff. (I would just cause more work due to questions, lol.) I also figured I should finish at least some of my stuff first, to get a free mind.
I assume that Stand has a large(r) backlog of crashs and will just publish them when needed. However: Tthe debugging stuff of YimMenu could probably help you with all of that. It has script logs. If they work here, I have never used them, tho. Just FYI: The dev of stand is or at least was active reading/writing here in the repo.
Is your mod going to be P2C, or what is the plan of that? That would prob interest some possible helpers (if there are any).

**Comment by ghost** [comment]
> @xynnylol I can not help with the logs, I don't have enough knowledge of deeper GTA stuff. (I would just cause more work due to questions, lol.) I also figured I should finish at least some of my stuff first, to get a free mind. I assume that Stand has a large(r) backlog of crashs and will just publish them when needed. However: Tthe debugging stuff of YimMenu could probably help you with all of that. It has script logs. If they work here, I have never used them, tho. Just FYI: The dev of stand is or at least was active reading/writing here in the repo. Is your mod going to be P2C, or what is the plan of that? That would prob interest some possible helpers (if there are any).

Sounds good, I find it funny that the stand developer was in the repository lol (By the looks of it just to start chaos with a french guy and contributors of this project), I think by the looks of the latest commits the elegant crash might be patched already. Haven't got around to testing it yet (quite busy on another project). Update: No I plan on making my menu free. Thanks

**Comment by tyackman** [comment]
> I think by the looks of the latest commits the elegant crash might be patched already.

Unfortunately not. There was no stack trace following this time, as I was told. Sorry I can't provide more information atm.

**Comment by malloc2k** [comment]
@xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)

**Comment by ghost** [comment]
> @xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)

I am yes. But i don't give my discord out to random people. Secondly my menu is written in the rust programming language which as far as i know no other gta mod menu is at the time of writing.

**Comment by malloc2k** [comment]
> > @xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)
> 
> I am yes. But i don't give my discord out to random people. Secondly my menu is written in the rust programming language which as far as i know no other gta mod menu is at the time of writing.

Damn i was hoping maybe to help you out on the menu, but it's alright :/

**Comment by ghost** [comment]
> > > @xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)
> > 
> > 
> > I am yes. But i don't give my discord out to random people. Secondly my menu is written in the rust programming language which as far as i know no other gta mod menu is at the time of writing.
> 
> Damn i was hoping maybe to help you out on the menu, but it's alright :/

Sorry unless you are good in programming rust i don't see how you could be of help? But anyways

**Comment by malloc2k** [comment]
> > > > @xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)
> > > 
> > > 
> > > I am yes. But i don't give my discord out to random people. Secondly my menu is written in the rust programming language which as far as i know no other gta mod menu is at the time of writing.
> > 
> > 
> > Damn i was hoping maybe to help you out on the menu, but it's alright :/
> 
> Sorry unless you are good in programming rust i don't see how you could be of help? But anyways

Not rust, but similar ( CPP, C# etc)

**Comment by ghost** [comment]
> > > > > @xynnylol sorry to ping you back here, I read above that you were developing your own menu, I would like to get your Discord, because I would like to see how you are doing it ;). Just tryna gain some more knowledge to someday make mine :)
> > > > 
> > > > 
> > > > I am yes. But i don't give my discord out to random people. Secondly my menu is written in the rust programming language which as far as i know no other gta mod menu is at the time of writing.
> > > 
> > > 
> > > Damn i was hoping maybe to help you out on the menu, but it's alright :/
> > 
> > 
> > Sorry unless you are good in programming rust i don't see how you could be of help? But anyways
> 
> Not rust, but similar ( CPP, C# etc)

Ok. Anyways lets try and keep this issue on topic.

Update:

I can't reproduce the crash as often with the latest YimMenu and my patches applied. Will need to dig deeper into the source code and/or reverse stand.

**Comment by tyackman** [comment]
[cout (15).log](https://github.com/YimMenu/YimMenu/files/14484484/cout.15.log)
Not sure which menu this originated from. Seems to make use of what was recently patched though, and then some. She's a big gorl.

**Comment by ghost** [comment]
> [cout (15).log](https://github.com/YimMenu/YimMenu/files/14484484/cout.15.log) Not sure which menu this originated from. Seems to make use of what was recently patched though, and then some. She's a big gorl.

Perfect log i will find some time to patch it and port the patches to yim menu

Also stand has some lua scripts that can crash yim menu and detect it.. might have a look into those later But thanks for the log

**Comment by GreySideMM** [comment]
Both patches never got triggered for me since then. But I had been crashed, but not so often. Idk which menus it where. (Not 2t1, apparently.)
These Lua scripts are interesting, I only found one by accident. But it's YimMenu detection must be out of date and not working, I checked. Are you by any chance on the Matrix channel? (See https://github.com/YimMenu/YimMenu/discussions/2533) I would like to see these scripts. But we don't need to spam this issue here with that.

**Comment by ghost** [comment]
> Both patches never got triggered for me since then. But I had been crashed, but not so often. Idk which menus it where. (Not 2t1, apparently.) These Lua scripts are interesting, I only found one by accident. But it's YimMenu detection must be out of date and not working, I checked. Are you by any chance on the Matrix channel? (See #2533) I would like to see these scripts. But we don't need to spam this issue here with that.

The lua script abuses the fact that yimmenu and the skidded versions as they call them use a fixed host token which they detect. I will probably join the matrix later. Nearly 1am for me lol Xforce and north can still crash yimmenu afaik as i tested with north before they hwid blacklisted me.

**Comment by xiaoxiao921** [comment]
The host token is randomly generated, or atleast should be, are you sure they still detect through that?

**Comment by ghost** [comment]
> The host token is randomly generated, or atleast should be, are you sure they still detect through that?

tested it seems to be detected still Update: Seems i got unlucky and had the detected token, Can't reproduce it anymore today

**Comment by ghost** [comment]
@tyackman I think this issue can be closed, I have tested the latest YimMenu against stand ultimate the only thing stand can do is Spam PTFX which can lag you down to 20fps on a 4090 or cage you (Have a WIP commit for that)

**Comment by themonsterdev** [comment]
> Sure, I am trying to find how to do burger king right now, Done elegant protection.

I recreated the burger king crash and elegant, the burger king is just a hash change on a spawn object, which causes an invalid object hash crash.

**Comment by xiaoxiao921** [comment]
Pretty sure it's fixed, reopen / tell if needed
