### ISSUE TITLE
[Improvement]: improve kick option without a Host

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#2673]
### Which feature

 when I'm not a host most kick not work with  ( other modder - they have strong menu ) and also not work with most spammer
host kick and breakup kick this just work when I'm a host

### Reason

is it possible to improve  or add new kick work when I'm not a host 

### Additional context

.

**Comment by lonelybud** [comment]
use desync kick

**Comment by D-Borkan** [comment]
> use desync kick

kick me instead of kick him ( backfire )

**Comment by lonelybud** [comment]
i have not tried on strong menus but in most of the cases if you desync the target and they dont attack back then it works.

**Comment by tyackman** [comment]
The desync kick and protections are quite far behind some p2cs. It is nearly useless currently. Force host, use breakup kick, and pray.

**Comment by D-Borkan** [comment]
yes for now the solution is get a host

**Comment by lonelybud** [comment]
there are some modders who you if try to desync kick you will get desynced instead, first i thought that i had strict NAT type thats why it happened but it happened even with moderate NAT type. May be the players host token plays a role in it? dont know

**Comment by D-Borkan** [comment]
> there are some modders who you if try to desync kick you will get desynced instead, first i thought that i had strict NAT type thats why it happened but it happened even with moderate NAT type. May be the players host token plays a role in it? dont know

i don't think the cause from NAT type bc i always get kick when use desynced kick

**Comment by snowleopardd** [comment]
it's simple, if they aren't hosting just desync kick them, it even works with paid menus.
If theyre host, you don't kick them, just kick everybody else and leave the lobby.

**Comment by GreySideMM** [comment]
> it's simple, if they aren't hosting just desync kick them, it even works with paid menus. If theyre host, you don't kick them, just kick everybody else and leave the lobby.

How sure are you about this? I had that an attempted desync kick backfired for me when used against a certain modder. I tried it serveral times (I rejoined every time). I also encountered another modder (with a custom mod, I guess) where desync kick had no effect. (Or do I need to spam that?) That modder also had - I assume - a new kicking method.

**Comment by snowleopardd** [comment]
> > it's simple, if they aren't hosting just desync kick them, it even works with paid menus. If theyre host, you don't kick them, just kick everybody else and leave the lobby.
> 
> How sure are you about this? I had that an attempted desync kick backfired for me when used against a certain modder. I tried it serveral times (I rejoined every time). I also encountered another modder (with a custom mod, I guess) where desync kick had no effect. (Or do I need to spam that?) That modder also had - I assume - a new kicking method.

Yeah theres a new option in some paid menus called "Desync Karma", that will desync both of you, but he will still be kicked.
Then, if you wanna "take control" of the session, you have to join back ASAP with session id and lock the lobby or block him joining using the database.

and thats how u win against a paid user :)

**Comment by GreySideMM** [comment]
> Yeah theres a new option in some paid menus called "Desync Karma", that will desync both of you, but he will still be kicked. Then, if you wanna "take control" of the session, you have to join back ASAP with session id and lock the lobby or block him joining using the database.
> 
> and thats how u win against a paid user :)

That implies that is indeed possible to detect who initiated the desync? I think @maybegreat48 said that (might have been an older post, tho). I was wondering about that anyway (but have never looked into this).
If I can I'll try the desync with some guys I know (with paid menus). And also that one (apparently) not desync-able "Guard Bot" user who was sus.
