### ISSUE TITLE
[Bug]: gtav crashes when dll is injected 

### ISSUE THREAD

**Issue by coprofago** [Yimura/YimMenu#2676]
### Describe the bug

using xenos to inject the dll, the game crashes right after the injection.

### Steps To Reproduce

1. open gtav
2. open xenos with the yimmenu.dll loaded
3. select gtav.exe to inject 
4. click the button "inject" in xenos window
5. game crash

### Expected Behavior

game to run normally with dll injected and be able to use yimmenu in the game.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14113215/cout.log)

### Store

Epic Games

### Language

Brazilian Portuguese

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
It is crashing somewhere with ImGui trying to load fonts. Are you on a Chinese build of Windows or something?

**Comment by coprofago** [comment]
> It is crashing somewhere with ImGui trying to load fonts. Are you on a Chinese build of Windows or something?

I am in a brazilian portuguese build of windows

**Comment by Yimura** [comment]
We can add some additional safety checks I guess to just stop trying to load a part of the font map if we can’t find the font at all.

**Comment by gir489returns** [comment]
> We can add some additional safety checks I guess to just stop trying to load a part of the font map if we can’t find the font at all.

On BBv2 to solve this, Poccaking just [bytecode included the font](https://bitbucket.org/gir489/bigbasev2/src/4dd1da37d335daa235d35f40a9e478e34fa6f276/BigBaseV2/src/fonts.cpp#lines-4). 

Is there any reason we can't do this? (Copyright/collisions/regional differences/etc)?

**Comment by Yimura** [comment]
> On BBv2 to solve this, Poccaking just [bytecode included the font](https://bitbucket.org/gir489/bigbasev2/src/4dd1da37d335daa235d35f40a9e478e34fa6f276/BigBaseV2/src/fonts.cpp#lines-4).
> 
> Is there any reason we can't do this? (Copyright/collisions/regional differences/etc)?

Reduce the bloat of the DLL, however I think we've since passed the threshold of keeping the DLL size reasonable lol (+5MB).
I also think adding the font like that fugly so I want to prevent doing that until they add `#embed` support to C++ (or C).

**Comment by gir489returns** [comment]
```
file font_file_path = windows_fonts.get_file("./msyh.ttc");
if (!font_file_path.exists())
	font_file_path = windows_fonts.get_file("./msyh.ttf");
auto font_file            = std::ifstream(font_file_path.get_path(), std::ios::binary | std::ios::ate);
```

Currently we are error-correcting for msyh.ttc not existing, then trying msyh.ttf, however, there is not scenario for when both do not exist. That being said, what font would we even look for? We'd have to scrounge every instance of Windows to know which font is always on there, versus which is omitted for regional (copyright) reasons.

**Comment by gir489returns** [comment]
@coprofago Can you try #2696 and see if it says "Failed to retrieve msyh font." in your log? The builder bot will emplace a DLL in the comments for the ticket for you to use.

**Comment by coprofago** [comment]
> @coprofago Can you try #2696 and see if it says "Failed to retrieve msyh font." in your log? The builder bot will emplace a DLL in the comments for the ticket for you to use.

ok, i will try when i get home, TY

**Comment by coprofago** [comment]
> @coprofago Can you try #2696 and see if it says "Failed to retrieve msyh font." in your log? The builder bot will emplace a DLL in the comments for the ticket for you to use.

I tested this other dll and the same think happens, crash at the moment i inject =(

my cout.log:

[cout.log](https://github.com/YimMenu/YimMenu/files/14227642/cout.log)

**Comment by gir489returns** [comment]
@Yimura Line 486 of his log, you can see the entry:

`[16]	ntdll.dll RtlUserThreadStartFailed to retrieve msyh font.`

His computer does not have the font. How should we gracefully handle this scenario?

**Comment by gir489returns** [comment]
@coprofago Can you show us a screenshot of what you do have in C:\Windows\Fonts? Or, if you know how, use the command prompt and do a dir /all on the folder and paste the output.

**Comment by Yimura** [comment]
> @Yimura Line 486 of his log, you can see the entry:
> 
> `[16] ntdll.dll RtlUserThreadStartFailed to retrieve msyh font.`
> 
> His computer does not have the font. How should we gracefully handle this scenario?

Yeah I’ve already thought of something.

**Comment by coprofago** [comment]
> @coprofago Can you show us a screenshot of what you do have in C:\Windows\Fonts? Or, if you know how, use the command prompt and do a dir /all on the folder and paste the output.

here is the list of my C:\Windows\Fonts

[fonts.txt](https://github.com/YimMenu/YimMenu/files/14229212/fonts.txt)

**Comment by coprofago** [comment]
well, i did a test here, i installed this font msyh.ttc for all users, so the file goes to c:\windows\fonts folder, and it worked, gtav didnt crash and i can use yimmenu within the game normally =)
