### ISSUE TITLE
[Improvement]: Remove SET_ENTITY_AS_NO_LONGER_NEEDED

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2680]
### Which feature

Vehicle Spawning

Can we make SET_ENTITY_AS_NO_LONGER_NEEDED() a toggleable option in settings somewhere?

Using my addon, vehicle gifting works, but only when this is removed from YimMenu itself.  If its not removed or toggled off, it kicks the user from the vehicle every time you hit gift.

https://imgur.com/a/4dMx3mc

NOTE:  I had mentions of this causing aimbot to not work properly?  I dont use Yim's aimbot feature but if this is the case, making it toggleable will be the best option here.

**Comment by maybegreat48** [comment]
Compile YimMenu in Release mode

**Comment by Deadlineem** [comment]
> Compile YimMenu in Release mode

I have never used visual studio before.  Can you lmk how i do that?

**Comment by Deadlineem** [comment]
@Yimura @gir489returns

**Comment by gir489returns** [comment]
This is irrelevant as you can reimplement Spawn Vehicle on your own, there is no need to call it yourself.

**Comment by Yimura** [comment]
When writing this feature in Lua you can indeed spawn a vehicle completely yourself and do with it whatever you want.

The menu has vehicle spawning setup like this because we prefer automatic cleanup of vehicles rather than have thousands of random vehicles scattered around map that cannot be cleaned up (automatically).

**Comment by Deadlineem** [comment]
> This is irrelevant as you can reimplement Spawn Vehicle on your own, there is no need to call it yourself.
> 
> https://github.com/YimMenu-Lua/DailyCollectibles/blob/main/util.lua#L39
> 
> I even made one in Lua. (It was PR'd by Shiny)

True, but i didnt want to have to add in a second vehicle spawner just for vehicle gifting, I really rather like the way Yim's Spawner/LS customs is set up so i felt there wasn't a need to code an entirely new spawner, although I do have a complete list of vehicles inside my script already, so I could do this alternatively..  I figured if this were toggleable (defaulted to on) it would make things a whole lot simpler for everybody without reimplementation of a feature thats already there, though.

I do understand @Yimura that I can write this myself, though and also use the provided util.lua as well.

**Comment by Deadlineem** [comment]
@gir489returns @Yimura 

I have done the lua script for vehicle gifting and it works, HOWEVER.  As soon as i modify the car using LS Customs on Yim, it sets it as no longer needed yet again and kicks them out of the car.  

Can we please make this togglable....  I really dont think all of this extra creation is necessary at this point, now i would need to recreate the entire LS customs portion in lua so it does not cause this issue :(

**Comment by gir489returns** [comment]
@Deadlineem Its not Yim doing that it’s the script like I told you on UC.

**Comment by Deadlineem** [comment]
> @Deadlineem Its not Yim doing that it’s the script like I told you on UC.

No sir, it is not.  I made a LUA script spawner as you suggested

https://www.unknowncheats.me/forum/grand-theft-auto-v/622944-advanced-vehicle-spawner-yimmenu.html

It works like that, but if i get in the spawned car and use LS Customs to mod it for the player, have them get in and hit gift, it kicks them like it was before.

It does not do this when i use the custom DLL, or when i spawn a car and gift it to them with the LUA script above, its only doing it when i mod the car for them now.

I did take your advice and im coming back to prove that this is something that could be easily fixed with a simple toggle of SET_ENTITY_AS_NO_LONGER_NEEDED() in view_spawned_vehicle.cpp and spawn_vehicle.cpp

Settings > Vehicle Spawn Settings > Set as No longer needed (Active by default) - uncheck to turn off when you want to spawn, gift or customize a car for someone.

Otherwise, i would have to write the LS customs portion in LUA as well, alot of unnecessary work imo.

**Comment by Deadlineem** [comment]
@gir489returns 
Confirmed using the lua script lets you gift spawned cars from it, but does not let you modify the cars using LS Customs in the menu.  I did think of something though...

https://www.unknowncheats.me/forum/3989145-post3.html

If that works the same or similar in C++, the delete function could possibly be used instead of SET_ENTITY_, no?

**Comment by gir489returns** [comment]
@Deadlineem I have no idea what you're talking about.

**Comment by Yimura** [comment]
LS Customs just mods the vehicle, it shouldn’t be spawning a new vehicle.

As you can see there's no references to the internal spawn function used by the menu nor the SET_ENTITY_AS_NO_LONGER_NEEDED in the LS Customs code.

https://github.com/YimMenu/YimMenu/blob/master/src/views/vehicle/view_lsc.cpp

Or are you triggering the LS Customs with the in-game UI perhaps? I doubt it as that one is broken.

**Comment by Deadlineem** [comment]
> LS Customs just mods the vehicle, it shouldn’t be spawning a new vehicle.

Im aware, but for some reason, using the lua script above, i can spawn the car and gift it to them as long as i dont get in it and use LS customs, maybe its because i am sitting in the car?  Maybe its from LS customs modifying the car and then setting the entity as no longer needed?  

I do know that without SET_ENTITY_ in those two lines of the code, it works without issue i can spawn and modify them completely and then gift them through the addon im working on, no need to build a whole new spawner in lua, either, just the gift option.

**Comment by Deadlineem** [comment]
> LS Customs just mods the vehicle, it shouldn’t be spawning a new vehicle.
> 
> As you can see there's no references to the internal spawn function used by the menu nor the SET_ENTITY_AS_NO_LONGER_NEEDED in the LS Customs code.
> 
> https://github.com/YimMenu/YimMenu/blob/master/src/views/vehicle/view_lsc.cpp
> 
> Or are you triggering the LS Customs with the in-game UI perhaps? I doubt it as that one is broken.

Im aware, but for some reason, using the lua script above, i can spawn the car and gift it to them as long as i dont get in it and use LS customs (the menu one, not the in game broken ui one), maybe its because i am sitting in the car? Maybe its from LS customs modifying the car and then setting the entity as no longer needed?

I do know that without SET_ENTITY_ in those two lines of the code, it works without issue i can spawn and modify them completely and then gift them through the addon im working on, no need to build a whole new spawner in lua, either, just the gift option.

But i figured if the gift option had a sleep timer and deleted the vehicles after a set time, maybe it would work as an alternative if SET_ENTITY_ cannot be toggled?

Im new to this though so thats why im bringing this up to you guys, trust me, i know nothing of C++ except for what im trying to find in there to make things in lua, and i have 0 plans to continue re-releasing a dll without that SET_ENTITY_ line removed every time you guys update, hence why a toggleable option would thus solve both problems, turn it off when you want to gift cars to people, turn it back on when youre done and in between that while its off, use the delete gun and delete the invisible junk after they take the car in their garage, it works :D

`#include <iostream>

class Entity {
public:
    void setEntityAsNoLongerNeeded() {
        std::cout << "Entity is set as no longer needed!" << std::endl;
        // Additional actions related to setting entity as no longer needed can be added here
    }

    void performAction() {
        std::cout << "Action performed!" << std::endl;
        // Additional actions to be performed can be added here
    }
};

int main() {
    Entity entity;

    // Perform action (since the entity is needed)
    entity.performAction();

    // Set the entity as no longer needed
    entity.setEntityAsNoLongerNeeded();

    // Attempt to perform action (but it should do nothing since the entity is not needed)
    entity.performAction();

    return 0;
}
`

Something like this in C++ idk exactly.

**Comment by GreySideMM** [comment]
Your description are not clear:
Which LS Costums are you using? The real ingame entity or the menu "LS Customs" titled one?
What is the order you did things? And was the order same for both variants (spawned thru menu or thru LUA)? Spawned, modded, gifted? Or spawned, gifted, modded?
Latter could be a problem but shouldn't be related to YimMenu.

**Comment by snowleopardd** [comment]
Just add an option disabled by default to make the cars "persistent and giftable", whats the point of not implementing it native if you can literally do it with a lua script

**Comment by Deadlineem** [comment]
> Your description are not clear: Which LS Costums are you using? The real ingame entity or the menu "LS Customs" titled one? What is the order you did things? And was the order same for both variants (spawned thru menu or thru LUA)? Spawned, modded, gifted? Or spawned, gifted, modded? Latter could be a problem but shouldn't be related to YimMenu.

I just use my lua script for gifting.  It works, most of the time anyways.  Currently trying to figure out how to use the model previewer for it because im being asked about it by others who use my addon, the yim spawner is perfect it just messes the gifting up when you spawn with yims spawner.

**Comment by GreySideMM** [comment]
> I just use my lua script for gifting. It works, most of the time anyways. Currently trying to figure out how to use the model previewer for it because im being asked about it by others who use my addon, the yim spawner is perfect it just messes the gifting up when you spawn with yims spawner.

Yes. But that wasn't what I asked.
I'm using your script by myself (thanks to you & others at this point). I run my own version of YM with a despawn checkbox. Besides the need to smash that button it works fine. Also: I can understand your need but it's Yimuras decision - which I also can fully understand.
PS: Maybe you can clean up your script a bit and add it to the YimMenu-Lua repo here on GH. Idk who it manages, tho.
