### ISSUE TITLE
[Bug]: Gta Crashing when spawning xml vehicles

### ISSUE THREAD

**Issue by Maxi23-1** [Yimura/YimMenu#2682]
### Describe the bug

I tried downloading xml vehicles meant for menyoo and I tried spawning them on YimMenu, when I spawn any of the xml vehicles my game instantly crashes, playing gta online and story mode

### Steps To Reproduce

Spawn a xml vehicle

### Expected Behavior

getting the xml vehicle spawned

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

no

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by V1RU513N** [comment]
Yes, #2669 broke xml vehicles & xml maps

**Comment by 99Anvar99** [comment]
Interesting... I mean its true, requesting models that are not in CDImage or valid will return false. I will add a check for xml vehicles and maps.

**Comment by gir489returns** [comment]
> Interesting... I mean its true, requesting models that are not in CDImage or valid will return false. I will add a check for xml vehicles and maps.

Is that the proper solution? Sounds like it should be the other way around. XML vehicles/maps should only request models that are valid...

**Comment by 99Anvar99** [comment]
> > Interesting... I mean its true, requesting models that are not in CDImage or valid will return false. I will add a check for xml vehicles and maps.
> 
> Is that the proper solution? Sounds like it should be the other way around. XML vehicles/maps should only request models that are valid...


Right, i am gonna quickly test what really happens, and fix the error based on results. and yes Gir i guess that might be the correct solution.

**Comment by gir489returns** [comment]
@99Anvar99 If you have questions about the XML implementations, please contact @DayibBaba as he was the one who wrote the majority of the code.

**Comment by 99Anvar99** [comment]
@Maxi23-1 Please provide the xml file that you have used in order to re-produce the crash

Contact Me: 
- Matrix: Mister 998
- Github: https://github.com/99Anvar99

**Comment by 99Anvar99** [comment]
I have found what exactly causes game to crash.

- World Spawn Bypass (byte_pach)

it has been incorrectly set.

**Comment by gir489returns** [comment]
@99Anvar99 Is that similar to the original vehicle model spawn bypass? https://bitbucket.org/gir489/bigbasev2/src/4dd1da37d335daa235d35f40a9e478e34fa6f276/BigBaseV2/src/pointers.cpp#lines-100

I seriously doubt that signature still works.

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/commit/ad1dfc71d2d5b2a9fb16f1c2009e4bc60bd65231#diff-bc0e89b70bc06d7ae31244db426b4fae320982f07067c0f639ef290d6da43b4eL8

this is because Anvar changed the code, which afaik was working perfectly fine before that

**Comment by gir489returns** [comment]
> this is because Anvar changed the code, which afaik was working perfectly fine before that

Makes sense.

**Comment by 99Anvar99** [comment]
Well, when i was doing the helper function for request model 
Yimura saw and asked me to make the world spawn bypass trough byte_patch.

I tried making it but didn't test the result of that.

**Comment by Pablo-Martinetz** [comment]
same happens to me

**Comment by Yimura** [comment]
> same happens to me

1. Crash log
2. are you using the latest version of YimMenu
