### ISSUE TITLE
Add "Fix NPC Traffic" Button

### ISSUE THREAD

**Issue by TwystedMind** [Yimura/YimMenu#2684]
### Problem

Assuming that someone knows what precisely causes NPC Traffic to randomly despawn sometimes (aside from players with menus who are intentionally disabling traffic), it would be extremely awesome if there were a button that "fixes" NPC Traffic allowing it to begin respawning like normal again.

### Solution

The idea would be to have a button that executes a list of necessary tasks and/or executes the necessary script thread(s) that causes NPC Traffic to spawn in the session as it would naturally.  I know a lot of players like to disable traffic through the menu for whatever reason they have.  However, there are many sessions that NPC Traffic is disabled in, yet no one has forcefully disabled the traffic and caused it.  There appears to be various scenarios or events that can cause traffic to "break" without any way to re-enable it within that session afterwards.

**If you wish to read the three potential situations I have currently landed on that may be causing broken traffic in some lobbies based off of my observations, research and testing - that information is below:**

1. **SESSION HOST SPOOFING** - If I am the active Session Host of a session that has **normal and functioning NPC Traffic**, but another player attempts to join with "Aggressive Host Token Spoofing" enabled, the player will attempt to kick me so they can become Session Host, however, my kick reactions will end up kicking said player instead - in cases like this, traffic does **not** seem to be affected.  However, if that player joins with Host Spoofing enabled (but does not make a kick attempt on me), they are able to successfully join the session.  In cases where this happens (multiple players who have Host Spoofing enabled are in the same session), I suspect that during the attempt to take Session Host, some sort of event or script thread(s) might be getting "hung up" because the anticipated player does not end up becoming Session Host, therefore leaving "Paused" or "Killed" threads in limbo and no longer running as they should be.  I do want to clarify that traffic does not break in these situations **every** time, however, I seem to notice traffic despawn very frequently when this happens and never actually re-spawn.  If the player who was attempting to spoof their Host Token leaves the session, traffic seems to begin to re-spawn (the same happens if I leave the session and that player is able to successfully take-over Session Host).

2. **SCRIPT HOST SWITCHING** - If I join into a session with "Aggressive Host Spoofing" enabled and am successfully able to take-over as Session Host, I then check to confirm that NPC Traffic is working properly.  Once I verify traffic is spawning as it should be and begin playing, there are many times where after so long, I will notice NPC Traffic beginning to "thin" out until there are no more NPC vehicles on the road.  I verify that there are no other players in the session who are flagged with "Spoofed Host Token".  Once I have confirmed there are no players with spoofed data, I had came up with the idea of trying to give Script Host to different players in the session to see what happens.  I specifically avoid giving Script Host to players who are flagged as modders (just so there are no competing events/tasks from the modder's menu interfering).  I had tested this in 3 different sessions last night, and had consistent results.  There would be no NPC Traffic in the session, I would give Script Host to a different player, and would gradually begin to see more and more NPC cars start to appear as I drive around in my car.  Since Rockstar dynamically assigns the Script Host position as different scripted events spawn, there were multiple times when traffic would begin working fine, but would then despawn again.  I would then give Script Host to a different non-modding player, and begin to see traffic spawn in again as it should.  This particular testing has lead me to believe that the Script Host is responsible for NPC Traffic script threads/events that occur in the game - but of course, cannot definitively confirm this.

3. **POOR SERVER/HOST CONNECTION** - The only "answer" I was ever able to come across throughout my numerous searches trying to figure out why some lobbies don't have traffic, but others do (and are not being modded).  Apparently having a poor network connection to the Session (or maybe Script) Host can cause NPC Traffic to heavily decrease in density, start delay spawning, or just stop spawning altogether.  From my understanding, having a high-latency (poor) network connection to the Session/Script Host, or the Session/Script Host having a high-latency (poor) network connection to Rockstar's servers, can result in NPC Traffic being disabled (I assume because it would cause all sorts of sync issues for players who are near each other).  In these cases, I generally just end up switching sessions (but will try to give Script Host to different players and see if that helps next time).

_Thank you so much for continuing to improve/fix YimMenu!  I apologize about the length of this section - again, just picturing a clickable button that is able to locate and execute the necessary script threads (or however traffic is managed), therefore "forcing" the handler for NPC Traffic to be started and fixed during situations where the traffic just randomly despawns._

### Reason

Having the ability to essentially "force fix" despawning NPC Traffic at the click of a button would be extremely useful in my opinion.  There are some days where 70%+ of the GTA Online Public Sessions that I join have absolutely no traffic.  Sure, there are a lot of times when a menu user will intentionally disable traffic so they can drive around, race, etc. without the obstacles.  However, for the sessions that have "broken" traffic, it would be very convenient and helpful to the rest of the players in the session, if the traffic could be respawned in how it is supposed to.

There are times where leaving the lobby is not a viable option (working on active missions, playing with a large group of people, PVPing with other players, etc.), and having a simple and realistic way to trigger a "fix" would be very effective!  Worse case scenario, changing to a new lobby should resolve the issue.  However, there are times where the Matchmaking is on vacation and just continues to place you in the same exact session over and over again.  There are also times where you may session-hop 4-5 times **in a row**, and all 5 sessions have no NPC Traffic either.  In those cases, I usually end up re-launching the game and hoping I don't get put back into one of those same "broken" sessions.

### Additional context

If this feature does not seem like one that will make it into YimMenu - assuming you know what is actually responsible for the spawning of NPC Traffic - could you possibly provide me with the Script Thread(s) that I should be looking at?  Or guide me to the line(s) of code that triggers NPC Traffic to spawn?  I have had absolutely **no** luck finding any information on what controls traffic in GTA Online.

I am wondering if the responsible Script Thread exists in the "Debug" section of the menu under "Threads" that I could possibly execute to respawn traffic.  I have tested some different script and threads to see what happens, but have never had any luck in the end.

_NOTE:  I will attempt to reproduce the 3 different scenarios I listed above tonight or tomorrow so that I can provide some cout.log files showing everything that's going on in these sessions with broken NPC Traffic_

**Thank you so much for taking the time to read this and assist if possible - even if that's just helping me figure out what is actually executed in order to spawn in NPC Traffic, or if maybe there is a thread that needs to be randomly "Killed" to fix the issue (hey, I can hope right?) ... If there is ANYTHING that I can provide, add or test, please let me know and I will do it!**

**Comment by pierrelasse** [comment]
Average twitter apology

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/168b1ea7-7454-4fa5-96ca-3fe3a0456df7)

**Comment by TwystedMind** [comment]
To be fair, a lot of what I said was irrelevant if you happen to understand what causes traffic to break and/or know how to fix it 😂

But yes, as usual, I have written a novel for what is probably extremely simple ... I'll update this and remove all of my in-game observations.  That's like 75% of this submission anyway 🙃

My bad!

**Comment by Yimura** [comment]
Traffic has been randomly breaking for me for ages now, I remember seeing this behaviour 1+ year ago.

I don’t know what causes it but I’m really starting to doubt the menu is causing this and it’s just shitty R* code.

**Comment by pierrelasse** [comment]
> My bad!

shame on you

**Comment by GreySideMM** [comment]
I also encounter this regularly, even before using a menu. But then there always have been modders so who knows.
I also had the nice issue of traffic only being present on distance, as soon as you approach.. Well, at least that's really rare.
But anyways:
A way of being at least able to tell if a modder disabled the traffic would be nice. I became host and even then traffic was gone - until one specific modder left and within a second the traffic started to reappear.

**Comment by alyxme** [comment]
I'd start a new fresh session rather than fight with random cause of disabled scripts.

**Comment by maybegreat48** [comment]
> I suspect that during the attempt to take Session Host, some sort of event or script thread(s) might be getting "hung up" because the anticipated player does not end up becoming Session Host, therefore leaving "Paused" or "Killed" threads in limbo and no longer running as they should be

No, but the world grids *might* break during host transitions. I have however never seen that happen before. Session (and script) hosts also do not control whether script threads are paused or running

>  I would then give Script Host to a different non-modding player, and begin to see traffic spawn in again as it should. This particular testing has lead me to believe that the Script Host is responsible for NPC Traffic script threads/events that occur in the game

The script host cannot directly control traffic, but this finding is interesting nonetheless

> Apparently having a poor network connection to the Session (or maybe Script) Host can cause NPC Traffic to heavily decrease in density

Connection latency to the session/script host shouldn't affect vehicle spawns

**Comment by Yimura** [comment]
Fixed in #2688
