### ISSUE TITLE
[Bug]: Kick Everyone from Interiors

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2685]
### Describe the bug

Simply pressing the button crashes you.

### Steps To Reproduce

Network > Griefing > Kick Everyone From Interiors

### Expected Behavior

To kick everyone from their apartments?

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
You didn't include a crash log, therefore I can't figure out why you are crashing. I need your cout.log from when it crashed.

**Comment by loveshacks** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/14325423/cout.log)

I just did a new log for this problem, Deleted old, ran game, used the Kick from Interior (Network > Griefing).

Game immediately crashes and goes to desktop.

**Comment by malloc2k** [comment]
**Same problem here**
