### ISSUE TITLE
[Build]: How do I use the action feature?

### ISSUE THREAD

**Issue by a461581873** [Yimura/YimMenu#2686]
### Describe the build issues

I want to use personalized actions, such as sitting in a chair anytime, anywhere, but I don't know how to add this

### Screenshots and/or Logs

![IMG_20240208_194245](https://github.com/YimMenu/YimMenu/assets/150590245/0cf4d755-013e-421d-a901-632a372438bf)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by lonelybud** [comment]
[ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)

add this inside `X:\Users\a461581873\AppData\Roaming\YimMenu`

now in animation > Saved animations > Action > sit (michael)

**Comment by a461581873** [comment]
gtav gets stuck when I press to get the animation
![IMG_20240208_223430](https://github.com/YimMenu/YimMenu/assets/150590245/11684c44-3220-4e6c-bb4d-f9cdb8879cdd)

**Comment by a461581873** [comment]
> [ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)
> 
> 在里面添加这个`X:\Users\a461581873\AppData\Roaming\YimMenu`
> 
> 现在在动画中 > 保存的动画 > 动作 > 坐下 （michael）



> [ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)
> 
> 在里面添加这个`X:\Users\a461581873\AppData\Roaming\YimMenu`
> 
> 现在在动画中 > 保存的动画 > 动作 > 坐下 （michael）



> [ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)
> 
> 在里面添加这个`X:\Users\a461581873\AppData\Roaming\YimMenu`
> 
> 现在在动画中 > 保存的动画 > 动作 > 坐下 （michael）

gtav gets stuck when I press to get the animation
![IMG_20240208_223430](https://github.com/YimMenu/YimMenu/assets/150590245/a78bf902-b647-41b6-be44-51cf2ad4b6b1)

**Comment by a461581873** [comment]
> [ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)
> 
> 在里面添加这个`X:\Users\a461581873\AppData\Roaming\YimMenu`
> 
> 现在在动画中 > 保存的动画 > 动作 > 坐下 （michael）

gtav gets stuck when I press to get the animation
![IMG_20240208_223430](https://github.com/YimMenu/YimMenu/assets/150590245/93d41748-9af4-4d2f-8f6b-290abe09aa59)

**Comment by a461581873** [comment]
> [ped_animations.json](https://github.com/YimMenu/YimMenu/files/14209533/ped_animations.json)
> 
> 在里面添加这个`X:\Users\a461581873\AppData\Roaming\YimMenu`
> 
> 现在在动画中 > 保存的动画 > 动作 > 坐下 （michael）

I can already get the animation, but I don't know which one corresponds to the sitting action

**Comment by lonelybud** [comment]
in `Action` category, double click `Action: sitting (Michael)`

**Comment by Yimura** [comment]
This should've been a discussion not an issue (with YimMenu itself).
