### ISSUE TITLE
[Request]: Game options console features repair (read the details)

### ISSUE THREAD

**Issue by spankymonkey** [Yimura/YimMenu#2687]
### Problem

**Issue 1**: Mini map, menu, phone, map prompt, weapon, all disappear.
I try to moderate sessions by entering a new public session as host to kick cheaters. Often I am either detected as a modder or cheaters attempt to kick the host out of the session with all sorts of malicious attempts. Most malicious acts are harmless as annoying as they may be I end up kicking out the cheaters. However, in some instances I encounter a cheat that removes my mini map, cannot use the phone or menu, cannot enter my businesses, makes the game missing some of it most important features and nearly useless. It is all repaired by changing to another session which defeats the reason I become a session host in the first place. Any ideas how to repair such bug without changing session?

**Issue 2**: Spammers should enter the players database in which I like to block them from entering the session again after session host kick.

**Issue 3**: Small bug involving NPC or user fight without the use of a weapon (bare hand). It is working properly when removing the menu.

**BTW** network players database is a very useful tool to block malicious players from re-entering the same session after host kick.

### Solution

Possible refresh  or "repair" mode or possibly another feature or something that I may be missing?

### Reason

Game become useless due to malicious players. (referring to issue 1)

**Comment by gir489returns** [comment]
This is incomprehensible. I have no idea what you're trying to ask.

**Comment by GreySideMM** [comment]
> This is incomprehensible. I have no idea what you're trying to ask.

Issue 1:
Apparently he means the feature of some P2Cs which can bug out your phone (that's the only one I know of from his list): Your phone gets stuck in your hand and you can't get rid of it.
Idk if YimMenu already blocks this and/or similar grieving methods. (I also encountered the inability to enter some interiors but idk what caused it.)

Issue 2:
I mean, that could be added.. but I don't think that's worth it?

Issue 3:
I also have no clue what this is about.

Btw:
Kicking someone automatically blocks players from rejoining - but only for that session.

**Comment by maybegreat48** [comment]
> Your phone gets stuck in your hand and you can't get rid of it

I haven't seen this in GTA before, but there's something similar in RDR with weapon objects

> However, in some instances I encounter a cheat that removes my mini map, cannot use the phone or menu, cannot enter my businesses, makes the game missing some of it most important features and nearly useless

That should not happen. Can you log script events and send that when someone forces you into that state?

> Small bug involving NPC or user fight without the use of a weapon (bare hand). It is working properly when removing the menu

Do you have anything enabled under `World`?

**Comment by spankymonkey** [comment]
> Issue 1: Apparently he means the feature of some P2Cs which can bug out your phone (that's the only one I know of from his list): Your phone gets stuck in your hand and you can't get rid of it. Idk if YimMenu already blocks this and/or similar grieving methods. (I also encountered the inability to enter some interiors but idk what caused it.)
> 
> Issue 2: I mean, that could be added.. but I don't think that's worth it?
> 
> Issue 3: I also have no clue what this is about.
> 
> Btw: Kicking someone automatically blocks players from rejoining - but only for that session.



> > Your phone gets stuck in your hand and you can't get rid of it
> 
> I haven't seen this in GTA before, but there's something similar in RDR with weapon objects
> 
> > However, in some instances I encounter a cheat that removes my mini map, cannot use the phone or menu, cannot enter my businesses, makes the game missing some of it most important features and nearly useless
> 
> That should not happen. Can you log script events and send that when someone forces you into that state?
> 
> > Small bug involving NPC or user fight without the use of a weapon (bare hand). It is working properly when removing the menu
> 
> Do you have anything enabled under `World`?

Issue 1 happens after a player in the session uses "OOM kick" on the session host (unconfirmed but a very plausible cause).
The phone does not get stuck but rather not showing up at all. The menu does not show up at all. The mini map is removed. Click ESC or P for map prompt and nothing show up. No possible of entering any business or any event. All prompts disappear. Can't use any weapon. I can see other players only within camera distance. My menu is set with zero mods, so it is as game normal as it can be.

Issue 2 I got resolved with entering the user in the database and then finding it in the user database and then issue a block from future entering into the public session. Blocking toxic users entering the public session is very useful and keeps the session just a bit more friendly.

Issue 3 still persists. Let me explain... when the menu is open then any fight my character involves using only bare hand (no weapon) it would miss the target. When the menu is off then a "no weapon" fight gets to the nearest target, say for example punching NPC to death and then it goes and punch the next NPC that is the closest by. When the menu is on then it would miss the NPC target like as if the target does not exists. Take for example the Taquilala mission for MC supply will completely not work with the menu on (it's that mission that require punching gang members not using any weapon).

I hope this clarifies a few things

**Comment by Yimura** [comment]
Improperly formatted issue.

An issue should be formatted as follows:
- One request/bug report per issue
- Follow the issue template as they are provided to you in the type selection screen
- Write a short title describing the contents, don't explain the whole problem in your title

Please open new issues, I will not spend any time reading the contents.
