### ISSUE TITLE
[Build]:  prevent from biddening account

### ISSUE THREAD

**Issue by a461581873** [Yimura/YimMenu#2691]
### Describe the build issues

Does yimmenu have a feature that prevents RockStar from detecting cheats?

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by pierrelasse** [comment]
Yimmenu has a anti anticheat if you mean that. Thats why after game updates, it is more common to be banned since the game updated their anticheat but yimmenu still has the old anti anticheat.
