### ISSUE TITLE
[Bug]: crash on inject

### ISSUE THREAD

**Issue by afasdfsfdsagddafh** [Yimura/YimMenu#2694]
### Describe the bug

cant inject

### Steps To Reproduce

open extreme injector (manual map)
open gta
load in
inject
crash

### Expected Behavior

injecting

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14220730/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Hi there, your crash log isn't useful. Could you repeat the steps you wrote down and upload the cout.log again?

**Comment by maybegreat48** [comment]
> open extreme injector (manual map)

Do not manual map YimMenu. It will crash your game

**Comment by Yimura** [comment]
> > open extreme injector (manual map)
> 
> Do not manual map YimMenu. It will crash your game

Whoops I missed that, indeed don't manual map YimMenu.
