### ISSUE TITLE
Cannot open source file "atSingleton.hpp" or "CTunables.hpp" since latest update

### ISSUE THREAD

**Issue by JTD420** [Yimura/YimMenu#270]
**Describe the bug**
The latest update which disables the sigscanner includes two new files in `pointers.hpp` which are not currently included in YimMenu resulting in errors building.

**To Reproduce**
Do a git pull to have the latest version and then attempt to build

**Expected behavior**
a successful build

**Logs**

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
Could add more details but I believe it's enough? Presuming just forgot too include the new files? lol

**Comment by Yimura** [comment]
Did you follow the exact staying up to date instructions?

https://github.com/Yimura/YimMenu#staying-up-to-date

**Comment by JTD420** [comment]
oof no I always forget about submodules ffs! My bad lemme do that now haah

**Comment by JTD420** [comment]
Thanks for fast reply! Problem fixed :)

Just had to do `git submodule update` & `GenerateProjects.bat` and it's building successfully again! Thanks :)
