### ISSUE TITLE
[Build]: Game Crashes With Latest Build

### ISSUE THREAD

**Issue by USBMenus** [Yimura/YimMenu#2705]
### Describe the build issues

after compiling the latest build with x64-Release, and loading into online, my game will crash within a minute or so (cout.log provided below), when building with x64-Debug i will receive the error in the image below

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/14234236/cout.log)

![image](https://github.com/YimMenu/YimMenu/assets/69381115/6d0605ce-0aaa-4553-8a59-144540e714fd)

### IDE/Compiler

Visual Studio 2022

### Additional context

ive compiled older versions and theyve worked fine

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by Yimura** [comment]
Only use debug if you know what you're doing otherwise it isn't too helpful.

Crash log was generated in Debug so it cannot be used, recreate the crash in Release mode and upload the cout.log of that.

**Comment by USBMenus** [comment]
i guess i was still using the debug version but i switched to the release and its seems to be doing fine, been playing for about 10 minutes and couldnt get an error

**Comment by USBMenus** [comment]
this isnt related so idk if i should make a new issue, but the outfit slots names arent showing, they havent been working for a while now

**Comment by Yimura** [comment]
Yes, unrelated create a new issue for this and check if there isn't already an issue stating this. If there isn't you can create one.
