### ISSUE TITLE
[Bug]: Crash on Proton due to commit #2698 or #2699

### ISSUE THREAD

**Issue by GreySideMM** [Yimura/YimMenu#2710]
### Describe the bug

Apparently GetWindowsVersion() causes a crash when running GTA thru Proton.
Disabling this line "solves" the problem:
https://github.com/YimMenu/YimMenu/blob/master/src/main.cpp#L164
I wasn't able to get a stacktrace as of now. (How to do so using Proton?)

### Steps To Reproduce

1. Use latest Proton

### Expected Behavior

No Crash

### Logs and/or screenshots

```
[22:29:03.9399848][DEBUG/logger.cpp:28] Using simple logger.
[22:29:05.2058948][INFO/main.cpp:158] Yim's Menu Initializing
[22:29:05.2059060][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	ec7735cb3a0e7fedb2fcf89112323fdff0dfe22d
	Date:	Mon Feb 12 18:26:07 2024
[22:29:05.2060947][INFO/main.cpp:113] Unable to read registry key UBR
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Oh yeah makes sense I guess, I'll fix this in a moment.

**Comment by Yimura** [comment]
Hey @GreySideMM, could you check out the build that the @github-actions bot will posted here #2711? Normally it should work after this.

**Comment by GreySideMM** [comment]
@Yimura Yes, this file starts up without any problem. Thank you very very much!

**Comment by Yimura** [comment]
Alright thanks for confirming, I'll merge it into master now.

**Comment by Vitamin-X** [comment]
how do you got the DLL to start in proton? tryed so many ways now and none worked

**Comment by Yimura** [comment]
> how do you got the DLL to start in proton? tryed so many ways now and none worked

Could you open up a new issue? There’s too little information provided in your comment for us to properly assess the problem you’re facing.

**Comment by Vitamin-X** [comment]
sorry, i just hoped he might can give me a hint with what he injected the DLL

but sure i can open an new issue, but its not really an issue more like seaking for an advise

still want me to open one?

**Comment by Yimura** [comment]
> sorry, i just hoped he might can give me a hint with what he injected the DLL
> 
> but sure i can open an new issue, but its not really an issue more like seaking for an advise
> 
> still want me to open one?

There are plenty of other issues where this was discussed from what I remember is that they used an ASI loader to then inject it as soon as the game booted up. Start with by looking at #334

**Comment by Vitamin-X** [comment]
got it working, Xenos was the problem, i used it to inject the dll on windows, but in proton is wasn't good

let make me a little tutorial....
im Running xUbuntu 23.10 on kernel 6.5.0-21 with NVIDIA 535.154.05 and the experimental proton in steam


1. install protontricks with running "sudo apt protontricks" in a terminal
(Rockstar version) 
2a. you need to add your socialclub launcher to steam
2b. right click on the Launcher.exe in your library and click on settings
2c open compatibility and select "Proton Experimental"
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/c7e4101c-e2b2-401c-9f77-ed1d48d78cad)
2d. run "protontricks -l 2> /dev/null | grep Launcher.exe" next in the terminal and note the ID, it shows something like that "Non-Steam shortcut: Launcher.exe (3274051658)"  
 
 (steam version) not exactly sure but 
 2a. change the compatibility to proton Experimental
 2a. run "protontricks -l" and look for GTAs ID and note it 

3. run "protontricks <GTA id> --gui " next in the terminal but change <GTA id> with the id you noted
3b. sometimes it shows "protontricks (ERROR): Active compatibility tool was found, but it's not a Proton installation supported by protontricks.
Proton installation could not be found!" no idea why but usually i just need to wait for a minute and run the command again and it works, or run "while [ true ]; do protontricks 3274051658 --gui;done" if you were impatient and then just get a coffee and come back to an open GUI
4. next select "select standard wineprefix" and click ok
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/2cc678e8-16f5-40e3-8618-cf86b325cabc)
5. next select "start winecfg" and click ok
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/a43217e8-3c34-44a0-bb7a-805b887de49b)
6.  next select "Windows 10" at Windows-Version and click ok
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/83dc780c-acfc-4f27-a1fe-7e0e48a30ac4)
7. if u used the impation way, focus the terminal and push crtl+c, if not closing the gui is enough
8. open steam again and start GTA (or just the launcher)
9. next you need RemoteDLL, seems like you can only download it from some shady websites but here is a version from one of them
[RemoteDll.zip](https://github.com/YimMenu/YimMenu/files/14403480/RemoteDll.zip)
10. extract it somewhere on your PC
11. next you need a version of protonhax you get it from here https://github.com/jcnils/protonhax/releases/
12. extract it ( and move the "protonhax" file to "/usr/bin/" if you wanna be able to start if from everywhere )
13. run "protonhax ls" that shows your the IDs of the currently running proton stances, (you probably only have 1 running so its ID 0)
14. run "protonhax run <instance id from before probably 0> <full path to RemoteDLL64.exe>"
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/cb67bd9e-5b22-4c88-b2b6-6ab053dcfc4c)
15. start GTA 
16. click on the little windows logo next to the box of "Target Process"
17. select the GTA5.exe from the list and click "Select"
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/2761e5da-1df3-4a9d-a1a1-78e435cba81c)
18. now open the folder where you saved your YimMenu.dll and drag the dll file into the box called "DLL Name
19. next click on "Inject DLL"
20. be happy that you finally got it running
![grafik](https://github.com/YimMenu/YimMenu/assets/8036752/72f7e80f-195f-4c60-9f87-8980350ece79)

**Comment by GreySideMM** [comment]
@Vitamin-X Oh well, sry for being late but it was already mentioned in the linked issue: You can simply use Ultimate ASI Loader.
See description here: https://github.com/YimMenu/YimMenu/issues/334#issuecomment-1668845510
Just better use the newest loader from https://github.com/ThirteenAG/Ultimate-ASI-Loader instead, not the linked in that post.
The ASI Loader even has the benefit that the menu is the "first" to be loaded and it won't fail. That's helpful when GTA tries to send a "bonus report" like a minute after the game launch.
(I'm using Steam, idk if that matters.)
For me your post might still be helpful, because as of now I have to reload the entire game just to test a new build.

**Comment by Vitamin-X** [comment]
yea i also liked it to have it seperate and years ago the asi loader was no bueno for online

**Comment by GreySideMM** [comment]
@Vitamin-X I never had it removed due to an update. (I'm using YimMenu only since 2 month, tho.) I used the ASI Loader before for offline mods. They (by accident) even survived a complete reinstall of the game. Idk about the social club (or R* launcher), but using Steam SC only gets launched after the start of the game. And then "fixed" by Yim. SocialClub never runs without the game, idk if this is even possible (directly) using Steam as the store.

**Comment by Vitamin-X** [comment]
i got the rockstar version directly, so i start social club over steam to get it running inside an proton instance

**Comment by gir489returns** [comment]
>This issue is closed
>Yet these two are having a discussion on it still

Github.
