### ISSUE TITLE
[Bug/Fix]: Yimmenu.dll crashing Game after update

### ISSUE THREAD

**Issue by GoldenGets** [Yimura/YimMenu#2712]
### Describe the bug

My game crash when inject Yimmenu.dll with xenos64 in version changelogs 2024-01-28 and 2024-02-10. Before that was fine when i use version changelog 2023-12-21 with the lua file. 

in cout.log, I thought the problem was: 
[08:33:14.8708422][WARN/batch.hpp:113] Failed to find 'CTSHP'.
[08:33:14.8915852][WARN/batch.hpp:113] Failed to find 'WMSB'

### Steps To Reproduce

1. launch game 2. open xenos injector 3. wait until loading is complete 4. when I inject yimmenu.dll with new version game will crashing

### Expected Behavior

I hope I can run yimmenu with the latest version

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14258711/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Do you have any mods installed? The game seems to be running in a polluted state on your end which causes YimMenu to crash.

**Comment by GoldenGets** [comment]
> Do you have any mods installed? The game seems to be running in a polluted state on your end which causes YimMenu to crash.

I forgot to say, yes that's right I installed menyoo with the latest hook script. and now I deleted it and reinstalled it. after that it runs normally again. thanks yimmura. 
And Is it dangerous in the future if I continue to use Menyoo online even with the latest scripthook?

**Comment by Yimura** [comment]
Without a mod menu that blocks that anti-cheat I wouldn’t use it in online because menyoo had some intentional vehicle spawning methods that would trigger the anti-cheat and possibly ban you.

I’m not sure that is still completely true after their anti-cheat rework.
