### ISSUE TITLE
[Request]: Retrieving entities

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2713]
### Problem

using lua, i would like to get all entities (vehicles/peds) with one binding

currently its individual bindings are vehicles, peds, props in lua > bindings > entities.cpp

static std::vector<Entity> get_all_vehicles_as_handles()
{
	return big::pools::get_all_vehicles_array();
}

### Solution

static std::vector<Entity> get_all_vehicles_and_peds()
{
	return big::pools::get_all_vehicles_array();
	return big::pools::get_all_peds_array();
}

### Reason

it would simply make things like forcefield and blackhole much easier to create via lua.

### Additional context

is it possible to make all of the bindings work with either capital or lowercase letters?  Not required, i guess its a way to tell the bindings apart from the natives.

**Comment by gir489returns** [comment]
Your solution doesn't work, once the C++ compiler encounters a return, it does a jump back to the subroutine that called it. The compiler will just optimize out your 2nd return (not call it).

This seems stupid and unnecessary, we already have [enough APIs exposed](https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/entities.md) that you could do this readily easily.

**Comment by xiaoxiao921** [comment]
```lua
local function get_all_vehicles_and_peds()
	local result = entities.get_all_vehicles_as_handles()
	
	local peds = entities.get_all_peds_as_handles()
	for k, v in pairs(peds) do
		table.insert(result, v)
	end
	
	return result
end
```
