### ISSUE TITLE
[Improvement]: Some settings should not be saved

### ISSUE THREAD

**Issue by GreySideMM** [Yimura/YimMenu#2719]
### Which feature

All settings that are session/world related, e.g.: Riot Mode, Never Wanted (for all), etc.

### Reason

I enabled Riot Mode, crashed a bit later (unrelated). And then I forgot that option - for the next hours. I even played missions with it. After a bunch modders in freemode attacked me out of nowhere and even crashed me twice for no obvious reason I remembered this setting. So I assume Riot Mode does send out some request that their menu blocked & notified them. Because I wasn't doing anything at all and only I got that much attacked.
So my proposal:
Don't save such settings.
Reset them with every new session.

**Comment by maybegreat48** [comment]
Riot mode cannot be detected over the network

> and even crashed me twice for no obvious reason

People can crash you?

**Comment by GreySideMM** [comment]
Oh, ok. Wasn't sure about that tho. Haven't looked into that code yet. (I played with another modder, he hasn't said anything about it.)
Crashing? Yes, sure. Well besides that known Stand crash #2672 there seems wo be further methods as I have added these two methods into my code. At least 2t1 seems to be a no-problem. I have been crashed at least 3 times within the last week. (One prior the two new methods.)

**Comment by tyackman** [comment]
> People can crash you?

![chairhax](https://github.com/YimMenu/YimMenu/assets/38179522/695264e5-8e25-4065-8b9d-e07f3050ee83)

This may have been incorporated into stand's elegant crash as well

**Comment by ghost** [comment]
> > People can crash you?
> 
> ![chairhax](https://private-user-images.githubusercontent.com/38179522/305728466-695264e5-8e25-4065-8b9d-e07f3050ee83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDYxNDIsIm5iZiI6MTcwODQ0NTg0MiwicGF0aCI6Ii8zODE3OTUyMi8zMDU3Mjg0NjYtNjk1MjY0ZTUtOGUyNS00MDY1LThiOWQtZTA3ZjMwNTBlZTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE2MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYjllOGZjOTg4NWIxNmFmZmI0YzI1NWZjZDk0YzMzZTdkYWJmMTRkNTI0MzM3ZWE3YWI5NjIwMDVkNDYyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XhwFU0zIY-PH3AXj7MCR7PFvyalAH2fN3BSQuachbGU)
> 
> This may have been incorporated into stand's elegant crash as well

Interesting I will have a look into this as this would help patching #2672
