### ISSUE TITLE
Spoofing crew tag (and more)

### ISSUE THREAD

**Issue by maybegreat48** [Yimura/YimMenu#272]
**Is your feature request related to a problem? Please describe.**
Pretty much every p2c have this one

**Describe the solution you'd like**
```c++
class CPlayerGamerDataNode
{
public:
	char pad_0000[192]; //0x0000
	bool m_has_clan_data; //0x00C0
	char pad_00C1[7]; //0x00C1
	int32_t m_clan_id; //0x00C8
	char pad_00CC[16]; //0x00CC
	bool m_is_rockstar_clan; //0x00DC
	bool m_square_clan_tag; //0x00DD
	char pad_00DE[1]; //0x00DE
	char m_clan_name[24]; //0x00DF
	char m_clan_tag[8]; //0x00F7
	char pad_00FF[73]; //0x00FF
	char m_clan_role[32]; //0x0148
	char pad_0168[170]; //0x0168
	bool m_is_rockstar_dev; //0x0212
	bool m_is_rockstar_qa; //0x0213
	bool m_is_cheater; //0x0214
	char pad_0215[23]; //0x0215
	bool m_has_communication_privilege; //0x022C
	char pad_022D[627]; //0x022D
}; //Size: 0x04A0
static_assert(sizeof(CPlayerGamerDataNode) == 0x4A0);

void hooks::write_player_gamer_data_node(rage::netObject* player, CPlayerGamerDataNode* node)
{
	g_hooking->m_write_player_gamer_data_node_hook.get_original<decltype(&write_player_gamer_data_node)>()(player, node);

	if (g.spoofing.spoof_crew_data)
	{
		strcpy(node->m_clan_tag, g.spoofing.crew_tag.c_str());
		node->m_is_rockstar_clan = g.spoofing.rockstar_crew;
		node->m_square_clan_tag = g.spoofing.square_crew_tag;

		if (g.spoofing.rockstar_crew)
		{
			strcpy(node->m_clan_name, "Rockstar");
		}
	}

	node->m_is_cheater = g.spoofing.spoof_cheater;
	node->m_is_rockstar_dev = g.spoofing.spoof_rockstar_dev;
	node->m_is_rockstar_qa = g.spoofing.spoof_rockstar_qa;
}

// Write Player Gamer Data Node
main_batch.add("WPGDN", "48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC 20 48 81 C1 ? ? ? ? 48 8B DA E8", [this](memory::handle ptr)
{
	m_write_player_gamer_data_node = ptr.as<PVOID>();
});
```

**Provide Reasoning**
Complements name and RID spoofing, will be more beneficial if spoofer profiles are added in the future.

**Additional context**
Make sure RID is spoofed when spoofing R* Dev and QA status as every player in the session will send metrics if you join with that enabled

**Comment by Yimura** [comment]
Yo good stuff!

**Comment by SkiddyToast** [comment]
Just wondering, how were you able to figure out the purpose of the offsets, as I don't see any public documentation of that node?

**Comment by maybegreat48** [comment]
Fairly easy to reverse that one. You can see that the writer gets the owner `CNetGamePlayer` of the object and uses some offset (need to be added to GTAV-Classes) to get `netPlayerData` which contains the crew info that can be found at `NETWORK_CLAN_PLAYER_GET_DESC` and the scripts

**Comment by SkiddyToast** [comment]
I have made an updated struct as yours has some incorrect sizing (Correct sizing was found in `NodeCommonDataOperations<CPlayerGamerDataNode,IPlayerNodeDataAccessor>`), and I added some new variables that were in the pads you had.
```c++
class CPlayerGamerDataNode
{
public:
  char pad_0000[192];
  int64_t unk_0xC0;
  int64_t m_clan_id;
  int32_t unk_0xD0;
  int32_t unk_0xD4;
  int32_t unk_0xD8;
  bool m_is_rockstar_clan;
  bool m_square_clan_tag;
  char m_clan_name[25];
  char m_clan_tag[5];
  char unk_0xFC[65];
  char pad_013D[3];
  int64_t m_clan_id_2;
  char m_clan_role[25];
  char pad_0161[3];
  int32_t unk_0x164;
  int64_t unk_0x168;
  char pad_0170[8];
  bool unk_0x178;
  bool unk_0x179;
  char unk_0x17A[25];
  bool unk_0x193;
  bool unk_0x194;
  char unk_0x195[125];
  bool m_is_rockstar_dev;
  bool m_is_rockstar_qa;
  bool m_is_cheater;
  char pad_0215[3];
  uint32_t unk_0x218;
  bool unk_0x21C;
  char pad_021D[3];
  int32_t unk_0x220;
  int32_t unk_0x224;
  uint32_t unk_0x228;
  bool m_has_communication_privilege;
  char pad_022D[3];
  int32_t unk_0x230;
  char pad_0234[620];
};
```

**Comment by maybegreat48** [comment]
unk_0x195 is the base64 encoded version of the current `rlSessionInfo` aka "gsinfo"
unk_0x218 is most likely matchmaking group

**Comment by cristyanul** [comment]
Idk why my implementation of this doesn't work -> [commit](https://github.com/cristyanul/YimMenu/commit/6637c21c10251f03ed7e492b892392200efe995b)

**Comment by Yimura** [comment]
> Idk why my implementation of this doesn't work -> [commit](https://github.com/cristyanul/YimMenu/commit/6637c21c10251f03ed7e492b892392200efe995b)

Don't want to be mean but issues aren't a place to ask for help really on your implementation of it.

**Comment by maybegreat48** [comment]
> Idk why my implementation of this doesn't work -> [commit](https://github.com/cristyanul/YimMenu/commit/6637c21c10251f03ed7e492b892392200efe995b)

You have to call the original first then modify the node later, changes will not be visible locally so ask someone to verify whether its working or not. The function does not return anything

**Comment by SkiddyToast** [comment]
If I went through all of the nodes and made classes for them, could you help on identifying the variables in the undocumented classes? I'm attempting to make a full set of classes for the nodes, but the documentation I use to name them (FiveM's `SyncTrees_Five.h`) doesn't parse certain nodes, such as this one. Of course it will all be available to the public, I just want to document the sync trees as much as possible in order to make sync crash protections easier and more available.

**Comment by maybegreat48** [comment]
I will help where I can. FiveM has probably covered the most important stuff though

**Comment by maybegreat48** [comment]
unk_0x230 is a "account id" might be another RID leak (not tested)

**Comment by SkiddyToast** [comment]
I have updated the class with the debug names of the variables from here: [Pastebin of NodeCommonDataOperation classes from an Xbox dump](https://pastebin.com/raw/iaehSAws)
```c++
class CPlayerGamerDataNode
{
public:
  char pad_0000[192];// 0x0000
  int64_t m_clan_member_id;// 0x00C0
  int64_t m_clan_id;// 0x00C8
  int32_t m_clan_color;// 0x00D0
  int32_t m_clan_member_count;// 0x00D4
  int32_t m_clan_created_time;// 0x00D8
  bool m_is_system_clan;// 0x00DC
  bool m_is_clan_open;// 0x00DD
  char m_clan_name[25];// 0x00DE
  char m_clan_tag[5];// 0x00F7
  char m_clan_motto[65];// 0x00FC
  char pad_013D[3];// 0x013D
  int64_t m_clan_id_2;// 0x0140
  char m_clan_rank_name[25];// 0x0148
  char pad_0161[3];// 0x0161
  int32_t m_clan_rank_order;// 0x0164
  int64_t m_clan_rank_flags;// 0x0168
  char pad_0170[8];// 0x0170
  bool m_need_crew_rank_sysflags;// 0x0178
  bool m_need_crew_rank_title;// 0x0179
  char m_crew_rank_title[25];// 0x017A
  bool m_has_started_transition;// 0x0193
  bool m_has_transition_info;// 0x0194
  char m_transition_info_buffer[125];// 0x0195
  bool m_is_rockstar_dev;// 0x0212
  bool m_is_rockstar_qa;// 0x0213
  bool m_is_cheater;// 0x0214
  char pad_0215[3];// 0x0215
  uint32_t m_matchmaking_group;// 0x0218
  bool m_need_mute_data;// 0x021C
  char pad_021D[3];// 0x021D
  int32_t m_mute_count;// 0x0220
  int32_t m_mute_talkers_count;// 0x0224
  uint32_t unk_0x228;// 0x0228
  bool m_has_communication_privilege;// 0x022C
  char pad_022D[3];// 0x022D
  int32_t unk_0x230;// 0x0230
  char pad_0234[620];// 0x0234
};

```

**Comment by RileySpier** [comment]
> I have updated the class with the debug names of the variables from here: [Pastebin of NodeCommonDataOperation classes from an Xbox dump](https://pastebin.com/raw/iaehSAws)
> 
> ```c++
> struct CPlayerGamerDataNode
> {
>   char pad_0000[192];
>   int64_t m_clan_member_id;
>   int64_t m_clan_id;
>   int32_t m_clan_color;
>   int32_t m_clan_member_count;
>   int32_t m_clan_created_time;
>   bool m_is_system_clan;
>   bool m_is_clan_open;
>   char m_clan_name[25];
>   char m_clan_tag[5];
>   char m_clan_motto[65];
>   char pad_013D[3];
>   int64_t m_clan_id_2;
>   char m_clan_rank_name[25];
>   char pad_0161[3];
>   int32_t m_clan_rank_order;
>   int64_t m_clan_rank_flags;
>   char pad_0170[8];
>   bool m_need_crew_rank_sysflags;
>   bool m_need_crew_rank_title;
>   char m_crew_rank_title[25];
>   bool m_has_started_transition;
>   bool m_has_transition_info;
>   char m_transition_info_buffer[125];
>   bool m_is_rockstar_dev;
>   bool m_is_rockstar_qa;
>   bool m_is_cheater;
>   char pad_0215[3];
>   uint32_t m_matchmaking_group;
>   bool m_need_mute_data;
>   char pad_021D[3];
>   int32_t m_mute_count;
>   int32_t m_mute_talkers_count;
>   uint32_t unk_0x228;
>   bool m_has_communication_privilege;
>   char pad_022D[3];
>   int32_t unk_0x230;
>   char pad_0234[620];
> };
> ```

good
can u add offsets as comment like from the original struct from maybegreat48

**Comment by maybegreat48** [comment]
> I have updated the class with the debug names of the variables from here: [Pastebin of NodeCommonDataOperation classes from an Xbox dump](https://pastebin.com/raw/iaehSAws)
> 
>
> ...

Ah now I see how FiveM reversed a lot of the node data. Thanks for the info

**Comment by ApoIlos** [comment]
So im still new to revering and need abit of help i need help identifying witch function is for each node here's the ones i have named so far

![image](https://user-images.githubusercontent.com/65520840/173408799-27dfa7d2-3284-41bb-bdda-2349e656e275.png)
