### ISSUE TITLE
[Improvement]: The built-in font causes some Chinese to be displayed as ? logo, is it possible to fix or disable the font that comes with it?

### ISSUE THREAD

**Issue by xiaoyou1933** [Yimura/YimMenu#2723]
### Which feature

The built-in font causes some Chinese to be displayed as ? logo, is it possible to fix or disable the font that comes with it?

### Reason

The built-in font causes some Chinese to be displayed as ? logo, is it possible to fix or disable the font that comes with it?

**Comment by MarkEcza** [comment]
This is because it's loaded with the range: ``GetGlyphRangesChineseSimplifiedCommon`` instead of ``GetGlyphRangesChineseFull``.

**Comment by Yimura** [comment]
And this can currently not be fixed because or technical limitations.

**Comment by xiaoyou1933** [comment]
> 由于技术限制，目前无法解决此问题。

Well, hopefully this issue will be solved, I like yimmenu very much, he is great and his developers are great!
