### ISSUE TITLE
[Bug]: Invalid character output error

### ISSUE THREAD

**Issue by xenix4845** [Yimura/YimMenu#2724]
### Describe the bug

When you click 'Forced Update Language', there is an error in choosing to participate in a session that is filled with unknown numbers or letters or disappears.

![image](https://github.com/YimMenu/YimMenu/assets/156365851/acac2937-76d2-42f7-87b9-7c619258b60b)
There appears to be a problem with the session switcher

### Steps To Reproduce

1. Force update language
2. Network > session switch 

### Expected Behavior

Bad character output and mess up

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

Korean

### YimMenu Language

English (US)

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
I can confirm this bug is indeed present.
