### ISSUE TITLE
[Request]: LUA binding for Model Preview

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2725]
### Problem

Id like to simply request a lua script binding addition for using the model preview service and maybe to allow the model preview service to also allow previewing peds and objects(props) if it doesnt already.

### Solution

a lua binding such as 

preview.show_model_preview(hash for Obj/Ped/Veh)

### Reason

In my own object spawner/vehicle spawner scripts in lua, it would not only help me figure out the object im spawning before i spawn it, but also help me figure out which objects are invalid so i can get rid of the ones that do nothing when spawned.

would also generally benefit others who have created their own spawners as well.

### Additional context

Is it possible to get real object names like the vehicles have?

Bind > vehicles.get_vehicle_display_name(veh)

Bind > objects.get_object_display_name(obj)

**Comment by Deadlineem** [comment]
@Yimura Possible to look into this with the next update?  Would love to have the lua binding for it.

**Comment by Yimura** [comment]
> @Yimura Possible to look into this with the next update? Would love to have the lua binding for it.

No, I can’t give guarantees nor promises on priority of things.

**Comment by Deadlineem** [comment]
> > @Yimura Possible to look into this with the next update? Would love to have the lua binding for it.
> 
> No, I can’t give guarantees nor promises on priority of things.

No sir, just peek into it if you have time, no rush on it.  I wish i knew more C++ id push the code lol

**Comment by gir489returns** [comment]
This is not possible to add currently, due to the way the previewer works. This is because the previewer is not thread-safe.
