### ISSUE TITLE
[Bug]: Game Crash [Launcher Update]

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2726]
### Describe the bug

Game crashes immediately upon injection after the laucher updated this morning

### Steps To Reproduce

Update launcher, try to inject yim

### Expected Behavior

I mean, it IS an update so i guess i dont expect it to work without being updated lol

### Logs and/or screenshots

cout.log
--------------------------------------------------
https://pastebin.com/L2DMXv4q

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Can repro, please wait a bit until we fix this!

**Comment by Deadlineem** [comment]
You guys are the best team around!  Long live YimMenu!

**Comment by opium-user** [comment]
> You guys are the best team around! Long live YimMenu!

Hey, sorry, but can you please describe how do i apply theese changes? like what do i do to fix this issue
(I'm a complete 0 in coding so thats probably might be a dumb question)

**Comment by Aftab-Fury** [comment]
To be honest, this project is too complex for someone who is zero in coding. 
Anyways about fixing this issue, some fixes will be pushed and new dll will be generated, just that dll and you are good to go.

**Comment by Aftab-Fury** [comment]
> > You guys are the best team around! Long live YimMenu!
> 
> Hey, sorry, but can you please describe how do i apply theese changes? like what do i do to fix this issue (I'm a complete 0 in coding so thats probably might be a dumb question)

To be honest, this project is too complex for someone who is zero in coding.
Anyways about fixing this issue, some fixes will be pushed and new dll will be generated, just download that dll and you are good to go.

**Comment by opium-user** [comment]
> > > You guys are the best team around! Long live YimMenu!
> > 
> > 
> > Hey, sorry, but can you please describe how do i apply theese changes? like what do i do to fix this issue (I'm a complete 0 in coding so thats probably might be a dumb question)
> 
> To be honest, this project is too complex for someone who is zero in coding. Anyways about fixing this issue, some fixes will be pushed and new dll will be generated, just that dll and you are good to go.

Well I'm not really taking part in this project) Just wanted to fix the thing, thank the developers and move on.
So ur saying that I can't just edit this "src/pointers.cpp" by myself? I don't even know how do I get to it haha. But I'd try for sure

**Comment by lisarun** [comment]
The new PD should be

 48 8D 05 ? ? ? ? 48 8B D9 48 89 01 48 83 C1 48 E8 ? ? ? ? 48 8B

**Comment by Deadlineem** [comment]
I have applied the changes myself/compiled it and can confirm this solves the crashing

Line 1773 

`"PD",
"48 8D 05 ? ? ? ? 48 8B D9 48 89 01 48 83 C1 48 E8 ? ? ? ? 48 8B",
[](memory::handle ptr)
{
    auto presence_data_vft             = ptr.add(3).rip().as<PVOID*>();
    g_pointers->m_sc.m_update_presence_attribute_int    = (functions::update_presence_attribute_int)presence_data_vft[1];
    g_pointers->m_sc.m_update_presence_attribute_string = (functions::update_presence_attribute_string)presence_data_vft[3];
}`

Thank you @sch-lda for that quick fix!

**Comment by lisarun** [comment]
The new PD should be

 48 8D 05 ? ? ? ? 48 8B D9 48 89 01 48 83 C1 48 E8 ? ? ? ? 48 8B

**Comment by Deadlineem** [comment]
> > > > You guys are the best team around! Long live YimMenu!
> > > 
> > > 
> > > Hey, sorry, but can you please describe how do i apply theese changes? like what do i do to fix this issue (I'm a complete 0 in coding so thats probably might be a dumb question)
> > 
> > 
> > To be honest, this project is too complex for someone who is zero in coding. Anyways about fixing this issue, some fixes will be pushed and new dll will be generated, just that dll and you are good to go.
> 
> Well I'm not really taking part in this project) Just wanted to fix the thing, thank the developers and move on. So ur saying that I can't just edit this "src/pointers.cpp" by myself? I don't even know how do I get to it haha. But I'd try for sure

I commented the fix above, you can clone the repo and open with visual studio, find pointers.cpp and Ctrl+F for "PD" (with quotes) the first one is a short line, the second find of the search provides the PD line that requires changing.

**Comment by Deadlineem** [comment]
> > > You guys are the best team around! Long live YimMenu!
> > 
> > 
> > Hey, sorry, but can you please describe how do i apply theese changes? like what do i do to fix this issue (I'm a complete 0 in coding so thats probably might be a dumb question)
> 
> To be honest, this project is too complex for someone who is zero in coding. Anyways about fixing this issue, some fixes will be pushed and new dll will be generated, just download that dll and you are good to go.

Im new asf to C++ n its pretty straight forward following yimuras pull link
 https://github.com/YimMenu/YimMenu/pull/2727 and clicking the commits tab, shows you exactly what/where to edit.

**Comment by coolou3456** [comment]
Hi i have downloaded the new version yimenu still getting the same issue  when i inject  yimenu into the game using Xenos64 the game crashes. I tried to delete the old Xenos profile too but it still wont work please help !

**Comment by Aftab-Fury** [comment]
> Hi i have downloaded the new version yimenu still getting the same issue when i inject yimenu into the game using Xenos64 the game crashes. I tried to delete the old Xenos profile too but it still wont work please help !

Please go through the comments.

**Comment by coolou3456** [comment]
> > Hi i have downloaded the new version yimenu still getting the same issue when i inject yimenu into the game using Xenos64 the game crashes. I tried to delete the old Xenos profile too but it still wont work please help !
> 
> Please go through the comments.

I have and hence why i downloaded the newer yimenu.dll BUT the issue is still there i think you have to change a code lin to fix it looking at comments BUT  im 0 at coding lol. I was wondering if changing the injector would fix it ?

**Comment by Deadlineem** [comment]
> > Hi i have downloaded the new version yimenu still getting the same issue when i inject yimenu into the game using Xenos64 the game crashes. I tried to delete the old Xenos profile too but it still wont work please help !
> 
> Please go through the comments.

48 8D 05 ? ? ? ? 48 8B F9 48 89 01 48 83 C1 08 E8 ? ? ? ? 33 C0

Gir corrected it, though the last one DOES work, if it doesnt match it could cause adverse effects, use this one instead in pointers.cpp

**Comment by Deadlineem** [comment]
> > > Hi i have downloaded the new version yimenu still getting the same issue when i inject yimenu into the game using Xenos64 the game crashes. I tried to delete the old Xenos profile too but it still wont work please help !
> > 
> > 
> > Please go through the comments.
> 
> I have and hence why i downloaded the newer yimenu.dll BUT the issue is still there i think you have to change a code lin to fix it looking at comments BUT im 0 at coding lol. I was wondering if changing the injector would fix it ?

Its not updated just yet, R* updated the launcher this morning so Yimura and the rest just found out about the crashing.

I have the updated dll myself i just cloned the repo n made the changes

**Comment by coolou3456** [comment]
So does that mean Yimenu should work now?

**Comment by Deadlineem** [comment]
> 48 8D 05 ? ? ? ? 48 8B F9 48 89 01 48 83 C1 08 E8 ? ? ? ? 33 C0

Not unless you make the changes yourself and compile it in Visual Studio.  Otherwise, you need to wait for the commit to be pushed to the main branch and the dll to update here.

**Comment by coolou3456** [comment]
Sounds bit complicated i guess i have to wait for a newer version of Yimenu as im 0 at coding haha

**Comment by huddaasss** [comment]
go team yim we will wait for your update to fix this bug

**Comment by coolou3456** [comment]
appreciate the effort you guys put behind the scenes to make something this complicated work !
