### ISSUE TITLE
[Bug]: Failed pattrn search for Social Club

### ISSUE THREAD

**Issue by jolbus52** [Yimura/YimMenu#2734]
### Describe the bug

After trying to inject multiple instances of the yim dll i come across the same kind of error message: UserThreadStartFailed to find some patterns for Social Club, game crashes afterwards

### Steps To Reproduce

1. Injecting the dll

### Expected Behavior

The menu loading in normally without crashing the game

### Logs and/or screenshots

..

[19:12:33.8768795][FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3765269347
Dumping modules:
GTA5.exe Base Address: 0x7FF7D0500000 Size: 67215872
ntdll.dll Base Address: 0x7FF83B9B0000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FF83A870000 Size: 528384
KERNELBASE.dll Base Address: 0x7FF839230000 Size: 1638400
USER32.dll Base Address: 0x7FF839C70000 Size: 610304
win32u.dll Base Address: 0x7FF838CF0000 Size: 49152
GDI32.dll Base Address: 0x7FF839B70000 Size: 57344
gdi32full.dll Base Address: 0x7FF838FA0000 Size: 675840
msvcp_win.dll Base Address: 0x7FF838E40000 Size: 335872
ucrtbase.dll Base Address: 0x7FF838D20000 Size: 798720
PSAPI.DLL Base Address: 0x7FF83B880000 Size: 4096
WS2_32.dll Base Address: 0x7FF839BF0000 Size: 290816
RPCRT4.dll Base Address: 0x7FF83A590000 Size: 880640
CRYPT32.dll Base Address: 0x7FF8390C0000 Size: 1134592
WINTRUST.dll Base Address: 0x7FF839690000 Size: 307200
msvcrt.dll Base Address: 0x7FF839710000 Size: 507904
VERSION.dll Base Address: 0x7FF82FFC0000 Size: 12288
DSOUND.dll Base Address: 0x7FFFF49E0000 Size: 491520
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFFC1BE0000 Size: 96256
IMM32.dll Base Address: 0x7FF839E20000 Size: 126976
advapi32.dll Base Address: 0x7FF83AE30000 Size: 442368
bcrypt.dll Base Address: 0x7FF839660000 Size: 110592
sechost.dll Base Address: 0x7FF83B7D0000 Size: 458752
SHLWAPI.dll Base Address: 0x7FF83AEF0000 Size: 212992
combase.dll Base Address: 0x7FF8397C0000 Size: 2539520
SHELL32.dll Base Address: 0x7FF83AF70000 Size: 6852608
bink2w64.dll Base Address: 0x7FFFF68D0000 Size: 307712
ole32.dll Base Address: 0x7FF83A1F0000 Size: 909312
OLEAUT32.dll Base Address: 0x7FF83B890000 Size: 647168
WININET.dll Base Address: 0x7FF8180F0000 Size: 2113536
WINMM.dll Base Address: 0x7FF8314F0000 Size: 114688
MF.dll Base Address: 0x7FF832680000 Size: 372736
MFPlat.DLL Base Address: 0x7FF831D20000 Size: 1503232
shcore.dll Base Address: 0x7FF83A430000 Size: 684032
msdmo.dll Base Address: 0x7FF812030000 Size: 16384
MFReadWrite.dll Base Address: 0x7FFFD0500000 Size: 995328
PROPSYS.dll Base Address: 0x7FF833AB0000 Size: 692224
WTSAPI32.dll Base Address: 0x7FF837B90000 Size: 40960
d3d9.dll Base Address: 0x7FFFD17C0000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFFC5530000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF81DED0000 Size: 48128
ResampleDmo.DLL Base Address: 0x7FFFEF520000 Size: 503808
DINPUT8.dll Base Address: 0x7FF81DCD0000 Size: 176128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FF83A940000 Size: 913408
IPHLPAPI.DLL Base Address: 0x7FF8377E0000 Size: 122880
powrprof.dll Base Address: 0x7FF837B40000 Size: 77824
winmmbase.dll Base Address: 0x7FF826650000 Size: 102400
d3dx9_43.dll Base Address: 0x7FFFC4020000 Size: 2280960
cfgmgr32.dll Base Address: 0x7FF8389E0000 Size: 221184
dwmapi.dll Base Address: 0x7FF8363D0000 Size: 90112
OPENGL32.dll Base Address: 0x7FFFF5FC0000 Size: 798720
dxcore.dll Base Address: 0x7FF836440000 Size: 139264
GLU32.dll Base Address: 0x7FF82B8A0000 Size: 126976
MFCORE.DLL Base Address: 0x7FF8321F0000 Size: 3022848
UMPDC.dll Base Address: 0x7FF837B20000 Size: 36864
kernel.appcore.dll Base Address: 0x7FF837DE0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FF8395E0000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FF831BC0000 Size: 102400
MSASN1.dll Base Address: 0x7FF838990000 Size: 36864
gameoverlayrenderer64.dll Base Address: 0x7FF81E2F0000 Size: 999424
inputhost.dll Base Address: 0x7FF826E60000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FF835950000 Size: 864256
CRYPTBASE.DLL Base Address: 0x7FF838580000 Size: 12288
windows.storage.dll Base Address: 0x7FF836C10000 Size: 7032832
wintypes.dll Base Address: 0x7FF836AD0000 Size: 544768
dbghelp.dll Base Address: 0x7FF835EF0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FF81C370000 Size: 131072
d3d12.dll Base Address: 0x7FF81A440000 Size: 102400
CRYPTSP.dll Base Address: 0x7FF8385A0000 Size: 57344
rsaenh.dll Base Address: 0x7FF837D40000 Size: 147456
uxtheme.dll Base Address: 0x7FF836150000 Size: 425984
clbcatq.dll Base Address: 0x7FF839E60000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFF5F50000 Size: 253952
d3d11.dll Base Address: 0x7FF834A90000 Size: 1867776
DEVOBJ.dll Base Address: 0x7FF8389B0000 Size: 110592
dxgi.dll Base Address: 0x7FF8362C0000 Size: 651264
WMICLNT.dll Base Address: 0x7FF832C20000 Size: 32768
imagehlp.dll Base Address: 0x7FF83AF50000 Size: 49152
wbemprox.dll Base Address: 0x7FF82F5D0000 Size: 28672
wbemcomn.dll Base Address: 0x7FF82F550000 Size: 311296
wbemsvc.dll Base Address: 0x7FF82CBB0000 Size: 8192
fastprox.dll Base Address: 0x7FF82D310000 Size: 708608
amsi.dll Base Address: 0x7FF82CB20000 Size: 57344
USERENV.dll Base Address: 0x7FF8382F0000 Size: 102400
profapi.dll Base Address: 0x7FF838C20000 Size: 90112
MpOav.dll Base Address: 0x7FF82C2E0000 Size: 204800
gpapi.dll Base Address: 0x7FF8382C0000 Size: 77824
cryptnet.dll Base Address: 0x7FF82FF80000 Size: 139264
WINNSI.DLL Base Address: 0x7FF836400000 Size: 16384
NSI.dll Base Address: 0x7FF83A390000 Size: 8192
steam_api64.dll Base Address: 0x63BE0000 Size: 110592
steamclient64.dll Base Address: 0x7FFFB2D00000 Size: 16407040
tier0_s64.dll Base Address: 0x7FF81E100000 Size: 260608
vstdlib_s64.dll Base Address: 0x7FF81E040000 Size: 285696
Secur32.dll Base Address: 0x7FF837BB0000 Size: 12288
MSWSOCK.dll Base Address: 0x7FF838250000 Size: 331776
SSPICLI.DLL Base Address: 0x7FF838040000 Size: 126976
directxdatabasehelper.dll Base Address: 0x7FF831740000 Size: 196608
nvapi64.dll Base Address: 0x7FF824430000 Size: 6290432
drvstore.dll Base Address: 0x7FF82FE20000 Size: 1044480
wldp.dll Base Address: 0x7FF8384D0000 Size: 188416
D3D10_1.DLL Base Address: 0x7FFFFA4A0000 Size: 147456
d3d10_1core.dll Base Address: 0x7FF834460000 Size: 12288
dhcpcsvc.DLL Base Address: 0x7FF831C20000 Size: 69632
MSCTF.dll Base Address: 0x7FF839F90000 Size: 1077248
textinputframework.dll Base Address: 0x7FF827F80000 Size: 1015808
CoreUIComponents.dll Base Address: 0x7FF830CE0000 Size: 2039296
WINSTA.dll Base Address: 0x7FF837770000 Size: 229376
nvldumdx.dll Base Address: 0x7FF82DB80000 Size: 591872
nvgpucomp64.dll Base Address: 0x7FF8291E0000 Size: 29061632
nvwgf2umx.dll Base Address: 0x7FF81F010000 Size: 38347776
MessageBus.dll Base Address: 0x7FF82CBD0000 Size: 5349888
HID.DLL Base Address: 0x7FF837510000 Size: 24576
MMDevApi.dll Base Address: 0x7FF82E210000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFF5EC0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FF828370000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FF8366E0000 Size: 36864
Windows.UI.dll Base Address: 0x7FF81CA80000 Size: 966656
avrt.dll Base Address: 0x7FF8318E0000 Size: 8192
napinsp.dll Base Address: 0x7FF8327E0000 Size: 53248
pnrpnsp.dll Base Address: 0x7FF832720000 Size: 69632
DNSAPI.dll Base Address: 0x7FF837850000 Size: 737280
winrnr.dll Base Address: 0x7FF8315B0000 Size: 32768
nlansp_c.dll Base Address: 0x7FFFEF330000 Size: 81920
wshbth.dll Base Address: 0x7FF8317F0000 Size: 45056
fwpuclnt.dll Base Address: 0x7FF830A00000 Size: 294912
rasadhlp.dll Base Address: 0x7FF82DE50000 Size: 8192
socialclub.dll Base Address: 0x7FFFF5700000 Size: 2599424
chrome_elf.dll Base Address: 0x7FF81DEF0000 Size: 901120
libcef.dll Base Address: 0x7FFF93610000 Size: 151009280
COMDLG32.dll Base Address: 0x7FF83A0F0000 Size: 778240
COMCTL32.dll Base Address: 0x7FF827EC0000 Size: 573440
UIAutomationCore.DLL Base Address: 0x7FF80EAB0000 Size: 3063808
OLEACC.dll Base Address: 0x7FF828D10000 Size: 274432
NETAPI32.dll Base Address: 0x7FF81C800000 Size: 49152
WINHTTP.dll Base Address: 0x7FF831F10000 Size: 987136
ncrypt.dll Base Address: 0x7FF838690000 Size: 114688
DWrite.dll Base Address: 0x7FF834810000 Size: 1654784
WINSPOOL.DRV Base Address: 0x7FF82B740000 Size: 405504
USP10.dll Base Address: 0x7FFFD1970000 Size: 4096
urlmon.dll Base Address: 0x7FF82C360000 Size: 1298432
dxva2.dll Base Address: 0x7FFFD1790000 Size: 102400
wevtapi.dll Base Address: 0x7FF831790000 Size: 245760
CRYPTUI.dll Base Address: 0x7FFFD1730000 Size: 278528
ESENT.dll Base Address: 0x7FF8191D0000 Size: 3145728
credui.dll Base Address: 0x7FF835C50000 Size: 65536
iertutil.dll Base Address: 0x7FF81ED50000 Size: 557056
netutils.dll Base Address: 0x7FF837760000 Size: 20480
srvcli.dll Base Address: 0x7FF826050000 Size: 57344
DSROLE.DLL Base Address: 0x7FF837A10000 Size: 8192
WKSCLI.DLL Base Address: 0x7FF831530000 Size: 49152
SAMCLI.DLL Base Address: 0x7FF82D6F0000 Size: 61440
NTASN1.dll Base Address: 0x7FF838650000 Size: 69632
FirewallAPI.dll Base Address: 0x7FF837680000 Size: 385024
fwbase.dll Base Address: 0x7FF837600000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FF825FF0000 Size: 245760
wdmaud.drv Base Address: 0x7FFFF6E50000 Size: 200704
ksuser.dll Base Address: 0x7FF81D770000 Size: 8192
msacm32.drv Base Address: 0x7FF81D200000 Size: 20480
MSACM32.dll Base Address: 0x7FF804140000 Size: 77824
midimap.dll Base Address: 0x7FF8107D0000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FF80F5B0000 Size: 45056
dhcpcsvc6.DLL Base Address: 0x7FF831C40000 Size: 28672
YimMenu(53).dll Base Address: 0x7FFF91840000 Size: 9221120
MSVCP140.dll Base Address: 0x7FFFF72F0000 Size: 345600
D3DCOMPILER_47.dll Base Address: 0x7FF834000000 Size: 3043328
VCRUNTIME140_1.dll Base Address: 0x7FF830CA0000 Size: 15360
VCRUNTIME140.dll Base Address: 0x7FF830CB0000 Size: 65024
Dumping registers:
RAX: 0x5F00630073005C
RCX: 0x6E0069006F0070
RDX: 0x73007200650074
RBX: 0x7FFF922A0E18
RSI: 0xA94280E440
RDI: 0x19930520
RSP: 0xA94280E2D0
RBP: 0xA94280E510
R8:  0x0
R9:  0x0
R10: 0x0
R11: 0x0
R12: 0x7FFF921B9630
R13: 0x7FFF921B9670
R14: 0x0
R15: 0x26C2BACA888
Dumping stacktrace:
[0]	KERNELBASE.dll RaiseException
[1]	VCRUNTIME140.dll CxxThrowException
[2]	YimMenu(53).dll+0x64345F 0x7FFF91E8345F
[3]	YimMenu(53).dll+0x637710 0x7FFF91E77710
[4]	YimMenu(53).dll+0x63849D 0x7FFF91E7849D
[5]	YimMenu(53).dll+0x636C11 0x7FFF91E76C11
[6]	KERNEL32.DLL BaseThreadInitThunk
[7]	ntdll.dll RtlUserThreadStartFailed to find some patterns for Social Club

--------End of exception--------

..

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Update your YimMenu.dll, this has been solved in #2727.
