### ISSUE TITLE
[Bug]: Crash Problem

### ISSUE THREAD

**Issue by BlueVapor42** [Yimura/YimMenu#2735]
### Describe the bug

I been using the Xenos to inject the Yimmenu. Even since today it been crashing alot lately. I tried updating the Xenos, and replacing the .dll. None of the methods works

### Steps To Reproduce

1. add .dll
2. Process GTAV.exe
3. Inject and crash

### Expected Behavior

Crash the game and shut it down

### Logs and/or screenshots

```
<paste your logs here>
```
[cout.log](https://github.com/YimMenu/YimMenu/files/14350750/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
For the million babillionth time, you're on an old DLL, solved in #2729.
