### ISSUE TITLE
[Bug]: Request Model Bypass

### ISSUE THREAD

**Issue by YimMenuTheBest** [Yimura/YimMenu#2739]
### Describe the bug

Something broke or was not tested enough since both the vehicle xml, the map xml and an anim system with props that I am making to implement it in yimmenu stopped working when implementing this PR, the objects that need the bypass simply Now they don't charge anymore.

### Steps To Reproduce

1.- Go to online.
2.- Use xml vehicles or xml maps
3.- Objects that cannot be used without bypass will not load

### Expected Behavior

You should be able to spawn objects that need to be bypassed with world_model::spawn

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Example not working with the new implementation:
![image](https://github.com/YimMenu/YimMenu/assets/129180905/763fc198-ccf6-4e02-8b8b-02f52301c07c)

Example working before new implementation:
![image](https://github.com/YimMenu/YimMenu/assets/129180905/3cfa252c-870f-4171-974c-412fea2a753b)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Can confirm this is broken with latest nightly.

@99Anvar99 Please fix your world model spawn bypass changes whenever you can. use this JSON vehicle for testing

[Miata.json](https://github.com/YimMenu/YimMenu/files/14352581/Miata.json)

The car should have a maze bank model attached to it (not visible when you are inside it, only when you have a bit of distance from it

**Comment by 99Anvar99** [comment]
> Can confirm this is broken with latest nightly.
> 
> @99Anvar99 Please fix your world model spawn bypass changes whenever you can. use this JSON vehicle for testing
> 
> [Miata.json](https://github.com/YimMenu/YimMenu/files/14352581/Miata.json)
> 
> The car should have a maze bank model attached to it (not visible when you are inside it, only when you have a bit of distance from it

Understood.  Thank you for letting me know.
