### ISSUE TITLE
[Bug]: Menu Closing upon injection 

### ISSUE THREAD

**Issue by ZeroGTAV** [Yimura/YimMenu#2741]
### Describe the bug

Everytime I open The YIm Menu on GTA upon launch i inject it and the game crashes. 

### Steps To Reproduce

load the Game, Inject YimMenu

### Expected Behavior

I expected the Game to Open i inject and it worked like a few days ago.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
The 5th (or idk) issue about this today.
Please check others (including closed) issues first - and make sure you *actually* are using the latest version. (The checkmark is there for an purpose.)
See #2729.

(And: Leave this open so other people can find it easier..)

**Comment by spankymonkey** [comment]
I posted similar issue and what seems to fix the problem is and outdated yimmenu. Check for newest release
