### ISSUE TITLE
[Bug]: Chinese display problem

### ISSUE THREAD

**Issue by xiaoyou1933** [Yimura/YimMenu#2746]
### Describe the bug

The last commit was not detailed enough, I very much hope to fix this problem, this time I brought an in-game screenshot hoping to help fix it, the specific problem is that some Chinese display as? symbol

### Steps To Reproduce

1. Inject DLL files
2. Translate documents in Chinese language
2. Find bugs

### Expected Behavior

A text display problem that greatly affects reading and use, some Chinese will be displayed as? symbol

### Logs and/or screenshots

![gtabug1](https://github.com/YimMenu/YimMenu/assets/130754930/59eac412-b8e6-444a-b68f-11ed31a2878b)
![gtabug2](https://github.com/YimMenu/YimMenu/assets/130754930/0708af42-24ee-40e4-8600-c0af0c24951e)
![gtabug3](https://github.com/YimMenu/YimMenu/assets/130754930/0a3c8a50-042a-4382-9b89-c216e586cfa1)
![gtabug4](https://github.com/YimMenu/YimMenu/assets/130754930/590c7930-9356-4568-9df0-a0d660f692bd)

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I am confused, I see no question marks in the screenshot. Am I missing something? Is there something lost in translation here? Maybe @sch-lda can help.

**Comment by Yimura** [comment]
This should have been fixed with #2738, the DLL for it isn't available yet.
