### ISSUE TITLE
[Bug]: GTA crash after injection

### ISSUE THREAD

**Issue by Manuee02** [Yimura/YimMenu#2759]
### Describe the bug

When i inject YimMenu.dll (latest version) with xenos in GTAV the game crashes with a command prompt, my city recently had a blackout, after i turned the pc on again the cheat wasnt working anymore.

### Steps To Reproduce

1. Open GTAV
2. Open Xenos.exe
3. Add "YimMenu.dll" to Xenos
4. Press "Inject"
5. Game freezes then crashes and for a fraction of a second it opens a prompt with the log i uploaded

### Expected Behavior

1. Open GTAV
2. Open Xenos.exe
3. Add "YimMenu.dll" to Xenos
4. Press "Inject"
5. YimMenu GUI appears in-game and works perfectly fine

### Logs and/or screenshots

[19:23:58.3630920][INFO/main.cpp:159] Yim's Menu Initializing
[19:23:58.3631073][INFO/main.cpp:160] Git Info
	Branch:	master
	Hash:	4e294162fbed6bc5674b4795b8d133092badc0aa
	Date:	Mon Feb 19 11:37:00 2024
[19:23:58.3631780][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[19:23:58.3644385][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[19:23:58.3646568][INFO/main.cpp:180] Thread pool initialized.
[19:23:58.3665253][INFO/main.cpp:183] Settings Loaded.
[19:23:58.3665278][DEBUG/thread_pool.cpp:96] Thread 18700 executing settings.cpp:12
[19:23:58.3666505][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[19:23:58.3666547][INFO/pointers.cpp:1812] Loading pointers instance from cache
[19:23:58.3666559][INFO/pointers.cpp:1821] Pointers cache: Loading 215 fields from the cache
[19:23:58.3666606][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[19:23:58.3671622][INFO/batch.hpp:106] Found 'SGPA' GTA5.exe+0x1C1F48
[19:23:58.3676062][FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3221227278
Dumping modules:
GTA5.exe Base Address: 0x7FF6D91A0000 Size: 67215872
ntdll.dll Base Address: 0x7FFFD2B70000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FFFD1060000 Size: 528384
KERNELBASE.dll Base Address: 0x7FFFD0320000 Size: 1638400
USER32.dll Base Address: 0x7FFFD2860000 Size: 610304
win32u.dll Base Address: 0x7FFFCFEB0000 Size: 49152
GDI32.dll Base Address: 0x7FFFD0950000 Size: 57344
gdi32full.dll Base Address: 0x7FFFD01D0000 Size: 675840
msvcp_win.dll Base Address: 0x7FFFD0000000 Size: 335872
ucrtbase.dll Base Address: 0x7FFFCFEE0000 Size: 798720
PSAPI.DLL Base Address: 0x7FFFD2450000 Size: 4096
WS2_32.dll Base Address: 0x7FFFD27E0000 Size: 290816
RPCRT4.dll Base Address: 0x7FFFD2A10000 Size: 880640
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFF6C450000 Size: 96256
VERSION.dll Base Address: 0x7FFFC71A0000 Size: 12288
CRYPT32.dll Base Address: 0x7FFFD06D0000 Size: 1134592
msvcrt.dll Base Address: 0x7FFFD0D90000 Size: 507904
DSOUND.dll Base Address: 0x7FFFB6250000 Size: 491520
WINTRUST.dll Base Address: 0x7FFFD0160000 Size: 307200
advapi32.dll Base Address: 0x7FFFD2720000 Size: 442368
IMM32.dll Base Address: 0x7FFFD2540000 Size: 126976
bink2w64.dll Base Address: 0x7FFFBCFE0000 Size: 307712
sechost.dll Base Address: 0x7FFFD0B30000 Size: 458752
bcrypt.dll Base Address: 0x7FFFD02F0000 Size: 110592
ole32.dll Base Address: 0x7FFFD2580000 Size: 909312
SHLWAPI.dll Base Address: 0x7FFFD1130000 Size: 212992
combase.dll Base Address: 0x7FFFD11B0000 Size: 2539520
SHELL32.dll Base Address: 0x7FFFD1710000 Size: 6852608
WININET.dll Base Address: 0x7FFFBC3F0000 Size: 2113536
WINMM.dll Base Address: 0x7FFFC7160000 Size: 114688
OLEAUT32.dll Base Address: 0x7FFFD2460000 Size: 647168
MF.dll Base Address: 0x7FFFC3320000 Size: 372736
shcore.dll Base Address: 0x7FFFD0A30000 Size: 684032
MFPlat.DLL Base Address: 0x7FFFB6EB0000 Size: 1503232
msdmo.dll Base Address: 0x7FFFBB0A0000 Size: 16384
MFReadWrite.dll Base Address: 0x7FFF87CE0000 Size: 995328
PROPSYS.dll Base Address: 0x7FFFCB090000 Size: 692224
ResampleDmo.DLL Base Address: 0x7FFF7C560000 Size: 503808
WTSAPI32.dll Base Address: 0x7FFFCECA0000 Size: 40960
d3d9.dll Base Address: 0x7FFF87B30000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFF5DB90000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFFCA600000 Size: 48128
DINPUT8.dll Base Address: 0x7FFF7C130000 Size: 176128
IPHLPAPI.DLL Base Address: 0x7FFFCE970000 Size: 122880
powrprof.dll Base Address: 0x7FFFCFCD0000 Size: 77824
d3dx9_43.dll Base Address: 0x7FFF5D920000 Size: 2280960
winmmbase.dll Base Address: 0x7FFFAAB50000 Size: 102400
cfgmgr32.dll Base Address: 0x7FFFCFB20000 Size: 221184
dwmapi.dll Base Address: 0x7FFFCD680000 Size: 90112
OPENGL32.dll Base Address: 0x7FFF7DF40000 Size: 798720
dxcore.dll Base Address: 0x7FFFCD510000 Size: 139264
GLU32.dll Base Address: 0x7FFF7DDB0000 Size: 126976
XINPUT1_3.dll Base Address: 0x550000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFFD1F70000 Size: 913408
MFCORE.DLL Base Address: 0x7FFF73070000 Size: 3022848
UMPDC.dll Base Address: 0x7FFFCFBB0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFFCEEF0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFFD0840000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFFC2E30000 Size: 102400
MSASN1.dll Base Address: 0x7FFFCF620000 Size: 36864
inputhost.dll Base Address: 0x7FFFB81A0000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FFFCCE90000 Size: 864256
CRYPTBASE.DLL Base Address: 0x7FFFCF5E0000 Size: 12288
sdk_legacy_led_x64.dll Base Address: 0x7FFF5CC40000 Size: 2650112
MSVCP140.dll Base Address: 0x7FFFAACF0000 Size: 343040
VCRUNTIME140.dll Base Address: 0x7FFFAAD80000 Size: 64000
VCRUNTIME140_1.dll Base Address: 0x7FFFAA9C0000 Size: 14848
CRYPTSP.dll Base Address: 0x7FFFCF5C0000 Size: 57344
rsaenh.dll Base Address: 0x7FFFCEE50000 Size: 147456
mswsock.dll Base Address: 0x7FFFCF370000 Size: 331776
windows.storage.dll Base Address: 0x7FFFCDE10000 Size: 7032832
wintypes.dll Base Address: 0x7FFFCDCD0000 Size: 544768
dbghelp.dll Base Address: 0x7FFFC8FC0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FFFC18A0000 Size: 131072
d3d12.dll Base Address: 0x7FFF7DCD0000 Size: 102400
uxtheme.dll Base Address: 0x7FFFCD3D0000 Size: 425984
clbcatq.dll Base Address: 0x7FFFD0BE0000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFB94D0000 Size: 253952
d3d11.dll Base Address: 0x7FFFCBFB0000 Size: 1867776
WMICLNT.dll Base Address: 0x7FFFCAD80000 Size: 32768
dxgi.dll Base Address: 0x7FFFCD550000 Size: 651264
DEVOBJ.dll Base Address: 0x7FFFCFAF0000 Size: 110592
wbemprox.dll Base Address: 0x7FFFC1380000 Size: 28672
wbemcomn.dll Base Address: 0x7FFFC2710000 Size: 311296
wbemsvc.dll Base Address: 0x7FFFC1AF0000 Size: 8192
fastprox.dll Base Address: 0x7FFFC1B10000 Size: 708608
amsi.dll Base Address: 0x7FFFC16F0000 Size: 57344
USERENV.dll Base Address: 0x7FFFCF460000 Size: 102400
profapi.dll Base Address: 0x7FFFCFDE0000 Size: 90112
MpOav.dll Base Address: 0x7FFFC1670000 Size: 204800
directxdatabasehelper.dll Base Address: 0x7FFFCA380000 Size: 196608
D3D10_1.DLL Base Address: 0x7FFFBD9F0000 Size: 147456
d3d10_1core.dll Base Address: 0x7FFFCD1D0000 Size: 12288
apphelp.dll Base Address: 0x7FFFCD260000 Size: 335872
MSCTF.dll Base Address: 0x7FFFD0F00000 Size: 1077248
textinputframework.dll Base Address: 0x7FFFBD560000 Size: 1015808
WINSTA.dll Base Address: 0x7FFFCF8A0000 Size: 229376
aticfx64.dll Base Address: 0x7FFFC71B0000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFFC6850000 Size: 190464
atidxx64.dll Base Address: 0x7FFFC48B0000 Size: 11699712
amdihk64.dll Base Address: 0x7FFFC45B0000 Size: 117248
HID.DLL Base Address: 0x7FFFCE710000 Size: 24576
MMDevApi.dll Base Address: 0x7FFFC4620000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFB61C0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFFC3A90000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FFFCD9C0000 Size: 36864
Windows.UI.dll Base Address: 0x7FFFC11C0000 Size: 966656
avrt.dll Base Address: 0x7FFFCA6E0000 Size: 8192
napinsp.dll Base Address: 0x7FFFB4950000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFFAF670000 Size: 69632
DNSAPI.dll Base Address: 0x7FFFCE9E0000 Size: 737280
NSI.dll Base Address: 0x7FFFD1190000 Size: 8192
winrnr.dll Base Address: 0x7FFF98370000 Size: 32768
wshbth.dll Base Address: 0x7FFFBA8B0000 Size: 45056
nlansp_c.dll Base Address: 0x7FFFCD130000 Size: 81920
fwpuclnt.dll Base Address: 0x7FFFC8F30000 Size: 294912
rasadhlp.dll Base Address: 0x7FFFB4970000 Size: 8192
imagehlp.dll Base Address: 0x7FFFD0E40000 Size: 49152
gpapi.dll Base Address: 0x7FFFCF400000 Size: 77824
cryptnet.dll Base Address: 0x7FFFC0D40000 Size: 139264
WINNSI.DLL Base Address: 0x7FFFCD4F0000 Size: 16384
SspiCli.dll Base Address: 0x7FFFCF150000 Size: 126976
DPAPI.dll Base Address: 0x7FFFCFB90000 Size: 8192
socialclub.dll Base Address: 0x7FFF7F040000 Size: 2599424
chrome_elf.dll Base Address: 0x7FFF7EEF0000 Size: 901120
libcef.dll Base Address: 0x7FFF43AC0000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFFD0C90000 Size: 778240
COMCTL32.dll Base Address: 0x7FFFA5580000 Size: 573440
UIAutomationCore.DLL Base Address: 0x7FFFB72A0000 Size: 3063808
OLEACC.dll Base Address: 0x7FFFB8810000 Size: 274432
NETAPI32.dll Base Address: 0x7FFFB58C0000 Size: 49152
Secur32.dll Base Address: 0x7FFFCECC0000 Size: 12288
WINHTTP.dll Base Address: 0x7FFFCA4C0000 Size: 987136
DWrite.dll Base Address: 0x7FFFCBD30000 Size: 1654784
WINSPOOL.DRV Base Address: 0x7FFFA5E50000 Size: 405504
ncrypt.dll Base Address: 0x7FFFCF780000 Size: 114688
USP10.dll Base Address: 0x7FFFBD380000 Size: 4096
dxva2.dll Base Address: 0x7FFF99930000 Size: 102400
urlmon.dll Base Address: 0x7FFFBA900000 Size: 1298432
CRYPTUI.dll Base Address: 0x7FFF7EA20000 Size: 278528
wevtapi.dll Base Address: 0x7FFFCA300000 Size: 245760
dhcpcsvc.DLL Base Address: 0x7FFFCA460000 Size: 69632
credui.dll Base Address: 0x7FFFB25E0000 Size: 65536
ESENT.dll Base Address: 0x7FFFB77F0000 Size: 3145728
iertutil.dll Base Address: 0x7FFFBF920000 Size: 557056
srvcli.dll Base Address: 0x7FFFBA8D0000 Size: 57344
netutils.dll Base Address: 0x7FFFCE960000 Size: 20480
DSROLE.DLL Base Address: 0x7FFFCEBA0000 Size: 8192
WKSCLI.DLL Base Address: 0x7FFFCA2E0000 Size: 49152
SAMCLI.DLL Base Address: 0x7FFFC1E80000 Size: 61440
NTASN1.dll Base Address: 0x7FFFCF740000 Size: 69632
FirewallAPI.dll Base Address: 0x7FFFCE850000 Size: 385024
fwbase.dll Base Address: 0x7FFFCE7C0000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FFFB02C0000 Size: 245760
wdmaud.drv Base Address: 0x7FFFAC590000 Size: 200704
ksuser.dll Base Address: 0x7FFFBBA90000 Size: 8192
msacm32.drv Base Address: 0x7FFFB70E0000 Size: 20480
MSACM32.dll Base Address: 0x7FFFB70C0000 Size: 77824
midimap.dll Base Address: 0x7FFFB5910000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FFFBC8F0000 Size: 45056
MSVCP140_2.dll Base Address: 0x7FFF87F90000 Size: 126976
D3DCOMPILER_47.dll Base Address: 0x7FFFCB790000 Size: 3043328
winbrand.dll Base Address: 0x7FFFB1140000 Size: 180224
Dumping registers:
RAX: 0x7FFFD2BAD1AA
RCX: 0x60007
RDX: 0x20
RBX: 0xFFFFFFFFC0000135
RSI: 0x55BFFDA8
RDI: 0x1
RSP: 0x55BFFB40
RBP: 0x55BFFBE9
R8:  0x404500
R9:  0x6
R10: 0x7FFFD2BAD1AA
R11: 0x0
R12: 0xA28981F0
R13: 0x0
R14: 0xA28981B0
R15: 0x0
Dumping stacktrace:
[0]	ntdll.dll EtwLogTraceEvent
[1]	ntdll.dll RtlClearThreadWorkOnBehalfTicket
[2]	KERNEL32.DLL BaseThreadInitThunk
[3]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[19:23:58.3684649][FATAL/exception_handler.cpp:42] UNKNOWN_EXCEPTION: CODE: 3221227278
Dumping modules:
GTA5.exe Base Address: 0x7FF6D91A0000 Size: 67215872
ntdll.dll Base Address: 0x7FFFD2B70000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FFFD1060000 Size: 528384
KERNELBASE.dll Base Address: 0x7FFFD0320000 Size: 1638400
USER32.dll Base Address: 0x7FFFD2860000 Size: 610304
win32u.dll Base Address: 0x7FFFCFEB0000 Size: 49152
GDI32.dll Base Address: 0x7FFFD0950000 Size: 57344
gdi32full.dll Base Address: 0x7FFFD01D0000 Size: 675840
msvcp_win.dll Base Address: 0x7FFFD0000000 Size: 335872
ucrtbase.dll Base Address: 0x7FFFCFEE0000 Size: 798720
PSAPI.DLL Base Address: 0x7FFFD2450000 Size: 4096
WS2_32.dll Base Address: 0x7FFFD27E0000 Size: 290816
RPCRT4.dll Base Address: 0x7FFFD2A10000 Size: 880640
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFF6C450000 Size: 96256
VERSION.dll Base Address: 0x7FFFC71A0000 Size: 12288
CRYPT32.dll Base Address: 0x7FFFD06D0000 Size: 1134592
msvcrt.dll Base Address: 0x7FFFD0D90000 Size: 507904
DSOUND.dll Base Address: 0x7FFFB6250000 Size: 491520
WINTRUST.dll Base Address: 0x7FFFD0160000 Size: 307200
advapi32.dll Base Address: 0x7FFFD2720000 Size: 442368
IMM32.dll Base Address: 0x7FFFD2540000 Size: 126976
bink2w64.dll Base Address: 0x7FFFBCFE0000 Size: 307712
sechost.dll Base Address: 0x7FFFD0B30000 Size: 458752
bcrypt.dll Base Address: 0x7FFFD02F0000 Size: 110592
ole32.dll Base Address: 0x7FFFD2580000 Size: 909312
SHLWAPI.dll Base Address: 0x7FFFD1130000 Size: 212992
combase.dll Base Address: 0x7FFFD11B0000 Size: 2539520
SHELL32.dll Base Address: 0x7FFFD1710000 Size: 6852608
WININET.dll Base Address: 0x7FFFBC3F0000 Size: 2113536
WINMM.dll Base Address: 0x7FFFC7160000 Size: 114688
OLEAUT32.dll Base Address: 0x7FFFD2460000 Size: 647168
MF.dll Base Address: 0x7FFFC3320000 Size: 372736
shcore.dll Base Address: 0x7FFFD0A30000 Size: 684032
MFPlat.DLL Base Address: 0x7FFFB6EB0000 Size: 1503232
msdmo.dll Base Address: 0x7FFFBB0A0000 Size: 16384
MFReadWrite.dll Base Address: 0x7FFF87CE0000 Size: 995328
PROPSYS.dll Base Address: 0x7FFFCB090000 Size: 692224
ResampleDmo.DLL Base Address: 0x7FFF7C560000 Size: 503808
WTSAPI32.dll Base Address: 0x7FFFCECA0000 Size: 40960
d3d9.dll Base Address: 0x7FFF87B30000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFF5DB90000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFFCA600000 Size: 48128
DINPUT8.dll Base Address: 0x7FFF7C130000 Size: 176128
IPHLPAPI.DLL Base Address: 0x7FFFCE970000 Size: 122880
powrprof.dll Base Address: 0x7FFFCFCD0000 Size: 77824
d3dx9_43.dll Base Address: 0x7FFF5D920000 Size: 2280960
winmmbase.dll Base Address: 0x7FFFAAB50000 Size: 102400
cfgmgr32.dll Base Address: 0x7FFFCFB20000 Size: 221184
dwmapi.dll Base Address: 0x7FFFCD680000 Size: 90112
OPENGL32.dll Base Address: 0x7FFF7DF40000 Size: 798720
dxcore.dll Base Address: 0x7FFFCD510000 Size: 139264
GLU32.dll Base Address: 0x7FFF7DDB0000 Size: 126976
XINPUT1_3.dll Base Address: 0x550000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFFD1F70000 Size: 913408
MFCORE.DLL Base Address: 0x7FFF73070000 Size: 3022848
UMPDC.dll Base Address: 0x7FFFCFBB0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFFCEEF0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFFD0840000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFFC2E30000 Size: 102400
MSASN1.dll Base Address: 0x7FFFCF620000 Size: 36864
inputhost.dll Base Address: 0x7FFFB81A0000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FFFCCE90000 Size: 864256
CRYPTBASE.DLL Base Address: 0x7FFFCF5E0000 Size: 12288
sdk_legacy_led_x64.dll Base Address: 0x7FFF5CC40000 Size: 2650112
MSVCP140.dll Base Address: 0x7FFFAACF0000 Size: 343040
VCRUNTIME140.dll Base Address: 0x7FFFAAD80000 Size: 64000
VCRUNTIME140_1.dll Base Address: 0x7FFFAA9C0000 Size: 14848
CRYPTSP.dll Base Address: 0x7FFFCF5C0000 Size: 57344
rsaenh.dll Base Address: 0x7FFFCEE50000 Size: 147456
mswsock.dll Base Address: 0x7FFFCF370000 Size: 331776
windows.storage.dll Base Address: 0x7FFFCDE10000 Size: 7032832
wintypes.dll Base Address: 0x7FFFCDCD0000 Size: 544768
dbghelp.dll Base Address: 0x7FFFC8FC0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FFFC18A0000 Size: 131072
d3d12.dll Base Address: 0x7FFF7DCD0000 Size: 102400
uxtheme.dll Base Address: 0x7FFFCD3D0000 Size: 425984
clbcatq.dll Base Address: 0x7FFFD0BE0000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFB94D0000 Size: 253952
d3d11.dll Base Address: 0x7FFFCBFB0000 Size: 1867776
WMICLNT.dll Base Address: 0x7FFFCAD80000 Size: 32768
dxgi.dll Base Address: 0x7FFFCD550000 Size: 651264
DEVOBJ.dll Base Address: 0x7FFFCFAF0000 Size: 110592
wbemprox.dll Base Address: 0x7FFFC1380000 Size: 28672
wbemcomn.dll Base Address: 0x7FFFC2710000 Size: 311296
wbemsvc.dll Base Address: 0x7FFFC1AF0000 Size: 8192
fastprox.dll Base Address: 0x7FFFC1B10000 Size: 708608
amsi.dll Base Address: 0x7FFFC16F0000 Size: 57344
USERENV.dll Base Address: 0x7FFFCF460000 Size: 102400
profapi.dll Base Address: 0x7FFFCFDE0000 Size: 90112
MpOav.dll Base Address: 0x7FFFC1670000 Size: 204800
directxdatabasehelper.dll Base Address: 0x7FFFCA380000 Size: 196608
D3D10_1.DLL Base Address: 0x7FFFBD9F0000 Size: 147456
d3d10_1core.dll Base Address: 0x7FFFCD1D0000 Size: 12288
apphelp.dll Base Address: 0x7FFFCD260000 Size: 335872
MSCTF.dll Base Address: 0x7FFFD0F00000 Size: 1077248
textinputframework.dll Base Address: 0x7FFFBD560000 Size: 1015808
WINSTA.dll Base Address: 0x7FFFCF8A0000 Size: 229376
aticfx64.dll Base Address: 0x7FFFC71B0000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFFC6850000 Size: 190464
atidxx64.dll Base Address: 0x7FFFC48B0000 Size: 11699712
amdihk64.dll Base Address: 0x7FFFC45B0000 Size: 117248
HID.DLL Base Address: 0x7FFFCE710000 Size: 24576
MMDevApi.dll Base Address: 0x7FFFC4620000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFB61C0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFFC3A90000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FFFCD9C0000 Size: 36864
Windows.UI.dll Base Address: 0x7FFFC11C0000 Size: 966656
avrt.dll Base Address: 0x7FFFCA6E0000 Size: 8192
napinsp.dll Base Address: 0x7FFFB4950000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFFAF670000 Size: 69632
DNSAPI.dll Base Address: 0x7FFFCE9E0000 Size: 737280
NSI.dll Base Address: 0x7FFFD1190000 Size: 8192
winrnr.dll Base Address: 0x7FFF98370000 Size: 32768
wshbth.dll Base Address: 0x7FFFBA8B0000 Size: 45056
nlansp_c.dll Base Address: 0x7FFFCD130000 Size: 81920
fwpuclnt.dll Base Address: 0x7FFFC8F30000 Size: 294912
rasadhlp.dll Base Address: 0x7FFFB4970000 Size: 8192
imagehlp.dll Base Address: 0x7FFFD0E40000 Size: 49152
gpapi.dll Base Address: 0x7FFFCF400000 Size: 77824
cryptnet.dll Base Address: 0x7FFFC0D40000 Size: 139264
WINNSI.DLL Base Address: 0x7FFFCD4F0000 Size: 16384
SspiCli.dll Base Address: 0x7FFFCF150000 Size: 126976
DPAPI.dll Base Address: 0x7FFFCFB90000 Size: 8192
socialclub.dll Base Address: 0x7FFF7F040000 Size: 2599424
chrome_elf.dll Base Address: 0x7FFF7EEF0000 Size: 901120
libcef.dll Base Address: 0x7FFF43AC0000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFFD0C90000 Size: 778240
COMCTL32.dll Base Address: 0x7FFFA5580000 Size: 573440
UIAutomationCore.DLL Base Address: 0x7FFFB72A0000 Size: 3063808
OLEACC.dll Base Address: 0x7FFFB8810000 Size: 274432
NETAPI32.dll Base Address: 0x7FFFB58C0000 Size: 49152
Secur32.dll Base Address: 0x7FFFCECC0000 Size: 12288
WINHTTP.dll Base Address: 0x7FFFCA4C0000 Size: 987136
DWrite.dll Base Address: 0x7FFFCBD30000 Size: 1654784
WINSPOOL.DRV Base Address: 0x7FFFA5E50000 Size: 405504
ncrypt.dll Base Address: 0x7FFFCF780000 Size: 114688
USP10.dll Base Address: 0x7FFFBD380000 Size: 4096
dxva2.dll Base Address: 0x7FFF99930000 Size: 102400
urlmon.dll Base Address: 0x7FFFBA900000 Size: 1298432
CRYPTUI.dll Base Address: 0x7FFF7EA20000 Size: 278528
wevtapi.dll Base Address: 0x7FFFCA300000 Size: 245760
dhcpcsvc.DLL Base Address: 0x7FFFCA460000 Size: 69632
credui.dll Base Address: 0x7FFFB25E0000 Size: 65536
ESENT.dll Base Address: 0x7FFFB77F0000 Size: 3145728
iertutil.dll Base Address: 0x7FFFBF920000 Size: 557056
srvcli.dll Base Address: 0x7FFFBA8D0000 Size: 57344
netutils.dll Base Address: 0x7FFFCE960000 Size: 20480
DSROLE.DLL Base Address: 0x7FFFCEBA0000 Size: 8192
WKSCLI.DLL Base Address: 0x7FFFCA2E0000 Size: 49152
SAMCLI.DLL Base Address: 0x7FFFC1E80000 Size: 61440
NTASN1.dll Base Address: 0x7FFFCF740000 Size: 69632
FirewallAPI.dll Base Address: 0x7FFFCE850000 Size: 385024
fwbase.dll Base Address: 0x7FFFCE7C0000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FFFB02C0000 Size: 245760
wdmaud.drv Base Address: 0x7FFFAC590000 Size: 200704
ksuser.dll Base Address: 0x7FFFBBA90000 Size: 8192
msacm32.drv Base Address: 0x7FFFB70E0000 Size: 20480
MSACM32.dll Base Address: 0x7FFFB70C0000 Size: 77824
midimap.dll Base Address: 0x7FFFB5910000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FFFBC8F0000 Size: 45056
MSVCP140_2.dll Base Address: 0x7FFF87F90000 Size: 126976
D3DCOMPILER_47.dll Base Address: 0x7FFFCB790000 Size: 3043328
winbrand.dll Base Address: 0x7FFFB1140000 Size: 180224
Dumping registers:
RAX: 0x7FFFD2BAD1AA
RCX: 0x60007
RDX: 0x20
RBX: 0xFFFFFFFFC0000135
RSI: 0x55BFFDA8
RDI: 0x1
RSP: 0x55BFFB40
RBP: 0x55BFFBE9
R8:  0x404500
R9:  0x6
R10: 0x7FFFD2BAD1AA
R11: 0x0
R12: 0xA28981F0
R13: 0x0
R14: 0xA28981B0
R15: 0x0
Dumping stacktrace:
[0]	ntdll.dll EtwLogTraceEvent
[1]	ntdll.dll RtlClearThreadWorkOnBehalfTicket
[2]	KERNEL32.DLL BaseThreadInitThunk
[3]	ntdll.dll RtlUserThreadStart
--------End of exception--------
UNKNOWN_EXCEPTION: CODE: 3221227278
Dumping registers:
RAX: 0x7FFFD2BAD1AA
RCX: 0x16001C
RDX: 0x20
RBX: 0xFFFFFFFFC0000135
RSI: 0xA16FFDA8
RDI: 0x1
RSP: 0xA16FFB40
RBP: 0xA16FFBE9
R8:  0x404800
R9:  0x0
R10: 0x7FFFD2BAD1AA
R11: 0x0
R12: 0xA28983F0
R13: 0x0
R14: 0xA28983B0
R15: 0x0
Dumping stacktrace:
[0]	ntdll.dll EtwLogTraceEvent
[1]	ntdll.dll RtlClearThreadWorkOnBehalfTicket
[2]	KERNEL32.DLL BaseThreadInitThunk
[3]	ntdll.dll RtlUserThreadStart
--------End of exception--------

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

Here is the video of the error i uploaded: https://youtu.be/bRwh0Oq039o

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
I hope you know what it means to check the "I've confirmed the issue exists on the latest version of YimMenu" button implies. Basically it's to make sure you've used the most recent version of YimMenu before opening an issue. From having looked at your cout.log you're behind 12 commits including the commit that fixes the issue you're reporting on....

![image](https://github.com/YimMenu/YimMenu/assets/24669514/d03b9f1b-2858-411a-87d2-e5d72489369e)

**Comment by Manuee02** [comment]
i still dont understand how to fix that can you be more clear? im not an expert at using github/coding. Thank you for your time

**Comment by Yimura** [comment]
You can download the latest version of YimMenu from the [releases section](https://github.com/YimMenu/YimMenu/releases).

Try and see if that fixes it.

**Comment by Manuee02** [comment]
thank you so much it fixed it
