### ISSUE TITLE
[Bug]: When pressing "Start LS Customs" in the "LS Customs" tab, the game does not let me get out of the vehicle after customizing it nor move it.

### ISSUE THREAD

**Issue by passionfr7it** [Yimura/YimMenu#2767]
### Describe the bug

When I try to customize any vehicle (spawned) using the inbuilt LSCM customization panel in "LS Customs" tab under Vehicle section, I am immediately stuck and cannot move my vehicle nor exit out of it. To fix it, I have to join a new session.

### Steps To Reproduce

1. Inject DLL.
2. Get into a vehicle.
3. Press Vehicle > LS Customs.
4. Press "Start LS Customs".
5. Exit.

### Expected Behavior

Won't be able to move the vehicle nor get out of it. Even if vehicle is deleted, character will be stuck and not able to move.

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14383673/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Tayipc38** [comment]
This feature has been broken since dawn of time.

**Comment by Yimura** [comment]
Feature has been removed until someone makes the time to properly fix it.

**Comment by gir489returns** [comment]
> Feature has been removed until someone makes the time to properly fix it.

It wasn't removed, we just moved it to the Debug section. It works, just, not... very well....
