### ISSUE TITLE
[Improvement]: pointer

### ISSUE THREAD

**Issue by Joker11hl** [Yimura/YimMenu#2768]
### Which feature

modest menu xenos

### Reason

it wont let me to use anywhere and the pointer keeps staying on the middle of monitor and i tried to move it, it didnt work

**Comment by sch-lda** [comment]
Change Mouse Input Method to Raw Input in GTA5 Settings

**Comment by Yimura** [comment]
Should be solved by following the instructions that sch-ida provided.
