### ISSUE TITLE
When I inject YimMenu. DLL, this prompt pops up:

### ISSUE THREAD

**Issue by lisarun** [Yimura/YimMenu#2769]
### Describe the build issues

When I inject YimMenu. DLL, this prompt pops up。I'm sure this is the latest YimMenu I pulled and the latest version I built

### Screenshots and/or Logs

![5fbdd288b6a62acb0ef1b379f2240a6](https://github.com/YimMenu/YimMenu/assets/147649364/aacdeaa6-9e9a-4821-a759-6094654c9d60)

```
I'm sure this is the latest YimMenu I pulled and the latest version I built



### IDE/Compiler

Visual Studio 2022

### Additional context

_No response_

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by Yimura** [comment]
Build in release mode

**Comment by lisarun** [comment]
OK, thank you for your clarification, big brother! Thank you very much, big brother. You are really a good person
