### ISSUE TITLE
[Bug]: Game crashes when calling natives with 'Any*' parameter

### ISSUE THREAD

**Issue by ShinyWasabi** [Yimura/YimMenu#2774]
### Describe the bug

Calling a Lua native with a parameter of type `Any*` results in a game crash.

### Steps To Reproduce

1. Try to call a native with an `Any*` parameter in a Lua script.

### Expected Behavior

No crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14393332/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

This is my test code:
```lua
function GET_INITIAL_COORD_FROM_UGC(file, dict1, dict2)
    if not DATAFILE.DATAFILE_LOAD_OFFLINE_UGC(file, 0) then
        log.warning("Could not load UGC " .. file)
        return RE.VECTOR_ZERO
    end

    local uVar0 = DATAFILE.DATAFILE_GET_FILE_DICT(0)
    local uVar1 = DATAFILE.DATADICT_GET_DICT(uVar0, "mission")
    local iVar29 = DATAFILE.DATADICT_GET_DICT(uVar1, dict1)
    local iVar30 = DATAFILE.DATADICT_GET_DICT(iVar29, dict2)
    local uVar37 = DATAFILE.DATADICT_GET_ARRAY(iVar30, "pos")
    local coord = DATAFILE.DATAARRAY_GET_VECTOR(uVar37, 0)

    DATAFILE.DATAFILE_DELETE(0)

    return coord
end
-- ...
if ImGui.Button("TEST") then
    script.run_in_fiber(function()
        local coords = GET_INITIAL_COORD_FROM_UGC("RE_Store_Robbery_1", "pd", "pds")
        log.info(string.format("Val: %.3f, %.3f, %.3f", coords.x, coords.y, coords.z))
    end)
end
```

I have also tested non-datafile natives such as `GET_ALL_VEHICLES(Any* vehsStruct)` etc., they resulted the same behaviour.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/d106af0e-ac65-44aa-b2fc-b18f07447b21)

@xiaoxiao921 Is this the proper implementation for this? Lua can only do PBV yet you're taking the value from the sol stack and passing a reference of it to the native, that seems wrong. We might have to write a helper class for this like Vector3.

**Comment by xiaoxiao921** [comment]
It's not the proper impl, just never bothered to handle these cases are those native are basically never used

There is two behaviours and I just prefered to have the generator handle the most usual ones, which you can see in `LUA_NATIVE_VEHICLE_DELETE_VEHICLE`, this native works just fine with how it is implemented currently

**Comment by gir489returns** [comment]
> There is two behaviours and I just prefered to have the generator handle the most usual ones, which you can see in `LUA_NATIVE_VEHICLE_DELETE_VEHICLE`, this native works just fine with how it is implemented currently

The vehicle gets deleted, but I don't think it is proper. The only reason it needs a reference to it, is the natives writes null to it. However, my guess is that the native has some kind of sanity check seeing that potentially people could just pass the value of the vehicle ID, and since it doesn't need to write null back to it, it's just there because Rockstar, it probably deletes the vehicle.

We should reverse the natives he's trying to call and see why this one fails but delete works.

**Comment by xiaoxiao921** [comment]
Funnily enough looks like I was already well aware of it, completly forgot about it https://github.com/YimMenu/YimMenu/blob/9855e46dd164df6c00d5f6b212ef5084e68c7785/scripts/natives_gen.py#L53
