### ISSUE TITLE
[Bug]: context menu enable stopped working

### ISSUE THREAD

**Issue by MoJoestar** [Yimura/YimMenu#2776]
### Describe the bug

it only worked for about half an hour then i got offline, since then it stopped working , i have since restarted the game and my laptop many times and turning it off/on doesn't do anything

### Steps To Reproduce

![Screenshot 2024-02-25 112834](https://github.com/YimMenu/YimMenu/assets/112313884/a3307ad7-32af-4592-b825-33b5ec28b967)

### Expected Behavior

when enabled it should show a box around the entities i choose and i can control it

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Hey there, the context menu has a button to completely disable which is what you're seeing in the UI, there's also a key to toggle the feature while playing. Currently it's hard coded to the button you use to duck in a vehicle (it works regardless of if you're in a vehicle or not).

**Comment by lonelybud** [comment]
yeah context menu when enabled need another key pressed to actually open it. It is the key which you press when you duck in vehicle. Usually X key on keyboard.

**Comment by MoJoestar** [comment]
ok i just tried it and it worked, thanks guys
