### ISSUE TITLE
[Request]: Add XML outfits? 

### ISSUE THREAD

**Issue by Aftab-Fury** [Yimura/YimMenu#2781]
### Solution

Need for XML outfits as json are not readily available 

### Reason

Feature

**Comment by gir489returns** [comment]
The developer who was responsible for the XML parser for maps and vehicles no longer is feature-active. I'm sure as hell not going to work on this as I am a strong believer in K:V data as K:V:K can suck me.

That being said, I'm not totally unsympathetic to your cause. If you would post a few XMLs here, I could write a converter for you that would change it from XML (garbage) to JSON (chad) for you.

**Comment by Aftab-Fury** [comment]
Thanks @gir489returns Really appreciate it, I have attached 2 zip with sample.

[b54e86-UltimateOutfitPackv3.zip](https://github.com/YimMenu/YimMenu/files/14406242/b54e86-UltimateOutfitPackv3.zip)

[xml_sample.zip](https://github.com/YimMenu/YimMenu/files/14406257/xml_sample.zip)

**Comment by gir489returns** [comment]
There are a lot of fields we don't persist that they do. Like type, dynamic, etc. Do you have the source code to what loads this? I could add the fields to the JSON parser, but I don't know what some of these do.

**Comment by Aftab-Fury** [comment]
> There are a lot of fields we don't persist that they do. Like type, dynamic, etc. Do you have the source code to what loads this? I could add the fields to the JSON parser, but I don't know what some of these do.

its menyoo mod, are you aware about it?

**Comment by Tayipc38** [comment]
Ive had it with xml files.

> There are a lot of fields we don't persist that they do. Like type, dynamic, etc. Do you have the source code to what loads this? I could add the fields to the JSON parser, but I don't know what some of these do.

I believe this info pertains to actual pedestrian entities, not outfits to use on the player per-se.

**Comment by gir489returns** [comment]
> Ive had it with xml files.

Same.

> I believe this info pertains to actual pedestrian entities, not outfits to use on the player per-se.

I think you are correct, as I began to inspect menyoo's parser, the amount of spaghetti code and nonsense they use was just head-spinning.

I vote we close this issue as out-of-band, as this has nothing to do for the local player, and could probably be done in Lua.

**Comment by Tayipc38** [comment]
This will not be implemented.
