### ISSUE TITLE
[Bug]: Crash bug

### ISSUE THREAD

**Issue by 69Yazo** [Yimura/YimMenu#2782]
### Describe the bug

When i inject the YimMenu.dll via Xenos64 into gta5, it shows some code it didnt showed me before and crashes my game seconds after
![image](https://github.com/YimMenu/YimMenu/assets/161340326/3217c92b-4383-4867-b612-b51b3a19aa75)

### Steps To Reproduce

1. Launch GTA V via the Rockstar Games Launcher
2. Open Xenos64 Injector
3. Add YimMenu.dll into the injector
4. Select GTA V and then Inject
5. Boom! crash

### Expected Behavior

i expected for the yim menu to work correctly

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

French

### YimMenu Language

Français (FR)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Are you sure you're injecting to the right process? Make sure that you select `GTA5.exe` in the process selector before injecting

**Comment by Nctfx** [comment]
crashes with anarchy injector aswell

**Comment by xiaoxiao921** [comment]
Closing due to the issue being invalid. Send a proper cout.log file in your issue so that we can actually help you. You can  find it in %appdata%/YimMenu folder

**Comment by 69Yazo** [comment]
I got the solution guys dw i just had to update the yim menu im so fcking dumb
