### ISSUE TITLE
[Request]: sending chat messages in lua

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2783]
### Problem

network.send_chat_message(msg, bool) uses true for team chat, false for all chat

requesting bool to be an int range 1, 2, 3 or string ("all", "team", "org") 

so it can be used for the entire organization youre in as well.

### Solution

problem sums it up, no rush, would just be nice to add.

### Reason

it already uses all/team, why not?

**Comment by GreySideMM** [comment]
The perceived difference between "team" and "org" does not exist within the game engine. It is only "all" and "team" as a boolean. Your game then decides whether it was team or org - and if that message was from of your team/org members and should be shown to you. -- Well, that is if I got that part right.

**Comment by Deadlineem** [comment]
> The perceived difference between "team" and "org" does not exist within the game engine. It is only "all" and "team" as a boolean. Your game then decides whether it was team or org - and if that message was from of your team/org members and should be shown to you. -- Well, that is if I got that part right.

That being the case, wouldn't setting this to true output to organization instead of team when youre in a ceo/mc?  as of current it always sends to team
