### ISSUE TITLE
[Improvement]: Add Kill Police & Kill NPC's Loop

### ISSUE THREAD

**Issue by GoldenGets** [Yimura/YimMenu#2784]
### Which feature

It would be better if there were four additional options: kill police, kill all ped loop, kill enemies loop, and kill police loop in the world>ped options.

The options are already available in the menyoo mod, but they only provide auto-kill enemies (weak or radical).

### Reason

I often run missions in GTA Online, especially heists, to help players who don't cheat. However, non-godmode players often die from police and frequently perform quick restarts.

**Comment by GreySideMM** [comment]
You can enable semi-godmode for these players. Invididually or - IIRC - there is a an option to set it for the entire session. With it they only can die from explosions.
On a note: Other Mods might block that and notify their users. YimMenu doesn't however, as I noticed just recently (or that was some odd game bug).

**Comment by xiaoxiao921** [comment]
Such features can trivially be added through lua scripts, the feature creep is quite insane in the menu already so note that nobody from the main contributor team will work on this specifically

**Comment by binded-zz** [comment]
your looking for something like https://github.com/sch-lda/SCH-LUA-YIMMENU  from sch-lda

theres a person that does a english translation  on his page 
theres is npc controls to kill burn make them fly though the air and to just delete them  some for all npc some for just attacking npcs

this is most likely the closest you will find for a script like that unless  you make your own

on at the bottom of the english page for pics  there old but its pretty much the same

**Comment by gir489returns** [comment]
I figured this was already a Lua script. Thanks binded.
