### ISSUE TITLE
[Request]: Add /Zi flag / .pdb to CI / nightly

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#2787]
### Problem

A bit annoying to having to locally compile the linked commit in cout.log issues

### Solution

zi flag in the build step will generate debug symbols in pdb file

### Reason

Allow to easily link back symbols through the .pdb file for easier debugging

**Comment by gir489returns** [comment]
I disapprove of this change. While it may seem like a good idea to have easier to read logs and what-not, the nightly builds should be release-ready builds, not debug builds. Unless we offer both a debug and release build which may also get confusing to the user, what we have no works just fine, so long as the cout log properly labels which commit hash the crash came from, if the crash even came from within YimMenu.dll.

**Comment by xiaoxiao921** [comment]
/Zi flag or not the produced dll is the exact same, the only difference is that a .pdb file is generated alongside it.

**Comment by gir489returns** [comment]
I still don't think it should, as A: adds download bloat that the user will never need, B: users might get confused at the PDB file and its purpose and C: we can always compile the commit hash if we need the PDB itself.

**Comment by xiaoxiao921** [comment]
Compiling for every nightly / hash release on my machine is annoying, since the CI already build the dll might as well have the pdb done too at the same time. The pdb don't have to be shipped in the GitHub Release Tab in the nightly tag, just done as an artifact in the CI GitHub Action output that maintainers / devs would just grab from 
![image](https://github.com/YimMenu/YimMenu/assets/837334/c6897518-4d41-4166-be75-307036dc2d42)
