### ISSUE TITLE
[Bug]: Crashing upon launching any game mode

### ISSUE THREAD

**Issue by malloc2k** [Yimura/YimMenu#2794]
### Describe the bug

When I inject with my Injector or any other, and since the last build i haven't been able to use YimMenu. 
I also asked other users and they report the crashing.

### Steps To Reproduce

1. Open GTAV
2. Inject with any injector
3. Load any game mode
4. **Crash**

### Expected Behavior

For the menu not to crash xD

### Logs and/or screenshots

```
<paste your logs here>
[cout.log](https://github.com/YimMenu/YimMenu/files/14466967/cout.log)

```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Can't reproduce from the latest nightly that the user was also using. [cout.log](https://github.com/YimMenu/YimMenu/files/14467776/cout.log)

This is clearly a case of user error, I just don't know what. Co-loading perhaps?

**Comment by malloc2k** [comment]
Well, I’ve tried it with different injectors, my injector may be the problem but I don’t think so, because it works to inject on all other games ( manual map )…
I’ll try to inject it again?
And no Co-Loading, it also always pops up a thing saying that it needs to have the single player cache ?

**Comment by Yimura** [comment]
> Well, I’ve tried it with different injectors, my injector may be the problem but I don’t think so, because it works to inject on all other games ( manual map )… I’ll try to inject it again

See that’s the problem, you’re manual mapping. Use the conventional injection method and you should be good to go.

**Comment by malloc2k** [comment]
> > Well, I’ve tried it with different injectors, my injector may be the problem but I don’t think so, because it works to inject on all other games ( manual map )… I’ll try to inject it again
> 
> See that’s the problem, you’re manual mapping. Use the conventional injection method and you should be good to go.

Ohh, gotcha, and because I’m really used to use manual map everywhere I tought that GTAV blocked LoadLibraryA like most games do xD

**Comment by malloc2k** [comment]
Once I’ve tried LLA I’ll update you on the issue.
Thanks for the support!

**Comment by Yimura** [comment]
> Ohh, gotcha, and because I’m really used to use manual map everywhere I tought that GTAV blocked LoadLibraryA like most games do xD

Yeah we should probably add the injection type to bug reports so we can see if any unsupported methods have been used.

**Comment by malloc2k** [comment]
> 
> Yeah we should probably add the injection type to bug reports so we can see if any unsupported methods have been used.

I forgot to mentio this too: I can’t compile the menu due to some “ range “ error…
When I get back home I’ll share the error with you. 
And as I said I’ll also try to use LLA :)

**Comment by malloc2k** [comment]
@Yimura I've tested with LLA and it works just fine.

Please add ManualMap as a "forbidden" injection method.

**Thanks**

**Comment by Yimura** [comment]
> @Yimura I've tested with LLA and it works just fine.
> 
> Please add ManualMap as a "forbidden" injection method.
> 
> **Thanks**

Any reason why we should consider adding that? LLA works just fine, GTA doesn't try to detect the method and we disable the AC as well so.

**Comment by malloc2k** [comment]
> > @Yimura I've tested with LLA and it works just fine.
> > Please add ManualMap as a "forbidden" injection method.
> > **Thanks**
> 
> Any reason why we should consider adding that? LLA works just fine, GTA doesn't try to detect the method and we disable the AC as well so.

I would think that would be just an extra thing to do, so users like me that normally use MM don’t come again opening more and more issues when it’s not necessary :) 
You are the owner, you decide.

**Comment by malloc2k** [comment]
Btw I’m gonna show you the compile error thst I get 
![image](https://github.com/YimMenu/YimMenu/assets/69867754/3bb9fdcd-e740-467a-b7e7-ec2312ca6e91)

And it says that constexpr is not valid there too lmao

sorry for not screenshotting 🤣🤣

**Comment by Yimura** [comment]
Make a new issue for build errors, there is some basic information we collect to better understand your problem.
