### ISSUE TITLE
[Bug]: Weapon bullets not being "shot"

### ISSUE THREAD

**Issue by malloc2k** [Yimura/YimMenu#2796]
### Describe the bug

When im using the menu after some time my weapons bullets just dont exist like the weapon makes the noise but no impact!

### Steps To Reproduce

1. Not sure what causes this

### Expected Behavior

Weapons bullets to work properly

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Related to #2701
Waiting on #2659

**Comment by Yimura** [comment]
@malloc2k do you have rapid fire enabled by any chance?

**Comment by malloc2k** [comment]
> @malloc2k do you have rapid fire enabled by any chance?

I did have it enabled but that wasnt the problem I think...

what I think was causing the problem was the custom veh weapons, IIRC when i got in and then got out they seemed to stopped working...


I think maybe a combination of features could have caused this, but for now as Im not enabling that feature i mentioned no issues xD
