### ISSUE TITLE
Player Window uses a copy of the selected player, causing the variable to become outdated when switching lobbies and sometimes causing a crash

### ISSUE THREAD

**Issue by beast177** [Yimura/YimMenu#28]
If You enter into a session and select a player, Player window pops up, but if we change the session right after that if u select any other player it will crash the game if the pervious Player window is opened from the last session.

**Comment by Yimura** [comment]
Do you happen to have any crash logs available?

**Comment by beast177** [comment]
Nothing

**Comment by Yimura** [comment]
Sure thanks, will try to see if I can replicate the issue on my end.

**Comment by Yimura** [comment]
I'm unable to crash myself, are you using your own version of YimMenu or just compiling straight from master branch.

**Comment by beast177** [comment]
Yes, m using my own version of YimMenu, I'll just check my code again

**Comment by Yimura** [comment]
Is something that you can do consistently or did it just randomly happen?

**Comment by beast177** [comment]
It just happens randomly or like right after 10-15mins in game, I saw your recent commits I'll apply those first, maybe it will fix

**Comment by Yimura** [comment]
Yep I have been able to replicate your issue, I will try and see if I can fix it.

**Comment by Yimura** [comment]
Check if https://github.com/Yimura/YimMenu/commit/bac623ed8b1e204221e9847039c4d66a91bc80ee fixes your issue.

**Comment by beast177** [comment]
Sure I'll try this

**Comment by beast177** [comment]
Playing on : **Window Mode**
The game crashes as I loaded into a session and selected myself in the Players List, I provided a File attachment 
[Sleepy.log](https://github.com/Yimura/YimMenu/files/7821237/Sleepy.log)

**Comment by Yimura** [comment]
Can you post your settings.json?

Are you doing anything with the selected player?
I've been swapping New Public Sessions and Normal Sessions and I just can't get myself to crash.

**Comment by beast177** [comment]
Are you doing anything with the selected player? 
=> Yea, I added some kicks and a crash, But besides that I haven't done anything just added Your new Commits.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Json file isn't supported I posted as txt,
[settings.txt](https://github.com/Yimura/YimMenu/files/7821946/settings.txt)

**Comment by beast177** [comment]
> Check if [bac623e](https://github.com/Yimura/YimMenu/commit/bac623ed8b1e204221e9847039c4d66a91bc80ee) fixes your issue.

I removed this, and it didn't crash. . .

**Comment by beast177** [comment]
I rechecked my code so nothing wrong there, I found this new crash, where if all players leave (or u get dsync) and if u select urself from the player list it crashes XD, ill try to get a vid for better understanding of this issue.

**Comment by Yimura** [comment]
Eh ye, well good luck with that!

**Comment by Yimura** [comment]
Should be fixed since https://github.com/Yimura/YimMenu/commit/927203b844a91b8256857424434e979210782959

If you still required to reset player related settings you can that before switching the selected player.
https://github.com/Yimura/YimMenu/blob/a8581a1f4d07d492c6f47663e58b5fd92f8f159d/BigBaseV2/src/services/player_service.cpp#L152-L155
