### ISSUE TITLE
Replay Interface pattern is wrong 

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#280]
regression introduced by this commit https://github.com/Yimura/YimMenu/commit/d1814cf55f7618a3e0a46e972632c8107f07e094

didnt check the others sigs, but this one is definitly wrong because simply pressing the keybind for the context menu will cause an instant crash

**Comment by Yimura** [comment]
The signature is fine, seems my pointer math was incorrect.

Forgot to add the mov instruction to the `.add()` call.
