### ISSUE TITLE
[Bug]: Ped Removal & Weapon Type crashes

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#2804]
### Describe the bug

Yimmenu says it blocks these when they are executed on me, however, I crash extremely hard when someone uses these, not sure why.

### Steps To Reproduce

Join a session with a modder who has these crashes.

### Expected Behavior

Not to get crashed by them?

### Logs and/or screenshots

No logs, just a screenshot.

![Screenshot_370](https://github.com/YimMenu/YimMenu/assets/24372625/92930cf5-642f-4e4b-ac76-f28999f770c4)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Duplicate of https://github.com/YimMenu/YimMenu/issues/2672

**Comment by ghost** [comment]
I have added some extra hashes that were able to crash YimMenu but elegant crash on stand is still a problem (working on patches). Maybe I should create a PR for them and have them added on the YimMenu repository too.
