### ISSUE TITLE
[Build]: Release Build on CLion

### ISSUE THREAD

**Issue by malloc2k** [Yimura/YimMenu#2805]
### Describe the build issues

Shii dont build :(
It's on release mode and it doesnt find something that is there

### Screenshots and/or Logs

```
====================[ Build | YimMenu | Release ]===============================
"C:\Program Files\JetBrains\CLion 241.12662.59\bin\cmake\win\x64\bin\cmake.exe" --build C:\Users\HWND\Desktop\C++\CLION\YimMenu\cmake-build-release --target YimMenu -j 22
ninja: fatal: ReadFile: The handle is invalid.

[1/781] Building ASM_MASM object CMakeFiles/YimMenu.dir/src/hooks/protections/sound_overload_detour_asm.asm.obj
FAILED: CMakeFiles/YimMenu.dir/src/hooks/protections/sound_overload_detour_asm.asm.obj 
ml -DCURL_STATICLIB -DNOMINMAX -DWIN32_LEAN_AND_MEAN -DYimMenu -DYimMenu_EXPORTS -D_CRT_SECURE_NO_WARNINGS -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/src -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/json-src/single_include -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/gtav_classes-src -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/imgui-src -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/minhook-src/src/hde -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/pugixml-src/src -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/minhook-src/include -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/asynclogger-src/src -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/asynclogger-src/include -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/cpr-src/include -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/cpr-build/cpr_generated_includes -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/curl-src/include -IC:/Users/HWND/Desktop/C++/CLION/YimMenu/cmake-build-release/_deps/lua-src/lua-5.4.4/include -Wa,-mbig-obj -c -Fo CMakeFiles/YimMenu.dir/src/hooks/protections/sound_overload_detour_asm.asm.obj C:/Users/HWND/Desktop/C++/CLION/YimMenu/src/hooks/protections/sound_overload_detour_asm.asm
CreateProcess failed: The system cannot find the file specified.

```

### IDE/Compiler

Other (please mention in "Additional context")

### Additional context

Clion EAP 2024.1 and 2023.3

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by Yimura** [comment]
This build issue is not one that stems inherently from YimMenu's CMake being incorrect. This seems more like an issue with CLion, CMake or some other external factor over which we haven't got any influence over.

**Comment by malloc2k** [comment]
> This build issue is not one that stems inherently from YimMenu's CMake being incorrect. This seems more like an issue with CLion, CMake or some other external factor over which we haven't got any influence over.

Why would it be CLion's fault? (just asking :P)
Does this CMake by any chance use python?

I've read online that ppl are having this error related to python?


Also would like to fix this, because CLion is a really powerful IDE and i could help out by forking if I can get this to work :P 

thanks in advance, Yimura :)

**Comment by Yimura** [comment]
I get that it's a really powerful IDE for C++ deving, however I haven't used it for YimMenu or any other projects before.

Looking at the crash logs there isn't anything useful to take note of:

> ninja: fatal: ReadFile: The handle is invalid.
Indicates something going wrong within ninja

With the second clue being
> CreateProcess failed: The system cannot find the file specified.

Neither of which seem to have anything to do with YimMenu, to build a release version of YimMenu we use CMake directly from the command line. Meaning that as long as your IDE executes that correctly there shouldn't be any problems.

We can't really take the `.asm` file as a clue either as that's the first file to be compiled on any system, perhaps search around for CLion having issues with CMake and assembly files?

**Comment by malloc2k** [comment]
> I get that it's a really powerful IDE for C++ deving, however I haven't used it for YimMenu or any other projects before.
> 
> Looking at the crash logs there isn't anything useful to take note of:
> 
> > ninja: fatal: ReadFile: The handle is invalid.
> > Indicates something going wrong within ninja
> 
> With the second clue being
> 
> > CreateProcess failed: The system cannot find the file specified.
> 
> Neither of which seem to have anything to do with YimMenu, to build a release version of YimMenu we use CMake directly from the command line. Meaning that as long as your IDE executes that correctly there shouldn't be any problems.
> 
> We can't really take the `.asm` file as a clue either as that's the first file to be compiled on any system, perhaps search around for CLion having issues with CMake and assembly files?

Now that I’m in bed ( no one cares ) I just remembered: 

IIRC the compiler I’m currently using with all my projects on CLion is MinGW, I don’t really know if they can maybe have something to do with the build settings? 
Here is kinda late, if I have time tommorow I’ll give it a shot at using MSVC and I’ll post logs here.

Thanks for the support Yim ;)

**Comment by Yimura** [comment]
MingW is not supported for YimMenu sorry.

You need to use MSVC.

**Comment by Yimura** [comment]
See #562 for more information

**Comment by malloc2k** [comment]
Ohhh Gotcha!

As I said earlier I’ll give it a shot tomorrow and update you on the issue haha. 

There’s no problem to use MSVC just have to change 1 setting… Will check that out

Thanks, once again

**Comment by malloc2k** [comment]
This issue is no longer an issue, seems like the problem with this was really just using MinGW which is not supported by YimMenu.

@Yimura thanks for all the support and ill try to contribute to the project :)
