### ISSUE TITLE
[Improvement]: Question for the owners of the project

### ISSUE THREAD

**Issue by malloc2k** [Yimura/YimMenu#2810]
### Which feature

@Yimura sorry to bother you all the time, would u accept PR's that fix some warnings? As im using CLion i can see a bunch of warnings that dont really make a huge change but can overall affect the menu itself and maybe make ir run a bit quicker

### Reason

explained above :)

**Comment by malloc2k** [comment]
What im really talking about here is following some more Clang-Tidy checks :)

**Comment by Tayipc38** [comment]
Opening an issue to ask permission for a PR is not really its intended purpose. You can just PR and see whether yim accepts it or not. May take small fractions of ur lifespan till he does anything but guess thats life.

**Comment by malloc2k** [comment]
> Opening an issue to ask permission for a PR is not really its intended purpose. You can just PR and see whether yim accepts it or not. May take small fractions of ur lifespan till he does anything but guess thats life.

I was asking cuz i dont wanna fill their asses with random PRs

**Comment by gir489returns** [comment]
> > Opening an issue to ask permission for a PR is not really its intended purpose. You can just PR and see whether yim accepts it or not. May take small fractions of ur lifespan till he does anything but guess thats life.
> 
> I was asking cuz i dont wanna fill their asses with random PRs

We would just close it. Speaking of, I've been asking Yim to close #2594 because we're not going to accept it as-is and he's not going to do what we asked, so it should be closed. General rule of thumb is, don't submit things for a PR that can be done in Lua, as we don't want to maintain the code necessary for it to continue working. If it can rely on Natives or Globals/locals then it can be done in Lua.

**Comment by malloc2k** [comment]
> > > Opening an issue to ask permission for a PR is not really its intended purpose. You can just PR and see whether yim accepts it or not. May take small fractions of ur lifespan till he does anything but guess thats life.
> > 
> > 
> > I was asking cuz i dont wanna fill their asses with random PRs
> 
> We would just close it. Speaking of, I've been asking Yim to close #2594 because we're not going to accept it as-is and he's not going to do what we asked, so it should be closed. General rule of thumb is, don't submit things for a PR that can be done in Lua, as we don't want to maintain the code necessary for it to continue working. If it can rely on Natives or Globals/locals then it can be done in Lua.

Ion know bout that, i was looking to PRs and I found one that added a search bar to the players list but wasnt acceptd?

**Comment by malloc2k** [comment]
(https://github.com/YimMenu/YimMenu/pull/2766)

**Comment by malloc2k** [comment]
@gir489returns any ideas?

**Comment by Yimura** [comment]
@malloc2k, feel free to open up a PR whenever and if you're going to do a big change consider opening a discussion so people can join in and share their thoughts on the specific changes you're planning.
