### ISSUE TITLE
[Bug]: fill ammo dont work

### ISSUE THREAD

**Issue by Zucesa** [Yimura/YimMenu#2813]
### Describe the bug

it just dont work

### Steps To Reproduce

"fill ammo" button under the general tab for 'self' 

### Expected Behavior

my ammo to be filled

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
IIRC this fills your current weapon’s ammo not all of them as it’s not easy to know which weapons you are using and what ammo types they consume (MK2).

**Comment by Zucesa** [comment]
> IIRC this fills your current weapon’s ammo not all of them as it’s not easy to know which weapons you are using and what ammo types they consume (MK2).

hovering over 'fill ammo' says it 'fills all of your ammo', i have tried pressing it while holding both normal weapons and mk2 but neither have worked

**Comment by gir489returns** [comment]
> > IIRC this fills your current weapon’s ammo not all of them as it’s not easy to know which weapons you are using and what ammo types they consume (MK2).
> 
> hovering over 'fill ammo' says it 'fills all of your ammo', i have tried pressing it while holding both normal weapons and mk2 but neither have worked

Right, so, this is the code that is used:

`virtual void execute(const command_arguments&, const std::shared_ptr<command_context> ctx) override
{
	for (const auto& [_, weapon] : g_gta_data_service->weapons())
	{
		int ammo_in;
		WEAPON::GET_MAX_AMMO(self::ped, weapon.m_hash, &ammo_in);
		WEAPON::SET_PED_AMMO(self::ped, weapon.m_hash, ammo_in, 0);
	}
}
`

Either your weapons.json wasn't properly populated, you're trying to fill a MK2 ammo'd weapon, or something else is wrong.

To check the first thing, see if the Ammunation's weapon drop-down is populated.

**Comment by gir489returns** [comment]
Cool.
