### ISSUE TITLE
Crash on Session switch While Spectating a target that left.

### ISSUE THREAD

**Issue by KaroqDave** [Yimura/YimMenu#282]
**Describe the bug**
Game Crashes on session swithc when spectating player left before.

**To Reproduce**
1. Go to a player press spectate
2. If player leaves
3. Join new session

**Expected behavior**
No Crash

**Screenshots**
[Stack dump](https://imgur.com/a/j5Bf5vf)

**Logs**
```
2022/06/24 18:55:05 883788

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 13788

*******	STACKDUMP *******
stack dump [0]		C:\Users\.\Desktop\YimMenu-master\YimMenu\BigBaseV2\src\backend\looped\player\spectate.cpp L: 14 big::looped::player_spectate
stack dump [1]		C:\Users\.\Desktop\YimMenu-master\YimMenu\BigBaseV2\src\backend\backend.hpp L: 129 big::backend::remote_loop
stack dump [2]		C:\Users\.\Desktop\YimMenu-master\YimMenu\BigBaseV2\src\script.cpp L: 72 big::script::fiber_func
stack dump [3]		C:\Users\.\Desktop\YimMenu-master\YimMenu\BigBaseV2\src\script.cpp L: 29 <lambda_c124bb592cd2d6c42964ae720d232470>::operator()
stack dump [4]		C:\Users\.\Desktop\YimMenu-master\YimMenu\BigBaseV2\src\script.cpp L: 30 <lambda_c124bb592cd2d6c42964ae720d232470>::<lambda_invoker_cdecl>
stack dump [5]	 RegQueryInfoKeyA
stack dump [6]	 RtlUserFiberStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```

**Build**
Select which applies for you:
- [ ] I used YimMenu unmodified
- [x] I use my own version of YimMenu
but with latest commits, only added some self features.

**Additional context**
I tested it, it happend twice now.

**Comment by Yimura** [comment]
Thanks for your bug report.

I've only tested leaving players.
Leaving online while a player is selected and some other stuff.

Will see what I can do to resolve it without making the code ugly.

**Comment by Yimura** [comment]
Unable to replicate could you provide a video showing how you exactly triggered the crash?

I will try to replicate it a bit longer but haven't been able to do it yet...

**Comment by KaroqDave** [comment]
Ill try to record a video but im not at home currently so it might take some time.

**Comment by KaroqDave** [comment]
Here we go:
[Crash thing](https://youtu.be/DKb87BrVk0Y)
It crashes basically when the spectated target left while spectating, and then switching sessions.

**Comment by DaniTRDev** [comment]
By just looking at the video it seems that it crashes because when you leave the session, the player service removes all the players and it is causing a nullptr somehwere.

Edit: 
```
if (!g_player_service->get_selected()->is_valid() || !g->player.spectating)
``` 
That's the line causing the crash. I assume that since the player list is empty when get_selected() gets called it returns either a nullptr and crash or the program crashes because of the vector is out of range.

**Comment by Yimura** [comment]
I think I know what is causing the problem though it's odd that it crashes like that.

So to recap:
1. You spectate someone
2. That person leaves
3. Spectate auto disables when the CNetGamePlayer becomes invalid
4. You leave and the smart pointer is deallocated but the selected player isn't being replaced by the dummy player.

To fix it I just need to set the selected player in player_service::do_cleanup() to the dummy before I call .clean() on the m_players.

Though when in the player_service::player_leave() method it should swap the selected player with the dummy so I don't really understand...

**Comment by Yimura** [comment]
Check if the issue has been fixed, if there's still a problem, comment on this issue and I'll reopen it.
