### ISSUE TITLE
[Bug]: Additional font size not working

### ISSUE THREAD

**Issue by sch-lda** [Yimura/YimMenu#2820]
### Describe the bug

It seems that Yimmenu supports several different font sizes(Based on the code shown in screenshots), but in actual use, I can't see any difference. Even when I change the three font sizes of extra_font_sizes to 40px, the displayed text remains the same as before.
![image](https://github.com/YimMenu/YimMenu/assets/54973190/38f60cd4-bb5a-44fc-b941-8039d199a0fc)
![image](https://github.com/YimMenu/YimMenu/assets/54973190/6e4b74fa-f879-4b53-bedb-5dfb89f2c584)

### Steps To Reproduce

1. Attempt to visually observe if there are differences in size in the text displayed in Yimmenu.

### Expected Behavior

make additional font size work, or... remove it?

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Yeah that shouldn't happen mmmm

**Comment by Yimura** [comment]
@sch-lda, it seems to work perfectly fine for Latin characters, unsure what's going wrong with Chinese characters here 🤔 

![image](https://github.com/YimMenu/YimMenu/assets/24669514/f95bf32a-f42b-417f-82cc-569e38c42786)

**Comment by Yimura** [comment]
Similarly Chinese (CN) seems to be rendering in different font sizes for me as well just fine.

![image](https://github.com/YimMenu/YimMenu/assets/24669514/d9429524-54c0-475e-9a46-3f4b432ad562)

**Comment by sch-lda** [comment]
Retested and it indeed works fine.🤔Sorry for opening this pointless issue
