### ISSUE TITLE
Add Option to Enable/Disable "Block Request Vehicle Control"

### ISSUE THREAD

**Issue by TwystedMind** [Yimura/YimMenu#2821]
### Problem

When attempting to gift another YimMenu user a vehicle, the "Block Request Vehicle Control" protection blocks the ability - and there is no option to disable this protection in-menu.

### Solution

Add an option to enable/disable "Block Request Vehicle Control"

### Reason

To be able to gift vehicles properly, and for more versatility in-menu :)

**Comment by Deadlineem** [comment]
If the other user is using YimMenu, you have no need to gift cars to them as they can do this themselves (watch video)

https://www.youtube.com/watch?v=q9oz0prkZ0U

**Comment by TwystedMind** [comment]
I was never aware we could simply drive spawned vehicles into LS Customs.  Is this still the case after the most recent updates?  Because some things have been patched.

I'll test it out in a couple of hours and confirm, appreciate it!

**Comment by TwystedMind** [comment]
I did try this and it appears to work (I can at least spawn and drive into LS Customs, however, I didn't actually purchase a tracker to save the vehicle as I assume that works).

This request can be closed in the meantime - however, I still think it would be nice to have the ability to enable/disable "Block Request Vehicle Control", as more functionality and granular options are always better in my opinion.

However, it's no longer necessary in order to do what I'm trying to do.  Thank you for the assistance!

**Comment by Tayipc38** [comment]
There are a lot of out-of-the-box protections with YimMenu that an end-user cannot disable. They are however crafted carefully to avoid and mitigate as many false positives as possible. Request control could be added to the protection settings seen as similar options are already available there.

**Comment by gir489returns** [comment]
YimMenu isn't to be used in this way, and it was originally intended to just be a protective menu, not a cheating menu. We keep buckling and capitulating to everyone's wants and whims for this menu, instead of making them fix it themselves. I feel the true sprit of the project is lost now, as this has just become a rival cheat that's free. Although maybe I'm just jaded from those assholes in the crash thread who constantly spamming every 4 seconds that the menu wasn't working even demanding that Yim fix it.

**Comment by Yimura** [comment]
Improved with #2847

**Comment by Deadlineem** [comment]
> YimMenu isn't to be used in this way, and it was originally intended to just be a protective menu, not a cheating menu. We keep buckling and capitulating to everyone's wants and whims for this menu, instead of making them fix it themselves. I feel the true sprit of the project is lost now, as this has just become a rival cheat that's free. Although maybe I'm just jaded from those assholes in the crash thread who constantly spamming every 4 seconds that the menu wasn't working even demanding that Yim fix it.

That is true, however, p2c users hardcore target yim users to an extreme and keeping it as it is works for protecting yourself usually, but mostly if you are host.  Thats why yim has lua support, for scripts that others make to add onto yim itself and the spirit and overall concept hasn't been lost, you guys are doing a great job, a great service and a great help to all of us who use it, youre not those greedy p2c people and it takes alot not to be "that guy" and also says alot about the team that works on yimmenu in a positive way.  

Its frustrating in your shoes, having to answer stupid questions or something, i get it, but remember what youre doing for the community and the positive impact youre making regardless how this menu is built.  You can literally strip yimmenu to the bone and only allow lua scripts and make everyone work for the options they want, but you take the time to do this for the people, if they are greedy about it, oh well, its a free menu and as far as im concerned you guys do a magnificent job keeping things up to date promptly, so thanks.
