### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by givememulch** [Yimura/YimMenu#2822]
### Problem

Hey, I'd imagine you've been asked this before. 

Is there a discord server at all for YimMenu?
If so can I please get an invitation, thank you!

### Solution

.

### Reason

I would like to join the discord server for YimMenu.

**Comment by Yimura** [comment]
The answer remains the same as the previous issues and discussion opened around this question.

**Comment by givememulch** [comment]
Which is what?

**Comment by Yimura** [comment]
Have you searched for the answer before asking?
