### ISSUE TITLE
[Bug]: Open key is set to unknown (not exactly a bug)

### ISSUE THREAD

**Issue by Takka111** [Yimura/YimMenu#2828]
### Describe the bug

My open key is set to unknown. How can I reset it?

### Steps To Reproduce

.

### Expected Behavior

.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment]
Go to AppData\Roaming\YimMenu open settings.json search for "menu_toggle" and replace the value with 45 for Insert Key
