### ISSUE TITLE
[Bug]: Cant load bc Crash

### ISSUE THREAD

**Issue by ID-162773** [Yimura/YimMenu#2835]
### Describe the bug

If I start it instantly crashes

### Steps To Reproduce

Start GTA V Inject Crash

### Expected Behavior

It instantly crashes the game after Injecting

### Logs and/or screenshots

I would put it in but its too long :) 200.000 Characters

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
"I CRASH AND I DON'T KNOW WHY!"
"I would post the thing you need to help, but I won't, because too long! :)"

Duplicate of #2830

**Comment by ID-162773** [comment]
Can you tell me how to send a 4 times the limit file? bc I dont know. havent needed Support til now so Im new at this.

**Comment by ID-162773** [comment]
To correct I copy pasted it in but 65000 caracters are the limit my log is 200000

**Comment by gir489returns** [comment]
> To correct I copy pasted it in but 65000 caracters are the limit my log is 200000

Just drag and drop it into the window.

**Comment by xiaoxiao921** [comment]
Zip it, it reduce the size of logs by a ton
