### ISSUE TITLE
[Improvement]: put back the detections protections alerts  back in the console 

### ISSUE THREAD

**Issue by binded-zz** [Yimura/YimMenu#2838]
### Which feature

console no longer displays modders detected or modder tried to what every action   protections alerts 

its just loads startup info now and stops there 

not even metrics or any joins  parts  nothing is streamed to the console 

### Reason

you dont always remember what the toast protections said 

### Additional context

allow the output of protections to a onscreen console or something 

maybe its user error and i just dont see the option for it any more or using it wrong some how idk

**Comment by xesdoog** [comment]
This is a known issue. #2773
As a temporary fix, go to **Settings** > **Debug** > disable **External Developer Console** then re-enable it.

**Comment by Yimura** [comment]
Fixed with #2858
