### ISSUE TITLE
[Bug]: my friend cant drive his car when im inside of it 

### ISSUE THREAD

**Issue by Wizors** [Yimura/YimMenu#2841]
### Describe the bug

 also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue 

### Steps To Reproduce

 also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue 

### Expected Behavior

 also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue 

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Deadlineem** [comment]
> ### Describe the bug
> also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue
> 
> ### Steps To Reproduce
> also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue
> 
> ### Expected Behavior
> also in the missions we cant collect stuff it freezes for my friend. i tried all protection off still same issue
> 
> ### Logs and/or screenshots
> ```
> <paste your logs here>
> ```
> 
> ### Store
> Steam
> 
> ### Language
> English
> 
> ### YimMenu Language
> English (US)
> 
> ### Additional context
> _No response_
> 
> ### Build
> * [x]  I've confirmed the issue exists on the latest version of YimMenu
> 
> ### Coload
> * [x]  I've tested this without co-loading anything.

Need more info here, is it possible you have an option toggled somewhere that shouldn't be toggled?  For example, under Vehicles > Fun Features there is an option for vehicle fly enabling, if youre in any vehicle, youll be flying/controlling it, even if you are not the driver.

**Comment by Tayipc38** [comment]
It seems after an operation that executes a network get control, you being in the car has the effect of retaining the control. Exiting the car fixes it. Don't know how this can be fixed personally.

**Comment by Yimura** [comment]
Perhaps we can check if we’re in the driver seat and if not we just give control.

**Comment by gir489returns** [comment]
> It seems after an operation that executes a network get control, you being in the car has the effect of retaining the control. Exiting the car fixes it. Don't know how this can be fixed personally.

I fixed this in BBv2 by just checking if I'm driving if someone requests control. Also, should probably check if it's our PV or spawned vehicle, which I thought we do already?

**Comment by Tayipc38** [comment]
> Perhaps we can check if we’re in the driver seat and if not we just give control.

How do we "give" control exactly. By just allowing the request control?

**Comment by gir489returns** [comment]
> > Perhaps we can check if we’re in the driver seat and if not we just give control.
> 
> How do we "give" control exactly. By just allowing the request control?

```
if (g_local_player && g_local_player->m_vehicle && g_local_player->m_vehicle->m_net_object
    && g_local_player->m_vehicle->m_net_object->m_object_id == net_id) //The request is for a vehicle we are currently in.
{
	Vehicle personal_vehicle = mobile::mechanic::get_personal_vehicle();
	Vehicle veh              = g_pointers->m_gta.m_ptr_to_handle(g_local_player->m_vehicle);
	if (!NETWORK::NETWORK_IS_ACTIVITY_SESSION() //If we're in Freemode.
	    || personal_vehicle == veh              //Or we're in our personal vehicle.
	    || self::spawned_vehicles.contains(net_id)) // Or it's a vehicle we spawned.
	{
		g_pointers->m_gta.m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset); // Tell them to get bent.
		g.reactions.request_control_event.process(plyr);
		return;
	}
}
```

This is the code block that determines if we should reject the call. I believe the problem is that he is in freemode. :|

**Comment by Tayipc38** [comment]
> > > Perhaps we can check if we’re in the driver seat and if not we just give control.
> > 
> > 
> > How do we "give" control exactly. By just allowing the request control?
> 
> ```
> if (g_local_player && g_local_player->m_vehicle && g_local_player->m_vehicle->m_net_object
>     && g_local_player->m_vehicle->m_net_object->m_object_id == net_id) //The request is for a vehicle we are currently in.
> {
> 	Vehicle personal_vehicle = mobile::mechanic::get_personal_vehicle();
> 	Vehicle veh              = g_pointers->m_gta.m_ptr_to_handle(g_local_player->m_vehicle);
> 	if (!NETWORK::NETWORK_IS_ACTIVITY_SESSION() //If we're in Freemode.
> 	    || personal_vehicle == veh              //Or we're in our personal vehicle.
> 	    || self::spawned_vehicles.contains(net_id)) // Or it's a vehicle we spawned.
> 	{
> 		g_pointers->m_gta.m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset); // Tell them to get bent.
> 		g.reactions.request_control_event.process(plyr);
> 		return;
> 	}
> }
> ```
> 
> This is the code block that determines if we should reject the call. I believe the problem is that he is in freemode. :|

Was just looking at it. Its retarded we block almost all requests when this has legit scenarios.

**Comment by gir489returns** [comment]
> Was just looking at it. Its retarded we block all requests when this has legit scenarios.

I didn't know of any Freemode scenarios when I wrote this. But then again, I don't play with friends in Freemode, we all play on heists/missions, so yeah.
