### ISSUE TITLE
[Bug]: Vehicle List Missing

### ISSUE THREAD

**Issue by IndexOut0fBounds** [Yimura/YimMenu#2849]
### Describe the bug

Current build is missing the whole vehicle spawn list. Personal and persistent vehicles are unaffected.

### Steps To Reproduce

Go to Spawn Vehicles

### Expected Behavior

Every vehicle should be shown in the dropdown

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
><paste your logs here>

**Comment by ToXicVibezz** [comment]
This is something fixed by verifying game files..
