### ISSUE TITLE
[Bug]: Cannot customize vehicle if it requires you to press (E).

### ISSUE THREAD

**Issue by BigboiKilljoy** [Yimura/YimMenu#2855]
### Describe the bug

Title

### Steps To Reproduce

1. Turn on the setting "Peds Ignore"
2. Go into any self owned building with a customize area and try to customize your car (Like maze bank)
3. Now you have to press (E) from the vehicle seat to customize (Except you cant)

### Expected Behavior

You know the expected behavior, you've played the game.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

 I tested what was stopping me from customizing the vehicle and its got something to do with the "Peds Ignore" setting. Please fix :)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is a byproduct of setting peds ignore on. The mechanic has to start a sequence that you are blocking by setting him into a state he can’t get out of.

**Comment by BigboiKilljoy** [comment]
> This is a byproduct of setting peds ignore on. The mechanic has to start a sequence that you are blocking by setting him into a state he can’t get out of.

Well if this is something that can't be worked around then the "Ped Ignore" option should say that you wont be able to customize vehicles when you hover your mouse over it

**Comment by BigboiKilljoy** [comment]
Idk why you closed this lol, just because we know why its happening doesn't mean we've figured out what to do with it.
