### ISSUE TITLE
[Bug]: Forged chat messages aren't seen by other players

### ISSUE THREAD

**Issue by Tayipc38** [Yimura/YimMenu#2861]
### Describe the bug

When an authorized player makes use of the chat commands, any automatic response via the chat from our client is purely local. Other players don't see it.

### Steps To Reproduce

1. Enable chat commands
2. Allow someone access to chat commands
3. Let them input a wrong command or argument
4. Ask whether they see the response
5. They Don't.

### Expected Behavior

The messages should be networked and visible to the lobby and also restricted to the channel the command is received from (all or team).

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Tayipc38** [comment]
And if anyone can think of an alternative chat command channel (other than the ingame chat) im all ears.

**Comment by gir489returns** [comment]
@maybegreat48 Didn't they patch this a long time ago?

**Comment by Yimura** [comment]
The title is misleading, he's just talking about the send_chat_command function not working as expected.

**Comment by GreySideMM** [comment]
So I had noticed before that basically everywhere this is being used to send chat messages:
g_hooking->get_original<hooks::send_chat_message>()(...)
That does circumvent our own function hooks::send_chat_message(). At least in one test I had done so far. (I was planing to check what the reason for this was as I make use of it in yet another odd feature of mine..)
The original function shouldn't be used anyway, imo. (I read somewhere that it sends the chat to R*, too. ...)

**Comment by Tayipc38** [comment]
> @maybegreat48 Didn't they patch this a long time ago?

>The title is misleading, he's just talking about the send_chat_command function not working as expected.

Yea did not mean the most toxic feature ever, however fun that was. I just mean sending a message as ourselves.

**Comment by hathyr12** [comment]
HOW CAN I FIX THISSS?

**Comment by gir489returns** [comment]
> HOW CAN I FIX THISSS?

MA’AM DO NOT REDEEEEEEEEM!!!!!
