### ISSUE TITLE
[Bug]: crash on injection

### ISSUE THREAD

**Issue by GHDavor** [Yimura/YimMenu#2868]
### Describe the bug

idk, out of nowhere it started crashing everytime i inject

### Steps To Reproduce

amm, ???

### Expected Behavior

it shouldn't crash

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14729949/cout.log)

Demo:
https://github.com/YimMenu/YimMenu/assets/91034453/0da0f33c-a4ca-461e-875c-4e0314b33318

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
you installed ASI mods which are conflicting with YimMenu, remove them
