### ISSUE TITLE
[Request]: Desync Kick is now detected by modders and Improvements.

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#2870]
### Problem

Recently i got kicked by some paid menu modders, the protections detected that they were trying to control my car, so i decided to desync kick the guy (he wasn't the host), it really felt like the bullet bounced and got myself kicked... that's how funny it was, also this isn't the first time this incident happens, **desync kick can now be detected by other modders**, not sure if they can stop it tho.

Some useful info:
- I got desync kicked according to protections, so there's no new method, they just seem to detect who's desyncing and desync them back.
- The modder didn't get kicked for some reason, might have blocked it (he had no host)

### Solution

There's some major improvements that can be done.

1- Make the desync kick anonymous again, not sure how they are detecting it, but the idea is there.
2- Add the "Desync Karma", essentially kicking the player who's desyncing you (this requires detecting who's desyncing before ur out), as far as i know, you will still get kicked, but the other will too.
3- Find a way to block the kick (this is the least probable one).

### Reason

The Desync Kick was the last good option to deal with annoying paid modders griefing the entire session, now it's useless and i feel like there's little no protection anymore, i really think it's a concern!

### Additional context

https://github.com/YimMenu/YimMenu/assets/88536465/7b21ba3f-ec8b-4b65-a727-489a284372c0

**Comment by binded-zz** [comment]
i just set my self to always be host and kick host so that why when you join 99% of the time you will get host 

then its easy to deal with them with kick show cheat message lol 
also it some what protects you a lil more  less likely to get kicked as you are the host 
i dont have the force script host though 

i have alot of reactions that just timeout, kick, block when modding me

**Comment by Tayipc38** [comment]
Being host should be your top priority. Otherwise you won't last long in any session.

**Comment by vladdoser** [comment]
Same, see that some menu's have desync detection & auto reaction, which literally kick me in few seconds after trying to desync 1 specific guy (tested on other mods in session).
Note that he wasn't host or etc at that moment.
![image](https://github.com/YimMenu/YimMenu/assets/49642466/3a31b5c5-6007-493f-9641-6ebcbe57059a)
![image](https://github.com/YimMenu/YimMenu/assets/49642466/dcc0fd66-6524-4298-9989-9d99482deaaa)

**Comment by Ahmad23145** [comment]
same issue pls fix it

**Comment by snowleopardd** [comment]
> Being host should be your top priority. Otherwise you won't last long in any session.

I really love this menu, and the fact that it's open source and so premium, but we can't just ditch the functions that were working great and resort to not so practical alternatives/workarounds until none of them work, preferring to kick a random legit player to take host (the feature is already buggy) instead of fixing/improving a countermeasure is not cool, also please don't take this as criticism, i love all your guys work but this shouldn't be left unresolved

**Comment by Rxann** [comment]
> > Being host should be your top priority. Otherwise you won't last long in any session.
> 
> I really love this menu, and the fact that it's open source and so premium, but we can't just ditch the functions that were working great and resort to not so practical alternatives/workarounds until none of them work, preferring to kick a random legit player to take host (the feature is already buggy) instead of fixing/improving a countermeasure is not cool, also please don't take this as criticism, i love all your guys work but this shouldn't be left unresolved

I check all the boxes but kick host when joining, and then whenever the host leaves I usually get it. I don't like kicking random people so this is a solution to this too.

**Comment by vladdoser** [comment]
> > > Being host should be your top priority. Otherwise you won't last long in any session.
> > 
> > 
> > I really love this menu, and the fact that it's open source and so premium, but we can't just ditch the functions that were working great and resort to not so practical alternatives/workarounds until none of them work, preferring to kick a random legit player to take host (the feature is already buggy) instead of fixing/improving a countermeasure is not cool, also please don't take this as criticism, i love all your guys work but this shouldn't be left unresolved
> 
> I check all the boxes but kick host when joining, and then whenever the host leaves I usually get it. I don't like kicking random people so this is a solution to this too.

I can say that 20% of sessions u trying to join in, will instantly drop u by reaction of host-modders, which already got host, and knowing about your try.

**Comment by Rxann** [comment]
> > > > Being host should be your top priority. Otherwise you won't last long in any session.
> > > 
> > > 
> > > I really love this menu, and the fact that it's open source and so premium, but we can't just ditch the functions that were working great and resort to not so practical alternatives/workarounds until none of them work, preferring to kick a random legit player to take host (the feature is already buggy) instead of fixing/improving a countermeasure is not cool, also please don't take this as criticism, i love all your guys work but this shouldn't be left unresolved
> > 
> > 
> > I check all the boxes but kick host when joining, and then whenever the host leaves I usually get it. I don't like kicking random people so this is a solution to this too.
> 
> I can say that 20% of sessions u trying to join in, will instantly drop u by reaction of host-modders, which already got host, and knowing about your try.

I have not experienced this. I also focus more on RDR2 now so I don't play by far as much as I used to.

**Comment by lonelybud** [comment]
> I check all the boxes but kick host when joining, and then whenever the host leaves I usually get it. I don't like kicking random people so this is a solution to this too.

that's what one should do wait for your turn don't disturb someone's gameplay for our own foolish needs

**Comment by snowleopardd** [comment]
> > > > Being host should be your top priority. Otherwise you won't last long in any session.
> > > 
> > > 
> > > I really love this menu, and the fact that it's open source and so premium, but we can't just ditch the functions that were working great and resort to not so practical alternatives/workarounds until none of them work, preferring to kick a random legit player to take host (the feature is already buggy) instead of fixing/improving a countermeasure is not cool, also please don't take this as criticism, i love all your guys work but this shouldn't be left unresolved
> > 
> > 
> > I check all the boxes but kick host when joining, and then whenever the host leaves I usually get it. I don't like kicking random people so this is a solution to this too.
> 
> I can say that 20% of sessions u trying to join in, will instantly drop u by reaction of host-modders, which already got host, and knowing about your try.

Thats another good reason, when you're in a session where there's already a modder spoofing their token, the only things u have to defend yourself from other modders (assuming the host is friendly) are these kick/crash countermeasures
