### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by LettHead1** [Yimura/YimMenu#2876]
### Describe the bug

I keep crashing whenever I do anything. I crashed when I got into a vehicle an started to drive twice. I crashed while trying to open the kotkey menu. I crashed when I tried to spectate someone.

### Steps To Reproduce

Moving through the menu works fine but once I do something it crashes the game.

### Expected Behavior

The most it allowed me to play was 5 minutes, and that was without using the menu for anything just driving,

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14765154/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

The log file was from the last crash which was when I tried to spectate someone.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
You a using a debug build. Switch to release mode or RelWithDebInfo when you compile it yourself. Debug is currently broken.

**Comment by gir489returns** [comment]
Well Danny. If you had actually taken the time to READ the log, at the top you'll see:

`[21:53:47.2983553][WARN/main.cpp:175] Debug Build. Switch to RelWithDebInfo or Release Build for a more stable experience`

**Comment by LettHead1** [comment]
Sorry first time doing anything like this
