### ISSUE TITLE
[Bug]: Chat now prints everything as [team]

### ISSUE THREAD

**Issue by GreySideMM** [Yimura/YimMenu#2878]
### Describe the bug

Must be due to #2864 or previous commits. Whenever someone writes something for "all" it is being displayed as "team".
There was a duplicated is_team Read<bool>() removed here: https://github.com/YimMenu/YimMenu/commit/7e7bcb155a5594a6e5955894cc2b8f05d063b31c#diff-12a073d544e519b46ab3e4f1eb08c2098f554ecbcf7aa72e61d776fc2cd9ca63L150
So that apparently should have never been there and might even had caused unnoticed misbehavior before. Also: In the chat.log everything is correct.

So it seems to be what I suspected: There is a bug with buffer.Read<bool>(1) I encountered before. Not sure about every details anymore:
While is_team logs as "0" to the console it actually has the uint8_t value of "6" (e.g. 0b0110). IIRC when passed as boolean to a function it "correctly" interprets this "6" as false (probably only checks the lowest bit). I suspect this to not work with the call of `g_pointers->m_gta.m_handle_chat_message()`.
Treating is_team as an int and then check for == 1 is a stupid workaround I used and seems to work. Everything else might be killed by the compilers optimization. (I used similar in some WIP before.)
```
if ((int)is_team == 1)
	is_team = true;
else
	is_team = false;
```

### Steps To Reproduce

-

### Expected Behavior

-

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Yes we are aware.

**Comment by gir489returns** [comment]
@GreySideMM Is it correct in chat.log? Or is it just always printing ALL? We use a different callback for logging our own chats than we do when we receive them from other people. Ask a friend to team chat something to you.

**Comment by GreySideMM** [comment]
> @GreySideMM Is it correct in chat.log? Or is it just always printing ALL? We use a different callback for logging our own chats than we do when we receive them from other people. Ask a friend to team chat something to you.

Well, could take some day(s) before I can test this, I basically have only some "randos" in GTA. (And my current day is over now.)

**Comment by Yimura** [comment]
Granted that before the team chats weren't recognised at all before (at the least I seem to remember), it's just now much more noticeable since everything is team.

**Comment by Tayipc38** [comment]
@GreySideMM There is an additional issue. The buffer seems to contain a rlGamerHandle before the is_team bool. On @maybegreat48 aimbot branch he has changed the interpretation to account for this, however it still does not work. So your buffer read bug could be our culprit I was after.

EDIT: I can personally vouch for rlGamerHandle being in the buffer since it never fails reading the correct rockstarId.

**Comment by DayibBaba** [comment]
> @GreySideMM There is an additional issue. The buffer seems to contain a rlGamerHandle before the is_team bool. On @maybegreat48 aimbot branch he has changed the interpretation to account for this, however it still does not work. So your buffer read bug could be our culprit I was after.

EDIT: I can personally vouch for rlGamerHandle being in the buffer since it never fails reading the correct rockstarId.

**Comment by Tayipc38** [comment]
What if we read out the buffer for our commands and spam check, and seek to 0 to return original?
EDIT: This works.
