### ISSUE TITLE
[Improvement]: Model Previewing

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#2880]
Currently the model preview service uses the frame rate/tick rate of the game to determine the rotation.
This should be swapped out with a time delta calculation as to make it independent of the frame rate/tick rate.

https://github.com/YimMenu/YimMenu/blob/399a5d3dec8adf830e1cac7b2306d1b2f1f411f8/src/services/model_preview/model_preview_service.cpp#L207-L212

#2879 already does something to remove some of the jank.

**Comment by gir489returns** [comment]
This isn't a bug, it's just not designed well.
