### ISSUE TITLE
[Bug]: Crash with invalid json through self_persist_outfit looped

### ISSUE THREAD

**Issue by zdzisioO** [Yimura/YimMenu#2893]
### Describe the bug

When i open game and go singleplayer or multiplayer and open my mod it crush my game, I tried a few injector and everything looks the same.

### Steps To Reproduce

1.open game 2.go to single/multi 3.open mod 4.see crash log

### Expected Behavior

I expected that my mod will work well not crash.

### Logs and/or screenshots

[crash log.txt](https://github.com/YimMenu/YimMenu/files/14809221/crash.log.txt)

### Store

Rockstar

### Language

Polish

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
`[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`

A JSON configuration file either the translations, your config file itself or something else is causing this. Delete the YimMenu folder in AppData and try again.

**Comment by zdzisioO** [comment]
Bro thanks, actually worked.

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/21da47f3e5b2abd7f2aadda3140859900b9e97e4/src/backend/looped/self/persist_outfit.cpp#L59
