### ISSUE TITLE
[Bug] Chat dispatches are not seen by other clients.

### ISSUE THREAD

**Issue by xxsnoopcattxx** [Yimura/YimMenu#2897]
### Problem

First of all, thank you @Yimura for sharing the work with public, I have been enjoying it and helping my friends in game a lot with the help of your work. I do not know if its the proper place to post this thread because I am new to github and do not really know how things work here. I had even got the pop up for understanding how things work here but it seems to be a lot complicated.

The Problem 
is that whenever i inject the dll, I cant send chats in lobby as well as in organization chat  but I am able to receive them.  On my screen, I am sending the chats but no one from the lobby or my organization is receiving it. And as soon as I unload the dll, the chat starts working without even requiring a game restart. I have been a user since long but this particular issue has started only since yesterday. 

The in game phone message system still works.

Therefore I am requesting help to fix this issue as I am very much used to this menu and I do not want to switch to any other menu.

### Solution

I am requesting one.

### Reason

I want to get this issue fixed and enjoy game again like before.

### Additional context

I do not have simple coding knowledge, I am a 12 year old.

**Comment by gir489returns** [comment]
I have no idea what the hell you are asking us to do.

**Comment by CypherMorgan** [comment]
I can confirm. After the chat fixes, the other players in session cannot see our chat and it's just being sent in our pov.

> I have no idea what the hell you are asking us to do.

**Comment by gir489returns** [comment]
> I can confirm. After the chat fixes, the other players in session cannot see our chat and it's just being sent in our pov.
> 
> > I have no idea what the hell you are asking us to do.

So this is a bug? Why is it labeled as a request?

**Comment by lonelybud** [comment]
its a bug. can confirm old code was fine.

**Comment by gir489returns** [comment]
> its a bug. can confirm old code was fine.

We'll look into it when we get time. Right now I'm tired of GTA V development after #2888.

**Comment by lonelybud** [comment]
> We'll look into it when we get time. Right now I'm tired of GTA V development after #2888.

this one works fine for me -
https://github.com/lonelybud/lonelyMenu/blob/e9d90dc25ba137d6a8a7ea26c0b1034e2515ebe2/src/util/chat.hpp#L44-L50

**Comment by xxsnoopcattxx** [comment]
> > We'll look into it when we get time. Right now I'm tired of GTA V development after #2888.
> 
> this one works fine for me - https://github.com/lonelybud/lonelyMenu/blob/e9d90dc25ba137d6a8a7ea26c0b1034e2515ebe2/src/util/chat.hpp#L44-L50

What do i do with it ? Do I have to download the file and put it in appdata ? If yes, could you please tell me the path where I have to put it ?

**Comment by lonelybud** [comment]
once there is a build triggered in this pull request https://github.com/YimMenu/YimMenu/pull/2900. Download the dll from there and inject it

**Comment by xxsnoopcattxx** [comment]
> once there is a build triggered in this pull request #2900. Download the dll from there and inject it

It works fine now, thanks a lot for your time and helping me out. Wishing good luck for you.
