### ISSUE TITLE
Get Spoofed Players

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#29]
Any way to find out which user spoofed some values for himself?

To like categorize spoofed players

**Comment by Yimura** [comment]
If they didn't spoof their R* ID or the R* ID doesn't match the name they're playing with they're spoofing their values. Although good luck on using the social club API I don't intend to invest any time in that.

**Comment by Yimura** [comment]
One thing to check is a username that's 5 characters or less, those names are 100% spoofed since the api doesn't allow for such short names to be set.
