### ISSUE TITLE
[Bug]: Updated personal vehicle spawn implementation does not correctly update preview models between same-model vehicles

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#2903]
### Describe the bug

Commit #2888 seems to have introduced a minor bug that is encountered when scrolling between two or more same personal vehicle models. The preview will not update past the first model.

For example, I have two armored Kurumas - one white and one black. When I mouse-over the first Kuruma in the list, the preview will show me the white one. When I then mouse-over the second Kuruma, the rotation preview model will continue to display the same white Kuruma, not the second Black one.

The same thing happens going the other direction. Only the first vehicle preview model is shown (black Kuruma), and will not correctly update to the white Kuruma above it in the list. This occurs for all vehicles that have multiples across the player's garages.

### Steps To Reproduce

1. Have two identical model personal vehicles (e.g., Obey 8F, Kuruma, etc.) - the vehicles don't need to be exact duplicates in terms of configuration, they just need to have the same display name (minus the license plate) in the menu
2. Enter the personal vehicle spawn window in Yim, and mouse-over one of the vehicles in the list that has multiples
3. Observe the previewed vehicle model
4. Immediately mouse-over another vehicle model that is the same model as the first, without mousing over any other vehicles in between
5. Observe that the previewed vehicle model has not updated, and continues to show the first-selected vehicle

### Expected Behavior

The preview vehicle model should be updating with every mouse-over

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Can you upload your entire persisted vehicles folder so I can test this?

**Comment by gir489returns** [comment]
Please test https://github.com/YimMenu/YimMenu/pull/2904 and ignore my previous comment, I didn't read your ticket properly.

**Comment by rkwapisz** [comment]
Verified fixed. Vehicle previews now updated as expected.

**Comment by gir489returns** [comment]
This has to stay open until the changes are merged.
