### ISSUE TITLE
[Bug]: Helicopter vehicle spawner previews instantly explode

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#2905]
### Describe the bug

When using the preview feature in the Spawn Vehicle menu, selecting any helicopter for preview instantly causes the helicopter to explode. I have not been able to replicate this issue with any other vehicles or vehicle types.

Examples of impacted helicopters:
- Akula
- Annihilator Stealth
- Conada
- FH-1 Hunter
- Havok
- Sea Sparrow
- Weaponized Conada

### Steps To Reproduce

1. Open the Spawn Vehicle menu
2. Ensure that Preview is enabled
3. Select any helicopter from either the New or Personal categories

### Expected Behavior

The helicopter should be rendered just like other vehicles without exploding.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
I wasn't able to reproduce this. (Using the latest binary from #2904.) Neither with or without max mods, or spawning. I also tried steep terrain, buildings, and other obstacles.
Can you tell any other details that could be relevant here?

**Comment by rkwapisz** [comment]
Well I'm at a loss. After switching sessions, the issue seems to have resolved.

I'll close this issue as not planned, but I'll check the feature regularly to see if it was a one-off or if I had accidentally set up some sort of state within the menu that then caused this issue. Very strange.

**Comment by rkwapisz** [comment]
Closing as non-reproducible for now.

**Comment by rkwapisz** [comment]
https://github.com/YimMenu/YimMenu/assets/13259220/40f07391-8c05-43e8-b77c-b07954518456

I've reopened this issue as it has reappeared. I'm using a build with the updated vehicle spawning architecture and #2904.

The issue does not appear to be related to any protections, and I don't have any other settings (like vehicle toggles) enabled that I can see potentially conflicting with this feature. I'll keep an eye out for anything that may trigger it to start occurring.

**Comment by rkwapisz** [comment]
There is something either in the menu or the world that triggers this behavior, as it doesn't occur immediately.

1) Created or joined a session (tried both public and closed, behavior is reproducible whether there are others in the session or if I'm alone)
2) Immediately verified that helicopter previews work as intended
3) Entered a personal vehicle, again verified helicopter previews worked
4) Drove for approximately one minute with no particular destination in mind
5) Helicopter previews started exploding, and behavior continued until I created or joined a new lobby

**Comment by gir489returns** [comment]
@rkwapisz Does the bug occur with Persist Vehicles preview?

**Comment by gir489returns** [comment]
Please try the build enclosed with #2908 to see if I fixed it.

**Comment by rkwapisz** [comment]
Verified fixed.

No idea why it was only helicopters being affected, but setting the entity proofs does the trick.
