### ISSUE TITLE
[Improvement]: smaller GUI scale

### ISSUE THREAD

**Issue by coprofago** [Yimura/YimMenu#2907]
### Which feature

Add smaller options to GUI interface scale.

### Reason

Interface is still too big at smallest scale when using lower game resolution (Potato PC =D).

### Additional context

![a2](https://github.com/YimMenu/YimMenu/assets/106185220/9e13a99b-88f7-4cb9-b616-5a5800859d86)
![a1](https://github.com/YimMenu/YimMenu/assets/106185220/b24b524e-630a-4e3d-8604-07b40c0ab1df)

**Comment by Yimura** [comment]
He’s not really the first, however the menu just can’t handle it.

**Comment by GreySideMM** [comment]
Sry but I have to add: At 0.75 and 1080p it is in deed quite large. Setting it manually to 0.70 (via settings.json for example) works without issue. Optically even smaller values should be possible with latin text. What's the expected problem? (Well, for me, on rescale the game/menu sometimes crashes even using the allowed values. There goes another issue?)
