### ISSUE TITLE
[Bug]: Cart in Daily Vault disappears in Casino Heist Finale AND does not proceed from Mantrap when exiting Main Vault

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#2909]
### Describe the bug

It's as the title says.

### Steps To Reproduce

1.Casino Heist Start
2.into Daily Vault, cart disappear
3.Mantrap to Main Vault
4.Main Vault to Mantrap, not load next prosess

### Expected Behavior

display Cart in Daily Vault and load next prosess from Mantrap

### Store

Epic Games

### Language

Japanese

### YimMenu Language

English (US)

### Additional context

What I tried
- All protection turn off
- Debug -> Scripts -> All turn off

*The improvement occurred when I unloaded Yim Menu.
*Probably occurs after the following versions.
https://github.com/YimMenu/YimMenu/commit/95259faf593150dc5d5b929a457b4b0ae91f778e

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I play through the casino heist at least 10 times a month, and never ever encountered this. No log posted and very little information + basic github avatar + L + ratio.

**Comment by rkwapisz** [comment]
Are you using any LUA scripts in addition to the base menu?

Can you please provide more detail? Your report is difficult to understand.

**Comment by oxUNKNOWNxo** [comment]
Add missing information.
- I'm playing on two PCs by myself.
- Both PCs use YimMenu and not Lua Scripts.
- Cayo Perico, Doomsday Heist ends normally under the same conditions.

Add verified results.
- This problem does not occur on the mission host side.
- I turned off both host and crew options as much as possible, but it didn't improve.
- It was resolved by unloading the crew's YimMenu.
- Not only the Cart but also the keypad cannot be operated.
- Guard man, CCTVs stop
- The situation is different, such as opening the door on the host side but not opening it on the crew side.
*Image reference

Host Cart
![host_cart](https://github.com/YimMenu/YimMenu/assets/112477569/2cb371d3-d04d-4fa6-b463-97b686f7857c)
Crew Cart
![crew_cart](https://github.com/YimMenu/YimMenu/assets/112477569/2a2040e8-62ea-4335-b9d9-691f61f91b98)
Host Door
![host_door](https://github.com/YimMenu/YimMenu/assets/112477569/a673a7c7-e0a8-43d6-b4ea-a494a2c89ee0)
Crew Door
![crew_door](https://github.com/YimMenu/YimMenu/assets/112477569/9129c513-2437-46d7-9d82-2efc8f4ee808)

**Comment by gir489returns** [comment]
That could explain why I never encounter it, I always host. The only thing I could think of is we block it somehow.

@maybegreat48 Any ideas?

**Comment by rkwapisz** [comment]
Is this reproducible each time you run the heist, @oxUNKNOWNxo?

I've experienced very similar symptoms across some contact missions with my online partner, but I attribute it to the netcode rather than my use of Yim. It seems like some kind of session desync which can cause objectives to update on one player's game but not the other's, map blips disappearing randomly, etc.

I just want to make sure we've identified that this is a consistent issue that can be attributed to the menu rather than GTA:O's incredibly efficient, bug-free, optimized netcode.

**Comment by oxUNKNOWNxo** [comment]
Yes, it is reproducible.

Admittedly, Heist is buggy, and at first I suspected a bug in GTAO, but it's weird that it improves when you Unload the YimMenu on the crew side.

**Comment by Tessio** [comment]
by reversing this #2857 note that there are no longer any errors when making the diamond casino heist

**Comment by gir489returns** [comment]
> by reversing this #2857 note that there are no longer any errors when making the diamond casino heist

OK that makes sense that #2857 caused it. @DayibBaba claimed it had serious amounts of false positives. @Yimura Should we walk back that commit?

**Comment by Yimura** [comment]
Probably for the best yeah.
