### ISSUE TITLE
[Bug]: Onboarding Window does not show up on fresh YimMenu installs.

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#2910]
### Describe the bug

It simply show the Build Cache window, you press Update Cache, and then the window is gone, and the onboarding never show up.

### Steps To Reproduce

.

### Expected Behavior

.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Huh weird, it should show up by default? Will need to investigate this.
