### ISSUE TITLE
[Improvement]: Breakup Kick Karma when someone tries kick me as host

### ISSUE THREAD

**Issue by Ahmad23145** [Yimura/YimMenu#2912]
### Which feature

in the title

### Reason

because then I can kick modders more easily

**Comment by rkwapisz** [comment]
There is a Reactions feature in YimMenu that allows you to do this, depending on the kind of kick.
Have you explored this feature, or are you asking for something new that hasn't been implemented?

**Comment by the-easter-git** [comment]
literally Settings -> Reactions

**Comment by the-easter-git** [comment]
you want to karma kick the host or breakup kick as a reaction as the host? not sure what you're asking for here.
the former is no longer possible, the latter is Settings -> Reactions

**Comment by Ahmad23145** [comment]
Okay
