### ISSUE TITLE
[Bug]: Story Mode vehicle preview models immediately despawn entities inside them

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#2913]
### Describe the bug

Currently only tested this in Story Mode with #2908; I have not tested with the stable build. 

When in Story Mode, rotating vehicle models that are displayed in the game world via the vehicle preview function immediately despawn any entities inside them. This behavior is easily observable by bringing up a vehicle preview and then walking the character over other entities. Online mode does **not** exhibit this behavior.

This also makes it significantly more difficult to spawn new vehicles in Story Mode with the vehicle preview feature since the preview model immediately removes the newly-spawned vehicle from the game world.

I like using YimMenu in Story Mode. It greatly enhances the replayability of single player by introducing new multiplayer-only vehicles and weapons that cannot otherwise be obtained in Story Mode. I hope the intent of YimMenu is to support use in Story Mode where it makes sense.

### Steps To Reproduce

1. Enter single-player Story Mode
2. Open the Vehicle Spawn menu
3. Enable vehicle previews, and mouse over any vehicle in any of the lists
4. With the preview still active, move the player character around the world in a way that collides the previewed vehicle model with other entities in the game world
5. Observe as existing entities are removed from the game world when the vehicle preview collides with them

### Expected Behavior

The vehicle preview should not be despawning entities already in the world.

### Logs and/or screenshots

```
<paste your logs here>
```

https://github.com/YimMenu/YimMenu/assets/13259220/6b3b8a44-aa29-4f80-94f7-2d3991825eec

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
This is expected behavior and also applies to online mode. However it can't delete any vehicle like player vehicles or protected entities by other modders. Also: Often it deletes previously spawned vehicles for me, too. But not always and I haven't paid enough attention to this for now.
