### ISSUE TITLE
[Request]: Block Outgoing Syncs

### ISSUE THREAD

**Issue by divinusinc** [Yimura/YimMenu#2917]
### Problem

Currently we have the ability to block incoming syncs (e.g. clone syncs)

### Solution

It would be nice to block outgoing syncs as well.

### Reason

At times there are entities I spawn that crash surrounding players, blocking outgoing syncs would prevent this.

**Comment by gir489returns** [comment]
I'm assuming you closed this because you realized the moment you block outgoing syncs from you (as the host?) that you would just desync and disconnect, right?
