### ISSUE TITLE
[Bug]: when i run the cheat i can't open the menu to select the second weapon

### ISSUE THREAD

**Issue by dadik999** [Yimura/YimMenu#2923]
### Describe the bug

when i run the cheat i can't open the menu to select the second weapon

### Steps To Reproduce

when i run the cheat i can't open the menu to select the second weapon

### Expected Behavior

when i run the cheat i can't open the menu to select the second weapon

### Logs and/or screenshots

```
when i run the cheat i can't open the menu to select the second weapon
```
when i run the cheat i can't open the menu to select the second weapon

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

when i run the cheat i can't open the menu to select the second weapon

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### Second Weapon

- [X] when i run the cheat i can't open the menu to select the second weapon

### PS
when i run the cheat i can't open the menu to select the second weapon

**Comment by gir489returns** [comment]
when i run the cheat i can't open the menu to select the second weapon
