### ISSUE TITLE
[Bug]: Lua Command

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#2924]
### Describe the bug

Cant call commands using command.call_player, even with example from commands.md im getting troubles with args, where provided needed amount, but expected same amount.

### Steps To Reproduce

Can use any of variants;
command.call("spawn", {joaat("adder")}) - this works, cause it not call_player
command.call_player(network.get_selected_player(), "spawn", {joaat("adder")}) - default example not works
command.call_player(network.get_selected_player(), "playertp", { self.get_id() })
command.call_player(network.get_selected_player(), "clearwanted", { 0 })
command.call_player(network.get_selected_player(), "clearwantedlvl", { })

### Expected Behavior

Command executed successfully

### Logs and/or screenshots

![image](https://github.com/YimMenu/YimMenu/assets/49642466/a36a7439-b4e9-4a77-8401-2052e2993f6c)
![image](https://github.com/YimMenu/YimMenu/assets/49642466/f41dc373-b340-496f-b79d-283527164ac7)
![image](https://github.com/YimMenu/YimMenu/assets/49642466/2448e42e-174c-46ad-9b17-f4aa8d8bda92)
![image](https://github.com/YimMenu/YimMenu/assets/49642466/2511f3c8-135f-40be-ab88-0384dcbeb2f1)

### Store

Epic Games

### Language

English

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by vladdoser** [comment]
@xiaoxiao921 are u sure that problem solved?

i still cant call any command, and even "spawn" command is missing: 
[21:39:42.4400225][FATAL/command.cpp:54] No player command called spawn
[21:39:53.9882834][FATAL/command.cpp:54] No player command called spawn

Any command makes game crashed, example:  
command.call_player(network.get_selected_player(), "explode", { "*nickname*" })
command.call_player(network.get_selected_player(), "playertp", { "*nickname*" })

Reason only i get from console: 
[21:54:00.7935469][FATAL/lua_module.cpp:53] Lua is in a panic state and will now abort() the application

Check it pls.

**Comment by xiaoxiao921** [comment]
- `spawn` is not a player command, so you can't call it with `call_player`.
- `command.call_player(network.get_selected_player(), "playertp")` should work. idk why you using an extra parameter called "nickname"

**Comment by vladdoser** [comment]
> * `spawn` is not a player command, so you can't call it with `call_player`.
> * `command.call_player(network.get_selected_player(), "playertp")` should work. idk why you using an extra parameter called "nickname"

So why u have in LuaDocs? 
command.call_player(somePlayerIndex, "spawn", {joaat("adder")})

My bad, i though it command calls like from his ask, as chat commands..

**Comment by xiaoxiao921** [comment]
Yeah sorry the doc is wrong. but yeah call_player spawn never worked

**Comment by vladdoser** [comment]
> Yeah sorry the doc is wrong. but yeah call_player spawn never worked

Now clear, is it possible make method, which gonna work like "Chat commands" for players in Network section?
