### ISSUE TITLE
[Request]: Protection setting UI for give_collectible protection is missing

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#2935]
### Problem

https://github.com/search?q=repo%3AYimMenu%2FYimMenu%20%22give_collectible%22&type=code

### Solution

.

### Reason

.

### Additional context

.

**Comment by GreySideMM** [comment]
![collectible](https://github.com/YimMenu/YimMenu/assets/155721485/438ac975-33c5-41ef-9952-8ff00cdaf450)
?
(Own branch but..)

**Comment by xiaoxiao921** [comment]
This is the reaction panel, not the protection panel.

**Comment by Yimura** [comment]
Ahah, the protection is present but there's no UI element to actually toggle it.

**Comment by xiaoxiao921** [comment]
Closed by https://github.com/YimMenu/YimMenu/pull/2990
