### ISSUE TITLE
[Bug]: CEO & MC Invites don't send or recieve

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#2936]
### Describe the bug

Players I send MC and CEO invites to do not receive them, and I do not receive their invites.

### Steps To Reproduce

1. Invite a Player to your CEO or Motorcycle Club.
2. Observe that they do not receive it.

### Expected Behavior

Invites are able to work properly.

### Logs and/or screenshots

[My Settings File](https://github.com/YimMenu/YimMenu/files/14953082/settings.json)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I am not entirely sure this is YimMenu related.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Can't reproduce.

**Comment by Rxann** [comment]
> Can't reproduce.

Hmm wierd, I just had this problem last night. Did you reproduce in a public session?

**Comment by gir489returns** [comment]
> > Can't reproduce.
> 
> Hmm wierd, I just had this problem last night. Did you reproduce in a public session?

I had a friend join me, and I set him a CEO invite, he accepted.

**Comment by Rxann** [comment]
Block CEO money seems to be the culprit of this issue.

**Comment by gir489returns** [comment]
> Block CEO money seems to be the culprit of this issue.

Works as intended then.

**Comment by Yimura** [comment]
Probably best to enable the notification so you’re aware of someone trying to invite you.

**Comment by Rxann** [comment]
The notification is enabled.
