### ISSUE TITLE
[Bug]: Radio Station Syncing Problems

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#2939]
### Describe the bug

When I play with my friend without the menu, we have the same songs playing on the radio, but when I use YimMenu we have different songs playing at different times.

### Steps To Reproduce

1. Get into a vehicle with a player
2. Observe the song that is playing for you
3. Observe the song that is playing for them

### Expected Behavior

You are able to hear the same songs at the same time as other players.

### Logs and/or screenshots

N/A

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

May be OOM kick related, idk. I know that OOM kick protection blocks excessive radio sync requests.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Does this occur without YimMenu?

**Comment by Rxann** [comment]
> Does this occur without YimMenu?

No

**Comment by TheGreenBandit** [comment]
Are u using mobile radio?

**Comment by Rxann** [comment]
> Are u using mobile radio?

Nope!

**Comment by gir489returns** [comment]
This might be because we just return true for MsgRadioStationSyncRequest if the player variable is a nullptr, which is set by finding the host by iterating all the players and finding who has the host token.

**Comment by lonelybud** [comment]
> MsgRadioStationSyncRequest

this happens during relay connection to that player.

Edit: you wont even log there messages when they are in relay connection with you

**Comment by lonelybud** [comment]
the only thing i dont understand is how the game is able to recognize the correct person (who we are connected to via relay connection bcz he is so long distance separated) who sent the chat but the menu cannot figure out.

**Comment by gir489returns** [comment]
> the only thing i dont understand is how the game is able to recognize the correct person (who we are connected to via relay connection bcz he is so long distance separated) who sent the chat but the menu cannot figure out.

It's done through the R* servers, which we are discussing rolling back to in #2928

**Comment by Rxann** [comment]
> This might be because we just return true for MsgRadioStationSyncRequest if the player variable is a nullptr, which is set by finding the host by iterating all the players and finding who has the host token.

So if I am understanding correctly, we would just return false for the syncs that are not from the player that is not nullptr?

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/1fa3ef8a453632b44fd5dfcfc7434826323483e4/src/hooks/protections/receive_net_message.cpp#L233-L240

**Comment by Rxann** [comment]
> https://github.com/YimMenu/YimMenu/blob/1fa3ef8a453632b44fd5dfcfc7434826323483e4/src/hooks/protections/receive_net_message.cpp#L233-L240

Yes, we should be returning false there? I will work on it later today if so.

**Comment by lonelybud** [comment]
> Yes, we should be returning false there?

someone can OMM kick you easily then

**Comment by Rxann** [comment]
> > Yes, we should be returning false there?
> 
> 
> 
> someone can OMM kick you easily then

I will test it out.

**Comment by lonelybud** [comment]
> It's done through the R* servers, which we are discussing rolling back to in #2928

we cannot even send private messages to peer relay connected players.

**Comment by maybegreat48** [comment]
> > https://github.com/YimMenu/YimMenu/blob/1fa3ef8a453632b44fd5dfcfc7434826323483e4/src/hooks/protections/receive_net_message.cpp#L233-L240
> 
> Yes, we should be returning false there? I will work on it later today if so.

Yeah, in hindsight, returning true there wasn't the best idea. You can add a global rate limit to avoid being kicked, but still let legit messages through. Return false isn't any different from returning true for this hook

**Comment by lonelybud** [comment]
>  Return false isn't any different from returning true for this hook

what about little corrections?
```C++
			case rage::eNetMessage::MsgRadioStationSyncRequest:
			{
				static rate_limiter unk_player_radio_requests{2s, 2};

				if (unk_player_radio_requests.process())
				{
					if (unk_player_radio_requests.exceeded_last_process())
					{
						// Make a translation for this new OOM kick protection
						g_notification_service.push_error("PROTECTIONS"_T.data(), "OOM_KICK"_T.data());
					}
                                        return true;
				}
				break;
			}
```

**Comment by maybegreat48** [comment]
Yeah, that should work

**Comment by Rxann** [comment]
I have a PR drafted and I will add this change
