### ISSUE TITLE
[Bug]: Game Crash

### ISSUE THREAD

**Issue by poweromania** [Yimura/YimMenu#2945]
### Describe the bug

The Game crashes when injecting after latest rockstar update

### Steps To Reproduce

1. Start the game
2 Inject

### Expected Behavior

not to crash

### Logs and/or screenshots

```
Apparently, the log is too long to be pasted here so i will upload it here instead https://gist.github.com/poweromania/1abb97861ae4076a3f2ce52f48e2d4e9


```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by prince4589** [comment]
had the same issue, game was working fine before a ~300MB ish update.
i think the error might be this line

[10:42:30.9160867][WARN/batch.hpp:113] Failed to find 'RS'.

**Comment by TBNRkenhutt** [comment]
Same here, i also have the same problem with the game crashing after i inject the mod menu.
This is after the "small" update on rockstar stuff.

**Comment by nlmfor** [comment]
same here please fix

**Comment by JBoogieman** [comment]
Anyone have theirs working yet?

**Comment by 4157haifeng** [comment]
我两台电脑上都试了，游戏崩溃 无法注入，进入线上模式点击注入DLL 游戏就崩溃了 ，大佬赶快来修复吧。
