### ISSUE TITLE
[Improvement]: 

### ISSUE THREAD

**Issue by BURAKmen12** [Yimura/YimMenu#2947]
### Which feature
I have a crash problem, how can I fix it?

### Reason

a

### Additional context

a

**Comment by nlmfor** [comment]
same here. when i inject its just crashes

**Comment by BURAKmen12** [comment]
Nezaman duzelir acaba ya

16 Nis 2024 Sal 20:40 tarihinde nlmfor ***@***.***> şunu
yazdı:

**Comment by ghost** [comment]
You're supposed to state your issues in English so that people can understand you and actually help you.

**Comment by D-Borkan** [comment]
please just wait .. new update will be Release as soon as it is completed

**Comment by Asiamies** [comment]
> You're supposed to state your issues in English so that people can understand you and actually help you.

I think it's quite clear what he meant

**Comment by ghost** [comment]
> > You're supposed to state your issues in English so that people can understand you and actually help you.
> 
> I think it's quite clear what he meant

It was written in Turkish for me, no idea why.

**Comment by loveshacks** [comment]
You are supposed to provide descriptions of the issue, as well as logs from the Menu logs.

Rockstar launcher just pushed an update, Yim needs to compile a new version.

**Comment by wizvrd1** [comment]
Hello, I just opened YIM and I got a Windows Defender virus warning, does anyone know anything?

**Comment by dantheman89** [comment]
dont know what happen yim menu not working

**Comment by dantheman89** [comment]
yimmura plz fix this

**Comment by TwystedMind** [comment]
> dont know what happen yim menu not working
> 
> 

GTA Online was updated from v1.68 (3095) to v1.68 (3179), there were some changes that broke compatibility with YimMenu.  They are already aware of the issue and are in the process of fixing it.  There is already a ticket open keeping track of the progress.

The ticket tracking the progress of this issue is:  #2946

**Comment by Tayipc38** [comment]
No title no regard for due process and no clarification of your issue.
