### ISSUE TITLE
[Bug]: ingame_overlay can't closed

### ISSUE THREAD

**Issue by DSRC-L** [Yimura/YimMenu#2952]
### Describe the bug

struct ingame_overlay
			{
				bool opened                = false;
			}
When I set opend to false and inject the dll, this popup still appears (and I want to know which cpp file the hotkey click event is in).

### Steps To Reproduce

Enter the game and inject the dll

### Expected Behavior

Entering the game does not show this popup

### Logs and/or screenshots

![420140754](https://github.com/YimMenu/YimMenu/assets/80384227/cba27276-ff45-4512-ac77-c39cd92a5865)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
you should only create bug issue ticket for a feature that is not working.

**Comment by Yimura** [comment]
@DSRC-L, changing the value in the CPP file is only setting the default option of the feature. You need to remove your settings file or remove that specific option from the settings file (allowing the menu to reset it).

To find where the value is used you can just check definitions which is an option any decent IDE has. Then again the issue appears to not be a problem with the menu rather someone not able to code properly.
