### ISSUE TITLE
[Bug]: Problem with Vehicle spawning

### ISSUE THREAD

**Issue by Fyfa4ok** [Yimura/YimMenu#2955]
### Describe the bug

When I go to my YimMenu I go to the Vehicle section, and I can’t spawn a vehicle because it says “No vehicle in the register”

### Steps To Reproduce

When I go to my YimMenu I go to the Vehicle section, and I can’t spawn a vehicle because it says “No vehicle in the register”

### Expected Behavior

Help me solve the problem, I want to spawn cars without problems

### Logs and/or screenshots

```
![изображение_2024-04-20_185357634](https://github.com/YimMenu/YimMenu/assets/167634793/d79f6312-3f6f-45b2-919f-ba318ebfbbcf)

<paste your logs here>
```

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
You are in single player...

**Comment by gir489returns** [comment]
This might be related to #1859 but the error says "No cars in registry." The game is supposed to generate a list of weapons/vehicles, which yours has not done, but we can't figure out why, because you posted a single screenshot and not your YimMenu log.

**Comment by TwystedMind** [comment]
After injecting the menu in Story Mode, open the menu and go to Settings > Cache > Rebuild Cache then check again.  Make sure the game is not paused while rebuilding the cache.

If after clicking Rebuild Cache it displays "0" next to each category, then try the following:

- Exit out of GTA and YimMenu
- Re-Launch GTA and load into Story Mode
- Open the Injector by right-clicking and selecting "Run As Administrator"
- Inject YimMenu.dll and see if the vehicle registry is showing properly.

**Comment by Tayipc38** [comment]
I can't spawn cars with the command in singleplayer too.

**Comment by Yimura** [comment]
Yeah vehicle spawning is broken in single player, haven't debugged yet why. Probably related to the recent changes that were made to resolve the issues with the vehicle previewer.

However this user is mainly talking about the issue where YimMenu is unable to open the rpf files on disk and thus not able to generate a vehicle/ped/weapon cache.

**Comment by gir489returns** [comment]
I am able to spawn vehicles just fine in single player but I use persist vehicle.

**Comment by Yimura** [comment]
> I am able to spawn vehicles just fine in single player but I use persist vehicle.

Yeah there's just some problem with the actual implementation of how the spawn function is called in the spawn command.
```
spawn adder
```
doesn't work in single player for example.

**Comment by gir489returns** [comment]
> > I am able to spawn vehicles just fine in single player but I use persist vehicle.
> 
> Yeah there's just some problem with the actual implementation of how the spawn function is called in the spawn command.
> 
> ```
> spawn adder
> ```
> 
> doesn't work in single player for example.

I have debugged the issue, and it stems from get_spawn_location returning 0,0,0. Maybe this only works in MP?
