### ISSUE TITLE
[Bug]: Does not work on latest patch. 

### ISSUE THREAD

**Issue by tommyBELLOFIGO** [Yimura/YimMenu#2958]
### Describe the bug

Rockstar, only to fuck with modders made a new patch for the game.
There is no difference except some awards in the new patch.
I know you, Yimura, will fix it, but could you give us a date or could you tell us why not? 
Thank you for reading this.

### Steps To Reproduce

1. Inject YimMenu.
2. Doesn't work and closes the game.

### Expected Behavior

Injecting doesn't work and closes the game.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

Italian

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
No logs provided, useless issue.

Make sure that you've got the latest version of YimMenu installed. We released a fix for the recent update of GTA that dropped.

Edit:
And if it still crashes, give us a log file!!!

**Comment by D-Borkan** [comment]
it work fine, if still crash your game when inject try use another injector 
and make sure to share your log file direct when the game is cloesd

**Comment by tommyBELLOFIGO** [comment]
Sorry, i've realised minutes later writing this that i had the previous version
