### ISSUE TITLE
[Request]: Pls add blame {Player} for {action/message}

### ISSUE THREAD

**Issue by tommyBELLOFIGO** [Yimura/YimMenu#2960]
### Problem

Self explanatory 

### Solution

I'd like a section to be added to the online players menu.
For example Blame and a list of things you could blame people for.

### Reason

Because it would be fun and interesting to troll fruends and randoms.
Other menus already do this and there is even a protection against it.

**Comment by ghost** [comment]
This feature was here a long time ago but has been removed because it's toxic, and leads players to insult or report somebody who did nothing.

**Comment by Yimura** [comment]
Exactly as @Alex-MHR  said.
