### ISSUE TITLE
[Build]: error during compiling

### ISSUE THREAD

**Issue by SirGarmy** [Yimura/YimMenu#2965]
### Describe the build issues

I have an odd issue. Every time I try to compile menu using Visual Studio 22 it gets stuck with those errors. I've recently reinstaled my system and this error is since that. IDK what logs or files you guys need to help me figure this out. I've tried completely delete all files and downloading again with no succes

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://github.com/YimMenu/YimMenu/assets/91479717/496ed178-f66f-491e-b7a0-961f64497c79)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by ghost** [comment]
Does the build process also fail in Release Mode ?

**Comment by SirGarmy** [comment]
Yes, tried all modes it offers with same result

**Comment by Yimura** [comment]
The async logger dependency appears to not have been setup correctly. I’d assume git comes preinstalled with Visual Studio as it has an interface for it in the app.

Did you actually follow the setup guide? Git is a requirement to setup the build environment.

**Comment by SirGarmy** [comment]
I belive u mean this 
![image](https://github.com/YimMenu/YimMenu/assets/91479717/01d0cb6e-a579-4215-9da0-4a331f2d880d)
If so I instaled it
Is there any way of getting already compiled file?

**Comment by Yimura** [comment]
You mean just the DLL? That’s what the release section is for yes.

**Comment by SirGarmy** [comment]
I'm so sorry that I have to ask this but I can't find release section

**Comment by ghost** [comment]
Right here : https://github.com/YimMenu/YimMenu/releases/tag/nightly

**Comment by SirGarmy** [comment]
Thx so much
