### ISSUE TITLE
[Improvement]: Vehicle Handling Tab

### ISSUE THREAD

**Issue by xesdoog** [Yimura/YimMenu#2966]
### Which feature

Additional sliders under Vehicle -> Handling -> Suspension that control front/rear camber and front/rear track width.

### Reason

>gir489 please don't kill me if this is too stupid of a request.

I previously opened a discussion about this which was ignored and hurt my feelies a little bit but believe me, a stancer would be a huge addition because every car enthusiast loves it and you guys have made all the work and it's goddamn beautiful. The only things that would turn the actual handling tab into a stancer is those aforementioned options. That's it.

### Additional context

I don't like asking for too much but my journey towards having a stancer with YimMenu first started a few months ago with me trying to make an ASI loader for the menu so I can load VStancer but I failed miserably because I don't know anything about any of the C languages. Then I tried writing something similar in Lua but quickly realized that everything I needed was under CFX natives so it was impossible. Lastly, I was browsing through some of Yimura's GTAV-Classes and saw some stuff relating to exactly what I needed so this is my last straw. I am now gonna attempt to bribe you with sexy car pics.

This is a Karin 190z with a widebody kit. Notice how ugly the default wheel fitment is:
![x1boce2nm0s41](https://github.com/YimMenu/YimMenu/assets/66764345/d7025990-00ba-440e-8d7c-dfe9f530aa77)

This is the same car with modified camber, wheel width and track width:
![25496443648_4c66da2419_b](https://github.com/YimMenu/YimMenu/assets/66764345/3da10091-d138-4717-9a1c-13369384f2b1)

**Comment by rkwapisz** [comment]
Are these Benny's mods that you're describing?

**Comment by xesdoog** [comment]
> You are always free to do the work yourself and submit a PR and we'll iron out the rough edges with you together.
> 
> However, as I've stated on numerous other tickets, we have too many fires to put out right now, and not enough people who care. Right now, it's just me, myself and I working on the project.

Thank you for everything you do. I really appreciate each and everyone of you ❤️

I'll try to get myself to learn the fundamentals at least so I could help with anything I can

**Comment by xesdoog** [comment]
> Are these Benny's mods that you're describing?

No these are similar to what we currently have in the menu to modify acceleration, suspension, steering angle, etc..
These are the [classes](https://github.com/Yimura/GTAV-Classes/blob/master/vehicle/CCarHandlingData.hpp#L51) that I was referring to.
And this is [VStancer](https://github.com/ikt32/GTAVStancer).

**Comment by xesdoog** [comment]
maybegreat48 has made an [ASI loader for YimMenu](https://github.com/maybegreat48/YimASI) that can load VStancer.

*closing as resolved*.
