### ISSUE TITLE
[Bug]: After new nightly, something going wrong with money

### ISSUE THREAD

**Issue by heni015** [Yimura/YimMenu#2968]
### Describe the bug

After new nightly i got problem with font of GTA money
![image](https://github.com/YimMenu/YimMenu/assets/49375523/e89ed980-7c05-422a-93ab-9804598b3e7f)
I have GTA in Polish language, testing Yim translated, but nightly one back was worked fine

### Steps To Reproduce

Using Xenos,
Injecting,
Press Z to check amount.

### Expected Behavior

Normal functioning of subtitles like version form 21.04 after injecting and checking:
![image](https://github.com/YimMenu/YimMenu/assets/49375523/b831415c-2ccd-46c2-8f1a-d4c836b936bc)

### Logs and/or screenshots

nothing at logs :x all fine

### Store

Rockstar

### Language

Polish

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
I was afraid of this. Does Poland use commas or decimals for placements of thousands? I wanted @Yimura to test the decimal scenario, since I didn't know if it would handle it, and I guess it doesn't.

**Comment by Sheeeeit** [comment]
> I was afraid of this. Does Poland use commas or decimals for placements of thousands? I wanted @Yimura to test the decimal scenario, since I didn't know if it would handle it, and I guess it doesn't.

Same for me with ENG language:
![изображение](https://github.com/YimMenu/YimMenu/assets/111229260/3f4579fa-628f-4783-87dc-4b0e0130ff96)

P.S: Possible apply this update for casino chips?

**Comment by heni015** [comment]
Now that works great, if I can ask, in this binary what u pull there is also a last nightly included? Cuz size of file was smaller then I was askin.

**Comment by gir489returns** [comment]
@Sheeeeit @ShinyWasabi was able to get your request working.

![image](https://github.com/YimMenu/YimMenu/assets/100792176/db62214c-422d-4ebe-af26-e2b90a40b68c)

**Comment by heni015** [comment]
Hmm... it still doesn't work in the new nightly, now I checked that it is newer nightly.
![image](https://github.com/YimMenu/YimMenu/assets/49375523/6604d392-f74f-486f-9bd8-5798e14230e0)

**Comment by gir489returns** [comment]
> Hmm... it still doesn't work in the new nightly, now I checked that it is newer nightly. ![image](https://private-user-images.githubusercontent.com/49375523/325279802-6604d392-f74f-486f-9bd8-5798e14230e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzI2NDMsIm5iZiI6MTcxMzk3MjM0MywicGF0aCI6Ii80OTM3NTUyMy8zMjUyNzk4MDItNjYwNGQzOTItZjc0Zi00ODZmLTliZDgtNTc5OGUxNDIzMGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTgxYjg5MzU4ZWIyYjQxNTljYWNkZTczMzVjMmQxMjhkOGUzYThiZmMzODg2MzhlMmY0ZWU0N2M4MGY3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BE4tqSYJyCLIsoGTY3t8dqvp65OGPDPJUa4Fph4RCjY)

Try this https://github.com/YimMenu/YimMenu/pull/2969#issuecomment-2073944547

**Comment by heni015** [comment]
Yes, I did it before, but in the latest edition of the evening I thought it was solved ^^

**Comment by gir489returns** [comment]
The changes have not been merged yet.
