### ISSUE TITLE
How to block this invalid pickup

### ISSUE THREAD

**Issue by beast177** [Yimura/YimMenu#30]
Idk how to block this PickUp basically it crashes the game `vw_prop_vw_colle_prbubble` I would be much grateful if someone finds a fix

**Comment by Yimura** [comment]
Possibly by using this:
https://github.com/Yimura/YimMenu/blob/bac623ed8b1e204221e9847039c4d66a91bc80ee/BigBaseV2/src/hooks/received_event.cpp#L95-L112

**Comment by beast177** [comment]
thanks!!!,  I'll use this, cuz modders crashing is unbearable

**Comment by MoneyDropLobby** [comment]
My implementation:

 

> case RockstarEvent::GIVE_PICKUP_REWARDS_EVENT:

		{
			uint32_t amount, hash;
			buffer->ReadDword(&amount, 3);
			buffer->ReadDword(&hash, 32);
			switch (hash)
			{
			case RAGE_JOAAT("vw_prop_vw_colle_prbubble"):
				char crash[64];
				strcpy(crash, "~g~BLOCKED Pickup Crash ~s~\nFrom: <C>");
				strcat(crash, source_player->get_name());
				strcat(crash, "</C>");
				LOG(INFO) << crash;
				g_pointers->m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);
				notify::blocked_event(event_name, source_player->player_id);
				return false;
			default:
				LOG(INFO) << "Pickup Crash detected with hash: %d", hash;
				buffer->Seek(0);
				return true;
			}
		}

**Comment by Yimura** [comment]
Since this isn't an issue related to YimMenu, I will be closing it. You're free to contribute the code to this protection in a PR.
