### ISSUE TITLE
[Bug]: Game crash a few seconds after injection

### ISSUE THREAD

**Issue by coprofago** [Yimura/YimMenu#3012]
### Describe the bug

Game crash a few seconds (not instantly) after injection, with this new version of yimmenu.dll.

### Steps To Reproduce

1. Start game
2. Wait game to go online
3. Inject dll with xenos
4. Wait a few seconds (either doing or not doing anything)
5. Game crash

### Expected Behavior

Game to run normally

### Logs

[cout.zip](https://github.com/YimMenu/YimMenu/files/15170604/cout.zip)

### Screenshots / Video

![Capturar](https://github.com/YimMenu/YimMenu/assets/106185220/62d5cfdb-f2b3-494c-bb21-99de3813c5cc)

### Store

Epic Games

### Language

Brazilian Portuguese

### YimMenu Language

Portuguese (BR)

### Additional context

It generates a cout.log with 200mb size (weird)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Any change if you inject in single player or on the main menu?

**Comment by coprofago** [comment]
i will test this, just a minute

**Comment by coprofago** [comment]
i tried with single player and it worked well, i played a few minutes normally, tested some little features like god mode, infinite ammo, horn boost, and all worked well, after this i tried to go online and after few seconds it crashed

**Comment by Yimura** [comment]
Could you upload the log file of that one as well?

**Comment by coprofago** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/15170759/cout.log)

**Comment by Yimura** [comment]
@coprofago could you send your setting.json here? You might need to change the file extension to .txt before being able to upload it (or zip it alternatively). After which you can just delete the file and see if that fixes the issue in question (unlikely to resolve the issue but it's worth a try).


For developers on YimMenu, seems something is throwing an exception in YimMenu. ~~Granted that his YimMenu is 2 days old (last release was yesterday).~~ ff55db8fa3ae1721dbcd166ed2c26407844e325e
Interesting stack trace:
```
Dumping registers:
RAX: 0x0
RCX: 0x0
RDX: 0x0
RBX: 0x7FFEFF0B4148
RSI: 0x4DB28FF290
RDI: 0x19930520
RSP: 0x4DB28FF130
RBP: 0x4DB28FF480
R8:  0x7FFF0C4D8912
R9:  0x12
R10: 0x7FFF0C4D67B6
R11: 0x6A6
R12: 0xFFFFFFFFFFFFFFFF
R13: 0x80
R14: 0x0
R15: 0x7FFEC24F9D18
Dumping stacktrace:
[0]	KERNELBASE.dll RaiseException
[1]	VCRUNTIME140.dll CxxThrowException
[2]	MSVCP140.dll std::_Xruntime_error
[3]	YimMenu.dll+0x18D55A 0x7FFEC1ECD55A
[4]	YimMenu.dll+0x18B2A4 0x7FFEC1ECB2A4
[5]	YimMenu.dll+0x18B504 0x7FFEC1ECB504
[6]	GTA5.exe+0x2F70C3 0x7FF7A1E270C3
[7]	GTA5.exe+0x2EDA6A 0x7FF7A1E1DA6A
[8]	GTA5.exe+0x1633449 0x7FF7A3163449
[9]	GTA5.exe+0x1632C7F 0x7FF7A3162C7F
[10]	GTA5.exe+0x276A4 0x7FF7A1B576A4
[11]	GTA5.exe+0x20D8B 0x7FF7A1B50D8B
[12]	GTA5.exe+0x1632888 0x7FF7A3162888
[13]	GTA5.exe+0x1494 0x7FF7A1B31494
[14]	GTA5.exe+0x130904F 0x7FF7A2E3904F
[15]	GTA5.exe+0x1825DCC 0x7FF7A3355DCC
[16]	KERNEL32.DLL BaseThreadInitThunk
[17]	ntdll.dll RtlUserThreadStartbad locale name

--------End of exception--------
```

**Comment by Yimura** [comment]
Most likely culprit without analyzing YimMenu.dll:
https://github.com/YimMenu/YimMenu/blob/d1d72e54b99c18b36d72cee1cc1623f0f40c3cb1/src/util/sync_trees.hpp#L547

Based on:
- Only in online
- Menu operates correctly in single player
- Only runtime_error that is an online only component that isn't triggered while initializing YimMenu
- Exception occurs infinitely

**Comment by coprofago** [comment]
> @coprofago could you send your setting.json here? You might need to change the file extension to .txt before being able to upload it (or zip it alternatively). After which you can just delete the file and see if that fixes the issue in question (unlikely to resolve the issue but it's worth a try).
> 
> For developers on YimMenu, seems something is throwing an exception in YimMenu. ~Granted that his YimMenu is 2 days old (last release was yesterday).~ [ff55db8](https://github.com/YimMenu/YimMenu/commit/ff55db8fa3ae1721dbcd166ed2c26407844e325e) Interesting stack trace:
> 
> ```
> Dumping registers:
> RAX: 0x0
> RCX: 0x0
> RDX: 0x0
> RBX: 0x7FFEFF0B4148
> RSI: 0x4DB28FF290
> RDI: 0x19930520
> RSP: 0x4DB28FF130
> RBP: 0x4DB28FF480
> R8:  0x7FFF0C4D8912
> R9:  0x12
> R10: 0x7FFF0C4D67B6
> R11: 0x6A6
> R12: 0xFFFFFFFFFFFFFFFF
> R13: 0x80
> R14: 0x0
> R15: 0x7FFEC24F9D18
> Dumping stacktrace:
> [0]	KERNELBASE.dll RaiseException
> [1]	VCRUNTIME140.dll CxxThrowException
> [2]	MSVCP140.dll std::_Xruntime_error
> [3]	YimMenu.dll+0x18D55A 0x7FFEC1ECD55A
> [4]	YimMenu.dll+0x18B2A4 0x7FFEC1ECB2A4
> [5]	YimMenu.dll+0x18B504 0x7FFEC1ECB504
> [6]	GTA5.exe+0x2F70C3 0x7FF7A1E270C3
> [7]	GTA5.exe+0x2EDA6A 0x7FF7A1E1DA6A
> [8]	GTA5.exe+0x1633449 0x7FF7A3163449
> [9]	GTA5.exe+0x1632C7F 0x7FF7A3162C7F
> [10]	GTA5.exe+0x276A4 0x7FF7A1B576A4
> [11]	GTA5.exe+0x20D8B 0x7FF7A1B50D8B
> [12]	GTA5.exe+0x1632888 0x7FF7A3162888
> [13]	GTA5.exe+0x1494 0x7FF7A1B31494
> [14]	GTA5.exe+0x130904F 0x7FF7A2E3904F
> [15]	GTA5.exe+0x1825DCC 0x7FF7A3355DCC
> [16]	KERNEL32.DLL BaseThreadInitThunk
> [17]	ntdll.dll RtlUserThreadStartbad locale name
> 
> --------End of exception--------
> ```

OK, i cant do that right now, im not home, when i get back i wll do that, TY

**Comment by xiaoxiao921** [comment]
@Yimura it literally say in the stack trace bad locale name

**Comment by Yimura** [comment]
> @Yimura it literally say in the stack trace bad locale name

Ah, I guess this is because of the money formatting in online then.

**Comment by gir489returns** [comment]
> > @Yimura it literally say in the stack trace bad locale name
> 
> Ah, I guess this is because of the money formatting in online then.

I doubt it because when I returned a corrupted message from the function it failed safely by rendering the unknown characters as boxes.

**Comment by xiaoxiao921** [comment]
> > @coprofago could you send your setting.json here? You might need to change the file extension to .txt before being able to upload it (or zip it alternatively). After which you can just delete the file and see if that fixes the issue in question (unlikely to resolve the issue but it's worth a try).
> > For developers on YimMenu, seems something is throwing an exception in YimMenu. ~Granted that his YimMenu is 2 days old (last release was yesterday).~ [ff55db8](https://github.com/YimMenu/YimMenu/commit/ff55db8fa3ae1721dbcd166ed2c26407844e325e) Interesting stack trace:
> > ```
> > Dumping registers:
> > RAX: 0x0
> > RCX: 0x0
> > RDX: 0x0
> > RBX: 0x7FFEFF0B4148
> > RSI: 0x4DB28FF290
> > RDI: 0x19930520
> > RSP: 0x4DB28FF130
> > RBP: 0x4DB28FF480
> > R8:  0x7FFF0C4D8912
> > R9:  0x12
> > R10: 0x7FFF0C4D67B6
> > R11: 0x6A6
> > R12: 0xFFFFFFFFFFFFFFFF
> > R13: 0x80
> > R14: 0x0
> > R15: 0x7FFEC24F9D18
> > Dumping stacktrace:
> > [0]	KERNELBASE.dll RaiseException
> > [1]	VCRUNTIME140.dll CxxThrowException
> > [2]	MSVCP140.dll std::_Xruntime_error
> > [3]	YimMenu.dll+0x18D55A 0x7FFEC1ECD55A
> > [4]	YimMenu.dll+0x18B2A4 0x7FFEC1ECB2A4
> > [5]	YimMenu.dll+0x18B504 0x7FFEC1ECB504
> > [6]	GTA5.exe+0x2F70C3 0x7FF7A1E270C3
> > [7]	GTA5.exe+0x2EDA6A 0x7FF7A1E1DA6A
> > [8]	GTA5.exe+0x1633449 0x7FF7A3163449
> > [9]	GTA5.exe+0x1632C7F 0x7FF7A3162C7F
> > [10]	GTA5.exe+0x276A4 0x7FF7A1B576A4
> > [11]	GTA5.exe+0x20D8B 0x7FF7A1B50D8B
> > [12]	GTA5.exe+0x1632888 0x7FF7A3162888
> > [13]	GTA5.exe+0x1494 0x7FF7A1B31494
> > [14]	GTA5.exe+0x130904F 0x7FF7A2E3904F
> > [15]	GTA5.exe+0x1825DCC 0x7FF7A3355DCC
> > [16]	KERNEL32.DLL BaseThreadInitThunk
> > [17]	ntdll.dll RtlUserThreadStartbad locale name
> > 
> > --------End of exception--------
> > ```
> 
> OK, i cant do that right now, im not home, when i get back i wll do that, TY

The crash described here is because the user doesn't have the locale installed

**Comment by gir489returns** [comment]
> The crash described here is because the user doesn't have the locale installed

So this is the reverse of the issue of forcing en_US. I tried to have C++ determine which locale the user had and just use that to instantiate from their own machine, but commas do not work in the dollar font they use. We could reimplement the code manually to do the commas and crap, but that seems excentric to do.

**Comment by xiaoxiao921** [comment]
std::locale(".utf8")

And wrap it around a try catch. Cause locale ctor will throw if the user don't have the locale installed

**Comment by gir489returns** [comment]
> std::locale(".utf8")
> 
> And wrap it around a try catch. Cause locale ctor will throw if the user don't have the locale installed

That will just grab the user's locale again same thing as "". Doesn't solve the issue. Try catch is stupid, you should never use that in production and I detest the idea of even using that as a solution to the edge case.

We should either enforce that users install en_US as we already do with the project now because we require certain English assets to be loaded from Windows, or we reimplement this by hand, which I really don't want to.

**Comment by xiaoxiao921** [comment]
I thought the purpose was to get localized money for user? Writing .UTF8 as the locale will do as intended

**Comment by gir489returns** [comment]
> I thought the purpose was to get localized money for user? Writing .UTF8 as the locale will do as intended

See #2968

It originally behaved like that but it doesn't work.

**Comment by xiaoxiao921** [comment]
Oh ok I didnt understand. Now I get it.
Well if the user doesn't have en_US utf8 then just disable this feature and tell them to install it if they want comma separated numbers? Or yeah reimplement it.

**Comment by gir489returns** [comment]
We could probably remove the dependency on std::locale and just force the use_commas parameter to true, however, we'd still have to deal with it for chips manually.
