### ISSUE TITLE
[Request]: Health Regeneration

### ISSUE THREAD

**Issue by C47CH-71** [Yimura/YimMenu#3015]
### Problem

I would like to have this option from the main YimMenu window, so as not to wait for a new update of a custom module every time.
Why not add this functionality to YimMenu?

### Solution

There is a custom Script for Health (and Armor) Regeneration - HarmlessScript.lua
I find this script very useful for myself personally, just because of this feature.

p.s, there is also a very cool implementation of the ability to turn on the Drift mode - by holding down the 'Shift' key! (awesome)

### Reason

Because this is really missing, as they say "out of the box solution"

### Additional context

This script: https://github.com/YimMenu-Lua/Harmless-Scripts/tree/v1.2.1

p.p.s. sorry for my english, I tried my best)
thx

**Comment by GreySideMM** [comment]
Do you mean slow generation or just set full health on every tick?
Latter is already available, tho a bit hidden / not too obvious: You can set it for every player - including yourself! - in the player tab menu. It's the "semi-godmode" option.

**Comment by gir489returns** [comment]
If it's already a script, why would we implement it into the menu itself when the purpose of the Lua engine was to not do this?

**Comment by rkwapisz** [comment]
Since this is something a LUA already does, I'd recommend closing this as won't do. If there are issues with the development of the LUA script or scheduled updates, those should be posted to the relevant script's github.

There is little to no value implementing existing LUA script features directly into Yim, and will only cause unnecessary bloat.

**Comment by xesdoog** [comment]
Just use Harmless's scripts? You don't need to wait for an update to use it unless Harmless adds a new feature.
If you only want to use autoheal then here's one:

Go to

     %AppData%\YimMenu\scripts

Create a new text file and paste this inside it:

```lua

autoregen = gui.get_tab("GUI_TAB_SELF"):add_tab("Auto-Heal")
local autoheal = false
local chkbxTxt = "STRING"
autoregen:add_imgui(function()
  ImGui.TextWrapped("Automatically Heal Yourself Over Time");ImGui.Spacing()
  regen, used = ImGui.Checkbox("##enable", regen, true);ImGui.SameLine();ImGui.Text(chkbxTxt)
    if regen then
      autoheal = true
      chkbxTxt = "On"
    else
      autoheal = false
      chkbxTxt = "Off"
    end
end)
script.register_looped("healme", function(ah)
  ah:yield()
  if autoheal and not ENTITY.IS_ENTITY_DEAD(self.get_ped()) then
    local maxHp  = ENTITY.GET_ENTITY_MAX_HEALTH(self.get_ped())
    local myHp   = ENTITY.GET_ENTITY_HEALTH(self.get_ped())
    local myArmr = PED.GET_PED_ARMOUR(self.get_ped())
    if math.floor(myHp) < maxHp and math.floor(myHp) > 0 then
      ENTITY.SET_ENTITY_HEALTH(self.get_ped(), myHp + 1, 0, 0)
      ah:sleep(100)
    end
    if myArmr == nil then
      PED.SET_PED_ARMOUR(self.get_ped(), 10)
    elseif math.floor(myArmr) < 100 then
      PED.ADD_ARMOUR_TO_PED(self.get_ped(), 1)
      ah:sleep(100)
    end
  end
end)
```
Change its extension from .txt to .lua and save it. This will add a checkbox in the **Self tab** of YimMenu:
![Screenshot 2024-05-04 102629](https://github.com/YimMenu/YimMenu/assets/66764345/28f5e093-b01e-46fe-aaf5-d4ad470e4a17)

This will not save your choice for the next load so you will have to activate it every time you inject. If you want it to be always active then remove the tab part and only keep the looped script without the `if autoheal` statement like so: 

```lua
script.register_looped("healme", function(ah)
  ah:yield()
  if not ENTITY.IS_ENTITY_DEAD(self.get_ped()) then
    local maxHp  = ENTITY.GET_ENTITY_MAX_HEALTH(self.get_ped())
    local myHp   = ENTITY.GET_ENTITY_HEALTH(self.get_ped())
    local myArmr = PED.GET_PED_ARMOUR(self.get_ped())
    if math.floor(myHp) < maxHp and math.floor(myHp) > 0 then
      ENTITY.SET_ENTITY_HEALTH(self.get_ped(), myHp + 1, 0, 0)
      ah:sleep(100)
    end
    if myArmr == nil then
      PED.SET_PED_ARMOUR(self.get_ped(), 10)
    elseif math.floor(myArmr) < 100 then
      PED.ADD_ARMOUR_TO_PED(self.get_ped(), 1)
      ah:sleep(100)
    end
  end
end)
```
