### ISSUE TITLE
[Improvement]: Add more options to react to spammers

### ISSUE THREAD

**Issue by Kurd1stan** [Yimura/YimMenu#3026]
### Which feature

As far as I understand, we can only kick the chat of spammers, but there is no way, for example, to add them to the database, set a timeout, block joining, etc. I think it’s not difficult to add a “chat spam” section to the reaction and the player will independently choose what to do. And remove the checkbox for automatic kicking of spammers in the Network section and set it as default in reactions.

### Reason

I think it would be more logical.

### Additional context

Or, to avoid the hassle altogether, move it to the Reactions/Moder Detection section.

**Comment by lonelybud** [comment]
i think they are automatically added to database and blocked right?

**Comment by Kurd1stan** [comment]
> i think they are automatically added to database and blocked right?

As far as I understand, the menu simply kicks them but does not add them to the database, but when the session is again filled to 30 players, the same spammers enter the session again

**Comment by lonelybud** [comment]
> As far as I understand, the menu simply kicks them but does not add them to the database,

yes you are right. There should be checkbox to add them to database and block them. This is a problem mostly with asian lobbies where there are lot of spammers and the spammers list keeps building up
