### ISSUE TITLE
[Bug]: Yim Menu crashing even on story mode

### ISSUE THREAD

**Issue by RealAspidiske** [Yimura/YimMenu#3038]
### Describe the bug

I've been reading the github issues and followed what some people mentioned like starting yim menu on story mode or making the Direct X to 11. However, it's still crashing whenever I inject it with either Xenos 64 or Xenos exe only. I added the Xenos log here as mentioned. I am using the latest one in this repository.

### Steps To Reproduce

1. Run the game
2. Go to story mode
3. Run Xenos 64 or Xenos and inject yim menu dll on GTA 5 process

### Expected Behavior

The game will instantly crash

### Logs

[Xenos.log](https://github.com/YimMenu/YimMenu/files/15200761/Xenos.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Unsure where you see xenos log mentioned, it clearly asks for the YimMenu log in the section description.

![image](https://github.com/YimMenu/YimMenu/assets/24669514/5c91b645-0a97-43d7-95c9-d05d1d3ef82d)

**Comment by ghost** [comment]
reading is hard :(

**Comment by RealAspidiske** [comment]
Sorry, it was a mistake on my end. Here's the yim menu log. No need to be edgy. @eggrolls-repu 
[cout.txt](https://github.com/YimMenu/YimMenu/files/15206440/cout.txt)

**Comment by GreySideMM** [comment]
Your build is a freaking month old. A docent fixes and changes related to crashes have been made in this time. So this issue is invalid.
Check if your injector uses the correct file in case you actually regularly download the latest release.

**Comment by RealAspidiske** [comment]
Yeah that actually is the issue and I just thought of re downloading the dll before going back to this thread. @GreySideMM Thanks for actually replying properly to me.
