### ISSUE TITLE
[Bug]: Has anyone encountered the wanted level bug?

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3040]
### Describe the bug

I once dragged the police wanted level slider, first to 5 and then to zero. And now all the time when I restart the game or re-inject anti-cheat, the police do not react to me at all. Unless I get into someone’s car who is already wanted by the police.

### Steps To Reproduce

1. Move the slider from 0 to any value
2. Play for a while and return to zero and your wanted level will disappear.
3. Restart the game and inject anti-cheat and the police will not respond to you.

### Expected Behavior

I think it’s worth adding the ability to hide the slider, for example if you add a checkbox “Set a specific wanted level” or something like that and then the slider appears. If the checkbox is inactive, it will be possible to come to the attention of the police. It seems to me that this is simply saved to the settings file, but the checkbox itself is inactive. Clicking the "Clear Wanted Level" button does not help.

### Logs

No logs sry(

### Screenshots / Video

![pic1](https://github.com/YimMenu/YimMenu/assets/168850586/d0fe8435-bdf0-4134-b08c-89c73010c9b2)

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
In general, I have to first turn on and then turn off the “never wanted level” checkbox after each injection into the game so that the wanted level can appear again. but there is another bug: when the wanted level does appear, the police still don’t spawn and after a while the wanted level disappears. the menu interferes with the spawning of police officers, and when you don’t inject the menu, everything is fine. Perhaps someone has also encountered this?

**Comment by tyackman** [comment]
I use never wanted; When playing without injecting, I can't walk into a store without them profiling me and calling the police :(

**Comment by ghost** [comment]
> I use never wanted; When playing without injecting, I can't walk into a store without them profiling me and calling the police :(



> I use never wanted; When playing without injecting, I can't walk into a store without them profiling me and calling the police :(

what is the point of the joke? Why is it that when the forced wanted level checkbox is not active, the slider forcibly sets the wanted level to zero. The slider should generally be inactive in such cases. and as a result, I play the “never wanted level” all the time, although this function is not active. So that the cops would start looking for me, every time I load the game, first turn on the “never wanted level” and then turn it off.

**Comment by rkwapisz** [comment]
Yeah... I don't use this feature much aside from the Never Wanted toggle, but looking at some of the code around this it's clear to me that it needs a refresh.

Stuff like this in clear_wanted.cpp... really?
`g_local_player && g_local_player !=nullptr`

And some of the logic is so weird with how the different options interact together. Makes the intended behavior completely unintuitive.

I'll see what I can do.
