### ISSUE TITLE
[Bug]: YimMenu Appears to Block Some Valid Start Script Events

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#3042]
### Describe the bug

YimMenu appears to be blocking some valid start script events even with protections disabled.
Behavior is consistent with https://github.com/YimMenu/YimMenu/issues/3001

![image](https://github.com/YimMenu/YimMenu/assets/13259220/0574e916-d8da-433e-9817-215cf369e6a2)

![image](https://github.com/YimMenu/YimMenu/assets/13259220/13d69935-7d6c-4cd0-9121-51221fb163f0)

Events launch fine if I'm host, but when I'm not, the following behavior occurs:
1) Quick Job launches and I am able to select a vehicle/loadout and proceed through the setup screens until "Ready to Play"
2) Once the event is launched by the host, the game appears to try to load for a few seconds
3) Fly-up freemode transition screen begins, and I'm placed back into freemode

Not all events seem to be affected, but it's been difficult to verify every event since people don't even play some of them anymore.

Series Events I've tested this with (I was not host in any of these sessions):
Open Wheel Series (didn't work, returned to freemode)
Drift Series (didn't work, returned to freemode)
Community Series (go kart race, worked, 2-person lobby and the other was host)
Stunt Series (didn't work, returned to freemode)

### Steps To Reproduce

1. Disable all protections
2. Enter a Series Mode event
3. Validate that you are not host
4. Wait for event to begin - notice YimMenu issues a Blocked Script notification in the event lobby (see screenshot)
5. Confirm that you get booted out back into freemode

### Expected Behavior

Event launches normally.

### Logs

Names redacted to protect the innocent.

```
[20:36:01.0295195][WARN/reaction.cpp:60] Received Start Script from [PLAYER] (1448XXXX)
[20:38:54.2340446][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:38:54.2342704][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:42:49.4592443][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:42:49.4593573][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":6934549,"type":3136273443,"cat":654913086,"pt":3274731811,"slot":0
[20:45:15.8930801][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:45:33.4695242][WARN/reaction.cpp:60] Received Start Script from [PLAYER] (14987XXXX)
[20:52:37.1679157][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:52:37.1680768][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
```

### Screenshots / Video

https://github.com/YimMenu/YimMenu/assets/13259220/f25d9673-80c4-406c-ad80-4ac510af32da

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
We should probably add a protection toggle for the Start Script protection @gir489returns

**Comment by maybegreat48** [comment]
Yeah we can disable the protection in activity sessions

**Comment by rkwapisz** [comment]
I'm close to publishing a PR for this, but am wondering if there is still value in keeping a toggle for script protection, or if it's just enough to check for NETWORK_IS_ACTIVITY_SESSION.

If I'm interpreting the implementation correct, the list of bad ids simply prevents us from being forcefully loaded into these scripts from freemode, correct?. But if we're in an activity session, then we should be good to go since that's what we want.

`bad_script_ids = {17 /*AM_PI_MENU*/, 20 /*fm_intro*/, 212 /*golf_mp*/, 214 /*tennis_network_mp*/, 215 /*Pilot_School_MP*/, 216 /*FM_Impromptu_DM_Controler*/, 217 /*fm_Bj_race_controler*/, 218 /*fm_deathmatch_controler*/, 221 /*FM_Race_Controler*/, 222 /*FM_Horde_Controler*/, 226 /*grid_arcade_cabinet*/, 227 /*scroll_arcade_cabinet*/, 229 /*road_arcade*/, 231 /*wizard_arcade*/, 235 /*ggsm_arcade*/, 236 /*puzzle*/, 238 /*SCTV*/};`

The toggle would disable script protection entirely, but this bug in particular seems like it would be fixed with just the latter. Any opinions about whether a toggle is overkill or not?

**Comment by maybegreat48** [comment]
Yeah. Modders obviously do exist in missions but they're generally less toxic and the script starter wouldn't do anything meaningful in activity sessions anyway. Modders actually have access to more script events and broadcast variables in missions that we don't even bother to protect

We don't need a toggle AFAIK after we add the activity session check
