### ISSUE TITLE
[Improvement]: Send SEXT - Toxic command

### ISSUE THREAD

**Issue by heni015** [Yimura/YimMenu#3046]
### Which feature

Choose player ->Toxic -> SEND SEXT
https://github.com/YimMenu/YimMenu/blob/d9576584f5750a69495e60ba002ea2c7cba9ddf4/src/backend/commands/player/toxic/send_sext.cpp#L14

### Reason

I don't want to be recognized as a modder, I prefer to calmly clean up the lobby and, for example, warn people when they do something wrong, not in the chat, and if there is such an option as SMS, it can be developed.
Obviously, when someone knows that a modder often looks askance wanna money or others ;d or u are attacked from other modders ;d.

Maybe we can do something like "Private messange" and at this SMS on phone add a choosen IMAGE (if it's possible) and input for own text of messange?

Sending an image is supposed to work, but it doesn't. Instead of the player's name, you can add a title of your choice, e.g. "ADMIN" "WARN", or your own nickname (of the person sending the message).

### Additional context

`Sends a random sext (with an image attachment) to the player` but messange was blink
![image](https://github.com/YimMenu/YimMenu/assets/49375523/c921423e-bc66-435c-bcc8-5970f36c2145)

**Comment by Friuuu** [comment]
This and send fake ban message have been broken for a few months now

**Comment by ghost** [comment]
Was sending silly texts really useful anyway?

**Comment by gir489returns** [comment]
> Was sending silly texts really useful anyway?

You could argue the entire toxic section isn’t useful, but we have it already and it should work.
