### ISSUE TITLE
[Request]: Add build date into Release post

### ISSUE THREAD

**Issue by GreySideMM** [Yimura/YimMenu#3050]
### Problem

Currently after each new build only the contents [of this post](https://github.com/YimMenu/YimMenu/releases/tag/nightly) are being updated. The date underneath it consistently indicates "Dec 3, 2023". This makes it seem there has been no updates.

### Solution

I assume deleting this post and reposting would trigger notifications etc. so another solution would be to write the build or commit date into the title. This should help reduce out-of-date issues. The commit hash as displayed now has basically no benefits imo.

Idk how GitHub workflows work but here might be one helpful information:
https://stackoverflow.com/questions/72932928/how-can-i-get-the-date-of-a-commit-in-github-actions-workflow

### Reason

-

**Comment by gir489returns** [comment]
December 3rd 2023 was when the post was made.

**Comment by xiaoxiao921** [comment]
How about just bookmarking the nightly page directly and checking the date at the bottom?

**Comment by GreySideMM** [comment]
> How about just bookmarking the nightly page directly and checking the date at the bottom?

At that point the user already would know that the date doesn't get updated. You kinda have to look quite closely to notice that. I was talking about people not knowing this yet: When I was new it took me quite some time till I figured that updates are pushed but the date stays the same. And since often enough people create new bug reports with vastly outdated versions I figured this might be one reason for it: They might not yet have noticed that new versions are released every other day.

So yes, Muhammad007228 is correct. But creating a new post every X days might be unwanted since this should (I assume) also cause a lot of notifications for every contributor here.

**Comment by xiaoxiao921** [comment]
Feel free to make a pr and I'll happily review it

**Comment by lonelybud** [comment]
duplictate of https://github.com/YimMenu/YimMenu/issues/2499

**Comment by abriginets** [comment]
I believe the only correct way of resolving this would be introducing semantic versioning, meaning that every contributor must mark their commits as fix, feat, chore, deps or breaking change. The question is would that really be necessary? Who would use the old versions of Yim?

For now your best option would be looking at the commit near the release name. It is currently [d957658](https://github.com/YimMenu/YimMenu/commit/d9576584f5750a69495e60ba002ea2c7cba9ddf4)

![image](https://github.com/YimMenu/YimMenu/assets/17240507/fb5532e9-e931-41d8-80cb-a904b4488028)

Commits can be found at the commits list page, where they are grouped by date.

https://github.com/YimMenu/YimMenu/commits/master/

**Comment by xiaoxiao921** [comment]
Nobody is gonna bother do versioning. Forget about this.

**Comment by GreySideMM** [comment]
I don't think that this is doing what I was thinking about. Was thinking about something more like the following code, but I yet have to test if it actually would work. (I might do this if I actually figure out how to compile using Github and stuff.)
Changes near the end of the .yaml:
```
[...]
      - name: Echo Commit Date
        id: commit_date
        run: |
          echo $(git log -1 --format=%cd --date=format:%Y-%m-%d)

      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly [${{ needs.commit_date.outputs.commit_date }}]
[...]
```
