### ISSUE TITLE
[Bug]: Crash when joining a session

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#3055]
### Describe the bug

When I join a free mode session. When loading in, the crash specifically occurs when I reach "Join Freemode Session" in the bottom loading/busy spinner text.

### Steps To Reproduce

1. Load into story mode
2. Use the Network Tab to load into a session(already existing session, not creating a new one).
3. Observe the crash

### Expected Behavior

Not Crash on joining a new session.

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15213833/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Could be my shitty pc.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
You are on a dirty branch that is not even main, closing as invalid.

**Comment by Rxann** [comment]
> You are on a dirty branch that is not even main, closing as invalid.

I was using a branch for my other pr, but i have observed with both. this should be reopened, as it is still valid. I can get you some logs if you require that.
