### ISSUE TITLE
[Improvement]: Remove looped::system_desync_kick_protection()?

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#3062]
### Which feature

Recent discussions have lead me into investigating our various kicks and protections. In YimMenu we have the following call in backend::loop()

`looped::system_desync_kick_protection();`

Which brings us to YimMenu's complaint handler, and I can see that we're simply setting m_host_tokens_complained to zero every game tick. However, never in my time with YimMenu has desync protection actually worked. If it did something for us in the past, it seems like it no longer does so. Is this something we need to keep looping? Am I misunderstand the purpose of this code?

### Reason

Code maintenance, spending time doing unnecessary things, etc.

**Comment by gir489returns** [comment]
It was experimental code, probably from @maybegreat48.
