### ISSUE TITLE
[Bug]: Crash while joining public session

### ISSUE THREAD

**Issue by leeqin6** [Yimura/YimMenu#3064]
### Describe the bug

Crash while joining public session

### Steps To Reproduce

When I joined a public conversation, I saw an unnamed player on the yim menu, and the game immediately crashed

### Expected Behavior

No breakdown

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15220725/cout.log)

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Additional context

I use the latest yimmenu

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by llltttjjj** [comment]
I've encountered the same bug here.

**Comment by GreySideMM** [comment]
Duplicate of #3029
