### ISSUE TITLE
[Bug]: Another P2C crash

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3085]
### Describe the bug

"Perhaps someone has encountered it, but there's a crash that doesn't produce any logs. Apparently, it's related to some P2C menu. Initially, I get a ped removal crash, then an invalid weapon type crash, and after that, the game freezes without logs and crashes."

### Steps To Reproduce

1. Find a player with P2C menu
2. Wait until he crashes you
3. Enjoy your desktop

### Expected Behavior

No crash

### Logs

Logs are useless (end on this):
[15:28:41.5863152][WARN/notify.cpp:35] Blocked player ped removal crash from **** (251298654)
[15:28:41.6195039][WARN/notify.cpp:35] Blocked invalid weapon type crash from **** (251298654)

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Amazing steps and process that's totally reproduceable with a log taboot!
