### ISSUE TITLE
[Improvement]: Add OpenAI as an alternative service.

### ISSUE THREAD

**Issue by FromTheSeaToTheRhine** [Yimura/YimMenu#3088]
### Which feature

I suggest reintroducing at least one commercial chat translation service as an example by OpenAI. And adding to the documentation, for instance, in capital letters, that the service may send your data to the FBI or something like that, but still leaving the choice of service up to the user.

### Reason

Some users don't want to deploy Docker containers. There could be various reasons for this; for example, Docker might simply consume too much of the computer's performance, or beginners might encounter difficulties with its installation. And the obvious reason is that he translates messages much better for understandable reasons

### Additional context

Maybe we shouldn't reject this request right away? Let's discuss whether it's worth adding it.

**Comment by ghost** [comment]
Perhaps we should discuss your profile photo?

**Comment by BugisoftRSG** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/58910128/6541a8f9-e5f1-4079-88d7-39b9ee1b166c)

**Comment by ghost** [comment]
> ![image](https://private-user-images.githubusercontent.com/58910128/329716904-6541a8f9-e5f1-4079-88d7-39b9ee1b166c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzQ5MjYsIm5iZiI6MTcxNTM3NDYyNiwicGF0aCI6Ii81ODkxMDEyOC8zMjk3MTY5MDQtNjU0MWE4ZjktZTVmMS00MDc5LTg4ZDctMzliOWVlMWIxNjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIwNTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjc1YzBlZjlmMjYwMTZmM2JmNDg3ZDA3NzA5MDUxZWVmMzhiOTdiMzk2ZDdhODdjMGVkNDFlN2Q4NWNkMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRzFBVQEmMmH0J81fRV9wcYMRmldmHm-sQrUHrE2fEk)

Would such statements pass through censorship in the chat?
P.S. Or ask for translation more politely
![dickpic](https://github.com/YimMenu/YimMenu/assets/168850586/c59572b9-676f-44fe-a72c-30bb8d996651)

**Comment by gir489returns** [comment]
> ![image](https://private-user-images.githubusercontent.com/58910128/329716904-6541a8f9-e5f1-4079-88d7-39b9ee1b166c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzc1MDQsIm5iZiI6MTcxNTM3NzIwNCwicGF0aCI6Ii81ODkxMDEyOC8zMjk3MTY5MDQtNjU0MWE4ZjktZTVmMS00MDc5LTg4ZDctMzliOWVlMWIxNjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIxNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNTMwYWY2NzQwM2UxN2NlM2IyZmRlZjdiMmZmOWNiMjBiNzk0ZjdlMmY5NmU5NWNjZTYzMjJlNTE4NTNkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FnWoA-Wwj5IPagGoduMnnu5AJN-ONAvpCvVVbs-UuFE)

We should close it just for this. #NoNiggers

**Comment by ghost** [comment]
The main issue is that the conversation might not flow smoothly since there's a delay in sending data to GPT and receiving its response.

One way to tackle this is by hosting the service locally, but it could slow things down.

Also, you need an API Key to use ChatGPT, and it's not free after the initial usage.

There's a Python Paackage called GPT4 which supposedly lets you use ChatGPT for free and without limits, but it seems like it's not working properly.

Using the official API, there's a risk of getting into trouble if your messages contain inappropriate stuff.

Before diving into implementing this feature, you should really think about whether it's worth it for people to see others' messages translated.

**Comment by pierrelasse** [comment]
Or maybe a locally hosted (rip cpu and gpu tho) model that was made for translating instead of assisting the user like GPT does.

**Comment by Tayipc38** [comment]
Go change your name and your profile picture. I veto anything you suggest or want.

**Comment by FromTheSeaToTheRhine** [comment]
That's better? Re-open
