### ISSUE TITLE
[Improvement]: remove "oom kick" from smart-kick

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#3099]
### Which feature
smart-kick uses the oom-kick as one of its methods

This option is really cool i'm loving it, but it will end up using the oom kick and backfire, as this kick method states: "This kick method has a high chance of backfiring in its current state", happened to me many times using smart-kick

### Reason

unstable kick method that will end up backfiring

**Comment by ghost** [comment]
then what method do you suggest?  end kick is blocked by almost all menus, unlike oom.  then what remains?  add crash?  this is unlikely to happen.

**Comment by ghost** [comment]
YimMenu has protection against OOM kick [here](https://github.com/YimMenu/YimMenu/blob/773f57baccd4574f66d7e2b9f8ed061e91de2349/src/hooks/protections/receive_net_message.cpp#L159), so it makes me wonder if other menus lack it. Or maybe this protection is only partial ?

Additionally, does the OOM kick frequently have unintended consequences ?

**Comment by ghost** [comment]
> Additionally, does the OOM kick frequently have unintended consequences ?

I personally have never had this happen

**Comment by snowleopardd** [comment]
> then what method do you suggest? end kick is blocked by almost all menus, unlike oom. then what remains? add crash? this is unlikely to happen.

there's literally over 3 more methods to kick people, the desync kick is one of them.

**Comment by ghost** [comment]
> > then what method do you suggest? end kick is blocked by almost all menus, unlike oom. then what remains? add crash? this is unlikely to happen.
> 
> there's literally over 3 more methods to kick people, the desync kick is one of them.

you cannot kick the host using the desync method

**Comment by snowleopardd** [comment]
> > > then what method do you suggest? end kick is blocked by almost all menus, unlike oom. then what remains? add crash? this is unlikely to happen.
> > 
> > 
> > there's literally over 3 more methods to kick people, the desync kick is one of them.
> 
> you cannot kick the host using the desync method

oom kick is easily protected nowadays, you cannot kick modder hosts with these neither, and if you want to, would be better off using the method alone

**Comment by ghost** [comment]
> > > > then what method do you suggest? end kick is blocked by almost all menus, unlike oom. then what remains? add crash? this is unlikely to happen.
> > > 
> > > 
> > > there's literally over 3 more methods to kick people, the desync kick is one of them.
> > 
> > 
> > you cannot kick the host using the desync method
> 
> oom kick is easily protected nowadays, you cannot kick modder hosts with these neither, and if you want to, would be better off using the method alone

I apologize for the misunderstanding.  By what method do you want to kick out the host?

**Comment by snowleopardd** [comment]
> Contributor



> > > > > then what method do you suggest? end kick is blocked by almost all menus, unlike oom. then what remains? add crash? this is unlikely to happen.
> > > > 
> > > > 
> > > > there's literally over 3 more methods to kick people, the desync kick is one of them.
> > > 
> > > 
> > > you cannot kick the host using the desync method
> > 
> > 
> > oom kick is easily protected nowadays, you cannot kick modder hosts with these neither, and if you want to, would be better off using the method alone
> 
> I apologize for the misunderstanding. By what method do you want to kick out the host?

np, my whole suggestion is about removing the oom kick from the smart-kick as it's not safe to use due to backfire, if people want to risk it and try to kick the modder host, a better option would be to use the oom kick manually and not integrated in the general smart-kick

**Comment by lonelybud** [comment]
true smart kick should not include oom kick instead it should warn that it does not work on host.

**Comment by lonelybud** [comment]
i think OOM kick should work on non modded host. Also there is no need to send 2000 network events in oom kick i think 200 - 400 should do the job

**Comment by Rxann** [comment]
> i think OOM kick should work on non modded host. Also there is no need to send 2000 network events in oom kick i think 200 - 400 should do the job

I am going to open a PR for this.

EDIT: Nevermind, 2000 network events are needed. I added a check to see how many would actually be needed before the player would be invalid using `player->is_valid` in the for loop condition and counted using a debug variable and it logged 2000. So, I don't think 200-400 would do the job.

**Comment by Rxann** [comment]
And also, OOM kick needs to stay in smart kick. It rarely backfires and we only have so many kicks. Desync and OOM are the two best, and as someone said before me end session is blocked by almost all menus.

**Comment by lonelybud** [comment]
> player->is_valid in the for loop condition and counted using a debug variable and it logged 2000

thats bcz it does not happen in an instant.

**Comment by lonelybud** [comment]
@mikedrugs dont know who added backfire label. Maybe they meant that the protected host will kick you if they detect it

**Comment by Rxann** [comment]
> @mikedrugs dont know who added backfire label. Maybe they meant that the protected host will kick you if they detect it

It used to backfire a long time ago before it was redone. I think it never got changed.

**Comment by snowleopardd** [comment]
Ok, seems like i wasn't getting backfire, i was just trying to kick modders with decent menus and obviously most of them were the host, so that may explain everything, i hope someone makes a PR to avoid confusion with the tooltip.
