### ISSUE TITLE
Feature Request: Expand vehicle tab functionality

### ISSUE THREAD

**Issue by ThatKakiGuy** [Yimura/YimMenu#31]
Upgrading vehicles and changing weapons would be nice.

**Comment by Yimura** [comment]
If you're gonna make this, don't hard-code the labels, there are natives in the game which you can call to get the names of vehicle mods.

```cpp
VEHICLE::SET_​VEHICLE_​MOD_​KIT(veh, 0);
VEHICLE::GET_LIVERY_NAME// not all vehicles use this
VEHICLE::GET_VEHICLE_MOD
VEHICLE::GET_​NUM_​VEHICLE_​MODS
VEHICLE::SET_VEHICLE_MOD
// etc...

// for labels
VEHICLE::GET_​MOD_​SLOT_​NAME
VEHICLE::GET_​MOD_​TEXT_​LABEL
// to get the localised text
HUD::_​GET_​LABEL_​TEXT
```

**Comment by ThatKakiGuy** [comment]
Saving vehicles as personal vehicles would be nice, too :D If I've time I'll look into it

**Comment by Yimura** [comment]
I have literally no idea how you'd forcefully add a vehicle to your personal vehicle list.

**Comment by Yimura** [comment]
I figured out how the LS Customs can be started anywhere, will try to make it into a proper feature and drop it tomorrow in the menu.

Keep in mind this one doesn't work for vehicles you haven't bought since it's the actual Los Santos Customs.

**Comment by ThatKakiGuy** [comment]
> I have literally no idea how you'd forcefully add a vehicle to your personal vehicle list.

There is a script event for [disowning a personal vehicle](https://www.unknowncheats.me/forum/3342885-post8.html) so maybe there is one for setting a personal vehicle as well, idk.

**Comment by ThatKakiGuy** [comment]
> Keep in mind this one doesn't work for vehicles you haven't bought since it's the actual Los Santos Customs.

If we find a way to add a vehicle as a personal vehicle that would do the job for any vehicle.
Provided you can figure it out and add it :D

**Comment by Yimura** [comment]
I've pushed the LS Customs code to the repo, it doesn't work 100% of the time since there are some problems with the carmod_shop trying to teleport the player into an interior.

I will have to hook the ENTITY::SET_ENTITY_COORDS native to prevent it from executing inside the carmod_shop script.

**Comment by Yimura** [comment]
No need to wait for teleport in the carmod_shop script, with the new native hooking I can prevent the carmod shop from teleporting our player to an unwanted location.

Bit off-topic but so much more can be done as well with this dynamic native hooking, I've made it pretty good in my opinion.
For example we can stop the freemode NETWORK::NETWORK_CAN_BAIL() from returning true EVER.

https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/native_hooks/freemode.hpp#L7-L12

**Comment by ThatKakiGuy** [comment]
> I have literally no idea how you'd forcefully add a vehicle to your personal vehicle list.

Made a post on unknowncheats about it, if I can get it to work I'll make a Pull Request

**Comment by Yimura** [comment]
Sure sounds good for me.

**Comment by ThatKakiGuy** [comment]
Hm, so apparently it's not really possible to add any vehicle as a personal vehicle.. :/ But starting LS Coustoms anywhere is still a good feature

**Comment by Yimura** [comment]
Are you talking about permanently adding it or just temporarily?

**Comment by ThatKakiGuy** [comment]
Permanently. Unless you fake getting the podium vehicle or something like that you can't add it permanently

**Comment by Yimura** [comment]
Closing issue as the scope of it is too broad and this has been partially implemented or other more specific issues have been opened.
