### ISSUE TITLE
[Bug]: Freeze Player doesnt work

### ISSUE THREAD

**Issue by Ahmad23145** [Yimura/YimMenu#3111]
### Describe the bug

When I try freeze a palyer it just doesnt work

### Steps To Reproduce

1. Open YimMenu 2. Select a Player 3. Freeze the Player 

### Expected Behavior

To freeze the player

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15297739/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ege-art** [comment]
Same for me

**Comment by xiaoxiao921** [comment]
You can't freeze players since quite a while now, in fact if you are on latest master this feature is not even in the menu anymore
