### ISSUE TITLE
[Request]: Bring back and add something

### ISSUE THREAD

**Issue by ilpiruz** [Yimura/YimMenu#3113]
### Problem

bring back the old car ramming option (but keep the new) because sometimes it works better, add an option to make and apply forces like wind and explosion on selected player

### Solution

bring back the old car ramming option (but keep the new) because sometimes it works better, add an option to make and apply forces like wind and explosion on selected player

### Reason

bring back the old car ramming option (but keep the new) because sometimes it works better, add an option to make and apply forces like wind and explosion on selected player

**Comment by Yimura** [comment]
Not following the issue template is an insult to our free time.

Closing this and please consider using your eyes and reading what the individual titles are asking for.

**Comment by ilpiruz** [comment]
sorry my fault, i'm not an english guy and i use github rarely
