### ISSUE TITLE
[Bug]: Occasional Crashes in get_entities

### ISSUE THREAD

**Issue by rkwapisz** [Yimura/YimMenu#3114]
Issue also noted in https://github.com/YimMenu/YimMenu/pull/3081 but I'm opening a separate ticket for just this crash.

I've been noticing infrequent crashes that seem to be caused inside m_ptr_to_handle when we're passing a ped. In my fork, I'm calling get_entities each tick with ped == true for a ped ESP feature. However, several other features use get_entities with peds == true like ped rain, ped ignore, and ped rush. I recall experiencing similar crashes with ped ignore in the past.

The crash is occurring here in entity.cpp according to the log dump and VS debugger:

```
		if (peds)
		{
			for (auto ped : pools::get_all_peds())
			{
				if (!ped || ped == g_local_player)
					continue;

				**target_entities.push_back(g_pointers->m_gta.m_ptr_to_handle(ped));** // CRASH HERE
			}
		}
```

At the time of the crash, my debugger confirmed the address of m_ptr_to_handle as 0x7FF7707A8A5F. Past that I have no visibility into what is happening at the very top of the stack.

Ped should be valid, so I'm guessing this may be a case of "we're calling GTA functions too quickly".

```
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x0
RCX: 0x1000120700003100
RDX: 0x1E
RBX: 0x10001A0000000700
RSI: 0x1000120700003100
RDI: 0x1E
RSP: 0xBD4B9FF6D0
RBP: 0x2BAB9C0E1D0
R8:  0x1E
R9:  0x1
R10: 0x3
R11: 0xBD4B9FF600
R12: 0x0
R13: 0x1
R14: 0x0
R15: 0x2BAB9C0E1D0
Dumping stacktrace:
[0]	GTA5.exe+0x1678372 0x7FF7707F8372
[1]	GTA5.exe+0x1628A5F 0x7FF7707A8A5F
[2]	D:\Documents\GitHub\YimMenu\src\util\entity.cpp L: 186 big::entity::get_entities
[3]	D:\Documents\GitHub\YimMenu\src\views\esp\view_esp.cpp L: 508 big::esp::draw
[4]	D:\Documents\GitHub\YimMenu\src\renderer\renderer.cpp L: 81 big::renderer::on_present
[5]	D:\Documents\GitHub\YimMenu\src\hooks\gui\swap_chain_present.cpp L: 14 big::hooks::swapchain_present
[6]	GTA5.exe+0x139A54E 0x7FF77051A54E
[7]	GTA5.exe+0x7ED74D 0x7FF76F96D74D
[8]	GTA5.exe+0x167F5E1 0x7FF7707FF5E1
[9]	GTA5.exe+0x167F4FE 0x7FF7707FF4FE
[10]	GTA5.exe+0x1659DC5 0x7FF7707D9DC5
[11]	GTA5.exe+0x165A736 0x7FF7707DA736
[12]	GTA5.exe+0x166342A 0x7FF7707E342A
[13]	GTA5.exe+0x131266A 0x7FF77049266A
[14]	KERNEL32.DLL BaseThreadInitThunk
[15]	ntdll.dll RtlUserThreadStart
--------End of exception--------
```

### Steps To Reproduce

May be reproducible using one of ped features that makes use of get_entities with ped == true, such as ped high alert, ped ignore, ped rain, and ped rush.

### Expected Behavior

Drama-free crashless behavior when repeatedly calling m_ptr_to_handle.

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15299756/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
You are just calling it at a point where it's not safe to do so. thread/racing issue.

**Comment by rkwapisz** [comment]
That makes sense. I'm going to see if I have better luck just accessing pointers from pools::get_all_peds instead of resolving them to handles all the time (which I probably should have been doing from the start).

**Comment by rkwapisz** [comment]
Closing this issue as I think I've resolved it on my end. Had to get a bit re-acquainted with Threading 101; mutexes and scoped_lock to the rescue!
