### ISSUE TITLE
[Request]: Extend Waterproof option to support vehicles

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#313]
### Problem

Waterproof option right now only supports Cped, it doesn't work if Cped is in vehicle

### Solution

Vehicles should be able to drive underwater on the sea bed if waterproof option is enabled

### Reason

Exploring seabed with vehicles is much cooler

**Comment by Aure7138** [comment]
`g_local_player->m_vehicle->m_damage_bits |= static_cast<int>(eEntityProofs::WATERPROOF);`
