### ISSUE TITLE
[Request]: Add block join reason in the reactions

### ISSUE THREAD

**Issue by MuammarIsAlive** [Yimura/YimMenu#3131]
### Problem

There is no way to automatically specify the reason for the block, such as Cheater, Session Full, etc

### Solution

Just add a dropdown list with block join reasons under the 'block join' checkbox.

### Reason

It would be quite logical compared to setting it manually for each player, and I don't think it's very difficult to implement.

**Comment by rkwapisz** [comment]
You mean you want this setting to just be global instead of per-player?

![image](https://github.com/YimMenu/YimMenu/assets/13259220/f82194bc-ea94-4aff-951d-ee1c149396db)

**Comment by snowleopardd** [comment]
ngl it would be much better to have a global one forever, instead of setting it for every player we add to the database

**Comment by rkwapisz** [comment]
Yeah I think that would make sense. It would turn a two-step process into one after the initial block notice configuration is done.
