### ISSUE TITLE
[Improvement]: add better session lock

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#3135]
### Which feature

the current handling of session lock is in `assign_physical_index` 
https://github.com/search?q=repo%3AYimMenu%2FYimMenu%20lock_session%20&type=code

 which result in joining and kicking of player and give the bad idea to player that the host tried to kick them for no reason. Instead handle the session lock logic in `handle_join_request` so that the player is not allowed to even join - 

eg -

https://github.com/lonelybud/lonelyMenu/blob/master/src/hooks/protections/handle_join_request.cpp

### Reason

improve quality of life

**Comment by gir489returns** [comment]
Are you asking, or are you just submitting this ticket to addendum to a subsequent PR?

**Comment by lonelybud** [comment]
just a discussion and then pr

**Comment by lonelybud** [comment]
i would also also suggest removing this code when not host bcz you may end up desyncing yourself - 

https://github.com/YimMenu/YimMenu/blob/059f831c52ebe814881bc0aa7d7488c05e914134/src/hooks/player_management/assign_physical_index.cpp#L125

**Comment by rkwapisz** [comment]
> i would also also suggest removing this code when not host bcz you may end up desyncing yourself -
> 
> https://github.com/YimMenu/YimMenu/blob/059f831c52ebe814881bc0aa7d7488c05e914134/src/hooks/player_management/assign_physical_index.cpp#L125

This is a good point. I don't think desync kicks should ever be automated - or at least we should check if the target falls within YimMenu's criteria for desync protection.
