### ISSUE TITLE
[Bug]: Unknown crash can hit Yim

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#3140]
### Describe the bug

This is a crash from the mod menu Infamous, it spawns a 2 peds, and 2 obj it spawns a rat and a this ped="s_m_m_janitor" the obj that spawns its unk i dont have time to grab that hash and the granade seems to be like some normal granade that u can pick it up but u cant , it takes a some secs then u get crashed

### Steps To Reproduce

1. Go online
2. Someone press the crash 13

### Expected Behavior

Block the crash

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15345659/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
It is probably some sort of invalid data that goes along with it. That is a shot in the dark and I have no proof nor did I look at the log deeply.

**Comment by lonelybud** [comment]
`[08:02:46.0432457][INFO/can_apply_data.cpp:390] 	m_model: 0x8077CE20`

what object is this

**Comment by Rxann** [comment]
> `[08:02:46.0432457][INFO/can_apply_data.cpp:390] 	m_model: 0x8077CE20`
> 
> 
> 
> what object is this

prop_tall_grass_ba

**Comment by lonelybud** [comment]
> > `[08:02:46.0432457][INFO/can_apply_data.cpp:390] 	m_model: 0x8077CE20`
> > what object is this
> 
> prop_tall_grass_ba

this one is not included in crash list

**Comment by Rxann** [comment]
> > > `[08:02:46.0432457][INFO/can_apply_data.cpp:390] 	m_model: 0x8077CE20`
> 
> > > what object is this
> 
> > 
> 
> > prop_tall_grass_ba
> 
> 
> 
> this one is not included in crash list
> 
> 

Could this be the burger king foot lettuce crash? Where they send the model and swap it so it doesn't get blocked. I will add it later in a PR even though it might not be the model. But, if it is burger king then blacklisting it will do nothing afaik.

**Comment by 0xEmiil** [comment]
With #3146 it fix the crash (The one mentioned here!)

**Comment by gir489returns** [comment]
The fix for this hasn't been merged into master yet.
