### ISSUE TITLE
[Bug]: Found a crash

### ISSUE THREAD

**Issue by FromTheSeaToTheRhine** [Yimura/YimMenu#3142]
### Describe the bug

I am able to reproduce the crash.

### Steps To Reproduce

1. First, you need to find Trevor's model 'player_two' and then click the 'Change Player Model' button.
2. Then I applied the naked Trevor skin to myself through the 'Outfit Editor'. I will attach the JSON file.
3. Next, you need to select in the ped spawner Online/Self, choose a weapon, for example, an RPG and Invincible, and spawn it for everyone by clicking 'Spawn Ped'
4. Thus, you spawned Trevor with your naked skin and then ran to the nearest Trevor and waited for him to kill you (this will happen very quickly)
5. After death, you enter a loading screen, but before it finishes, a crash occurs

### Expected Behavior

No crash

### Logs

[trevor.json.txt](https://github.com/YimMenu/YimMenu/files/15354244/trevor.json.txt)
[cout.log](https://github.com/YimMenu/YimMenu/files/15354269/cout.log)
Do not pay attention to the fact that this is not the original .dll in the logs. The crash occurs the same way with the original

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Ahmad23145** [comment]
sus

**Comment by ghost** [comment]
Trying not to say anything offensive challenge

**Comment by ghost** [comment]
I tried to reproduce it, but either it crashes or the character becomes invisible after death. I have to apply some random outfit to see character again

**Comment by Rxann** [comment]
I think this might be something that isn't explicitly fixed, but if someone ends up really wanting to use the trevor model they can find a fix for themselves.

**Comment by rkwapisz** [comment]
Buyer beware. I think this is one of those corner cases where all we can say is "don't do that".

**Comment by Rxann** [comment]
> Buyer beware. I think this is one of those corner cases where all we can say is "don't do that".

Agreed.

**Comment by snowleopardd** [comment]
can this be used as a weapon to crash others? or is it fully clientside?

**Comment by Mr-X-GTA** [comment]
> can this be used as a weapon to crash others?

No



> not exactly sure how to fix it?

```
// Sync Tree Update
{
    "STU",
    "E8 ? ? ? ? 45 84 ED 75 1B",
    [](memory::handle ptr)
    {
        g_pointers->m_gta.m_sync_tree_update = ptr.add(1).rip().as<PVOID>();
    }
}

void hooks::sync_tree_update(rage::netSyncTree* _this, __int64 target, uint32_t a3, uint32_t a4, bool a5)
{
	auto sync_data = (*(rage::netSyncData*(__fastcall**)(__int64))(*(__int64*)target + 0x50))(target);

	if (!sync_data)
		return;

	g_hooking->get_original<hooks::sync_tree_update>()(_this, target, a3, a4, a5);
}
```
