### ISSUE TITLE
[Request]: Playerlist

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#315]
### Problem

- select player box only turns blue for this player after selecting it, but if you then click on another player, he is not selected

### Solution

- After clicking on a other player it also be able to mark it right 

### Reason

Improves the playerlist for many People by far

### Additional context

- None

**Comment by LiamD-Flop** [comment]
@Clone69420 Any reason why you edited the previous issue #278 ?

**Comment by Clone69420** [comment]
Github issues idk

**Comment by Yimura** [comment]
Closed with #317
