### ISSUE TITLE
[Bug]: Never Wanted doesn't work properly

### ISSUE THREAD

**Issue by ShinyWasabi** [Yimura/YimMenu#3150]
### Describe the bug

The recent implementation of the Never Wanted feature doesn't work properly. It is inefficient in Fort Zancudo, and causes wanted level to go back and forth in some cases.

### Steps To Reproduce

1. Enable Self -> Never Wanted.
2. Go to Fort Zancudo or play a mission that constantly sets your wanted level.

### Expected Behavior

No wanted level.

### Logs

[cout.txt](https://github.com/YimMenu/YimMenu/files/15366330/cout.txt)

### Screenshots / Video

![1](https://github.com/YimMenu/YimMenu/assets/121949966/a5a8905e-f0c5-457a-9a9d-5223ce628906)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

The purpose of the max wanted level byte patch was to prevent this issue. I think we should add it back, or directly use `SET_MAX_WANTED_LEVEL` native.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is related to the change from #3070. @rkwapisz I'm assigning this to you.

**Comment by rkwapisz** [comment]
Thanks. I'll take a look at this.

**Comment by gir489returns** [comment]
I suggest we hook the natives that try to set the wanted level and reject the call if never_wanted is enabled. However, this could have side effects like getting the game stuck in a loop, where it needs the player to be wanted for something like a mission.

**Comment by rkwapisz** [comment]
> I suggest we hook the natives that try to set the wanted level and reject the call if never_wanted is enabled. However, this could have side effects like getting the game stuck in a loop, where it needs the player to be wanted for something like a mission.

Thanks. I've been able to try a few things with hooking SET_PLAYER_WANTED_LEVEL.

I can confirm with the log outputs that SET_PLAYER_WANTED_LEVEL is being invoked when trespassing into Zancudo or Bolingbroke. However, even when I prevent the native from being called, the wanted level is still being modified from somewhere else. I thought maybe SET_PLAYER_WANTED_LEVEL_NO_DROP, but same thing.

Arguments are coming in correctly, so the player and wanted level checks are as expected. Yet despite the appearance of my BLOCKED SET_PLAYER_WANTED_LEVEL messages the wanted level continues to refresh consistently.

Note that increasing the player's wanted level by attacking peds does not involve SET_PLAYER_WANTED_LEVEL (this was previously unknown to me).

SET_MAX_WANTED_LEVEL to 0 helps prevent this, but the problem with this is that while we can remember what the max wanted level was before enabling never_wanted, we can't know what it SHOULD be once the player disables it. Could be some corner cases (perhaps some heists?) where the player is doing something with never_wanted at a point where the game wants to change it, but we ignore that change entirely.

```
void SET_PLAYER_WANTED_LEVEL(rage::scrNativeCallContext* src)
{
	const auto player = src->get_arg<Player>(0);
	const int level = src->get_arg<int>(1);

	LOG(INFO) << "SET_PLAYER_WANTED_LEVEL: " << self::id << " " << player << " " << level << " " << src->get_arg<BOOL>(2);

	// Stop the wanted level from being set in the first place by a script if g.self.never_wanted (and we're not trying to set it to 0)
	if (player == self::id && g.self.never_wanted && level > 0)
	{
		LOG(INFO) << "BLOCKED SET_PLAYER_WANTED_LEVEL: " << self::id << " " << player << " " << level << " " << src->get_arg<BOOL>(2);
		return;
	}

	PLAYER::SET_PLAYER_WANTED_LEVEL(player, level, src->get_arg<BOOL>(2));
}
```

**Comment by snowleopardd** [comment]
This is actually true, sometimes the wanted level goes on and off and i can see it on the cops visually trying to attack me for a second and they leave, it's not just on the fort zancudo.

**Comment by gir489returns** [comment]
@rkwapisz Please see @ShinyWasabi's post here: https://github.com/YimMenu/YimMenu/pull/3152#issuecomment-2119183089 as to why that occurs.
