### ISSUE TITLE
hasnt worked in a month. [Bug]: 

### ISSUE THREAD

**Issue by Shaggedelic** [Yimura/YimMenu#3153]
### Describe the bug

so my friends and i all used this for a long time, it worked great and was a way higher quality mod than kiddions or any other free menus. but when the update in april happened, me and my friends cannot get it too work. i thought it was dead until today when i kept getting crashed by some kid because i have no protection and decided to dig deeper. came back to this and made an account when i seen that the thread was active and people are actualy using it. ive watched well over 6 hours of youtube trying to figure out a fix, so if anyone can tell me what were doing wrong that would be greatly helpful. i have already deinstalled and reinstalled everything from scratch including the game itself and still not shit.

### Steps To Reproduce

1.open game
2.go to story mode
3.inject
4.crash

### Expected Behavior

i expected it to just work like it used to.

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15367637/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
Your version of YimMenu is over an month old. Always update first. (The "I've confirmed the issue exists on the latest version of YimMenu" checkmark is there for a reason.)
New versions are available basically at least weekly.

PS: Also make sure your injector uses the correct file. In case you actually updated previously.

**Comment by T14D3** [comment]
> Uses severely outdated build
> Crashes
> Ignores Checkboxes
> Complains it doesn't work
