### ISSUE TITLE
[Bug]: Vehicle spawning goes wrong

### ISSUE THREAD

**Issue by roadsport** [Yimura/YimMenu#3164]
### Describe the bug

Sometimes, when you spawn a vehicle, the map bugs out and is super low poly, youre also stuck and cant move your current car or spawn a new one, cant move camera, basically a soft lock. You might be lucky that it lets you spawn a different car after like 2 minutes, and then the game is normal again.

### Steps To Reproduce

1. Go to "Spawn Vehicle"
2. Spawn a vehicle

### Expected Behavior

Vehicle spawned normally and game workingx

### Logs

Error doesnt generate anything in the cout.txt file

### Screenshots / Video

![Zrzut ekranu (2)](https://github.com/YimMenu/YimMenu/assets/160645036/05171b8a-aadc-4805-b566-8ab27c899b2e)

### Store

Steam

### Language

Polish

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
Log should still be provided, per the instructions.

**Comment by lonelybud** [comment]
i had problem with new fix_vectors implementation but still want to see whats the problem here

**Comment by tyackman** [comment]
`i had problem with new fix_vectors implementation but still want to see whats the problem here` Even after reverting fix vectors, this problem still occurs. Nothing useful in the log. I get a prompt to start a random event followed by the game eventually crashing after spawning vehicles (sometimes, this stopped happening for a while).

**Comment by lonelybud** [comment]
when are you experiencing the problem while sitting in car and spawning or spawning bare foot

**Comment by tyackman** [comment]
> when are you experiencing the problem while sitting in car and spawning or spawning bare foot

Both for me. It doesn't discriminate on when to ruin my vehicle spawning experience. 😢

**Comment by Rxann** [comment]
Sounds like we need to hook fix_vectors again and remove our current way of doing it.

**Comment by BugisoftRSG** [comment]
> Sounds like we need to hook fix_vectors again and remove our current way of doing it.

fix_vectors was never hooked

**Comment by Rxann** [comment]
> > Sounds like we need to hook fix_vectors again and remove our current way of doing it.
> 
> 
> 
> fix_vectors was never hooked

not hook, but get it as a pointer

**Comment by Rxann** [comment]
> > Sounds like we need to hook fix_vectors again and remove our current way of doing it.
> 
> 
> 
> fix_vectors was never hooked

not hook, but get it as a pointer

**Comment by Rxann** [comment]
> > Sounds like we need to hook fix_vectors again and remove our current way of doing it.
> 
> 
> 
> fix_vectors was never hooked

not hook, but get it as a pointer
