### ISSUE TITLE
[Bug]: Various Crashes

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#3166]
### Describe the bug

Any protection against these crashes?  its always these 2/3 that crash me doesn't matter if i am host or not, either.
![Screenshot_64](https://github.com/YimMenu/YimMenu/assets/24372625/22009d51-c48c-4fd0-b3d7-4d190987c976)

### Steps To Reproduce

Go into a session with a modder, you don't have to do anything since they are severely toxic most of the time.

### Expected Behavior

To block these crashes as it says its doing, but seems to do nothing.

### Logs

[18:46:41.4598744][WARN/notify.cpp:35] Blocked player ped removal crash from ChadddyBoyyyy (162939655)
[18:46:41.4599264][WARN/notify.cpp:35] Blocked invalid weapon type crash from ChadddyBoyyyy (162939655)
[18:46:41.4599452][WARN/reaction.cpp:59] Received Sound Spam from ChadddyBoyyyy (162939655)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Are you actually using the latest version of the menu?

**Comment by Deadlineem** [comment]
> Are you actually using the latest version of the menu?

I update it daily tbh.  Prolly one of the few people who focuses on that bc ik you guys push updates every few hours or so.  I actually use my update.bat from the extras addon repository to update yimmenu, makes life alot easier than getting it off of github every time.

![Screenshot_65](https://github.com/YimMenu/YimMenu/assets/24372625/0a08c3f6-8bb8-4236-bc0b-2be9a0d4fb8c)
![Screenshot_66](https://github.com/YimMenu/YimMenu/assets/24372625/83b2e4a5-7fe3-4adb-aad2-5ccb95cce050)

**Comment by maybegreat48** [comment]
> [18:46:41.4598744][WARN/notify.cpp:35] Blocked player ped removal crash from ChadddyBoyyyy (162939655)

I can confirm this guy can crash you on master. It is likely a variation of [this](https://github.com/YimMenu/YimMenu/blob/master/src/hooks/protections/script_event_handler.cpp#L133) crash. Thanks for not censoring out the name

**Comment by Deadlineem** [comment]
> > [18:46:41.4598744][WARN/notify.cpp:35] Blocked player ped removal crash from ChadddyBoyyyy (162939655)
> 
> I can confirm this guy can crash you on master. It is likely a variation of [this](https://github.com/YimMenu/YimMenu/blob/master/src/hooks/protections/script_event_handler.cpp#L133) crash. Thanks for not censoring out the name

No problem, i'm always down to help YimMenu's team out when i encounter things like this, im usually testing my addon in public lobbies so i stand around 90% of the time coding/refreshing.  Its always these 3 that seem to get me, or desync (which there is a protection for so it happens alot less vs how it was)

**Comment by Rxann** [comment]
> > [18:46:41.4598744][WARN/notify.cpp:35] Blocked player ped removal crash from ChadddyBoyyyy (162939655)
> 
> I can confirm this guy can crash you on master. It is likely a variation of [this](https://github.com/YimMenu/YimMenu/blob/master/src/hooks/protections/script_event_handler.cpp#L133) crash. Thanks for not censoring out the name

That is a variation of the elegant crash then?

**Comment by maybegreat48** [comment]
> That is a variation of the elegant crash then?

Yes, it is. The idea is that passing certain floats to that TSE will start a long-winded process that will eventually call `OBJECT::IS_POINT_IN_ANGLED_AREA` with malformed parameters that gets
```c++
for ( i = atan2f(v8 - v10, v9 - v11) + 1.5707964; i < 0.0; i = i + 6.2831855 )
    ;
  while ( i > 6.2831855 )
    i = i + -6.2831855;
```
stuck in an infinite loop

**Comment by gir489returns** [comment]
> > That is a variation of the elegant crash then?
> 
> Yes, it is. The idea is that passing certain floats to that TSE will start a long-winded process that will eventually call `OBJECT::IS_POINT_IN_ANGLED_AREA` with malformed parameters that gets
> 
> ```c++
> for ( i = atan2f(v8 - v10, v9 - v11) + 1.5707964; i < 0.0; i = i + 6.2831855 )
>     ;
>   while ( i > 6.2831855 )
>     i = i + -6.2831855;
> ```
> 
> stuck in an infinite loop

Can’t we instead hijack is point in angled area with our own math that doesn’t get stuck in an infinite loop?

**Comment by xiaoxiao921** [comment]
Depends, either hook that yeah or sanitize the received event
