### ISSUE TITLE
[Build]: Unable to build with VSC 2022 17.10.0

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#3181]
### Describe the build issues

I was able to build with previous VSC versions. I have tried clean and rebuilding again, but to fail.

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/90883505/c5e65a09-0a94-4b1c-8407-0c215fa79c04)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by docentwars** [comment]
Same problem

**Comment by CypherMorgan** [comment]
Make sure you're using the Community version not the Community Preview version. (Preview version caused this issue for me and was fixed on just community version)

**Comment by xiaoxiao921** [comment]
> Make sure you're using the Community version not the Community Preview version. (Preview version caused this issue for me and was fixed on just community version)

No. This also happen on non preview version. The fix for this is to just bump the git hash from the AsyncLogger dependency. I already fixed the issue all is needed is to bump the number in the cmake fetch.

**Comment by howdoiusekeyboard** [comment]
Fixed
