### ISSUE TITLE
[Bug]: CEO Special Merchandises money is set too high

### ISSUE THREAD

**Issue by Azeroxy** [Yimura/YimMenu#3191]
### Describe the bug

When I go into my agency and try to delvier the goods/merchandise the price of only 1 crate is set to 6 MILLIONS and I didn't enbale that so I was just wondering how I can disable that issue

### Steps To Reproduce

No steps

### Expected Behavior

Money will not even get sent to account you just deliver and nothing hapens or get kicked

### Logs

[05-27-2024-14-56-28_cout.txt.log](https://github.com/YimMenu/YimMenu/files/15456608/05-27-2024-14-56-28_cout.txt.log)

### Screenshots / Video

![Capture d'écran 2024-05-27 153123](https://github.com/YimMenu/YimMenu/assets/74677619/e8b15f0c-6a15-4704-a7d7-4f68801b8ff5)

### Store

Rockstar

### Language

French

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Your log file is empty, could you verify again to make sure you uploaded the right log file?

**Comment by Azeroxy** [comment]
Sorry it seems that the issue comes from the Ultimate Menu script but I still dont know how to disable it

**Comment by Yimura** [comment]
1. Disable the script in YimMenu
2. Not a YimMenu issue
3. Contact the developer on the dedicated repo of the script.
