### ISSUE TITLE
[Bug]：Auxiliary aiming unavailable - Aimbot

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#3209]
### Describe the bug

Auxiliary aiming, why do aim 360 degrees at nearby enemies, my  sight is already aiming at the enemy in front of me, auxiliary aiming will automatically select another target, which is not usable at all, please fix it, and the crosshair can not be moved from the target at all, the automatic adsorption range is too large, can not be used unless the aiming button is turned off

### Steps To Reproduce

1.Open auxiliary aiming
2.Aim at the enemy in front of you
3.Auxiliary aiming automatically selects another target

### Expected Behavior

 why do aim 360 degrees at nearby enemies, my  sight is already aiming at the enemy in front of me, auxiliary aiming will automatically select another target, which is not usable at all, please fix it, and the crosshair can not be moved from the target at all, the automatic adsorption range is too large, can not be used unless the aiming button is turned off

### Logs

123

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
We have a new aimbot, try modifying the FOV aimbot option it should work much better now
