### ISSUE TITLE
[Bug]: Got Crashed by Modder

### ISSUE THREAD

**Issue by Ahmad23145** [Yimura/YimMenu#3211]
### Describe the bug

I got crashed from someone 

### Steps To Reproduce

1. Go to Online Session 2. Meet a toxic modder 3. Get crashed

### Expected Behavior

To not get crashed

### Logs

[cout.log](https://github.com/user-attachments/files/15523598/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
why in the logs there is this file mentioned in stacktrace - 

`src\backend\commands\player\crash\ultimate_crash.cpp`

are you sure you using yimmenu without any modification?

**Comment by who-care123** [comment]
Are u sure it is not self crash?

**Comment by Ahmad23145** [comment]
> why in the logs there is this file mentioned in stacktrace -
> 
> `src\backend\commands\player\crash\ultimate_crash.cpp`
> 
> are you sure you using yimmenu without any modification?

i only added few crashes

**Comment by rkwapisz** [comment]
> > why in the logs there is this file mentioned in stacktrace -
> > `src\backend\commands\player\crash\ultimate_crash.cpp`
> > are you sure you using yimmenu without any modification?
> 
> i only added few crashes

You're copy-pasting crashes from old forks that don't work anymore.

**Comment by Ahmad23145** [comment]
I got crashed from Modder again with Yim , I only saw someone is spamming some objects (idk) in front of me, it crashes by received_clone_create and receive_net_message
[cout.log](https://github.com/user-attachments/files/15523595/cout.log)

**Comment by maybegreat48** [comment]
Yeah I think I know what this is. I'll fix it in my next PR

Also why were you being crashed by five players at the same time?

> (not modified)

You sure?

```
[22:32:38.1361337][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x3F80000000000000
RCX: 0x3F80000000000000
RDX: 0x7FF6D4DCBC48
RBX: 0x3F80000000000000
RSI: 0x97C32800
RDI: 0x0
RSP: 0xBC05BE8F50
RBP: 0xBC05BE90B0
R8:  0x7F8459
R9:  0x1C99AB09330
R10: 0x0
R11: 0xBC05BE8EB0
R12: 0x74019666
R13: 0x94551490
R14: 0xE3CE09E2
R15: 0xEDA96F47
Dumping stacktrace:
[0]	GTA5.exe+0xA3B820 0x7FF6D3A4B820
[1]	GTA5.exe+0xCF256A 0x7FF6D3D0256A
[2]	C:\Users\Administrator\Source\Repos\YimMenu\src\backend\commands\player\crash\ultimate_crash.cpp L: 309 big::ultimate_crash::execute
[3]	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\functional L: 909 std::_Func_impl_no_alloc<`big::player_command::call'::`2'::<lambda_1>,void>::_Do_call
[4]	C:\Users\Administrator\Source\Repos\YimMenu\src\fiber_pool.cpp L: 43 big::fiber_pool::fiber_tick
[5]	C:\Users\Administrator\Source\Repos\YimMenu\src\fiber_pool.cpp L: 52 big::fiber_pool::fiber_func
[6]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 101 big::script::fiber_func
[7]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 27 `big::script::script'::`2'::<lambda_1>::operator()
[8]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 28 `big::script::script'::`2'::<lambda_1>::<lambda_invoker_cdecl>
[9]	KERNELBASE.dll PackageIdFromFullName
[10]	ntdll.dll RtlUserFiberStart
[11]	ntdll.dll RtlUserFiberStart
[12]	GTA5.exe+0x10CA305 0x7FF6D40DA305
[13]	GTA5.exe+0x1633449 0x7FF6D4643449
[14]	GTA5.exe+0x1632C7F 0x7FF6D4642C7F
[15]	GTA5.exe+0x2767E 0x7FF6D303767E
[16]	GTA5.exe+0x20D8B 0x7FF6D3030D8B
[17]	GTA5.exe+0x1632888 0x7FF6D4642888
[18]	GTA5.exe+0x1494 0x7FF6D3011494
[19]	GTA5.exe+0x130904F 0x7FF6D431904F
[20]	GTA5.exe+0x1825DCC 0x7FF6D4835DCC
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
```

**Comment by Ahmad23145** [comment]
> Yeah I think I know what this is. I'll fix it in my next PR
> 
> Also why were you being crashed by five players at the same time?

Thank you
I don't know, somehow

**Comment by Ahmad23145** [comment]
> Yeah I think I know what this is. I'll fix it in my next PR
> 
> Also why were you being crashed by five players at the same time?
> 
> > (not modified)
> 
> You sure?
> 
> ```
> [22:32:38.1361337][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
> Dumping registers:
> RAX: 0x3F80000000000000
> RCX: 0x3F80000000000000
> RDX: 0x7FF6D4DCBC48
> RBX: 0x3F80000000000000
> RSI: 0x97C32800
> RDI: 0x0
> RSP: 0xBC05BE8F50
> RBP: 0xBC05BE90B0
> R8:  0x7F8459
> R9:  0x1C99AB09330
> R10: 0x0
> R11: 0xBC05BE8EB0
> R12: 0x74019666
> R13: 0x94551490
> R14: 0xE3CE09E2
> R15: 0xEDA96F47
> Dumping stacktrace:
> [0]	GTA5.exe+0xA3B820 0x7FF6D3A4B820
> [1]	GTA5.exe+0xCF256A 0x7FF6D3D0256A
> [2]	C:\Users\Administrator\Source\Repos\YimMenu\src\backend\commands\player\crash\ultimate_crash.cpp L: 309 big::ultimate_crash::execute
> [3]	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\functional L: 909 std::_Func_impl_no_alloc<`big::player_command::call'::`2'::<lambda_1>,void>::_Do_call
> [4]	C:\Users\Administrator\Source\Repos\YimMenu\src\fiber_pool.cpp L: 43 big::fiber_pool::fiber_tick
> [5]	C:\Users\Administrator\Source\Repos\YimMenu\src\fiber_pool.cpp L: 52 big::fiber_pool::fiber_func
> [6]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 101 big::script::fiber_func
> [7]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 27 `big::script::script'::`2'::<lambda_1>::operator()
> [8]	C:\Users\Administrator\Source\Repos\YimMenu\src\script.cpp L: 28 `big::script::script'::`2'::<lambda_1>::<lambda_invoker_cdecl>
> [9]	KERNELBASE.dll PackageIdFromFullName
> [10]	ntdll.dll RtlUserFiberStart
> [11]	ntdll.dll RtlUserFiberStart
> [12]	GTA5.exe+0x10CA305 0x7FF6D40DA305
> [13]	GTA5.exe+0x1633449 0x7FF6D4643449
> [14]	GTA5.exe+0x1632C7F 0x7FF6D4642C7F
> [15]	GTA5.exe+0x2767E 0x7FF6D303767E
> [16]	GTA5.exe+0x20D8B 0x7FF6D3030D8B
> [17]	GTA5.exe+0x1632888 0x7FF6D4642888
> [18]	GTA5.exe+0x1494 0x7FF6D3011494
> [19]	GTA5.exe+0x130904F 0x7FF6D431904F
> [20]	GTA5.exe+0x1825DCC 0x7FF6D4835DCC
> [21]	KERNEL32.DLL BaseThreadInitThunk
> [22]	ntdll.dll RtlUserThreadStart
> --------End of exception--------
> ```

Sorry, it's only a bit modified

**Comment by maybegreat48** [comment]
What modifications did you make to the menu? Did you run your "ultimate crash" before you got the errors?

**Comment by Ahmad23145** [comment]
I runned that in session before. But in the new session I didn't do anything

**Comment by maybegreat48** [comment]
`tiffyLive (201625899)` is using an unreleased menu I haven't heard of. They could not crash me

**Comment by maybegreat48** [comment]
> I runned that in session before. But in the new session I didn't do anything

What is ultimate crash anyway?

**Comment by Ahmad23145** [comment]
> > I runned that in session before. But in the new session I didn't do anything
> 
> What is ultimate crash anyway?

It crashes players game (Invalid Object Crash)

**Comment by maybegreat48** [comment]
Can I see the file? And is it the only modification you've made to YimMenu?

**Comment by Ahmad23145** [comment]
> Can I see the file? And is it the only modification you've made to YimMenu?

Yes, 
[ultimatecrash.zip](https://github.com/user-attachments/files/15523640/ultimatecrash.zip)

**Comment by maybegreat48** [comment]
I would get rid of that trash and just stick to plain YimMenu

**Comment by Ahmad23145** [comment]
> I would get rid of that trash and just stick to plain YimMenu

Ok so the solution is just removing it thanks

**Comment by lonelybud** [comment]
I think `invalid object model` can be false positive when you have players around you meaning the one syncing with you was not the original crasher.

**Comment by Yimura** [comment]
Recreate the crash with Vanilla YimMenu and then report it.
