### ISSUE TITLE
[Improvement]: Block join reason to reaction #3190

### ISSUE THREAD

**Issue by binded-zz** [Yimura/YimMenu#3213]
### Which feature

could be just me but i swear block was under a collapsable option under add to database
now you can block without checking the add to database 

pertty sure if not the case should just auto check mark add to database when selecting block join 

other then that it works

### Reason

if adding to the database should just automatically checkmark add to the database
or just a note that they will still be added to the database

someone might think that its blocking a user but not added to a user database

### Additional context

not a huge deal just makes a lil more sense

**Comment by rkwapisz** [comment]
This is intended behavior. Block Joins no longer has a dependency on enabling Add Player to Database (though yes, it will still add them to the DB which is a requirement for it to work).
