### ISSUE TITLE
[Bug]: Play Sounds through  chat

### ISSUE THREAD

**Issue by ege-art** [Yimura/YimMenu#3219]
### Describe the bug

I converted a sound file with the orginal https://yim.gta.menu/audio/ converter tool, i did everything right as it says in yimMenu. But when i play the sound i just get a static or interference sound out of it, i dont know if this should be like this.

### Steps To Reproduce

1. put a random sound file (i think so) in this https://yim.gta.menu/audio/ converter tool
2. put the converted sound file in the yim directory
3. in yimMenu go to spoofing and turn on (play audio through Voice Chat) 
4. Hear the sound of static/interference sounds 

### Expected Behavior

That the audio plays normally through the Voice Chat without static noise. (basically just like how the orginal does sound)

### Logs
[cout.txt](https://github.com/user-attachments/files/15537235/cout.txt)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I know that a same issue like this one exists... issue (#2951), but i still want to discuss this. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
Same problem, I wanted to convert my Teufelslied.mp3 through that site and also broadcast the sound during the flight on a Deluxo with a swastika, but alas... My dream did not come true. But in my case I didn’t hear any sounds at all

**Comment by ege-art** [comment]
Yea nothing works as expected, I'm waiting for a fix

**Comment by maybegreat48** [comment]
Have you tried Tracks > Resample > 16000 and Edit > Preferences > Project Sample Rate > 16000? This feature has always worked for me

**Comment by ege-art** [comment]
> Have you tried Tracks > Resample > 16000 and Edit > Preferences > Project Sample Rate > 16000? This feature has always worked for me

I haven't, How can I do that? Do You mean on VLC Or Audacity? Why shouldn't the original converter for yim that I used not meet the requirements?

**Comment by maybegreat48** [comment]
> I haven't, How can I do that? Do You mean on VLC Or Audacity? Why shouldn't the original converter for yim that I used not meet the requirements?

These are for Audacity. The web converter does not work for me either

**Comment by ege-art** [comment]
> > I haven't, How can I do that? Do You mean on VLC Or Audacity? Why shouldn't the original converter for yim that I used not meet the requirements?
> 
> 
> 
> These are for Audacity. The web converter does not work for me either

Ah already, I'll try that

**Comment by ege-art** [comment]
> Have you tried Tracks > Resample > 16000 and Edit > Preferences > Project Sample Rate > 16000? This feature has always worked for me

Thank you, that worked! Now everything works as it should. I'll close this
