### ISSUE TITLE
[Improvement]: Increase your chances of joining

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3222]
### Which feature

How do we know that in order to successfully be in a session and not be kicked, you need to become a session host, right? But considering that we are not alone, I suggest adding a filter for modder sessions to the session browser. how will this work? We have a database of players whom we mark as modders, if the modder sessions filter checkbox is active, then we will exclude sessions hosted by a modder. this will be very useful for those who already have a fairly large database of cheaters (for me, for example). But how do we know that a modder owns the session? Without joining, we can get the host's RID and compare it with the database and then filter it. At least that’s what a stand can do (it can get all the information about the session and also the host’s nickname).

### Reason

This way we will reduce the time required to find a suitable session in which we can become the host and will not be desynchronized by others.

**Comment by snowleopardd** [comment]
This is crazy, it is simpler to switch sessions honestly, you would need a giant database and that costs money

**Comment by Yimura** [comment]
Do you want to link this to the existing local DB or to some DB that's online?

Because an online DB would be a terrible idea.

**Comment by ghost** [comment]
> This is crazy, it is simpler to switch sessions honestly, you would need a giant database and that costs money

in fact, the sessions are hosted mostly by the same cheaters and most of them are already known to my database that I don’t even receive a notification about the detection of a modder and the cheat immediately tries to kick them.

> Do you want to link this to the existing local DB or to some DB that's online?
> 
> Because an online DB would be a terrible idea.

to the local one, of course, I just wanted to add a filter to the session browser that would filter sessions hosted by modders already known to us. and sometimes in order to join any full session without a modder host you sometimes have to click up to 10 times, sometimes even more

**Comment by snowleopardd** [comment]
> > This is crazy, it is simpler to switch sessions honestly, you would need a giant database and that costs money
> 
> in fact, the sessions are hosted mostly by the same cheaters and most of them are already known to my database that I don’t even receive a notification about the detection of a modder and the cheat immediately tries to kick them.
> 
> > Do you want to link this to the existing local DB or to some DB that's online?
> > Because an online DB would be a terrible idea.
> 
> to the local one, of course, I just wanted to add a filter to the session browser that would filter sessions hosted by modders already known to us. and sometimes in order to join any full session without a modder host you sometimes have to click up to 10 times, sometimes even more

Thats actually pretty smart, i like it
