### ISSUE TITLE
[Improvement]: OOM-kick-reaction

### ISSUE THREAD

**Issue by Flylow260** [Yimura/YimMenu#3223]
### Which feature

As far as I remember, the reaction tab had the function to react to OOM kicks and it doesn't seem to exist anymore since one of the updates.

### Reason

Now if someone wants to kick me with OOM, they will no longer be kicked automatically and only if they use other methods, which in turn works normally.

**Comment by ghost** [comment]
Maybe it’s worth making a single reaction called “Kick” that will react to any type of kick

**Comment by Rxann** [comment]
I will implement an OOM kick reaction.

**Comment by snowleopardd** [comment]
we really need this now
