### ISSUE TITLE
[Bug]: GUI Scaling

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#3227]
### Describe the bug

GUI Scaling slider is very buggy, if you have a smaller screen resolution the menu takes up most of the screen and when trying to resize it, the slider sort of "snaps back" so instead of being able to slide it, you have to really quickly click on it to get it to set to a lower value scale.

### Steps To Reproduce

Settings > GUI > UI Scale Slider

Try to drag the slider

### Expected Behavior

Slider should easily work and transition through the values without snapping itself back and bugging out

Potential fixes:  
1. Automatic rescaling of the GUI based on screen resolution
2. Fix the slider itself 
3. Make the scaling an input value defaulted at 1.00 instead so it can be manually changed

### Logs

Not Applicable

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
you can change the scale in %appdata%\YimMenu\settings.json but that's very user friendly 
`"gui_scale": 1.0,`

**Comment by Deadlineem** [comment]
> you can change the scale in %appdata%\YimMenu\settings.json but that's very user friendly `"gui_scale": 1.0,`

Its not very user friendly doing it that way, even though its an alternative to get it to downscale easily, the interface should be fixed regardless

**Comment by xesdoog** [comment]
If this wasn't intentionally disabled, you can CTRL + click on any ImGui slider to manually input values.

**Comment by lonelybud** [comment]
if someone wants to fix the slider. try adding a debouncer mechanism which will always reject previous changes and reflect only the latest change after few milliseconds

**Comment by lonelybud** [comment]
we can use `IsItemDeactivatedAfterEdit` to use the final value as mentioned here https://github.com/ocornut/imgui/issues/1875
