### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by buzaslan129** [Yimura/YimMenu#3230]
### Problem

hi when i am host the lobby locks up and not populating. how can i fix it.

### Solution

fix

### Reason

half an hour later I'm the only one standing

**Comment by lonelybud** [comment]
check your NAT type and contact your network provider.

Edit which region you facing issue?

**Comment by Yimura** [comment]
If you can't get your lobby to fill up with even the multiplexer enabled then the issue is not with YimMenu but with your network setup.

**Comment by buzaslan129** [comment]
ı have 2 router and 1 fiber modem so how can ı fix that .D

**Comment by buzaslan129** [comment]
im in eu

**Comment by Yimura** [comment]
Double NAT-ing would probably be a large part of your problems, try and ask Google as we're not your personal AI to solve these problems (that are not relevant to YimMenu).
