### ISSUE TITLE
[Improvement]: Menu keybind wont work sometimes 

### ISSUE THREAD

**Issue by BigboiKilljoy** [Yimura/YimMenu#3243]
### Which feature

Sometimes i start up the mod and theres literally nothing on my keyboard that will open the menu. though i can 100% of the time open the console command, so it'd be nice if i could, from the console command, open the menu. The command could simply be "Open Sesame Bitch". Thank you for listening.

### Reason

Cause i said so

**Comment by lonelybud** [comment]
your toggle key is saved in `C:\Users\XXX\AppData\Roaming\YimMenu\settings.json`

you can either delete this file to reset the toggle key to `insert` key or manually set the value `45` in order to set it back to `insert` key - 

```
    "settings": {
        "hotkeys": {
            "menu_toggle": 45
        }
    },
```

Edit: 
> Menu keybind wont work sometimes

it may be possible that you set the key to one of numpad keys and in order to it to work you must then have numlock on

**Comment by BigboiKilljoy** [comment]
> your toggle key is saved in `C:\Users\XXX\AppData\Roaming\YimMenu\settings.json`
> 
> you can either delete this file to reset the toggle key to `insert` key or manually set the value `45` in order to set it back to `insert` key -
> 
> ```
>     "settings": {
>         "hotkeys": {
>             "menu_toggle": 45
>         }
>     },
> ```
> 
> Edit:
> 
> > Menu keybind wont work sometimes
> 
> it may be possible that you set the key to one of numpad keys and in order to it to work you must then have numlock on

Well now i know how to solve the issue but other people in the future wont. That's why i think something simple like a command for the command line would save a lot of people a lot of time. When my Keybind doesn't work i try to use the command line, and i type in things like "menu", "open", "Keybinds". These could be quick fixes any quick thinking person could use without even know the commands exist, just by simply guessing.

**Comment by xiaoxiao921** [comment]
Duplicate of #3436

**Comment by BigboiKilljoy** [comment]
> Duplicate of #3436

How is this a duplicate? #3436 does not fix my issue, as i never used my mouse buttons as a way to open the menu. I literally have the default menu open key which is my numpad

**Comment by xiaoxiao921** [comment]
If your problem is that you are setting a numpad number key and that you forget to have numpad lock then this is not an issue with YimMenu

**Comment by BigboiKilljoy** [comment]
> If your problem is that you are setting a numpad number key and that you forget to have numpad lock then this is not an issue with YimMenu

It's NOT an issue with me. If it was it's pretty odd how it's solved simply by me restarting the game. Its not numpad lock, its not a bad keybind, its not the keybind not working, its just the menu being broken. Sometimes ill get on and it wont work, so i restart, and then it does

**Comment by Yimura** [comment]
And you're using what as a keybind exactly? Because I have never experienced this issue.

**Comment by BigboiKilljoy** [comment]
> And you're using what as a keybind exactly? Because I have never experienced this issue.

It's the default keybind i believe numpad 0. I haven't gotten on gta in a hot minute sooo not sure

**Comment by Yimura** [comment]
> It's the default keybind i believe numpad 0. I haven't gotten on gta in a hot minute sooo not sure

The zero key on your keypad also serves as the insert key if you disable num lock, are you sure you don't have num lock enable _sometimes_ when you get in the game and try to open YimMenu?

**Comment by BigboiKilljoy** [comment]
> > It's the default keybind i believe numpad 0. I haven't gotten on gta in a hot minute sooo not sure
> 
> The zero key on your keypad also serves as the insert key if you disable num lock, are you sure you don't have num lock enable _sometimes_ when you get in the game and try to open YimMenu?

Yes im very sure. Theres no reason restarting my game would would change anything about how my numlock keys work, and yet that always fixes things.

**Comment by BigboiKilljoy** [comment]
Ive also tabbed out of gta to make sure the numpad was working correct before even restarting, it just doesn't seem to be an issue with me. Unless maybe sometimes loading up the menu something glitches due to my pc not being the greatest
