### ISSUE TITLE
[Improvement]: ImGui DefaultCollapsed flag

### ISSUE THREAD

**Issue by Deadlineem** [Yimura/YimMenu#3244]
### Which feature

Can we add this flag support in yimmenu?  I tried adding this flag to the submenus 
`ImGui.Begin("Extras Addon (Grief Options) - Target: ".. selPlayer, flags)` where `flags = ImGuiWindowFlags.DefaultCollapsed`  it throws the below error (Using LUA)

### Reason

attempt to perform bitwise operation on a nil value (field 'DefaultCollapsed')

`ImGuiWindowFlags.DefaultCollapsed`

**Comment by lonelybud** [comment]
nil value means it is not defined in `ImGuiWindowFlags`

Edit: may be you can find something here https://github.com/YimMenu/YimMenu/blob/8bbab4c76531a905a885f667af34315516489534/src/lua/bindings/imgui.hpp#L2893

**Comment by Deadlineem** [comment]
> nil value means it is not defined in `ImGuiWindowFlags`
> 
> Edit: may be you can find something here
> 
> https://github.com/YimMenu/YimMenu/blob/8bbab4c76531a905a885f667af34315516489534/src/lua/bindings/imgui.hpp#L2893

This is where it should be but DefaultCollapsed is not defined anywhere in here, not sure if its imgui version related or just wasn't added

**Comment by xiaoxiao921** [comment]
DefaultCollapsed has never been a thing from imgui, if you want a window to be collapsed by default you jsut pass a bool open = false within your ImGui::Begin call, like it is explained in the original imgui doc. Or use SetWindowCollapsed, which is also exposed to the lua api.
