### ISSUE TITLE
[Bug]: Spoofing does not work.

### ISSUE THREAD

**Issue by DeformedSAS** [Yimura/YimMenu#3247]
### Describe the bug

Trying to spoof like kd or level or crew or even hide god mode does not work on yim menu, it worked before but now it doesn't....

### Steps To Reproduce

none

### Expected Behavior

none

### Logs

none

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
Send the log for when you faced this issue.

**Comment by DeformedSAS** [comment]
there is no log for the spoofing i checked it...

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rxann** [comment]
> there is no log for the spoofing i checked it... Sent from Outlook for Android<https://aka.ms/AAb9ysg>

You should still send it anyway

**Comment by DeformedSAS** [comment]
i'll send it tomorrow when i get on my pc

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Yimura** [comment]
Most spoofing options are only visible to other players in your session, you yourself can't see these things being spoofed.

**Comment by Yimura** [comment]
Spoofing works as intended:
![image](https://github.com/user-attachments/assets/5228b3bd-f87b-462d-8e14-53bb9c86372b)
