### ISSUE TITLE
[Bug]: I got crashed

### ISSUE THREAD

**Issue by 420tsu69** [Yimura/YimMenu#3270]
### Describe the bug

I got crashed but i don't know by what, since the menu was already blocking mount flag crash and that has worked in the past.

### Steps To Reproduce

1. Go online. 2. Anger another modder in a public session. 3. They try to crash you. 4. You crash.

### Expected Behavior

To block the crash.

### Logs

[cout.log](https://github.com/user-attachments/files/15918080/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Mr-X-GTA** [comment]
Duplicate of https://github.com/YimMenu/YimMenu/issues/3263

**Comment by xiaoxiao921** [comment]
This issue has an actual log so the other issue should probably be closed and this one kept open
