### ISSUE TITLE
[Request]: RID Joining

### ISSUE THREAD

**Issue by Sofaeinhorn22** [Yimura/YimMenu#328]
### Solution

A way To RID join Could be a nice addon to the cheat

### Reason

there is already the option to see RID's so why not make RID Joining Possible Via Yim

**Comment by Vali0004** [comment]
This question has been answered multiple times, and the answer is no. The reason and answer can be found in https://github.com/YimMenu/YimMenu/issues/151 and https://www.unknowncheats.me/forum/3328773-post109.html

**Comment by Vali0004** [comment]
A discussion has been started to appeal this answer (ref. https://github.com/YimMenu/YimMenu/discussions/299)

**Comment by Yimura** [comment]
Well actually in a later issue we discussed some stuff about RID joining.
