### ISSUE TITLE
[Bug]: Can't see chat

### ISSUE THREAD

**Issue by tiCkuhAr** [Yimura/YimMenu#3282]
### Describe the bug

When I have chat commands on and someone incorrectly types the car name for /spawn, triggering the menu to send a message in chat while I'm tabbed out of GTA, it makes it so I can't see chat anymore.

### Steps To Reproduce

1. Turn on chat cmds
2. Tab out of GTA
3. Have someone do /spawn t or something random
4. Go back to GTA, and you should not see your chat anymore.

### Expected Behavior

Not break chat?

### Logs

[cout.log](https://github.com/user-attachments/files/15961771/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

The chat can be fixed by either changing sessions or triggering the menu to send a message in chat while you are tabbed in on GTA.

Also, there is a small bug: when the menu sends a message in chat, if you are in the middle of typing a message, it will automatically close chat and clear your message.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
Always include the log, there might not be anything you see but it is always important.

**Comment by tiCkuhAr** [comment]
I will add one later

**Comment by gir489returns** [comment]
This ticket is 2 weeks stale, I assume MBG has figured out the issue and included it it in his massive commit that he didn't document, so I'm going to close this. OP, if you feel this ticket is still valid, open a new one with a log included and screenshots, please.
