### ISSUE TITLE
[Bug]: crashing on injection

### ISSUE THREAD

**Issue by VortxxxxFr** [Yimura/YimMenu#3285]
### Describe the bug

i inject with xenos and crash soon after

### Steps To Reproduce

load gta
inject with xenos
crash

### Expected Behavior

load gta 
inject with xenos
dont crash

### Logs

[cout.txt](https://github.com/user-attachments/files/15968968/cout.txt)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by D-Borkan** [comment]
game has been update to 1.69

**Comment by Alex-MHR** [comment]
By the way, here are the Signatures that have changed :

```
Failed to find 'SCM'
Failed to find 'SGSBGH'
Failed to find 'HRGC'
Failed to find 'PIGI'
Failed to find 'SOD'
Failed to find 'NHM'
Failed to find 'WN'
Failed to find 'SSDM'
Failed to find 'SRP'
```

**Comment by VortxxxxFr** [comment]
> game has been update to 1.69

what does that mean? yim isn't updated to 1.69?

**Comment by D-Borkan** [comment]
> > game has been update to 1.69
> 
> what does that mean? yim isn't updated to 1.69?

just wait until developers update the menu

**Comment by VortxxxxFr** [comment]
okay thanks 🙏

**Comment by chriperseo** [comment]
Waiting to play the game XD. Pls hurry , Thanks for the gods work.

**Comment by roadsport** [comment]
Same thing happens every update since YimMenu exists, why are people still shocked when the menu doesnt work after an update

**Comment by VortxxxxFr** [comment]
i didnt know it updated + i only just started using yim again yesterday lol

**Comment by ILcign0** [comment]
when can i use the mod menu yall?

**Comment by roadsport** [comment]
when they update the mod menu to work on 1.69

**Comment by ILcign0** [comment]
when?

**Comment by roadsport** [comment]
sometime later today most likely

**Comment by tupoy-ya** [comment]
Updated signatures, not tested in game.

```cpp
// Send Chat Message
"SCM", "48 81 EC 80 00 00 00 48 8B E9 48 8B CA 41" ptr.sub(21)

// Start Matchmaking Find Sessions
"SGSBGH", "83 ? ? ? ? E8 ? ? ? ? 84 C0 0F 84 ? ? ? ? C7" ptr.add(6).rip()

// Handle Remove Gamer Command
"HRGC", "74 74 33 FF" ptr.sub(0x3B)

// Player Info Gamer Info
"PIGI", "E8 ? ? ? ? 48 8D 4B 20 48 8B D0 E8 ? ? ? ? 41 8A CF" ptr.add(1).rip().add(3).rip()

// Not sure if this is still needed or works
// Sound Overload Detour
"SOD", "66 41 3B D1 74 43"

// Not sure if this is still needed or works
// NetFilter Handle Message
"NHM", "EB 2E 49 8D 82 ? ? ? ? 4C" ptr.sub(4).rip()

// This sig overlaps into a function right after it, but this sig works on 2699, 3179, 3258.
// Write Node
"WN", "49 89 43 C8 E8 ? ? ? ? 84 C0 0F 95 C0 48 83 C4 ? C3 4C 8B DC" ptr.sub(0x49)

// Should be more stable
// Send Session Detail Msg
"SSDM", "4C 8D 85 ? ? 00 00 49 8B D5 49" ptr.add(0xE).rip()

// Can't we just `send_response(0)` in `handle_join_request` hook instead of trying to patch to original, on second thoughts that would require us to rewrite the entire `handle_join_request` function, I'm stupid.
// Session Request Patch
"SRP", "48 8B BD 70 01 00 00 E9 FF 00 00 00" ptr.add(0x13)
```

**Comment by CypherMorgan** [comment]
> Updated signatures, not tested in game.
> 
> ```c++
> // Send Chat Message
> "SCM", "48 81 EC 80 00 00 00 48 8B E9 48 8B CA 41" ptr.sub(21)
> 
> // Start Matchmaking Find Sessions
> "SGSBGH", "83 ? ? ? ? E8 ? ? ? ? 84 C0 0F 84 ? ? ? ? C7" ptr.add(6).rip()
> 
> // Handle Remove Gamer Command
> "HRGC", "74 74 33 FF" ptr.sub(0x3B)
> 
> // Player Info Gamer Info
> "PIGI", "E8 ? ? ? ? 48 8D 4B 20 48 8B D0 E8 ? ? ? ? 41 8A CF" ptr.add(1).rip().add(3).rip()
> 
> // Not sure if this is still needed or works
> // Sound Overload Detour
> "SOD", "66 41 3B D1 74 43"
> 
> // Not sure if this is still needed or works
> // NetFilter Handle Message
> "NHM", "EB 2E 49 8D 82 ? ? ? ? 4C" ptr.sub(4).rip()
> 
> // This sig overlaps into a function right after it, but this sig works on 2699, 3179, 3258.
> // Write Node
> "WN", "49 89 43 C8 E8 ? ? ? ? 84 C0 0F 95 C0 48 83 C4 ? C3 4C 8B DC" ptr.sub(0x49)
> 
> // Should be more stable
> // Send Session Detail Msg
> "SSDM", "4C 8D 85 ? ? 00 00 49 8B D5 49" ptr.add(0xE).rip()
> 
> // Can't we just `send_response(0)` in `handle_join_request` hook instead of trying to patch to original, on second thoughts that would require us to rewrite the entire `handle_join_request` function, I'm stupid.
> // Session Request Patch
> "SRP", "48 8B BD 70 01 00 00 E9 FF 00 00 00" ptr.add(0x13)
> ```
So, there's "Start Matchmaking Find Sessions" which is also named as SGSBGH which needs to be updated. (in pointers.cpp there are two SGSBGH)

**Comment by gir489returns** [comment]
> So, there's "Start Matchmaking Find Sessions" which is also named as SGSBGH which needs to be updated. (in pointers.cpp there are two SGSBGH)

Yes, the one that's broken should be renamed SMFS since it was clearly copied from the item before it SGSBGH but not renamed.

**Comment by CypherMorgan** [comment]
> > So, there's "Start Matchmaking Find Sessions" which is also named as SGSBGH which needs to be updated. (in pointers.cpp there are two SGSBGH)
> 
> Yes, the one that's broken should be renamed SMFS since it was clearly copied from the item before it SGSBGH but not renamed.

Yes, and after renaming, I got this [WARN/batch.hpp:113] Failed to find 'SMFS'.

**Comment by gir489returns** [comment]
> > > So, there's "Start Matchmaking Find Sessions" which is also named as SGSBGH which needs to be updated. (in pointers.cpp there are two SGSBGH)
> > 
> > 
> > Yes, the one that's broken should be renamed SMFS since it was clearly copied from the item before it SGSBGH but not renamed.
> 
> Yes, and after renaming, I got this [WARN/batch.hpp:113] Failed to find 'SMFS'.

This isn't as simple as a copypaste job, the bytes changed for a reason, which means the function needs to be reversed again which means our code needs to be updated. So unless you know why they changed, I suggest you wait until we fix it. Can't you guys touch grass or something? Do you guys seriously just play GTA V 24/7? How do you not get bored?

**Comment by CypherMorgan** [comment]
> > > > So, there's "Start Matchmaking Find Sessions" which is also named as SGSBGH which needs to be updated. (in pointers.cpp there are two SGSBGH)
> > > 
> > > 
> > > Yes, the one that's broken should be renamed SMFS since it was clearly copied from the item before it SGSBGH but not renamed.
> > 
> > 
> > Yes, and after renaming, I got this [WARN/batch.hpp:113] Failed to find 'SMFS'.
> 
> This isn't as simple as a copypaste job, the bytes changed for a reason, which means the function needs to be reversed again which means our code needs to be updated. So unless you know why they changed, I suggest you wait until we fix it. Can't you guys touch grass or something? Do you guys seriously just play GTA V 24/7? How do you not get bored?

Nah, I was just letting ya know. That's all.
Edit: I know this isn't a Copy-Paste Job.

**Comment by gir489returns** [comment]
> Nah, I was just letting ya know. That's all. 

Thanks, the 2 duplicate tickets and the 15 e-mails from this ticket I got wasn't enough to know GTA V updated. I really needed 16.

**Comment by maybegreat48** [comment]
It seems that Rockstar changed more stuff than I had anticipated. You might have to wait a bit longer

**Comment by ghost** [comment]
Perhaps we should delete the release so it doesn't confuse people

**Comment by Rxann** [comment]
> Perhaps we should delete the release so it doesn't confuse people

That could be a good idea

**Comment by ghost** [comment]
Closed
