### ISSUE TITLE
[Build]: 

### ISSUE THREAD

**Issue by kekobob122** [Yimura/YimMenu#3287]
### Describe the build issues

you need a update fot the new gta version

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Additional context

please update yimmenu

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by gir489returns** [comment]
This is a duplicate of #3285
