### ISSUE TITLE
[Request]: crash protect

### ISSUE THREAD

**Issue by Roseiit** [Yimura/YimMenu#329]
### Problem

add invalid clothing protect

### Solution

protect

### Reason

crash me

**Comment by womblee** [comment]
It won't be nice to see ebay modders that can't be crashed.

**Comment by Yimura** [comment]
> It won't be nice to see ebay modders that can't be crashed.

The game has enough crashes, if you aren't an ebay modder yourself you can find a non-public crash just fine.

**Comment by maybegreat48** [comment]
Don't we already have a few protections in the discussion that can be added?

**Comment by Yimura** [comment]
1. Which of them are up-to-date
2. Which of them are finished
3. I won't have much time to dedicate to this project till the end of August

I can however approve PR's but I don't know if I'll got the time to test them properly.

**Comment by maybegreat48** [comment]
Most of the protections are finished. However I can't test them too as I can't reliably get someone to crash me (they generally just use the breakup kick or the TSE crash)
