### ISSUE TITLE
[Bug]: crashing

### ISSUE THREAD

**Issue by molochkoff** [Yimura/YimMenu#3293]
### Describe the bug

i inject with xenos and crash soon after

### Steps To Reproduce

load gta
inject with xenos
crash

### Expected Behavior

load gta
inject with xenos
dont crash

### Logs

[logs.txt](https://github.com/user-attachments/files/16051283/logs.txt)

### Store

Epic Games

### Language

Russian

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ToXicVibezz** [comment]
Try using the latest .dll 👍

**Comment by NoSetViolin** [comment]
it also happen to me, even not work at fca2533

**Comment by molochkoff** [comment]
> Try using the latest .dll 👍

I'm using the latest .dll, which is listed [here](https://github.com/YimMenu/YimMenu/releases/tag/nightly)

**Comment by ToXicVibezz** [comment]
ohh mine is working so i assumed it should be for you as well. im sorry

**Comment by Alexander69H** [comment]
> > Try using the latest .dll 👍
> 
> I'm using the latest .dll, which is listed [here](https://github.com/YimMenu/YimMenu/releases/tag/nightly)

use this the one [here](https://github.com/YimMenu/YimMenu/pull/3288#issuecomment-2194132800)

**Comment by molochkoff** [comment]
> > > Try using the latest .dll 👍
> > 
> > 
> > I'm using the latest .dll, which is listed [here](https://github.com/YimMenu/YimMenu/releases/tag/nightly)
> 
> use this the one [here](https://github.com/YimMenu/YimMenu/pull/3288#issuecomment-2194132800)

yea. its working. thank you
