### ISSUE TITLE
[Bug]: Crashing on injection

### ISSUE THREAD

**Issue by The-UnXpLaiNeD** [Yimura/YimMenu#3294]
### Describe the bug

I inject with xenos and crash straight away

### Steps To Reproduce

load gta
inject with xenos
crash

### Expected Behavior

load gta
inject with xenos
dont crash

### Logs

[cout.log](https://github.com/user-attachments/files/16052908/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by qLucaa** [comment]
wait for the menu to update ,Jesus y all desperate

**Comment by Duisiufam** [comment]
How long does it take to complete the update :)))

**Comment by AdmiralArmin** [comment]
I have the same issue

**Comment by BlueVapor42** [comment]
This Online Version is 1.68, you'll have to wait until the menu is updated

**Comment by Calichuseets** [comment]
but when is it done

**Comment by Yimura** [comment]
Time to limit interactions with the repository again...

Duplicate of #3285
