### ISSUE TITLE
[Bug]: Can't inject.

### ISSUE THREAD

**Issue by jwestern1337** [Yimura/YimMenu#3302]
### Describe the bug

Just downloaded the latest build (1 hour old), gone to inject and get the error "General Error: Call to LoadLibraryW in remote process failed.", using xenos64 i get the erorr 0xC0000135.

### Steps To Reproduce

![image](https://github.com/YimMenu/YimMenu/assets/97195980/beb983d7-9dd1-480e-8537-8a1e64e4d74d)
![image](https://github.com/YimMenu/YimMenu/assets/97195980/361d8638-991d-461e-bf89-743c42ac7d48)

### Expected Behavior

Expected behaviour - inject properly lol

### Logs

[cout.log](https://github.com/user-attachments/files/16131734/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by infosergej** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/48388489/0a07a994-3887-4ca6-b104-31c044219684)
 
Extreme Injector v3.7.3 I'm also getting an error

**Comment by gir489returns** [comment]
Is this related to #3301? @xiaoxiao921 did you test it properly?

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/8889ab4d-7d5e-46a5-90dc-c3d980af21b9)

I am also getting the same error building locally.

**Comment by Yimura** [comment]
Yeah we've figured out the issue, we're fixing it currently.
