### ISSUE TITLE
[Bug]: cant spawn big vehicles

### ISSUE THREAD

**Issue by sosiso4ka111** [Yimura/YimMenu#3306]
### Describe the bug

when preview enable cant spawn big vehicles

### Logs

[cout.log](https://github.com/user-attachments/files/16133163/cout.log)

### Store

Epic Games

### Language

Russian

### YimMenu Language

Русский (RU)

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/assets/100792176/f33b7e9c-dbd7-4fea-934c-d9b84fd52efd

You keep changing and editing the parameters of the ticket, it's working fine.
