### ISSUE TITLE
[Bug]: Unable To Join Any Racing Job

### ISSUE THREAD

**Issue by ewenjam** [Yimura/YimMenu#3312]
### Describe the bug

Joining any public racing job (drift, stunt, street, etc.) results in a "BLOCKED START SCRIPT" notification from the host. This occurs regardless of whether the session has been set as trusted or not.

I have not tested if this occurs with friends hosting the race.

### Steps To Reproduce

1. Inject YimMenu
2. Load into GTA Online and matchmake into any racing event
3. Upon reaching the vehicle selection screen, you will get the "BLOCKED START SCRIPT" notification
4. Once the event starts, you will be stuck in the blurred loading screen
5. You will eventually get kicked back into freemode, with a depth of field effect applied to your screen as well from the vehicle selection menu

### Expected Behavior

You should be able to participate in the race job as usual

### Logs

[cout.log](https://github.com/user-attachments/files/16140945/cout.log)

NOTE: this log has the host of the race get detected as a modder, but this issue occurs with normal players as well. I am also using DLC Hash Spoofing. No LUA scripts have been loaded.

### Screenshots / Video

![startscript - Copy](https://github.com/YimMenu/YimMenu/assets/159111807/efdce00c-ca98-47c1-bba5-8736765e0272)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I tried joining subsequent racing jobs after the first BLOCKED START SCRIPT, and even though it would not show any notification, it would still kick me out of the race before it started.

I have tried enabling and disabling all protection measures as well.

Unsure if this affects other job types. I have tested missions and heists, where there have been no issues so far.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Thanks for reporting the bug, I saw some people on UC were complaining about this however we hadn't gotten a formal report on here with all the details.

@maybegreat48 any clue what's going on exactly? I'm assuming the script blocker doesn't understand it's in a legit job lobby and then blocking the start script request.

**Comment by prince4589** [comment]
yep can confirm this happened with me several time trying to join stunt races
the depth field and bloom effect was main thing i noticed after activity failed to join
needed a game restart to make it normal again

**Comment by tennomai** [comment]
Problem still occurs for me even after downloading latest nightly build
