### ISSUE TITLE
[Bug]: Force script host not working / host token spoofing not working

### ISSUE THREAD

**Issue by Tremzy** [Yimura/YimMenu#3315]
### Describe the bug

The Force script host is turned on, but i dont get host when i kick the previous one.
Also the host token spoofing dropdown isnt useable.

### Steps To Reproduce

1. Join a session
2. turn on force script host
3. join another session
4. kick the host
5. you dont get the host even though its turned on

### Expected Behavior

Get the host after kicking the previous host

### Logs

[cout.log](https://github.com/user-attachments/files/16143338/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

The session was modder free, which means the other host who got the host from the previous one after i kicked him, was NOT a modder.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
this is getting weird. Are users seriously using `force script host` to get the host?

Edit - paste the screenshot of menu where you facing problem.

**Comment by Tremzy** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/115173864/b494f76d-47f8-4ef6-937a-ec5a0609b37c)

**Comment by lonelybud** [comment]
as you can see host token spoofing is off. Dont use `Force Script Host` if you dont know what it does. I think you can see what each option does by hovering over it

**Comment by xiaoxiao921** [comment]
The  label is misleading, you need to use the drop-down combo box just above force script host checkbox if you want to be the session host.

**Comment by Tremzy** [comment]
As i mentioned earlier, the dropdown is greyed out, i cant use it.

**Comment by CypherMorgan** [comment]
> As i mentioned earlier, the dropdown is greyed out, i cant use it.

You can only use the dropdown in single player game mode. After changing it's settings you can try loading into the online session. ( You will have to kick the host if you want to become one. )

**Comment by Tremzy** [comment]
> > As i mentioned earlier, the dropdown is greyed out, i cant use it.
> 
> You can only use the dropdown in single player game mode. After changing it's settings you can try loading into the online session. ( You will have to kick the host if you want to become one. )

Love you :3

**Comment by snowleopardd** [comment]
SH kick doesn't work so i'm pretty sure SH script neither does
