### ISSUE TITLE
[Bug]: Our Desync Protections are getting bypassed again.

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#3326]
### Describe the bug

So i was in a public session flying around with my raiju till this guy felt attacked and decided to kick me from the session, i managed to join back and desync kicked his ass, but it seems like our protections failed, i remember using the dev builds like a week ago and literally no one could kick me, only hosts, so maybe they improved their desyncs.

Some notes:
(he wasn't the host)
(i had script host checked)
(all my protections were ON, including desync ofc)
(i wasn't actively trying to kick him, my desync didn't backfire)
(I joined back and desync kicked him, this proves he wasn't in control of the session)

### Steps To Reproduce

1. Go to online
2. Join this Lipinho0000 (72204852) guy (he's probably using a p2c)
3. Get desync kicked...

### Expected Behavior

The desync kick should get blocked or redirected to him.

### Logs

[cout.zip](https://github.com/user-attachments/files/16154723/cout.zip)

### Screenshots / Video

![image](https://github.com/YimMenu/YimMenu/assets/88536465/48e6156c-da09-413b-9dd6-d6be69a099f8)

https://github.com/YimMenu/YimMenu/assets/88536465/924c9e7e-5298-4c15-bbf9-39e05b10aed0

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

I'm using the latest official build in releases. 64faa40

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Please see https://github.com/YimMenu/YimMenu/issues/3119#issuecomment-2110965628

**Comment by Yimura** [comment]
As highlighted by maybegreat48, desync cannot be made perfect. If both parties have the protection it will still end up being a fight for who kicks who first.
