### ISSUE TITLE
[Bug]: Vehicle autodrive and vehicle fly bug

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#333]
### Describe the bug

1. Vehicle autodrive is stuck at the first drive option: "Law-Abiding", doesn't seem to switch to "The Road is Yours" anyhow. The notification is shown but the vehicle driving style still remains the same as it stops on traffic lights
2. Vehicle autodrive speed  doesn't match to the speed of car...For eg: if i set autodrive speed to 26, vehicle speed will top out at 58 mph.
3. Vehicle fly speed doesn't work at all. Irrespective of what I set on the slide, vehicle will fly at max speed allowed in game: 335mph

### Steps To Reproduce

-Not needed-

### Expected Behavior

-Not needed`

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by howdoiusekeyboard** [comment]
According to my testing, first bug got introduced because of #330.
I used the nightly build which is 1 commit behind and the first bug wasn't there

**Comment by aa15032261** [comment]
> According to my testing, first bug got introduced because of #330.
> I used the nightly build which is 1 commit behind and the first bug wasn't there

I’ll look into it. Thanks for the feedback!

**Comment by Yimura** [comment]
Has this been fixed in #332 ?

**Comment by howdoiusekeyboard** [comment]
Yes
