### ISSUE TITLE
[Improvement]: Japanese font support

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#3331]
### Which feature

The names of Vehicle and Gun are garbled. I think that's probably why YimMenu doesn't have a built-in Japanese font. Can add one?

### Reason

Since the names of vehicles and guns are not known, Vehicles Spawn etc. cannot be used.

### Additional context

![347332790-49b8f8ea-e7e9-45e1-a1b7-921ab74aee8c](https://github.com/YimMenu/YimMenu/assets/112477569/86a56ba8-a655-41aa-99f9-6b6011913ce3)

**Comment by gir489returns** [comment]
We do have support for Japanese, but it requires the game to have its language set to Japanese.

{eAlphabetType::JAPANESE, {"msyh.ttc", "msyh.ttf", "arial.ttf"}},

If those 2 fonts don't contain the Japanese characters required, submit one that does.

**Comment by oxUNKNOWNxo** [comment]
Sorry, the font was built-in.

I did some testing and found the following.
As a premise, I'm playing the Epic Games version.

-Even if I put "japanese" in the command line argument, the characters were garbled.
-Even if I typed in the command line argument, Settings->GTA Cache->Rebuild Cache and restarted, the characters were still garbled.
-It only displayed correctly when I set YimMenu's Settings->Languages->Menu Language to "Chinese(CN)" or "Chinese(TW)".

That's all.
P.S. Was the Unload button deleted?

**Comment by gir489returns** [comment]
@oxUNKNOWNxo This is because we don't have official support for a Japanese translation. Would you like to add one?

**Comment by oxUNKNOWNxo** [comment]
Hmm... It would be nice if I could add it, but I have never used Git and I am relying on Google Translate for this exchange, so I wonder if I would be able to translate it.

> It's only enabled for developers.

OK :-)

**Comment by gir489returns** [comment]
> Hmm... It would be nice if I could add it, but I have never used Git and I am relying on Google Translate for this exchange, so I wonder if I would be able to translate it.

While we apricate the gesture, we expect translators to do human translation. There's nothing stopping us from simply running the en_US through Google Translate and spitting a jp_JP translation, the problem is it probably wouldn't be understandable to most people. How are you able to read the menu if it is in English?

**Comment by oxUNKNOWNxo** [comment]
If it's in English, I read it using my knowledge and translation.
Everything is an experience...Ok, I'll try it.

**Comment by gir489returns** [comment]
I know this has nothing to do with the ticket, but have a look at this bird:

https://youtu.be/T8e6vezQYyM
https://youtu.be/7SDwE1re6Kc

His owner is Japanese.

**Comment by tyackman** [comment]
> I know this has nothing to do with the ticket, but have a look at this bird:
> 
> https://youtu.be/T8e6vezQYyM https://youtu.be/7SDwE1re6Kc
> 
> His owner is Japanese.

gumi beste

**Comment by oxUNKNOWNxo** [comment]
> I know this has nothing to do with the ticket, but have a look at this bird:
> 
> https://youtu.be/T8e6vezQYyM https://youtu.be/7SDwE1re6Kc
> 
> His owner is Japanese.

Whats this ?????

> https://youtu.be/T8e6vezQYyM

bird sounds like it's calling a person's name...
Propably Ume chan?

Either way, it's a cute bird :-)

**Comment by gir489returns** [comment]
> bird sounds like it's calling a person's name... Propably Ume chan?
> 
> Either way, it's a cute bird :-)

He's saying his name, Gumi-chan.

**Comment by oxUNKNOWNxo** [comment]
birds calling his name, i see :D

**Comment by oxUNKNOWNxo** [comment]
I'm translating using automatic translation, but it is difficult to translate nearly 2000 lines of data...

**Comment by oxUNKNOWNxo** [comment]
I've identified where the problem is so I'll close it.
