### ISSUE TITLE
[Request]: please bring back auto add to database

### ISSUE THREAD

**Issue by r00st3r-tech** [Yimura/YimMenu#3334]
### Problem

[Request]: please bring back auto add to database with a block join as a reaction to de sync and other forms of crash. idk if its me that's done something or the update but assistance would be great. i'm finding because of the no db i'm still crashing sometimes. thank you for this menu btw your amazing

### Solution

auto add to database with a block join as a reaction to de sync and other forms of crash.

### Reason

still occasionally getting crashed maybe x4-8 times a day.

### Additional context

leaving the logs open after game closes would also be helpful

**Comment by snowleopardd** [comment]
Yeah i was looking for this feature but i never knew it was removed, i think it's essential to save time before getting kicked

**Comment by r00st3r-tech** [comment]
exactly atleast a way to delay them by 10 seconds after the warning "player1234" has tried to crash you blip appears in the top right

**Comment by Yimura** [comment]
This is still possible, just mark in the reaction settings to add people to the Player DB. We removed any implicit adding to the Player DB as there were people complaining about it getting too large.

As such you need to manually choose for which events you want to add players to the DB and what sort of action to take.

**Comment by Yimura** [comment]
The following options should be available under Settings > Reactions:
- Reaction in Chat (All/Team chat)
- Notify (show notification in-game)
- Log (log to console and log file)
- Add to database
- Block Join
- Kick Player (instantly if the offending event is detected)
- Timeout (doesn't appear to be used currently)
