### ISSUE TITLE
[Bug]: Crash methods crashing myself

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3349]
### Describe the bug

Use parachute crash.
Crashes yourself but not the other person.
Close GTA since not responding anymore.
Also i cant find spoof host token anymore, its possible it got removed idk

### Steps To Reproduce

1. Use Parachute crash
2. Crash yourself
3. Profit :)

### Expected Behavior

Not crashing myself but the other person

### Logs

[cout.log](https://github.com/user-attachments/files/16227719/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
> Use parachute crash.

Crashing features are not included in Yimmenu. Its not a bug.

> Also i cant find spoof host token anymore, its possible it got removed idk

it should be there in network controls. The UI has been changed.

**Comment by Yimura** [comment]
Invalid issue tbh, YimMenu isn’t meant to crash others and as such isn’t trying/made to catch self caused crashes.
