### ISSUE TITLE
[Request]: RP levels

### ISSUE THREAD

**Issue by Ahmadalbalaa** [Yimura/YimMenu#3352]
### Solution

A way to add rp level or double your rp gains or any other way to get rp meybe add rp directly like set my level to 1000 or 300 or just earn ×10 or ×100 or ×1000 rp we really need this feature we would love to have it in yim menu

### Reason

We all love money in gta am i right we all love buying stuff in this game but there is one problem we can make money but the problem is if we dont have high rp level we cant buy all the upgrades in a viecle if you add this feature im 100% sure you will get more than 50 million downloads in just 7 hours

### Additional context

Im very happy that i discovered this mod menu and i will continue to support it till my death

**Comment by gir489returns** [comment]
This counts as recovery, we are not a recovery menu.

**Comment by Ahmadalbalaa** [comment]
Oh ok thanks for the reply
