### ISSUE TITLE
[Improvement]: No notifications about source of explosions

### ISSUE THREAD

**Issue by opt8** [Yimura/YimMenu#3353]
### Which feature

Earlier i had notifications about all explosions in my area, they told me who initiated the explosion, and from whom the "complaint" came. When the moder looped explosions, or rockets/mines/bombs were used without reload, it was possible to immediately understand who was doing it. There are no such notifications right now, which is sad. Maybe im missing some settings, but I haven't changed any of them since i received these notifications.

### Reason

Quick understanding of the source of explosions

**Comment by gir489returns** [comment]
If you get that notification, it means the cheat rejected the explosion event.

**Comment by opt8** [comment]
> If you get that notification, it means the cheat rejected the explosion event.

no, they were like "player1 is blamed for the explosion by player2"

**Comment by gir489returns** [comment]
> > If you get that notification, it means the cheat rejected the explosion event.
> 
> no, they were like "player1 is blamed for the explosion by player2"

https://github.com/YimMenu/YimMenu/blob/49a34f5789238c451e2cfe1dbd3c9b88f121666c/src/hooks/protections/received_event.cpp#L371-L384

The code simply logs the explosion then rejects the event, that's all it does. I'm not sure what more you want us to do here?

**Comment by opt8** [comment]
> > > If you get that notification, it means the cheat rejected the explosion event.
> > 
> > 
> > no, they were like "player1 is blamed for the explosion by player2"
> 
> https://github.com/YimMenu/YimMenu/blob/49a34f5789238c451e2cfe1dbd3c9b88f121666c/src/hooks/protections/received_event.cpp#L371-L384
> 
> The code simply logs the explosion then rejects the event, that's all it does. I'm not sure what more you want us to do here?

Two days ago i met modder which looped explosions on me. they were not reject, and i didnt get any logs. maybe its my mistake and i turned something off. but all checkboxes are selected in protection section, and all the checkboxes that are responsible for notifications in the reactions section are also selected.

**Comment by lonelybud** [comment]
>they were not reject, and i didnt get any logs. 

`eNetworkEvents` are not logged I guess. You will receive explosion events here.

**Comment by opt8** [comment]
> > they were not reject, and i didnt get any logs.
> 
> `eNetworkEvents` are not logged I guess. You will receive explosion events here.

i just got event for myself when i threw the grenade and exploded vehicle. but it happened by accident and no matter how many further explosions I did (near the players or not, were the cars blown up or not), there were no notifications more

**Comment by Yimura** [comment]
Explosion blame detection is quite shit in YimMenu and can't be 100% trusted, however I do agree that a ratelimit should be imposed if there's an abnormal amount of explosions in a short period of time.

**Comment by Yimura** [comment]
Duplicate of #3369
