### ISSUE TITLE
[Bug]: No fill inventory

### ISSUE THREAD

**Issue by BabyLoves** [Yimura/YimMenu#3354]
### Describe the bug

When click "fill inventory" does nothing.

### Steps To Reproduce

1. Open the GTA
2. Inject the .dll
3. Use some ammu or items
4. Then use the 'fill inventory' button

### Expected Behavior

Fill all items and ammu on inventory

### Logs

[cout.log](https://github.com/user-attachments/files/16228539/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

Portuguese (BR)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Works fine for me.

**Comment by lonelybud** [comment]
"Refills snacks and armor"
