### ISSUE TITLE
[Request]: Info for usage under Linux?

### ISSUE THREAD

**Issue by Hyperstructx** [Yimura/YimMenu#3356]
### Problem

I want to use the menu under Linux, with Steam and Steam's compatibility layer as well as ProtonGE+GTA V which currently works mostly flawlessly without any menus under Linux (Fedora 40, proprietary NVIDIA drivers via rpmfusion).

### Solution

What's needed to see this become a thing? Maybe I can contribute if I know specifically where to start or someone to write a job description to help me find a freelance programmer to hire to get this done for me and then as a pull/merge request to upstream it into the main YimMenu repo...

### Reason

There are no other menus for usage under Linux that I am aware of.

**Comment by gir489returns** [comment]
>Refuses to pay for windows

>Will pay a programmer to write a cross compatibility layer for a cheat. 

I don’t know what you’re talking about.  Several people use YimMenu on Linux just fine. Yim himself is on Arch. So you just have to figure out how to LoadLibrary the YimMenu DLL through proton.

**Comment by Hyperstructx** [comment]
> > Refuses to pay for windows
> 
> > Will pay a programmer to write a cross compatibility layer for a cheat.
> 
> I don’t know what you’re talking about. Several people use YimMenu on Linux just fine. Yim himself is on Arch. So you just have to figure out how to LoadLibrary the YimMenu DLL through proton.

Oh, wow, interesting...

Is there anything public for this? I have heard of folks using 'SteamTinkerLaunch' to do it but some detailed instructions would be greatly appreciated.

EDIT: BTW, what about Lua Scripting support and API / Script feature parity/compatibility with scripts made for other menus such as Stand?

**Comment by Yimura** [comment]
See #334

**Comment by Hyperstructx** [comment]
> See #334

Thanks. Does your repo, "Injector" work for this purpose or which injector do you suggest if not ASI Loader (latest comments there suggest that ASI Loader and rename of DLL had become problematic, untested by me); Cheat Engine or something else?

**Comment by SylveonDeko** [comment]
so heres the thing, im using the regular rockstar games launcher and want to use yim, any solution? Renaming the dll just makes it want to update  gta

**Comment by tupoy-ya** [comment]
> so heres the thing, im using the regular rockstar games launcher and want to use yim, any solution? Renaming the dll just makes it want to update gta

Try adding `-skipPatcherCheck` to `GTA5.exe` launch parameters, that's what the steam version does so maybe it will help but it probably wont because the check is not in `GTA5.exe`.

You can also write a small program in C/C++ that starts `GTA5.exe` and name it `PlayGTAV.exe`, that way GTAV will think you are running it through the launcher. It may however ask for a CD-Key, and I don't know what happens if you give it your CD-Key.

**Comment by adrienleblanc123** [comment]
I wrote a short guide on DLL injection under Proton to get YimMenu working perfectly on Linux.
https://gist.github.com/adrienleblanc123/a0721cac42b87c2af48c3a6d9c1c8d1b
