### ISSUE TITLE
[Request]:  Contact Yimura, contributing further

### ISSUE THREAD

**Issue by Hyperstructx** [Yimura/YimMenu#3358]
### Problem

I would like to contact Yimura directly and contribute toward the project with a donation to Yimura and other contributors...

However while trying to contact Yimura via details on their GitHub profile, via Discord, it seems Yimura is not accepting requests.

### Solution

Please open requests for a few hours or provide alternate contact details?

### Reason

I like the project and after reviewing it and related projects in greater detail, would like to provide further support in the form of a monetary donation.

**Comment by Tayipc38** [comment]
Is your inquiry simply to donate or do you have something else you'd like to ask?

**Comment by Hyperstructx** [comment]
> Is your inquiry simply to donate or do you have something else you'd like to ask?

I would like to establish contact with those I am to donate to. Other comments (Or questions I might like to ask anyone) seem inappropriate and unprofessional for this particular channel and its intended purposes. I searched for a Discord server for this project and did not find one.

**Comment by ghost** [comment]
Used to be a public Discord server for that but it went down

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/discussions/2533
