### ISSUE TITLE
[Improvement]:  Dont let Yimmenu unlock the los santos customs Modifications！

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3359]
### Which feature

When I injected Yimmenu, it happened.
When I went to the los santos customs, YimMenu canceled the level restrictions on my vehicle upgrades. How do I turn this off?

### Reason

There can be a switcher to cancel and restore normal game settings to satisfy the players who like to unlock it normally
Put a switch in the settings for players to choose.

**Comment by Inkmaveil** [comment]
Please

**Comment by Yimura** [comment]
The following code should be commented/removed, we don't want any implicit behaviour imposed on users.

https://github.com/YimMenu/YimMenu/blob/2ff310568475f63d1fc3da5e78a2926b4f557d25/src/native_hooks/carmod_shop.hpp#L9-L51

**Comment by ghost** [comment]
> The following code should be commented/removed, we don't want any implicit behaviour imposed on users.
> 
> https://github.com/YimMenu/YimMenu/blob/2ff310568475f63d1fc3da5e78a2926b4f557d25/src/native_hooks/carmod_shop.hpp#L9-L51

still unlocked in the los santos customs，Just like when I'm in auto shop,
