### ISSUE TITLE
[Request Feature]: Add Semi godmode for character

### ISSUE THREAD

**Issue by rr1231234** [Yimura/YimMenu#3361]
### Problem

I see there's a semi godmode for other players but there isn't one for myself.

**Comment by dqb286** [comment]
find yourself through that same menu and you can
In the "Player" tab you are correct, down below in the players in lobby menu, try there

**Comment by rr1231234** [comment]
> find yourself through that same menu and you can In the "Player" tab you are correct, down below in the players in lobby menu, try there

wouldnt put up this feeature request if it worked for my character, probably due to the protection

**Comment by xesdoog** [comment]
Go to the scripts folder, create a new text file and rename it to auto-heal.lua or something like that then paste this inside it and save it. A new tab will appear under the **Self** tab named "**Auto Heal**", just open it and check the box.
```lua
autoregen = gui.get_tab("GUI_TAB_SELF"):add_tab("Auto-Heal")

local autoheal = false
local chkbxTxt = "STRING"

autoregen:add_imgui(function()
  ImGui.TextWrapped("Automatically Heal Yourself Over Time");ImGui.Spacing()
  regen, _ = ImGui.Checkbox("##enable", regen, true);ImGui.SameLine();ImGui.Text(chkbxTxt)
    if regen then
      autoheal = true
      chkbxTxt = "On"
    else
      autoheal = false
      chkbxTxt = "Off"
    end
end)

script.register_looped("healme", function(ah)
  ah:yield()
  if autoheal and not ENTITY.IS_ENTITY_DEAD(self.get_ped()) then
    local maxHp  = ENTITY.GET_ENTITY_MAX_HEALTH(self.get_ped())
    local myHp   = ENTITY.GET_ENTITY_HEALTH(self.get_ped())
    local myArmr = PED.GET_PED_ARMOUR(self.get_ped())
    if math.floor(myHp) < maxHp and math.floor(myHp) > 0 then
      if PED.IS_PED_IN_COVER(self.get_ped()) then
        ENTITY.SET_ENTITY_HEALTH(self.get_ped(), myHp + 20, 0, 0)
      else
        ENTITY.SET_ENTITY_HEALTH(self.get_ped(), myHp + 10, 0, 0)
      end
    end
    if myArmr == nil then
      PED.SET_PED_ARMOUR(self.get_ped(), 10)
    end
    if myArmr ~= nil and math.floor(myArmr) < 100 then
      PED.ADD_ARMOUR_TO_PED(self.get_ped(), 0.5)
    end
  end
end)
```

**Comment by rr1231234** [comment]
@xesdoog thanks dawg, do you happen to have a script for RP tunable? I wanna pause my RP gain to 0 so the level will stay at 420

**Comment by xesdoog** [comment]
> @xesdoog thanks dawg, do you happen to have a script for RP tunable? I wanna pause my RP gain to 0 so the level will stay at 420

No I don't but check [UC forum](https://www.unknowncheats.me/forum/grand-theft-auto-v/) you'll probably find something there.

**Comment by Yimura** [comment]
Why would you want a semi-godmode? Semi-godmode is offered for other players as there's no way to give them full god mode.

**Comment by rr1231234** [comment]
> Why would you want a semi-godmode? Semi-godmode is offered for other players as there's no way to give them full god mode.

For fun I guess. Actually I'd love the same SemiGodmode from kiddion's menu which just make character harder to kill (more resistance to weapons), it's not a total godmode or auto heal
