### ISSUE TITLE
[Bug]: Small Sessions When Using YimMenu

### ISSUE THREAD

**Issue by SubjectZeros** [Yimura/YimMenu#3362]
### Describe the bug

I get into small sessions when using YimMenu. I used default settings and tried different network settings but couldn't find a fix. Also sometimes I get into bigger sessions (20-25 players) but nobody new joins and that session dies eventually. This only happens when using YimMenu.

### Steps To Reproduce

1. Inject YimMenu
2. Join a public session
3. Check the player count.

### Expected Behavior

There should not be a difference in the session size using YimMenu and not using it.

### Logs

[cout.txt](https://github.com/user-attachments/files/16251565/cout.txt)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

Is this even a bug?

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
go to Tab Network/Session Browser and check the checkboxes for the number of players from 25 to 32 and check the Replace Player Matchmaking checkbox.  In order for the session to fill quickly, go to the Network/Spoofing tab and set the Multiplexing Session checkbox active and set the value to the maximum.  this should help in your case

EDIT: I forgot something else.  To make the session fill up even faster, go to the Network/Spoofing tab and set the fake number of players in the session to 25

**Comment by SubjectZeros** [comment]
Thank you. Worked like a charm!
