### ISSUE TITLE
[Bug]: Update gta to 3274

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3366]
### Describe the bug

There's a new update that's breaking the menu.

### Steps To Reproduce

1. update the game
2. run
3. inject
4. crash

### Expected Behavior

no crash

### Logs

[without_scripts.log](https://github.com/user-attachments/files/16265849/without_scripts.log)
[without_scripts_and_cache.log](https://github.com/user-attachments/files/16265852/without_scripts_and_cache.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment]
Works fine for me! Maybe you're injecting too early? ( I tried injecting after loading into singleplayer and had to update cache)

Edit: There might be some Globals that got outdated. I can load into online w/o any issues.

**Comment by ghost** [comment]
> There might be some Globals that got outdated. I can load into online w/o any issues.

I don't think it's safe yet

**Comment by xiaoxiao921** [comment]
Outdated lua script?

**Comment by Yimura** [comment]
We'll still need to update the metadata.json.

**Comment by ghost** [comment]
but my game still crashes
[without_scripts.log](https://github.com/user-attachments/files/16265849/without_scripts.log)
[without_scripts_and_cache.log](https://github.com/user-attachments/files/16265852/without_scripts_and_cache.log)

**Comment by CypherMorgan** [comment]
> but my game still crashes [without_scripts.log](https://github.com/user-attachments/files/16265849/without_scripts.log) [without_scripts_and_cache.log](https://github.com/user-attachments/files/16265852/without_scripts_and_cache.log)

Could be Steam Version's issue? I used RSL version to test.

**Comment by snowleopardd** [comment]
Epic Games version here, no issues, it asked me to rewrite the cache and nothing else, no crashes

**Comment by tiCkuhAr** [comment]
I'm also experiencing crashes on the Epic Games version.
[cout.log](https://github.com/user-attachments/files/16266296/cout.log)

**Comment by xiaoxiao921** [comment]
Can someone who is experiencing crashes send me their AppData YimMenu folder zipped and upload it here?
This is most likely related to some caching we do, I suspect something related to tunables / globals

**Comment by tiCkuhAr** [comment]
25 crashes later and I got it to work

**Comment by tiCkuhAr** [comment]
When I inject the menu right when GTA opens, it seems to prevent Social Club from loading.

**Comment by gir489returns** [comment]
> 25 crashes later and I got it to work

Do not go online with YImMenu, the anit-cheat disabler is not working.

**Comment by tiCkuhAr** [comment]
I had no plans of going online until after the menu is updated, but it's still good to know.

**Comment by prince4589** [comment]
i did inject yim once after the update , but it did not crashed the game and worked fine with steam version, just cache update thats it , now im playing without it idk if i will get banned or not

**Comment by maybegreat48** [comment]
> Can someone who is experiencing crashes send me their AppData YimMenu folder zipped and upload it here?
This is most likely related to some caching we do, I suspect something related to tunables / globals

Yeah, the old cache breaks the anticheat bypass for some reason

**Comment by xiaoxiao921** [comment]
> > Can someone who is experiencing crashes send me their AppData YimMenu folder zipped and upload it here?
> > This is most likely related to some caching we do, I suspect something related to tunables / globals
> 
> Yeah, the old cache breaks the anticheat bypass for some reason

I vote for permanently disabling this feature. We keep having various related issues where the only solution we had for users was for them to delete their AppData/YimMenu folder, which is not really acceptable

**Comment by rk134** [comment]
i am using a yim dll thats slightly behind HEAD (2-3 commits), but it worked fine earlier, and i was able to inject it without issues.

how can i check if the anti-cheat bypass even works?

**Comment by maybegreat48** [comment]
> I vote for permanently disabling this feature. We keep having various related issues where the only solution we had for users was for them to delete their AppData/YimMenu folder, which is not really acceptable

Why are we using the timestamp as an identifier instead of the size like we did before?

**Comment by gir489returns** [comment]
> I vote for permanently disabling this feature. We keep having various related issues where the only solution we had for users was for them to delete their AppData/YimMenu folder, which is not really acceptable

For me, the cache updated fine and I am not crashing. This sounds like square peg round hole situation. Do we have the cheat bootstrap itself each time, or do we just fix the bad apples as we find them? What exactly from the cache isn't working? The tunables and/or globals should never be cached at rest.

**Comment by gir489returns** [comment]
> Why are we using the timestamp as an identifier instead of the size like we did before?

Because we had a problem where for some reason, the SCDLL was exactly the same size as its previous update, and did not trigger an update, the only difference between it was the TimeDateStamp in the NTDLL header.
