### ISSUE TITLE
[Feature Request]: Make car windows behave like Armored Kuruma bulletproof windows

### ISSUE THREAD

**Issue by rr1231234** [Yimura/YimMenu#3370]
You get in a car, toggle this on, the windows/windshield will have bulletproof

**Comment by Tayipc38** [comment]
Any reason why u didn't stick to the issue format?

**Comment by gir489returns** [comment]
bro i got sandwiches to eat and my mom is calling me i dont have time to write an essay 4 u!!!!!!!

**Comment by Yimura** [comment]
Issue format was not followed.
