### ISSUE TITLE
[Request]: OOM Kick Reaction

### ISSUE THREAD

**Issue by snowleopardd** [Yimura/YimMenu#3375]
### Problem

There's no way to set reactions to an OOM kick.

### Solution

Add OOM Kick to the reactions tab

### Reason

**My personal reason and what I've seen:**
This reaction is so important because it warns us that the attacker might be about to send us a desync kick as its last resort (predictable human behavior), and what does this means? if we enable this reaction we can instantly trigger a smart kick/block join against them before they have time to do anything else (like sending all their crash/kick methods towards us) (this happened to me yesterday and i couldn't find the guy on the player list, and got me desync kicked..)

Also the reactions not only are useful for auto kicking them, the auto-add to database feature is a must honestly.

Anyways, it's needed whatever the reason is, we got network bail and other useless kicks in reactions, why not OOM?

### Additional context

![300px-Modern_Problems_Require_Modern_Solutions](https://github.com/user-attachments/assets/0b9ae98b-cf9a-40f3-b0e0-356f3764df75)

**Comment by ToXicVibezz** [comment]
Smart Kick does this desync if the player isnt host.. `if (g_player_service->get_self()->is_host())
			{
				player_command::get("breakup"_J)->call(player, {});
			}
			else
			{
				if (player->is_host())
					player_command::get("oomkick"_J)->call(player, {});
				else
					player_command::get("desync"_J)->call(player, {});
			}`

**Comment by snowleopardd** [comment]
> Smart Kick does this desync if the player isnt host.. `if (g_player_service->get_self()->is_host()) { player_command::get("breakup"_J)->call(player, {}); } else { if (player->is_host()) player_command::get("oomkick"_J)->call(player, {}); else player_command::get("desync"_J)->call(player, {}); }`

thats totally fine
