### ISSUE TITLE
[Improvement]: Some of the menus are not displayed correctly.

### ISSUE THREAD

**Issue by namachoco0228** [Yimura/YimMenu#3390]
### Which feature

When selecting a car spawn or gun item, it does not display correctly and “???” is displayed.

### Reason

I want to fix it because it is inconvenient to operate it as I want.

### Additional context

![スクリーンショット 2024-07-20 192304](https://github.com/user-attachments/assets/3d6a7c3b-67ff-4d30-8430-d4972a6fee89)

**Comment by Yimura** [comment]
This is because your game language does not match the language the menu is in, what language is your game set as?

**Comment by namachoco0228** [comment]
The game language is Japanese, but the menu is in English. However, I tried changing the game language to English, but nothing changed.

**Comment by ghost** [comment]
> The game language is Japanese, but the menu is in English. However, I tried changing the game language to English, but nothing changed.

after you have changed the language everywhere to English you will need to rebuild the cache

**Comment by namachoco0228** [comment]
It's now displayed correctly! Thank you so much!
