### ISSUE TITLE
[Improvement]: Buttons for kamikazes, etc.

### ISSUE THREAD

**Issue by Donald-Trump-Maga** [Yimura/YimMenu#3391]
### Which feature

I noticed that you recently added a kamikaze team and a squad, but it’s not clear how to use it. after entering two arguments as indicated in the notification, the error is still present. I suggest adding this to the Network/Controls/PlayerOptions tab and the Player tab.

### Reason

It is not possible to use this on the command line or write me the correct command for this

**Comment by Tayipc38** [comment]
Honestly, the suggestion system should help you out there. The commands were complimentary test subjects when developing the CMD system.

**Comment by Donald-Trump-Maga** [comment]
According to the idea, after entering the kamikazeall command, something like REGULAR, SELF, TOPDOWN should be offered and then the name of the vehicle when entered, or vice versa, but this does not happen. Perhaps I'm entering the command incorrectly somehow?

**Comment by Tayipc38** [comment]
`kamikazeall` is an automatically generated command which does not work well with hand crafted multi argument commands like this one. For one, I don't think it inherits the suggestions. Try using the singular one `kamikaze`.

**Comment by Donald-Trump-Maga** [comment]
Yea, but I want to destroy the session with the `kamikazeall` command. what do you recommend to do? or how to write it correctly? and the same with squadall

**Comment by Tayipc38** [comment]
> Yea, but I want to destroy the session with the `kamikazeall` command. what do you recommend to do? or how to write it correctly? and the same with squadall

Wouldn't know what is needed to make this suitable, but I do know it won't work as you expect since players are most probably out of your render range and the engine won't spawn anything that far.

**Comment by ghost** [comment]
> Yea, but I want to destroy the session with the `kamikazeall` command. what do you recommend to do? or how to write it correctly? and the same with squadall

you can use this [lua script](https://github.com/Deadlineem/Extras-Addon-for-YimMenu) for that. the functions are called `Clown Jet Attack` and `Clown Bombers` do almost the same thing

**Comment by Donald-Trump-Maga** [comment]
> > Yea, but I want to destroy the session with the `kamikazeall` command. what do you recommend to do? or how to write it correctly? and the same with squadall
> 
> you can use this [lua script](https://github.com/Deadlineem/Extras-Addon-for-YimMenu) for that. the functions are called `Clown Jet Attack` and `Clown Bombers` do almost the same thing

thanks, I'll try this
