### ISSUE TITLE
[Bug]: crash when injecting

### ISSUE THREAD

**Issue by GHDavor** [Yimura/YimMenu#3394]
### Describe the bug

the cmd window throws and error and crashes

### Steps To Reproduce

1. open gta 5 2. open xenos 3. inject

### Expected Behavior

amm, work normally?<r

### Logs

[cout.log](https://github.com/user-attachments/files/16321956/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment]
Unable to Reproduce for now.

**Comment by maybegreat48** [comment]
Are you loading anything else with YimMenu?

**Comment by gir489returns** [comment]
> Are you loading anything else with YimMenu?

He can't be, he checked the box that he pinky swore he wasn't!!!!!!!!!!

**Comment by CypherMorgan** [comment]
> He can't be, he checked the box that he pinky swore he wasn't!!!!!!!!!!

Lmao

**Comment by maybegreat48** [comment]
> He can't be, he checked the box that he pinky swore he wasn't!!!!!!!!!!

Odds are he's co-loading something, likely Menyoo, but I didn't want to close it to give him the benefit of doubt

**Comment by Yimura** [comment]
100% something is co-loaded with YimMenu making this issue invalid.
