### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by cultysdaop** [Yimura/YimMenu#3397]
### Problem

Add more fun features like UFO abduction, pizza delivery but fix them first half of the time they works and half of the time they dont
Add back "Gooh" feature that would steal from players 10k cash like back then, i saw that feature in the menu before
But just make Gooh spawn instantly, faster cuz before it was slow and half of the time it didnt spawn
add new features that would maybe um trap players in some ufo abduction site where they would fight aliens or something
Add a feature that would sent more thugs like Gooh and idk steal most of their cash or their ammo or guns or something
Add a feature that would trap them in a truck, like they would spawn in a truck thats controlled by AI and AI would drive to a nearest sea/river water and so truck door gate couldnt be open by walking into it like in Aurora menu truck trap 

### Solution

Add more fun features like UFO abduction, pizza delivery but fix them first half of the time they works and half of the time they dont
Add back "Gooh" feature that would steal from players 10k cash like back then, i saw that feature in the menu before
But just make Gooh spawn instantly, faster cuz before it was slow and half of the time it didnt spawn
add new features that would maybe um trap players in some ufo abduction site where they would fight aliens or something
Add a feature that would sent more thugs like Gooh and idk steal most of their cash or their ammo or guns or something
Add a feature that would trap them in a truck, like they would spawn in a truck thats controlled by AI and AI would drive to a nearest sea/river water and so truck door gate couldnt be open by walking into it like in Aurora menu truck trap 

### Reason

Cause fun and would be worth it

**Comment by Yimura** [comment]
No title and poorly formatted issue.

Please come back when you’ve put some effort into following the issue template and put a title.
