### ISSUE TITLE
[Request]: how to change wanted level

### ISSUE THREAD

**Issue by rarcns** [Yimura/YimMenu#3399]
### Solution

I want to know how to change the wanted level.
I looked at your code, but I didn't see how you changed the wanted level.
Can you give me something that turns the wanted level to 5 as an example?
I would be grateful if you could show it with a simple function.

### Reason

For the future development of yimmenu, you need to understand the menu code by myself

**Comment by xiaoxiao921** [comment]
https://letmegooglethat.com/?q=c%2B%2B+tutorial
