### ISSUE TITLE
[Bug]: YimMenu is triggering game anti-cheat

### ISSUE THREAD

**Issue by prince4589** [Yimura/YimMenu#3401]
### Describe the bug

after using the latest yim build other of my yim user friends said that ive triggered game anti cheat and ive been detected modder by game anti cheat !!
idk if i will get banned or not :(

### Steps To Reproduce

1. inject latest build
2. wait for other yim user to detect game anti cheat trigger !! edit even detected by stand user

### Expected Behavior

not to trigger game anti cheat and not to be detected as modder by game anti-cheat

### Logs

[cout.log](https://github.com/user-attachments/files/16336322/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

just loaded the fresh yim dll and also made sure to clear old cache by myself beforehand.
As i joined few of my fellow yim user friends are going mad in chat about me triggering my anti cheat and im in panic after their mod menu alerting anti cheat trigger on me

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
are you injecting menu in singleplayer or online mode?

EDIT: it could be a detection of the stand itself and not the rockstar anti-cheat. correct me if I'm wrong

**Comment by prince4589** [comment]
obvio. single player !!!
the detection was shown in both yim user and stand user, they all were my friends.

yim friends said (prince detected by modder by game anti cheat , prince triggered game anti-cheat)
stand friend said (prince triggered rockstar anti cheat)

they all messaged me on discord about my detection so i quit my game and clear cache and loaded old yim dll 1 build previous of current build (2 days ago build) and started game with that prev. yim build and the trigger notification was still popping up on their screens and after some time the map went low res. the textures where low res of buildings and roads , everything and then my game crashed !!!

and since then im on my alt account with that old yim build and its not triggering on other of my friends !!!

i might load old yim on my main account again to test it and will notify you all !!!

**Comment by ghost** [comment]
![giphy](https://github.com/user-attachments/assets/0843a851-f331-497b-9396-ea8fb8287e06)

**Comment by prince4589** [comment]
am i cooked ?here

**Comment by xiaoxiao921** [comment]
If you remove the lua scripts, does it still happen?

**Comment by prince4589** [comment]
yep still happened !!! my first guess was its must be lua scripts 
edit : im using extra addons and yimactions if you wanna know :\

**Comment by CypherMorgan** [comment]
> after some time the map went low res. the textures where low res of buildings and roads , everything and then my game crashed !!!

I face that issue as well from a couple of days.

**Comment by maybegreat48** [comment]
1. Did you install an "antiban hosts file" or something similar? Please remove it if you did
2. Can you reproduce this without a menu loaded?
3. Can you send me your friend's YimMenu log when the detection gets triggered?

**Comment by gir489returns** [comment]
I think the user's terrible articulation and childish phraseology makes this ticket seem like he's trigger the Rockstar anti-cheat, when in fact, he's just coping and seething about Stand and other Yim users detecting him as a cheater. This is a non-issue and probably due to user-error by enabling something that said it would be detectable by other modders.

**Comment by prince4589** [comment]
no i did not use any anti ban hosts file !!
i will try to ask log files from my friends !!

and i'm using yim since april and regularly check this git hub section for anything serious always pay attention to new issues here and never immediately use yim after any slight or major game update.

i mean other modders can see desync kick protection that i know, but im not sure about anti cheat detection notification


edit : tested without menu loaded on main acc. and its not showing on yim and stand users as of now

but im seeing 
[18:58:16.5916061][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x31B61C
[18:58:16.5952636][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x337FB0
[18:58:16.5952834][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x337F88
[18:58:16.5953563][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x404204
[18:58:16.6016732][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45DA94
[18:58:16.6017781][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45CCA8
[18:58:16.6017828][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x5CD410
[18:58:16.6068432][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x672338
[18:58:16.6068651][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x672360

these lines popup most of the time in dev console

**Comment by maybegreat48** [comment]
OK, can you get them to send their logs to you?

**Comment by prince4589** [comment]
the guys are offline rn i will get their logs asap if they are online tomorrow

**Comment by Mr-X-GTA** [comment]
@prince4589 Can you join my session?

**Comment by xesdoog** [comment]
This happened to me too about a week ago. I only play in locked solo sessions but a week ago a friend asked me to help sell their bunker so I joined with a fresh YimMenu (newly downloaded Nightly build, no cache, no Lua scripts, nothing) and in the middle of the sale mission they said they got a notification saying I triggered R* anti-cheat. My friend was using another mod menu (I think phantoms or something)

**Comment by tiCkuhAr** [comment]
I have also had this happen before. It's a bit random when it does it.

**Comment by prince4589** [comment]
@maybegreat48 
[07-22-2024-21-41-45_cout.log](https://github.com/user-attachments/files/16353091/07-22-2024-21-41-45_cout.log)

the log files from my friend

**Comment by snowleopardd** [comment]
This happened to me as well

**Comment by Yimura** [comment]
@prince4589 could you send us your settings.json file and make sure that you send the settings.json file when you've triggered the anti-cheat. We have apparently implemented a feature incorrectly in YimMenu which is causing this event to be sent out in the lobby, however because of the large amount of features in YimMenu it's quite hard to pinpoint what is causing the event to be sent out.

@mikedrugs, if you could send your settings.json file as well when you've confirmed that your game is also sending out the anti-cheat detection event then we can more easily figure out which feature is causing this.

**Comment by prince4589** [comment]
@Yimura  
[settings.json](https://github.com/user-attachments/files/16360458/settings.json)

**Comment by snowleopardd** [comment]
> @prince4589 could you send us your settings.json file and make sure that you send the settings.json file when you've triggered the anti-cheat. We have apparently implemented a feature incorrectly in YimMenu which is causing this event to be sent out in the lobby, however because of the large amount of features in YimMenu it's quite hard to pinpoint what is causing the event to be sent out.
> 
> @mikedrugs, if you could send your settings.json file as well when you've confirmed that your game is also sending out the anti-cheat detection event then we can more easily figure out which feature is causing this.

[settings.json](https://github.com/user-attachments/files/16362139/settings.json)
keep in mind that this happened to me a while ago (1 month or so) but i usually don't change any settings it should be okay, also i found out because one of my friends had my username in their yim database flagged as like i triggered the rockstar anticheat

**Comment by TaylorSwiftMyLove** [comment]
is it safe to play now? and will they ban us?

**Comment by ghost** [comment]
> is it safe to play now?

No

> and will they ban us?

Yes
