### ISSUE TITLE
[Improvement]: Revert outfit editor buttons

### ISSUE THREAD

**Issue by karinaquill** [Yimura/YimMenu#3406]
### UI / Sliders

Hi! 

The sliders are super nice - and generally, while I feel it's a bit big, I'm a big fan of the new UI! 

I'd however suggest the sliders in specific become optional; or allow for inputting direct numbers once more. It's very difficult in stuff like outfit editing to get bang-on the exact number, so I've found myself re-injecting older versions of Yim which is unideal! 

tldr; create an option to toggle sliders & big buttons.

### Reason

Precision!

**Comment by Yimura** [comment]
CTRL + Left Click should allow you to directly modify the slider input fields.

**Comment by xiaoxiao921** [comment]
@Yimura a text in the outfit editor GUI should be here telling this exact tip

**Comment by gir489returns** [comment]
> @Yimura a text in the outfit editor GUI should be here telling this exact tip

That's nonsense, it should be implicit with ImGui. They should also not be entering outfits outside the boundaries either, as the game isn't designed to do that.

**Comment by xiaoxiao921** [comment]
Come on, you can't expect people to know about this shortcut. It's not a GUI standard behavior / well known

**Comment by gir489returns** [comment]
> Come on, you can't expect people to know about this shortcut. It's not a GUI standard behavior / well known

Regardless, they shouldn't be doing it because it's unsupported. Only debugging/devs should be doing it, which is why I changed it in the first place.

**Comment by karinaquill** [comment]
> > @Yimura a text in the outfit editor GUI should be here telling this exact tip
> 
> That's nonsense, it should be implicit with ImGui. They should also not be entering outfits outside the boundaries either, as the game isn't designed to do that.

The issue spoken of wasn't the boundaries, it was that the slider skips stuff within the bounds.

Also! 

The way gta's sliders worked prior, they'd get "stuck" at a certain number, and you'd have to jump 10 or so Id's to continue, so. Still useful to have precise control.

Anyways! Would be cool to have this notated somewhere as stated above, but, thank you!

**Comment by lonelybud** [comment]
> > > @Yimura a text in the outfit editor GUI should be here telling this exact tip
> > 
> > 
> > That's nonsense, it should be implicit with ImGui. They should also not be entering outfits outside the boundaries either, as the game isn't designed to do that.
> 
> The issue spoken of wasn't the boundaries, it was that the slider skips stuff within the bounds.
> 
> Also!
> 
> The way gta's sliders worked prior, they'd get "stuck" at a certain number, and you'd have to jump 10 or so Id's to continue, so. Still useful to have precise control.
> 
> Anyways! Would be cool to have this notated somewhere as stated above, but, thank you!

if the slider is jumping more ids on sliding than I will agree that +/- buttons worked better.

**Comment by lonelybud** [comment]
> Only debugging/devs should be doing it, which is why I changed it in the first place.

I think the general users were using +/- buttons more than manually editing and  there were checks that keep the values under the bounds

**Comment by ghost** [comment]
This is the same request as mine : https://github.com/YimMenu/YimMenu/issues/3400 what I don't understand, why my report  seems completely ignored.

**Comment by lonelybud** [comment]
> This is the same request as mine : https://github.com/YimMenu/YimMenu/issues/3400 what I don't understand, why my report seems completely ignored.

its not ignored. its similar and will be taken care

**Comment by gir489returns** [comment]
> This is the same request as mine : #3400 what I don't understand, why my report seems completely ignored.

Fuck you, expecting us to bend to your every whim, go suck a dick dude. We're not obligated to do anything you ask of us.

**Comment by ghost** [comment]
> > This is the same request as mine : #3400 what I don't understand, why my report seems completely ignored.
> 
> Fuck you, expecting us to bend to your every whim, go suck a dick dude. We're not obligated to do anything you ask of us.

Dude, it was my first request. Not "every whim". Not obligated of course, find a word from my side where I obligated anyone. Insult me don't make you better than me. This is assured.
