### ISSUE TITLE
[Request]: Make it so “Send Fake Ban Message” comes from Rockstar Games instead of the players name

### ISSUE THREAD

**Issue by itisme123-lol** [Yimura/YimMenu#3415]
### Problem

It makes you vulnerable to being booted when you use this on modders who are being pr*cks since they can see who sent the message. 
![IMG_6823](https://github.com/user-attachments/assets/3e1e41a8-9d95-4bf7-b1e6-ec5de55e5b68)
The profile pic should also be a rockstar logo instead of the player

### Solution

Literally changing it

### Reason

Scares the very annoying modders and forces them to chill with the booting

**Comment by gir489returns** [comment]
See #3141
