### ISSUE TITLE
[Bug]: Calling Script Functions with Reference Parameters Causes Exception

### ISSUE THREAD

**Issue by ShinyWasabi** [Yimura/YimMenu#3417]
### Describe the bug

When calling a script function that includes a parameter passed by reference, an EXCEPTION_ACCESS_VIOLATION occurs.

Example:
```c
void func_1460(int iParam0, int iParam1, var uParam2, bool bParam3, bool bParam4, bool bParam5)
```
```cpp
uint64_t transaction_hash = "SERVICE_EARN_DAILY_STASH_HOUSE_COMPLETED"_J;
uint64_t transaction_price = NETSHOPPING::NET_GAMESERVER_GET_PRICE(transaction_hash, "CATEGORY_SERVICE_WITH_THRESHOLD"_J, true);
uint64_t service_index = 0;

scr_functions::fire_service_transaction({ transaction_hash, transaction_price, service_index, true, false, false });
```
In this scenario, service_index (uParam2) must be passed by reference, but the current implementation does not support this, leading to an exception.

### Steps To Reproduce

1. Call a script function with a parameter that should be passed by reference.

### Expected Behavior

The function should execute without causing an EXCEPTION_ACCESS_VIOLATION. The value should be correctly passed to the reference parameter, and any modifications made to the reference parameter within the function should be returned correctly.

### Logs

Log for Lua: [cout.txt](https://github.com/user-attachments/files/16357985/cout.txt)
Log for YimMenu: [cout.log](https://github.com/user-attachments/files/16358208/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Have you tried using `(uint64_t)&service_index` instead?

**Comment by ShinyWasabi** [comment]
Yeah, that fixes the exception but the value isn't returned to the variable.
