### ISSUE TITLE
Being unable to inject

### ISSUE THREAD

**Issue by donovanbarnacle** [Yimura/YimMenu#3421]
### Describe the bug

when i try to inject it says try running the injector as administrator even tho im already running it as a administrator

### Steps To Reproduce

go to yim menu press run as administrator then press on inject

### Expected Behavior

the menu being injected

### Logs

i dont have logs as its my first time trying to launch it after re downloading it

### Screenshots / Video

![image](https://github.com/user-attachments/assets/d18ba755-0aa9-4970-84d3-d41515ad34df)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Can't reproduce, consider opening up an issue on the repository of that injector instead.
