### ISSUE TITLE
[Bug]: "Give Weapon" list is not working correctly

### ISSUE THREAD

**Issue by VXNTXBLXCK** [Yimura/YimMenu#3423]
### Describe the bug

If the Menu Language is set to Russian or Korean, then the "Self > Weapons > Ammu-Nation > Give Weapon" list merged with the "Self >Weapons > Custom Weapons" list. To select a weapon for "Give Weapon" list, you need to open the "Custom Weapons" list. However, the "Give Weapon" list does not respond to clicks

### Steps To Reproduce

1. Inject Menu
2. Set Menu Language to Russian or Korean
3. Try to give yourself a weapon

### Expected Behavior

Select weapon from correct list, as if the menu language was set to English, German, French or any other

### Logs

Sure (but I don't know if I did the right thing)
[cout.txt](https://github.com/user-attachments/files/16366627/cout.txt)

### Store

Epic Games

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
screenshot?

**Comment by VXNTXBLXCK** [comment]
![weaponlist](https://github.com/user-attachments/assets/a5789ffc-c21f-4eaa-85a1-ad70b88703bb)
those marked in red refer to the list of Custom Weapons
those marked in yellow refer to the list of Give Weapons

**Comment by Yimura** [comment]
I'm betting the labels for have the same value in those translations, in code they reference different translation labels though.
https://github.com/YimMenu/YimMenu/blob/086f42f21e7297334f7b0fcba6306918127eed74/src/views/self/view_weapons.cpp#L139
https://github.com/YimMenu/YimMenu/blob/086f42f21e7297334f7b0fcba6306918127eed74/src/views/self/view_weapons.cpp#L236

Taking a look at the translations we can see that for both the labels "WEAPON" and "GUI_TAB_WEAPONS" the same value of "Оружие" is used in the Russian translation.

To fix this we'll have to append a label to those translations or push and pop an ID in the code.

**Comment by lonelybud** [comment]
adding `##` to create unique ids should work

**Comment by Yimura** [comment]
> adding `##` to create unique ids should work

Yeah but it isn't a good long term solution for all the other languages, neither is it implied from the translation label that you need to put an ID behind it. Best would be to make use of `ImGui::PushId` and `ImGui::PopId`.
