### ISSUE TITLE
[Improvement]: Nitro Boost from Arena Tuning

### ISSUE THREAD

**Issue by VXNTXBLXCK** [Yimura/YimMenu#3425]
### Which feature

While playing on a third-party server, I discovered an interesting feature: unlike Rocket Boost (Scramjet, Vigilante, etc.), Nitro Boost does not have a speed limit and allows you to gain speed constantly, until the nitro runs out. 

I also recently met a modder (in GTA Online) who could activate nitro on any non-arena vehicle: Banshee, Infernus, Elegy, etc. However, it later turned out that this does not apply to electric cars (for obvious reasons).

Based on these discoveries, I have the following suggestions:
1. Expand the work of the already existing Boost Behavior function on Nitro Boost
2. Add the ability to activate nitro on any suitable vehicle: cars, motorcycles, ATVs...

Note: Nitro is activated by the X key. The hydraulic suspension of lowriders is activated by the same key. I have no idea how to resolve this conflict

### Reason

I use a rather specific vehicle: Vapid Imperator - a muscle car that can do wheelie and is equipped with nitro. Mix this two together and you get the killer cocktail called Nitrowheelie: blazing acceleration and a monstrous top speed. And all this until the nitro runs out. 
But what if...?

**Comment by ewenjam** [comment]
[This LUA script](https://github.com/YimMenu-Lua/TokyoDrift) by xesdoog includes this feature in the meantime

**Comment by xiaoxiao921** [comment]
There is no meantime. The menu features is already bloated as it this. If you want extra features just take the habit of checking the yim menu Lua org.
