### ISSUE TITLE
[Bug]: Vehicles not being cleaned up during mission restarts

### ISSUE THREAD

**Issue by ewenjam** [Yimura/YimMenu#3427]
### Describe the bug

When a mission or heist is restarted (due to a player dying or an objective failing for example), your vehicle does not get removed by the game.

In the past it sometimes showed a notification saying "xyz tried to delete your vehicle", but nowadays it doesnt even show that.

**For example:** the driller failed during the Fleeca Bank job and we restarted from a checkpoint. The Armored Kuruma I was sitting in was not cleaned up by the game, and now its just sitting there as an extra unused vehicle.

![car bug](https://github.com/user-attachments/assets/ba6cc2e4-7c72-41dd-8ec8-ef050ed81b45)

### Steps To Reproduce

1. Start any mission/heist
2. Fail mid-way and restart from checkpoint
3. Your vehicle, regardless of whether you're sitting in or not, get carried over into the restart

### Expected Behavior

The game should delete them.

### Logs

[cout.log](https://github.com/user-attachments/files/16374439/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I have observed this with and without my LUAs being active.

I have all my protection settings disabled (I do not play in public lobbies anyway). I have tried resetting and then disabling them again as well.

I have tried resetting my entire Yim settings as well.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
who was the host?

**Comment by ewenjam** [comment]
> who was the host?

The other player

**Comment by lonelybud** [comment]
> The other player

So it is most likely they must be script host something and if they send delete vehicle event then it should be accepted by other players. Seems to me like a bug

**Comment by gir489returns** [comment]
I've had this happen too. While on the Prison Break heist at the end, I recieved the following:

`[02:10:39.8715453][WARN/reaction.cpp:57] Received DELETE_VEHICLE from RichardTwin (44238823)`

We should probably check if we're on a mission and allow this, as it's a legit scenario.

**Comment by gir489returns** [comment]
@ewenjam Would you mind testing the build from PR #3434 and seeing if the issue is resolved?

**Comment by ewenjam** [comment]
> @ewenjam Would you mind testing the build from PR #3434 and seeing if the issue is resolved?

Yep, Ill give it a go today and get back to you

**Comment by ewenjam** [comment]
I tested the PR build on The Fleeca Heist again (with the same fail state and checkpoint, friend as the host), did not notice any duped vehicles this time. I dont know if my friend being the host might affect the results, wasn't having much luck finding randoms to test with.
