### ISSUE TITLE
YimMenu is detecting other players as triggering the Rockstar anti-cheat

### ISSUE THREAD

**Issue by sandubba** [Yimura/YimMenu#3433]
### Describe the bug

yim menu is (hopefully) giving false positives on rockstar anti cheat detection

### Steps To Reproduce

join a freemode session

### Expected Behavior

*not* doing that

### Logs

[settings.json](https://github.com/user-attachments/files/16382116/settings.json)
[cout.log](https://github.com/user-attachments/files/16382175/cout.log)

### Screenshots / Video

https://github.com/user-attachments/assets/ca7647ca-8a10-40b7-abc4-3692bee470f2

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by snowleopardd** [comment]
Yup this literally happened to me moments ago

**Comment by snowleopardd** [comment]
![Screenshot 2024-07-25 150507](https://github.com/user-attachments/assets/a85eefc0-2b13-40ca-b321-ee5c1f67fa8c)
![Screenshot 2024-07-25 150337](https://github.com/user-attachments/assets/9b17585b-e0db-4b03-989f-e95b0dd9e5ba)

**Comment by sandubba** [comment]
sounds like a ban wave is coming, it's been a long run

**Comment by Yimura** [comment]
This might be related to #3422.

**Comment by snowleopardd** [comment]
> This might be related to #3422.

This only happened to me after i joined story mode and then injected and joined online, but when i inject on the start this doesn't seem to happen

**Comment by Yimura** [comment]
I'm going to check it out right now in online if I can reproduce it reliably.

**Comment by sandubba** [comment]
> > This might be related to #3422.
> 
> This only happened to me after i joined story mode and then injected and joined online, but when i inject on the start this doesn't seem to happen

i injected mine on the main menu, loaded single player, played an entire heist prep then it began happening
also, people on ukc seem to be having the same issue
![image](https://github.com/user-attachments/assets/fac037a3-a90e-4778-a9c8-6170e1e90714)

**Comment by snowleopardd** [comment]
> > > This might be related to #3422.
> > 
> > 
> > This only happened to me after i joined story mode and then injected and joined online, but when i inject on the start this doesn't seem to happen
> 
> i injected mine on the main menu, loaded single player, played an entire heist prep then it began happening also, people on ukc seem to be having the same issue ![image](https://private-user-images.githubusercontent.com/107658836/352253242-fac037a3-a90e-4778-a9c8-6170e1e90714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzM5NDgsIm5iZiI6MTcyMTkzMzY0OCwicGF0aCI6Ii8xMDc2NTg4MzYvMzUyMjUzMjQyLWZhYzAzN2EzLWE5MGUtNDc3OC1hOWM4LTYxNzBlMWU5MDcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxODU0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTI1ZWQ0MGRlYzhhODBmYzJkODY0ZDU4MTRmMjE0YjQyMThlNTRmZmMwMTc0ZDI1M2E5NWFkZmY0MWRhNzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B6e8Z66Xtzp7tiZzpIdOCXK-H4U8klGtZt5e_zwgw90)

If you inject on the start and load directly into online it doesn't happen (atleast in my case)

**Comment by maybegreat48** [comment]
If you are able to reproduce this, can you try kicking out the people who are *not* sending this event to see if they're the real modders?

Also, if you could, can you try [using a build](https://github.com/YimMenu/YimMenu/actions/runs/10078140255/artifacts/1735333959) before #3422 was merged?

**Comment by gir489returns** [comment]
Bruh what are you playing on, a fucking N64? Jesus christ, get a bigger screeen.

**Comment by tnsgaming** [comment]
If you go to china server there are more moders I choose different server and only one moder detects ![image](https://github.com/user-attachments/assets/9c3411ab-a977-4ab3-bf1f-a1c35fac3e17)

**Comment by lonelybud** [comment]
i can confirm

**Comment by lonelybud** [comment]
> If you are able to reproduce this, can you try kicking out the people who are _not_ sending this event to see if they're the real modders?

i can confirm happening in friend lobby as well. They are not modders

**Comment by noorameer12** [comment]
Any updates? Is this bug from the game and we do not have to worry? Or Yimmenu got detected?

**Comment by Civilux** [comment]
> Any updates? Is this bug from the game and we do not have to worry? Or Yimmenu got detected?

rockstar was having server issues

**Comment by ghost** [comment]
We are waiting for a new "Ban data collection thread" in a month

**Comment by gir489returns** [comment]
> We are waiting for a new "Ban data collection thread" in a month

I already got my LTC wallet ready to go for another Russian grey-market key for $6. 🤑🤑🤑🤑🤑🤑🤑🤑🤑

**Comment by nastimch** [comment]
my account suspond from online game until 23 August and reset all achivment
is there someone get same ?

**Comment by nastimch** [comment]
think from yumenu bcz i did sell bunker business !! or someone report me my be !

**Comment by gir489returns** [comment]
![image](https://github.com/user-attachments/assets/f5a558e5-3bcb-451e-b62b-d0ea01193985)

I'm still not banned. 💪🏻

**Comment by Rxann** [comment]
> I'm still not banned. 💪🏻

Same, no bans for me yet. I don't use any recovery features though.

**Comment by Yimura** [comment]
I don't understand why we're talking about game bans here because this specific bug has nothing to do with YimMenu users getting banned. It's just Rockstar fucking something up with their Telemetry server which then caused all these players to send out an event saying that they can't connect to the Telemetry server.

**Comment by snowleopardd** [comment]
Yup this should be closed to prevent further confusion
