### ISSUE TITLE
[Request]: Can add a bribe authorities Feature?

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3435]
Add a bribe authorities，Same as in the interaction menu-VIP/CEO abilities-bribe authorities
Can avoid being wanted at any time，bribe authorities

**Comment by gir489returns** [comment]
bribe the authorities

**Comment by Inkmaveil** [comment]
> bribe the authorities

Is this function possible?

**Comment by ghost** [comment]
> bribe the authorities

Can this feature be add?
