### ISSUE TITLE
[Bug]: Fix buttons not being recognised by WndProc callback but are supported through ImGui::Hotkey

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#3436]
### Describe the bug

The ImGui::Hotkey has support for the mouse buttons, however our WndProc hook does not pick up on these.

People will usually make YimMenu unusable trying to set one of the buttons on their mouse to open and close the menu overlay.

### Steps To Reproduce

1. Go to hotkey tab under settings
2. Change hotkey to one of the mouse buttons
3. Observe that the menu overlay cannot be closed after setting this button and on next inject the menu cannot be opened.

### Expected Behavior

Either we remove support for these buttons from the ImGui::Hotkey or we find a proper way of capture and sending them through the WndProc callback.

### Logs

None.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

See #3116, #3420; there are plenty of other examples of users making it so they can't open and close the menu anymore.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This bug makes no sense, because if ImGui_ImplWin32_WndProcHandler wasn't receiving mouse inputs, the menu itself would not be working (you wouldn't be able to click buttons).

**Comment by xiaoxiao921** [comment]
It doesn't work because you need to listen to the MSG from the wndproc for mouse buttons. And our hotkey system doesn't do that. It only listen to the wm_key event

**Comment by kraken307** [comment]
anyone know how to fix this bug?

**Comment by lonelybud** [comment]
> Either we remove support for these buttons from the ImGui::Hotkey

we should remove support for mouse. But some people use the new type of mouse with lot of buttons and they might ask for the support

**Comment by xiaoxiao921** [comment]
Why should we remove support? It's quite an easy fix like I said.

**Comment by lonelybud** [comment]
> Why should we remove support? It's quite an easy fix like I said.

yeah editing the wndproc function. got it

**Comment by gir489returns** [comment]
> > Either we remove support for these buttons from the ImGui::Hotkey
> 
> we should remove support for mouse. But some people use the new type of mouse with lot of buttons and they might ask for the support

Microsoft does not support anything except the 5 mouse buttons (Left, Right, Center, Back and Forward). So their 50 button WoW mouse won't work anyway. What they usually allow through the software is key rebinding or macroing. Anyway, this isn't a square peg round hole situation anyway.

**Comment by lonelybud** [comment]
https://github.com/YimMenu/YimMenu/discussions/3512 one more, The simplest thing we can do right now is to show the menu by default after inject
