### ISSUE TITLE
а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать[Bug]: 

### ISSUE THREAD

**Issue by nazar737** [Yimura/YimMenu#3438]
### Describe the bug

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Steps To Reproduce

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Expected Behavior

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Logs

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Screenshots / Video

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Additional context

а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
Nobody speaks suka blyat language

**Comment by gir489returns** [comment]
а што делать єсли мой друг может кикать с етим читом а я нет и как можна сделать штоб он перестал мення кикать
