### ISSUE TITLE
[Bug]: Aimbot aims at people inside your car

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3442]
### Problem

Aimbot locks on player in your vehicle and starts to repidly spin

### Solution

Create a check if player is sitting in same vehicle. Otherwhise create a threshhold for the aimbot that it wont target people less than 5m to you

### Reason

idk just realized and was annoyed

**Comment by gir489returns** [comment]
There should never be a scenario where you try to aim at players/peds inside your car, this is a bug not a request. I've fixed it with #3443. Can you confirm with the build produced in the PR that it is indeed fixed?

**Comment by ghost** [comment]
I can confirm it does NOT target players inside my own vehicle anymore. perfectly done

**Comment by gir489returns** [comment]
The ticket has to stay open until the changes are merged. Thank you for confirming.

**Comment by ghost** [comment]
Oh im sorry i forgot this has to stay open. Im glad to help. I have found some more bugs but i felt like they were too minor to open a ticket for. Ill collect them and maybe do a group ticket when i feel like it. Ty for maintaining this project. <3
