### ISSUE TITLE
[Request]: menu size is very big for 1920-1080p

### ISSUE THREAD

**Issue by Beginner555989** [Yimura/YimMenu#3451]
### Problem

![Screenshot (105)](https://github.com/user-attachments/assets/dc8ee177-14e3-4eac-b8d6-3ae9225b28a0)

### Solution

can you plz make the UI scale 0.50  bcz we as 1080p players have problem with the menu size 

### Reason

![Screenshot (105)](https://github.com/user-attachments/assets/4f4ec6b5-ba95-478d-9163-f58769705283)

**Comment by lonelybud** [comment]
you can ctrl click inside and manually enter the value.

**Comment by Beginner555989** [comment]
> you can ctrl click inside and manually enter the value.

thank bro hahaha that easy was it !!!!!
