### ISSUE TITLE
The function of unloading the menu

### ISSUE THREAD

**Issue by Anonymous-76-r** [Yimura/YimMenu#3452]
### Which feature

Hello! In the version before there was a “Unload” function at the top of the menu next to the nickname that allowed you to disable the menu right in the game, now after the update I can't find this button, hint, maybe you moved it?

### Reason

This function has disappeared from its usual place

**Comment by xiaoxiao921** [comment]
Removed cause it's unsafe to unload while being in multiplayer.

**Comment by Elfish-beaker** [comment]
> Removed cause it's unsafe to unload while being in multiplayer.
How is it unsafe to unload in multiplayer? What makes it unsafe?
