### ISSUE TITLE
[Request]: Gravity gun, Airstrike gun, thermal vision and night vision.

### ISSUE THREAD

**Issue by juhannnnnn** [Yimura/YimMenu#3457]
### Solution

I would highly appreciate if gravity gun and airstrike gun could be added. These could be used with any weapons. Night vision and thermal vision would be cool too.

### Reason

To have more features and fun!

**Comment by ghost** [comment]
we already have a gravity gun

![image](https://github.com/user-attachments/assets/ed738ccb-1296-427a-b10a-4045ec1fe76d)

EDIT: instead of an airstrike you can use a special ammo it does almost the same thing

![image](https://github.com/user-attachments/assets/d7be249e-5d57-424d-b086-d9d567e3e5bb)

**Comment by snowleopardd** [comment]
> we already have a gravity gun
> 
> ![image](https://private-user-images.githubusercontent.com/168850586/352801028-ed738ccb-1296-427a-b10a-4045ec1fe76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODY4NTQsIm5iZiI6MTcyMjE4NjU1NCwicGF0aCI6Ii8xNjg4NTA1ODYvMzUyODAxMDI4LWVkNzM4Y2NiLTEyOTYtNDI3YS1iMTBhLTQwNDVlYzFmZTc2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNzA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDVjYTRjMGI1YmIyMmI5NWNlNjdhOGY3Mjg5OWEzZDE3M2Y3YTdkMDI5MjVjNTIzZDE0ZWNiMjhjMjIxNDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EEjZn6d_eSpCp1Ns6Zih9gsQVnAxU2fDXLwxvTDhkTs)
> 
> EDIT: instead of an airstrike you can use a special ammo it does almost the same thing
> 
> ![image](https://private-user-images.githubusercontent.com/168850586/352801216-d7be249e-5d57-424d-b086-d9d567e3e5bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODY4NTQsIm5iZiI6MTcyMjE4NjU1NCwicGF0aCI6Ii8xNjg4NTA1ODYvMzUyODAxMjE2LWQ3YmUyNDllLTVkNTctNDI0ZC1iMDg2LWQ5ZDU2N2UzZTViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNzA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjE1YThlOTU3YWNkNTY1OThmNzc4YTZiMWZlYzU1NWFhZDg1ZjZhOGI4MmI2Yzk5ZDI0ZGJkNTE2MzI2YjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jxM_Riq501NZPmH3EIVm7XMHeUkY-I6TDBrZCrUivAA)

i think he's referring to the merryweather airstrike or some shit

**Comment by gir489returns** [comment]
> we already have a gravity gun

When the breaking bad man says we.

![image](https://github.com/user-attachments/assets/b72c0db0-cdb0-474d-a4a6-8edede3acff6)

**Comment by xiaoxiao921** [comment]
Can be done through a lua script
