### ISSUE TITLE
[Request]: Ceo Helicopter pickup

### ISSUE THREAD

**Issue by StyleCanadian** [Yimura/YimMenu#3458]
### Solution

It would be cool if you add ceo helicopterpickup to mod menu.
also is there anyway to change back character model to default after "change player mode" except rejoining the session

**Comment by ghost** [comment]
Open your eyes

![image](https://github.com/user-attachments/assets/37e8ecac-fdde-424a-96e7-e1d33a4d5d95)

**Comment by StyleCanadian** [comment]
![photo_2024-07-28_18-42-21](https://github.com/user-attachments/assets/dce6a928-c9c3-4d12-811d-28fda0264b03)
As I mentioned, I meant "CEO helicopter pickup," not Merryweather helicopter pickup.

**Comment by xesdoog** [comment]
[Billionaire Services](https://github.com/xesdoog/Billionaire-Script)

**Comment by gir489returns** [comment]
I figured we already had a Lua script for this somewhere around the ether. Nice work, @xesdoog.
