### ISSUE TITLE
[Improvement]: Bounty protection wont protect from peds in game

### ISSUE THREAD

**Issue by rr1231234** [Yimura/YimMenu#3460]
### Which feature

Bounty protection 

### Reason

Steal a car from peds, they will put a bounty on your head and current protection wont prevent this. Still working well against players however. Or better yet, need a feature to clear up the bounty just in case.

**Comment by gir489returns** [comment]
Oh yeah, I've run into this a couple of times. Stealing cars and stuff, you'll get a text from someone saying "THAT WAS MY RIDE" or something, then you get a bounty. Lester Crester really gets around, eh? Do you by chance have a snippit/screenshot of exactly the exact text message? I need it to trace through the freemode script of where it comes from.

**Comment by FIying-Scotsman** [comment]
> Oh yeah, I've run into this a couple of times. Stealing cars and stuff, you'll get a text from someone saying "THAT WAS MY RIDE" or something, then you get a bounty. Lester Crester really gets around, eh? Do you by chance have a snippit/screenshot of the exact text message? I need it to trace through the freemode script of where it comes from.

From the GTA Wiki:-
![image](https://github.com/user-attachments/assets/4b5ee2e3-8dd3-4c9b-b72f-3dcf3057fcb3)

**Comment by gir489returns** [comment]
@rr1231234 Can you please test the build from PR #3461 and see if this gets stopped now? Make sure you have bounty script protections on before you steal a car.
