### ISSUE TITLE
[Bug]: Train Speed Changer Doesn't Work

### ISSUE THREAD

**Issue by SubjectZeros** [Yimura/YimMenu#3468]
### Describe the bug

So in the Train section, you can't set the train speed. It doesn't work. (Yes drive train is enabled)

### Steps To Reproduce

1. Enter train
2. Check Drive
3. Set Train Speed

### Expected Behavior

The Train speed should change.

### Logs

[cout.txt](https://github.com/user-attachments/files/16413964/cout.txt)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
The instructions aren't very clear, and it's not a piece of the cheat we really care about, but the controls should be implicit. You hold W to go forward, S to go backwards. But it's a train dude, it takes a while to get up to speed. Maybe pop a ritalin or Adderall or watch a family guy/subway surfers/minecraft parkour video for a second and wait for it to get up to speed.

**Comment by Yimura** [comment]
This should probably be removed, it was once made but never done properly. Nobody cares to maintain (nor does the original creator care).

At most this should be a Lua...

**Comment by SubjectZeros** [comment]
> The instructions aren't very clear, and it's not a piece of the cheat we really care about, but the controls should be implicit. You hold W to go forward, S to go backwards. But it's a train dude, it takes a while to get up to speed. Maybe pop a ritalin or Adderall or watch a [family guy/subway surfers/minecraft parkour zoomer video](https://www.youtube.com/shorts/1YHvkBP_VFw?feature=share) for a second and wait for it to get up to speed.

The controls don't work. I literally held down w and s for 30 seconds and my speed hasn't changed. I do agree with Yimura that this should be removed.

**Comment by gir489returns** [comment]
> The controls don't work. I literally held down w and s for 30 seconds and my speed hasn't changed. I do agree with Yimura that this should be removed.

>NOOOOO I'M NOT A HECKIN ZOOMERARINO! I DID IT RIGHT BUT IT DOESN'T WORK! MY EGO WON'T LET ME ADMIT I'M WRONG, YOU'RE WRONG, YOU NEED TO FIX IT! Why? Um, Because.... BECAUSE YOU JUST DO OK?!?!?!?! I AGREE WE SHOULD REMOVE IT BECAUSE MY 40 IQ BRAIN CAN'T FIGURE OUT CHECKBOXES AND SLIDERS!!!!! I MEAN, IT'S BROKEN!!!!!!!!!!!

[Skill issue.](https://youtu.be/o5LKhLfxDCc)
