### ISSUE TITLE
[Request]: Set time of the Day/Override time with non static clock.

### ISSUE THREAD

**Issue by Muharys92** [Yimura/YimMenu#3469]
### Problem

The menu does override time but the clock freezes. 

### Solution

If there was a way that we can just rewind / forward time locally (like single player) and after that the clock continues to moves forward in Gta time (30X faster). Also can be implemented the option to slow down time or accelerate time.

### Reason

Helps in role playing. for example start day and go to work at 6am or 9am and then go back to apartment at 5pm etc. 

### Additional context

Got this idea as it was the feature of Wasabi Unlocker menu by @ShinyWasabi. If he can add the same code into the menu or added Lua Script. The time dilation is the idea Model railroad designer use all the time.

**Comment by gir489returns** [comment]
I don't understand, you already said this is available from Shiny's Lua script, why does it need to be in the base mod? Nonsense request, closed.

**Comment by Muharys92** [comment]
> I don't understand, you already said this is available from Shiny's Lua script, why does it need to be in the base mod? Nonsense request, closed.

@gir489returns 
No, I didn't say its available as a Lua script. I said It was a feature of Wasabi Unlocker menu(a separate mod menu developed by shiny wasabi, no longer working) just for reference.
