### ISSUE TITLE
[Bug]: After clicking the RID join button, the RID input box changes to 0

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#3474]
### Describe the bug

After clicking the RID join button, the RID input box changes to 0.
After entering the RID, pressing Enter will cause the game to crash

### Steps To Reproduce

.

### Expected Behavior

.

### Logs

.

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
This is because I made some changes in #3464 without properly testing the RID joining option again. I shouldn't have assume that because the join by username function doesn't require a queued fiber that the RID joining function doesn't.

I'll fix it this evening when I get to it.

**Comment by iwanttodo1t** [comment]
Still not working
