### ISSUE TITLE
[Improvement]: Make the IPL maps for everyone to see

### ISSUE THREAD

**Issue by infinity-stack** [Yimura/YimMenu#3476]
### Which feature

I would like the IPL maps in the teleport section to be everyone to be seen but fix the ocean

### Reason

It would be fun to see cayo perico or north yankton

**Comment by maybegreat48** [comment]
That's not possible

**Comment by infinity-stack** [comment]
why

**Comment by infinity-stack** [comment]
people are able to flip the map in the sky but its not possible to add cayo?

**Comment by Yimura** [comment]
Because the flipped map are low poly object models that can just be spawned by any mod menu, that's why they're visible and networked.

Cayo and North Yankton are actual full parts of the map, these cannot just be spawned and network by your mod menu (so they're visible to all other players).
