### ISSUE TITLE
[Improvement]: Join player session button is inactive in players base when player is not online

### ISSUE THREAD

**Issue by opt8** [Yimura/YimMenu#3488]
### Which feature

Join player session button in player base

### Reason

I noticed that the join player session button is not active if the player is not displayed online. I consider this an unnecessary limitation, because over time the list of players grows to an incredible size and it takes a very long time to wait for the entire list to be updated

**Comment by CypherMorgan** [comment]
Afaik it takes just 1-2 seconds for me to load the player states, what do you actually mean by 'takes very long time'? And if you really wanna join a Specific player, you can just Track the player and turn on 'Notify When Online' in the Player Database tab.

**Comment by opt8** [comment]
> Afaik it takes just 1-2 seconds for me to load the player states, what do you actually mean by 'takes very long time'? And if you really wanna join a Specific player, you can just Track the player and turn on 'Notify When Online' in the Player Database tab.

i have 3k players in database and it takes i think about a minute to update them all. i think doing this (refreshing them all) for every added player is not practical. we need at least a button to refresh info only about selected player

**Comment by snowleopardd** [comment]
btw, sometimes ppl can appear offline but are still joinable, i think this limitation should be removed.

**Comment by opt8** [comment]
and it is advisable to do something with the "delete all players" (from our database) button - it is very easy to click by mistake and lose them all, this has already happened to me once. we need some kind of confirmation for this action or hide the button under some kind of spoiler

**Comment by xiaoxiao921** [comment]
A small confirmation window should definitly be added

**Comment by gir489returns** [comment]
This issue is complaining about a non-issue. You're saying that the player is offline, and the button to join them is greyed out. What exactly is the issue here? If they are not appearing online, the SCAPI query to join their session will fail anyway, why even allow this?

**Comment by snowleopardd** [comment]
> This issue is complaining about a non-issue. You're saying that the player is offline, and the button to join them is greyed out. What exactly is the issue here? If they are not appearing online, the SCAPI query to join their session will fail anyway, why even allow this?

https://github.com/YimMenu/YimMenu/issues/3488#issuecomment-2263544221

**Comment by snowleopardd** [comment]
Kinda wild that this issue was classified as "invalid" but never closed, i'll make another when i have time.
https://github.com/YimMenu/YimMenu/pull/3515#discussion_r1703363453
