### ISSUE TITLE
[Bug]: Gravity Gun breaking

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3490]
### Describe the bug

I have no idea why and how but sometimes the gravity gun stops working. It doesnt tell stuff like "target is not an entity" etc up top it just doesnt do aynthing anymore. sometimes removing custom gun and then switching again makes it work again but now its just completly broken

### Steps To Reproduce

1. Activate gravity gun
2. use it
3. Broken

### Expected Behavior

1. Use it
2. be happy :3

### Logs

No log from this incident

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by juhannnnnn** [comment]
Same bug i am facing

**Comment by Mr-X-GTA** [comment]
It works for vehicles and non-player peds, but `take_control_of` can block the loop for a few seconds. Sometimes `m_request_control` even triggers exceptions and may crash the game
