### ISSUE TITLE
i cant open menu anymore

### ISSUE THREAD

**Issue by lovingstarss** [Yimura/YimMenu#3492]
### Describe the bug

 i put my open key to right shift instead of insert and now it dosent open

### Steps To Reproduce

s

### Expected Behavior

s

### Logs

s

### Screenshots / Video

s

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment]
Go to "C:\Users\<username>\AppData\Roaming\YimMenu" and open settings.json and set "menu_toggle": 45. This will revert it back to Insert Key.

**Comment by gir489returns** [comment]
s
