### ISSUE TITLE
[Build]: Crashing when injecting

### ISSUE THREAD

**Issue by wibba918** [Yimura/YimMenu#3493]
### Describe the build issues

I found a tutorial on youtube on how to download it and it lead me to the yimmenu website and i downloaded the dll file and they recommended to use xenos injector but it still crashes. Other posts about the same issue as mine says that i have to look at the pull request and download the binary zip and inject the dll in it but it still crashes. Hope this reaches out to devs. Kuddos wib

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by CypherMorgan** [comment]
What's your Xenos settings? Make sure you're using it on default profile. 
> i have to look at the pull request 

You have to download the DLL from the Releases, Not the Pull Request.

**Comment by lonelybud** [comment]
https://github.com/pierrelasse/YimStuff/blob/master/docs/YimMenuInstallation.md

**Comment by wibba918** [comment]
It still crashes

**Comment by gir489returns** [comment]
Are you compiling in Debug or Release mode?

**Comment by wibba918** [comment]
release
mode

**Comment by gir489returns** [comment]
> release mode

Do you have an output from Ninja we can see?

**Comment by wibba918** [comment]
ninja?

**Comment by gir489returns** [comment]
> ninja?

Ninja is the name of the build suite we use with CMake, you should have that if you imported the project properly into VS2022.

**Comment by wibba918** [comment]
do i need to do something in VS?
(sorry im just new to using github and yim)

**Comment by gir489returns** [comment]
> do i need to do something in VS? (sorry im just new to using github and yim)

Did you follow this? https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development

**Comment by xiaoxiao921** [comment]
Delete your `%appdata%/YimMenu` folder
Inject the YimMenu.dll from https://github.com/YimMenu/YimMenu/releases/download/nightly/YimMenu.dll
using xenos default settings
if it still crashes upload your `%appdata%/YimMenu/cout.log` file here

**Comment by wibba918** [comment]
> > do i need to do something in VS? (sorry im just new to using github and yim)
> 
> Did you follow this? https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development

i haven't

**Comment by wibba918** [comment]
> Delete your `%appdata%/YimMenu` folder Inject the YimMenu.dll from https://github.com/YimMenu/YimMenu/releases/download/nightly/YimMenu.dll using xenos default settings if it still crashes upload your `%appdata%/YimMenu/cout.log` file here

[cout.log](https://github.com/user-attachments/files/16459079/cout.log)
here it is

**Comment by CypherMorgan** [comment]
You're co-loading the menu, aren't you?
The logs are same as #3394

**Comment by xiaoxiao921** [comment]
Yeah, bunch of asi getting loaded
