### ISSUE TITLE
[Request]: Forge LSC MODEL for Modded Cars Saving.

### ISSUE THREAD

**Issue by ENC4YP7ED** [Yimura/YimMenu#3495]
### Problem

Could be risky if doing it but I don't really know how it is nower days

### Solution

but could be enabled in settings like : Risky Features or something.

### Reason

Modded Cars are nice to have and looks good even without Menu so I want to save them in my Garage or Put Insurence on them so they don't dissapear

### Additional context

I love the Work you put in the Menu and and like it really much and I would highly aprreciate it when you could add something like this.

**Comment by gir489returns** [comment]
We already have this.
