### ISSUE TITLE
[Bug]: Teleport to Objective teleports to random player

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3505]
### Describe the bug

When there is no Objective using the hotkey or Button will tp you to a player. Sometimes a random one sometimes the same

### Steps To Reproduce

1. Tp to Objective without having one

### Expected Behavior

Dont tp and give error that there is no objective as it did a a few versions back.

### Logs

No log

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This was probably introduced with #3473. @xesdoog do you have insight on why this might occur? It's basically using your Lua script.

**Comment by ghost** [comment]
It might be connected to the player closest to me or if i hovered over them on the map. Im not sure i can test this further if wanted. I cant code and therefore cant help with that

**Comment by gir489returns** [comment]
> This was probably introduced with #3473. @xesdoog do you have insight on why this might occur? It's basically using your Lua script.

I have a feeling it has to do with this:

`auto blip_icons = {0, 1, 2, 143, 144, 145, 146, 280, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 535, 536, 537, 538, 539, 540, 541, 542};`

They are the Icon IDs, but I just copy pasted it from xes' script, and didn't double check it. I think 1 is circle, and the player's also use circles.

**Comment by xesdoog** [comment]
> > This was probably introduced with #3473. @xesdoog do you have insight on why this might occur? It's basically using your Lua script.
> 
> I have a feeling it has to do with this:
> 
> `auto blip_icons = {0, 1, 2, 143, 144, 145, 146, 280, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 535, 536, 537, 538, 539, 540, 541, 542};`
> 
> They are the Icon IDs, but I just copy pasted it from xes' script, and didn't double check it. I think 1 is circle, and the player's also use circles.

Yes I agree. I haven't checked the blips either I just gathered whatever I thought was valid as an objective blip and didn't double check useless or wrong blips.
Looking at them now I think 1, 280, 502 to 511, and 542 are useless and should be removed.

**Comment by gir489returns** [comment]
> Yes I agree. I haven't checked the blips either I just gathered whatever I thought was valid as an objective blip and didn't double check useless or wrong blips. Looking at them now I think 1, 280, 502 to 511, and 542 are useless and should be removed.

https://docs.fivem.net/docs/game-references/blips/

I'm using this as a reference and currently rebuilding our blip enum based off it.

**Comment by gir489returns** [comment]
@Kibasmoothie Would you mind testing the build from PR #3509 and seeing if your issue is resolved?

**Comment by ghost** [comment]
@gir489returns i will test it as soon as I have time when waking up. It’s the middle of the night rn. I’ll be happy to help when I wake up.

**Comment by ghost** [comment]
@gir489returns I can CONFIRM that using #3509 i no longer tp to random players. It appears to fix the issue. No other issues connected to this bug. Ready to merge after checks
