### ISSUE TITLE
[Build]: Can't build YimMenu keep getting a VS error

### ISSUE THREAD

**Issue by ProdByRyze** [Yimura/YimMenu#3517]
### Describe the build issues

When I try to compile I instantly get this error (screenshot)

### Screenshots and/or Logs

![grafik](https://github.com/user-attachments/assets/bea2782e-f52b-49ce-991a-cd7f74c10296)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by Deadlineem** [comment]
Read the setup guide and follow the instructions.  I use the command when i install Visual Studio

https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development

`winget install Microsoft.VisualStudio.2022.Community --silent --override "--wait --quiet --add ProductLang En-us --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended"`
