### ISSUE TITLE
[Improvement]: Whilst saving a persistent vehicle into a JSON file, not changing any aspects of vehicle.

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#3520]
### Which feature

I'd like the Vehicle->Spawn Vehicle->Persistent->Save Vehicle, to not update the car's direction and such.

### Reason

There has been many times where I want to save a vehicle through this function and it changes its direction and whenever I'm close to a wall it's just chaos. I don't know if it was intentional or some missed settings or if it's a bug.

### Additional context

Using latest commit (013b463), with the Epic Games version of the game; but this has been present since the introduction of said function.

Here's a video of what happens:
https://github.com/user-attachments/assets/6fb591c6-9fbe-46af-80ac-57374f7856ce

**Comment by ghost** [comment]
I guess thats cause changing it spawn it and the spawn values arent changed from a default. Meaning it alligns to the vectors of the world and therefore points to north? or whatever axis it is. Shouldnt be that hard to fix by someone. IF my guess is correct and thats the reason for it

**Comment by gir489returns** [comment]
This is the stupidest thing ever, cope with it.

**Comment by gamerboy1992** [comment]
> This is the stupidest thing ever, cope with it.

I did not mean to ridicule anyone's work, I was just  bringing the attention of this very small detail since I was following what you had said to me a while ago.. I apologise for the inconvenience.
