### ISSUE TITLE
[Bug]: Random errors whilst injecting YimMenu but still injects it.

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#3522]
### Describe the bug

Every now and then when I inject the menu, I get random errors which don't stop the menu from injecting but I am not sure if they are of interest.

### Steps To Reproduce

1. Load GTA 5
2. Inject YimMenu on online or story mode

### Expected Behavior

I guess a clear log?

### Logs

[cout.log](https://github.com/user-attachments/files/16495746/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

This has happened to me since early 2023. I don't know how to reproduce it consistently. What's strange is that I just unload the menu and load it back up when those "errors" happen and sometimes I get no errors whilst loading it again. Other times, I have to unload and load up to 4 times to not show any error.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Unless you are experiencing actual issues while playing we are not really interested
