### ISSUE TITLE
[Bug]: Ranks of the 17th player doesn't appear correctly when there is 17 players in a lobby

### ISSUE THREAD

**Issue by gamerboy1992** [Yimura/YimMenu#3523]
### Describe the bug

When you press Z on keyboard or D-pad Down until you see the second list of the players in the lobby, it briefly appears the correct rank of the player then it changes to my players current rank. This does not seem to happen when there is 18 players tho.

### Steps To Reproduce

1. Have a lobby with 17 players
2. Press button to expand radar and show players in lobby
3. Go to the second list where there is only 1 player

### Expected Behavior

I expect the correct rank to show up next to the player name.

### Logs

[cout.log](https://github.com/user-attachments/files/16498518/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

It's very small detail, could be related to gta 5 itself and not the menu but I am not sure. In the pause menu, inspecting each player shows the correct rank.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Isn't this just the game messing up? I doubt this is YimMenu's fault.

**Comment by gamerboy1992** [comment]
I think it does have to do with gta 5, I will close the issue since I can't reproduce it now that I joined a new session.
