### ISSUE TITLE
[Bug]: Constant error code for this weeks build

### ISSUE THREAD

**Issue by Joao-Roberto-MG** [Yimura/YimMenu#3531]
### Describe the bug

ERR_GFX_D3D_INIT
getting this error code even in private sessions teleporting around or in story mode, didnt find where the error codes list are so I am asking here about this ;-;

### Steps To Reproduce

Honestly idk what, probably my shitty laptop

### Expected Behavior

I did two diferent builds, usual vs and vscode dll and both are crashing with this  same error code

### Logs

could not find any logs,where the hell would the dll make the logs go to?

### Store

Epic Games

### Language

Brazilian Portuguese

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Seems like an issue with your computer, have you looked on Google for solutions to your problem?

**Comment by Joao-Roberto-MG** [comment]
No i have not found anything related to the error code sadly
But every build has came out with every item sucessfully built or its what the console says so idk whats going on

**Comment by Yimura** [comment]
This seems like a solution to your problem, though the guy only managed to get it fixed by reinstalling Windows on his computer.

https://www.reddit.com/r/gtaonline/comments/13poc5z/gta_v_err_gfx_d3d_init_error/

**Comment by Yimura** [comment]
I'm closing this as this is an issue with your computer and not with YimMenu.

**Comment by Joao-Roberto-MG** [comment]
holy reinstaling windows
ok thanks mate
