### ISSUE TITLE
[Improvement]: Lua script config folder

### ISSUE THREAD

**Issue by OoCookieNinja** [Yimura/YimMenu#3533]
### Which feature

I'd like to know how to use the `scripts_config` folder

### Reason

To have permenent values for lua scripts to use for configuration instead of needing to set it every time it launches

**Comment by Tayipc38** [comment]
Any useage of the IO table will automatically write to the scripts_config folder. I personally opted to create a higher level lua file which has base functions and can be imported into other lua scripts.

**Comment by OoCookieNinja** [comment]
thanks
