### ISSUE TITLE
[Bug]: Lua Scripts failing to load - unexpected symbol near '<'

### ISSUE THREAD

**Issue by FireseekerDE** [Yimura/YimMenu#3534]
### Describe the bug

I downloaded CasinoPacino.lua and Pessi.lua and was trying to load the scripts. As you can see in the attached logs, some error occured. The tool is likely to read the script correctly, as it can read the symbols - so i guess its not a reading permission issue. It just moans at the opening tag. Didn't occur on the build before this.

OS: Windows 11
Injector Used: xenos latest version x86

### Steps To Reproduce

1. Start GTA Online
2. Inject YimMenu.dll
3. Load any lua script

### Expected Behavior

Scripts should load properly

### Logs

[cout.log](https://github.com/user-attachments/files/16533459/cout.log)

### Store

Rockstar

### Language

German

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
I don't know how you installed the Lua script but you did it wrong.

Please install your Lua scripts correctly, I will close this as this is not YimMenu's fault but rather user error.

**Comment by xesdoog** [comment]
Casino Pacino works fine. There's no `<` symbol at line 1 in the script unless you opened it and tried to edit it without knowledge.
This is the 1st line in the script: `local json = require('CasinoPacinoJson')`

**Comment by FireseekerDE** [comment]
Already figured out what my mistake was.
