### ISSUE TITLE
[Bug]: Start Lua Scripts Problems

### ISSUE THREAD

**Issue by SeeeSe** [Yimura/YimMenu#3535]
### Describe the bug

Why I cant use these scripts? 
[natives-1627063482.lua.txt](https://github.com/user-attachments/files/16533562/natives-1627063482.lua.txt)
[1_cat.lua.txt](https://github.com/user-attachments/files/16533565/1_cat.lua.txt)

### Steps To Reproduce

Always

### Expected Behavior

Idk

### Logs

Idk

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
That lua script is not made for YimMenu.

**Comment by xesdoog** [comment]
There's already an [animation player](https://github.com/xesdoog/YimActions) for YimMenu.

**Comment by SeeeSe** [comment]
> There's already an [animation player](https://github.com/xesdoog/YimActions) for YimMenu.

Thx me friend
