### ISSUE TITLE
[Bug]: Lua binding for `ImGui.Sliderfloat3` is broken.

### ISSUE THREAD

**Issue by tupoy-ya** [Yimura/YimMenu#3538]
### Describe the bug

The binding reads from an empty index.
https://github.com/YimMenu/YimMenu/blob/09b91ca6d719023be7092f7e634e138cdbe36f06/src/lua/bindings/imgui.hpp#L1258
https://github.com/YimMenu/YimMenu/blob/09b91ca6d719023be7092f7e634e138cdbe36f06/src/lua/bindings/imgui.hpp#L1270
https://github.com/YimMenu/YimMenu/blob/09b91ca6d719023be7092f7e634e138cdbe36f06/src/lua/bindings/imgui.hpp#L1282

We need to read from `value[2]` instead of `value[3]`.

### Steps To Reproduce

```lua
local lua_tab = gui.get_tab("GUI_TAB_LUA_SCRIPTS")
local x,y,z

lua_tab:add_imgui(function()
	local input_table = {x,y,z}
	local return_table, used = ImGui.SliderFloat3("Test", input_table, -10, 10)
	if used then
		x = return_table[1]
		y = return_table[2]
		z = return_table[3]
	end
end)
```

### Expected Behavior

`return_table[3]` shouldn't always be empty.

### Logs

[cout.txt](https://github.com/user-attachments/files/16539966/cout.txt)

### Store

Other (please mention in "Additional context")

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
Feels like this report would take longer to create than to just give a .txt file with the code fixed
