### ISSUE TITLE
[Bug]: Keep Vehicle Repared

### ISSUE THREAD

**Issue by SeeeSe** [Yimura/YimMenu#3541]
### Describe the bug

For a while now, every time I get into someone's car with the 'Keep Vehicle Repaired' option, it takes control away from the other person, preventing them from driving.  I have restarted the game, so I assume it is not a bug.

### Steps To Reproduce

Vehicle -> Keep Vehicle Repaired

### Expected Behavior

null

### Logs

null

### Store

Rockstar

### Language

Spanish

### YimMenu Language

Español (España)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by noorameer12** [comment]
that's right. It is happening to me too. Others can't drive their car while I am passenger if I use keep vehicle repaired option

**Comment by Yimura** [comment]
This issue is not really giving an expected correct behaviour in this case. What do you want to happen exactly? So that keep vehicle repaired works on anyone's vehicle or just yours? Repairing someone's vehicle will always require control over their vehicle, it may not be possible to properly fix this and we'll instead just have to stop repairing vehicles as long as you're not the driver.

**Comment by lonelybud** [comment]
https://github.com/YimMenu/YimMenu/blob/09b91ca6d719023be7092f7e634e138cdbe36f06/src/backend/looped/vehicle/keep_vehicle_repaired.cpp#L13-L19

take control should only happen when damage is detected. But looking at the code someof them are straigtforward and does not check for any damage for example clean vehicle dirt. So the only solution will be to either add lot of checks to ensure request control when required or just enable this feature when you are the driver

**Comment by gir489returns** [comment]
I agree, these iteration features should be checking if we're driving them first before attempting anything to them.

**Comment by gir489returns** [comment]
@SeeeSe and maybe @noorameer12 since you said you had this occur too, would you please test the build included with #3548 to see if the behavior is resolved?

**Comment by SeeeSe** [comment]
I'll check, look at, and edit this in 5 minutes. The expected behavior, or the desired one (the way it worked until a couple of days ago) was that it only cleans the vehicle that the player is driving (since we have other options like 'fix vehicles' to apply to other players). Although if it could be improved so that it cleans the vehicle you are in, even if you are not driving without taking control of the other player, it would be better. (Google translator)

**Comment by gir489returns** [comment]
> Although if it could be improved so that it cleans the vehicle you are in, even if you are not driving without taking control of the other player, it would be better.

**Comment by SeeeSe** [comment]
> I'm sure if you looked at the Carwash script, there's some script event it fires to tell everyone to clean that car or something because Rockstar is lazy, but I do not care enough to reverse it to find out.

Unfortunately I don't have enough knowledge about GTA, cracking and yimmod to read the scripts. (If you have a guide or something similar that would help programmers getting into this project, I'd be glad.) If it would cost to improve it, just making it work only when the player is driving would be enough. I'll go into the game right away to check the update.

**Comment by SeeeSe** [comment]
With update #3548 the bug has been fixed and now the option works as expected (as before)
