### ISSUE TITLE
[Bug]: Someone can't drive when i'm in with them

### ISSUE THREAD

**Issue by infinity-stack** [Yimura/YimMenu#3546]
### Describe the bug

when i do the fleeca job people can't move or drive but when I'm off the vehicle people can drive

### Steps To Reproduce

Get in the kurma
People can't drive

### Expected Behavior

people can drive

### Logs

[cout.log](https://github.com/user-attachments/files/16556367/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment]
It's caused by "Keep Vehicle Repaired" checkbox in Vehicles tab, probably it's taking control over vehicle every time someone else is driving.

Edit: Duplicate of #3541

**Comment by infinity-stack** [comment]
you gotta put warnings for these man
