### ISSUE TITLE
[Request]: Update Button

### ISSUE THREAD

**Issue by Nzii3** [Yimura/YimMenu#3560]
### Problem

Having to download the yimmenu DLL every time there is an update.

### Solution

An update button in the menu or injector to update Yimmenu from the source. That way it’s easier to update it.

### Reason

This would make it easier to update it.

**Comment by ghost** [comment]
https://github.com/NiiV3AU/YMU/releases/

**Comment by Nzii3** [comment]
> https://github.com/NiiV3AU/YMU/releases/

What does that do? I’m not gonna download something that isn’t made by the yimmenu developers.

**Comment by ghost** [comment]
> I’m not gonna download something that isn’t made by the yimmenu developers.

Do you think I care? I recommended you a tool that does what you asked for. The developers aren't going to make their own injector because there are plenty of them on GitHub.

**Comment by Nzii3** [comment]
> > I’m not gonna download something that isn’t made by the yimmenu developers.
> 
> Do you think I care? I recommended you a tool that does what you asked for. The developers aren't going to make their own injector because there are plenty of them on GitHub.

I was asking a developer, not you. Not downloading a virus.

**Comment by ghost** [comment]
this stupid request should be closed. what the hell do you even want? for the dll to download a new dll for you, seriously? typical frontend developer

**Comment by Nzii3** [comment]
> this stupid request should be closed. what the hell do you even want? for the dll to download a new dll for you, seriously? typical frontend developer

its called convience you fuckin idiot. who even asked for your help? exactly, no one did. crying that an issue is open is just embarrassing for you.

**Comment by ghost** [comment]
> > this stupid request should be closed. what the hell do you even want? for the dll to download a new dll for you, seriously? typical frontend developer
> 
> its called convience you fuckin idiot. who even asked for your help? exactly, no one did. crying that an issue is open is just embarrassing for you.

I need dll to inject itself and update itself womp womp
![image](https://github.com/user-attachments/assets/9e9e2509-0124-40e8-bd3a-d202f4c1c642)

**Comment by xesdoog** [comment]
> I was asking a developer, not you. Not downloading a virus.

Your profile status says "Probably in VS Code" but you can't read a simple Python code? What are you doing in VSC then? Uninstall.

**Comment by Nzii3** [comment]
> > I was asking a developer, not you. Not downloading a virus.
> 
> Your profile status says "Probably in VS Code" but you can't read a simple Python code? What are you doing in VSC then? Uninstall.

#1 never read the code idiot
#2 again, you guys are obsessed with me it’s hilarious
