### ISSUE TITLE
Lua Script (Third Party): Cargo loop detected

### ISSUE THREAD

**Issue by UnforseenDeath** [Yimura/YimMenu#3570]
### Describe the bug

Banned for using cargo loop

### Steps To Reproduce

1. Download ultimate menu
2. Use cargo loop
3. Wait for ban

### Expected Behavior

Banned within a week of using cargo loop, to my knowledge cargo loops have been undetected for years so my only assumption is that yim is detected 
No I did not use anything else, all I did was log onto a freshly wiped account l, use cargo loop for around an hour and mess around with it then got off, didn't unlock anything, change my level.

### Logs

[cout.txt](https://github.com/user-attachments/files/16591559/cout.txt)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

![Screenshot_20240812_131207_Email](https://github.com/user-attachments/assets/114ccf05-b9d6-400b-af99-8051eff1e391)
![Screenshot_20240812_131116_Email](https://github.com/user-attachments/assets/6a84eafe-a814-457e-a79c-164b4871b297)

Proof of ban today 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by snowleopardd** [comment]
Yeah i think there's a ban wave right now, but it's about a money method, so yim should be safe, i think it's your fault for using third party money scripts.

**Comment by CrownCCX** [comment]
Was also thinking it could be that, still not sure on it but what was used was ultimate menu, talking with another person that hasn't used scripts on yim though and they said they're fine ¯\_(ツ)_/¯ just thought I'd post this anyways considering the current situation of a mini banwave

**Comment by qzxyzy** [comment]
Funny to say i wasnt using it even for 2 days and im gone permanently XD kinda funny tbh

**Comment by Ahmad23145** [comment]
Cargo Loop is detected now 😔

**Comment by V1RU513N** [comment]
If the problem comes from a Lua script, it should be posted on the creator's repository. It doesn't have much to do with YIM

**Comment by Ahmad23145** [comment]
> If the problem comes from a Lua script, it should be posted on the creator's repository. It doesn't have much to do with YIM

Yeah it's not YimMenu's problem
