### ISSUE TITLE
[Bug]: Keep vehicle repaired works client-sided only

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#3577]
### Describe the bug

The vehicle doesn't gets repaired for others pov while using the keep vehicle repaired option, it's just repaired for our pov.

### Steps To Reproduce

1. Spawn a vehicle
2. Make sure Keep vehicle repaired is turned on
3. Get it damaged ( Drive it into a wall or something)
4. Ask your friend/other player if the vehicle is damaged for their pov
5. Notice your vehicle is just fine in your pov

### Expected Behavior

The vehicle must be fixed for other's pov too

### Logs

[cout.log](https://github.com/user-attachments/files/16601951/cout.log)

### Screenshots / Video

My pov: 
![image](https://github.com/user-attachments/assets/cfa218e1-9dc6-4352-bc06-7b49dfb0c43a)
Other player's Pov: 
![image](https://github.com/user-attachments/assets/3c2c4db3-b4fc-406a-976e-e9d9ae49fda5)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

Using the Fix Vehicle in Context menu actually fixes the vehicle.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is probably a causality of #3548.

**Comment by gir489returns** [comment]
Actually, it's more likely that this has always existed, and it's due to us using SET_VEHICLE_DEFORMATION_FIXED instead of SET_VEHICLE_FIXED. SET_VEHICLE_FIXED emits a damage packet to everyone in the bubble that the car has been fixed. This has probably always been an issue and just nobody noticed. We will have to manually craft this packet ourselves after invoking SET_VEHICLE_DEFORMATION_FIXED, it was probably not meant to be used online.

**Comment by CypherMorgan** [comment]
> Actually, it's more likely that this has always existed, and it's due to us using SET_VEHICLE_DEFORMATION_FIXED instead of SET_VEHICLE_FIXED. SET_VEHICLE_FIXED emits a damage packet to everyone in the bubble that the car has been fixed. This has probably always been an issue and just nobody noticed. We will have to manually craft this packet ourselves after invoking SET_VEHICLE_DEFORMATION_FIXED, it was probably not meant to be used online.

Yeah probably as i've faced this issue since last couple of updates, but wasnt too sure as some players said its fixed and some said its not, but now its damaged for all of them.

**Comment by gir489returns** [comment]
I have made an initial attempt to solve this via #3578 however while reversing the CNetObjVehicle class, I discovered that our netObject class is out of sync, and might need to be adjusted, so I don't know if this code will work as-is.

**Comment by SeeeSe** [comment]
> however while reversing the CNetObjVehicle class, I discovered that our netObject class is out of sync, and might need to be adjusted, so I don't know if this code will work as-is.

Works fine for me. Wait for other people to report before changing anything.

**Comment by gir489returns** [comment]
> Works fine for me. Wait for other people to report before changing anything.

Did other people see your car as fixed?

**Comment by CypherMorgan** [comment]
I'll try it, and will update ya!

**Comment by SeeeSe** [comment]
> Did other people see your car as fixed?

Yes, without the update #3578. (I have checked it with the update #3541 I don't know if you put the #3578 implementations there)

**Comment by CypherMorgan** [comment]
> I have made an initial attempt to solve this via #3578 however while reversing the CNetObjVehicle class, I discovered that our netObject class is out of sync, and might need to be adjusted, so I don't know if this code will work as-is.

I tried it, and it's still getting damaged for other players. That player's POV:
![image](https://github.com/user-attachments/assets/a6044de4-50e6-4145-b0b8-684d37a014b8)

My pov:  
![image](https://github.com/user-attachments/assets/ac2cfe14-d026-4a43-87af-c06955e49775)


Edit: It's another friend of mine, so multiple users can see the damage.

**Comment by SeeeSe** [comment]
> I tried it, and it's still getting damaged for other players. That player's POV:

Morgan, could you tell me what settings you put in the vehicles? (goodmode, keep vehicle repair, etc...). Have you tried using you_user->fix vehicle?
P.S: Have you tested if there is a difference with personal vehicles and cloned vehicles?

**Comment by gir489returns** [comment]
> I tried it, and it's still getting damaged for other players. That player's POV: ![image](https://private-user-images.githubusercontent.com/108661795/357571467-a6044de4-50e6-4145-b0b8-684d37a014b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODQ1MzcsIm5iZiI6MTcyMzU4NDIzNywicGF0aCI6Ii8xMDg2NjE3OTUvMzU3NTcxNDY3LWE2MDQ0ZGU0LTUwZTYtNDE0NS1iMGI4LTY4NGQzN2EwMTRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QyMTIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjZhMjA4NWYwNmRkMGIwY2RjNjQ0YTUxMTU2ZjYyN2ZlMmQxZjIxYjk3MWRjZDk2ZDlkMmM4YjIyNGVkZjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.77H15GHowD-mZyIeVak2dth7ybV0ZUe_sbGsimWQMIs)
> 
> My pov: ![image](https://private-user-images.githubusercontent.com/108661795/357571568-ac2cfe14-d026-4a43-87af-c06955e49775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODQ1MzcsIm5iZiI6MTcyMzU4NDIzNywicGF0aCI6Ii8xMDg2NjE3OTUvMzU3NTcxNTY4LWFjMmNmZTE0LWQwMjYtNGE0My04N2FmLWMwNjk1NWU0OTc3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QyMTIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2M0YThhOTBhZWJjNjViMzdmNzc1ZmQ1YTk1MzBjZGFhM2EzMTZmOGE5YmI0ODdhYTNlNzkwMmExNzk5NWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YEAt2ZzgjyA4wdmCc2T6slRzLnaI9FVymBgLsWd9jOs)

The cars do not look damaged to me in either picture compared to your control pictures.

**Comment by CypherMorgan** [comment]
> > I tried it, and it's still getting damaged for other players. That player's POV:
> 
> Morgan, could you tell me what settings you put in the vehicles? (goodmode, keep vehicle repair, etc...). Have you tried using you_user->fix vehicle? P.S: Have you tested if there is a difference with personal vehicles and cloned vehicles?

I've Godmode, keep vehicle repaired and all the proof checks enabled.

**Comment by gir489returns** [comment]
> > > I tried it, and it's still getting damaged for other players. That player's POV:
> > 
> > 
> > Morgan, could you tell me what settings you put in the vehicles? (goodmode, keep vehicle repair, etc...). Have you tried using you_user->fix vehicle? P.S: Have you tested if there is a difference with personal vehicles and cloned vehicles?
> 
> I've Godmode, keep vehicle repaired and all the proof checks enabled.

What is damaged in your picture.

**Comment by CypherMorgan** [comment]
> The cars do not look damaged to me in either picture compared to your control pictures.

If you notice, the hood of the car is poped open which usually happens when the car hits something

Edit: The Itali GTO ( Black one )... I'll get more detailed information after a couple of hours ( sorry ) as my friend is offline rn and the other players are kinda slow with processing things i ask ._. but yea afaik in the most cases they saw dents, and hood being poped open.

**Comment by gir489returns** [comment]
> > The cars do not look damaged to me in either picture compared to your control pictures.
> 
> If you notice, the hood of the car is poped open which usually happens when the car hits something
> 
> Edit: The Itali GTO ( Black one )... I'll get more detailed information after a couple of hours ( sorry ) as my friend is offline rn and the other players are kinda slow with processing things i ask ._. but yea afaik in the most cases they saw dents, and hood being poped open.

I can't see shit, it looks fine compared to the orange car you posted. I added 2 new buttons to the Vehicle tab, next to Repair, there should be SET_VEHICLE_DEFORMATION_FIXED and SYNC_DAMAGES. Repair should obviously fix the damages and force a sync to everyone, so don't press that one unless the other two aren't working and you need it to go back to baseline. SET_VEHICLE_DEFORMATION_FIXED just sets the deformation variables back to 0, and SYNC_DAMAGES marks the vehicle sync tree as dirty. Try pressing each one once at a time and seeing if it syncs. If pressing just SET_VEHICLE_DEFORMATION_FIXED fixes it, then we don't need this elaborate bullshit, but I have a feeling we might. If pressing SET_VEHICLE_DEFORMATION_FIXED  then pressing SYNC_DAMAGES works, then I can fix that. If just pressing SYNC_DAMAGES works, then you're a dirty-ass liar and it was working.

**Comment by CypherMorgan** [comment]
So I tried it, and as per the other players say, the car is still damaged using both options but what I think is, its not damaged like the Orange car but just damages like Hood, doors poped open, a couple of dents(I dont really know if we can consider it damaged tho, the deformation gets fixed with SET_VEHICLE_DEFORMATION_FIXED then pressing SYNC_DAMAGES). Repair fixes all of the damage for other players...

Edit: I tried with the same guy again, the car is broken in most of the cases, even after trying the way you asked me to... 
My POV: 
![image](https://github.com/user-attachments/assets/85aafcf4-b941-4daa-9368-da14b5714ffe)
and his pov: 
![rn_image_picker_lib_temp_c198fc3e-1d54-43da-a91b-654a82b1617d](https://github.com/user-attachments/assets/152ee5b1-9e5e-4674-929c-776c03e76dcf)
I had Keep vehicle repaired turned on in this with GodMode and Proofs enabled.

and this is the image of car when i kept the keep vehicle repaired turned off :
![rn_image_picker_lib_temp_c198fc3e-1d54-43da-a91b-654a82b1617d](https://github.com/user-attachments/assets/d2e5b28a-3bfb-4db6-a388-d8cbb3f49007)
 and for my pov the car looked like this: 
![image](https://github.com/user-attachments/assets/ae14bad3-5549-4c27-8926-89ef7d5004b1)

**Comment by gir489returns** [comment]
@CypherMorgan I have dug deeper into this, but I still can't figure out why we're still emitting damage information to other players. I was able to confirm the behavior you described with @ShinyWasabi but wasn't able to pin down the cause. 

Please retest with the build from #3583 as I have completely rewrote Vehicle Godmode from scratch now with some logging information (and an additional hook) that should at least tell us what's going on.

**Comment by CypherMorgan** [comment]
Okay so i tried it, this was my pov using keep vehicle repaired, godmode and all the proofs enabled: 
![image](https://github.com/user-attachments/assets/3d2c26f7-c8c7-4c12-8de7-ea41cdabe07f)
and this one is another player's pov: 
![image](https://github.com/user-attachments/assets/1665dd6a-d7f2-4294-8f2f-56ec1a05bf1d)
and here are the logs: 
[cout.log](https://github.com/user-attachments/files/16618952/cout.log)
Edit: It was having a lil bit of scratches for me but deformed for the other player ( I drove the car into a tree so the front is damaged like that )

**Comment by gir489returns** [comment]
Alright so all I learned is that we're not updating them on the damage, which might be the issue. The game might locally interpolate the damage, then wait for a damage sync packet from the host, and we're probably never sending one. What we're basically doing is telling the game that the car can't be deformed at all, so it never runs the deformation code. Maybe we can try to sync that behavior to other players. There's a check the game does that sees if you just spawned. I added code to try writing to it constantly so that maybe it will emit to other players you have just spawned and to not apply damage to the vehicles. @CypherMorgan can you try again? If this doesn't work, I'm starting to run out of ideas.

**Comment by SeeeSe** [comment]
If it helps, by using userA->fix vehicle you fix their car for everyone, including the broken doors, but you fail to keep the car "clean", leaving scratches on it.  (Tested on the latest official update)

**Comment by CypherMorgan** [comment]
> Alright so all I learned is that we're not updating them on the damage, which might be the issue. The game might locally interpolate the damage, then wait for a damage sync packet from the host, and we're probably never sending one. What we're basically doing is telling the game that the car can't be deformed at all, so it never runs the deformation code. Maybe we can try to sync that behavior to other players. There's a check the game does that sees if you just spawned. I added code to try writing to it constantly so that maybe it will emit to other players you have just spawned and to not apply damage to the vehicles. @CypherMorgan can you try again? If this doesn't work, I'm starting to run out of ideas.

I tried that built but.. i dont have any other player to test their pov but yeah with all the proofs and settings enabled i got the vehicle in this state, after hitting a couple of poles..
![image](https://github.com/user-attachments/assets/2a3ec4a8-a555-40e4-a927-add1d6b1dd8f)
here's the logs 
[cout.log](https://github.com/user-attachments/files/16619647/cout.log)

**Comment by CypherMorgan** [comment]
I know, i tried it on my Online, asked a random player in public lobby, they described the vehicle's state somewhat similar to the one in picture. That player said, "The front view is damaged" so i assume it is getting synced? I'll have to get more detailed info whenever a friend of mine is available, I'll update here.

**Comment by gir489returns** [comment]
> I know, i tried it on my Online, asked a random player in public lobby, they described the vehicle's state somewhat similar to the one in picture. That player said, "The front view is damaged" so i assume it is getting synced? I'll have to get more detailed info whenever a friend of mine is available, I'll update here.

I don't think you're using the right build or something. 

https://github.com/user-attachments/assets/98e46e2a-e6a0-4f7f-8246-e0d693ccf974

My personal vehicle is the Toreador and the Dominator is a car I spawned in. It only affects the car you're driving.

**Comment by CypherMorgan** [comment]
I tried to compile your branch and used that build and this is what i got, The D10 is my pv and the gto is the one i spawned
![image](https://github.com/user-attachments/assets/a9a7e949-aeaf-45c0-b96f-fd01150945ca)

i tried to get the car damaged infront of my friend and here are the povs
Mine: 
![image](https://github.com/user-attachments/assets/16627114-1f2a-43c4-8b27-758ef3c8be38)
and his: 
![rn_image_picker_lib_temp_16ae0ba4-c5e0-495a-aa45-2679474ecdbb](https://github.com/user-attachments/assets/b6df543c-3592-4d12-a352-855c247107bf)
here are the logs: 
[cout.log](https://github.com/user-attachments/files/16623141/cout.log)
Oh btw, I'm the host of the sessions mostly, just letting ya know if that would cause any difference?

Edit: My cars have 0 Armor, forgot to mention that.

**Comment by CypherMorgan** [comment]
@gir489returns I found the issue i guess, its working fine and the car isnt getting damaged with the Godmode turned off. 
Maybe the issue is this? `if (!g.vehicle.god_mode)`
and i modified the code a bit to this; 
```
if (!g.vehicle.god_mode)
{
        VEHICLE::SET_VEHICLE_FIXED(veh);
	VEHICLE::SET_VEHICLE_DEFORMATION_FIXED(veh);
}
```

I will get the Screenshots too, in a while and ill add them here if it's actually working fine.

Edit: Sorry for the tag

my pov; 
![image](https://github.com/user-attachments/assets/c61229f8-58a4-489a-808d-17f3f52cf3ce)


friend's pov 
![image](https://github.com/user-attachments/assets/522d8ec2-c0d9-4aaf-bb62-7a00a7da9430)

**Comment by gir489returns** [comment]
@CypherMorgan No, the issue was determined to be spoofing.spoof_hide_veh_god.

```
if (g.spoofing.spoof_hide_veh_god && g_local_player && self::veh && g_local_player->m_vehicle && g_local_player->m_vehicle->m_net_object == net_object)
{
	node->m_godmode         = false;
	node->m_bullet_proof    = false;
	node->m_fire_proof      = false;
	node->m_smoke_proof     = false;
	node->m_steam_proof     = false;
	node->m_collision_proof = false;
	node->m_explosion_proof = false;
	node->m_melee_proof     = false;
	node_updated = true;
}
```

With the spoofing turned on, nothing we would do would sync to the client. So the solution to this is to not use spoof vehicle godmode if you want to have your deformation sync to the client.

**Comment by CypherMorgan** [comment]
> With the spoofing turned on, nothing we would do would sync to the client. So the solution to this is to not use spoof vehicle godmode if you want to have your deformation sync to the client.

Ah, understood, then i'll probably change it on my local build, thanks for trying to figure out the issue though, i really appreciate the efforts you put in.
