### ISSUE TITLE
[Improvement]: List of some problems (includes bugs).

### ISSUE THREAD

**Issue by SeeeSe** [Yimura/YimMenu#3579]
### Which feature

Since I've seen 'gir489returns' eager to work, I'll leave this here for you.

(Version 2024-08-10)

NEED proteccion:
- Trigger UFO abduction (to disable abduction, use force mission and exit mission screen)
- Trigger pizza delivery
- Some modders have the option to leave you in an infinite taser state blocking your movement
- Some modders manage to teleport me or even send me on a mission
- Some modders can kick you out of your vehicle

BUG: 
- Delete gun cant delete cages
- Desynck kick not working(?)
- When you use modderUser->BACKEND_DELETE_VEHICLE On a protected modder, on your screen (I don't know about other people's, but not the modder's)
their character stays still inside the car and locked in place, not moving again until the modder gets out of the car.

IDEA vs FPS Bomb:
- Hotkey to quickly lock/unlock all explosions as a quick fix for FPS bombs.

### Reason

'gir489returns' likes to work

**Comment by gir489returns** [comment]
Fuck you.
