### ISSUE TITLE
[Request]: Set Memory Values

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#358]
### Problem

- We can not set Memory Values

### Solution

- "  memory::set_value<uint32_t>({ 0x..... });  "

### Reason

- You would be able to make more epic Feartures

### Additional context

- None

**Comment by Clone69420** [comment]
Tell me if its already in the menu not quiet sure

**Comment by Yimura** [comment]
This will never be added to YimMenu, you're free to implement it into your custom version but not in YimMenu.

The reason being that all values you'd ever wish to modify can be modified through classes which are much more transparent on what you're actually doing. While just a bunch of offsets is very obscure in what you're trying to achieve or doing.
Classes are also much easier to update than some obscure offsets.

I don't see a reason on why I would need to add this, neither did you provide an example of some sort of feature you wish to make using this.

**Comment by SkiddyToast** [comment]
You can set memory by pattern scanning, and setting the value of the pointer.
For example:
```c++
//pointers.cpp
if (auto world_object_check = mem_region.scan("48 85 C0 0F 84 ? ? ? ? 8B 48 50"); world_object_check)
{
	memset(world_object_check.as<void*>(), 0x90, 24);
}
```
or
```c++
//pointers.cpp
main_batch.add("Whatever", "Pattern Here", [this](memory::handle ptr)
{
	m_whatever = ptr.as<uint32_t*>();
});
//Somewhere else
*m_whatever = 0;
```

**Comment by Clone69420** [comment]
> You can set memory by pattern scanning, and setting the value of the pointer. For example:
> 
> ```c++
> //pointers.cpp
> if (auto world_object_check = mem_region.scan("48 85 C0 0F 84 ? ? ? ? 8B 48 50"); world_object_check)
> {
> 	memset(world_object_check.as<void*>(), 0x90, 24);
> }
> ```
> 
> or
> 
> ```c++
> //pointers.cpp
> main_batch.add("Whatever", "Pattern Here", [this](memory::handle ptr)
> {
> 	m_whatever = ptr.as<uint32_t*>();
> });
> //Somewhere else
> *m_whatever = 0;
> ```
If i would change for example the run multi with setmem how would it look like?

|| memset<float>({ OFFSET_PLAYER , OFFSET_PLAYER_INFO , OFFSET_PLAYER_INFO_RUN_SPD }, 2.5); ||

**Comment by SkiddyToast** [comment]
No, you would use the CPedFactory class and the classes it has in it.
```c++
(*g_pointers->m_ped_factory)->m_local_ped->m_player_info->m_run_speed = 2.5;
```

**Comment by Yimura** [comment]
There are whole bunch of other things you can modify in the CPlayerInfo class, take a look here:
https://github.com/Yimura/GTAV-Classes/blob/master/CPlayerInfo.hpp

**Comment by maybegreat48** [comment]
> You can set memory by pattern scanning, and setting the value of the pointer. For example:
> 
> ```c++
> //pointers.cpp
> if (auto world_object_check = mem_region.scan("48 85 C0 0F 84 ? ? ? ? 8B 48 50"); world_object_check)
> {
> 	memset(world_object_check.as<void*>(), 0x90, 24);
> }
> ```
> 
> or
> 
> ```c++
> //pointers.cpp
> main_batch.add("Whatever", "Pattern Here", [this](memory::handle ptr)
> {
> 	m_whatever = ptr.as<uint32_t*>();
> });
> //Somewhere else
> *m_whatever = 0;
> ```

The world object pattern (what does that do anyway?) in your example is integrity checked

**Comment by SkiddyToast** [comment]
It enables the spawning of world objects (such as trees and Mt. Chiliad). Thanks for letting me know!

**Comment by maybegreat48** [comment]
You have to use that like the model spawn bypass, patch it, call `CREATE_OBJECT` and then restore the original bytes. Off topic but does Mt chiliad actually sync with other players?

**Comment by SkiddyToast** [comment]
Alright! I will go ahead and do that. And only the LOD, but yes! Here's the hash if you want it:
`RAGE_JOAAT("cs1_lod3_terrain_slod3_01")` or `0x5CA4A9A0`
