### ISSUE TITLE
[Improvement]: Make people's ip more accurate

### ISSUE THREAD

**Issue by infinity-stack** [Yimura/YimMenu#3580]
### Which feature

I would like to see people's ip in session more accurate instead of being in a random park in the middle of nowhere.

### Reason

I want to meet one of my friends because we wanted to meet up

### Additional context

I will not be using this to grief or scare people, I am not those type of people.

**Comment by Yimura** [comment]
What do you mean “make people’s IP more accurate”, the IP address is as accurate as it can already be. If you really want to meet up why not ask the person?

Closing this as there’s no way to “make an IP address more accurate” than it already is.
