### ISSUE TITLE
[Bug]: Typo in language name, "Chinese (Simpified)"

### ISSUE THREAD

**Issue by rjp421** [Yimura/YimMenu#3581]
### Describe the bug

There seems to be a typo in "Simpified", missing the L.

### Steps To Reproduce

- View "Extra Info" on a player using Chinese (Simplified).
- Use LUA to call `network.get_player_language_name()` on a player using Chinese (Simplified).

It will return "Chinese (Simpified)"

### Expected Behavior

It should return "Chinese (Simplified)"

### Logs

[cout.txt](https://github.com/user-attachments/files/16616461/cout.txt)

### Screenshots / Video

![yim-simpified](https://github.com/user-attachments/assets/f7bfe81e-5181-49cd-9cc5-a167ef31d5fc)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
![image](https://github.com/user-attachments/assets/5440f8d5-ec49-4d42-8b9b-2f4ae9e69d1b)

![image](https://github.com/user-attachments/assets/f639ae10-8c78-49ad-b57c-6e8de6f5f470)

I actually noticed this too a few weeks back, I just never got around to filing a ticket/fixing it.
