### ISSUE TITLE
[Request]: Set/Remove "Block join" on a player from LUA

### ISSUE THREAD

**Issue by rjp421** [Yimura/YimMenu#3582]
### Problem

As far as I know, I cannot block another player from joining with LUA.

### Solution

Add the ability to block another player from joining, with LUA.

The same way the `Network > Player Database > "Block Join"` Checkbox works.

### Reason

Making a LUA script that needs to set players flagged as modders with certain reasons, as being Blocked from joining again.

### Additional context

Also the ability to remove the "Block Join" from the player in the database if it exists, and to return the Blocked status of a player.

Thanks!

**Comment by gir489returns** [comment]
Why would someone want a Lua script to be able to do this? What's the usecase? This seems stupid.

**Comment by rjp421** [comment]
it took you 3 days to come up with that?

uh, because there are so many toxic people, i want to easily kick and block them from joining again, without having to search for them in the database and block.


Reason
Making a LUA script that needs to set players flagged as modders with certain reasons, as being Blocked from joining again.

**Comment by gir489returns** [comment]
It took us 3 days to care, fuck-ass.
