### ISSUE TITLE
[Request]: Bodyguards attack players.

### ISSUE THREAD

**Issue by Mrokoui** [Yimura/YimMenu#3588]
### Problem

So we already have in yim menu peds as bodyguards. Problem is they fight only with npc, it would be great if someone will fix code so peds can defend us from players :)

### Solution

In yim menu you can add separate bodyguards to fight with players, or change existed code and just do bodyguard for npc and players 

### Reason

That's would be great, improve some RolePlay mode in gta v, already we have peds and animations, this would help with RP drive by gangs or spawn swat team to fight toxic kids

### Additional context

I am interested only with peds

**Comment by xesdoog** [comment]
Most of these things can be (and have already been) done in Lua so there's no need to bloat the menu. Have you checked the [YimMenu-Lua](https://github.com/YimMenu-Lua) repository? [Billionaire Services](https://github.com/YimMenu-Lua/Billionare-Services) has that option but you can only spawn 3 bodyguards and 3 escorts (6 in total).
You can ask them to attack a player or start a random driveby shooting on everybody.
