### ISSUE TITLE
[Request]: Character Model Swapper

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3597]
### Problem

Some other menus have libraries with hundreds of models including all models from the gamefiles. Would be cool to see this get implemented into Yim :)

### Solution

No idea how to do it

### Reason

Nice to have and funny

**Comment by xiaoxiao921** [comment]
World -> Model Swapper

**Comment by ghost** [comment]
I meant Player Model swapper.... i tried to do that with the Swapper in World but that doesnt work
