### ISSUE TITLE
if self_no_ragdoll() is active, your ped movement is incorrect

### ISSUE THREAD

**Issue by The-Denno** [Yimura/YimMenu#36]
**Describe the bug**

If self->no_ragdoll is active the ped will get into ragdoll if in appartment or in garage.
If you are outside in freemode and run against an object, you might fall and can't get up again.

Disabling the injection or the self protection will remove this behavior.

**To Reproduce**
1. Go to 'GTA Online with injected dll and walk into a car in garage'
2. Click on ''

**Expected behavior**

The expected behavior should be, that I can disable the no_ragdoll option in settings menu.
Maybe I will provide a PR later...

**Logs**
Nothing in log to this specific error

**Build** ===> Nightly af9c4ea
Select which applies for you:
- [x] I used YimMenu unmodified
- [x] I use my own version of YimMenu

tried compiling it myself, same result.

**Additional context**

**Comment by Yimura** [comment]
Thanks for your bug report, I will look into fixing this, I'm not gonna lie I kinda forgot about this bug. Whoops...

**Comment by The-Denno** [comment]
no problem - have a look at my PR 

[Pull Request 37 ](https://github.com/Yimura/YimMenu/pull/37)

PS: Kinda ruined the first commit - didn't get that feat(GUI) - GUI is not a feature in my conventions :D

**Comment by Yimura** [comment]
Yes I did, did you see my comment on it?

**Comment by The-Denno** [comment]
you are too damn fast

**Comment by The-Denno** [comment]
Could be this the fix ? 

Works for me.

[Pull Request 39](https://github.com/Yimura/YimMenu/pull/39)

**Comment by Yimura** [comment]
Ye might be, I can't check right now though
