### ISSUE TITLE
[Request]: Any way to disable the snack inventories autofull in contact missions and heists.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3600]
### Problem

![批注 2024-08-18 201438](https://github.com/user-attachments/assets/ad2de14f-ff47-4258-870a-c298479d7c66)

### Solution

Request a switch to choice enable and disable.

### Reason

I have already feedback this to Rockstar，I don't like redwood cigarettes and beer in my snack inventories！I want my snacks to be limited and eat up , so that they are meaningful and enjoyable

**Comment by Inkmei** [comment]
I'm not very good at computers，i know kiddion lua

**Comment by ghost** [comment]
> This could easily be made into a Lua script.

I'm not very good at computers，but i know Kiddion support lua
