### ISSUE TITLE
[Bug]: Godmode on vehicles bug

### ISSUE THREAD

**Issue by SeeeSe** [Yimura/YimMenu#3604]
Godmode doesn't work on vehicles.

UPDATE: I restarted the game and it still happened, suddenly I got into a personal vehicle and the godmode started working, I got into a spawn and it worked again.

The bug starts:
The bug occurs when you enter any type of vehicle before entering a personal one.

Version: YimMenu-dev-deb35d7fb2e923fab40a3e116910231506782730

**Comment by lonelybud** [comment]
godmode will be removed once you exit the vehicle

**Comment by CypherMorgan** [comment]
> Version: YimMenu-dev-deb35d7fb2e923fab40a3e116910231506782730

Have you tried the latest version, rather than the dev-deb build?

**Comment by SeeeSe** [comment]
> godmode will be removed once you exit the vehicle

If I had noticed, I say that if I throw a C4 while inside the vehicle, the vehicle breaks (IT DOES NOT HAVE GODMODE)

**Comment by SeeeSe** [comment]
> Have you tried the latest version, rather than the dev-deb build?

Not yet, can you try it yourself?
When you start the game, get into any vehicle that is not a personal one and explode some C4s while inside.

**Comment by gir489returns** [comment]
> godmode will be removed once you exit the vehicle

Yes, and this was always the bahviour.

**Comment by SeeeSe** [comment]
> Yes, and this was always the bahviour.

I didn't write that comment... please re-open and read it all. If I'm in the car and a C4 explodes, the car breaks down.

**Comment by SeeeSe** [comment]
I don't know why I write if no one reads me...

**Comment by xiaoxiao921** [comment]
Your issue is invalid because you are not using the latest dll available from the nightly. No need to spam

**Comment by SeeeSe** [comment]
> Your issue is invalid because you are not using the dll available from the nightly. No need to spam

I'm using the update that gir4 made to avoid the false DELETE_VEHICLE warnings, which come after the last update. If that has already been fixed, could you give me that answer, but I got the wrong one.

**Comment by xiaoxiao921** [comment]
Right, when you make an issue you are supposed to follow the issue template which forces you to check if you are using the dll from the latest nightly release.

**Comment by SeeeSe** [comment]
> Right, when you make an issue you are supposed to follow the issue template which forces you to check if you are using the dll from the latest nightly release.

I had to delete it because I reported the bug incorrectly and redo it, my bad. Thanks for the help.

**Comment by CypherMorgan** [comment]
> > Have you tried the latest version, rather than the dev-deb build?
> 
> Not yet, can you try it yourself? When you start the game, get into any vehicle that is not a personal one and explode some C4s while inside.

Yeah I tried it, and No I'm not able to reproduce it on the latest build which is `4046640c1e2e9f7fdd6d51895020889d98ca30b6`

**Comment by gir489returns** [comment]
> Yeah I tried it, and No I'm not able to reproduce it on the latest build which is `4046640c1e2e9f7fdd6d51895020889d98ca30b6`

Because I fixed this in #3552
