### ISSUE TITLE
[Build]:  Question

### ISSUE THREAD

**Issue by matarife123** [Yimura/YimMenu#3606]
### Describe the build issues

When I use the "ls custom" editor, the changes to the car are not saved when starting a new game, what am I doing wrong?

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by gir489returns** [comment]
We are not a recovery menu.

**Comment by matarife123** [comment]
> We are not a recovery menu.

It's a question I have, I don't know where to post it.

**Comment by Yimura** [comment]
What he said is correct though, we are not a recovery menu thus changes to your vehicle will not persist.
