### ISSUE TITLE
[Request]: slaping me with gun 

### ISSUE THREAD

**Issue by Beginner555989** [Yimura/YimMenu#3618]
### Problem

i have God mode on and NOclip  on and if someone close to me he slaping me with the gun i stay 20 sec on ground cant move o_O 

### Solution

![Capture](https://github.com/user-attachments/assets/5f4e9c47-97d8-4376-8b0a-9d104f5a0c70)
![Screenshot (118)](https://github.com/user-attachments/assets/dcb0ce6d-e4e1-449b-84ad-96c57c5035cb)

### Reason

other modders laughing at me bcz of it ^^

**Comment by Ahmad23145** [comment]
It's normal lol
