### ISSUE TITLE
[Bug]: probleme pour ouvrir les fonctionalliter 

### ISSUE THREAD

**Issue by Dydax18** [Yimura/YimMenu#3620]
### Describe the bug

bonjours quand je lance le menu sa me dit de cliquer sur vkl button mais quand je le fais rien ce passe jaimerais remettre les parametre a 0 si cest possible pour pouvoir louvrir avec la touche inser

### Steps To Reproduce

ffff

### Expected Behavior

 remettre mon mode menu a 0 

### Logs

idem je ne comprend pas 

### Store

Steam

### Language

French

### YimMenu Language

Français (FR)

### Additional context

ff

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
By default the key is INSERT on you keyboard, if you changed it and don't know what it is now delete your %appdata%/YimMenu/settings.json file to start fresh

**Comment by Dydax18** [comment]
tu le trouve ou ce ficher ?
