### ISSUE TITLE
[Bug]: LOT OF NOT VISIBLE NEWER CARS IN SHOPS

### ISSUE THREAD

**Issue by vojta0808** [Yimura/YimMenu#3625]
### Describe the bug

When I am playing with yimmenu in online, I do not see lot of newer cars. (for example new police cars in warstock and lot of another cars in other shops.. + for example tab FEATURED is empty without cars)

### Steps To Reproduce

1. Enter warstock shop for example
2. Not seeing lot of new cars

### Expected Behavior

I want to open shop and see every car in shop which is normally avalaible. (I do not mean removed cars from mercenary update)

### Logs

[cout.txt](https://github.com/user-attachments/files/16743076/cout.txt)

### Screenshots / Video

![obrázek_2024-08-26_035903212](https://github.com/user-attachments/assets/7a89e790-bfbe-40c2-966f-e31bf9c8d576)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

When I do not have turned on yimmenu, I see every avalaible car so it is something with menu + I tried it also with last release - cars still do not show

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by vojta0808** [comment]
I deleted ultimate menu and it works. Thanks for response!

**Comment by gir489returns** [comment]
> I deleted ultimate menu and it works. Thanks for response!

![futurama-bender](https://github.com/user-attachments/assets/645831dc-4f4a-4dee-acf6-af756447fe1c)
