### ISSUE TITLE
[Request]: Turn off spammer notification

### ISSUE THREAD

**Issue by jackdayungog** [Yimura/YimMenu#3626]
### Solution

Add option to turn off chat spammer notification

### Reason

Can't turn off notification when chat spammer joins

**Comment by Beginner555989** [comment]
go to setting >> reaction >> chatspamm detected >>> block join

**Comment by ghost** [comment]
we need to remove this from src/hooks/protections/receive_net_message.cpp:
```
g_notification_service.push("PROTECTIONS"_T.data(),

	std::format("{} {}", player->get_name(), "IS_A_SPAMMER"_T.data()));
```

because of this we see 2 notifications instead of one
