### ISSUE TITLE
[Bug]: SOME BUGS ABOUT VHEICLES

### ISSUE THREAD

**Issue by HD6630** [Yimura/YimMenu#3633]
### Describe the bug

These issues have been bothering me for a long time. After generating the vehicle, I can only use the machine gun in the vehicle. When using missiles, the missiles cannot be launched and explode like fireworks stuck in the launch well on my vehicle, but there is no damage. Now I cannot use any vehicles with missiles in GTAOL, not even my own RPG, and can only stay away from my vehicle. And these bugs only occur after I inject YimMenu. 

### Steps To Reproduce

Click on 'Vehicle' to generate a vehicle with missiles and launch them
Using tracking missiles or any explosives near personal vehicles

### Expected Behavior

fix them

### Logs

[cout.log](https://github.com/user-attachments/files/16796875/cout.log)

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xesdoog** [comment]
This is not a YimMenu issue. You're using [this script](https://github.com/YimMenu-Lua/Samurais-Scripts) with **'Missile Defense'** enabled. The feature has both a tooltip and a notification that explain to you what it does and warns you about this exact thing. If you want to fire missiles from or near your vehicle, just disable it.

**Comment by HD6630** [comment]
thank you very much!
