### ISSUE TITLE
[Bug]: Reaction settings to the crash of the game is not saved

### ISSUE THREAD

**Issue by opt8** [Yimura/YimMenu#3638]
### Describe the bug

the settings for this reaction resets with game start

### Steps To Reproduce

change reaction settings
close game
start game
reaction settings has been reset

### Expected Behavior

its saved

### Logs

-

### Store

Epic Games

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/master/src/core/settings.hpp#L199-L251

Reactions should already be serialized to disk. If someone else can confirm this behavior I'll look into it.

**Comment by lonelybud** [comment]
which reaction is not saved?

**Comment by gir489returns** [comment]
@lonelybud I got an e-mail notification you commented, but I can't see your post. break_game seemed to have been missing. I generated all of them using a RegEx pattern.

**Comment by lonelybud** [comment]
> @lonelybud I got an e-mail notification you commented, but I can't see your post. break_game seemed to have been missing. I generated all of them using a RegEx pattern.

yeah i deleted my comment bcz i thought it made no sense but you found one.

**Comment by gir489returns** [comment]
> > @lonelybud I got an e-mail notification you commented, but I can't see your post. break_game seemed to have been missing. I generated all of them using a RegEx pattern.
> 
> yeah i deleted my comment bcz i thought it made no sense but you found one.

I thought your comment was that you did find one so I went and looked.

**Comment by lonelybud** [comment]
@opt8 why you mentioned crash in the title?

**Comment by gir489returns** [comment]
> @opt8 why you mentioned crash in the title?

What the fuck are you talking about?

**Comment by gir489returns** [comment]
Oh, @lonelybud you have to remember, he's using the Russian version with my shitty translations. He's trying his best to understand what I wrote and tried to translate it back into English.
