### ISSUE TITLE
[请求]：如何用b11轰炸机取代战斗机？

### ISSUE THREAD

**Issue by Hawkeww** [Yimura/YimMenu#3653]
### Problem

Help, how do I replace a fighter in the Battle Team Generator with a b11 bomber? A team of B11s like this one, how can I replace the fighter, call for help,

### Solution

I really need this

### Reason

I really need this
![b645857807f3dee5d1d5ea0ebffd9760](https://github.com/user-attachments/assets/6a484503-0e19-45c0-88aa-8579771afae8)
![3b1c0d8b9a9fa870ed8e2c73b6678dc1](https://github.com/user-attachments/assets/48239678-0800-42d2-bce5-78687069f489)

**Comment by ghost** [comment]
I don´t think you can. The preset for this squad spawner includes the jets. if you want it to be B-11s you could code it yourself. No idea if that possible
