### ISSUE TITLE
[Bug]: not letting me join sessions

### ISSUE THREAD

**Issue by tinglefart445** [Yimura/YimMenu#3661]
### Describe the bug

when i try to join an online session it says "invalid assets" or "incompatible downloadable content"

### Steps To Reproduce

1. load the game with yimmenu
2. try to join a game
3. it says that (if i load yimmenu in the middle of an online game it works but then if i try to join another session it says that)

### Expected Behavior

well to let me join a session

### Logs

[cout.log](https://github.com/user-attachments/files/16871987/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by RKDeviancy** [comment]
Is your asset hash spoofer active so you can load custom DLC like graphic mods or model replacements online or something? If so, it might be that the asset hashes you have entered or copied are out of date

Whenever GTA last updated I had this issue because I needed to update the hashes in the hash spoofer.

That's the only idea I have so I hope that's the issue or someone else knows what else it could be

**Comment by tinglefart445** [comment]
whats that?

**Comment by tinglefart445** [comment]
> Is your asset hash spoofer active so you can load custom DLC like graphic mods or model replacements online or something? If so, it might be that the asset hashes you have entered or copied are out of date
> 
> Whenever GTA last updated I had this issue because I needed to update the hashes in the hash spoofer.
> 
> That's the only idea I have so I hope that's the issue or someone else knows what else it could be

whats that?

**Comment by RKDeviancy** [comment]
> whats that?

It's a thing you can turn on under Network -> Spoofing. After clicking on Spoofing, scroll down on the new menu that pops up all the way to the bottom. 

If you have Spoof Data Hashes and Spoof DLC Hashes on and you *don't* have any singleplayer mods, you should just disable it. If you have singleplayer mods on and dont want them online, you have to remove them before going online, but if you want to play online with them you'd use a combination of those Hash Spoofers and YimASI and the like.

I'm going to assume you probably aren't doing that if you didn't know what I was talking about though, so I don't think I'll be of much help. I hope someone else can help!

**Comment by tinglefart445** [comment]
> > whats that?
> 
> It's a thing you can turn on under Network -> Spoofing. After clicking on Spoofing, scroll down on the new menu that pops up all the way to the bottom.
> 
> If you have Spoof Data Hashes and Spoof DLC Hashes on and you _don't_ have any singleplayer mods, you should just disable it. If you have singleplayer mods on and dont want them online, you have to remove them before going online, but if you want to play online with them you'd use a combination of those Hash Spoofers and YimASI and the like.
> 
> I'm going to assume you probably aren't doing that if you didn't know what I was talking about though, so I don't think I'll be of much help. I hope someone else can help!

holy shit it worked thanks bro
