### ISSUE TITLE
[Improvement]: dlc vehicles showing up

### ISSUE THREAD

**Issue by iq1x** [Yimura/YimMenu#3666]
### Which feature

it seems that dlc cars dont show up when i inject the menu

### Reason

i cannot buy the vehicles i want while using the menu at the same time.

**Comment by xesdoog** [comment]
#3625

**Comment by gir489returns** [comment]
Lmao another victim of the Ultimate Menu cuck.

**Comment by RogueB4rcode** [comment]
yes u shuld erase the ultimate menu i alr try it and it works
