### ISSUE TITLE
[Bug]: Fatal Exception while gta loads

### ISSUE THREAD

**Issue by ciprinicu** [Yimura/YimMenu#3675]
### Describe the bug

I use auto inject from xenos, meaning the injector waits ~3000ms after detecting that gta started then injects.
The console prints error messages while gta is loading.

### Steps To Reproduce

Set xenos to the following settings
![image](https://github.com/user-attachments/assets/b653c51b-2a72-429d-a305-7def4b4e4b79)
Click inject then start gta

### Expected Behavior

No errors.

### Logs

[cout.txt](https://github.com/user-attachments/files/16923069/cout.txt)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I want to mention that I have the following scripts:
![image](https://github.com/user-attachments/assets/46594f2a-83da-49b2-9d12-e0026d20012b)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ciprinicu** [comment]
i tried injecting after gta loads me in a multiplayer session and I got no errors now, it may be the fact that I inject too early.

**Comment by Yimura** [comment]
Does the game crash? Because if it doesn’t you can just ignore these errors.

**Comment by RKDeviancy** [comment]
> Does the game crash? Because if it doesn’t you can just ignore these errors.

That's what I have been doing, because I started getting the same error as OP for the past week or so after one of the nightly uploads. It wasn't there a few weeks ago, but everything is still functional!

**Comment by gir489returns** [comment]
Do not unlink modules.
Do not erase PE headers.
Stop trying to be hack master-supreme doing all the extra cool stuff.

Just fucking inject the module and let us deal with the anti-cheat. Fucking kids, I swear to god.

**Comment by ciprinicu** [comment]
> Do not unlink modules. Do not erase PE headers. Stop trying to be hack master-supreme doing all the extra cool stuff.
> 
> Just fucking inject the module and let us deal with the anti-cheat. Fucking kids, I swear to god.

sorry i may have turned them on while using another menu, im 19 years old, just not that experienced with injectors xd

**Comment by ciprinicu** [comment]
> Does the game crash? Because if it doesn’t you can just ignore these errors.

the game does not crash, no worries!

**Comment by Yimura** [comment]
> the game does not crash, no worries!

Injecting early does give errors, you can safely ignore them normally. Otherwise just inject in Single Player, our suggestion is to not inject while already in online to prevent potential detections from the anti-cheat while YimMenu is still busy disabling it.

**Comment by RKDeviancy** [comment]
> Injecting early does give errors, you can safely ignore them normally. Otherwise just inject in Single Player, our suggestion is to not inject while already in online to prevent potential detections from the anti-cheat while YimMenu is still busy disabling it.

In case its helpful to know: I still get this error while injecting in story-mode, and it did not happen a week or so ago. It started after I updated to the most recent Nightly at the time, and is still present on the most recent Nightly. I don't remember which Nightly introduced this error for me, otherwise I'd give you the exact Nightly.

Everything is still functional though, so I have been basically ignoring the error.

**Comment by Yimura** [comment]
Could you give a date of when this exactly started to happen or give a commit hash perhaps?

**Comment by RKDeviancy** [comment]
> Could you give a date of when this exactly started to happen or give a commit hash perhaps?

I first saw it after updating to one of the nightly's towards the end of August. I don't recall the exact nightly but I think it was one of the nightly's after the August 23rd commit (e61dc44) that I noticed the error start to occur. I hope that's useful

**Comment by ShinyWasabi** [comment]
From what I see in the log, one of the scripts you're using tries to write to / read globals at a moment script globals haven't been populated yet (when scripts not started).

**Comment by RKDeviancy** [comment]
> From what I see in the log, one of the scripts you're using tries to write to / read globals at a moment script globals haven't been populated yet (when scripts not started).

Might be the same for me then, I'm guessing. When I have time later I'll test to see which script it is. Thank you for the info!

Edit: I tried without any scripts and it still happened when injecting in story mode. However earlier in the day the error did not occur *with* my scripts (Extras-Addon and Samurai Scripts 1.2.5) despite injecting in story mode so I am unsure what that tells me
