### ISSUE TITLE
[Bug]: huge error log in console

### ISSUE THREAD

**Issue by fakej1nx1e** [Yimura/YimMenu#3677]
### Describe the bug

Everytime I start GTA and injecting Yim with Xenos, it will everytime give me a big error.

### Steps To Reproduce

1. Start GTA
2. Start your Injector
3. Inject Yim with GTA
4. Tadaaaaaa.... error

### Expected Behavior

I expected it would start without any huge big errors.

### Logs

[cout.log](https://github.com/user-attachments/files/16937180/cout.log)

### Screenshots / Video

---

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
>Xenos.

Let me guess, you got it set to manually map with destroy the PE headers, and delink from the PEB and hack the matrix all selected on because you're the hack master supreme 420XXX?

**Comment by fakej1nx1e** [comment]
> >Xenos.
> 
> 
> 
> Let me guess, you got it set to manually map with destroy the PE headers, and delink from the PEB and hack the matrix all selected on because you're the hack master supreme 420XXX?

Idk what you talking about😭 I use Xenos as usual, quite normal and has never had any problems before. Idk what you talking about💀

**Comment by fakej1nx1e** [comment]
> > Xenos.
> 
> Let me guess, you got it set to manually map with destroy the PE headers, and delink from the PEB and hack the matrix all selected on because you're the hack master supreme 420XXX?

Just solved the problem. I just added a Inject Delay and it works now. But never used manually map with destroy the PE headers😭
