### ISSUE TITLE
[Bug]: Got crashed by a p2c who kept spamming their crashes

### ISSUE THREAD

**Issue by HowyDarko** [Yimura/YimMenu#3679]
### Describe the bug

As the title says.. got crashed by this guy who was griefing the lobby in god mod.. after trolling him a bit, he tried to tp me to a warehouse and clear my ped tasks? after non of that worked out he started spamming his crashes which ultimately resulted in me crashing.
Also note that few moments before i crashed i enabled no clip.. not sure if it has to do with anything.
Also i have my crash reaction set to kick.. so with every crash he sent he got a desync kick from me i believe.. since none of us was host.

### Steps To Reproduce

Hurt PinaLacroosa (227743404) feelings

### Expected Behavior

Handling Multiple crash attempts at the same time? 

### Logs

[09-11-2024-20-03-52_cout.zip](https://github.com/user-attachments/files/16970076/09-11-2024-20-03-52_cout.zip)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
There's no crash in the log captured here, what do you want us to do with this?

**Comment by HowyDarko** [comment]
@gir489returns what do you mean there was no crash captured in the log? scroll to the bottom
