### ISSUE TITLE
[Bug]: Start Ls Customs  doesn't work

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#368]
### Describe the bug

Start Ls Customs  doesn't work

### Steps To Reproduce

1. Go to Vehicle
2. Click LS Customs
3. Press "Start LS Customs"

### Expected Behavior

Remote LS Customs should be triggered

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by TheGreenBandit** [comment]
@Yimura take a look on these old issues, a lot can be closed or solved, like this one can definitely be closed as its not a problem anymore
