### ISSUE TITLE
[Bug]: Not able to join public sessions while menu is injected

### ISSUE THREAD

**Issue by SahilBulatoo** [Yimura/YimMenu#3682]
### Describe the bug

When ever i join a public session whether through the menu or normally in game it kicks me to a solo session. It first load in a public session with players but i get time out then it try to join another public session but time out again. In the end it either put me in a solo session or says cant join gta online.  

### Steps To Reproduce

1.Launch gta
2.Inject yimmenu
3.Join online session
4. Check the player list on mod menu
5. It loads for a bit then try to join another session
6. In the end it joins solo

### Expected Behavior

Should have join a public session normally and not time out to a solo session

### Logs

[cout.log](https://github.com/user-attachments/files/16991250/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by D-Borkan** [comment]
try delete YimMenu folder in %appdata% then inject again

**Comment by SahilBulatoo** [comment]
yeah deleting the yimmenu folder worked perfectly. Idk  why i never thought of that. Thanks
