### ISSUE TITLE
[Request]: Linux inject

### ISSUE THREAD

**Issue by Flopperpev** [Yimura/YimMenu#3689]
### Problem

Cant launch on Linux. Can you add Linux injector, or a way to eject it on the linux?

### Solution

Injector on linux, launch with terminal or app, something else, just a way to launch mod menu on the linux.

### Reason

Because I cant launch it on Linux.

**Comment by gir489returns** [comment]
![no](https://github.com/user-attachments/assets/5a746549-5025-4746-a5bf-d8240bf1c36b)

**Comment by Yimura** [comment]
Please see #334 for more information. We do not offer an official injection method for Linux.
