### ISSUE TITLE
[Bug]: BattlEye anti-cheat detection added to GTAOL

### ISSUE THREAD

**Issue by Baugle** [Yimura/YimMenu#3690]
### Describe the bug

**BattlEye** anti-cheat detection added to GTAOL,Yimmenu's injections are highly likely to be detected.  
It could be extremely **unsafe** right now.

### Steps To Reproduce

When opening GTA5, BattlEye updates and pops up a MessageBox

### Expected Behavior

Hopefully changes can be made for this update

### Logs

<none>

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
All we can do is warn users, don’t unnecessarily go creating a panic. We don’t know if it’s detected currently but we can’t guarantee that it won’t be detected in the near future (ie. through injection methods used and other things that were previously fine to do).

**Comment by SLGMSEppe** [comment]
> All we can do is warn users, don’t unnecessarily go creating a panic. We don’t know if it’s detected currently but we can’t guarantee that it won’t be detected in the near future (ie. through injection methods used and other things that were previously fine to do).

they will prob go hwid bans they said they will go kernel

**Comment by Eedge-e** [comment]
Will the Majority of Mod Menus retire like you Yimura or still planning to continue your project? Bypassing the anticheat of Battleye Skeleton could be a more work to do.

**Comment by ghost** [comment]
tried in gta story mode, cant inject with xenos

**Comment by Baugle** [comment]
Thank you for your reply, I will test if it can be detected.

> tried in gta story mode, cant inject with xenos

You need an injector that can bypass BattlEye, Xenos is detected, but the good thing is you inject offline!My teacher recommended this:https://github.com/Neijwiert/Feeder

**Comment by Baugle** [comment]
> tried in gta story mode, cant inject with xenos

You need an injector that can bypass BattlEye, Xenos is detected, but the good thing is you inject offline!My teacher recommended this:https://github.com/Neijwiert/Feeder

**Comment by lonelybud** [comment]
you can check if its installed in rockstar launcher settings [image](https://github.com/user-attachments/assets/731b7d7f-a3ca-4999-bc56-e518390af55d)

**Comment by Nzii3** [comment]
> you can check if its installed in rockstar launcher settings [image](https://github.com/user-attachments/assets/731b7d7f-a3ca-4999-bc56-e518390af55d)
> 
> 

Is that check mark required to play GTA Online?

**Comment by ghost** [comment]
> > you can check if its installed in rockstar launcher settings [image](https://github.com/user-attachments/assets/731b7d7f-a3ca-4999-bc56-e518390af55d)
> 
> Is that check mark required to play GTA Online?

It is

**Comment by Naruto-Dattebayo** [comment]
So injecting the current build of YimMenu will result in account ban or smth? there would be an injector which bypasses BE

**Comment by Yimura** [comment]
> So injecting the current build of YimMenu will result in account ban or smth? there would be an injector which bypasses BE

You can't even inject so there _shouldn't_ be a ban risk, though I wouldn't push it.
And until #3691 is merged the game/YimMenu will just crash if you're injecting it.

**Comment by L7NEG** [comment]
So basically we have to wait for a proper working 💪 yimmenu for online (for now it is working in sp only) keep it up

**Comment by CSY0N** [comment]
that's right @L7NEG now we need wait that @Yimura Updated he's Menu

**Comment by ViVi-Phantom** [comment]
Bro the BE AC is relay easy to bypass if you want bypass methout + src .
Dm me on Discord seifen_wasser

**Comment by ViVi-Phantom** [comment]
Yo if somone needs a Inj use the inj by this paster "paysonism/Payson-Injector" it works

**Comment by uint124** [comment]
In order for this menu to work you need to make a kernel injector, probably the end of this project since most of the people using it played online.

**Comment by Nzii3** [comment]
@Yimura is it even possible to get Yimmenu working again for online again? or is this the end of the project? (and probably the end for mod menus)

**Comment by maybegreat48** [comment]
This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on

**Comment by Nzii3** [comment]
> This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on

Ok. Idk anything about the back end of game hacking, but this menu has allowed me to help my friends earn money by protecting them from griefers, rage hackers, and rig poker for them if they need quick cash. This menu is has positively impacted my experience to just remove all the wasted time so we can all have a great time and have (game) protection (pause). I hope you guys will be able to overcome this bump in the road to being Yimmenu back to gtao.

**Comment by Deadlineem** [comment]
> This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on

I believe in the GTA modding community entirely.  R* should give up when we bypass this.

**Comment by ghost** [comment]
there's a way around everything, just need be patient and let the smart people figure it out :)

**Comment by tenko23** [comment]
This just started happening within the last 24 hours?

EDIT:  Just saw the patch notes.

**Comment by Yimura** [comment]
> So injecting the current build of YimMenu will result in account ban or smth? there would be an injector which bypasses BE

You can use it offline just fine, for online you'll need an additional bypass.

**Comment by juhannnnnn** [comment]
> > So injecting the current build of YimMenu will result in account ban or smth? there would be an injector which bypasses BE
> 
> You can use it offline just fine, for online you'll need an additional bypass.

How is this additional bypass for online to be configured?

**Comment by Yimura** [comment]
> How is this additional bypass for online to be configured?

Look on Google for BattleEye bypasses/injectors, and try not to get a virus in the meantime. The YimMenu team is currently not providing a bypass themselves.

**Comment by juhannnnnn** [comment]
> > How is this additional bypass for online to be configured?
> 
> Look on Google for BattleEye bypasses/injectors, and try not to get a virus in the meantime. The YimMenu team is currently not providing a bypass themselves.

oh ok...

**Comment by TedBig** [comment]
> > 这个额外的在线旁路该如何配置？
> 
> 在 Google 上查找 BattleEye 绕过/注入器，同时尽量不要感染病毒。YimMenu 团队目前不提供绕过方法。

will we have a official bypasser from yim in the future?

**Comment by KernelFrog** [comment]
> will we have a official bypasser from yim in the future?

Sure.  Just as soon as you create the pull request.

**Comment by L7NEG** [comment]
> This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on

As expected I know modding community never dies that's will be A W better than Paying a 70$ for a paid one fr

**Comment by L7NEG** [comment]
> > This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on
> 
> I believe in the GTA modding community entirely. R* should give up when we bypass this.

True facts

**Comment by L7NEG** [comment]
> there's a way around everything, just need be patient and let the smart people figure it out :)

Fr

**Comment by L7NEG** [comment]
It is not the end of the world guys

**Comment by TheDuke203** [comment]
> > This project will continue to exist, BattlEye or not. We (the GTA modding community, not just YimMenu) need some time to understand what's going on
> 
> I believe in the GTA modding community entirely. R* should give up when we bypass this.

Problem is, it's not a rockstar developed anti-cheat
It's off the shelf product they buy and implemented into their game.
_Speculation_
Now it'll always be an arms race to determine what gets detected and what doesn't.
The way it works is, if it detects you it won't insta ban but use you to gather info on what you do.
You can read about it here: https://www.battleye.com/about/
The big thing about it is this:
**BattlEye thereby does its entire job independently without requiring any input from the developer’s side.**

**Comment by YimMenuTheBest** [comment]
Stand and other paid mod menus are back in Online Mode by disabling BattlEye.

It's just a matter of waiting for YimMenu to come back like the greats.

**Comment by YimMenuTheBest** [comment]
I tried co-loading with Stand but i got a crash due to errors from several outdated pointers, it remains to wait.

**Comment by rafkak** [comment]
ye i tried to load yim with stand aswell and i got instant crash.i guess we wait

**Comment by mikedrugs** [comment]
> Stand and other paid mod menus are back in Online Mode by disabling BattlEye.
> 
> It's just a matter of waiting for YimMenu to come back like the greats.

I'm pretty sure rockstar won't just let menus to disable battleye, expect a hotfix soon

**Comment by HowyDarko** [comment]
> It's just a matter of waiting for YimMenu to come back like the greats.

Yim is probably in a difficult position.. where if they figure out a bypass, they gonna have to open source it, which is not ideal for a bypass

**Comment by YimMenuTheBest** [comment]
Actually many of those talking about a bypass are making it very complicated, from sainan's words, they seem to have bypassed the BattlEye screen when entering online when it is disabled, so it is an excellent way and very optimized vision, I am sure that a bypass will not be necessary as in Fornite or other games.

**Comment by TheDuke203** [comment]
> Actually many of those talking about a bypass are making it very complicated, from sainan's words, they seem to have bypassed the BattlEye screen when entering online when it is disabled, so it is an excellent way and very optimized vision, I am sure that a bypass will not be necessary as in Fornite or other games.

I think this is just the solution by downgrading the game version to an earlier version?
This won't be a workable solution as you can only play with people on that game version it won't let you play with anyone with running the battle eye version.

**Comment by YimMenuTheBest** [comment]
> > Actually many of those talking about a bypass are making it very complicated, from sainan's words, they seem to have bypassed the BattlEye screen when entering online when it is disabled, so it is an excellent way and very optimized vision, I am sure that a bypass will not be necessary as in Fornite or other games.
> 
> I think this is just the solution by downgrading the game version to an earlier version? This won't be a workable solution as you can only play with people on that game version it won't let you play with anyone with running the battle eye version.

No, you are literally using code to bypass the BE screen when trying to go from story mode to online without BattlEye enabled in the RGL, I insist that many of you are making it difficult for yourselves.

**Comment by rafkak** [comment]
i had my game downgraded and i used yim it worked but it was boring since there were less people but ye its a solution

**Comment by HowyDarko** [comment]
>from sainan's words, they seem to have bypassed the BattlEye screen when entering online when it is disabled

Yes i know, @gir489returns called it when the update first dropped. https://github.com/YimMenu/YimMenu/pull/3691#issuecomment-2356211705
My point however remains.

**Comment by TheDuke203** [comment]
> > > Actually many of those talking about a bypass are making it very complicated, from sainan's words, they seem to have bypassed the BattlEye screen when entering online when it is disabled, so it is an excellent way and very optimized vision, I am sure that a bypass will not be necessary as in Fornite or other games.
> > 
> > 
> > I think this is just the solution by downgrading the game version to an earlier version? This won't be a workable solution as you can only play with people on that game version it won't let you play with anyone with running the battle eye version.
> 
> No, you are literally using code to bypass the BE screen when trying to go from story mode to online without BattlEye enabled in the RGL, I insist that many of you are making it difficult for yourselves.

Hm, this surprises me is there just a single check for battleeye activation? They are sure it's not running silently? It maybe collecting data for upcoming banwave
I'm surprised they haven't added many continous checks.
But I guess if you can pass once you can pass again.

**Comment by vuk-beta** [comment]
Can anyone explain how to inject Yim by downgrading, or any other method currently?

**Comment by opt8** [comment]
in the announcement of another mod menu, they wrote that you can disable this shit with the usual game launch flag in rockstar launcher, lol?
**-nobattleye**
what is that? did they really add the option to disable it?

**Comment by tenko23** [comment]
> in the announcement of another mod menu, they wrote that you can disable this shit with the usual game launch flag in rockstar launcher, lol? **-nobattleye** what is that? did they really add the option to disable it?

That's what I read too -- so that third party launchers can continue to function supposedly.

**Comment by HowyDarko** [comment]
S+ tier work, good job everybody!

**Comment by bukizzz** [comment]
Tested, works online flawlessly, thank you

**Comment by Nzii3** [comment]
> > It's just a matter of waiting for YimMenu to come back like the greats.
> 
> 
> 
> Yim is probably in a difficult position.. where if they figure out a bypass, they gonna have to open source it, which is not ideal for a bypass

Why would they have to open source it? It's been a trustworthy menu hence why people want it "back" so

EDIT: damn I have work the the day it was fixed 😭

**Comment by whosblue** [comment]
So... how do I use the menu now that's it been fixed?

**Comment by HowyDarko** [comment]
> So... how do I use the menu now that's it been fixed?

https://github.com/YimMenu/YimMenu/pull/3697

**Comment by tenko23** [comment]
Just to clarify (to be safe), it's mandatory to delete the local settings file?

**Comment by maybegreat48** [comment]
No, but the game generally crashes if you don't

**Comment by Aholicknight** [comment]
What injector is everyone using to bypass battleeye?

**Comment by HowyDarko** [comment]
@maybegreat48 hey, sorry i don't wanna open a new issue but why can't i join online even tho i followed all the instructions in https://github.com/YimMenu/YimMenu/pull/3697 ?.. I tried playing without injecting the menu and with BE enabled and i got into a lobby just fine. 
i have the game on steam btw
![Screenshot (1253)](https://github.com/user-attachments/assets/150c814d-9157-4aa3-b20e-baf315333020)

**Comment by Mr-X-GTA** [comment]
Deleting your settings file is necessary because the array size of game_data_hash changed and YimMenu does not handle this correctly (need to fix this later).


> What injector is everyone using to bypass battleeye?

You don't need a special injector, just use the same one as before

**Comment by Mr-X-GTA** [comment]
> @maybegreat48 hey, sorry i don't wanna open a new issue but why can't i join online even tho i followed all the instructions in #3697 ?.. I tried playing without injecting the menu and with BE enabled and i got into a lobby just fine.
> i have the game on steam btw

You have to inject right after starting GTA

**Comment by HowyDarko** [comment]
> You have to inject right after starting GTA

Ohh.. So i don't have to wait until it loads into single player?
 
-Update: It worked, thanks man!

**Comment by Beginner555989** [comment]
can we use same scripts and make money or heist editor or is risky now?

**Comment by Aholicknight** [comment]
> > What injector is everyone using to bypass battleeye?
> 
> 
> 
> You don't need a special injector, just use the same one as before

@Mr-X-GTA I am using Xenos and it's crashing as soon as I inject at the main menu, and yes I disabled battleeye in the rockstar launcher.

**Comment by HowyDarko** [comment]
> I am using Xenos and it's crashing as soon as I inject at the main menu, and yes I disabled battleeye in the rockstar launcher.

Delete "settings.json" from C:\Users\User\AppData\Roaming\YimMenu

**Comment by L7NEG** [comment]
> @maybegreat48 hey, sorry i don't wanna open a new issue but why can't i join online even tho i followed all the instructions in #3697 ?.. I tried playing without injecting the menu and with BE enabled and i got into a lobby just fine. i have the game on steam btw ![Screenshot (1253)](https://private-user-images.githubusercontent.com/129800100/368791316-150c814d-9157-4aa3-b20e-baf315333020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDc3ODgsIm5iZiI6MTcyNjcwNzQ4OCwicGF0aCI6Ii8xMjk4MDAxMDAvMzY4NzkxMzE2LTE1MGM4MTRkLTkxNTctNGFhMy1iMjBlLWJhZjMxNTMzMzAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMDU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzM0MzFlOGZhNzY3ZTY0MjZiYTYwNTAwMjlkNjMwNGQyMWNhNGEwYjZjYTEwZTU5N2U0ODNjNjUxNDE2NGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y_lTvOEN5OWOBZ6ncO1XuEZ7v2zp5tviIXXuQ6ngKzg)

1st open your game and just stay at the main window dont choose online or offline (make sure you have disabled BE toggle)
then just use any injector ex xenos injector 
finally just start yimmenu and you are done you can either load into story mode or online mode 

fr W yimura and mrxgta ik it is not a perm bypass but yee ac disabled in less than 3 days is wild 

![Screenshot 2024-09-19 035033](https://github.com/user-attachments/assets/f79604ef-16d2-4778-8c6a-7e07a9524035)

**Comment by Aholicknight** [comment]
> > I am using Xenos and it's crashing as soon as I inject at the main menu, and yes I disabled battleeye in the rockstar launcher.
> 
> 
> 
> Delete "settings.json" from C:\Users\User\AppData\Roaming\YimMenu

@HowyDarko yup this works, thanks!

**Comment by HowyDarko** [comment]
> 1st open your game and just stay at the main window dont choose online or offline (make sure you have disabled BE toggle) then just use any injector ex xenos injector finally just start yimmenu and you are done you can either load into story mode or online mode

yeah i got it to work.. thanks for the help anyways

**Comment by L7NEG** [comment]
> > > I am using Xenos and it's crashing as soon as I inject at the main menu, and yes I disabled battleeye in the rockstar launcher.
> > 
> > 
> > Delete "settings.json" from C:\Users\User\AppData\Roaming\YimMenu
> 
> @HowyDarko yup this works, thanks!

you are welcome bro enjoy <3 happy modding

**Comment by L7NEG** [comment]
> > 1st open your game and just stay at the main window dont choose online or offline (make sure you have disabled BE toggle) then just use any injector ex xenos injector finally just start yimmenu and you are done you can either load into story mode or online mode
> 
> yeah i got it to work.. thanks for the help anyways

you are welcome enjoy and happy modding <3

**Comment by L7NEG** [comment]
> can we use same scripts and make money or heist editor or is risky now?

yes you can nothing really changed

**Comment by L7NEG** [comment]
> > @maybegreat48 hey, sorry i don't wanna open a new issue but why can't i join online even tho i followed all the instructions in #3697 ?.. I tried playing without injecting the menu and with BE enabled and i got into a lobby just fine.
> > i have the game on steam btw
> 
> You have to inject right after starting GTA

for me just wait into main screen without choosing offline or online and just inject in it and done ✅ + W man keep it up

**Comment by Beginner555989** [comment]
> > can we use same scripts and make money or heist editor or is risky now?
> 
> yes you can nothing really changed

thanks habibi i love Egypt

**Comment by L7NEG** [comment]
> > > can we use same scripts and make money or heist editor or is risky now?
> > 
> > 
> > yes you can nothing really changed
> 
> thanks habibi i love Egypt

you are welcome (qlby = my ❤️)

**Comment by tenko23** [comment]
> > > > can we use same scripts and make money or heist editor or is risky now?
> > > 
> > > 
> > > yes you can nothing really changed
> > 
> > 
> > thanks habibi i love Egypt
> 
> you are welcome (qlby = my ❤️)

❤️❤️ from the U.S.!

**Comment by bastuFTG** [comment]
idk if this has anything with Yimmenu or if its just Gta it self, but After i followed all the steps in this Issue tab to launch gta with yimmenu Everyone Randomly leaves my session and doesnt matter how many different seasons i join still presist have anyone else experinced that?

**Comment by Beginner555989** [comment]
> idk if this has anything with Yimmenu or if its just Gta it self, but After i followed all the steps in this Issue tab to launch gta with yimmenu Everyone Randomly leaves my session and doesnt matter how many different seasons i join still presist have anyone else experinced that?

same to me

**Comment by Mr-X-GTA** [comment]
I haven't experienced this yet, but do you happen to know if they get this?
![image](https://github.com/user-attachments/assets/3ea9e94d-61dd-4c71-9f6f-d1e58b5e6efe)

**Comment by Beginner555989** [comment]
> I haven't experienced this yet, but do you happen to know if they get this? ![image](https://private-user-images.githubusercontent.com/110748953/368811249-3ea9e94d-61dd-4c71-9f6f-d1e58b5e6efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTA4NDMsIm5iZiI6MTcyNjcxMDU0MywicGF0aCI6Ii8xMTA3NDg5NTMvMzY4ODExMjQ5LTNlYTllOTRkLTYxZGQtNGM3MS05ZjZmLWQxZTU4YjVlNmVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMTQ5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTI1MTM1NDQzYjFhMzJjNjQ0M2FiNDMxMmNmZDhkNzU5MzAwOTI1Y2Y5ODA2YjQyOTllYTc3NzdlMTI2M2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmTc02mwpEoPg2iHmyK3HNm74eNuu0mnHfCmruv9AwM)

if ure the Host this will not happend

**Comment by HowyDarko** [comment]
> I haven't experienced this yet, but do you happen to know if they get this?

yup.. my non-modder friend been getting disconnected to that error too when he joins me when i'm host 
![image272](https://github.com/user-attachments/assets/34685c39-d183-46ea-8eca-be5cef454e1d)

**Comment by HowyDarko** [comment]
@gir489returns why the laughing?

**Comment by tenko23** [comment]
It seems like there are some internal checks that are happening -- that are under the hood and unseen 😬 .....

**Comment by bastuFTG** [comment]
> > idk if this has anything with Yimmenu or if its just Gta it self, but After i followed all the steps in this Issue tab to launch gta with yimmenu Everyone Randomly leaves my session and doesnt matter how many different seasons i join still presist have anyone else experinced that?
> 
> same to me

Well then im not alone with this issue damn hoped i was the only one then it would prob me who fuked smth up

**Comment by tenko23** [comment]
> > > idk if this has anything with Yimmenu or if its just Gta it self, but After i followed all the steps in this Issue tab to launch gta with yimmenu Everyone Randomly leaves my session and doesnt matter how many different seasons i join still presist have anyone else experinced that?
> > 
> > 
> > same to me
> 
> Well then im not alone with this issue damn hoped i was the only one then it would prob me who fuked smth up

Wild guess is that GTAV is internally checking if BattlEye is enabled on the host or not; if not, one becomes untrusted... just a guess though.

**Comment by Mr-X-GTA** [comment]
They enabled this now, legitimate players disconnect from the session after 5 minutes if the host does not have BE running

**Comment by So7lb** [comment]
So guys i just did what yall did but somehow when i inject the settings file comes back with a note file named cout clearing the error and the game crashes. 
it looks like this 
![Uploading IMG_0295.jpeg…]()
Any Suggestion ?

**Comment by Aholicknight** [comment]
> So guys i just did what yall did but somehow when i inject the settings file comes back with a note file named cout clearing the error and the game crashes. 
> 
> it looks like this 
> 
> ![Uploading IMG_0295.jpeg…]()
> 
> Any Suggestion ?

@So7lb we can't see your image.

**Comment by terminaate** [comment]
> They enabled this now, legitimate players disconnect from the session after 5 minutes if the host does not have BE running

will there be fix for this?

**Comment by Aholicknight** [comment]
> > They enabled this now, legitimate players disconnect from the session after 5 minutes if the host does not have BE running
> 
> will there be fix for this?

@terminaate that's server-side so no

**Comment by Cqseur** [comment]
Using no clip seems to trigger battleeye and get you desync kicked by the game

**Comment by tenko23** [comment]
They sure know how to ruin a good game 😩 .....

**Comment by HowyDarko** [comment]
> Using no clip seems to trigger battleeye and get you desync kicked by the game

How would it trigger it when it's disabled in the first place?. nope, you're probably getting kicked by the host for not having BE enabled

**Comment by Cqseur** [comment]
> > Using no clip seems to trigger battleeye and get you desync kicked by the game
> 
> How would it trigger it when it's disabled in the first place?. nope, you're probably getting kicked by the host for not having BE enabled

i need to make more testings (the reason i deleted the reply), but the two times i used no clips i've been kicked literally 1 second later. quite odd

**Comment by tenko23** [comment]
> > > They enabled this now, legitimate players disconnect from the session after 5 minutes if the host does not have BE running
> > 
> > 
> > will there be fix for this?
> 
> @terminaate that's server-side so no

If the server is reaching out to the host-client to see if BE is running, then all the host-client would need to do is to send a spoof back to the server, telling it that BE is running when it isn't... am I right on that?  Would need some reverse engineering if the case.....

(alternately, the joined clients' BE is checking with the host-client to see if BE is running via the server... the same could apply)

**Comment by juhannnnnn** [comment]
i think force host option should be disabled for now as this is the likely reason why all players get removed from session after sometime.

**Comment by lonelybud** [comment]
> I haven't experienced this yet, but do you happen to know if they get this?

is it mandatory to be the host to use the menu online?

**Comment by juhannnnnn** [comment]
> > I haven't experienced this yet, but do you happen to know if they get this?
> 
> is it mandatory to be the host to use the menu online?

as far as i have seen yes...

**Comment by L7NEG** [comment]
So far I'm just playing in invite only session it works like a charm

**Comment by TwystedMind** [comment]
> So far I'm just playing in invite only session it works like a charm

I had to install a second update since the original BE update on 09/17.  And this is what I'm experiencing:

 - I added the -nobattleye argument in Steam
 - I'm successfully able to inject Yim using Xenos upon game launch.

However, the game does not hit the landing screen where I'm able to choose between Online and Story Mode, so it just launches straight into Story Mode.  I've changed my launch option in Steam to go directly into Online, regardless, it gives me the "Online is unavailable, please return to GTA V" because my SC is logged in as Offline Mode since BE is disabled.

Is this due to the recent update (that happened within the last couple of hours), or am I doing something incorrect?  I'm responding directly to you since you're reporting that you're able to still play in Invite Only within the last hour.

**Comment by L7NEG** [comment]
> > So far I'm just playing in invite only session it works like a charm
> 
> I had to install a second update since the original BE update on 09/17. And this is what I'm experiencing:
> 
> * I added the -nobattleye argument in Steam
> * I'm successfully able to inject Yim using Xenos upon game launch.
> 
> However, the game does not hit the landing screen where I'm able to choose between Online and Story Mode, so it just launches straight into Story Mode. I've changed my launch option in Steam to go directly into Online, regardless, it gives me the "Online is unavailable, please return to GTA V" because my SC is logged in as Offline Mode since BE is disabled.
> 
> Is this due to the recent update (that happened within the last couple of hours), or am I doing something incorrect? I'm responding directly to you since you're reporting that you're able to still play in Invite Only within the last hour.

Simple fix I think in steam there is an option to not make the game auto launch in either story or online

**Comment by L7NEG** [comment]
> > So far I'm just playing in invite only session it works like a charm
> 
> I had to install a second update since the original BE update on 09/17. And this is what I'm experiencing:
> 
> * I added the -nobattleye argument in Steam
> * I'm successfully able to inject Yim using Xenos upon game launch.
> 
> However, the game does not hit the landing screen where I'm able to choose between Online and Story Mode, so it just launches straight into Story Mode. I've changed my launch option in Steam to go directly into Online, regardless, it gives me the "Online is unavailable, please return to GTA V" because my SC is logged in as Offline Mode since BE is disabled.
> 
> Is this due to the recent update (that happened within the last couple of hours), or am I doing something incorrect? I'm responding directly to you since you're reporting that you're able to still play in Invite Only within the last hour.

![Screenshot_20240919-130910_YouTube](https://github.com/user-attachments/assets/1e3f0835-4288-4dbb-bd9f-85b9a1d19fd7)

**Comment by L7NEG** [comment]
Just enable landing page (it is the main choose window of online or story mode)

**Comment by TwystedMind** [comment]
> Simple fix I think in steam there is an option to not make the game auto launch in either story or online 

Thank you for getting back to me!  I'll see if I can modify it from the Pause Menu.  Normally my game goes to the landing page each time, but it's no longer doing that.  I did change the setting in Steam to have it go directly into Online, but it ends up giving the "Online is unavailable right now" error, then forces me back to Story.

I did notice there are a lot of reports on DownDetector for GTA right now, so that may be the issue for me.  I'll try it again in a few hours and see how it goes.

Thank you again!

**Comment by L7NEG** [comment]
> > Simple fix I think in steam there is an option to not make the game auto launch in either story or online
> 
> Thank you for getting back to me! I'll see if I can modify it from the Pause Menu. Normally my game goes to the landing page each time, but it's no longer doing that. I did change the setting in Steam to have it go directly into Online, but it ends up giving the "Online is unavailable right now" error, then forces me back to Story.
> 
> I did notice there are a lot of reports on DownDetector for GTA right now, so that may be the issue for me. I'll try it again in a few hours and see how it goes.
> 
> Thank you again!

You are welcome bro ❤

**Comment by divytube** [comment]
So not its like if you have Battleye disabled they are not letting you sign in on R* server, they boot you straight to Story Mode, you can only boot to landing page if you have Battle eye enabled 🤷🏻

**Comment by YimMenuTheBest** [comment]
I think Stand is also experiencing the kicks of all players in your session, apparently there is still no solution for that yet, is there?

Maybe with PinkEye, which is the injector that allows you to use Stand with Battleye activated and play with other players without any problems, that's the way to start...

Or reverse engineering and send a false positive to the 5 minute scan to know if you have battleye activated and not leave you alone in a session.
