### ISSUE TITLE
[Bug]: New GTA5 Version does not work

### ISSUE THREAD

**Issue by JAaHab** [Yimura/YimMenu#3694]
### Describe the bug

So when i want to play online/story with BATTLE EYE i cant inject it, **but** if i disable it in RL i can inject but YIMMENU says that it is version for previous version 

(1. 0.3323.0 on Rockstar Launcher)

### Steps To Reproduce

1. Disable Battle eye in rockstar launcher 2. Start Granfd Theft Auto V  3. Inject it using[XENOS INJECTOR](https://github.com/DarthTon/Xenos) 4. Error 

### Expected Behavior

That menu will successfully start.

### Logs

[cout.log](https://github.com/user-attachments/files/17044731/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [ ] I've tested this without co-loading anything.

**Comment by Mr-X-GTA** [comment]
https://github.com/YimMenu/YimMenu/releases/tag/nightly
