### ISSUE TITLE
[Bug]: I cant inject errorcode: "Failed to inject image 0xC0000022"

### ISSUE THREAD

**Issue by elciiBTD6** [Yimura/YimMenu#3695]
### Describe the bug

i use Xenos to try to inject the menu, i put the menu in xenosX64 then i select the current gta process, press inject but then it gives me the error code: "Failed to inject image 0xC0000022".
how do i fix this? i have the new dll + i redownloaded Xenos already

### Steps To Reproduce

1. Open Xenos64.exe
2. Select the current GTA5.exe Process
3. Insert the dll into Xenos64.exe
4. Inject the dll into GTA5.exe
5. Get The Error

### Expected Behavior

it should just inject but it doesn't

### Logs

None

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by V1RU513N** [comment]
https://github.com/YimMenu/YimMenu/issues/3690
