### ISSUE TITLE
[Request]: BigBaseV1 DirectX Script System

### ISSUE THREAD

**Issue by Killer4563782** [Yimura/YimMenu#371]
### Problem

X

### Solution

a way to add a ImGui/DX Script via Scriptmanager what loads the window

### Reason

to make it easier to add a DX window/script and also make it toggleable

### Additional context

X

**Comment by Yimura** [comment]
BBv1's system will not be copied but I have a different idea on how to do this.

**Comment by Killer4563782** [comment]
I know I didn't think you were going to do that either but just so you have some kind of idea
