### ISSUE TITLE
[Request]: Clean JSON serialization & deserialization

### ISSUE THREAD

**Issue by DaniTRDev** [Yimura/YimMenu#374]
### Problem

The current implementation of "from_json" & "to_json" methods inside settings are not the best option at all.

### Solution

Instead of manually declaring those functions it would be better to use 

`NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Class, members, ...)` for structs (or classes that only contains public members)
`NLOHMANN_DEFINE_TYPE_INTRUSIVE(Class, members, ...)` for classes (or structs that contains private members)

### Reason

Code will be simplified and it will be easier to read and understand.

### Additional context

More info: [official nlohman's guide to these macros](https://github.com/nlohmann/json#simplify-your-life-with-macros)

**Comment by Yimura** [comment]
Seems good to me, this will also dramatically simplify the layout of the settings/globals.
