### ISSUE TITLE
[Bug]: Switch games

### ISSUE THREAD

**Issue by ligonfei** [Yimura/YimMenu#378]
### Describe the bug

When I inject it and switch games, I will switch to a single game and join a friend game. When I join a friend game, I will prompt that it does not exist. After uninstalling, it will return to normal. I hope it can be repaired

### Steps To Reproduce

1.open the  gta5 Enter online games
2.Enter the war situation and open it
3.A friend invited to join the war
4.Prompt that there is no war situation

### Expected Behavior

In the case of injection, you can join the battle with someone

### Screenshots and/or Logs

```
<paste your logs here>
```
![image](https://user-images.githubusercontent.com/73727313/182005918-9d05fcd8-4816-41d9-92b4-7ce446abeb83.png)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
This issue often occurs if you're spoofing your name or rockstar id.

What happens is you get either one of two problems.
- Connection to session timed out
or
- Silent bail from session

With the silent bail from the session you're actually completely in the session but then suddenly the game just bails you out and you're in an empty session.

**Comment by Yimura** [comment]
It's possible that #666 fixed this issue.

**Comment by Yimura** [comment]
I haven't had this issue myself in a good while so I assume this has been fixed.
