### ISSUE TITLE
[Bug]: gtav-sigscan-action not working.

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#389]
### Describe the bug

Sigscan not working. I forked sigscan repository and run action (Test Local Github Action) with detected.dll.
Result: No detections found, doing nothing...

### Steps To Reproduce

1. Run scan action.

### Expected Behavior

Result: dll detected.

### Store

Other (please mention in "Additional context")

### Additional context

Action runned on GitHub.

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Try reporting this issue on the appropriate repository, this one isn't related to the sigscan action.

https://github.com/Yimura/gtav-sigscan-action

**Comment by Yimura** [comment]
I've enabled issues on the other repository.
