### ISSUE TITLE
[Bug]: Nightly build detected ?

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#391]
### Describe the bug

Sigscanner finded detects:
Warning: (YimMenu.dll) "pattern_batch.cpp" (17) (v2699) (PAGE_READONLY) (~11481.088 kb region)
(YimMenu.dll) "ely the hook set" (16) (v2699) (PAGE_READONLY) (~20197.376 kb region)
(YimMenu.dll) "DownLogging was " (16) (v2699) (PAGE_READONLY) (~20197.376 kb region)

### Steps To Reproduce

1) Run Scan Action

### Expected Behavior

No detects,

### Store

Other (please mention in "Additional context")

### Additional context

GitHub Action

### Build

- [X] I used YimMenu unmodified

**Comment by Vali0004** [comment]
You see, I would post a way to disable sig scanning entirely but I don’t want it to be patched because Yim is public

**Comment by GeopJr** [comment]
Confirming: https://github.com/YimMenu/YimMenu/runs/7682676154?check_suite_focus=true

**Comment by maybegreat48** [comment]
Looking at the region size they are targetting some extremely bloated BBv2 menu (its literally 20 MB lol) so we have nothing to worry about for now. There are a couple of methods to disable sigscans and full RAGE Security(RAC) scattered around this repo and other places

**Comment by Yimura** [comment]
Regardless of if YimMenu was actually detected by this it has been fixed with #395 and #396
