### ISSUE TITLE
[Request]: Remove Client and NotFriend icon from Playerlist and add a icon for people that have Never Wanted

### ISSUE THREAD

**Issue by RainerZufall187** [Yimura/YimMenu#393]
### Problem

All those icons make it hard to see who you're friends with and who the host is.

### Solution

Remove the Client and NotFriend icon from the playerlist. Also add an icon to identify players given to Never Wanted.

### Reason

All those icons make it hard to see who you're friends with and who the host is. It would also be nice to have an icon to be able to directly see the player that was given to Never Wanted.

**Comment by Yimura** [comment]
Sounds good to be honest, Client and Not Friend should be hidden as not having the icon there will make it clear someone isn't your friend or isn't the host and will make it easier to glance who is and isn't important in the list.

Unsure how you would expect us to detect never wanted though.

**Comment by RainerZufall187** [comment]
> Unsure how you would expect us to detect never wanted though.

I meant that it will show up a Never Wanted icon near players that **you** gave never wanted to and you remove their wanteds in the loop. Would be nice to have but isn't necessary.
