### ISSUE TITLE
[Bug]: game crashes after injection 

### ISSUE THREAD

**Issue by hichemmezemate** [Yimura/YimMenu#403]
### Describe the bug

 whenever i inject YimMenu i get an error and the game crashes, it was working normally but now no 

### Steps To Reproduce

inject dll 
get error 
game crashes

### Expected Behavior

i expected to work normally 

### Screenshots and/or Logs

```
<paste your logs here>
```
![Sans titre](https://user-images.githubusercontent.com/78790205/184161366-d36464d4-2862-44d9-a8df-87fc28ef702c.png)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Yeah I've noticed with some of the new additions that YimMenu has become a bit unstable, adding on top of that that we have to rely on a `HTTP` proxy to fetch our data.

In the future I'd like do away with relying on any external sources, no downloading required from people using the menu or compiling the data into our menu.

If possible I'd like to make some kind of cache that's generated when the games build version changes or the version of the cache changes:
https://github.com/YimMenu/YimMenu/blob/c83dee8700158ce1a999b0e1452685a8ce1f0936/BigBaseV2/src/pointers.cpp#L319-L355

**Comment by hichemmezemate** [comment]
and i don't know how to build it with git and premake

**Comment by hichemmezemate** [comment]
> Yeah I've noticed with some of the new additions that YimMenu has become a bit unstable, adding on top of that that we have to rely on a `HTTP` proxy to fetch our data.
> 
> In the future I'd like do away with relying on any external sources, no downloading required from people using the menu or compiling the data into our menu.
> 
> If possible I'd like to make some kind of cache that's generated when the games build version changes or the version of the cache changes:
> 
> https://github.com/YimMenu/YimMenu/blob/c83dee8700158ce1a999b0e1452685a8ce1f0936/BigBaseV2/src/pointers.cpp#L319-L355

how to it .???

**Comment by Yimura** [comment]
Don't worry the comment isn't really pointed towards you, we'll figure out what the problem is.

I'm just stating what changes I'd like to make to YimMenu in the future.

**Comment by xM4ddy** [comment]
> and i don't know how to build it with git and premake

## Premake:
[Download this](https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip)

1. Press the Windows key on your keyboard.
2. Search and open “Edit the system environment variables.”
3. Go to the “Advanced” tab.
4. Click the “Environment variables” button.
5. Select the “Path” variable under “User variables” or “System variables.”
6. Click the “Edit” button.
7. Press the “New” button.
8. Type the full directory path of the program. (something like `C:\users\blah\blah\premake5.exe`)
9. Press “Enter” to confirm the path.
10. Click “Ok.”
11. Press the “Ok” button in the Environment Variables window.
12. Click “Ok” in the System Variables window.

## Git:
[Download this](https://github.com/git-for-windows/git/releases/download/v2.37.1.windows.1/Git-2.37.1-32-bit.exe)

1. In a folder where you want yim menu use git to run the command
`git clone https://github.com/YimMenu/YimMenu.git --recursive || echo "You don't have git installed, install it from https://git-scm.com/download/win"`
2. Manually click the folder then click GenerateProjects.bat or do cd YimMenu then GenerateProjects.bat

## VS and build
1. Open visual studio installed and press `Ctrl + Shift B` or the green arrow to build it. If you need help try YouTube or the UC thread.

**Comment by aa15032261** [comment]
Maybe you can try this version: https://github.com/YimMenu/YimMenu/actions/runs/2842496550

This version is from PR #400, which embeds all necessary data into the binary. Just download the binary from the Artifacts section and test if it works.

**Comment by hichemmezemate** [comment]
> Maybe you can try this version: https://github.com/YimMenu/YimMenu/actions/runs/2842496550
> 
> This version is from PR #400, which embeds all necessary data into the binary. Just download the binary from the Artifacts section and test if it works.

This one is working

**Comment by hichemmezemate** [comment]
> Maybe you can try this version: https://github.com/YimMenu/YimMenu/actions/runs/2842496550
> 
> This version is from PR #400, which embeds all necessary data into the binary. Just download the binary from the Artifacts section and test if it works.

Thanks

**Comment by aa15032261** [comment]
> Thanks

Glad to know its working for you
