### ISSUE TITLE
[Bug]: Session Switcher

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#405]
### Describe the bug

If you are useing some other Session Types like "Join Invite Only" it puts you in public Lobbies and that with some other Types

### Steps To Reproduce

1. Go to Network
2. Select a Session Type

### Expected Behavior

- x

### Screenshots and/or Logs

```
- Not needed
```

### Store

Rockstar

### Additional context

- None

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Unable to reproduce, all join options seem to work as intended.
