### ISSUE TITLE
[Bug]: Can't move with cursor

### ISSUE THREAD

**Issue by dimmuboy** [Yimura/YimMenu#416]
### Describe the bug

When I open menu I can't move with mouse cursor. Cursor is stucked in the middle of screen and I can move just around but not so far to reach corner of screen where is the menu.

### Steps To Reproduce

1. Inject menu (Xenos64)
2. Press hotkey to open menu
3. Move mouse

### Expected Behavior

Free move

### Screenshots and/or Logs

```
No relevant logs
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by boredom1234** [comment]
You have dual screen setup?

**Comment by dimmuboy** [comment]
no, I have single screen and windowed fullscreen, but it's same with just windowed or fullscreen

**Comment by nvb-uy** [comment]
Go to your mouse settings ingame and use another input method, iirc the windows one does not work with the menu :)

**Comment by dimmuboy** [comment]
Yes I forget to answer but this is how I already solved an issue

**Comment by Yimura** [comment]
Alright, good to know for in the future.
