### ISSUE TITLE
[Request]: A fix for name spoofing to work locally

### ISSUE THREAD

**Issue by Slanderrr** [Yimura/YimMenu#417]
### Problem

When spoofing the username, it doesn't spoof it locally. When you type in chat, it shows the spoofed username for everyone else. But for you, it still shows your R* username.

### Solution

Essentially would just love to see it spoofed everywhere.

### Reason

At times, I can't really tell if has worked or not. I would have to have someone read the username off to me in-game, or a friend I am playing with has to tell me. I can't tell as its not spoofed for myself.

**Comment by Adler-D3R** [comment]
Well the solution is quite simple : you need to get all occurences of the name in memory, and replace the value with the spoofed one. However, the number of occurences isn't always the same. Also, by replacing every single occurences, it will also replace value sent to host. So what we need to do is only replace a few that will be only used locally. Cheat Engine might be useful to do some tests. (Don't use it Online)

**Comment by M1XT3NZ** [comment]
Cheat engine is fair game online.

**Comment by Vali0004** [comment]
> Well the solution is quite simple : you need to get all occurences of the name in memory, and replace the value with the spoofed one. However, the number of occurences isn't always the same. Also, by replacing every single occurences, it will also replace value sent to host. So what we need to do is only replace a few that will be only used locally. Cheat Engine might be useful to do some tests. (Don't use it Online)

Look for the native GET_PLAYER_NAME and it’s occurrences. I’d also locally modify your rlGamerInfo and other classed data.

**Comment by maybegreat48** [comment]
Writing a different name to `rlGamerInfo`/`netPlayerData`/`CPlayerInfo` or replacing all results with CE is detected (more info on this in the AC discussion), Hooking GET_PLAYER_NAME  should be fine. You can just try asking a random in the session to verify if it is spoofed correctly

**Comment by ghost** [comment]
> Cheat engine is fair game online.

Cheat Engine installs bloatwares/adwares:
![shitengine](https://user-images.githubusercontent.com/95159500/192153746-b8182bcf-3a8f-4e11-9d7a-29cf749fa937.png)
Source: https://github.com/cheat-engine/cheat-engine/issues/1157

**Comment by M1XT3NZ** [comment]
because its an old af version maybe check the NEWEST instead of a version
from around 2020 xd

**Comment by Yimura** [comment]
Idk why but you're referencing a 3y old Cheat Engine issue. I installed Cheat Engine fresh and it definitely had the option not to install the adware.

**Comment by ghost** [comment]
> because its an old af version maybe check the NEWEST instead of a version from around 2020 xd

> Idk why but you're referencing a 3y old Cheat Engine issue. I installed Cheat Engine fresh and it definitely had the option not to install the adware.

Yeah but the latest installer from their GitHub releases section and their official sites still do this and i'll not trust the installer, i don't want to launch it on my PC and risking being infected.

**Comment by ghost** [comment]
Sorry for duplicate, a recent issue: https://github.com/cheat-engine/cheat-engine/issues/2315

**Comment by M1XT3NZ** [comment]
> > because its an old af version maybe check the NEWEST instead of a version from around 2020 xd
> 
> > Idk why but you're referencing a 3y old Cheat Engine issue. I installed Cheat Engine fresh and it definitely had the option not to install the adware.
> 
> Yeah but the latest installer from their GitHub releases section and their official sites still do this and i'll not trust the installer, i don't want to launch it on my PC and risking being infected.

https://i.imgur.com/xD6OWx6.png

**Comment by Yimura** [comment]
> Sorry for duplicate, a recent issue: https://github.com/cheat-engine/cheat-engine/issues/2315

That issues legit tells you that the installer and Cheat Engine are 2 separate programs.

Cheat Engine does not require you to install adware, so as a solution just compile Cheat Engine yourself and put that in your program files directory.

Or just don't install Cheat Engine if you're that worried.

**Comment by ghost** [comment]
> Or just don't install Cheat Engine if you're that worried.

That's why we need this feature on the mod menu to do videos without our real name being stalked when we do YouTube videos as exemple.

> That issues legit tells you that the installer and Cheat Engine are 2 separate programs.
> 
> Cheat Engine does not require you to install adware, so as a solution just compile Cheat Engine yourself and put that in your program files directory.

I will not support Cheat Engine, by using it by compiling or donating to on Patreon to get a installer without Adwares.
Proposing installer with Adwares and having to pay to not have them is like websites wish asks to pay to remove tracking cookies on their websites, it is really a shame.
If they not used this shame to monetize their project i would be ok to donate them some bucks but else not, sorry.

**Comment by M1XT3NZ** [comment]
> > Or just don't install Cheat Engine if you're that worried.
> 
> That's why we need this feature on the mod menu to do videos without our real name being stalked when we do YouTube videos as exemple.
> 
> > That issues legit tells you that the installer and Cheat Engine are 2 separate programs.
> > Cheat Engine does not require you to install adware, so as a solution just compile Cheat Engine yourself and put that in your program files directory.
> 
> I will not support Cheat Engine, by using it by compiling or donating to their Patreon to get a installer without Adware. Proposing installer with Adwares and havingg to pay to not have them is like websites that ask to pay to remove tracking cookies on their websites, it is really a shame. If they not used this shame to monetize their project i would be ok to dontae them some bucks but else not, sorry.

dude you dont need to install any of the adware as you see in the image i sent above you can just skip them all but you do you xd

**Comment by ghost** [comment]
> > > Or just don't install Cheat Engine if you're that worried.
> > 
> > 
> > That's why we need this feature on the mod menu to do videos without our real name being stalked when we do YouTube videos as exemple.
> > > That issues legit tells you that the installer and Cheat Engine are 2 separate programs.
> > > Cheat Engine does not require you to install adware, so as a solution just compile Cheat Engine yourself and put that in your program files directory.
> > 
> > 
> > I will not support Cheat Engine, by using it by compiling or donating to their Patreon to get a installer without Adware. Proposing installer with Adwares and havingg to pay to not have them is like websites that ask to pay to remove tracking cookies on their websites, it is really a shame. If they not used this shame to monetize their project i would be ok to dontae them some bucks but else not, sorry.
> 
> dude you dont need to install any of the adware as you see in the image i sent above you can just skip them all but you do you xd

I do not trust the installer.
A lot of installers like this i used in the past was still installing crapwares on my PC even i unchecked all checkboxes.

**Comment by Yimura** [comment]
> I do not trust the installer.
> A lot of installers like this i used in the past was still installing crapwares on my PC even i unchecked all checkboxes.

1. The issue is still open and being tracked, so Cheat Engine was offered as a solution until the actual problem is solved in YimMenu
2. There's a second issue that's called streamer mode (#200) which is made to hide your name in-menu since spoofing locally doesn't change your name in menu.

Please stop going any further off-topic. Any problems that you have with Cheat Engine will need to be resolved with Cheat Engine devs not with us.

**Comment by ghost** [comment]
you can just hook GET_PLAYER_NAME to change the name locally and use snitl to spoof it for other players

**Comment by Yimura** [comment]
Remote spoofing is already implemented, only the local spoofing remains.

**Comment by ghost** [comment]
> Remote spoofing is already implemented, only the local spoofing remains.

like i said just hook GET_PLAYER_NAME and set it as the name you wanna spoof to
note: it will only display locally
