### ISSUE TITLE
[Bug]: Sigscan Detected?

### ISSUE THREAD

**Issue by Auzzaue** [Yimura/YimMenu#419]
### Describe the bug

Sigscan detected on build 889
(BigBaseV2.dll) "YimMenu\bin" (11) (v2699) (PAGE_READONLY)
(BigBaseV2.dll) "reLoggingHook(.." (16) (v2699) (PAGE_READONLY)

### Steps To Reproduce

1.cmd.exe
2.singscan.exe

### Expected Behavior

Don't have any output

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
I'm running nightly to see if it returns the same results, check the workflow run [here](https://github.com/YimMenu/YimMenu/actions/runs/2882894449).

Edit:

Result of sigscan:
```
(YimMenu.dll) "YimMenu\bin" (11) (v2699) (PAGE_READONLY) (~454.656 kb region)
(YimMenu.dll) "reLoggingHook(.." (16) (v2699) (PAGE_READONLY) (~20201.472 kb region)
```

We don't need to worry about the one in the 20201.472 kb region the other I'd have to check in IDA or some hex editor.

**Comment by Yimura** [comment]
These strings appear to be targeting other menu's than YimMenu.

The detection for the "YimMenu\bin" string is in the `454.656 kb region`, meanwhile if I use the YimMenu built from the Github Action the string is in the `1.894 MB region`.
As such we shouldn't need to worry about us being detected by the sigscanner.
