### ISSUE TITLE
[Bug]: remove detected IS_DLC_PRESENT hook

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#420]
As stated here in the Arxan Reversal thread: https://github.com/YimMenu/YimMenu/discussions/137#discussioncomment-2738192

This hook wasn't ever active in YimMenu but has recently been enabled in #399 .

**Comment by maybegreat48** [comment]
You can just replace it with a native hook applied on all threads, possibly with a toggle to disable that feature
