### ISSUE TITLE
[Request]: New Weapons Joat for 1.61

### ISSUE THREAD

**Issue by thizsam** [Yimura/YimMenu#421]
### Problem

Hi, Can you update the Weapons.h with new weapons included in 1.61 like m16 , compact emp and some drip feed weapons 

### Solution

New Weapons

### Reason

Update Request

**Comment by aa15032261** [comment]
I believe yim gets the weapon hashes from external source on startup, take a look at gta data service.

**Comment by Yimura** [comment]
Not an issue related to YimMenu, closing it.
