### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tord-Zhang** [Yimura/YimMenu#422]
### Describe the bug

Hi, thanks for your wonderful work, I followed your way to get the ground z coordinates, https://github.com/YimMenu/YimMenu/blob/master/BigBaseV2/src/util/teleport.hpp#L37, but the code crashed.

### Steps To Reproduce

float GetGroundCoords(float x, float y, int tries)
{
	float groundZ;
    for(int i = 0; i < tries; i++)
    {
        for (float z = 1.f; i && z >= 0.f; z -= 0.1)
        {
            STREAMING::REQUEST_COLLISION_AT_COORD(x, y, z);
            WAIT(0);
        }

        if (GAMEPLAY::GET_GROUND_Z_FOR_3D_COORD(x, y, 500.f, &groundZ, 0))
        {
            return groundZ;
        }
    }

	return 500.f;
}

![FEH3GFsxVV](https://user-images.githubusercontent.com/18326098/185927729-7b4ba6a9-22c9-4d58-9d03-016e81c8c8ce.jpg)

**Comment by Yimura** [comment]
I don't see how this is a problem with YimMenu?

Please refrain from making issues about your personal implementation of the code. Issues are meant for problems with YimMenu.

If you need help with coding a GTA V mod menu go to [UnknownCheats](https://www.unknowncheats.me/forum/grand-theft-auto-v/).
