### ISSUE TITLE
[Bug]: Preview of vehicles in mid air

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#424]
### Describe the bug

All vehicles in the spawn list and PV list except the first 2 in PV list preview in mid air incorrectly. 

### Steps To Reproduce

--

### Expected Behavior

Preview on land

### Screenshots and/or Logs

https://user-images.githubusercontent.com/90883505/186155477-7178e22c-7c49-4b46-8f24-c606d45b5011.mp4

### Store

Epic Games

### Additional context

I have some minor modifications to the menu, but I don't think any of them is causing this or conflicting with this, hence I checked that I'm using unmodified YimMenu

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
I don't think this can be fixed.

When previewing a vehicle the game will try to stick it to the ground, I think this is their code trying to prevent cars from floating with a bad host or a player with a bad connection.
I haven't found a way to disable this behaviour of sticking the car to the ground.

**Comment by Yimura** [comment]
Unable to resolve this issue because of quirks in the rage engine.
