### ISSUE TITLE
[Request]: Signature scanning improvements

### ISSUE THREAD

**Issue by Vali0004** [Yimura/YimMenu#426]
### Problem

I mean, I went and improved the hooking so I might as well say something about the pointers now.
All the sigs are mostly from BigBaseV2, not that there's anything wrong with that, it's just that those sigs are long and fairly late in the callstack compared to what it can be.

### Solution

I'll provide an example, the native handler signature. In BigBaseV2 and Yim it's "48 8D 0D ? ? ? ? 48 8B 14 FA E8 ? ? ? ? 48 85 C0 75 0A".
In my source, it's "40 B6 01 39 79 2C" + 0xF. My signature has no wildcards, it's early in the callstack and it has a low byte count making it much better.

I mean, going into IDA, grabbing the old signature, xrefing it, getting a sig early in the callstack and jumping around when the byte count is high af isn't hard.

### Reason

I mean, less memory allocation, speeds up signature scanning and it makes things simpler.
A small improvement like this could make YimMenu drastically better, I don't know why this wasn't done before.

**Comment by Aure7138** [comment]
If I remember correctly, it was optimized before.
https://github.com/YimMenu/YimMenu/commit/d1814cf55f7618a3e0a46e972632c8107f07e094

**Comment by Vali0004** [comment]
I'm well aware, yet it's still not the best (Plus not everything was optimized, most things still need to be done). Most of my sigs are 10 bytes or less. My longest is 12 bytes, I have 46 sigs and the same/or more as YimMenu. There is no reason not to.

**Comment by Yimura** [comment]
A better sig scanner has been implemented in #470 and we can "infinitely" improve the sig scanner so I'm closing this issue.

If the sig scanner somehow becomes super slow, we can open a new issue.
