### ISSUE TITLE
[Request]: make bodyguards attack players who attack you or who you attack

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#429]
### Problem

bodyguards dont attack players.

### Solution

making it so bodyguards can attack players also maybe make it so they can have godmode on.

### Reason

it would be funny and it would make the experience way better lol. imagine having bodyguard army

**Comment by MyPadOS** [comment]
can edit  source  set  ENTITY::SET_ENTITY_INVINCIBLE(ped,true);  this is  god mod .  or edit TASK source making it so bodyguards can attack players but i cant search method

**Comment by ghost** [comment]
You can create a Ped with the name "player_two" that will appear as Trevor and attack nearby players and you can set it to INVINCIBLE. I have no idea how to implement an attack on a specific player and not on everyone who is nearby
