### ISSUE TITLE
Locals

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#43]
Hey, just wondering on which line you found in freemode???
*script_local(freemode_thread, 17437).at(176).as<int*>() = 0; // spawn vehicle instantly

I cant find it..

**Comment by Yimura** [comment]
Why lol

**Comment by Yimura** [comment]
@MoneyDropLobby please answer within the next 24h or I'll remove your issue, please go on UnknownCheats to ask for things that are not relevant to bugs or new features.
