### ISSUE TITLE
[Bug]: Sparrow rags in Kosatka

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#432]
### Describe the bug

Stepping off the Sparrow in Kosatoka causes the Sparrow to break rough

ps.This article was created using a translation tool

### Steps To Reproduce

Ride a Sparrow inside Kosatka

### Expected Behavior

Sparrow stays there

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by GeopJr** [comment]
Hi, your issue is missing some info, could you answer the following:

- Does it occur when you don't inject YimMenu?
- Does it occur when you inject YimMenu without enabling anything?
- If no, what options did you enable on YimMenu before it occurred?

**Comment by Yimura** [comment]
Seems like a general bug from one of the features in the menu.
Though I don't have the Kosatka and don't feel like replicating.

**Comment by Yimura** [comment]
No further context was provided, I will reopen if the original author responds.

**Comment by halny197** [comment]
Please reopen this issue. I also have the same problem. I used YimMenu unmodified.
Some info that I have:
- It doesn't occur when I don't inject YimMenu.
- It occurs when I inject YimMenu without enabling anything.
- It occurs when I get out of the Sparrow after landing it inside the Kosatka.
- It seems to only happen with the Sparrow. I don't have the problem on the Avisa or the Toreador when entering the Kosatka.

**Comment by oxUNKNOWNxo** [comment]
> Please reopen this issue. I also have the same problem. I used YimMenu unmodified. Some info that I have:
> 
>     * It doesn't occur when I don't inject YimMenu.
> 
>     * It occurs when I inject YimMenu without enabling anything.
> 
>     * It occurs when I get out of the Sparrow after landing it inside the Kosatka.
> 
>     * It seems to only happen with the Sparrow. I don't have the problem on the Avisa or the Toreador when entering the Kosatka.

Sorry for the late reply. Same situation as the quoted reply.

- Occurs only on YimMenu, improves when YimMenu is unloaded

- all options are off

- I tried deleting the configuration file just in case, but it doesn't change

It can also occur in missions involving vehicles other than Kosatka 
e.g. the Avenger is shaking in the final cinematic of the Bogdan Problem Finale in the Doomsday Heist.

PS, this sentence was created with Google Translate

**Comment by tupoy-ya** [comment]
Just realized that i also experience this bug in SP cutscenes ex: Prologue car after the train crash.

**Comment by Yimura** [comment]
The two don't have collision? Or what exactly is happening?

**Comment by tupoy-ya** [comment]
This is recorded in my version of YimMenu and i didn't test if it occurs the in normal YimMenu, but judging by this issue it does.

https://user-images.githubusercontent.com/72797377/206187605-e69e0ca6-1c97-459c-ae3a-329d41c9827e.mp4

**Comment by Yimura** [comment]
Probably a looped feature, could you go into settings > manage scripts and toggle them all off to see if it's on of the looped features doing it.
I'll probably test later today.

**Comment by oxUNKNOWNxo** [comment]
Apparently, it seems that the vehicle you got on is generated.
This is the first time I've seen multiple Sparrows spawn

https://user-images.githubusercontent.com/112477569/206188353-b99a5f83-3ddc-4a36-bd0a-707467be76dc.mp4

**Comment by oxUNKNOWNxo** [comment]
> Probably a looped feature, could you go into settings > manage scripts and toggle them all off to see if it's on of the looped features doing it. I'll probably test later today.

Certainly, It stopped happening when I turned everything off with manage script.

**Comment by tupoy-ya** [comment]
It's probably noclip that's causing it, disabling all of the other scripts but keeping noclip enabled result in this bug.

```cpp
	void looped::self_noclip()
	{
		const auto bNoclip = g->self.noclip;

		const auto location = self::pos;
		const Entity ent = (self::veh != 0 && g_local_player->m_ped_task_flag & (int)ePedTask::TASK_DRIVING) ? self::veh : self::ped;

		// cleanup when changing entities
		if (prev != ent)
		{
			ENTITY::FREEZE_ENTITY_POSITION(prev, false);
			ENTITY::SET_ENTITY_COLLISION(prev, true, true); // Probably this is what causes it

			prev = ent;
		}
```

**Comment by Yimura** [comment]
Yeah thought it was something like that, it's probably permanently unfreezing the vehicle or the change in entity collision.

Saving the collision state before changing it should probably fix it.

**Comment by maybegreat48** [comment]
Is this still an issue?

**Comment by oxUNKNOWNxo** [comment]
seems to be fine for now.

**Comment by Yimura** [comment]
Fixed, closing.
