### ISSUE TITLE
[Bug]: Using stand at the same time will end the game

### ISSUE THREAD

**Issue by Jiangdonganxia** [Yimura/YimMenu#433]
### Describe the bug

After updating, using Stand at the same time will automatically close the game

### Steps To Reproduce

1.injection YimMenu
2.injection Stand

### Expected Behavior

I need Stand to protect me，But it can't be used together after you update it

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Yeah there's no real way to make Stand and YimMenu work together, the way mod menu's work and protections need to be implemented will start creating problems at some point in the future.

With YimMenu implementing more features we will create more incompatibilities with other "internal" mod menu's.


I'm surprised it was possible at all to co-load these two.

**Comment by Aure7138** [comment]
@Jiangdonganxia Seriously, report this issue here. Report this bug to the stand server instead of here?
We don't know how the stand is loaded, but the stand knows how we load it, so asked them to fix this bug.

**Comment by Jiangdonganxia** [comment]
> @Jiangdonganxia说真的，请在此处报告此问题。将此错误报告给站立服务器而不是这里？我们不知道支架是如何加载的，但是支架知道我们如何加载它，所以要求他们修复这个错误。
The two menus have been updated recently. I can't judge whose fault it is, so I reported it on both menus.

**Comment by wdymUsername** [comment]
Just as side note, stand co-loaded just fine before yesterdays update

**Comment by MarkEcza** [comment]
![image](https://user-images.githubusercontent.com/85032105/187742353-077f40c7-a354-4770-bcfc-40568af6c66f.png)

**Comment by Jiangdonganxia** [comment]
> ![图像](https://user-images.githubusercontent.com/85032105/187742353-077f40c7-a354-4770-bcfc-40568af6c66f.png)

THX

**Comment by Yimura** [comment]
I presume this issue can be closed then?

**Comment by Jiangdonganxia** [comment]
> 我想这个问题可以关闭吗？

of course
