### ISSUE TITLE
[Bug]: Game crash when u tried spawn these cars

### ISSUE THREAD

**Issue by Sheeeeit** [Yimura/YimMenu#435]
### Describe the bug

If you try to spawn these vehicles, the game simply closes:
- **ARBITER GT**
- **ASTRON CUSTOM**
- **CYCLONE II**
- **WEAPONIZED IGNUS**
- **S95**

### Steps To Reproduce

1. Start game
2. Inject DLL
3. Open menu and try spawn it

### Expected Behavior

I don't know what could be causing this problem. The only option is to remove them from the list of all machines.

### Screenshots and/or Logs

[19:39:33][INFO/main.cpp:56]: Yim's Menu Initializing
[19:39:33][INFO/batch.cpp:23]: Found 'SCREEN_RESOLUTION' GTA5.exe+0x16C583
[19:39:33][INFO/batch.cpp:23]: Found 'GS' GTA5.exe+0x2BF4D0
[19:39:33][INFO/batch.cpp:23]: Found 'ISA' GTA5.exe+0xEDBF
[19:39:33][DEBUG/pointers.cpp:34]: CPedFactory => [0x7FF6CE63C868]
[19:39:33][INFO/batch.cpp:23]: Found 'PF' GTA5.exe+0x729AA4
[19:39:33][INFO/batch.cpp:23]: Found 'NPM' GTA5.exe+0x1095BC8
[19:39:33][INFO/batch.cpp:23]: Found 'NH' GTA5.exe+0x15D4C35
[19:39:33][INFO/batch.cpp:23]: Found 'FV' GTA5.exe+0x15D18F0
[19:39:33][INFO/batch.cpp:23]: Found 'ST' GTA5.exe+0x15D4AD7
[19:39:33][INFO/batch.cpp:23]: Found 'SP' GTA5.exe+0xA3D429
[19:39:33][DEBUG/pointers.cpp:74]: ScriptGlobals => [0x7FF6CEF07910]
[19:39:33][INFO/batch.cpp:23]: Found 'SG' GTA5.exe+0x15D4328
[19:39:33][INFO/batch.cpp:23]: Found 'CGSHM' GTA5.exe+0x15D96AD
[19:39:33][INFO/batch.cpp:23]: Found 'S' GTA5.exe+0x1364065
[19:39:33][INFO/batch.cpp:23]: Found 'MSB' GTA5.exe+0xA3B1C2
[19:39:33][INFO/batch.cpp:23]: Found 'NRF' GTA5.exe+0x26E29
[19:39:33][INFO/batch.cpp:23]: Found 'GTS' GTA5.exe+0x15D4594
[19:39:33][INFO/batch.cpp:23]: Found 'TK' GTA5.exe+0xA41590
[19:39:33][INFO/batch.cpp:23]: Found 'TSE' GTA5.exe+0xD81FDC
[19:39:33][INFO/batch.cpp:23]: Found 'REH' GTA5.exe+0x168C458
[19:39:33][INFO/batch.cpp:23]: Found 'SEA' GTA5.exe+0x16770E9
[19:39:33][INFO/batch.cpp:23]: Found 'RBWD' GTA5.exe+0x13BEAE5
[19:39:33][INFO/batch.cpp:23]: Found 'RBA' GTA5.exe+0x13028B4
[19:39:33][INFO/batch.cpp:23]: Found 'RBS' GTA5.exe+0x1190390
[19:39:33][INFO/batch.cpp:23]: Found 'RBB' GTA5.exe+0x1146CFF
[19:39:33][INFO/batch.cpp:23]: Found 'RBA' GTA5.exe+0x13028B4
[19:39:33][INFO/batch.cpp:23]: Found 'WBD' GTA5.exe+0x140F128
[19:39:33][INFO/batch.cpp:23]: Found 'WBQ' GTA5.exe+0x1309E9C
[19:39:33][INFO/batch.cpp:23]: Found 'WBI64' GTA5.exe+0x11939C5
[19:39:33][INFO/batch.cpp:23]: Found 'WBI32' GTA5.exe+0x1192897
[19:39:33][INFO/batch.cpp:23]: Found 'WBB' GTA5.exe+0x119241C
[19:39:33][INFO/batch.cpp:23]: Found 'WBA' GTA5.exe+0x1676EAA
[19:39:33][INFO/batch.cpp:23]: Found 'RCOE-Patch' GTA5.exe+0xCD42D4
[19:39:33][DEBUG/pointers.cpp:215]: rage::CReplayInterface => [0x7FF6CE004948]
[19:39:33][INFO/batch.cpp:23]: Found 'RI' GTA5.exe+0x1F80
[19:39:33][INFO/batch.cpp:23]: Found 'PTH' GTA5.exe+0x15D9169
[19:39:33][INFO/batch.cpp:23]: Found 'BE' GTA5.exe+0xA7397F
[19:39:33][INFO/batch.cpp:23]: Found 'IDP' GTA5.exe+0xA814AC
[19:39:33][INFO/batch.cpp:23]: Found 'SNITL' GTA5.exe+0x13DB3C2
[19:39:33][INFO/batch.cpp:23]: Found 'CNOM' GTA5.exe+0xB16BE4
[19:39:33][INFO/batch.cpp:23]: Found 'NPMI' GTA5.exe+0x10F6927
[19:39:33][INFO/batch.cpp:23]: Found 'NPMS' GTA5.exe+0x112AC76
[19:39:33][DEBUG/pointers.cpp:265]: FriendRegistry => [0x7FF6CEA41E3C]
[19:39:33][INFO/batch.cpp:23]: Found 'FR' GTA5.exe+0xCD08D0
[19:39:33][INFO/batch.cpp:23]: Found 'GSCFWC' GTA5.exe+0xA3C598
[19:39:33][INFO/batch.cpp:23]: Found 'GGCC' GTA5.exe+0xA7E386
[19:39:33][INFO/batch.cpp:23]: Found 'GPR' GTA5.exe+0x11AE73C
[19:39:33][INFO/batch.cpp:23]: Found 'NGO' GTA5.exe+0x727C74
[19:39:33][INFO/batch.cpp:23]: Found 'RNM' GTA5.exe+0x1422341
[19:39:33][INFO/batch.cpp:23]: Found 'GNED' GTA5.exe+0x19E3348
[19:39:33][INFO/batch.cpp:23]: Found 'API' GTA5.exe+0x169251C
[19:39:33][INFO/batch.cpp:23]: Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x1101E99
[19:39:33][DEBUG/pointers.cpp:324]: HashTable => [0x7FF6CDF4BAA0]
[19:39:33][INFO/batch.cpp:23]: Found 'MHT' GTA5.exe+0xB0FC
[19:39:33][INFO/batch.cpp:23]: Found 'GLT' GTA5.exe+0xDA336B
[19:39:34][INFO/main.cpp:58]: Pointers initialized.
[19:39:34][INFO/main.cpp:61]: Renderer initialized.
[19:39:34][INFO/main.cpp:64]: Fiber pool initialized.
[19:39:34][INFO/main.cpp:67]: Hooking initialized.
[19:39:34][INFO/main.cpp:70]: Settings Loaded.
[19:39:34][INFO/main.cpp:73]: Thread pool initialized.
[19:39:34][INFO/main.cpp:86]: Registered service instances...
[19:39:34][INFO/main.cpp:103]: Scripts registered.
[19:39:34][INFO/script_hook.cpp:61]: Hooked shop_controller script (0x22AB66F0000)
[19:39:34][INFO/main.cpp:106]: Dynamic native hooker initialized.
[19:39:34][DEBUG/thread_pool.cpp:21]: Allocating 16 threads in thread pool.
[19:39:34][INFO/main.cpp:109]: Hooking enabled.
[19:39:34][INFO/backend.cpp:30]: Starting script: Self
[19:39:34][INFO/backend.cpp:49]: Starting script: Weapons
[19:39:34][INFO/backend.cpp:73]: Starting script: Vehicles
[19:39:34][INFO/backend.cpp:107]: Starting script: Miscellaneous
[19:39:34][INFO/backend.cpp:122]: Starting script: Remote
[19:39:34][INFO/backend.cpp:139]: Starting script: No clip
[19:39:34][INFO/backend.cpp:151]: Starting script: Ls customs
[19:39:34][INFO/backend.cpp:163]: Starting script: Rainbow paint
[19:39:34][INFO/backend.cpp:175]: Starting script: Vehicle fly
[19:39:34][INFO/backend.cpp:95]: Starting script: turnsignal
[19:39:34][INFO/backend.cpp:187]: Starting script: Disable Control Action
[19:39:35][INFO/gta_data_service.cpp:152]: Checking update (attempt: 1/3): Vehicle
[19:39:35][INFO/api.hpp:72]: Create session and received ID: lLfZFqBQyYsol/pGHGe0RA==
[19:39:35][INFO/gta_data_service.cpp:166]: Data updated: Vehicle
[19:39:35][INFO/gta_data_service.cpp:170]: Data loaded: Vehicle
[19:39:36][INFO/gta_data_service.cpp:152]: Checking update (attempt: 1/3): Ped
[19:39:36][INFO/gta_data_service.cpp:166]: Data updated: Ped
[19:39:37][INFO/gta_data_service.cpp:170]: Data loaded: Ped
[19:39:38][INFO/gta_data_service.cpp:152]: Checking update (attempt: 1/3): Weapon
[19:39:38][INFO/gta_data_service.cpp:166]: Data updated: Weapon
[19:39:38][INFO/gta_data_service.cpp:170]: Data loaded: Weapon
2022/08/31 19:48:20 443678

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 22848

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll Base Address: 0x7FFDAC7C0000 Size: 0x188000
C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GFSDK_ShadowLib.win64.dll Base Address: 0x7FFD75290000 Size: 0x3CC000
C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFDDF270000 Size: 0x1C000
C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GTA5.exe Base Address: 0x7FF6CBFD0000 Size: 0x4A83A00
C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\bink2w64.dll Base Address: 0x7FFDC5630000 Size: 0x8D000
C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\steam_api64.dll Base Address: 0x661F0000 Size: 0x3F000
C:\Program Files (x86)\Steam\steamclient64.dll Base Address: 0x7FFD75660000 Size: 0x1536000
C:\Program Files (x86)\Steam\tier0_s64.dll Base Address: 0x7FFDAC510000 Size: 0x195000
C:\Program Files (x86)\Steam\vstdlib_s64.dll Base Address: 0x7FFDD15C0000 Size: 0x82000
C:\Program Files\NVIDIA Corporation\NvContainer\MessageBus.dll Base Address: 0x7FFDCB800000 Size: 0x737000
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FFDB0D30000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FFD473F0000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FFD728E0000 Size: 0xA14000
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2205.7-0\MpOav.dll Base Address: 0x7FFDDA100000 Size: 0x7B000
C:\Users\Cat\AppData\Local\Discord\app-1.0.9006\modules\discord_hook-1\discord_hook\d88e7fbd607\DiscordHook64.dll Base Address: 0x7FFD71930000 Size: 0x1DC000
C:\Users\Cat\MEGA\Games & Programms\GTA V Online\Mods\BigBaseV2.dll Base Address: 0x7FFD45330000 Size: 0x212000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FFDD2980000 Size: 0x182000
C:\WINDOWS\SYSTEM32\AcGenral.DLL Base Address: 0x7FFDCB200000 Size: 0x6B000
C:\WINDOWS\SYSTEM32\AcLayers.DLL Base Address: 0x7FFD76D80000 Size: 0x494000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FFDE4D20000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FFDE4D30000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FFDC8890000 Size: 0x5E000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FFDE2560000 Size: 0xF2000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FFDE21B0000 Size: 0x35E000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FFDC8060000 Size: 0x31000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FFDE1130000 Size: 0x263000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FFD77330000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCompiler_47.dll Base Address: 0x7FFDE0CD0000 Size: 0x45D000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FFDCB4F0000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FFDE4820000 Size: 0xCA000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FFDD9820000 Size: 0x9C000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FFDC51C0000 Size: 0x27F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FFDCE4C0000 Size: 0x32B000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FFDD1590000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FFDE3BF0000 Size: 0xD000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FFDE47D0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FFDE0390000 Size: 0x84000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FFD89A20000 Size: 0x48E000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FFDDFBE0000 Size: 0x1BC000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FFDDF6F0000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\MPR.dll Base Address: 0x7FFDCAC10000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FFDAC6B0000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FFDE4F60000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FFDCD840000 Size: 0x8E000
C:\WINDOWS\SYSTEM32\MSWSOCK.dll Base Address: 0x7FFDE4B30000 Size: 0x6A000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FFDD7C00000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FFDE4E00000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\OLEACC.dll Base Address: 0x7FFDDC100000 Size: 0x66000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FFD843C0000 Size: 0x127000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FFDE08D0000 Size: 0xF6000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FFDDFA90000 Size: 0x34000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FFDDC280000 Size: 0x19000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FFDCB140000 Size: 0xC000
C:\WINDOWS\SYSTEM32\SspiCli.dll Base Address: 0x7FFDE5230000 Size: 0x32000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FFDB0460000 Size: 0x2F5000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FFDE47B0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FFDE5270000 Size: 0x2E000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FFDD9E60000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FFDCD8D0000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FFDCD830000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FFDDF360000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FFDDB830000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FFDD4140000 Size: 0x4D6000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FFDDA1A0000 Size: 0x27000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FFDDFA50000 Size: 0xB000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FFDCB0A0000 Size: 0x98000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FFDE40E0000 Size: 0x5A000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FFDE4560000 Size: 0x19000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FFDE0CB0000 Size: 0x14000
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll Base Address: 0x7FFDDE290000 Size: 0x1B4000
C:\WINDOWS\SYSTEM32\Wldp.dll Base Address: 0x7FFDE4DD0000 Size: 0x30000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll Base Address: 0x7FFDE06C0000 Size: 0x7000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FFDDA180000 Size: 0x20000
C:\WINDOWS\SYSTEM32\apphelp.dll Base Address: 0x7FFDE2870000 Size: 0x90000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FFDDFA80000 Size: 0xA000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FFDDBE80000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FFDDDD90000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FFDDC270000 Size: 0xD000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FFDBE430000 Size: 0x1CF000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FFD75020000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FFDDD990000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FFDE3060000 Size: 0x1E4000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FFDE5120000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FFDDF4A0000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FFDDF370000 Size: 0x17000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FFDDDC40000 Size: 0x148000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FFDE2CB0000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FFDDBF40000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FFDE3C70000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FFDDBDF0000 Size: 0x24000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FFDE3C20000 Size: 0x23000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FFDD9960000 Size: 0x2B1000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FFDC6C40000 Size: 0x152000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FFDE3C00000 Size: 0x12000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FFDE05D0000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FFDC1C90000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FFDDC250000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FFDE0450000 Size: 0xB000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FFDE4E40000 Size: 0x27000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FFDE4810000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FFDE7C50000 Size: 0x1F8000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FFDE4070000 Size: 0x33000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FFDC18F0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FFDE48F0000 Size: 0x4B000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FFDE52B0000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FFDE2B40000 Size: 0x14000
C:\WINDOWS\SYSTEM32\sfc.dll Base Address: 0x22A74490000 Size: 0x3000
C:\WINDOWS\SYSTEM32\sfc_os.DLL Base Address: 0x7FFDCAF70000 Size: 0x12000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FFDD9C20000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FFDC83B0000 Size: 0xF9000
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll Base Address: 0x7FFDDE640000 Size: 0x200000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FFDD9C50000 Size: 0x1EC000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FFDC1CA0000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FFDE0830000 Size: 0x65000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FFDE3450000 Size: 0x794000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FFDD7DD0000 Size: 0x26000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FFDE1AE0000 Size: 0x154000
C:\WINDOWS\SYSTEM32\xinput1_4.dll Base Address: 0x7FFDBDEA0000 Size: 0x11000
C:\WINDOWS\System32\ADVAPI32.dll Base Address: 0x7FFDE6260000 Size: 0xAE000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FFDE5D30000 Size: 0xDA000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FFDE5B50000 Size: 0x156000
C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b65eb0793435320a\NvCamera\NvCamera64.dll Base Address: 0x7FFD46880000 Size: 0x851000
C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b65eb0793435320a\NvCamera\d3dcompiler_47_64.dll Base Address: 0x7FFD46470000 Size: 0x404000
C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b65eb0793435320a\nvcuda64.dll Base Address: 0x7FFD43950000 Size: 0x169F000
C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b65eb0793435320a\nvldumdx.dll Base Address: 0x7FFDDB2E0000 Size: 0xB0000
C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b65eb0793435320a\nvwgf2umx.dll Base Address: 0x7FFDB21B0000 Size: 0x294A000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FFDE71D0000 Size: 0x2A000
C:\WINDOWS\System32\IMM32.DLL Base Address: 0x7FFDE6230000 Size: 0x30000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FFDE6020000 Size: 0xBD000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FFDE54F0000 Size: 0x2CE000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FFDDCD00000 Size: 0x85000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FFDE72A0000 Size: 0x115000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FFDE6620000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FFDE68E0000 Size: 0xCD000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FFDE60E0000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FFDE64F0000 Size: 0x125000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FFDE73C0000 Size: 0x46F000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FFDE69B0000 Size: 0x744000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FFDE6880000 Size: 0x55000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FFDE6640000 Size: 0x1A0000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FFDE58A0000 Size: 0x68000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FFDE7160000 Size: 0x6B000
C:\WINDOWS\System32\bcrypt.dll Base Address: 0x7FFDE5870000 Size: 0x27000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FFDE5410000 Size: 0x82000
C:\WINDOWS\System32\cfgmgr32.dll Base Address: 0x7FFDE54A0000 Size: 0x4E000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FFDE6310000 Size: 0xA9000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FFDE78B0000 Size: 0x354000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FFDD93C0000 Size: 0x80000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FFDE5A10000 Size: 0x10B000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FFDE5CB0000 Size: 0x1D000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FFDE5370000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FFDE67E0000 Size: 0x9E000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FFDE63C0000 Size: 0x12A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FFDE7200000 Size: 0x9C000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FFDE60F0000 Size: 0xAD000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FFDE5910000 Size: 0x100000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FFDE5B20000 Size: 0x22000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FFDB5F00000 Size: 0x12000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll Base Address: 0x7FFDBD900000 Size: 0xB0000
C:\WINDOWS\system32\NLAapi.dll Base Address: 0x7FFDDFA30000 Size: 0x1D000
C:\WINDOWS\system32\XAudio2_7.dll Base Address: 0x7FFD89500000 Size: 0x8B000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FFDB9750000 Size: 0x17000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FFDD7330000 Size: 0x769000
C:\WINDOWS\system32\nvspcap64.dll Base Address: 0x7FFDB6920000 Size: 0x2C7000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FFDB6C60000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FFDE4440000 Size: 0x34000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FFDE29B0000 Size: 0x9E000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FFDB9770000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FFDD7F90000 Size: 0x51000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FFDE3FA0000 Size: 0xA0000
C:\Windows\System32\WindowManagementAPI.dll Base Address: 0x7FFDDE840000 Size: 0xA1000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FFDC6DA0000 Size: 0x141000
C:\Windows\System32\fwbase.dll Base Address: 0x7FFDE3EF0000 Size: 0x3A000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FFDD8FA0000 Size: 0xA000

Dumping registers:

RAX: 0x0
RCX: 0x22A0C23FA10
RDX: 0x7FF6CE98F7E4
RBX: 0x7FF6CEA14080
RSI: 0x0
RDI: 0x22A0C23FA10
RSP: 0xCCA61E73E0
RBP: 0xCCA61E7510
R8:  0x4
R9:  0x7FF6CE98F834
R10: 0x4038000000000000
R11: 0xCCA61E73D8
R12: 0x7FF6CEA14090
R13: 0x22A14E51DA0
R14: 0x0
R15: 0x7FF6CE995E70

stack dump [0]	 C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0xF1637A 0x7FF6CCEE637A
stack dump [1]	 C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0xFC1FDC 0x7FF6CCF91FDC
stack dump [2]	 C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x12DC18E 0x7FF6CD2AC18E
stack dump [3]	 C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x12E4A5A 0x7FF6CD2B4A5A
stack dump [4]	 C:\WINDOWS\System32\KERNEL32.DLL+0x17034 BaseThreadInitThunk
stack dump [5]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by FIying-Scotsman** [comment]
Those vehicles are "next gen" and don't have any textures which is why you crash. They've been slowly adding them in (again, without textures) since 1.60.

While there was a rumour a P2C figured out how to apply textures to them - it's just easier to remove them from the spawn list.

**Comment by Sheeeeit** [comment]
> ... - it's just easier to remove them from the spawn list.

The problem is that I can't find these cars in the list through a search by name or ID.

**Comment by Yimura** [comment]
It's because they crash the game that you can't find them in the crash list, you have the option to spawn anything, it crashing your game is on you.

**Comment by Yimura** [comment]
We filter out crash vehicles out here: https://github.com/YimMenu/YimMenu/blob/61a95fcbfe1d3006e8d3d71133149e6b7929016d/BigBaseV2/src/services/gta_data/gta_data_service.cpp#L239

You can spawn any other vehicle using their spawn name though which is probably what you did.
