### ISSUE TITLE
[Request]: Block chat and sms advertisements

### ISSUE THREAD

**Issue by Zhou377** [Yimura/YimMenu#436]
### Problem

Although Yim has the function of blocking the advertising machine, I hope to add a function of kicking out the advertising machine to make the whole war better，Another, this is an extremely crazy idea, or can you add similar functions such as preventing reporting in the future?

### Solution

Through some means to block the advertising machine? There are also reports that can be detected. Why can't we join in preventing reports? Sorry, these are some of my ideas. I hope to join Yim

### Reason

Although Yim is already very good, adding these functions may make Yim more powerful

**Comment by Aure7138** [comment]
> Zhou377

Kicking ads is actually kicking people, which is a toxic feature, requests for toxic features will not respond.
The blocking report is automatically turned on, you can choose to show notifications in settings->notification.

**Comment by unoreversocard** [comment]
could you make it so you can toggle those features on/off

**Comment by Aure7138** [comment]
> could you make it so you can toggle those features on/off

It's very simple, maybe you can do a PR

**Comment by unoreversocard** [comment]
i don't know how to code :(

**Comment by Yimura** [comment]
Implemented in #625
