### ISSUE TITLE
[Bug]: Error: ** Error: Failed to locate vendor directories. Try doing git pull --recurse-submodules.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#444]
### Describe the bug

```
C:\Users\******\.git>git clone https://github.com/YimMenu/YimMenu.git --recursive
Cloning into 'YimMenu'...
remote: Enumerating objects: 8583, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 8583 (delta 22), reused 39 (delta 8), pack-reused 8511
Receiving objects: 100% (8583/8583), 4.33 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (5403/5403), done.
git: 'submodule' is not a git command. See 'git --help'.

C:\Users\******\.git>cd YimMenu

C:\Users\******\.git\YimMenu>GenerateProjects.bat
Error: ** Error: Failed to locate vendor directories. Try doing git pull --recurse-submodules.
Appuyez sur une touche pour continuer...
```

### Steps To Reproduce

git clone https://github.com/YimMenu/YimMenu.git --recursive
cd YimMenu
GenerateProjects.bat

### Expected Behavior

Built DLL

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I used YimMenu unmodified

**Comment by xiaoxiao921** [comment]
- Cloning a git from a .git folder is weird.
- your terminal is saying that git submodule is not a valid command when in fact it is, I highly suggest checking your git installation https://git-scm.com/download/win
- this is not an issue with YimMenu as YimMenu itself build just fine

**Comment by Yimura** [comment]
Issue is unrelated to YimMenu, closing.
