### ISSUE TITLE
[Request]: Invalid Model Protection

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#449]
### Problem

- crashes your game

### Solution

- block invalid models in the rcs hook to prevent it.

### Reason

- patches many free menu crashes

**Comment by SkiddyToast** [comment]
Take a look at #407, I believe it addresses your concern.

**Comment by Yimura** [comment]
#407 has been merged into master, if there are any missing crash models then a new issue should be made to add these to the list.
