### ISSUE TITLE
Playerlist Host Token 

### ISSUE THREAD

**Issue by PrivMeta** [Yimura/YimMenu#45]
I was wondering how a session host force works (not script host) and eventually got it to working by changing the m_host_token and got it confirmed by other p2c's like Cherax, Frontier, 2Take1 etc. however as soon as I tried to read the value of m_host_token in the playerlist it just gives some random numbers. I even tried to get the hex value of it however it's also wrong.

player_info.cpp
`ImGui::Text("Host Token: %d", netData.m_host_token);`

m_host_token is a uint64_t like the m_rockstar_id

Maybe I miss something or it is something else.

**Comment by Yimura** [comment]
Might be that my class structures are incorrect, check if the m_peer_id is instead the correct value.
I may have swapped the two of them around:
https://github.com/Yimura/GTAV-Classes/blob/a069ad9316e70f612a937f5bda31fcc36dc38441/CPlayerInfo.hpp#L28-L29

If so please tell me here, I will update the class for the correct member variable!

**Comment by PrivMeta** [comment]
What I now tried was swapping these two variables, re-checking it with reclass just in case... however everything seems fine to me and as I said before I **can** change the m_host_token and it is visible to all other players, but I can't **read** the correct m_host_token. Thats why it is so mysterious and no the m_peer_id was completly something different.

For example if I set the m_host_token to 123456789:
The result for other players in their p2c's is also 123456789 (75BCD15).
The result for me viewing it by getting m_host_token is 1973817221 (75A60F85)

After I restart the game to verify it is not just a random number I spoofed again the same host token but this time it was again a different number but still other player's can see the spoofed host token.

For me the only reasonable way this could happend is now the formatting of m_host_token... but don't have any ideas more.

**Comment by Yimura** [comment]
That's because you're spoofing the values to the lobby, you're not modifying it locally. You're just intercepting the call that requests your data and spoofing the data that's returned.

This was answered if you looked in the unknowncheats thread of this menu as well as in an issue.

References:
 - https://github.com/Yimura/YimMenu/issues/19
 - https://www.unknowncheats.me/forum/3326297-post102.html

**Comment by PrivMeta** [comment]
Yeah you are right now if I think about it, it makes absolute sense. Thank you for now.
