### ISSUE TITLE
[Bug]: Unable to open YimMenu after switching to another PC and changing globals.hpp

### ISSUE THREAD

**Issue by funnel1** [Yimura/YimMenu#464]
### Describe the bug

Hello, as the title describes the whole issue.

On my PC, I had changed the hotkey to open the menu to Left Control key. Few months later when I got myself a laptop, I had copied the Extreme Injector v3.7.3 and the YimMenu repo with built solution into my laptop and ran it in GTA5. I only copied the injector and menu, not GTA5. I have freshly install GTA5 from Epic Games. It showed the ```VK_LCONTROL``` to open the menu but on hitting the key, it didn't show up. Here are the combinations I have tried to debug this issue myself:

1. Changed ```core\globals.hpp>settings>hotkeys>menu_toggle``` to another key from ```widgets\imgui_hotkey.hpp```. (Keeping in mind to put a constant as a value, since these are defined somewhere)
2. I have tried pulling the repo completely clean and building solution.
3. Using Xenos Injector to inject the dll.
4. Clearing temporary files manually and Disk Cleanup.
5. Restarted my PC and tried all of this again.

It still showed me ```VK_LCONTROL``` to open the menu but it never worked, even after hitting the Left Control key or any other key be it the one changed in menu_toggle variable or the whole keyboard. I have used virtual keyboard as well to test out this issue. On other note, on hitting ```X```, it showed the quick menu to Delete, Kill, Explode, TP into and TP to options, meaning the menu was injected.

What I haven't tried is to reinstall GTA5. The only reason I haven't done it yet is the download is huge. What I believe, is happening, is somehow there's some sort of issue in .obj or while mapping the addresses for specific variables or functions or even some cache is stored somewhere. Or somehow the menu is opening outside my window (I have set this to fullscreen in game settings), but then it should have shown me a cursor, which it didn't. I am however going to try to reinstall GTA5 if that resolves the issue, but in the mean time, I was hoping to find some answers here.

PS. I don't have access to the old PC to test if it is still working. This issue occurs on slightly modified YimMenu, that being only ```core\globals.hpp```

### Steps To Reproduce

Steps to reproduce are quite unique as you will need a whole new PC to test it, but here goes nothing.

1. YimMenu works fine on one PC. Change hotkey to open the menu to something else.
2. Copy Built Solution + Injector to another PC.
3. Inject it on new PC with fresh GTA5 install.
4. Message pops up, to open the menu use the new hotkey which was changed in point 1.
5. Hit the key, it doesn't work.
6. Debug 1: Change key directly from solution and rebuild.
7. Should show changed key in message.
8. Still shows the old key on injecting. Hitting new key and old key doesn't work.
9. Debug 2: Use another injector.
10. Same as 7 & 8.
11. Debug 3: Get fresh clone of repo to build solution
12. Inject solution. Same as 7 & 8.

### Expected Behavior

All the steps should allow user to open the menu, especially after using debug 3 option.

### Screenshots and/or Logs

bin\int\Release\BigBaseV2\BigBaseV2.log:
```
  Assembling src\invoker_asm.asm...
  common.cpp
  backend.cpp
  login_session.cpp
  hud_transition_state.cpp
  player_never_wanted.cpp
  spectate.cpp
  clean_player.cpp
  free_cam.cpp
  godmode.cpp
  invisibility.cpp
  no_ragdoll.cpp
  noclip.cpp
  off_radar.cpp
  police.cpp
  super_run.cpp
  local_time.cpp
  desync_kick_protection.cpp
  self_globals.cpp
  update_pointers.cpp
  disable_phone.cpp
  no_idle_kick.cpp
  auto_drive.cpp
  boost_behavior.cpp
  despawn_bypass.cpp
  drive_on_water.cpp
  fly.cpp
  horn_boost.cpp
  instant_brake.cpp
  is_targetable.cpp
  ls_customs.cpp
  rgb_paint.cpp
  seatbelt.cpp
  speedo_meter.cpp
  turn_signals.cpp
  vehicle_god.cpp
  vehicle_jump.cpp
  ammo_special_type.cpp
  cage_gun.cpp
  custom_gun_disable_control_action.cpp
  delete_gun.cpp
  force_crosshairs.cpp
  gravity_gun.cpp
  increase_damage.cpp
  infinite_ammo.cpp
  infinite_mag.cpp
  no_recoil.cpp
  no_spread.cpp
  repair_gun.cpp
  steal_vehicle_gun.cpp
  vehicle_gun.cpp
  detour_hook.cc
  fiber_pool.cpp
  file.cpp
  folder.cpp
  icons.cpp
  storopia.cpp
  gui.cpp
  button.cpp
  custom_text.cpp
  icon.cpp
  input_text_with_hint.cpp
  nav_button.cpp
  nav_item.cpp
  selectable.cpp
  small.cpp
  sub_title.cpp
  title.cpp
  current_profile_brakes.cpp
  current_profile_gearing.cpp
  current_profile_general.cpp
  current_profile_other.cpp
  current_profile_roll_centre_height.cpp
  current_profile_rollbars.cpp
  current_profile_steering.cpp
  current_profile_suspension.cpp
  current_profile_traction.cpp
  current_profile_transmission.cpp
  handling_current_profile.cpp
  handling_my_profiles.cpp
  handling_saved_profiles.cpp
  handling_search.cpp
  save_handling.cpp
  update_handling.cpp
  hooking.cpp
  swap_chain_present.cpp
  swap_chain_resizebuffers.cpp
  wndproc.cpp
  get_network_event_data.cpp
  get_label_text.cpp
  gta_thread_kill.cpp
  gta_thread_start.cpp
  assign_physical_index.cpp
  network_player_mgr.cpp
  increment_stat_event.cpp
  network_group_override.cpp
  receive_net_message.cpp
  received_clone_sync.cpp
  received_event.cpp
  script_event_handler.cpp
  send_net_info_to_lobby.cpp
  invoker.cpp
  main.cpp
  batch.cpp
  module.cpp
  pattern.cpp
  range.cpp
  native_hooks.cpp
  pointers.cpp
  renderer.cpp
  script.cpp
  script_global.cpp
  script_hook.cpp
  script_local.cpp
  script_mgr.cpp
  context_menu_service.cpp
  custom_text_callbacks.cpp
  custom_text_service.cpp
  friends_service.cpp
  globals_service.cpp
  gta_data_service.cpp
  ped_item.cpp
  vehicle_item.cpp
  weapon_item.cpp
  gui_service.cpp
  mobile_service.cpp
  model_preview_service.cpp
  notification_service.cpp
  pickup_service.cpp
  player.cpp
  player_service.cpp
  persist_car_service.cpp
  vehicle_service.cpp
  vehicle_helper.cpp
  thread_pool.cpp
  view_active_view.cpp
  view_heading.cpp
  view_navigation.cpp
  view_notifications.cpp
  view_root.cpp
  view_esp.cpp
  view_session.cpp
  view_spoofing.cpp
  view_player.cpp
  view_players.cpp
  view_mobile.cpp
  view_self.cpp
  view_teleport.cpp
  view_weapons.cpp
  view_context_menu_settings.cpp
  view_debug.cpp
  view_esp_settings.cpp
  view_gui_settings.cpp
  view_notification_settings.cpp
  view_protection_settings.cpp
  view_settings.cpp
  view_fun_vehicle.cpp
  view_lsc.cpp
  view_persist_car.cpp
  view_pv.cpp
  view_spawn_vehicle.cpp
  view_vehicle.cpp
  view_context_menu.cpp
  view_spawn_ped.cpp
  vmt_hook.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 14706 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  BigBaseV2.vcxproj -> ~\YimMenu\bin\Release\BigBaseV2.dll
```

Please let me know if there are any additional logs required.

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by xiaoxiao921** [comment]
In YimMenu unmodified the key for opening the menu is whatever the menu_toggle value is in %appdata%/bigbasev2/settings.json
That's it. If your keyboard doesn't have the key that is defined in that file just change it with anything that is listed in there https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by funnel1** [comment]
I am currently reinstalling GTA5. Will try changing settings.json once it is done. Until then, I guess we can close this issue.

**Comment by Yimura** [comment]
I'm closing this, comment if you're still having problems with this, I'll reopen the issue.
