### ISSUE TITLE
[Bug]: Detected by sigscanner

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#465]
### Describe the bug

The following string appears to be detected inside of YimMenu.dll, `ot the one that ` this appears to be a string inside one of the dependencies.

### Steps To Reproduce

Run nightly action or sigscanner on YimMenu.dll.

### Expected Behavior

Not be detected

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by MarkEcza** [comment]
Looks like it's in `g3log` 
https://github.com/YimMenu/g3log/blob/23812b5ab3c32325bd8e9f108d8c25cf3a13b86f/src/g3log.cpp#L143

**Comment by Yimura** [comment]
Lmao check the PR that references this, it fixes the problem.

**Comment by MarkEcza** [comment]
> Lmao check the PR that references this, it fixes the problem.

Yeah didn't see that until now. My bad.
