### ISSUE TITLE
[Bug]: Crash when uninjecting

### ISSUE THREAD

**Issue by Vlhss** [Yimura/YimMenu#469]
### Describe the bug

Uninjecting the menu when playing gta on steam crashes the game.

### Steps To Reproduce

1. Inject
2. Play and do whaterver you want
3. Uninject
4. Crash

### Expected Behavior

Not to crash

### Screenshots and/or Logs

Everything seems to be normal
![image](https://user-images.githubusercontent.com/106196444/195822798-c2f82d5e-93aa-4484-b4a5-78096bfbaf4e.png)

### Store

Steam

### Additional context
None

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Unable to reproduce, are you still having this problem?

**Comment by Vali0004** [comment]
> 

It was likely my bruh moment pr that required far too many fixes

**Comment by Yimura** [comment]
> > 
> 
> It was likely my bruh moment pr that required far too many fixes

This is on unloading though and not on second inject.
Also the date of this issue is pre-#470

**Comment by Vali0004** [comment]
> > It was likely my bruh moment pr that required far too many fixes
> 
> This is on unloading though and not on second inject.

Sorry, my bad, disregard my comment then

**Comment by Yimura** [comment]
Closing issue, please reply if you have more information regarding this issue @Vlhss.
I'll reopen it if it's relevant.
