### ISSUE TITLE
[Bug]: Players randomly go offline

### ISSUE THREAD

**Issue by lfengss** [Yimura/YimMenu#476]
### Problem

I found in the game that other players suddenly went offline,! Is this I was attacked? It is determined not to be my network problem!

### Solution

I found in the game that other players suddenly went offline,! Is this I was attacked? It is determined not to be my network problem!

### Reason

I found in the game that other players suddenly went offline,! Is this I was attacked? It is determined not to be my network problem!

**Comment by lfengss** [comment]
![QQ截图20221017235645](https://user-images.githubusercontent.com/87269887/196227949-e93f7a55-3372-464b-8902-93340be14aa3.png)

**Comment by Yimura** [comment]
Sorry this is an issue we are unable to fix.

This could be caused by other modders detecting the desycn kick protection built into YimMenu and breakup kicking you.
Breakup kick is something that cannot be blocked without any side effects.
