### ISSUE TITLE
[Bug]: Game crash

### ISSUE THREAD

**Issue by howdoiusekeyboard** [Yimura/YimMenu#489]
### Describe the bug

crashes the game

### Steps To Reproduce

Not sure
It was random afaik

### Expected Behavior

Not crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by howdoiusekeyboard** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/9834156/cout.log)

**Comment by Yimura** [comment]
Were you co-loading?

**Comment by howdoiusekeyboard** [comment]
No

**Comment by Yimura** [comment]
Oh you're just using Stand's injector then?

**Comment by ghost** [comment]
Are you sure you used the latest version?

**Comment by howdoiusekeyboard** [comment]
> Oh you're just using Stand's injector then?

yes

**Comment by howdoiusekeyboard** [comment]
> Are you sure you used the latest version?

hmmm yea

**Comment by ghost** [comment]
Yeah, just use Xenos or Extreme Injector.
Don't use stand skidpad.

**Comment by Yimura** [comment]
Latest YimMenu is stable, do you keep crashing?
Is it at random the crashing or does it happen the moment you inject/unload?

**Comment by howdoiusekeyboard** [comment]
I only crashed once, afaik it was 10 secs after i unchecked spoof ip thing....
I have not been using the menu since a long while and this was my first inject in a while
(i reset my pc)

**Comment by howdoiusekeyboard** [comment]
Is this fixed?

**Comment by Yimura** [comment]
Sorry haven't had this issue you're describing.

You'll have to offer more information on the matter or try to reproduce the bug to help us fix it.

**Comment by fangshun2004** [comment]
Performing an injection while performing an injection or again after the injection is complete will result in a crash Performing a second injection in bigbasev2 will result in a warning box Stop the second injection behavior Also, repeating the injection and unload actions multiple times will also cause a crash

**Comment by Yimura** [comment]
> Performing an injection while performing an injection or again after the injection is complete will result in a crash Performing a second injection in bigbasev2 will result in a warning box Stop the second injection behavior Also, repeating the injection and unload actions multiple times will also cause a crash

I don't see the problem in what you're describing, YimMenu makes modifications to the game that are only restored after unloading properly. If you inject YimMenu a second time it will not work because there are changes in memory that make the signature scanner fail in YimMenu which then causes a crash.

We're not supposed to account for the fact that YimMenu has already been injected as this is not within the bounds of how YimMenu operates.

**Comment by Yimura** [comment]
Closing this issue as stale, please comment if you've found more information that could help us.

(Even though the description of the crash is non-descriptive)
