### ISSUE TITLE
LS Customs is invisible to other players in the lobby

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#49]
**Is your feature request related to a problem? Please describe.**
Other players are unable to see you modify your vehicle, the moment you enable the LS Customs feature.

**Describe the solution you'd like**
Hooking the natives that are responsible for making the player invisible in the lobby.

**Provide Reasoning**
Cause it would be cool.

**Additional context**
I've tried hooking the following natives:
 - `BOOL NETWORK_​IS_​PLAYER_​CONCEALED(​Player player)` (never called)
 - `void NETWORK_​CONCEAL_​PLAYER(​Player player, BOOL toggle, BOOL p2)` (never called)
 - `void SET_​ENTITY_​VISIBLE(​Entity entity, BOOL toggle, BOOL unk)` (called every frame)
 - `void _​NETWORK_​SET_​ENTITY_​INVISIBLE_​TO_​NETWORK(​Entity entity, BOOL toggle)` (never called or didn't manage to catch it)
 - and many others

**Comment by Mystro69** [comment]
decompiled_scripts > am_mp_property_int.c > line:516994
it can be help

**Comment by Yimura** [comment]
#254  Implements a LS Customs 
People can just use that if they want to be visible to others when tuning.
