### ISSUE TITLE
[Request]: Rapid Fire

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#495]
### Problem

We can already change bullet impacts, but seeing the billion of projectiles flying for like the rocket launcher is much more fun

### Solution

Implement it

### Reason

Fun

**Comment by TheGreenBandit** [comment]
This is a implemented feature in SechsMenu by howdoiusekeyboard, could be taken from there

**Comment by TheGreenBandit** [comment]
> This is a implemented feature in SechsMenu by howdoiusekeyboard, could be taken from there

It goes under the name "pewpee gun"
