### ISSUE TITLE
Building fails: "Cannot use __try in functions that require object unwinding"

### ISSUE THREAD

**Issue by Panky55** [Yimura/YimMenu#51]
i keep getting this error while building yes i saw the debug thing that was pinned and i dont get what you mean by that

Error  C2712 Cannot use __try in functions that require object unwinding invoker.cpp 33

**Comment by Panky55** [comment]
nvm i seem to know how to change it to release

**Comment by Yimura** [comment]
How long did that take you to find out?
Did you even Google it before you made an issue?

**Comment by Panky55** [comment]
it took me a couple of minutes not that long

**Comment by Panky55** [comment]
how do i disable AVX512 tho i cant figure out that one now lol not sure if i support it

**Comment by Yimura** [comment]
Duplicate of #13
