### ISSUE TITLE
[Bug]: Russian characters aren't displayed correctly

### ISSUE THREAD

**Issue by tupoy-ya** [Yimura/YimMenu#512]
### Describe the bug

Russian characters are displayed as question marks. Similar to the cjk problem shown here https://www.unknowncheats.me/forum/3551540-post347.html which was fixed in #487 

### Steps To Reproduce

- Generate cache with the game language set as Russian.
- Type Russian characters into any input box. 

### Expected Behavior

Show russian characters normally.

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/72797377/197581502-64755129-25f6-4375-82b1-a6b3d330b8d2.png)

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
The way this is going I'll probably need to add South-Korean and Russian to the font texture.

**Comment by Vali0004** [comment]
Øzark moment
