### ISSUE TITLE
[Bug]: Newest version of GTA Online breaks the menu.

### ISSUE THREAD

**Issue by SpaghettDev** [Yimura/YimMenu#514]
### Describe the bug

The newest version of GTA 5 (Build 2699, Version 1.63) crashes GTA 5 and doesn't work.

### Steps To Reproduce

1. Inject YimMenu.dll
2. See Error

### Expected Behavior

To run.

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/9861405/cout.log)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by SpaghettDev** [comment]
My bad, I have a modified version of YimMenu and updated GTA 5 and it crashed, so i though it was something related to YimMenu.

**Comment by xiaoxiao921** [comment]
YimMenu unmodified does crash, we are working on it

**Comment by Yimura** [comment]
No it's an issue with the classes used by YimMenu so it's sort of related to YimMenu.

**Comment by SpaghettDev** [comment]
Oh, that's weird, cause after injecting YimMenu unmodified, it ran without any issue...

**Comment by Loko415** [comment]
update weapons and vehicles etc is broken but menu injects fine

**Comment by Loko415** [comment]
anyone else having this issue?

**Comment by Loko415** [comment]
[16:03:45][WARNING/gta_data_service.cpp:182]: Failed to load vehicles.json:
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
[16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Vehicle
[16:03:45][INFO/remote.hpp:56]: Update Error: Request timed out
[16:03:45][INFO/remote.hpp:56]: Update Error: Request timed out
[16:03:45][WARNING/gta_data_service.cpp:228]: Failed to load peds.json:
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
[16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Ped
[16:03:45][WARNING/gta_data_service.cpp:271]: Failed to load weapons.json:
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'
[16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Weapon

**Comment by Yimura** [comment]
Loko you're doing it again, please edit your old comment unless someone has commented in the meantime...

**Comment by Yimura** [comment]
> [16:03:45][WARNING/gta_data_service.cpp:182]: Failed to load vehicles.json: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<' [16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Vehicle [16:03:45][INFO/remote.hpp:56]: Update Error: Request timed out [16:03:45][INFO/remote.hpp:56]: Update Error: Request timed out [16:03:45][WARNING/gta_data_service.cpp:228]: Failed to load peds.json: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<' [16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Ped [16:03:45][WARNING/gta_data_service.cpp:271]: Failed to load weapons.json: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<' [16:03:45][INFO/gta_data_service.cpp:156]: Data updated: Weapon

Make a new issue regarding this, it's unrelated to this issue.
