### ISSUE TITLE
[Bug]: Vehicle / Ped Spawn Crash

### ISSUE THREAD

**Issue by JohnXyy** [Yimura/YimMenu#517]
### Describe the bug

Spawning a vehicle or a ped will cause game crash.

### Steps To Reproduce

1. Start Yim
2. Open Vehicle Spawner
3. Spawn some cars..

### Expected Behavior

Car spawn should work.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Other (please mention in "Additional context")

### Additional context

Tested with Rockstar and Steam Version of GTAV

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Yeah seems I forgot to update the tlsContext which is causing the crashes.

After [this action](https://github.com/YimMenu/YimMenu/actions/runs/3324142054) has finished running can you download the [latest DLL](https://github.com/YimMenu/YimMenu/releases/latest) of YimMenu.

**Comment by JohnXyy** [comment]
> 

Worked, thx!
