### ISSUE TITLE
Feature Request: Bring back friends list in the player list

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#52]
**Is your feature request related to a problem? Please describe.**
The player list no longer contains a list of friends

**Describe the solution you'd like**
Bring the friends list back!

I want to take a look at how the friends list is populated in the game and compare like this if CNetGamePlayers are friends or not.

**Comment by SkiddyToast** [comment]
There's a struct that contains 250(I think) friends.
It looks like this:
```c++
class CFriend
{
public:
	char pad_0000[128]; //0x0000
	char name[20]; //0x0080
	char pad_0094[36]; //0x0094
	uint64_t rockstar_id; //0x00B8
	char pad_00C0[4]; //0x00C0
	int32_t online; //0x00C4
	char pad_00C8[304]; //0x00C8
	int32_t multiplayer; //0x01F8
	char pad_01FC[4]; //0x01FC
}; //Size: 0x0200

static_assert(sizeof(CFriend) == 0x200);

class CFriendList
{
public:
	CFriend friends[250];
};
```
I could only find a couple of things from it, so there's probably plenty more that you could get from this struct.

You can get the friends list struct and friend count from these signatures (for Epic/Social Club, haven't checked but these should be the same for Steam):
```c++
//Friend List
main_batch.add("FL", "48 03 0D ? ? ? ? E9 ? ? ? ? 48 8D 05", [this](memory::handle ptr)
{
	m_friend_list = ptr.add(3).rip().as<CFriendList**>();
});

//Friend Count
main_batch.add("FC", "3B 0D ? ? ? ? 73 13 48 63 C9", [this](memory::handle ptr)
{
	m_friend_count = ptr.add(2).rip().as<uint32_t*>();
});
```
You could probably use RIDs from this to check for friends. That's all the information I know, so good luck!

**Comment by Yimura** [comment]
Ye I already completely reversed that lol, with the signature of your friend_count landing inside the same native I used as a starting point:
```c
const char *__fastcall NETWORK_GET_FRIEND_NAME(unsigned int a1)
{
  const char *result; // rax

  if ( a1 >= friends_count )
    result = "*****";
  else
    result = (const char *)get_name_from_friend_struct(friends_list + ((signed __int64)(signed int)a1 << 9));
  return result;
}
```

I got the following data, you can also abuse the friends list as a R*ID joiner, I won't say exactly how but it isn't that hard if you fiddle a bit with the values:
```cpp
class FriendInfo
{
public:
	char pad_0000[128]; //0x0000 - path to the user's profile image, no idea how much is allocated for it
	char m_name[20]; //0x0080
	char pad_0094[36]; //0x0094
	uint64_t m_rockstar_id; //0x00B8
	uint8_t unk_0xC0; //0x00C0
	char pad_00C1[3]; //0x00C1
	uint32_t m_friend_state; //0x00C4
	char pad_00C8[304]; //0x00C8
	uint32_t m_is_joinable; //0x01F8
	char pad_01FC[4]; //0x01FC
}; //Size: 0x0200
static_assert(sizeof(FriendInfo) == 0x200);

class FriendList
{
public:
	class FriendInfo m_data[250]; //0x0000
}; //Size: 0x1F400
static_assert(sizeof(FriendList) == 0x1F400);

class FriendRegistry
{
public:
	uint32_t m_friend_count; //0x0000
	char pad_0004[8]; //0x0004
	class FriendList *m_friends_list; //0x000C
}; //Size: 0x0014
static_assert(sizeof(FriendRegistry) == 0x14);
```

For the signatures I'll probably do something like the following:
```cpp
//Friend Registry
main_batch.add("FC", "3B 0D ? ? ? ? 73 13 48 63 C9", [this](memory::handle ptr)
{
	m_friend_registry = ptr.add(2).rip().as<FriendRegistry*>();
});
```

I can then make some kind of service to wrap around to nicely access friends.

**Comment by Yimura** [comment]
Added in https://github.com/Yimura/YimMenu/commit/13b37fa5a5eff1caa5714e102eed6b5cbdd1ee28
