### ISSUE TITLE
[Request]: kick out 

### ISSUE THREAD

**Issue by Yunconnect** [Yimura/YimMenu#540]
### Problem

I wish YimMenu could add a kick out feature

### Solution

Send other players "rage: : eNetMessage: : CMsgRemoveGamersFromSessionCmd:" events

### Reason

Kick out the other advertising machines and Kick out other players who play tricks on others.
While this may cause some users to abuse the feature, I don't think people are bored enough to kick others out for fun.

**Comment by MarkEcza** [comment]
Doesn't this fall under the "toxic" category, also for advertising i believe it's just better to block the chat messages that contain certain words, can be done in get chat data IIRC.
