### ISSUE TITLE
[Request]: Fight against mod players

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#552]
### Problem

Some mod players sent me a lot of events , Causes the game to crash
Or send some events that can't be intercepted

### Solution

I hope to fight back.
Sometimes offense is the best defense

### Reason

If you don't attack, the opponent will keep attacking until you can't play

**Comment by GeopJr** [comment]
There are no current plans on adding toxic or recovery features for multiple reasons. Refer to: #237.

If you have further feedback on this, that discussion is probably the best place to submit it.

**Comment by maybegreat48** [comment]
Can you give examples of events that "cannot be intercepted"?
