### ISSUE TITLE
Sig scan

### ISSUE THREAD

**Issue by XXTOUCOXX** [Yimura/YimMenu#557]
So when I use sig scanner and sig scan this menu it gives me nothing after this update. How should I check for the detection.Is sig scanner outdated?

**Comment by Yimura** [comment]
The sigscanner still functions as in it'll notify you if there are strings / byte arrays found in the DLL that exist in the bonus list.

That it'll get you banned or cause transactions/metrics to be sent out that's a different question.

**Comment by XXTOUCOXX** [comment]
Ok thanks
