### ISSUE TITLE
[Bug]:  Vehicle "Deveste Eight" Causing crash

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#559]
### Describe the bug

at the time to spawn the vehicle the game crash idk if its related to a dlc that its no skiping on cache or the online vehicles on storymode bypass but as far as i remember before the updated classes everything works fine so idk../

### Steps To Reproduce

Open menu
Go to vehicle spawner
Spawn the vehicle
Crash

### Expected Behavior

Spawn with no problem

### Screenshots and/or Logs

```
Dumping registers:

RAX: 0xC6FC61F908
RCX: 0x21D69E00B80
RDX: 0x21D5CB16680
RBX: 0x0
RSI: 0x21D5CB17080
RDI: 0x0
RSP: 0xC6FC61F810
RBP: 0xC6FC61F8A9
R8: 0xC6FC61F9D0
R9: 0x0
R10: 0x0
R11: 0xC6FC61F840
R12: 0x21D69E00B80
R13: 0x21D5CB16680
R14: 0x14
R15: 0x0

stack dump [0] D:\Program Files (x86)\GTAV\GTA5.exe+0x8E5DEA 0x7FF6A6185DEA
stack dump [1] D:\Program Files (x86)\GTAV\GTA5.exe+0x534442 0x7FF6A5DD4442
stack dump [2] D:\Program Files (x86)\GTAV\GTA5.exe+0x161DA91 0x7FF6A6EBDA91
stack dump [3] D:\Program Files (x86)\GTAV\GTA5.exe+0x161D9AE 0x7FF6A6EBD9AE
stack dump [4] D:\Program Files (x86)\GTAV\GTA5.exe+0x15F888D 0x7FF6A6E9888D
stack dump [5] D:\Program Files (x86)\GTAV\GTA5.exe+0x15F922A 0x7FF6A6E9922A
stack dump [6] D:\Program Files (x86)\GTAV\GTA5.exe+0x1601E4A 0x7FF6A6EA1E4A
stack dump [7] D:\Program Files (x86)\GTAV\GTA5.exe+0x12C5642 0x7FF6A6B65642
stack dump [8] C:\WINDOWS\System32\KERNEL32.DLL+0x1244D BaseThreadInitThunk
stack dump [9] C:\WINDOWS\SYSTEM32\ntdll.dll+0x5DF78 RtlUserThreadStart
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by xiaoxiao921** [comment]
This crash is caused by invalid MODS, if you don't want to crash disable spawn maxed

**Comment by xiaoxiao921** [comment]
From SkiddyToast
```
just check if a1+0xD8 is a nullptr
```
```
E8 ? ? ? ? 40 88 7C 24 40 49 89 9C 24 D8 00 00 00 .add(1).rip()
```
Now someone just need to implement it

**Comment by who-care123** [comment]
Name: sentinel | Hash: 0x50732C82
Name: deveste | Hash: 0x5EE005DA
Name: banshee | Hash: 0xC1E908D2
Name: hakuchou2 | Hash: 0xF0C2A91F
Name: brioso | Hash: 0x5C55CB39
Name: turismo2 | Hash: 0xC575DF11

These 6 vehicles have invalid mods.
