### ISSUE TITLE
Kicking/Crashing/Removing player from session causes crash

### ISSUE THREAD

**Issue by CSharpDaddy** [Yimura/YimMenu#56]
Open Player Window => Toxic =>

By
- Kicking
- Crashing
- Removing player from PlayerMgr

the game crashes.

Note by Yimura:

This can happen while you're drawing player info in UI elements without checking it it's valid or using the player instance from player service without calling #valid before acting on said player.

**Comment by Yimura** [comment]
Please don't edit out details, keep the post as detailed as possible, future people might find your issue/solution helpful.
