### ISSUE TITLE
[Help] CMake Problems

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#563]
While trying to build the Project i got this Errror and idk what the Problem is ¯\_(ツ)_/¯

```
$ cmake --build build --config Release --target ALL_BUILD
MSBuild version 17.4.0+18d5aef85 for .NET Framework
MSBUILD : error MSB1009: The project file does not exist.
Switch: ALL_BUILD.vcxproj
```

**Comment by Aure7138** [comment]
looks like the vendor is not downloaded properly

**Comment by Yimura** [comment]
I personally use Visual Studio Code to compile YimMenu, it handles everything for me.

This is the full command that VS Code uses to generate Release w/ YimMenu target:
```bash
cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Sc:/Users/u/Documents/Coding/cpp/YimMenu -Bc:/Users/u/Documents/Coding/cpp/YimMenu/build -G "Visual Studio 17 2022" -T host=x64 -A x64
```

**Comment by Sheeeeit** [comment]
Two questions:
1) Where to find the compiled file (I may not be able to do this because everything ends up with an error, hence the next question)
2) Constantly gives out the following lines:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4100	'log_level': unreferenced formal parameter	g3log	C:\Users\Cat\Desktop\YimMenu\build\_deps\g3log-src\src\loglevels.cpp	130	
Error	C2712	Cannot use __try in functions that require object unwinding	YimMenu	C:\Users\Cat\Desktop\YimMenu\src\invoker.cpp	37	
Error	C2220	the following warning is treated as an error	YimMenu	C:\Users\Cat\Desktop\YimMenu\src\services\gui\gui_service.cpp	19	
Warning	C4172	returning address of local variable or temporary: tab_none	YimMenu	C:\Users\Cat\Desktop\YimMenu\src\services\gui\gui_service.cpp	19	
```

**Comment by Yimura** [comment]
Seems to me you're building in Debug which is why you're getting those two errors.

Try switching to any of the other build variants:
![image](https://user-images.githubusercontent.com/24669514/201402004-6199d9b2-a8dd-4e6d-a3f2-5ddba2045797.png)

**Comment by Sheeeeit** [comment]
Thank you, the change to Release helped, but the only question remains as to what Visio gives me:
```
Severity Code Description Project File Line Suppression State
Warning C4100 'log_level': unreferenced formal parameter g3log C:\Users\Cat\Desktop\YimMenu\build\_deps\g3log-src\src\loglevels.cpp 130	
```
Is this critical or is it not worth paying attention to?

**Comment by Yimura** [comment]
That's an issue with g3log that has existed since forever, it hasn't caused us any issues ever, so we never bothered fixing it.
