### ISSUE TITLE
Clear log

### ISSUE THREAD

**Issue by GibsonHF** [Yimura/YimMenu#57]
**Is your feature request related to a problem? Please describe.**
Clear log button

**Describe the solution you'd like**
When logging script events for long periods of time the gui tends to lag unless you minimize the log

**Provide Reasoning**
when logging for a while ends up crashing due to overflow

**Comment by Yimura** [comment]
I will probably stop using the current method of logging and start using the old external console window to log stuff  to.

**Comment by Yimura** [comment]
I will still be reverting to the old logging method, rather I will improve it. I'm currently working on an internal mod menu template which has a really nice logging method.

**Comment by Yimura** [comment]
I modified the logger to use an attached console window.

I will be working on detaching and attaching it dynamically.

Modified with https://github.com/Yimura/YimMenu/commit/595c8d4c76ad0bc29f9a91ac8aff788ed9a6c2dd
