### ISSUE TITLE
[Request]: discord server

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#577]
### Problem

old discord server terminated. Discord was a nice community

### Solution

create a new discord server

### Reason

socialise and help eachother with issues

**Comment by Yimura** [comment]
Not up for debate, please join the Matrix server instead.

People are actually active on there so if you wish to engage with us go there.

**Comment by tupoy-ya** [comment]
> Not up for debate, please join the Matrix server instead.
>
> People are actually active on there so if you wish to engage with us go there.

So if you aren't planning to bridge discord again why not enable encryption in matrix?
Related:
> @geopsie:matrix.org
> [🤷](https://matrix.to/#/!lBBMVBvodcCNBgJVAe:matrix.org/$YM8RsjtH7L6FxVepLQw5XrSJyf8gEGHJDiiMnkPa2jo?via=matrix.org&via=arcticfoxes.net)
>[we can enable encryption ig](https://matrix.to/#/!lBBMVBvodcCNBgJVAe:matrix.org/$hYbWYMNfJ-755T8jJfPKxh7XmUVMvgfBRejnBlzQdYk?via=matrix.org&via=arcticfoxes.net)
