### ISSUE TITLE
[Bug]: Access denied

### ISSUE THREAD

**Issue by Giinsho** [Yimura/YimMenu#582]
### Describe the bug

Access Denied while trying to release/debug  solution.
Visual Studio 2022
Paths:  

1. YimMenu\build\x64\Debug\ALL_BUILD 
2. YimMenu\build\x64\Release\ALL_BUILD

### Steps To Reproduce

1. gitclone
2. mkdir build && cd build (inside cloned repo folder)
3. cmake ..
4. open solution
5. release/debug solution

### Expected Behavior

Build without last error.

### Screenshots and/or Logs

![release](https://user-images.githubusercontent.com/78929935/201445310-362f7930-dc49-49cf-8ca6-07143fdc7bc1.png)
![image](https://user-images.githubusercontent.com/78929935/201445599-8869a899-227d-494d-8fb5-1d81d81bc700.png)

### Store

Other (please mention in "Additional context")

### Additional context

Tried:

1. Several different places
2. Reinstal VS 2022
3. Check read only files
4. Started VS as Administrator
5. Swap folder, make new with git clone [newest version] at different location than C:
6. Make :
- attrib -r +s “path + name”
- sfc /scannow
- dism /online /cleanup-image /restorehealth
- net user administrator /active:yes
7. Check permission for user

### Build

- [X] I used YimMenu unmodified

**Comment by ghost** [comment]
sounds like cmake. no idea why the switch was made. try an older source of yimmenu (go like 50 up commit history) and try again

**Comment by xiaoxiao921** [comment]
An actual screenshot of the error would be helpful
Also try opening the git cloned folder through VS 
![image](https://user-images.githubusercontent.com/837334/201483841-759389fc-f486-4758-a76d-fcd3f55f21b5.png)
Its supposed to handle CMake directly when doing that

**Comment by tupoy-ya** [comment]
Had this problem when generating projects from `cygwin` launched as "Administrator"
Did you run `cmake` as administrator?

**Comment by Giinsho** [comment]
@FireFox101889: tested with older versions before
@tupoy-ya : yes all done with admin permissions
@xiaoxiao921 **### method solved my problem**:
Steps: 
1. Open VS 2022 - admin 
2. Open a local folder
3. Show all folders
4. Set project build -> Release



- Tested with the newest Git version, and older one
- Got same error only once but after Rebuild again -> error gone 

- Also got: Cannot use __try in functions that require object unwinding -> only in Debug build
function: `end_call(), line:37`
file: invoker.cpp

Nicely done menu. Thanks for help guys

**Comment by tupoy-ya** [comment]
You should run it as normal user instead of admin
