### ISSUE TITLE
[Bug]: The cmake is stuck when running to g3log

### ISSUE THREAD

**Issue by penguin239** [Yimura/YimMenu#584]
### Describe the bug

The cmake is stuck when running to g3log

### Steps To Reproduce

cmake ..

### Expected Behavior

fine

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
How long did you wait at the g3log step? I know that for me personally it also takes a while.

**Comment by penguin239** [comment]
Since the update, I have never successfully compiled, whether CMake or VS

**Comment by tupoy-ya** [comment]
Well it looks like i successfully failed at "Don't increase amount of people failing to build YimMenu by 90%"

**Comment by Yimura** [comment]
@Liyn13, did you manage to fix your issue?

**Comment by Yimura** [comment]
Will reopen this issue if there's a response from the original author.
