### ISSUE TITLE
[Request]: fix cmake building trashing folder hierarchy

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#586]
### Problem

Would be cool if cmake generated stuff would be put into a folder called cmake_build or similar, I'm seeing people left and right ending up with some awful folder hierarchy that make the dev experience very much not desirable 

### Solution

Modify cmake / fix it with a build script maybe

### Reason

Enhance the dev experience

**Comment by xiaoxiao921** [comment]
![Uploading explorer_JugCCLVKNP.png…]()

**Comment by xiaoxiao921** [comment]
![explorer_JugCCLVKNP](https://user-images.githubusercontent.com/837334/201476938-3509c208-f080-4dfd-8515-bd8b2838e1be.png)

**Comment by tupoy-ya** [comment]
Why people use `cmake .` instead of `mkdir build && cd build` and then running `cmake ..`?

**Comment by xiaoxiao921** [comment]
Giving people the ability of messing this up in the first place should be fixed

**Comment by tupoy-ya** [comment]
I guess we should add `script.bat` back then and maybe also add `script.sh`.

**Comment by xiaoxiao921** [comment]
Yeah I totally agree, before it was dead simple as you'd just click the bat and end up with a sln file directly with much less way of messing it up

**Comment by pelecanidae** [comment]
Why is an `sln` needed anyway? Can't VS open CMake projects now?

**Comment by xiaoxiao921** [comment]
It seems you are right, apparently you can just have VS "open directory" and it'll handle the CMake file automatically, I just didnt try myself so I can't confirm.

**Comment by GeopJr** [comment]
Is there a reason we went with `mkdir x && cd x && cmake ..` instead of `cmake -Bbuild` like the ci?

**Comment by tupoy-ya** [comment]
> Is there a reason we went with `mkdir x && cd x && cmake ..` instead of `cmake -Bbuild` like the ci?

Because most READMEs use `mkdir build && cd build` `cmake ..` [ex. g3log](https://github.com/YimMenu/g3log/blob/master/docs/building.md) and that's what i personally do when i clone a CMake repository.

It's also easier to understand then `cmake -Bbuild`.

**Comment by GeopJr** [comment]
Since it seems to have caused some confusion, perhaps we could include both options?

e.g.
```
cmake -Bbuild
```

or

```
mkdir build
cd build
cmake ..
```

**Comment by tupoy-ya** [comment]
Then we will need to have 2 versions of every `cmake ..` instance in the README.
