### ISSUE TITLE
[Request]: UI Scaling

### ISSUE THREAD

**Issue by H4ckerxx44** [Yimura/YimMenu#587]
### Problem

I use a 4k screen to play and the menu is pretty small on the screen

### Solution

Implement some sort of scaling.

Either by multiplication (2x, 4x, ...), or by percentage (150% scaling, 275% scaling, ...)

### Reason

On 4k screens, the menu is pretty small

**Comment by xiaoxiao921** [comment]
A barebone scaling is easily doable through a ImGui slider and something like this afaik https://github.com/ocornut/imgui/issues/2442#issuecomment-487364993

Most notably playing with these 2
```cpp
ImGui::GetStyle().ScaleAllSizes(relative_scale);
ImGui::GetIO().FontGlobalScale = relative_scale;
```
