### ISSUE TITLE
Can't build due to missing FriendRegistry

### ISSUE THREAD

**Issue by cristyanul** [Yimura/YimMenu#59]
FriendRegistry.hpp is missing

**Comment by Yimura** [comment]
Try pulling latest version of the menu.

**Comment by cristyanul** [comment]
I did, but I can't find FriendRegistry.hpp file, where's that supposed to be?

**Comment by Yimura** [comment]
Open command window in the directory of YimMenu.

```bash
cd vendor/GTAV-Classes

git pull
git checkout d8c62840df3634d9f4dbc848d5720ebc95f8d778
```

Tell me if this works...

**Comment by cristyanul** [comment]
It did, thanks!
