### ISSUE TITLE
[Bug]: spawn bodyguard crash

### ISSUE THREAD

**Issue by woruteyqi** [Yimura/YimMenu#591]
### Describe the bug

when spawn a bodyguard game will crash

### Steps To Reproduce
open game
inject dll and go session 
spawn bodyguard
crash

### Expected Behavior

fix it

### Screenshots and/or Logs

```
<paste your logs here>
```
[11-13-2022-18-24-13_cout.log](https://github.com/YimMenu/YimMenu/files/9996963/11-13-2022-18-24-13_cout.log)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by Aure7138** [comment]
which ped model

**Comment by Aure7138** [comment]
> open game
> inject dll and go session
> spawn bodyguard
> crash
i did all these, i didnt crash, latest version
[img]https://i.imgur.com/MXLZVZv.png[/img]

**Comment by woruteyqi** [comment]
> which ped model

such as Lester or any other npc

**Comment by woruteyqi** [comment]
> > open game
> > inject dll and go session
> > spawn bodyguard
> > crash
> > i did all these, i didnt crash, latest version
> > [img][https://i.imgur.com/MXLZVZv.png[/img]](https://i.imgur.com/MXLZVZv.png%5B/img%5D)

spawn self is work , but other will crash
https://user-images.githubusercontent.com/20475872/201609258-d97a44b1-80f8-4535-a987-7d1ba7ad19c2.mp4

**Comment by Aure7138** [comment]
yeah, same, didnt crash. https://i.imgur.com/2qrxJw9.png
If you still crash, make sure you are using the latest version(https://github.com/YimMenu/YimMenu/releases) and send relevant logs

**Comment by Aure7138** [comment]
You're right, I could be wrong, I'm having the same crash stack as you, thanks for someone's help I think the crash is giving too many weapons or invalid weapons to the bodyguard, the crash seems to happen when accessing the CAmmoInfo node

**Comment by woruteyqi** [comment]
> You're right, I could be wrong, I'm having the same crash stack as you, thanks for someone's help I think the crash is giving too many weapons or invalid weapons to the bodyguard, the crash seems to happen when accessing the CAmmoInfo node

https://imgur.com/a/hfuVvkK
it's work thx, I chose a single weapon so didn't crash
