### ISSUE TITLE
[Bug]: A large number of the same events crash the game

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#601]
### Describe the bug

Another modder sent a ton of events that crashed my game

### Steps To Reproduce

Another modder sent a ton of events that crashed my game

### Expected Behavior

Events are well blocked and the game doesn't crash

### Screenshots and/or Logs

[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 12 Tree name: TRAILER From: other-player
[10:20:03][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 8 Tree name: PICKUP_PLACEMENT From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 11 Tree name: PLAYER From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 7 Tree name: PICKUP From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 6 Tree name: PED From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 2 Tree name: BOAT From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 8 Tree name: PICKUP_PLACEMENT From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 3 Tree name: DOOR From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 4 Tree name: HELI From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 8 Tree name: PICKUP_PLACEMENT From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 1 Tree name: BIKE From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 10 Tree name: SUBMARINE From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 13 Tree name: TRAIN From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 2 Tree name: BOAT From: other-player
[10:20:04][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 2 Tree name: BOAT From: other-player
[10:20:05][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 8 Tree name: PICKUP_PLACEMENT From: other-player
[10:20:05][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 8 Tree name: PICKUP_PLACEMENT From: other-player
[10:20:05][WARNING/received_clone_sync.cpp:364]: Mismatch sync: Type: 0 Tree name: AUTOMOBILE From: other-player
2022/11/16 10:20:05 276331

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 11780

*******	STACKDUMP *******

Loaded Modules:
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FFAABB80000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FFA757E0000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FFA88C00000 Size: 0xA14000
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2210.6-0\MpOav.dll Base Address: 0x7FFABE010000 Size: 0x7B000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FFACB130000 Size: 0x182000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FFAD10C0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FFAD1190000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FFAB2830000 Size: 0x5E000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FFACECB0000 Size: 0xF2000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FFACE940000 Size: 0x35E000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FFAB2970000 Size: 0x31000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FFACD490000 Size: 0x263000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FFA89620000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll Base Address: 0x7FFACD700000 Size: 0x45D000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FFAB8540000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FFAD0C40000 Size: 0xCA000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FFAAC590000 Size: 0x9C000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FFABDC90000 Size: 0x27F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FFAB99A0000 Size: 0x32B000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FFACC280000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FFAD0010000 Size: 0xD000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FFAD0BF0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FFAACDD0000 Size: 0x84000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FFAAC940000 Size: 0x48E000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FFAAC780000 Size: 0x1BC000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FFAA9300000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FFAB8880000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FFAD13C0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FFAAD4B0000 Size: 0x8E000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FFABB220000 Size: 0x19000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FFAD11B0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FFACD300000 Size: 0x125000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FFACCE00000 Size: 0xF6000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FFAB8310000 Size: 0x34000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FFAC7D10000 Size: 0x19000
C:\WINDOWS\SYSTEM32\SSPICLI.DLL Base Address: 0x7FFAD1690000 Size: 0x32000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FFABB1F0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FFAA4370000 Size: 0x2F5000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FFAD0BD0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FFAD16D0000 Size: 0x2E000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FFAB7DF0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FFABAD70000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FFACD2F0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FFAC9710000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FFAC9DD0000 Size: 0x10C000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FFABA3C0000 Size: 0x4D9000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FFAC0280000 Size: 0x27000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FFACAB30000 Size: 0xB000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FFABF2A0000 Size: 0x98000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FFAD0640000 Size: 0x64000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FFAD0960000 Size: 0x19000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FFACD470000 Size: 0x14000
C:\WINDOWS\SYSTEM32\Wldp.dll Base Address: 0x7FFAD1150000 Size: 0x30000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FFABF1F0000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FFACB880000 Size: 0xA000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FFABAD90000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FFAC96D0000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FFABB780000 Size: 0xD000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FFAC3B90000 Size: 0x1CF000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FFA89D90000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FFAAB400000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FFAC86A0000 Size: 0x1E4000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FFAD1580000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FFACA7E0000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FFACA800000 Size: 0x17000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FFAC92C0000 Size: 0x148000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FFACF490000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FFACBC70000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FFAD0050000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FFABF550000 Size: 0x24000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FFAD0020000 Size: 0x23000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FFAC3F70000 Size: 0x2B1000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FFAC56B0000 Size: 0x152000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FFACF670000 Size: 0x12000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FFABB760000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FFAB9550000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FFAB9560000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FFABF540000 Size: 0xB000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FFAD1210000 Size: 0x27000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FFAD0C30000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FFAD40D0000 Size: 0x1F8000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FFAD0920000 Size: 0x33000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FFAA01D0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FFAD0D60000 Size: 0x4B000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FFAD1710000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FFACF270000 Size: 0x14000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FFABF630000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FFAC5810000 Size: 0xF9000
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll Base Address: 0x7FFACA380000 Size: 0x200000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FFABF6E0000 Size: 0x1ED000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FFAAE190000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FFACD020000 Size: 0x65000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FFACF870000 Size: 0x792000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FFABA8F0000 Size: 0x26000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FFACE270000 Size: 0x154000
C:\WINDOWS\SYSTEM32\xinput1_4.dll Base Address: 0x7FFABF5D0000 Size: 0x11000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FFAD2290000 Size: 0xDA000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FFAD1B30000 Size: 0x156000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll Base Address: 0x7FFAC5430000 Size: 0x117000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvwgf2umx.dll Base Address: 0x7FFAC0520000 Size: 0x3664000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FFAD2470000 Size: 0x2B000
C:\WINDOWS\System32\IMM32.dll Base Address: 0x7FFAD2250000 Size: 0x32000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FFAD3AE0000 Size: 0xBF000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FFAD17D0000 Size: 0x2D2000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FFACAC50000 Size: 0x85000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FFAD3D50000 Size: 0x115000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FFAD3D40000 Size: 0x8000
C:\WINDOWS\System32\Normaliz.dll Base Address: 0x7FFAD2F40000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FFAD2E70000 Size: 0xCD000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FFAD3BA0000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FFAD2910000 Size: 0x125000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FFAD24A0000 Size: 0x468000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FFAD2F50000 Size: 0x743000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FFAD3CE0000 Size: 0x55000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FFAD3E70000 Size: 0x19D000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FFAD1F70000 Size: 0x6A000
C:\WINDOWS\System32\WLDAP32.dll Base Address: 0x7FFAD2A40000 Size: 0x56000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FFAD2E00000 Size: 0x6B000
C:\WINDOWS\System32\advapi32.dll Base Address: 0x7FFAD3A30000 Size: 0xAE000
C:\WINDOWS\System32\bcrypt.dll Base Address: 0x7FFAD1AB0000 Size: 0x27000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FFAD1FE0000 Size: 0x82000
C:\WINDOWS\System32\cfgmgr32.dll Base Address: 0x7FFAD1AE0000 Size: 0x4E000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FFAD3BB0000 Size: 0xAF000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FFAD2AA0000 Size: 0x354000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FFAC7F00000 Size: 0x80000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FFAD1C90000 Size: 0x10F000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FFAD3CC0000 Size: 0x1D000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FFAD1ED0000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FFAD3900000 Size: 0x9E000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FFAD2120000 Size: 0x12A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FFAD23D0000 Size: 0x9C000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FFAD36A0000 Size: 0xAD000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FFAD1DA0000 Size: 0x100000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FFAD1EA0000 Size: 0x22000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FFAC62F0000 Size: 0x12000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll Base Address: 0x7FFAB9EC0000 Size: 0xB0000
C:\WINDOWS\system32\NLAapi.dll Base Address: 0x7FFACD090000 Size: 0x1D000
C:\WINDOWS\system32\Oleacc.dll Base Address: 0x7FFABF230000 Size: 0x66000
C:\WINDOWS\system32\XAudio2_7.dll Base Address: 0x7FFA9F470000 Size: 0x8B000
C:\WINDOWS\system32\mswsock.dll Base Address: 0x7FFAD0F30000 Size: 0x6A000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FFAC78C0000 Size: 0x17000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FFAC5A60000 Size: 0x761000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FFAC6310000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FFAD0800000 Size: 0x34000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FFACF1A0000 Size: 0x9E000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FFACC250000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FFABAFB0000 Size: 0x51000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FFAD03B0000 Size: 0xA1000
C:\Windows\System32\WindowManagementAPI.dll Base Address: 0x7FFACA820000 Size: 0xA1000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FFAC5910000 Size: 0x141000
C:\Windows\System32\fwbase.dll Base Address: 0x7FFAD0340000 Size: 0x3A000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FFAC88F0000 Size: 0xA000
D:\epicgame\GTAV\EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA72880000 Size: 0xA18000
D:\epicgame\GTAV\GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA73C20000 Size: 0x3CC000
D:\epicgame\GTAV\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFABB7B0000 Size: 0x1C000
D:\epicgame\GTAV\GTA5.exe Base Address: 0x7FF7CBFF0000 Size: 0x3D20600
D:\epicgame\GTAV\bink2w64.dll Base Address: 0x7FFAA9410000 Size: 0x8D000
D:\gta5\YimMenu.dll Base Address: 0x7FFA70940000 Size: 0x1F0000

Dumping registers:

RAX: 0x3003B88800000002
RCX: 0x2290B537038
RDX: 0x2
RBX: 0xD7E41C0B5C
RSI: 0x0
RDI: 0xD7E41C0B68
RSP: 0xD7E41C08A0
RBP: 0x2
R8:  0x2
R9:  0x2290B5814E0
R10: 0xD7E41C0B91
R11: 0x0
R12: 0x2
R13: 0x2290B5814E0
R14: 0xD7E41C0B18
R15: 0x2290B537038

stack dump [0]	 D:\epicgame\GTAV\GTA5.exe+0x168886B 0x7FF7CD67886B
stack dump [1]	 D:\epicgame\GTAV\GTA5.exe+0x111F126 0x7FF7CD10F126
stack dump [2]	 D:\epicgame\GTAV\GTA5.exe+0x168886E 0x7FF7CD67886E
stack dump [3]	 D:\epicgame\GTAV\GTA5.exe+0x111F126 0x7FF7CD10F126
stack dump [4]	 D:\epicgame\GTAV\GTA5.exe+0x16889BD 0x7FF7CD6789BD
stack dump [5]	 D:\epicgame\GTAV\GTA5.exe+0x1682E1F 0x7FF7CD672E1F
stack dump [6]	 D:\epicgame\GTAV\GTA5.exe+0x168700A 0x7FF7CD67700A
stack dump [7]	 D:\epicgame\GTAV\GTA5.exe+0x111452E 0x7FF7CD10452E
stack dump [8]	 D:\epicgame\GTAV\GTA5.exe+0x1685B5C 0x7FF7CD675B5C
stack dump [9]	 D:\epicgame\GTAV\GTA5.exe+0x1113D39 0x7FF7CD103D39
stack dump [10]	 D:\epicgame\GTAV\GTA5.exe+0x108B996 0x7FF7CD07B996
stack dump [11]	 D:\epicgame\GTAV\GTA5.exe+0x15D10C1 0x7FF7CD5C10C1
stack dump [12]	 D:\epicgame\GTAV\GTA5.exe+0x15D08EF 0x7FF7CD5C08EF
stack dump [13]	 D:\epicgame\GTAV\GTA5.exe+0x271AA 0x7FF7CC0171AA
stack dump [14]	 D:\epicgame\GTAV\GTA5.exe+0x208BF 0x7FF7CC0108BF
stack dump [15]	 D:\epicgame\GTAV\GTA5.exe+0x15D04F8 0x7FF7CD5C04F8
stack dump [16]	 D:\epicgame\GTAV\GTA5.exe+0x1494 0x7FF7CBFF1494
stack dump [17]	 D:\epicgame\GTAV\GTA5.exe+0x12BBE0F 0x7FF7CD2ABE0F
stack dump [18]	 D:\epicgame\GTAV\GTA5.exe+0x17C3988 0x7FF7CD7B3988
stack dump [19]	 C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [20]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by SkiddyToast** [comment]
This crash is happening in a `rage::netSyncParentNode` virtual function and happens when `node+0x38` is not null, but invalid.

Here's the assembly of where it crashes
```asm
call    qword ptr [rax+30h]
```
