### ISSUE TITLE
[Request]: Verified Icon in each chat message

### ISSUE THREAD

**Issue by RainerZufall187** [Yimura/YimMenu#615]
### Solution

Would be cool to have an checkbox where you can automatically put `¦` in front of each of your chat messages

### Reason

why not? ok

**Comment by ghost** [comment]
you will need to intercept the function that sends your messages and edit the message content. only logical way to go about it.

**Comment by RainerZufall187** [comment]
yes what else?

> you will need to intercept the function that sends your messages and edit the message content. only logical way to go about it.
@FireFox101889

**Comment by Yimura** [comment]
Probably not possible because of the strict character limits imposed by R* on chat.
