### ISSUE TITLE
[Bug]: Receiving many of the same events in a short period of time causes the game to crash

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#616]
### Describe the bug

Receiving many of the same events in a short period of time causes the game to crash

### Steps To Reproduce

Receiving many of the same events in a short period of time causes the game to crash

### Expected Behavior

Will not crash

### Screenshots and/or Logs

[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked incorrect object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds decorator count crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds decorator count crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
[14:32:34][WARNING/notify.hpp:22]: Blocked out of bounds object type crash from player (216606654)
2022/11/19 14:32:34 935855

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 11968

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FFCED3C0000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FFCBC060000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FFCC4100000 Size: 0xA14000
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2210.6-0\MpOav.dll Base Address: 0x7FFD0CC90000 Size: 0x7B000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FFD13B90000 Size: 0x182000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FFD19600000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FFD195E0000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FFD03A40000 Size: 0x5E000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FFD17280000 Size: 0xF2000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FFD16E20000 Size: 0x35E000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FFCFD1D0000 Size: 0x31000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FFD16350000 Size: 0x263000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FFCED730000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll Base Address: 0x7FFD15930000 Size: 0x45D000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FFD039F0000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FFD190E0000 Size: 0xCA000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FFCF2300000 Size: 0x9C000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FFD0D7E0000 Size: 0x27F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FFD006E0000 Size: 0x32B000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FFD15850000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FFD184B0000 Size: 0xD000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FFD19090000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FFCFFB20000 Size: 0x84000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FFCB9D40000 Size: 0x48E000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FFCEB1C0000 Size: 0x1BC000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FFCED2B0000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FFCFF610000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FFD19820000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FFCF8EB0000 Size: 0x8E000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FFD03F00000 Size: 0x19000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FFD196C0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\OLEACC.dll Base Address: 0x7FFD0AB10000 Size: 0x66000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FFD03B40000 Size: 0x125000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FFD15490000 Size: 0xF6000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FFD00D90000 Size: 0x34000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FFD11680000 Size: 0x19000
C:\WINDOWS\SYSTEM32\SSPICLI.DLL Base Address: 0x7FFD19AF0000 Size: 0x32000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FFD09770000 Size: 0xC000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FFCF06C0000 Size: 0x2F5000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FFD19070000 Size: 0x12000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FFD19B30000 Size: 0x2E000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FFD10940000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FFD03E80000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FFD157C0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FFD12190000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FFD11540000 Size: 0x10C000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FFD033B0000 Size: 0x4D9000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FFD0DBF0000 Size: 0x27000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FFD134B0000 Size: 0xB000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FFD0AC20000 Size: 0x98000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FFD18930000 Size: 0x64000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FFD18E00000 Size: 0x19000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FFD15910000 Size: 0x14000
C:\WINDOWS\SYSTEM32\Wldp.dll Base Address: 0x7FFD19690000 Size: 0x30000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FFD0D7C0000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FFD13AA0000 Size: 0xA000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FFD03F40000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FFD12150000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FFD13F70000 Size: 0xD000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FFD089D0000 Size: 0x1CF000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FFCBA1D0000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FFCF9510000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FFD112F0000 Size: 0x1E4000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FFD199E0000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FFD12D30000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FFD13490000 Size: 0x17000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FFD11E00000 Size: 0x148000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FFD17930000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FFD13FC0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FFD184F0000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FFD00FD0000 Size: 0x24000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FFD184C0000 Size: 0x23000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FFD09410000 Size: 0x2B1000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FFD0E7E0000 Size: 0x152000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FFD17B10000 Size: 0x12000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FFD00380000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FFD00000000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FFD000F0000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FFD157E0000 Size: 0xB000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FFD19700000 Size: 0x27000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FFD190D0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FFD1C530000 Size: 0x1F8000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FFD18DC0000 Size: 0x33000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FFCE8350000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FFD19200000 Size: 0x4B000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FFD19B70000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FFD17710000 Size: 0x14000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FFD08700000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FFD0E940000 Size: 0xF9000
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll Base Address: 0x7FFD12B30000 Size: 0x200000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FFD08BA0000 Size: 0x1ED000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FFCF23A0000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FFD152C0000 Size: 0x65000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FFD17D10000 Size: 0x792000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FFD03C70000 Size: 0x26000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FFD16720000 Size: 0x154000
C:\WINDOWS\SYSTEM32\xinput1_4.dll Base Address: 0x7FFD01B30000 Size: 0x11000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FFD1BA80000 Size: 0xDA000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FFD19C30000 Size: 0x156000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvldumdx.dll Base Address: 0x7FFD0EA40000 Size: 0x117000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_1b5e80ff87b1f5c8\nvwgf2umx.dll Base Address: 0x7FFD04AE0000 Size: 0x3664000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FFD1C2B0000 Size: 0x2B000
C:\WINDOWS\System32\IMM32.dll Base Address: 0x7FFD1B720000 Size: 0x32000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FFD1A610000 Size: 0xBF000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FFD1A270000 Size: 0x2D2000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FFD13B00000 Size: 0x85000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FFD1AFB0000 Size: 0x115000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FFD1B180000 Size: 0x8000
C:\WINDOWS\System32\Normaliz.dll Base Address: 0x7FFD1AA00000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FFD1A880000 Size: 0xCD000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FFD1B710000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FFD1A730000 Size: 0x125000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FFD1AA10000 Size: 0x468000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FFD1BB60000 Size: 0x743000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FFD1B760000 Size: 0x55000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FFD1B570000 Size: 0x19D000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FFD19EE0000 Size: 0x6A000
C:\WINDOWS\System32\WLDAP32.dll Base Address: 0x7FFD1B970000 Size: 0x56000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FFD1C380000 Size: 0x6B000
C:\WINDOWS\System32\advapi32.dll Base Address: 0x7FFD1A950000 Size: 0xAE000
C:\WINDOWS\System32\bcrypt.dll Base Address: 0x7FFD1A190000 Size: 0x27000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FFD1A100000 Size: 0x82000
C:\WINDOWS\System32\cfgmgr32.dll Base Address: 0x7FFD19E90000 Size: 0x4E000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FFD1B9D0000 Size: 0xAF000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FFD1B210000 Size: 0x354000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FFD0FC40000 Size: 0x80000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FFD19F50000 Size: 0x10F000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FFD1A860000 Size: 0x1D000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FFD1A060000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FFD1C3F0000 Size: 0x9E000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FFD1AE80000 Size: 0x12A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FFD1C2E0000 Size: 0x9C000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FFD1B0D0000 Size: 0xAD000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FFD19D90000 Size: 0x100000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FFD1A550000 Size: 0x22000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FFD147A0000 Size: 0x12000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll Base Address: 0x7FFD02D90000 Size: 0xB0000
C:\WINDOWS\system32\NLAapi.dll Base Address: 0x7FFD15440000 Size: 0x1D000
C:\WINDOWS\system32\XAudio2_7.dll Base Address: 0x7FFCEADA0000 Size: 0x8B000
C:\WINDOWS\system32\mswsock.dll Base Address: 0x7FFD193F0000 Size: 0x6A000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FFD15890000 Size: 0x17000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FFD0DF10000 Size: 0x761000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FFD15830000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FFD18CA0000 Size: 0x34000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FFD17640000 Size: 0x9E000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FFD14710000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FFD04000000 Size: 0x51000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FFD18820000 Size: 0xA1000
C:\Windows\System32\WindowManagementAPI.dll Base Address: 0x7FFD12DF0000 Size: 0xA1000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FFD0EB70000 Size: 0x141000
C:\Windows\System32\fwbase.dll Base Address: 0x7FFD187A0000 Size: 0x3A000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FFD116E0000 Size: 0xA000
D:\epicgame\GTAV\EOSSDK-Win64-Shipping.dll Base Address: 0x7FFCB8990000 Size: 0xA18000
D:\epicgame\GTAV\GFSDK_ShadowLib.win64.dll Base Address: 0x7FFCE5FE0000 Size: 0x3CC000
D:\epicgame\GTAV\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFD157A0000 Size: 0x1C000
D:\epicgame\GTAV\GTA5.exe Base Address: 0x7FF7E2C70000 Size: 0x3D20600
D:\epicgame\GTAV\bink2w64.dll Base Address: 0x7FFCFED40000 Size: 0x8D000
D:\gta5\YimMenu.dll Base Address: 0x7FFCC5FC0000 Size: 0x1FA000

Dumping registers:

RAX: 0x3
RCX: 0x0
RDX: 0xFFFFFFFFFFFFFFFF
RBX: 0x1F73C7FD7E0
RSI: 0x1F73CA1AAE0
RDI: 0x0
RSP: 0x1B70EFB6C8
RBP: 0x1F73CA1AB88
R8:  0xC
R9:  0x4C0
R10: 0x1F72BE049C0
R11: 0x1F735372F10
R12: 0x7FF7E35AAE00
R13: 0x0
R14: 0x1F73CA1ABA8
R15: 0x1F73CA1AB08

stack dump [0]	 D:\epicgame\GTAV\GTA5.exe+0x162E04B 0x7FF7E429E04B
stack dump [1]	 D:\epicgame\GTAV\GTA5.exe+0xBA0DD8 0x7FF7E3810DD8
stack dump [2]	 D:\epicgame\GTAV\GTA5.exe+0x881CFA 0x7FF7E34F1CFA
stack dump [3]	 D:\epicgame\GTAV\GTA5.exe+0x15EC913 0x7FF7E425C913
stack dump [4]	 D:\epicgame\GTAV\GTA5.exe+0x15ECD51 0x7FF7E425CD51
stack dump [5]	 D:\epicgame\GTAV\GTA5.exe+0x15E6C29 0x7FF7E4256C29
stack dump [6]	 D:\epicgame\GTAV\GTA5.exe+0x10E3C2C 0x7FF7E3D53C2C
stack dump [7]	 D:\epicgame\GTAV\GTA5.exe+0x93AEAA 0x7FF7E35AAEAA
stack dump [8]	 D:\epicgame\GTAV\GTA5.exe+0x16176E1 0x7FF7E42876E1
stack dump [9]	 D:\epicgame\GTAV\GTA5.exe+0x92D926 0x7FF7E359D926
stack dump [10]	 D:\epicgame\GTAV\GTA5.exe+0x94A84D 0x7FF7E35BA84D
stack dump [11]	 D:\epicgame\GTAV\GTA5.exe+0x15D10C1 0x7FF7E42410C1
stack dump [12]	 D:\epicgame\GTAV\GTA5.exe+0x15D08EF 0x7FF7E42408EF
stack dump [13]	 D:\epicgame\GTAV\GTA5.exe+0x271D0 0x7FF7E2C971D0
stack dump [14]	 D:\epicgame\GTAV\GTA5.exe+0x208BF 0x7FF7E2C908BF
stack dump [15]	 D:\epicgame\GTAV\GTA5.exe+0x15D04F8 0x7FF7E42404F8
stack dump [16]	 D:\epicgame\GTAV\GTA5.exe+0x1494 0x7FF7E2C71494
stack dump [17]	 D:\epicgame\GTAV\GTA5.exe+0x12BBE0F 0x7FF7E3F2BE0F
stack dump [18]	 D:\epicgame\GTAV\GTA5.exe+0x17C3988 0x7FF7E4433988
stack dump [19]	 C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [20]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by SkiddyToast** [comment]
Here's a decompilation of where the crash occurs:
```c++
__int64 __fastcall sub_7FF7565EE03C(__int64 a1)
{
  __int64 v1; // rdx
  unsigned __int8 v2; // al
  __int64 v3; // rax

  v1 = -1i64;
  while ( 1 )
  {
    v2 = *(_BYTE *)(a1 + 4i64 * dword_7FF756F31970 + v1 + 225); // Crashes here
    if ( v2 != 12 )
      break;
    if ( ++v1 >= 3 )
    {
      v3 = 0i64;
      return *(_QWORD *)(v3 + 32);
    }
  }
  v3 = *(_QWORD *)(a1 + 8i64 * v2 + 72);
  return *(_QWORD *)(v3 + 32);
}
```
It seems that `a1` can be null/invalid, as multiple xrefs don't check the value before it's passed in.
Sadly, it's used in a lot of places.

Here's an example from `CPed::SetPedOutOfVehicle`:
```c++
if ( v19 )
    v20 = *(_QWORD *)(v19 + 64);
else
    v20 = 0i64;
v21 = sub_7FF7565EE03C(v20); // Passes in a potentially NULL v20
```
