### ISSUE TITLE
[Crash]: Vehicle Spawning

### ISSUE THREAD

**Issue by MoneyDropLobby** [Yimura/YimMenu#619]
### Describe the bug

Crashing when spawning a car

### Steps To Reproduce

1. Go in GTA 5 SP
2. Try to spawn a car
3. Crash

### Expected Behavior

Not to crash

### Screenshots and/or Logs

```
![Unbenannt](https://user-images.githubusercontent.com/30525845/202855537-ce3f5f3e-3768-4bc7-a159-74af0864dc92.png)

```

### Store

Rockstar

### Additional context

I used my own version of YimMenu

### Build

- [ ] I used YimMenu unmodified

**Comment by Yimura** [comment]
Bug reports are only valid for unmodified versions of YimMenu, please use YimMenu unmodified and confirm the bug exists there as well.
