### ISSUE TITLE
[Bug]: Failed to checkout tag while building 

### ISSUE THREAD

**Issue by AtomicBool** [Yimura/YimMenu#623]
### Describe the bug

  fatal: reference is not a tree: 6ccf93c2e966e9ae13df75496a88e7b45214f7f8
  CMake Error at g3log-subbuild/g3log-populate-prefix/tmp/g3log-populate-gitclone.cmake:49 (message):
    Failed to checkout tag: '6ccf93c2e966e9ae13df75496a88e7b45214f7f8'

### Steps To Reproduce

git config --global url."https://gitclone.com/".insteadOf https://
mkdir build 
cd build
cmake ..

### Expected Behavior

hope someone can help me ,plz!

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Have you tried following the normal setup instructions instead?

**Comment by AtomicBool** [comment]
> Have you tried following the normal setup instructions instead?

except use gitclone.com/ instead of github.com/
i even cant use'git clone' without it
i dont think it will have influnce to complie

**Comment by Yimura** [comment]
Sorry but I don't see how this is an issue with YimMenu.
You've modified how git pulls repositories, please go ask on git forums for better support regarding problems you're having with git. Or alternatively since CMake is having issues, go on a CMake forum and ask for help.

**Comment by AtomicBool** [comment]
> 抱歉，但我不明白这是YimMenu的问题。您已经修改了 git 拉取存储库的方式，请在 git 论坛上询问有关您在使用 git 时遇到的问题的更好支持。或者，由于 CMake 遇到问题，请访问 CMake 论坛并寻求帮助。

ok thanku
