### ISSUE TITLE
[Request]: Disconnect from the modder player

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#627]
### Problem

When I was the session host, the modder player kept attacking my game, rendering it unresponsive, and after a few seconds, I was disconnected from all players

### Solution

Whether you can disconnect from the modder player

### Reason

When I am attacked by a modder player, I should disconnect directly from it to avoid being attacked all the time

**Comment by Yimura** [comment]
What are you doing exactly? Cause you specifically seem to get attacked by modders every other day.
(in regards to the two previous issues you made where modders attacked you #601 & #616)

Are you perhaps forcing session host? The feature specifically mentions that this is easily detected by modders, to prevent getting targeted please disable this feature.

Following note appears when hovering over `Force Session Host`:
```
Join another session to apply changes. The original host of the session must leave or be kicked. This feature is easily detectable by other mod menus, use with caution
```

**Comment by iwanttodo1t** [comment]
Without using the feature, I didn't want to be kicked by a breakup, so I created a public session

**Comment by Yimura** [comment]
Being host does not prevent you from being breakup kicked (yet).

After #625 is merged you can enable breakup kick protection.

**Comment by iwanttodo1t** [comment]
Thank you so much for the code so that we can have fun playing the game and I would like to treat you to coffee
