### ISSUE TITLE
[Bug]: Menu unusable for long gaming sessions

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#629]
### Describe the bug

Ever since #606, I've start having regular crashes.
At first #407 was partially to blame but seems that this has been resolved by later PR's.

When playing for around 30 minutes in different session you might get the following error:
![image](https://user-images.githubusercontent.com/24669514/203171098-fbbe55a7-95db-4e98-95e8-aa15eea8c312.png)

This is one of the many ways that the game may crash.

### Steps To Reproduce

No exact steps to reproduce.

### Expected Behavior

Remain somewhat stable or at the least not crash every 5 minutes.

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by 0xEmiil** [comment]
if you unload and inject the menu, sometimes (up to 5) the menu crash, this doesn't happened before :/
Oh and yeah, it doesn't generate a log

**Comment by iwanttodo1t** [comment]
I've been using the latest yim and haven't encountered this kind of situation

**Comment by Yimura** [comment]
Fixed in #633
