### ISSUE TITLE
[Bug]: Kick/Crash spam

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#639]
### Describe the bug

Cars most of problems. In any case with PV or any other car, when close to player onfoot - u can got "U have been desync kicked" or Crash(report above).
Sometimes, just kicking at spawnpoint, after desync kick by cars..

### Steps To Reproduce

Take personal veh(PV), ask guy to sit, car will kick both of u, in some cases, players existing nearly to PV - will kick u from PV.

### Expected Behavior

Dont kicks or crashes by just existing players near u, while u or both in car.

### Screenshots and/or Logs

1st- instant after desync kick
2nd- just come to player on PV, got kicked from car, tried to get back and got crashed
https://imgur.com/a/TQOGPvI

Dumping registers:

RAX: 0x1B39747
RCX: 0x1CE0F8345C8
RDX: 0x1B39746
RBX: 0x1CE0F834630
RSI: 0x1CF63E0312F
RDI: 0x1CF643F9EBD
RSP: 0x215BCFF420
RBP: 0x215BCFF4B9
R8:  0x7FF72315E700
R9:  0x1CE0F80E550
R10: 0x2
R11: 0x1CE0F834598
R12: 0x8
R13: 0x1CE5DB1E930
R14: 0x1CF87EC0000
R15: 0x1CE0F12D8B8

stack dump [0]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15C105C 0x7FF72182105C
stack dump [1]   F:\Games\GTA Files\Online\YimMenu.dll+0x4F947 0x7FFF54C6F947
stack dump [2]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15C19E7 0x7FF7218219E7
stack dump [3]   F:\Games\EpicGames\GTAV\GTA5.exe+0xA49648 0x7FF720CA9648
stack dump [4]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15C20C9 0x7FF7218220C9
stack dump [5]   F:\Games\EpicGames\GTAV\GTA5.exe+0xA3DE84 0x7FF720C9DE84
stack dump [6]   F:\Games\EpicGames\GTAV\GTA5.exe+0xA416EC 0x7FF720CA16EC
stack dump [7]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15D10C1 0x7FF7218310C1
stack dump [8]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15D10C1 0x7FF7218310C1
stack dump [9]   F:\Games\EpicGames\GTAV\GTA5.exe+0x15D08EF 0x7FF7218308EF
stack dump [10]  F:\Games\EpicGames\GTAV\GTA5.exe+0x271D0 0x7FF7202871D0
stack dump [11]  F:\Games\EpicGames\GTAV\GTA5.exe+0x208BF 0x7FF7202808BF
stack dump [12]  F:\Games\EpicGames\GTAV\GTA5.exe+0x15D04F8 0x7FF7218304F8
stack dump [13]  F:\Games\EpicGames\GTAV\GTA5.exe+0x1494 0x7FF720261494
stack dump [14]  F:\Games\EpicGames\GTAV\GTA5.exe+0x12BBE0F 0x7FF72151BE0F
stack dump [15]  F:\Games\EpicGames\GTAV\GTA5.exe+0x17C3988 0x7FF721A23988
stack dump [16]  C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [17]  C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by SkiddyToast** [comment]
This crash is in the script VM, on the opcode `ARRAY_U16` or `ARRAY_U8`, by accessing an invalid index of the array.
This is the assembly where the crash occurs:
```asm
mov     rcx, [rcx+rax*8]
```
In your logs, `rcx` seems valid, as it follows the same pattern as the rest of the heap-allocated memory, but `rax`, being the index, seems much too large.

**Comment by Adler-D3R** [comment]
A solution could be creating an array to store " bad modders " RIDs, and add their RID when you detect an attack, and then block every entries from them (Script Events, Net Events, Clone Syncs and stuff) so that you stay safe from unknown crash/kick methods and event spam.

**Comment by Yimura** [comment]
Closing as RID spoofing has been patched by the game and is likely to be impossible to do.
