### ISSUE TITLE
More info on players tab

### ISSUE THREAD

**Issue by FriXeee** [Yimura/YimMenu#64]
add more information about the player and some other options in the toxic tab

**Comment by Yimura** [comment]
sOmE oThEr OpTiOnS iN tOxIc TaB

Tell me what you would like to add, what you're asking for isn't anything specific.

**Comment by FriXeee** [comment]
I didn't mean cancer options.
Option like steal outfits,give weap,remove police,ESP(player,npc), stuff like that...
on protection ''Anti report'', and gui color changer.
on weapon: no recoil, no spread, increase damage weap, crosshair.
watermark option with session info, car noclip.
on self ''clean player'',invisibility.

- [x] Gui > Color changer
- [x] Gui > Info window
- [ ] Other > RP multiplier
- [ ] Other > Cut Editor
- [x] Other > ESP
- [x] Player > Steal outfits
- [x] Player > Give weapons
- [x] Player > Remove police
- [x] Protections > Anti report
- [ ] Spoof > Spoof position
- [ ] Self > Refill HP/Armor
- [x] Self > Clean player model
- [x] Self > Invisibility
- [x] Weapons > No recoil
- [x] Weapons > No spread
- [x] Weapons > Increase damage
- [x] Weapons > Crosshair

**Comment by Yimura** [comment]
Anti report is enabled by default.

Also we're in the middle of a GUI redesign, so I wont' be touching the UI until that's finished.

**Comment by FriXeee** [comment]
okay, i hope you can add some of these options in the future

**Comment by LiamD-Flop** [comment]
I cleaned up your comment.... Please use the Template next time. It makes our lives easier.
The checked checkboxes are either already implemented or in the pool of features to implement.

**Comment by xM4ddy** [comment]
I've finished work on clean player, invisibility, no recoil, and crosshair. The one thing stumping me for the moment is what's going on with m_spread. I have the pointer chain and it's almost the same feature as no recoil where I *think* I just need to set it to 0.f but for some reason spread still seems present. Not sure if an offset is out of date or if I'm making a mistake or what.

**Comment by Yimura** [comment]
Spread offset might be incorrect, don't worry.

**Comment by Yimura** [comment]
> I've finished work on clean player, invisibility, no recoil, and crosshair. The one thing stumping me for the moment is what's going on with m_spread. I have the pointer chain and it's almost the same feature as no recoil where I _think_ I just need to set it to 0.f but for some reason spread still seems present. Not sure if an offset is out of date or if I'm making a mistake or what.

I've updated the CWeaponInfo class so spread offsets should be up to date now.
https://github.com/Yimura/GTAV-Classes/blob/master/CWeaponInfo.hpp

Including others like CItemInfo and CAmmoInfo have also been adjusted.

**Comment by xM4ddy** [comment]
Bottom 6 boxes should be checked by my pull request.

**Comment by FriXeee** [comment]
no spread don't work, there is a problem with the CWeapons class

**Comment by Yimura** [comment]
> no spread don't work, there is a problem with the CWeapons class

Which value are using from CWeaponInfo and modifying?

I took all information for variable names from here: https://github.com/Yimura/GTAV-Classes/issues/1

Perhaps there's a different value that you need to adjust for it work.

Also if there's a problem with classes, don't make an issue here, make it on the designated repository.

**Comment by FriXeee** [comment]
Fixed m_spread => m_accuracy_spread

**Comment by Yimura** [comment]
@FriXeee please refrain from updating this issue, we just split up your request in checkboxes  so we can keep track of it.
For new additions please create a new issue, (follow the issue template or your request will be ignored).

**Comment by howdoiusekeyboard** [comment]
ESP would be sick

**Comment by LiamD-Flop** [comment]
Everything from issue has been implemented / decided to be put on **Won't fix**
