### ISSUE TITLE
[Bug]: namespace "std" has no member "unreachable

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#642]
### Describe the bug

when cloning yim menu and doing cmake this is a  build error that shows up every single time. I have no idea how to fix this.

### Steps To Reproduce

1. clone yim menu
2. do cmake
3. build the menu
4. get error

### Expected Behavior

it builds fine

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/67609719/204095008-a0588556-0c3e-46a0-91e5-500115cb1259.png)

### Store

Rockstar

### Additional context

i did not modify the mod menu

### Build

- [X] I used YimMenu unmodified

**Comment by Loko415** [comment]
6>F:\YimMenu\src\services\matchmaking\matchmaking_service.cpp(91,12): error C2039: 'unreachable': is not a member of 'std'
6>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\bitset(22): message : see declaration of 'std'
6>F:\YimMenu\src\services\matchmaking\matchmaking_service.cpp(92,6): error C3861: 'unreachable': identifier not found

**Comment by Yimura** [comment]
Make sure your installation of MSVC is up to date.

You can do this by opening the Visual Studio Installer, also make sure you're using the latest VS.

**Comment by Loko415** [comment]
updating it now. I'll let you know how it goes

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/204096777-4477e80b-99e7-4302-af5a-1d75eeefbd51.png)
FIXED! thank you
