### ISSUE TITLE
[Request]: Don't trigger Hotkeys when chatting

### ISSUE THREAD

**Issue by RainerZufall187** [Yimura/YimMenu#645]
### Solution

hm ok

### Reason

annoying ok

**Comment by Aure7138** [comment]
Then don't set the keys you will use in chat lol, I think F4-F10 are all ok

**Comment by TheGreenBandit** [comment]
I think this could be fixed by getting if the player is in chatbox then disable hotkey service, most logical answer

**Comment by ghost** [comment]
https://docs.fivem.net/natives/?_0x5FCF4D7069B09026
in your checks just make sure this is false

**Comment by Yimura** [comment]
I'm preparing to use this class I added just recently to the GTAV-Classes repo.

I really don't plan on using natives for this.
