### ISSUE TITLE
[Request]: Add Admin detect protection

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#650]
### Solution

no thing

### Reason

For more safety

### Additional context

Add  Admin detect protection and Report protection

**Comment by Yimura** [comment]
Report protection already exists in YimMenu.

**Comment by D-Borkan** [comment]
> Report protection already exists in YimMenu

> Report protection already exists in YimMenu.

ok thank

**Comment by Adler-D3R** [comment]
Some player spoof their name and RID to make people think they are admis, so not sure if this detector could be useful since there will be a lot of false positives. Never encountered am admin in my life so, it's not really useful.
