### ISSUE TITLE
[Bug]: Context Menu freezed if use it on annoying players lot times

### ISSUE THREAD

**Issue by Sheeeeit** [Yimura/YimMenu#655]
### Describe the bug

The context menu [freezed ](https://mega.nz/file/lYE1HKAI#xnThCdIAiLEL4Chs8Q3g9iJgmNZLStX_vAlo9czmMpk)if you make two or more clicks on the player (exactly the player), with NPCs this does not happen. After that it is impossible to use items.

### Steps To Reproduce

1. Start the game
2. Inject dll
3. Load to the online session
4. Open context menu
5. Choose any (kill engine, delete, explode, tp into) on the player
6. Context menu now freezed

### Expected Behavior

No freezing

### Screenshots and/or Logs

`without log
`

### Store

Steam

### Additional context

```
Branch:	master
Hash:	675548770c5876ca6dc648f9efdeeb7d90b1cc73-dirty
Date:	Thu Dec 1 23:37:58 2022
```

### Build

- [X] I used YimMenu unmodified

**Comment by iwanttodo1t** [comment]
Do not use on players

**Comment by TheGreenBandit** [comment]
We should make a player tab part for the context menu, this way its not using shared things that could break it like the guy in this issue is taking about

**Comment by Sheeeeit** [comment]
UPD: This also happens if there is a dead NPC sitting in the car

**Comment by GeopJr** [comment]
Does this still occur on latest YimMenu?

**Comment by Sheeeeit** [comment]
> Does this still occur on latest YimMenu?

 If used on an NPC - no, on the player [still freezed](https://i.imgur.com/uFlyS3C.png), but after a while the menu becomes active again.
UPD: Game crashed, when u missclicked and delete yourself.

**Comment by Yimura** [comment]
Closing as this should have been fixed.
