### ISSUE TITLE
[Bug]: Can still be crashed by 2take

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#656]
### Describe the bug

Dumping registers:

RAX: 0x205F1655710
RCX: 0x0
RDX: 0x621ECFCBF0
RBX: 0x205F0A25FE8
RSI: 0x0
RDI: 0x621ECFCBF0
RSP: 0x621ECFCB70
RBP: 0x621ECFCBC0
R8:  0x0
R9:  0x21005221
R10: 0x205F1A3FC10
R11: 0x205F1655710
R12: 0x5E4
R13: 0x1
R14: 0xFFFCFFFF
R15: 0x621ECFCC68

stack dump [0]	 D:\epicgame\GTAV\GTA5.exe+0x1618978 0x7FF7B6F78978
stack dump [1]	 D:\epicgame\GTAV\GTA5.exe+0x10FAD9F 0x7FF7B6A5AD9F
stack dump [2]	 D:\epicgame\GTAV\GTA5.exe+0x1666A89 0x7FF7B6FC6A89
stack dump [3]	 D:\epicgame\GTAV\GTA5.exe+0x10A9E39 0x7FF7B6A09E39
stack dump [4]	 D:\epicgame\GTAV\GTA5.exe+0x10E277B 0x7FF7B6A4277B
stack dump [5]	 D:\epicgame\GTAV\GTA5.exe+0x1679A10 0x7FF7B6FD9A10
stack dump [6]	 D:\epicgame\GTAV\GTA5.exe+0x1671498 0x7FF7B6FD1498
stack dump [7]	 D:\epicgame\GTAV\GTA5.exe+0x1676ADC 0x7FF7B6FD6ADC
stack dump [8]	 D:\epicgame\GTAV\GTA5.exe+0x13BAE51 0x7FF7B6D1AE51
stack dump [9]	 D:\epicgame\GTAV\GTA5.exe+0x1676C06 0x7FF7B6FD6C06
stack dump [10]	 D:\epicgame\GTAV\GTA5.exe+0x140367E 0x7FF7B6D6367E
stack dump [11]	 D:\gta5\YimMenu.dll+0x4B406 0x7FFBB724B406
stack dump [12]	 D:\epicgame\GTAV\GTA5.exe+0x1403731 0x7FF7B6D63731
stack dump [13]	 D:\epicgame\GTAV\GTA5.exe+0x1403447 0x7FF7B6D63447
stack dump [14]	 D:\epicgame\GTAV\GTA5.exe+0x14274DA 0x7FF7B6D874DA
stack dump [15]	 D:\epicgame\GTAV\GTA5.exe+0x108B450 0x7FF7B69EB450
stack dump [16]	 D:\epicgame\GTAV\GTA5.exe+0x15D10C1 0x7FF7B6F310C1
stack dump [17]	 D:\epicgame\GTAV\GTA5.exe+0x15D08EF 0x7FF7B6F308EF
stack dump [18]	 D:\epicgame\GTAV\GTA5.exe+0x271AA 0x7FF7B59871AA
stack dump [19]	 D:\epicgame\GTAV\GTA5.exe+0x208BF 0x7FF7B59808BF
stack dump [20]	 D:\epicgame\GTAV\GTA5.exe+0x15D04F8 0x7FF7B6F304F8
stack dump [21]	 D:\epicgame\GTAV\GTA5.exe+0x1494 0x7FF7B5961494
stack dump [22]	 D:\epicgame\GTAV\GTA5.exe+0x12BBE0F 0x7FF7B6C1BE0F
stack dump [23]	 D:\epicgame\GTAV\GTA5.exe+0x17C3988 0x7FF7B7123988
stack dump [24]	 C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [25]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

### Steps To Reproduce

Is there a crash that can't be prevented？

### Expected Behavior

Will not crash

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by MarkEcza** [comment]
Seems like a "rope crash" to me, although can't say for sure.( edit no it's not jumped to the wrong place :( )

**Comment by SkiddyToast** [comment]
It failed to allocate a `rage::fwDecorator`, and didn't check if it had failed, causing a crash.
Here's a quick decompilation to show how/where it's happening:
```c++
v8 = rage::sysMemPoolAllocator::PoolNode::Allocate(DecoratorPool); // The name of this function is 100% incorrect lmao
if ( v8 ) // Checking if v8 was allocated properly
{
    rage::fwDecorator::fwDecorator((__int64)v8, (__int64)a2, 2);
    v4 = v9;
}
else // Failed to allocate
{
    v4 = 0i64;
}
*(_QWORD *)(v4 + 8) = *(_QWORD *)(a1 + 8); // v4 can be NULL here, causing a STATUS_ACCESS_VIOLATION
```
This is the assembly of the line that causes the crash, you can see that it would attempt to dereference `rcx+8`, and rcx is 0 in your logs:
```asm
mov     [rcx+8], rax
```
