### ISSUE TITLE
chore: Mark as deprecated/unused

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#658]
### Either remove from codebase or comment it as deprecated/unused.

https://github.com/YimMenu/YimMenu/blob/3c9e0775271f59ba1ad0fdfdc4c641f1f70c6f6e/src/hooks/protections/can_apply_data.cpp#L86-L159

**Comment by xiaoxiao921** [comment]
Remove, commented code shouldnt be a thing as we have version control
