### ISSUE TITLE
[Bug]: Crash after waiting for socialclub.dll

### ISSUE THREAD

**Issue by Fongyei** [Yimura/YimMenu#662]
### Describe the bug

The game crashes when I inject, and many times it crashes when injecting

### Steps To Reproduce

![qaz](https://user-images.githubusercontent.com/120026616/206183685-f7a28dbb-b8be-49a6-b83d-269fa4e1fd62.jpg)

### Expected Behavior

The game crashes when I inject, and many times it crashes when injecting

### Screenshots and/or Logs

![qaz](https://user-images.githubusercontent.com/120026616/206183662-b52d7548-8d4f-4a03-923b-9f78a2474d45.jpg)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by sch-lda** [comment]
This issue for me occured after updating Rockstar Social Club automatically

**Comment by sch-lda** [comment]
I noticed that in the log. Maybe Rockstar modified socialclub.dll... 

[20:36:55][DEBUG/module.cpp:49]: Waiting for socialclub.dll...
2022/12/07 20:36:55 725180

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 3916

*******	STACKDUMP *******

**Comment by sch-lda** [comment]
I noticed that in the log. Maybe Rockstar modified socialclub.dll... 

[20:36:55][DEBUG/module.cpp:49]: Waiting for socialclub.dll...
2022/12/07 20:36:55 725180

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 3916

*******	STACKDUMP *******

**Comment by Yimura** [comment]
Have you tried updating your YimMenu?

Most likely Duplicate of #659

**Comment by sch-lda** [comment]
Thaks for your work.The latest release runs smoothly.
