### ISSUE TITLE
[Bug]: NPCs in properties not spawning

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#663]
### Describe the bug

NPCs in the following properties do not spawn (others unconfirmed)
- AutoShop
- NightClub(There is no music, probably because there are no NPCs.)

### Steps To Reproduce

Enter each property and vehicle with YimMenu inserted.

### Expected Behavior

NPC not spawning.

### Screenshots and/or Logs

![nightclub1](https://user-images.githubusercontent.com/112477569/206193267-6548be09-0cdf-4d1d-85f7-8c461e3cac6c.png)
![nightclub2](https://user-images.githubusercontent.com/112477569/206193286-5bba7d24-b8be-4394-a1ae-d16116d50525.png)
![nightclub2_unload](https://user-images.githubusercontent.com/112477569/206193300-6b9629cd-ada7-4bba-b791-0f2a3dccddd5.png)

### Store

Epic Games

### Additional context

- Turning off Manage Script does not improve
- I turned off the option as much as possible, but it didn't improve
- Unloading YimMenu inside the property will spawn NPCs.
- When entering the property, I feel that it takes a little time to initialize (only confirmed at Nightclub).

### Build

- [X] I used YimMenu unmodified

**Comment by Peax** [comment]
You also can't set your spawn location to properties with NPCs, for example Arcade, without getting stuck in an infinite loading screen.

**Comment by Yimura** [comment]
The infinite loading screen is something I definitely have noticed but never tried to investigate.

**Comment by oxUNKNOWNxo** [comment]
> You also can't set your spawn location to properties with NPCs, for example Arcade, without getting stuck in an infinite loading screen.

Infinite loading when moving to an island with Vellum on Cayo Perico Heist Prep: Gather Intel.
It's just a different issue if the NPCs don't spawn this time.

**Comment by Peax** [comment]
Can confirm this issue was fixed with #666. Thank you @maybegreat48 👍🏻
