### ISSUE TITLE
[Bug]: Rapid Fire is bugged

### ISSUE THREAD

**Issue by Sheeeeit** [Yimura/YimMenu#668]
### Describe the bug

After the release of update #641, with the addition of Rapid Fire it has the following bug:
1) rapid happens when you trying to select something in the menu (car, healing, etc.)
2) rapid happens if you select a pistol/smg when you are in a car, while trying to use the mouse control
3) rapid happens if after death/kill you press the LMB to quickly respawn (and if the camera is on the player who killed you, you can kill him with it)

[Video](https://mega.nz/file/IR9SSSZC#eguqWqzYFMkkTCsfKCLkstc_rQ2gDKm3H6h12JsSF_4)

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by Aure7138** [comment]
It works by shooting bullets in front of you when you press the attack button, so I'm not sure if it's a bug

**Comment by Adler-D3R** [comment]
Yup, but this could be prevented by checking if the menu or UI is displayed or not. Shouldn't be hard to patch.

**Comment by Aure7138** [comment]
sure, i will add check for both menu open and is ped dead, but for the vehicle one i can't seem to do anything
