### ISSUE TITLE
[Bug]: Infinite load when traveling to Cayo Perico in Heist Prep: Gather Intel

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#670]
### Describe the bug

After reaching the yellow marker to the south with Vellum, it becomes an infinite load.
Similarly, when doing Gather additional intel, it will be an infinite load when flying from LSIA with Vellum.

### Steps To Reproduce

Gather Intel
 - Reach the yellow marker south on Vellum

Gather additional intel
 - Go to the LSIA's yellow marker and enter the cinematic where Vellum takes off from the LSIA

### Expected Behavior

Black screen with white icon spinning in bottom right corner.

### Screenshots and/or Logs

![load](https://user-images.githubusercontent.com/112477569/206473442-9504db1b-b040-4655-a0ac-b7f86410500e.png)

### Store

Epic Games

### Additional context

- Insert YimMenu only
- Option turned off as much as possible
- Turn off all Manage Scripts
- It was possible to end the game by Alt + F4 operation during infinite loading
- By using YimMenu's Network Bail and Join Session, it was possible to move to story mode and another session

### Build

- [X] I used YimMenu unmodified

**Comment by maybegreat48** [comment]
Are you using the latest version of the menu?

**Comment by oxUNKNOWNxo** [comment]
I'm using Nightly [173d011]
Probably the latest version.
