### ISSUE TITLE
[Request]: Prohibit known cheaters from joining the session

### ISSUE THREAD

**Issue by iwanttodo1t** [Yimura/YimMenu#671]
### Solution

Now it can only be manually banned in the player database, and I would like to be able to automatically ban known cheaters from joining the session

### Reason

Just kick out unfriendly players and sometimes they will join again

**Comment by tupoy-ya** [comment]
I feel like there is just too much false positives to auto block players right now.

**Comment by iwanttodo1t** [comment]
Or just ban players who have been kicked from joining

**Comment by iwanttodo1t** [comment]
You can use RID or name matching to avoid RID spoofing and name spoofing

**Comment by Yimura** [comment]
Do you want a database with all the known cheaters or what are you implying?
It's an extremely bad idea to use a centralised DB that anyone can report cheaters to.
You cannot trust anyone to report legit, besides YimMenu detects modders that might not be trying to disrupt gameplay (desync protection), should we block these people also from joining? Not really.

You'll have to add modders yourself you wish to be blocked and manually set them to be blocked from joining.

**Comment by iwanttodo1t** [comment]
Just a local player database

**Comment by Yimura** [comment]
Do you want to automatically block anyone that has been detected as modder? Because that would be unnecessary.
