### ISSUE TITLE
[Bug]: Crashes when i inject the dll

### ISSUE THREAD

**Issue by Miko0187** [Yimura/YimMenu#672]
### Describe the bug

When i inject the dll, gta freezes and then crashes

### Steps To Reproduce

1. build it
2. inject it

### Expected Behavior

idk

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [x] I used YimMenu unmodified

**Comment by Yimura** [comment]
Not an issue for me, please get the latest version of YimMenu.

**Comment by Peax** [comment]
I also cannot confirm a general injection issue. Latest build based on commit 173d011 injects flawlessly on my end. I use [Koaloader](https://github.com/acidicoala/Koaloader) by _acidicoala_.

**Comment by Miko0187** [comment]
> Not an issue for me, please get the latest version of YimMenu.

I have

**Comment by Miko0187** [comment]
> I also cannot confirm a general injection issue. Latest build based on commit 173d011 injects flawlessly on my end. I use [Koaloader](https://github.com/acidicoala/Koaloader) by _acidicoala_.

Maybe its a problem from extreme injector, i another one

**Comment by Yimura** [comment]
Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`

**Comment by Miko0187** [comment]
> Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`

I send them tomorrow

**Comment by Miko0187** [comment]
> Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`

My log is empty 
![image](https://user-images.githubusercontent.com/113242324/206705514-35f31cb1-9fbc-4a0a-a5b9-8298e688a90b.png)

**Comment by Miko0187** [comment]
> Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`

It worked, extreme injector was the problem

**Comment by Cryxyemi** [comment]
> Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`

it doesnt work, here is the log:
[14:08:44][INFO/main.cpp:61]: Yim's Menu Initializing
[14:08:44][INFO/main.cpp:62]: Git Info
	Branch:	master
	Hash:	173d01145da2f62c270cf797c829e77e09fc5310
	Date:	Thu Dec 8 13:35:41 2022
[14:08:44][INFO/main.cpp:65]: Settings Loaded.
Found 'SCREEN_RESOLUTION' GTA5.exe+0x16C157
Found 'RC' GTA5.exe+0x13C825C
Found 'MWL' GTA5.exe+0x5D45BB
Found 'GS' GTA5.exe+0x2BF068
Found 'ISA' GTA5.exe+0xEC43
Found 'PF' GTA5.exe+0x728E48
Found 'NPM' GTA5.exe+0x1076C6C
Found 'NH' GTA5.exe+0x15C2131
Found 'FV' GTA5.exe+0x15BF0E0
Found 'ST' GTA5.exe+0x15C2087
Found 'SP' GTA5.exe+0xA3B7CD
Found 'SG' GTA5.exe+0x15C19D8
Found 'CGSHM' GTA5.exe+0x15C6B69
Found 'S' GTA5.exe+0x1345189
Found 'WMSB' GTA5.exe+0xCDCE99
Found 'NRF' GTA5.exe+0x4A0C32
Found 'GTS' GTA5.exe+0x15C1BA0
Found 'TK' GTA5.exe+0xA3F898
Found 'TSE' GTA5.exe+0xD6A848
Found 'REH' GTA5.exe+0x167940C
Found 'SEA' GTA5.exe+0x1664215
Found 'RBWD' GTA5.exe+0x109D111
Found 'RBA' GTA5.exe+0x12E353C
Found 'RBS' GTA5.exe+0x1170CFC
Found 'RBB' GTA5.exe+0x11278C7
Found 'WBD' GTA5.exe+0x1127E10
Found 'WBQ' GTA5.exe+0x12EB2EC
Found 'WBI64' GTA5.exe+0x1174381
Found 'WBI32' GTA5.exe+0x1173253
Found 'WBB' GTA5.exe+0x1172DD8
Found 'WBA' GTA5.exe+0x1663FD6
Found 'WPGSDN' GTA5.exe+0x10CCE94
Found 'RCOE-Patch' GTA5.exe+0xCCC264
Found 'RI' GTA5.exe+0x1E9C
Found 'PTH' GTA5.exe+0x15C6625
Found 'GSH' GTA5.exe+0x15C7AF4
Found 'BE' GTA5.exe+0xA64FBB
Found 'SNITL' GTA5.exe+0x13BC4BA
Found 'CNOM' GTA5.exe+0xB108C4
Found 'NPMI' GTA5.exe+0x10D78E7
Found 'NPMS' GTA5.exe+0x110BB3A
Found 'FR' GTA5.exe+0xCC8F38
Found 'GSCFWC' GTA5.exe+0xA3A934
Found 'GGCC' GTA5.exe+0xA6F1F2
Found 'GPR' GTA5.exe+0x118F304
Found 'WPGDN' GTA5.exe+0x10CD9B0
Found 'RNM' GTA5.exe+0x14035FD
Found 'GNED' GTA5.exe+0x19D32F8
Found 'API' GTA5.exe+0x167F4D8
Found 'RCC' GTA5.exe+0x10E1EAC
Found 'CAD' GTA5.exe+0x16675F4
Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x10E2E61
Found 'RBIST' GTA5.exe+0x10E202C
Found 'MHT' GTA5.exe+0xAF80
Found 'GLT' GTA5.exe+0xD86917
Found 'MCF' GTA5.exe+0x163D5E2
Found 'N' GTA5.exe+0x10448B1
Found 'RENC' GTA5.exe+0x142900A
Found 'FDGD' GTA5.exe+0x12CF527
Found 'FDS' GTA5.exe+0x12D2084
Found 'FPFC' GTA5.exe+0x12CBEB2
Found 'FPFOA' GTA5.exe+0x12D0DA0
Found 'FPFM' GTA5.exe+0x12D22FA
Found 'FPFUM' GTA5.exe+0x69E6C7
Found 'GVOV' GTA5.exe+0x2E0438
Found 'IMCD' GTA5.exe+0x53443D
Found 'SCP' GTA5.exe+0x2ED858
Found 'SCM' GTA5.exe+0x1088BD9
Found 'FMFS' GTA5.exe+0x13BB9D8
Found 'SGSBGH' GTA5.exe+0x439B89
Found 'SGSBGH' GTA5.exe+0x13CE2BE
Found 'JSBI' GTA5.exe+0x114EA64
Found 'INT' GTA5.exe+0x15BE806
Found 'VM' GTA5.exe+0x15C19E2
Found 'GU' GTA5.exe+0x13EC4BE
Found 'HT' GTA5.exe+0x13C1BF5
Found 'PGI' GTA5.exe+0x13DCF98
Found 'PIGI' GTA5.exe+0x1082ACB
Found 'C' GTA5.exe+0xCCAF27
Found 'SDEGSDN' GTA5.exe+0x10EC0C4
Found 'SPIDN' GTA5.exe+0x10EE41C
Found 'SVGDN' GTA5.exe+0x10F5B64
Found 'GVGAS' GTA5.exe+0x10CFE54
Found 'HJR' GTA5.exe+0x115341C
Found 'WJRD' GTA5.exe+0x1154088
Found 'QP' GTA5.exe+0x1421C2E
Found 'SGS' GTA5.exe+0x1166CBC
Found 'APTS' GTA5.exe+0x11C319C
Found 'SCNM' GTA5.exe+0x11C3552
Found 'PMFR' GTA5.exe+0x13D82E0
Found 'SPDM' GTA5.exe+0x10F7FA4
Found 'SPDM' GTA5.exe+0x124FCAD
Found 'IMSV' GTA5.exe+0x11329D9
Found 'SND' GTA5.exe+0xF31D5E
Found 'RR' GTA5.exe+0xBFE9DB
Found 'GCP&SRGC' GTA5.exe+0x11C439A
Found 'HRGC' GTA5.exe+0x11BD1FA
Found 'BNA' GTA5.exe+0x16893F0
Found 'BP' GTA5.exe+0x16895DA
Found 'RS' GTA5.exe+0x3AA5DA4
Found 'SPDM' GTA5.exe+0x13B5AD8
Found 'STOPVT' GTA5.exe+0x695B04
Found 'CD' GTA5.exe+0x18ECDB
Found 'CSH' GTA5.exe+0xA2CD60
Found 'CW' GTA5.exe+0x166717
Found 'WBGH' GTA5.exe+0x1129640
Found 'RBGH' GTA5.exe+0x1129730
[14:08:49][DEBUG/module.cpp:49]: Waiting for socialclub.dll...
Found 'PD' GTA5.exe+0xC4EF8
[14:08:51][INFO/main.cpp:68]: Pointers initialized.
2022/12/09 14:08:51 563986

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 10820

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll Base Address: 0x7FFF061E0000 Size: 0x188000
C:\Program Files (x86)\Steam\steamclient64.dll Base Address: 0x7FFEA2AB0000 Size: 0x157F000
C:\Program Files (x86)\Steam\tier0_s64.dll Base Address: 0x7FFF05860000 Size: 0x195000
C:\Program Files (x86)\Steam\vstdlib_s64.dll Base Address: 0x7FFF05A00000 Size: 0xB2000
C:\Program Files\Bitdefender\Bitdefender Security\bdamsi\266168522393987938\antimalware_provider64.dll Base Address: 0x7FFF18830000 Size: 0xBC000
C:\Program Files\NVIDIA Corporation\NvContainer\MessageBus.dll Base Address: 0x7FFF12F70000 Size: 0x737000
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FFEFF750000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FFE9AA10000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FFEB0320000 Size: 0xB9B000
C:\Users\maik\AppData\Local\Discord\app-1.0.9007\modules\discord_hook-1\discord_hook\e7081b4d927\DiscordHook64.dll Base Address: 0x7FFEFF590000 Size: 0x127000
C:\Users\maik\Desktop\YimMenu\out\build\x64-Release\YimMenu.dll Base Address: 0x7FFE97760000 Size: 0x50C000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FFF302A0000 Size: 0x182000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FFF35A00000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FFF35E00000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FFF10AE0000 Size: 0x5E000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FFF335E0000 Size: 0xF2000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FFF33280000 Size: 0x35E000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FFEFFBF0000 Size: 0x31000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FFF31DD0000 Size: 0x263000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FFEAD460000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCompiler_47.dll Base Address: 0x7FFF32040000 Size: 0x45D000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FFED36B0000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FFF35570000 Size: 0xCA000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FFEE2D40000 Size: 0x9C000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FFF20ED0000 Size: 0x27F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FFF15BC0000 Size: 0x32B000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FFF02780000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FFF34950000 Size: 0xD000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FFF35530000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FFEF1210000 Size: 0x84000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FFEBECC0000 Size: 0x48E000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FFEF7760000 Size: 0x1BC000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FFEBDDD0000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FFF2C2C0000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FFF35EB0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FFF15B10000 Size: 0x8E000
C:\WINDOWS\SYSTEM32\MSWSOCK.dll Base Address: 0x7FFF35870000 Size: 0x6A000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FFF2F760000 Size: 0x19000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FFF35AC0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\OLEACC.dll Base Address: 0x7FFF1ADD0000 Size: 0x66000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FFEB0030000 Size: 0x125000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FFF31B00000 Size: 0xF6000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FFEF8D30000 Size: 0x34000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FFF2E1C0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\SSPICLI.DLL Base Address: 0x7FFF35FD0000 Size: 0x32000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FFF2C290000 Size: 0xC000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FFEF9170000 Size: 0x2F5000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FFF35510000 Size: 0x12000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FFF36010000 Size: 0x2E000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FFEFCBE0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FFF15BA0000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FFF15B00000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FFF2FE60000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FFF2DC10000 Size: 0x10C000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FFF22CA0000 Size: 0x4D9000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FFF312B0000 Size: 0x27000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FFF30670000 Size: 0xB000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FFF1B240000 Size: 0x98000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FFF34DD0000 Size: 0x64000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FFF352A0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FFF31DB0000 Size: 0x14000
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll Base Address: 0x7FFF30430000 Size: 0x1B4000
C:\WINDOWS\SYSTEM32\Wldp.dll Base Address: 0x7FFF35A90000 Size: 0x30000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll Base Address: 0x7FFF1B530000 Size: 0x7000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FFF188F0000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FFF312A0000 Size: 0xA000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FFEFA5F0000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FFF301B0000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FFF31D90000 Size: 0xD000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FFF22AD0000 Size: 0x1CF000
C:\WINDOWS\SYSTEM32\d3dx11_43.dll Base Address: 0x7FFEFF340000 Size: 0x46000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FFEB2210000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FFF14AF0000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FFF2F3B0000 Size: 0x1E4000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FFF35E20000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FFF2FDF0000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FFF2FEF0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FFF2D9A0000 Size: 0x148000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FFF33DD0000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FFF2E180000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FFF34990000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FFF19A00000 Size: 0x24000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FFF34960000 Size: 0x23000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FFF2CF40000 Size: 0x2B1000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FFF2A020000 Size: 0x152000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FFF33FB0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FFF33820000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FFF286B0000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FFF28720000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FFEFA2A0000 Size: 0xB000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FFF35B00000 Size: 0x27000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FFF35640000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FFF38A10000 Size: 0x1F8000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FFF35260000 Size: 0x33000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FFF29CE0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FFF35650000 Size: 0x4B000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FFF36050000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FFF33BC0000 Size: 0x14000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FFF2D200000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FFF2A180000 Size: 0xF9000
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll Base Address: 0x7FFF30800000 Size: 0x200000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FFF2D230000 Size: 0x1ED000
C:\WINDOWS\SYSTEM32\wbemcomn.dll Base Address: 0x7FFF21230000 Size: 0x90000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FFF06370000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FFF31070000 Size: 0x65000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FFF341B0000 Size: 0x792000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FFEFDBB0000 Size: 0x26000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FFF32BB0000 Size: 0x154000
C:\WINDOWS\System32\ADVAPI32.dll Base Address: 0x7FFF37C10000 Size: 0xAE000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FFF37550000 Size: 0xDA000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FFF361B0000 Size: 0x156000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\NvCamera\NvCamera64.dll Base Address: 0x7FFE99F10000 Size: 0x84F000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\NvCamera\d3dcompiler_47_64.dll Base Address: 0x7FFE99B00000 Size: 0x404000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\nvldumdx.dll Base Address: 0x7FFF2DB30000 Size: 0xBE000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\nvwgf2umx.dll Base Address: 0x7FFF24250000 Size: 0x368D000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FFF378E0000 Size: 0x2B000
C:\WINDOWS\System32\IMM32.dll Base Address: 0x7FFF37510000 Size: 0x32000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FFF373E0000 Size: 0xBF000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FFF366E0000 Size: 0x2D2000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FFF30680000 Size: 0x85000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FFF37630000 Size: 0x115000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FFF36C80000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FFF38490000 Size: 0xCD000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FFF383F0000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FFF37750000 Size: 0x125000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FFF38560000 Size: 0x468000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FFF36C90000 Size: 0x743000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FFF37B00000 Size: 0x55000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FFF36AE0000 Size: 0x19D000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FFF369C0000 Size: 0x6A000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FFF37CC0000 Size: 0x6B000
C:\WINDOWS\System32\bcrypt.dll Base Address: 0x7FFF36A30000 Size: 0x27000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FFF36650000 Size: 0x82000
C:\WINDOWS\System32\cfgmgr32.dll Base Address: 0x7FFF36310000 Size: 0x4E000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FFF37B60000 Size: 0xAF000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FFF37E80000 Size: 0x354000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FFF2CE70000 Size: 0x80000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FFF36460000 Size: 0x10F000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FFF37E60000 Size: 0x1D000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FFF36110000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FFF37910000 Size: 0x9E000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FFF37D30000 Size: 0x12A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FFF379B0000 Size: 0x9C000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FFF37A50000 Size: 0xAD000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FFF36360000 Size: 0x100000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FFF36620000 Size: 0x22000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FFEFD680000 Size: 0x12000
C:\WINDOWS\System32\xaudio2_7.dll Base Address: 0x7FFEFF6C0000 Size: 0x8B000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll Base Address: 0x7FFF19FF0000 Size: 0xB0000
C:\WINDOWS\system32\NLAapi.dll Base Address: 0x7FFF31AE0000 Size: 0x1D000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FFEFD6C0000 Size: 0x17000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FFF2A8D0000 Size: 0x76F000
C:\WINDOWS\system32\nvspcap64.dll Base Address: 0x7FFEED540000 Size: 0x2CF000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FFEFD6A0000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FFF35140000 Size: 0x34000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FFF33AE0000 Size: 0x9E000
C:\WINDOWS\system32\wbem\fastprox.dll Base Address: 0x7FFF18B60000 Size: 0x10B000
C:\WINDOWS\system32\wbem\wbemprox.dll Base Address: 0x7FFF212C0000 Size: 0x11000
C:\WINDOWS\system32\wbem\wbemsvc.dll Base Address: 0x7FFF211A0000 Size: 0x14000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FFF313A0000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FFF16D80000 Size: 0x51000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FFF34CC0000 Size: 0xA1000
C:\Windows\System32\WindowManagementAPI.dll Base Address: 0x7FFF30C30000 Size: 0xA1000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FFF2A280000 Size: 0x141000
C:\Windows\System32\fwbase.dll Base Address: 0x7FFF34C40000 Size: 0x3A000
C:\Windows\System32\pid.dll Base Address: 0x7FFF1AC40000 Size: 0x10000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FFF2CD40000 Size: 0xA000
D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GFSDK_ShadowLib.win64.dll Base Address: 0x7FFEB2480000 Size: 0x3CC000
D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFF28730000 Size: 0x1C000
D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe Base Address: 0x7FF7DC6E0000 Size: 0x3D20600
D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\bink2w64.dll Base Address: 0x7FFF06040000 Size: 0x8D000
D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\steam_api64.dll Base Address: 0x5AC90000 Size: 0x3F000
D:\Program Files\Overwolf\0.212.1.5\OWClient.dll Base Address: 0x7FFE98450000 Size: 0x459000
D:\Program Files\Overwolf\0.212.1.5\OWExplorer.dll Base Address: 0x7FFED3630000 Size: 0x7D000
D:\Program Files\Overwolf\0.212.1.5\OWUtils.dll Base Address: 0x7FFED65D0000 Size: 0xC7000


Dumping registers:

RAX: 0x35
RCX: 0x1EA683BAC18
RDX: 0x1
RBX: 0x1E9CAFCDF38
RSI: 0x1EA5C9C407F
RDI: 0x1EA5C9CCD4D
RSP: 0xCF8F5F290
RBP: 0xCF8F5F329
R8:  0x7FF7DF5DE700
R9:  0x1E9CAFCD920
R10: 0x2
R11: 0x1E9CAFCDF10
R12: 0x8
R13: 0x1EA5C9CF8E0
R14: 0x1EA5C9C8000
R15: 0x1E9CB0E0A18

stack dump [0]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15C0EFD 0x7FF7DDCA0EFD
stack dump [1]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15C19E7 0x7FF7DDCA19E7
stack dump [2]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0xA49648 0x7FF7DD129648
stack dump [3]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15C20C9 0x7FF7DDCA20C9
stack dump [4]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0xA3DE84 0x7FF7DD11DE84
stack dump [5]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0xA416EC 0x7FF7DD1216EC
stack dump [6]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15D10C1 0x7FF7DDCB10C1
stack dump [7]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15D10C1 0x7FF7DDCB10C1
stack dump [8]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15D08EF 0x7FF7DDCB08EF
stack dump [9]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x271D0 0x7FF7DC7071D0
stack dump [10]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x208BF 0x7FF7DC7008BF
stack dump [11]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15D04F8 0x7FF7DDCB04F8
stack dump [12]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x1494 0x7FF7DC6E1494
stack dump [13]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x12BBE0F 0x7FF7DD99BE0F
stack dump [14]	 D:\Games\SteamLibrary\steamapps\common\Grand Theft Auto V\GTA5.exe+0x17C3988 0x7FF7DDEA3988
stack dump [15]	 C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [16]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

**Comment by ghost** [comment]
> > Please send the logs as well, you can find them here `%appdata%/BigBaseV2/cout.log`
> 
> 
> 
> It worked, extreme injector was the problem

extreme injector probably wasn't the problem. you may have messed with settings

**Comment by GeopJr** [comment]
Stale / needs more info / can't reproduce
