### ISSUE TITLE
Crashed by other menu

### ISSUE THREAD

**Issue by EnTechblyat** [Yimura/YimMenu#675]
I dont know what exctlly that player's menu  who crashed me but i open all of protech is still crashed like some out of memory 
And when i open game again and inject Yimmenu game crashed again i deleted bigbaseV2 date folder and re inject yimmenu
Game didnt crash

**Comment by EnTechblyat** [comment]
Ah. another bug:when i spawn more than 3 ped of bodyguard Game crash
I tested on two PC both crashed

**Comment by Yimura** [comment]
Please post logs!

You can find them here `%appdata%/BigBaseV2/cout.log`.
If the crash is in an older log please grab that one from the backup folder.

**Comment by EnTechblyat** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/10199991/cout.log)

**Comment by EnTechblyat** [comment]
hmm I didnt find log bout Ped spawn crash

**Comment by LiamD-Flop** [comment]
Possibly fixed already
