### ISSUE TITLE
[Bug]: Game content errors caused by using YimMenu

### ISSUE THREAD

**Issue by Aigio1064** [Yimura/YimMenu#678]
### Describe the bug

After injecting YimMenu, the Battle Session used by the Heist mission is inaccessible and the issues are reopened.  

### Steps To Reproduce

1. Open the game  
2. Inject the Yim menu  
3. Enter online mode  
4. Enter the killer whale submarine  
5. Start the Perico Island Heist mission  
When you start entering the battle, you will get stuck  

### Expected Behavior

I hope this error is resolved, as I mentioned earlier that the Mission Battles session is also not working

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/97342833/206888208-b65de2bb-22eb-4d5f-bb49-d5a217c6483b.png)

### Store

Steam

### Additional context

YimMenu 0bbdacb

### Build

- [X] I used YimMenu unmodified

**Comment by maybegreat48** [comment]
Cannot reproduce, do you have the latest version?

**Comment by Aigio1064** [comment]
I'm using version 8c3953a
[YimMenu[8c3953a].zip](https://github.com/YimMenu/YimMenu/files/10199915/YimMenu.8c3953a.zip)
It's not up to date, but it hasn't been long either, not even more than a week.  
![image](https://user-images.githubusercontent.com/97342833/206851574-12bb1332-ff7b-4789-959b-1eb621221a78.png)

**Comment by maybegreat48** [comment]
But this bug was fixed in f338479, 2 days ago. You can download the latest version [here](https://github.com/YimMenu/YimMenu/releases/download/nightly/YimMenu.dll)

**Comment by Yimura** [comment]
I believe this was fixed in PR #666, please make sure YimMenu is from that commit hash or newer. In general you should always make sure you use the most recent version of YimMenu when making a bug report.

**Comment by Aigio1064** [comment]
ok

**Comment by Aigio1064** [comment]
There is still a problem, This issues is reopened.
