### ISSUE TITLE
[Bug]: The more I play in the same session, the less players I can see on the minimap.

### ISSUE THREAD

**Issue by Adler-D3R** [Yimura/YimMenu#679]
### Describe the bug

When joining a new session, I can see every player on the map (the one who already spawned of course). However, if I take a look at the map several mioutes later, I will only see a part of the session. And then, if I take another look later, I'll see less and less. I remember a Script Event being charged of displaying the flag icon when a player is paused, that's why I think it could be linked to a blocked Script Event (not sure at all though, I wonder if other YimMenu users experience the same as me).

### Steps To Reproduce

1. Start the game, go in Online Mode.
2. Just play randomly, and you should notice player disapearing from the minimap.

### Expected Behavior

Player should still be shown on the minimap.

### Screenshots and/or Logs

```
No logs.
```

### Store

Rockstar

### Additional context

No additional context.

### Build

- [X] I used YimMenu unmodified

**Comment by Adler-D3R** [comment]
EDIT : After some tests, it does not seem to be related to Script Events, nor Network Events.

**Comment by Adler-D3R** [comment]
EDIT 2 : Seems like player who join after me aren't shown on the minimap. The more you play, the more player leave the session, that's why I was seeing less and less players. No idea why it behaves like this though. Are you guys experiencing the same ?

**Comment by Yimura** [comment]
Haven't noticed this myself yet, though I may be wrong.

Do you have off the radar enabled? Personally I always have reveal off the radar players enabled so that might be why I haven't noticed this yet.

**Comment by Adler-D3R** [comment]
I always play with of the radar enabled, I didn't try without it. Also, I don't play with reveal players, I should try with this too. I'll make tests without off the radar once at home.

**Comment by Adler-D3R** [comment]
I played without Off The Radar, and it seems nobody was hidden anymore, except players who had not spawned yet. Definitely linked, no idea what triggers this though.

**Comment by Yimura** [comment]
Is this still an issue?

**Comment by Adler-D3R** [comment]
Nope, you can close it now.
