### ISSUE TITLE
Detect Blackscreen

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#68]
**Is your feature request related to a problem? Please describe.**
There's no way to really detect if we're stuck inside a permanent load or if the game is just stuck loading.

**Describe the solution you'd like**
It's not actually possible to detect this black screen, but we can add a timeout.

**Comment by xM4ddy** [comment]
I guess my initial gut reaction would be to look at using the natives 
```c++
IS_SCREEN_FADED_IN();
IS_SCREEN_FADED_OUT();
IS_SCREEN_FADING_IN();
IS_SCREEN_FADING_OUT();
```
or one of the ones related to busy spinner or a combination.

**Comment by Yimura** [comment]
Yes indeed, sometimes the game calls the fade_in due to some bug in Rockstar's scripts fade_out is never called causing you to "black screen". Additionally I believe you can also use this to fix the "Infinite Load" from scripts.

**Comment by xM4ddy** [comment]
Or maybe one of these havent looked into them yet.
```c++
GET_IS_LOADING_SCREEN_ACTIVE();
IS_NETWORK_LOADING_SCENE();
_LOADINGSCREEN_IS_LOADING_FREEMODE();
```

**Comment by xM4ddy** [comment]
> Yes indeed, sometimes the game calls the fade_in due to some bug in Rockstar's scripts fade_out is never called causing you to "black screen". Additionally I believe you can also use this to fix the "Infinite Load" from scripts.

Ah I see.

**Comment by Yimura** [comment]
There might be globals with which we can check if we're loaded or what state the game is in. If we detect we're completely loaded, spawned in and ready to control our ped but somehow `IS_SCREEN_FADED_IN` is still returning true then we can maybe attempt to fix this stuff.

**Comment by xM4ddy** [comment]
Maybe take a look at this its a lua written by my friend [Quicknet-Tech](https://github.com/QuickNET-Tech) for stand mod menu but the global may be of use. https://hastebin.skyra.pw/ihuheyegeh.pgsql (global may be out of date)

**Comment by Yimura** [comment]
Seems completely unrelated, it's just a lua script that triggers main_transition to move to single player, creator, multiplayer, etc...

Could be nice to skid those "session" types and add them into YimMenu (if they're at all related)
https://github.com/Yimura/YimMenu/blob/ce3f2e3a36f295d372a8605509c1dfe24a977958/BigBaseV2/src/core/enums.hpp#L59-L71

**Comment by xM4ddy** [comment]
> Seems completely unrelated, it's just a lua script that triggers main_transition to move to single player, creator, multiplayer, etc...
> 
> Could be nice to skid those "session" types and add them into YimMenu (if they're at all related)
> 
> https://github.com/Yimura/YimMenu/blob/ce3f2e3a36f295d372a8605509c1dfe24a977958/BigBaseV2/src/core/enums.hpp#L59-L71

Look at it harder, the script gets the current transition state and displays it as a busy spinner it doen't change your session or anything. https://www.youtube.com/watch?v=-6Qv5ZJoBD8

**Comment by Yimura** [comment]
You are right, could be nice to just add to YimMenu like that, with it I/we can get a better understanding of how session transition work exactly.

**Comment by Yimura** [comment]
Haven't had this bug occur in quite a while and there doesn't  really seem to be a solution to safely assume that we're stuck on a black screen.
