### ISSUE TITLE
crashed by another menu

### ISSUE THREAD

**Issue by Killer4563782** [Yimura/YimMenu#684]
### Problem

I got crashed from another menu with a net event

### Solution

Improve the receive_net_message Protection

### Reason

Because i already got crashed the second or Third time 

### Additional context

[12:33:38][INFO/main.cpp:61]: Yim's Menu Initializing
[12:33:38][INFO/main.cpp:62]: Git Info
	Branch:	master
	Hash:	031067a6687edb8d81e9f3cc4a646c03ed83324b
	Date:	Sun Dec 11 01:28:56 2022
[12:33:38][INFO/main.cpp:65]: Settings Loaded.
Found 'SCREEN_RESOLUTION' GTA5.exe+0x16C157
Found 'RC' GTA5.exe+0x13C825C
Found 'MWL' GTA5.exe+0x5D45BB
Found 'GS' GTA5.exe+0x2BF068
Found 'ISA' GTA5.exe+0xEC43
Found 'PF' GTA5.exe+0x728E48
Found 'NPM' GTA5.exe+0x1076C6C
Found 'NH' GTA5.exe+0x15C2131
Found 'FV' GTA5.exe+0x15BF0E0
Found 'ST' GTA5.exe+0x15C2087
Found 'SP' GTA5.exe+0xA3B7CD
Found 'SG' GTA5.exe+0x15C19D8
Found 'CGSHM' GTA5.exe+0x15C6B69
Found 'S' GTA5.exe+0x1345189
Found 'WMSB' GTA5.exe+0xCDCE99
Found 'NRF' GTA5.exe+0x4A0C32
Found 'GTS' GTA5.exe+0x15C1BA0
Found 'TK' GTA5.exe+0xA3F898
Found 'TSE' GTA5.exe+0xD6A848
Found 'REH' GTA5.exe+0x167940C
Found 'SEA' GTA5.exe+0x1664215
Found 'RBWD' GTA5.exe+0x109D111
Found 'RBA' GTA5.exe+0x12E353C
Found 'RBS' GTA5.exe+0x1170CFC
Found 'RBB' GTA5.exe+0x11278C7
Found 'WBD' GTA5.exe+0x1127E10
Found 'WBQ' GTA5.exe+0x12EB2EC
Found 'WBI64' GTA5.exe+0x1174381
Found 'WBI32' GTA5.exe+0x1173253
Found 'WBB' GTA5.exe+0x1172DD8
Found 'WBA' GTA5.exe+0x1663FD6
Found 'WPGSDN' GTA5.exe+0x10CCE94
Found 'RCOE-Patch' GTA5.exe+0xCCC264
Found 'RI' GTA5.exe+0x1E9C
Found 'PTH' GTA5.exe+0x15C6625
Found 'GSH' GTA5.exe+0x15C7AF4
Found 'BE' GTA5.exe+0xA64FBB
Found 'SNITL' GTA5.exe+0x13BC4BA
Found 'CNOM' GTA5.exe+0xB108C4
Found 'NPMI' GTA5.exe+0x10D78E7
Found 'NPMS' GTA5.exe+0x110BB3A
Found 'FR' GTA5.exe+0xCC8F38
Found 'GSCFWC' GTA5.exe+0xA3A934
Found 'GGCC' GTA5.exe+0xA6F1F2
Found 'GPR' GTA5.exe+0x118F304
Found 'WPGDN' GTA5.exe+0x10CD9B0
Found 'RNM' GTA5.exe+0x14035FD
Found 'GNED' GTA5.exe+0x19D32F8
Found 'API' GTA5.exe+0x167F4D8
Found 'RCC' GTA5.exe+0x10E1EAC
Found 'CAD' GTA5.exe+0x16675F4
Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x10E2E61
Found 'RBIST' GTA5.exe+0x10E202C
Found 'MHT' GTA5.exe+0xAF80
Found 'GLT' GTA5.exe+0xD86917
Found 'MCF' GTA5.exe+0x163D5E2
Found 'N' GTA5.exe+0x10448B1
Found 'RENC' GTA5.exe+0x142900A
Found 'FDGD' GTA5.exe+0x12CF527
Found 'FDS' GTA5.exe+0x12D2084
Found 'FPFC' GTA5.exe+0x12CBEB2
Found 'FPFOA' GTA5.exe+0x12D0DA0
Found 'FPFM' GTA5.exe+0x12D22FA
Found 'FPFUM' GTA5.exe+0x69E6C7
Found 'GVOV' GTA5.exe+0x2E0438
Found 'IMCD' GTA5.exe+0x53443D
Found 'SCP' GTA5.exe+0x2ED858
Found 'SCM' GTA5.exe+0x1088BD9
Found 'FMFS' GTA5.exe+0x13BB9D8
Found 'SGSBGH' GTA5.exe+0x439B89
Found 'SGSBGH' GTA5.exe+0x13CE2BE
Found 'JSBI' GTA5.exe+0x114EA64
Found 'INT' GTA5.exe+0x15BE806
Found 'VM' GTA5.exe+0x15C19E2
Found 'GU' GTA5.exe+0x13EC4BE
Found 'HT' GTA5.exe+0x13C1BF5
Found 'PGI' GTA5.exe+0x13DCF98
Found 'PIGI' GTA5.exe+0x1082ACB
Found 'C' GTA5.exe+0xCCAF27
Found 'SDEGSDN' GTA5.exe+0x10EC0C4
Found 'SPIDN' GTA5.exe+0x10EE41C
Found 'SVGDN' GTA5.exe+0x10F5B64
Found 'GVGAS' GTA5.exe+0x10CFE54
Found 'HJR' GTA5.exe+0x115341C
Found 'WJRD' GTA5.exe+0x1154088
Found 'QP' GTA5.exe+0x1421C2E
Found 'SGS' GTA5.exe+0x1166CBC
Found 'APTS' GTA5.exe+0x11C319C
Found 'SCNM' GTA5.exe+0x11C3552
Found 'PMFR' GTA5.exe+0x13D82E0
Found 'SPDM' GTA5.exe+0x10F7FA4
Found 'SPDM' GTA5.exe+0x124FCAD
Found 'IMSV' GTA5.exe+0x11329D9
Found 'SND' GTA5.exe+0xF31D5E
Found 'RR' GTA5.exe+0xBFE9DB
Found 'GCP&SRGC' GTA5.exe+0x11C439A
Found 'HRGC' GTA5.exe+0x11BD1FA
Found 'BNA' GTA5.exe+0x16893F0
Found 'BP' GTA5.exe+0x16895DA
Found 'RS' GTA5.exe+0x3AA5DA4
Found 'SPDM' GTA5.exe+0x13B5AD8
Found 'STOPVT' GTA5.exe+0x695B04
Found 'CD' GTA5.exe+0x18ECDB
Found 'CSH' GTA5.exe+0xA2CD60
Found 'CW' GTA5.exe+0x166717
Found 'WBGH' GTA5.exe+0x1129640
Found 'RBGH' GTA5.exe+0x1129730
Found 'CAC' GTA5.exe+0x144BF98
Found 'IDC' GTA5.exe+0x671F92
[12:33:41][DEBUG/module.cpp:49]: Waiting for socialclub.dll...
Found 'PD' GTA5.exe+0xC4EF8
[12:33:42][INFO/main.cpp:68]: Pointers initialized.
[12:33:43][INFO/main.cpp:71]: Renderer initialized.
[12:33:43][INFO/main.cpp:74]: Fiber pool initialized.
[12:33:43][INFO/main.cpp:77]: Hooking initialized.
[12:33:43][INFO/main.cpp:80]: Thread pool initialized.
[12:33:43][DEBUG/thread_pool.cpp:21]: Allocating 16 threads in thread pool.
[12:33:43][DEBUG/gta_data_service.cpp:134]: Loading data from cache.
[12:33:43][INFO/gta_data_service.cpp:146]: Loading 309 peds from cache.
[12:33:43][INFO/gta_data_service.cpp:164]: Loading 776 vehicles from cache.
[12:33:43][INFO/gta_data_service.cpp:182]: Loading 291 weapons from cache.
[12:33:43][DEBUG/gta_data_service.cpp:140]: Loaded all data from cache.
[12:33:43][INFO/main.cpp:97]: Registered service instances...
[12:33:43][INFO/main.cpp:114]: Scripts registered.
[12:33:43][INFO/main.cpp:117]: Hooking enabled.
[12:33:43][INFO/main.cpp:120]: Dynamic native hooker initialized.
[12:33:43][WARNING/invoker.cpp:56]: Failed to find 0x812595A0644CE1DE native's handler.
[12:33:44][INFO/backend.cpp:31]: Starting script: Self
[12:33:44][INFO/backend.cpp:57]: Starting script: Weapons
[12:33:44][INFO/backend.cpp:82]: Starting script: Vehicles
[12:33:44][INFO/backend.cpp:117]: Starting script: Miscellaneous
[12:33:44][INFO/backend.cpp:135]: Starting script: Remote
[12:33:44][INFO/backend.cpp:149]: Starting script: No clip
[12:33:44][INFO/backend.cpp:161]: Starting script: Ls customs
[12:33:44][INFO/backend.cpp:173]: Starting script: Rainbow paint
[12:33:44][INFO/backend.cpp:185]: Starting script: Vehicle fly
[12:33:44][INFO/backend.cpp:105]: Starting script: turnsignal
[12:33:44][INFO/backend.cpp:197]: Starting script: Disable Control Action
[12:34:14][DEBUG/send_metric.cpp:47]: METRIC: UVC; DATA: "vc":false
2022/12/11 12:36:06 590023

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 24892

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files\NVIDIA Corporation\NvContainer\MessageBus.dll Base Address: 0x7FF9B1B40000 Size: 0x737000
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FF9B0D10000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FF949CD0000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FF9612B0000 Size: 0xB9B000
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2211.5-0\MpOav.dll Base Address: 0x7FF9A6E50000 Size: 0x7B000
C:\Users\patri\AppData\Local\Discord\app-1.0.9008\modules\discord_hook-1\discord_hook\d07f021492a\DiscordHook64.dll Base Address: 0x7FF95D210000 Size: 0x127000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FF9BCFE0000 Size: 0x182000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FF9C2F90000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FF9C2F70000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FF9AB4D0000 Size: 0x51000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FF9C0B90000 Size: 0xF2000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FF9C06F0000 Size: 0x35E000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FF9B8C20000 Size: 0x31000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FF9BF140000 Size: 0x263000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FF962B50000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCompiler_47.dll Base Address: 0x7FF9BF3B0000 Size: 0x45D000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FF9B4BA0000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FF9C2A70000 Size: 0xCA000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FF9A1CF0000 Size: 0x9C000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FF9B4920000 Size: 0x27F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FF9A8DA0000 Size: 0x32B000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FF9B4FD0000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FF9C1E20000 Size: 0xD000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FF9C2A20000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FF986D00000 Size: 0x84000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FF9637D0000 Size: 0x48E000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FF9AED30000 Size: 0x1BC000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FF965370000 Size: 0x10A000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FF9BB4E0000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FF9C31B0000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FF9ACE60000 Size: 0x8E000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FF9AB0C0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FF9C3050000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\OLEACC.dll Base Address: 0x7FF9BAE30000 Size: 0x66000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FF986BD0000 Size: 0x125000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FF9BE8D0000 Size: 0xF6000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FF9AFE80000 Size: 0x34000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FF9BB860000 Size: 0x19000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FF9A9C60000 Size: 0xC000
C:\WINDOWS\SYSTEM32\SspiCli.dll Base Address: 0x7FF9C3480000 Size: 0x32000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FF9A4F20000 Size: 0x2F5000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FF9C2A00000 Size: 0x12000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FF9C34C0000 Size: 0x2E000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FF9878C0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FF9ACEF0000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FF9ACE50000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FF9BD7B0000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FF9BC5E0000 Size: 0x10C000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FF9A4620000 Size: 0x4D9000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FF9B4210000 Size: 0x27000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FF9BD7A0000 Size: 0xB000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FF9AF8B0000 Size: 0x98000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FF9C22C0000 Size: 0x64000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FF9C2790000 Size: 0x19000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FF9BEDB0000 Size: 0x14000
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll Base Address: 0x7FF9BC1D0000 Size: 0x1B4000
C:\WINDOWS\SYSTEM32\Wldp.dll Base Address: 0x7FF9C3020000 Size: 0x30000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll Base Address: 0x7FF9BBB80000 Size: 0x7000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FF9A6ED0000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FF9BDCE0000 Size: 0xA000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FF9878A0000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FF9BCD00000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FF9B8FE0000 Size: 0xD000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FF9B96F0000 Size: 0x1CE000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FF95EB20000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FF9ACAC0000 Size: 0x35000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FF9B1080000 Size: 0x1E4000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FF9C3370000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FF9BDCC0000 Size: 0x1D000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FF9BDCF0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FF9BC6F0000 Size: 0x148000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FF9C1190000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FF9BE3B0000 Size: 0x3B000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FF9C1E80000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FF9B0BE0000 Size: 0x24000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FF9C1E30000 Size: 0x23000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FF9B4240000 Size: 0x2B1000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FF9BB340000 Size: 0x152000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FF9C1480000 Size: 0x12000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FF9BE780000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FF9BFE10000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FF9BFE20000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FF9BB880000 Size: 0xB000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FF9C3090000 Size: 0x27000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FF9C2A60000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FF9C5ED0000 Size: 0x1F8000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FF9C2750000 Size: 0x33000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FF9B0BA0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FF9C2B40000 Size: 0x4B000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FF9C3500000 Size: 0x1F000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FF9C1090000 Size: 0x14000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FF9B2920000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FF9BB1F0000 Size: 0xF9000
C:\WINDOWS\SYSTEM32\twinapi.appcore.dll Base Address: 0x7FF9BC8E0000 Size: 0x200000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FF9B2950000 Size: 0x1ED000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FF9B8D20000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FF9BE630000 Size: 0x65000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FF9C1680000 Size: 0x792000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FF9AB100000 Size: 0x26000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FF9BFF40000 Size: 0x154000
C:\WINDOWS\SYSTEM32\xinput1_4.dll Base Address: 0x7FF9A9C70000 Size: 0x11000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FF9C4A50000 Size: 0xDA000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FF9C3940000 Size: 0x156000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\NvCamera\NvCamera64.dll Base Address: 0x7FF95BB30000 Size: 0x84F000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\NvCamera\d3dcompiler_47_64.dll Base Address: 0x7FF95AC00000 Size: 0x404000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\nvcuda64.dll Base Address: 0x7FF947FA0000 Size: 0x1D29000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\nvldumdx.dll Base Address: 0x7FF9AA460000 Size: 0xBE000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f52c4b8723f8dd33\nvwgf2umx.dll Base Address: 0x7FF980330000 Size: 0x368D000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FF9C4DF0000 Size: 0x2B000
C:\WINDOWS\System32\IMM32.dll Base Address: 0x7FF9C4950000 Size: 0x32000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FF9C4990000 Size: 0xBF000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FF9C35F0000 Size: 0x2D2000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FF9BCE90000 Size: 0x85000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FF9C4C30000 Size: 0x115000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FF9C5890000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FF9C57C0000 Size: 0xCD000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FF9C4940000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FF9C44B0000 Size: 0x125000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FF9C3F90000 Size: 0x468000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FF9C4F30000 Size: 0x744000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FF9C4B30000 Size: 0x55000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FF9C5C80000 Size: 0x1A1000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FF9C38D0000 Size: 0x69000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FF9C5C10000 Size: 0x6B000
C:\WINDOWS\System32\advapi32.dll Base Address: 0x7FF9C4E20000 Size: 0xAE000
C:\WINDOWS\System32\bcrypt.dll Base Address: 0x7FF9C35C0000 Size: 0x27000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FF9C3D00000 Size: 0x82000
C:\WINDOWS\System32\cfgmgr32.dll Base Address: 0x7FF9C3EC0000 Size: 0x4E000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FF9C5A50000 Size: 0xAF000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FF9C45E0000 Size: 0x355000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FF9B34B0000 Size: 0x80000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FF9C3AA0000 Size: 0x10F000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FF9C5BF0000 Size: 0x1D000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FF9C3C60000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FF9C4B90000 Size: 0x9E000
C:\WINDOWS\System32\mswsock.dll Base Address: 0x7FF9C2D80000 Size: 0x6A000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FF9C5690000 Size: 0x12A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FF9C4D50000 Size: 0x9C000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FF9C4400000 Size: 0xAD000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FF9C3D90000 Size: 0x100000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FF9C3E90000 Size: 0x22000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FF9AC070000 Size: 0x12000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll Base Address: 0x7FF9B3F40000 Size: 0xB0000
C:\WINDOWS\system32\NLAapi.dll Base Address: 0x7FF9BF810000 Size: 0x1D000
C:\WINDOWS\system32\XAudio2_7.dll Base Address: 0x7FF9A3080000 Size: 0x8B000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FF9ACD20000 Size: 0x17000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FF99C730000 Size: 0x76F000
C:\WINDOWS\system32\nvspcap64.dll Base Address: 0x7FF962DC0000 Size: 0x2CF000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FF9AC090000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FF9C2630000 Size: 0x34000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FF9C0F10000 Size: 0x9E000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FF99E020000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FF9AEAA0000 Size: 0x51000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FF9C21B0000 Size: 0xA1000
C:\Windows\System32\WindowManagementAPI.dll Base Address: 0x7FF9BCDC0000 Size: 0xA1000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FF9B7FC0000 Size: 0x141000
C:\Windows\System32\fwbase.dll Base Address: 0x7FF9C2130000 Size: 0x3A000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FF9B3570000 Size: 0xA000
D:\Games\Grand Theft Auto V\GFSDK_ShadowLib.win64.dll Base Address: 0x7FF95ED90000 Size: 0x3CC000
D:\Games\Grand Theft Auto V\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF9B9030000 Size: 0x1C000
D:\Games\Grand Theft Auto V\GTA5.exe Base Address: 0x7FF745DA0000 Size: 0x3D20600
D:\Games\Grand Theft Auto V\bink2w64.dll Base Address: 0x7FF9B5060000 Size: 0x8D000
D:\Source code\YimMenu\out\build\x64-Release\YimMenu.dll Base Address: 0x7FF946C60000 Size: 0x50F000

Dumping registers:

RAX: 0x0
RCX: 0x0
RDX: 0x5CE08FC750
RBX: 0x25295841188
RSI: 0x0
RDI: 0x5CE08FC750
RSP: 0x5CE08FC6D0
RBP: 0x5CE08FC720
R8:  0x0
R9:  0x0
R10: 0x2529579BC10
R11: 0x25295841188
R12: 0xE56
R13: 0x1
R14: 0xFFFCFFFF
R15: 0x5CE08FC7C8

stack dump [0]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1618978 0x7FF7473B8978
stack dump [1]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x10FAD9F 0x7FF746E9AD9F
stack dump [2]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1666A89 0x7FF747406A89
stack dump [3]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x10A9E39 0x7FF746E49E39
stack dump [4]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x10E277B 0x7FF746E8277B
stack dump [5]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1679A10 0x7FF747419A10
stack dump [6]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1671498 0x7FF747411498
stack dump [7]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1676ADC 0x7FF747416ADC
stack dump [8]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x13BAE51 0x7FF74715AE51
stack dump [9]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1676C06 0x7FF747416C06
stack dump [10]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x140367E 0x7FF7471A367E
stack dump [11]	 D:\Source code\YimMenu\src\hooks\protections\receive_net_message.cpp L: 226 big::hooks::receive_net_message
stack dump [12]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1403731 0x7FF7471A3731
stack dump [13]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1403447 0x7FF7471A3447
stack dump [14]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x14274DA 0x7FF7471C74DA
stack dump [15]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x108B450 0x7FF746E2B450
stack dump [16]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x15D10C1 0x7FF7473710C1
stack dump [17]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x15D08EF 0x7FF7473708EF
stack dump [18]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x271AA 0x7FF745DC71AA
stack dump [19]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x208BF 0x7FF745DC08BF
stack dump [20]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x15D04F8 0x7FF7473704F8
stack dump [21]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x1494 0x7FF745DA1494
stack dump [22]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x12BBE0F 0x7FF74705BE0F
stack dump [23]	 D:\Games\Grand Theft Auto V\GTA5.exe+0x17C3988 0x7FF747563988
stack dump [24]	 C:\WINDOWS\System32\KERNEL32.DLL+0x174B4 BaseThreadInitThunk
stack dump [25]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526A1 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

**Comment by Adler-D3R** [comment]
I don't think that was a modder.
It's not because the crash occurs in ReceiveNetMessage hook that it has to do with a modder.
Also, after taking a look at the file, it seems it crashed right after the return, at the next `}`.
No real idea what could cause this, it can happen some data is not correctly parsed or treated ans that it goes boom, but I don't really think it's a modder, since I don't know any crash from this hook (except maybe some buffer crash that could go there).
I could be wrong though lol.

**Comment by Killer4563782** [comment]
ok so it wasn't a modder it just was a random crash then ? if this the case i can close this issue right ? or could it be a crash that doesnt Get blocked and thats why it shows the line ?

**Comment by Yimura** [comment]
It's probably one of the sync protections that blocked something and made the game crash right after.

**Comment by Yimura** [comment]
Closing as this issue has gone stale and possible fixed in the current versions of YimMenu.
