### ISSUE TITLE
[Bug]: Crash Protection

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#685]
### Describe the bug

Example: Someone tried a Blocked Crash (not SE) once it Blocks it but if he spams it multiplier times you getting crashed by it, need to be confirmed by other!

### Steps To Reproduce

1. Attacker loaded xforce mod menu
2. Used basic Crash on you => Blocked
3. Spams basic crash on you => Crash

### Expected Behavior

Spam Crash => Crash

### Screenshots and/or Logs

- x

### Store

Rockstar

### Additional context

Fix Idea: after receive one crash by someone timeout him for 10sec to prevent a spam crash which crashes you (maybe breaks the menu bec of that)

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment]
Probably sound crash

**Comment by Adler-D3R** [comment]
If it's sound crash, it should be easily blockable in ReceivedNetEvent Hook. You just need to add a rate limiter, and here you go.

**Comment by Yimura** [comment]
Rate Limiter already exists, check the hook.

**Comment by Yimura** [comment]
This has been fixed with #767
