### ISSUE TITLE
[Bug]: YimMenu makes it so I can't setup my GTA

### ISSUE THREAD

**Issue by LiamD-Flop** [Yimura/YimMenu#689]
### Describe the bug

When I have a fresh install of gta and I inject right when I launch it to get the full YimMenu experience. It shows me the popup to load game cache. But I can't as I'm setting up my game.... But I can't setup my game because I have the YimMenu popup

### Steps To Reproduce

1. Uninstall gta and all it's files
2. Install gta
3. Launch gta for the first time
4. Inject YimMenu
5. Be amazed

### Expected Behavior

I would expect YimMenu to patiently wait for me to setup my stuff :)

### Screenshots and/or Logs

![image](https://user-images.githubusercontent.com/40887493/207165463-ffc83eee-bee8-44d4-bb93-c7ad7af3a053.png)

### Store

Steam

### Additional context

Makes the game totally unplayable

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Nice hardlock 👍

**Comment by Peax** [comment]
I remember this. Try connecting a Xbox Controller.
