### ISSUE TITLE
[Bug]: New Update in GTA

### ISSUE THREAD

**Issue by BugisoftRSG** [Yimura/YimMenu#692]
### Describe the bug

Welcome back to Los Scumtus with new innovative changes we dont even care about trailer so fuck you and new cars that nobody will use in 1 week. Even on our logo for this update we shit on you except for a combat lesbian, some more npcs you dont care and get 1 call per minute. AND for the best Ron is back because a update without reused locations, npcs wouldnt be our standard. So turn back today. jk

fuck you rockstar for removing the rtti

+ Menu not working because some sigs changed etc. every time the same game

### Steps To Reproduce

Inject YimMenu
Get Crashed
Be Happy

### Expected Behavior

No Crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Should be fixed after #691 is merged.
