### ISSUE TITLE
[Bug]: New version you uploaded still crsahing, is it expected? 

### ISSUE THREAD

**Issue by MrNoBrain** [Yimura/YimMenu#695]
### Describe the bug

when trying to inject the version u uploaded 14min ago still crashing idk if is not to be used yet 

### Steps To Reproduce

1. Inject
2. crash
3. :]

### Expected Behavior

Is expected to work or is that in-proggres  version ?

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Nightly is automatically triggered, it being new doesn't mean anything new was added to the repository.

Please keep track of #692 or #691 to stay up-to-date on YimMenu being updated.
