### ISSUE TITLE
[Bug]: PV kicking, ContextMenu break game

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#699]
### Describe the bug

After update, PV kickout both again, if player too close in any way.
Context menu still deadly freeze after interact on players vehs - break game until reinject.. 

### Steps To Reproduce

Get PV and come close to any player, get kicked from it.
Sit in car, get C4, toggle menu and try to interact(kill eng, or delete) other player vehicle. 

### Expected Behavior

Cars dont kicking, menu works..

### Screenshots and/or Logs

no logs

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
seems to be fixed?

**Comment by vladdoser** [comment]
Menu still freeze while trying to access to other player, but unlagg after ~min.
PV still trying to kick me, while riding close to other player
![image](https://user-images.githubusercontent.com/49642466/212762280-147e0f5c-83c1-43c0-b21c-4c18842ba138.png)

**Comment by Yimura** [comment]
Disable RID spoofing or the notification of someone trying to kick you from  your vehicle.

**Comment by vladdoser** [comment]
Looks like last comment true. Its not big deal, but exists. Thanks.

**Comment by Yimura** [comment]
Can you confirm the freezing still occurs?

**Comment by vladdoser** [comment]
still, if car in other player sync, i think
![image](https://user-images.githubusercontent.com/49642466/212764171-2de89782-e6ae-486c-b14c-1b1dfc1d7826.png)
![image](https://user-images.githubusercontent.com/49642466/212764174-afed0642-723e-4a4b-9066-983f4d92ab93.png)
