### ISSUE TITLE
[DETECTED] YimMenu is being detected!

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#702]
YimMenu is being detected by the sigscanner, my advise is not to use if you care about your account until a bypass is implemented.

We removed the previous bypass as its specific implementation was being detected by the anti-cheat. We're currently looking into other possiblities to fix this issue.

**Comment by Yimura** [comment]
Possibly fixed with #703

**Comment by Yimura** [comment]
Appears to have been fixed with #703.

**Comment by Yimura** [comment]
YimMenu still appears to be detected by something else, however the sigscanner has been successfully defeated.

**Comment by Fuscina** [comment]
> YimMenu still appears to be detected by something else, however the sigscanner has been successfully defeated.

Metrics, Ie Using God mode, teleporting

**Comment by Democles85** [comment]
I was just using it... oof. Hope nothing bad happens I guess 😵‍💫

**Comment by Democles85** [comment]
> 

Was just using the vehicle handling thingy and on a Private Lobby, so... :d

**Comment by Yimura** [comment]
> Metrics, Ie Using God mode, teleporting

Yeah those metrics I'm not too worried about however it's a different type of detection that worries me.
You need to do something specific with YimMenu before it triggers, trying to figure out what.

**Comment by maybegreat48** [comment]
There are two things that are currently detecting YimMenu:
1. Something is intentionally tampering with the sigscan time variable in order to send out a report transaction
2. Some other thing is causing a stat named `MINORITY_REPORT` to be set on your account and also reporting you to every player that joins

**Comment by Gh0sSte** [comment]
interesting. Is there a way we can clear the stat?

**Comment by Yimura** [comment]
> interesting. Is there a way we can clear the stat?

I would advice against trying to reset the stat, it might cause a ban on your account if you try to lower the value of it.

**Comment by Gh0sSte** [comment]
can you check if you have the stat on you? like see how many times it has been set on you...

**Comment by Gh0sSte** [comment]
im sorry my english is very poor. I may be hard to understand

**Comment by maybegreat48** [comment]
You can try using GTAHaX

**Comment by Yimura** [comment]
My account is very old and in the past my cheats have been terrible, I'm sure the number is fairly high on mine.

**Comment by Gh0sSte** [comment]
rockstar has a habit of detecting stuff but doing nothing with it...

**Comment by Democles85** [comment]
> rockstar has a habit of detecting stuff but doing nothing with it...

Would hope this one is one of those cases. Cause loosing a main account it's annoying as hell. 
Regarding the sigscan, could it be something that is happening during the injection of the DLL,  during loading in online mode or some option while using the menu?

**Comment by Yimura** [comment]
False alarm, it seems the tool we were using to develop experimental stuff was causing it.
YimMenu vanilla does not cause this issue.

**Comment by Yimura** [comment]
That should get rid of the last possible detection report from being sent out.
