### ISSUE TITLE
R* patching these features / Drop cash,Ceo kick, Ceo ban & Turn into random animal

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#705]
That was last update from Stand menu :

`• Removed drop cash, ceo kick, ceo ban & turn into random animal due to R* patching these features`

**Comment by TheGreenBandit** [comment]
> `• Removed drop cash, ceo kick, ceo ban & turn into random animal due to R* patching these features`

Idk if drop cash can be patched, but for ceo kick, ban, and turn into animal they probably were just a bit lazy and didnt feel like getting the script events

**Comment by maybegreat48** [comment]
```c++
void func_20734(int iParam0) // Position - 0x6355D4 Hash - 0xDC3C7972 ^0x38AB6921
{
    struct<4> eventData;
    char* str;
    char* str2;

    if (SCRIPT::GET_EVENT_DATA(SCRIPT_EVENT_QUEUE_NETWORK, iParam0, &eventData, 4))
    {
        if (_IS_PLAYER_BOSS_OF_ORGANIZATION(eventData.f_1) && func_8968(eventData.f_1, false)) // << checks if the sender is the leader of the target's CEO/MC
        {
```
Same checks exists for CEO ban
