### ISSUE TITLE
[Bug]: The game crashes when a vehicle handling profile is loaded up.

### ISSUE THREAD

**Issue by Nygosaki** [Yimura/YimMenu#707]
### Describe the bug

The game crashes when a vehicle handling profile is loaded up.
Video: https://imgur.com/a/7f6uDNg

### Steps To Reproduce

1. Save a Vehicle Handling Profile
2. Load up the profile
3. Crash!

### Expected Behavior

Doesn't crash

### Screenshots and/or Logs

Video: https://imgur.com/a/7f6uDNg

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
This is normal, I added more data to the CHandlingData structure and this would end up overriding the original data.
I'll have to start using JSON again to save handling data.
