### ISSUE TITLE
[Bug]: Cayoperico not loading when u want to do gather intel.

### ISSUE THREAD

**Issue by MrNoBrain** [Yimura/YimMenu#708]
### Describe the bug

When u have injected menu no matter if u got all protection off or force host off u wont be able to get to landing cutscene and need to find new season.

### Steps To Reproduce

1. got menu already injected
2. protection ( all off doesn't matter still wont work even if on)
3. start gather intel mission
4.Fly with plane to point where it should tp u to cutscene
5.infinite loading.  [even if u unload menu before getting  to point]

### Expected Behavior

No idea how it works but it sometimes happened to other preps missions but the cayo perico all the time.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

If u unload menu and change server it works again but menu crash GTA if u inject it again many times 
 just found out the menu cmd is sill in background if I unload it in mission, but the menu itself its not working in game after it and when u close it its crash game and u cant inject before u close it

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
I can confirm this, duplicate of #678 and #670

**Comment by Yimura** [comment]
Duplicate of #678
Duplicate of #670
