### ISSUE TITLE
[Request]: Session Counter

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#710]
### Problem

Want session counter for searched sessions.
report protection from other players who tries to report. (If possible)

### Solution

.

### Reason

.

**Comment by Yimura** [comment]
Report protection already exist, in the notification settings you can enable notifications of other players trying to report you.

https://github.com/YimMenu/YimMenu/blob/8c3953ab20eab0c88e796b48f46269a47b3182c9/src/hooks/protections/increment_stat_event.cpp#L1-L34

**Comment by Honex98** [comment]
ok, thanks. now the session counter, would be cool if i can know how many sessions r on

**Comment by Yimura** [comment]
> ok, thanks. now the session counter, would be cool if i can know how many sessions r on

We can't really grab all sessions that exists because there are limits on how many sessions can be fetched from the API.
We can only show a number for the sessions that have been returned by your search criteria.

**Comment by Honex98** [comment]
> We can't really grab all sessions that exists because there are limits on how many sessions can be fetched from the API.
>We can only show a number for the sessions that have been returned by your search criteria.

ye that would be nice too.
also, i dont get the part explaining how to spoof, i mean i tried changing session but it didnt work, i still can see my real account name

**Comment by Yimura** [comment]
> ye that would be nice too. also, i dont get the part explaining how to spoof, i mean i tried changing session but it didnt work, i still can see my real account name

Go into a session with a friend and ask him to verify the spoofed name and RID, you can't see your spoofed user details as they are server side and not client side (aka you can't see the modified name in your game).
Or ask someone in your session to read out your name.

**Comment by Honex98** [comment]
also joining cayo heist is buggy, its stuck.

**Comment by Yimura** [comment]
> also joining cayo heist is buggy, its stuck.

Please note that issues aren't a place to discuss your thoughts on the menu but to report single feature requests or report single bugs.

There exists several issues already noting the same #678, #670 and #708. Before opening an issue please verify there doesn't already exist one.

**Comment by Honex98** [comment]
Changed the header to suggest a new request.

**Comment by Yimura** [comment]
> Changed the header to suggest a new request.

No you should make a new issue if you want to request something new.

**Comment by Yimura** [comment]
This has been implemented by #954
