### ISSUE TITLE
[Request]: Use ImGui C++ headers

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#718]
### Problem

Currently we require char* for input fields.

### Solution

Include the following header `misc/cpp/imgui_stdlib.h`.

### Reason

This way we can just use `std::string` instead of struggling between char* and std::string.

**Comment by TheRouletteBoi** [comment]
std::string will affect performace. can I suggest using std::string_view instead?

**Comment by Yimura** [comment]
> std::string will affect performace. can I suggest using std::string_view instead?

Do some research first because std::string_view is not a storage class, from the cpp reference page:
```
The class template basic_string_view describes an object that can refer to a constant contiguous sequence of char-like objects with the first element of the sequence at position zero.
```

Note the "describes an object that can refer to a constant contiguous sequence of char-like objects", this means that a string_view can only point to somewhere else in memory and that that object is non-modifiable.
We can technically write to this memory region but that's undefined behavior and should never be done, that's a good way to cause crashes of memory overflows.

I'm proposing this as currently there some serious inefficient code to write to std::string in YimMenu:
https://github.com/YimMenu/YimMenu/blob/e442e284dba151d9e9b6bbde56fbd1c6606d1d36/src/views/self/view_weapons.cpp#L143-L149

You ask why I use std::string? Because our json library does not support char arrays, and adding support for that would be stupid.

**Comment by Yimura** [comment]
This has been implemented for quite a while now.
