### ISSUE TITLE
[Request]: Send SMS Message

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#719]
### Problem

Send SMS Message

### Solution

Want to send ingame sms msgs to players.

### Reason

trolling

### Additional context

it'd be funny sending ingame sms msgs to friends and players.

**Comment by gir489returns** [comment]
You basically want someone to reverse engineer the game for you and find the SMS send function. Go fuck yourself, dude.

**Comment by Honex98** [comment]
> You basically want someone to reverse engineer the game for you and find the SMS send function. Go fuck yourself, dude.

i aint a programmer it's up to the developers to either add or no.
i just suggested a thing.

**Comment by sch-lda** [comment]
Most players wont need or like this function. Yim can block spam sms. Yim can send spam sms. So,can yim block spam sms from other yim user? If you need an ad bot, you can buy one from China with only 10$

**Comment by Honex98** [comment]
nope not looking for an ad bot but i thought it'd be cool to troll friends and make a laugh. about blocking and sending, its same concept of kicking and kick protection.
its up to devs tho. if its possible in their spare time, add it.

**Comment by RainerZufall187** [comment]
what? would be useful if you want to tell them something private

**Comment by Honex98** [comment]
> what? would be useful if you want to tell them something private

yep indeed

**Comment by TheGreenBandit** [comment]
solved?

**Comment by Yimura** [comment]
Has been patched by R*, no longer possible.
