### ISSUE TITLE
[Bug]: request control

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#723]
### Describe the bug

request control event is preventing my friends to drive my personal vehicles and always teleports it away. also, i was playing with a guy in his MC bus, and we went into sparrow, as soon as we got out of kosatka, the sparrow exploded.

### Steps To Reproduce

Settings > Notifications > Request control (checked both notify and logs)

### Expected Behavior

guess it shouldnt do that.

### Screenshots and/or Logs

```
<
[12-17-2022-22-50-42_cout.log](https://github.com/YimMenu/YimMenu/files/10260268/12-17-2022-22-50-42_cout.log)
>
```

### Store

Epic Games

### Additional context

it also seems to happen with vehicle kick protection.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Honex98** [comment]
i really hope this bug to be fixed because i cant fix it myself and its really bothering

**Comment by Yimura** [comment]
Are you RID spoofing? RID spoofing will make it so you get kicked from your own vehicles.
As for the request control thing, I personally haven't had any real issue with it but I'm aware it's a thing.

**Comment by Honex98** [comment]
> Are you RID spoofing? RID spoofing will make it so you get kicked from your own vehicles. As for the request control thing, I personally haven't had any real issue with it but I'm aware it's a thing.

yes im using RID Spoofing, the kick protection succeeds to block others' "vehicle kick" but its not as a problem for me as for my friends if they wanted to use my PV, they get instantly kicked -in passenger seat- or PV being tp'ed away if they wanted to drive it.
for example, i cant let anyone get in PV in heists to missions. they get kicked however i allow it from interaction menu.

EDIT: i turned off Username, RID and IP spoofer and problem solved but i usually use spoofers so i really hope it works with spoofers on.
