### ISSUE TITLE
[Bug]: No Idle Kick does not work.

### ISSUE THREAD

**Issue by CaptainFrostty** [Yimura/YimMenu#726]
### Describe the bug

As the title describes, No Idle Kick does not work.

### Steps To Reproduce

1. Start menu and click self.
2. Check off No Idle Kick
3. Just wait for it.

### Expected Behavior

Should be able to prevent game from kicking you when idle.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

This is the nightly build I used.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Sheeeeit** [comment]
To prevert create new issue: it still isnt work on #745
