### ISSUE TITLE
[Request]: Noclip speed control

### ISSUE THREAD

**Issue by Anartale** [Yimura/YimMenu#728]
### Problem

It would be nice if you add to YimMenu control speed of Noclip from GUI

### Solution

Add a slider to adjust the speed of Noclip from 1 to 10 for example
Or it can be controlled with mouse wheel

### Reason

More convenient use of Noclip

**Comment by RainerZufall187** [comment]
Maybe with mouse wheel?

**Comment by Anartale** [comment]
> Maybe with mouse wheel?

Yea, it sounds good!

**Comment by Yimura** [comment]
Implemented.
