### ISSUE TITLE
[Bug]: RID Joiner not working.

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#729]
### Describe the bug

RID joiner not working. Native hook `network::NETWORK_SESSION_HOST` not triggered. Loaded to empty open session.

### Steps To Reproduce

1) Enter RID
2) Click "Join"

### Expected Behavior

...

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by dioguy** [comment]
How did I fix this bug myself, in the **join_session** function, after the line `session code::join_type({ eSessionType::NEW_PUBLIC });` i added  
```
const std::chrono::time_point<std::chrono::high_resolution_clock> time_point =
				std::chrono::high_resolution_clock::now();

	while (SCRIPT::GET_NUMBER_OF_THREADS_RUNNING_THE_SCRIPT_WITH_THIS_HASH(
			rage::joaat("maintransition")) == 0 && std::chrono::high_resolution_clock::now() <=
		time_point + 2s)
		script::get_current()->yield();
```
Because sometimes there is not enough time to check. @Yimura

**Comment by Yimura** [comment]
Try disabling IP spoofing and see if it changes anything.

**Comment by Yimura** [comment]
Closing this for now, if the author of the issue responds with further information I can reopen it.
