### ISSUE TITLE
[Request]: Griefer Jesus's

### ISSUE THREAD

**Issue by binded-zz** [Yimura/YimMenu#730]
### Problem

i use two different menus this stock nightly YM and tupoyemenu nightly's
i like tupoye's for the menu layout and Griefer Jesus's to send after god mode people that are griefing they cant die so they just keep attacking till they kill them which in turn means they have less time to bother others or my self 

i get alot of infinite loading screens with his menu that only closing the game will work to fix 
is Griefer Jesus's the 3 versions that he has too toxic for YM to be added ???

### Solution

add the 3 versions of Griefer Jesus's from tupoyemenu

### Reason

as stated above it gives them something else to deal with besides bugging people in god mode

**Comment by Adler-D3R** [comment]
Why do you guys always want to add stuff from other menus ? I don't get it.
Almost every menu have the same features now, cause they keep copying themselves.

**Comment by izeerF** [comment]
> Why do you guys always want to add stuff from other menus ? I don't get it. Almost every menu have the same features now, cause they keep copying themselves.

true, yim menu is nearly perfect and it dosent need thoose things like other menus have

**Comment by binded-zz** [comment]
the menus are near the same but different layout theme if you will he has a few other menu stuff that i dont care about  a few crashes but i found using any of them triggers the whole lobby trying to crash you ...

what ever izeerF i dont even care  and at least i can join a session with more then 2 people ..

**Comment by Yimura** [comment]
Can probably be achieved with the bodyguard spawn feature, closing for now.
