### ISSUE TITLE
[Bug]: Cannot enter any session with menu on

### ISSUE THREAD

**Issue by izeerF** [Yimura/YimMenu#733]
### Describe the bug

When I load menu inside story mode or i just want to change session its sending me to empty session, when im trying to join my friend it says that session no loger exists and when my friend is trying to join to me he is having the same error. 

### Steps To Reproduce

1. Open GTA
2. Inject menu
3. try to join session
OR
1. Open GTA online
2. inject menu
3. switch session

### Expected Behavior

as obvious it should join me to normal session

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Are you playing with friends? Which region do you play in? Are you only using YimMenu? Spoofing anything?

**Comment by izeerF** [comment]
like i said, yes to join them i need to unload menu and join session then load it again. central europe. yep latest version of yimmenu only. nah, no vpn or no specific spoofers.

**Comment by Yimura** [comment]
We'll keep it open as this is an ongoing issue that multiple people have reported.

**Comment by izeerF** [comment]
i know im writeing on phone rn and i missclicked sorry

**Comment by maybegreat48** [comment]
Does your friend use a mod menu? Are you sure you aren't spoofing anything? (Uncheck everything in Network > Spoofing)
By spoofing we do not mean external HWID spoofers nor VPNs but the spoofing facilities offered by the menu itself. IP spoofing is enabled by default and disabling it sometimes fixes the issue for me

**Comment by izeerF** [comment]
One friend yes, second nope. ohhh spoofing in menu, yes i have some spoofers on. ill try without it ty.

**Comment by izeerF** [comment]
Okey, after I disabled spoofing i can normally join session ty bro

**Comment by Yimura** [comment]
> Okey, after I disabled spoofing i can normally join session ty bro

Alright thanks for confirming that, we'll have to work on clarifying that and disabling IP spoofing by default instead of having it enabled.

**Comment by vladdoser** [comment]
same, if using stand with yim(loaded 1st). cant join to any session while 2 menu enabled after last few yim updates, if only yim, full time kicks from sesseions
like "error while running freemode in operation return"
![image](https://user-images.githubusercontent.com/49642466/209246249-fe062fff-08ab-4498-af58-29a2eecc6675.png)

**Comment by Yimura** [comment]
> same, if using stand with yim(loaded 1st). cant join to any session while 2 menu enabled after last few yim updates, if only yim, full time kicks from sesseions
> like "error while running freemode in operation return"
> ![image](https://user-images.githubusercontent.com/49642466/209246249-fe062fff-08ab-4498-af58-29a2eecc6675.png)
> 

What can I say except don't co-load YimMenu with Stand.
YimMenu is starting to get really complex and is modifying the game in ways  that does not allow it work nicely with other menu's.
In general it's not worth our time or our issue that YimMenu isn't working with Stand loaded. From our standpoint YimMenu works as intended.

**Comment by vladdoser** [comment]
> 

yim dont have enough protections anyway, i cant play with only yim and not to be crashed or desynced by others or by itself..
it was fine actually, but last few updates break co-load normal work

**Comment by vladdoser** [comment]
@Yimura  yim dont have enough protections anyway, i cant play with only yim and not to be crashed or desynced by others or by itself..
it was fine actually, but last few updates break co-load normal work

**Comment by Yimura** [comment]
Closing this as the solutions has been found to this issue.
