### ISSUE TITLE
[Bug]: No NPCs on the streets

### ISSUE THREAD

**Issue by dioguy** [Yimura/YimMenu#734]
### Describe the bug

No NPCs on the streets

### Steps To Reproduce

1. inject

### Expected Behavior

No bots walk the streets, only drive cars. To remove this bug, I deleted the hook hooks::create_script_handler
i also removed the code 
`for (auto& thread : *m_script_threads)
		{
			if (thread->m_handler)
				hook_script_handler((CGameScriptHandler*)thread->m_handler);
		}`
and removed natives hooks: NETWORK_SET_THIS_SCRIPT_IS_NETWORK_SCRIPT and NETWORK_TRY_TO_SET_THIS_SCRIPT_IS_NETWORK_SCRIPT.

After these actions, NPCs appeared on the streets. I'm not sure exactly which function (hook) of the above affects this

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by maybegreat48** [comment]
Do NPCs appear in singleplayer? If so, I think I know why this is occuring

**Comment by dioguy** [comment]
Yes, they appear in singleplayer

**Comment by maybegreat48** [comment]
Can you try [this](https://github.com/maybegreat48/YimMenu/suites/9991269122/artifacts/484892952) build and verify that this issue is fixed?

**Comment by dioguy** [comment]
> Can you try [this](https://github.com/maybegreat48/YimMenu/suites/9991269122/artifacts/484892952) build and verify that this issue is fixed?

It seems like this bug is fixed here

**Comment by dioguy** [comment]
@maybegreat48 Sorry for the offtop, but what should Net Time features do? The player's time does not change, he gets $2000 several times for good behavior, then he gets a transaction error. I tried to be a host before the player's join and after. He was without a menu

**Comment by Yimura** [comment]
> @maybegreat48 Sorry for the offtop, but what should Net Time features do? The player's time does not change, he gets $2000 several times for good behavior, then he gets a transaction error. I tried to be a host before the player's join and after. He was without a menu

It does not affect in-game time as in you'd expect the position of the sun and clock. But actually changes the time value used by the scripts internally. This is used to determine when to give a player an award for good behaviour or mission timers as they aren't dependend on the time from your clock.

**Comment by tupoy-ya** [comment]
Would be nice to have a helper text there so people can understand what it is.
