### ISSUE TITLE
[Bug]: Delete Gun, Gravity Gun, Repair Gun ( All the Gun mods ) stop working after a certain event that I can't pin point.

### ISSUE THREAD

**Issue by Swashn** [Yimura/YimMenu#735]
### Describe the bug

Happens every lobby that I manage to bug the options to use either of the Delete Gun, Repair Gun, Gravitiy Gun etc. It just doesn't shoot at all anymore. I can switch to " No Weapon Mod " And I can shoot normal bullets but no special bullet works either.

I think it happens everytime after you use the Delete Gun on a Player ( On accident )

### Steps To Reproduce

No clue, just play around with them

### Expected Behavior

-

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Loko415** [comment]
can agree this happens to me too.

**Comment by Loko415** [comment]
not just on a player. if you stress the thread pool out enough it eventually starts glitching and eventually it stops working. All weapon options stop working or whatever script you have put it under.

**Comment by izeerF** [comment]
yep im getting it too

**Comment by maybegreat48** [comment]
I can confirm this. The fiber pool eventually breaks after a while and you will not even be able to unload the menu. I've also noticed that my FPS drops significantly when this occurs
