### ISSUE TITLE
[Request]: Weapons in Interior

### ISSUE THREAD

**Issue by Adler-D3R** [Yimura/YimMenu#736]
### Problem

I feel kinda frustrated when I can't use my weapons everywhere, especially in Ammu Nation. 

### Solution

I'd like to have weapons in interior feature implemented in the menu.

### Reason

It could be cool to have this feature, since I think its a useful one.

**Comment by izeerF** [comment]
Why Yimura should do such useless features, u know that u can just shoot when u r in the middle of the doors and u can kill the ammu nation guy?

**Comment by Yimura** [comment]
> Why Yimura should do such useless features, u know that u can just shoot when u r in the middle of the doors and u can kill the ammu nation guy?

Request are request, and anyone is entitled to make these. In the end the it's up to us to add it to YimMenu or alternatively someone outside of the people currently working on YimMenu could add this in a Pull Request.
Let's not berate people for making a request to add a certain feature.

**Comment by izeerF** [comment]
ye, u r right

**Comment by Adler-D3R** [comment]
> Why Yimura should do such useless features, u know that u can just shoot when u r in the middle of the doors and u can kill the ammu nation guy?

I mentionned Ammu Nation as an example, but I was thinking about the Island or other weapon restricted places.
That's a suggestion, if they want to work on this, they can, if they don't want to, they won't. No problem with that.

**Comment by NefariousIntent2** [comment]
> > Why Yimura should do such useless features, u know that u can just shoot when u r in the middle of the doors and u can kill the ammu nation guy?
> 
> I mentionned Ammu Nation as an example, but I was thinking about the Island or other weapon restricted places. That's a suggestion, if they want to work on this, they can, if they don't want to, they won't. No problem with that.

I mean, most of the NPCs on Cayo are invincible. So weapons there really dont do anything. Anything with a DEC/DET model is vulernable, and destroyable
