### ISSUE TITLE
[Request]: Block all advertising SMS

### ISSUE THREAD

**Issue by Aure7138** [Yimura/YimMenu#737]
### Problem

Some text messages are sent through script events, which will not be intercepted by receive_net_message

### Solution

This is the event used to send SMS in 1.64 `1519903406`, just need to switch a few sessions to get it

### Reason

Advertising bot is annoying

### Additional context

![Imgur](https://i.imgur.com/DgLXWUy.png)
![Imgur](https://i.imgur.com/595ZWrl.png)

**Comment by maybegreat48** [comment]
The 'm' used in the message is the Cyrillic M so the chat filter wouldn't have worked anyway. There is a region switcher if you don't want to join sessions in Asia (sure there are still spammers, but they are considerably less annoying and they definitely don't promote NSFW web services in GTA Online chat...)
