### ISSUE TITLE
[Request]: Keep car engine running even when you get out of the car.

### ISSUE THREAD

**Issue by Democles85** [Yimura/YimMenu#739]
### Problem

I was looking for a general idea on how to implement a button to keep the car engine running, even when I get out of the car. 

### Solution

A code implementation solution, so I can implement it myself.

### Reason

Would be cool to have it, I guess.

**Comment by Democles85** [comment]
```c++
components::sub_title("Keep engine running");
		{
			static bool keep_engine_running = false;

			ImGui::Checkbox("Keep engine running", &keep_engine_running);  //:P

			if (keep_engine_running)
			{
				if (self::veh != 0)
				{
					VEHICLE::SET_VEHICLE_ENGINE_ON(self::veh, true, true, false);
				}
			}
		}
```

Would this be a solution?

**Comment by xiaoxiao921** [comment]
Prolly much more convenient to have it as a checkbox so that you don't have to press it each time

**Comment by Democles85** [comment]
Yeah just noticed that I did it as selectable...

**Comment by Democles85** [comment]
> Prolly much more convenient to have it as a checkbox so that you don't have to press it each time

Just noticed that I did as a selectable :P

**Comment by Democles85** [comment]
It doesn't work this way sadly, have to find out on how to do it, that even though I get out of the car the engine is on.

**Comment by Democles85** [comment]
So, there is an existing function on the object VEHICLE by the name `SET_VEHICLE_KEEP_ENGINE_ON_WHEN_ABANDONED`, which does exactly what I need it to do, thing is now, to make it a bit more quality of life, is there a way I can check every time a player enters a new vehicle and memorize this to the `self::veh`?

**Comment by Democles85** [comment]
So I have made a "solution", and @Yimura, I want your approval on this one.

_`For anyone who wants to add it to their own version of the menu. (Might not be the most optimal solution, but I am new to the game modding scene.)`_

### Step 1:
Created a function on `src -> util -> vehicle.hpp`:
```c++
	inline bool keep_engine_running(Vehicle current_vehicle, bool state) {
		if (!ENTITY::IS_ENTITY_A_VEHICLE(current_vehicle) || !entity::take_control_of(current_vehicle))
			return false;
		
		VEHICLE::SET_VEHICLE_KEEP_ENGINE_ON_WHEN_ABANDONED(current_vehicle, state);

		return true;
	}
```

### Step 2:
Created Global `bool keep_engine_running = false;` on `src -> core -> globals.hpp`

### Step 3:
Created UI Toggle on `src -> views -> vehicle -> view_vehicle.cpp`:
```c++
	ImGui::Checkbox("Keep Engine Running", &g.vehicle.keep_engine_running);
```

### Step 4:
Created file `keep_engine_running.cpp` on `src -> backend -> looped -> vehicle`:
```c++
#include "backend/looped/looped.hpp"
#include "util/vehicle.hpp"

namespace big
{
	void looped::vehicle_keep_engine_running()
	{
		if (g.vehicle.keep_engine_running) 
			vehicle::keep_engine_running(self::veh, true);
		else
			vehicle::keep_engine_running(self::veh, false);
	}
}
```

### Step 5:
Added function `void looped::vehicle_keep_engine_running()` to files `src -> backend -> backend.cpp` & `src -> backend -> looped -> looped.cpp`.

**Comment by ghost** [comment]
Why make an unnecessary call for when it's off? Use the games memory for the last vehicle you were in (can't remember the native) and keep looping it while the bool is true and while the ped is not using a vehicle.

**Comment by Democles85** [comment]
> Why make an unnecessary call for when it's off? Use the games memory for the last vehicle you were in (can't remember the native) and keep looping it while the bool is true and while the ped is not using a vehicle.

You are right, but thing is, idk how to do that yet 🤪.

**Comment by Yimura** [comment]
Looks good to me, definitely looking at adding such a feature in the future.

Also good job on working out some code yourself :+1:
