### ISSUE TITLE
[Request]: Code Execution/Scripting System

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#742]
### Solution

Allow us to execute code using native functions like 
`PED::GET_VEHICLE_PED_IS_IN(PED::PLAYER_PED_ID(), FALSE)`

or execute from a file in BigBaseV2 folder.

### Reason

The community can be creative so I feel this can reflect upon it.

**Comment by ghost** [comment]
Huh? Can you further explain?

**Comment by yasmasdas** [comment]
https://github.com/YimMenu/YimMenu/pull/488

**Comment by GeopJr** [comment]
Duplicate of #83
