### ISSUE TITLE
[Request]: CEO Abilities

### ISSUE THREAD

**Issue by Democles85** [Yimura/YimMenu#744]
### Problem

A CEO Abilities section to the Mobile Navigation tab, to allow the player to get a bullshark testosterone delivery, or some of the other abilities that CEO provides.

### Solution

A CEO Abilities section inside the Mobile Navigation Tab.

![CEO Abilities Section](https://i.imgur.com/qTZ9cPL.png)

### Reason

It would be a nice quality of life compared to Rockstars crappy menu layout. I myself am looking on how to implement this, but since I am not that familiar with game modding and am trying to get better it could take time and might not be the optimal solution.

### Additional context

:]

**Comment by TheGreenBandit** [comment]
there isnt anything that could fit in there. The only thing i find we could add is the request helicopter but that  isnt really needed as you could spawn your own.

**Comment by TheGreenBandit** [comment]
I have the helicopter script logged, just need to sort it out of a couple and icould probably make it
