### ISSUE TITLE
[Bug]: Vehicles randomly become personal vehicles

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#747]
### Describe the bug

Random cars randomly become personal vehicles

### Steps To Reproduce

1. Go to a car
2. Break into it and turn it on
3. Get kicked out
4. "You do not have access to this personal vehicle"

### Expected Behavior

The car does not randomly become permanently inaccessible to me because it is an un-owned pedestrian car

### Screenshots and/or Logs

Video of bug:
https://youtu.be/d460pxBAG5w

### Store

Steam

### Additional context

I downloaded the build from nightly. I didn't compile the solution myself.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by SkiddyToast** [comment]
Can you upload your `settings.json` file?

**Comment by cl1xa** [comment]
[settings.txt](https://github.com/YimMenu/YimMenu/files/10299386/settings.txt)

Wouldn't let me upload as json. Changed extension to txt.

**Comment by ghost** [comment]
[settings.txt](https://github.com/YimMenu/YimMenu/files/10299405/settings.txt)

Here

**Comment by urmommine** [comment]
Yep its sometimes happens to me

**Comment by Yimura** [comment]
Did you join someone in a solo session? I've only had this happen when joining session types not made for more than one person.

**Comment by ghost** [comment]
> Did you join someone in a solo session? I've only had this happen when joining session types not made for more than one person.

I use the session browser to scan for 25+ english lobbies

**Comment by RyomenPanda** [comment]
If you're using the RID spoofer try turning it off and see if it's fixed.

**Comment by Yimura** [comment]
No further response from author received and with RID spoofing disable this shouldn't be an issue anymore.
