### ISSUE TITLE
[Bug]: Seatbelt and Drive Underwater are stored under the same variable

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#748]
### Describe the bug

Checking "Drive Underwater" also forces "Seatbelt" to be checked.

### Steps To Reproduce

1. Go to Vehicle tab
2. Click on Seatbelt
3. Witness Drive underwater magically enable itself
4. Moment

### Expected Behavior

THE HACK WORKS AND ISN'T PASTED

Wasn't the menu already proofread?
(https://github.com/YimMenu/YimMenu/commit/54b3267537e3bf07f97d6a0ddb59aacf0a54d0c1)

### Screenshots and/or Logs

Gif of the phenomenon

https://i.imgur.com/jUt3nEX.gif

### Store

Steam

### Additional context

Used latest nightly build as of 12/24

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
can confirm, the problem is here
https://github.com/YimMenu/YimMenu/blob/54b3267537e3bf07f97d6a0ddb59aacf0a54d0c1/src/backend/looped/vehicle/seatbelt.cpp#L23
