### ISSUE TITLE
[Bug]: Player list UI sizing is improper

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#752]
### Describe the bug

Player list has horizontal scrolling, for no reason

### Steps To Reproduce

1. Open menu
2. Hover over any name on the player list
3. Hold shift and scroll
4. Player list will slightly shift

### Expected Behavior

Only vertical scrolling on the list of players

### Screenshots and/or Logs

https://i.imgur.com/Cnh8dvg.gif

### Store

Steam

### Additional context

Used latest nightly build as of 12/24

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by hotgreecyman** [comment]
can you stfu
