### ISSUE TITLE
How Convert ( see inside the post ) to work with YimMenu ?

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#753]
### Problem

.

### Solution

.

### Reason

.

### Additional context

How convert this to work with YimMenu

- stats.set_bool_masked : example
`stats.set_bool_masked("MP0_LIFETIME_BUY_COMPLETE",true, 6)`

- add_int_range : example
`add_int_range("1", 20000, 11000, 2500000, function() 
	return globals.get_int(262145+15788)
end, function(value)
	globals.set_int(262145+15788, value)
end)`

Thanks .

**Comment by xiaoxiao921** [comment]
?

**Comment by ghost** [comment]
Man, stop skidding. Read the arguments and think of a possible solution. Your first ''problem'' is a native..

**Comment by Yimura** [comment]
YimMenu uses natives, these are exactly the same as the one you mentioned in your example.
Though I failed to find a SET_BOOL_MASKED.

Here's STATS::STAT_SET_MASKED_INT:
https://nativedb.spyral.dev/natives/0x7BBB1B54583ED410

For the globals please use the search feature you'll find many examples in YimMenu of other globals:
https://github.com/YimMenu/YimMenu/search?q=script_global

**Comment by D-Borkan** [comment]
i found `STAT_SET_BOOL_MASKED` 
here :  https://docs.fivem.net/natives/?_0x5BC62EC1937B9E5B

is that right : example
`static BOOL STAT_SET_BOOL_MASKED(Hash statName, BOOL value, int mask, BOOL save) { return invoke<BOOL>(0x5BC62EC1937B9E5B, statName, value, mask, save); } // 0x5BC62EC1937B9E5B 0x7842C4D6 b323
`

**Comment by D-Borkan** [comment]
> Man, stop skidding. Read the arguments and think of a possible solution. Your first ''problem'' is a native..
I searched but didn't find a suitable solution so I asked if someone could help with that
