### ISSUE TITLE
[Request]: block remote kick from 2t1 and cherax

### ISSUE THREAD

**Issue by PromSkid** [Yimura/YimMenu#759]
### Problem

Most paid menus like 2take1 and cherax are adding remote kicks, can you make a protection for this please.

### Solution

Protection against remote kicks

### Reason

remote kicks are broken af and makes the game unplayable

**Comment by SkiddyToast** [comment]
The kicks are unblockable, they're technically breakup kicks.

**Comment by MarkEcza** [comment]
Well, we just got to wait until they are more widespread then fingers crossed rockstar will patch it. I guess it's up to them.

**Comment by Yimura** [comment]
It's blockable as host, but if the host has no protections against it you're pretty much fucked.

**Comment by PromSkid** [comment]
i suppose you could add the kick so rockstar patches it faster. Making the source public in yim menu

**Comment by PromSkid** [comment]
> It's blockable as host, but if the host has no protections against it you're pretty much fucked.

is this already in the menu?

**Comment by MarkEcza** [comment]
> i suppose you could add the kick so rockstar patches it faster. Making the source public in yim menu

Don't think thats a good idea...

**Comment by Yimura** [comment]
We know the theory behind the kick but implementing such a thing into YimMenu is bit more complex.

And no it's not yet in YimMenu.

**Comment by PromSkid** [comment]
will the lessen breakup kicks feature not protect against it?

**Comment by Yimura** [comment]
Has been fixed in #807 and remote kick has been added to YimMenu as well.
