### ISSUE TITLE
[Request]: Notification for trollers

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#764]
### Problem

i ran out to a troller who kept sending cages and troll stuff and i couldnt know who

### Solution

a little notification about it so i may know so i can kick them

### Reason

they r pain

**Comment by ghost** [comment]
The playerlist literally flashes their name red if they trigger anything that YimMenu is capable of detecting. Use the player database feature.

**Comment by Honex98** [comment]
> The playerlist literally flashes their name red if they trigger anything that YimMenu is capable of detecting. Use the player database feature.

not everything, some guy was trolling with cages and i couldnt know who

**Comment by SkiddyToast** [comment]
Our data node identification broke when the new update released, when we update it cages will be blocked.

**Comment by Honex98** [comment]
> Our data node identification broke when the new update released, when we update it cages will be blocked.

pretty much looking forward to it. great job so far
