### ISSUE TITLE
[Bug]: Network error while git cloning

### ISSUE THREAD

**Issue by zhongmof** [Yimura/YimMenu#768]
### Describe the bug

严重性	代码	说明	项目	文件	行	禁止显示状态
错误		CMake Error at minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake:39 (message):
  Failed to clone repository: 'https://github.com/YimMenu/minhook.git'

[1/9] Creating directories for 'minhook-populate'
[1/9] Performing download step (git clone) for 'minhook-populate'
FAILED: minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download C:/Users/djh13/Desktop/YimMenu-multi-select-gravity-gun/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download 
cmd.exe /C "cd /D C:\Users\djh13\Desktop\YimMenu-multi-select-gravity-gun\out\build\x64-Release\_deps && "D:\visual studio\ide\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P C:/Users/djh13/Desktop/YimMenu-multi-select-gravity-gun/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake && "D:\visual studio\ide\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch C:/Users/djh13/Desktop/YimMenu-multi-select-gravity-gun/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download"
ninja: build stopped: subcommand failed.		C:\Users\djh13\Desktop\YimMenu-multi-select-gravity-gun\minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake		

### Steps To Reproduce

1

### Expected Behavior

1

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

1

### Build

- [ ] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Chomator** [comment]
Failed to clone repository: 'https://github.com/YimMenu/minhook.git'

You need check you network to connected to github.com. Maybe you need add git*.exe to you proxy server.

It's about your network, not the source code.

Peace & Love.

**Comment by Yimura** [comment]
@zhongmof was your issue fixed by trying again?

**Comment by zhongmof** [comment]
> 重试解决了@zhongmof问题？

yes ,thank you
