### ISSUE TITLE
[Request]: Constructor or Converter for Fun Vehicles / Player Customizations

### ISSUE THREAD

**Issue by Swashn** [Yimura/YimMenu#769]
### Problem

Currently you can build your own Vehicles but it takes alot of time searching all the offsets and hashes and building your own car. 

### Solution

So I suggest either build something like https://github.com/hexarobi/stand-lua-constructor or a conversion tool that converts already existing vehicles into usable ones for YimMenu https://github.com/hexarobi/stand-curated-constructs

### Reason

Yes I know it's just Copy & Paste in both cases but that's the easiest way. If it's a sh*t idea let me know but I just thought it's funny to have an easier way to make such cool vehicles yourself. If I could I would do it myself but I'm honestly too stupid to figure a way out.

**Comment by maybegreat48** [comment]
Duplicate of #103

**Comment by Swashn** [comment]
Oh, seems like I'm not the only one. My bad.
