### ISSUE TITLE
[Request]: Anonymously kill player

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#771]
### Problem

i noticed when i hit "kill player" from toxic section, it notifies the whole session that i killed that player.

### Solution

suggest to anonymously kill players.

### Reason

to hide my char

**Comment by Loko415** [comment]
toxic::blame_explode_player(
						g_player_service->get_selected(),
						g_player_service->get_selected(),
						eExplosionTag::PLANE, 1000, false, true, 0.f 
                                               );

**Comment by Loko415** [comment]
paste this into the player toxic kill player view.

**Comment by urmommine** [comment]
> ```
> 				toxic::blame_explode_player(
> 					g_player_service->get_selected(),
> 					g_player_service->get_selected(),
> 					eExplosionTag::PLANE, 1000, false, true, 0.f 
>                                            );
> ```

i tried and it works only with selected players, how to make it works on kill all players?

**Comment by Honex98** [comment]
> ```
> 				toxic::blame_explode_player(
> 					g_player_service->get_selected(),
> 					g_player_service->get_selected(),
> 					eExplosionTag::PLANE, 1000, false, true, 0.f 
>                                            );
> ```

im not a programmer im just a user to i dont know how to do it. thanks for it tho.
u can suggest the edit to contributors so they can add it. or they can add it.
