### ISSUE TITLE
[Request]: stand remote crash

### ISSUE THREAD

**Issue by SwishyW** [Yimura/YimMenu#775]
### Problem

stand has a new feature that can remotely crash you even if you are in story mode.

### Solution

make a protection for this

### Reason

this makes the game unplayable

**Comment by Yimura** [comment]
Duplicate of #773 and #774

**Comment by maybegreat48** [comment]
Are you sure that you can be crashed in singleplayer? The stack trace posted in the other issue doesn't look like it

**Comment by BugisoftRSG** [comment]
> Are you sure that you can be crashed in singleplayer? The stack trace posted in the other issue doesn't look like it
![image](https://user-images.githubusercontent.com/58910128/210019367-269976ee-a797-47ca-a86f-dc81e5227a35.png)
