### ISSUE TITLE
[Bug]: new protections making menu crash?

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#779]
### Describe the bug

whenever i get the notification for the new crash protections my game crashes 3 seconds later?

### Steps To Reproduce

get crash notification against remote crash

### Expected Behavior

doesnt crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Loko415** [comment]
RAX: 0xA6002800220248
RCX: 0xFB386800
RDX: 0x7FF727FA3304
RBX: 0x7FFAA5A6C340
RSI: 0xD2993FF8E8
RDI: 0xD2993FFAE0
RSP: 0xD2993FF020
RBP: 0x1F6
R8:  0xFFFB3868
R9:  0x204209EEFB0
R10: 0x100000001B3
R11: 0xD2993FEFE0
R12: 0x0
R13: 0x5F9532F3B5CC2551
R14: 0x54
R15: 0x7239B21A38F536BA

stack dump [0]	 D:\Grand Theft Auto V\GTA5.exe+0xA33886 0x7FF727F73886
stack dump [1]	 D:\Grand Theft Auto V\GTA5.exe+0xA70CC4 0x7FF727FB0CC4
stack dump [2]	 D:\Grand Theft Auto V\GTA5.exe+0xA63318 0x7FF727FA3318
stack dump [3]	 D:\Grand Theft Auto V\GTA5.exe+0x11D31C 0x7FF72765D31C
stack dump [4]	 0x4D04
stack dump [5]	 0x6704
stack dump [6]	 0x8106
stack dump [7]	 0xA07
stack dump [8]	 0x1B606
stack dump [9]	 0x22905
stack dump [10]	 0x1A703
stack dump [11]	 0x7404
stack dump [12]	 0x19A04
stack dump [13]	 0x1F406
stack dump [14]	 0xFD04
stack dump [15]	 0x1B306
stack dump [16]	 0x22B05
stack dump [17]	 0x22B05
stack dump [18]	 0x22B05
stack dump [19]	 0x22B05
stack dump [20]	 0x9D04
stack dump [21]	 0x22B05
stack dump [22]	 0x29504
stack dump [23]	 0x1E504
stack dump [24]	 0x1E504
stack dump [25]	 0x1E504
stack dump [26]	 0x1E504
stack dump [27]	 0x1E504
stack dump [28]	 0x1E504
stack dump [29]	 0x15204
stack dump [30]	 0x18C04
stack dump [31]	 0x1E504
stack dump [32]	 0x1E504
stack dump [33]	 0x1E504
stack dump [34]	 0x1E504
stack dump [35]	 0x15204
stack dump [36]	 0x18C04
stack dump [37]	 0x1E504
stack dump [38]	 0x1EB04
stack dump [39]	 0x1EB04
stack dump [40]	 0x1E504
stack dump [41]	 0x1EB04
stack dump [42]	 0x1E504

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

**Comment by Yimura** [comment]
What was the issue exactly?

**Comment by Loko415** [comment]
i was using the rpg and i keep crashing

**Comment by Loko415** [comment]
this only started happening after adding the new protectiions?

**Comment by Loko415** [comment]
ive done it a few times it seems like its a reaccuring issue

**Comment by Loko415** [comment]
my game crashed again.  I dont know if its just me or

**Comment by SkiddyToast** [comment]
The log you posted points to a function in the native `GET_SHAPE_TEST_RESULT`, I heavily doubt the protection is causing this issue.

**Comment by Loko415** [comment]
ok. im sorry i will check it out. Ill let you know what i find

**Comment by MarkEcza** [comment]
YimMenu unmodified?

**Comment by Loko415** [comment]
that native is only mentioned once in the code. util/entity.hpp

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/210030564-6003962a-0178-447b-9f15-7dd5c8cce1e4.png)

**Comment by Loko415** [comment]
i think its the protections. Im going to try and revert the protection and see if that fixes it

**Comment by MarkEcza** [comment]
> i think its the protections. Im going to try and revert the protection and see if that fixes it

Try the same thing on unmodified YimMenu.

**Comment by Loko415** [comment]
let me try that

**Comment by Loko415** [comment]
no issue is not in yim menu. Sorry i will close this issue

**Comment by Loko415** [comment]
iif anyone could help mte out with whats wrong id appreciate it. Sorry for wasting your time

**Comment by Yimura** [comment]
@Loko415 please in the future, ALWAYS test if the issue also exists on YimMenu unmodified.

Why do you think I added a checkmark that's required and asks for this?
It's to make sure no false reports are made on crashes that don't even exist in the latest version of YimMenu.
