### ISSUE TITLE
[Bug]: Enter Interior is glitchy

### ISSUE THREAD

**Issue by Honex98** [Yimura/YimMenu#781]
### Describe the bug

when i choose a player then click enter interior of someone's, it enters some random warehouse.

### Steps To Reproduce

Choose player from player list > Misc > Enter Interior

### Expected Behavior

should enter player's interior

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Yeah this feature doesn't actually work, it was an attempt at getting it to work and then someone else added it to the UI.
