### ISSUE TITLE
[Bug]: Dance Mode crashes in Story Mode

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#784]
### Describe the bug

When using the Dance Mode feature, you crash in Story Mode. This is due to it requesting assets from the online nightclub.
This is easily resolved by adding a check whether the player is in Online. (You already have the is_session_started pointer)

### Steps To Reproduce

1. Load into Story Mode
2. Enable Dance Mode

### Expected Behavior

To not crash.

### Screenshots and/or Logs

N/A

### Store

Epic Games

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
Provide logs to be certain.

**Comment by LiamD-Flop** [comment]
Same reason as #873
