### ISSUE TITLE
issue with my MASM

### ISSUE THREAD

**Issue by Loko415** [Yimura/YimMenu#785]
![image](https://user-images.githubusercontent.com/67609719/210115220-4e6e27ef-39ed-4b4b-9a19-4af020e591c8.png)
****

**Comment by Loko415** [comment]
this is for default yim menu aswell. My path is really messed up

**Comment by Loko415** [comment]
ive tried fixing this myself and was not able to

**Comment by Yimura** [comment]
Have you saved the CMakeLists.txt again to reconfigure your CMake build instructions?

**Comment by Loko415** [comment]
yes

**Comment by Loko415** [comment]
my path was corrupted but i fixed it i have no idea whats wrong with it

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/210115602-270b8b3b-5898-4fa0-88db-b1a642bdefcd.png)
tried with default cmake settings same issue

**Comment by secret-stash** [comment]
Instead of complaining and crying in here every 2 seconds, why don't figure it our yourself? You constantly ask stupid fucking shit, you waste the time of the people reviewing these retarded issues simply by existing. People like you don't deserve to breathe the air we share.

**Comment by BugisoftRSG** [comment]
censorship

**Comment by Loko415** [comment]
?

**Comment by xiaoxiao921** [comment]
> this is for default yim menu aswell. My path is really messed up

It doesn't

**Comment by Loko415** [comment]
wtf? well for me it is

**Comment by Loko415** [comment]
technically its an issue and i am using unmodified yim menu

**Comment by xiaoxiao921** [comment]
You are not, the project is called Prometheus. I won't reopen this

**Comment by secret-stash** [comment]
> wtf? well for me it is

cry about it

**Comment by Loko415** [comment]
ill reclone yim menu just to prove my point

**Comment by Loko415** [comment]
it will be the same result. If its not im worthy of the brain damage tag

**Comment by BugisoftRSG** [comment]
![image](https://user-images.githubusercontent.com/58910128/210117222-dfb9ec05-e3e1-4a95-8dce-950147db0d74.png)
All I say
