### ISSUE TITLE
[Request]: More hotkeys

### ISSUE THREAD

**Issue by HEJiNi** [Yimura/YimMenu#790]
### Problem

Add more hotkeys

### Solution

Clear wanted, Toggle god mode, Bring personal vehicle.

### Reason

QOL

**Comment by ghost** [comment]
Also a vehicle fly mode hotkey would be nice to have

**Comment by TheGreenBandit** [comment]
I'll work on it in a bit

**Comment by HEJiNi** [comment]
so for **_bring personal vehicle_**  this will work:
in "global.hpp"
```
			struct hotkeys
			{
				bool editing_menu_toggle = false;
				int menu_toggle = VK_INSERT;
				int teleport_waypoint = 0;
				int teleport_objective = 0;
				int noclip = 0;
				int bring_personal_vehicle = 0;

				NLOHMANN_DEFINE_TYPE_INTRUSIVE(hotkeys, editing_menu_toggle, menu_toggle, teleport_waypoint, teleport_objective, noclip, bring_personal_vehicle)
			} hotkeys{};
			
```

in "view_settings.cpp"
```
		if (ImGui::Hotkey("Teleport to waypoint", &g.settings.hotkeys.teleport_waypoint))
			g_hotkey_service->update_hotkey("waypoint", g.settings.hotkeys.teleport_waypoint);
		if (ImGui::Hotkey("Teleport to objective", &g.settings.hotkeys.teleport_objective))
			g_hotkey_service->update_hotkey("objective", g.settings.hotkeys.teleport_objective);
		if (ImGui::Hotkey("Toggle Noclip", &g.settings.hotkeys.noclip))
			g_hotkey_service->update_hotkey("noclip", g.settings.hotkeys.noclip);
		if (ImGui::Hotkey("Bring PV", &g.settings.hotkeys.bring_personal_vehicle))
			g_hotkey_service->update_hotkey("bring", g.settings.hotkeys.bring_personal_vehicle);
```
and in "hotkey_service.cpp"
```
    hotkey_service::hotkey_service()
    {
        register_hotkey("waypoint", g.settings.hotkeys.teleport_waypoint, RAGE_JOAAT("waypointtp"));
        register_hotkey("objective", g.settings.hotkeys.teleport_objective, RAGE_JOAAT("objectivetp"));
        register_hotkey("noclip", g.settings.hotkeys.noclip, RAGE_JOAAT("noclip"));
        register_hotkey("bring", g.settings.hotkeys.bring_personal_vehicle, RAGE_JOAAT("bringpv"));
```
but for other stuff like _toggle god mod_ or _clear wanted_, idk how they works, they are toggles and are different.

**Comment by TheGreenBandit** [comment]
> so for **_bring personal vehicle_** this will work: in "global.hpp"
> 
> ```
> 			struct hotkeys
> 			{
> 				bool editing_menu_toggle = false;
> 				int menu_toggle = VK_INSERT;
> 				int teleport_waypoint = 0;
> 				int teleport_objective = 0;
> 				int noclip = 0;
> 				int bring_personal_vehicle = 0;
> 
> 				NLOHMANN_DEFINE_TYPE_INTRUSIVE(hotkeys, editing_menu_toggle, menu_toggle, teleport_waypoint, teleport_objective, noclip, bring_personal_vehicle)
> 			} hotkeys{};
> 			
> ```
> 
> in "view_settings.cpp"
> 
> ```
> 		if (ImGui::Hotkey("Teleport to waypoint", &g.settings.hotkeys.teleport_waypoint))
> 			g_hotkey_service->update_hotkey("waypoint", g.settings.hotkeys.teleport_waypoint);
> 		if (ImGui::Hotkey("Teleport to objective", &g.settings.hotkeys.teleport_objective))
> 			g_hotkey_service->update_hotkey("objective", g.settings.hotkeys.teleport_objective);
> 		if (ImGui::Hotkey("Toggle Noclip", &g.settings.hotkeys.noclip))
> 			g_hotkey_service->update_hotkey("noclip", g.settings.hotkeys.noclip);
> 		if (ImGui::Hotkey("Bring PV", &g.settings.hotkeys.bring_personal_vehicle))
> 			g_hotkey_service->update_hotkey("bring", g.settings.hotkeys.bring_personal_vehicle);
> ```
> 
> and in "hotkey_service.cpp"
> 
> ```
>     hotkey_service::hotkey_service()
>     {
>         register_hotkey("waypoint", g.settings.hotkeys.teleport_waypoint, RAGE_JOAAT("waypointtp"));
>         register_hotkey("objective", g.settings.hotkeys.teleport_objective, RAGE_JOAAT("objectivetp"));
>         register_hotkey("noclip", g.settings.hotkeys.noclip, RAGE_JOAAT("noclip"));
>         register_hotkey("bring", g.settings.hotkeys.bring_personal_vehicle, RAGE_JOAAT("bringpv"));
> ```
> 
> but for other stuff like _toggle god mod_ or _clear wanted_, idk how they works, they are toggles and are different.

bring personal vehicle has been added in #802, the other stuff isn't added right now

**Comment by Yimura** [comment]
A bunch of these have been implemented.
