### ISSUE TITLE
[Request]: A lot of suggestions

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#794]
### Problem

- Players -
- Be able to select multiple or all players to troll
- Explode player
- Explode player's vehicle
- Change players gravity
- Delete player's vehicle
- Kill player's vehicle
- Steal players money 
- Auto win events
- Spam player's message
- Spam chat
- Put selected player in cage
- Make annoying sounds (with the option to change volume and loop audio)

- Weapons -
- Airstrike Gun
- Gravity Gun
- Vehicle Gun
- Money Gun
- Aimbot
- Wallhack

- Money -
- Rig Casino/Daily Wheel
- Drop Money

- Misc -
- Auto-Report (Drop money then report the user saying he is using cheats to get money in online)
- Auto TP Out Of Bounds (If below the ground or in a building/wall then tp out of there)

- Heists -
- Change amount given from heist
- Change RP from heist
- Change how much you are given from the heist.

- Improvements -
- Make NoClip just phases you through walls (teleporting/disable collision with specific wall)

### Solution

For all of these to be added. I don't know a lot about modding so I don't know if all my features can work properly. But I know a lot of my suggestions are possible. 

### Reason

This would make YimMenu infinitely better, quality of life improvements, and up to par with client standard.

**Comment by Clone69420** [comment]
Some Suggestions are already implemented or wont be implemented due YimMenu dosent Support Recovery Options!

**Comment by NefariousIntent2** [comment]
> Some Suggestions are already implemented or wont be implemented due YimMenu dosent Support Recovery Options!

1.) What are recovery options
2.) What suggestions are implemented and how can I find them?

**Comment by ghost** [comment]
> > Some Suggestions are already implemented or wont be implemented due YimMenu dosent Support Recovery Options!
> 
> 1.) What are recovery options 2.) What suggestions are implemented and how can I find them?

recovery options = quite literally recovery options, but in general is money related or quick progression.
you can usually check what is implemented by using github's search feature in this repo. or you can iterate over everything in the menu. or  just by browsing code if you have half a brain.

**Comment by secret-stash** [comment]
> > > Some Suggestions are already implemented or wont be implemented due YimMenu dosent Support Recovery Options!
> > 
> > 
> > 1.) What are recovery options 2.) What suggestions are implemented and how can I find them?
> 
> recovery options = quite literally recovery options, but in general is money related or quick progression. you can usually check what is implemented by using github's search feature in this repo. or you can iterate over everything in the menu. or just by browsing code if you have half a brain.

Ofcourse, having half a brain will be sufficient to make a very good contribution to an ImGui Notification library :P

**Comment by Loko415** [comment]
prometheus has all of these. id merge them into yim menu but many of them break rules

**Comment by FireFox101889** [comment]
> > > > Some Suggestions are already implemented or wont be implemented due YimMenu dosent Support Recovery Options!
> 
> > > 
> 
> > > 
> 
> > > 1.) What are recovery options 2.) What suggestions are implemented and how can I find them?
> 
> > 
> 
> > recovery options = quite literally recovery options, but in general is money related or quick progression. you can usually check what is implemented by using github's search feature in this repo. or you can iterate over everything in the menu. or just by browsing code if you have half a brain.
> 
> 
> 
> Ofcourse, having half a brain will be sufficient to make a very good contribution to an ImGui Notification library :P

The hell u talking about

**Comment by ghost** [comment]
> 

Prometheus has nothing of significance, it is just another poorly customized YimMenu with half ass features.
Nothing you have is made by yourself or unique.

**Comment by secret-stash** [comment]
> The hell u talking about

Removed the repo because you got bullied too hard? 
It's okay, take a deep breath...

**Comment by Yimura** [comment]
@Loko415 , you say Prometheus has most of these without actually specificy which it actually has.
Saying it like that feels like a cheap way to advertise your customized version of YimMenu.

**Comment by ghost** [comment]
I'm gonna use prometheus mode menu, and leave my honest feedback xx

**Comment by NefariousIntent2** [comment]
> @Loko415 , you say Prometheus has most of these without actually specificy which it actually has. Saying it like that feels like a cheap way to advertise your customized version of YimMenu.

Sorry to bother, but what is your opinion on my suggestions. So far this comment section is just people arguing

**Comment by Yimura** [comment]
> Sorry to bother, but what is your opinion on my suggestions. So far this comment section is just people arguing

Yeah ignore them, they're not mature, I dislike removing comments as it may come over as if I'm trying to silence their opinion however off-topic talk I do not tolerate.

Anyways, regarding your requests, I prefer in general that feature requests are split into individual issues.
Money features will not be added into YimMenu as it may attract the attention of YimMenu and you're better off using Kiddions modest menu for this.

Wallhack already exists in YimMenu and is called to ESP.
So do the gravity ane vehicle guns.

All other features just serve to actively annoy other players and I wouldn't want to add in YimMenu. There are probably several features that might be interesting to add but in general many of them I wouldn't want to add.

**Comment by NefariousIntent2** [comment]
Wallhack means to shoot bullets at players through walls not ESP in this case.

>All other features just serve to actively annoy other players

Yes the other features are annoying to players but maybe some can be added with tweaks/nerfs? Because exploding vehicles/players is basically the same as using the orbital cannon, and there is a cage gun so cage player should by default be added, also to troll players with gravity is to hijack their vehicle and change the gravity but this would make it easier to change the gravity of other players. Also I want to know a full opinion on Auto-Report since it is different from any other feature and doesn't fall into any category listed above. Thanks.

**Comment by NefariousIntent2** [comment]
> Anyways, regarding your requests, I prefer in general that feature requests are split into individual issues.

If I did that, then github would ban me from creating issues and my profile would be deleted because they would see me as spam which is why I compiled them into a full list.

**Comment by maybegreat48** [comment]
Reports aren't used anymore as modders have found a way to modify them remotely
Changing gravity for another player is impossible

**Comment by SkiddyToast** [comment]
You might be able to set vehicle gravity but I'm not sure if it's synced.

**Comment by Yimura** [comment]
> Yes the other features are annoying to players but maybe some can be added with tweaks/nerfs? Because exploding vehicles/players is basically the same as using the orbital cannon, and there is a cage gun so cage player should by default be added, also to troll players with gravity is to hijack their vehicle and change the gravity but this would make it easier to change the gravity of other players. Also I want to know a full opinion on Auto-Report since it is different from any other feature and doesn't fall into any category listed above. Thanks.

Why would you activily want to report people for behaviour they're not actually responsible for? Seems unnecessarily toxic in my opinion.
Regarding the gravity thing, I think it's impossible as gravity is completely client side on a per entity basis.

**Comment by ghost** [comment]
Wallhack has multiple definitions, According to google. Also it would probably make more sense to generalize issues with what you are suggesting instead of 1 by 1. GitHub probably won't pick up on that many anyways. If you're to appeal it would be obvious it wasnt spam.

**Comment by urmommine** [comment]
> I'm gonna use prometheus mode menu, and leave my honest feedback xx

Where can i find the fork of Prometheus?

**Comment by NefariousIntent2** [comment]
> > Yes the other features are annoying to players but maybe some can be added with tweaks/nerfs? Because exploding vehicles/players is basically the same as using the orbital cannon, and there is a cage gun so cage player should by default be added, also to troll players with gravity is to hijack their vehicle and change the gravity but this would make it easier to change the gravity of other players. Also I want to know a full opinion on Auto-Report since it is different from any other feature and doesn't fall into any category listed above. Thanks.
> 
> Why would you activily want to report people for behaviour they're not actually responsible for? Seems unnecessarily toxic in my opinion. Regarding the gravity thing, I think it's impossible as gravity is completely client side on a per entity basis.

What about the explode player/cage player? Since exploding the player is in the context menu I feel it should be added.

**Comment by Loko415** [comment]
> > > Yes the other features are annoying to players but maybe some can be added with tweaks/nerfs? Because exploding vehicles/players is basically the same as using the orbital cannon, and there is a cage gun so cage player should by default be added, also to troll players with gravity is to hijack their vehicle and change the gravity but this would make it easier to change the gravity of other players. Also I want to know a full opinion on Auto-Report since it is different from any other feature and doesn't fall into any category listed above. Thanks.
> > 
> > 
> > Why would you activily want to report people for behaviour they're not actually responsible for? Seems unnecessarily toxic in my opinion. Regarding the gravity thing, I think it's impossible as gravity is completely client side on a per entity basis.
> 
> What about the explode player/cage player? Since exploding the player is in the context menu I feel it should be added.

prometheus has this but yea its like a more immature version of yim menu. It has cage ped large cage and alot of toxic stuff. Also has money drops. I did want to add these features to yim menu but i cannot.

**Comment by Loko415** [comment]
i credit yim and this menu inside the menu.

**Comment by Loko415** [comment]
> @Loko415 , you say Prometheus has most of these without actually specificy which it actually has. Saying it like that feels like a cheap way to advertise your customized version of YimMenu.

i never wanted to offend you in any way. I just mentioned it has these features. I didnt link it.

**Comment by Loko415** [comment]
Explode player
Explode player's vehicle
Money Gun
Aimbot
rig slot
nightclub 300k loop
cage player
annoying sounds
drop money
various removable commands (crash, pickupcrash)
pickup crash acts as a detected rp drop. Making the player report themself

**Comment by Loko415** [comment]
prometheus has all of the above.

**Comment by NefariousIntent2** [comment]
> Explode player Explode player's vehicle Money Gun Aimbot rig slot nightclub 300k loop cage player annoying sounds drop money various removable commands (crash, pickupcrash) pickup crash acts as a detected rp drop. Making the player report themself

Show me a video, cant be editied and fully RAW and can be 3 days old no older. Of prometheus working.

**Comment by Yimura** [comment]
I swear to god when will you stop sending multiple messages for things that can be said in the same message, you haven't changed since the first time you spoke on Discord.

**Comment by NefariousIntent2** [comment]
> I swear to god when will you stop sending multiple messages for things that can be said in the same message, you haven't changed since the first time you spoke on Discord.

Who?

**Comment by Loko415** [comment]
fair enough.I am trying to change my typing style. I should probably get grammarly or something like that

**Comment by Loko415** [comment]
> > Explode player Explode player's vehicle Money Gun Aimbot rig slot nightclub 300k loop cage player annoying sounds drop money various removable commands (crash, pickupcrash) pickup crash acts as a detected rp drop. Making the player report themself
> 
> Show me a video, cant be editied and fully RAW and can be 3 days old no older. Of prometheus working.

i do have a discord server for it. If you want to join idk i would have to ask for yims permission to post.

**Comment by ghost** [comment]
This issue officially sucks pp. Why the irrelevancy for a simple list of suggestions??

**Comment by NefariousIntent2** [comment]
> > > Explode player Explode player's vehicle Money Gun Aimbot rig slot nightclub 300k loop cage player annoying sounds drop money various removable commands (crash, pickupcrash) pickup crash acts as a detected rp drop. Making the player report themself
> > 
> > 
> > Show me a video, cant be editied and fully RAW and can be 3 days old no older. Of prometheus working.
> 
> i do have a discord server for it. If you want to join idk i would have to ask for yims permission to post.

Upload on youtube and give me the link

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/210159356-4e915bab-75e6-49c8-8654-961b1722eb8c.png)
![image](https://user-images.githubusercontent.com/67609719/210159359-053b548e-ed4d-4bce-ade0-49a12126d304.png)
![image](https://user-images.githubusercontent.com/67609719/210159361-c8bdfe9c-2e8a-4036-9d1a-1c537fdb388a.png)
![image](https://user-images.githubusercontent.com/67609719/210159366-5ca88ff0-2821-4454-8ffb-ffea69e6df2b.png)
![image](https://user-images.githubusercontent.com/67609719/210159368-10fef07a-ead0-43cd-9f54-6c6157811b20.png)
MOST OF THIS IS PASTED*
![image](https://user-images.githubusercontent.com/67609719/210159370-7d6b8bf1-e6e3-43b0-b30d-b618fd1637ae.png)
![image](https://user-images.githubusercontent.com/67609719/210159372-fc905298-7680-427a-9c96-9e2edcfa9f2a.png)

**Comment by Loko415** [comment]
wait let me load into online to show the toxic features and drops features

**Comment by NefariousIntent2** [comment]
@Yimura I wanted to know what features wouldn't be added and what would be. thanks

**Comment by Loko415** [comment]
> @Yimura I wanted to know what features wouldn't be added and what would be. thanks

If you really want a trolling centered menu add Loko#0993 on discord. This will be the last time i comment on this pull request.

**Comment by NefariousIntent2** [comment]
> 

New update has explode players. Still no cage players, would be cool just saying.

**Comment by NefariousIntent2** [comment]
@Loko415 how do I know Promethus isn't a virus?

**Comment by LiamD-Flop** [comment]
@NefariousIntent2 
> I wanted to know what features wouldn't be added and what would be. thanks

Players
- Be able to select multiple or all players to troll > Feature is already requested
- Explode player > Already in YimMenu
- Explode player's vehicle > Could be added
- Change players gravity > Uncertain if this is possible
- Delete player's vehicle > Could be added
- Kill player's vehicle > Could be added
- Steal players money > Won't be added
- Auto win events
- Spam player's message > Unclear as our previous stance was no, but we've added some toxic stuff since so maybe?
- Spam chat > Unclear as our previous stance was no, but we've added some toxic stuff since so maybe?
- Put selected player in cage > Unclear as our previous stance was no, but we've added some toxic stuff since so maybe?
- Make annoying sounds (with the option to change volume and loop audio) > Unclear as our previous stance was no, but we've added some toxic stuff since so maybe?

Weapons
- Airstrike Gun > If you mean merryweather airstrike then this could be added. if you mean the explosion then it already is added under the custom bullet or whatever it is called.
- Gravity Gun > Already in YimMenu
- Vehicle Gun > Already in YimMenu
- Money Gun > Won't be added
- Aimbot > Unclear as our previous stance was no, but we've added some toxic stuff since so maybe?
- Wallhack > Could be added

Money
- Rig Casino/Daily Wheel > Won't be added
- Drop Money > Won't be added

Misc
- Auto-Report (Drop money then report the user saying he is using cheats to get money in online) > Won't be added
- Auto TP Out Of Bounds (If below the ground or in a building/wall then tp out of there) > Could be added

Heists
- Change amount given from heist > Won't be added
- Change RP from heist > Won't be added
- Change how much you are given from the heist. > Won't be added

Improvements
- Make NoClip just phases you through walls (teleporting/disable collision with specific wall) > Already in YimMenu, (Noclip and No collision)

@Yimura you can edit this if there are things that are incorrect.

**Comment by NefariousIntent2** [comment]
> 

I know but these were suggested before Yim added

**Comment by magistrjan** [comment]
> > Извините за беспокойство, но каково ваше мнение о моих предложениях? Пока что в этом разделе комментариев просто спорят люди
> 
> Да, игнорируйте их, они не зрелые, мне не нравится удалять комментарии, так как может показаться, что я пытаюсь заставить замолчать их мнение, однако я не терплю разговоров не по теме.
> 
> В любом случае, что касается ваших запросов, я предпочитаю в целом, чтобы запросы функций были разделены на отдельные вопросы. Денежные функции не будут добавлены в YimMenu, так как это может привлечь внимание YimMenu, и вам лучше использовать для этого скромное меню Kiddions.
> 
> Wallhack уже существует в YimMenu и вызывается в ESP. То же самое делают и гравитационные пушки ane vehicle.
> 
> Все остальные функции просто служат для того, чтобы активно раздражать других игроков, и я бы не хотел добавлять их в YimMenu. Вероятно, есть несколько функций, которые было бы интересно добавить, но в целом многие из них я бы не хотел добавлять.

Йимура, в твоём чите есть функция взорвать всех. О чём ты? Мне, конечно, очень нравится yim, но вредительские функции всё же есть)

**Comment by LiamD-Flop** [comment]
Unable to track if all these issues have been resolved or not.
