### ISSUE TITLE
protections_replay_interface causes heavy desync / crashes in heavy scripted missions

### ISSUE THREAD

**Issue by xiaoxiao921** [Yimura/YimMenu#8]
Took me a while to find what the culprit was and i'm not sure if this is generalized across all machines but for me `protections_replay_interface` causes a lot of problems in scripted missions like the casino heist for example, makes the thing not completable at all even if the `attach` bool is set to false

I'm not sure of the exact cause of this but a nice fix would be to automatically detect if the player is in a mission or not but i'm not sure how to do that

**Comment by Yimura** [comment]
Interesting, probably because the checks happen on the game thread. I'll take a look if I can lessen the load or asynchronously handle this stuff.

**Comment by Yimura** [comment]
I don't script yield on this line, possibly long lockups happen causing the game to desync.

https://github.com/Yimura/YimMenu/blob/master/BigBaseV2/src/backend/looped/protections/replay_interface.cpp#L25

**Comment by Yimura** [comment]
Check if https://github.com/Yimura/YimMenu/commit/f88b493680e0242df66a63022ac8c77232cb5f21 fixes your issue

**Comment by xiaoxiao921** [comment]
It does not. I'm thinking of hooking the cnetobject method that spanker is talking about here, its only called when stuff is getting attached to a given ped so it'll greatly reduce the charge on the thread

https://www.unknowncheats.me/forum/2524680-post18.html
https://www.unknowncheats.me/forum/2523962-post13.html

**Comment by Yimura** [comment]
Sounds good, I might take a look as well.

**Comment by Yimura** [comment]
Seems this is similarly related to #10

**Comment by Yimura** [comment]
I have disabled the replay interface features for now, I will look into implementing the attach stuff from the links you posted.

**Comment by xiaoxiao921** [comment]
Thanks a lot, i've already tried a bit to find the functions from the vtables spanker is talking about but without any success yet, i've also tried to pinpoint them from the native calls but looks like arxan obf is making it difficult

**Comment by Yimura** [comment]
This hook only triggers when someone else gets something attached to them, this doesn't trigger when an external party tries to attach something to me.
```cpp
// Attach Entity to Entity
main_batch.add("AETE", "48 8B 01 48 8B F2 48 8B F9 45 32 F6 FF 90 ? ? ? ? 48 8B CE 4C 8B E8 E8 ? ? ? ?", [this](memory::handle ptr)
{
	m_attach_entity_to_entity = ptr.sub(0x1C).as<decltype(m_attach_entity_to_entity)>();
});
```

**Comment by Yimura** [comment]
I have made a branch with what I've attempted:
https://github.com/Yimura/YimMenu/tree/feat_attach_hook

**Comment by Yimura** [comment]
Going to close this issue as this doesn't seem to be much of an issue anymore, entity attachments don't seem to be synced with targets by default, it's probably still possible but most modders don't care enough at the moment.
