### ISSUE TITLE
[Bug]: Cmake compilation failed

### ISSUE THREAD

**Issue by penguin239** [Yimura/YimMenu#800]
### Describe the bug

Cmake compilation failed
![image](https://user-images.githubusercontent.com/65529592/210242976-d5afb5c7-ab57-4c59-a85c-1551cbb91aee.png)

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/65529592/210242992-d3375730-71bb-4c4a-8172-e9180aac2ed8.png)

### Expected Behavior

compilation

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Did you follow the instructions from the README?

**Comment by penguin239** [comment]
> Did you follow the instructions from the README?

Yes, I have the latest yimmenu and the latest cmake

**Comment by Yimura** [comment]
Did you install Git as well? Make sure it's added to your Windows PATH as well.

**Comment by penguin239** [comment]
> Did you install Git as well? Make sure it's added to your Windows PATH as well.

Need to use git during compilation?

**Comment by Yimura** [comment]
Well the README mentions it as a requirement and if you look at the CMake logs is says it failed to find git.

```
-- Could not find Git (missing: GIT_EXECUTABLE)
```

**Comment by penguin239** [comment]
> Well the README mentions it as a requirement and if you look at the CMake logs is says it failed to find git.
> 
> ```
> -- Could not find Git (missing: GIT_EXECUTABLE)
> ```

Okay, I'll download it now

**Comment by penguin239** [comment]
> Well the README mentions it as a requirement and if you look at the CMake logs is says it failed to find git.
> 
> ```
> -- Could not find Git (missing: GIT_EXECUTABLE)
> ```

thanks, working!
