### ISSUE TITLE
[Bug]: Co-load

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#804]
### Describe the bug

After [Nightly Build](https://github.com/YimMenu/YimMenu/actions/runs/3727113907) 381 no more co-load with Stand. Please solve this problem, Yim dont have enough protection, many ppls still can crash me.

### Steps To Reproduce

get 381 build, inject Yim, then Stand, works.
get next builds 382+, inject Yim, then Stand, try to join in any session, get Stand error while character creation in join process

### Expected Behavior

co-load

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by sch-lda** [comment]
![image](https://user-images.githubusercontent.com/54973190/210297840-c09037c5-9d87-4550-ae7d-f3285f9511cd.png)

**Comment by vladdoser** [comment]
Anyway its still able to co-load with 381 build, and i prefer to use it.  So just need to lookup what was changed in join or creation process.. I think its real for Yim devs.

**Comment by MarkEcza** [comment]
> Anyway its still able to co-load with 381 build, and i prefer to use it. So just need to lookup what was changed in join or creation process.. I think its real for Yim devs.

And why exactly do we have to worry about co-loadability on an open source mod?

**Comment by maybegreat48** [comment]
What is the "381 build" you speak of? Can you give a commit hash?

**Comment by sch-lda** [comment]
https://github.com/YimMenu/YimMenu/actions/runs/3727113907

**Comment by Yimura** [comment]
e442e284dba151d9e9b6bbde56fbd1c6606d1d36...c2e9e61c01e841ad71425ae3370c64e037404742

**Comment by Sainan** [comment]
Trying out Nightly Build 402, and I can see "freemode script died on Return". I can offer Game > Use Script VM Reimplementation as a work-around (plus, it gives you ~1 FPS more), but it won't fix whatever bad script patching YimMenu is doing, it'll simply skip past it. I figure this "Found pattern SFSA in script freemode" is related.
![image](https://user-images.githubusercontent.com/63328889/210509786-d8525894-f162-4ba9-95e8-9fc1ed5fc9c6.png)

**Comment by maybegreat48** [comment]
The [script function caller](https://github.com/YimMenu/YimMenu/blob/master/src/script_function.cpp#L39) creates a fake thread instance and calls the script VM with it. I assume Stand must have thought that the actual freemode script had died when the VM killed the fake thread

**Comment by LiamD-Flop** [comment]
Third party issue
