### ISSUE TITLE
[Request]: Force weapon

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#811]
### Problem

Force hold a weapon. In penthouses/apartments/the casino/arcades and many more places you can't have a weapon. Have an option to force a weapon of your choosing.

### Solution

I don't know GTA code and GTA modding so I don't know if its possible, but considering this is Rockstar I would assume it is.

### Reason

Testing AI behavior.. etc.

**Comment by sean24YT** [comment]
2nd

**Comment by TheGreenBandit** [comment]
duplicate of #736
