### ISSUE TITLE
[Request]: Can you make a translation system

### ISSUE THREAD

**Issue by xkcheats** [Yimura/YimMenu#812]
### Solution

Hope YimMenu can load language file(json/ini/yml etcs)

### Reason

Cause many people don't know English well.
YimMenu is an excellent menu, many guys like it

**Comment by D-Borkan** [comment]
yeah that is good thing to support that

**Comment by Yimura** [comment]
I'll make a separate issue for font system as to not close this issue prematurely without implementing both.

New issue for font system #845
