### ISSUE TITLE
[Bug]: Job load times out

### ISSUE THREAD

**Issue by oxUNKNOWNxo** [Yimura/YimMenu#813]
### Describe the bug

When YimMenu users start jobs, they cannot start and are excluded from the session.

### Steps To Reproduce

1.YimMenu inject
2.invite friends to job
3.start job
4.job times out

### Expected Behavior

job starts

### Store

Epic Games

### Additional context

- I tried it by myself using 2 computers and 2 accounts.
- I tried with a combination of Epic Games version and Rockstar Launcher version,
- I turned off all the protection items, but it didn't change.
- Unloading YimMenu from either PC allowed the job to start.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Any specific jobs this happens with? I know I can start races and successfully host them without having to unload.
I'm assuming these are special jobs like heists and such.

**Comment by oxUNKNOWNxo** [comment]
I'm currently checking the following.
- Street Race Series 
- Three approaches to casino heists

**Comment by Yimura** [comment]
Alright we'll have to take a look at it because I've heard of people complaining in my sessions that they can't launch jobs because of protections in YimMenu.

**Comment by Aure7138** [comment]
In order to exclude possible reasons, have you tried to turn off the protection, it is in Settings->Protection
also spoofing RID, it is in Network->Spoofing

**Comment by oxUNKNOWNxo** [comment]
I double-checked the settings on both computers just in case.
- Settings->Protection all off
- Network->Spoofing all off
- Network->Session Browser->Replace Game Matchmaking off

Also, the firewall was set based on the site below, so I canceled it and verified it, but the result did not change.
  https://leo3418.github.io/collections/gta-online-guides/firewall-rule-on-pc.html

**Comment by Yimura** [comment]
This has been partially fixed but there are still some jobs that fail to launch (ex. Fleeca Heist).

**Comment by oxUNKNOWNxo** [comment]
I tried it with Nightly [53061a9], but it doesn't seem to be fixed, at least in the Street Race Series.
Also, when inviting a YimMenu user who is in an invite-only session to a job, they get stuck unable to join.
