### ISSUE TITLE
[Request]: Make menu recover from crashes

### ISSUE THREAD

**Issue by Gh0sSte** [Yimura/YimMenu#814]
### Problem

menus like cherax can recover from crashes by hopping gta masm i think. I am not very educated on this but in theory could you recover from a crash without patching it?. If so what are the downsides of doing this? Great menu by the way

### Solution

Make it so menu can recover from crashes if we get crashed

### Reason

dont have to patch certain crashes because the menu will just recover itself

**Comment by MarkEcza** [comment]
> ### Problem
> menus like cherax can recover from crashes by hopping gta masm i think. I am not very educated on this but in theory could you recover from a crash without patching it?. If so what are the downsides of doing this? Great menu by the way
> 
> ### Solution
> Make it so menu can recover from crashes if we get crashed
> 
> ### Reason
> dont have to patch certain crashes because the menu will just recover itself
> 
> ### Additional context
> _No response_

Yes. You can using WinAPI. Downsides are you might get stuck on a infinite loop on recursive crashes. And it does not prevent all crashes from going through. And also this isn't an excuse to not patch crashes. This is mainly for smaller stuff. And if not implemented correctly it also passes g3 logs stackdumper.

**Comment by SkiddyToast** [comment]
You just need a disassembler to find the length of the current instruction and add that length to `RIP` before continuing execution.

**Comment by Yimura** [comment]
Implemented in #882
