### ISSUE TITLE
IDA help

### ISSUE THREAD

**Issue by JDMJay** [Yimura/YimMenu#818]
How do I find addresses in IDA
stack dump [0]     D:\Grand Theft Auto V\GTA5.exe+0x1384D4C 0x7FF69B994D4C
stack dump [1]     D:\Grand Theft Auto V\GTA5.exe+0x135DF99 0x7FF69B96DF99
stack dump [2]     D:\Grand Theft Auto V\GTA5.exe+0x1365790 0x7FF69B975790
stack dump [3]     D:\Grand Theft Auto V\GTA5.exe+0x136531D 0x7FF69B97531D
stack dump [4]     D:\Grand Theft Auto V\GTA5.exe+0x13ACB45 0x7FF69B9BCB45
stack dump [5]     D:\Grand Theft Auto V\GTA5.exe+0x13ACCBD 0x7FF69B9BCCBD
stack dump [6]     D:\Grand Theft Auto V\GTA5.exe+0x13AD0E8 0x7FF69B9BD0E8
stack dump [7]     D:\Grand Theft Auto V\GTA5.exe+0x13A802D 0x7FF69B9B802D
stack dump [8]     D:\Grand Theft Auto V\GTA5.exe+0x5A8301 0x7FF69ABB8301
stack dump [9]     D:\Grand Theft Auto V\GTA5.exe+0x536C94 0x7FF69AB46C94
stack dump [10]     D:\Grand Theft Auto V\GTA5.exe+0x1640DED 0x7FF69BC50DED
stack dump [11]     D:\Grand Theft Auto V\GTA5.exe+0x1640D0A 0x7FF69BC50D0A
stack dump [12]     D:\Grand Theft Auto V\GTA5.exe+0x161B5FD 0x7FF69BC2B5FD
stack dump [13]     D:\Grand Theft Auto V\GTA5.exe+0x161BF9A 0x7FF69BC2BF9A
stack dump [14]     D:\Grand Theft Auto V\GTA5.exe+0x1624D5E 0x7FF69BC34D5E
stack dump [15]     D:\Grand Theft Auto V\GTA5.exe+0x12E7022 0x7FF69B8F7022
stack dump [16]     C:\WINDOWS\System32\KERNEL32.DLL+0x155A0 BaseThreadInitThunk
stack dump [17]     C:\WINDOWS\SYSTEM32\ntdll.dll+0x485B RtlUserThreadStart

**Comment by BugisoftRSG** [comment]
dont you have your sgt guy for that? lmao

**Comment by JDMJay** [comment]
> dont you have your sgt guy for that? lmao

I would like to learn myself.

**Comment by BugisoftRSG** [comment]
> > dont you have your sgt guy for that? lmao
> 
> I would like to learn myself.

you could ask him? Or ask google
Also this is not a forum for ida questions please refer to https://forum.hex-rays.com

**Comment by Yimura** [comment]
Not an issue with YimMenu.

**Comment by Vali0004** [comment]
Not to comment on closed issues, but it’s a file offset. Address - base, (EX: 0x1384D4C). You can jump to that address by using a game dump loaded in IDA, going to Jump and Jump to File Offset
