### ISSUE TITLE
[Request]: When doing nightly builds, tell us what has changed.

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#821]
### Problem

So we don't have to look through the entire menu when a new build comes out just to find a few features.

### Solution

Just telling us what has been added. A QOL improvement.

### Reason

Saves us time and makes what changed not a pain in the ass to figure out.

**Comment by RainerZufall187** [comment]
what? where is the problem to just look into history?

**Comment by sch-lda** [comment]
Firefox Nightly doesnt provide changelog in google play too.Yim is for education, not a commercial product

**Comment by NefariousIntent2** [comment]
> Firefox Nightly doesnt provide changelog in google play too.Yim is for education, not a commercial product



> what? where is the problem to just look into history?

Sometimes, the requester doesn't add codelines or walkthroughs which makes it painful to know what they are talking about. Why are you using Firefox as an example, this is Yim, a GTA mod menu, not a browser.

**Comment by sch-lda** [comment]
There is no need for devs to summarize their work everyday. Yim has many contributors. The question is that who has the duty to summarize all contributors' work every day? Do other menus that have changelog use nightly build?  Do other menus that have changelog contributed by many strangers? Write changelog for nightly build everyday is stupid. Do you like to summarize your work everyday? Yim is not a commercial product. Why not try to find what changed in PRs?
![image](https://user-images.githubusercontent.com/54973190/211129937-995f1800-19da-4d2c-963b-9a068bc26f59.png)

**Comment by Yimura** [comment]
Closing this, if you really want to know what changed please have a look at the commit history.
