### ISSUE TITLE
[Request]: See how much money a person has.

### ISSUE THREAD

**Issue by UnderDog656** [Yimura/YimMenu#822]
### Solution

N/A

### Reason

I find it useful to know,

**Comment by RainerZufall187** [comment]
++++++++++++++++++++


wasn't there already a request for this some time ago?

**Comment by pelecanidae** [comment]
https://github.com/YimMenu/YimMenu/blob/5260b27899224946ef5923a9dc55e08568cfa5b9/src/views/players/player/player_info.cpp#L142

**Comment by Yimura** [comment]
Yeah it actually already exists in YimMenu as @pelecanidae has shown.
