### ISSUE TITLE
[Request]: Protection against Lost Connection Kick

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#824]
### Problem

There isn't protection against Lost Connection kick, I had one of my friends who uses a different mod menu test Lost Connection kick and I did get kicked. Everyone "left" on my screen but that was not the case and I was gone from the map. I had the modders screen and an alt to prove I was kicked.

### Solution

Protection against it?

### Reason

For a mod that can kick using Lost Connection, protection should seem embedded.

**Comment by maybegreat48** [comment]
It's impossible to protect against the lost connection kick without being the session host. If you want to ensure that you're always the host, enable "Force Session Host" and "Kick Host During Join"
