### ISSUE TITLE
Does YimMenu log all players who enter session?

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#826]
If so tell me how to access the log.

**Comment by sch-lda** [comment]
Yes.But its not just for players.It includes many other things.It contains Players' name and RID like "[20:43:03][INFO/assign_physical_index.cpp:43]: Player joined '*********' allocating slot #27 with Rockstar ID: *********
"
last session:   C:\Users\[your Windows user name]\AppData\Roaming\BigBaseV2\cout.log
history:          C:\Users\[your Windows user name]\AppData\Roaming\BigBaseV2\backup\

**Comment by NefariousIntent2** [comment]
> Yes.But its not just for players.It includes many other things.It contains Players' name and RID like "[20:43:03][INFO/assign_physical_index.cpp:43]: Player joined '*********' allocating slot #27 with Rockstar ID: ********* " last session: C:\Users[your Windows user name]\AppData\Roaming\BigBaseV2\cout.log history: C:\Users[your Windows user name]\AppData\Roaming\BigBaseV2\backup\

I can't find any usernames

**Comment by Yimura** [comment]
Not really an issue with the menu, closing.
