### ISSUE TITLE
[Bug]: CMake Error

### ISSUE THREAD

**Issue by alex421220** [Yimura/YimMenu#828]
### Describe the bug

i cloned the repository using git, opened a local folder in visual studio and cmake failed somewhere

### Steps To Reproduce

1) Clone the repository using git
2) Open local folder created by git in visual studio
3) CMake project generation error

### Expected Behavior

successful project generation

### Screenshots and/or Logs

1> Для конфигурации запущено создание CMake: "x64-Release".
1> Командная строка: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Alex\YimMenu\out\install\x64-Release" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Alex\YimMenu" 2>&1"
1> Рабочий каталог: C:\Users\Alex\YimMenu\out\build\x64-Release
1> [CMake] -- The CXX compiler identification is MSVC 19.34.31937.0
1> [CMake] -- The ASM_MASM compiler identification is MSVC
1> [CMake] -- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/ml64.exe
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - failed
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken
1> [CMake] CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
1> [CMake]   The C++ compiler
1> [CMake] 
1> [CMake]     "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"
1> [CMake] 
1> [CMake]   is not able to compile a simple test program.
1> [CMake] 
1> [CMake]   It fails with the following output:
1> [CMake] 
1> [CMake]     Change Dir: C:/Users/Alex/YimMenu/out/build/x64-Release/CMakeFiles/CMakeTmp
1> [CMake]     
1> [CMake]     Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_b25da && [1/2] Building CXX object CMakeFiles\cmTC_b25da.dir\testCXXCompiler.cxx.obj
1> [CMake]     [2/2] Linking CXX executable cmTC_b25da.exe
1> [CMake]     FAILED: cmTC_b25da.exe 
1> [CMake]     cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_b25da.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_b25da.dir\testCXXCompiler.cxx.obj  /out:cmTC_b25da.exe /implib:cmTC_b25da.lib /pdb:cmTC_b25da.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
1> [CMake]     RC Pass 1: command "rc /fo CMakeFiles\cmTC_b25da.dir/manifest.res CMakeFiles\cmTC_b25da.dir/manifest.rc" failed (exit code 0) with the following output:
1> [CMake]     Не удается найти указанный файл
1> [CMake]     ninja: build stopped: subcommand failed.
1> [CMake]     
1> [CMake]     
1> [CMake] 
1> [CMake]   
1> [CMake] 
1> [CMake]   CMake will not be able to correctly generate this project.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:3 (project)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "C:/Users/Alex/YimMenu/out/build/x64-Release/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "C:/Users/Alex/YimMenu/out/build/x64-Release/CMakeFiles/CMakeError.log".
1> Не удалось выполнить команду "C:\Windows\system32\cmd.exe" с аргументами "/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Alex\YimMenu\out\install\x64-Release" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Alex\YimMenu" 2>&1"". Код завершения: Команда "C:\Windows\system32\cmd.exe" с аргументами "/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Alex\YimMenu\out\install\x64-Release" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Alex\YimMenu" 2>&1"" завершила работу с кодом завершения 1..

### Store

Other (please mention in "Additional context")

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Peax** [comment]
> 1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken

Verify your Visual Studio installation and make sure C++ extensions are installed. Also – if Git is installed ­– you can use Visual Studio to clone a Git repository. I also recommend to re-run cmake after each Git pull. In Visual Studio, you do that by open the CMAKE Settings (CMakeSettings.json) and clicking on any field. Do not change anything. Then click the save file icon.
