### ISSUE TITLE
Add a Lua scripting API

### ISSUE THREAD

**Issue by bugmaschine** [Yimura/YimMenu#83]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to load Lua files

**Provide Reasoning**
It would be cool to make some Scripts.

**Additional context**

**Comment by Yimura** [comment]
Currently we aren't planning on adding a lua scripting api but rather some kind of command like behaviour.

Commands can be used to bind to keys dynamically.
Commands can be used to execute from some sort of std::cin or input line.
Commands can be used for scripting purposes.

Some examples of how scripting would work:
```
teleport x y z
unload

bind k "teleport 0 0 15";
```

Maybe in the future we might expand to some kind of lua scripting, I believe once the command like behaviour is implemented it shouldn't be too hard to expose these to lua scripting...

Edit:

We'll add both a lua scripting api and command like interface.
