### ISSUE TITLE
[Bug]: Random Game Crashes

### ISSUE THREAD

**Issue by JDMJay** [Yimura/YimMenu#840]
### Describe the bug

1. My Game just freezes randomly and crashes
2. Getting crashed by something that uses Invalid Ped Attachment But CanApplyData is Blocking "CPedAttachDataNode"
3. Are CanApplyData Tables Correct, I'm assuming no because I'm being crashed by stuff that is in the tables
4. The logs where not showing anything.
5. Tested on YimMenu unmodified

### Steps To Reproduce

.

### Expected Behavior

Less crashes

### Screenshots and/or Logs

```
cout.log didn't show any crash logs
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by JDMJay** [comment]
The issue with the random freezing leading to crashes does not happen when I do not have a menu injected

**Comment by sean24YT** [comment]
hello, im new to this kinda stuff. i will say ive ben reading around and best to fined if you have source. that the saved settings of the menu to chang back to defalt to mabe see if that works.
C:\Users\YOURPCNAME\AppData\Roaming\BigBaseV2/settings

try to dl this new or maybe clear it. not sure if this will help but good luck!

**Comment by LiamD-Flop** [comment]
Should be fixed
