### ISSUE TITLE
[Bug]: p2c crashed

### ISSUE THREAD

**Issue by Roseiit** [Yimura/YimMenu#849]
### Describe the bug

crashed

### Steps To Reproduce

.

### Expected Behavior

.

### Screenshots and/or Logs

```
<paste your logs here>
```
Dumping registers:RAX: 0x2E00131D400RCX: 0xADE08FEDC0RDX: 0xADE08FED40RBX: 0xADE08FEF14RSI: 0xF0RDI: 0x1F2775FD410RSP: 0xADE08FEC80RBP: 0xADE08FECF9R8:  0x2A034EFCDE0R9:  0xADE08FED20R10: 0xADE08FEDC0R11: 0xADE08FED58R12: 0x2A0391B3AD0R13: 0x2A03B7E5000R14: 0x2A057EFC260R15: 0x3stack dump [0]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x13A4115 0x7FF61DEB4115stack dump [1]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x68438F 0x7FF61D19438Fstack dump [2]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x5543B1 0x7FF61D0643B1stack dump [3]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x4F9E67 0x7FF61D009E67stack dump [4]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x5034E5 0x7FF61D0134E5stack dump [5]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x51008C 0x7FF61D02008Cstack dump [6]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x1618967 0x7FF61E128967stack dump [7]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x512484 0x7FF61D022484stack dump [8]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x161CB4F 0x7FF61E12CB4Fstack dump [9]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x512630 0x7FF61D022630stack dump [10]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x512574 0x7FF61D022574stack dump [11]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x50B4F6 0x7FF61D01B4F6stack dump [12]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x51E4B7 0x7FF61D02E4B7stack dump [13]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x51C21E 0x7FF61D02C21Estack dump [14]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x1619AA9 0x7FF61E129AA9stack dump [15]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x1ED53 0x7FF61CB2ED53stack dump [16]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x20D65 0x7FF61CB30D65stack dump [17]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x15F4094 0x7FF61E104094stack dump [18]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x1494 0x7FF61CB11494stack dump [19]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x12DD997 0x7FF61DDED997stack dump [20]	 D:\steam\steamapps\common\Grand Theft Auto V\GTA5.exe+0x17E678C 0x7FF61E2F678Cstack dump [21]	 C:\Windows\System32\KERNEL32.DLL+0x155A0 BaseThreadInitThunkstack dump [22]	 C:\Windows\SYSTEM32\ntdll.dll+0x485B RtlUserThreadStartExiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATIONLog content flushed successfully to sink

### Store

Steam

### Additional context

.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Couldn't you just comment this on the last issue?

**Comment by Roseiit** [comment]
> Couldn't you just comment this on the last issue?
In the 1.63 game, yim can be blocked, but you may forget to check the base model info m_model_type
