### ISSUE TITLE
[Bug]: RID Spoofer Is not Working As It Should 

### ISSUE THREAD

**Issue by Mohi-eddine** [Yimura/YimMenu#852]
### Describe the bug

The RID Spoofer Is only spoofing my RID to 1 no matter what was my input. 
the problem is at: YimMenu\src\backend\looped\system\spoofing.cpp 
line 35 ```g.spoofing.applied_spoof_rockstar_id = g.spoofing.spoof_rockstar_id;```
as its writing the bool value to the RID which explain the value of 1

### Steps To Reproduce

use rid spoofer 
input a value 
ask a friend to check your rid

### Expected Behavior

the rid to change based on my input.
where to fix:
YimMenu\src\backend\looped\system\spoofing.cpp 
line 35: 
replace with ```g.spoofing.applied_spoof_rockstar_id = g.spoofing.rockstar_id;```

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
You're correct, I noticed something funky with RID spoofing.

**Comment by Mohi-eddine** [comment]
its hard to notice unless u see your spoofed rid

**Comment by NefariousIntent2** [comment]
> You're correct, I noticed something funky with RID spoofing.
Yeah, thats a thing I noticed too.
