### ISSUE TITLE
[Request]: YimMenu is dead. 

### ISSUE THREAD

**Issue by NefariousIntent2** [Yimura/YimMenu#859]
### Problem

No update for 4 days, no commits for 3 days. Yimaura doesn't respond unless its a bug which means he doesn't give a flying fuck about enhancement. Yimaura. Please.

### Solution

a

### Reason

a

**Comment by Yimura** [comment]
Damn 3 days, YimMenu is definitely dead.

How privileged do you think you are? We owe you NOTHING, YimMenu is completely free and as such people only work on it in their free time.

Enhancements are completely different from bugs and as such I always prioritize those. If a bug makes YimMenu unusable vs a new feature that doesn't exist in YimMenu? Which of these two do you think is the most catastrophic?

If you're that keen on getting new features, kindly learn to code and add them yourself.

**Comment by LiamD-Flop** [comment]
Thank you for your opinion on the matter. As Yim stated we're not full time developers on this project and have personal lives. It started out as a fun side thing and grew in proportions none of us could've imagined. Still there is nobody who owes you anything. Like Yim said, if you want new stuff add it yourself or wait for someone else to do it. But none of the contributors are obligated to do anything for anyone.
If the contributors decide to take a break, so be it. But I can assure you the repo is far from dead and is still actively being worked on. There are some big changes on their way and I don't think you understand how much work goes into building stuff like this. Still if you compare to others I would say Yim doesn't even come close to being inactive.
