### ISSUE TITLE
notification spam

### ISSUE THREAD

**Issue by FriXeee** [Yimura/YimMenu#86]
**Describe the bug**
When i enter in the bunker or Motorcycle club, a spam of protection warnings of '' denied player control request from * user * '' starts.
i have all protection off but still continue even after i drive

**Expected behavior**
should appear less, or put options to want notification or not

**Screenshots**
![screen](https://user-images.githubusercontent.com/61766432/156821030-b1d71520-4f6a-4d14-8226-556ad71f04a0.png)

**Comment by howdoiusekeyboard** [comment]
Yes even I face this issue alot, even with friends who don't mod
![image](https://user-images.githubusercontent.com/90883505/157118254-ed7bbf27-d035-421b-a0bd-9f7c234bfac7.png)
There was a rotate cam spam also which I face whenever a game mode round starts
And a depost notif whenever any player dies in the game mode
One time I got the player control request spammed so hard that I got this
![image](https://user-images.githubusercontent.com/90883505/157118598-278f3933-00e2-449f-8523-13b519919a94.png)

**Comment by howdoiusekeyboard** [comment]
Also, during cayo heist when you have the to unlock the doors using the keycards, the other player's character gets stuck (bugged/glitched) and I constantly get the played control request denied spam

**Comment by Yimura** [comment]
Ye we're aware of the issue, it will get worked on when we make the time.
