### ISSUE TITLE
[Bug]: Crashing randomly

### ISSUE THREAD

**Issue by empty-head** [Yimura/YimMenu#862]
### Describe the bug

Crashing randomly. Doesn't seem to be at any specific time, just crashing after a while of playing

### Steps To Reproduce

1. Crash (cool)

### Expected Behavior

aaaaaa

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/10419769/cout.log)

### Store

Rockstar

### Additional context

Originally the crash logs were saying it was from the receive_net_message hook but even after disabling that hook it crashes randomly

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Loko415** [comment]
goto reactions turn off lost connection kick and breakup kick notis
