### ISSUE TITLE
[Request]: INI and XML

### ISSUE THREAD

**Issue by llmmqq123** [Yimura/YimMenu#864]
### Problem

INI and XML

### Solution

Request the addition of INI and XML support

### Reason

practicability

**Comment by Yimura** [comment]
INI and XML support for what?

**Comment by TheGreenBandit** [comment]
There is no need for ini support, xml support if you really want to use xml vehicles i can convert them for u sometime, however with json vehicles there really is no need for xml

**Comment by Yimura** [comment]
But like the issue is pretty useless in its current state, INI/XML for what?

XML vehicles are a thing, but it might also be that they're asking for alternatives to settings.json and instead have those be in XML or INI.
Anyways pretty terrible issue and more context is required.

**Comment by Loko415** [comment]
> There is no need for ini support, xml support if you really want to use xml vehicles i can convert them for u sometime, however with json vehicles there really is no need for xml

you going to paste them from the old eclipse source? 💀

**Comment by Loko415** [comment]
Maybe looking at menyoos source code may help... or maybe looking at essential trainer?

**Comment by Loko415** [comment]
> But like the issue is pretty useless in its current state, INI/XML for what?
> 
> XML vehicles are a thing, but it might also be that they're asking for alternatives to settings.json and instead have those be in XML or INI. Anyways pretty terrible issue and more context is required.

my guess could be xml vehicles / map mods or ini vehicles or map mods. Maybe even xml outfits and ini outfits

**Comment by FIying-Scotsman** [comment]
> INI and XML support for what?

I assume for Spooner and other saved things from other menus (past and present) etc.

Menyoo uses XML but there's been menus in the past which have saved custom vehicles, outfits and loadouts in JSON and ini format.

Issue is no menu was consistent with their approach so you may end up with a huge amount of bloat trying to cover all the possible anchor values.

**Comment by mcoo** [comment]
> There is no need for ini support, xml support if you really want to use xml vehicles i can convert them for u sometime, however with json vehicles there really is no need for xml

YES I need a tool to convert xml vehicles to json vehicles. Looking forward to your update.

**Comment by TheGreenBandit** [comment]
> > There is no need for ini support, xml support if you really want to use xml vehicles i can convert them for u sometime, however with json vehicles there really is no need for xml
> 
> YES I need a tool to convert xml vehicles to json vehicles. Looking forward to your update.

ok first you are gonna build tupoyemenu from here -> https://github.com/TupoyeMenu/TupoyeMenu
then you are gonna head over and download https://github.com/tupoy-ya/MenyooMP from tupoy-ya again
then what you want to do is run tupoyemenu in game so u can get the appdata, then paste in the menyoo asi into the asi folder in the appdata, then you run the menu again and u will have menyoo and tupoyemenu loaded at once, then what u needa do is spawn in whatever xml cars u want, hop in them and save them with tupoyemenu, once you are done with getting the xml cars converted to json you now need to transfer them to yimmenu so go to appdata in tupoye, go to saved cars, copy the saved cars, go to saved cars in appdata in yimmenu then paste the ones you converted there. thats how i do it if i want any vehicles
