### ISSUE TITLE
[Request]: Change most of the `ImGui::InputText` to use `components::input_text`

### ISSUE THREAD

**Issue by aoqia194** [Yimura/YimMenu#868]
### Problem

When people use `ImGui::InputText`, it doesn't block controls when inputting the text. So when you type the keybinds get sent to the game too.

adding a `components::input_text` is not hard, you can look at example I have here with std::string in src/gui/components/input_text.cpp: https://github.com/faithfullunaa/YimMenu/blob/ped-editor/src/gui/components/input_text.cpp

### Solution

Replace the `ImGui::InputText`s with `components::input_text` or `components::input_text_with_hint` where necessary.

### Reason

So when you press keys, it doesn't spam keybinds in the game like T for text chat.

**Comment by Loko415** [comment]
why not open a pull request instead?

**Comment by TheGreenBandit** [comment]
i got it

**Comment by aoqia194** [comment]
I was going to but i have no time currently but if someone doesnt do it in
the next like 2 hours then i will do it

**Comment by TheGreenBandit** [comment]
> I was going to but i have no time currently but if someone doesnt do it in the next like 2 hours then i will do it

im doing it rn, almost finished, will post pr when done dw

**Comment by aoqia194** [comment]
Resolved in Pull #869

**Comment by GeopJr** [comment]
Please wait until it gets merged!

**Comment by Loko415** [comment]
> > I was going to but i have no time currently but if someone doesnt do it in the next like 2 hours then i will do it
> 
> im doing it rn, almost finished, will post pr when done dw

gg. I can respect that

**Comment by Loko415** [comment]
abit off topc but i wanted to compliment you i guess
