### ISSUE TITLE
[Request]: Loose backend files should be organized

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#872]
### Problem

I know this isn't super important but every file that isn't categorized in a folder should probably go somewhere.

### Solution

Organize the damn solution. I understand things are categorized but the loose files should be taken care of.

### Reason

Human legibility

### Additional context

![Screenshot 2023-01-17 142822](https://user-images.githubusercontent.com/104751596/212994000-09dad7d5-5877-4a49-82d5-02b52432f35f.png)

This is what I mean

**Comment by ghost** [comment]
I'd do this myself, but I already know it will take a bit and Yim isn't going to approve it anyway.

**Comment by Yimura** [comment]
What a nice attitude, I bet people really like this side of yours.
Anyways, last time you just closed your PR and removed the fork of Yim.
There was no way to merge after that, you can check the history of PR's and I've only had one PR that wasn't merged of yours.
https://github.com/YimMenu/YimMenu/pull/174

You can also see I approved those changes so I don't think I'm that horrible of a person.

You can also check for yourself if you don't believe me and I can't hide or remove PR's once they've been opened.
https://github.com/YimMenu/YimMenu/pulls?q=is%3Apr+author%3Acl1xa+is%3Aclosed

**Comment by TheGreenBandit** [comment]
ill take care of this issue quick

**Comment by Yimura** [comment]
Not really necessary.

Some files should be moved to subfolders but definitely not all of them.

**Comment by TheGreenBandit** [comment]
in the commit im about to push i just moved some files around to places i thought were suitable. Obiously changes have to be requested because i wasnt paying to much attention doing it and i would have to code everything to their new file placemnts in the includes, however i would definitely like feedback before that #875

**Comment by ghost** [comment]
> What a nice attitude, I bet people really like this side of yours. Anyways, last time you just closed your PR and removed the fork of Yim. There was no way to merge after that, you can check the history of PR's and I've only had one PR that wasn't merged of yours. #174
> 
> You can also see I approved those changes so I don't think I'm that horrible of a person.
> 
> You can also check for yourself if you don't believe me and I can't hide or remove PR's once they've been opened. https://github.com/YimMenu/YimMenu/pulls?q=is%3Apr+author%3Acl1xa+is%3Aclosed

I am just antagonizing you. I promise you I am joking. I'm usually intoxicated when I make bug reports and I think they're funnier than they are. As long as I get my point across.

**Comment by TheGreenBandit** [comment]
> I am just antagonizing you. I promise you I am joking. I'm usually intoxicated when I make bug reports and I think they're funnier than they are. As long as I get my point across.


It is very hard to convery sarcasm or joking manner through text, dont worry, it has happened to all of us
