### ISSUE TITLE
[Bug]: Dance mode crashing game

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#873]
### Describe the bug

Toggled on dance mode in single player and the game closed. Not a single feature on the menu was enabled. Blank configuration.

### Steps To Reproduce

1. Delete settings configuration, and online cache from YimMenu folder in roaming
2. Inject in singleplayer
3. Click "I will update cache in online"
4. Enable dance mode
5. Gone

### Expected Behavior

I am dancing

### Screenshots and/or Logs

[dance mode crash.txt](https://github.com/YimMenu/YimMenu/files/10438793/dance.mode.crash.txt)

### Store

Steam

### Additional context

Latest nightly build release as of 1/17/2023

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
After the cache is completed, try to restart the game to see if it still crash

**Comment by LiamD-Flop** [comment]
For me it doesn't crash, but it isn't working either

**Comment by TheGreenBandit** [comment]
this is because dance mode requires assets from gtav online that are not loaded in singleplayer. it can only be used in single player, could be disabled if !m_in_session or whatever it is

**Comment by LiamD-Flop** [comment]
Dance mode is disabled at the moment + shouldn't cause crash anymore
