### ISSUE TITLE
[Request]: Backend code cleanup

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#874]
### Problem

Code is messy and inconsistent. I am aware that there are a lot of contributors, but here's a few things that should be reviewed more carefully. 

I AM NO PROFESSIONAL. I AM JUST BEING PICKY. I UNDERSTAND THIS IS ALL PREFERENCE

### Solution

Please review the following

### Random line breaks

![image](https://user-images.githubusercontent.com/104751596/212997434-4e34a89a-0b02-4432-8fe9-72b4aaee3992.png)
![image](https://user-images.githubusercontent.com/104751596/213001264-0f31172b-aef3-48ac-bb79-b6a00f3245af.png)

Line breaking was used to make the separators a little more clear. Great! I agree. Why isn't it done in all classes?
![image](https://user-images.githubusercontent.com/104751596/213000913-d3e1bb7a-5380-42f9-9a1a-bf0bf54db8d8.png)
![image](https://user-images.githubusercontent.com/104751596/213001069-24549b89-283a-480a-9003-29cbaf1ff2c0.png)

### Formatting inconsistency

Some statements look like this...
![image](https://user-images.githubusercontent.com/104751596/212997515-1c3ad35d-dcea-4b75-8ec5-ec3a6c3f8eb5.png)
![image](https://user-images.githubusercontent.com/104751596/213000156-10bffac6-7983-48a9-8cf9-85da1d5e329e.png)
...and others look like this
![image](https://user-images.githubusercontent.com/104751596/212997575-fd9cc0dc-a398-49a6-acd1-ea15f443d2e7.png)
![image](https://user-images.githubusercontent.com/104751596/213000214-60a58ac8-67d8-4135-9513-42c5d8acd729.png)

This line seems to have a well formatted if statement...
![image](https://user-images.githubusercontent.com/104751596/212998534-a2ac2779-efe3-488b-a25d-1d68a87d958d.png)
...but in the same exact file this happens...
![image](https://user-images.githubusercontent.com/104751596/212998662-73436e99-3a61-4b21-86b2-16d783439215.png)
...and then THIS later on in a different class
![image](https://user-images.githubusercontent.com/104751596/213000826-cc793c6b-804d-450c-8d6e-adfa269e4709.png)

### Legibility

Why do this to make it more "readable"
![image](https://user-images.githubusercontent.com/104751596/212997932-ad3dabc8-76fe-454d-9fe7-75acdb97572c.png)
When you could just do this
![image](https://user-images.githubusercontent.com/104751596/212998039-f0df7b9d-4eb2-4c79-b7e4-804daa80ae95.png)
Or just don't do it at all?
![image](https://user-images.githubusercontent.com/104751596/212999118-b2c713d2-103c-42d3-ac87-8181a2a9c3e8.png)

I understand that this is a short and simple function, but why not make break it up and make it look clean?
**Before:**
![image](https://user-images.githubusercontent.com/104751596/212999735-0ba8ec87-55a4-49c8-8188-8f25b427191d.png)
**After:**
![image](https://user-images.githubusercontent.com/104751596/212999486-928a8e50-45da-43fa-8b4a-2e2fe5dc70da.png)
Compiles exactly the same except now it's not a cluster fuck at first glance

### Reason

Consistency reflects a positive image and cleanliness is always preferred.

### Additional context

One more time in case you can't read
I AM NO PROFESSIONAL. I AM JUST BEING PICKY. I UNDERSTAND THIS IS ALL PREFERENCE

**Comment by xiaoxiao921** [comment]
This is definitly a minor issue, that said if anyone know about a good commit hook for auto formating that would be nice

**Comment by ghost** [comment]
> This is definitly a minor issue, that said if anyone know about a good commit hook for auto formating that would be nice

Time to beg jeop

**Comment by Loko415** [comment]
big issue... ive had the entire backend loop crash and not recover when looping certain stuff

**Comment by Loko415** [comment]
like with the vehicle weapons bugging out sometimes when you aim at a player

**Comment by Yimura** [comment]
Loko

**Comment by Yimura** [comment]
Please use one comment

**Comment by Yimura** [comment]
To explain what you're doing

**Comment by BugisoftRSG** [comment]
one

**Comment by BugisoftRSG** [comment]
word

**Comment by BugisoftRSG** [comment]
per

**Comment by Loko415** [comment]
i did use one comment somewhat.... idk since ive added alot of stuff to my fork i could have broken something maybe

**Comment by BugisoftRSG** [comment]
sentence

**Comment by BugisoftRSG** [comment]
please

**Comment by TheGreenBandit** [comment]
lmao

**Comment by tupoy-ya** [comment]
My email, oh no.

**Comment by Yimura** [comment]
I was hoping that satire would get through to him cause he doesn't change.

**Comment by SkiddyToast** [comment]
If it doesn't occur with an unmodified version of YimMenu, your problem is invalid, Loko.

**Comment by Loko415** [comment]
ill try the code under unmodified yim menu and see if it does the same thing. I think it will since someone made an issue about this before. It grabs the nearby peds and vehicles then stresses the script out and crashes. Atleast thats what i think happens. It doesnt recover unless you reload the menu...

**Comment by LiamD-Flop** [comment]
imagine

**Comment by LiamD-Flop** [comment]
typing

**Comment by LiamD-Flop** [comment]
everything

**Comment by LiamD-Flop** [comment]
in

**Comment by LiamD-Flop** [comment]
each

**Comment by LiamD-Flop** [comment]
comment

**Comment by LiamD-Flop** [comment]
separately
