### ISSUE TITLE
[Request]: #874 Cont.

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#876]
### Problem
#874
#874
#874
#874
Cont. because thread was locked due to contributor immaturity (and Loko).

### Grouping

Some code uses groups, and other code doing almost the same thing is not grouped.
![image](https://user-images.githubusercontent.com/104751596/213009907-1a18f8de-9c02-4d9d-b6d5-2387a089bd83.png)

### ImGui helper functions vs actual ImGui calls 

Someone also mentioned this (partially) in #868
Either make everything a helper func or just remove this junk entirely?
![image](https://user-images.githubusercontent.com/104751596/213010542-ba4be8dd-d8f9-4f70-8f37-0ed19b328b12.png)
![image](https://user-images.githubusercontent.com/104751596/213010060-536f257d-76c3-4df3-8341-a3ebe8661ec7.png)
![image](https://user-images.githubusercontent.com/104751596/213010134-3dbe5404-9205-4d6c-aca0-8df2d5d7ae62.png)

### Solution

#874

### Reason

#874

### Additional context

#874

**Comment by LiamD-Flop** [comment]
Some of these issues are already solved in pr's but we understand
Most of the issues with the commands is that not all features are converted to commands yet.
But this is slowly being converted

**Comment by ghost** [comment]
I think the commands are a good idea for the most part. Though it's strange to me that it was released before everything was converted.

**Comment by aoqia194** [comment]
I feel like refactor is needed. Like using Clang Tidy and having formatting setting file inside project so user always formats using that format! It is easy to install for code editors too.

Also with ped weapon, maybe have function get_ped_weapon for Ped class? or just weapon_hash.
I think better idea than calling the same natives in 50 different files.
