### ISSUE TITLE
[Bug]: can_apply_data not working

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#877]
### Describe the bug

can_apply_data  does not filter crash models.

### Steps To Reproduce

Enable crash model protection.

### Expected Behavior

-

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Loko415** [comment]
+16 on the end of vtables fixes this

**Comment by Aboba7778** [comment]
> +16 on the end of vtables fixes this

Did not quite understand. Can be more ?

**Comment by ghost** [comment]
> > +16 on the end of vtables fixes this
> 
> Did not quite understand. Can be more ?

Just see past his conceitment. If hes vague he sounds smarter.

**Comment by Roseiit** [comment]
because r * has removed some things, most of the protection has failed

**Comment by Aboba7778** [comment]
> because r * has removed some things, most of the protection has failed


In most paid menus, object protection works fine.
If you do not check datanodes in the YimMenu code and always return false, then the objects will not spawn.

**Comment by Roseiit** [comment]
> > because r * has removed some things, most of the protection has failed
> 
> In most paid menus, object protection works fine. If you do not check datanodes in the YimMenu code and always return false, then the objects will not spawn.

obviously, no one updates the latest sync tree for yim
