### ISSUE TITLE
[Bug]: instantly crash after inject

### ISSUE THREAD

**Issue by AtomicBool** [Yimura/YimMenu#879]
### Describe the bug

instantly crash after inject

### Steps To Reproduce

open theg game
inject
crash

OS:windows 22H2 19045.2486
can inject to the game three days ago
used cmake to build it myself

### Expected Behavior

Needs help with that

### Screenshots and/or Logs

```
<paste your logs here>
[cout.log](https://github.com/YimMenu/YimMenu/files/10445714/cout.log)

```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
I've seen that the new windows update has caused frequent bluescreens, try redownloading/rebuilding dll

**Comment by AtomicBool** [comment]
> I've seen that the new windows update has caused frequent bluescreens, try redownloading/rebuilding dll, and deleting appdata, if that doesn't work it is definitely the new windows update


seem windows update caused that?
i have remove folder Bigbase v2 but it still crash

**Comment by AtomBottle** [comment]
> I've seen that the new windows update has caused frequent bluescreens, try redownloading/rebuilding dll, and deleting appdata, if that doesn't work it is definitely the new windows update

i have remove folder Bigbase v2 but it still crash
