### ISSUE TITLE
[Request]:  r* disabled the run time type info

### ISSUE THREAD

**Issue by Roseiit** [Yimura/YimMenu#881]
### Problem

.

### Solution

So this is the reason why each sync protection node does not work. Now only someone needs to re-enable it

### Reason

.

### Additional context

.

**Comment by ghost** [comment]
Explain?

**Comment by FIying-Scotsman** [comment]
> Explain?

I assume the OP is asking for the sync tree names in Yim to be fixed as when the RTTI info was stripped from GTA - the names changed/were mangled breaking sync tree related features.

It's possible with IDA Python scripts to restore the RTTI (take the RTTI from an old dump and map it to the QWORDs in the new one) in a dump and/or find the new tree names but it's not going to be quick.

**Comment by Roseiit** [comment]
> > Explain?
> 
> I assume the OP is asking for the sync tree names in Yim to be fixed as when the RTTI info was stripped from GTA - the names changed/were mangled breaking sync tree related features.
> 
> It's possible with IDA Python scripts to restore the RTTI (take the RTTI from an old dump and map it to the QWORDs in the new one) in a dump and/or find the new tree names but it's not going to be quick.
It has been a month since no one can make sync node work again. I think

**Comment by Roseiit** [comment]
> > Explain?
> 
> I assume the OP is asking for the sync tree names in Yim to be fixed as when the RTTI info was stripped from GTA - the names changed/were mangled breaking sync tree related features.
> 
> It's possible with IDA Python scripts to restore the RTTI (take the RTTI from an old dump and map it to the QWORDs in the new one) in a dump and/or find the new tree names but it's not going to be quick.

It has been a month since no one can make sync node work again. I think

**Comment by yasmasdas** [comment]
Isn't the RTTI just hashed now?

**Comment by Yimura** [comment]
> Isn't the RTTI just hashed now?

Not all classes have this hashes RTTI available, to be more specific.
The classes we use to protect from crashes don't have these hashes, only certain other classes have them.
