### ISSUE TITLE
[Request]: Some QOL options

### ISSUE THREAD

**Issue by HEJiNi** [Yimura/YimMenu#888]
### Problem

1- There should be a "Give all ammos" option in self/weapons then we can also add it to hotkeys. (also if you pick yourself in playerlist and go to Misc and press give ammo it won't work.)
2- an Option for making session empty would be nice.
3- there is ESP so why there isn't aim assist/ aimbot (atleast for NPC's, that's fun i guess).
4- just a reminder "No idle kick" not working right now.
5- Option for "Clear wanted level" in self. so you don't have to check and uncheck never wanted level everytime you want to clear wanted. it also makes it easy to add a hotkey for it later. and no if you pick yourself in playerlist and go to Misc and press clear wanted it won't work.
6- an option for regen health and armor fast so you don't have to use god mode in some situations.( i don't think this is as detected as god mode or bullet proof by other menus).

### Solution

1- for now we can use "Give all weapons" (it also gives all ammos) but it ruins your custom Loadout. or use unlimited ammos but i guess that's detected in some menus.
2- for now i can "lost connection kick" myself is this the right way? 

### Reason

QOL

**Comment by TheGreenBandit** [comment]
Ill work on this tommorow, i already have the aim assist drawn up where it just shoots a bullet at the head of the entity you look at, will make it only for peds

**Comment by JDMJay** [comment]
> Ill work on this tommorow, i already have the aim assist drawn up where it just shoots a bullet at the head of the entity you look at, will make it only for peds

Wouldn't it be more efficient if it actually moved your aiming cursor to lock on to the ped/player so you can see which ped you killed in a big radius of pedestrians

**Comment by TheGreenBandit** [comment]
> > Ill work on this tommorow, i already have the aim assist drawn up where it just shoots a bullet at the head of the entity you look at, will make it only for peds
> 
> 
> 
> Wouldn't it be more efficient if it actually moved your aiming cursor to lock on to the ped/player so you can see which ped you killed in a big radius of pedestrians

The way i have it is if you press shoot while aiming at a ped it will shoot another bullet hitting their head. There is a check for if they are a player also

**Comment by TheGreenBandit** [comment]
>2- for now i can "lost connection kick" myself is this the right way?

yes, you can do it this way

**Comment by Gasferr** [comment]
> Ill work on this tommorow, i already have the aim assist drawn up where it just shoots a bullet at the head of the entity you look at, will make it only for peds

It's a long time before the version with aimbot/shooting aim comes out?

**Comment by TheGreenBandit** [comment]
> 
> It's a long time before the version with aimbot/shooting aim comes out?

Oh yeah ive just been busy, it will be finished soon
