### ISSUE TITLE
[Bug]: random crashing

### ISSUE THREAD

**Issue by empty-head** [Yimura/YimMenu#893]
### Describe the bug

crashing for seemingly no reason at random times
tried regenerating cache, tried turning off all reactions, tried turning off all protections. all same result

### Steps To Reproduce

1. play
2. crash

### Expected Behavior

not crashing

### Screenshots and/or Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/10471728/cout.log)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Gh0sSte** [comment]
i think its because of asynchronous hooking? Since when i removed it the game ran fine but with it the game crashes randomly? this could just be on my side but doing that fixed it for me.

**Comment by MarkEcza** [comment]
> i think its because of asynchronous hooking? Since when i removed it the game ran fine but with it the game crashes randomly? this could just be on my side but doing that fixed it for me.

Unlikely, the async pattern scanning runs one time on inject. It also waits for the threads to complete.

**Comment by Yimura** [comment]
Is this still an issue?

**Comment by LiamD-Flop** [comment]
No response, possibly fixed
