### ISSUE TITLE
[Request]: Integration of Coloading with Stand 

### ISSUE THREAD

**Issue by LasNarvalo** [Yimura/YimMenu#895]
### Problem

I have try to rendering compatible Yim Menu with 2take1 and stand but when i join a Only invite Lobby im stuck on the clouds. 

I have just one hooks of broken : 

[11:52:20][WARNING/batch.cpp:33]: Failed to find 'BE'.

Its possible to replace that Hooks by an other ? I dont have the skill for that. 

Im stuck on the : "Start Freemode Launch Script" moment. 

and Stand return : 

[21/01/2023 11:53:33] freemode script died on Return.

i think its a protection of Yim with the Freemode script.

### Solution

deleted in /src/script_function.hpp

static inline script_function set_freemode_session_active("SFSA", RAGE_JOAAT("freemode"), "2D 00 02 00 00 75 5D ? ? ? 50", 0);

### Reason

I love Yim menu and i want coloading that menu without problems👍

**Comment by Adler-D3R** [comment]
Leave Stand for YimMenu then, that will make you cool guy 😎.

**Comment by maybegreat48** [comment]
This is a Stand issue as I've explained before. We can't do anything about it

**Comment by LasNarvalo** [comment]
I like stand just because i have my own Lua for stand and the API its not to complex. But haaaa Yim menu is also really interesting. Its sad for me i dont have a big skill on C++ but its the first project like that i have see on the GTA community. And with a big heart nothing is impossible :)

**Comment by LasNarvalo** [comment]
[](url)

> This is a Stand issue as I've explained before. We can't do anything about it

![Coloading Yim](https://user-images.githubusercontent.com/101971293/213866159-b87ba92a-032e-4557-9a75-52777f3fe9a9.png)

**Comment by LiamD-Flop** [comment]
https://github.com/YimMenu/YimMenu/issues/804
This is another issue that wants us to fix this. I can't find the specific one, but as we said. It's easier for stand to fix this than for us. As the stand devs are able to see what we do "hence open-source" but we have no idea what is happening on their end.

**Comment by LasNarvalo** [comment]
> #804 This is another issue that wants us to fix this. I can't find the specific one, but as we said. It's easier for stand to fix this than for us. As the stand devs are able to see what we do "hence open-source" but we have no idea what is happening on their end.

I have fix that issue and i can coload Yim Menu now with all my internal menus 👍

**Comment by LasNarvalo** [comment]
![Coloading Yim](https://user-images.githubusercontent.com/101971293/213866615-92718d0c-cbd3-487b-b30c-f9d0b7efc81f.png)

Its the party of coloading now xD

**Comment by Gh0sSte** [comment]
how did you do this? I am also interested in doing this....

**Comment by Sainan** [comment]
> how did you do this? I am also interested in doing this....

As mentioned in the other thread, Game > Use Script VM Reimplementation can be used as a workaround.

**Comment by LasNarvalo** [comment]
> > how did you do this? I am also interested in doing this....
> 
> As mentioned in the other thread, Game > Use Script VM Reimplementation can be used as a workaround.

I dont have do that, i have deleted in /src/script_function.hpp

static inline script_function set_freemode_session_active("SFSA", RAGE_JOAAT("freemode"), "2D 00 02 00 00 75 5D ? ? ? 50", 0);

that work too, peace ;)

**Comment by maybegreat48** [comment]
Doing that will cause infinite loading screens for anyone looking to enter Cayo Perico in your session

**Comment by NefariousIntent2** [comment]
> ![Coloading Yim](https://user-images.githubusercontent.com/101971293/213866615-92718d0c-cbd3-487b-b30c-f9d0b7efc81f.png)
> 
> Its the party of coloading now xD

Lol, 3 of the best mod menus and you still have a free one lol

**Comment by Yimura** [comment]
Duplicate of #804, closing this one.
