### ISSUE TITLE
[Request]: Enhancement of IP spoofing 

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#896]
### Problem

Other modders are able to see our original IP while for us it's spoofed using the menu.. 

### Solution

I'm not sure if this can be done but changing something in order to Spoof the IP in such a way so that it cannot be detected by the modders..

### Reason

This would be a great enhancement if it's done..

**Comment by Yimura** [comment]
If you go too hard on spoofing your IP other clients won't be able to communicate properly with your game client.

As such it's not possible to completely spoof it, you can only use a VPN in such cases if you wish to hide your real IP.

**Comment by CypherMorgan** [comment]
Alright..
