### ISSUE TITLE
[Bug]: Protections: Blocked request control event by [player in the same lobby]

### ISSUE THREAD

**Issue by farsdewibs0n** [Yimura/YimMenu#899]
### Describe the bug

Playing Casino Heist (Big Con) Gruppe Sechs. After arriving at the location, it goes black screen and loads indefinitely.

This error shown by all players in the lobby.

### Steps To Reproduce

Get a friend to start the heist
Reach the spot (in any way)

### Expected Behavior

It should load just fine.

### Screenshots and/or Logs
[cout.log](https://github.com/YimMenu/YimMenu/files/10475265/cout.log)

![gambar](https://user-images.githubusercontent.com/13050356/213934640-d061a7b3-9413-461c-aa88-fa16e36f8d32.png)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment]
Ah yes, the ol' request control problem. I had this issue in my cheat, constantly trying to add edge case detection. There is also the prison bus request control during a cutscene, although if you reject that, nothing really happens you still get off the bus, but it could lead to Rashkovsky getting stuck after you give him a gun, I've run into that like 100 times. What I eventually did was check if the request was for my personal vehicle, then reject it. If it wasn't, I would let it through.

**Comment by Yimura** [comment]
@gir489returns 

I think that's exactly what we're doing currently:
https://github.com/YimMenu/YimMenu/blob/2ce44e8d9874f23d1657f97567d920de78c08f95/src/hooks/protections/received_event.cpp#L469-L480

**Comment by gir489returns** [comment]
> @gir489returns
> 
> I think that's exactly what we're doing currently:
> 
> https://github.com/YimMenu/YimMenu/blob/2ce44e8d9874f23d1657f97567d920de78c08f95/src/hooks/protections/received_event.cpp#L469-L480

Close, you're not checking the personal vehicle flag. You're just checking if it's requesting the vehicle you're in, which is causing the OP's issue.

**Comment by SkiddyToast** [comment]
> Close, you're not checking the personal vehicle flag. You're just checking if it's requesting the vehicle you're in, which is causing the OP's issue.

Isn’t this a decorator?

**Comment by gir489returns** [comment]
> > Close, you're not checking the personal vehicle flag. You're just checking if it's requesting the vehicle you're in, which is causing the OP's issue.
> 
> Isn’t this a decorator?

Yep.

**Comment by gir489returns** [comment]
@Yimura You did not properly address this issue. While it may (somehow?) remove the player from the driver's seat, there could still be scenarios where the script host requests control of your vehicle during a cut scene for some reason. I suggest you instead replace it with a personal vehicle check.

**Comment by maybegreat48** [comment]
While that may work, I (and probably others) spawn anonymous vehicles using the menu and only use PVs when I have to. An activity session check could be added to allow the event during missions and heists if required

We should be able to whitelist vehicles with the mission flag set too, but that may allow for griefing opportunities

**Comment by gir489returns** [comment]
> While that may work, I (and probably others) spawn anonymous vehicles using the menu and only use PVs when I have to. An activity session check could be added to allow the event during missions and heists if required

`DECORATOR::DECOR_SET_INT(vehicle, "RandomID", g_local_player.player_hash);`

I checked for personal or spawned vehicles, for me they had the same decorator that I set, which was RandomID. You can't use an arbitrary decorator, the game will just reject it. I think that would be the proper solution, since it should cover your edge case.

**Comment by Yimura** [comment]
Issue still present.

**Comment by gir489returns** [comment]
> Issue still present.

The issue described by OP is (kinda) still there. While we just got the blocked events, we didn't get stuck in purgatory loading hell like he did. It's usually when I don't get the blocked message is when I get stuck loading, because something is wrong with the script.
