### ISSUE TITLE
[Request]: Save Handling

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#902]
### Solution

Make sure that the handling parameters are saved on the vehicle for other players in the session.

### Reason

-

**Comment by Yimura** [comment]
This is not possible as handling data is client side only and impossible to transfer to other players.

**Comment by Aboba7778** [comment]
> This is not possible as handling data is client side only and impossible to transfer to other players.

In 0xCheats saving on session: Increase speed and Unlimited Speed

**Comment by Yimura** [comment]
These are not related to modifying the handling of vehicles in the handling menu.

However this native is probably the one used:
`VEHICLE::SET_VEHICLE_FORWARD_SPEED` : https://natives.gta.menu/natives/0xAB54A438726D25D5

**Comment by Aboba7778** [comment]
> These are not related to modifying the handling of vehicles in the handling menu.
> 
> However this native is probably the one used: `VEHICLE::SET_VEHICLE_FORWARD_SPEED` : https://natives.gta.menu/natives/0xAB54A438726D25D5


This native speeds up the vehicle in the one moment, but there is a change acceleration.

**Comment by yasmasdas** [comment]
This is the native @Aboba7778 likely meant
https://natives.gta.menu/natives/0x93A3996368C94158
VEHICLE::MODIFY_VEHICLE_TOP_SPEED

**Comment by Aboba7778** [comment]
> This is the native @Aboba7778 likely meant https://natives.gta.menu/natives/0x93A3996368C94158 VEHICLE::MODIFY_VEHICLE_TOP_SPEED

thx.
