### ISSUE TITLE
[Request]: Show who online in players tab

### ISSUE THREAD

**Issue by PrimeMK105** [Yimura/YimMenu#904]
### Solution

![example — копия](https://user-images.githubusercontent.com/42176307/214230012-341a5122-cae3-49da-afd0-5362c9e50133.png)

### Reason

I think it help a bit to know if angry dude what wait you until next launch of the game is online or not.

**Comment by gir489returns** [comment]
We had this in bigbase v2, it requires making calls to the SCAPI. You can use two vectors to make the call. A: You can find the functions internally that setup the call and then read the struct it returns. B: You can make the calls manually. If you look at the function used for joining SCID, it should be somewhere within the ESC menu's friends list function. Work out how it determines the online state from friends, and you can give it an arbitrary list of SCIDs.

**Comment by PrimeMK105** [comment]
> If you have someone harassing you and he knows what he's doing, he can change his SCID and this will fail.

yeah i know, this was just an example
