### ISSUE TITLE
[Request]: Change color of ingame HUD

### ISSUE THREAD

**Issue by PrimeMK105** [Yimura/YimMenu#906]
### Problem

Right now you can change only color of the menu, but not of ingame color for hud.

### Solution

A option in settings (maybe over the GUI color of menu) that will allow you to change color of ingame hud (watch examples)
![settings](https://user-images.githubusercontent.com/42176307/214391226-cd0b2609-5472-4ad2-b5b2-c822131695aa.png)
![example](https://user-images.githubusercontent.com/42176307/214391233-61784491-8c99-49d5-bad5-14bff72c2fa8.png)

### Reason

If game not allow us to change colors of hud, why not to make it in menu? Also i think many of us will gonna enjoy of custom color, not this standard blue.

**Comment by TheGreenBandit** [comment]
Ill add it in my qol repo

**Comment by Sys0xdbg** [comment]
here's list with index and default colors (from n3nyooo)
https://pastebin.com/5F2tum3i
