### ISSUE TITLE
Request - Outfit Editor

### ISSUE THREAD

**Issue by OmniModz** [Yimura/YimMenu#908]
Will you guys be implementing an outfit editor anytime in the future? The ability to create modded outfits would be amazing.

**Comment by Peax** [comment]
People tried to no avail in #624

**Comment by Rxann** [comment]
#1089

it's waiting to be merged

**Comment by Rxann** [comment]
you should be able to close this

**Comment by Yimura** [comment]
@Rxann , when the PR gets closed the issue closes automatically.

**Comment by Rxann** [comment]
@Yimura Thanks,will it be getting merged soon?

**Comment by Yimura** [comment]
> @Yimura Thanks,will it be getting merged soon?

Sometime in the future, I don’t give ETA’s.

**Comment by Rxann** [comment]
Okay, thanks for helping
