### ISSUE TITLE
[Request]: Change other player's money and rp

### ISSUE THREAD

**Issue by Cuqty** [Yimura/YimMenu#915]
### Problem

Change other player's money and rp

### Solution

i dont know

### Reason

i like yimmenu

**Comment by TheGreenBandit** [comment]
Too toxic imo to have something like that readily public

**Comment by Cuqty** [comment]
In my opinion, this function has no lethality, and I only requested it because I was flashed to 8000rp by a cheater

**Comment by CzuyK** [comment]
> 在我看來，這種東西太毒了，不能輕易公開

In my opinion, this function has no lethality, and I only requested it because I was flashed to 8000rp by a cheater

**Comment by Aure7138** [comment]
> In my opinion, this function has no lethality, and I only requested it because I was flashed to 8000rp by a cheater

A bit off topic, but if you want to change back to your RP you can use this stat https://github.com/YimMenu/YimMenu/blob/f1c00929566051f99e2f8256b974c784af9c9fb2/src/util/local_player.hpp#L22 to set the rp value, 

about the rp value list can be found here https://github.com/YimMenu/YimMenu/blob/master/src/core/data/levels.hpp 

or use 1.64 global 297010 (can be found by searching for >=8000 in the decompiled scripts)

**Comment by ghost** [comment]
I'd settle for having script kiddie attacks have no effect, which should make them feel more flaccid than anything else. 

Fighting fire with fire only gives them the attention they so desperately crave.

**Comment by gir489returns** [comment]
This hasn't been patched yet? Yikes.

**Comment by SkiddyToast** [comment]
> This hasn't been patched yet? Yikes.

I have put a patch in the Matrix, R* is a little slow.

**Comment by Cuqty** [comment]
> > 在我看來，這個功能沒有殺傷力，我只是因為被作弊者刷到8000rp才請求的
> 
> 有點跑題了，但如果你想改變你的RP，你可以使用這個統計
> 
> https://github.com/YimMenu/YimMenu/blob/f1c00929566051f99e2f8256b974c784af9c9fb2/src/util/local_player.hpp#L22
> 
> 設置rp值，
> 關於rp值列表可以在這裡找到https://github.com/YimMenu/YimMenu/blob/master/src/core/data/levels.hpp
> 
> 或者使用1.64 global 297010（可以在反編譯腳本中搜索 >=8000 找到）

how to use it please help me

**Comment by TheGreenBandit** [comment]
> > > 在我看來，這個功能沒有殺傷力，我只是因為被作弊者刷到8000rp才請求的
> > 
> > 
> > 有點跑題了，但如果你想改變你的RP，你可以使用這個統計
> > https://github.com/YimMenu/YimMenu/blob/f1c00929566051f99e2f8256b974c784af9c9fb2/src/util/local_player.hpp#L22
> > 
> > 設置rp值，
> > 關於rp值列表可以在這裡找到https://github.com/YimMenu/YimMenu/blob/master/src/core/data/levels.hpp
> > 或者使用1.64 global 297010（可以在反編譯腳本中搜索 >=8000 找到）
> 
> how to use it please help me

just use kiddions to set it if u honestly cant figure it out

**Comment by TheGreenBandit** [comment]
@Yimura this can be closed as its not possible anymore

**Comment by Yimura** [comment]
@TheGreenBandit, this is still possible. 

Regarding this issue however such a feature will never be implemented in YimMenu.

**Comment by TheGreenBandit** [comment]
> @TheGreenBandit, this is still possible. 

That sucks. Im glad it atleast patched the main way of doing it, so any menus that got their hands on the code to do it will have to spend awhile to update it. 👍
