### ISSUE TITLE
[Bug]: Crashed by a Modder

### ISSUE THREAD

**Issue by Clone69420** [Yimura/YimMenu#916]
### Describe the bug

- crash

### Steps To Reproduce

- none

### Expected Behavior

- crash

### Screenshots and/or Logs

```
Dumping registers:

RAX: 0x3
RCX: 0x0
RDX: 0xFFFFFFFFFFFFFFFF
RBX: 0x2809BDACA50
RSI: 0x1
RDI: 0x2809BDACA90
RSP: 0xEC2F0FE768
RBP: 0x1
R8:  0xC
R9:  0x282278C6B70
R10: 0xEC2F0FE6D8
R11: 0xEC2F0FE6B0
R12: 0x0
R13: 0x0
R14: 0x280A2505BA0
R15: 0x2809BDACA78

stack dump [0]	 D:\Grand Theft Auto V\GTA5.exe+0x1650E4B 0x7FF7A6620E4B
stack dump [1]	 D:\Grand Theft Auto V\GTA5.exe+0xB80761 0x7FF7A5B50761
stack dump [2]	 D:\Grand Theft Auto V\GTA5.exe+0xBAD269 0x7FF7A5B7D269
stack dump [3]	 D:\Grand Theft Auto V\GTA5.exe+0x888516 0x7FF7A5858516
stack dump [4]	 D:\Grand Theft Auto V\GTA5.exe+0x1610051 0x7FF7A65E0051
stack dump [5]	 D:\Grand Theft Auto V\GTA5.exe+0x8C902A 0x7FF7A589902A
stack dump [6]	 D:\Grand Theft Auto V\GTA5.exe+0x16104A1 0x7FF7A65E04A1
stack dump [7]	 D:\Grand Theft Auto V\GTA5.exe+0x8C9259 0x7FF7A5899259
stack dump [8]	 D:\Grand Theft Auto V\GTA5.exe+0x160A1C9 0x7FF7A65DA1C9
stack dump [9]	 D:\Grand Theft Auto V\GTA5.exe+0x71EF1C 0x7FF7A56EEF1C
stack dump [10]	 D:\Grand Theft Auto V\GTA5.exe+0x1104138 0x7FF7A60D4138
stack dump [11]	 D:\Grand Theft Auto V\GTA5.exe+0x1104646 0x7FF7A60D4646
stack dump [12]	 D:\Grand Theft Auto V\GTA5.exe+0x941106 0x7FF7A5911106
stack dump [13]	 D:\Grand Theft Auto V\GTA5.exe+0x95149C 0x7FF7A592149C
stack dump [14]	 D:\Grand Theft Auto V\GTA5.exe+0x933BD3 0x7FF7A5903BD3
stack dump [15]	 D:\Grand Theft Auto V\GTA5.exe+0x950A85 0x7FF7A5920A85
stack dump [16]	 D:\Grand Theft Auto V\GTA5.exe+0x15F4C55 0x7FF7A65C4C55
stack dump [17]	 D:\Grand Theft Auto V\GTA5.exe+0x15F448B 0x7FF7A65C448B
stack dump [18]	 D:\Grand Theft Auto V\GTA5.exe+0x27648 0x7FF7A4FF7648
stack dump [19]	 D:\Grand Theft Auto V\GTA5.exe+0x20D37 0x7FF7A4FF0D37
stack dump [20]	 D:\Grand Theft Auto V\GTA5.exe+0x15F4094 0x7FF7A65C4094
stack dump [21]	 D:\Grand Theft Auto V\GTA5.exe+0x1494 0x7FF7A4FD1494
stack dump [22]	 D:\Grand Theft Auto V\GTA5.exe+0x12DD997 0x7FF7A62AD997
stack dump [23]	 D:\Grand Theft Auto V\GTA5.exe+0x17E678C 0x7FF7A67B678C
stack dump [24]	 C:\WINDOWS\System32\KERNEL32.DLL+0x126BD BaseThreadInitThunk
stack dump [25]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x5DFB8 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by SkiddyToast** [comment]
`CTaskTakeOffPedVariation` crash.

**Comment by TheGreenBandit** [comment]
i got it too by some guy when i tried to enter his vehicle lmao
RAX: 0xA2719263
RCX: 0xBFAB85F340
RDX: 0x1C5E7851601
RBX: 0xBFAB85F340
RSI: 0x0
RDI: 0x0
RSP: 0xBFAB85F190
RBP: 0xBFAB85F320
R8:  0x0
R9:  0x101
R10: 0x121
R11: 0x1C5E86D9CC0
R12: 0x0
R13: 0x0
R14: 0xBFAB85F380
R15: 0x0

stack dump [0]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0x1008232 0x7FF7F00F8232
stack dump [1]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0xFF5748 0x7FF7F00E5748
stack dump [2]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EC93 0x7FF7EFDFEC93
stack dump [3]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EBCC 0x7FF7EFDFEBCC
stack dump [4]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EB4A 0x7FF7EFDFEB4A
stack dump [5]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD050B9 0x7FF7EFDF50B9
stack dump [6]	 C:\Program Files\Epic Games\GTAV\GTA5.exe+0x11D31C 0x7FF7EF20D31C

**Comment by SkiddyToast** [comment]
> i got it too by some guy when i tried to enter his vehicle lmao RAX: 0xA2719263 RCX: 0xBFAB85F340 RDX: 0x1C5E7851601 RBX: 0xBFAB85F340 RSI: 0x0 RDI: 0x0 RSP: 0xBFAB85F190 RBP: 0xBFAB85F320 R8: 0x0 R9: 0x101 R10: 0x121 R11: 0x1C5E86D9CC0 R12: 0x0 R13: 0x0 R14: 0xBFAB85F380 R15: 0x0
> 
> stack dump [0] C:\Program Files\Epic Games\GTAV\GTA5.exe+0x1008232 0x7FF7F00F8232 stack dump [1] C:\Program Files\Epic Games\GTAV\GTA5.exe+0xFF5748 0x7FF7F00E5748 stack dump [2] C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EC93 0x7FF7EFDFEC93 stack dump [3] C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EBCC 0x7FF7EFDFEBCC stack dump [4] C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD0EB4A 0x7FF7EFDFEB4A stack dump [5] C:\Program Files\Epic Games\GTAV\GTA5.exe+0xD050B9 0x7FF7EFDF50B9 stack dump [6] C:\Program Files\Epic Games\GTAV\GTA5.exe+0x11D31C 0x7FF7EF20D31C

This is a different crash, please make another issue.

**Comment by TheGreenBandit** [comment]
> This is a different crash, please make another issue.

Ah nvm then
