### ISSUE TITLE
[Request]: Base Dir

### ISSUE THREAD

**Issue by Primexz** [Yimura/YimMenu#918]
### Problem

Currently Yim writes the configuration and much more under Appdata in the [BigBaseV2](https://github.com/YimMenu/YimMenu/blob/f1c00929566051f99e2f8256b974c784af9c9fb2/src/main.cpp#L46) directory.
Do we want to continue using this path or do we want to break away from BigBaseV2 and rename the path to YimMenu?

The disadvantage would be that each user would lose his current configuration and cache.

### Solution

Mayby switch from **BigBaseV2** path to **YimMenu**

### Reason

Just looks better

**Comment by ghost** [comment]
it's bigbasev2 so... no?

**Comment by Yimura** [comment]
Yeah I agree but I'm not sure how to handle this, maybe some sort of migration notice?

I didn't want to just willy nilly move the files inside the BigBaseV2 directory to a dedicated YimMenu directory in-case they have files there from other menus.

It's unlikely that this would cause problems but yeah.

**Comment by Primexz** [comment]
Do we want to start a vote on this topic before we do the "work" of doing it all automatically?
If the majority of users have no major problem with it, I think such breaking changes are quite possible.
Most users should also be able to copy over a file. (maybe at least a notifaction would be good that old Yim files were found)

**Comment by xiaoxiao921** [comment]
You could also have some code that detect if some specific YimMenu files are in appdata/bbv2 and if so copy them over the new YimMenu folder

**Comment by ghost** [comment]
We should add an on-inject notification that grabs from github for quick information just like this

**Comment by ghost** [comment]
It is officially time to delete this garbage software and design it from the ground up using no base 👍

**Comment by ghost** [comment]
> It is officially time to delete this garbage software and design it from the ground up using no base 👍 

Wow very constructive! Did you use your 3.2 brain cells to think that up?

**Comment by ghost** [comment]
> > It is officially time to delete this garbage software and design it from the ground up using no base 👍
> 
> Wow very constructive! Did you use your 3.2 brain cells to think that up?

You are not as funny as Yim.

**Comment by FireFox101889** [comment]
> > > It is officially time to delete this garbage software and design it from the ground up using no base 👍
> 
> > 
> 
> > Wow very constructive! Did you use your 3.2 brain cells to think that up?
> 
> 
> 
> You are not as funny as Yim.

Confirmed simp

**Comment by Yimura** [comment]
Modified in #1578
