### ISSUE TITLE
[Bug]: I am Sorry yim menu

### ISSUE THREAD

**Issue by Gh0sSte** [Yimura/YimMenu#922]
### Describe the bug

https://github.com/Gh0sSte/YimMenu this is prometheuses source code. It was leaked by a developer of it called jdm jay. I hope you can forgive me for my actions. I am very sorry. This menu is a paste ill admit that but i spent 4 months on it comitting working till 4am to atleast learn stuff and have some fun. I am sorry for all the arguments i have caused and all the mistakes i have made. This source has been leaked recently and i dont want people like greenbandit comitting it i feel like i should be the one to. this may sound like yea kinda big ego but im sorry i want to see this off by myself. This menu was like a child to me i guess. I want to see it off by releasing all of its code into yim menu. Sadly i couldnt commit it all in. I hope you change this issue to the correct thing i set bug report because i didnt know what else to put. I am very very sorry for everything. I have been using yim menu for a long time and i loved the menu. My only issue was my fleeting ambition and my pride. I am so sorry to yim and the other contributors i wish i could take back all my actions, I am so sorry. I hope you can forgive me. Please dont close this but if you do please add a pr merging stuff you can but its your choice. I just dont want someone like greenbandit to merge this stuff in. Im sorry. Atleast this way some of prometheuses code lives on in yim menu. What it was based on. I am sorry for not comitting anything large to yim menu. I am sorry for being so obnoxious and self centered. I am very sorry. I hope one day i can learn how to reverse and learn how to make my own menu properly without having to give people the code and have it leaked like this. I admit i am a skid. I am sorry for everything. I hope this menu can be used as a beginning poont for some other people. this menu i see myself in it abit. I see all my struggles i see all the effort i put in for these stupid skidded commands im sorry. I am losing it rn and im still somewhat in denial. This entire issue may seem inconsistant and broken but its because i myself am slowly breaking down discovering this was leaked. It is not a nice feeling at all. Im sorry again. Please forgive me im sorry. I hope one day i can be a proper contributer of yim menu. Im so sorry.

### Steps To Reproduce

1 i am sorrry

### Expected Behavior

i stopped skidding and contributed to yim menu

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

im sorry. Please move this to a different issue since bug report isnt exactly fitting like maybe move it to feature request? im very sorry i was not thinking straight. I am sorry to everyone i skidded off. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Gh0sSte** [comment]
credit dayib tupoya maybegreat yim bugisoft liamdflop and all the other yim contributors. Also maddy. If it wasnt for maddy i wouldnt even know how to loop a basic command

**Comment by Gh0sSte** [comment]
yea fair enough

**Comment by Gh0sSte** [comment]
can you change the tag my bad i was distraught and i selected bug. I feel like it should be a feature request kind of...

**Comment by Yimura** [comment]
Man why bring the drama here.

The only one who cares about the source are you (the developers) and skids.
The source is now public and as it contains a license file anyone is allowed to use it.

Idk what you’d expect me to do in this case? Watch better on who you add to the source repository I guess…

**Comment by Gh0sSte** [comment]
> Man why bring the drama here.
> 
> The only one who cares about the source are you (the developers) and skids. The source is now public and as it contains a license file anyone is allowed to use it.
> 
> Idk what you’d expect me to do in this case? Watch better on who you add to the source repository I guess.

i wanted to add some of it to yim i guess

**Comment by pelecanidae** [comment]
Don't be too hard on yourself. At the end of the day, we're all just cheating in a 10 year old video game.
