### ISSUE TITLE
Game has been updated!

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#927]
I have enabled interaction limits on the repo for now.

**Comment by TheGreenBandit** [comment]
The modifying others stats through an invalid array mod is patched, we can remove it if needed. Thats all i know about the update

**Comment by Primexz** [comment]
> The modifying others stats through an invalid array mod is patched, we can remove it if needed. Apparently messaging has also been modified so idk if our send message feature works. Thats all i know about the update

https://www.unknowncheats.me/forum/grand-theft-auto-v/569324-released-update.html

**Comment by TheGreenBandit** [comment]
Quote Adventure Box in the above forum "Seems like they went overboard with fixing crashes - bunch of classes shifted, matchmaking code changed (RID joining is broken) etc etc.

Crossmap and globals should still be the same though. This is very much an engine/security related update this time.

*Edit* - crossmap and script events changed, but globals are the same.
"

**Comment by Primexz** [comment]
Updated GTA Scripts (with new crossmap)

https://github.com/Primexz/GTAV-Decompiled-Scripts

**Comment by Seanghost117** [comment]
mechanic global changed from 2793044 -> 2793046, only noticeable global change that we may care about

**Comment by TheGreenBandit** [comment]
All of them went up by 2 i think
