### ISSUE TITLE
[Bug]: Crash with latest build

### ISSUE THREAD

**Issue by survivalizeed** [Yimura/YimMenu#931]
### Describe the bug

No matter in which scenario I inject the dll it show the menu for a short time and then the game crashes.

### Steps To Reproduce

Launch Game
Inject and wait 5 Seconds
Crash

### Expected Behavior

Should not have crashed

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Did you use the nightly build from 12 minutes ago?
Did you inject in single player or online?

Try removing the `%appdata%/BigBaseV2/` folder, it worked for me and others while testing.

**Comment by survivalizeed** [comment]
Yes I am using the latest build from around 12 minutes ago. I deleted the BigBaseV2 folder but it still crashes in multiplayer. Also tried with single player. 
Crash dump for single player:
RAX: 0x6BF53FFE20
RCX: 0x1E7C5FBC8BC
RDX: 0x6BF53FFDD0
RBX: 0x0
RSI: 0x7FF758980000
RDI: 0x0
RSP: 0x6BF53FFD90
RBP: 0x6BF53FFE39
R8:  0x1C
R9:  0x40
R10: 0x7FFC1ACE0000
R11: 0x400154000E005050
R12: 0x0
R13: 0x140C57140
R14: 0x3F3F3F
R15: 0x7FFC1ACE000

**Comment by Yimura** [comment]
That's not enough info, please also give the stack trace below those registers.

**Comment by survivalizeed** [comment]
I will try. The window closes very fast :D

**Comment by Yimura** [comment]
You can find the logs in `%appdata%/BigBaseV2/cout.log`, no need to try and grab it from the console.

**Comment by Hydra-Source** [comment]
> I will try. The window closes very fast :D

%appdata%->BigBaseV2(or YimMenu if they switched)->cout.log.

**Comment by survivalizeed** [comment]
Seems to work now Switched from Xenos to Extreme. I don't know what went wrong there thanks for your help

**Comment by Yimura** [comment]
Maybe some setting in Xenos was causing problems while injecting?
