### ISSUE TITLE
[Bug]: Translation cannot be loaded correctly

### ISSUE THREAD

**Issue by localhosts-A** [Yimura/YimMenu#934]
### Describe the bug

Both Chinese (CN) and Chinese (TW) cannot be loaded correctly, and there are individual characters that are displayed as "Chinese" incorrectly? Symbol

### Steps To Reproduce

1.Open the game, inject Yimmenu into the main menu, and switch translation

### Expected Behavior

All words should be correctly translated into Chinese without error display

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
YimMenu loads only a limited range of the Chinese charset and as such not all characters may be visible. 
what did you do to resolve this or why did you close the issue?

**Comment by localhosts-A** [comment]
> YimMenu loads only a limited range of the Chinese charset and as such not all characters may be visible. what did you do to resolve this or why did you close the issue?

I haven't solved this problem. I think the Chinese display error is a font problem

**Comment by Yimura** [comment]
> I haven't solved this problem. I think the Chinese display error is a font problem

YimMenu only loads simplified Chinese as loading the full font might cause the font texture to become too large and as such impossible to be loaded by the GPU correctly.

**Comment by oakboat** [comment]
#941 I sloved it now

**Comment by localhosts-A** [comment]
> #941 I sloved it now

Great, but I searched the Internet according to the author's words and found that the problem of insufficient display in Chinese does not seem to have much to do with fonts. It seems that the imgui limits the number of words loaded so that they cannot be displayed correctly.

**Comment by localhosts-A** [comment]
I read this article, but I have no ability to test or verify. https://www.jianshu.com/p/dd029e6d9dd4

**Comment by localhosts-A** [comment]
> I read this article, but I have no ability to test or verify. https://www.jianshu.com/p/dd029e6d9dd4

It gives the method of customizing the Chinese character set to display the wrong Chinese

**Comment by oakboat** [comment]
Yes i add simhei.ttf fonts with full chinese character supported.I specific it's loaded range.Like this, fonts_map.insert({ "simhei.ttf", io.Fonts->GetGlyphRangesChineseFull() });.
