### ISSUE TITLE
[Bug]: Config is not loading

### ISSUE THREAD

**Issue by magistrjan** [Yimura/YimMenu#947]
### Describe the bug

Tried to download the config (BigBaseV2) from version 1.64, but it simply does not change anything, the settings remain the same: protection, notifications, hotkeys

### Steps To Reproduce

1. Copied BigBaseV2 from one directory to %appdata%

### Expected Behavior

The config should have been loaded

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by LiamD-Flop** [comment]
Where did you download a config?

**Comment by Yimura** [comment]
Unable to reproduce.
