### ISSUE TITLE
[Request]: Name Spoofing

### ISSUE THREAD

**Issue by R3tr0ooo** [Yimura/YimMenu#948]
### Problem

I found name spoofing feature in an external menu and it worked

### Solution

If yimura have some spare time and think adding it back is reasonable

### Reason

:D

### Additional context

Will post it's link if allowed

**Comment by muhittinceko** [comment]
It would be great if she came back

**Comment by Aure7138** [comment]
> I found name spoofing feature in an external menu and it worked

iirc there is a static address to change the name to spoof, or that external menu just searches all the names and changes

**Comment by Adler-D3R** [comment]
It could also only be working locally.

**Comment by TheGreenBandit** [comment]
> It could also only be working locally.

thats probably it, thats what stand and many others who kept name spoofing did

**Comment by R3tr0ooo** [comment]
> It could also only be working locally.

it's 1:27AM in my country , i'll test it tomorrow

**Comment by Yimura** [comment]
@R3tr0ooo, I'm closing this, I'll reopen if you respond with more information or if you confirm this to be working with other people.
