### ISSUE TITLE
Steal Identity doesn't copy tattoos

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#95]
**Describe the bug**
When stealing someone's identity their tattoos don't end up being copied.

**To Reproduce**
1. Go to 'Player List'
2. Select Someone from Player List
3. Misc => Steal Identity
4. Observe the problem

**Expected behavior**
That a player its tattoos are copied over to the new ped.

**Screenshots**
None

**Logs**
None

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
None

**Comment by karifeld** [comment]
I suppose we could use some of the natives, namely

`PED::ADD_PED_DECORATION_FROM_HASHES`
and
`PED::GET_PED_DECORATION_ZONE_FROM_HASHES`

**Comment by xM4ddy** [comment]
> I suppose we could use some of the natives, namely
> 
> `PED::ADD_PED_DECORATION_FROM_HASHES` and `PED::GET_PED_DECORATION_ZONE_FROM_HASHES`

As far as I know its not possible with known natives.
