### ISSUE TITLE
[Bug]: Incorrect work Breakup Kick

### ISSUE THREAD

**Issue by Aboba7778** [Yimura/YimMenu#950]
### Describe the bug

Breakup Kick kicked random player, but not selected player.

### Steps To Reproduce

1) Select Player
2) Use Breakup Kick
3) Random player left session after click.

### Expected Behavior

Kick selected player

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Are you using the latest version of YimMenu?
This should be fixed in that version.

**Comment by JDMJay** [comment]
This is fixed in the latest version please goto https://github.com/YimMenu/YimMenu/releases/tag/nightly and download the latest version.

**Comment by muhittinceko** [comment]
> YimMenu'nun en son sürümünü mü kullanıyorsunuz? Bu, bu sürümde düzeltilmelidir.
Can animation feature be added?

**Comment by Yimura** [comment]
@Aboba7778, I'll be closing this issue for now as it should've been fixed.
