### ISSUE TITLE
[Request]: Remove receive_pickup hook

### ISSUE THREAD

**Issue by Vali0004** [Yimura/YimMenu#956]
### Problem

https://github.com/YimMenu/YimMenu/pull/933/commits/499192512743f9a6b39331f9f2cc7d20be451c39#diff-6ae96aa26432fa1a08bf5755c5879042232f2bd67aaf206e932ae0aecce56a9f
Why add a extra hook? There is literally a network event that handles pickups, so why not use it?

### Solution

CEventNetworkPlayerCollectedAmbientPickup - Event responsible
A concise solution I have in my menu to correct the pickup rather than blocking the entire net sync at a netObject level: https://cdn.upload.systems/uploads/lj0TZrb3.png
```
	class sEventPlayerCollectedAmbientPickup {
	public:
		char pad_0000[24]; //0x0000
		rage::joaat_t m_pickup_hash; //0x0018
		char pad_001C[4]; //0x001C
		int m_value; //0x0020
		char pad_0024[12]; //0x0024
		rage::joaat_t m_model; //0x0030
	}; //Size: 0x0034
	static_assert(sizeof(sEventPlayerCollectedAmbientPickup) == 0x34);
```

### Reason

This hook is not required

**Comment by SkiddyToast** [comment]
This is the correct struct for that event:
```c++
struct sEventPlayerCollectedAmbientPickup 
{
	alignas(8) joaat_t PickupType;
	alignas(8) int PickupAmount;
	alignas(8) Player PlayerIndex;
	alignas(8) joaat_t PickupModel;
	alignas(8) bool PlayerGift;
	alignas(8) bool DroppedByPed;
	alignas(8) int PickupCollected;
	alignas(8) Pickup PickupIndex;
};
```

**Comment by Adler-D3R** [comment]
Something like this should be working.
```
case RockstarEvent::GIVE_PICKUP_REWARDS_EVENT:
{
	uint32_t amount, hash;
	buffer->ReadDword(&amount, 3);
	buffer->ReadDword(&hash, 32);

	g_pointers->m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);

	if (hash == rage::joaat("HashToBlock"))
	{
		buffer->Seek(0);
		return;
	}
	buffer->Seek(0);
	break;
}
```

**Comment by Vali0004** [comment]
> Something like this should be working.
> 
> ```
> case RockstarEvent::GIVE_PICKUP_REWARDS_EVENT:
> {
> 	uint32_t amount, hash;
> 	buffer->ReadDword(&amount, 3);
> 	buffer->ReadDword(&hash, 32);
> 
> 	g_pointers->m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);
> 
> 	if (hash == rage::joaat("HashToBlock"))
> 	{
> 		buffer->Seek(0);
> 		return;
> 	}
> 	buffer->Seek(0);
> 	break;
> }
> ```

The goal was to allow pickup blocking, and correction. Correcting the amount wouldn’t be possible with a packed event

**Comment by Vali0004** [comment]
> This is the correct struct for that event:
> 
> ```c++
> struct sEventPlayerCollectedAmbientPickup 
> {
> 	alignas(8) joaat_t PickupType;
> 	alignas(8) int PickupAmount;
> 	alignas(8) Player PlayerIndex;
> 	alignas(8) joaat_t PickupModel;
> 	alignas(8) bool PlayerGift;
> 	alignas(8) bool DroppedByPed;
> 	alignas(8) int PickupCollected;
> 	alignas(8) Pickup PickupIndex;
> };
> ```

Wow mine is wildly wrong. It worked though
