### ISSUE TITLE
[Bug]: Disable Idle Kick does nothing

### ISSUE THREAD

**Issue by TheUnknownCod3r** [Yimura/YimMenu#958]
### Describe the bug

Upon loading into online, one of my default enabled options is Disable Idle Kick. Since 1.66, this option no longer works, and you get Idle kicked. 

### Steps To Reproduce

1. Load GTA Online with YimMenu injected.
2. Enable No Idle Kick in Self Options.
3. Go Idle and wait to be kicked.

### Expected Behavior

No Idle Kick to actually disable Idle Kick. 

### Screenshots and/or Logs

```
Not applicable since Its just Idle Kick
```

### Store

Steam

### Additional context

I have also tried it on both Epic Games Store and the Rockstar Launcher version, both return the same results.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by AuroraDoesCode** [comment]
Closing as I did not realise there was already an Open bug report regarding this, seems it didn't work correctly before either, and I was just lucky. Please see https://github.com/YimMenu/YimMenu/issues/726
