### ISSUE TITLE
Player Invisibility locally set player visible

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#96]
**Describe the bug**
Currently invisibility will remotely and locally make the ped invisible.

**To Reproduce**
Enable invisibility under **Self**.

**Expected behavior**
The local ped should still be visible or have some kind of alpha toggle on itself.

**Screenshots**
Add screenshots here,  you may remove this section if there are no screenshots applicable.

**Logs**
None

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
None

**Comment by xM4ddy** [comment]
First 
`ENTITY::SET_ENTITY_VISIBLE(ped, false, false);`
Then
`NETWORK::SET_ENTITY_LOCALLY_VISIBLE(ped);`

**Comment by Tayipc38** [comment]
`NETWORK::_NETWORK_SET_ENTITY_INVISIBLE_TO_NETWORK`

Why would you want your local player ped invisible?
