### ISSUE TITLE
[Bug]: Got Crashed

### ISSUE THREAD

**Issue by R3tr0ooo** [Yimura/YimMenu#964]
### Describe the bug

Got crashed by modder(probably has nothing to do with the blocked ones)

### Steps To Reproduce

Just got crashed

### Expected Behavior

Block crash

### Screenshots and/or Logs

[10:40:05][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:05][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Clear Ped Tasks from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 879177392
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Force Teleport from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1192608757
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1124104301
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Clear Ped Tasks from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 879177392
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Force Teleport from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1192608757
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1124104301
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Clear Ped Tasks from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 879177392
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Force Teleport from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1192608757
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1124104301
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Clear Ped Tasks from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 879177392
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Force Teleport from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1192608757
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][INFO/script_event_handler.cpp:388]: Hash = 1124104301
[10:40:06][INFO/script_event_handler.cpp:389]: Sender = 5
[10:40:06][WARNING/reaction.cpp:24]: Received TSE Sender Mismatch from Brunohan_18 (192193285)
[10:40:06][WARNING/reaction.cpp:24]: Received Crash from Brunohan_18 (192193285)
2023/02/09 10:52:14 066177

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 12152

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files\Bonjour\mdnsNSP.dll Base Address: 0x55490000 Size: 0x26000
C:\Program Files\Logitech Gaming Software\SDK\LED\x64\LogitechLed.dll Base Address: 0x7FF9D31E0000 Size: 0x2D000
C:\Program Files\MacType\Easyhk64.dll Base Address: 0x7FF98D160000 Size: 0x5A000
C:\Program Files\MacType\MacType64.Core.dll Base Address: 0x7FF98D050000 Size: 0x10B000
C:\Program Files\MacType\MacType64.dll Base Address: 0x7FF991850000 Size: 0x2D000
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x7FF97DA30000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x7FF963540000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x7FF976480000 Size: 0xB9B000
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2211.5-0\MpOav.dll Base Address: 0x7FF9E9E80000 Size: 0x7B000
C:\Users\gugugu\AppData\Roaming\Stand\Bin\Temp\SL_NB7ND.dll Base Address: 0x7FF972A50000 Size: 0x360000
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL Base Address: 0x7FF9DBD30000 Size: 0x1D3000
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL Base Address: 0x7FF9F3C00000 Size: 0xC000
C:\WINDOWS\SYSTEM32\CRYPTSP.dll Base Address: 0x7FF9F3CE0000 Size: 0x18000
C:\WINDOWS\SYSTEM32\CRYPTUI.dll Base Address: 0x7FF9D5D50000 Size: 0x5D000
C:\WINDOWS\SYSTEM32\CoreMessaging.dll Base Address: 0x7FF9EEEF0000 Size: 0x132000
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll Base Address: 0x7FF9E6B40000 Size: 0x36D000
C:\WINDOWS\SYSTEM32\D3D10_1.DLL Base Address: 0x7FF990D50000 Size: 0x37000
C:\WINDOWS\SYSTEM32\D3D11.DLL Base Address: 0x7FF9F1EF0000 Size: 0x280000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_43.dll Base Address: 0x7FF993230000 Size: 0x26F000
C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll Base Address: 0x7FF9EE480000 Size: 0x466000
C:\WINDOWS\SYSTEM32\DINPUT8.dll Base Address: 0x7FF9CE8C0000 Size: 0x45000
C:\WINDOWS\SYSTEM32\DNSAPI.dll Base Address: 0x7FF9F3060000 Size: 0xE8000
C:\WINDOWS\SYSTEM32\DSOUND.dll Base Address: 0x7FF9C3490000 Size: 0xA2000
C:\WINDOWS\SYSTEM32\DWrite.dll Base Address: 0x7FF9F17F0000 Size: 0x25F000
C:\WINDOWS\SYSTEM32\ESENT.dll Base Address: 0x7FF9DBF10000 Size: 0x3CB000
C:\WINDOWS\SYSTEM32\GLU32.dll Base Address: 0x7FF9930F0000 Size: 0x2D000
C:\WINDOWS\SYSTEM32\HID.DLL Base Address: 0x7FF9F2DE0000 Size: 0xE000
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL Base Address: 0x7FF9F3030000 Size: 0x2D000
C:\WINDOWS\SYSTEM32\MF.dll Base Address: 0x7FF9D5610000 Size: 0x8B000
C:\WINDOWS\SYSTEM32\MFCORE.DLL Base Address: 0x7FF9D7730000 Size: 0x3D6000
C:\WINDOWS\SYSTEM32\MFPlat.DLL Base Address: 0x7FF9F06D0000 Size: 0x1CE000
C:\WINDOWS\SYSTEM32\MFReadWrite.dll Base Address: 0x7FF9D3900000 Size: 0x120000
C:\WINDOWS\SYSTEM32\MSACM32.dll Base Address: 0x7FF9DA4B0000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\MSASN1.dll Base Address: 0x7FF9F3D30000 Size: 0x12000
C:\WINDOWS\SYSTEM32\MSVCP120.dll Base Address: 0x7FF9B3B20000 Size: 0xA6000
C:\WINDOWS\SYSTEM32\MSVCP140.dll Base Address: 0x7FF9DB970000 Size: 0x8D000
C:\WINDOWS\SYSTEM32\MSVCR120.dll Base Address: 0x7FF9B3A30000 Size: 0xEF000
C:\WINDOWS\SYSTEM32\NETAPI32.dll Base Address: 0x7FF9DBCB0000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\NTASN1.dll Base Address: 0x7FF9F3DB0000 Size: 0x37000
C:\WINDOWS\SYSTEM32\OPENGL32.dll Base Address: 0x7FF993120000 Size: 0x101000
C:\WINDOWS\SYSTEM32\PROPSYS.dll Base Address: 0x7FF9EF7A0000 Size: 0xF7000
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL Base Address: 0x7FF9EFF60000 Size: 0x32000
C:\WINDOWS\SYSTEM32\ResampleDmo.DLL Base Address: 0x7FF9B5B70000 Size: 0xB1000
C:\WINDOWS\SYSTEM32\SAMCLI.DLL Base Address: 0x7FF9EC990000 Size: 0x19000
C:\WINDOWS\SYSTEM32\SSPICLI.DLL Base Address: 0x7FF9F37C0000 Size: 0x42000
C:\WINDOWS\SYSTEM32\Secur32.dll Base Address: 0x7FF9E15D0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL Base Address: 0x7FF9C8380000 Size: 0x43E000
C:\WINDOWS\SYSTEM32\UMPDC.dll Base Address: 0x7FF9F37A0000 Size: 0x13000
C:\WINDOWS\SYSTEM32\USERENV.dll Base Address: 0x7FF9F3AB0000 Size: 0x29000
C:\WINDOWS\SYSTEM32\USP10.dll Base Address: 0x7FF9B39F0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll Base Address: 0x7FF9DF1A0000 Size: 0x1B000
C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll Base Address: 0x7FF9DEFA0000 Size: 0xC000
C:\WINDOWS\SYSTEM32\VERSION.dll Base Address: 0x7FF9EDB20000 Size: 0xA000
C:\WINDOWS\SYSTEM32\WINHTTP.dll Base Address: 0x7FF9EFA00000 Size: 0x10C000
C:\WINDOWS\SYSTEM32\WININET.dll Base Address: 0x7FF9D9390000 Size: 0x4FA000
C:\WINDOWS\SYSTEM32\WINMM.dll Base Address: 0x7FF9EF9C0000 Size: 0x33000
C:\WINDOWS\SYSTEM32\WINNSI.DLL Base Address: 0x7FF9EFD20000 Size: 0xC000
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV Base Address: 0x7FF9DDB00000 Size: 0x9B000
C:\WINDOWS\SYSTEM32\WINSTA.dll Base Address: 0x7FF9F3360000 Size: 0x63000
C:\WINDOWS\SYSTEM32\WKSCLI.DLL Base Address: 0x7FF9EE390000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\WTSAPI32.dll Base Address: 0x7FF9EFD30000 Size: 0x14000
C:\WINDOWS\SYSTEM32\XINPUT1_3.dll Base Address: 0x400000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\amsi.dll Base Address: 0x7FF9EA100000 Size: 0x25000
C:\WINDOWS\SYSTEM32\apphelp.dll Base Address: 0x7FF9EF5F0000 Size: 0x91000
C:\WINDOWS\SYSTEM32\avrt.dll Base Address: 0x7FF9F2280000 Size: 0xB000
C:\WINDOWS\SYSTEM32\bcrypt.dll Base Address: 0x7FF9F3E20000 Size: 0x27000
C:\WINDOWS\SYSTEM32\cfgmgr32.dll Base Address: 0x7FF9F4110000 Size: 0x4C000
C:\WINDOWS\SYSTEM32\credui.dll Base Address: 0x7FF9D8420000 Size: 0x1A000
C:\WINDOWS\SYSTEM32\cryptnet.dll Base Address: 0x7FF9EBBB0000 Size: 0x31000
C:\WINDOWS\SYSTEM32\d3d10_1core.dll Base Address: 0x7FF9DBB60000 Size: 0xE000
C:\WINDOWS\SYSTEM32\d3d9.dll Base Address: 0x7FF9E58C0000 Size: 0x1A6000
C:\WINDOWS\SYSTEM32\d3dx9_43.dll Base Address: 0x7FF976210000 Size: 0x263000
C:\WINDOWS\SYSTEM32\dbgcore.DLL Base Address: 0x7FF9E6780000 Size: 0x31000
C:\WINDOWS\SYSTEM32\dbghelp.dll Base Address: 0x7FF9F1CA0000 Size: 0x221000
C:\WINDOWS\SYSTEM32\dcomp.dll Base Address: 0x7FF9E6920000 Size: 0x21A000
C:\WINDOWS\SYSTEM32\devobj.dll Base Address: 0x7FF9F4160000 Size: 0x2C000
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL Base Address: 0x7FF9F08C0000 Size: 0x1E000
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL Base Address: 0x7FF9EF9A0000 Size: 0x19000
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll Base Address: 0x7FF9E8360000 Size: 0x44000
C:\WINDOWS\SYSTEM32\drvstore.dll Base Address: 0x7FF9EB6C0000 Size: 0x149000
C:\WINDOWS\SYSTEM32\dwmapi.dll Base Address: 0x7FF9F1110000 Size: 0x2F000
C:\WINDOWS\SYSTEM32\dxcore.dll Base Address: 0x7FF9F0FB0000 Size: 0x38000
C:\WINDOWS\SYSTEM32\dxgi.dll Base Address: 0x7FF9F2170000 Size: 0xF3000
C:\WINDOWS\SYSTEM32\dxva2.dll Base Address: 0x7FF9B5960000 Size: 0x25000
C:\WINDOWS\SYSTEM32\gpapi.dll Base Address: 0x7FF9F3A80000 Size: 0x24000
C:\WINDOWS\SYSTEM32\iertutil.dll Base Address: 0x7FF9ED250000 Size: 0x2B3000
C:\WINDOWS\SYSTEM32\inputhost.dll Base Address: 0x7FF9DD8C0000 Size: 0x1C9000
C:\WINDOWS\SYSTEM32\kernel.appcore.dll Base Address: 0x7FF9F3570000 Size: 0x18000
C:\WINDOWS\SYSTEM32\ksuser.dll Base Address: 0x7FF9E94A0000 Size: 0x9000
C:\WINDOWS\SYSTEM32\midimap.dll Base Address: 0x7FF9DBB30000 Size: 0xB000
C:\WINDOWS\SYSTEM32\msacm32.drv Base Address: 0x7FF9DA4D0000 Size: 0xD000
C:\WINDOWS\SYSTEM32\msdmo.dll Base Address: 0x7FF9D8A70000 Size: 0xB000
C:\WINDOWS\SYSTEM32\mskeyprotect.dll Base Address: 0x7FF9D7EE0000 Size: 0x15000
C:\WINDOWS\SYSTEM32\ncrypt.dll Base Address: 0x7FF9F3DF0000 Size: 0x28000
C:\WINDOWS\SYSTEM32\netutils.dll Base Address: 0x7FF9F3020000 Size: 0xC000
C:\WINDOWS\SYSTEM32\ntdll.dll Base Address: 0x7FF9F6F60000 Size: 0x209000
C:\WINDOWS\SYSTEM32\ntmarta.dll Base Address: 0x7FF9F0E80000 Size: 0x34000
C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll Base Address: 0x7FF9C80E0000 Size: 0x17000
C:\WINDOWS\SYSTEM32\powrprof.dll Base Address: 0x7FF9F3850000 Size: 0x4D000
C:\WINDOWS\SYSTEM32\profapi.dll Base Address: 0x7FF9F4370000 Size: 0x21000
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll Base Address: 0x7FF9F0E60000 Size: 0x15000
C:\WINDOWS\SYSTEM32\srvcli.dll Base Address: 0x7FF9ED510000 Size: 0x28000
C:\WINDOWS\SYSTEM32\textinputframework.dll Base Address: 0x7FF9DD790000 Size: 0x12D000
C:\WINDOWS\SYSTEM32\urlmon.dll Base Address: 0x7FF9ED5C0000 Size: 0x1EF000
C:\WINDOWS\SYSTEM32\wdmaud.drv Base Address: 0x7FF9DC710000 Size: 0x46000
C:\WINDOWS\SYSTEM32\wevtapi.dll Base Address: 0x7FF9EE8F0000 Size: 0x60000
C:\WINDOWS\SYSTEM32\windows.storage.dll Base Address: 0x7FF9F2570000 Size: 0x867000
C:\WINDOWS\SYSTEM32\winmmbase.dll Base Address: 0x7FF9E1430000 Size: 0x29000
C:\WINDOWS\SYSTEM32\wintypes.dll Base Address: 0x7FF9F2400000 Size: 0x166000
C:\WINDOWS\SYSTEM32\wldp.dll Base Address: 0x7FF9F3C90000 Size: 0x40000
C:\WINDOWS\SYSTEM32\xinput1_4.dll Base Address: 0x7FF98E5B0000 Size: 0x11000
C:\WINDOWS\System32\COMDLG32.dll Base Address: 0x7FF9F6C50000 Size: 0xEC000
C:\WINDOWS\System32\CRYPT32.dll Base Address: 0x7FF9F49F0000 Size: 0x162000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsig.inf_amd64_2929fc0ddbd6b167\nvldumdx.dll Base Address: 0x7FF9E53E0000 Size: 0xBE000
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsig.inf_amd64_2929fc0ddbd6b167\nvwgf2umx.dll Base Address: 0x7FF9E16A0000 Size: 0x368E000
C:\WINDOWS\System32\GDI32.dll Base Address: 0x7FF9F6640000 Size: 0x29000
C:\WINDOWS\System32\IMM32.dll Base Address: 0x7FF9F56D0000 Size: 0x31000
C:\WINDOWS\System32\KERNEL32.DLL Base Address: 0x7FF9F6340000 Size: 0xBD000
C:\WINDOWS\System32\KERNELBASE.dll Base Address: 0x7FF9F44B0000 Size: 0x379000
C:\WINDOWS\System32\MMDevApi.dll Base Address: 0x7FF9EA8E0000 Size: 0x9C000
C:\WINDOWS\System32\MSCTF.dll Base Address: 0x7FF9F4DF0000 Size: 0x11E000
C:\WINDOWS\System32\NSI.dll Base Address: 0x7FF9F5D70000 Size: 0x9000
C:\WINDOWS\System32\Normaliz.dll Base Address: 0x7FF9F5D80000 Size: 0x8000
C:\WINDOWS\System32\OLEAUT32.dll Base Address: 0x7FF9F5710000 Size: 0xD6000
C:\WINDOWS\System32\PSAPI.DLL Base Address: 0x7FF9F5D90000 Size: 0x8000
C:\WINDOWS\System32\RPCRT4.dll Base Address: 0x7FF9F6DA0000 Size: 0x120000
C:\WINDOWS\System32\SETUPAPI.dll Base Address: 0x7FF9F5860000 Size: 0x46C000
C:\WINDOWS\System32\SHELL32.dll Base Address: 0x7FF9F4F10000 Size: 0x7B8000
C:\WINDOWS\System32\SHLWAPI.dll Base Address: 0x7FF9F6D40000 Size: 0x5D000
C:\WINDOWS\System32\USER32.dll Base Address: 0x7FF9F6190000 Size: 0x1AC000
C:\WINDOWS\System32\WINTRUST.dll Base Address: 0x7FF9F4440000 Size: 0x67000
C:\WINDOWS\System32\WLDAP32.dll Base Address: 0x7FF9F6EC0000 Size: 0x60000
C:\WINDOWS\System32\WS2_32.dll Base Address: 0x7FF9F6BE0000 Size: 0x6F000
C:\WINDOWS\System32\advapi32.dll Base Address: 0x7FF9F64A0000 Size: 0xAE000
C:\WINDOWS\System32\bcryptPrimitives.dll Base Address: 0x7FF9F4D40000 Size: 0x7F000
C:\WINDOWS\System32\clbcatq.dll Base Address: 0x7FF9F5DA0000 Size: 0xAF000
C:\WINDOWS\System32\combase.dll Base Address: 0x7FF9F6850000 Size: 0x379000
C:\WINDOWS\System32\fwpuclnt.dll Base Address: 0x7FF9EDE90000 Size: 0x81000
C:\WINDOWS\System32\gdi32full.dll Base Address: 0x7FF9F4C20000 Size: 0x112000
C:\WINDOWS\System32\imagehlp.dll Base Address: 0x7FF9F6830000 Size: 0x1F000
C:\WINDOWS\System32\msvcp_win.dll Base Address: 0x7FF9F4830000 Size: 0x9D000
C:\WINDOWS\System32\msvcrt.dll Base Address: 0x7FF9F5FF0000 Size: 0xA3000
C:\WINDOWS\System32\ole32.dll Base Address: 0x7FF9F5E50000 Size: 0x19A000
C:\WINDOWS\System32\sechost.dll Base Address: 0x7FF9F6400000 Size: 0x9E000
C:\WINDOWS\System32\shcore.dll Base Address: 0x7FF9F6550000 Size: 0xEA000
C:\WINDOWS\System32\ucrtbase.dll Base Address: 0x7FF9F48D0000 Size: 0x111000
C:\WINDOWS\System32\win32u.dll Base Address: 0x7FF9F4DC0000 Size: 0x26000
C:\WINDOWS\System32\winrnr.dll Base Address: 0x7FF9DBB40000 Size: 0x12000
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22000.1_none_271a8fad6a2d1b1e\COMCTL32.dll Base Address: 0x7FF9DD360000 Size: 0xB2000
C:\WINDOWS\system32\Oleacc.dll Base Address: 0x7FF9DDA90000 Size: 0x69000
C:\WINDOWS\system32\XAudio2_7.dll Base Address: 0x7FF975B40000 Size: 0x8B000
C:\WINDOWS\system32\mswsock.dll Base Address: 0x7FF9F3A10000 Size: 0x67000
C:\WINDOWS\system32\napinsp.dll Base Address: 0x7FF9DBC70000 Size: 0x17000
C:\WINDOWS\system32\ncryptsslp.dll Base Address: 0x7FF9D8570000 Size: 0x27000
C:\WINDOWS\system32\nlansp_c.dll Base Address: 0x7FF9D8A90000 Size: 0x1F000
C:\WINDOWS\system32\nvapi64.dll Base Address: 0x7FF9E8D30000 Size: 0x770000
C:\WINDOWS\system32\pnrpnsp.dll Base Address: 0x7FF9DBBB0000 Size: 0x1B000
C:\WINDOWS\system32\rsaenh.dll Base Address: 0x7FF9F34D0000 Size: 0x35000
C:\WINDOWS\system32\schannel.DLL Base Address: 0x7FF9F33D0000 Size: 0xA9000
C:\WINDOWS\system32\uxtheme.dll Base Address: 0x7FF9F0240000 Size: 0xAC000
C:\WINDOWS\system32\wshbth.dll Base Address: 0x7FF9D8B40000 Size: 0x15000
C:\Windows\System32\FWPolicyIOMgr.dll Base Address: 0x7FF9EA170000 Size: 0x47000
C:\Windows\System32\FirewallAPI.dll Base Address: 0x7FF9F2F10000 Size: 0xA3000
C:\Windows\System32\Windows.UI.dll Base Address: 0x7FF9E83F0000 Size: 0x188000
C:\Windows\System32\fwbase.dll Base Address: 0x7FF9F2E90000 Size: 0x35000
C:\Windows\System32\rasadhlp.dll Base Address: 0x7FF9EC4D0000 Size: 0xA000
K:\GTAV\EOSSDK-Win64-Shipping.dll Base Address: 0x7FF96E000000 Size: 0xA18000
K:\GTAV\GFSDK_ShadowLib.win64.dll Base Address: 0x7FF96FA60000 Size: 0x3CC000
K:\GTAV\GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF9D3C10000 Size: 0x1C000
K:\GTAV\GTA5.exe Base Address: 0x7FF771320000 Size: 0x3C5D200
K:\GTAV\bink2w64.dll Base Address: 0x7FF9C3090000 Size: 0x8D000

Dumping registers:

RAX: 0x0
RCX: 0x2B0EE6755F0
RDX: 0x7FF773C5D500
RBX: 0x2B04B210610
RSI: 0x1
RDI: 0xFFFFFFFFFFFFFFFF
RSP: 0xE6223FF480
RBP: 0xE6223FF580
R8:  0x71
R9:  0x0
R10: 0x7FF9F49A3020
R11: 0xE6223FF6A0
R12: 0x1B0
R13: 0x2AF63AB4050
R14: 0x0
R15: 0x2B00F8E8DF0

stack dump [0]	 C:\Users\gugugu\AppData\Roaming\Stand\Bin\Temp\SL_NB7ND.dll+0x113BBC 0x7FF972B63BBC
stack dump [1]	 C:\Users\gugugu\AppData\Roaming\Stand\Bin\Temp\SL_NB7ND.dll+0x1139EC 0x7FF972B639EC
stack dump [2]	 C:\Users\gugugu\AppData\Roaming\Stand\Bin\Temp\SL_NB7ND.dll+0xC971F 0x7FF972B1971F
stack dump [3]	 C:\Users\gugugu\AppData\Roaming\Stand\Bin\Temp\SL_NB7ND.dll+0x9F5CF 0x7FF972AEF5CF
stack dump [4]	 K:\GTAV\GTA5.exe+0x1371152 0x7FF772691152
stack dump [5]	 K:\GTAV\GTA5.exe+0x7E6631 0x7FF771B06631
stack dump [6]	 K:\GTAV\GTA5.exe+0x16518E9 0x7FF7729718E9
stack dump [7]	 K:\GTAV\GTA5.exe+0x1651806 0x7FF772971806
stack dump [8]	 K:\GTAV\GTA5.exe+0x162C23D 0x7FF77294C23D
stack dump [9]	 K:\GTAV\GTA5.exe+0x162CBDA 0x7FF77294CBDA
stack dump [10]	 K:\GTAV\GTA5.exe+0x16358C2 0x7FF7729558C2
stack dump [11]	 K:\GTAV\GTA5.exe+0x12E93DA 0x7FF7726093DA
stack dump [12]	 C:\WINDOWS\System32\KERNEL32.DLL+0x154E0 BaseThreadInitThunk
stack dump [13]	 C:\WINDOWS\SYSTEM32\ntdll.dll+0x485B RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Aure7138** [comment]
The crash location occurs at SL_NB7ND.dll...
and please provide the version hash

**Comment by R3tr0ooo** [comment]
> The crash location occurs at SL_NB7ND.dll... and please provide the version hash

f12cc48

**Comment by JDMJay** [comment]
move to the latest version it has a functional exception handler [335e932](https://github.com/YimMenu/YimMenu/commit/335e9325b02fb6410b78e066775d952c0ea436aa)
