### ISSUE TITLE
[Request]: Can you add trigger bot or aimbot ?

### ISSUE THREAD

**Issue by BeztNA** [Yimura/YimMenu#965]
### Solution

pls add trigger bot or aimbot

### Reason

make menu perfect

**Comment by TheGreenBandit** [comment]
Its being added in #889

**Comment by BeztNA** [comment]
> Its being added in #889

how to add it to yim menu

**Comment by ghost** [comment]
Trigger bot is extremely easy. Do a raycast and if entity is of any type; shoot a bullet (there's a native)

**Comment by TheGreenBandit** [comment]
> Trigger bot is extremely easy. Do a raycast and if entity is of any type; shoot a bullet (there's a native)

Ill add it to my pr. Just so there is no need of another

**Comment by BeztNA** [comment]
> > Trigger bot is extremely easy. Do a raycast and if entity is of any type; shoot a bullet (there's a native)
> 
> Ill add it to my pr. Just so there is no need of another

can u add it to yim ?

**Comment by BeztNA** [comment]
> > can u add it to yim ?
> 
> Yes, my pr adds it to yim

thank you, hope to use it soon

**Comment by ghost** [comment]
> Trigger bot is extremely easy. Do a raycast and if entity is of any type; shoot a bullet (there's a native)

A big issue with triggerbot is it not working properly with moving entities. Such as shooting when they pass but not compensating for movement or bullet travel, etc. Have you polished out these issues?

**Comment by Seanghost117** [comment]
I will finish this in #975 , WIP Preview (if it embeds):

https://user-images.githubusercontent.com/36561158/218383933-f78b9ffb-4206-457f-bbda-19bc681b6370.mp4

**Comment by ghost** [comment]
> > Trigger bot is extremely easy. Do a raycast and if entity is of any type; shoot a bullet (there's a native)
> 
> 
> 
> A big issue with triggerbot is it not working properly with moving entities. Such as shooting when they pass but not compensating for movement or bullet travel, etc. Have you polished out these issues?

Raycast doesn't check far enough for bullet travel to be an issue. bullets are static in this game as far as I'm aware. If you shoot; no movement will change its trajectory
