### ISSUE TITLE
[Request]: Can I make a money loop that works with 1.66?

### ISSUE THREAD

**Issue by mitchie418** [Yimura/YimMenu#967]
### Solution

Can I make a money loop that works with 1.66?

### Reason

I am not as smart as you.

I'm sorry if I'm saying something strange.

**Comment by Seanghost117** [comment]
It is possible to add whatever money feature you may so choose with Yim menu. You would have to do some research regarding it and clone the repo and then develop it yourself and compile the binary though. Yim menu itself does not support any recovery features so not to garner negative attention and problems with T2 Interactive. There are also some forks that use Yim menu and may have recovery options built in if you look around. Probably no loops though.

**Comment by Seanghost117** [comment]
If you are talking about automating the Special CEO Cargo there is more to it than that, you are going to have to make use of script locals and have an understanding of setting and clearing bits for this. Globals will help you with the buy and sell cooldown as well as setting the price crate though. You can mess with the delays of course and finish the sale and buy again with locals. You may also want to look into drawing the warehouse or terrorbyte screen remotely, using technician source as the sourcing method and various helpers such as checking the property ID, setting the property ID, and getting the sell mission goal, among other things.

**Comment by LiamD-Flop** [comment]
No recovery in YimMenu
