### ISSUE TITLE
[Bug]: cant launch heist(or setup) with friends

### ISSUE THREAD

**Issue by Ferhat99** [Yimura/YimMenu#968]
### Describe the bug

let a friend join my heist setup to do it together.
if im not wrong it was the one you use the facility for (Act 2: The Bogdan Problem).
he gets stuck in an infinite loop when he accepts the invite. --> https://ibb.co/vXYg9zG

after some time loading, the joining cancels and gives this error on the screen of the player that was joining --> https://ibb.co/9w3PpV6

after this, you cant really play heists anymore (havnt tested with missions). you can invite random people to your heist, but you cant start it. once you press start, you load into the map with your team. the second you can move, you get an error that says: you have been kicked from the mission, not enough players (like someone left), but nobody has left. --> https://ibb.co/D5Jgm5c.

some methods that seems to fix it are;

- when the friend you invite gets in infinite joining screen, unloading the menu fixes it.
(dont know if it wil work while he is frozen, but joining the new invite again works.)
- when you get the error with "kicked from mission, not enough players", you need to restart GTA to fix that.
even after unloading the menu it keeps crashing your heists

when you inject mid heist nothing happens. but at the end after the "succes" screen we both got the black screen.
we were supposed to be put back in the lobby. (however the messages below(who left and joined) still showed up).

i havent had these problems with random players tho, so maybe that helps a bit

### Steps To Reproduce

.

### Expected Behavior

should not happen, the game should let you play together.

### Screenshots and/or Logs

[https://ibb.co/vXYg9zG]
[https://ibb.co/9w3PpV6]
[https://ibb.co/D5Jgm5c]

### Store

Steam

### Additional context

build 1.66

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Sk-ljy** [comment]
我认为这是一个严重的问题，我猜测是通过虚假ID加入会话时导致的失败。
当你创建一个差事会话时，你邀请的朋友是通过ID加入的。
另外我提一个建议，中文汉化并不完全，我查看过项目代码，有些翻译文本里面的词条并没有在代码项目中引用。

**Comment by Aure7138** [comment]
> 我认为这是一个严重的问题，我猜测是通过虚假ID加入会话时导致的失败。 当你创建一个差事会话时，你邀请的朋友是通过ID加入的。 另外我提一个建议，中文汉化并不完全，我查看过项目代码，有些翻译文本里面的词条并没有在代码项目中引用。

Just complaining won't help, and translation is out of scope of this issue

**Comment by Ferhat99** [comment]
i know its not a great explanation but excuse me, my english is not that great. its something with friends being in your heist. If there are specific questions, you can just ask. i'll try to help as much as i can. discussing it in a voice call is also possible.

**Comment by ghost** [comment]
It's probably the sync "protection".

Yim needs to make hooks only run any amount of code in them if the user has that feature enabled. Even when features are disabled even just having the menu injected will pass data through them.
