### ISSUE TITLE
[Bug]: teleport to wrong place while the waypoint is on water

### ISSUE THREAD

**Issue by yyk725** [Yimura/YimMenu#972]
### Describe the bug

character will be moved to the bottom of the sea when trying to teleport into water, and I have to use noclip to go back to the surface

it will always teleport to the surface in the past (before 1.66)

### Steps To Reproduce

put the waypoint on the sea and use "teleport to waypoint"

### Expected Behavior

i think teleport to the surface of the water is more convenient( •̀ ω •́ )✧

### Store

Epic Games

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by ghost** [comment]
It's doing what it's supposed to. It found ground but it doesn't know it's an ocean.

**Comment by Yimura** [comment]
Teleport to waypoint works as expected, closing.

**Comment by BUZZARDGTA** [comment]
Hello, I reopen this issue because I experience it every day, and always have to use no-clip to come up to the surface of the sea is quite annoying and can even destroy vehicles while teleporting.
So I'm going to make a simple suggestion for the developers to fix it:
The sea is flat in GTA, right? So you developers can put a new default unchecked checkbox named "Teleport over water" or something similar, and it will teleport on the surface of the water, to the checkpoint destination from the user.

**Comment by Yimura** [comment]
Why exactly are you so in need to teleport above water with a land vehicle? Just curious honestly.

**Comment by ghost** [comment]
The sea isn't flat, And yeah I'm curious too. Why?

**Comment by BUZZARDGTA** [comment]
teleport on sea I use it in Cayo to escape the Island. And about the vehicle it happened to me when I where doing a mission from the agency when you have to steal a car, one of those where located in the sea, the mission wants you to pick it up with a Cargobob. I teleported near the car I had to steal with my cargobob, and forgot that this would teleport me under water, and that failed my mission cuz the cargobob isn't meant to fly in the sea :D

**Comment by BUZZARDGTA** [comment]
@FireFox101889 Isn't the sea flat in GTA? I mean I know that there are waves but that's it, I always tough it was flat mhmm..

**Comment by ghost** [comment]
> @FireFox101889 Isn't the sea flat in GTA? I mean I know that there are waves but that's it, I always tough it was flat mhmm..

The sea bed isn't. But I'm not sure about water level.

**Comment by BUZZARDGTA** [comment]
yeah I where talking about the sea level, because the original thread issue is that we wanna teleport here and not in the bed. I know some people might want to get into the bed as well. That's why an checkable option to choose would be useful ;)

**Comment by Yimura** [comment]
I “sea” your point, I guess it would be a helpful option indeed.

I’ll see if there’s an easy method of grabbing the water level in a certain area and use that otherwise as a short term solution we can hardcode the sea level.

**Comment by xiaoxiao921** [comment]
simply using TEST_PROBE_AGAINST_WATER and modify the vector before tping should do the work
