### ISSUE TITLE
[Request]: Do you mind setting a advanced bodyguards in YimMenu

### ISSUE THREAD

**Issue by Pikapoolie** [Yimura/YimMenu#973]
### Solution

- Selecting some cars for your bodyguards.
- Making bodyguards drive car for you.
- If car is full, take another car what we decided or just one guy can be driver for a car and others can just sit on it. 
- Speed limit for convoy with bodyguards.
- Deciding number of bodyguards and creating squads for each.
- When you select a waypoint, some of squad cars can block front ways for opening your way to waypoint.
- Re-organising your squad like: Changing weapons, NPC models, Car which attached to a bodyguard etc.

### Reason

It creates a better aura while in jobs or just hanging in freemode.

**Comment by Seanghost117** [comment]
This sounds like quite a lot to implement, if someone makes this into a PR it may take a while, especially grouping bodyguards into squads and still managing them. Also, the logic behind the AIs deciding the vehicle to take, which bodyguard does road blocking, etc, especially if the waypoint has no road. For starters, it would be easy to add bodyguard management to the existing selection though.

**Comment by Tayipc38** [comment]
> * If car is full, take another car what we decided or just one guy can be driver for a car and others can just sit on it.

This one just seems overly complicated. A certain boundary between available seats and group size would be more manageable.

> * Speed limit for convoy with bodyguards.

If you mean more than a single car following you that might also prove difficult.

> * Deciding number of bodyguards and creating squads for each.
> * When you select a waypoint, some of squad cars can block front ways for opening your way to waypoint.

Don't really understand this one

> * Re-organising your squad like: Changing weapons, NPC models, Car which attached to a bodyguard etc.

**Comment by Yimura** [comment]
Won't implement.
