### ISSUE TITLE
ESP loading through startup screen

### ISSUE THREAD

**Issue by LiamD-Flop** [Yimura/YimMenu#98]
**Describe the bug**
When launching the game straight into GTA Online the esp draws through the images of the loading screen.

**To Reproduce**
1. Launch the game
2. Inject during loading
3. Goto online
4. Watch ESP draw through

**Expected behavior**
ESP can draw when loading in the clouds. But not through the images on the launch screen

**Screenshots**
![image](https://user-images.githubusercontent.com/40887493/157354730-82bcf8da-c334-404e-98e7-757c0db45dfe.png)

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Comment by Tayipc38** [comment]
Could we remove the loading pictures? Then is would be a feature rather than a bug.

**Comment by howdoiusekeyboard** [comment]
I think the ESP crashes my game when its on during a mission loading screen
Ok I tried same thing the 2nd time and I didn't crash so I think something else was the issue? I was in an invite only lobby with only friends (they don't mod)
Well anyways, here are the screenshots
![image](https://user-images.githubusercontent.com/90883505/157449464-3842b968-e18c-4fe6-b7f7-369684715cfd.png)
![image](https://user-images.githubusercontent.com/90883505/157449567-72c0b222-7ab0-49b0-b83c-bc1beed0a6eb.png)

**Comment by LiamD-Flop** [comment]
> I think the ESP crashes my game when its on during a mission loading screen Ok I tried same thing the 2nd time and I didn't crash so I think something else was the issue? I was in an invite only lobby with only friends (they don't mod) Well anyways, here are the screenshots

@howdoiusekeyboard 
Do you have the crash log by any chance?

**Comment by howdoiusekeyboard** [comment]
No, sorry, how do I get that?

**Comment by thews42** [comment]
> No, sorry, how do I get that?
@howdoiusekeyboard 
windows key + r and copy paste >>> %appdata%\BigBaseV2\Backup

**Comment by thews42** [comment]
> No, sorry, how do I get that?

@howdoiusekeyboard
windows key + r and copy paste >>> %appdata%\BigBaseV2\Backup

**Comment by howdoiusekeyboard** [comment]
Oh nice!

```
***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 12140

*******	STACKDUMP *******
stack dump [0]		D:\YimMenu\BigBaseV2\src\views\esp\view_esp.cpp L: 44 big::esp::draw
stack dump [1]		D:\YimMenu\BigBaseV2\src\hooking.cpp L: 182 big::hooks::swapchain_present
stack dump [2]	
stack dump [3]	
stack dump [4]	
stack dump [5]	
stack dump [6]	
stack dump [7]	
stack dump [8]	
stack dump [9]	
stack dump [10]	 BaseThreadInitThunk
stack dump [11]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```

This should be the crash log

**Comment by LiamD-Flop** [comment]
Thank you @thews42 

And thanks for the logs @howdoiusekeyboard I'll take a look at it.

**Comment by Yimura** [comment]
Can confirm got the same crash:

```
2022/03/10 00:01:55 995847

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 32332

*******	STACKDUMP *******
stack dump [0]		C:\Users\user\Coding\cpp\YimMenu\BigBaseV2\src\views\esp\view_esp.cpp L: 44 big::esp::draw
stack dump [1]		C:\Users\user\Coding\cpp\YimMenu\BigBaseV2\src\hooking.cpp L: 182 big::hooks::swapchain_present
stack dump [2]	
stack dump [3]	
stack dump [4]	
stack dump [5]	
stack dump [6]	
stack dump [7]	
stack dump [8]	
stack dump [9]	
stack dump [10]	 BaseThreadInitThunk
stack dump [11]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```
