### ISSUE TITLE
[Request]: Suggestions for anti-breakup kick feature improvements

### ISSUE THREAD

**Issue by Aigio1064** [Yimura/YimMenu#980]
### Problem

The existing anti-breakup kick function will still be kicked offline, but after I used the external program to initialize the memory function a few times, the game returned to normal, and I think this can be done into the anti-breakup kick function.

### Solution

It is when kicked by a breakup, being able to perform several operations to initialize the GTA5 memory module to restore the game to normal operation.

### Reason

It will still be kicked off the line by the breakup.

**Comment by Aigio1064** [comment]
Well... Bing translation, can be a little difficult to understand...

**Comment by maybegreat48** [comment]
> but after I used the external program to initialize the memory function a few times

Can you elaborate further?

**Comment by ghost** [comment]
> Well... Bing translation, can be a little difficult to understand...

Use deepl for future reference

**Comment by Yimura** [comment]
@Aigio1064, could you further elaborate on what you did?

**Comment by Aigio1064** [comment]
> @Aigio1064, could you further elaborate on what you did?

After I was kicked by other exotics using breakups, I initialized the game's memory module a few times using the GTAOnlineTools tool made by CrazyZhang666, I'm not sure if it's called that, but that's what it says in the tool, and when I repeated it a few times, the game returned to normal except for dropping out of the original battle. I'm pretty sure I just repeated the initialize memory module operation a few times, and the most obvious feature was that the frame rate returned to normal.

Translated with www.DeepL.com/Translator (free version)
原文：
> 在我被其他外挂使用分手踢之后，我使用CrazyZhang666制作的GTAOnlineTools工具初始化了几遍游戏的内存模块，我不确定是不是叫这个，但是工具里是这样写的，当我重复执行了几次之后，除了掉出了原来的战局，游戏恢复了正常。我很确定我只是重复执行了几遍初始化内存模块操作，最明显的特征就是帧率恢复正常。

我叫它分手踢的原因是breakup kick翻译过来是叫分手踢，虽然我知道它的翻译不正确....
