### ISSUE TITLE
[Bug]: 线上使用YimMenu掉帧严重

### ISSUE THREAD

**Issue by 55U55** [Yimura/YimMenu#986]
### Describe the bug

线上注入YimMenu后掉帧非常卡顿，然后游戏就卡退出去了咋回事？

### Steps To Reproduce

1.通过steam进入故事模式。
2.然后打开GTA5线上小助手。
3.注入YimMenu,等待一会就会掉帧卡顿，然后游戏就卡退出去了。

### Expected Behavior

这会让我们这些人没办法使用这个功能了

### Store

Other (please mention in "Additional context")

### Additional context

steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
English?

**Comment by 55U55** [comment]
Chinese






                       
原始邮件
                       
                     

发件人："Yimura"< ***@***.*** &gt;;

发件时间：2023/2/14 7:15

收件人："YimMenu/YimMenu"< ***@***.*** &gt;;

抄送人："55U55"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986)




 
English?

**Comment by 55U55** [comment]
Because I can't speak English.







                       
原始邮件
                       
                     

发件人："Yimura"< ***@***.*** &gt;;

发件时间：2023/2/14 7:15

收件人："YimMenu/YimMenu"< ***@***.*** &gt;;

抄送人："55U55"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986)




 
English?

**Comment by Alice2333g** [comment]
> Because I can't speak English. 原始邮件 发件人："Yimura"< ***@***.*** &gt;; 发件时间：2023/2/14 7:15 收件人："YimMenu/YimMenu"< ***@***.*** &gt;; 抄送人："55U55"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; 主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986) English? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Would you like to see what you are talking about?

**Comment by 55U55** [comment]
Please fix this problem as soon as possible. There are many players like me who are troubled by this problem in China.


                       
原始邮件
                       
                     

发件人："Yimura"< ***@***.*** &gt;;

发件时间：2023/2/14 7:15

收件人："YimMenu/YimMenu"< ***@***.*** &gt;;

抄送人："55U55"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986)




 
English?

**Comment by 55U55** [comment]
？啥？








                       
原始邮件
                       
                     

发件人："Alice"< ***@***.*** &gt;;

发件时间：2023/2/14 7:21

收件人："YimMenu/YimMenu"< ***@***.*** &gt;;

抄送人："55U55"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986)




  
Because I can't speak English. 原始邮件 发件人："Yimura"< @.*** &gt;; 发件时间：2023/2/14 7:15 收件人："YimMenu/YimMenu"< @.*** &gt;; 抄送人："55U55"< @.*** &gt;;"Author"< @.*** &gt;; 主题：Re: [YimMenu/YimMenu] [Bug]: 线上使用YimMenu掉帧严重 (Issue #986) English? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Would you like to see what you are talking about?

**Comment by 55U55** [comment]
Chinese

**Comment by 55U55** [comment]
Because I can't speak English.

**Comment by 55U55** [comment]
Please fix this problem as soon as possible. There are many players like me who are troubled by this problem in China.

**Comment by Alice2333g** [comment]
> 请尽快解决此问题。在中国，有很多像我一样的玩家被这个问题所困扰。

yim不欠你的。但是和小助手扯上关系我不是很理解2333
这完全两个不同的东西。不要混淆概念丢中国人的脸

**Comment by 55U55** [comment]
你妈

**Comment by Alice2333g** [comment]
> 你妈

哈哈哈急了

**Comment by 55U55** [comment]
> > 请尽快解决此问题。在中国,有很多像我一样的玩家被这个问题所困扰。
> 
> yim不欠你的。但是和小助手扯上关系我不是很理解2333这完全两个不同的东西。不要混淆概念丢中国人的脸

你妈

**Comment by Alice2333g** [comment]
> > > 请尽快解决此问题。在中国,有很多像我一样的玩家被这个问题所困扰。
> > 
> > 
> > yim不欠你的。但是和小助手扯上关系我不是很理解2333这完全两个不同的东西。不要混淆概念丢中国人的脸
> 
> 你妈

我知道你急但是你先别急，小助手频道都在看你笑话

**Comment by 55U55** [comment]
急你妈的个比的
