### ISSUE TITLE
[Bug]: cannot go into vehicle assets

### ISSUE THREAD

**Issue by yyk725** [Yimura/YimMenu#987]
### Describe the bug

cannot go into vehicle assets like kosatka, terrorbyte, MOC... ; friends nearby will also failed to use theirs
the game will give a message like "You cannot enter your ___(vehicle name) here. Please move it to another area"

*the bug will not appear if yimmenu wasn't injected
**i translate the bug from chinese into english, so some words may be wrong

### Steps To Reproduce

1. inject yimmenu and start online mode
2. call for a vehicle asset like terrorbyte, go into it and then exit
3. happens when trying to go in for a second time

### Expected Behavior

go inside

### Screenshots and/or Logs

![Grand Theft Auto V 2023_2_14 19_23_32](https://user-images.githubusercontent.com/72236930/218724342-13895f5c-5551-4042-a20f-0507090a60b2.png)
sry i cant translate this by myself so i use machine translate to get the message in English: 

`You cannot access the nerve center in this area. Please move the terror to the appropriate area.`

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Are you using YimMenu downloaded from this repository or somewhere else?

**Comment by yyk725** [comment]
> Are you using YimMenu downloaded from this repository or somewhere else?

I'm using the official version downloaded from releases

**Comment by maybegreat48** [comment]
Cannot reproduce with a MOC. Have you tried entering them in a solo session?

**Comment by yyk725** [comment]
In solo session I can enter them, but the game just can't register for CEO/VIP/leader in solo session so I can't do my missions

And bug will happen when I try to enter them in invite only/public session so I cant do friend's missions either

According to my friend, when i enter the vehicle luckily and invite them using "m"menu, they will also failed to get in(blackscreen for a while and then return to last place, giving no response)

**Comment by Yimura** [comment]
Is this still an issue? I haven't gotten around to testing this.
