### ISSUE TITLE
[Request]: Chinese translation

### ISSUE THREAD

**Issue by Hzxc123** [Yimura/YimMenu#988]
### Problem

能不能将那个yimmenu完全汉化

### Solution

希望能完全汉化

### Reason

因为有些真的看不懂啥英文

**Comment by Seanghost117** [comment]
Chinese translations are already made here: https://github.com/YimMenu/Translations, not everything is translated or set to translate, updates to Chinese translations and full translations will happen over time

**Comment by Yimura** [comment]
Non-English issue, closing.
