### ISSUE TITLE
[Request]: player db enhancements 

### ISSUE THREAD

**Issue by binded-zz** [Yimura/YimMenu#990]
### Problem

i asked some thing like this a while back but maybe now it sounds more useful 

there has been some work on the player DB and some upcoming updates to it that i seen on here 
any way to add a lock user flag so that you can keep some users on the list and use the remove all function to clear out the list but not remove the locked users

the player list gets long i have it adding on alot of the protections 
be great if there was a date and maybe or time aswell as maybe "NOTE"

### Solution

a check mark for the user on the player db so when you remove all it only removes unlocked players
maybe a date and time  with the reasons 

maybe groups 
 blocks, friends, chat commands, ungrouped, offline, "ONLINE" 
i guess it could be alot of ways things atleast  some sorta group or lock on user

### Reason

just makes the player db easier to use 
groups  
able to remove mass users with out affecting users that i want to keep blocked or friend or able to use commands 
this i think would make sense seeing that i read that there adding online status to the player DB

i am sure this is not just that easy todo 

### Additional context

i guess thats the best that i can explain

**Comment by Seanghost117** [comment]
This is possible, the list can be sorted as well as filtered quite easily based on preset data, I might also be able to add in a custom list that makes it possible to add users to said list. Making a checkbox within the list might be hard as it would require some hacking of the selectable if that route is chosen, it would be easier for me to add multi select and allow users to either delete selected (on multi select), delete unselected, and delete by type (here you can apply filters (ie. Delete all classified as modder or not, or not friends, etc). 

I can start working on this after my current PR but you might have to give me sometimes I also don't want to have conflicts with @Primexz 's commit. And also yes if I understand what you are asking it is possible to add in first seen and last met with general ease.

**Comment by binded-zz** [comment]
yes you get the idea
i know there are limits to what you can do. some that you dont control 

thanks in advance for any work you or others do

**Comment by Kaki7964** [comment]
Also whitelist friends from protections, so in case a mission breaks you can just whitelist everyone.

**Comment by Yimura** [comment]
Trusted players can be maintained in the PlayerDB with current versions of YimMenu.
