### ISSUE TITLE
[Request]: Add the Recovery section to the menu and AimBot as in Lightning

### ISSUE THREAD

**Issue by DrakesBot12** [Yimura/YimMenu#995]
### Problem

Add the Recovery section to the menu

### Solution

Add the Recovery section to the menu

### Reason

Add the Recovery section to the menu

### Additional context

Add the Recovery section to the menu

**Comment by Yimura** [comment]
Recovery features will not be added to YimMenu.

**Comment by SkiddyToast** [comment]
For more clarification, please look at #237.
